### ISSUE TITLE
router: recover missed route deletions after sync failure

### ISSUE THREAD

**Issue by benburkert** [flynn/flynn#1002]
`DataStore` uses a `LISTEN` connection to watch for route changes. This connection will occasionally fail, and to recover the `DataStore` must restart the `LISTEN` connection then do a full-sync of all routes to pickup routes added while the `LISTEN` connection dropped.

This recovery strategy currently has a flaw which causes routes to never be removed if the remove is issued during a window when the `LISTEN` connection has failed and the `DataStore` has not detected the failure.

In order to solve this, the Sync API, which is currently asynchronous (`StartSync`/`StopSync`), needs to be synchronous (`Sync`), so that the caller (`HTTPListener`/`TCPListener`) can be notified of errors. This allows the caller to rebuild it's routing state from scratch when `Sync` fails. Furthermore, the caller should be capable of rebuilding the routing state without having to lock routing.

**Comment by benburkert** [comment]
Shelving my work this for now, for reference the commits are here: https://github.com/benburkert/flynn/tree/router-route-table

**Comment by bgentry** [comment]
FYI this issue applies to any updates that happen while the sync is disconnected, not just deletions. I'll leave my version of the test here for reference and hopefully we can come back to fix this for real https://github.com/bgentry/flynn/commit/634de1b522b6d0f8efc16966c21d8a3869ddd115
