### ISSUE TITLE
Need more port accessing from  the back of firewall.

### ISSUE THREAD

**Issue by monaka** [flynn/flynn#1016]
I got /etc/flynn/host.json after executing ```sudo flynn-host init```

```
{
        "env": {
                "ETCD_INITIAL_CLUSTER": "04e9d29fcf1ec17eb35b1a82daf453db=http://100.72.162.59:2380",
                "ETCD_INITIAL_CLUSTER_STATE": "new",
                "ETCD_NAME": "04e9d29fcf1ec17eb35b1a82daf453db"
        }
}
```

So I think I must open TCP port 2380 when I use clustered Flynn.
But there is no description about the port 2380 on README.md.
Which is wrong, flynn-host or the document? (or my misunderstanding?)

**Comment by titanous** [comment]
From the installation docs:

> The nodes also need to be able to communicate with each other internally on all ports.

I don't think the docs are incorrect.
