### ISSUE TITLE
router: unnecessary mutex lock in tcpRoute.Serve()?

### ISSUE THREAD

**Issue by bgentry** [flynn/flynn#1034]
I stumbled across the following mutex calls in the TCP router: https://github.com/flynn/flynn/blob/6369dd5675b215201d1f923b118642a1f729270c/router/tcp.go#L249-L251

```go
r.mtx.RLock()
go r.service.ServeConn(conn)
r.mtx.RUnlock()
```

I didn't dig any further as I didn't want to get sidetracked from what I'm working on, but it has to be either a race or completely unnecessary. /cc @benburkert @titanous

**Comment by titanous** [comment]
I think this was originally to prevent races when changing the service: https://github.com/flynn/flynn/blob/6369dd5675b215201d1f923b118642a1f729270c/router/tcp.go#L180

We need a test, and should probably switch to `atomic.Value`.
