### ISSUE TITLE
IPv6 only flynn-host

### ISSUE THREAD

**Issue by floatdrop** [flynn/flynn#1037]
Hi. I'm trying to setup basic flynn setup by [installation docs](https://flynn.io/docs/installation). But after `flynn-host init --discovery https://discovery.etcd.io/xxx` command this error pops up:

`host.go:119: config: Unable to determine default IPv4 address`

Is IPv6 only hosts are not supported yet?

**Comment by titanous** [comment]
No, currently container networking is IPv4 only. There is no good reason other than we haven't had the time to update flannel and the networking code to handle IPv6. I'll leave this open as a feature request.

**Comment by floatdrop** [comment]
@titanous sorry to bother, but any news/eta on this?

**Comment by titanous** [comment]
No news, it is a currently unscheduled feature.

**Comment by thomas-lange-smf** [comment]
Any news here?
We currently have a pending iOS app, that would require IPv6 support

**Comment by philiplb** [comment]
Wheras Apple has a new policy that new apps and updates have to support IPv6. So that forces us to use infrastructure supporting it and rules out Flynn as long as it doesn't support IPv6 externally. I guess at least the router had to support it?

**Comment by lmars** [comment]
Whilst Flynn doesn't use IPv6 directly, we have had reports of users successfully deploying Flynn in IPv6 only environments (see [here](https://botbot.me/freenode/flynn/2017-02-21/?msg=81344177&page=2)).

**Comment by philiplb** [comment]
Ok, cool. So Flynn itself is fine with ipv6 as long as the host machines support it? If the VMs are reachable via IPv6 and a proper AAA record is set, would the router respond to IPv6 requests?

**Comment by lmars** [comment]
@philiplb the router will be fine with IPv6 (it operates at the TCP / UDP layer which would work the same way) but the flynn-host daemon currently expects to create an IPv4 network for the overlay network (hence the error in the original comment here) so that would need to be updated for Flynn to properly support IPv6 only.

I believe the user in IRC deployed Flynn inside a KVM machine with an IPv4 stack, and ran that in an IPv6 only environment, proxying TCP connections using nginx.

**Comment by simonamor** [comment]
To clarify, the kvm machine I built for flynn had a public IPv6 address but still had an internal IPv4 address in the 192.168.x.x range for management purposes. The only DNS records were AAAA records pointing to the public IPv6. The flynn dashboard and test apps provisioned to the host worked fine over IPv6.

**Comment by johnnagro** [comment]
@thomas-lange-smf we run cloduflare infront of our flynn setup, and that gives us ipv6 support. just set a high file descriptor setting for your router (open issue with CF)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
