### ISSUE TITLE
Allow changing clusters without breaking clients

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1039]
In order to swap out a cluster without the dashboard CA cert changing or the CLI TLS pin changing, we should allow all of the following to be extracted and reused for bootstrap:

- CA certificate (the private key is discarded and unecessary)
- Cluster domain wildcard cert and keypair (used by controller, dashboard, router)

Bootstrap should be modified to allow specifying any/all of these parameters instead of generating them, and we should have documentation on how to extract them.

**Comment by temujin9** [comment]
+1, this works as expected and helps simplify our credential migration process. Thanks!
