### ISSUE TITLE
ruby buildpack 503 and connectivity errors

### ISSUE THREAD

**Issue by heavenlyhash** [flynn/flynn#1045]
GitDeploySuite.TestRubyBuildpack fails while attempting to communicate with the service via the router.

Log: https://s3.amazonaws.com/flynn-ci-logs/20150221185047-e3454316-build-1441f2e7cc255e2ff4a3e35248e9a4bcc69968b0-2015-02-21-18-59-36.txt

The router app contains many lines like:
```
2015/02/21 18:53:51 router: proxy error: router: no backends available
```

Meanwhile, flynn/receiver job (host id 9d17bed5 in this log) also contains copious amounts of:

```
2015/02/21 18:52:10 Failed to handshake: EOF
2015/02/21 18:52:12 Failed to handshake: read tcp 100.100.92.4:34060: connection reset by peer
```

... which may point to some other networking issues behind this.

**Comment by titanous** [comment]
Closing, as this appears to have been fixed by #1254.
