### ISSUE TITLE
Implement OCSP stapling

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1049]
The router should provide [OCSP stapling](https://en.wikipedia.org/wiki/OCSP_stapling) in handshakes for certificates that support it.

**Comment by Vorror** [comment]
Is this still a feature flynn plans to add? #3184 was closed.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
