### ISSUE TITLE
CI "unexpected end of file" in slugrunner based job

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1057]
`ControllerSuite.TestExampleOutput` failed with:

```
    t.Assert(errs, c.HasLen, 0, c.Commentf("%s validation errors: %v\ndata: %v\n", cacheKey, errs, string(jsonData)))
... obtained []jsonschema.ValidationError = []jsonschema.ValidationError{jsonschema.ValidationError{Keypath:[]string{"response", "body"}, Description:"Additional properties aren't allowed, found \"message\" as one of its keys"}}
... n int = 0
... https://flynn.io/schema/examples/controller/job_update validation errors: [{[response body] Additional properties aren't allowed, found "message" as one of its keys}]
data: {
	"request": {
		"body": {
			"app": "6030514e9e394e699624c8e61caf0a15",
			"id": "192081b6-45c4437d8631433dbe327b9afd4479db",
			"release": "e53440ec01c948a58e637525b4830617",
			"state": "down"
		},
		"headers": {
			"Authorization": "Basic OjZhMDM3ZmU2NTFiNGY5MWE=",
			"Content-Type": "application/json"
		},
		"method": "PUT",
		"url": "/apps/6030514e9e394e699624c8e61caf0a15/jobs/192081b6-45c4437d8631433dbe327b9afd4479db"
	},
	"response": {
		"body": {
			"code": "validation_error",
			"detail": {
				"field": "state"
			},
			"message": "state pq: invalid job state transition: crashed -\u003e down"
		},
		"headers": {
			"Content-Type": "application/json"
		}
	}
}
```

The problem here is that the controller example tries to set the job state to `down`, but the job was in the `crashed` state (leading to an invalid state transition) due to the following error in it's log:

```
HostID: 3d89767a - flynn-host log --init 192081b6-45c4437d8631433dbe327b9afd4479db
...
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

https://s3.amazonaws.com/flynn-ci-logs/20150223001629-720e9a9c-build-121f09d518886c9ba7e635c082c240c9a0ae1ee4-2015-02-23-00-25-49.txt

**Comment by lmars** [comment]
@jvatic even though there was an underlying issue, I think the response from the controller was in fact valid, does the schema check need updating?

**Comment by jvatic** [comment]
@lmars it's testing the response body against [website/schema/controller/job.json](https://github.com/flynn/flynn/blob/master/website/schema/controller/job.json). The test is not currently aware of error responses which can make the output of such failures confusing.

**Comment by jvatic** [comment]
https://s3.amazonaws.com/flynn-ci-logs/20150226202401-fbd7841e-build-38707ef28bdf489d97e3fea69e2a0d501906133a-2015-02-26-20-34-20.txt

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150228053200-3a10d6dc

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150310193522-64b520dc

**Comment by titanous** [comment]
This hasn't happened recently.
