### ISSUE TITLE
Improve output of controller JSON schema integration test

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1058]
Currently if a response body contains an error response, the error output from the test will be complaining it does not match the appropriate resource schema. The test should be made aware of error responses and complain about getting an error instead of the individual fields not complying to the resource schema.

refs #1057

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
