### ISSUE TITLE
DeployerSuite.TestServiceEvents wrong job state

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1060]
```text
FAIL: test_deployer.go:155: DeployerSuite.TestServiceEvents

++ 18:09:26.051 created app rabbits-threaten-bromley (b1c680cd9c8442309513855058524ad1)
++ 18:09:26.140 waiting for job events: map[echoer:map[up:2]]
++ 18:09:26.219 got job event: echoer 03658763-75790ae6b92d4ff280eb6e345336dc5c starting
++ 18:09:26.249 got job event: echoer 8c7945fe-15e77202b2cf42328b5a8faeaaf9e2cd starting
++ 18:09:27.079 got job event: echoer 03658763-75790ae6b92d4ff280eb6e345336dc5c up
++ 18:09:27.289 got job event: echoer 8c7945fe-15e77202b2cf42328b5a8faeaaf9e2cd up
++ 18:09:27.289 waiting for 2 echo-service services
++ 18:09:27.290 got echo-service service up event
++ 18:09:27.372 got echo-service service up event
++ 18:09:27.401 waiting for 9 deployment events
++ 18:09:27.431 got deployment event: echoer starting
++ 18:09:27.431 got deployment event: echoer starting
++ 18:09:28.781 got deployment event: echoer up
++ 18:09:28.791 got deployment event: echoer up
++ 18:09:28.791 got deployment event: echoer stopping
++ 18:09:28.991 got deployment event: echoer down
++ 18:09:29.001 got deployment event: complete
test_deployer.go:175:
    waitForDeploymentEvents(t, events, expected)
test_deployer.go:100:
    t.Assert(i.JobState, c.Equals, j.JobState)
... obtained string = "down"
... expected string = "stopping"
```

https://s3.amazonaws.com/flynn-ci-logs/20150223180406-61cf1448-build-72de0e99a9b6e79bb1cc08730edbc3092536f19b-2015-02-23-18-13-22.txt

**Comment by jvatic** [comment]
Here's another such failure: https://ci.flynn.io/builds/20150224160916-708c8157

**Comment by titanous** [comment]
This is still occurring: https://ci.flynn.io/builds/20150723223417-78986b59

I *think* it's due to a race, just because the test gets a notification that a service is up from discoverd  doesn't mean that the deployer has the same view on the service (it could be talking to a different etcd/discoverd instance).

A bit of analysis here: https://botbot.me/freenode/flynn/2015-06-16/?msg=42050032&page=2

**Comment by lmars** [comment]
@titanous two possible solutions:

* sleep for ~heartbeatInterval in the test before starting the deployment
* have the deployer wait a further X seconds after receiving the current event if the release was created in the last Y seconds (so expecting the release to still be starting up)
