### ISSUE TITLE
[install-flynn] Missing package on Linode

### ISSUE THREAD

**Issue by meskyanichi** [flynn/flynn#1076]
I had some credits left on Linode so I figured I'd use it to give Flynn a try.

The install script, when running on Linode, yields the following error:

```
===> 18:52:20.596 ERROR: failed to run "apt-get install --yes aufs-tools iptables libvirt-bin ubuntu-zfs linux-image-extra-3.18.5-x86_64-linode52", exit status 100
```

The offending package being:

```
linux-image-extra-3.18.5-x86_64-linode52
```

With error:

```
E: Unable to locate package linux-image-extra-3.18.5-x86_64-linode52
E: Couldn't find any package by regex 'linux-image-extra-3.18.5-x86_64-linode52'
```

I've also tried other variants:

```
apt-get install linux-image-extra-3.18.5-x86_64
```

and:

```
apt-get install linux-image-extra-3.18.5
```

and:

```
apt-get install linux-image-extra
```

But yields the same error.

Deploying to Digital Ocean now using the same script without issues.

**Comment by lmars** [comment]
@meskyanichi thanks for reporting this, I will boot a Linode slice and see what changes need to be made.

**Comment by meskyanichi** [comment]
:+1:

**Comment by lmars** [comment]
@meskyanichi it seems Linode kernels do not support AUFS, so a switch to an Ubuntu kernel is necessary, see #1080.

**Comment by meskyanichi** [comment]
Thanks @lmars !
