### ISSUE TITLE
Improve deploying Docker images

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1085]
The current workflow for deploying a Docker image involves writing a JSON file representing a release, constructing a valid registry URI and calling `flynn release add`. This workflow is cumbersome, error prone and in no way easy to use.

One approach is to not involve a registry and support pushing images directly to Flynn, e.g.:

```
docker save redis | flynn push
```

Once we have a `Flynnfile` (#1084), we can extract that from the image during the push and use it to create a release.

**Comment by dts** [comment]
I am busy trying to migrate from Tutum (my trust for closed-source PaaS is waning now that Parse is shutting down), so I'd just like to put out there that compatibility with a subset of the docker-compose YML spec would be fantastic - this is how Tutum does their "Stack" management.  It's the go-to way of understanding the relationships between docker instances, and framing it in those terms (maybe with some process-type extension, a-la the procfile, who knows) would go a long way to explaining this to someone like me, who is super familiar with docker and docker-compose, but not necessarily so much with Flynn.

**Comment by temujin9** [comment]
:+1: for this; it'll help migrating databases between clusters without downtime.

**Comment by titanous** [comment]
@temujin9 I think you meant #2395.

**Comment by temujin9** [comment]
@titanous so I did. Derp.

**Comment by jvatic** [comment]
Support for pushing Docker images directly to flynn would be very useful on it's own.

Looks like it's as simple as adding `Artifact.ImageID` to be used instead of `Artifact.URI` and endpoints to the host and controller APIs for uploading the image.

**Comment by lmars** [comment]
Docker images can now be pushed using `flynn docker push REF` (see #2857).

This should be in tomorrows nightly release (9th June 2016), then we will likely announce via the blog / updated documentation when it makes it into stable (most likely within a week or two).
