### ISSUE TITLE
Upgrade/Reinstall Flynn? 

### ISSUE THREAD

**Issue by martensson** [flynn/flynn#1092]
Hi,

Is there a way to upgrade a Flynn cluster to a newer version? If not, is there an easy way to completely uninstall Flynn to after reinstall it?

And keep up the amazing work, I am really looking forward to the day its officially production ready!

**Comment by lmars** [comment]
@martensson we are currently working on an updater which will update Flynn components in place to a newer version, we are hoping to ship that very soon.

There is currently no easy way to uninstall Flynn (see #1020), but you can get a new version by stopping Flynn (i.e. `sudo stop flynn-host`) then re-running the installation script.

And thanks for the encouragement!

**Comment by martensson** [comment]
@lmars great to know you are planning to ship an updated and in the meanwhile I will just re-run the install script. Thanks for the help! :+1:

**Comment by thomasfedb** [comment]
To others who find this issue, #1020 was closed by #1393 and the installer now includes an uninstaller with `--remove`. It also allows explicit install from scratch with `--clean`.

**Comment by martensson** [comment]
Thanks Guys! :+1:
