### ISSUE TITLE
Validate SSE responses via JSON schemas

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1108]
We're currently just validating the request exists when the response doesn't map nicely into a schema. I don't think it would be too hard for the example generator to map SSE responses into JSON that could then be validated with a schema.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
