### ISSUE TITLE
Controller deploy can fail to set app release

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1119]
If the `web` process is the last one to restart, the deployer sometimes fails with "connection refused" when calling `SetAppRelease`.

See https://s3.amazonaws.com/flynn-ci-logs/20150301130013-72d02e32-build-8faaae3105ebb22e95c95d60d987bcdb21c2b7b7-2015-03-01-13-18-14.txt.

The deployer needs better retry logic when deploying the controller.

**Comment by jvatic** [comment]
Closing on the basis that #1991 fixes the issue
