### ISSUE TITLE
ReleaseSuite.TestReleaseImages fails

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1123]
https://s3.amazonaws.com/flynn-ci-logs/20150302021042-794b0eec-build-6776184d8372352798ed83c647f554292be1a489-2015-03-02-02-26-23.txt

/cc @lmars

**Comment by titanous** [comment]
Another failure of the same test, different error: https://ci.flynn.io/builds/20150302072334-e3c6b69f

**Comment by titanous** [comment]
https://s3.amazonaws.com/flynn-ci-logs/20150304000436-cb63b94d-build-14d507b0175dc98a3e0f2d8bf2854dc5cae9985e-2015-03-04-00-14-35.txt

**Comment by titanous** [comment]
See also #1097 #1102

**Comment by lmars** [comment]
These errors haven't occurred since 27687ef, closing.

**Comment by lmars** [comment]
This happened again: https://s3.amazonaws.com/flynn-ci-logs/20150312213442-0f1de312-build-2ed2800cc173a73d8e8431b60ba224a7825c766b-2015-03-12-21-51-04.txt

Unfortunately there are no logs from the release instances so it is hard to figure out what went wrong, I am going to fix CI so that it dumps logs from all instances.

**Comment by jvatic** [comment]
Another failure: https://ci.flynn.io/builds/20150322021953-a779e693

```
FAIL: test_release.go:99: ReleaseSuite.TestReleaseImages

test_release.go:119:
    // boot the release cluster, release components to a blobstore and output the new version.json
    releaseCluster := s.addReleaseHosts(t)
test_release.go:28:
    t.Assert(err, c.IsNil)
... value *url.Error = &url.Error{Op:"POST", URL:"https://10.69.30.1:443/cluster/41c04ee8/release", Err:(*errors.errorString)(0xc2083f27a0)} ("POST https://10.69.30.1:443/cluster/41c04ee8/release: httpclient: unexpected status 500")
```

**Comment by lmars** [comment]
@jvatic the last failure you posted was an instance of #1142 (bootstrapping the release cluster failed).

**Comment by jvatic** [comment]
Another one: https://s3.amazonaws.com/flynn-ci-logs/20150411012906-bfada49b-build-9223a51d85d64e30ef682f4788e194b458562081-2015-04-11-01-40-47.txt

**Comment by lmars** [comment]
Hmm in that last failure, it looks like jobs failed to start because libvirt restarted:

```
++ 01:35:38.544 t=2015-04-11T01:35:38+0000 lvl=info msg="starting deploy of system app" name=blobstore
++ 01:35:39.255 t=2015-04-11T01:35:39+0000 lvl=eror msg="error deploying app" name=blobstore err="deployer: web job failed to start"
```

```
HostID: 77f43e1e - flynn-host ps -a

ID                                                         STATE    STARTED        CONTROLLER APP  CONTROLLER TYPE
...
77f43e1e-33a7356841d94a04a01ad194ca597cfe                  failed                  blobstore       web
77f43e1e-3a3660687155487c9b1b0ae39961403c                  failed                  blobstore       web
```

```
HostID: 77f43e1e - flynn-host log --init 77f43e1e-3a3660687155487c9b1b0ae39961403c

01:40:43.722202 host.go:132: [Code-1] [Domain-7] internal error: client socket is closed
```

```
HostID: 77f43e1e - ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         2  0.0  0.0      0     0 ?        S    01:32   0:00 [kthreadd]
...
root      1065  0.2  1.3 1196004 27976 ?       Sl   01:32   0:01 flynn-host daemon --id 77f43e1e --manifest /etc/flynn-host.json --external 10.69.21.6 --force --backend libvirt-lxc
...
root      4479  0.0  0.9 372316 18616 ?        Sl   01:35   0:00 /usr/sbin/libvirtd -d
```

Given we are likely going to move away from libvirt soon, and this is not very frequent, I am tempted to ignore that one for now.

**Comment by titanous** [comment]
Closing, #1458 fixes the libvirt restart errors.
