### ISSUE TITLE
HTTP maintenance mode

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1126]
I would like to put my site into maintenance mode when doing deploys which require downtime or if my app is misbehaving so users see a helpful message rather than a 500 error page / dropped connection.

Ideally I would like to specify a HTML file (e.g. `flynn route add http --maintenance 503.html`) which will get served by the router either if there are no backends (because my app is crashing or down for a long deploy) or I have explicitly enabled maintenance mode (e.g. `flynn maintenance enable`).

This is a simpler version of #65 for handling this case.

**Comment by titanous** [comment]
One aspect of this is providing custom error pages for each error that the router can emit (what else is there other than 503?).

**Comment by nicolas-brousse** [comment]
What about having something similar to Heroku with https://devcenter.heroku.com/articles/maintenance-mode?

And so using the application metas to store the value, somethink like:

```sh
$ flynn meta set maintenance=true
$ flynn meta set maintenance=false
$ flynn meta set maintenance=http://domain.tld/some_static_file.html

# Or create a command to make the same as an "alias"
$ flynn maintenance on [--url=http://domain.tld/some_static_file.html]
$ flynn maintenance off
```
I think I could try to work on a PR for this if you are interested. But I miss some technical comprehension of Flynn router to do it.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
