### ISSUE TITLE
Allow trusted hosts to be added to cluster.

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#1128]
When deploying a RoR application which used Bundler, and which attempted to fetch some dependances via git, the following error resulted:

```
Fetching git@github.com:rails-sqlserver/tiny_tds.git
Host key verification failed.
fatal: Could not read from remote repository.
```

The issue involved ssh not trusting the `github.com`, as the host key had not been added. The immediate, stop-gap resolution was to tell Bundler to fetch the repo by HTTPS.

Discussion on IRC with @lmars resulted in the suggestion that, similar to `flynn add key`, a command is added to allow the addition of trusted hosts to the cluster, eg: `flynn trust host-key github.com`. Such a command could then fetch the key from `github.com`, allow the user to confirm it, and then store it.

Credit to @patcoll for the CLI command name.

**Comment by titanous** [comment]
This appears to be a relatively broad thing: have a generic trust store for public keys/certificates, and apply that to all components of the system. It's not just SSH host keys but CA certificates, TUF keys, etc.

**Comment by thomasfedb** [comment]
This might be of interest @titanous, https://square.github.io/keywhiz/

**Comment by thomasfedb** [comment]
I solved this using a buildpack that lets you give your slug it's own SSH keys.
