### ISSUE TITLE
bootstrap: timed out waiting for http://postgres-api.discoverd/ping

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1142]
```text
Bootstrapping layer 1...
bootstrap ===> online-hosts start
bootstrap ===> require-env start
bootstrap ===> require-env done
bootstrap ===> pg-password start
bootstrap ===> pg-password done
bootstrap ===> postgres start
bootstrap ===> postgres done
bootstrap ===> controller-key start
bootstrap ===> controller-key done
bootstrap ===> dashboard-session-secret start
bootstrap ===> dashboard-session-secret done
bootstrap ===> dashboard-login-token start
bootstrap ===> dashboard-login-token done
bootstrap ===> name-seed start
bootstrap ===> name-seed done
bootstrap ===> postgres-wait start
bootstrap ===> postgres-wait error
bootstrap: timed out waiting for http://postgres-api.discoverd/ping, last response "Get http://postgres-api.discoverd/ping: dial tcp: lookup postgres-api.discoverd: no such host"
```

https://ci.flynn.io/builds/20150302234049-464870cd

**Comment by davidcelis** [comment]
This has been happening to me while trying to boot a new 3-instance Flynn cluster on DigitalOcean. Here are the results of `sudo flynn-host upload-debug-info`: https://gist.github.com/8b6ef28460794cd4edfa

**Comment by titanous** [comment]
@davidcelis In your case it's probably because the etcd state is being reused, but the postgres state isn't, I'm in the process of fixing this. Running `sudo flynn-host destroy-volumes` on each host after stopping flynn-host should fix that if I'm correct.

**Comment by davidcelis** [comment]
Thanks for that tip; unfortunately it looks like it's still happening in my cluster... If it's unrelated to this particular issue, I can open a separate one.

**Comment by titanous** [comment]
Yeah, please open a new issue.

**Comment by lmars** [comment]
Another case of this error: https://ci.flynn.io/builds/20150306022801-6ccc7f9f

**Comment by titanous** [comment]
After implementing #1201, it looks like there is an underlying networking error on CI:

```text
t=2015-03-10T21:22:36+0000 lvl=eror msg="error getting upstream status" app=postgres component=postgres fn=waitForUpstream upstream=100.100.93.2:5432 err="Get http://100.100.93.2:5433/status: dial tcp 100.100.93.2:5433: i/o timeout"
```

https://s3.amazonaws.com/flynn-ci-logs/20150310211844-03ae0ae2-build-45660b74fd8f15bc413553cd40ab5d1149c35cf7-2015-03-10-21-22-39.txt

**Comment by davidcelis** [comment]
Here's more debug output (after updating to the latest Flynn containing #1201) in the wild: https://gist.github.com/00fd579e4b8678105bbd

**Comment by titanous** [comment]
@davidcelis The useful line is this:

```text
t=2015-03-11T20:48:26+0000 lvl=eror msg="error getting upstream status" app=postgres component=postgres fn=waitForUpstream upstream=100.100.11.2:5432 err="Get http://100.100.11.2:5433/status: dial tcp 100.100.11.2:5433: i/o timeout"
```

Which points to there still being networking communication issues in your install.

**Comment by davidcelis** [comment]
At this point, I'm not sure what I'd need to fix in my networking setup aside from just opening all ports and going wild:

```
*filter

#  Allow all loopback (lo0) traffic and drop all traffic to 127/8 that doesn't use lo0
-A INPUT -i lo -j ACCEPT
-A INPUT -d 127.0.0.0/8 -j REJECT

# Allow all flynn (flynnbr0, flannel0, vnetN) traffic
-A INPUT -i flynnbr0 -j ACCEPT
-A INPUT -i flannel0 -j ACCEPT
-A INPUT -i flannel.1 -j ACCEPT
-A INPUT -i vnet+ -j ACCEPT

#  Accept all established inbound connections
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

#  Allow all outbound traffic - you can modify this to only allow certain traffic
-A OUTPUT -j ACCEPT

#  Allow HTTP and HTTPS connections from anywhere (the normal ports for websites and SSL).
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT

#  Allow SSH connections
#
#  The -dport number should be the same port number you set in sshd_config
#
-A INPUT -p tcp -m state --state NEW --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW --dport 2222 -j ACCEPT

#  Allow connections to user defined TCP services
-A INPUT -p tcp --match multiport --dports 3000:3500 -j ACCEPT

#  Allow all TCP/UDP packets from other nodes in the Flynn cluster
-A INPUT -s 104.236.58.155 -j ACCEPT
-A INPUT -s 104.131.50.188 -j ACCEPT
-A INPUT -s 104.236.107.58 -j ACCEPT

#  Allow ping
-A INPUT -p icmp --icmp-type echo-request -j ACCEPT

#  Log iptables denied calls
-A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7

#  Drop all other inbound - default deny unless explicitly allowed policy
-A INPUT -j DROP
-A FORWARD -j DROP

COMMIT
```

I don't suppose you have some sort of example iptables rules somewhere? What does a successful network setup look like? I know this probably isn't a way y'all want to be spending your time, so I'm sorry to keep needing help with this. I figure if I can get this set up correctly, I can at least help out with documentation for people wanting to run their own clusters :+1:

**Comment by titanous** [comment]
@davidcelis Here's a ruleset I've used in the past:

```text
iptables -A FORWARD -i eth0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A FORWARD -i eth0 -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -i eth0 -p tcp --dport 443 -j ACCEPT
iptables -A FORWARD -i eth0 -p tcp --dport 22 -j ACCEPT
iptables -A FORWARD -i eth0 -p tcp --dport 2222 -j ACCEPT
iptables -A FORWARD -i eth0 -p icmp --icmp-type echo-request -j ACCEPT
iptables -A FORWARD -i eth0 -j DROP
```

It needs a bit of tweaking as it's only for a single node and doesn't have the TCP router ports.

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150318193648-fbaccb30

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150319193714-92dda8a7

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150323225747-bd4bdc81

**Comment by lmars** [comment]
I managed to reproduce this in CI, but haven't found the root cause, see [this IRC conversation](https://botbot.me/freenode/flynn/2015-04-01/?msg=35536667).

**Comment by balzaczyy** [comment]
I also hit the same issue. Is there any update to this issue?

**Comment by titanous** [comment]
@balzaczyy This usually means you have a firewall incorrectly configured.

**Comment by titanous** [comment]
Closing, this test failure does not appear in the CI logs dating back to May 1st.
