### ISSUE TITLE
Installation complete but flynn command not found.

### ISSUE THREAD

**Issue by jeffkit** [flynn/flynn#1143]
The installation logs show as bellow:

```text
===> 10:07:08.674 installing runtime dependencies
===> 10:07:08.676 running "apt-get install --yes aufs-tools iptables libvirt-bin ubuntu-zfs"
Reading package lists... Done
Building dependency tree       
Reading state information... Done
iptables is already the newest version.
aufs-tools is already the newest version.
libvirt-bin is already the newest version.
ubuntu-zfs is already the newest version.
The following packages were automatically installed and are no longer required:
  libjansson4 sqlite3 uwsgi-core
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 105 not upgraded.
===> 10:07:09.404 downloading flynn-host binary to tmp dir
===> 10:09:36.954 verifying flynn-host binary checksum
===> 10:09:36.999 moving verified flynn-host binary to /usr/local/bin
===> 10:09:37.003 running "gunzip /tmp/tmp.RrqFFY1NZJ/flynn-host.gz"
===> 10:09:37.325 running "mv /tmp/tmp.RrqFFY1NZJ/flynn-host /usr/local/bin/flynn-host"
===> 10:09:37.341 running "chmod +x /usr/local/bin/flynn-host"
===> 10:09:37.346 downloading Flynn components
10:09:37.520270 host.go:122: tuf: no root keys found in local meta store
===> 10:09:37.524 installing Upstart job
cp: cannot stat ‘/etc/flynn/upstart.conf’: No such file or directory
===> 10:09:37.589 installation complete!
root@i-aoggstf5:~# flynn
flynn: command not found
root@i-aoggstf5:~# flynn-host 
usage: flynn-host [-h|--help] <command> [<args>...]
```

**Comment by lmars** [comment]
@jeffkit was this the first time you ran the script? If not, what was the previous output?

**Comment by jeffkit** [comment]
The last 4 lines of log is the same, no matter the first time or the second time, third time.  After first time, the installation is more quickly.

My OS is ubuntu 14.04. install script is: 
bash < <(curl -fsSL https://dl.flynn.io/install-flynn)

**Comment by lmars** [comment]
@jeffkit do you by any chance have the complete output from the first time you ran the installer? It looks like the first install failed in some way and left your system in an odd state where further attempts will also fail. Seeing the complete output of the first install will help me understand what went wrong.

**Comment by jeffkit** [comment]
@lmars OK, I just copy the complete output and paste it here, I found some strange log like:

`W: Duplicate sources.list entry http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main i386 Packages (/var/lib/apt/lists/ppa.launchpad.net_saltstack_salt_ubuntu_dists_trusty_main_binary-i386_Packages)
W: You may want to run apt-get update to correct these problems`

I am not sure if it is the reason fail to install. 
The complete log is:

root@i-aoggstf5:~# bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
===> 14:44:17.573 adding zfs-native APT PPA
===> 14:44:17.575 running "apt-key adv --keyserver keyserver.ubuntu.com --recv E871F18B51E0147C77796AC81196BA81F6B0FC61"
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.WeXuIam7W4 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/saltstack-salt.gpg --keyserver keyserver.ubuntu.com --recv E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server keyserver.ubuntu.com
gpg: key F6B0FC61: public key "Launchpad PPA for Native ZFS for Linux" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
===> 14:44:21.666 running "apt-get update"
Ign http://ftp.sjtu.edu.cn trusty InRelease
Ign http://ftp.sjtu.edu.cn trusty-updates InRelease                            
Ign http://ftp.sjtu.edu.cn trusty-security InRelease                           
Hit http://ftp.sjtu.edu.cn trusty Release.gpg                                  
Hit http://ftp.sjtu.edu.cn trusty-updates Release.gpg                          
Hit http://ftp.sjtu.edu.cn trusty-security Release.gpg                         
Hit http://ftp.sjtu.edu.cn trusty Release                               
Hit http://ftp.sjtu.edu.cn trusty-updates Release                              
Hit http://ftp.sjtu.edu.cn trusty-security Release                             
Hit http://ftp.sjtu.edu.cn trusty/main Sources                                 
Hit http://ftp.sjtu.edu.cn trusty/restricted Sources                           
Hit http://ftp.sjtu.edu.cn trusty/universe Sources                             
Hit http://ftp.sjtu.edu.cn trusty/multiverse Sources                           
Hit http://ftp.sjtu.edu.cn trusty/main amd64 Packages                          
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://ftp.sjtu.edu.cn trusty/restricted amd64 Packages                    
Hit http://ftp.sjtu.edu.cn trusty/universe amd64 Packages                      
Hit http://ftp.sjtu.edu.cn trusty/multiverse amd64 Packages                    
Hit http://ftp.sjtu.edu.cn trusty/main i386 Packages                           
Hit http://ftp.sjtu.edu.cn trusty/restricted i386 Packages        
Hit http://ftp.sjtu.edu.cn trusty/universe i386 Packages          
Hit http://ftp.sjtu.edu.cn trusty/multiverse i386 Packages        
Ign http://ppa.launchpad.net trusty InRelease                     
Hit http://ftp.sjtu.edu.cn trusty/main Translation-en             
Hit http://ftp.sjtu.edu.cn trusty/multiverse Translation-en       
Hit http://ftp.sjtu.edu.cn trusty/restricted Translation-en       
Hit http://ftp.sjtu.edu.cn trusty/universe Translation-en         
Hit http://ftp.sjtu.edu.cn trusty-updates/main Sources                         
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://ftp.sjtu.edu.cn trusty-updates/restricted Sources        
Ign http://get.docker.io docker InRelease                                      
Hit http://ftp.sjtu.edu.cn trusty-updates/universe Sources                     
Hit http://ftp.sjtu.edu.cn trusty-updates/multiverse Sources        
Hit http://ftp.sjtu.edu.cn trusty-updates/main amd64 Packages
Hit http://ftp.sjtu.edu.cn trusty-updates/restricted amd64 Packages
Hit http://ftp.sjtu.edu.cn trusty-updates/universe amd64 Packages  
Hit http://ftp.sjtu.edu.cn trusty-updates/multiverse amd64 Packages
Hit http://ftp.sjtu.edu.cn trusty-updates/main i386 Packages
Hit http://ftp.sjtu.edu.cn trusty-updates/restricted i386 Packages
Get:1 http://ppa.launchpad.net trusty Release.gpg [316 B]
Hit http://ftp.sjtu.edu.cn trusty-updates/universe i386 Packages              
Hit http://ftp.sjtu.edu.cn trusty-updates/multiverse i386 Packages
Hit http://ftp.sjtu.edu.cn trusty-updates/main Translation-en
Hit http://ftp.sjtu.edu.cn trusty-updates/multiverse Translation-en
Hit http://ftp.sjtu.edu.cn trusty-updates/restricted Translation-en
Hit http://ftp.sjtu.edu.cn trusty-updates/universe Translation-en  
Hit http://ftp.sjtu.edu.cn trusty-security/main Sources
Hit http://ftp.sjtu.edu.cn trusty-security/restricted Sources
Hit http://ppa.launchpad.net trusty Release  
Hit http://ftp.sjtu.edu.cn trusty-security/universe Sources                    
Hit http://ftp.sjtu.edu.cn trusty-security/multiverse Sources                  
Hit http://ftp.sjtu.edu.cn trusty-security/main amd64 Packages     
Hit http://ftp.sjtu.edu.cn trusty-security/restricted amd64 Packages
Hit http://ftp.sjtu.edu.cn trusty-security/universe amd64 Packages
Hit http://ftp.sjtu.edu.cn trusty-security/multiverse amd64 Packages
Hit http://ftp.sjtu.edu.cn trusty-security/main i386 Packages       
Hit http://ftp.sjtu.edu.cn trusty-security/restricted i386 Packages 
Hit http://ftp.sjtu.edu.cn trusty-security/universe i386 Packages   
Hit http://ftp.sjtu.edu.cn trusty-security/multiverse i386 Packages
Get:2 http://ppa.launchpad.net trusty Release [15.1 kB]
Hit http://ftp.sjtu.edu.cn trusty-security/main Translation-en                
Hit http://ftp.sjtu.edu.cn trusty-security/multiverse Translation-en          
Hit http://ftp.sjtu.edu.cn trusty-security/restricted Translation-en          
Hit http://ftp.sjtu.edu.cn trusty-security/universe Translation-en           
Hit http://ppa.launchpad.net trusty/main amd64 Packages               
Ign http://ftp.sjtu.edu.cn trusty/main Translation-en_US           
Ign http://ftp.sjtu.edu.cn trusty/multiverse Translation-en_US     
Ign http://ftp.sjtu.edu.cn trusty/restricted Translation-en_US     
Ign http://ftp.sjtu.edu.cn trusty/universe Translation-en_US
Hit http://ppa.launchpad.net trusty/main i386 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Get:3 http://ppa.launchpad.net trusty/main amd64 Packages [4,530 B]
Get:4 http://ppa.launchpad.net trusty/main i386 Packages [4,543 B]   
Hit http://get.docker.io docker Release.gpg                            
Get:5 http://ppa.launchpad.net trusty/main Translation-en [2,181 B]
Hit http://get.docker.io docker Release                                        
Hit http://get.docker.io docker/main amd64 Packages                            
Hit http://get.docker.io docker/main i386 Packages                             
Ign http://get.docker.io docker/main Translation-en_US                         
Ign http://get.docker.io docker/main Translation-en
Fetched 26.7 kB in 41s (637 B/s)
Reading package lists... Done
W: Duplicate sources.list entry http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main amd64 Packages (/var/lib/apt/lists/ppa.launchpad.net_saltstack_salt_ubuntu_dists_trusty_main_binary-amd64_Packages)
W: Duplicate sources.list entry http://ppa.launchpad.net/saltstack/salt/ubuntu/ trusty/main i386 Packages (/var/lib/apt/lists/ppa.launchpad.net_saltstack_salt_ubuntu_dists_trusty_main_binary-i386_Packages)
W: You may want to run apt-get update to correct these problems
===> 14:45:09.027 installing runtime dependencies
===> 14:45:09.029 running "apt-get install --yes aufs-tools iptables libvirt-bin ubuntu-zfs"
Reading package lists... Done
Building dependency tree       
Reading state information... Done
iptables is already the newest version.
aufs-tools is already the newest version.
aufs-tools set to manually installed.
The following packages were automatically installed and are no longer required:
  libjansson4 sqlite3 uwsgi-core
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  augeas-lenses bridge-utils dkms ebtables iproute libaugeas0
  libboost-system1.54.0 libboost-thread1.54.0 libnetcf1 libnvpair1
  libpciaccess0 librados2 librbd1 libuutil1 libvirt0 libx86-1 libxen-4.4
  libxenstore3.0 libxml2-utils libyajl2 libzfs2 libzpool2 mountall pm-utils
  spl spl-dkms vbetool zfs-dkms zfs-doc zfsutils
Suggested packages:
  augeas-doc debhelper augeas-tools qemu-kvm qemu radvd lvm2 cpufrequtils
  radeontool zfs-auto-snapshot samba-common-bin nfs-kernel-server
  zfs-initramfs
The following NEW packages will be installed:
  augeas-lenses bridge-utils dkms ebtables iproute libaugeas0
  libboost-system1.54.0 libboost-thread1.54.0 libnetcf1 libnvpair1
  libpciaccess0 librados2 librbd1 libuutil1 libvirt-bin libvirt0 libx86-1
  libxen-4.4 libxenstore3.0 libxml2-utils libyajl2 libzfs2 libzpool2 pm-utils
  spl spl-dkms ubuntu-zfs vbetool zfs-dkms zfs-doc zfsutils
The following packages will be upgraded:
  mountall
1 upgraded, 31 newly installed, 0 to remove and 105 not upgraded.
Need to get 8,048 kB of archives.
After this operation, 42.3 MB of additional disk space will be used.
Get:1 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main libboost-system1.54.0 amd64 1.54.0-4ubuntu3.1 [10.1 kB]
Get:2 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main libboost-thread1.54.0 amd64 1.54.0-4ubuntu3.1 [26.5 kB]
Get:3 http://ftp.sjtu.edu.cn/ubuntu/ trusty/main libpciaccess0 amd64 0.13.2-1 [20.4 kB]
Get:4 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main librados2 amd64 0.80.7-0ubuntu0.14.04.1 [1,413 kB]
Get:5 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main mountall amd64 2.53-zfs1 [69.9 kB]
Get:6 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main librbd1 amd64 0.80.7-0ubuntu0.14.04.1 [316 kB]
Get:7 http://ftp.sjtu.edu.cn/ubuntu/ trusty/main libx86-1 amd64 1.1+ds1-10 [83.0 kB]
Get:8 http://ftp.sjtu.edu.cn/ubuntu/ trusty/main libyajl2 amd64 2.0.4-4 [20.8 kB]
Get:9 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main augeas-lenses all 1.2.0-0ubuntu1.1 [230 kB]
Get:10 http://ftp.sjtu.edu.cn/ubuntu/ trusty/main bridge-utils amd64 1.5-6ubuntu2 [29.2 kB]
Get:11 http://ftp.sjtu.edu.cn/ubuntu/ trusty/main ebtables amd64 2.0.10.4-3ubuntu1 [77.5 kB]
Get:12 http://ftp.sjtu.edu.cn/ubuntu/ trusty/main iproute all 1:3.12.0-2 [2,384 B]
Get:13 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main libaugeas0 amd64 1.2.0-0ubuntu1.1 [135 kB]
Get:14 http://ftp.sjtu.edu.cn/ubuntu/ trusty/main libnetcf1 amd64 1:0.2.3-4ubuntu1 [44.4 kB]
Get:15 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main libvirt0 amd64 1.2.2-0ubuntu13.1.9 [830 kB]
Get:16 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main dkms all 2.2.0.3-1.1ubuntu5.14.04+zfs9~trusty [72.0 kB]
Get:17 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main libxenstore3.0 amd64 4.4.1-0ubuntu0.14.04.3 [18.7 kB]
Get:18 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main libxen-4.4 amd64 4.4.1-0ubuntu0.14.04.3 [272 kB]
Get:19 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main libvirt-bin amd64 1.2.2-0ubuntu13.1.9 [2,065 kB]
Get:20 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main spl-dkms all 0.6.3-3~trusty [390 kB]
Get:21 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main libxml2-utils amd64 2.9.1+dfsg1-3ubuntu4.4 [34.7 kB]
Get:22 http://ftp.sjtu.edu.cn/ubuntu/ trusty-updates/main pm-utils all 1.4.1-13ubuntu0.1 [50.8 kB]
Get:23 http://ftp.sjtu.edu.cn/ubuntu/ trusty/main vbetool amd64 1.1-3 [11.6 kB]
Get:24 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main zfs-doc amd64 0.6.3-5~trusty [60.2 kB]
Get:25 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main zfs-dkms amd64 0.6.3-5~trusty [988 kB]
Get:26 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main spl amd64 0.6.3-3~trusty [16.3 kB]
Get:27 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main libuutil1 amd64 0.6.3-5~trusty [27.3 kB]
Get:28 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main libnvpair1 amd64 0.6.3-5~trusty [22.9 kB]
Get:29 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main libzpool2 amd64 0.6.3-5~trusty [355 kB]
Get:30 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main libzfs2 amd64 0.6.3-5~trusty [101 kB]
Get:31 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main zfsutils amd64 0.6.3-5~trusty [254 kB]
Get:32 http://ppa.launchpad.net/zfs-native/stable/ubuntu/ trusty/main ubuntu-zfs amd64 8~trusty [1,752 B]
Fetched 8,048 kB in 1min 36s (83.1 kB/s)                                       
Extracting templates from packages: 100%
(Reading database ... 101665 files and directories currently installed.)
Preparing to unpack .../mountall_2.53-zfs1_amd64.deb ...
Unpacking mountall (2.53-zfs1) over (2.53) ...
Selecting previously unselected package libboost-system1.54.0:amd64.
Preparing to unpack .../libboost-system1.54.0_1.54.0-4ubuntu3.1_amd64.deb ...
Unpacking libboost-system1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Selecting previously unselected package libboost-thread1.54.0:amd64.
Preparing to unpack .../libboost-thread1.54.0_1.54.0-4ubuntu3.1_amd64.deb ...
Unpacking libboost-thread1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Selecting previously unselected package libpciaccess0:amd64.
Preparing to unpack .../libpciaccess0_0.13.2-1_amd64.deb ...
Unpacking libpciaccess0:amd64 (0.13.2-1) ...
Selecting previously unselected package librados2.
Preparing to unpack .../librados2_0.80.7-0ubuntu0.14.04.1_amd64.deb ...
Unpacking librados2 (0.80.7-0ubuntu0.14.04.1) ...
Selecting previously unselected package librbd1.
Preparing to unpack .../librbd1_0.80.7-0ubuntu0.14.04.1_amd64.deb ...
Unpacking librbd1 (0.80.7-0ubuntu0.14.04.1) ...
Selecting previously unselected package libx86-1:amd64.
Preparing to unpack .../libx86-1_1.1+ds1-10_amd64.deb ...
Unpacking libx86-1:amd64 (1.1+ds1-10) ...
Selecting previously unselected package libyajl2:amd64.
Preparing to unpack .../libyajl2_2.0.4-4_amd64.deb ...
Unpacking libyajl2:amd64 (2.0.4-4) ...
Selecting previously unselected package dkms.
Preparing to unpack .../dkms_2.2.0.3-1.1ubuntu5.14.04+zfs9~trusty_all.deb ...
Unpacking dkms (2.2.0.3-1.1ubuntu5.14.04+zfs9~trusty) ...
Selecting previously unselected package spl-dkms.
Preparing to unpack .../spl-dkms_0.6.3-3~trusty_all.deb ...
Unpacking spl-dkms (0.6.3-3~trusty) ...
Selecting previously unselected package zfs-doc.
Preparing to unpack .../zfs-doc_0.6.3-5~trusty_amd64.deb ...
Unpacking zfs-doc (0.6.3-5~trusty) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up dkms (2.2.0.3-1.1ubuntu5.14.04+zfs9~trusty) ...
Setting up spl-dkms (0.6.3-3~trusty) ...
Loading new spl-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.13.0-36-generic
Building initial module for 3.13.0-36-generic
Done.

spl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-36-generic/updates/dkms/

splat.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-36-generic/updates/dkms/

Running the post_install script:

depmod......

DKMS: install completed.
Selecting previously unselected package zfs-dkms.
(Reading database ... 102108 files and directories currently installed.)
Preparing to unpack .../zfs-dkms_0.6.3-5~trusty_amd64.deb ...
Unpacking zfs-dkms (0.6.3-5~trusty) ...
Selecting previously unselected package augeas-lenses.
Preparing to unpack .../augeas-lenses_1.2.0-0ubuntu1.1_all.deb ...
Unpacking augeas-lenses (1.2.0-0ubuntu1.1) ...
Selecting previously unselected package bridge-utils.
Preparing to unpack .../bridge-utils_1.5-6ubuntu2_amd64.deb ...
Unpacking bridge-utils (1.5-6ubuntu2) ...
Selecting previously unselected package ebtables.
Preparing to unpack .../ebtables_2.0.10.4-3ubuntu1_amd64.deb ...
Unpacking ebtables (2.0.10.4-3ubuntu1) ...
Selecting previously unselected package iproute.
Preparing to unpack .../iproute_1%3a3.12.0-2_all.deb ...
Unpacking iproute (1:3.12.0-2) ...
Selecting previously unselected package libaugeas0.
Preparing to unpack .../libaugeas0_1.2.0-0ubuntu1.1_amd64.deb ...
Unpacking libaugeas0 (1.2.0-0ubuntu1.1) ...
Selecting previously unselected package libnetcf1.
Preparing to unpack .../libnetcf1_1%3a0.2.3-4ubuntu1_amd64.deb ...
Unpacking libnetcf1 (1:0.2.3-4ubuntu1) ...
Selecting previously unselected package libvirt0.
Preparing to unpack .../libvirt0_1.2.2-0ubuntu13.1.9_amd64.deb ...
Unpacking libvirt0 (1.2.2-0ubuntu13.1.9) ...
Selecting previously unselected package libxenstore3.0.
Preparing to unpack .../libxenstore3.0_4.4.1-0ubuntu0.14.04.3_amd64.deb ...
Unpacking libxenstore3.0 (4.4.1-0ubuntu0.14.04.3) ...
Selecting previously unselected package libxen-4.4.
Preparing to unpack .../libxen-4.4_4.4.1-0ubuntu0.14.04.3_amd64.deb ...
Unpacking libxen-4.4 (4.4.1-0ubuntu0.14.04.3) ...
Selecting previously unselected package libvirt-bin.
Preparing to unpack .../libvirt-bin_1.2.2-0ubuntu13.1.9_amd64.deb ...
Unpacking libvirt-bin (1.2.2-0ubuntu13.1.9) ...
Selecting previously unselected package libxml2-utils.
Preparing to unpack .../libxml2-utils_2.9.1+dfsg1-3ubuntu4.4_amd64.deb ...
Unpacking libxml2-utils (2.9.1+dfsg1-3ubuntu4.4) ...
Selecting previously unselected package pm-utils.
Preparing to unpack .../pm-utils_1.4.1-13ubuntu0.1_all.deb ...
Unpacking pm-utils (1.4.1-13ubuntu0.1) ...
Selecting previously unselected package spl.
Preparing to unpack .../spl_0.6.3-3~trusty_amd64.deb ...
Unpacking spl (0.6.3-3~trusty) ...
Selecting previously unselected package libuutil1.
Preparing to unpack .../libuutil1_0.6.3-5~trusty_amd64.deb ...
Unpacking libuutil1 (0.6.3-5~trusty) ...
Selecting previously unselected package libnvpair1.
Preparing to unpack .../libnvpair1_0.6.3-5~trusty_amd64.deb ...
Unpacking libnvpair1 (0.6.3-5~trusty) ...
Selecting previously unselected package libzpool2.
Preparing to unpack .../libzpool2_0.6.3-5~trusty_amd64.deb ...
Unpacking libzpool2 (0.6.3-5~trusty) ...
Selecting previously unselected package libzfs2.
Preparing to unpack .../libzfs2_0.6.3-5~trusty_amd64.deb ...
Unpacking libzfs2 (0.6.3-5~trusty) ...
Selecting previously unselected package zfsutils.
Preparing to unpack .../zfsutils_0.6.3-5~trusty_amd64.deb ...
Unpacking zfsutils (0.6.3-5~trusty) ...
Selecting previously unselected package ubuntu-zfs.
Preparing to unpack .../ubuntu-zfs_8~trusty_amd64.deb ...
Unpacking ubuntu-zfs (8~trusty) ...
Selecting previously unselected package vbetool.
Preparing to unpack .../vbetool_1.1-3_amd64.deb ...
Unpacking vbetool (1.1-3) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Processing triggers for initramfs-tools (0.103ubuntu4.2) ...
update-initramfs: Generating /boot/initrd.img-3.13.0-36-generic
Setting up mountall (2.53-zfs1) ...
Setting up libboost-system1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Setting up libboost-thread1.54.0:amd64 (1.54.0-4ubuntu3.1) ...
Setting up libpciaccess0:amd64 (0.13.2-1) ...
Setting up librados2 (0.80.7-0ubuntu0.14.04.1) ...
Setting up librbd1 (0.80.7-0ubuntu0.14.04.1) ...
Setting up libx86-1:amd64 (1.1+ds1-10) ...
Setting up libyajl2:amd64 (2.0.4-4) ...
Setting up zfs-doc (0.6.3-5~trusty) ...
Setting up zfs-dkms (0.6.3-5~trusty) ...
Loading new zfs-0.6.3 DKMS files...
First Installation: checking all kernels...
Building only for 3.13.0-36-generic
Building initial module for 3.13.0-36-generic
Done.

zavl:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-36-generic/updates/dkms/

zcommon.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-36-generic/updates/dkms/

znvpair.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-36-generic/updates/dkms/

zpios.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-36-generic/updates/dkms/

zunicode.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-36-generic/updates/dkms/

zfs.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/3.13.0-36-generic/updates/dkms/

depmod....

DKMS: install completed.
Setting up augeas-lenses (1.2.0-0ubuntu1.1) ...
Setting up bridge-utils (1.5-6ubuntu2) ...
Setting up ebtables (2.0.10.4-3ubuntu1) ...
Setting up iproute (1:3.12.0-2) ...
Setting up libaugeas0 (1.2.0-0ubuntu1.1) ...
Setting up libnetcf1 (1:0.2.3-4ubuntu1) ...
Setting up libvirt0 (1.2.2-0ubuntu13.1.9) ...
Setting up libxenstore3.0 (4.4.1-0ubuntu0.14.04.3) ...
Setting up libxen-4.4 (4.4.1-0ubuntu0.14.04.3) ...
Setting up libvirt-bin (1.2.2-0ubuntu13.1.9) ...
Adding group `libvirtd' (GID 117) ...
Done.
libvirt-bin start/running, process 1359
Setting up libvirt-bin dnsmasq configuration.
Setting up libxml2-utils (2.9.1+dfsg1-3ubuntu4.4) ...
Setting up pm-utils (1.4.1-13ubuntu0.1) ...
Setting up spl (0.6.3-3~trusty) ...
Setting up libuutil1 (0.6.3-5~trusty) ...
Setting up libnvpair1 (0.6.3-5~trusty) ...
Setting up libzpool2 (0.6.3-5~trusty) ...
Setting up libzfs2 (0.6.3-5~trusty) ...
Setting up zfsutils (0.6.3-5~trusty) ...
Setting up vbetool (1.1-3) ...
Processing triggers for initramfs-tools (0.103ubuntu4.2) ...
update-initramfs: Generating /boot/initrd.img-3.13.0-36-generic
Processing triggers for ureadahead (0.100.0-16) ...
Setting up ubuntu-zfs (8~trusty) ...
Processing triggers for libc-bin (2.19-0ubuntu6.4) ...
===> 14:53:55.768 downloading flynn-host binary to tmp dir
===> 14:54:25.563 verifying flynn-host binary checksum
===> 14:54:25.610 moving verified flynn-host binary to /usr/local/bin
===> 14:54:25.612 running "gunzip /tmp/tmp.hRIJecRpvu/flynn-host.gz"
===> 14:54:25.820 running "mv /tmp/tmp.hRIJecRpvu/flynn-host /usr/local/bin/flynn-host"
===> 14:54:25.825 running "chmod +x /usr/local/bin/flynn-host"
===> 14:54:25.828 downloading Flynn components
14:54:55.902154 host.go:122: tuf: failed to download root.json: Get https://dl.flynn.io/tuf/root.json: dial tcp 54.230.159.71:443: i/o timeout
===> 14:54:55.907 installing Upstart job
cp: cannot stat ‘/etc/flynn/upstart.conf’: No such file or directory
===> 14:54:55.989 installation complete!

**Comment by lmars** [comment]
@jeffkit thanks for that output, the original error was this:

```
14:54:55.902154 host.go:122: tuf: failed to download root.json: Get https://dl.flynn.io/tuf/root.json: dial tcp 54.230.159.71:443: i/o timeout
```

I will open an issue so that this error does not prevent further installs to fail, and I have also opened #1144 to update the script so that those types of failures halt the installation with an error.

For now, to complete the installation run `sudo rm -rf /etc/flynn` and re-run the installation script.

**Comment by jeffkit** [comment]
@lmars Cool!  thanks!
