### ISSUE TITLE
router: sync error: cannot acquire from closed pool logspam

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1145]
There is some scenario where the router can fail into a loop infinitely printing this error:

```text
router: sync error: cannot acquire from closed pool
```

I *think* this happens when postgres goes away.

/cc @benburkert @bgentry

**Comment by bgentry** [comment]
hm, looked into this briefly just now, but I can't see anywhere we're closing the `pgx.ConnPool` except for on shutdown:

https://github.com/flynn/flynn/blob/9574f9aea07dd0e28caeea56284f596d64036af2/router/server.go#L116

Do you have any more details on when this happened? Was the server up and running for awhile?

**Comment by titanous** [comment]
I'm pretty sure I saw this after booting a cluster with `SINGLETON=false` and killing the postgres primary, but I didn't have time to look at it in detail or try again. It was just reported in IRC by a user that had a bunch of issues getting the router going, possibly port collisions.

**Comment by titanous** [comment]
@monaka is running into this: https://gist.github.com/f29f850ffcd3f871cb9d

**Comment by titanous** [comment]
I haven't seen this in quite a while, closing.
