### ISSUE TITLE
Flynn-host bootstrap: timeout waiting for http://router-api.discoverd

### ISSUE THREAD

**Issue by jeffkit** [flynn/flynn#1147]
I Have Flynn install in one single node. Just want to make it run. I follow the installation guide but unable to bootstrap it.

```text
root@i-aoggstf5:~# start flynn-host
flynn-host start/running, process 10049
root@i-aoggstf5:~# status flynn-host
flynn-host start/running, process 10049

export CLUSTER_DOMAIN=flynn.127.0.0.1.xip.io && flynn-host bootstrap --min-hosts=1 /etc/flynn/bootstrap-manifest.json
12:23:58.995959 check online-hosts
12:23:58.999301 require-env require-env
12:23:58.999947 gen-random pg-password
12:23:59.000875 gen-random pg-password 8f4a4b525477d43a9b7d81bd427dccd8
12:23:59.000975 run-app postgres
12:23:59.592141 gen-random controller-key
12:23:59.592335 gen-random controller-key ecbecd36349b3a2c2261866a63e98f9f
12:23:59.592360 gen-random dashboard-session-secret
12:23:59.592413 gen-random dashboard-session-secret 69e7287e0a8d559904b2800ffa99be90
12:23:59.592429 gen-random dashboard-login-token
12:23:59.592479 gen-random dashboard-login-token eda8ff02e108ec35680f8113cfab5a4b
12:23:59.592484 gen-random name-seed
12:23:59.592559 gen-random name-seed 324d56a15064b5960820
12:23:59.592565 wait postgres-wait
12:24:05.558038 run-app controller
12:24:06.463216 wait controller-wait
12:24:07.538477 add-app controller-inception
12:24:07.597682 add-app postgres-app
12:24:07.619884 scale-app scheduler-scale
12:24:07.628489 run-app scheduler
12:24:07.852767 deploy-app blobstore
12:24:08.649001 deploy-app router
12:24:09.268676 gen-ssh-key gitreceive-key
12:24:11.264537 deploy-app gitreceive
12:24:11.328832 gen-tls-cert controller-cert
12:24:14.039246 gen-tls-cert controller-cert pin: 4ULHe7YNT2m6/gFrv0UyNm2R/Z08MJm1o6BfHTr6/DQ=
12:24:14.039448 wait router-wait
12:26:14.532003 wait router-wait error: bootstrap: timed out waiting for http://router-api.discoverd, last response "Get http://router-api.discoverd: dial tcp: lookup router-api.discoverd: no such host"
```

**Comment by titanous** [comment]
Please run `flynn-host upload-debug-info` and post the link here.

**Comment by jeffkit** [comment]
@titanous  
root@i-aoggstf5:~# flynn-host upload-debug-info
12:36:56.647353 upload-debug-info.go:48: error adding tmp-flynn-host.log: open /tmp/flynn-host.log: no such file or directory
12:37:05.793866 upload-debug-info.go:71: Debug information uploaded to: https://gist.github.com/573966d39e05602f5f09

**Comment by bgentry** [comment]
looks like one of these from the router on each of the 3 attempts to boot:

```
04:24:10.789036 server.go:137: address already in use
```

**Comment by titanous** [comment]
Do you have anything listening on TCP ports 80, 443, 2222, or 3000-3500? The router is reporting that it can't bind to one of those ports.

**Comment by jeffkit** [comment]
@titanous Yes, An Nginx instance is running in the same node.

**Comment by titanous** [comment]
That's the problem. Flynn needs port 80 to work properly.

**Comment by jeffkit** [comment]
OK, I am going to fix it.

**Comment by jeffkit** [comment]
Still another problem after I stop nginx.

root@i-aoggstf5:~# /etc/init.d/nginx stop
root@i-aoggstf5:~# export CLUSTER_DOMAIN=flynn.127.0.0.1.xip.io && flynn-host bootstrap --min-hosts=1 /etc/flynn/bootstrap-manifest.json
12:44:55.044425 check online-hosts
12:44:55.053223 require-env require-env
12:44:55.053997 gen-random pg-password
12:44:55.054910 gen-random pg-password 3b5c6671a21fbcdbf3836e4078555c28
12:44:55.055026 run-app postgres
12:44:55.636844 gen-random controller-key
12:44:55.637095 gen-random controller-key a6bc71daef95f9947d0aaf5b424d257c
12:44:55.637103 gen-random dashboard-session-secret
12:44:55.637136 gen-random dashboard-session-secret a3b9d8cd212d30955ccd7e7c40d557e7
12:44:55.637141 gen-random dashboard-login-token
12:44:55.637194 gen-random dashboard-login-token 206540123f8e2e7c8f079eea8e886dbb
12:44:55.637200 gen-random name-seed
12:44:55.637278 gen-random name-seed ee035221ea9fa3cc45ef
12:44:55.637285 wait postgres-wait
12:44:55.647337 run-app controller
12:44:56.388670 wait controller-wait
12:44:56.396073 add-app controller-inception
12:44:56.398440 add-app controller-inception error: POST http://100.100.75.4:80/apps: httpclient: unexpected status 401
root@i-aoggstf5:~# flynn-host upload-debug-info
12:45:34.121287 upload-debug-info.go:48: error adding tmp-flynn-host.log: open /tmp/flynn-host.log: no such file or directory
12:45:43.999122 upload-debug-info.go:71: Debug information uploaded to: https://gist.github.com/bfd1b7541d9168c6460a

**Comment by titanous** [comment]
That's a different error. You should stop flynn-host and run `sudo flynn-host destroy-volumes` before restarting.

**Comment by jeffkit** [comment]
I follow your  instruction, but problem still there.
The nginx was stop, but the port 80 is using by flynn itself.

root@i-aoggstf5:~# stop flynn-host
flynn-host stop/waiting
root@i-aoggstf5:~# flynn-host destroy-volumes 
opening volume state db...
DBUG[03-03|13:11:21] zfs get all -Hp flynn-default            package=zfs
DBUG[03-03|13:11:21] zfs get all -Hp flynn-default/9b0b969e8662437facbb08b038842181 package=zfs
volume state db opened.
'--include-data' not specified; leaving backend data storage intact.
state db file "/var/lib/flynn/volumes/volumes.bolt" removed.
root@i-aoggstf5:~# start flynn-host
flynn-host start/running, process 31748
root@i-aoggstf5:~# export CLUSTER_DOMAIN=flynn.127.0.0.1.xip.io && flynn-host bootstrap --min-hosts=1 /etc/flynn/bootstrap-manifest.json
13:11:42.801881 check online-hosts
13:11:43.778442 require-env require-env
13:11:43.778939 gen-random pg-password
13:11:43.780412 gen-random pg-password 2426f92bdab33cd3fd21de6d14d4145a
13:11:43.780559 run-app postgres
13:11:45.007407 gen-random controller-key
13:11:45.007607 gen-random controller-key 40d9be1b254420ddebddeb7002cb69f1
13:11:45.007633 gen-random dashboard-session-secret
13:11:45.007667 gen-random dashboard-session-secret ffb85d2ed88a15f546864d1a2a429276
13:11:45.007673 gen-random dashboard-login-token
13:11:45.007723 gen-random dashboard-login-token dc3fd469044efe97432927c1430d9676
13:11:45.007729 gen-random name-seed
13:11:45.009054 gen-random name-seed 1a51824f8507905c595e
13:11:45.009163 wait postgres-wait
13:12:00.694683 run-app controller
13:12:02.460667 wait controller-wait
13:12:04.602152 add-app controller-inception
13:12:04.771863 add-app postgres-app
13:12:04.828383 scale-app scheduler-scale
13:12:04.849803 run-app scheduler
13:12:06.032766 deploy-app blobstore
13:12:07.483216 deploy-app router
13:12:08.486439 gen-ssh-key gitreceive-key
13:12:10.181947 deploy-app gitreceive
13:12:10.297819 gen-tls-cert controller-cert
13:12:18.270544 gen-tls-cert controller-cert pin: EgDXYihBbe5voTP950C2U1r2b0RrpAF8hD3bYCZZJ0k=
13:12:18.270834 wait router-wait
13:14:27.551589 wait router-wait error: bootstrap: timed out waiting for http://router-api.discoverd, last response "Get http://router-api.discoverd: dial tcp: lookup router-api.discoverd: no such host"

**Comment by titanous** [comment]
Please run `flynn-host upload-debug-info`.

**Comment by jeffkit** [comment]
root@i-aoggstf5:~# flynn-host upload-debug-info
13:15:56.409436 upload-debug-info.go:48: error adding tmp-flynn-host.log: open /tmp/flynn-host.log: no such file or directory
13:30:37.047829 upload-debug-info.go:71: Debug information uploaded to: https://gist.github.com/7d12dff22bf4ea8dc03c

**Comment by titanous** [comment]
@bgentry I think this is another case of #1145, the router log is too big to view.

@jeffkit Do you mind posting a few lines from the log files in `/tmp/flynn-host-logs/d6cbe56b0c25403e8183f5933d920996`?

**Comment by jeffkit** [comment]
root@i-aoggstf5:~# tail -100 /tmp/flynn-host-logs/d6cbe56b0c25403e8183f5933d920996/d6cbe56b0c25403e8183f5933d920996.log 
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587753,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587754,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587755,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587756,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":2,"t":1425359587757,"m":"2015/03/03 05:13:07 router: sync error: cannot acquire from closed pool\n"}
{"s":3,"t":1425359890768,"m":"t=2015-03-03T05:18:03+0000 lvl=info msg=\"command exited due to signal\" app=containerinit fn=babySit\n"}
{"s":3,"t":1425359892085,"m":"t=2015-03-03T05:18:07+0000 lvl=info msg=\"command exited\" app=containerinit fn=containerInitApp status=0\nt=2015-03-03T05:18:07+0000 lvl=info msg=exiting app=containerinit fn=containerInitApp\nt=2015-03-03T05:18:05+0000 lvl=info msg=\"received signal\" app=containerinit fn=babySit type=\"child exited\"\n"}

**Comment by jeffkit** [comment]
Any new clew to continue?
