### ISSUE TITLE
bootstrap should error if run against a bootstrapped or partially bootstrapped cluster

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1150]
Running bootstrap against a cluster that is partially or completely running is a bad idea and will never work. Until we fix #225 we should warn and/or stop the user from doing this and tell them to restart from scratch.

**Comment by paralin** [comment]
What do you mean, restart from scratch? How do we debootstrap?

**Comment by titanous** [comment]
stop flynn-host and run `sudo flynn-host destroy-volumes`

**Comment by titanous** [comment]
The `resource-check` step does this.

**Comment by temujin9** [comment]
So we should now expect that bootstraps attempted from second and subsequent nodes, after the first has launched its bootstrap, should be stopped harmlessly? Just confirming before I nuke some old code . . .

**Comment by titanous** [comment]
I believe so. The bootstrap should fail because [at least one of these ports](https://github.com/flynn/flynn/blob/f58f01ead7eab6fea25f0b2a29cdd8b70fd9df3a/bootstrap/manifest_template.json#L11-L14) is bound.
