### ISSUE TITLE
data race in discoverd server test

### ISSUE THREAD

**Issue by benburkert** [flynn/flynn#1151]
Hit this data race in a CI job: https://s3.amazonaws.com/flynn-ci-logs/20150303212705-cc6cf3f8-build-c7978cc9dd1b22b08435a573a38b293cb85c427b-2015-03-03-21-28-45.txt

**Comment by titanous** [comment]
This is actually a race in the test suite that only happens when that test fails. Gocheck assertions must not be used from goroutines.

**Comment by jvatic** [comment]
https://s3.amazonaws.com/flynn-ci-logs/20150323213442-44344386-build-feaf56c8785d95b70eb7124b759edaf3a938c672-2015-03-23-21-36-43.txt

**Comment by titanous** [comment]
This hasn't happened recently.
