### ISSUE TITLE
deployer: Rolling back the controller breaks the cluster

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1160]
If the controller fails to deploy, the deployer will do a rollback which calls `PutFormation` and `DeleteFormation` in quick succession (i.e. [here](https://github.com/flynn/flynn/blob/master/controller/deployer/main.go#L154-L164)) , which leads to the scheduler potentially scaling itself down before it has started new schedulers to replace itself, leaving the cluster in a broken state.

**Comment by jvatic** [comment]
The scheduler should create an event (e.g. `deploy_complete`) once a formation is in it's final state, the deployer can then wait for this event between `PutFormation` and `DeleteFormation`.

**Comment by lmars** [comment]
@jvatic the deployer could just wait for the appropriate amount of old jobs to be running? I don't see the need for an extra event.

**Comment by jvatic** [comment]
@lmars yes, and I think that may be the better short-term solution here, however having to do a formation diff and wait for the appropriate job events in order to know a formation is deployed and running seems like too much. I'll open a separate issue for that.
