### ISSUE TITLE
CI build stuck on go test -race

### ISSUE THREAD

**Issue by bgentry** [flynn/flynn#1161]
This build was stuck on `go test -race` for > 20 minutes before @lmars killed it: https://ci.flynn.io/builds/20150304034700-3dc21039

I re-pushed with a tweaked commit message and the build went through just fine.

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150803215800-5463e274

**Comment by titanous** [comment]
This has not happened recently.
