### ISSUE TITLE
If the AWS installer can't write to ~/.flynnrc access is impossible

### ISSUE THREAD

**Issue by jellybob** [flynn/flynn#1165]
I'm not sure why I had a root owned flynnrc in my home directory, but its presence caused the installer to abort because it couldn't be written to. This meant that despite the cluster being up, I wasn't able to authenticate with it since the details had never been displayed.

Maybe it would make sense to dump what would have been written to the user's console in that situation?

**Comment by jvatic** [comment]
I think in this case the installer should print an error about not being able to write to `~/.flynnrc` and present a yes/no prompt for trying again (allowing you to make it writable). If it fails a second time, it should print the `flynn cluster add` command instead.

**Comment by jvatic** [comment]
This situation has improved with #1305 as the installer will print a warning instead of aborting.
