### ISSUE TITLE
Internal HTTP clients should use a low connect timeout

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1167]
Internal HTTP clients use `http.DefaultTransport` which [uses a connect timeout of 30s](https://golang.org/pkg/net/http/#RoundTripper) which is a lot higher than needed. We should use an explicit transport with a lower timeout (e.g. 5s).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
