### ISSUE TITLE
Host ID parsing errors should 400

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1174]
Currently if I pass an unparsable job identifier is passed to the controller, it will result in a 500. This should be a 400 error with a validation error message. (example triggering error: `flynn log foo`)

**Comment by jzila** [comment]
This doesn't reproduce for me with `flynn log foo` (triggers `usage: ...` output), not sure if it's been fixed.

**Comment by titanous** [comment]
@jzila Try `flynn kill`, the log command uses the aggregation backend now.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
