### ISSUE TITLE
Setting up a cluster with an AWS AutoScaling Group

### ISSUE THREAD

**Issue by psirenny** [flynn/flynn#1175]
Sorry if this question is more related to AWS than it is to flynn, but I figured it might be something you already considered. Which is: What is the best way to set up an autoscaling group with flynn?

The tricky part is having only one instance in the group run `sudo flynn-host init --init-discovery=3` and exposing the token it generates to all other instances. If the discovery token was already generated/known it would be easier because you could create each instance with a user startup script that basically did this: `sudo flynn-host init --discovery <token>`. Is that possible?

**Comment by titanous** [comment]
You can create a token that will work with `--discovery` by running this command:

```text
curl -w "\n" https://discovery.etcd.io/new?size=3
```

**Comment by psirenny** [comment]
awesome, thanks!
