### ISSUE TITLE
Vagrant:  push flynn master, Permission denied!

### ISSUE THREAD

**Issue by jeffkit** [flynn/flynn#1183]
After "Vagrant up", the flynn cluster is already there. I flow the use flynn document, everything goes well, but can not push code to flynn, do I miss any step?

root@flynn:/home/vagrant# flynn cluster add -g demo.localflynn.com:2222 -p y7Vi8rw94eHuqrFqLanjUSe4OmfyouTUJ6U2MUgCT1A= default https://controller.demo.localflynn.com 9f0245f1cec62f3b42b790ae0337d778
Cluster "default" added and set as default.
vagrant@flynn:~$ flynn key add
Key 49:68:75:a0:d3:ac:51:8f:33:56:06:a8:93:dd:c1:9d added.
vagrant@flynn:~$ ls
vagrant@flynn:~$ pwd
/home/vagrant
vagrant@flynn:~$ git clone https://github.com/flynn/nodejs-flynn-example.git
Cloning into 'nodejs-flynn-example'...
remote: Counting objects: 25, done.
remote: Total 25 (delta 0), reused 0 (delta 0), pack-reused 25
Unpacking objects: 100% (25/25), done.
Checking connectivity... done.
vagrant@flynn:~$ cd nodejs-flynn-example/
vagrant@flynn:~/nodejs-flynn-example$ flynn create example
Created example
vagrant@flynn:~/nodejs-flynn-example$ git remote -v
flynn	ssh://git@demo.localflynn.com:2222/example.git (fetch)
flynn	ssh://git@demo.localflynn.com:2222/example.git (push)
origin	https://github.com/flynn/nodejs-flynn-example.git (fetch)
origin	https://github.com/flynn/nodejs-flynn-example.git (push)
vagrant@flynn:~/nodejs-flynn-example$ flynn route
ROUTE                             SERVICE      ID
http:example.demo.localflynn.com  example-web  http/1c495e8d-eef4-4e68-9864-86642a25f5ac
vagrant@flynn:~/nodejs-flynn-example$ git push flynn master
The authenticity of host '[demo.localflynn.com]:2222 ([192.0.2.200]:2222)' can't be established.
ECDSA key fingerprint is e3:ce:5f:b8:c3:1c:86:70:5f:87:a0:19:44:f1:98:3d.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[demo.localflynn.com]:2222,[192.0.2.200]:2222' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by titanous** [comment]
Please run `ssh -vvv -p 2222 git@demo.localflynn.com` and post a link to a gist with the output.

**Comment by jeffkit** [comment]
jeff@ns1~/projects/flynn/demo$vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'flynn-base' is up to date...
==> default: A newer version of the box 'flynn-base' is available! You currently
==> default: have version '20150305.0'. The latest is version '20150307.0'. Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.
jeff@ns1~/projects/flynn/demo$ssh -vvv -p 2222 git@demo.localflynn.com
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/jeff/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: /etc/ssh_config line 53: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to demo.localflynn.com [192.0.2.200] port 2222.
debug1: connect to address 192.0.2.200 port 2222: Connection refused
ssh: connect to host demo.localflynn.com port 2222: Connection refused

**Comment by titanous** [comment]
Please run `vagrant provision` and try again.

**Comment by jeffkit** [comment]
jeff@ns1~/projects/flynn/demo$vagrant provision
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: flynn-host start/running, process 1981
==> default: 07:34:15.787146 check online-hosts
==> default: 07:34:15.792809 require-env require-env
==> default: 07:34:15.793081 gen-random pg-password
==> default: 07:34:15.794746 gen-random pg-password eba720727363a5dba3194907a9988029
==> default: 07:34:15.794789 run-app postgres
==> default: 07:34:16.196835 gen-random controller-key
==> default: 07:34:16.197236 gen-random controller-key 61914e32168ab5297bae5d0326c43361
==> default: 07:34:16.197384 gen-random dashboard-session-secret
==> default: 07:34:16.197621 gen-random dashboard-session-secret b8db6ffe30b7c5a62d9370066550f127
==> default: 07:34:16.197801 gen-random dashboard-login-token
==> default: 07:34:16.198062 gen-random dashboard-login-token 2cbf3b0385a5e750aeb6cad10d3585c9
==> default: 07:34:16.198261 gen-random name-seed
==> default: 07:34:16.198515 gen-random name-seed f248ab5d400d465842c6
==> default: 07:34:16.198722 wait postgres-wait
==> default: 07:36:16.265614 wait postgres-wait error: bootstrap: timed out waiting for http://postgres-api.discoverd/ping, last response "Get http://postgres-api.discoverd/ping: dial tcp: lookup postgres-api.discoverd: no such host"
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by titanous** [comment]
Hmm, could be corrupt state, I'd run `vagrant destroy -f && vagrant up`. I merged a bunch of fixes today that will show up in the next nightly.

**Comment by chrise86** [comment]
I'm having the same issue, none of the steps above worked for me...

**Comment by titanous** [comment]
@chrise86 Please open a new issue describing your situation and the errors you are getting, a lot has changed since this issue was resolved.
