### ISSUE TITLE
Docs for migrating from zfs backing file to real devs

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1189]
Currently we provision a zpool on a 100GB sparse file so that the user doesn't have to set up backing disks. We should document migrating the datasets on this zpool to a zpool backed by real disks. We should also document the caveats of using the flat file and the considerations that go into building a production zpool.

**Comment by josephglanville** [comment]
Ran into this the other day when wanting to use my own zpool.

Short and sweet version of how to do so is to create your own pool prior to starting `flynn-host` with the name `flynn-default`. Flynn will then not create it's own pool or even create the sparse backing file in the first place.

As for migration from a backing file to a real zpool backed by real zdevs, this should be possible via a combination of zpool attach and zpool detach to first add the new zdev as a mirror and then later remove the sparse file when all the blocks have been replicated.

Here is an example of how that would work:
```
# truncate -s 2G vdev1
# truncate -s 2G vdev2
# zpool create mpool /root/vdev1
# zpool list
NAME    SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
mpool  1.98G    50K  1.98G         -     0%     0%  1.00x  ONLINE  -
# zpool attach mpool /root/vdev1 /root/vdev2
root@booking-staging-i-93a3754d:~# zpool status
  pool: mpool
 state: ONLINE
  scan: resilvered 52K in 0h0m with 0 errors on Sat Aug 22 16:26:26 2015
config:

	NAME             STATE     READ WRITE CKSUM
	mpool            ONLINE       0     0     0
	  mirror-0       ONLINE       0     0     0
	    /root/vdev1  ONLINE       0     0     0
	    /root/vdev2  ONLINE       0     0     0

errors: No known data errors
# zpool detach mpool /root/vdev1
# zpool status
  pool: mpool
 state: ONLINE
  scan: resilvered 52K in 0h0m with 0 errors on Sat Aug 22 16:26:26 2015
config:

	NAME           STATE     READ WRITE CKSUM
	mpool          ONLINE       0     0     0
	  /root/vdev2  ONLINE       0     0     0

errors: No known data errors
```
