### ISSUE TITLE
Too Many Open Files in Router and Apps

### ISSUE THREAD

**Issue by Lazyshot** [flynn/flynn#1205]
I'm currently receiving `too many open files` errors from the router and both my application after using it for a while. This could occur between a couple hours to a few days depending on server load.  Current temporary fix is to restart router via `virsh` and scale apps 1->0->1.

## Router Log
```
2015/03/10 15:34:53 http: Accept error: accept tcp 0.0.0.0:80: too many open files; retrying in 1s
2015/03/10 15:34:54 http: Accept error: accept tcp 0.0.0.0:80: too many open files; retrying in 1s
2015/03/10 15:34:55 http: Accept error: accept tcp 0.0.0.0:80: too many open files; retrying in 1s
```

## Router Limits
```
...
Limit                     Soft Limit           Hard Limit           Units
Max open files            1024                 4096                 files
...
```

## Sysctl.conf
`fs.file-max = 2097152`

## Ulimits
```
~  ulimit -n
500000
```

**Comment by titanous** [comment]
I was unable to reproduce this with repeated runs of `wrk` and 200 concurrent connections, so I'm assuming that there is no meaningful fd leak in the router, and you are hitting the fd limit due to real requests or leaks in your application. I will look into tuning the max fds parameter next.

**Comment by titanous** [comment]
I filed a quick PR to bump the limit to 10k, and opened #1230 to track coming up with a good way to specify custom values.
