### ISSUE TITLE
Sync files?

### ISSUE THREAD

**Issue by stela5** [flynn/flynn#1206]
I tried to find an answer in your documentation and issue tracker but didn't find one so my apologies if this is a duplicate...   I know Flynn supports a clustered database (Postgres) out of the box, but does it also support file syncing as well?  For example, something like powerstrip-flocker or seafiles?  Use case is end-user file uploads that I don't want to commit to version control.

**Comment by titanous** [comment]
No, we do not support any clustered filesystems currently. Internally we use the postgres large object APIs to store arbitrary binary blobs.

**Comment by stela5** [comment]
Thanks for the fast response!
