### ISSUE TITLE
Buildpack-multi caching

### ISSUE THREAD

**Issue by geovanisouza92** [flynn/flynn#1214]
Related to #619.

This not seems to work with buildpack-multi. My apt/python stack is compiled from scratch all times.

There is a way to change the buildpack-multi to take advantage of #653 or change slugbuilder to install dependencies from requirements.apt file or something like that?

**Comment by lmars** [comment]
@geovanisouza92 what buildpacks are you ultimately using (i.e. the contents of `.buildpacks` in your repository)? It sounds like the buildpacks you are using do not utilise the cache.

**Comment by geovanisouza92** [comment]
.buildpacks

```
https://github.com/ddollar/heroku-buildpack-apt
https://github.com/heroku/heroku-buildpack-python
```

Aptfile

```
libfbclient2
```

**Comment by lmars** [comment]
@geovanisouza92 this seems to work ok with the [Python example app](https://github.com/flynn-examples/python-flynn-example):

* initial deploy downloads `libfbclient2` & `Flask`

```
$ cat .buildpacks 
https://github.com/ddollar/heroku-buildpack-apt
https://github.com/heroku/heroku-buildpack-python

$ cat Aptfile 
libfbclient2

$ flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-multi.git

$ git push flynn master
...
-----> Fetching .debs for libfbclient2
...
       Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe firebird2.5-common-doc all 2.5.2.26540.ds4-9ubuntu1 [30.9 kB]
       Get:2 http://archive.ubuntu.com/ubuntu/ trusty/universe firebird2.5-common all 2.5.2.26540.ds4-9ubuntu1 [95.8 kB]
       Get:3 http://archive.ubuntu.com/ubuntu/ trusty/universe libfbclient2 amd64 2.5.2.26540.ds4-9ubuntu1 [278 kB]
       Fetched 404 kB in 0s (2867 kB/s)
       Download complete and in download only mode
-----> Installing firebird2.5-common-doc_2.5.2.26540.ds4-9ubuntu1_all.deb
-----> Installing firebird2.5-common_2.5.2.26540.ds4-9ubuntu1_all.deb
-----> Installing libfbclient2_2.5.2.26540.ds4-9ubuntu1_amd64.deb
...
-----> Installing dependencies with pip
       Collecting Flask==0.9 (from -r requirements.txt (line 1))
       Downloading Flask-0.9.tar.gz (481kB)
...
=====> Application deployed
```

* adding `gunicorn` to `requirements.txt` only downloads `gunicorn`

```
$ echo 'gunicorn>=19.1' >> requirements.txt
$ git commit --all --message "Add gunicorn"
$ git push flynn master
-----> Fetching .debs for libfbclient2
...
       Need to get 0 B/404 kB of archives.
...
-----> Installing dependencies with pip
       Collecting gunicorn>=19.1 (from -r requirements.txt (line 2))
       Downloading gunicorn-19.3.0-py2.py3-none-any.whl (110kB)
...
=====> Application deployed
```

* deploying no changes doesn't download anything

```
$ git commit --allow-empty --message "noop"
$ git push flynn master
...
-----> Fetching .debs for libfbclient2
...
       Need to get 0 B/404 kB of archives.
...
-----> Installing dependencies with pip
...
=====> Application deployed
```

If your experience is different, please add the output of multiple git pushes.

**Comment by geovanisouza92** [comment]
@lmars I hadn't setted BUILDPACK_URL, I've tried and now seems that the dependencies from ```Aptfile``` and ```requirements.txt``` are correctly cached and updated.

But it seems that the buildpacks is still downloaded:

```sh
-----> Building quail-torment-havelock...
-----> Fetching custom buildpack
-----> Multipack app detected
       =====> Downloading Buildpack: https://github.com/ddollar/heroku-buildpack-apt
       =====> Detected Framework: Apt
...
-----> Writing profile script
       =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-python
       =====> Detected Framework: Python
```

The python buildpack specially takes some seconds. There is a way to cache it to reduce even more the build time?

**Comment by lmars** [comment]
@geovanisouza92 I'm glad it's working for you now!

The downloading of the buildpacks is handled by the multi builpack [here](https://github.com/ddollar/heroku-buildpack-multi/blob/master/bin/compile#L27-L38), so if you want the buildpacks cached then you should modify that buildpack to utilise the cache we provide to it, or open an issue on [the multi buildpack repo](https://github.com/ddollar/heroku-buildpack-multi) requesting it.

**Comment by geovanisouza92** [comment]
I understand. Thank you for the explanation. :smile:
