### ISSUE TITLE
Host fails to upload debug info.

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#1215]
Running `flynn-host upload-debug-info` produces:

```
23:33:32.334497 upload-debug-info.go:48: error adding tmp-flynn-host.log: open /tmp/flynn-host.log: no such file or directory
```

Host is Ubuntu 14.04 LTS, 3.13.0-46-generic, x86_64.

**Comment by thomasfedb** [comment]
flynn-host v20150302.0

**Comment by lmars** [comment]
@thomasfedb so is that the only output from running the command, and then it exited?

**Comment by thomasfedb** [comment]
@lmars No, error is produced, and then the command keeps running. In fact it hasn't finished yet.

**Comment by thomasfedb** [comment]
@lmars If long execution time is expected then some more -v would be nice.
