### ISSUE TITLE
Dashboard hung when accessing large log

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#1216]
When I accessed a large (I estimate ~600KB) logfile via the dashboard web interface, it hung and I had to forcefully restart it by scaling to 0 and then back to 1.

During this period I was also unable to access my application, although this resolved without direct intervention when the dashboard was restarted.

**Comment by thomasfedb** [comment]
flynn-host v20150302.0

**Comment by titanous** [comment]
This will be resolved by the log aggregation tier landing soon.
