### ISSUE TITLE
FAIL: logbuf_test.go:112: S.TestClose

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1224]
```
FAIL: logbuf_test.go:112: S.TestClose

logbuf_test.go:141:
    c.Assert(ok, Equals, true)
... obtained bool = false
... expected bool = true
```

https://ci.flynn.io/builds/20150311211127-0900d9f5

**Comment by titanous** [comment]
Duplicate of #457

**Comment by titanous** [comment]
Actually, crap, it's not.

**Comment by jvatic** [comment]
https://s3.amazonaws.com/flynn-ci-logs/20150312033301-368f6e5f-build-b3ad8cbbc1f403c085cdb4113bf18d01b81a4fec-2015-03-12-03-35-31.txt

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150319202001-5c957a20

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150322134822-ff1db869

**Comment by jvatic** [comment]
https://s3.amazonaws.com/flynn-ci-logs/20150323213442-44344386-build-feaf56c8785d95b70eb7124b759edaf3a938c672-2015-03-23-21-36-43.txt

**Comment by titanous** [comment]
logbuf was deleted in #2008.
