### ISSUE TITLE
one-off jobs get a type of "" instead of something like "run"

### ISSUE THREAD

**Issue by bgentry** [flynn/flynn#1232]
Jobs that are created with `flynn run` receive a type of `""` instead of something like `"run"`, as they do on Heroku. This may be intentional, but @titanous suggests it also may not have been given much thought.

There are likely a bunch of tests that will have to be fixed if this is changed, but the decision could at least use some more thought.

**Comment by lmars** [comment]
The scheduler uses an empty process type to detect one-off jobs and ignore them (see [here](https://github.com/flynn/flynn/blob/master/controller/scheduler/main.go#L644-L648) and [here](https://github.com/flynn/flynn/blob/master/controller/scheduler/main.go#L722-L725)).

We should add extra metadata for that (e.g. `flynn-controller.one-off=true`) and use a more descriptive process type for one-off jobs.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
