### ISSUE TITLE
CLI created AWS instance detached after assigning elastic IP

### ISSUE THREAD

**Issue by drunknbass** [flynn/flynn#1243]
flynn version: 20150305

Via OS X,
Create new instance via CLI for AWS and reassign IP address in AWS console breaks flynn hub connection. Performing an action results in a time out and prints the old expired IP to the console.

After getting guidance from "lmars" in the irc it turns out this is currently a limitation.

**Comment by titanous** [comment]
I don't think this is a bug. You can change the IP address in the Route 53 zone and health check in your AWS account. Why did you want to use an elastic IP?
