### ISSUE TITLE
Force Buildpack

### ISSUE THREAD

**Issue by temp** [flynn/flynn#1245]
I just tried to deploy a php application to flynn, with a composer file.
But there is also a package.json, which leads flynn to think it's a nodejs app, and uses the nodejs buildpack.
Is there a way to force a buildpack, like heroku has, as described in the following link? 
Described here: http://tomatohater.com/2013/08/29/want-heroku-apache-php-but-getting-nodejs-stack/

**Comment by lmars** [comment]
@temp you can use an explicit buildpack by setting the `BUILDPACK_URL` environment variable:

```
flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php.git
```
