### ISSUE TITLE
Add flag to override domain for cluster install on aws

### ISSUE THREAD

**Issue by rpeterson** [flynn/flynn#1246]
Would like a way to supply domain in flynn install aws to change out flynnhub domain name with custom domain such as cloud.example.com.

**Comment by douganger** [comment]
I would very much like this functionality as well, preferably with the ability to use a subdomain on a hosted zone already on AWS.

**Comment by jvatic** [comment]
Note that we do have the ability to migrate to a new domain now via the cli (`flynn cluster migrate-domain`).

**Comment by sarbull** [comment]
i got here also by needing this feature 👍
