### ISSUE TITLE
layer 0 init seems not to startup port 111

### ISSUE THREAD

**Issue by ebergonzi** [flynn/flynn#1258]
https://gist.github.com/b02bc6711852887a7f57

**Comment by ebergonzi** [comment]
thanx in advance.

**Comment by lmars** [comment]
@ebergonzi it looks like there are issues with the etcd cluster, can you please gist the contents of the following file:

```
/tmp/flynn-host-logs/flynn-etcd-23e2e3434fc64b2d92be1518484a2e72/flynn-etcd-23e2e3434fc64b2d92be1518484a2e72.log
```

**Comment by ebergonzi** [comment]
Thank you for the answer. Im not running a custer. Im running in a single
node over ubuntu into virtualbox. Excuse for not to explain myself

**Comment by lmars** [comment]
@ebergonzi ok thanks for clarifying, the contents of that log file will still be helpful though, can you upload  it to a gist so I can take a look?

**Comment by ebergonzi** [comment]
Thanks for the reply.
Pittifully, the file requested for you doesn't exists, but i'll upload flynn-hosts.log. Maybe you can guide to me to research for something into the info inducted from it.

https://gist.github.com/ebergonzi/283afc091c435394e8b8

**Comment by ebergonzi** [comment]
The ls -la of the dir requested for you doesn't seems to contain an etcd related dir nor an etcd related file.

I'll show that

root@flynn:/tmp/flynn-host-logs# ls -la /tmp/flynn-host-logs/
total 32
drwxr--r-- 8 root root 4096 mar 16 11:56 .
drwxrwxrwt 3 root root 4096 mar 16 12:20 ..
drwxr--r-- 2 root root 4096 mar 16 11:56 4649f5188e824512866c21e706c4bed5
drwxr--r-- 2 root root 4096 mar 16 11:40 8534f380885d456eafdf3ba0526d504e
drwxr--r-- 2 root root 4096 mar 16 11:44 99df96a6039347df9b307fbcdc0553a7
drwxr--r-- 2 root root 4096 mar 16 11:47 d75374b620934b8e9052d5c8caf1df4c
drwxr--r-- 2 root root 4096 mar 16 11:47 e5f6c6a251d7495bbde6b0508810b74b
drwxr--r-- 2 root root 4096 mar 16 11:58 f1ef45f0dfaa4b5db9995d73e10e0558

**Comment by lmars** [comment]
@ebergonzi since you do not have the relevant logs it is quite difficult for me to understand what the issue is.

I would suggest building a new VM and seeing if you still have issues bootstrapping, and if you do then run `sudo flynn-host collect-debug-info` again and also gist the contents of any files with name like `/tmp/flynn-host-logs/*-etcd-*/*.log`.

**Comment by ebergonzi** [comment]
Lmars... we've talked via irc, and you've solved thw trouble. ...Not to use
a proxy between slugrunner and blobstore.... Excuse me for not to upload a
gist. This issue is solved
