### ISSUE TITLE
Add docs on how to operate flynn

### ISSUE THREAD

**Issue by alex** [flynn/flynn#1286]
Once I've installed flynn, how do I:

* Add capacity
* Remove capacity
* Upgrade flynn
* Monitor/observe system health
* Find logs to debug production issues
* etc :-)

Cheers.

PS: I'm very excited about flynn

**Comment by philiplb** [comment]
+1! :-)

**Comment by aaronshaf** [comment]
+1

**Comment by gmaclennan** [comment]
+1 how to add capacity

**Comment by titanous** [comment]
Documentation covering how to operate Flynn in production is available at https://flynn.io/docs/production

Please open new issues for anything you notice that is missing.
