### ISSUE TITLE
Flynn layer1 can't start normally

### ISSUE THREAD

**Issue by xubenling0918** [flynn/flynn#1317]
Help~
When I execute the command "CLUSTER_DOMAIN=demo.localflynn.com flynn-host bootstrap /etc/flynn/bootstrap-manifest.json" to start flynn layer 1, it show me the fllowing messages:
check online-hosts
check online-hosts error: Get http://127.0.0.1:1111/services/flynn-host: dial tcp 127.0.0.1:1111: connection refuesed

The flynn layer0 has started, but when I execute "flynn-host ps", it also show me the wrong message "host.go:130: Get http://127.0.0.1:1111/services/flynn-host: dial tcp 127.0.0.1:1111: connection refuesed"

**Comment by lmars** [comment]
@xubenling0918 please run `flynn-host collect-debug-info` to upload logs and system information to a gist, then post the gist link here so we can take a look.

**Comment by JohnyMoSwag** [comment]
I'm seeing a similar issue.

https://gist.github.com/6f94c51d07ab8b9005ef

**Comment by xubenling0918** [comment]
@lmars @JohnyMoSwag Thanks for your answers sincerely. I redeployed a new virtual machine in virtualbox and repeated the installation steps, then it worked. It seems that the problem comes from my virtual machine.
