### ISSUE TITLE
node.js build fail

### ISSUE THREAD

**Issue by sukitha** [flynn/flynn#1334]
Hi all,

I am new to flynn, this is my first experience with it. My sample node.js application build failed with error no 7. Debug info attached bellow, please help me to fix this issue.  

https://gist.github.com/anonymous/855b43cd2eaccede7095

**Comment by lmars** [comment]
@sukitha do you have any firewall rules blocking outbound traffic?

**Comment by sukitha** [comment]
I checked with infastructure team and they said there are no any blocking rule applied

**Comment by lmars** [comment]
@sukitha ok so it looks like the build is stuck trying to run the following command:

```
curl --silent --get --data-urlencode range=0.10.x https://semver.herokuapp.com/node/resolve
```

Can you try running that from the command line on the host running Flynn? It should output a version number like `0.10.37`.

**Comment by sukitha** [comment]
i installed flynn in digital-ocean its working fine. may be our network issue as you say
