### ISSUE TITLE
bootstrap: timed out waiting for http://router-api.discoverd

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1343]
```
++ 22:53:20.508 bootstrap: timed out waiting for http://router-api.discoverd, last response "Get http://router-api.discoverd: dial tcp: lookup router-api.discoverd: no such host"
```

https://ci.flynn.io/builds/20150323224536-e4a54ec7

**Comment by lmars** [comment]
This looks very similar to #1142 with lots of `i/o timeout` errors, but interestingly in this failure postgres managed to come up before those errors started, whereas in the other issue the network never seems functional.

**Comment by jvatic** [comment]
https://s3.amazonaws.com/flynn-ci-logs/20150325223924-f80ca0a7-build-88b0a1f2c6b742f236b34b2d11cfc613db4d1fda-2015-03-25-22-44-02.txt

**Comment by monaka** [comment]
I got similar (maybe same) situation. I tried five or more on the same standalone machine and 100% reproduction.
This is an debug log: https://gist.github.com/f29f850ffcd3f871cb9d

**Comment by titanous** [comment]
Closing, this test failure does not appear in the CI logs dating back to May 1st.

**Comment by titanous** [comment]
@monaka You encountered #1145. All further discussion should happen there.

**Comment by monaka** [comment]
I tried again on the same hardware, the latest flynn.
Log spams are stopped (So I record this here instead of #1145).

But I got same error.
https://gist.github.com/anonymous/600ae873829ec7e9deb3

**Comment by titanous** [comment]
@monaka you are running nginx on that host, so the router is unable to bind to port 80/443.

**Comment by monaka** [comment]
Ah, thank you for your pointing out, @titanous. It's my mistake.

**Comment by monaka** [comment]
And I got same error messages on the another box. Web servers don't run on it.
https://gist.github.com/cfd3323c4a14a542432f
It seems some discoverd were crashed on there.
I create an new issue about this if it was better.

**Comment by titanous** [comment]
@monaka Please open a new issue with the exact error message that you got.
