### ISSUE TITLE
Redis database appliance

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#1345]
A Redis database appliance should be available. It's commonly used for job queues and other key-value store requirements.

**Comment by lmars** [comment]
We do plan to have a Redis appliance out-of-the-box in the future, but for now see the following gist for a way to run Redis using a Docker image from the Docker registry:

https://gist.github.com/lmars/fca0f18b4ecd507fb39a

**Comment by OwlyCode** [comment]
:+1: that would be great to scale sessions across multiple web instances.

**Comment by zeroasterisk** [comment]
And while you're at it, add MongoDB and RethinkDB and Cassandra, and, and... oh and managed multi-master clustering for each :smiley:

**Comment by titanous** [comment]
@zeroasterisk That's absolutely the plan, it's just a matter of resources.

**Comment by thomasmodeneis** [comment]
@lmars thanks for your link, however I can see on the gist that:
# note that although the container has a data volume, they are not currently sticky so restarting the container will get a new data directory. This will be fixed when we have a Redis appliance / sticky volumes.

Any ideas on how to achieve data persistence?

**Comment by thomasfedb** [comment]
Gosh, that font-size...

**Comment by christiangenco** [comment]
:+1: for data persistence.

**Comment by stretchkennedy** [comment]
:+1: Redis would provide a simpler example than Postgres to anyone looking to write an appliance in the future, and might be a good opportunity to write a guide on how to do that :smiley:

**Comment by titanous** [comment]
There is now an alpha Redis appliance that can be used as a cache (no persistence). `flynn resource add redis`.

**Comment by thomasmodeneis** [comment]
Nice, I will test this :)
