### ISSUE TITLE
Installer's go-bindata should be moved to a go generate definition

### ISSUE THREAD

**Issue by pzduniak** [flynn/flynn#1348]
IMO go-bindata command should be moved from tupfile (which doesn't work on Windows) to go generate and the result file should end up in the repo. It will make it very easy to make `cli` command go get-able.

**Comment by titanous** [comment]
We provide nightly builds capable of auto-updating, so there's no need to support `go get`. #1350 resolves getting the cross-compile going for Windows, we'll provide officially supported builds.

**Comment by titanous** [comment]
Running this in PowerShell should install the auto-updating CLI binary on Windows:

```powershell
(New-Object Net.WebClient).DownloadString('https://dl.flynn.io/cli.ps1') | iex
```

I still need to fix a few paths, but it seems to mostly work. Please let me know if you try it out!
