### ISSUE TITLE
Backing Services

### ISSUE THREAD

**Issue by sukitha** [flynn/flynn#1360]
I want to deploy a application with backing services support such as Redis, logstash, RabbitMQ and SMTP. I managed to install Redis by following instruction in "https://gist.github.com/lmars/fca0f18b4ecd507fb39a". Is there a standard way to install rest of backing services in flynn environment.

**Comment by lmars** [comment]
@sukitha the approach in the linked gist is currently the standard way to deploy non-buildpack based services using Docker images from a Docker registry.

For reference, here are URIs to Docker images for some of the services you mentioned:

Logstash `1.4.2`:
```
https://registry.hub.docker.com?name=logstash&id=98a09aa3e8b23e0edd447287feae70c833a8cc10253fa179cb7594c847482603
```

RabbitMQ `3.5.0`:
```
https://registry.hub.docker.com?name=rabbitmq&id=571751cd6dddb556d8d256f7f6a652595974e49bc2ab0c0de89765d5c220a82a
```

We know this isn't a simple way to deploy these services, and we have plans to improve the workflow for deploying generic images in the future (see for example #1085).

In the long term, we aim to support these services out-of-the-box (e.g. `flynn resource add rabbitmq`).
