### ISSUE TITLE
Request for open source of https://domains.flynn.io

### ISSUE THREAD

**Issue by rpeterson** [flynn/flynn#1362]
I would love it if we could make https://domains.flynn.io open source as it is a part of the installer at this point and is something that get's in the way of working on improving flynn outside of the core team.

**Comment by titanous** [comment]
Is there anything specific you're interested in improving? The server doesn't do much.

**Comment by rpeterson** [comment]
mainly just want to know steps required in order get custom domain AWS deployments in place. And I think it would be a nice tool to handle some of the cluster management issues if you are dealing with isolated clusters of flynn installs.

**Comment by titanous** [comment]
#1246 (looks like it was also filed by you) covers allowing custom domains from the install flow, the code for domains.flynn.io won't be particularly helpful.

 However, I'll investigate releasing the code.

**Comment by titanous** [comment]
https://github.com/flynn/flynn-subdomainer
