### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Natsuke** [flynn/flynn#1375]
Starting a new 3 nodes cluster today, have deployed some apps successfuly and another which result in a failing state. Since this fail, got a ```unknown_error: Something went wrong``` while creating or deleting apps.

Here is a [flynn-host collect-debug-info](https://gist.github.com/anonymous/addae51fa11ca8150b67)

Let me know if I can provide you more informations.
Thanks in advance for incoming help.

**Comment by lmars** [comment]
@Natsuke it looks like there is a service discovery issue:

```
15:13:25.529998 heartbeat.go:138: discoverd: heartbeat flynn-host (10.10.8.1:1113) failed: unknown_error: Something went wrong
```

Can you please gist the contents of the following file:

```
/tmp/flynn-host-logs/flynn-etcd-fa0ba973dbb1476986f6e13e8b95d8d9/flynn-etcd-fa0ba973dbb1476986f6e13e8b95d8d9.log
```

**Comment by Natsuke** [comment]
Thanks for fast reply,

here is the log content of [flynn-etcd-fa0ba973dbb1476986f6e13e8b95d8d9.log](https://gist.github.com/Natsuke/b3ec759b22e89fdf2cec)

**Comment by lmars** [comment]
@Natsuke there are a lot of network related errors in the etcd logs, for example:

```
2015/03/30 13:09:06 rafthttp: encountered error reading the client log stream: read tcp 10.10.8.2:2380: use of closed network connection
2015/03/30 13:13:22 etcdhttp: unexpected error: etcdserver: request timed out
2015/03/30 13:13:48 rafthttp: encountered error reading the client log stream: read tcp 10.10.8.3:2380: i/o timeout
2015/03/30 14:13:57 rafthttp: encountered error writing to server log stream: write tcp 10.10.8.3:33279: broken pipe
```

This is then causing service discovery issues, and ultimately leading to components unable to find each other.

Are all your nodes in the same availability zone? etcd is known not to work well when there is potential for high latency between nodes.

**Comment by Natsuke** [comment]
@lmars For now our 3 nodes run on a Proxmox hypervisor on the same machine with these [spec](https://www.ovh.co.uk/dedicated_servers/storage/2014-FS-12T.xml) which is our testing machine before switch to our dev cluster.
We noticed poor i/o performance which maybe cause etcd failure.

**Comment by lmars** [comment]
@Natsuke ok yes, poor i/o performance could indeed cause issues. You may want to consider running a single node Flynn cluster until you have tracked down the i/o issues.

**Comment by Natsuke** [comment]
@lmars Okay i'll give a try. Thanks a lot for time sparing. I'll reopen new issue if we encounter another failure.
