### ISSUE TITLE
flynn log returns with error: resource not found

### ISSUE THREAD

**Issue by rukor** [flynn/flynn#1379]
# flynn log
controller: resource not found

This is for a freshly installed cluster.

**Comment by titanous** [comment]
Can you list the commands that you ran before `flynn log`? Were you in a git repo?

**Comment by rukor** [comment]
flynn key add
flynn create 
flynn env set ...
git push flynn master
flynn log

**Comment by rukor** [comment]
Looking at the controller logs using flynn-host, I see this:

t=2015-03-31T11:05:46+0000 lvl=info msg="request started" component=controller req_id=6dbef22d7ebc4bfea56b403e0c65cc64 method=GET path=/apps/auth-server/log client_ip=86.8.22.221
t=2015-03-31T11:05:46+0000 lvl=info msg="request completed" component=controller req_id=6dbef22d7ebc4bfea56b403e0c65cc64 status=*404* duration=333.848µs

**Comment by kwando** [comment]
I get this error too with the Vagrant box.

````
vagrant box update
vagrant reload --provision
vagrant ssh
vagrant@flynn:~$ flynn-host version
v20150109.0
````

**Comment by titanous** [comment]
@kwando That flynn-host version is *very* old. You need to destroy the box and recreate it after updating.

@rukor What version of flynn-host are you running?

**Comment by kwando** [comment]
Ah, that explains a lot of things. Thanks for the info.

**Comment by rukor** [comment]
```
roland@fly01:~$ flynn-host version
v20150223.0
```

I guess that is old?

**Comment by titanous** [comment]
@rukor correct.

**Comment by rukor** [comment]
Thanks, I'd upgrade it now.

**Comment by rukor** [comment]
please, what is the best way to upgrade flynn-host when installed via the install-flynn script, previously i would just use apt-get from the flynn repo, but now looks lke i have to manually download from the repo. is that right?

**Comment by titanous** [comment]
@rukor #1390 handles clean upgrades.
