### ISSUE TITLE
Start Flynn Layer 1 - connection refused

### ISSUE THREAD

**Issue by tcdev0** [flynn/flynn#1382]
After executing bootstrap command on node1 from install docs (3 nodes on digital ocean)

```sh
$ sudo \
    CLUSTER_DOMAIN=demo.localflynn.com \
    flynn-host bootstrap --min-hosts=3 /etc/flynn/bootstrap-manifest.json
```
 i get the following output:

```sh
$ check online-hosts
$ check online-hosts error: Get http://127.0.0.1:1111/services/flynn-host: dial tcp 127.0.0.1:1111: connection refused
```

[node1 - debug info ](https://gist.github.com/ff40252aece2c510abd5)
[node2 - debug info ](https://gist.github.com/12025596b9a5a719c447)
[node3 - debug info ](https://gist.github.com/b8ebb5b987977b927555)

any ideas?

thanks

**Comment by rukor** [comment]
Have you started `flynn-host` on each node?

**Comment by tcdev0** [comment]
thanks for your reply, i repeated the steps from docs and the previous problem was solved, but a new error occurred.

executing on node1

```sh
$ sudo \
    CLUSTER_DOMAIN="demo.localflynn.com" \
    flynn-host bootstrap --min-hosts=3 /etc/flynn/bootstrap-manifest.json
```

leads to

```sh
$ check online-hosts
$ check online-hosts error: timed out waiting for 3 hosts to come online (currently 1 online)
```

Digital Ocean Droplets
- Private Networking enabled
- DNS set


something i missed ?

**Comment by titanous** [comment]
Please collect debug info on each of the hosts again.

**Comment by tcdev0** [comment]
...

[node1 - debug info ](https://gist.github.com/anonymous/03b1d1f0df545d4c3a29)
[node2 - debug info ](https://gist.github.com/anonymous/1142dbe84b6f96f57ce2)
[node3 - debug info ](https://gist.github.com/anonymous/3e167a7bcf65067fd06d)

**Comment by titanous** [comment]
It looks like there are a bunch of restarts and other issues that may or may not be related, please try resetting and restarting the install process on all nodes:

- `sudo stop flynn-host`
- `sudo rm /var/lib/flynn/host-state.bolt`
- `sudo rm /var/log/upstart/flynn-host.log`
- generate a new discovery token, and follow the instructions from `flynn-host init`

If you're still having trouble after that, collect debug info yet again and we'll start finding the root cause.

**Comment by tcdev0** [comment]
now it works right away, thanks for your quick response.

**Comment by rukor** [comment]
I upgaded and got this error, tried the instructions you gave, same problem:

Logs here:

 [Node 1] (https://gist.github.com/anonymous/91d8b31b0779a2a8ffe4)

**Comment by rukor** [comment]
restarting the box fixed it.
