### ISSUE TITLE
flynn log does not show output of running jobs

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#1383]
I have very simple ruby worker
````ruby
require 'logger'
LOGGER = Logger.new(STDOUT)
loop do
  sleep 5
  LOGGER.info 'heartbeat'
end
````
It is deployed together with a small sinatra app.

````flynn log -f```` does not output anything from the worker. If I push a new version or scale down the job the log (job is stopped) it's log is visible.

**Comment by lmars** [comment]
@kwando Ruby is buffering the small amount of output in memory, and flushing it when the process exits.

You can disable the buffering by setting `STDOUT.sync = true` (see [this post](http://blog.bigbinary.com/2009/07/04/stdout-sync-true-to-flush-output-immediately.html) for an example).

**Comment by kwando** [comment]
ah, thanks =)
added a ```STDOUT.flush``` inside the loop, works now!
