### ISSUE TITLE
dashboard: Changing env vars can revert code changes

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1389]
If I have the dashboard open on my app, deploy my app on the command line via `git push`, and then change an environment variable in the dashboard (without refreshing the page), then my deployed changes will be reverted.

The dashboard / controller API needs to change so that changing env vars always affects the current app release.

**Comment by titanous** [comment]
The correct way to fix this would be CAS via etags, but a quick fix would be to fetch the current release and merge the changed variables into it before saving.
