### ISSUE TITLE
Installer only creates A record for 1 instance in Route53

### ISSUE THREAD

**Issue by jzila** [flynn/flynn#1397]
The installer should create records for all instances in a cluster, instead it only creates an instance for 1. This in effect causes 1 instance to be the load balancer for the cluster.

**Comment by jzila** [comment]
https://github.com/flynn/flynn/blob/fdea6983461009b7139c791b8ef2c337f0659ecd/installer/stack_template.go#L243

Set identifier has to be unique, it's probably only creating 1 because the others fail due to duplication errors. Should be `frontend{{$i}}`

**Comment by titanous** [comment]
Looks like that whole record needs to be repeated for each instance.

**Comment by jzila** [comment]
Which it should be thanks to the range loop above.

**Comment by titanous** [comment]
Ah, that looks like another typo, there should be a separate range so that only one record group is added.
