### ISSUE TITLE
Add default static buildpack

### ISSUE THREAD

**Issue by dhrp** [flynn/flynn#1398]
It would be great to have a default static buildpack, so static apps can easily be deployed too.

**Comment by dhrp** [comment]
I've tried the following two candidates, which turned up after some google searches.

- https://github.com/pearkes/heroku-buildpack-static (using apache 2.2)
- https://github.com/cloudfoundry-incubator/staticfile-buildpack (using nginx 1.7)

I like the cloudfoundry one, which is based on nginx. It requires you to put a 'Staticfile' file in the root of your app, so the system can detect it's a static app (which is preferred over detecting index.html). 

Furthermore it allows setting some (basic) directives in this file. I think it's done pretty cleverly

**Comment by titanous** [comment]
I just tried out the staticfile buildpack, and it looks good. I'll go ahead and add it. Thanks for looking into this!
