### ISSUE TITLE
Provide instructions on how to run behind a reverse proxy

### ISSUE THREAD

**Issue by rukor** [flynn/flynn#1400]
Currently, the instructions are to have A DNS records for all hosts, which means they have to be public facing as the CLI/dashboard doesnt work otherwise.

I would like to have a setup, where I have a reverse proxy in front acting as a bridge between the outside world and the internal flynn cluster. That way if a node goes down, I am not at the mercy of the DNS round robin (ie the reverse proxy will catch it earlier and ensure requests are not directed to it). 

Also because I normally prefer to do SSL termination there.

I would hope that this is possible as it has been a bit problematic for me to get this to work properly.

Thanks,
R

**Comment by lmars** [comment]
@rukor it is certainly possible to use an external load balancer, but given you want it to be external to the Flynn cluster it really depends on your infrastructure.

For example, if you are using AWS you can use either an ELB or Route53 with TCP health checks.

You could also run HAProxy in front of the cluster and use the [check option](http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#check) to only route requests to healthy hosts and do SSL termination. The issue then is this instance becomes a single point of failure, and if it goes down your entire cluster is inaccessible.
