### ISSUE TITLE
After leaving the cluster to run for two days, flynn-host ps returns nothing

### ISSUE THREAD

**Issue by rukor** [flynn/flynn#1405]
I cant run flynn create either, it returns with: httpclient: unexpected status 503.

[Debug info 1](https://gist.github.com/anonymous/60b569d960e7739db830)
[Debug info 2](https://gist.github.com/anonymous/4780e745f25b528ac369)

**Comment by titanous** [comment]
How many nodes in the cluster?

**Comment by rukor** [comment]
5

**Comment by titanous** [comment]
Okay, this looks like "cluster collapse" due to a combination of issues with etcd, discoverd, and flynn-host that I'm currently working on resolving. #1373 will resolve this.

**Comment by rukor** [comment]
@titanous Thanks. Please how do I restart the cluster without loosing data under this scenario?

**Comment by titanous** [comment]
If the postgres server is still running, you should find it and take a dump of your app databases directly. After doing that, you can try stopping flynn-host on all nodes and then starting it on all nodes. If that doesn't resolve the issue, a clean re-install is probably the next step.

**Comment by rukor** [comment]
OK. Thanks.
