### ISSUE TITLE
SSL Certificate and CORS

### ISSUE THREAD

**Issue by arekkas** [flynn/flynn#1411]
When setting up Flynn, you're being asked to download and install the certificate. IIRC this only works on per-browser basis. Whenever another client (different browser instance) logs into the dashboard, he'll see a warning:

![flynn1](https://cloud.githubusercontent.com/assets/3372410/7004132/c4ee5906-dc66-11e4-952b-94790e5a3252.PNG)

Once added, he can sign in and proceed to the apps tab, but he won't see any:

![flynn2](https://cloud.githubusercontent.com/assets/3372410/7004139/d5352704-dc66-11e4-90f1-e16d146ef9ae.PNG)

This is because the security exception applies only for this specific domain.

I suggest to add a warning to the dashboard which instructs the user to download the certificate if network calls are blocked due to insecure responses.

If anyone can hint me at the proper direction for this, I'd  be happy to create a PR.

**Comment by jvatic** [comment]
Visiting the HTTP version should walk you through installing the certificate which will bypass this issue. 

We should make a request to the `/ping` endpoint of the controller using both HTTP and HTTPS if any request to the controller fails with a status of `0` (all requests to the controller go through [here](https://github.com/flynn/flynn/blob/master/dashboard/app/lib/javascripts/dashboard/client.js#L64-L72)). If they both fail, a `SERVICE_UNAVAILABLE` event should be fired ([example](https://github.com/flynn/flynn/blob/master/dashboard/app/lib/javascripts/dashboard/config.js#L21-L24)). If HTTP succeeds and HTTPS fails, we should redirect the user to the HTTP version for certificate install instructions (we should add an event for this, say `HTTPS_UNAVAILABLE`, and handle the redirect [here](https://github.com/flynn/flynn/blob/master/dashboard/app/lib/javascripts/dashboard/main.js#L95)).

I think we'll also need to update the logic for detecting if the certificate needs installing as it [currently assumes if it can get the config over HTTPS the cert is installed](https://github.com/flynn/flynn/blob/master/dashboard/app/lib/javascripts/dashboard/main.js#L97-L103), it should use the controller's `/ping` endpoint using HTTPS instead.

@arekkas let me know if you're still up for creating a PR for this / if you have any questions.

**Comment by arekkas** [comment]
I can try, probably need some time to get into React tho. You could point me at the files I should look at

**Comment by jvatic** [comment]
The files linked in my previous comment should be all you need for this, and as none of them are views you don't need to be familiar with React :wink: [marbles-js](https://github.com/jvatic/marbles-js/tree/e11f4b306d0bddac25a768fcee1a3092bfa12700) is used in these places though, so you may wish to look at the docs for that.

**Comment by jvatic** [comment]
Oh, and for [dashboard](https://github.com/flynn/flynn/tree/master/dashboard) development, it's best to run it standalone on your computer (see [here](https://github.com/flynn/flynn/blob/master/dashboard/config.go#L28) for the various ENV vars you'll need). Replace/add `dashboard/bindata.go` with [this](https://gist.github.com/jvatic/81774775199a7225acb1) and compile assets by running `bundle exec rake compile` in [the app directory](https://github.com/flynn/flynn/tree/master/dashboard/app).

**Comment by arekkas** [comment]
Thanks, I'll give it a shot :)

**Comment by jvatic** [comment]
Great, let us know how it goes :)

**Comment by arekkas** [comment]
is there by any chance a vagrantfile for the dashboard app? the ruby env doesn't work on windows because I could not figure out how to install puma.

**Comment by jvatic** [comment]
@arekkas puma isn't actually used. If removing it from the Gemfile doesn't get it working, you could try running it in the [dev box](https://github.com/flynn/flynn/blob/master/Vagrantfile).

**Comment by arekkas** [comment]
removing it did the trick. should I add this to the commit?

**Comment by jvatic** [comment]
I've removed it in #1432

**Comment by arekkas** [comment]
Any idea why the asset is missing?

```
D, [2015-04-09T17:17:06.063948 #1468] DEBUG -- : Compiled dashboard/main.js  (0ms)  (pid 1468)
rake aborted!
StaticSprockets::App::AssetServer::SprocketsHelpers::AssetNotFoundError: "windows-firefox-cert-1.png" does not exist within ["
D:/workspace/go/src/github.com/flynn/flynn/dashboard/app/lib/javascripts", "D:/workspace/go/src/github.com/flynn/flynn/dashboa
rd/app/lib/stylesheets", "D:/workspace/go/src/github.com/flynn/flynn/dashboard/app/lib/fonts", "D:/workspace/go/src/github.com
/flynn/flynn/dashboard/app/lib/images", "D:/workspace/go/src/github.com/flynn/flynn/dashboard/app/vendor/javascripts", "D:/wor
kspace/go/src/github.com/flynn/flynn/dashboard/app/vendor/stylesheets", "D:/workspace/go/src/github.com/flynn/flynn/dashboard/
app/vendor/fonts", "D:/workspace/go/src/github.com/flynn/flynn/dashboard/app/vendor/images", "C:/Ruby/lib/ruby/gems/2.2.0/bund
ler/gems/marbles-js-e11f4b306d0b/src", "C:/Ruby/lib/ruby/gems/2.2.0/bundler/gems/flynn-dashboard-web-icons-a03e56dbe3dd/assets
", "D:/workspace/go/src/github.com/flynn/flynn/dashboard/app/lib/installer/images"]!
```

**Comment by jvatic** [comment]
You'll need to run `make` within the Vagrant dev box as some shared files are copied over from the installer.

**Comment by arekkas** [comment]
I'm not able to run make:

```
`[ tup ] [37.694s] Executing Commands...
 [                                               ETA~=??? Remaining=126 Active=2                                                ]   0%.tup/tmp/output-17974: Text file busy
tup error: Unable to unlink sub-process output file.
 *** Command ID=17974 failed: ./build.sh
 [                                               ETA~=??? Remaining=126 Active=1                                                ]   0%.tup/tmp/output-17984: Text file busy
tup error: Unable to unlink sub-process output file.
 *** Command ID=17984 failed: CGO_ENABLED=0 ../../util/_toolchain/go/bin/go build -installsuffix nocgo -o bin/flynn-postgres -ldflags="-X github.com/flynn/flynn/pkg/version.commit $GIT_COMMIT -X github.com/flynn/flynn/pkg/version.branch $GIT_BRANCH -X github.co
m/flynn/flynn/pkg/version.tag $GIT_TAG -X github.com/flynn/flynn/pkg/version.dirty $GIT_DIRTY" -tags="$GO_BUILD_TAGS"
 [                                               ETA~=??? Remaining=126 Active=0                                                ]   0%
 *** tup: 2 jobs failed.
make: *** [all] Error 1

```

@current master

**Comment by titanous** [comment]
@arekkas I assume this is from within the development VM? Try deleting `.tup` before running it again.

**Comment by arekkas** [comment]
Yup, I did that and also removed the local copy and cloned it again - didn't help. My best guess is some mixup with the windows host. I'll try it on mac now

**Comment by arekkas** [comment]
I was able to run make and bundle exec :) Seems to be a problem with Windows.
However, "localflynn.com" doesn't work. What I did was:

```
host$ git clone https://github.com/flynn/flynn
host$ vagrant up
host$ cd dashboard/app
host$ bundle install
host$ bundle exec rake compile
host$ vagrant ssh
vm$ make
host$ flynn key add
host$ flynn -a dashboard env get LOGIN_TOKEN
host$ open http://dashboard.demo.localflynn.com
```

Should I be running vagrant up from the demo dir instead?

**Comment by arekkas** [comment]
Ok, running it with demo works :)

**Comment by arekkas** [comment]
Ok, I was able to get the local version of flynn running using:

```
$ cd flynn/demo
$ make init
$ make dashboard
```

However I haven't figured out how to make the changes I did visible in the dashboard app. Any tips how to do that?

**Comment by jvatic** [comment]
@arekkas I've [responded in IRC](https://botbot.me/freenode/flynn/2015-04-13/?msg=36486143&page=1).

**Comment by arekkas** [comment]
Thanks! I got to the point where I was able to bootstrap the dev flynn. However, I still haven't figured out how to get the dashboard running locally:

To get things going I did what the docs told me:

```
$ vagrant up
$ vagrant ssh
vm$ make
vm$ scripts/bootstrap-flynn
```

Then I started with a very simple example and tried to add a console.log() here: https://github.com/flynn/flynn/blob/0f4a636e97c4c2538a86bfaa0c0c7b46935bc616/dashboard/app/lib/javascripts/dashboard/main.js#L21

## Via VM

At first I tried to update the dashboard via the VM:

```
vm$ make
vm$ bin/bootstrap-flynn
```

That worked :) However it's pretty resource heavy and takes quite some time for rebuilding.

## Standalone

I wasn't able to build `main.go` nor to use `bin/flynn-dashboard` since the host ist MacOS. What I did was:

```
$ cd dashboard/app
$ bundle exec rake compile
$ cd ../
$ DEFAULT_ROUTE_DOMAIN=dev.localflynn.com:2222 CONTROLLER_DOMAIN=https://controller.dev.localflynn.com CONTROLLER_KEY={{key}} URL=https://controller.dev.localflynn.com SESSION_SECRET=foobar LOGIN_TOKEN={{key}} go run main.go
```

Which resulted in:

```
# command-line-arguments
./main.go:17: undefined: LoadConfigFromEnv
./main.go:18: undefined: APIHandler
```

what is really weird because these packages *should* be available. The flynn source is in: `$GOPATH/src/github.com/flynn/flynn`

Any ideas?

**Comment by arekkas** [comment]
I created a ping method in `client.js`:

```js
    ping: function (protocol) {
        var controllerKey = (Dashboard.config.user || {}).controller_key,
    	    endpoint;

        protocol = protocol === undefined ? 'https' : protocol;
        endpoint = this.endpoints.cluster_controller.substr(0, 5) === "https" ?
           protocol + endpoint.substr(5) :
           protocol + endpoint.substr(4);

	    return this.performRequest('GET', {
            middleware: [
                Marbles.HTTP.Middleware.BasicAuth("", controllerKey)
            ],
            url: endpoint + "/ping"
        });
    },
```

However I am not sure where to trigger this. When triggered from the `run` method in `main.js`, `this.endpoints` as well as `Dashboard.config.user` are still undefined (I guess they're being hydrated later on?).

**Comment by jvatic** [comment]
@arekkas regarding running the dashboard standalone, you'll need to either list all package files in the `go run` command or run `go build` then `./dashboard`.

**Comment by arekkas** [comment]
great, thanks :)
