### ISSUE TITLE
bootstrap failed 

### ISSUE THREAD

**Issue by altV** [flynn/flynn#1415]
sudo CLUSTER_DOMAIN=** flynn-host bootstrap --min-hosts=3 /etc/flynn/bootstrap-manifest.json
sudo: unable to resolve host ip-10-200-128-22
20:31:26.017048 check online-hosts
20:31:26.021445 require-env require-env
20:31:26.021605 gen-random pg-password
20:31:26.022217 gen-random pg-password ee0be2f8f149800c1052bece0dd3a590
20:31:26.022237 run-app postgres
20:31:29.255903 gen-random controller-key
20:31:29.256067 gen-random controller-key 877bda8c8ae080e3d44ad7f45171aaca
20:31:29.256074 gen-random dashboard-session-secret
20:31:29.256101 gen-random dashboard-session-secret ee4896577d9158321e835983736f75de
20:31:29.256105 gen-random dashboard-login-token
20:31:29.256131 gen-random dashboard-login-token 5171688bc9b7da4cfc08681cfbdef37c
20:31:29.256135 gen-random name-seed
20:31:29.256213 gen-random name-seed a1de831061e71ca9d5a2
20:31:29.256218 wait postgres-wait
20:31:34.614995 run-app controller
20:31:38.481692 gen-tls-cert controller-cert
20:31:39.400287 gen-tls-cert controller-cert pin: i1QmOyahDi2M9hjUaS2qb7VtGlaoVhVqd4Jp7L1pAnM=
20:31:39.400330 wait controller-wait
20:31:40.098587 add-app controller-inception
20:31:40.160315 add-app postgres-app
20:31:40.189049 scale-app scheduler-scale
20:31:40.197299 run-app scheduler
20:31:40.841277 deploy-app blobstore
20:31:42.871298 deploy-app router
20:31:44.551499 gen-ssh-key gitreceive-key
20:31:45.185815 deploy-app gitreceive
20:31:45.238412 wait router-wait
20:31:45.926161 add-route gitreceive-route
20:31:45.929072 add-route gitreceive-route error: unknown_error: Something went wrong

**Comment by titanous** [comment]
Please run `flynn-host collect-debug-info` and post the link here.

**Comment by altV** [comment]
node 1, https://gist.github.com/anonymous/4937a50af634e414f92b

node 3, https://gist.github.com/anonymous/fb7bdaf396b4f5fa9724

there were six attempts,
all subsequent displayed different error:
20:38:40.463358 check online-hosts
20:38:40.469382 require-env require-env
20:38:40.469524 gen-random pg-password
20:38:40.470175 gen-random pg-password 2ccf06bc51c1860aa979b474bf79bac9
20:38:40.470246 run-app postgres
20:38:48.221546 gen-random controller-key
20:38:48.221694 gen-random controller-key db91cd302e3ff5da03411834edd08537
20:38:48.221700 gen-random dashboard-session-secret
20:38:48.221738 gen-random dashboard-session-secret db9919f52571bcd49bcd5da2fc90a919
20:38:48.221743 gen-random dashboard-login-token
20:38:48.221770 gen-random dashboard-login-token b22eea0afe607ecbd6dce9321ad03543
20:38:48.221775 gen-random name-seed
20:38:48.221821 gen-random name-seed a786988dc5e80659cb71
20:38:48.221825 wait postgres-wait
20:38:48.224570 run-app controller
20:38:52.292649 gen-tls-cert controller-cert
20:38:53.862250 gen-tls-cert controller-cert pin: 4ZKuXtQvNe9Ysn50g3htAqlBMOMMfEZcYpPoYeRTAdI=
20:38:53.862282 wait controller-wait
20:38:53.866226 add-app controller-inception
20:38:53.869441 add-app controller-inception error: POST http://100.100.21.3:80/apps: httpclient: unexpected status 401

**Comment by titanous** [comment]
I'm going to close this, as I believe it was resolved in IRC.

**Comment by altV** [comment]
yes, thank you
