### ISSUE TITLE
Multiple flynn remotes cause "multiple apps in git remotes" error

### ISSUE THREAD

**Issue by jzila** [flynn/flynn#1419]
I have 2 remotes: "flynn" and "flynn-prod".

Some commands `flynn env` allow operating without specifying an app `flynn -a foo ...`. Other commands return an error: "main.go:266: multiple apps in git remotes". Since `-a foo` is the same on both clusters, nothing is disambiguated by specifying the app, but the command then works.

I'd expect all the commands just to go to the default cluster in .flynnrc, for the app name in the current git tree.

**Comment by geovanisouza92** [comment]
You can override the cluster you talking to with the "-c" flag on flynn command, like:

```sh
$ flynn -c prod env

$ flynn -c stage env
```

**Comment by jzila** [comment]
I know, but that is independent of the issue. The issue is that if I have multiple git remotes, the flynn CLI complains whenever I try to do anything saying "multiple apps in git remotes". Even though the apps have nothing to do with anything when I'm inside the git directory.

**Comment by geovanisouza92** [comment]
As a workaround, I'll recommend you to create apps with different names or let the cli generate random ones.

To fix that I think that we need some tests on [TestCluster suite](https://github.com/flynn/flynn/blob/master/test/test_cli.go#L540) to reproduce and find a way to differentiate between the apps.

One thing that I thought is to have a registry linking git repos with apps, that apparently is not registered anywhere on controller.
