### ISSUE TITLE
Support remote syslog servers

### ISSUE THREAD

**Issue by jschneiderhan** [flynn/flynn#1422]
In our current environment, where we are running Docker containers directly, we use a sidekick container on each machine to ship syslog messages to a remote syslog server (Loggly in our case). After moving to Flynn, we would like to preserve that ability since the searching/visualization/alerting has become an integral part of our workflow.

It would be great if there was a way to hook into the logaggregator to process messages and send them to a remote syslog server. There was mention in the IRC room of log drains possibly being developed. That sounds like the type of thing that would permit this.

One simple solution that could be used in the meantime is to setup a file monitor on the file that the logaggregator dumps snapshots to, although I doubt that will scale very far.

**Comment by temujin9** [comment]
+1: We use a similar setup, and making it an amenity of the cluster itself would be pretty awesome.

**Comment by tombh** [comment]
Would love to see this too

**Comment by siavashs** [comment]
We are also interested in this.

**Comment by ggrochow** [comment]
This would be amazing
