### ISSUE TITLE
Route53 wildcard should be A alias

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1424]
Instead of a CNAME, the installer wildcard Route53 record should be an A record with an ALIAS (health evaluation on) pointing at the domain, this avoids a potential second DNS lookup caused by the CNAME.

**Comment by cancan101** [comment]
An A alias can point to only:
![image](https://cloud.githubusercontent.com/assets/51059/7969308/fcecbd28-0a03-11e5-81d2-c448f9048338.png)

**Comment by titanous** [comment]
Yes, "domain name of a record set in this zone" is what I'm talking about (the non-wildcard domain).
