### ISSUE TITLE
etcd causing high CPU and Disk I/O usage

### ISSUE THREAD

**Issue by geovanisouza92** [flynn/flynn#1426]
I'm running a single flynn host (pseudo cluster) and I'm concerned about the performance of the apps.

Looking at server with nmon, it seems that is a high cpu and disk i/o usage, and the top processes seems to be etcd and discoverd.

Take a look at some [etcd logs](https://gist.github.com/geovanisouza92/9081937ffc1bb92a8101), [discoverd logs](https://gist.github.com/geovanisouza92/0f8382bcaa5f18d90ce5) and [some](http://imgur.com/ojzCKDE) [interesting](http://imgur.com/f2yEH7f) [statistics](http://imgur.com/XkE3JE6) [screenshots](http://imgur.com/sJvE12I) to clear this.

**Comment by titanous** [comment]
Thanks for reporting this! Do you mind grabbing a tcpdump containing the traffic between etcd and discoverd?

Run this for 30s:

```text
sudo tcpdump -i lo "port 2379" -w discoverd.pcap
```

And then compress and upload the file somewhere and post the link here.

**Comment by geovanisouza92** [comment]
Ok, I'll do that tomorrow.

**Comment by geovanisouza92** [comment]
@lmars [discoverd.pcap](https://drive.google.com/file/d/0B_uDk36gNaWFUmhBWkgtMFEyaFE/view?usp=sharing)

**Comment by lmars** [comment]
@geovanisouza92 I haven't used `nmon` before, but from a quick scan of the screenshots, it seems the CPU usage is mainly in i/o wait on the `sda5` device, is `sda5` your swap device?

**Comment by geovanisouza92** [comment]
@lmars No, ```sda5``` is a partition attached on LVM. Swap is a logical volume on it.

```sh

# fdisk -l
Dispositivo Boot  Início   Fim       Blocos    Id  Sistema
/dev/sda1   *     2048     499711    248832    83  Linux
/dev/sda2         501758   83884031  41691137  5   Estendida
/dev/sda5         501760   83884031  41691136  8e  Linux LVM

# pvdisplay 
  --- Physical volume ---
  PV Name               /dev/sda5
  VG Name               main-vg
  PV Size               39,76 GiB / not usable 2,00 MiB
  Allocatable           yes (but full)
  PE Size               4,00 MiB
  Total PE              10178
  Free PE               0
  Allocated PE          10178
  PV UUID               ...

# df
Sist. Arq.                                     1K-blocks    Usado Disponível Uso% Montado em
/dev/mapper/main--vg-root                       36774596 20122356   14761120  58% /
none                                                   4        0          4   0% /sys/fs/cgroup
udev                                             2009476        4    2009472   1% /dev
tmpfs                                             404132      528     403604   1% /run
none                                                5120        0       5120   0% /run/lock
none                                             2020644     7240    2013404   1% /run/shm
none                                              102400        0     102400   0% /run/user
/dev/sda1                                         240972    69248     159283  31% /boot
flynn-default/6a72692863f04a3491d687edc7bb311c  93128064    17152   93110912   1% /var/lib/flynn/volumes/zfs/mnt/6a72692863f04a3491d687edc7bb311c
flynn-default/1c1daf0a2112420aa62bf9845b11fd55  95976064  2865152   93110912   3% /var/lib/flynn/volumes/zfs/mnt/1c1daf0a2112420aa62bf9845b11fd55
flynn-default/f66b7506557a4f3081757428631fec71  93110912        0   93110912   0% /var/lib/flynn/volumes/zfs/mnt/f66b7506557a4f3081757428631fec71

```

**Comment by lmars** [comment]
@geovanisouza92 ok, I cannot see your apps in any of the screenshots, is your application performing badly in anyway?

From what I can see, other than some i/o wait on sda5, your server does not seem to be in bad shape, the load seems normal, system + user CPU usage is low, memory usage is ok.

Is there high latency on the disks?

**Comment by geovanisouza92** [comment]
@lmars I have only 2 apps (4 processes in total, 1 app with 3 processes) and the system seems always busy when I try to "git push flynn master" or "flynn env set ...", in general, each deployment takes 30~50 seconds, and some cases just reach the timeout, but when I take a look at "flynn-host" and kill some frozen jobs, the scheduler seems to dispatch whatever was waiting. I'm concerned that this orchestration issue affect the general performance of the apps.

**Comment by lmars** [comment]
@geovanisouza92 what would be useful is to see some stats during those events, e.g. what is the load at those times, what are the CPUs doing (sys / user / io wait), what processes are consuming resources at those times, what are the disk io latencies?

Something like recording the output of `top` whilst you do a git push would probably be helpful, unless you have better tools available.

**Comment by jzila** [comment]
Here's another repro: https://gist.github.com/jzila/fd23e54a86f88dcd83bd

**Comment by titanous** [comment]
Closing, as we no longer use etcd.

**Comment by ffrouin** [comment]
I still confirm IO issues with latest  etcd-v2.3.0-alpha.1-linux-amd64... moving to consul gave same results without IO issues...

**Comment by titanous** [comment]
@ffrouin this should be discussed upstream, we don't maintained etcd.
