### ISSUE TITLE
script/bootstrap-flynn fails on default vagrant due to missing zfs

### ISSUE THREAD

**Issue by jzila** [flynn/flynn#1436]
Attempting to run `script/bootstrap-flynn` after a clean make on the vagrant box fails:
https://gist.github.com/jzila/69cda9135cb9c165e18d

`/tmp/flynn-host.log`:
https://gist.github.com/jzila/96de95fc0b58d2fba0c8

I fixed it on my vagrant by calling `sudo apt-get install zfs-fuse`.

**Comment by lmars** [comment]
@jzila this is very odd, the `zfs` command should be located at `/sbin/zfs` and installed by the [ubuntu-zfs package](https://github.com/flynn/flynn/blob/master/util/packer/ubuntu-14.04/scripts/install.sh#L182), did you by any chance run `which zfs` when this error happened?

**Comment by jzila** [comment]
I did; the command wasn't found.

**Comment by titanous** [comment]
Is it possible that you are running an old version of the box?

**Comment by jzila** [comment]
I suppose it's possible, but I ran `vagrant box update` and then halted and
brought up the vagrant before working around the issue.

**Comment by jvatic** [comment]
You'd need to run `vagrant destroy` after the update to use the latest image.

**Comment by jzila** [comment]
Well that solves that, thanks.
