### ISSUE TITLE
Document the dashboard development workflow

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1452]
1. launch the vagrant development box (`vagrant up` from the project root)
1. `vagrant ssh`
1. `make`
1. `bootstrap-flynn`
1. `./script/dashboard-dev compile` (repeat this step after every change)
1. `CONTROLLER_KEY="<KEY>" ./script/dashboard-dev run` (see the output of `bootstrap-flynn` for the `CONTROLLER_KEY`)

**Comment by jvatic** [comment]
Draft: https://gist.github.com/jvatic/df346cfdf1632ca0ccd3

**Comment by philiplb** [comment]
On the vagrant box 20160624.1 I had to install some dependencies in order to make "go run compiler.go" work:
```bash
sudo apt-get update
sudo apt-get install nodejs
sudo apt-get install npm
apt-get install ruby-bundler
sudo gem install yajl-ruby
# this one was needed as well and feels hacky
sudo ln -s `which nodejs` /usr/bin/node
```

**Comment by lmars** [comment]
FYI I've added a convenience script in #3024.
