### ISSUE TITLE
Dashboard should show diagnostics.

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#1469]
The Flynn dashboard should display diagnostics / statistics including the following:

**System**
- `uptime` (incl. load)
- `free -m`
- `df` (incl. zfs pools)

**Flynn**
- number of apps running
- number of jobs running
- cluster info

I'm sure there's heaps else to add, but even some basic info would help.

**Comment by philiplb** [comment]
+1 :)
Would be very usefull for a big wall mounted display.

**Comment by kwando** [comment]
Yeah, this info would be very useful to show in the dashboard. Just the basic things like, load avg, memory pressure and disk usage would give you a quick overview of the health of your nodes.

In larger setups you will probably want to add a proper monitoring solution, but for simple setups this would be awesome.
