### ISSUE TITLE
There is some way to deploy from a Dockerfile?

### ISSUE THREAD

**Issue by flaviobarros** [flynn/flynn#1477]
I have an app that i only can deploy from a Dockerfile. I deploy it at dokku-alt. There is some way to do it with flynn?

**Comment by lmars** [comment]
Flynn does not currently build images at runtime using Dockerfiles.

What you can do is build the image locally, push it to a Docker registry and then reference the image in a release.

Here is an example of deploying Redis using an image from the default Docker registry: https://gist.github.com/lmars/fca0f18b4ecd507fb39a

Whilst this workflow works it isn't a particularly good one, and we have plans to improve it (see #1085).

**Comment by flaviobarros** [comment]
Thanks! You are fast...

**Comment by alioygur** [comment]
I think flynn must have this feature.

**Comment by lmars** [comment]
@alioygur you can now deploy Docker images directly, see https://flynn.io/docs/docker

**Comment by alioygur** [comment]
@imars not image from Dockerfile. Like dokku

**Comment by lmars** [comment]
@alioygur if you are using a Dockerfile to develop your app, it is likely that you are also building the image in development (so you know the Dockerfile results in a valid image), so in that case you may as well push the already built image?

Or do you have some other workflow in mind?

**Comment by alioygur** [comment]
Dear I know that.

But this way is harder than with Dockerfile.

Also this way require docker in local.

**Comment by koolay** [comment]
+1

Pushing image to flynn-server is too slow from local.

**Comment by praveenperera** [comment]
+1 

@lmars I want to use a dockerfile to customize the build but I usually don't use docker in development. Would be nice to be able to push the dockefile and have it build on the server like dokku.
