### ISSUE TITLE
Docs should talk more about network requirements?

### ISSUE THREAD

**Issue by phildini** [flynn/flynn#1485]
In trying to setup flynn on a digitalocean box running ubuntu 14.04, I ran into some trouble using `ufw` and flynn in tandem.

`ufw` is a fairly common technology on ubuntu for managing firewalls, and I think a lot of more junior systems people (like me!) would appreciate better documentation. 

I had trouble getting flynn to bootstrap until I opened port 1111, ran `sudo ufw allow in on flynnbr0`, and did this: https://bugs.launchpad.net/ubuntu/+source/ufw/+bug/573461/comments/3

I'm not sure exactly which incantation fixed the problem, but it would be awesome if the docs could link to an FAQ about the full network requirements.

Thanks so much for what you're doing!

**Comment by balasan** [comment]
@phildini any chance you can share your complete ufw settings? i'm still having problem w postgres connection after the edits you mentioned

12:45:24.851568 wait postgres-wait
12:47:25.072044 wait postgres-wait error: bootstrap: timed out waiting for http://postgres-api.discoverd/ping, last response "Get http://postgres-api.discoverd/ping: dial tcp: lookup postgres-api.discoverd: no such host"

**Comment by tyler274** [comment]
+1 for this

**Comment by balasan** [comment]
@tyler274 this did the trick for me:
https://docs.docker.com/installation/ubuntulinux/#enable-ufw-forwarding

**Comment by dottodot** [comment]
+1 for this. Really need some more detailed information on how to setup firewalls as it really not clear how to set internal communication between nodes

**Comment by philiplb** [comment]
Maybe this helps a bit:
https://philiplb.de/flynn/2016/04/19/flynn-ufw/

**Comment by dottodot** [comment]
@philiplb Thanks for that, so is that needed in addition to the firewall I can configure on my cloud hosting

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
