### ISSUE TITLE
`flynn -c CLUSTER ps` breaks with multiple remotes

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1489]
I'm setting the `-c` flag to disambiguate, but it's not working:

```
 ∵ temujin9@takni:~/Projects/Bazaarvoice/flynn-repos/terminus ∴ flynn -c t9-flynn-ci-us-east-1 ps
error: Multiple apps listed in git remotes, please specify one with the global -a option to disambiguate.

Available Flynn remotes:
flynn-ci-us-east-1
t9-flynn-ci-us-east-1
```

Removing one of the remotes patches the problem.

**Comment by lmars** [comment]
@temujin9 Flynn looks at the remotes to determine which application you want to interact with, but it doesn't know which app belongs to which cluster, so it cannot disambiguate, hence the error.

One way to fix this is to namespace the remote name like `cluster-name:app-name`, but I wonder whether we should stop using the remote and consider alternatives, for example:

* create a Flynn specific file (e.g. `.flynn/config`)
* keep a mapping of directory -> config in `~/.flynnrc`

Any thoughts on that?

**Comment by titanous** [comment]
I think we can fix this by filtering the apps picked up from remotes when a cluster is specified explicitly. The workaround is to specify a remote name with `-a`.

**Comment by lmars** [comment]
@titanous I was clearly wrong, next time I will actually look at the code :grin:

**Comment by temujin9** [comment]
Unfortunately, this still happens with the latest build:

```
 ∵ temujin9@takni:~/Projects/Bazaarvoice/flynn-repos/terminus ∴ flynn -c flynn-ci-us-east-1 ps
error: Multiple apps listed in git remotes, please specify one with the global -a option to disambiguate.

Available Flynn remotes:
flynn-ci-us-east-1
t9-flynn-ci-us-east-1
```

There is no "global -a option" I can throw from the command I am running. These are both Flynn clusters, with remotes named after the cluster they address. I'm not certain why the git remotes are even involved here, as I'm just running a `ps` command, which shouldn't care about my local git config at all.

**Comment by titanous** [comment]
@temujin9 Using master?

> There is no "global -a option" I can throw from the command I am running.

For example: `flynn -a flynn-ci-us-east-1 ps`

>  I'm not certain why the git remotes are even involved here, as I'm just running a ps command, which shouldn't care about my local git config at all.

The CLI uses the git remotes to figure out which app/cluster to talk to if an app isn't specified explicitly. The change I just added should filter the remotes when the cluster is specified explicitly, which should allow the command that you are trying.

**Comment by temujin9** [comment]
@titanous Yes, using updated `flynn` binary as well as newly built `flynn-host`s.

`flynn-ci-us-east-1` is not the app name, though. It works, but I'll be damned if I understand why.

**Comment by temujin9** [comment]
(To clarify `flynn-ci-us-east-1` is the _cluster_ name, so I would expect the command to be `flynn -c flynn-ci-us-east-1 ps`.)

**Comment by titanous** [comment]
@temujin9 The `-a` flag matches against the remote name first, and then then app name if there are no matches. Can you construct an example set of remotes and cluster configuration that triggers this message on master? I put together one and fixed it with this patch, but clearly didn't fix it completely.

**Comment by temujin9** [comment]
That works, it just doesn't make much sense to me. "remote name" and "application name" seem like two wholly disparate concepts.

So: code functions as described, I'm just at a loss for why the `-a` flag does what it does there.

**Comment by titanous** [comment]
Hmm, this behavior is taken from the Heroku CLI, and it makes sense when you have multiple apps spread across multiple clusters as it saves you from specifying the app name *and* the cluster name (since they are both taken from the remote).

The patch I pushed was supposed to make `-c` work as you were using it, so if it still doesn't work, that's a bug and I'd like to fix it. I just need a `.flynnrc` and `git remote -v` that triggers the issue so that I can fix the code.

**Comment by temujin9** [comment]
Ah, okay. Weird, but at least the legacy behavior makes a little more sense.

`git remote -v`:
```
flynn-ci-us-east-1      ssh://git@flynn-ci-us-east-1.nexus.bazaarvoice.com:2222/terminus.git (fetch)
flynn-ci-us-east-1      ssh://git@flynn-ci-us-east-1.nexus.bazaarvoice.com:2222/terminus.git (push)
origin  git@github.com:bazaarvoice/terminus.git (fetch)
origin  git@github.com:bazaarvoice/terminus.git (push)
t9-flynn-ci-us-east-1   ssh://git@t9-flynn-ci-us-east-1.nexus.bazaarvoice.com:2222/terminus.git (fetch)
t9-flynn-ci-us-east-1   ssh://git@t9-flynn-ci-us-east-1.nexus.bazaarvoice.com:2222/terminus.git (push)
```

`.flynnrc`:
```
default = "t9-flynn-ci-us-east-1"

[[cluster]]
  Name = "t9-flynn-ci-us-east-1"
  GitHost = "t9-flynn-ci-us-east-1.nexus.bazaarvoice.com:2222"
  URL = "https://controller-static.t9-flynn-ci-us-east-1.nexus.bazaarvoice.com"
  Key = "REMOVEDKEYHERE"
  TLSPin = "REMOVEDPINHERE"

[[cluster]]
  Name = "flynn-ci-us-east-1"
  GitHost = "flynn-ci-us-east-1.nexus.bazaarvoice.com:2222"
  URL = "https://controller-static.flynn-ci-us-east-1.nexus.bazaarvoice.com"
  Key = "REMOVEDKEYHERE"
  TLSPin = "REMOVEDPINHERE"
```

**Comment by titanous** [comment]
@temujin9 Are you sure you are using master? I just tested with the remotes and config you provided and my patch appears to work (specifying `-c` sends the command to the expected cluster/app).

**Comment by temujin9** [comment]
Ah, yeah. I was using the public build, assuming it had caught up to master.

Privately built flynn works correctly, now.
