### ISSUE TITLE
Slug download errors should be more precise

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1490]
If a slug fails to download for any reason (including a missing `SLUG_URL` env var), the same error is reported:

``` text
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

The error should describe the problem instead of passing along the gzip/tar errors from getting an EOF.

**Comment by huhaodong** [comment]
So the error ,unexpected end of file , just means cannot download the env?

**Comment by titanous** [comment]
Slugs are now downloaded by flynn-host so detailed errors will show up as the job failure message now.
