### ISSUE TITLE
Resource specification

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1496]
Job resource limits are currently either non-existent or hard-coded (e.g. [available memory](https://github.com/flynn/flynn/blob/master/host/libvirt_lxc_backend.go#L567), [available CPUs](https://github.com/flynn/flynn/blob/master/host/libvirt_lxc_backend.go#L568), [max fd and processes](https://github.com/flynn/flynn/blob/master/host/containerinit/init.go#L416-L419)).

Expanding on #1230, it should be easy for users to specify values for resource limits, including (but not limited to):

* available memory
* available swap
* available CPUs
* CPU time (either hard limit or relative share)
* block I/O time (either hard limit or weighted)
* max file descriptor
* max number of processes

As well as providing a hard upper limit, it would also be useful to provide similar values which can be used by the scheduler to decide where to place jobs based on available resources across the cluster (and also act as a soft limit for `rlimit` style limits).

With this in mind, I propose a structure similar to the [Kubernetes Resource Specification](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/resources.md#resource-specifications):

```go
type Spec struct {
	// Request is the amount of resource a job expects to consume, so the
	// job should only be placed on a host with at least this amount of
	// resource available, and once scheduled this amount of resource
	// should then be unavailable on the given host.
	Request int64

	// Limit is an upper limit on the amount of resource a job can consume,
	// the outcome of hitting this limit being implementation defined (e.g.
	// a system error, throttling, catchable / uncatchable signals etc.)
	Limit int64
}
```

There would be a hard-coded list of resources with default specs, e.g.:

```go
type Type string

const (
	TypeMemory  Type = "memory"
	TypeNumCPUs Type = "num_cpus"
	TypeMaxFD   Type = "max_fd"
	...
)

var Defaults = map[Type]Spec{
	TypeMemory:  {Request: 1*GB, Limit: 2*GB},
	TypeNumCPUs: {Request: 1,    Limit: 2},
	...
}
```

In the controller, resource specs would be declared at the individual process level, e.g.:

```go
type ProcessType struct {
	...
	Resources map[resource.Type]resource.Spec
}
```

and these would be transferred to the job, which the container runner would use to impose the limits:

```go
type Job struct {
	...
	Resources map[resource.Type]resource.Spec
}
```

Hosts would also expose their available resources to aid in scheduling decisions:

```go
type Host struct {
	...
	AvailableResources map[resource.Type]int64
}
```

This description is intentionally vague on the implementation of the limits, but should provide an adequate level of abstraction to accommodate the limits mentioned above.

The ability to handle user-defined limits is not supported, with the idea that tag based filtering will give users enough flexibility to handle custom scheduling decisions.

**Comment by lmars** [comment]
Here is a concrete implementation of this proposal: https://github.com/flynn/flynn/compare/resource-specification

/cc @titanous

**Comment by titanous** [comment]
I believe this was implemented.
