### ISSUE TITLE
Trying to connect to Azure server times out

### ISSUE THREAD

**Issue by m0ngr31** [flynn/flynn#1501]
I've installed Flynn on a Ubuntu 14.04 server running on Azure. I followed all the instructions, deciding to just install one node for testing. Everything seems to have launched fine, and I've setup the DNS records as described, but I can't connect to dashboard.*.*.com, and I get a connection timed out message when I try and run `flynn key add`.

Any suggestions?

quick edit: I also disabled the firewall thinking that might be the issue, but it didn't change anything.

**Comment by lmars** [comment]
The Flynn CLI needs to be able to access the controller at `https://controller.$CLUSTER_DOMAIN` (with `$CLUSTER_DOMAIN` being the value you used to bootstrap the cluster), so if that is timing out it sounds like connections are not being allowed through.

What I would do is first check things work from the cluster itself by running the `flynn cluster add ...` command on the node where Flynn is running, then trying to use the CLI (e.g. `flynn apps`).

If that works on the node, but not externally, then it seems like a routing issue, perhaps an Azure firewall setting?

If that doesn't work then let us know if you get any errors, and run `sudo flynn-host collect-debug-info` to upload some system information and logs to a gist and post the gist link here so we can investigate further.

**Comment by m0ngr31** [comment]
Looks like it was an Azure thing. I had to add 'endpoints' with ports 80, 443, 2222 to my VM. Seems to work now.
