### ISSUE TITLE
Flynn Client CLI should allow and application/job/type to be restarted

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#1504]
It should be possible to request Flynn to restart an application, single job, or all jobs of a specified type.

In doing so Flynn should perform a 'rolling restart' to ensure continued availability. In the case of a single job, the replacement should be started before the original is killed. The same applies when a job type is specified and only one instance exists.

```
# Restart particular job
flynn restart -j metis-43b6976a04624556a11e6f97010caa85

# Restart a whole job type
flynn restart -t web

# Restart entire application
flynn restart-app
```

There should also be a flag `--no-rolling` to prevent rolling for jobs that cannot coexist with multiple instances.

```
# Restart job, without rolling
flynn restart --no-rolling -j metis-43b6976a04624556a11e6f97010caa85

# Equivalent to
flynn scale clock=0 && flynn scale clock=1
```

**Comment by titanous** [comment]
This makes sense, `restart` with no arguments can restart the entire app. A rolling restart *should* just be a matter of subscribing to job events and then killing the existing jobs one by one.

**Comment by thomasfedb** [comment]
I was wary about having no arguments result in a full restart. Sounds like a potential (bad) surprise? In theory it shouldn't be a problem though, I suppose. Am I being over cautious?

If an app has a single instance of a job type, you should start the new job before killing existing ones.

**Comment by titanous** [comment]
As long as it's a rolling restart, it should be safe (I don't think it's any different in safety characteristics or surprises than the proposed `flynn restart-app`)

**Comment by lmars** [comment]
Probably want to handle this similar to the deployer and prefer watching service events for the new jobs, with a fallback to job events. And saying that, this would be trivial if it were just a one-by-one deployment of the same release...

**Comment by thomasmodeneis** [comment]
+1
that would be really nice feature to have

**Comment by titanous** [comment]
FYI the `--no-rolling` flag is not necessary since there is no way to avoid a rolling deploy, processes should implement their own leader election/mutual exclusion system.

**Comment by thomasfedb** [comment]
@titanous how so? Couldn't I simply scale to zero and then scale back up?

**Comment by titanous** [comment]
Yeah, but there's no point since when you deploy a new version of the code it will boot a new process before stopping the old one.

**Comment by thomasfedb** [comment]
Sounds like that would be something that it would be helpful to be able to configure in your Flynnfile. Perhaps I don't ever want more than one `tax_agent` running at once, for example...

**Comment by titanous** [comment]
There's basically no way to do that safely without a ton of overhead and the loss of availability during partitions. Look up "exactly once semantics" for more details. The only way to do this safely is to serialize all transactions through a consistent and partition tolerant register (for example, a Raft cluster or our Postgres appliance).

**Comment by thomasfedb** [comment]
So you're saying "start the new job after the old job has stopped" is harder than "stop the old job after the new job has started"? I find that hard to believe.

**Comment by titanous** [comment]
No, I'm saying that guaranteeing that there is only ever one instance of a process running anywhere in the cluster is a hard problem.

**Comment by thomasfedb** [comment]
Right. So Flynn only promises that the number of a given job will tend towards the desired number?

**Comment by titanous** [comment]
Correct, we provide no exact guarantees about the number of processes of a particular type that are running. The scheduler tries to make sure there are at least the requested number running, but in a variety of scenarios that may not be the case.

**Comment by pltchuong** [comment]
In order to trigger this behavior I have to add a dummy environment variable. I wonder why it's so hard to make it happen from CLI?

**Comment by lmars** [comment]
@pltchuong it's not difficult, someone just needs to make the change, I'd be happy to give you some pointers on what changes are necessary.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
