### ISSUE TITLE
Cluster resurrection is undocumented

### ISSUE THREAD

**Issue by lukerandall** [flynn/flynn#1508]
As per #1187, it would appear that a cluster that dies can be restarted successfully. However, this is not documented anywhere and the naive approach of just restarting the nodes in the cluster and hoping has not proved successful.

Does cluster resurrection currently work, or is it undocumented because it is still a work in progress?

**Comment by titanous** [comment]
Resurrection is partially implemented and should work for basic single-node reboots, but has not been tested more than that. After #1170 lands, I plan to re-evaluate where we are and do extensive testing and fix anything that's broken.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
