### ISSUE TITLE
Build and release pipeline

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1515]
There are some limitations with the current build workflow, for example a lack of support for installing system dependencies (#409) and an inability to perform custom actions both pre, post and during a build.

Before proposing changes, I think it's a good idea to understand what requirements a typical app has of a prospective build & release pipeline.

As a concrete example, here is how I would like Flynn to build one of my Rails applications:
- install system libs at a specific version (e.g. `libssl 1.0.2a`)
- install specific Ruby version (only performed if requested version changes)
- bundle install gems (bundler cache enabled, so adding one gem doesn't re-bundle all gems)
- run unit / integration tests (this involves provisioning resources like a test DB for model tests, memcached for cache tests etc., and ability to skip the step completely for deploying content changes, urgent bug fixes etc.)
- compile assets

This would then create an artifact that I can feed into the following release pipeline to deploy changes to an environment (e.g. staging / production):
- run database migrations (this may involve putting the site into maintenance mode for data integrity)
- rebuild search indexes (conditionally based on whether search related files have changed)
- run cache invalidation / warming tasks
- start / stop relevant jobs (zero downtime)
- run acceptance tests (only in staging, not production)
- notify third-party APIs of deployment

Thoughts are more than welcome on what other steps could be involved.

Here are some suggested changes which could bring us closer to supporting such a workflow:
- Track changes to the root filesystem at each build step, with the final artifact being a union fs of each step, making it easy to use familiar tools such as `apt`, `rpm` etc. for system deps
- Provide a Nix installation to ease installing specific system libs and improve cacheability
- Provide a wrapper around `git push` which supports per-deploy variables (e.g. whether to go into maintenance mode, skip tests etc.)
- Add metadata to aid in determining what code changes have been made

**Comment by temujin9** [comment]
https://github.com/ddollar/heroku-buildpack-apt handles the dependencies problem well. Unfortunately, maintenance appears to have lapsed; I've contacted the owner by email, about transferring the repo to one of our organizations so it can be properly maintained.

**Comment by lmars** [comment]
@temujin9 whilst the apt buildpack does provide options in terms of managing system deps, I think things would be simpler and more flexible if the resulting slug contained any changes to the root filesystem (rather than just changes to `/app`), meaning we wouldn't need to fiddle with things like `LD_LIBRARY_PATH`, and would support arbitrary dependency management (e.g. `apt` / `rpm` / `nix` / `make` etc.)

**Comment by temujin9** [comment]
For those of us with multiple clusters due to separation of concerns, it would be good if the build pipeline included clean ways to push slugs/artifacts between those clusters.

**Comment by temujin9** [comment]
Also: I have written a wrapper around git push for our internal clusters, and will almost certainly be rewriting it in GoLang. When you start needing such a thing, let me know, because I will hopefully have a good framework ready to work with.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
