### ISSUE TITLE
Apps should have a canonical route

### ISSUE THREAD

**Issue by aeneasr** [flynn/flynn#1516]
When adding routes to an app like:
- www.tld.com
- tld.com

there should be a way to specify the canonical route, so all requests get redirected to that domain.
This is extremely useful when dealing with SEO (Search engines hate dupe content).

A way to do this could be: `flynn route add http --canonical www.tld.com`.

**Comment by arekkas** [comment]
If somebody points me in the right direction I'd be happy to try and implement this if desired.

**Comment by titanous** [comment]
I'm not sure about this. The proposed implementation would toggle all of the other routes to a different *type* (a HTTP redirect).

Also, it's not clear that this is actually a problem that we should be solving right now in the router, as we'd also need to open the door to handle HTTPS redirects, HSTS, path rewriting, etc.

**Comment by arekkas** [comment]
> I'm not sure about this. The proposed implementation would toggle all of the other routes to a different type (a HTTP redirect).

The canonical redirect is only required for http, but you are right that other redirects might be required as well. But having both `www.tld.com` and `tld.com` is a common issue so it should be tackled imho.

For now however, the redirect can be solved by adding a URL to the DNS records, which circumvents the necessity to solve this problem from within the app.

**Comment by arekkas** [comment]
Having redirects might be something which could be tackled in #1084

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
