### ISSUE TITLE
Install: Can't remove deployed flynn clusters

### ISSUE THREAD

**Issue by arekkas** [flynn/flynn#1518]
When trying to remove a deployed flynn cluster from the install wizzard, I receive: `unknown field id`

**Comment by jvatic** [comment]
This appears to be due to a typo in [installer/installer.go#L144](https://github.com/flynn/flynn/blob/master/installer/installer.go#L144): `WHERE id == $1` should be `WHERE ID == $1`.

This is fixed in #1506 which should be landing shortly.

**Comment by jvatic** [comment]
closed via #1506
