### ISSUE TITLE
Is it possible to bind app to a specific port

### ISSUE THREAD

**Issue by haifengkao** [flynn/flynn#1522]
I know the tcp route command can bind an app to a random port (3000~3500). 
Is there a way to specify the exact port number in `flynn route add tcp` command?

**Comment by lmars** [comment]
@haifengkao you can't currently bind services to arbitrary external ports, only random ones in the 3000-3500 range.

It is very much possible, we just haven't done the work to make it possible.

I have opened an issue to track the feature: #1524.
