### ISSUE TITLE
Install: Configurable VM disk size

### ISSUE THREAD

**Issue by arekkas** [flynn/flynn#1523]
**Updated issue**

Host disk sizes should be configurable, eg by doing:

```
$ VM_DISK_SIZE=120 flynn install
$ flynn install --vm-disk-size=120
```

---

Deploying often to Flynn causes the host to run out of disk space. As @lmars mentioned, there is a more complex issue regarding ZFS here.

Since this issue makes it impossible to use a cluster for more than a few days, I propose to at least get more time by increasing the disk size, while the bigger problem get's tackled with more time.

The idea is to make the VM disk size configurable by either setting an env var, a parameter or choose a form option from the install ui.

```
$ VM_DISK_SIZE=120 flynn install
$ flynn install --vm-disk-size=120
```

**Comment by arekkas** [comment]
Side note: @lmars mentioned that restarting the host VM might cause issue with Flynn. That makes it impossible to scale the disk by creating a snapshot.

**Comment by arekkas** [comment]
Note: There probably should be a minimum, like 50GB.

**Comment by kwando** [comment]
IMHO increasing disk size is the wrong thing to do here. If anything I propose to set the disk space even lower so that this issue becomes more urgent to fix properly =)

**Comment by arekkas** [comment]
Just as a quick fix until the issue is resolved.

**Comment by kwando** [comment]
A quick fix would be pasting a command here that we can run when we find ourself out of disk space.

**Comment by arekkas** [comment]
@lmars what do you think? A one off cmd would indeed be more useful

**Comment by titanous** [comment]
A component of this fix is using a separate EBS volume (AWS) or sizing the sparse file (DigitalOcean). See also #1189.

**Comment by lmars** [comment]
The ZFS backing file will now default to 70% of available space (see #1528), which should stop the host from running out of disk space.

That being said, I still think it is reasonable to be able to specify disk sizes when using `flynn install`.

**Comment by arekkas** [comment]
Unfortunately, this isn't solved yet:

```
remote: Build failed: exec: job exited with status 1        
remote: mkdir: cannot create directory '/tmp/cache/pip': No space left on device  
```

**Comment by arekkas** [comment]
I'll keep the cluster alive so we can do some debugging
