### ISSUE TITLE
router: Support binding TCP services to specific ports

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1524]
I should be able to add a TCP route which binds to a specific port, for example:

```
$ flynn route add tcp --service mail-server --port 25
```

**Comment by temujin9** [comment]
+1

I need this to make https://github.com/lmars/flynn-webhook-deploy work with a private cluster.

**Comment by jzila** [comment]
Can this not be done by `--tcp-range-start` and `--tcp-range-end` to the desired port?

**Comment by lmars** [comment]
@jzila those flags control the pool of ports the router will currently use to assign ports to TCP services, so you can alter that pool, but the router will still give out ports in that pool randomly, whereas I would like to assign specific ports to my services.

**Comment by jzila** [comment]
Right, but if your pool has a size of 1, doesn't that make it deterministic?

**Comment by lmars** [comment]
@jzila sure, but I don't really want to have to make the decision of what port I will be using at bootstrap time, and I may also want to run multiple TCP services (e.g. in my mail server example, I may want ports 25, 110, 143 etc.)

**Comment by jzila** [comment]
@lmars fair enough, makes sense.
