### ISSUE TITLE
Ubuntu installation script assumes "yes" to prompt on end of input

### ISSUE THREAD

**Issue by MarkusMattinen** [flynn/flynn#1542]
Steps to reproduce:
1. Download installation script from https://dl.flynn.io/install-flynn, and run it with --clean or --remove.
2. Get asked for confirmation "Are you sure this is what you want?"
3. Press ctrl-d or don't have a terminal.

Expected result: script should probably assume "no" and exit if --yes parameter was not used.
Actual result: script proceeds with removal even without --yes parameter.

**Comment by lmars** [comment]
@MarkusMattinen this will be fixed in the next release (see #1543), thanks for pointing this out!
