### ISSUE TITLE
No hosts found when pushing to Flynn

### ISSUE THREAD

**Issue by shideneyu** [flynn/flynn#1545]
I've setted up my app correctly, I got it up and running, and even succeded deploying my app using flynn, twice.

However, the third time that I tried to deploy, I run into the following issue:

    ➜  webscrap_master_service git:(master) git push flynn master                                         
    Counting objects: 11, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (6/6), done.
    Writing objects: 100% (6/6), 582 bytes | 0 bytes/s, done.
    Total 6 (delta 4), reused 0 (delta 0)
    -----> Building webscrap...
    -----> Fetching custom buildpack
    -----> Ruby app detected
    -----> Compiling Ruby/Rails
    -----> Using Ruby version: ruby-2.1.2
    -----> Installing dependencies using 1.9.6
           Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
           Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
           Using CFPropertyList 2.3.1
           Using i18n 0.7.0
           Using rake 10.4.2
           Using json 1.8.2
           Using minitest 5.6.1
           Using thread_safe 0.3.5
           Using builder 3.2.2
           Using erubis 2.7.0
           Using mini_portile 0.6.2
           Using rack 1.6.0
           Using mime-types 2.5
           Using arel 6.0.0
           Using hitimes 1.2.2
           Using coffee-script-source 1.9.1.1
           Using execjs 2.5.2
           Using thor 0.19.1
           Using commonjs 0.2.7
           Using connection_pool 2.2.0
           Using daemons 1.2.2
           Using unf_ext 0.0.7.1
           Using excon 0.45.3
           Using multipart-post 2.0.0
           Using formatador 0.2.5
           Using net-ssh 2.9.2
           Using multi_json 1.11.0
           Using ipaddress 0.8.0
           Using inflecto 0.0.2
           Using hike 1.2.3
           Using tilt 1.4.1
           Using libv8 3.16.14.7
           Using net-http-digest_auth 1.4
           Using net-http-persistent 2.9.4
           Using ntlm-http 0.1.1
           Using webrobots 0.1.1
           Using pg 0.18.1
           Using bundler 1.9.6
           Using rails_serve_static_assets 0.0.4
           Using rails_stdout_logging 0.0.3
           Using redis 3.2.1
           Using ref 1.0.5
           Using rubyzip 1.1.7
           Using sass 3.2.19
           Using temple 0.7.5
           Using fission 0.5.0
           Using tzinfo 1.2.2
           Using nokogiri 1.6.6.2
           Using rack-test 0.6.3
           Using puma 2.11.2
           Using rack-protection 1.5.3
           Using mail 2.6.3
           Using timers 4.0.1
           Using coffee-script 2.4.1
           Using uglifier 2.7.1
           Using figaro 1.1.1
           Using less 2.6.0
           Using unf 0.1.4
           Using faraday 0.9.1
           Using net-scp 1.2.1
           Using sprockets 2.12.3
           Using redis-namespace 1.5.2
           Using rails_12factor 0.0.3
           Using activesupport 4.2.1
           Using loofah 2.0.1
           Using therubyracer 0.12.2
           Using celluloid 0.16.0
           Using slim 3.0.3
           Using domain_name 0.5.24
           Using fog-core 1.30.0
           Using sinatra 1.4.6
           Using rails-deprecated_sanitizer 1.0.3
           Using globalid 0.3.5
           Using activemodel 4.2.1
           Using rails-html-sanitizer 1.0.2
           Using sidekiq 3.3.4
           Using http-cookie 1.0.2
           Using fog-xml 0.1.2
           Using fog-json 1.0.1
           Using fog-local 0.2.1
           Using fog-vmfusion 0.1.0
           Using rails-dom-testing 1.0.6
           Using activejob 4.2.1
           Using activerecord 4.2.1
           Using fog-brightbox 0.7.1
           Using fog-sakuracloud 1.0.1
           Using fog-serverlove 0.1.2
           Using fog-softlayer 0.4.5
           Using fog-storm_on_demand 0.1.1
           Using fog-atmos 0.1.0
           Using fog-aws 0.1.2
           Using fog-ecloud 0.1.1
           Using fog-powerdns 0.1.1
           Using fog-profitbricks 0.0.2
           Using fog-radosgw 0.0.4
           Using fog-riakcs 0.1.0
           Using fog-terremark 0.1.0
           Using fog-voxel 0.1.0
           Using actionview 4.2.1
           Using mechanize 2.7.3
           Using actionpack 4.2.1
           Using fog 1.29.0
           Using swiffer 1.1.9
           Using actionmailer 4.2.1
           Using railties 4.2.1
           Using less-rails 2.7.0
           Using sprockets-rails 2.2.4
           Using coffee-rails 4.0.1
           Using jquery-rails 4.0.3
           Using rails 4.2.1
           Using sass-rails 4.0.5
           Using slim-rails 3.0.1
           Using twitter-bootstrap-rails 3.2.0
           Bundle complete! 25 Gemfile dependencies, 111 gems now installed.
           Gems in the groups development and test were not installed.
           Bundled gems are installed into ./vendor/bundle.
           Bundle completed (1.14s)
           Cleaning up the bundler cache.
           Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
    -----> Preparing app for Rails asset pipeline
           Running: rake assets:precompile
           Asset precompilation completed (2.89s)
           Cleaning assets
           Running: rake assets:clean
           
    -----> Discovering process types
           Procfile declares types -> web, worker
           Default process types for Ruby -> rake, console, web, worker
    -----> Compiled slug size is 53M
    remote: Build failed: exec: job exited with status 23
    To ssh://git@services.textmaster.com:2222/webscrap.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'ssh://git@services.textmaster.com:2222/webscrap.git' 

I retried again, without any further modification, and now I got a new error:

	➜  webscrap_master_service git:(master) git push flynn master
	Counting objects: 11, done.
	Delta compression using up to 8 threads.
	Compressing objects: 100% (6/6), done.
	Writing objects: 100% (6/6), 582 bytes | 0 bytes/s, done.
	Total 6 (delta 4), reused 0 (delta 0)
	-----> Building webscrap...
	remote: Build failed: exec: no hosts found
	To ssh://git@services.textmaster.com:2222/webscrap.git
	 ! [remote rejected] master -> master (pre-receive hook declined)
	error: failed to push some refs to 'ssh://git@services.textmaster.com:2222/webscrap.git'

Here is my debug information link:  https://gist.github.com/60ebe72ee3fc6a54ec2f 

So, I can't can't deploy my new commits using flynn, because of those errors.
Thanks you

PS: Here is the custom buildpack, nothing fancy (upgrading Bundler): https://github.com/gottfrois/heroku-buildpack-ruby 

PS2: I also got the logs of the second time that I've succeeded in deploying with Flynn:
https://gist.github.com/shideneyu/7897c1b891973af36dcf

PS3:

    ~$ flynn-host version
    v20150515.0

**Comment by titanous** [comment]
This is a known issue, there are some edge cases around transient etcd failures. #1373 should resolve this.

**Comment by Vaultman** [comment]
I have the same issue. Is there a way how to solve this right now, or do I have to wait weeks/months to #1373 ?

**Comment by shideneyu** [comment]
The only solution is to destroy your server and rebuild it from scratch, because this issue means that your cluster **is dead**. This is not the only issue that needs to reinstall your cluster from scratch.

Due to this, I dropped the possibility of using Flynn for a big project. Flynn is not reliable for multiple critical issues including this one.

Here is a step by step guide:

#### Dumping your PG Database

Connect to one of the nodes of the server in `ssh`

In your local machine, get the requested data to connect to the PG database:

    flynn env get PGDATABASE
    flynn env get PGUSER
    flynn env get PGPASSWORD

In one of the remote nodes, run the following commands to get the IP address on which the PG Server is accessible:

    ip_addr=`ifconfig flynnbr0 | grep "inet " | awk -F'[: ]+' '{ print $4 }'`
    curl http://$ip_addr:1111/services/postgres/leader

This should gets returns a JSON file. Get the value of the `addr` key. We will refer to it in the next command as the var `PGADDR`

Then, still on the node's console, dump the database:

    pg_dump -h PGADDR -d PGDATABASE -U PGUSER -f dump.sql

Enter the password that we retrieved a few steps ago and that will be all, the dump is now in `dump.sql`. (export it to your own machine by doing `cat dump.sql` and copy paste it).

#### Reinstalling Flynn

On each of your nodes, run those commands

    curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn
    sudo bash /tmp/install-flynn --clean

And you need to follow this guide back: https://flynn.io/docs/installation
