### ISSUE TITLE
Creating a single worker creates two workers

### ISSUE THREAD

**Issue by shideneyu** [flynn/flynn#1555]
Hi,

I cannot create a single worker (for Sidekiq / Redis background jobs ).

    ➜  webscrap_master_service git:(master) ✗ flynn scale worker=1
    scaling worker: 0=>1

    15:30:07.868 ==> worker ip172300162-493b9fe52370413395d8548fc1527ffc starting
    15:30:08.110 ==> worker ip172300162-8ed3124c9aa8492c91d3e575ef11cffd starting
    15:30:08.259 ==> worker ip172300162-493b9fe52370413395d8548fc1527ffc up

    scale completed in 478.673701ms

I need a single worker, not two. Because each of my jobs need to fetch a file which is located inside the hard drive of the current job that is not persisted across other nodes.

Debug info: https://gist.github.com/543c54ca5613c8d92bea
 
I have a cluster of three nodes.

Thanks you

**Comment by titanous** [comment]
This is #1182. It will be fixed by #1484.
