### ISSUE TITLE
router api requires no auth and binds to public ip address

### ISSUE THREAD

**Issue by ssendev** [flynn/flynn#1562]
with a default ubuntu install everyone can create, delete routes and change certificates

**Comment by titanous** [comment]
We need to access the router API from other nodes in the cluster, so it needs to be accessible via LAN (the discoverd/etcd/flynn-host APIs are all set up this way as well). The correct solution is to enable a firewall as documented in the install instructions. 

After looking at the install instructions closer, it seems we can be more explicit about an external firewall being required for security. I'll send a PR shortly with a clarifying sentence.

**Comment by ssendev** [comment]
i just checked the vagrant image to get a firewall config i could use but there are only the default rules. which i guess is not that important since the virtual machine dons't forward ports. the digital ocean installer appears to set firewall rules, but in the aws installer i couldn't find anyting firewall related maybe its's already in the base image or i missed it.

**Comment by titanous** [comment]
The AWS installer uses a security group to firewall: https://github.com/flynn/flynn/blob/2a16a7f46eff77f2501bd3b13b4116537e9a8e48/installer/stack_template.go#L128-L184
