### ISSUE TITLE
Failed to decode snapshot.json

### ISSUE THREAD

**Issue by Vaultman** [flynn/flynn#1564]
Hi, when I try to install or update Flynn (even on a fresh box), I get this error:

`11:44:32.180052 host.go:133: tuf: failed to decode snapshot.json: expired at 2015-06-01 06:04:27 +0000 UTC`

right after installer runs this command:

`===> 11:44:31.948 running "/usr/local/bin/flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin"`

Should I do something to fix this?

Thanks

**Comment by titanous** [comment]
Sorry about that, it should be working now.

**Comment by Vaultman** [comment]
Awesome, thanks.
