### ISSUE TITLE
Clean up old slugs stored in Postgres

### ISSUE THREAD

**Issue by arekkas** [flynn/flynn#1569]
When running into #1565 I also noticed, that Postgres was already requiring 13GB of space:

```
$ df -h
flynn-default/e7b868542018481db0782126697edfb6   34G   13G   21G  39% /var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6
```

```
$ ls /var/lib/flynn/volumes/zfs/mnt/e7b868542018481db0782126697edfb6
base    pg_clog      pg_hba.conf    pg_logical    pg_notify    pg_serial     pg_stat      pg_subtrans  pg_twophase  pg_xlog               postgresql.conf  postmaster.pid
global  pg_dynshmem  pg_ident.conf  pg_multixact  pg_replslot  pg_snapshots  pg_stat_tmp  pg_tblspc    PG_VERSION   postgresql.auto.conf  postmaster.opts
```

@lmars pointed out that this could be due to old slugs not being cleaned up.

Without cleaning up Postgres, every host is going to run into space problems at some point in time.

**Comment by arekkas** [comment]
@lmars it looks like you've already solved that [here](https://github.com/flynn/flynn/blob/d1c5b646ce2ac893618cb2d874fe83066fcd935b/controller/worker/app_deletion/app_deletion.go#L78-L81), if so, thanks! :)

**Comment by arekkas** [comment]
From my observations it does not seem to be fixed on `v20150603.0`. I've added and removed deployments, but the disk usage of postgres keeps increasing:

```
# initial state
flynn-default/3dbf9981ed5a4aabb74b3a9000a31a4c   34G   60M   34G   1% /var/lib/flynn/volumes/zfs/mnt/3dbf9981ed5a4aabb74b3a9000a31a4c
# deployed go app and mongodb docker image
flynn-default/3dbf9981ed5a4aabb74b3a9000a31a4c   34G  225M   34G   1% /var/lib/flynn/volumes/zfs/mnt/3dbf9981ed5a4aabb74b3a9000a31a4c
# deployed app via go buildpack
flynn-default/3dbf9981ed5a4aabb74b3a9000a31a4c   34G  298M   34G   1% /var/lib/flynn/volumes/zfs/mnt/3dbf9981ed5a4aabb74b3a9000a31a4c
# removed all apps
flynn-default/3dbf9981ed5a4aabb74b3a9000a31a4c   34G  298M   34G   1% /var/lib/flynn/volumes/zfs/mnt/3dbf9981ed5a4aabb74b3a9000a31a4c
# deployed go app again
flynn-default/3dbf9981ed5a4aabb74b3a9000a31a4c   34G  344M   34G   1% /var/lib/flynn/volumes/zfs/mnt/3dbf9981ed5a4aabb74b3a9000a31a4c
# deployed mongodb docker image
flynn-default/3dbf9981ed5a4aabb74b3a9000a31a4c   34G  573M   34G   2% /var/lib/flynn/volumes/zfs/mnt/3dbf9981ed5a4aabb74b3a9000a31a4c
# removed all
flynn-default/3dbf9981ed5a4aabb74b3a9000a31a4c   34G  573M   34G   2% /var/lib/flynn/volumes/zfs/mnt/3dbf9981ed5a4aabb74b3a9000a31a4c
```

As you can see, postgres keeps filling up, no matter what I do

**Comment by lmars** [comment]
@arekkas you should try filling up the disk to see if PostgreSQL then starts to free up space, it may well be optimized to only shrink on-disk files when available space becomes an issue.

**Comment by arekkas** [comment]
Great, I'll investigate further

**Comment by lmars** [comment]
@arekkas oh I just realised, the app deletion cleanup removes the cached git repository for the app, but it does not remove any slugs from the database.

**Comment by adamcharnock** [comment]
I'm seeing similar problems too. I just deployed at 160mb slug and the postgres disk usage jumped from 4.9gb to 6.1gb, so 1,200mb jump.

So it seems that for each deploy flynn currently consumes 7.5x the slug size (if this cursory test is anything to go by). A way to clean this up would be very useful indeed.

[Out of interest, what would happen if I truncated the blobstore's `files` table?]

**Comment by titanous** [comment]
@adamcharnock that measure is not quite accurate because ZFS is running on a sparse flat file. Look at the zpool info for more accurate numbers. (The sparse file will stop growing when it hits the max size)

**Comment by adamcharnock** [comment]
@titanous Ah, ok, that makes more sense. I'm not too familiar with ZFS, will the max size be that reported as 'size' by `df` (54G)?

**Comment by titanous** [comment]
```text
$ ls -l /var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev
-rw------- 1 root root 29568814284 Mar 17 15:01 /var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev

$ du /var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev
1562196	/var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev

$ sudo zfs list
NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
flynn-default                                        185M  26.5G    19K  none
flynn-default/6e7526e8-f9a9-4bfe-9e96-07a41ac70a5d  15.7M  26.5G  15.7M  /var/lib/flynn/volumes/zfs/mnt/6e7526e8-f9a9-4bfe-9e96-07a41ac70a5d
flynn-default/9903b516-f55b-45a4-b012-9f87dbb351c4   109M  26.5G   109M  /var/lib/flynn/volumes/zfs/mnt/9903b516-f55b-45a4-b012-9f87dbb351c4
flynn-default/ab7b755e-dab9-4273-ae49-fbd00d15641d  59.8M  26.5G  59.8M  /var/lib/flynn/volumes/zfs/mnt/ab7b755e-dab9-4273-ae49-fbd00d15641d
```

**Comment by lmars** [comment]
Slug cleanup was implemented in #2732. Once that makes it into a Flynn release, you can delete old releases and their associated slugs using `flynn release delete <id>`.

We will also be implementing garbage collection in the future to make this an automated process (i.e. only keep the last N releases, with N being configurable per app).

**Comment by adamcharnock** [comment]
Amazing :-) If I upgrade my cluster will old slugs now get cleaned up after deploying a new version of an existing app? Or do I need to delete and recreate my apps?

**Comment by adamcharnock** [comment]
@lmars I think our posts crossed over there :-)

**Comment by philiplb** [comment]
@lmars Lat me propose a slightly extended strategy for the garbarge collection.

Keeping the N last versions might be troublesome in situations were you deploy N times in a row (shit happens). Now you can't rollback to the version from yesterday.

Proposal: Keep the last N versions and delete the other versions only if they reach a certain, configurable minimum age.

**Comment by adamcharnock** [comment]
@lmars I'm trying this for the first time now (on a fresh Flynn install) and I'm seeing the following:

```
$ flynn release
ID                                    Created
c5bf311b-13ed-4f49-b8b6-a0f3fc1e09e6  25 minutes ago
425cb3ee-b64e-494b-bcdb-4d827392695f  31 minutes ago

$ flynn release delete 425cb3ee-b64e-494b-bcdb-4d827392695f
Are you sure you want to delete release "425cb3ee-b64e-494b-bcdb-4d827392695f"? (yes/no): yes
controller: resource not found
```

Any idea why I'd be receiving a 'resource not found' error?

**Comment by lmars** [comment]
@adamcharnock you are probably hitting the issue in #2990, try updating your CLI version (`flynn update` on your local machine).

**Comment by adamcharnock** [comment]
Thanks @lmars. I did as follows:

```
$ flynn update
Updated v20160624.1 -> v20160626.0.
```

Then tried again:

```
 flynn release
ID                                    Created
...
c11f144f-1ef6-49db-a50d-733d6e16ddce  25 hours ago
c5bf311b-13ed-4f49-b8b6-a0f3fc1e09e6  26 hours ago
425cb3ee-b64e-494b-bcdb-4d827392695f  26 hours ago
(django-decision-matrix)django-decision-matrix (master)$ flynn release delete 425cb3ee-b64e-494b-bcdb-4d827392695f
Are you sure you want to delete release "425cb3ee-b64e-494b-bcdb-4d827392695f"? (yes/no): yes
controller: resource not found
```

It seems the problem persists.

**Comment by lmars** [comment]
@adamcharnock can you give the output of the database commands I mentioned?

**Comment by adamcharnock** [comment]
My appologies @lmars, I totally missed that previous message (I'll blame having just woken from a nap!). Firstly, all releases:

```
$ flynn release
ID                                    Created
f6a2a778-ddf3-407b-96a9-4f1a42fd3b1f  15 hours ago
89102fa4-ccac-4de7-b069-62fb183fc6b0  15 hours ago
e7a9d593-f093-4dae-a041-aeae106c1368  15 hours ago
a714a4f4-f339-4f67-ab60-38d05a5e5029  26 hours ago
c11f144f-1ef6-49db-a50d-733d6e16ddce  26 hours ago
c5bf311b-13ed-4f49-b8b6-a0f3fc1e09e6  27 hours ago
425cb3ee-b64e-494b-bcdb-4d827392695f  27 hours ago
```

Then outputs for the oldest release:

```
$ flynn -a controller pg psql -- -c "SELECT release_id, created_at, deleted_at FROM releases WHERE release_id = '$RELEASE_ID'"


              release_id              |          created_at           | deleted_at
--------------------------------------+-------------------------------+------------
 425cb3ee-b64e-494b-bcdb-4d827392695f | 2016-06-25 13:03:46.732734+00 |
(1 row)
```

```
$ flynn -a controller pg psql -- -c "SELECT * FROM formations WHERE release_id = '$RELEASE_ID'"
                app_id                |              release_id              | processes |          created_at           |          updated_at           | deleted_at | tags
--------------------------------------+--------------------------------------+-----------+-------------------------------+-------------------------------+------------+------
 c3877b56-842a-4f18-9b29-449dd6ad4b0c | 425cb3ee-b64e-494b-bcdb-4d827392695f | null      | 2016-06-25 13:03:46.766707+00 | 2016-06-25 13:09:09.490093+00 |            | null
(1 row)
```

```
$ flynn -a controller pg psql -- -c "SELECT * FROM release_artifacts WHERE release_id = '$RELEASE_ID'"
              release_id              |             artifact_id              |          created_at           | deleted_at | index
--------------------------------------+--------------------------------------+-------------------------------+------------+-------
 425cb3ee-b64e-494b-bcdb-4d827392695f | 28470d6d-adb0-43d6-84f4-0d3e54009682 | 2016-06-25 13:03:46.732734+00 |            |     0
 425cb3ee-b64e-494b-bcdb-4d827392695f | ae26aa02-ecfb-47f1-a919-388d36038095 | 2016-06-25 13:03:46.732734+00 |            |     1
(2 rows)
```

Outputs for the second oldest release:

```
$ flynn -a controller pg psql -- -c "SELECT release_id, created_at, deleted_at FROM releases WHERE release_id = '$RELEASE_ID'"
              release_id              |          created_at           | deleted_at
--------------------------------------+-------------------------------+------------
 c5bf311b-13ed-4f49-b8b6-a0f3fc1e09e6 | 2016-06-25 13:08:49.725961+00 |
(1 row)
```

```
$ flynn -a controller pg psql -- -c "SELECT * FROM formations WHERE release_id = '$RELEASE_ID'"
                app_id                |              release_id              | processes |          created_at           |          updated_at           | deleted_at | tags
--------------------------------------+--------------------------------------+-----------+-------------------------------+-------------------------------+------------+------
 c3877b56-842a-4f18-9b29-449dd6ad4b0c | c5bf311b-13ed-4f49-b8b6-a0f3fc1e09e6 | null      | 2016-06-25 13:08:50.284409+00 | 2016-06-25 13:34:57.768315+00 |            | null
(1 row)
```

```
$ flynn -a controller pg psql -- -c "SELECT * FROM release_artifacts WHERE release_id = '$RELEASE_ID'"
              release_id              |             artifact_id              |          created_at           | deleted_at | index
--------------------------------------+--------------------------------------+-------------------------------+------------+-------
 c5bf311b-13ed-4f49-b8b6-a0f3fc1e09e6 | 28470d6d-adb0-43d6-84f4-0d3e54009682 | 2016-06-25 13:08:49.725961+00 |            |     0
 c5bf311b-13ed-4f49-b8b6-a0f3fc1e09e6 | 1c777646-8114-41c1-a8ee-2174a79a7e8d | 2016-06-25 13:08:49.725961+00 |            |     1
(2 rows)
```

**Comment by lmars** [comment]
@adamcharnock ok so in your case, the problem is the opposite of #2990, your Flynn CLI is newer than your cluster version and they are incompatible (I shamefully introduced a backwards incompatible change :unamused:).

Your options are to either downgrade your Flynn CLI to `v20160512.0` (let me know what platform you use - OSX / Linux / Windows - and I can give you instructions for doing that), or upgrade your cluster to the latest stable version `v20160624.1` (see [here](https://flynn.io/docs/operating#updating)).

**Comment by awayo** [comment]
@lmars i have the same problem that adam, and with flynn cli and flynn-host with different versions. Can't we have an script to remove the release artifacts from pg? or at least explain here how i can downgrade flynn ? 

I can't upgrade flynn-host. Update doesn't works and `flynn cluster backup` return: 

> error getting discoverd app details: GET https://controller.o17z.flynnhub.com/apps/discoverd: httpclient: raw req: unexpected status 503

**Comment by lmars** [comment]
@awayo sorry I didn't see your message until now, do you mind opening a new issue? Please run `sudo flynn-host collect-debug-info` and post the resulting gist in the issue too.
