### ISSUE TITLE
`flynn env set` times out, `flynn-host collect-debug-info` locks up

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1572]
https://gist.github.com/temujin9/7b04c669ffdbbccf3b44 has logs and ps output from the source cluster.

I will keep the cluster in question around for a little while, for further investigation.

**Comment by titanous** [comment]
The deployer is reporting an error starting at line 1496 of the logs:

> validation_error: Requested formation includes process types that do not exist in release. Invalid process types: [web]

**Comment by titanous** [comment]
Closing, as current evidence points to user error (missing `web` process type in Procfile). Please re-open if you see anything weird.
