### ISSUE TITLE
Failed to run remote commands

### ISSUE THREAD

**Issue by Vaultman** [flynn/flynn#1573]
Hi, suddenly I can't run commands like `flynn run something`, or `flynn pg psql`, or `flynn pg dump -f latest.dump`. I returns `unknown_error: Something went wrong`. Every other commands works. Well I didn't try scaling, I don't want to push my luck and break it even more :)

Here is my debug info https://gist.github.com/e1394f4ea95f5d95ca85

Thanks

**Comment by titanous** [comment]
From the log it looks like etcd failed at `2015-06-05 12:48:54` and didn't recover until `2015-06-05 12:56:03`. There are some issues in flynn that we're working that can cause clusters to not recover after etcd failures.

**Comment by Vaultman** [comment]
It seems so. I reinstalled flynn and it failed again after few hours. Is there any approx ETA when those critical issues will be fixed? (days, weeks, months...)

**Comment by titanous** [comment]
The first major PR #1373 should show up in the next few days.
