### ISSUE TITLE
updater: Support updating a single node cluster

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1575]
Running `flynn-host update` currently fails on single node clusters due to the postgres app being in singleton mode.

We should either skip the update of postgres on single node clusters, or support deploying postgres in singleton mode.

**Comment by kwando** [comment]
Why is this closed?

**Comment by lmars** [comment]
@kwando this issue is open, we closed the duplicate issue #1571.

**Comment by kwando** [comment]
My bad, I looked at the status label for #1571 :facepalm:
Sorry for the noise.

**Comment by lmars** [comment]
Updating a single node cluster will now fail when deploying discoverd (which [happens first](https://github.com/flynn/flynn/blob/master/updater/types/types.go#L10-L27)), we should skip that too.

**Comment by lmars** [comment]
I think it makes sense to not try deploying postgres in single node clusters (users shouldn't have the expectation of HA with a single node), but perhaps give users a tool to do an export, stop postgres, start with new image, then import.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
