### ISSUE TITLE
Flynn Layer 1 Connection Refused

### ISSUE THREAD

**Issue by KernCheh** [flynn/flynn#1586]
Hi,

I'm experiencing the same issue as [#1382]. Basically, I get the follow issue when trying to bootstrap Layer 1 with `min-hosts=3`

`check online-hosts error: Get http://127.0.0.1:1111/services/flynn-host: dial tcp 127.0.0.1:1111: connection refused`

I've collected the debug logs here:

node 0: https://gist.github.com/7f454d7a5aa8daf74116 
node 1: https://gist.github.com/4952d092d6a8bd190a8e 
node 2: https://gist.github.com/16f7feb543e93648bc56 

Anyone experiencing the same issue? Perhaps it's myself doing something wrong

**Comment by titanous** [comment]
Did you reuse a discovery token with different nodes?

**Comment by KernCheh** [comment]
Hi @titanous , thanks for your help. No I did not reuse a discovery token. However, some confusion could have occured because my `node 0` was previously a part of a single node cluster which could have potentially not been destroyed properly. The steps I took was (on all 3 clusters):
```
sudo rm -r /var/log/flynn/* # Clear all logs for easier tracing
sudo rm /var/lib/flynn/host-state.bolt
sudo rm /var/log/upstart/flynn-host.log

#node 1
sudo flynn-host init --init-discovery=3

#node 2, 3 
sudo flynn-host init --discovery <discovery_url>

#all nodes
sudo flynn-host start

# check logs
sudo ls -al /var/log/flynn
# trace discovery and etcd logs to ensure no errors
```

Also initially my IPtables were misconfigured to such that not all traffic between the hosts in a cluster is allowed. Thus, I had issues with etcd using ports 2379:2380, as well as postgres using port 1113.
