### ISSUE TITLE
Typo (or possibly deprecated?) about command-line message during 'flynn-host bootstrap'

### ISSUE THREAD

**Issue by remore** [flynn/flynn#1599]
I'm using Ubuntu 14.04 and followed [the documentation](https://flynn.io/docs/installation#ubuntu-14.04-amd64). At the bottom of this, it says

```
$ sudo \
    CLUSTER_DOMAIN=demo.localflynn.com \
    flynn-host bootstrap --min-hosts=3 /etc/flynn/bootstrap-manifest.json
```

and this works fine. What made me confusing was the following message resulting from this command:

```
...
04:58:35.747329 deploy-app logaggregator
04:58:35.798840 deploy-app taffy
04:58:35.862996 deploy-app dashboard
04:58:35.943808 add-route dashboard-route
04:58:35.961670 wait blobstore-wait
04:58:35.997993 wait gitreceive-wait
04:58:36.000138 log log-complete
04:58:36.000430 log log-complete

Flynn bootstrapping complete. Install the flynn-cli (see https://cli.flynn.io for instructions) and paste the line below into a terminal window:

flynn cluster add -g a.test-docker.ha-mo.jp:2222 -p aRh2cNpHkItRClN1iXYGl395JqSWLDZbNyg61x/qQXA= default https://controller.a.test-docker.ha-mo.jp 6391e177112812331902c2e2989a40a4

The built-in dashboard can be accessed at http://dashboard.a.test-docker.ha-mo.jp/login?token=59ef1452acef3f9314c21f1831ef532a
```

According to the message I should `Install the flynn-cli (see https://cli.flynn.io for instructions)` but I can't find the website `https://cli.flynn.io` working.(So that I wasn't able to find out what flynn-cli is.)

I'm not sure if this message is still valid or not.(Or is the website just down and I was just no luck?)

**Comment by titanous** [comment]
Take a look at https://github.com/flynn/flynn/blob/master/cli/README.md (I'll fix the message today)

**Comment by remore** [comment]
Thank you for quick follow-up! Understood.
