### ISSUE TITLE
Add a PG_URL environment variable

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#1601]
Currently flynn gives me PGDATABASE, PGHOST, PGPASSWORD and PGUSER.
It would be convenient to get get the same info in a URL-format too.

PG_URL=postgres://myuser:mypassword@postgres.discoverd:5432/mydatabase

**Comment by lmars** [comment]
You can construct this environment variable in the same way as [DATABASE_URL](https://flynn.io/docs/postgres#database_url), for example:

```sh
flynn env set PG_URL=$(export $(flynn env | xargs); echo "postgres://$PGUSER:$PGPASSWORD@$PGHOST:5432/$PGDATABASE")
```

**Comment by kwando** [comment]
Yeah, I read that in the manual at flynn.io.. though that variable would not update if the others are changed.

**Comment by kwando** [comment]
Anyway no biggie =)
