### ISSUE TITLE
Support updating flannel and discoverd

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1607]
Updating flannel should be straight forward, just need to check it comes back up with the correct config.

Updating discoverd involves handling watch streams disconnecting, a quick pass shows the following places that needs to happen (there could be more):

* deployer ([here](https://github.com/flynn/flynn/blob/master/controller/worker/deployment/job.go#L95-L98) and [here](https://github.com/flynn/flynn/blob/master/controller/worker/deployment/job.go#L124-L130))
* logmux ([here](https://github.com/flynn/flynn/blob/master/host/logmux/service_conn.go#L32) is the watch, the disconnect will be seen [here](https://github.com/flynn/flynn/blob/master/host/logmux/service_conn.go#L89-L92))
* [cluster.StreamHosts](https://github.com/flynn/flynn/blob/master/pkg/cluster/client.go#L79-L99) (probably just need to resync and send events for any hosts we may of missed events for)
* [postgres.Wait](https://github.com/flynn/flynn/blob/master/pkg/postgres/postgres.go#L36-L51) (resync to get the latest state)

For updating etcd, we need to decide if we can accept downtime due to a lack of consensus (i.e. stop the existing job and start a new one with the same volume) or if we want to start a new job first, have it join the cluster, then kill the old one (which may in fact not be feasible).

**Comment by titanous** [comment]
etcd should be able to handle a single node going down as long as there are at least three nodes. There are already some hacks in the wrapper script that work around the missing data directory, which should be a stopgap until the new raft stuff lands.

**Comment by lmars** [comment]
@titanous deploying etcd is going to require a new deployment strategy, outlined as follows:

1. set a key in the etcd cluster
2. send a request (e.g. a signal or HTTP) to stop ectd, but keep the job running so the scheduler does not restart it (similar to the postgres deploy)
3. start a new etcd job on the same host as the old one
4. wait for the key to appear in the new etcd job (an indication that it has caught up with the cluster)
5. remove the old member from the cluster (I'm not sure if this is strictly necessary)

For 2), we will need to right a wrapper program to receive the request and stop etcd. Also, because etcd is an omni job, we can't use the current scheduler as it will start / stop jobs on all hosts at once, rather than one by one, so we will have to start the jobs manually.

Given we are [removing the etcd dependency from discoverd](1612), we will also need to take a similar approach for that, and our remaining dependency on etcd will be flannel, so I am wondering if we could remove etcd entirely and modify Flannel to use discoverd service metadata (by implementing [this interface](https://github.com/coreos/flannel/blob/master/subnet/registry.go#L30-L37) and a little refactoring)?

**Comment by titanous** [comment]
Yes, we should change flannel to use discoverd.

**Comment by lmars** [comment]
Flannel has been switched to use discoverd rather than etcd in #1635, so we are waiting on #1612 before updating discoverd.

**Comment by lmars** [comment]
For the discoverd update, the current approach is for replacement jobs to first start a proxy DNS server using `SO_REUSEPORT` (for zero-downtime DNS), and then instruct the old job to shutdown but not to stop completely (so the scheduler does not restart it). Shutting down involves closing the Raft store plus all listeners and connections, after which the new job will open its own store, and appear to the cluster as the same job, just with missing logs which it will receive from the leader.

Given we need to maintain a majority in the Raft cluster during the update, we need to make sure the jobs only do this one at a time, so we are using service metadata to co-ordinate which job is currently performing the steps above, and other jobs wait for the performing job to finish before trying to perform themselves.

This has been partially implemented on the `update-discoverd` branch (see [here](https://github.com/flynn/flynn/compare/update-discoverd)), but the cluster after the update sometimes does not converge back to a healthy state.

Here are some known issues that I have observed but as yet been unable to fix:

* clients seem to remain connected to the old job, even though we are explicitly closing streams, disabling keep alives and closing the listeners (evident by a flurry of `discoverd: shutting down` errors in the log after the shutdown)
* when the deployment succeeds, sometimes the Raft state remains static; new jobs don't appear in the cluster state and nothing is broadcast

There are also a bunch of TODOs in the comments which require code changes that I haven't got round to doing.

**Comment by josephglanville** [comment]
We now have discoverd deployment and thus updates working.
