### ISSUE TITLE
New installation instructions

### ISSUE THREAD

**Issue by Vaultman** [flynn/flynn#1610]
Are there any changes in the installation process after this big architectural change introduced in #1597? I wasn't able to install flynn to my cluster following current documentation.

**Comment by titanous** [comment]
@Vaultman Looks like the discovery token is missing from the bootstrap command, is that where you encountered the problem?

**Comment by Vaultman** [comment]
Well, I run `flynn-host init --init-discovery` on one node, `flynn-host init --discovery https://discovery.flynn.io/clusters/{$token}` on others, successfully started flynn on all nodes with `start flynn-host` and then `CLUSTER_DOMAIN=mydomain.com flynn-host bootstrap --min-hosts=3` on the first note. As I remember, it failed on waiting for other hosts.

**Comment by titanous** [comment]
Try specifying `--discovery TOKEN` to the bootstrap command. I just opened #1611 which should fix this.

**Comment by Vaultman** [comment]
Thank you, will try when I have some time.

**Comment by Vaultman** [comment]
yep, it was the missing discovery token. Works like a charm now. Thanks.
