### ISSUE TITLE
Azure Installer: Use correct endpoint

### ISSUE THREAD

**Issue by felixrieseberg** [flynn/flynn#1613]
In order for the full authentication flow to work, we have to authenticate with the correct endpoint. Since the app is created within the context of a domain, we have to authenticate with that domain's correct OAuth 2 endpoint (which usually looks like `https://login.microsoftonline.com/cbd880ba-ffc3-4c35-91c4-3ed01b7c8f33/oauth2/token?api-version=1.0`) and can be found by clicking on the 'View Endpoints' button in the configuration for a domain in the Azure Management Portal.

![azure-app-1-1](https://cloud.githubusercontent.com/assets/1426799/8313400/46d40c1e-1997-11e5-84b2-cb4101bd7363.png)

**Comment by titanous** [comment]
Thanks for fixing this!
