### ISSUE TITLE
Azure Installer: Improve the Tutorial's UI/UX

### ISSUE THREAD

**Issue by felixrieseberg** [flynn/flynn#1615]
It's awesome to see that we have a working Azure flow, but I believe that the tutorial could look a bit better. In detail, I'd like to propose a small wizard that goes through the necessary actions step-by-step combined with a "Skip" option, allowing more professional users to just enter the necessary inputs.

I'm happy to provide a PR, if y'all are into that idea.

**Comment by titanous** [comment]
This sounds good. @jvatic any objections?

**Comment by jvatic** [comment]
This is an excellent idea!
