### ISSUE TITLE
Increased pps between two nodes.

### ISSUE THREAD

**Issue by Vaultman** [flynn/flynn#1616]
Today I received this notice about possible attack from my provider:

> Attack detail : 72247pps/4190326bps
Wed Jun 24 11:25:49 2015 $IP1:46428 > $IP2:8472 UDP
Wed Jun 24 11:25:49 2015 $IP1:46428 > $IP2:8472 UDP
Wed Jun 24 11:25:49 2015 $IP1:46428 > $IP2:8472 UDP
Wed Jun 24 11:25:49 2015 $IP1:46428 > $IP2:8472 UDP
Wed Jun 24 11:25:49 2015 $IP1:46428 > $IP2:8472 UDP

Those are two Flynn nodes. It runs only Flynn (+ flynn apps), nothing else.
Is it possible that it is caused by misbehaved flynn? Unfortunately I have no logs.

Thanks.

**Comment by titanous** [comment]
It is possible that a component in Flynn broke and is sending many requests. UDP port 8472 is the VXLAN port that Flynn uses for overlay networking of all traffic. Without logs or packet dumps it's hard to say what's happening.
