### ISSUE TITLE
Add a JavaScript style guide

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1625]
The basic guidelines are
- Run [jshint](http://jshint.com/)
- Use tabs instead of spaces
- Define vars individually (better indentation with tabs and cleaner diff when making changes)
- Use descriptive var names (avoid single character variable names except in for loops)
- Use `null` instead of `undefined`
- Avoid using `!someVar` except with booleans
- Give single space on either side of `!expression` in an `if` statement

**Comment by jvatic** [comment]
Here's a draft: https://gist.github.com/jvatic/612ece3e52cbb7560649

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
