### ISSUE TITLE
flynn release use cases

### ISSUE THREAD

**Issue by adrianmoya** [flynn/flynn#1633]
Hi, I don't fully understand the use cases for the `flynn release`  command. Is this to run arbitrary docker images in flynn? or to dockerize an app that already runs in flynn? 

If you can please elaborate the use cases that would be helpful. Thanks!

**Comment by lmars** [comment]
`flynn release` is used to create a release with an arbitrary image, typically from the default Docker registry.

It is currently under-documented as we are not happy with the current workflow (see #1085 for thoughts on improving it).

See [here](https://gist.github.com/lmars/fca0f18b4ecd507fb39a) for an example of using `flynn release` to deploy Redis.

**Comment by adrianmoya** [comment]
Thanks @lmars I'll be warching the feature as it evolves.
