### ISSUE TITLE
Got 503 error when using CLI.

### ISSUE THREAD

**Issue by monaka** [flynn/flynn#1637]
I installed Flynn on 3 nodes cluster in Azure two or three hours ago.
And I got 503 errors after I deployed Redmine a few times. Like this.

```
~/redmine$ flynn route
GET {{URL hidden}}: httpclient: unexpected status 503
~/redmine$ flynn key                                                                                                                                                                                   
GET {{URL hidden}}: httpclient: unexpected status 503
```

Debug info is https://gist.github.com/anonymous/daf3d7d6242fae397894

**Comment by titanous** [comment]
From the debug info it looks like etcd got partitioned and has not recovered. Is it possible for you to post the debug info from the other two nodes?

**Comment by monaka** [comment]
Here're other nodes.
https://gist.github.com/7e645f3e6f395216db69
https://gist.github.com/e9bd2548bfa53d23438a

One log couldn't upload as too big.
https://gist.githubusercontent.com/anonymous/7e645f3e6f395216db69/raw/0-debug-output.log

**Comment by titanous** [comment]
This looks like a catastrophic etcd failure, I'm unsure of the cause. I'd suggest deploying a new cluster.

**Comment by monaka** [comment]
Thanks for your analysis. I also have same opinion.
And I tried to deploy after I post this issue. The same issue was reproduced again...
(I'm not sure if 100% reproduction.)

My cluster is behind of Azure's load balancer. 80, 443, 2222 is load balanced.
Is it possible to relate this issue?

**Comment by titanous** [comment]
I'm investigating some similar problems. I'll update this issue when I know more.

**Comment by monaka** [comment]
It seems etcds in my cluster become to works well.
Thanks for your quick response and good fix!
