### ISSUE TITLE
Developer maintenance mode

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1647]
In order to cleanly migrate between clusters with import / export, it would be good to be able to place Flynn into a maintenance mode which blocks code pushes and configuration changes, with a friendly error message.

**Comment by temujin9** [comment]
Using `flynn -a gitreceive scale app=0` to turn maintenance-mode on works well. It lacks only the pretty error message, and we can live with that.

**Comment by temujin9** [comment]
Actually, we do want a more robust solution here: maintenance mode should disallow scaling events, metadata changes, and variable changes, in addition to pushes.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
