### ISSUE TITLE
Not getting a call back to local host after creating Azure app with oauth token endpoint

### ISSUE THREAD

**Issue by jamescw** [flynn/flynn#1655]
The flynn installer is not being called after setting up the Azure application and providing the local host address, application id and token endpoint, this was working two releases ago I am now on v20150710.0
The error should be recreatable by doing an Azure install using the installer.

**Comment by jvatic** [comment]
It appears the authorize URL is being malformed, I'll get this fixed shortly

**Comment by jvatic** [comment]
@jamescw Thanks for reporting this! It will be fixed in the next release. You can work around the issue by adding the `client_id`, `response_type`, and `resource` params from the broken URL to the “OAuth 2.0 Authorization Endpoint”.
