### ISSUE TITLE
SSH agent for slugbuilder (or other buildchain)

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1662]
Currently, we can't use slugbuilder to reach private Git repositories (e.g. for Gemfile or submodules). To solve this, add an SSH agent, and an API endpoint to which keys can be pushed.

**Comment by titanous** [comment]
Is an SSH agent required immediately? Would giving gitreceive/slugbuilder a SSH keypair that can be added as a deploy key work for now?

**Comment by temujin9** [comment]
I think the keypair could work, assuming I could establish it somewhere during cluster launch. Agent will probably be better long term, but we can wait to establish concrete needs there.
