### ISSUE TITLE
`flynn scale` should list scales for all releases

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1664]
Prior releases may be left scaled up, if certain conditions occur. In order to maintain in that event, it would be helpful to see a list of all (non-zero) scales, not just the one for the current release.

**Comment by lmars** [comment]
@temujin9 with the proposed change in #1785, you can achieve this with:

```
$ flynn release -q | xargs -L1 flynn scale -r
web=1
web=0
web=0
web=0
```

If you want the release IDs in the output:

```
$ for release in $(flynn release -q); do echo "${release}: $(flynn scale -r ${release})"; done
9ec2563c4989405d8b387d2ba41f1817: web=1
3d2b027fbbf24e549673af528c4b5e5b: web=0
e1a1bcbc8a1d460cb415bd062d763b94: web=0
3ea4fe62c40242a893f8c42ebea7f269: web=0
```

Is that good enough?

**Comment by temujin9** [comment]
Honestly, that's still quite illegible. I'll probably end up wrapping it if you don't implement in Flynn itself.

**Comment by titanous** [comment]
I think we should add a `flynn scale --all` command that does this.

**Comment by temujin9** [comment]
:+1: for @titanous' suggestion.
