### ISSUE TITLE
install-flynn script issues

### ISSUE THREAD

**Issue by NeilW** [flynn/flynn#1665]
I've come across a couple of potential issues with the install-flynn script.

Firstly if you use the documented instructions here: https://flynn.io/docs/installation#ubuntu-14.04-amd64 i.e.

```
$ sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
```

and any of the packages has an interactive update then you won't be able to put any input in the interactive update. The script needs `export DEBIAN_FRONTEND=noninteractive` somewhere to work properly. 

Additionally the script seems out of sync with the packer scripts. From a standard Trusty Cloud Image ( http://cloud-images.ubuntu.com/trusty/current/ ) I have to run:

```
DEBIAN_FRONTEND=noninteractive apt-get ${apt_options} install --install-recommends language-pack-en linux-generic-lts-vivid
DEBIAN_FRONTEND=noninteractive apt-get ${apt_options} autoremove
DEBIAN_FRONTEND=noninteractive apt-get ${apt_options} dist-upgrade
```

before running the install script to get to the same place as the packer output.

**Comment by titanous** [comment]
Thanks for this analysis! We should definitely add the noninteractive environment variable.

We don't upgrade the kernel in the install script because there are no known bugs that affect us so far in the older kernels and it requires a reboot.
