### ISSUE TITLE
What Code editor or IDE does Flynn team use for development?

### ISSUE THREAD

**Issue by showwayer** [flynn/flynn#1666]
Hi All

I am new to Flynn and new to Go. I have followed Flynn's official guide of setting up development environment using Vagrant and Packer. Things went very smoothly and my one-node cluster is up. However, the official guide doesn't mention what code editor or ide the team is using and is pre-built into the development environment. I looked into Packer's template file and install.sh script but don't find any relevant information about it. Does the team just use Vim for most of the development work? That seems pretty brave! If this is the case, does Flynn's contributing guideline encourage using gocode, go oracle toolchain to make contributed codes less error-prone?

Thanks.

Cai

**Comment by titanous** [comment]
The entire team uses Vim currently, but there's no need to advocate for a specific editor/plugins, Flynn/Go is editor-agnostic :)
