### ISSUE TITLE
Issues installing on ubuntu/openstack

### ISSUE THREAD

**Issue by adrianmoya** [flynn/flynn#1669]
I'm following the install instructions for ubuntu, and I'm having an issues when trying to bootstrap Layer 1:

I'm getting 

`{"s":3,"t":1437329964384,"m":"t=2015-07-19T18:19:24+0000 lvl=info msg=resuming app=containerinit fn=containerInitApp\nt=2015-07-19T18:19:24+0000 lvl=info msg=\"setting up the container\" app=containerinit fn=containerInitApp\nt=2015-07-19T18:19:24+0000 lvl=eror msg=\"error setting up the container\" app=containerinit fn=containerInitApp err=\"invalid argument\"\nt=2015-07-19T18:19:24+0000 lvl=info msg=\"changing state\" app=containerinit fn=changeState state=failed err=\"invalid argument\" exitStatus=-1\nt=2015-07-19T18:19:24+0000 lvl=info msg=\"sending state change\" app=containerinit fn=StreamState state=failed err=\"invalid argument\" exitStatus=-1\n"}`

when running 

`sudo CLUSTER_DOMAIN=mydomain.com flynn-host bootstrap --min-hosts 3 --discovery https://discovery.flynn.io/clusters/xxxx`

Any ideas on how to proceed?

Debug info: https://gist.github.com/anonymous/3d22f2b1f16695a2b219

**Comment by titanous** [comment]
Do you have the output from the bootstrap command handy?

**Comment by titanous** [comment]
Also, it looks like you are running `v20150706.0` which is an older version, the current version is `v20150718.0`.

**Comment by adrianmoya** [comment]
Output is
`sudo: unable to resolve host shcloud-demo-8d5395d4-f549-4048-9341-30eea1a818f0
18:19:22.550962 check online-hosts
18:19:23.065085 require-env require-env
18:19:23.079672 run-app etcd
18:19:24.442204 run-app etcd error: bootstrap: host error while launching job: "invalid argument"
`

Let me start fresh with the latest version.

**Comment by adrianmoya** [comment]
No luck with the new installation. This is the procedure I'm using:

1. Created an instance with ubuntu 14.04.
2. Upgraded packages and installed flynn using the online script.
3. Created an snapshot of this instance.
4. Launched 2 instances of the snapshot.
5. Init discovery on the 3 hosts (first with init-discovery, other two with the discovery token from 1)
6. Started flynn-host on the 3 nodes.
7. Tried to bootstrap Layer 1:

```
00:52:18.005875 check online-hosts
00:52:18.647606 require-env require-env
00:52:18.660883 run-app etcd
00:52:20.400707 run-app etcd error: bootstrap: host error while launching job: "invalid argument"
```
https://gist.github.com/fd20720c580aaa855781

**Comment by titanous** [comment]
Looks like our `sethostname(2)` inside the container is failing because the hostname of the host combined with the container ID is too long (limit is 64 characters!?!). The temporary workaround is to shorten the hostname, I'll follow up with an actual code fix.

**Comment by adrianmoya** [comment]
Ok, I was able to advance a bit by shortening the hosts names. But then I hit this issue:

```
sudo: unable to resolve host flynn-1
21:10:22.830701 check online-hosts
21:10:23.312823 require-env require-env
21:10:23.321149 run-app etcd
21:10:30.268085 run-app flannel
21:10:33.818268 run-app discoverd
21:10:41.345501 wait-hosts wait-hosts
21:11:00.405109 gen-random pg-password
21:11:00.405267 gen-random pg-password 472cbab6512e266f14d083c9c4b26fad
21:11:00.405274 run-app postgres
21:11:35.702516 gen-random controller-key
21:11:35.702689 gen-random controller-key a8e1dfbed9b722abe74acdf6a2858240
21:11:35.702703 gen-random dashboard-session-secret
21:11:35.702747 gen-random dashboard-session-secret c955be557d6216d1ada9afc4d8034cb1
21:11:35.702753 gen-random dashboard-login-token
21:11:35.702781 gen-random dashboard-login-token 52971ca00c485db7470fa580b52cabc9
21:11:35.702786 gen-random name-seed
21:11:35.702834 gen-random name-seed 1bddacbc487ee1c78269
21:11:35.702839 gen-random router-sticky-key
21:11:35.702951 gen-random router-sticky-key bJv9NoQCQvXPI+n9Gf7MdaB5WgJe9KUuVWlBVEa4JOA=
21:11:35.702958 wait postgres-wait
21:13:35.920969 wait postgres-wait error: bootstrap: timed out waiting for http://postgres-api.discoverd/ping, last response "Get http://postgres-api.discoverd/ping: dial tcp: lookup postgres-api.discoverd: no such host"
```

**Comment by titanous** [comment]
Would you please provide the debug info?

**Comment by adrianmoya** [comment]
Yeah, sorry I forgot:

https://gist.github.com/anonymous/86b64fb7726f196e173c

**Comment by titanous** [comment]
Do you have a firewall/security group enabled that blocks inter-node communication (TCP or UDP)?

**Comment by adrianmoya** [comment]
No, security group in openstack is configured to allow all tcp/udp traffic
from the private network. Do you have any command I can run to verify this?

El lunes, 20 de julio de 2015, Jonathan Rudenberg <notifications@github.com>
escribió:

> Do you have a firewall/security group enabled that blocks inter-node
> communication (TCP or UDP)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flynn/flynn/issues/1669#issuecomment-123082681>.
>


-- 
Adrian E. Moya G.
http://adrianmoya.com
http://www.linkedin.com/in/moyaadrian
310-2759555

**Comment by titanous** [comment]
Try pinging `100.100.27.1` from `flynn1` and `flynn2`.

**Comment by adrianmoya** [comment]
```
ubuntu@flynn-1:~$ ping 100.100.27.1
PING 100.100.27.1 (100.100.27.1) 56(84) bytes of data.
64 bytes from 100.100.27.1: icmp_seq=1 ttl=64 time=0.297 ms
64 bytes from 100.100.27.1: icmp_seq=2 ttl=64 time=0.330 ms
64 bytes from 100.100.27.1: icmp_seq=3 ttl=64 time=0.337 ms
^C
--- 100.100.27.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.297/0.321/0.337/0.022 ms
```

```
ubuntu@flynn-2:~$ ping 100.100.27.1
PING 100.100.27.1 (100.100.27.1) 56(84) bytes of data.
64 bytes from 100.100.27.1: icmp_seq=1 ttl=64 time=0.488 ms
64 bytes from 100.100.27.1: icmp_seq=2 ttl=64 time=0.220 ms
64 bytes from 100.100.27.1: icmp_seq=3 ttl=64 time=0.264 ms
^C
--- 100.100.27.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.220/0.324/0.488/0.117 ms
```

**Comment by titanous** [comment]
That looks good, try pinging `100.100.27.2` and curling `http://100.100.27.2:5433/status` from all three nodes, and provide the output of `ps faux` on `flynn3`.

**Comment by adrianmoya** [comment]
For flynn1 & flynn-2: ping to 100.100.27.2 & curl does not respond. On flynn-3:

```
ubuntu@flynn-3:~$ ping 100.100.27.2
PING 100.100.27.2 (100.100.27.2) 56(84) bytes of data.
64 bytes from 100.100.27.2: icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from 100.100.27.2: icmp_seq=2 ttl=64 time=0.040 ms
64 bytes from 100.100.27.2: icmp_seq=3 ttl=64 time=0.042 ms
^C
--- 100.100.27.2 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.036/0.039/0.042/0.005 ms
ubuntu@flynn-3:~$ curl http://100.100.27.2:5433/status
{"peer":{"id":"b2ed9fb7fc5198104e57811682a8183c","role":"sync","pg_retry_pending":"2015-07-21T00:11:20.087592282Z","state":{"generation":1,"init_wal":"0/00000000","primary":{"id":"222955f1e2cac1439ab63adcf7d71eb9","addr":"100.100.84.2:5432","proto":"tcp","meta":{"FLYNN_APP_ID":"dce6a5afd9d6402ab540a4b7d5a5ce7d","FLYNN_JOB_ID":"flynn1-415c5ba442da4fe9b9cab000058e4f07","FLYNN_PROCESS_TYPE":"postgres","FLYNN_RELEASE_ID":"23099859231142a387bb8499f2226c03"}},"sync":{"id":"b2ed9fb7fc5198104e57811682a8183c","addr":"100.100.27.2:5432","proto":"tcp","meta":{"FLYNN_APP_ID":"dce6a5afd9d6402ab540a4b7d5a5ce7d","FLYNN_JOB_ID":"flynn3-d57ce0369ad64ed895dac921a6b0b19c","FLYNN_PROCESS_TYPE":"postgres","FLYNN_RELEASE_ID":"23099859231142a387bb8499f2226c03"},"index":33},"async":[{"id":"e12896a23cae267cd5f2ef3567e8853b","addr":"100.100.43.2:5432","proto":"tcp","meta":{"FLYNN_APP_ID":"dce6a5afd9d6402ab540a4b7d5a5ce7d","FLYNN_JOB_ID":"flynn2-8b7ca96e85b24b34acca200cd02807f2","FLYNN_PROCESS_TYPE":"postgres","FLYNN_RELEASE_ID":"23099859231142a387bb8499f2226c03"},"index":39}]},"peers":[{"id":"222955f1e2cac1439ab63adcf7d71eb9","addr":"100.100.84.2:5432","proto":"tcp","meta":{"FLYNN_APP_ID":"dce6a5afd9d6402ab540a4b7d5a5ce7d","FLYNN_JOB_ID":"flynn1-415c5ba442da4fe9b9cab000058e4f07","FLYNN_PROCESS_TYPE":"postgres","FLYNN_RELEASE_ID":"23099859231142a387bb8499f2226c03"},"index":26},{"id":"b2ed9fb7fc5198104e57811682a8183c","addr":"100.100.27.2:5432","proto":"tcp","meta":{"FLYNN_APP_ID":"dce6a5afd9d6402ab540a4b7d5a5ce7d","FLYNN_JOB_ID":"flynn3-d57ce0369ad64ed895dac921a6b0b19c","FLYNN_PROCESS_TYPE":"postgres","FLYNN_RELEASE_ID":"23099859231142a387bb8499f2226c03"},"index":33},{"id":"e12896a23cae267cd5f2ef3567e8853b","addr":"100.100.43.2:5432","proto":"tcp","meta":{"FLYNN_APP_ID":"dce6a5afd9d6402ab540a4b7d5a5ce7d","FLYNN_JOB_ID":"flynn2-8b7ca96e85b24b34acca200cd02807f2","FLYNN_PROCESS_TYPE":"postgres","FLYNN_RELEASE_ID":"23099859231142a387bb8499f2226c03"},"index":39}]},"postgres":{"config":{"role":"sync","upstream":{"id":"222955f1e2cac1439ab63adcf7d71eb9","addr":"100.100.84.2:5432","proto":"tcp","meta":{"FLYNN_APP_ID":"dce6a5afd9d6402ab540a4b7d5a5ce7d","FLYNN_JOB_ID":"flynn1-415c5ba442da4fe9b9cab000058e4f07","FLYNN_PROCESS_TYPE":"postgres","FLYNN_RELEASE_ID":"23099859231142a387bb8499f2226c03"}},"downstream":{"id":"e12896a23cae267cd5f2ef3567e8853b","addr":"100.100.43.2:5432","proto":"tcp","meta":{"FLYNN_APP_ID":"dce6a5afd9d6402ab540a4b7d5a5ce7d","FLYNN_JOB_ID":"flynn2-8b7ca96e85b24b34acca200cd02807f2","FLYNN_PROCESS_TYPE":"postgres","FLYNN_RELEASE_ID":"23099859231142a387bb8499f2226c03"},"index":39}},"running":false,"synced_downstream":null}}ubuntu@flynn-3:~
```

ps faux -> https://gist.github.com/adrianmoya/fe5594f706eae8d984ee

**Comment by titanous** [comment]
We automatically set up a VXLAN overlay network (interface `flannel.1` encapsulates ethernet frames over UDP port 8472) that should route that IP to the postgres container on `flynn-3`. For some reason it is not being routed correctly. The weird part is that the `.1` addresses (assigned to the `flynnbr0` interface on each host) are routing fine.

Please provide the `route -n` output from each host.

Another question I have is whether this is consistently happening for all installs on this infrastructure/base image? One thing to try (currently with little empirical backing) is that updating to a new kernel is worth trying (for example `linux-generic-lts-vivid`).

**Comment by adrianmoya** [comment]
route -n:
```
ubuntu@flynn-1:~$ sudo route -n
sudo: unable to resolve host flynn-1
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.1.1        0.0.0.0         UG    0      0        0 eth0
10.0.1.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
100.100.0.0     0.0.0.0         255.255.0.0     U     0      0        0 flannel.1
100.100.27.0    100.100.27.0    255.255.255.0   UG    0      0        0 flannel.1
100.100.43.0    100.100.43.0    255.255.255.0   UG    0      0        0 flannel.1
100.100.84.0    0.0.0.0         255.255.255.0   U     0      0        0 flynnbr0
```

```
ubuntu@flynn-2:~$ sudo route -n
sudo: unable to resolve host flynn-2
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.1.1        0.0.0.0         UG    0      0        0 eth0
10.0.1.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
100.100.0.0     0.0.0.0         255.255.0.0     U     0      0        0 flannel.1
100.100.27.0    100.100.27.0    255.255.255.0   UG    0      0        0 flannel.1
100.100.43.0    0.0.0.0         255.255.255.0   U     0      0        0 flynnbr0
100.100.84.0    100.100.84.0    255.255.255.0   UG    0      0        0 flannel.1
```
```
ubuntu@flynn-3:~$ sudo route -n
sudo: unable to resolve host flynn-3
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.1.1        0.0.0.0         UG    0      0        0 eth0
10.0.1.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
100.100.0.0     0.0.0.0         255.255.0.0     U     0      0        0 flannel.1
100.100.27.0    0.0.0.0         255.255.255.0   U     0      0        0 flynnbr0
100.100.43.0    100.100.43.0    255.255.255.0   UG    0      0        0 flannel.1
100.100.84.0    100.100.84.0    255.255.255.0   UG    0      0        0 flannel.1
```

I've installed flynn some months ago without any issue, using the base ubuntu image, what I'm doing different this time is taking the snapshot of the first host to instantiate the other two.

I can try upgrading the kernel, but would prefer if we can spot the issue with vanila trusty. Let me know if you find something interesting from the output.

**Comment by titanous** [comment]
Please run `cat /proc/sys/net/ipv4/ip_forward` on all hosts.

**Comment by adrianmoya** [comment]
`cat /proc/sys/net/ipv4/ip_forward` is 1 in all host

**Comment by adrianmoya** [comment]
If it helps, here's the security group config on openstack:

```
[root@cc ~(keystone_admin)]# nova secgroup-list-rules d01d28ed-e1d3-4886-a603-dc07de4abc83
+-------------+-----------+---------+-------------+--------------+
| IP Protocol | From Port | To Port | IP Range    | Source Group |
+-------------+-----------+---------+-------------+--------------+
| tcp         | 2222      | 2222    | 0.0.0.0/0   |              |
| tcp         | 443       | 443     | 0.0.0.0/0   |              |
| tcp         | 1         | 65535   | 10.0.1.0/24 |              |
| tcp         | 80        | 80      | 0.0.0.0/0   |              |
| udp         | 1         | 65535   | 10.0.1.0/24 |              |
| tcp         | 3000      | 3500    | 0.0.0.0/0   |              |
+-------------+-----------+---------+-------------+--------------+
```

**Comment by titanous** [comment]
My next suggestion is to ping .1 and .2 (after verifying that .2 is still up) while tcpdumping `flannel.1`, `flynnbr0`, and `eth0` on both sides.

**Comment by adrianmoya** [comment]
Let me see if I got this right: I tcpdumped the 3 interfaces on host flynn-2 and flynn-3 and then pinged 100.100.27.1 and 100.100.27.2 in both servers, finally collected the logs. Is this what you expected?

You can get the results here:
https://dl.dropboxusercontent.com/u/2833685/tcpdump-flynn.tar.gz

**Comment by adrianmoya** [comment]
Hi, I installed again from scratch with kernel `linux-generic-lts-vivid`

The result is the same
 `17:12:48.780683 wait postgres-wait error: bootstrap: timed out waiting for http://postgres-api.discoverd/ping, last response "Get http://postgres-api.discoverd/ping: dial tcp: lookup postgres-api.discoverd: no such host"`

Debug info:
https://gist.github.com/anonymous/2e7f727a4116fd0b245f

Where the tcpdumps useful? Is there a way to change the flannel config to use udp backend instead maybe to test?

**Comment by titanous** [comment]
Sorry for the delay, looks like I missed the issue update somehow.

Looking at the pcaps I see that the data is making it all the way onto `flynnbr0` of flynn-3 as it should. Something is going wrong at the last hop, from `flynnbr0` to the veth interface (`vnet0`) in the container. I'd be interested in the following things:

- The bridge info (`brctl show flynnbr0`) from each of the hosts
- The same tcpdump/ping setup but including the `vnet0` device on the destination host.

**Comment by titanous** [comment]
We poked at this on IRC for a while and it looks like there is some underlying network instability in the OpenStack cluster. Feel free to open a new issue if you have trouble after fixing the network.

**Comment by adrianmoya** [comment]
Updated the whole stack (Base OS+Openstack), and configured using the other network card and got the same results. It's very frustrating. I'm not sure where's the bottleneck, I don't think it's cpu or mem, not sure if I should invest in a SSD maybe? Being a one in all server, network is local to the machine, so I'm not sure what to do to improve network performance.

**Comment by titanous** [comment]
@adrianmoya I don't think an SSD would make a difference, the network IO should not be disk-bound (unless you are swapping). There are a lot of moving parts here, I'm not really sure where to look, perhaps ask around in the OpenStack community?
