### ISSUE TITLE
controller: resource not found

### ISSUE THREAD

**Issue by molisoft** [flynn/flynn#1670]
Hi, 
Run any command returns an error:
```
$ flynn create
controller: resource not found
```

.flynnrc
```
default = "default"

[[cluster]]
  Name = "default"
  GitHost = "app.rkidc.net:2222"
  URL = "http://app.rkidc.net"
  Key = "4297f44b13xxxxxxxxxxxx
  TLSPin = ""
```

flynn-host.log
```
now=2015-07-19T18:02:32+0000 at=logmux_service_watch app=host status=event event=up
now=2015-07-19T18:02:32+0000 app=host at=logmux_service_watch status=event event=leader
now=2015-07-19T18:02:32+0000 at=start backend=libvirt-lxc fn=unbind_mounts job.id=vultr.guest-a9af36d7ed734161b397ba3eaa35ada2 app=host
now=2015-07-19T18:02:32+0000 app=host backend=libvirt-lxc fn=unbind_mounts job.id=vultr.guest-a9af36d7ed734161b397ba3eaa35ada2 at=finish
now=2015-07-19T18:02:32+0000 app=host backend=libvirt-lxc fn=watch_container job.id=vultr.guest-a9af36d7ed734161b397ba3eaa35ada2 at=cleanup_mounts status=finish
INFO[07-20|03:01:17] request started                          component=host req_id=0f9d95927a9e41d4ade8789e3b5e20cb method=GET path=/host/jobs client_ip=45.63.48.101
INFO[07-20|03:01:17] request completed                        component=host req_id=0f9d95927a9e41d4ade8789e3b5e20cb status=200 duration=1.5719ms
```

Why ..?
Thank ..

**Comment by titanous** [comment]
The URL in the config doesn't look correct, it should probably be `"https://controller.app.rkidc.net"`. Did you manually configure it?

**Comment by molisoft** [comment]
@titanous  ...oh! thank you ..
Now return:
```
POST http://controller.app.rkidc.net/keys: httpclient: unexpected status 401
```
Maybe is key error ...
What is a field ..?

**Comment by lmars** [comment]
@molisoft the controller key is in the output of the `flynn-host bootstrap` command that you ran to bootstrap the cluster.

If you no longer have that output you can find the key by running `flynn-host ps` on a node in your cluster, noting the ID of the job with APP=controller TYPE=web, running `flynn-host inspect ID` and the key is in the `ENV[AUTH_KEY]` field.

**Comment by molisoft** [comment]
I got it ..thank you !

**Comment by monaka** [comment]
I got same error and it is caused by the older flynn CLI.
some previous versions may failed to create ```~/.flynnrc``` correctly.
My trouble was fixed after upgrading my flynn CLI and re-run ```flynn cruster add ...```.
