### ISSUE TITLE
Add app metadata to namespaced jobs

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#1675]
It would be nice to add the recently merged `flynn meta` command to `flynn-host`.

Use Case - Would like to see `flynn meta` variables on a flynn host without having to configure a flynn cluster. That way I can use these values as part of a tag to associate with metrics.

**Comment by titanous** [comment]
Currently this metadata is only stored in the controller, but I think it's reasonable to copy it into each job namespaced under the app.

**Comment by titanous** [comment]
I think this would be a good addition to the v2 scheduler, since it will require subscribing to app changes and copying the metadata to every new job.

**Comment by lmars** [comment]
Could add the app metadata to `ExpandedFormation` (which the scheduler keeps in memory) and trigger a formation change when the metadata changes.

Refs #1484, /cc @jzila.

**Comment by titanous** [comment]
@lmars sounds like a plan.

**Comment by titanous** [comment]
I think #2243 at least partially implements this.

**Comment by lmars** [comment]
Job metadata is currently immutable, so I guess the question here is do we want to restart jobs if only the app metadata has changed, or make the metadata mutable?

**Comment by titanous** [comment]
I don't think that's necessary currently.
