### ISSUE TITLE
TestDeploySingleAsync: timed out waiting for postgres formation

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1692]
https://ci.flynn.io/builds/20150804163321-61fd163e

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150813191530-854bd474

**Comment by jvatic** [comment]
https://ci.flynn.io/builds/20150820185758-e5063eb2

**Comment by titanous** [comment]
The build database was inadvertently lost during the migration to new CI infrastructure, let's open new issues when we see flakes.
