### ISSUE TITLE
Demo's `make init` dies when no SSH public key is present

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#1693]
Running `make init` in demo/ without a public key in ~/.ssh/ causes the init process to abort late in the process. A nicer behavior would be to check for its existence ahead of time and warn the user if one does not exist, and instruct the user on how to create one.

```
flynn -c demo-virtualbox key add
open /Users/nobert/.ssh/id_dsa.pub: no such file or directory
make: *** [init] Error 1
```

**Comment by titanous** [comment]
This is now irrelevant, we don't use SSH keys.
