### ISSUE TITLE
Dashboard: trust ephemeral certificate workflow isn't accurate on Chrome/OSX 10.10

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#1695]
The trust certificate workflow needs to be updated, and possibly be more aware of browser/OS version context.

In Chrome (and possibly other browsers) on OSX 10.10 (and possibly other versions) doesn't automatically ask whether or not to trust an imported certificate upon importing it. After import, it has to be selected in Keychain and 'Always Trust' has to be selected from the dropdown.

**Comment by kwando** [comment]
I'm encountering this in chrome on OS X too.
