### ISSUE TITLE
Dashboard: blank screen/no login token after initially importing ephemeral certificate

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#1696]
In Chrome (and possibly other browsers) on OSX 10.10 (and possibly other versions), after running `make dashboard` for the first time and importing+trusting the ephemeral certificate, the user is thrown to a blank screen. Reloading the page gives the user the Login token prompt.

**Comment by lmars** [comment]
This just happened to me:

* Chrome 44.0.2403.155 (64-bit)
* OSX 10.10.3
* flynn-host dev build (commit 9d2ad95)

**Comment by lmars** [comment]
I should add that I did not provide the login token in the URL due to #1722 (and the fact that my dashboard is publicly accessible).
