### ISSUE TITLE
Replace rpcplus with HTTP

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#170]
We currently use a custom RPC protocol for a variety of low-level APIs. In the beginning, when the APIs were changing often, this made a lot of sense, but the APIs have not changed very much recently and there isn't a ton of surface area.

For a variety of reasons (introspection, interoperability, etc.) I think it's worth considering switching these APIs from rpcplus to JSON over HTTP.

The main point against HTTP is that we can't easily multiplex multiple streams and requests on a single TCP connection (discoverd would be hit the hardest by this). This problem is already solved by HTTP/2, though I'm not sure if there are any viable packages available currently. I think it makes sense to use server-sent events for streams, as they become trivially available in browsers as well (we already use them in the controller).

Please comment if you have any thoughts about this.

**Comment by archSeer** [comment]
@titanous for multiplexing streams https://github.com/inconshreveable/muxado

**Comment by archSeer** [comment]
Closing as this was resolved with #663

**Comment by archSeer** [comment]
Actually, this is technically not resolved until the discoverd rewrite lands and we completely drop rpcplus from the repository.
