### ISSUE TITLE
HTTP endpoint for creation of apps [POST `/apps`] seems missing

### ISSUE THREAD

**Issue by kgrz** [flynn/flynn#1701]
https://github.com/flynn/flynn/compare/master...kgrz:master

I'm just starting out with flynn and noticed that the HTTP endpoint for creation of an app is missing. The `client.go` file implements `CreateApp` function, but that's not exposed over HTTP? Is this intentional?

PS:  I haven't yet tested out the code above yet. Will post an update as and when I do.

**Comment by titanous** [comment]
This call to the `crud` helper handles that: https://github.com/flynn/flynn/blob/7990ad529885b11ab5e2a714120ee3da0cb020a0/controller/controller.go#L165

**Comment by kgrz** [comment]
@titanous Ah! Thanks for the clarification.
