### ISSUE TITLE
Error deploying app release

### ISSUE THREAD

**Issue by JMSwag** [flynn/flynn#1704]
After initial cluster creation I'm able to successfully upload 16 apps. Any subsequent git push calls, to an app already deployed, results in an error. I've attempt @lmars suggestion in https://github.com/flynn/flynn/issues/1682 to no avail.

[Debug logs](https://gist.github.com/anonymous/bab64939a277c4376429)

```
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 859 bytes | 0 bytes/s, done.
Total 6 (delta 4), reused 0 (delta 0)
-----> Building ilink...
-----> Python app detected
-----> Installing dependencies with pip

-----> Preparing static assets
       Collectstatic configuration error. To debug, run:
       $ heroku run python manage.py collectstatic --noinput

-----> Discovering process types
       Procfile declares types -> web
-----> Compiled slug size is 42M
-----> Creating release...
remote: Error deploying app release: validation_error: Cannot create deploy, there is already one in progress for this app.
To ssh://git@f.jmsapps.net:2222/ilink.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@f.jmsapps.net:2222/ilink.git'
```

**Comment by lmars** [comment]
@JMSwag it looks like your postgres cluster broke and then subsequently recovered at `2015-08-09T03:37:25` but the controller workers don't seem to be doing any work (the workers receive work from postgres).

Can you please send the worker processes (i.e. anything running `/bin/flynn-worker` on any host) a `SIGQUIT` signal and then re-run `flynn-host collect-debug-info`?

(On the host you ran the previous debuf-info command on, the worker has PID 27169 so you can SIGQUIT it like `sudo kill -SIGQUIT 27169`).

I suspect that once you have killed the current workers, the new ones that start will allow you to do a deployment, so it's worth trying again.

**Comment by JMSwag** [comment]
[Debug info](https://gist.github.com/c36feba28ef6cca1689b), generated after completing the requested steps.

**Comment by lmars** [comment]
@JMSwag ok thanks for that, I can't see anything unusual in the backtraces of each of the workers, and the new workers have not picked up any deployment jobs as I would have expected.

Please gist the output of the following two commands (run from your machine):

```
flynn -a controller pg psql -- -c "SELECT * FROM deployments"
flynn -a controller pg psql -- -c "SELECT * FROM que_jobs"
```

**Comment by JMSwag** [comment]
@lmars NP, here are the [logs](https://gist.github.com/JMSwag/a91e6f93783905da09bf)

**Comment by lmars** [comment]
@JMSwag ah ok, I can see the issue now. We don't currently create the deployment record and enqueue the deployment job in a DB transaction (see #1709), and your initial deployment failed to be added to the queue due to the postgres recovery, with the following error in the controller log:

```
t=2015-08-09T18:29:41+0000 lvl=eror msg="write tcp 100.100.60.2:5432: connection timed out" component=controller req_id=ee2872e8370141d781975bbbfff7df6f
```

We will work on a fix, but you should be able to mark the deployment as finished and do another deployment:

```
flynn -a controller pg psql -- -c "UPDATE deployments SET finished_at = now() WHERE deployment_id = '153363d4-8696-47df-9e3a-6a4b544507db'"
```

Let us know if you still have issues.

**Comment by JMSwag** [comment]
@lmars marking the deployment as finished allowed me to deploy successfully. Thank you
