### ISSUE TITLE
Recovery after reboot

### ISSUE THREAD

**Issue by Vaultman** [flynn/flynn#1714]
I run single node Flynn installation on a powerful dedicated machine. Is there any way to tell Flynn (or do it manually) to start all apps after server reboot?

**Comment by kwando** [comment]
you need to uncommet the start-on and the respawn lines in /etc/unit/flynn-host.conf

Then it should work. Rebooting/restarting flynn is not well tested so be careful.

**Comment by titanous** [comment]
This is now fixed.
