### ISSUE TITLE
Old build being deployed.

### ISSUE THREAD

**Issue by meteormanaged** [flynn/flynn#1721]
Interested to see if this is reproducible.

1. Commit repo
2. Push to flynn.
3. Via dashboard, change web processes to 0 and save.
4. Change code and commit repo.
5. Push to flynn (build successful).
6. Via dashboard, change web processes to 1 and save.

Commit from Step 1 runs.

**Comment by lmars** [comment]
@meteormanaged I reproduced this and the issue is that the dashboard does not stay in sync with the cluster, so when you scale back up to 1, the dashboard scales the old release.

A fix is being tracked by #1560, for now you will need to refresh the dashboard page before scaling.
