### ISSUE TITLE
dashboard: Login token is transmitted in plain text

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1722]
The bootstrap log message includes a link to the dashboard containing the login token, and the link does not use TLS:

```
Flynn bootstrapping complete. Install the Flynn CLI (see https://flynn.io/docs/cli for instructions) and paste the line below into a terminal window:

flynn cluster add -g example.com:2222 -p oAwLWGAdZrFT9a2oAsHMkDu1iwcxJI9mUS/Xd9ekRN4= default https://controller.example.com 1e554aad5c81f3cfabcd9e3919e08d1f

The built-in dashboard can be accessed at http://dashboard.example.com/login?token=8b7f259663c5877b0f6e5a59bbdf7c14
```

/cc @jvatic

**Comment by jvatic** [comment]
@lmars this is because the CA certificate needs to be installed before https will work.

**Comment by lmars** [comment]
@jvatic yep I get that, but why put the login token in the non-TLS link? I had to copy-and-paste the login token anyway (probably due to #1696).

**Comment by jvatic** [comment]
@lmars You shouldn't have to copy the login token again if it's present in the URL before installing the cert. #1696 only occurs for me when the login token is absent. It was added to the URL to reduce the number of copy/paste steps.

**Comment by lmars** [comment]
OK, but given anyone acquiring my login token would have free rein over my cluster, I don't think I should be encouraged to transmit it via plain text, even if just the once.

**Comment by jvatic** [comment]
@lmars When installing the cert in this manner you're already open to being man in the middled. We should probably add a command to the cli for installing the cert securely and prompt to change the token when provided via an http URL param.

**Comment by jvatic** [comment]
Opened #1724 to track the cli command. #1723 is also relevant as it should remove the need to use this step (the installer securely downloads the cert and transmits the token to the dashboard over https).

**Comment by jvatic** [comment]
I think the dashboard instruction can be changed to use the cli as part of #1724.

**Comment by titanous** [comment]
Since intercepting the login token is a passive attack, and changing the CA certificate is an active attack, we should revert to the separate token copy/paste step for now. Passive attacks are easy and invisible, active attacks are harder and there is a chance of discovery.
