### ISSUE TITLE
Load balancing strategy based on active connections count

### ISSUE THREAD

**Issue by pesho** [flynn/flynn#1727]
According to [router/README.md](https://github.com/flynn/flynn/blob/master/router/README.md) the Flynn `router` "acts as a standard reverse proxy with random load balancing". In some scenarios this is suboptimal. For example, assume we have several processes running which serve persistent Websocket connections. The load spikes, we add some new hosts to the cluster, and scale additional processes on them. Ideally, the routers should point new connections to the new processes, until their load (number of connections) reaches the same level as the old ones. A purely random strategy cannot achieve that.

It would be great if each router maintains a table with the number of active connections to each process, and uses that table to decide which process should handle a new connection. Note that such a table does not need to be cluster-global, it's enough to have separate tables per router (which is a much easier task).

**Comment by lmars** [comment]
FYI see #966 for a discussion on approaches (and difficulties) for the router keeping track of active connections.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
