### ISSUE TITLE
Automatically provision custom hostnames on popular DNS providers

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#1728]
Currently, support for using one's own domain requires either a CNAME to the provisioned flynnhub.com hostname, or manually adding A records for each of the cluster's hosts. Ideally, we could provision a hostname for the cluster and for each app within that cluster, and manage those hostnames as the cluster members change.

Off the top of my head I'd see support for Amazon Route 53, Google DNS, DNSimple, DNSmadeeasy, and Dyn.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
