### ISSUE TITLE
appliance/postgresql: Allow customisation of PostgreSQL settings

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#1740]
It's necessary to adjust settings like `shared_buffers`, `max_connections` and `work_mem` in order to tune PostgreSQL effectively for a given workload.

**Comment by onnimonni** [comment]
Somewhere in the future we could have a way to calculate the total max memory usage of user selected configs for the appliance in order to warn users if their configs are possibly dangerous because their system only has limited amount of ram.

This would be useful at least in mysql/mariadb.

**Comment by joeczucha** [comment]
Was there ever any update on this? I've an app that could do with more than the 4MB default work_mem. Thanks

**Comment by philiplb** [comment]
I think this feature has a PR with https://github.com/flynn/flynn/pull/3425 but it is a bit stuck since the 13th of february.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
