### ISSUE TITLE
Switch git from SSH to HTTPS 

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1744]
I believe we should change gitreceived to use the Smart HTTP(S) transport instead of SSH. This has a number of benefits, and basically no downsides.

For starters, here are some of the benefits:

1. No more `flynn key add` step (potentially requiring SSH key generation). We can preconfigure/generate credentials of many different types (including TLS client certificates) automatically without user knowledge.
1. The git push/pull streams will go through the router's HTTP stack, which means that technically only port 443 needs to be exposed to get useful Flynn functionality. (this will also be helpful for those that can't use "weird" protocols or need to proxy all network traffic)
1. We can easily and securely pre-pin the CA certificate using git's configuration options, this is way easier than trying to wrangle SSH configs.
1. It will be trivial to add all sorts of alternative auth mechanisms using `gitcredentials(7)` and the associated configuration options. This should allow two-factor auth, macaroons, and arbitrary SSO integration. Doing this with SSH would be annoying to say the least.
1. SSH configurations are very user-centric, programmatic management of them is hard for a variety of reasons, Git's HTTP support is the opposite.
1. Less crypto is in play, we won't have to audit the SSH library, only the TLS library which we already use for everything else.
1. Less code should be required to handle the push, for example: https://gitlab.com/gitlab-org/gitlab-git-http-server/blob/master/main.go
1. We already use HTTP(S) everywhere else, this is one less protocol we need to be able to understand and debug.

I can't really think of any real downsides, I do think that we should drop SSH support right away, since there's no reason to keep two protocols in play.

Any thoughts @lmars @nobert @temujin9?

**Comment by lmars** [comment]
SGTM

**Comment by temujin9** [comment]
+1, though I'll need #1647 at the same time (as my current "maintenance mode" relies on port blocking).

**Comment by nobert** [comment]
I do support this, but don't we still need to use SSH for bootstrapping Flynn on platforms that don't support booting from custom images?

**Comment by titanous** [comment]
@nobert Yeah, but that's a completely separate thing. We use SSH in the installer, but the key management is completely invisible to the user and we don't use OpenSSH as the client.
