### ISSUE TITLE
controller: Use PostgreSQL appliance for controller tests

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1751]
Controller tests currently rely on PostgreSQL to already be running, leading to us installing it in both [the Vagrantfile](https://github.com/flynn/flynn/blob/v20150825.0/Vagrantfile#L101-L106) and [the test rootfs](https://github.com/flynn/flynn/blob/v20150825.0/test/rootfs/setup.sh#L131-L135), but they should instead use the appliance (which is what the controller actually uses) to avoid version differences.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
