### ISSUE TITLE
host/discoverd: Support pluggable discovery mechanisms

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#1767]
It would be useful if flynn-host/discoverd could be bootstrapped using various discovery mechanism to determine the initial list of peers to connect to, namely:
- Using an external discoverd/etcd/zookeeper cluster
- AWS Tags or Autoscaling Groups (similar for GCE/Azure)

This is in contrast to the current discovery system which is single use as it's unable to determine if machines that connected have since become unavailable.

**Comment by munhitsu** [comment]
+1 on AWS Tags

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
