### ISSUE TITLE
After flynn-host update, dashboard can no longer find or display log files for existing apps

### ISSUE THREAD

**Issue by meteormanaged** [flynn/flynn#1774]
newly deployed apps logs show up as expected in dashboard.

**Comment by titanous** [comment]
This is a known issue, the log aggregator does not currently have replication.

**Comment by meteormanaged** [comment]
Single host deployment so I'm not sure that it would require replication?

**Comment by lmars** [comment]
@meteormanaged the log aggregator stores logs in memory, so without replication, the logs are lost after a deployment.
