### ISSUE TITLE
Dashboard memory leak

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#1776]
Run ```siege -b http://dashboard.mycluster.com``` for a while and watch ```flynn-dashboard``` eat up you memory.

Memory and CPU usage stays high when stopping the siege.

**Comment by kwando** [comment]
```flynn-node login: [257321.106418] Out of memory: Kill process 4018 (flynn-dashboard) score 279 or sacrifice child
[257321.107153] Killed process 4018 (flynn-dashboard) total-vm:305620kB, anon-rss:292808kB, file-rss:0kB```

**Comment by kwando** [comment]
From syslog:
```
Sep 17 06:40:30 flynn-node kernel: [767587.485629] Out of memory: Kill process 29895 (flynn-dashboard) score 252 or sacrifice child
Sep 17 06:40:30 flynn-node kernel: [767587.486534] Killed process 29895 (flynn-dashboard) total-vm:277320kB, anon-rss:264580kB, file-rss:0kB
```
This appears to happen even when I'm not actively using the dashboard... furthermore flynn does **not** restart the dashboard server once it is killed by the OS.

**Comment by jvatic** [comment]
I've confirmed there is a memory leak, CPU usage does subside. Interestingly, memory usage rises fastest when running `siege -b http://dashboard.mycluster.com/ping` which leads me to believe the in-memory assets are not to blame. I think a good starting point is to switch away from martini (#992).

**Comment by jvatic** [comment]
The `/ping` endpoint is no longer effected, still tracking down the source of the leak.

**Comment by jvatic** [comment]
Memory usage appears to stabilize over time. If you'd like to inspect what's going on, set `GODEBUG=gctrace=1` for the dashboard app.

**Comment by kwando** [comment]
Will this change be in if I rebuild my cluster tomorrow? I'd like to get rid of the ugly cronjob that scales down and up the dashboard app once every day xD

**Comment by titanous** [comment]
Yeah, as long as the nightly build succeeds.

**Comment by kwando** [comment]
This is still an issue.

```
ubuntu@flynn-node:~$ flynn-host version
v20151104.1
```

![htop](https://cloud.githubusercontent.com/assets/891566/11621579/f4b5616c-9cbd-11e5-833d-dd0f8482c286.jpg)

**Comment by jvatic** [comment]
@kwando does it's usage continue to grow, or remain relatively steady?

**Comment by kwando** [comment]
@jvatic well, after restarting the dashboard app (scale web=0, scale=1)  and clicking around in the UI ```htop``` shows memory usage of ```0.3 %```.  I left it unattended for 4 days and then memory consumption was near ```25 %``` on the same server (2GB RAM).

**Comment by jvatic** [comment]
I've narrowed this down to a memory leak in the session store we use (opened upstream issue: https://github.com/gorilla/sessions/issues/59).

**Comment by kwando** [comment]
@jvatic good work!
