### ISSUE TITLE
Support RHEL 8

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#1791]
Support installing Flynn on RHEL 8 and friends (Centos, Scientific Linux, Fedora, etc.).
- [x] Change AUFS to OverlayFS. AUFS is not supported in RHEL without using third-party kernels or compiling the kernel by hand. OverlayFS is available in RHEL 7.1 as a technology preview.
- [x] Add unit file for systemd.
- [ ] Update install script to use RHEL package manager, RHEL package names.

**Comment by charliewolf** [comment]
+1

**Comment by sebilasse** [comment]
:+1:

**Comment by thomasfedb** [comment]
@titanous how difficult is the change from AUFS to OverlayFS? The other changes are something I could probably contribute.

**Comment by titanous** [comment]
@thomasfedb It is non-trivial, but we'll be starting on it soon.

**Comment by SolarisYan** [comment]
how to install flynn on centos?
![image](https://cloud.githubusercontent.com/assets/8148762/13340905/063377b2-dc6f-11e5-9451-7aa7896add4b.png)

**Comment by titanous** [comment]
@SolarisYan Not currently possible, that's what this issue is about.

**Comment by SolarisYan** [comment]
@titanous get it, thank you

**Comment by fire** [comment]
Is it possible to update this issue for RHEL8 CENTOS8?

**Comment by thomasfedb** [comment]
> Is it possible to update this issue for RHEL8 CENTOS8?

Done!

**Comment by tokyodevs** [comment]
please clearify when we can expect the centos8 support for flynn?

**Comment by lmars** [comment]
@tokyodevs I'd be happy to point you at what needs to change if you're willing to contribute?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
