### ISSUE TITLE
Need to use the -a switch when importing an exported app

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#1797]
If an app is exported into a git repo I need to use the ```-a``` switch on the import command otherwise I get ```no apps in git remotes```.
```
$ flynn -c mycluster import -f app.tar
0 B / 17.31 MB [---------------------------------------------------------------------------------------------------------------------------------------] 0.00 % 
no apps in git remotes
```

``` 
$ flynn -c mycluster -a simple-app import -f app.tar                                                                                                           ✘
17.31 MB / 17.31 MB [================================================================================================================] 100.00 % 1005.44 KB/s 17s
```

**Comment by lmars** [comment]
@kwando we recently switched to using HTTP based git remotes, which included a change to how we detect those. If you bootstrapped a new cluster and ran `flynn cluster add`, the CLI was likely no longer able to identify the app from the old SSH remote, as it now expected a HTTP remote.

Can you try this one more time, not what you should be using a HTTP remote?

**Comment by kwando** [comment]
I do not think the change to HTTP is the issue. The issue is that flynn needs to have the app name when importing.

I need to provide the -a switch with the same name as the exported app had, even though the name is provided in the app.json file inside tar file. Using a name that do not match the app name in that file results in an error.

```
flynn -c mycluster -a whatever import -f app.tar 
0 B / 17.06 MB [---------------------------------------------------------------------------------------------------------] 0.00 % 0
error uploading slug: POST https://<cluster-host>/apps/whatever/jobs: httpclient: unexpected status 404
```

The command sequence I'm using is:
```
flynn -c mycluster create app
git push flynn master
flynn -c mycluster export -f app.tar
flynn -c mycluster delete -y
flynn -c mycluster import -f app.tar # => no apps in git remotes
flynn -c mycluster -a app import -f app.tar # => successful import
```
I know the delete command removes the git remote and thus makes flynn unable to guess my app name.

It would be a UX improvement if the import command A) read the name from the tar file instead B) asked me if I want to setup a remote in the git repo.

**Comment by titanous** [comment]
Ah, it looks like there may be a bug here, I'll fix it. I'll also add support for creating the git remote.
