### ISSUE TITLE
error: RPC failed

### ISSUE THREAD

**Issue by JMSwag** [flynn/flynn#1799]
Output from git push flynn master:
```text
Counting objects: 509, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (471/471), done.
Writing objects: 100% (509/509), 7.62 MiB | 1.14 MiB/s, done.
Total 509 (delta 187), reused 0 (delta 0)
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
No app release, specify a release with --release
```

Debug: https://gist.github.com/anonymous/109049e1f7e71c417183

Similar issue, different project: https://github.com/douban/gpack/pull/2

**Comment by titanous** [comment]
Does this happen consistently with this repo, all repos for this cluster, or intermittently?

**Comment by JMSwag** [comment]
8 of 15 repos on this 3rd cluster. The first 2 times I brought up a cluster, I noticed the error on the first repo push but didn't count how many repos threw errors.

**Comment by titanous** [comment]
Do the exact same repos cause trouble on other clusters? Are any of the problematic repos public? Does this happen for every push of the "broken" repos but never for others on the same cluster?

**Comment by JMSwag** [comment]
I'll have to test again to see if the same repo's are causing trouble on each cluster. Here's a [repo](https://dl.dropboxusercontent.com/u/10991186/jmsapps.zip) that gives me trouble. It happens on every push.

**Comment by titanous** [comment]
Reproduced locally! Looking into it, thanks! /cc @temujin9

**Comment by titanous** [comment]
I've made some progress on this, I have a sysdig trace and I've started going through it. It looks like the initial git repo is corrupt, possibly after a round-trip through the blobstore.

```text
24961 01:54:21.883103085 3 git (7250) > stat
24962 01:54:21.883111467 3 git (7250) < stat res=0 path=/tmp/repo-9144191d-6cde-40d9-b2ba-e662ef3a500a913702210/.git
24963 01:54:21.883116703 3 git (7250) > access
24964 01:54:21.883132558 3 git (7250) < access
24965 01:54:21.883134140 3 git (7250) > stat
24966 01:54:21.883136763 3 git (7250) < stat res=0 path=/tmp/repo-9144191d-6cde-40d9-b2ba-e662ef3a500a913702210
24967 01:54:21.883138714 3 git (7250) > access
24968 01:54:21.883144222 3 git (7250) < access
24969 01:54:21.883145603 3 git (7250) > stat
24970 01:54:21.883157279 3 git (7250) < stat res=-2(ENOENT) path=/tmp/repo-9144191d-6cde-40d9-b2ba-e662ef3a500a913702210.git/.git
24971 01:54:21.883158973 3 git (7250) > stat
24972 01:54:21.883161138 3 git (7250) < stat res=-2(ENOENT) path=/tmp/repo-9144191d-6cde-40d9-b2ba-e662ef3a500a913702210.git
24973 01:54:21.883168398 3 git (7250) > write fd=2(<p>) size=104
24974 01:54:21.883173626 3 git (7250) < write res=104 data=
	0x0000: 6661 7461 6c3a 2027 2f74 6d70 2f72 6570  fatal: '/tmp/rep
	0x0010: 6f2d 3931 3434 3139 3164 2d36 6364 652d  o-9144191d-6cde-
	0x0020: 3430 6439 2d62 3262 612d 6536 3632 6566  40d9-b2ba-e662ef
	0x0030: 3361 3530 3061 3931 3337 3032 3231 3027  3a500a913702210'
	0x0040: 2064 6f65 7320 6e6f 7420 6170 7065 6172   does not appear
```

My instinct says that this is related to the total size of the repo. Will resume investigation in the morning.

**Comment by kwando** [comment]
Good that you can reproduce this, cause I'm hitting that error too.

**Comment by kwando** [comment]
I'm no longer hitting this issue with a new cluster. Good job! =)

**Comment by JMSwag** [comment]
@titanous Thank you sir!
