### ISSUE TITLE
router,gitreceived: Connections hang indefinitely if gitreceived goes away

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#1808]
As part of debugging why #1747 was failing we discovered that the git client never disconnects from the router when gitreceived goes away, for instance during a deployment.

We expect the HTTP/TCP connection to be closed between the client and the router when this occurs to prevent the indefinite hang.

**Comment by lmars** [comment]
For a failing test:

* create an inline buildpack which blocks
* git push (background)
* deploy gitreceive
* check git push exited (or ideally got re-pushed, but thats asking a lot)

**Comment by titanous** [comment]
This is a git bug, a tcpdump shows that the request ends properly. Given that this should be pretty rare, I'm closing it.
