### ISSUE TITLE
Add easy procedure for migrating CLUSTER_DOMAIN

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1816]
Users shouldn't be stuck with the `CLUSTER_DOMAIN` after bootstrap.

**Comment by jvatic** [comment]
Proposal:

Add `PUT /domain` route to controller which performs the following:

- Generate new TLS certificate for the controller
- Deploy the following apps with updated env:
  - controller: `CA_CERT`, and `DEFAULT_ROUTE_DOMAIN`
  - router: `TLSCERT` and  `TLSKEY`
  - dashboard: `CA_CERT`, `DEFAULT_ROUTE_DOMAIN`, `CONTROLLER_DOMAIN`, and `URL`
- For all routes with the old cluster domain as the suffix, create a new one with the new cluster domain, then delete the old route

Should any of the above steps fail, it should attempt to restore things to their previous state.

This should be exposed through the cli which should call the controller endpoint then update local config. The installer and dashboard should also expose this, though those can be their own issues.

**Comment by titanous** [comment]
This should be done in an idempotent background job (specifying the current and new domain), as the controller (including the worker process) will be restarted when the new env vars are set. The old routes should not be deleted.
