### ISSUE TITLE
Cluster was broken after rebooting one node.

### ISSUE THREAD

**Issue by monaka** [flynn/flynn#1836]
I installed Flynn to 3 nodes Ubuntu 14.10 cluster on Azure.
I did 'apt-get update / upgrade' but I didn't do 'apt-get install' any new packages.
At the first, they worked well.
But after I reboot one node, the node didn't start containers up.
Where can I get the best way to reboot nodes?

The log of rebooted node. 
https://gist.github.com/anonymous/27d6ab28aebd02e7b43c

Another nodes.
https://gist.github.com/24e8fccdbca23266c1e3
https://gist.github.com/6e1e0600d1b82e2daf01

**Comment by kwando** [comment]
sudo start flynn-host

Flynn does not automatically boot on startup.. see /etc/init/flynn-host

AFAIK rebooting nodes is very hit and miss at the moment, sometimes it works.. other times the whole cluster dies.

**Comment by monaka** [comment]
@kwando I forgot to write it. I edited /etc/init/flynn-host before rebooting (```respawn limit 1000 60``` enabled.)
And I did ```sudo restart flynn-host``` also.

I found #1508 out after I created this issue.
Is it working on progress the cluster resurrection? Is it better to use on single node for now?

**Comment by monaka** [comment]
I tried dozens of shutdown and re-install. I got a trend.
A full resurrections of the cluster are quite rare for now. (less than 10% on my env.)

Scheduler, flannel, etcd, discoverd will be restarted on reboot.
Postgres may be restarted with lesser possibility.
Another apps (git related and so on) are almost not.

**Comment by titanous** [comment]
Yes, there are some known issues around this: #1714, #1789, #1428 

We will resolve them in the near future.
