### ISSUE TITLE
Deployment on Ubuntu 14.04 cluster

### ISSUE THREAD

**Issue by ashkarin** [flynn/flynn#1839]
Hi,

I cant to run Flynn on a cluster of Ubuntu VM 14.04. Hope for your help.

**Setup:**
1. Host machine with OpenSuse (holds a configured DNS)
2. Three nodes under Ubuntu VM (ubuntu/trusty64) launched with Vagrant in a private netwrok:
```
config.vm.network "private_network", ip: "192.168.10.2" -- Node 1
config.vm.network "private_network", ip: "192.168.10.3" -- Node 2
config.vm.network "private_network", ip: "192.168.10.4" -- Node 3
```
From all three nodes I can ping CLUSTER_DOMAIN (in my case: cluster.myflynn), which was configured as requested [ https://flynn.io/docs/installation ]. Here is the ping for Node 1:
```
node1$ ping cluster.myflynn
PING cluster.myflynn (192.168.10.4) 56(84) bytes of data.
64 bytes from 192.168.10.4: icmp_seq=1 ttl=64 time=0.387 ms

node1$ ping cluster.myflynn
PING cluster.myflynn (192.168.10.3) 56(84) bytes of data.
64 bytes from vagrant-ubuntu-trusty-64 (192.168.10.3): icmp_seq=1 ttl=64 time=0.017 ms
```

**Steps:**
On the first node:
```
sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
sudo flynn-host init --init-discovery
__CODE__
```
On the 2nd and 3rd nodes:
```
sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
sudo flynn-host init --discovery __CODE__
```
On the 1st, 2nd and 3d node:
```
sudo start flynn-host
```

**Other:**
I have found out that no etcd run, however it was said that Flynn uses it.
Debug output for node 1: https://gist.github.com/ashkarin/67224dcbc6cc32e0490c
Debug output for node 2: https://gist.github.com/ashkarin/586f1f884ec381dfb4fb

Thanks :)

**Comment by titanous** [comment]
Did you run the bootstrap step as described in the documentation?

**Comment by ashkarin** [comment]
@titanous Sorry, I forgot to mention it. Yes, I start the bootstrap on Node1:
```
node1$ sudo CLUSTER_DOMAIN=cluster.myflynn flynn-host bootstrap --min-hosts 3 --discovery __CODE__
13:38:27.712961 check online-hosts
13:38:57.827748 check online-hosts error: timed out waiting for 3 hosts to come online (currently 0 online)
```

I also tried to clean up nodes with the following commands and repeat, but it didn't help.
```
sudo stop flynn-host
sudo rm /var/lib/flynn/host-state.bolt
sudo rm /var/log/upstart/flynn-host.log
```

**Comment by titanous** [comment]
Okay, please run the install script again with `--clean` and generate a new discovery token. If it doesn't work, make sure you post the `flynn-host` log from each host.

**Comment by ashkarin** [comment]
@titanous Done, here are commands again. Please fine logs in the end of the message.
1. Init Node1 to get discovery key, init other nodes with obtained key
2. Start flynn-host at Node 1, 2, 3
3. Run bootstrap on Node 1

```
node1$  sudo flynn-host init --init-discovery
https://discovery.flynn.io/clusters/d5b084a9-897b-47d1-9a46-833f5807fdbc
node2$ sudo flynn-host init --discovery https://discovery.flynn.io/clusters/d5b084a9-897b-47d1-9a46-833f5807fdbc
node3$ sudo flynn-host init --discovery https://discovery.flynn.io/clusters/d5b084a9-897b-47d1-9a46-833f5807fdbc

node1$ sudo start flynn-host
flynn-host start/running, process 9147
node2$ sudo start flynn-host
flynn-host start/running, process 3542
node3$ sudo start flynn-host
flynn-host start/running, process 3547

...10 seconds after...

node1$ sudo status flynn-host
flynn-host start/running, process 9147
node2$ sudo status flynn-host
flynn-host start/running, process 3542
node3$ sudo status flynn-host
flynn-host start/running, process 3547

node1$ sudo CLUSTER_DOMAIN=cluster.myflynn flynn-host bootstrap --min-hosts 3 --discovery https://discovery.flynn.io/clusters/d5b084a9-897b-47d1-9a46-833f5807fdbc
14:02:11.746557 check online-hosts
14:02:41.962903 check online-hosts error: timed out waiting for 3 hosts to come online (currently 0 online)
```
Here are logs and results of ```ps faux```:
Node 1: https://gist.github.com/ashkarin/2c6b9e4f844d8e24b118
Node 2: https://gist.github.com/ashkarin/98380bb846dce3b278ad
Node 3: https://gist.github.com/ashkarin/0fce8f6c620f5b27c71d

**Comment by titanous** [comment]
Would you please check the IP addresses of your nodes? All of them are getting the same discovery instance ID, so I suspect the IPs are the same.

**Comment by titanous** [comment]
Specifically `10.0.2.15`.

**Comment by titanous** [comment]
The solution is to pass `--external-ip` to each `flynn-host init` call.

**Comment by ashkarin** [comment]
@titanous Thank you! The solution works. :+1:
