### ISSUE TITLE
Deployment on Ubuntu 14.04 cluster [ timed out waiting for hosts to come up ]

### ISSUE THREAD

**Issue by ashkarin** [flynn/flynn#1840]
Hi,

the previous [isse with deployment](https://github.com/flynn/flynn/issues/1839) has been resolved, however I faced up with the next one. First, I got the same error as in [Issue 1827](https://github.com/flynn/flynn/issues/1827), but it was resolved after running the install script again with ``--clean`` and generating a new discovery token.

For my setup, please look the [Issue 1839](https://github.com/flynn/flynn/issues/1839).

After fresh installation I got another issue:
```
node1$ sudo CLUSTER_DOMAIN=cluster.myflynn flynn-host bootstrap \
 --min-hosts 3 --discovery __TOKEN__

14:54:59.762631 check online-hosts
14:55:05.382428 require-env require-env
14:55:05.382907 run-app etcd
14:55:05.619708 run-app flannel
14:55:05.886757 run-app discoverd
14:55:06.040955 wait-hosts wait-hosts
14:56:06.483596 wait-hosts wait-hosts error: bootstrap: timed out waiting for hosts to come up
```

Here are the logs related to the time period (part of log was removed):
Node 1: https://gist.github.com/ashkarin/ee971fdc41fd0e2f08a1
Node 2: https://gist.github.com/ashkarin/8a399d814e37315d6ddf
Node 3: https://gist.github.com/ashkarin/1ac035971118b00c5731

In the logs you can see errors:
Node 1:
```
now=2015-09-08T14:55:05+0000 volumeID=8ec80ab9-17c0-4de1-93f1-54880d835423 app=host err="invalid argument" at=unmount target=/data job.id=vagrantubuntutrusty64-3d962800-6b59-44a0-9dcb-f6caf944e0d0 backend=libvirt-lxc fn=unbind_mounts status=error
now=2015-09-08T14:55:05+0000 backend=libvirt-lxc fn=unbind_mounts at=finish app=host job.id=vagrantubuntutrusty64-3d962800-6b59-44a0-9dcb-f6caf944e0d0
ERRO[0063] Removing active id tmp-vagrantubuntutrusty64-3d962800-6b59-44a0-9dcb-f6caf944e0d0 
```
Node 2:
```
now=2015-09-08T14:56:05+0000 status=error err="invalid argument" at=unmount file=resolv.conf fn=unbind_mounts job.id=vagrantubuntutrusty64-da2472f0-0468-4362-af42-986932d9e635 backend=libvirt-lxc app=host
now=2015-09-08T14:56:05+0000 job.id=vagrantubuntutrusty64-da2472f0-0468-4362-af42-986932d9e635 backend=libvirt-lxc at=finish app=host fn=unbind_mounts
ERRO[0120] Removing active id tmp-vagrantubuntutrusty64-da2472f0-0468-4362-af42-986932d9e635 
```

Node 2:
```
now=2015-09-08T14:56:06+0000 err="invalid argument" app=host backend=libvirt-lxc fn=unbind_mounts job.id=vagrantubuntutrusty64-1b7571c2-4f21-4068-bf42-cced29d366d5 at=unmount file=resolv.conf status=error
now=2015-09-08T14:56:06+0000 backend=libvirt-lxc fn=unbind_mounts at=finish job.id=vagrantubuntutrusty64-1b7571c2-4f21-4068-bf42-cced29d366d5 app=host
ERRO[0119] Removing active id tmp-vagrantubuntutrusty64-1b7571c2-4f21-4068-bf42-cced29d366d5 
```

Thanks. :)

**Comment by titanous** [comment]
Please run `flynn-host collect-debug-info` on each host and post the result.

**Comment by ashkarin** [comment]
@titanous Here is it.
Node 1: https://gist.github.com/c2fc2e1f22b14b28163d 
Node 2: https://gist.github.com/97c2f6823dee8412dae0
Node 3: https://gist.github.com/e79980e088a20a932169

**Comment by titanous** [comment]
It looks like etcd is failing in some way, but I'm not sure why. We're actually in the midst of replacing etcd and should be merging the new code today, I'd suggest trying again tomorrow (or if you're feeling really adventurous, build off of #1612).

**Comment by ashkarin** [comment]
@titanous Okay, thank you! Then I will try it after merge. :+1:

**Comment by titanous** [comment]
Closing, as we no longer use etcd.
