### ISSUE TITLE
ci: TestOmniJobs failing due to router blocking on startup

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1855]
`TestOmniJobs` is consistently failing in CI when [adding a new host](https://github.com/flynn/flynn/blob/master/test/helper.go#L194-L229) because the router is blocking before it gets chance to register in discoverd.

I sent a SIGQUIT to the router and here is the result (from [this build](https://ci.flynn.io/builds/20150910211937-8611f399)):

https://gist.github.com/lmars/851a209412cc653f9044

The router is blocked starting the HTTP listener (specifically at [startSync](https://github.com/flynn/flynn/blob/master/router/http.go#L94)), and following the goroutines, [setting initial routes](https://github.com/flynn/flynn/blob/master/router/data_store.go#L223-L227) is blocked [creating a service cache](https://github.com/flynn/flynn/blob/master/router/http.go#L227) (specifically [waiting for a current event](https://github.com/flynn/flynn/blob/master/discoverd/cache/cache.go#L95)).

**Comment by titanous** [comment]
@benbjohnson Can you think of a reason why the current event consistently wouldn't be sent?

**Comment by lmars** [comment]
Also, `TestOmniJobs` does not fail when run by itself.

**Comment by titanous** [comment]
I wonder if the stream isn't getting proxied correctly?

**Comment by benbjohnson** [comment]
I've been looking through the code but I don't see any reason why it would work when it runs by itself and not with the other tests. Does `TestOmniJobs` not run as a proxy when it's run alone?

**Comment by lmars** [comment]
The issue is that `http.Client` does not maintain headers through a redirect (see https://github.com/golang/go/issues/4800 and [the redirect logic](https://github.com/golang/go/blob/master/src/net/http/client.go#L351-L373)), so stream requests to a discoverd proxy are being redirected without the `Accept` header, and the discoverd server is just [returning an empty response](https://github.com/flynn/flynn/blob/master/discoverd/server/handler.go#L128-L134), meaning the stream keeps trying to connect.

We should update the discoverd server to return a `406` rather than an empty response when the `Accept` header is not `text/event-stream`, and also consider using [http.Client.CheckRedirect](https://github.com/golang/go/blob/master/src/net/http/client.go#L42-L53) to maintain the `Accept` header through the redirect.

I should also add that `TestOmniJobs` *does* fail when run by itself, maybe I ran the wrong branch :neutral_face:

**Comment by lmars** [comment]
I am working on a patch.

**Comment by benbjohnson** [comment]
@lmars Good catch. +1 for returning 406 as well.

**Comment by lmars** [comment]
So there is a simpler fix here which is for the service endpoint to always return a stream regardless of the headers: (https://github.com/flynn/flynn/commit/5d372464186b81d1a13bc4433a88662fe1ace9bf)

I think the client still needs to be fixed so that it maintains headers, but merging the above would allow us to re-enable the test, and perhaps we should wait for a proper solution to golang/go#4800.

WDYT?

/cc @titanous

**Comment by titanous** [comment]
I'm fine with the simple fix as a temporary measure, make sure you add a comment.
