### ISSUE TITLE
flynn install digital ocean controller: resource not found

### ISSUE THREAD

**Issue by ioRekz** [flynn/flynn#1861]
I have a controller: resource not found on a lot of cli commands after running flynn install and creating a digitalocean cluster

**Comment by titanous** [comment]
I am investigating this.

**Comment by titanous** [comment]
What version of the CLI are you using? (`flynn version`) What commands aren't working?

I just deployed a DO cluster with the latest (v20150911.0) and had no trouble.

**Comment by ioRekz** [comment]
flynn version : v20150911.0
commands : deploy release env  (havnt tested them all)

**Comment by ioRekz** [comment]
Ok sorry my bad, I had severals remote and used the -a option with a bad remote.
Sorry for the waste of time
