### ISSUE TITLE
the peer leaf certificate did not match the provided pin

### ISSUE THREAD

**Issue by cdesch** [flynn/flynn#1868]
After installing, the last line asks me to run the command:

        Flynn bootstrapping complete. Install the Flynn CLI (see https://flynn.io/docs/cli for instructions) and paste the line below into a terminal window:

        flynn cluster add -p <code>= default flynn.mydomain.com <code>

        The built-in dashboard can be accessed at http://dashboard.flynn.mydomain.com and your login token is <code>

After running the command I get a the error `the peer leaf certificate did not match the provided pin` 

        cj@kenj-app-c1-1:/var/log/upstart$ flynn cluster add -p <code>= default flynn.mydomain.com <code>
           
        Error writing CA certificate: Get https://controller.flynn.mydomain.com/ca-cert: pinned: the peer leaf certificate did not match the provided pin

Why is this error occurring?

**Comment by titanous** [comment]
The error indicates that the pin (specified in the `-p` flag) does not match the certificate provided for the connection. The two likely causes are that something else is listening with a different certificate at `https://controller.flynn.mydomain.com` or there was a transcription error when copying the command over.

**Comment by cdesch** [comment]
The generated key has a `/` in it. Could that be what is throwing everything off?

**Comment by titanous** [comment]
Where is the slash?

**Comment by cdesch** [comment]
in the pin like this `flynn cluster add -p feZH07l4il4tH233BX8677OJrq2Qu/R234lj3oDzjnWY= default flynn.mydomain.com b79a1e20a05cf3ee324850faf52b3a10`

The problem seemed to be the reverse nginx proxy I was running. It runs now that everything is public. The slash in the pin occurred again in the next cluster setup although did not cause an issue.

**Comment by hadifarnoud** [comment]
I ran into this issue after rebooting flynn host server. I can see the correct `AUTH_KEY` in controller env via flynn dashboard. but I can't connect to flynn via CLI. 

I deleted .flynnrc and deleted flynn certificate from Keychain Access and installed the certificate again. it did not help

```
flynn cluster add -p qbECimSmQ*********ULJDYwnLSkiqGiG4OLea7YU= default cluster2.kamva.in e1c431994bc8********2320290a4d4                   
Error writing CA certificate: Get https://controller.cluster2.kamva.in/ca-cert: pinned: the peer leaf certificate did not match the provided pin
```

**Comment by lmars** [comment]
@hadifarnoud I just ran:

```
$ openssl s_client -connect controller.cluster2.kamva.in:443 -showcerts
```

and it looks like that domain is returning a Let's Encrypt certificate:

```
CONNECTED(00000008)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = *.cluster2.kamva.in
```

so if that is the certificate you've set for your cluster, then just remove the `-p` flag from the `flynn cluster add` command and have the cert be verified by your system roots.

If this isn't your cluster's certificate, then something other than Flynn must be running on port 443.

**Comment by hadifarnoud** [comment]
thanks Lewis. I found the issue. There was a proxy running in front of my cluster domain.
