### ISSUE TITLE
Installation via ssh failed

### ISSUE THREAD

**Issue by adrianmoya** [flynn/flynn#1871]
Installed on 3 nodes via the new ssh installer. 

https://gist.github.com/anonymous/ed0f1637d86143ead9a1

Looks like some zfs issue.Complete install log can be seen here:

https://dl.dropboxusercontent.com/u/2833685/flynn-install-log.log

**Comment by titanous** [comment]
What happens if you run `modprobe zfs`?

**Comment by adrianmoya** [comment]
I get no output from that command. I also ran these:

```
root@flynn-1:~# /sbin/zfs zfs get all -Hp flynn-default
unrecognized command 'zfs'
```

and 
```
root@flynn-1:~# /sbin/zfs get all -Hp flynn-default
cannot open 'flynn-default': dataset does not exist
```

Let me know if this helps...

**Comment by titanous** [comment]
Okay, try running `zfs get all -Hp flynn-default`

**Comment by titanous** [comment]
Hmm, sounds like we might need to add `modprobe` to the install script...

**Comment by adrianmoya** [comment]
the `modprobe` binary seems to be present on the VMs, is there some previous setup I can try to give you additional feedback on the issue? like preinstalling something before running the installer?

**Comment by titanous** [comment]
Where is the Ubuntu image you're using from? What I really want to know is why the ZFS kernel module is not being loaded automatically by apt-get.

**Comment by adrianmoya** [comment]
It's the official ubuntu cloud image, you can get it from here:
https://cloud-images.ubuntu.com/trusty/current/ 
Specifically https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img

**Comment by adrianmoya** [comment]
@titanous I just confirmed installing manually the packages that after installation the module doesn't load. I did a `modprobe zfs` and the module got loaded, confirmed with `lsmod | grep zfs`. So I think yes, you may need to add the `modprobe` command to the script.

**Comment by adrianmoya** [comment]
I manually loaded the zfs module on each node, and run the installer. It finished flawlessly :D I'll leave the issue opened for the `modprobe` command to be added.

**Comment by maciejczyzewski** [comment]
Hey, I have the same problem with __modprobe zfs__... it would be nice to fix it :+1: 
(manually works well, but installation script always fails)
