### ISSUE TITLE
Dashboard: "Something went wrong" when adding a GitHub key

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#1872]
Using Chrome on OS X, when adding a GitHub key, I get the error message Something went wrong, and the process aborts. The GitHub key is stored, but the next part of the flow (i.e. going to the apps page) never happens.

It appears to be a failure to load `/apps/dashboard/events`. I suspect this is causing other pages to abort as well.

**Comment by cdesch** [comment]
+1 the github key only seems to keep for the session. Reloading the page completely will lose the key.

**Comment by nobert** [comment]
Other things do abort but I have not confirmed that they are the same problem. Most/any formation change, including new apps and adding env variables, will also abort.
