### ISSUE TITLE
ci: Access VMs after a failed build

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1882]
Once a build has failed, I want to access the VMs to have a look around rather than just relying on the log files.

I could either access them via SSH directly from a shell on the VM host, or access them via the web interface using a combination of [term.js](https://github.com/chjj/term.js/) + WebSockets (I have done this on a personal project, it works!). The advantage of a web interface is that you can have buttons which run arbitrary commands for you in the shell, and have multiple shells open.

Keeping the VMs around isn't too difficult (just wrap [this](https://github.com/flynn/flynn/blob/v20150916.0/test/runner/runner.go#L356) in `if err == nil`), but currently not feasible due to the fact that the VM hard disks are completely in RAM, and we only have enough RAM to support a small number of clusters.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
