### ISSUE TITLE
Accessing host from inside containers

### ISSUE THREAD

**Issue by tuananh** [flynn/flynn#1892]
Since only Postgres is supported at this time, i have to opt for running other databases outside of Flynn with docker (port A container to host: port B). How can i access the database from Flynn app?

**Comment by titanous** [comment]
Use the IP/port of the database, you can set environment variables with `flynn env set`.

**Comment by tuananh** [comment]
@titanous using `localhost`?

**Comment by titanous** [comment]
No, the IP of the host (when using port forwarding)
