### ISSUE TITLE
vagrant: Single machine multi-node test cluster doesn't work on Vagrant VM

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#1893]
After successful bootstrap fails with:

```
Error writing CA certificate: Get https://controller.dev.localflynn.com/ca-cert: dial tcp 192.0.2.100:443: connection refused
```

New DNS records are probably required to support this behaviour.

**Comment by lmars** [comment]
We should probably add `*.cluster.localflynn.com` pointing at `198.51.100.1`, and conditionally use that in `script/bootstrap-flynn`.

For now, you can either point `{dashboard.,controller.,}dev.localflynn.com` to `198.51.100.1` in `/etc/hosts`, or explicitly set `CLUSTER_DOMAIN` to something that points at `198.51.100.1` (e.g. `198.51.100.1.xip.io`).

**Comment by titanous** [comment]
`3.localflynn.com` through `10.localflynn.com` already exist, I can change the IPs if you don't want to use the current ones. Will that work?
