### ISSUE TITLE
git push flynn master stucks at "Building..."

### ISSUE THREAD

**Issue by tuananh** [flynn/flynn#1897]
It just stucks here at `-----> Building <appname>...` when i did `git push flynn master`

![](https://dl.dropboxusercontent.com/s/vpcv9n8wo3d2w9b/2015-09-22%20at%205.38%20PM.png)

**Comment by titanous** [comment]
Please post the debug info from the cluster: `flynn-host collect-debug-info`

**Comment by tuananh** [comment]
INFO[09-22|22:54:48] uploading logs and debug information to a private, anonymous gist
    INFO[09-22|22:54:48] this may take a while depending on the size of your logs
    INFO[09-22|22:54:48] getting flynn-host logs
    EROR[09-22|22:54:48] error getting flynn-host log "/var/log/upstart/flynn-host.log" err="open /var/log/upstart/flynn-host.log: permission denied"
    INFO[09-22|22:54:48] getting job logs
    INFO[09-22|22:54:59] getting system information
    EROR[09-22|22:55:00] error capturing output of "iptables -L -v -n --line-numbers" err="exit status 3"
    INFO[09-22|22:55:00] creating anonymous gist
    1.43 MB / 1.43 MB [=====================================================================================================================================================] 100.00 % 225.55 KB/s 6s
    INFO[09-22|22:55:06] debug information uploaded to: https://gist.github.com/d70deec4138ccbcfc7c5

**Comment by titanous** [comment]
It looks like slugbuilder is crashing without any output. The hang is caused by #1808. If you create a new app with the same repo does the push still hang? Do other repos have the same problem? Does the same repo work on another Flynn cluster?

**Comment by tuananh** [comment]
@titanous it seems somehow the disk is full with flynn taking 13GB. I have only 1 node app (rather small, slug size of 24MB). I did clean install last night since i couldn't wait.
