### ISSUE TITLE
Why is flynn taking a lot of space?

### ISSUE THREAD

**Issue by tuananh** [flynn/flynn#1900]
![](https://dl.dropboxusercontent.com/s/yaszui5c23se0yq/2015-09-25%20at%204.12%20PM.png)

I have only 2 very smaller apps but flynn keep filling disk space very quick. I don't have anything else running on this server yet 20GB is getting filled after 2 or 3 days.

Any way to debug this?

I used `du -h --max-depth=1 /` and track down and found out it is in fact flynn taking up space.

**Comment by titanous** [comment]
Have you tracked down specific files/directories that are taking up the space?

**Comment by tuananh** [comment]
My bad. The other guy did install `docker` on it. It was `docker` but not `flynn`.
