### ISSUE TITLE
Shell completion for flynn cli

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#1901]
As a user of the `flynn` CLI, it would be nice to have bash completion for `flynn` CLI commands. Here are some examples:
`flynn cluster default <cluster-name>`
`flynn cluster remove <cluster-name>`

These examples are for completion of cluster names. 
`flynn kill <job>`
Killing jobs.

`flynn env unset <var>`
Unsetting environment variables.

`flynn -a <app> delete`
Deleting apps.

Also just tab completing commands would be nice. It's nice to have tab completion in `git`. I feel like it would be nice to have it in `flynn` as well.

**Comment by lmars** [comment]
@tianx2 we do actually have a bash completion script [here](https://github.com/flynn/flynn/blob/master/cli/contrib/flynn-bash-completion.sh), but it looks like it has become stale and no longer works (`flynn help commands` no longer lists commands).

Fixing that would be a good start.

**Comment by titanous** [comment]
(I'd like this for ZSH as well) It would be neat if the CLI could spit out a completion file based on its internal command database so that we don't have to keep another file up to date.

**Comment by tianx2** [comment]
Cool. When this is fixed, will this do tab completion on things like cluster names or app names?

**Comment by titanous** [comment]
That's totally doable, though would require some new code.

**Comment by tianx2** [comment]
Thanks @lmars @titanous! Tab completion on ids, cluster-names, app-names, environment variables, and other areas where appropriate would help a lot!

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
