### ISSUE TITLE
bootstrap: Race when starting schedulers

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#1906]
During bootstrap, [the controller formation is scaled](https://github.com/flynn/flynn/blob/master/bootstrap/manifest_template.json#L231-L240) and then [schedulers are started](https://github.com/flynn/flynn/blob/master/bootstrap/manifest_template.json#L241-L248) ([one per host](https://github.com/flynn/flynn/blob/master/bootstrap/run_app_action.go#L106-L108) since the scheduler is an omni process type), but this leads to a race where the first scheduler syncs with the cluster + controller before bootstrap has finished starting all the schedulers, and it itself starts schedulers, leading to too many schedulers running.

This isn't particularly problematic as the scheduler will eventually rectify and stop the surplus schedulers, but we should try and avoid this if possible, perhaps by bootstrap only starting one scheduler and letting the scheduler start the rest.

**Comment by jzila** [comment]
What if we make the controller only start one scheduler: the leader?

**Comment by lmars** [comment]
This race caused a cluster to have two schedulers running on a single host: both the scheduler leader and bootstrap started a scheduler on a particular host, the scheduler leader realised there were too many but killed a job on a host with just one scheduler, not realising that would leave the cluster unbalanced (see #2511).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
