### ISSUE TITLE
What's my cluster domain?

### ISSUE THREAD

**Issue by adrianmoya** [flynn/flynn#1916]
I finished installed via the installer's ssh option, and I ended up in a dashboard with a domain flynnhub.com. What's my cluster domain? I didn't got a chance to set it up! So I'm a bit lost on how to continue. Any help appreciated.

**Comment by tuananh** [comment]
It's mentioned in (installation page](https://flynn.io/docs/installation#start-flynn-layer-1)

**Comment by adrianmoya** [comment]
That's for the ubuntu installation, I used the web installer. I think layer 1 is already bootstraped as I have access to the dashboard already.

**Comment by titanous** [comment]
Your cluster domain is the flynnhub domain (without the `dashboard.` part)

**Comment by lmars** [comment]
@adrianmoya can we consider this issue closed?

**Comment by adrianmoya** [comment]
@lmars sure, for what I understood, this is some kind of dynamic domain which got my local ip's registered? Is there more docs about what goes under the hood?
