### ISSUE TITLE
NPM build doesn't use SSH_CLIENT_HOSTS

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1917]
```
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror ssh://git@github.com/bazaarvoice/pontiac.git /app/.npm/_git-remotes/ssh-git-github-com-bazaarvoice-pontiac-git-19c32d27: Host key verification failed.
       npm ERR! git clone --template=/app/.npm/_git-remotes/_templates --mirror ssh://git@github.com/bazaarvoice/pontiac.git /app/.npm/_git-remotes/ssh-git-github-com-bazaarvoice-pontiac-git-19c32d27: fatal: Could not read from remote repository.
```

SSH_CLIENT_HOSTS and SSH_CLIENT_KEY are set correctly, so I would expect this to "just work".

**Comment by aaronfranco** [comment]
How do I set SSH_CLIENT_HOSTS and SSH_CLIENT_KEY? I'm getting this error.

**Comment by titanous** [comment]
@aaronfranco 

```text
flynn -a gitreceive env set SSH_CLIENT_HOSTS="$(cat ssh_hosts.txt)" SSH_CLIENT_KEY="$(cat id_rsa)"
```

The `ssh_hosts` file should be lines from `known_hosts` for the servers you will connect to. `id_rsa` should be a private key that is authorized to access the repo.

**Comment by aaronfranco** [comment]
That did not resolve the issue.

**Comment by titanous** [comment]
Is the repo you're trying to use private? What is the error?

**Comment by aaronfranco** [comment]
The repo is private

**Comment by aaronfranco** [comment]
npm ERR! code 128
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.

Seems to be an SSH key issue...

**Comment by lmars** [comment]
@aaronfranco you may want to try an explicit fetch of the appropriate host key, e.g. for `github.com`:

```
$ flynn -a gitreceive env set SSH_CLIENT_HOSTS="$(ssh-keyscan -H github.com)"
```

**Comment by aaronfranco** [comment]
http://stackoverflow.com/questions/28728665/how-to-use-private-github-repo-as-npm-dependency

This answer resolved the issue! Thanks for the help :+1:
