### ISSUE TITLE
scheduler: Make discoverd, controller, and host calls asynchronous

### ISSUE THREAD

**Issue by jzila** [flynn/flynn#1920]
Currently there are many synchronous network calls in the scheduler, including:
discoverd:
[controller/scheduler/scheduler.go#L881](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/controller/scheduler/scheduler.go#L881)
host:
[controller/scheduler/scheduler.go#L348](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/controller/scheduler/scheduler.go#L348)
[controller/scheduler/scheduler.go#L554](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/controller/scheduler/scheduler.go#L554)
controller:
[controller/scheduler/scheduler.go#L389](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/controller/scheduler/scheduler.go#L389)
[controller/scheduler/scheduler.go#L669](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/controller/scheduler/scheduler.go#L669)
[controller/utils/utils.go#L99](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/controller/utils/utils.go#L99)
[controller/utils/utils.go#L104](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/controller/utils/utils.go#L104)
[controller/utils/utils.go#L109](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/controller/utils/utils.go#L109)

These calls need to happen asynchronously or on short timeouts with recovery.

The first step should be to make a `SyncHosts` method in the spirit of `SyncJobs` and `SyncFormations`, so that hosts do not have to be retrieved each time a job request is processed.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
