### ISSUE TITLE
TestResourceLimits fails with empty response from command

### ISSUE THREAD

**Issue by jzila** [flynn/flynn#1927]
https://ci.flynn.io/builds/20151001185913-cef18a57

TestResourceLimits doesn't time out, but fails with an empty response. This has only been recorded in the above build.

[test/test_host.go#L291](https://github.com/flynn/flynn/blob/74c5592efa25759584b1c60fcc8766087475e3fb/test/test_host.go#L291)

**Comment by titanous** [comment]
This hasn't happened recently.
