### ISSUE TITLE
Cannot push more than a few times

### ISSUE THREAD

**Issue by nikokon** [flynn/flynn#1929]
I've been having trouble with pushing to my cluster multiple times. After a while i get:

```
Counting objects: 8, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 646 bytes | 0 bytes/s, done.
Total 8 (delta 7), reused 0 (delta 0)
-----> Building plick-api...
remote: write tcp 159.122.4.66:1113: connection reset by peer
To https://git.api.plick.se/plick-api.git
 ! [remote rejected] mangopay -> master (pre-receive hook declined)
```

I then collected debug information here : https://gist.github.com/anonymous/ee61c00bb0b2b9234de2

Deleting my app and then creating a new one solves the issue momentarily but then again when I push I get the same response.

After talking a bit with @lmars on IRC and fiddling around rereleasing my app by changing environment variables i started noticing in the logs that I was out of diskspace if this could possibly have anything to do with the issue.

I'm running a three node cluster and I've gathered the disk-usage:
https://gist.github.com/nikokon/9ec5508293fbc0c648e6
https://gist.github.com/nikokon/3056b8c75fbf4c2a0297
https://gist.github.com/nikokon/4ab8cb18d7294d05dd8f

and also an excerpt of the used directory space usage:
https://gist.github.com/nikokon/743725cf99d5a48f96c2

is 25GB too low diskspace for the servers? The slugsize is 66mb if thats useful information.

**Comment by titanous** [comment]
This looks like #38 is causing the disk to fill up.
