### ISSUE TITLE
Split VMs into separate pieces

### ISSUE THREAD

**Issue by cweagans** [flynn/flynn#1933]
Suggested in https://github.com/flynn/flynn/issues/1931#issuecomment-145256714. Just opening a separate issue to keep track of it.

**Comment by cweagans** [comment]
Two paths:

1) Build separate images that build on each other. Something like this:
```
                         /-> flynn-dev
ubuntu -> flynn-common ->
                         \-> flynn-demo
```

2) Build a set of Ansible playbooks with separate, well defined roles that install things appropriately. Optionally, we can also pre-package the demo VM so that demo users won't need to wait for the machine to be provisioned. Bonus on this point is that people can use the Ansible playbooks to install Flynn on their own servers as part of their normal provisioning workflow.

My preference is 2, and I can put it together really quickly.

@titanous thoughts?

**Comment by josephglanville** [comment]
It's probably not even necessary to have a 2 stage process or introduce Ansible.

The current system uses a single install script. This script could just be broken up into common, dev and demo. Then a separate set of builders can be introduced into the packer pipeline that calls either common + dev or common + demo.

I have done some work in #1720 to make this easier and will probably be cleaning it up now.

**Comment by cweagans** [comment]
@josephglanville It may not be strictly *necessary* to introduce Ansible, sure. I think it's a good way to build the installation scripts in a way that's reusable, rather than something specifically for Vagrant machines.

At the end of the day, I'm going to end up building Ansible playbooks either way because that's how I manage my servers. If somebody uses Chef or Puppet or something, they can also run Ansible playbooks through their existing scripts very easily - they're definitely not mutually exclusive. If they end up getting used for the main Flynn project, that's even better.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
