### ISSUE TITLE
Is it possible to rebuild app without pushing?

### ISSUE THREAD

**Issue by tuananh** [flynn/flynn#1939]
I have one of my dependencies get updated (npm module)? How to trigger app rebuild without `git push flynn master`?

**Comment by lmars** [comment]
@tuananh if you want your app to be recompiled, you will need to push a new commit. If your `npm` dependencies have changed, you should update your `package.json` file and push that, or alternatively just amend the previous commit (`git commit --amend`) and push it.

**Comment by tuananh** [comment]
@lmars the dependency is one of my own and i'm still working on it. so i don't want to change the main project (because there is nothing to change).

I guess i'll have to stick with your way for now.
