### ISSUE TITLE
Unable to push app via git (AWS instance via installer)

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#1946]
```
$ flynn create app
Created app
```

```
$ git push flynn master
fatal: unable to access 'https://git.x994.flynnhub.com/app.git/': Unknown SSL protocol error in connection to git.x994.flynnhub.com:-9838
```

Why is it trying to connect on port `-9838`?

cli version: `v20151006.0`
flynn-host version: `v20150825.0`

**Comment by titanous** [comment]
This is probably because the EC2 image is very old due to release issues.

**Comment by jvatic** [comment]
I will verify this works once a new release is available.

**Comment by jvatic** [comment]
This is resolved with the latest release (flynn-host `v20151006.0`)

**Comment by goocastro** [comment]
In a fresh AWS install it's happening v20161022.0

`Unknown SSL protocol error in connection`

**Comment by goocastro** [comment]
@jvatic could you elaborate what was the fix at `v20151006.0`?

I'm stuck with `git push flynn master` and no application gets deployed

**Comment by lmars** [comment]
@goocastro are there any errors in either the router or gitreceive logs?

```
$ flynn -a router log
$ flynn -a gitreceive log
```

Please open a new issue describing your issue and any errors you see in those logs.

**Comment by goocastro** [comment]
Ok @lmars.

Just opened a new issue #3564 with some log lines.
