### ISSUE TITLE
Not all Procfile processes appearing in dashboard UI

### ISSUE THREAD

**Issue by maclover7** [flynn/flynn#1959]
I'm encountering a weird bug with Flynn right now. I declared two processes in my Procfile, "web" and "worker", but only web is showing up on the dashboard UI interface. I took a screenshot of the terminal output when I deployed, and also the web interface.

Not sure what's going wrong here, but any help would be appreciated. :)
![screen shot 2015-10-10 at 7 45 50 pm](https://cloud.githubusercontent.com/assets/3020626/10413847/06ae0602-6f88-11e5-98cb-7e411c5883f4.png)
![screen shot 2015-10-10 at 7 46 14 pm](https://cloud.githubusercontent.com/assets/3020626/10413848/09472006-6f88-11e5-815b-7365b47385fb.png)

**Comment by titanous** [comment]
@jvatic please look into this.

**Comment by maclover7** [comment]
@jvatic Thanks for fixing this! How do I upgrade my Flynn installation to the latest version?

**Comment by jvatic** [comment]
@maclover7 There should be a new release by tomorrow (you can then run `flynn-host update` on one of the servers in your cluster).

You can run `flynn scale worker=1` for now to work around the issue (it will then appear in the dashboard).
