### ISSUE TITLE
Flynn on ARM (Scaleway)

### ISSUE THREAD

**Issue by sfcgeorge** [flynn/flynn#1965]
[Scaleway](https://www.scaleway.com) offers dedicated ARM servers for just €2.99/month which is crazy cheap and pretty powerful with quad cores and 2GB RAM. It seems like an ideal platform to build a resilient cloud and I was hoping to do so with Flynn for simplicity.

Flynn doesn't currently run on ARM so this is my :+1: for that to hopefully become possible.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
