### ISSUE TITLE
'run-app postgres error: bootstrap: timed out waiting for job event'

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#1974]
```
++ flynn-host bootstrap --peer-ips=10.100.46.229,10.100.36.13,10.100.42.133 --timeout 150
+ bootstrap_output='20:56:08.053105 check online-hosts
20:56:27.125646 require-env require-env
20:56:27.126099 run-app flannel
20:56:30.421195 run-app discoverd
20:56:31.808444 wait-hosts wait-hosts
20:56:33.828790 gen-random pg-password
20:56:33.828954 gen-random pg-password 4cb4fc509aa8cf65a2a2d76977173b62
20:56:33.828968 run-app postgres
20:56:46.263518 run-app postgres error: bootstrap: timed out waiting for job event'
+ echo 'Bootstrap failed, collecting debugging info'
Bootstrap failed, collecting debugging info
+ flynn-host collect-debug-info
t=2015-10-14T20:56:46+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
t=2015-10-14T20:56:46+0000 lvl=info msg="this may take a while depending on the size of your logs"
t=2015-10-14T20:56:46+0000 lvl=info msg="getting flynn-host logs"
t=2015-10-14T20:56:46+0000 lvl=info msg="getting job logs"
t=2015-10-14T20:56:55+0000 lvl=info msg="getting system information"
t=2015-10-14T20:56:55+0000 lvl=info msg="creating anonymous gist"
t=2015-10-14T20:56:55+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/56e6bc063aca0a52ee46"
```

**Comment by temujin9** [comment]
@benbjohnson This has your raft-debugging branch on it, which might help in debugging. @titanous asked me to ping you.

**Comment by benbjohnson** [comment]
@temujin9 Is the `godeps` version being compiled into the binary? I don't see any `leader loop:` lines in the output log.

**Comment by temujin9** [comment]
@benbjohnson Not certain how to determine that. I have a lot of things that say 'godep' in the build output, but nothing that looks like it's triggering a rebuild of the godeps, if that's what you mean. I could be missing it, though.

**Comment by benbjohnson** [comment]
@temujin9 Where's your current branch that you're working off of?

**Comment by temujin9** [comment]
I've got a build that merges your raft-debugging branch into latest master.

**Comment by temujin9** [comment]
Ran about an hour or two ago.

**Comment by temujin9** [comment]
https://github.com/bazaarvoice/flynn/tree/bazaarvoice-cedarish is the results.

**Comment by temujin9** [comment]
Issue is very replicable, at the moment: https://gist.github.com/f114edcdfbab52d72b99

**Comment by titanous** [comment]
@temujin9 Something weird is happening, the new log lines are not showing up. For example:

[This log line](https://gist.github.com/anonymous/f114edcdfbab52d72b99#file-discoverd-app-ip1010044222-b6efa734-741f-4d0a-bbb0-a9d547e975d2-log-L49) comes from [this code](https://github.com/bazaarvoice/flynn/blob/28f45c959d0a96a1ce8870bea7bb790818964e84/Godeps/_workspace/src/github.com/hashicorp/raft/raft.go#L975), called [from here](https://github.com/bazaarvoice/flynn/blob/28f45c959d0a96a1ce8870bea7bb790818964e84/Godeps/_workspace/src/github.com/hashicorp/raft/raft.go#L909). As you can see a log line should be printed from line 906 and it didn't show up in the logs. The most likely explanation is that the binary that emitted these logs is not compiled from the linked code, but I'm willing to entertain other theories.

**Comment by temujin9** [comment]
Hrm. Okay, that would be because I failed to throw the "dev build" flag correctly. Rebuilding now.

**Comment by temujin9** [comment]
And with the flag thrown, it doesn't reproduce. Hrm.

**Comment by benbjohnson** [comment]
@temujin9 The issue doesn't reproduce? Is it possibly using an old version of `hashicorp/raft`?

**Comment by temujin9** [comment]
@benbjohnson It was using the latest release when I built it yesterday; if you updated raft real recently in master, then maybe . . . otherwise that's probably not it.

**Comment by temujin9** [comment]
@benbjohnson Today's release didn't fail in the same place, but it did fail. https://gist.github.com/2a4e2d1f32eada027522

**Comment by titanous** [comment]
@temujin9 Do you have the bootstrap output from that? It doesn't look like any jobs were started on the host.

**Comment by temujin9** [comment]
```
++ flynn-host bootstrap --peer-ips=10.100.38.131,10.100.46.251,10.100.43.216 --timeout 150
+ bootstrap_output='16:34:23.631272 check online-hosts
16:34:46.687431 require-env require-env
16:34:46.688058 run-app flannel
16:34:56.696012 run-app flannel error: bootstrap: timed out waiting for job event'
+ echo 'Bootstrap failed, collecting debugging info'
Bootstrap failed, collecting debugging info
+ flynn-host collect-debug-info
t=2015-10-15T16:34:56+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
t=2015-10-15T16:34:56+0000 lvl=info msg="this may take a while depending on the size of your logs"
t=2015-10-15T16:34:56+0000 lvl=info msg="getting flynn-host logs"
t=2015-10-15T16:34:56+0000 lvl=info msg="getting job logs"
t=2015-10-15T16:35:26+0000 lvl=eror msg="error getting job logs, falling back to on-disk logs" err="could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
t=2015-10-15T16:35:26+0000 lvl=info msg="getting system information"
t=2015-10-15T16:35:26+0000 lvl=eror msg="error capturing output of \"bash -c tail -n 1000 /var/log/flynn/**/*.log\"" err="exit status 1"
t=2015-10-15T16:35:26+0000 lvl=info msg="creating anonymous gist"
t=2015-10-15T16:35:26+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/2a4e2d1f32eada027522"
```

**Comment by titanous** [comment]
Please dump the logs from the other two hosts, for some reason flannel did not start but there is no information in the logs uploaded.

**Comment by temujin9** [comment]
https://gist.github.com/394a0be50fe4f9892a63
https://gist.github.com/60697d60b13befd84c3b

**Comment by titanous** [comment]
@temujin9 there is no readily apparent explanation for this failure, I'll poke at the logs a bit more. Did a subsequent bootstrap work?

**Comment by titanous** [comment]
Hmm, I think this last failure was just a straight-up timeout. I'll bump the job event timeout.

**Comment by temujin9** [comment]
And another cluster (latest release) fails to stand up:
```
++ flynn-host bootstrap --peer-ips=10.100.36.135,10.100.43.109,10.100.44.104 --timeout 150
+ bootstrap_output='16:51:59.802414 check online-hosts
16:52:37.890492 require-env require-env
16:52:37.891086 run-app flannel
16:52:39.088719 run-app discoverd
16:52:40.540916 wait-hosts wait-hosts
16:53:40.677150 wait-hosts wait-hosts error: bootstrap: timed out waiting for hosts to come up'
+ echo 'Bootstrap failed, collecting debugging info'
Bootstrap failed, collecting debugging info
+ flynn-host collect-debug-info
t=2015-10-15T16:53:40+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
t=2015-10-15T16:53:40+0000 lvl=info msg="this may take a while depending on the size of your logs"
t=2015-10-15T16:53:40+0000 lvl=info msg="getting flynn-host logs"
t=2015-10-15T16:53:40+0000 lvl=info msg="getting job logs"
t=2015-10-15T16:54:10+0000 lvl=eror msg="error getting job logs, falling back to on-disk logs" err="could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
t=2015-10-15T16:54:10+0000 lvl=info msg="getting system information"
t=2015-10-15T16:54:10+0000 lvl=info msg="creating anonymous gist"
t=2015-10-15T16:54:10+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/b19fb1d5d8ab23028e29"
```
https://gist.github.com/cd7708748ccfb7e1f1b8 and https://gist.github.com/b62fbef1c98a08f3d919 are the other two.

**Comment by titanous** [comment]
@temujin9 did that last one have the patch from #1969 in it? If so, I didn't manage to fix the image cleanup problem :(

**Comment by temujin9** [comment]
Last one was another of the latest release.

**Comment by titanous** [comment]
@temujin9 I'm still not seeing any log messages with `leader loop:` in them, is this one supposed to have the debug logging?

**Comment by temujin9** [comment]
No, this is your latest release. The ones with debug don't seem to do this.

**Comment by temujin9** [comment]
My current timeout is only 150 seconds, which might be too low given variations in AWS instance launching. Expanding it to 600 seconds, trying again with latest release.

**Comment by temujin9** [comment]
Okay, that may have solved the issue; trying again a couple more times, to be sure.

**Comment by temujin9** [comment]
Feels like that fixed it. Closing this, and the other one I opened, until it reproduces.
