### ISSUE TITLE
How to deploy a certain commit to flynn?

### ISSUE THREAD

**Issue by tuananh** [flynn/flynn#1976]
As i understand i can only deploy master? How do i deploy an old commit?

**Comment by lmars** [comment]
@tuananh whatever you push to the `master` branch of the `flynn` git remote will be deployed, and you can push any commit to that branch using the following command:

```
$ git push flynn REF:master
```

where `REF` is a local git reference (e.g. a branch name or commit SHA).

So for example:

```
# deploy a local branch called "my-local-branch"
$ git push flynn my-local-branch:master

# deploy specific commit c30c557
$ git push flynn c30c557:master
```

You may need to use the `--force` flag if the commit you are pushing is not a descendant of the currently deployed commit.
