### ISSUE TITLE
discoverd instance expiry is not implemented

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#1984]
Currently instance expiry is only used for a minor component of leader election, instances do not appear to expire on their own. This needs to be implemented.

@benbjohnson Do you have thoughts on the strategy for this?

**Comment by benbjohnson** [comment]
@titanous We can add a goroutine within discoverd to continually check for expired instances and one or more exist then we can issue an `ExpireInstanceCommand` so that all the `discoverd` nodes can broadcast in sync. The goroutine would only be run on the current raft leader.

**Comment by benbjohnson** [comment]
@titanous I added instance expiration here: https://github.com/flynn/flynn/pull/1990
