### ISSUE TITLE
discoverd: enforce expiry: unexpected end of JSON input

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#1993]
I noticed this spamming the logs of one of my failed CI builds.

@benbjohnson does this look like a problem?

Example log: https://ci.flynn.io/builds/20151020094734-4e60fb01#default-discoverd-app-92525e90-a860bed4-7c3d-4584-9806-e9c8b465743e

**Comment by benbjohnson** [comment]
I wouldn't think it would cause the build to fail but perhaps it is. Here's a fix: https://github.com/flynn/flynn/pull/1997
