### ISSUE TITLE
Multi Data Center Support

### ISSUE THREAD

**Issue by danielsiders** [flynn/flynn#200]
- [ ] Apps only (e.g. TLS termination) 
- [ ] Cluster import/export
- [ ] Disaster recovery (database follower(s) in other DC(s)
- [ ] "True" multi-DC with Cassandra

**Comment by ChaosMTA** [comment]
This is a good suggestion in the event of a DC failure

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
