### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by danielsiders** [flynn/flynn#201]
Metrics aggregation service

**Comment by temujin9** [comment]
+1 - this is vital for cost accounting, which is vital for enterprise adoption.

**Comment by danielsiders** [comment]
I think there's a big challenge here in terms of how organizations keep track of departmental resource utilization. 

Historically they've used a VM based model where application X used Y of type Z for T. The static assignment of resources to a VM meant that even if the VM was underutilized by the app, the resources were still scheduled to (and requested by) the department, excluding others from using those same resources for the same period. 

With the widespread adoption of containers you're looking at summing the resources __actually utilized__ by a process. In the long run this approach is far more efficient by allowing for finer-grained dynamic resource allotment but will require organizations and infrastructure to retool for the dynamic resource limits, more detailed metrics, and internal accounting that comes with a more elastic world. Everyone benefits, but there will definitely be a learning curve and some heavy lifting.

There are however a number of short term hacks that can get at least some basics in place for early adopters to get their feet wet and start experimenting with different approaches.

**Comment by temujin9** [comment]
I envision us calculating costs based on time-series utilization of memory, correlated against the cost of the servers for that time period. Others might want to involve CPU, disc usage, etc. in their calculations, but in almost all cases time-series usage data is going to be necessary.

**Comment by johnnagro** [comment]
Even the basic metrics that Heroku provides on a per-app basis would be a big help in understanding how resources are being utilized, when resources need to be added or can be scaled down.

![screen shot 2017-03-06 at 09 03 30-fullpage](https://cloud.githubusercontent.com/assets/31442/23613170/4bbf37cc-024c-11e7-9596-a25d1bee5f4c.png)

**Comment by philiplb** [comment]
This just popped up in github trending: https://github.com/bcicen/ctop

**Comment by thomasmodeneis** [comment]
So, is ctop the only way out ?

**Comment by sirakoff** [comment]
Please is there any solution for collecting metrics for app level?

**Comment by thomasmodeneis** [comment]
@sirakoff 
Configure a prometheus outside flynn and install prometheus inside you apps. 
Right now is the best solution.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
