### ISSUE TITLE
JSON error when following "Go to dashboard" after installation

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2017]
```{"code":"syntax_error","message":"The provided JSON input is invalid","retry":false}```

When I reduce the URL from /user/sessions to / everything works fine.

Could be cookie related? I had ran a couple installations before this.

(Chrome on OSX)

**Comment by jvatic** [comment]
#1985 is responsible for this; The dashboad itself JSON encodes the login request where as the installer's request is form encoded, martini handled both behind the scenes.

I will add back support for the form encoded request and add test coverage.
