### ISSUE TITLE
flynn-host instances expire due to discoverd stall

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2027]
@temujin9 has been running into this one a lot.

It looks like some heartbeat writes are stalling for >8s, and so instance expiry gets triggered: 

https://gist.github.com/temujin9/af84cece2583c34b6846#file-ip1010046237-ea6f86be-dd2d-47ce-9aa2-e2081f47cd1a-log-L232-L248
https://gist.github.com/temujin9/0567e5a35d89a4bc7530#file-ip1010036205-ceb1eb9d-645d-4219-b73d-f1fb910f8397-L73-L80

So far it's unclear why this is happening.

/cc @benbjohnson 

Debug logs:

https://gist.github.com/dd3949c2cb3a3cb3d229
https://gist.github.com/a99e75e796cefdc10bf0

**Comment by titanous** [comment]
@temujin9 What EC2 instance type/configuration and region are you using? I think it's worth us trying to reproduce this outside of your system.

**Comment by temujin9** [comment]
The current clusters are single node r3.larges in us-east-1. I'm not designating AZ; the one that's still working is in us-east-1c at the moment.

**Comment by benbjohnson** [comment]
@titanous The only thing I can think of is latency with the underlying raft log storage although that seems really high even for AWS.

**Comment by titanous** [comment]
I just reproduced this on AWS with our `flynn install` tool.

**Comment by titanous** [comment]
@benbjohnson I can now reliably reproduce this, so if you put together more debug logging we can get moving on fixing this.

**Comment by benbjohnson** [comment]
@titanous I added raft timings for `commit` (time to get consensus), `lock` (time to obtain the `Store.mu` once applying), and `exec` (time to actually run the command):

https://github.com/benbjohnson/flynn/tree/apply-log

I wasn't sure if you wanted that PR'd to master or if you wanted to simply work off that commit.

**Comment by titanous** [comment]
K, great. I'll do a run with that on.

**Comment by titanous** [comment]
Here's the log: https://gist.github.com/anonymous/c73d3fe340f2d11092ea#file-discoverd-app-ip1001150-9ebda4e8-7516-497b-94a8-f946ab303ebe-log-L252-L266

I guess we need more granular logging in the raft library?

**Comment by benbjohnson** [comment]
@titanous Is it possible to do a cpu or blocking profile on the `discoverd` instance?

**Comment by titanous** [comment]
@benbjohnson Yeah, I can do that later today. The iterations are pretty slow since I need to build an EC2 image, do you have anything else you want me to do in the same run?

**Comment by benbjohnson** [comment]
@titanous I cherry picked https://github.com/benbjohnson/flynn/commit/ae140dd33ea2703ceba3d53c71c4ae0ef56dfcb3 over to the `apply-log` branch so we can get granular logging inside raft.

**Comment by titanous** [comment]
Here's the blocking profile: https://cl.ly/1V2s1p3N331z

And the log: https://gist.github.com/titanous/1210422abdef64bbdb88

**Comment by titanous** [comment]
I'm closer to this now:

> dispatchLogs: store=3.938028492s start=2.666µs set=301ns notify=2.197µs

[This line](https://github.com/benbjohnson/flynn/blob/ae140dd33ea2703ceba3d53c71c4ae0ef56dfcb3/Godeps/_workspace/src/github.com/hashicorp/raft/raft.go#L1048) is taking multiple seconds sometimes. Digging further in.

**Comment by titanous** [comment]
A layer deeper and we find:

> StoreLogs: n=1 begin=7.276µs put=32.342µs commit=2.201457741s

That's right, the [boltdb commit](https://github.com/benbjohnson/flynn/blob/ae140dd33ea2703ceba3d53c71c4ae0ef56dfcb3/Godeps/_workspace/src/github.com/hashicorp/raft-boltdb/bolt_store.go#L157) is taking >2s.

**Comment by benbjohnson** [comment]
Hmm, can you grab a cpu profile? 2s commit seems strange. Is there a bunch of other IO occurring at the same time? What kind of IOPS are available on the AWS box?

**Comment by titanous** [comment]
I'm pretty sure this is the problem:

> New EBS volumes receive their maximum performance the moment that they are available and do not require initialization (formerly known as pre-warming). However, storage blocks on volumes that were restored from snapshots must be initialized (pulled down from Amazon S3 and written to the volume) before you can access the block. This preliminary action takes time and can cause a significant increase in the latency of an I/O operation the first time each block is accessed. For most applications, amortizing this cost over the lifetime of the volume is acceptable. Performance is restored after the data is accessed once.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html

The solution is to create a separate data EBS volume when starting the EC2 instances, this way we don't have the "initialization" cost of the boot volume that loaded from the AMI (aka snapshot). It's not the IOPS limit because the burst credit bucket is pre-loaded with enough credits for 30 minutes of writes at 3k IOPS.

**Comment by benbjohnson** [comment]
Good find. That seems nuts that it would take that long though.

**Comment by titanous** [comment]
For all we know it's doing an HTTP request to S3 behind the scenes. :facepunch:
