### ISSUE TITLE
non-leader schedulers attempt to handle "crashed" jobs

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2030]
[This code](https://github.com/flynn/flynn/blob/dc83867a0fccbf07f744734f5737bf4dedca1ad1/controller/scheduler/scheduler.go#L952-L960)  appears to be wrong. It is run no matter if the scheduler is a leader or not, so it doesn't know if the job is supposed to be stopping (for instance it might not have an updated formation yet that the leader is reacting to).

It's possible that I'm missing something about how this is supposed to work, but it looks wrong to me.

**Comment by josephglanville** [comment]
This eventually calls `scheduleJobStart` to start the replacement job which has an `isLeader` check on it.
That said it does seem like non-leader instances do end up doing a lot of stuff that should probably be only done by the leader.

**Comment by titanous** [comment]
Yeah, I saw that. I'm more worried about a job being marked crashed in the controller by a random non-leader scheduler when it was intentionally killed by the leader.

**Comment by josephglanville** [comment]
Yeah, that was part of the stuff the "should probably be only done by the leader". :P

Maybe I miss-understand the design decisions but it seems to me anything that mutates state (either in the db or on hosts) should be carried out by the leader, basically the non-leader instances should basically sit idle waiting for election.

**Comment by titanous** [comment]
The original intention was to prevent events from being lost. But I think that can be remedied by having the leader look at the jobs table occasionally and sync with reality.

**Comment by lmars** [comment]
> This code appears to be wrong. It is run no matter if the scheduler is a leader or not, so it doesn't know if the job is supposed to be stopping (for instance it might not have an updated formation yet that the leader is reacting to).

As @josephglanville said, that code is responsible for scheduling a job restart, which will only actually schedule a new job if the scheduler is the leader, and also [marks the job as crashed in the internal state](https://github.com/flynn/flynn/blob/dc83867a0fccbf07f744734f5737bf4dedca1ad1/controller/scheduler/scheduler.go#L1025).

> I'm more worried about a job being marked crashed in the controller by a random non-leader scheduler when it was intentionally killed by the leader

The linked code doesn't lead to the job being persisted, that happens later in the method [here](https://github.com/flynn/flynn/blob/dc83867a0fccbf07f744734f5737bf4dedca1ad1/controller/scheduler/scheduler.go#L962-L971), and always saves the job state using [the status from the host.ActiveJob](https://github.com/flynn/flynn/blob/dc83867a0fccbf07f744734f5737bf4dedca1ad1/controller/scheduler/scheduler.go#L966), so it doesn't matter whether the scheduler is the leader or not, it is just keeping the controller in sync with the job's state in the cluster.

I think the code code be much clearer to show its intent, but I don't think there is a particular bug here, unless @titanous has seen odd behaviour resulting from this code?

**Comment by titanous** [comment]
No odd behavior, just unclear log lines. I'm happy to close this, though we should open a new issue to consider removing the standby monitoring and replacing it with anti-entropy in the leader.
