### ISSUE TITLE
git push flynn fails after changing fallback(global) certificate

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2034]
```
flynn -a router env set TLSCERT="$TLSCERT" TLSKEY="$TLSKEY"
git push flynn
fatal: unable to access 'https://git.xxx.com/kudus-pacify-archipelago.git/': Server aborted the SSL handshake
```

I removed the related self-signed certs from my git config, didn't help.

**Comment by titanous** [comment]
I'm unable to replicate this issue locally. It sounds like there is no route set up for the URL you are trying to use in the git remote.

**Comment by titanous** [comment]
Looks like this was user error, confirmed on IRC. Closing.
