### ISSUE TITLE
router: Setting incompatible TLS env vars breaks the cluster

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2036]
A user tried to change the TLS certs of the router but only set one of the two required variables:

```
$ flynn -a router env set TLSCERT="$TLSCERT"
unexpected close of deployment event stream
$ flynn -a router env get TLSCERT
Get https://controller.example.com/apps/router/release: dial tcp x.x.x.x:443: connection refused
```

This leads to the router exiting with the following:

```
22:11:34.655525 server.go:117: crypto/tls: private key does not match public key
```

but since the router deployment uses job events, the deployment succeeds, leaving the cluster with no router processes.

The router should instead use service events so that old router jobs are only killed after initial setup succeeds (i.e. once the router reaches [this code](https://github.com/flynn/flynn/blob/master/router/server.go#L171-L179)).

**Comment by lmars** [comment]
This is not as straight forward as just setting `service: "router-api"` in the bootstrap manifest because the router uses the host network, meaning the service address for both the old and new process is the same (so rather than an up followed by a down event, the worker sees update events).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
