### ISSUE TITLE
Execute script during slug building

### ISSUE THREAD

**Issue by etnbrd** [flynn/flynn#2038]
My applications are hosted on public github repos, so I cannot put config files containing password.
And some applications requires the config file to be present when starting.
(Restarting an application rebuild the slug, so any file modified, or added from the original repository is lost)

So I need to execute a simple command during the slug building to replace patterns in the config files with password from environment variables.

**Comment by titanous** [comment]
[Create a buildpack](https://devcenter.heroku.com/articles/buildpack-api) that writes the config file out using secrets from the app env (passed as `ENV_DIR`). Then reference the buildpack in a `.buildpacks` along with your app/framework buildpack, this file is automatically used by the built-in [multi buildpack](https://github.com/heroku/heroku-buildpack-multi).

**Comment by etnbrd** [comment]
The solution of @titanous is universal, and works for any buildpack.
But in my case, I use Node.js applications, and I find it easier to use the [`npm scripts`](https://docs.npmjs.com/misc/scripts) options in `package.json`.
For example, `preinstall` to execute a script before the installation of npm dependencies.
