### ISSUE TITLE
Speedup builds by using hosts squid-deb-proxy if available

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2042]
I was able to speed up my builds a lot by modifying the cedarish Dockerfile as follows:

```
FROM ubuntu-debootstrap:14.04

# Derived from https://github.com/heroku/stack-images/blob/master/Dockerfile

RUN echo 'deb http://archive.ubuntu.com/ubuntu trusty main' >/etc/apt/sources.list &&\
    echo 'deb http://archive.ubuntu.com/ubuntu trusty-security main' >>/etc/apt/sources.list &&\
    echo 'deb http://archive.ubuntu.com/ubuntu trusty-updates main' >>/etc/apt/sources.list &&\
    echo 'deb http://archive.ubuntu.com/ubuntu trusty universe' >>/etc/apt/sources.list &&\
    # try to use hosts deb cache
    echo 'Acquire { Retries "0"; HTTP { Proxy "http://172.17.42.1:8000"; }; };' > /etc/apt/apt.conf.d/10_docker_hostproxy &&\
...
```

I will try to find the time to see that it doesn't break anything if the flynn VM is not running squid-deb-proxy.

**Comment by rikur** [comment]
```docker images -q | xargs docker rmi -f; make clean && make```
The cache will serve 165mb of data for apt, which for me saves at least 10 minutes of downloading time and ever more building time, since cedarish builds faster and remaining tasks are not blocked by it for as long.

**Comment by lmars** [comment]
@rikur can we not rely on the Docker build cache?

**Comment by rikur** [comment]
@lmars: this will cache the .deb and .pkg.gz files and speed up the initial build as well, mostly thanks to caching the sources for apt-get update (and that many Docker images are built in parallel). Docker cache wasn't being utilized due to Dockerfiles being very different, part of this PR would fix that.

Considering that most development is meant(?) to be done on the Vagrant image, another option would be to bake in the Docker build caches (and repos for buildpacks).

My change doesn't brake anything though, it simply tries to use a squid proxy - if available - on the Docker host. It doesn't break even if there is no cache available.

I will finish this up, but if you feel it's too hackish then don't apply it :)

**Comment by lmars** [comment]
@rikur if it helps your use case then I have no issue with it, just wanted to understand the reasoning, happy to see it merged!

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
