### ISSUE TITLE
Single node resurrection

### ISSUE THREAD

**Issue by ClaudiuPID** [flynn/flynn#2046]
Hi,

I am playing with flynn in order to better understand it.
So after a few days of testing I decided to reboot the node (I have a single node setup) and see if I am able to resurrect it.

After reboot flynn-host did not start on its own and I had to start it manually.
Thing is that `flynn-host ps` returns: ..127.0.0.1:1111: connection refused.. (I can provide debug gist url if needed)

According to some issues I read, this feature should work. The node should come up on its own without human intervention.
I can't find any sort of documentation in regards to cluster restoration or maybe a recovery procedure.

Is there something documented for this scenario?

And let's assume I had 3 nodes setup but all 3 went down at the same time. Will the cluster be able to recover?

**Comment by kwando** [comment]
@ClaudiuPID have you uncommented the appropriate line in ```/etc/init.d/flynn-host.conf``` ?

**Comment by ClaudiuPID** [comment]
Thanks, that started flynn-host automatically but it did not resurrect the entire server.
It is stuck at `discovered` and I have nothing listening on port 1111, hence `flynn-host ps` is not working.

```
15:30:59.490072 host.go:130: could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused
```
