### ISSUE TITLE
Object storage appliance

### ISSUE THREAD

**Issue by ClaudiuLSH** [flynn/flynn#2047]
One thing missing from flynn is a decent storage appliance.
I've been using for various projects [seaweedfs](https://github.com/chrislusf/seaweedfs) which should not be that hard to implement as an appliance.

Do you guys have plans to implement something similar?
My programming experience is limited to python but if you guys have a guideline for appliance implementation I might give it a try.

**Comment by titanous** [comment]
There is a [blobstore](https://github.com/flynn/flynn/tree/master/blobstore) service internally that persists to Postgres.

**Comment by ClaudiuPID** [comment]
Is that even ok for performance and high traffic web sites?
Imagine an application generating 5 - 10 MB files every few seconds. How will that scale while using postgresql blobstore?

**Comment by titanous** [comment]
It hasn't really been benchmarked for that use case, we use it for git repo caches and app slugs.

**Comment by ClaudiuPID** [comment]
Ok, I see.
In this case, do you know of any plans for an object storage appliance?
Maybe you have time to take a look at seaweedfs, it is fairly simple to use.

What about documentation for building appliances? Or better a framework? I know this might be a bit farfetched but it is worth asking :)

**Comment by titanous** [comment]
Yes, we will be documenting how to build appliances in the future. I expect after we do that people will make various object storage appliances.

**Comment by ClaudiuPID** [comment]
I would like to give it a try with seaweedfs implementation as an appliance.
Do you think this might be accepted if I succeed?
If so, do you have some suggestions in regards to the implementation?

**Comment by titanous** [comment]
It's unlikely that it would be merged before we put together the generic appliance framework, we're currently focused on a few other high-priority issues before we do that.

**Comment by hermanbergwerf** [comment]
+1, seaweedfs would be awesome!

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
