### ISSUE TITLE
access azure machines after flynn install

### ISSUE THREAD

**Issue by pdaniel** [flynn/flynn#2048]
Hello,

I have used the flynn installer for azure ti create a flynn cluster. How can i ssh into the created machines ? I don;t have the private ssh key to be able to access them.

Thx

**Comment by titanous** [comment]
This should answer your question: https://flynn.io/docs/faq/how-do-i-ssh-to-flynn-cluster-hosts

**Comment by pdaniel** [comment]
Thx for your fast reply. I am on windows and used the installer from windows. I can't find the ~/.flynn/installer/keys/flynn directory.

**Comment by titanous** [comment]
On Windows it should be `%APPDATA%\flynn\installer\keys`. Let me know if that works and I'll update the docs.

**Comment by pdaniel** [comment]
No, i don't have the keys in AppData\Roaming\flynn\installer. I have a floder ca-certs  and inside a pem file.

**Comment by titanous** [comment]
I just tested this and I see it in `%APPDATA%\flynn\installer\keys`. Which Windows version are you using?

**Comment by pdaniel** [comment]
i use windows 7

**Comment by titanous** [comment]
Hmm, that's what I tested on. AFAIK there's nowhere else it would have gone. Try searching your computer for `flynn.pub` which should be in the same directory as the private key `flynn`.

**Comment by pdaniel** [comment]
![image](https://cloud.githubusercontent.com/assets/1587574/10852373/17d93742-7f39-11e5-8527-4b21f2760f3c.png)

This is all that i have in the installer folder. I will do a search on my entire computer :) I will let you know if i find something.

**Comment by jvatic** [comment]
Looks like a bug: The keypair isn't saved to disk during the azure install.

**Comment by pdaniel** [comment]
No flynn.pub on my computer. I will try to build another cluster using a fresh windows 10 installation. I will post the results.

**Comment by titanous** [comment]
@pdaniel No need, we need to fix a bit of code.

**Comment by jvatic** [comment]
@pdaniel The fix will be in the next release, a work around for now would be to generate an rsa keypair in `%APPDATA%\flynn\installer\keys` named `flynn`, or run either of the AWS or DO installers first.

**Comment by pdaniel** [comment]
Ok, i managed to pass this problem by generating a certificate before running the installer. Now i have another problem. When i try to do a push to a newly created project i get this error : 

PS E:\projects\paas\flynn-apps\nodejs-flynn-example> git push flynn master
C:\Users\daniel\AppData\Roaming\flynn\bin\flynn.exe git-credentials get: C:UsersdanielAppDataRoamingflynnbinflynn.exe: command not found

Any ideas?
 Thx

**Comment by jvatic** [comment]
@pdaniel Please open a new issue for this
