### ISSUE TITLE
Duplicate log entries

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#2056]
Ran into a situation where there were duplicate log entries returned from `flynn log -a controller log -t worker`, output here: https://gist.github.com/anonymous/860dd488ab8d1fae4b8e#file-worker-log-L52

Debug info: https://gist.github.com/ca73846de6b975f86609

**Comment by josephglanville** [comment]
Only seems to happen after discoverd deployment so probably doesn't effect master yet.

**Comment by jvatic** [comment]
This is occurring intermittently on the [current master](https://github.com/flynn/flynn/tree/d1e53681c9b2f4139b80b3e4b040b05d83945c65). I've seen as many as three of the same line.

**Comment by tombh** [comment]
I have about 15 duplicates for every line!

**Comment by kwando** [comment]
I got one app with 5 duplicates / line.
