### ISSUE TITLE
fsouza container is using ubuntu quantal, doesn't reuse cached debs

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2057]
Godeps/_workspace/src/github.com/fsouza/go-dockerclient/testing/data/Dockerfile
6:from	base:ubuntu-quantal

We could try to use trusty instead and leverage the already cached debs during build

**Comment by titanous** [comment]
That Dockerfile isn't used for anything.

**Comment by rikur** [comment]
Thanks for the info, closing.
