### ISSUE TITLE
All the buildpacks are cloned from scratch everytime we build the slugbuilder image

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2059]
I will see if we can do all/some of the following to speed up builds (as this is now the slowest part of building flynn AFAIK):
- have an initial version already cloned out within the Vagrant box
- do a git pull instead of git clone

**Comment by lmars** [comment]
> have an initial version already cloned out within the Vagrant box

Is this not already the case? The vagrant box comes with an installed version of Flynn (so has the latest images).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
