### ISSUE TITLE
run-app discoverd error: bootstrap: timed out waiting for job event

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2065]
Hi,

I've setup 3 fresh Ubuntu 14.04 LTE server machines with OpenSSH as the only software running on them and followed the instructions on https://flynn.io/docs/installation 
On each machine, I executed those commands as root:

```bash
L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
```
On the first machine, I executed:

```bash
flynn-host init --init-discovery
```
and noted down the URL it returned: https://discovery.flynn.io/clusters/<token>

Then I executed on the first machine:

```bash
start flynn-host
```

On the second and third machine, I executed (with the exact token I retrieved on the first machine):

```bash
flynn-host init --discovery https://discovery.flynn.io/clusters/<token>
start flynn-host
```

I added A-records to my DNS-system for each machine under my cluster-domain and I added a CNAME-entry for *.clusterDomain.

Now back to the first machine, I tried to setup Layer 1:

```bash
sudo \
    CLUSTER_DOMAIN=<clusterDomain> \
    flynn-host bootstrap \
    --min-hosts 3 \
    --discovery https://discovery.flynn.io/clusters/<token>
```

But it failed, this is the output:

> 17:23:15.594193 check online-hosts
> 17:23:16.302904 require-env require-env
> 17:23:16.303478 resource-check resource-check
> 17:23:16.307924 run-app discoverd
> 17:23:46.523911 run-app discoverd error: bootstrap: timed out waiting for job event

What have I done wrong, what is missing?

**Comment by titanous** [comment]
Please run `flynn-host collect-debug-info` on each of the hosts and post the resulting gist links here.

**Comment by philiplb** [comment]
Hi,
wow, that was fast. :) Here are the gists:
First machine: https://gist.github.com/9af33b0b974f56ca9a80
Second machine: https://gist.github.com/ad64d35289eb3bbff0cd
Third machine: https://gist.github.com/4ce513adde79f8576b66

**Comment by titanous** [comment]
It looks like the installation script failed on two of the servers (container images are missing). I'd suggest starting over and confirming that the install script succeeds before proceeding. Let me know if it fails (it's safe to re-run it to retry though).

**Comment by philiplb** [comment]
That did the trick, Layer 0 is now up and running. Thank you for the incredible fast and helpfull support. :)
