### ISSUE TITLE
Inject Flynn app name to the apps ENV vars

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2066]
As a developer, I want to leverage the already existing, shared database and connect using the flynn app name as part of the schema to connect to.

I'm sure there are other use-cases too.

**Comment by titanous** [comment]
One reasonable approach here is to include the app name as a stock environment variable, it can then be used by the application or a wrapper script called from the Procfile.

**Comment by rikur** [comment]
@titanous That's what I was thinking too. I will have a look if I can make a PR for this, but might have to wait until the weekend.

**Comment by titanous** [comment]
This is where the code would go: https://github.com/flynn/flynn/blob/04c12c72421a36f4cdf138f0a5af5600b44b76f6/controller/utils/utils.go#L30 (should be a one-liner)

**Comment by titanous** [comment]
Implemented in #2093
