### ISSUE TITLE
Documentation Request: How to use flynn-host

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2067]
Hi,
it would be great if there was a chapter in the docs available about how to upgrade flynn in my cluster in case a new version is released.
I just found out that

```bash
flynn-host update
```
is used for this. So I reformulate: It would be great if there was a chapter in the docs available about how to use the tool flynn-host. :)

**Comment by lmars** [comment]
We will be adding full documentation on the update process once #2003 is merged.

**Comment by titanous** [comment]
Many details are available at https://flynn.io/docs/production

Please open new issues for anything you notice that is missing.
