### ISSUE TITLE
Documentation Request: How to update SSL certificates

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2068]
Hi,

it would be great if the documentation would state how I can exchange SSL certificates for example if they expire.

**Comment by aaronshaf** [comment]
+1

**Comment by jvatic** [comment]
I think `flynn route update` is what you're looking for. It appears [the documentation](https://flynn.io/docs/cli#route) is out of date, but `flynn route --help` can guide you.

**Comment by philiplb** [comment]
Hi,
route update works just fine. I want to update the documentation, but I can't find the according file in the repo. Could someone give me a hint, what file it is? :)

**Comment by jvatic** [comment]
@philiplb the documentation for the cli is generated using the output of `flynn help --json`. I'll update the docs shortly.

**Comment by jvatic** [comment]
The [CLI docs](https://flynn.io/docs/cli) have been updated

**Comment by philiplb** [comment]
Thx. :)
