### ISSUE TITLE
Feature Request: Specify a path in the URL of a route

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2069]
Hi,

maybe this is already possible? I'm very new to flynn. :)
Can I add a path to a route to specify an application?
We often use this scheme here to differentiate between dev, beta and live versions like this:
- dev: http://www.foo.bar/dev
- beta: http://www.foo.bar/staging
- live: http://www.foo.bar

**Comment by titanous** [comment]
Currently you'd have to use separate subdomains, but I'll keep this issue open as an enhancement request.
