### ISSUE TITLE
flynn-host doesn't survive a reboot

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2075]
Hi,

I'm playing arround with what happens if a machine goes down in my cluster.
How can I configure flynn so that the daemon "flynn-host" survives a reboot? Currently, I have to start him manually via
```bash
sudo start flynn-host
```

**Comment by josephglanville** [comment]
Currently `flynn-host` has it's start configuration commented out in it's upstart config file.

For now you can uncomment that to have it restart automatically on boot.

This is probably quite safe in single node situations though you may still need to recover in the case of a non-graceful shutdown of `flynn-host`.

**Comment by philiplb** [comment]
Alright, will do, thank you.

**Comment by philiplb** [comment]
I edited the file "/etc/init/flynn-host.conf" to this:

```
description "Flynn layer 0"

start on (started libvirt-bin and started networking)
stop on stopping libvirt-bin
respawn
respawn limit 1000 60

exec /usr/local/bin/flynn-host daemon
```

reloaded the config:
```bash
sudo initctl reload-configuration
```

and rebooted.
The daemon is running, checked via

```bash
status flynn-host
```

but

```bash
flynn-host ps
```

throws this error?

> 11:52:48.780511 host.go:130: could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused

**Comment by philiplb** [comment]
Also this is strange: The example-application is still online but doesn't show up on the dashboard anymore.

**Comment by philiplb** [comment]
Here is a debug log info gist of the node: https://gist.github.com/0f2d160a9776ada2346b

**Comment by josephglanville** [comment]
Hmm looks like there might be a problem with resurrection here because it looks like `flynn-host` was gracefully stopped and did mark jobs for resurrection but then they weren't started when `flynn-host` come back up.

**Comment by philiplb** [comment]
Ok, thanks. How can I get out of this state and recover?

**Comment by titanous** [comment]
How many nodes were in the cluster? #2072 should resolve this.

**Comment by philiplb** [comment]
Three in total.
Looking forward to the merge. :)

**Comment by titanous** [comment]
Did you reboot all of the nodes or just one?

**Comment by philiplb** [comment]
Just one.

**Comment by mvd7793** [comment]
I'm having this problem as well in a single node setup, as well as an error when trying to run flynn-host fix.

mvd7793@hogwarts:~$ sudo flynn-host fix --min-hosts=1
EROR[11-09|08:30:20] unable to list hosts from discoverd, falling back to peer IP list error="Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
08:30:20.759047 host.go:132: error connecting to discoverd, use --peer-ips: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused

mvd7793@hogwarts:~$ sudo status flynn-host
flynn-host start/running, process 1977


Debug info:https://gist.github.com/c7e6e4402e960e8c3752

**Comment by titanous** [comment]
@mvd7793 Thanks for the log!

Try running `flynn-host fix --min-hosts 1 --peer-ips 127.0.0.1`

**Comment by mvd7793** [comment]
Didn't work. :(

mvd7793@hogwarts:~$ flynn-host fix --min-hosts 1 --peer-ips 127.0.0.1
EROR[11-10|04:55:59] unable to list hosts from discoverd, falling back to peer IP list error="Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
INFO[11-10|04:55:59] found expected hosts                     n=1
INFO[11-10|04:55:59] ensuring discoverd is running on all hosts 
INFO[11-10|04:55:59] checking flannel 
INFO[11-10|04:55:59] flannel not running, starting it on each host 
INFO[11-10|04:55:59] started flannel job                      job.id=hogwarts-c6bea69b-026b-4607-bcd2-a356df656094
INFO[11-10|04:55:59] flannel fix complete 
INFO[11-10|04:55:59] waiting for discoverd to be available 
04:56:59.302489 host.go:132: timed out waiting for discoverd, last error: Get http://127.0.0.1:1111/services/discoverd/instances: dial tcp 127.0.0.1:1111: connection refused

**Comment by titanous** [comment]
@mvd7793 If you still have this cluster around, please post the debug logs from it. There are probably some edge cases we're not catching.

**Comment by mvd7793** [comment]
I wound up trashing it in favor of reinstalling. I'll let you know if it happens again. :)

**Comment by kwando** [comment]
I've been hitting this as well, but I ended up rebuilding my node.. this is trivial thanks to the backup/restore feature and a small script.

**Comment by geetfun** [comment]
I'm also experiencing this reboot issue after the server is rebooted.

Here are the logs: https://gist.github.com/anonymous/0f2d160a9776ada2346b

**Comment by philiplb** [comment]
Hi,
I just rebooted all of my machines for flynn (3) and tried to launch flynn-host via

```bash
sudo start flynn-host
```

But my applications don't come up.
collect-debug-infos threw an error:

> INFO[12-02|10:39:46] uploading logs and debug information to a private, anonymous gist
> INFO[12-02|10:39:46] this may take a while depending on the size of your logs
> INFO[12-02|10:39:46] getting flynn-host logs
> INFO[12-02|10:39:46] getting job logs
> EROR[12-02|10:40:16] error getting job logs, falling back to on-disk logs err="could not list hosts: Get > http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
> INFO[12-02|10:40:16] getting system information
> EROR[12-02|10:40:16] error capturing output of "bash -c tail -n 1000 /var/log/flynn/**/*.log" err="exit status 1"
> INFO[12-02|10:40:16] creating anonymous gist
> 5.24 MB / 5.24 MB > [==============================================================================] > 100.00 % 1.80 MB/s 2s
> INFO[12-02|10:40:19] debug information uploaded to: https://gist.github.com/56151186c48bfb95914c

But at least something proceeded. :)
https://gist.github.com/anonymous/56151186c48bfb95914c

This is my output of the fix command:

```bash
sudo flynn-host fix --min-hosts 3 --peer-ips 127.0.0.1,213.73.xxx.xxx,213.73.xxx.xxx
```

> EROR[12-02|10:21:58] unable to list hosts from discoverd, falling back to peer IP list error="Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
> INFO[12-02|10:21:58] found expected hosts                     n=3
> INFO[12-02|10:21:58] ensuring discoverd is running on all hosts
> INFO[12-02|10:21:58] checking flannel
> INFO[12-02|10:21:58] flannel not running, starting it on each host
> INFO[12-02|10:21:58] started flannel job                      job.id=flynn0-341b4f49-b615-4aaa-9146-8d946c31263e
> INFO[12-02|10:21:58] started flannel job                      job.id=flynn1-f70a4ebd-efbf-4eaa-996e-4f91948493be
> INFO[12-02|10:21:58] started flannel job                      job.id=flynn2-e70af587-2509-447e-865a-793792a7766b
> INFO[12-02|10:21:58] flannel fix complete
> INFO[12-02|10:21:58] waiting for discoverd to be available
10:22:58.936975 host.go:132: timed out waiting for discoverd, last error: Get http://127.0.0.1:1111/services/discoverd/instances: dial tcp 127.0.0.1:1111: connection refused

**Comment by jvatic** [comment]
I was unable to get the cluster up and running again after doing the following:

1. Install 3 node cluster using installer on AWS
2. Select all three nodes in the EC2 Management Console, and select reboot
3. Run `start flynn-host` on each node

At this point the cluster is in a broken state.

```
$ flynn-host fix --min-hosts=3 --peer-ips=54.172.83.72,54.172.82.80,54.172.82.80
EROR[12-09|02:13:51] unable to list hosts from discoverd, falling back to peer IP list error="object_not_found: service not found"
02:14:21.418500 host.go:135: error connecting to 54.172.83.72: Get http://54.172.83.72:1113/host/status: dial tcp 54.172.83.72:1113: i/o timeout
```

```
$ flynn-host fix --min-hosts=3
INFO[12-09|02:23:09] found expected hosts                     n=3
INFO[12-09|02:23:09] ensuring discoverd is running on all hosts
INFO[12-09|02:23:09] checking flannel
INFO[12-09|02:23:09] flannel looks good
INFO[12-09|02:23:09] waiting for discoverd to be available
INFO[12-09|02:23:09] checking for running controller API
INFO[12-09|02:23:09] checking postgres
INFO[12-09|02:23:09] no running postgres leader
INFO[12-09|02:23:09] found 0 running postgres instances
INFO[12-09|02:23:09] getting postgres status
INFO[12-09|02:23:09] getting postgres service metadata
02:23:09.970530 host.go:135: error getting postgres state from discoverd: object_not_found: service meta not found
```

`flynn-host collect-debug-info`: https://gist.github.com/36519fcc665087895f6b

**Comment by kwando** [comment]
Rebooting a single node cluster is not possible either.

**Comment by philiplb** [comment]
Any news on this? This is the only issue keeping me from using flynn for more than just a single test application. :)

**Comment by titanous** [comment]
@philiplb Yep, @josephglanville is now working on fixing this.

**Comment by philiplb** [comment]
@titanous @josephglanville Awesome. :)

**Comment by rachid** [comment]
@philiplb @titanous @josephglanville 

Don't know if this will help, but I did get the next log (nil pointer dereference) while trying to reboot my single node flynn-host service.
```
now=2015-12-25T23:00:47+0000 backend=libvirt-lxc fn=cleanup job.id=LMCH001-a1f3eda1-0b60-4e6c-9e62-a2f488724494 at=finish
now=2015-12-25T23:00:47+0000 fn=run job.id=LMCH001-ea55c86d-b422-4c68-a1fb-7163b3200758 at=read_config backend=libvirt-lxc
now=2015-12-25T23:00:47+0000 backend=libvirt-lxc fn=run job.id=LMCH001-ea55c86d-b422-4c68-a1fb-7163b3200758 at=checkout
now=2015-12-25T23:00:47+0000 at=mount backend=libvirt-lxc fn=run job.id=LMCH001-ea55c86d-b422-4c68-a1fb-7163b3200758
now=2015-12-25T23:00:47+0000 job.id=LMCH001-ea55c86d-b422-4c68-a1fb-7163b3200758 backend=libvirt-lxc fn=run at=write_config
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x436fee]

goroutine 82 [running]:
main.(*State).SetContainerIP(0xc2080652c0, 0xc20816f470, 0x2c, 0x0, 0x0, 0x0)
        /tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/state.go:387 +0x13e
main.(*LibvirtLXCBackend).Run(0xc2080de700, 0xc20822c690, 0xc20810f7a0, 0x0, 0x0)
        /tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/libvirt_lxc_backend.go:564 +0x5fa2
main.func·035(0xc208217000)
        /tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/state.go:146 +0x2c5
created by main.func·036
        /tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/state.go:148 +0x158

goroutine 1 [semacquire]:
sync.(*WaitGroup).Wait(0xc20810ed60)
        /usr/local/go/src/sync/waitgroup.go:132 +0x169
main.func·036()
        /tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/state.go:150 +0x187
main.runDaemon(0xc2080b6080)
        /tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/host.go:451 +0x6ac7
github.com/flynn/flynn/host/cli.Run(0x7fffb2357f61, 0x6, 0x10e4070, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/cli/cli.go:59 +0x4a8
main.main()
        /tmp/tmp.id1MqgVs8n/src/github.com/flynn/flynn/host/host.go:128 +0x8c1
```

**Comment by lmars** [comment]
@rachid the panic you encountered was fixed in #2337 and will be in a release in the next few days.

As discussed in IRC, in the meantime you can start from fresh on the server by removing the state db and bootstrapping again (i.e. `sudo rm /var/lib/flynn/host-state.bolt; sudo start flynn-host; flynn-host bootstrap`)

**Comment by thomasmodeneis** [comment]
I'm having same problem on #2332 , this is the output 

```
root@flynn-1451135466-0:/etc/flynn# flynn-host fix --min-hosts 1 --peer-ips 127.0.0.1
EROR[01-02|09:06:05] unable to list hosts from discoverd, falling back to peer IP list error="Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
INFO[01-02|09:06:57] found expected hosts                     n=1
INFO[01-02|09:06:57] ensuring discoverd is running on all hosts 
EROR[01-02|09:06:57] error listing jobs                       host=flynn14511354660 error="Get http://127.0.0.1:1113/host/jobs: EOF"
09:06:57.795654 host.go:136: didn't find any discoverd release jobs
```

After I tried to run the @lmars cmd another error with env vars:
```
root@flynn-1451135466-0:/etc/flynn# sudo rm /var/lib/flynn/host-state.bolt; sudo start flynn-host; flynn-host bootstrap
flynn-host start/running, process 2647
09:09:08.382626 check online-hosts
09:09:08.386706 require-env require-env
09:09:08.386950 require-env require-env error: Missing required environment variable(s): CLUSTER_DOMAIN
```

**Comment by titanous** [comment]
This is now fixed.

**Comment by Assassyn** [comment]
I sitll have the same issue every single time after rebotting my single node.
