### ISSUE TITLE
Deployment of a Symfony 2.7 PHP application fails

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2078]
Hi,

I have a mostly basic Symfony 2.7 application here to deploy. The Procfile is just like the example:

> web: vendor/bin/heroku-php-apache2 web/

The git push works fine, the last lines are:

> -----> Preparing runtime environment...
> -----> Discovering process types
>        Procfile declares types -> web
>        Default process types for PHP -> web
> -----> Compiled slug size is 89M
> -----> Creating release...
> =====> Application deployed
> =====> Waiting for web job to start...
> =====> Default web formation scaled to 1

I grab the id via

```bash
flynn -a myApp ps
```

And on a flynn node, I watch the log with it via

```bash
flynn-host log myId
```
But as soon as I visit the URL, I get this in my browser:

> Service Unavailable

And the log I'm watching says:

> bash: vendor/bin/heroku-php-apache2: No such file or directory

The flynn installation is also very basic, I just followed the installation guide and nothing more on three nodes.

Any clue?

**Comment by lmars** [comment]
@philiplb please post the full output from the git push, there should be some lines similar to the following:

```
-----> PHP app detected
-----> No runtime required in 'composer.json', defaulting to PHP 5.6.12.
-----> Installing system packages...
       - PHP 5.6.12
       - Apache 2.4.10
       - Nginx 1.6.0
```

Also post the log output from your job (either `flynn -a myApp log` or `flynn-host log JOBID`).

You can also check if `vendor/bin/heroku-php-apache2` actually exists by running `flynn -a myApp run ls -l vendor/bin`

**Comment by philiplb** [comment]
Hi,
thank you. Here is the full output of the git push:
https://gist.github.com/philiplb/dff567e068e41f05ce03

The log output from the job gathered via (wheras "myApp" is a placeholder here for my application name):

```bash
flynn -a myApp log
```

> 2015-11-05T10:17:57.803680Z app[web.flynn2-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:17:57.803680Z app[web.flynn2-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:17:57.803680Z app[web.flynn2-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:17:57.803680Z app[web.flynn2-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:17:57.803680Z app[web.flynn2-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:17:57.803680Z app[web.flynn2-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:19:03.448728Z app[web.flynn1-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:19:03.448728Z app[web.flynn1-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:19:03.448728Z app[web.flynn1-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:19:03.448728Z app[web.flynn1-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:19:03.448728Z app[web.flynn1-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:19:03.448728Z app[web.flynn1-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-05T10:19:03.448728Z app[web.flynn1-xxx]: bash: vendor/bin/heroku-php-apache2: No such file or directory

And the output of the ls, sadly:

```bash
flynn -a myApp run ls -l vendor/bin
```

> GET https://controller.<...>/apps/myApp/release: httpclient: raw req: unexpected status 503

**Comment by lmars** [comment]
Please run `sudo flynn-host collect-debug-info` on a node in your cluster and post the resulting gist link here, I am not sue why you are getting a 503 from the controller.

**Comment by philiplb** [comment]
Ok, some news:
I reinstalled flynn today with the new version.
I managed to run this:

```bash
flynn -a beobachtungdev run ls -l vendor/bin
```

> ls: cannot access vendor/bin: No such file or directory

It took ages until the output arrived, maybe 2-3 minutes. But this afterwards failed:

```bash
flynn -a beobachtungdev run ls -l vendor
```

> GET https://controller.flynn.smfhq.com/apps/beobachtungdev/release: httpclient: raw req: unexpected status 503

Again after some minutes (2-3).

I tried to create a debug gist, but it hangs since 10 minutes:

> INFO[11-11|11:51:56] uploading logs and debug information to a private, anonymous gist
> INFO[11-11|11:51:56] this may take a while depending on the size of your logs
> INFO[11-11|11:51:56] getting flynn-host logs
> INFO[11-11|11:51:57] getting job logs

**Comment by philiplb** [comment]
Also intersting: On the Dashboard, the app suddenly disappeared.

**Comment by philiplb** [comment]
Current status with the most recent flynn release on deploy:

> -----> Creating release...
> remote: Error deploying app release: timed out waiting for deployment completion
> To https://git.flynn.....com/....git
> ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.flynn.....com/....git'

I'm afraid, debug info collecting still just hangs. I think I reinstall.

**Comment by philiplb** [comment]
Reinstalled everything, including Ubuntu and totally started from scratch.
I tried to deploy the php example application.

Here is the deployment log: https://gist.github.com/8f2750a68e4e60b43609

Here are the debug infos: https://gist.github.com/1bf31f08e65bdc389583

**Comment by philiplb** [comment]
Should I open a new ticket "PHP deployment fails" with this information about the example app?

**Comment by josephglanville** [comment]
@philiplb this issue is probably fine. Could you provide a repo that reproduces this?

**Comment by philiplb** [comment]
https://github.com/flynn-examples/nodejs-flynn-example

**Comment by josephglanville** [comment]
I was unable to reproduce the problem with the example application.

Though I did look at your logs and it looks like there is a seperate problem with that cluster.
@titanous could you take a look at https://gist.github.com/1bf31f08e65bdc389583 and see if that is similar to the issues you have been debugging with @temujin9?

**Comment by titanous** [comment]
Yeah, this looks like #2027.

@philiplb What are the hardware specs you are deploying on?

**Comment by philiplb** [comment]
Virtual Machine, 1 Core with 64 bit, 1GB memory, 32GB hard drive, Ubuntu 14.04.03 LTS Server 64 bit.

**Comment by titanous** [comment]
We've seen this issue with slow hard drives, I think the fix for #2073 will improve the situation significantly.

**Comment by philiplb** [comment]
Ou, I hope the functionality of Flynn doesn't depend on the performance of the hard drive as it can be anything from utter slow to super fast. And if the actual application causes some high io load, Flynn itself shouldn't be affected.

**Comment by philiplb** [comment]
Small update here: I reinstalled flynn today (with the --clean flag) and now the PHP sample application runs fine.
My symfony 2 application still crashes with the log entry

> 2015-11-30T10:06:40.156532Z app[web.flynn1-e45d45de-031e-4791-b1d9-19256f0fc663]: bash: vendor/bin/heroku-php-apache2: No such file or directory
> 2015-11-30T10:06:59.005942Z app[web.flynn1-58ae68ed-ed81-4956-a953-45d29a2527c7]: bash: vendor/bin/heroku-php-apache2: No such file or directory

**Comment by philiplb** [comment]
Here is a gist of the debug infos. Manually uploaded from --tarball, because the auto gist creation failed with an unexpected HTTP 403:
https://gist.github.com/philiplb/cd6a6aae56f069535fd2

**Comment by titanous** [comment]
What does `composer config bin-dir` return?

**Comment by philiplb** [comment]
Aha. :)

> bin

For the PHP Sample application:

> vendor/bin

**Comment by philiplb** [comment]
Yay, it seems to work now. :) I changed the bin-dir in the composer.json to this:

>     "config": {
>        "bin-dir": "vendor/bin"
>    },

It was at "bin". Not sure if this change has side effects as it is the default of a fresh symfony application. Maybe flynn should take care about this setting? I leave this ticket open due to this question.

**Comment by philiplb** [comment]
Now I ran into a missing extension, see php_mbstring, see https://github.com/flynn/flynn/issues/2220

**Comment by philiplb** [comment]
And after a third deployment, no more apps showing up on the dashboard:
https://gist.github.com/993f3f23ea5105197890

Logs for the app:

```bash
flynn -a myApp log
```

> GET https://controller.........com/apps/myApp/log: httpclient: raw req: unexpected status 503

**Comment by philiplb** [comment]
Trying to redeploy the app:

```bash
git push flynn master
```

> remote: Service Unavailable
> fatal: unable to access 'https://git.........com/myApp.git/': The requested URL returned error: 503

**Comment by philiplb** [comment]
Alright, with the mbstring extension up and running, everything seems to be fine now. :)
I would close this ticket now and open a new one with some new debug infos as soon as this deployment issue with missing apps on the dashboard would occure again.

**Comment by lmars** [comment]
@philiplb glad you got to the bottom of it!
