### ISSUE TITLE
Add TLS proxying support to router

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2082]
As a company, we are using client certificates to authenticate our users. We would like to use client certificates to limit access to some of our flynn applications as well.

https://golang.org/pkg/crypto/tls/ has support for them.
http://www.bite-code.com/2015/06/25/tls-mutual-auth-in-golang/ has a code sample.

**Comment by titanous** [comment]
Yeah, this is interesting. Since the router terminates TLS connections, it would have to do the handshake with the client. How do you think the handshake details should be passed back from the router to the app?

**Comment by titanous** [comment]
This should be implemented by adding a new route type that reads the SNI portion of the handshake, establishes a TCP connection to the backend and then proxies the full ClientHello back, splicing the connection in. This way the router is not party to the TLS handshake and the user app can use any TLS configuration it wants.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
