### ISSUE TITLE
cli: Update based on controller API version

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2085]
`flynn update` will currently fetch the latest nightly version (and so will the background update process), and this could be problematic if the updated CLI is incompatible with the controller API currently running in a user's cluster.

We should expose an endpoint in the controller which serves the controller API version, and then `flynn update` would only update as far as the most recent version which is compatible with the current controller API (we would need to handle the user having multiple clusters configured).

This should not encourage us to introduce backwards incompatible changes, but avoids users having a CLI with functionality which is not supported by their clusters.

**Comment by titanous** [comment]
I think we need to maintain backwards compatibility no matter what because the CLI will be used to communicate with multiple clusters. We should probably switch the CLI to have channel support and default to stable.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
