### ISSUE TITLE
Command to open dashboard

### ISSUE THREAD

**Issue by SebastianSzturo** [flynn/flynn#2087]
I'm not sure if I missed something. But it seams like the only way to open the dashboard right now is to bookmark the url or use `flynn install` and press on the "open dashboard" button again. 

It would be really useful to have a `flynn dashboard` command to open the dashboard from the terminal.

**Comment by jvatic** [comment]
This looks like a duplicate of #1724

**Comment by sethwebster** [comment]
This doesn't appear to be a duplicate of #1724. That issue is about certificates. This one is about having easy access to the dashboard. I too am looking for an easy return to the dashboard.

**Comment by shalakhin** [comment]
Any update here?

**Comment by dorra** [comment]
Any update here?

**Comment by lmars** [comment]
An explicit command like `flynn dashboard-url` would be useful, but in the meantime you can use something like:

```
$ CLUSTER="<cluster-name>"

$ echo "$(flynn cluster | grep "^${CLUSTER}" | grep -oP 'https?://controller.\S+' | sed 's/controller/dashboard/')?token=$(flynn -c ${CLUSTER} -a dashboard env get LOGIN_TOKEN)"
```

This will output a URL like:

```
https://dashboard.example.com?token=dceb740099cf4a19050a0be287af57d6
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
