### ISSUE TITLE
docs: Document how to use Flynn behind an AWS ELB

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2092]
Using an AWS ELB (or equivalent) gives users more control over routing / health checks than relying on DNS for load balancing. 

We should document the process, and advise users if their cluster is only accessible via the ELB using security groups they will need to direct controller / dashboard / git requests via the ELB too.

**Comment by aaronfranco** [comment]
any chance you can give a quick run-down on how to set that up?

**Comment by titanous** [comment]
Done: https://flynn.io/docs/production#dns-and-load-balancing

**Comment by tzusman** [comment]
@titanous Not sure that this should be closed out quite yet.

When deploying, how would Flynn register/unregister web services on the AWS ELB?

**Comment by titanous** [comment]
@tzusman There should be no need to register/unregister anything, enable TCP load balancing on ports 80/443.

**Comment by tzusman** [comment]
It's possible that I'm missing something bigger picture with Flynn (I've been reading through the docs the last few days).  Would Flynn work well with Elastic Beanstalk?  Provision the AWS environment (hosts, ELB, elasticsearch, other AWS services), and then have Flynn connect and deploy to the instances?  If this is the case, I understand what you're saying - just have the ELB listening on 80 on every host and wherever the web services pop up, they're available for the ELB.  If this isn't quite how things work, I'm totally confused.

**Comment by titanous** [comment]
I don't think Elastic Beanstalk would be a good fit for deploying Flynn, my understanding is that it is a platform-type thing itself. CloudFormation is most commonly used to deploy Flynn, we use it inside the cloud installer, and others use it as a part of their custom deploy/management systems.

**Comment by titanous** [comment]
Also, I should note that there is typically no need to use ELB, Flynn has its own load balancer.

**Comment by tzusman** [comment]
Why would there be a need for round robin DNS then?  I like the idea of the ELB managing SSL automatically, as well as (sort of) handling DDOS attacks.

**Comment by titanous** [comment]
Flynn's router does TLS termination. You can use ELB to load balance TCP to the Flynn router if you think that it will block specific attacks, I'm not aware of the specifics of ELB's DDoS mitigation capabilities.
