### ISSUE TITLE
dashboard: Document how to view system apps

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2109]
Adding `system=true` to the URL params will show all the system apps (e.g. https://dashboard.demo.localflynn.com/apps?system=true).

There should be a link somewhere in the UI to toggle this param.

**Comment by philiplb** [comment]
@jvatic 
Somewhat soonish, I would like to tackle this. :)
Would a simple UI like this do it?

<img width="492" alt="screen shot 2016-06-28 at 23 04 46" src="https://cloud.githubusercontent.com/assets/1672238/16432358/d90754e4-3d84-11e6-8ec6-b71beed43b8d.png">

Here, the system application flag is given. The link would be "Show system applications" if the flag is not given.
I didn't give him the button classes to make it not so prominent.

**Comment by jvatic** [comment]
That should be fine.
