### ISSUE TITLE
Installation Failure, Error 403

### ISSUE THREAD

**Issue by mvd7793** [flynn/flynn#2116]
Hello! I'm getting this error when trying to install flynn.

===> 05:33:50.226 running "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin"
INFO[11-11|05:33:50] initializing TUF client 
EROR[11-11|05:33:50] error updating TUF client                err="GET https://dl.flynn.io/tuf/e734e0b15a229bcc93ed103be46bc69fcfb365769ad687f64c019ab6ec06aad633dbf4be23bea621e538c478e4eb01b054f50f6889c25454b06c1b7a9c84ad0b.snapshot.json: unexpected HTTP status 403"
05:33:50.563714 host.go:132: GET https://dl.flynn.io/tuf/e734e0b15a229bcc93ed103be46bc69fcfb365769ad687f64c019ab6ec06aad633dbf4be23bea621e538c478e4eb01b054f50f6889c25454b06c1b7a9c84ad0b.snapshot.json: unexpected HTTP status 403
===> 05:33:50.565 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 1

**Comment by titanous** [comment]
Looks like we hit #1703 again. I've fixed it, the changes are propagating through the CDN. Let me know if you have any further trouble.

@lmars please fix this.
