### ISSUE TITLE
(Re-)Setup of flynn fails.

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2117]
Hi,

I'm trying to setup my cluster again via

```bash
sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
```

But now it stops with this error:

> INFO[11-11|11:09:50] initializing TUF client
> EROR[11-11|11:09:51] error updating TUF client                err="tuf: failed to decode timestamp.json: version 1249 is lower than current version 1251"
11:09:51.700631 host.go:132: tuf: failed to decode timestamp.json: version 1249 is lower than current version 1251
===> 11:09:51.706 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 1

Any clue?

**Comment by philiplb** [comment]
Resolved via

```bash
sudo rm -r /etc/flynn
```

**Comment by lmars** [comment]
FYI I believe this is caused by #1703 which I will be fixing shortly.
