### ISSUE TITLE
dashboard: Implement name generator

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2124]
Implement [controller/name pkg](https://github.com/flynn/flynn/blob/master/controller/name/name.go) in JavaScript and use it to generate a default app name.

**Comment by titanous** [comment]
Might make more sense to expose a name generator API from the controller.

**Comment by jvatic** [comment]
Yeah, maybe. It would be good to have it all in one place, though I was thinking the word list is relatively small and could easily be shared and the logic is fairly simple. Having it on the client would prevent a few ms delay between the launch view opening and the name appearing.

**Comment by jvatic** [comment]
If the client were to anticipate the launch view opening however (e.g. a page with a launch button loaded) and make the API call ahead of time, then the delay wouldn't be an issue.
