### ISSUE TITLE
Please add a "--leader" switch to the "flynn route" command

### ISSUE THREAD

**Issue by hazelesque** [flynn/flynn#2126]
Hi there!

I really like the way Flynn comes with data replication "from the moment you turn the key".

However, I'd like to be able to connect to the database remotely, so that I can set up an off-site postgresql instance as a streaming replica.

I asked in the #flynn IRC channel about my needs, and whilst I *can* add a route with "flynn -a postgres route add tcp -s postgres-postgres -p 5432", it looks like it **isn't** possible to configure the route to always send traffic to the leader.

Would it be possible for you to add a "--leader" switch to the "flynn route" command, to route traffic to the service leader only?

Thanks in advance for considering my feature request.

Kind Regards,

Hazel Smith

**Comment by temujin9** [comment]
:+1: this opens up great possibilities for data-layer migration, which is going to be a need for us soon.

**Comment by hazelesque** [comment]
Thanks!
