### ISSUE TITLE
Namespace existing "app" commands as sub-commands of `flynn app`

### ISSUE THREAD

**Issue by imjorge** [flynn/flynn#2127]
Perhaps we should namespace existing "app" commands under `flynn app`:
- `flynn app create` (instead of `flynn create`)
- `flynn app delete`  (instead of `flynn delete`)
- `flynn app list`  (instead of `flynn apps`)
- `flynn app` (could be used for listing info or, more verbose, `flynn app info`) [ see #2107 ]

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
