### ISSUE TITLE
router: Support TLS TCP routes

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2136]
I should be able to define a TCP route with TLS enabled:

```
$ flynn -a postgres route add tcp -s postgres -p 5432 --tls-key <file> --tls-cert <file>
```

**Comment by 256dpi** [comment]
I could really use this. I'm happy to contribute, If anyone can point out to me what needs to be changed where.

**Comment by titanous** [comment]
@256dpi This would be implemented in the router: https://github.com/flynn/flynn/blob/master/router/tcp.go

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
