### ISSUE TITLE
question: rebalancing / rescheduling containers when a node fails

### ISSUE THREAD

**Issue by jokeyrhyme** [flynn/flynn#2138]
I did search in a few places, but I did not find the answer...

When cluster has multiple nodes, and one of the nodes fails, does the scheduler automatically restart the containers on that node elsewhere?

If this isn't currently the case, is this something that is planned, or that you'd welcome a PR for?

**Comment by titanous** [comment]
@jokeyrhyme No, there would be three containers, but two would be on a host that didn't go down.

**Comment by jokeyrhyme** [comment]
Ah, okay. Well, that seems fine, actually. It could be disruptive to have a container migrated back unnecessarily.

Assuming a resurrected node is available to the scheduler for new containers / scale commands, I think that's everything I need to know here.

Thanks, @titanous and @josephglanville . :)
