### ISSUE TITLE
question: multi-tenant security / container network isolation

### ISSUE THREAD

**Issue by jokeyrhyme** [flynn/flynn#2139]
From here: https://flynn.io/docs/security

> Applications run within Flynn are not fully sandboxed and have access to internal Flynn APIs that can be used to gain root access on the server. Do not run untrusted code in Flynn.

From the documentation, I understand that Flynn is currently designed for single-tenant usage.

In a multi-tenant scenario, untrusted code should execute _without_ being able to access sensitive APIs / configuration data. Is this something that is planned, or that you'd welcome a PR for?

**Comment by KidkArolis** [comment]
Is there currently any way to run untrusted apps on a Flynn cluster? E.g. by pushing Docker images?

If not, what other OSS PaaS would your recommend for this use case :)

**Comment by jokeyrhyme** [comment]
A stepping stone on the way to being able to run untrusted containers is to look at PaaS solutions that are suitable for multi-tenant use. This requires some level of isolation that would be a key ingredient for securely executing untrusted containers.

Kubernetes isn't 100% suitable for multi-tenant usage yet:

-   https://github.com/kubernetes/kubernetes/issues/31824

But these solutions are based on Kubernetes and have _some_ level of multi-tenant support added on top:

-   https://www.openshift.org/

-   https://github.com/hyperhq/hypernetes

**Comment by titanous** [comment]
@KidkArolis Not currently, however we are working towards full multi-tenant security with the ability to run untrusted code: https://github.com/flynn/flynn/projects/1
