### ISSUE TITLE
How to inject apt-get style dependencies?

### ISSUE THREAD

**Issue by megamattron** [flynn/flynn#2143]
Is there a recommended way to add extra dependencies via apt-get? I'm trying to use node-canvas which requires the Cairo libraries. Here's how they recommend using it on Heroku: https://github.com/Automattic/node-canvas/wiki/Installation-on-Heroku but since I have lower level access to the machines I thought maybe I could just install the necessary stuff? It doesn't seem to work though, or at least isn't visible inside the VM.

Thanks very much for the great project!

**Comment by titanous** [comment]
Those instructions look correct. You could also try the [apt buildpack](https://github.com/ddollar/heroku-buildpack-apt) or one of its forks. Modifying the app base image is currently tricky.

**Comment by megamattron** [comment]
Thanks @titanous - related question: is there a way to set an environment variable before you successfully deploy the app? I'm not able to deploy until I set the custom buildpack variable, but can't seem to set the variable yet in the dashboard.

 Thanks again.

**Comment by titanous** [comment]
You should be able to set environment variables in the dashboard while deploying the first version of the app, @jvatic can help in more detail.

**Comment by megamattron** [comment]
I wasn't able to add environment variables from the dashboard before first deploy (the app environment dialog was missing fields and the save button), but I did find a way to do it via command line and was able to deploy after that. Might be worth changing the documentation at https://flynn.io/docs/faq/how-do-i-use-custom-buildpacks to add the cli option.

Thanks for your help!

**Comment by jvatic** [comment]
@megamattron if you're using the dashboard's Github integration to deploy an app, environment variables may be set in the launch modal.

<img width="736" alt="screen shot 2015-11-17 at 12 55 51 pm" src="https://cloud.githubusercontent.com/assets/171040/11219806/95371ba6-8d2a-11e5-96f4-f965d171fce6.png">

**Comment by megamattron** [comment]
@jvatic Ah, that's what that dialog is! I wasn't using the github integration, so I ended up having to use the CLI.

**Comment by jvatic** [comment]
@megamattron The dashboard currently requires there to be an existing release to set env vars, which is an oversight.

**Comment by lmars** [comment]
@megamattron FYI Flynn has the multi buildpack by default ([here](https://github.com/flynn/flynn/blob/master/slugbuilder/builder/buildpacks.txt) is the list of built-in buildpacks, tried in order), so just creating the `.buildpacks` file is enough to use a custom buildpack (you don't need to set the env var).
