### ISSUE TITLE
HTTPS Documentation?

### ISSUE THREAD

**Issue by gilbitron** [flynn/flynn#2144]
Is there any documentation on using custom domains with HTTPS? After using `flynn cluster migrate-domain new.domain.com` I can't access the dashboard anymore as the "Install CA certificate to continue" page keeps showing but the download certificate link doesn't work.

**Comment by titanous** [comment]
What browser/OS are you using?

**Comment by gilbitron** [comment]
Chomre v46 on OS X v10.11.1

**Comment by titanous** [comment]
@jvatic please investigate.

**Comment by diclophis** [comment]
Also, related question maybe... is it possible to use a custom SSL cert at the moment?

**Comment by titanous** [comment]
@diclophis Yes, `flynn route add http` has `--tls-cert` and `--tls-key` flags.

**Comment by jvatic** [comment]
@gilbitron I've reproduced the issue, there's a bug causing the link to download the certificate to be missing the protocol scheme. As such the browser treats it as being relative to the current URL, so the file being downloaded isn't the certificate. As a workaround you can download the certificate from `http://dashboard.CLUSTER_DOMAIN/cert`.

**Comment by gilbitron** [comment]
@jvatic Thanks.

**Comment by gilbitron** [comment]
`flynn -a dashboard env set URL="https://$(flynn -a dashboard env get URL)"` solved the downloading the certificate issue. However the "Install CA certificate to continue" page still persists now for both the flynnhub domain and a custom domain.

If using a custom domain do I need to setup a custom certificate (probably using `flynn route add http`)?

**Comment by titanous** [comment]
@gilbitron You shouldn't need a custom cert (one should be generated), but you can also add a custom route if you want to use different certificate. Have you tried manually changing the URL scheme to `https`? @jvatic will look into the issue, but changing the scheme may be a workaround.

**Comment by gilbitron** [comment]
Yes I tried both `http` and `https` for both the flynnhub domain and a custom domain. I downloaded the certificate for each and nothing got me past the "Install CA certificate to continue" page. I ended up just ditching my cluster and starting a new one.

**Comment by jvatic** [comment]
@gilbitron I'm unable to reproduce the certificate install page loop you described. Did you successfully migrate the domain on the new cluster?

**Comment by gilbitron** [comment]
@jvatic I've not tried yet. Decided it was easier to stick with the flynnhub domain for the moment.
