### ISSUE TITLE
Unable to start 3 node cluster

### ISSUE THREAD

**Issue by diclophis** [flynn/flynn#2147]
I am running into issues starting a 3 node cluster on my AWS account.

The error I am receiving is (wrapped in ansible run output):

	TASK: [bootstrap flynn] *******************************************************
	failed: [50.112.187.130] => {"changed": true, "cmd": "CLUSTER_DOMAIN=devstack.dev.mavenlink.net flynn-host bootstrap --min-hosts 3 --discovery https://discovery.flynn.io/clusters/aa0885ba-193d-4390-b589-87778a93381b", "delta": "0:01:30.389731", "end": "2015-11-17 07:12:53.430267", "rc": 1, "start": "2015-11-17 07:11:23.040536", "warnings": []}
	stderr: 07:11:23.053271 check online-hosts
	07:12:53.429370 check online-hosts error: timed out waiting for 3 hosts to come online (currently 0 online)
	07:12:53.429399 host.go:132: timed out waiting for 3 hosts to come online (currently 0 online)

Below are the links to the debug-collect-info gists:

01: https://gist.github.com/cf00abf4bc9ecec7e7c1

	t=2015-11-17T17:31:28+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
	t=2015-11-17T17:31:28+0000 lvl=info msg="this may take a while depending on the size of your logs"
	t=2015-11-17T17:31:28+0000 lvl=info msg="getting flynn-host logs"
	t=2015-11-17T17:31:28+0000 lvl=info msg="getting job logs"
	t=2015-11-17T17:31:58+0000 lvl=eror msg="error getting job logs, falling back to on-disk logs" err="could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
	t=2015-11-17T17:31:58+0000 lvl=info msg="getting system information"
	t=2015-11-17T17:31:58+0000 lvl=eror msg="error capturing output of \"bash -c tail -n 1000 /var/log/flynn/**/*.log\"" err="exit status 1"
	t=2015-11-17T17:31:58+0000 lvl=info msg="creating anonymous gist"
	t=2015-11-17T17:31:59+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/cf00abf4bc9ecec7e7c1"

02: https://gist.github.com/dab31b8c4908147afa20

	t=2015-11-17T17:30:57+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
	t=2015-11-17T17:30:57+0000 lvl=info msg="this may take a while depending on the size of your logs"
	t=2015-11-17T17:30:57+0000 lvl=info msg="getting flynn-host logs"
	t=2015-11-17T17:30:57+0000 lvl=info msg="getting job logs"
	t=2015-11-17T17:31:26+0000 lvl=eror msg="error getting job logs, falling back to on-disk logs" err="could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
	t=2015-11-17T17:31:26+0000 lvl=info msg="getting system information"
	t=2015-11-17T17:31:26+0000 lvl=eror msg="error capturing output of \"bash -c tail -n 1000 /var/log/flynn/**/*.log\"" err="exit status 1"
	t=2015-11-17T17:31:26+0000 lvl=info msg="creating anonymous gist"
	t=2015-11-17T17:31:27+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/dab31b8c4908147afa20"

03: https://gist.github.com/76784298368ca73e00cb

	t=2015-11-17T17:30:25+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
	t=2015-11-17T17:30:25+0000 lvl=info msg="this may take a while depending on the size of your logs"
	t=2015-11-17T17:30:25+0000 lvl=info msg="getting flynn-host logs"
	t=2015-11-17T17:30:25+0000 lvl=info msg="getting job logs"
	t=2015-11-17T17:30:55+0000 lvl=eror msg="error getting job logs, falling back to on-disk logs" err="could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
	t=2015-11-17T17:30:55+0000 lvl=info msg="getting system information"
	t=2015-11-17T17:30:55+0000 lvl=eror msg="error capturing output of \"bash -c tail -n 1000 /var/log/flynn/**/*.log\"" err="exit status 1"
	t=2015-11-17T17:30:55+0000 lvl=info msg="creating anonymous gist"
	t=2015-11-17T17:30:56+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/76784298368ca73e00cb"

I have not opened the `3000-3500` port range yet because I wasn't ready to start providing custom TCP services.

Also of note is that the DNS entries are only resolvable from within my VPC... not sure if this matters, I also tried to specific the `--external-ip` flag because my nodes have both an internal and external IP address

Any help in debugging this issue would be greatly appreciated!

**Comment by titanous** [comment]
The discovery token is showing three URLs for your hosts: `http://50.112.187.130:1113`, `http://52.34.84.61:1113`, `http://52.34.71.5:1113` are they accessible from the host that is running the bootstrap command?

**Comment by diclophis** [comment]
Ok, it appears its related to our security group settings.

Is it possible to get the bootstrap process to succeed using internal ip addresses?

The issue now is if we set the `flynn-host init --external-ip=XXX` all traffic between nodes ends up bridging outside of the internal network, and thus we are not able to use a self referential security group to only allow `flynn` nodes to talk to 1113 of other `flynn` nodes...

**Comment by josephglanville** [comment]
@diclophis one option is to run the `flynn-host bootstrap` command with `--peer-ips ip1,ip2,ip3`.
I think it might also be possible to create a new discovery token with the internal IPs instead too.

**Comment by titanous** [comment]
I believe if `--external-ip` is set with the internal IPs it will register those on the discover token.

**Comment by diclophis** [comment]
ok, thanks for the replies, I got waylaid on some other tasks and I will report back my findings here shortly

**Comment by titanous** [comment]
Closing, it looks like the original issue was addressed. Feel free to open a new issue if you have further trouble.
