### ISSUE TITLE
Flynn crashed with a 3 node AWS cluster installation

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2151]
https://gist.github.com/rikur/792c89417bf14dee66fa

**Comment by jvatic** [comment]
We need to handle the failure case here: [installer/cluster.go#L347-L374](https://github.com/flynn/flynn/blob/bd560e0c9f11832aef868a9cbd3ea1b353ae8bc1/installer/cluster.go#L347-L374) (check if `target.SSHClient` is nil before trying to close it).

The other issue here is the first host is inaccessible via ssh. @rikur what AWS region and instance type are being used here?

**Comment by rikur** [comment]
Worked on my second attempt.

I think the installer just gave up too quick, it almost timed out on the second installation as well:

INFO[11-17|11:55:29] Event: log: Running bootstrap
INFO[11-17|11:55:29] Event: log: dial tcp 52.34.89.6:22: connection refused
INFO[11-17|11:55:30] Event: log: dial tcp 52.34.89.6:22: connection refused
INFO[11-17|11:55:35] Event: log: online-hosts: start

**Comment by jvatic** [comment]
Yeah, looks like it's worth increasing the number of attempts [here](https://github.com/flynn/flynn/blob/bd560e0c9f11832aef868a9cbd3ea1b353ae8bc1/installer/cluster.go#L359) and maybe wait a bit longer each time.
