### ISSUE TITLE
controller: Include app metadata in more events in the event-stream

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2157]
I would like to listen to the event-stream and access an apps metadata from it, so that I can trigger registering the service to my internal load balancer using the information in the metadata..

I will use ENV vars for now to avoid multiple GET requests on every event.

**Comment by lmars** [comment]
@rikur what events do you want to include the app metadata? Currently both creating and updating an app trigger an `app` event, and both have the app in the event (with only the latter having the metadata because it was empty in the former):

```
$ flynn create my-app
Created my-app
$ flynn meta set foo=bar

# triggered the following events:

data: {"id":92,"app":"bdb99cca-f718-4457-b69b-212b914e0200","object_type":"app","object_id":"bdb99cca-f718-4457-b69b-212b914e0200","data":{"id":"bdb99cca-f718-4457-b69b-212b914e0200","name":"my-app","strategy":"all-at-once","created_at":"2015-11-18T01:11:13.777575Z","updated_at":"2015-11-18T01:11:13.777575Z","deploy_timeout":30},"created_at":"2015-11-18T01:11:13.777575Z"}

data: {"id":93,"app":"bdb99cca-f718-4457-b69b-212b914e0200","object_type":"route","object_id":"65c144c2-cd4b-4cf1-882b-e9243895c751","data":{"id":"65c144c2-cd4b-4cf1-882b-e9243895c751","type":"http","domain":"my-app.my-domain.com","service":"my-app-web","created_at":"2015-11-18T01:11:13.780598Z","parent_ref":"controller/apps/bdb99cca-f718-4457-b69b-212b914e0200","updated_at":"2015-11-18T01:11:13.780598Z"},"created_at":"2015-11-18T01:11:13.784403Z"}

data: {"id":94,"app":"bdb99cca-f718-4457-b69b-212b914e0200","object_type":"app","object_id":"bdb99cca-f718-4457-b69b-212b914e0200","data":{"id":"bdb99cca-f718-4457-b69b-212b914e0200","meta":{"foo":"bar"},"name":"my-app","strategy":"all-at-once","created_at":"2015-11-18T01:11:13.777575Z","updated_at":"2015-11-18T01:11:13.777575Z","deploy_timeout":30},"created_at":"2015-11-18T01:11:23.901018Z"}
```

**Comment by rikur** [comment]
Sorry for no clear answer, but I think any event that changes the state of the app should have the metadata on it. That way my SES listener can read the metadata and decide if it needs to act on it.

At the same time, ENV values often contain secrets that should not be broadcasted. What are your thoughts on that? Should they be left out from all events? Also, once there's some ACL built into the controller, I think the same should apply: metadata could be available with "READ" permission, ENV vars only with "WRITE" permission.

**Comment by titanous** [comment]
The plan is to move secrets out of the env vars, and yes, there will be quite granular permissions.

**Comment by lmars** [comment]
@rikur ok so I assume you want to watch both release and formation events and have the app metadata in there. The only issue there is that releases don't actually belong to a specific app, an app has a `release_id` which points at the current release for that app, but there is no link the other way (a release could be the current release for multiple apps).

Maybe we should just make releases belong to an app, because all use cases currently associate releases with just one app.

**Comment by jvatic** [comment]
@lmars we do have an [`app_release` event](https://github.com/flynn/flynn/blob/e400c10bd1290c12e90be4deecb0b3ea9436433e/controller/types/types.go#L253) that could be made to include the app json. Though if we're going to include the full app data for each event associated with one, that should probably be added to [`Event`](https://github.com/flynn/flynn/blob/e400c10bd1290c12e90be4deecb0b3ea9436433e/controller/types/types.go#L237-L245).

**Comment by rikur** [comment]
A wild idea: how about having an app_metadata event?

**Comment by jvatic** [comment]
@rikur does the `app` event (emitted each time an app is created or updated) not serve that purpose?

**Comment by rikur** [comment]
I somehow missed that.. That's all I really needed.

**Comment by rikur** [comment]
@titanous flynn env set never kicks of an app event, only app_release

**Comment by titanous** [comment]
That sounds right, the app doesn't get modified?

**Comment by jvatic** [comment]
The `release_id` field for the app is modified.

**Comment by titanous** [comment]
Isn't that what the event is about?

**Comment by rikur** [comment]
Works for me. Just thought it was a bit odd - the behaviour of the app can change quite a bit depending on the ENV vars.
