### ISSUE TITLE
Show deploy progress in git push

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2161]
We should print the deploy events that happen during the last part of a `git push` like we do in `flynn scale`.

**Comment by imjorge** [comment]
@titanous you mean that instead of:

```
=====> Waiting for web job to start...
=====> Default web formation scaled to 1
```

you want something like:

```
15:37:48.001 ==> web host-692d8a7f-3ae4-4ad9-80ba-634e521225e2 starting
15:37:48.906 ==> web host-692d8a7f-3ae4-4ad9-80ba-634e521225e2 up
```

**Comment by titanous** [comment]
Yeah.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
