### ISSUE TITLE
Deployer should not rollback if jobs fail to stop in a timely manner

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2162]
If we're doing an `all-at-once` deploy and the jobs fail to stop quickly, the deploy is rolled back, which doesn't make a ton of sense.

**Comment by lmars** [comment]
We use the same [60s timeout](https://github.com/flynn/flynn/blob/master/controller/worker/deployment/job.go#L299) when waiting for either up or down events, are you saying 60s is not long enough to wait for a job to stop, or that you are seeing it timeout much quicker than that?

**Comment by titanous** [comment]
I'm saying that after we've started the new jobs (and they are up) and requested that the old jobs stop, there's not much more we can do. Rolling back doesn't make a ton of sense because it involves stopping the new (working) jobs.

**Comment by imjorge** [comment]
So for this specific error https://github.com/flynn/flynn/blob/master/controller/worker/deployment/all_at_once.go#L75 we want to skip the rollback?

**Comment by lmars** [comment]
@imjorge sounds right yes
