### ISSUE TITLE
Command to ssh into flynn cluster

### ISSUE THREAD

**Issue by SebastianSzturo** [flynn/flynn#2167]
It would be great to have an easy way to ssh into a flynn cluster. Right now, [the documented way](https://flynn.io/docs/faq/how-do-i-ssh-to-flynn-cluster-hosts) to do this is to find out the ip of my cluster and run `ssh -l root -i ~/.flynn/installer/keys/flynn <ip>`

Maybe something like `flynn cluster ssh <cluster-name>` would be easier?

**Comment by elimisteve** [comment]
Yes please.  I was just looking for a way to shell in, and 

> $ ssh -i flynn-1455102435.pem ubuntu@xx.yy.zz.ww

gives me

> Enter passphrase for key 'flynn-1455102435.pem': 

and I don't see such a passphrase in ~/.flynnrc or elsewhere.

**Comment by elimisteve** [comment]
Got it, and now I realize that @SebastianSzturo actually mentioned this above :-) --

> ssh -i ~/.flynn/installer/keys/flynn ubuntu@xx.yy.zz.ww

**Comment by holtgrewe** [comment]
I don't see a `~/.flynn/installer/keys/flynn` file on my flynn host and also not on my workstation. Am I doing something wrong?

**Comment by elimisteve** [comment]
```bash
$ ls -R .flynn
.flynn:
ca-certs  installer

.flynn/ca-certs:
flynn-1448790966.pem  flynn-1455102435.pem  flynn-1455158138.pem
flynn-1450149441.pem  flynn-1455156337.pem

.flynn/installer:
data.db  keys

.flynn/installer/keys:
flynn  flynn.pub
```

**Comment by elimisteve** [comment]
^^ That's on my local machine, not the server(s) I'm deploying to.

**Comment by holtgrewe** [comment]
This is all I am seeing.

```
$ ls -R ~/.flynn
.flynn:
ca-certs

.flynn/ca-certs:
default.pem
```

**Comment by elimisteve** [comment]
@holtgrewe And you've deployed a cluster with Flynn?

**Comment by holtgrewe** [comment]
yes

**Comment by holtgrewe** [comment]
I used the install script on the server and not `flynn install` locally, though.

I removed everything from the server and redeployed using `flynn install` (forgetting to remove `~/.flynn`, my bad) and things are the same.

**Comment by titanous** [comment]
The SSH key will only be created if `flynn install` provisioned your infrastructure (AWS, Azure, DigitalOcean). If it did not provision the infrastructure, you specified the SSH key for the servers somewhere (and already have it if you managed to install Flynn over SSH).

**Comment by holtgrewe** [comment]
Then this was a misunderstanding, I assumed this meant ssh'ing as root into the containers not the cluster...

**Comment by titanous** [comment]
Ah. We don't run an SSH daemon inside of containers managed by Flynn.
