### ISSUE TITLE
various issues git push hangs, flynn create causes unknown_error: Something went wrong...

### ISSUE THREAD

**Issue by burma-shave** [flynn/flynn#2168]
I'm working with a 3 node cluster in Azure. Installing flynn was a breeze; its great to be a able to deploy my own PaaS quickly and easily.

Everything worked fine for the first few pushes, but I'm now getting various intermittent errors, such as:

* flynn create in new repos fails intermittently with `unknown_error: Something went wrong`.
* flynn log hangs or returns `GET https://controller.qj13.flynnhub.com/apps/kookaburas-amuse-caradoc/log?follow=true: httpclient: raw req: unexpected status 503`
* git push hangs on certain repos

repairing the cluster sometimes seems to improve things temporarily (but difficult to tell), here is the output of `flynn-host fix --min-hosts 3`:
```
INFO[11-19|16:48:30] found expected hosts                     n=3
INFO[11-19|16:48:30] ensuring discoverd is running on all hosts 
INFO[11-19|16:48:30] checking flannel 
INFO[11-19|16:48:30] flannel looks good 
INFO[11-19|16:48:30] waiting for discoverd to be available 
INFO[11-19|16:48:30] checking for running controller API 
INFO[11-19|16:48:30] found running controller API instances   n=2
INFO[11-19|16:48:30] found controller instance, checking critical formations 
INFO[11-19|16:48:30] checking postgres 
INFO[11-19|16:48:30] found running postgres leader 
INFO[11-19|16:48:30] found 2 running postgres instances 
INFO[11-19|16:48:30] getting postgres status 
INFO[11-19|16:48:30] postgres claims to be read-write 
INFO[11-19|16:48:30] checking for running controller API 
INFO[11-19|16:48:30] found running controller API instances   n=2
INFO[11-19|16:48:30] found controller instance, checking critical formations 
INFO[11-19|16:48:30] scheduler looks up, moving on 
INFO[11-19|16:48:30] cluster fix complete 
```
Here is the debug gist:
https://gist.github.com/anonymous/f7d4d7cfcb8d2fcc9301

I noticed there appear to be some SQL errors in there to do with the blob store.
E..g
```
2015/11/19 06:25:01 discoverd: heartbeat blobstore (100.100.23.6:80) failed: unknown_error: Something went wrong
2015/11/19 06:25:11 error: ERROR: cannot execute INSERT in a read-only transaction (SQLSTATE 25006)
```

flynn version is: v20151104.1

**Comment by titanous** [comment]
This looks like a variant of #2027, I think the fix merged in #2145 will help, and this should be fully resolved when #2158 is done.
