### ISSUE TITLE
flynn installer azure subscription is empty

### ISSUE THREAD

**Issue by talarari** [flynn/flynn#2176]
hey,
i tried setting up a flyn cluster in azure.
installed the cli on my dev machine and ran the installer web interface.
went through the steps (active directory and keys etc)
and the subscription box is always empty, what am i doing wrong?
![flynn](https://cloud.githubusercontent.com/assets/4973087/11362851/f5815a48-929e-11e5-9297-e42aaa1d177f.png)

**Comment by talarari** [comment]
looking at the web console i see an xhr request for subscriptions but it returns an empty array:
http://localhost:52461/azure/subscriptions?credential_id=6004991d-2481-49bf-93cc-ca04d82db239
returns []

**Comment by jvatic** [comment]
@talarari do you see any error in the command line output?

**Comment by talarari** [comment]
i deleted and re added the credentials, this is all i'm seeing
![image](https://cloud.githubusercontent.com/assets/4973087/11371910/71c3c4fe-92d3-11e5-9855-b6b406593417.png)

**Comment by jvatic** [comment]
@talarari can you confirm the existence of a subscription by logging into https://portal.azure.com and selecting "Subscriptions" on the left?

**Comment by talarari** [comment]
yeah definitely have a subscription.
maybe i'm missing something and the AD app has to be connected to the subscription somehow?

**Comment by jvatic** [comment]
I'd double check the user used to create the app has the appropriate role settings and is linked to the subscription.

**Comment by talarari** [comment]
Any news?

**Comment by jvatic** [comment]
@talarari I've been unable to reproduce the issue unfortunately.

**Comment by talarari** [comment]
OK thanks I'll give it another go, if I keep having problems I'll try to set up a repro for you and open a new issue. Closing this
