### ISSUE TITLE
host: Stopping a job which is already stopped should mark it as down

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2188]
In [this host log](https://gist.github.com/rikur/33e5c1fc84776f6f22d0), requests to stop a job are failing with:

```
INFO[11-26|22:36:43] stopping job                             app=host pid=3154 host.id=ip100054 fn=StopJob job.id=ip100054-d2934ade-5628-47d5-b13c-447723375ea4
2015/11/26 22:36:43 Client.Signal write unix /.container-shared/rpc.sock: broken pipe
EROR[11-26|22:36:43] write unix /.container-shared/rpc.sock: broken pipe req_id=b3bbe5fd-d86e-4c66-bb83-1e8bcbf23a38 component=host
INFO[11-26|22:36:43] request completed                        req_id=b3bbe5fd-d86e-4c66-bb83-1e8bcbf23a38 component=host status=500 duration=725.536µs
```

So the scheduler is receiving a 500, not receiving a stopped event, and then trying to stop it again 30s later in `SyncJobs`.

The job is not actually running ([confirmed by rikurr in IRC](https://botbot.me/freenode/flynn/2015-11-26/?msg=55042525&page=5)), so the host should just mark it as stopped in the state and emit an event, allowing the scheduler to continue along on its merry way...

**Comment by titanous** [comment]
This was implemented in #2833.
