### ISSUE TITLE
host: Add `flynn-host exec`

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2189]
I should be able to execute a command in the same namespaces as a running job (like [docker exec](https://docs.docker.com/engine/reference/commandline/exec/)).

There is `virsh lxc-enter-namespace` but it doesn't work for me:

```
$ virsh -c lxc:/// lxc-enter-namespace host-b174628b-59d0-4937-b99a-d60dc5140f96 bash
libvirt:  error : argument unsupported: Security model none cannot be entered
```

**Comment by lmars** [comment]
FYI you can call [`setns`](http://man7.org/linux/man-pages/man2/setns.2.html) from a Go program to enter namespaces, but you need to do [this](https://github.com/golang/go/issues/8676#issuecomment-66098496).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
