### ISSUE TITLE
docs: Document how to use an explicit host IP address

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2190]
If I create a 3 node cluster using Vagrant + VirtualBox + explicit IPs in Vagrantfile, I end up with `eth0` all having address `10.0.2.15` and `eth1` having the explicit IP address, and by default Flynn will use the `eth0` address which will prevent the cluster from booting.

We should document how to configure this type of cluster (mainly just specifying `--external-ip` in a few places, or perhaps we should support `--external-iface=eth1` so we don't need to hard code the IPs).

**Comment by Cosmin-Ecom** [comment]
I can confirm this is working.
What is needed is to change `flynn-host daemon --external-ip="IP"` in `/etc/flynn/upstart.conf` and also to run `flynn-host init` with the extra parameter `--external-ip "IP"`, IP being the VMs host-only network IP.

**Comment by lmars** [comment]
@Cosmin-Ecom thanks for confirming, we will get this documented soon.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
