### ISSUE TITLE
bootstrap: Controller crash shouldn't wait for timeout

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2195]
If the controller crashes after the `run-app controller` step, it isn't going to be started again as there is no scheduler yet, but bootstrap waits for a full minute before returning an error.

This really only affects development, hopefully the controller won't crash when bootstrapped by users :smile:

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
