### ISSUE TITLE
pinkerton: Support Docker registry V2

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2196]
We currently expect to pull Docker images from a Docker V1 registry (see [here](https://github.com/flynn/flynn/blob/master/pinkerton/registry/docker.go)) but V1 has been deprecated.

We should support pulling from a V2 registry, perhaps vendoring [some of the Docker code](https://github.com/docker/docker/blob/master/registry/session.go).

**Comment by rikur** [comment]
+1

**Comment by dts** [comment]
+1

**Comment by rdrsss** [comment]
+1
