### ISSUE TITLE
Dynamic scaling for applications

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2209]
Some of our developers are going to need the ability to dynamically scale their applications according to in-app load, which may present in any number of ways (e.g. SQS queue length, number of records in a ES query, etc.) not directly available to Flynn. It would be good if there was a way for those applications to handle measurement of those variables themselves, and then signal Flynn (from within the app) to scale up or down processes in response.

**Comment by titanous** [comment]
> It would be good if there was a way for those applications to handle measurement of those variables themselves, and then signal Flynn to scale up or down processes in response.

This can currently be done by having the monitoring process use the Flynn API to scale the formation up, though hooking up "auto scaling" of some type is definitely a future thing we want.

**Comment by temujin9** [comment]
Issue is that such would currently involve giving the monitoring process the keys to the API, which is (to my eye, at least) a security risk.

**Comment by titanous** [comment]
Makes sense. We'll be adding granular authorization throughout Flynn in the near future so that risk will be mitigated.

**Comment by abagshaw** [comment]
Any progress on this?

**Comment by lmars** [comment]
@abagshaw beyond the idea of having a monitoring process which runs `flynn scale` as required, no explicit progress has been made on this.

**Comment by abagshaw** [comment]
If we were using GCP - is there some way to use Google's auto-scaler to automatically bring new compute instances online from an image that contains Flynn if the CPU usage reaches a certain threshold - and when the new instance is brought online it is automatically added to the Flynn cluster and Flynn can begin to spread processes to it?

**Comment by abagshaw** [comment]
Actually I suppose one problem with this would be scaling down - GCP's auto scaler could terminate a node that may be still handling a few requests resulting in those final few requests failing. Is that why auto-scaling and load-balancing has to be done by the same service?

**Comment by josephglanville** [comment]
Not sure about GCP but AWS for instance has lifecycle hooks and termination notices for ASGs that you can use to drain nodes when scaling down.

**Comment by abagshaw** [comment]
Does Flynn have an easy way to pipe those terminations notices in and then automatically drain the node - or is that something that will require custom modification of the source?

**Comment by josephglanville** [comment]
Flynn currently doesn't have this capability but it is something that could be added to the scheduler.
If you are interested in working on this feature I am sure myself or other Flynn developers can provide guidance.

**Comment by abagshaw** [comment]
I don't have time to work on that right now - but if I do have some time in the future I'll get in touch and get some direction on how to tackle this. Thanks!

**Comment by WriteCodeEveryday** [comment]
This is the last feature I really need to move a whole bunch of clients' systems off of AWS ElastiBean. 

@lmars What are the odds we could get a "checkbox" right next to the process control in the dashboard (web, console, and such) that would just bump the number by 1 (if resources are being used close to the max - CPU, RAM in the underlying docker container) and decrease the number by 1 (if resource use is dropping)?

I don't need super granular control (over what exactly what the amount to trigger a resize should be) but something that won't exceed the Layer 0 hardware and cause instability would be awesome, and I could sell it as the "future plan". Help me Obi Wan Marshall, you're my only hope.

If I could write Go code in some manner, I'd take a crack at it myself but I'm a total noob that went the Rails route.

**Comment by temujin9** [comment]
Several of our users are currently running per-application autoscaling, by installing Flynn within the application and using it to signal the cluster as necessary. This feels a "more correct" path to take, as what counts as load worth responding to is a very individual thing to the process: some of them, for instance, scale based on the size of an external queue that they process.

**Comment by WriteCodeEveryday** [comment]
@temujin9 I rather like this approach but there should be some official documentation with best practices for this. I don't want to throw a .flynnrc file in there, commit it to Github and start loading it into Rails.

**Comment by eyalrosen** [comment]
@temujin9 regarding "using it to signal the cluster as necessary" - could you please share an example of how Flynn can signal when the app requires scaling?

**Comment by WriteCodeEveryday** [comment]
@temujin9 Oh man, we just kicked a hornet's nest. There's like 7 people on this Issue and all of them want their Flynn scaling and they want it now.

**Comment by temujin9** [comment]
@WriteCodeEveryday We currently use a sidecar application to ship credentials (via S3) in a secure manner. You could also use environmental variables, if you don't want to go that far.

@eyalrosen Unfortunately, the example code is proprietary, so I cannot share it directly. However, the core of it is simple to describe: ship in Flynn credentials, make your scaling decisions in your code, and then shell out to the flynn binary and call `flynn scale [proc]=[N]` as appropriate.

**Comment by WriteCodeEveryday** [comment]
@temujin9 Now I want to write a Rails gem for this. Maybe something on top of resource_monitor.

Why do you hate my weekends, man?

**Comment by eyalrosen** [comment]
@WriteCodeEveryday that would be amazing :)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
