### ISSUE TITLE
Git auth error Windows

### ISSUE THREAD

**Issue by adusak** [flynn/flynn#2215]
Hi I stumbled upon a problem in my fresh flynn instalation on Windows.
I created new flynn instance on Digital Ocean - everything went fine, but when I wanted to push app to flynn I got an error message saying command failed and asked for username and password to the flynn remote.

I found out that the paths to flynn certificate and flynn executable in the .gitconfig files were malformed and i needed to replace them with working paths.

The way they are generated
```[credential "https://git.9err.flynnhub.com"]```
	```helper = C:\\Users\\melku\\AppData\\Roaming\\flynn\\bin\\flynn.exe git-credentials```

The way they should be
```[credential "https://git.9err.flynnhub.com"]```
	```helper = C:/Users/melku/AppData/Roaming/flynn/bin/flynn.exe git-credentials```

**Comment by jvatic** [comment]
@adusak what version of windows are you using?

**Comment by adusak** [comment]
Windows 10 Home 1511, Build 10586.14

**Comment by patricialutar** [comment]
I had the same experience but i don't have any credential information in the .gitconfig file.
flynn version: v20151126.0
powershell version: 4.0
windows version: 8.1 [Version 6.3.9600]

Here is a test:

```
PS C:\dev\Azure\Flynn\TestRepo> git init
Initialized empty Git repository in C:/dev/Azure/Flynn/TestRepo/.git/
PS C:\dev\Azure\Flynn\TestRepo> git add *
PS C:\dev\Azure\Flynn\TestRepo> git commit -m "Test"
[master (root-commit) 1330fad] Test
 2 files changed, 3 insertions(+)
 create mode 100644 Procfile
 create mode 100644 index.php
PS C:\dev\Azure\Flynn\TestRepo> flynn create test
Created test
PS C:\dev\Azure\Flynn\TestRepo> git remote -v
flynn   https://git.[id].flynnhub.com/test.git (fetch)
flynn   https://git.[id].flynnhub.com/test.git (push)
PS C:\dev\Azure\Flynn\TestRepo> git push flynn master
C:\Users\Patrícia\AppData\Roaming\flynn\bin\flynn.exe git-credentials get: C:UsersPatríciaAppDataRoamingflynnbinflynn.exe: command not found
Username for 'https://git.[id].flynnhub.com':
```

After hardcoding those credential information with this command below ...

```
git config --local credential.https://git.[id].flynnhub.com.helper "C:\\Users\\Patrícia\\AppData\\Roaming\\flynn\\bin\\flynn.exe git-credentials"
```

or

```
git config --local credential.https://git.[id].flynnhub.com.helper "C:/Users/Patrícia/AppData/Roaming/flynn/bin/flynn.exe git-credentials"
```

... it was working "fine", but it's a workaround :-(

```
PS C:\dev\Azure\Flynn\TestRepo> git push flynn master 
C:\Users\Patrícia\AppData\Roaming\flynn\bin\flynn.exe git-credentials get: C:UsersPatríciaAppDataRoamingflynnbinflynn.exe: command not found
C:\Users\Patrícia\AppData\Roaming\flynn\bin\flynn.exe git-credentials store: C:UsersPatríciaAppDataRoamingflynnbinflynn.exe: command not found
Counting objects: 4, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
[...]
remote: =====> Application deployed
remote: =====> Waiting for web job to start...
remote: =====> Default web formation scaled to 1
To https://git.[id].flynnhub.com/test.git
 * [new branch]      master -> master
PS C:\dev\Azure\Flynn\TestRepo>
```

**Comment by nobert** [comment]
@patricialutar: did the shell from which you installed flynn have access to the git command? I just ran into a similar issue where the flynn installer was started from Powershell, but git on that system only worked from inside the bash that ships with git for Windows.

**Comment by nobert** [comment]
@patricialutar Did the shell from which you originally ran `flynn install` have access to `git`? I ran into this same problem when `git` was only in the path from the `bash` shell that ships with git for Windows, i.e. not from the Powershell that `flynn install` ran from.

(deleted the original comment by accident)
