### ISSUE TITLE
Ubuntu Flynn install connection refused

### ISSUE THREAD

**Issue by hmontazeri** [flynn/flynn#2217]
Hi

i tried to install flynn on my remote vm using
`L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L`

`flynn install` 
But i can't connect to the web interface. Always get connection refused on the browser...
`<ip>:<given port>`
I disabeld firewall -> didn't work

**Comment by adusak** [comment]
I got stuck on this "problem" as well, that is until I figured out how it works.
You install flynn on your local machine, run the installer on your local machine and during the install process you point it to your remote VM, and it installs the necessary tools on the remote.

On your local machine you then use the flynn CLI to deploy and manage your applications.

**Comment by lmars** [comment]
@hmontazeri sorry that the documentation is not clearer, but as @adusak says you should run `flynn install` on your local machine.

I have opened #2222 to address improving the documentation.
