### ISSUE TITLE
Documentation Request: How to alter the Apache config of a PHP application

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2219]
Hi,

I wonder how I can make adjustements to the Apache Config for a PHP application? Like memory limits, upload limits etc.. Two things I'd like to configure:
- Apache config for this very application
- PHP config for this very application

**Comment by titanous** [comment]
For now look at the docs on Heroku for the buildpack, we'll add docs to our site in the future.

https://devcenter.heroku.com/articles/custom-php-settings

**Comment by philiplb** [comment]
Alright, thank you. :)

**Comment by philiplb** [comment]
Would be done via https://github.com/flynn/flynn/pull/2223
