### ISSUE TITLE
Documentation Request: How to install PHP extensions

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2220]
Hi,

I'd love to know how I can install/manage PHP extensions for a single application? Maybe one app uses Postgres, maybe another uses MySQL. Both might use the cUrl extension etc.

**Comment by philiplb** [comment]
I just ran into an use case for this: I'm using the FOSUserBundle in my symfony 2 application which is highly popular. I need to activate this extension for it: php_mbstring

**Comment by titanous** [comment]
Try adding `ext-mbstring` to the `require` section of your `composer.json`.

**Comment by philiplb** [comment]
That did the trick, thank you. :) A hint towards the heroku PHP stuff would solve this for people like me who never touched this topic before. :)

**Comment by philiplb** [comment]
Actually, there is a hint towards the PHP buildpack. A sentence "look here for further configuration" would be great I guess.

**Comment by lmars** [comment]
@philiplb the current docs for PHP apps can be found [here](https://github.com/flynn/flynn/blob/master/docs/content/how-to-deploy-php.html.md), feel free to PR some changes that you would have found useful!

**Comment by philiplb** [comment]
Will do, thank you. :)
