### ISSUE TITLE
Routes lost of an application

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2221]
Hi,

I deployed a Symfony 2 application. It's up and running fine. But suddenly, the flynn dashboard lost all routes. And on the command line, the route list doesn't work, too:

```bash
flynn route
```

With this output:

> GET https://controller.........com/apps/myApp/routes: httpclient: raw req: unexpected status 503

Here is the debug gist:
https://gist.github.com/b49ca6570372af4d3ada

The interesting part is: The app is still available under the standard flynn url.

**Comment by titanous** [comment]
I wonder if these errors from the router have anything to do with it:

```text
2015/12/02 13:29:23 router: sync error: crypto/tls: private key does not match public key
```

Did you specify a TLS certificate for one or more routes?

**Comment by philiplb** [comment]
Yes, but it was a wrong one. It was for *.foo.mydomain.com where the application was running under:
- myapp.flynn.mydomain.com -> standard flynn domain
- myapp.foo.mydomain.com -> an additional route with a CNAME dns entry
This failed due to browsers not accepting the wildcard certificate as it didn't match the flynn domain to which the domain was pointing to.

Good that letsencrypt launches tomorrow. :)

**Comment by titanous** [comment]
Closing as #2442 tracks the long-term fix for this issue.

**Comment by philiplb** [comment]
Nice, thx.
