### ISSUE TITLE
host: Updating breaks the Upstart status

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2224]
Running `flynn-host update` causes `flynn-host` to spawn a new child process with the latest binary and then exit, and this causes the Upstart job to be marked as stopped (because Upstart tracks jobs using PIDs).

We should investigate if there is a way to make Upstart more aware of this update process.

**Comment by titanous** [comment]
There isn't. Upstart is stupid. There is no way that I've seen to fix this issue. I think the only workaround is to do this:

```text
pre-start exec ./bin  >> bin.log 2>&1 &
post-stop exec start-stop-daemon --stop --pidfile bin.pid
```

**Comment by titanous** [comment]
Closing, when we move to systemd (#2789) this will no longer be an issue and this doesn't come up often.
