### ISSUE TITLE
Cloud Installer: Azure - expired OAuth Token & Cluster delete

### ISSUE THREAD

**Issue by patricialutar** [flynn/flynn#2225]
I wanted to create a new cluster but the registered OAuth token is expired. It's ok but after the expiration i cannot delete the cluster which is attached to an expired token and i cannot delete the expired token because is attached to a cluster. It's a catch-22 situation.

Maybe some token swapping method will be a solution?

I cloud not find out how to refresh those tokens at the Azure management portal.

**Comment by jvatic** [comment]
@patricialutar I will push a fix for this soon to enable assigning a new token to a cluster. For now you can delete the resource group in the [azure portal](https://portal.azure.com/) and click the eye icon that appears in the installer after opting to delete the cluster to remove it from the local db.

**Comment by patricialutar** [comment]
@jvatic: I did it with my 3-node cluster but the "eye icon" is just hid the cluster because it appeared after i executed the ``` flynn cluster ``` command. I had to delete in manually with the ``` flynn cluster remove <clustername> ``` command.

**Comment by jvatic** [comment]
@patricialutar yes, the installer doesn't currently remove clusters from the flynnrc, I've opened a separate issue for that (#2226).

**Comment by kengoldfarb** [comment]
+1

@jvatic : After manually removing the resource group, etc. how can I force flynn to re-authenticate with Azure so I can install a new cluster?

I'm still getting oauth errors when I go to the Azure tab on the installer.

**Comment by jvatic** [comment]
@kengoldfarb select "New" from the credentials dropdown to re-authenticate

**Comment by kengoldfarb** [comment]
Ah...right in front of my face.  Thanks!
