### ISSUE TITLE
Cluster failing notice

### ISSUE THREAD

**Issue by patricialutar** [flynn/flynn#2228]
I made an 3-node cluster and a 1-node cluster on Azure. The PaaS deployment went good but the 3-node cluster is unstable.

It was a fresh new cluster. I attached my github account and i deployed my forked php-flynn-example repository. The first deployment crashed and needed to be deleted, i tried again. It went good and everything seemed fine. I raised the web scale to 3 and the dashboard went in none-deterministic state with this repo that means i refreshed the page but the app was either visible or invisible (like Schrödinger's cat), then i executed the command below so i cloud not find out what is the problem. Is not be propagated well the app to all node?

```
PS C:\dev\Azure\Flynn\TestRepo> flynn -c [cluster name] apps
ID                                    NAME
051f91f6-b425-491a-b6ec-b01790954922  patricialutar-php-flynn-exampl
1b4595d8-80d1-4e32-b4fc-7346d838b190  status
6287cc8d-afbe-4e08-a523-ceaeb195dd24  dashboard
c8fbdf96-7f77-4c91-942e-99146bdd9420  taffy
78e5a79d-c99d-419b-8143-21aacd5623f8  logaggregator
5ed80910-ab94-4e51-a4f4-85a38fea9a36  gitreceive
45ddf38a-7ebd-4f84-a9ae-751972230b12  router
ac48bc39-2017-4517-90d4-e4473e382eaa  blobstore
d7eb507f-ff3d-4585-bd10-f772be665d48  discoverd
a93879de-1fb6-4a38-b91e-312863e39edf  flannel
eb394fa7-b8e0-4fb2-9e8d-0ebdb64c35bf  postgres
e159107a-3861-4d05-8094-8d7335d6f7ae  controller
```

I thought it was a good plan to deploy again the app under another name and everything went bad. After that i got this:
```
PS C:\dev\Azure\Flynn\TestRepo> flynn -c [cluster name] apps
flynn : GET https://controller.[id].flynnhub.com/apps: httpclient: raw req: unexpected status 503
At line:1 char:1
+ flynn -c [cluster name] apps
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (GET https://con...cted status 503:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

I did SSH my cluster host and they seems to be working. I updated the flynn-host with the ``` sudo flynn-host update ``` command and fixed with the ``` sudo flynn-host fix --min-hosts 3 ``` command as well. Now the ``` flynn -c [cluster name] apps ``` is working again and there is no error, but the app is either visible or unvisible on the dashboard after every refresh. By the way the application is available. I can not delete the app via the dashboard or the CLI.

I decided to delete the whole cluster but i wanted to notice the situation.

**Comment by jvatic** [comment]
Can you post the region and size used?

**Comment by patricialutar** [comment]
North Europe; Standard_D2; 3-node

**Comment by titanous** [comment]
Closing, without logs it's not really possible to diagnose this.
