### ISSUE TITLE
PHP Application went down over night

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2232]
Hi,

17h ago, I deployed a PHP app and it was running smoothly along. Now it went down.
Those are the last log entries:

> 2015-12-02T17:12:46.679553Z app[web.flynn1-84de37e3-53a3-4a04-b1a2-a4ccdb538b8f]: Application ready for connections on port 8080.
> 2015-12-02T17:13:21.451011Z app[web.flynn1-84de37e3-53a3-4a04-b1a2-a4ccdb538b8f]: Going down, terminating child processes...

The collection of the debug gist hangs at "getting job logs". But I could give you temporary SSH access to the cluster if you like?

**Comment by titanous** [comment]
Closing, I believe this issue was fixed in #2171.
