### ISSUE TITLE
installer: Allow adding more nodes to running cluster

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2237]

**Comment by philiplb** [comment]
+1
(Thought this is already possible?)

**Comment by jvatic** [comment]
@philiplb you can manually add nodes to a cluster, this is for being able to do so through the installer UI

**Comment by aaronshaf** [comment]
`you can manually add nodes to a cluster`

How?

**Comment by josephglanville** [comment]
@aaronshaf simply starting another node with the discovery token or using the `--peer-ips` argument is enough to add a new node to the cluster.

Note that this node will not participate in consensus so the existing nodes will need to remain members of the cluster until dynamic membership is implemented.

You can remove this new node by simply powering it down or terminating the flynn-host process.

Do not remove nodes from the existing set used to bootstrap due the consensus issue mentioned above.

**Comment by philiplb** [comment]
@josephglanville is dynamic membership implemented now? What do you do if one of your original machines used to bootstrap just dies and never comes back and you have to setup a new one?

**Comment by josephglanville** [comment]
It's not yet implemented though changes have been merged upstream that may make this possible. We will be looking into this shortly along with other improvements to discoverd.

**Comment by jvatic** [comment]
I think this is better managed in the controller/dashboard/cli with platform-aware clusters (#2687).
