### ISSUE TITLE
Cluster in an undefined state

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2241]
Hi,

I'm playing arround with letsencrypt. To get my certs, I needed port 80 on my first machine of the cluster. So I temporarly stopped flynn-host. After restarting it, I needed multiple tries to modify my routes: Like 4 in 5 times, flynn route answered with

> Post https://controller.........com/apps/myApp/routes: dial tcp 213.73........:443: connection refused

This is what flynn-host ps on the first machine gave me:

> ID                                           STATE    STARTED         CONTROLLER APP         CONTROLLER TYPE
> flynn1-aff1eb28-b419-4b70-9f0b-1396452989c1  running  17 minutes ago  blobstore              web
> flynn2-80a2ed31-d7df-400c-95b0-58b2b44c8f89  running  27 minutes ago  discoverd              app
> flynn2-106fefa1-c73f-432d-acb0-994380634fc7  running  27 minutes ago  status                 web
> flynn2-15c1f7fb-05cf-4256-a9f9-4631fd39847a  running  27 minutes ago  controller             worker
> flynn1-8e930eb2-9cf5-45fb-9d0c-7f86e6b9eb26  running  16 hours ago    myApp  web
> flynn1-d50b9817-a6f6-462a-8eed-ce9fc4832216  running  16 hours ago    status                 web
> flynn2-0949316c-3fdf-4f39-a31f-4ace4eff176d  running  16 hours ago    dashboard              web
> flynn1-aff44ae1-158f-472c-88ac-124fdd63e672  running  16 hours ago    dashboard              web
> flynn2-964fd054-2260-4f46-b037-6e85f1a4b06d  running  16 hours ago    logaggregator          app
> flynn1-875b4ab5-156b-4c54-9243-729e6c4fa891  running  16 hours ago    logaggregator          app
> flynn2-3e1132c2-0110-41dd-91b1-0c567b3ded87  running  16 hours ago    gitreceive             app
> flynn1-b86f171b-dd67-45c4-a3de-2dc130b8cd51  running  16 hours ago    gitreceive             app
> flynn2-63cd63f8-7f5a-48aa-8db5-a54a9cef9756  running  16 hours ago    router                 app
> flynn1-a6d9c865-01f8-47dd-8961-766f677f72fa  running  16 hours ago    router                 app
> flynn2-5f2c646e-1039-487f-9038-d0603e800232  running  16 hours ago    blobstore              web
> flynn2-f8b72616-19be-4052-97b4-f8d9216c7986  running  16 hours ago    controller             web
> flynn1-bfdb7f3e-05c3-43ec-8859-c506ce1cd9d1  running  16 hours ago    controller             worker
> flynn1-10079698-29b0-4638-96b0-659b238f0fe2  running  16 hours ago    controller             scheduler
> flynn2-316b622a-e939-43eb-9522-edcea84b683e  running  16 hours ago    controller             scheduler
> flynn0-f2c9039e-434b-4da4-b5f7-7a79b4963922  running  16 hours ago    controller             web
> flynn2-98fc5ba5-302d-4e3b-8541-4cece78dc96d  running  16 hours ago    postgres               web
> flynn1-65990563-2963-4a86-870f-233a037a5854  running  16 hours ago    postgres               web
> flynn1-b61848c7-90b4-4046-83f4-bd227d5bd65c  running  16 hours ago    postgres               postgres
> flynn2-0c6f786e-db3f-4599-ab5b-4f17848cf694  running  16 hours ago    postgres               postgres
> flynn2-681d66a2-be60-4395-b91c-32f5e409375c  running  16 hours ago    flannel                app
> flynn1-cf1b7ce0-d58a-4e6e-8742-51a650248ce7  running  16 hours ago    flannel                app
> flynn1-44154587-83cb-4e40-962c-f53ce0c8d147  running  16 hours ago    discoverd              app
> flynn0-2c1e9972-aa46-4622-bcca-fe6b1dfaf586  running  16 hours ago    discoverd              app

So I restarted flynn-host on the first machine again. Now flynn-host ps gives me just that:

> 11:14:47.072828 host.go:135: could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused

Here is a gist from the first machine:
https://gist.github.com/70c23d5e27c9507d4a68

Collecting the infos on the first machine resulted in:

> EROR[12-04|11:18:03] error getting job logs, falling back to on-disk logs err="could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"

So I collected them on the second machine as well:
https://gist.github.com/ca4273e7a0e285a5479e

**Comment by philiplb** [comment]
Is this relevant? Or might I close this?

**Comment by titanous** [comment]
We have other issues about fixing up TLS cert handling (#2442) so we can close this one.

**Comment by philiplb** [comment]
Alright, thx.
