### ISSUE TITLE
Azure install should use Azure Resource Manager templates

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#2242]
Azure recently launched the Azure Resource Manager, which supports defining clusters via templates. This appears to be Azure's version of AWS CloudFormation. It supports e.g. defined networking, virtual machine images, RAID configurations, so we can speed up cluster creation and potentially have better performance tuning.

**Comment by titanous** [comment]
I'm pretty sure we already use this. /cc @jvatic

**Comment by jvatic** [comment]
Yes, [here's the template we're using](https://github.com/flynn/flynn/blob/cd38cb10e58e3e655eec24594840a679ce9a446e/installer/azure_template.go). It may be worth looking into optimizing it if documentation has improved.
