### ISSUE TITLE
Status page empty?

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2248]
Hi,

when I visit the flynn status page (status.....com), I only get an empty page with an HTTP 401.
How can I access it? It sounds like something usefull to monitor the cluster.

**Comment by lmars** [comment]
@philiplb the status endpoint returns a JSON object containing the status and version of the system components, and is protected by basic auth for clients outside the cluster.

You can get the auth key by running `flynn -a status env` and then using that as the basic auth password (empty username):

```
$ curl -u ":$AUTH_KEY" http://status.example.com
```

Or you can make the request from inside your cluster without the auth key:

```
$ flynn run curl http://status-web.discoverd
```

**Comment by philiplb** [comment]
Hi,
works perfectly fine, thank you. :)
