### ISSUE TITLE
flynn installer: drop the web interface

### ISSUE THREAD

**Issue by th3m4ri0** [flynn/flynn#2255]
Would it be better to drop the web interface for `flynn install` and use a standard command line input instead ? Or enable both ? I'm sure power users would like it :)

**Comment by lmars** [comment]
@th3m4ri0 there are a lot of options and steps when installing a Flynn cluster via `flynn install` (choosing a provider, choosing the size of the cluster, adding credentials etc.).

We are certainly open to exposing some options via the CLI, but to be honest I think most power users (myself included) would just boot their own servers and install Flynn themselves.

WDYT?

**Comment by th3m4ri0** [comment]
Your right, and that's what I ended up doing !
