### ISSUE TITLE
Dashboard: environment setting timeout

### ISSUE THREAD

**Issue by th3m4ri0** [flynn/flynn#2256]
On a rather large (62M) Rails application, setting environment variables from the dashboard times out.

**Comment by th3m4ri0** [comment]
<img width="771" alt="capture d ecran 2015-12-07 a 14 54 30" src="https://cloud.githubusercontent.com/assets/2685884/11637963/759f4be2-9cf2-11e5-9bd5-72e59a66599e.png">

**Comment by th3m4ri0** [comment]
`flynn env set` gets stuck for a lonnnnng time. Does it trigger a complete rebuild ?

**Comment by th3m4ri0** [comment]
The problem was that application start was crashing. Should the dashboard handle this case ?

**Comment by jvatic** [comment]
I believe this was fixed with #2605
