### ISSUE TITLE
controller: Improve job states

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2259]
The scheduler currently saves the following job states to the controller:

* `starting` - the job has been accepted by a host and is in the process of starting
* `up` - the job is running on a host
* `down` - the job is no longer running on a host, and exited with a zero exit status
* `crashed` - the job is no longer running on a host, and exited with a non-zero exit status
* `failed` - the job was accepted by a host but failed to start (e.g. the job's command was invalid)

I propose consolidating `down`, `crashed` and `failed` to just `down`, with extra fields on job (e.g. `ExitStatus` and `HostError`) to distinguish between them.

I also propose adding a new `pending` state for jobs which are either in the process of being started due to a recent formation change (i.e. [the `JobStateNew` state in the scheduler](https://github.com/flynn/flynn/blob/master/controller/scheduler/job.go#L37-L40)), or are scheduled to start in the future (i.e. [the `JobStateScheduled` in the scheduler](https://github.com/flynn/flynn/blob/master/controller/scheduler/job.go#L33-L35)), with an extra `RunAt` field so you can tell when the job is expected to be started.

The `pending` state will also be used when a job has been requested but cannot currently be placed in the cluster (e.g. the process type is tagged with `foo=bar` but no host currently has that tag, so the job will be pending until the tags can be satisfied).

So jobs would have the following states:

* `pending` - job will be started sometime in the future (either at `job.RunAt` or when tags are satisfied)
* `starting` - the job has been accepted by a host and is in the process of starting
* `up` - the job is running on a host
* `down` - the job was placed in the cluster but is no longer running on a host

There is an issue here that jobs in the controller have IDs like `hostID-UUID`, but `pending` jobs won't have a `hostID`. The scheduler gets around this by [only using the UUID part to identify a job](https://github.com/flynn/flynn/blob/master/controller/scheduler/job.go#L45-L51), should the controller also just use the UUID?

@titanous @josephglanville @jvatic thoughts?

**Comment by jvatic** [comment]
Backwards compatibility could be an issue with consolidating `down`, `crashed`, and `failed` (see [controller/client WaitFor](https://github.com/flynn/flynn/blob/master/controller/client/client.go#L70-L108) which the cli uses).

Other than that, this sounds reasonable. Maybe add a `HostID` field to `Job`? The UUID should be unique enough.

**Comment by titanous** [comment]
SGTM. Splitting out the UUID is fine and has the added benefit of being able to use the native PG UUID type for the jobs table.

**Comment by josephglanville** [comment]
To add to what @titanous is saying I think it would go some way to addressing #1761
Overall, SGTM.

**Comment by lmars** [comment]
Done in #2265 and #2295.
