### ISSUE TITLE
controller: Redundant endpoint for updating app

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2260]
#1618 introduced `POST /apps/:app_id/meta` which does almost exactly the same thing as `POST /apps/:app_id` (except it allows passing an empty object to clear the app meta).

**Comment by jvatic** [comment]
Once we have a deprecation system in place (see #2262), I'd like to phase out `POST /apps/:app_id/meta`. Removing `omitempty` from [`App.Meta`](https://github.com/flynn/flynn/blob/e400c10bd1290c12e90be4deecb0b3ea9436433e/controller/types/types.go#L28) would solve the issue of setting it to an empty object, we'd just need to make sure the map is not nil before encoding to avoid `{"meta": null}` responses.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
