### ISSUE TITLE
controller: API versioning

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2261]
- Require requests to specify the API version they expect (header and URL param, header taking precedence)
- Report current API version in response header (there should probably be an endpoint such as `GET /version` for this as well)
- Return an error if the requested API version is not compatible

**Comment by jvatic** [comment]
We need a schema for each API version to determine compatibility (which would allow only returning an error if the requested endpoint is not compatible).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
