### ISSUE TITLE
controller: API deprecation

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2262]
- There should be a page in the docs listing all deprecated endpoints and when they will be removed (possibly generated from a `GET /deprecations` endpoint?)
- Requests to a deprecated endpoint should return a header specifying when it will be removed

**Comment by jvatic** [comment]
Dependent on #2261

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
