### ISSUE TITLE
Dashboard consuming quite a lot of memory

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2266]
Hi,

the dashboard is consuming a quite high amount of memory, see attached screenshot.
![screen shot 2015-12-09 at 10 02 24](https://cloud.githubusercontent.com/assets/1672238/11680956/2a304466-9e5c-11e5-8906-7d8b2d7b17b7.png)

This is the machine of the cluster where I ran the init-discovery, the "first" machine of the cluster.

The second node has also a quite high amount of memory reserved to the dashboard, here arround 25%.

The third node is just fine.

Is there a way to get it down? Or might it be a leak? Or is it expected?

**Comment by kwando** [comment]
See #1776

**Comment by philiplb** [comment]
Ah, nice. :)
Duplicate then.
