### ISSUE TITLE
Dashboard not available anymore

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2275]
Hi,
I ran into memory problems due to the dashboard. Until a version with this fixed memory leak is released, I wanted to calm it down a bit with a trick I read in the leak ticket:

```bash
flynn -a dashboard scale web=0
flynn -a dashboard scale web=1
```

According to

```bash
flynn-host ps
```

the dashboard is running and I can for example watch some logs via

```bash
flynn -a dashboard log
```

But I can't visit it anymore in the browser:

> Service Unavailable

Here is the usual debug gist: https://gist.github.com/05c3d23f85a518494eba

How can I recover?

**Comment by titanous** [comment]
@lmars Looks like this might be a scheduler issue? I see a dashboard process that didn't get terminated correctly (`flynn1-210b56f8-2b06-488d-b682-f9ad57157642`).

**Comment by lmars** [comment]
It looks like job `flynn1-210b56f8-2b06-488d-b682-f9ad57157642` was killed but failed to go down, see the following at the end of the log:

```
t=2015-12-10T09:49:02+0000 lvl=info msg="received signal" app=containerinit fn=babySit type="child exited"
t=2015-12-10T09:49:02+0000 lvl=info msg="command exited" app=containerinit fn=containerInitApp service=dashboard-web port=80 proto=tcp status=2
```

but it is still marked as running on the host:

```
ID                         flynn1-210b56f8-2b06-488d-b682-f9ad57157642
Entrypoint                 
Cmd                        
Status                     running
```

@philiplb it looks like you scaled up to 2 and then back down to 1 (which leaves just this stuck job). When you scaled to 2, was the dashboard available?

**Comment by philiplb** [comment]
If I remember correctly, it was like this: I scaled down, got an error message (sry, can't remember which one :(), scaled up with a success message. I scaled down again to 0 with a success message and scaled up to 1, again with no error. And then the dashboard was history.

**Comment by lmars** [comment]
@philiplb ok please scale the dashboard to 2 and see if it becomes available.

**Comment by philiplb** [comment]
I've resetup the cluster already. Will try to reproduce this at some point.

**Comment by lmars** [comment]
@philiplb ok thanks, I have opened #2286 to track the underlying issue here.
