### ISSUE TITLE
containerinit: Not exiting when killed by signal

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2286]
In [this debug info](https://gist.github.com/anonymous/05c3d23f85a518494eba), job `flynn1-210b56f8-2b06-488d-b682-f9ad57157642` was killed but failed to go down, see the following at the end of the log:

```
t=2015-12-10T09:49:02+0000 lvl=info msg="received signal" app=containerinit fn=babySit type="child exited"
t=2015-12-10T09:49:02+0000 lvl=info msg="command exited" app=containerinit fn=containerInitApp service=dashboard-web port=80 proto=tcp status=2
```

but it is still marked as running on the host:

```
ID                         flynn1-210b56f8-2b06-488d-b682-f9ad57157642
Entrypoint                 
Cmd                        
Status                     running
```

This leaves the job marked as running in the controller, so scaling down and back up doesn't replace the job.

Originally reported in #2275.

**Comment by titanous** [comment]
I believe this was resolved by #2505.
