### ISSUE TITLE
flynn install error: "No 'Access-Control-Allow-Origin' header is present"

### ISSUE THREAD

**Issue by elimisteve** [flynn/flynn#2294]
I'm on the page where I'm supposed to install the Flynn SSL cert, which for me is `http://localhost:38303/clusters/flynn-1450149441`.  I installed the cert, and when I click "All Done", nothing happens in the UI but I see these errors in the JS console:

> XMLHttpRequest cannot load https://dashboard.969w.flynnhub.com/ping. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:38303' is therefore not allowed access.

I then get the same error twice:

```
flynn-1450149441:1 Uncaught (in promise)
["", XMLHttpRequest]
```

```
flynn-1450149441:1 Uncaught (in promise) 
["", XMLHttpRequest]
```

It's worth noting that, when I look at the output from `flynn install` in my terminal, I get the my dashboard URL, which I can then visit and log into using the token also provided in the console.

flynn version: v20151214.2

**Comment by elimisteve** [comment]
When I visit https://dashboard.969w.flynnhub.com/ping and https://dashboard.969w.flynnhub.com/ manually, in a new tab, I don't get an SSL error.

CORS issue, looks like.

**Comment by elimisteve** [comment]
I did _not_ have this issue with flynn version `v20151126`, or `v20151126.0`, I believe it was called.

**Comment by jvatic** [comment]
@elimisteve can you ssh into the cluster and run `flynn-host collect-debug-info`? This sounds like the dashboard is unavailable (and possibly other services).

**Comment by jvatic** [comment]
@elimisteve it's possible you're encountering a router bug fixed by #2291

**Comment by titanous** [comment]
@jvatic I might have broken this with my CORS changes?

**Comment by jvatic** [comment]
@titanous looks like that's the case, must have missed it when testing. I'll push a fix shortly.

**Comment by jvatic** [comment]
@elimisteve the cert should be installed, the installed is just unable to verify via the ping endpoint. Navigating to https://dashboard.969w.flynnhub.com/ in your browser should work (the token can be retrieved via `flynn -a dashboard env get LOGIN_TOKEN`).

**Comment by elimisteve** [comment]
@jvatic Yes [I was able to visit that page without SSL errors](https://github.com/flynn/flynn/issues/2294#issuecomment-164636547), thanks.

**Comment by jvatic** [comment]
@elimisteve Ah, missed that comment. The fix will be in the next release.
