### ISSUE TITLE
Lots of containerinit processes

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2299]
Currently, there are lots of containerinit processes on my yesterday freshly setup flynn cluster, first machine. The other two don't have it.
I don't know if this behaviour is intended so I'm better reporting it. :)

Logs: https://gist.github.com/0b7477bf0d63806a9be6

See this image:

![screen shot 2015-12-15 at 10 09 42](https://cloud.githubusercontent.com/assets/1672238/11806603/91b8a4cc-a314-11e5-80bd-57758a42ff55.png)

**Comment by titanous** [comment]
There's nothing wrong here. If you look at the process tree in the debug log you'll see 14 containerinit processes, one supervises each job on the cluster. The screenshot you posted shows that they each have a few threads. These processes should be very lightweight (each one is using less than 3MB of memory).

**Comment by philiplb** [comment]
Alright, thanks. :)
