### ISSUE TITLE
The logaggregator is consuming quite a lot of memory

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2304]
Hi,

see this:
![screen shot 2015-12-16 at 14 17 29](https://cloud.githubusercontent.com/assets/1672238/11841776/e49e5312-a3ff-11e5-94ae-b38b280ef62b.png)

This cluster is running now since a few days.

Normal or memory leak? :)

**Comment by titanous** [comment]
The logaggregator stores up to 10k lines from each app in memory. It may make sense to allow tweaking this for hosts with low resources.

**Comment by philiplb** [comment]
I think this is fine.
