### ISSUE TITLE
Deployment of a Symfony 2.7 PHP application fails

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2308]
Hi,

I'm trying to deploy an PHP application and suddenly, I get this:

> remote: [1G[K[1G-----> Compiled slug size is 109M[K
> remote: [1G[K-----> Creating release...[K
> remote: Error deploying app release: web process type failed to start, got down job event[K
> To https://git.........com/....git
> ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.........com/....git'

Log:

> 2015-12-16T16:20:58.960826Z app[web.flynn0-db77e7bf-9304-4088-b08d-cf6003406723]: Using Apache2 VirtualHost-level configuration include 'apache_app.conf'
> 2015-12-16T16:20:59.043666Z app[web.flynn0-db77e7bf-9304-4088-b08d-cf6003406723]: 4 processes at 128MB memory limit.
> 2015-12-16T16:20:59.048682Z app[web.flynn0-db77e7bf-9304-4088-b08d-cf6003406723]: Starting php-fpm...
> 2015-12-16T16:21:01.050160Z app[web.flynn0-db77e7bf-9304-4088-b08d-cf6003406723]: Starting httpd...
> 2015-12-16T16:21:01.058308Z app[web.flynn0-db77e7bf-9304-4088-b08d-cf6003406723]: Application ready for connections on port 8080.
> 2015-12-16T16:21:01.242660Z app[web.flynn0-54f50d1f-41b6-4901-976e-86befc453cc6]: Going down, terminating child processes...
> 2015-12-16T16:23:19.570054Z app[web.flynn0-177dcf75-c18e-4d1e-b27b-fd6f4389c208]: tar: This does not look like a tar archive
> 2015-12-16T16:23:19.570420Z app[web.flynn0-177dcf75-c18e-4d1e-b27b-fd6f4389c208]: tar: Exiting with failure status due to previous errors
> 2015-12-16T16:23:19.938508Z app[web.flynn0-ec31f3cd-0597-4fbd-9498-76c9c047b068]: tar: This does not look like a tar archive
> 2015-12-16T16:23:19.938816Z app[web.flynn0-ec31f3cd-0597-4fbd-9498-76c9c047b068]: tar: Exiting with failure status due to previous errors

**Comment by titanous** [comment]
That error typically indicates that the app slug was not successfully retrieved. Take a look at the blobstore log with `flynn -a blobstore log`

**Comment by philiplb** [comment]
Hi,

thanks. This is the blobstore log during the failing deploy:
> 2015-12-16T16:33:14.079802Z app[web.flynn0-54d86f60-fec0-4085-a5e1-26b7a20f7853]: 2015/12/16 16:33:14 GET /9bf22aa6-03f0-4f45-a215-57a6e89ba163.tgz
> 2015-12-16T16:33:35.739417Z app[web.flynn0-54d86f60-fec0-4085-a5e1-26b7a20f7853]: 2015/12/16 16:33:35 GET /repos/a5babc3a-dcb6-4cde-b831-80d5931e7b41.tar
2015-12-16T16:33:36.919802Z app[web.flynn0-54d86f60-fec0-4085-a5e1-26b7a20f7853]: 2015/12/16 16:33:36 GET /repos/a5babc3a-dcb6-4cde-b831-80d5931e7b41.tar
> 2015-12-16T16:33:47.873976Z app[web.flynn1-598b7c6a-ece0-4c85-8328-6bbaa0c73e26]: 2015/12/16 16:33:47 GET /a5babc3a-dcb6-4cde-b831-80d5931e7b41-cache.tgz
> 2015-12-16T16:35:22.779797Z app[web.flynn0-54d86f60-fec0-4085-a5e1-26b7a20f7853]: 2015/12/16 16:35:22 PUT /3ca0c389-a164-4790-9cf8-c5a53dd9dfc5.tgz
> 2015-12-16T16:35:39.662087Z app[web.flynn1-598b7c6a-ece0-4c85-8328-6bbaa0c73e26]: > 2015/12/16 16:35:39 PUT /a5babc3a-dcb6-4cde-b831-80d5931e7b41-cache.tgz
2015-12-16T16:35:50.787333Z app[web.flynn0-54d86f60-fec0-4085-a5e1-26b7a20f7853]: 2015/12/16 16:35:50 PUT /repos/a5babc3a-dcb6-4cde-b831-80d5931e7b41.tar

And this line also occures in the blobstore logs:

> 2015-12-16T16:23:18.141623Z app[web.flynn0-54d86f60-fec0-4085-a5e1-26b7a20f7853]: 2015/12/16 16:23:18 discoverd: heartbeat blobstore (100.100.63.7:80) failed: unknown_error: Something went wrong

**Comment by titanous** [comment]
Ah, it looks like there was a discoverd issue while you were deploying. It may have recovered, but the debug logs would be useful.

**Comment by philiplb** [comment]
Tried again, still getting this error.
Debug logs: https://gist.github.com/b2979d7e83485e497205

**Comment by titanous** [comment]
@benbjohnson It looks like discoverd is having some trouble, would you take a look?

**Comment by benbjohnson** [comment]
@titanous I think the network periodically has high latency. `discoverd` seems to be able to elect and hold a leader for a while and then it's showing `"raft: Failed to contact"` errors that show it's not connecting to followers for ~1s which would trigger an election timeout.

We should probably allow `discoverd`'s timeout settings to be configurable. We could also bump up the default settings to something higher than 1 second.

@philiplb Do you have any network latency stats? Do you see high latency between `discoverd` nodes or are you doing anything to saturate your network?

**Comment by philiplb** [comment]
@benbjohnson 
Hi,
there should be no network latency as flynn is the only application running on those three VMs.

**Comment by benbjohnson** [comment]
@philiplb What kind of VMs are you running? It could also be underprovisioned machines that are causing high latency in responding to heartbeats.

**Comment by philiplb** [comment]
Those are Cloud-VMs by www.inter.net. Kinda like Amazon EC2. No clue about the machines behind.

**Comment by titanous** [comment]
Looks like there is no bug here, we've only seen this on machines with very high load.

**Comment by philiplb** [comment]
Alright, thx.
