### ISSUE TITLE
An option for router to do HTTP -> HTTPS permanent redirects

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2310]
I would want to do it on a global level, but maybe a per route setting would also be nice

**Comment by englishm** [comment]
:+1:-ing per @lmars. :smile:

**Comment by philiplb** [comment]
Hi,
this is how I did it on an Apache served PHP application, just put this file in your repo: apache_app.conf

> RewriteEngine On
> RewriteCond %{HTTP:X-Forwarded-Proto} !https
> RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

And this is my Procfile:

> web: vendor/bin/heroku-php-apache2 -C apache_app.conf web/

**Comment by kevinob11** [comment]
Any guidance on how to do this now on an app that doesn't have a web server packaged with it?

**Comment by titanous** [comment]
@kevinob11 Flynn doesn't support apps without web servers, what language/framework are you using?

**Comment by kevinob11** [comment]
Probably wrong wording on my part. I'm running a node app that is served via express.

**Comment by titanous** [comment]
@kevinob11 Looks like there are some middleware options for doing this:

https://www.npmjs.com/search?q=express+ssl

Also, check out https://www.npmjs.com/package/helmet to get HSTS headers.

**Comment by kevinob11** [comment]
Ah just enforce in express instead of having the router handle it, thanks!

**Comment by brettneese** [comment]
Is there any way to get the router to do this for us?

**Comment by brettneese** [comment]
We'd actually be OK if all routes forced SSL, we just really need it to happen at the router level, not the app level.

**Comment by titanous** [comment]
@brettneese This is not currently possible, but we're evaluating doing it in the near future.

**Comment by rikur** [comment]
Pretty please. It can take a lot of effort to modify every individual service to force HTTPS redirects.

**Comment by michaelyork** [comment]
+1 ❤️

**Comment by thomasmodeneis** [comment]
So there is no way to force https, I need to code in every app that rule ? 

@titanous  What is the recommended approach for golang apps ?

Cheers.

**Comment by justingosan** [comment]
+1 ❤️

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
