### ISSUE TITLE
docs: Examples in Using Flynn should be generated

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2311]
[Using Flynn](https://github.com/flynn/flynn/blob/a93d1b782f56f0791c906dd5dd978a1f7890ef61/docs/content/index.html.md) should use generated examples.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
