### ISSUE TITLE
Documentation, SSL issue, stuck on git push line

### ISSUE THREAD

**Issue by wjdp** [flynn/flynn#2323]
On https://flynn.io/docs, where the app gets pushed doesn't seem to work after following the manual install doc here: https://flynn.io/docs/installation/manual. I think this is because we've installed the SSL trust cert into the browser but not the system but no mention of this in the docs.

**Comment by titanous** [comment]
Can you provide the error message you are encountering?

**Comment by wjdp** [comment]
Yep sorry, at first it was timing out. Now getting
```
remote: Internal server error
fatal: unable to access 'https://git.flynn.flatcar.xyz/example.git/': The requested URL returned error: 500
```

**Comment by titanous** [comment]
Hmm, the push is failing on the server side. Please post the debug log collected from a server with `sudo flynn-host collect-debug-info`.

**Comment by wjdp** [comment]
Logs here:

**Comment by titanous** [comment]
It looks like you have a firewall enabled that is preventing communication between containers:

> Get http://46.101.80.124:1113/host/jobs: net/http: request canceled while waiting for connection

**Comment by wjdp** [comment]
You're right, I'd put ufw on as a solution to the firewall requirement. Rather annoying that this breaks container comms

**Comment by titanous** [comment]
Yeah, I don't know anything about ufw, but if you come up with a solution let us know and we can put it in the docs.

**Comment by wjdp** [comment]
Ran across this: https://github.com/docker/docker/issues/1251, seems UFW touches all the iptables chains. Solution for me will be give up and just use iptables.
