### ISSUE TITLE
Cluster service un-available and not responding to scale commands

### ISSUE THREAD

**Issue by thomasmodeneis** [flynn/flynn#2332]
Hi,

I'm in a undefined state where my cluster on digital ocean is not responding to requests, is not scaling up or down either.

```
$ flynn scale web=5
scaling web: 1=>5

Timed out waiting for job events. Waited 20 seconds.
expected: map[web:map[up:4]]
actual: map[]

$ flynn ps
ID                                                     TYPE  RELEASE
flynn14503003612-1108e116-c724-4590-b271-01e9f2e542c1  web   c33b5b18-970f-4199-8f8c-17bebe4ca4f5
```

I made the blind decision to put all my servers to flynn in prod o/, it was all running fine for couple days but then....surprise :( and now I'm offline. Any help is welcome.

Thanks

**Comment by josephglanville** [comment]
Could you login to one of the cluster nodes and run `sudo flynn-host collect-debug-info` and post the gist link here.

**Comment by thomasmodeneis** [comment]
https://gist.github.com/anonymous/e669ab69adade1b50c47

**Comment by josephglanville** [comment]
There are suspect rules in `iptables` output, per chance you have enabled some sort of firewall?

**Comment by thomasmodeneis** [comment]
I just ran the flynn installer to setup the cluster on digitalocean. The instalation got stuck on Install CA certificate step but cluster was created and services where up and running for about two days, then this morning with no apparent reason I got into this state.

This is the output for
```
~# sudo flynn-host ps
07:34:10.509925 host.go:135: could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused 
```

**Comment by titanous** [comment]
Please gist `/var/log/flynn/fbc4ff99-6af0-44a8-99ff-6a94db8bafc5.log` from all of the hosts in the cluster.

**Comment by thomasmodeneis** [comment]
Hi,

I've delete the cluster and created a new but the same problem persists. Sorry I could not get the logs for the old servers before the backup because of a little problem I had with root password.
If you could please let me know 

Now I'm in the new cluster and this is the new gist files:
https://gist.github.com/ec74a355417ac571f100
https://gist.github.com/8c857dc4bb1134465107
https://gist.github.com/c48948d3b0695c693570

**Comment by titanous** [comment]
A few things are happening:

- Your app is crashing with this error:

```text
2015/12/19 18:30:26 Loading standalone localhost:28015
time="2015-12-19T18:30:26Z" level=warning msg="Error creating connection dial tcp 127.0.0.1:28015: connection refused" 
2015/12/19 18:30:26 no connections were made when creating the session
```

- One host decided to shut down for no good reason (I'll open an issue and fix this one)

```text
3072:EROR[12-19|13:33:09] failed to write message                  app=host pid=24565 host.id=flynn14505476100 component=logmux fn=sendToAggregator addr=100.100.51.8:514 error="write tcp 100.100.51.8:514: broken pipe"
```

- For some reason discoverd isn't available at `127.0.0.1:1111`, this is relatively minor and I'll look into it.

**Comment by thomasmodeneis** [comment]
I've moved the cfgs to an old folder and started the install again, setup a new cluster and now the cluster seems to be ok. I believe this has to do with some of the key pem files, it seems to be difficult to manage two clusters at the same time, the configurations get mixed and flynn can't manage this very well.
So I archived the old cfgs with:
```
$ mv .flynnrc .flynnrcoldout the 
$ mv .flynn .flynnold
```

Sorry for the (Error creating connection dial tcp 127.0.0.1:28015: connection refused") that was my bad I did not see it, its related to the internal database configurations I needed to add to env.

After the almost seamless installation with the flynn install via web browser my installation is getting stuck on the Install CA certificate to continue, is there a ticket open for that where I could report the problem or should I create a new one ?

Thanks for the prompt support guys I appreciate that.

**Comment by titanous** [comment]
The CA cert bug is fixed on master, the fix should go out to the release channel in the next few days. In the mean time you can look at the CLI output from the install command to find the URL for the dashboard and the login token.

**Comment by thomasmodeneis** [comment]
I will check out the new release when it comes and retest.
I'm monitoring the new cluster and its working ok now, If happens again in the next days I will report back here. Thanks

**Comment by thomasmodeneis** [comment]
Hi,

It just happened over night again and server is offline again.
```
$ flynn ps
ID                                                     TYPE  RELEASE
```

I wanted to run sudo flynn-host collect-debug-info, but I cant ssh to it, I can't find the ssk-keys flynn uses, can you let me know where it is and how do you manage to connect via root using it?
Otherwise I will have to reset the password.

Thanks

**Comment by jvatic** [comment]
@thomasmodeneis if you used `flynn install`, see https://flynn.io/docs/faq/how-do-i-ssh-to-flynn-cluster-hosts

**Comment by thomasmodeneis** [comment]
Again the cluster is returning 503 and my services are once again offline.

**Comment by thomasmodeneis** [comment]
Logs are reporting last activity:
```
2016-01-02T05:41:17.697881Z app[web.flynn14511354661-ce1e08d8-bc79-4edd-93e0-11d6af33a9c4]: Restart after timeout, (time.Minute)  30
2016-01-02T05:41:17.704583Z app[web.flynn14511354661-35a4fa14-10c0-4ded-affd-d21c06b55ae8]: Restart after timeout, (time.Minute)  30
```

I'm using a timeout chron to restart my apps every 30 minutes, and it seems that somehow the instances ran out of disk space?

```
2016-01-02T05:10:35.786246Z app[web.flynn14511354660-3b9dcc80-22ad-422f-b9d2-ce5534b12a0e]: Restart after timeout, (time.Minute)  30
2016-01-02T05:10:35.787217Z app[web.flynn14511354660-57b7df84-fb73-4682-9788-51b6f8d41e32]: Restart after timeout, (time.Minute)  30
2016-01-02T05:10:35.788706Z app[web.flynn14511354660-90473c63-9a91-4aff-b19d-d2f119d18b66]: Restart after timeout, (time.Minute)  30
2016-01-02T05:10:39.742292Z app[web.flynn14511354660-9e379791-e7ea-4653-b833-b37ca1f312c6]: tar: ./static/admin_static/vendors/flot/examples/series-toggle/index.html: Wrote only 1024 of 1709 bytes
2016-01-02T05:10:39.744303Z app[web.flynn14511354660-a6a9872a-ad5a-4d4d-8826-188b937407d8]: tar: ./static/admin_static/vendors/ckeditor/plugins/pastefromword/filter: Cannot mkdir: No space left on device
2
```

Logs are full of this and eventually by 05:41:17 the services stop completely. 
Any ideas how to deal with this ? This this help to investigate the possible problems ?

Thanks

**Comment by thomasmodeneis** [comment]
I've ran the collect logs and one of the 3 servers, but one was unable to execute the command and failed with following log:

```
root@flynn-1451135466-0:~# sudo flynn-host collect-debug-info
INFO[01-02|08:05:20] uploading logs and debug information to a private, anonymous gist 
INFO[01-02|08:05:20] this may take a while depending on the size of your logs 
INFO[01-02|08:05:20] getting flynn-host logs 
INFO[01-02|08:05:20] getting job logs 
EROR[01-02|08:05:50] error getting job logs, falling back to on-disk logs err="could not get jobs for host flynn14511354660: Get http://...:1113/host/jobs: dial tcp ...:1113: connection refused"
INFO[01-02|08:05:50] getting system information 
INFO[01-02|08:05:50] creating anonymous gist 
3.30 MB / 3.30 MB [=========================================================================================================================================] 100.00 % 956.78 KB/s 3s
INFO[01-02|08:05:54] debug information uploaded to: https://gist.github.com/d4b8259f7aec77f77484 
```

This are the other gists that went ok:
```
https://gist.github.com/9332977e6c295cdbf1aa
https://gist.github.com/83c4aad4a32d51bffcf3
```

**Comment by thomasmodeneis** [comment]
So I restarted the faulty server with shutdown -r and this helped the flynn cluster to recover and the two other servers are now handling the http requests so this is very good.

However I'm waiting now 20 minutes and the restarted server never came back to live.
My plan was to create manually another server and link it to the cluster but I can't find a straight forward explanation for this steps so I decided is better to just create another cluster and update my dns to point to it after its done and online it will be less effort.

**Comment by thomasmodeneis** [comment]
The restarted server is now back, however it seems that flynn failed to start, it will be good to add some documentation about restarting of the OS and how to get your cluster back in shape after such failure.
```
root@flynn-1451135466-0:~# flynn-host ps
08:56:37.192242 host.go:136: could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused
root@flynn-1451135466-0:~# ps -ef |grep flynn
root      1563  1516  0 08:57 pts/0    00:00:00 grep --color=auto flynn
```

**Comment by thomasmodeneis** [comment]
I've restored the services with 3 clusters by creating another one and pointing dns to new cluster and deleting the old one. Hopefully you guys can figure out what maybe wrong with the logs and info provided.
Cheers

**Comment by titanous** [comment]
Cluster restarts are now working properly.

**Comment by thomasmodeneis** [comment]
Right I'm not so clear on this one as I got the problem once again last week and had to restore the servers for the N time, is there a specific as well as commands you said are fixed that you could share with me so I can reproduce/test it ?

Thanks

**Comment by josephglanville** [comment]
@thomasmodeneis there is 2 kinds of resurrection that Flynn currently supports. Single node and cluster resurrection.

Single node resurrection is always carried out and brings back basic services that much always be running. Specifically discoverd and flannel.

Cluster resurrection builds on this to repair the cluster in cases where enough nodes have gone down to actually disable the clusters ability to function, This can happen when say all of the nodes are rebooted at the same time. Cluster resurrection is new and as such has some caveats. For now cluster resurrection will only be carried out if atleast the number of nodes that were present during bootstrap have gone through single-node resurrection routines and are re-registered with the discoverd cluster.
This means that if you reboot all your machines and not all of them come back online then your cluster won't recover by itself right now. But if you were to go and start those machines once they rejoin the cluster resurrection system should be able to bring your cluster back online.
