### ISSUE TITLE
host: Panic when resurrecting jobs

### ISSUE THREAD

**Issue by rachid** [flynn/flynn#2338]
I am not sure what's causing this error, but after a succesfull installation and run, setup none or more than 1 application. When I reboot my server the flynn-host fails to start. 

I mentioned this earlier in issue #2075 and @lmars would have fixed this in PR #2337 thought maybe to be related but the reboot survival, but I don't think this addresses the same problem. The reason I think this because I didn't see anyone else facing the same issue.

This time I included a full log:
https://gist.github.com/anonymous/9c8d0e6a90f208b8c028

Could it somehow have anything to do with the way IP are assigned to containers? I am really stuck here. Also wonder if other face(d) the same problem.

Thanks!

**Comment by rachid** [comment]
Also a debug overview with the nightly build (assuming it includes new changes, correct me if I am wrong.)
https://gist.github.com/anonymous/2c5a18799f9000940e79

**Comment by lmars** [comment]
@rachid the issue you reported in #2075 is indeed fixed in the latest nightly release, but there seems to be another bug resurrecting the jobs. I have proposed a fix in #2339.

**Comment by rachid** [comment]
@lmars thanks for picking this up.
