### ISSUE TITLE
Updating failed maybe

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2341]
Hi,
when updating to the version v20151223.0, those are the last few lines I just got:

> INFO[12-28|19:00:59] flynn-host updated successfully          host=flynn2
> INFO[12-28|19:01:00] flynn-host updated successfully          host=flynn0
> INFO[12-28|19:01:01] flynn-host updated successfully          host=flynn1
> EROR[12-28|18:01:14] cluster status is unhealthy              code=500
> 19:01:16.900933 host.go:136: exec: job exited with status 1

Afterwards, everything still seems to work?

Here is the usual log: https://gist.github.com/a2af5ba63a035797bf1a

**Comment by lmars** [comment]
@philiplb it looks like your cluster is in an unhealthy state which is preventing the update from progressing.

You can get the full status of the cluster by running `flynn run curl http://status-web.discoverd`, can you please gist the output?

**Comment by philiplb** [comment]
Looks like gitreceive is broken?
https://gist.github.com/philiplb/ddc4b800798a55cbda6d
Postgres as well but I don't use it.

**Comment by nobert** [comment]
@lmars I've also had this problem (as mentioned in chat). 

I get:
> EROR[12-28|19:16:13] error deploying app                      name=controller err="timed out waiting for deployment completion"

This breaks the cluster; subsequent runs complain that `cluster status is unhealthy code=500`, which can be fixed via `flynn-host fix`, but a subsequent update will fail at the same spot. I'm also running `v20151223.0`

Cluster debug info: https://gist.github.com/anonymous/58c429d7542776c87d4b

**Comment by philiplb** [comment]
In my case, I just tried to run the update again after a flynn-host fix and now it worked.

**Comment by philiplb** [comment]
I think this one is done now?
