### ISSUE TITLE
Dashboard: Logging system fails intermittently

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#2343]
The logging system in the dashboard is failing intermittently.

This has manifested in the deploy/launch process log viewport never appearing (and not completing successfully, though that may be a separate issue), and by the log view either not showing one or both lists of logs (i.e. deploy or process logs), or by not loading a selected log.

Gist of my cluster exhibiting this problem:
https://gist.github.com/anonymous/58c429d7542776c87d4b

**Comment by titanous** [comment]
This cluster is janky, @lmars please take a look when you have a minute.
