### ISSUE TITLE
"Failed" process left running on host

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2345]
`ip101005522-b644d58d-140c-44ed-a7d2-5de960052e98` is listed as failed by flynn-host, but still shows up as a live process via `ps auxf` (and is still logging, which is how we found it in the first place).

https://gist.github.com/d86a3800cbf25d65fdad has the debug-info.

**Comment by jontonsoup** [comment]
+1 I'm getting this as well

**Comment by temujin9** [comment]
I have not seen instances of this in a while: closing for now.
