### ISSUE TITLE
DHCP failed

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2348]
Hi,

all of a sudden, on all three flynn nodes, the DHCP service stopped working and I had to reboot the machines now.

**Comment by titanous** [comment]
Do you have any error logs? I don't have any ideas what would cause this.

**Comment by philiplb** [comment]
A bit tough to collect meaningfull logs here as the cluster is now in the "rebooted state". Anyway, here are the current debug logs:
https://gist.github.com/41fd72970a3c4bdac5eb

I think there is a high chance that the DHCP error is unrelated to flynn. Just opened the ticket in case it rings a bell at someone.
Could be closed as well as this ticket is so wague.

**Comment by titanous** [comment]
Okay, let us know if you find any reason to believe the problem was caused by Flynn.
