### ISSUE TITLE
Deployment hangs and server CPU is stuck at 100%

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2352]
Hi,

the current deployment is hanging here:

> remote:       Default process types for PHP -> web
> remote: -----> Compiled slug size is 109M

And the CPU is at 100%:
![screen shot 2016-01-06 at 14 06 41](https://cloud.githubusercontent.com/assets/1672238/12143176/c8134c68-b47e-11e5-828d-7edd52820242.png)

Unfortunatly, collecting the debug infos hangs at
 > INFO[01-06|14:07:31] getting system information

I collected this one from another machine of the cluster:
https://gist.github.com/77bf50c97a6d938e6d97

I will leave the cluster in this state until tomorrow and then resetup it to recover. In case the log is not enough, I could add the SSH key from someone of the Flynn-team to the server.

**Comment by titanous** [comment]
Have you identified what processes are consuming the majority of the CPU?

**Comment by philiplb** [comment]
According to htop
heroku-php-apache2

**Comment by titanous** [comment]
That is your PHP/Apache app's process, I'd suggest poking at it to see if you can figure out if anything looks wrong. You could also kill the process and Flynn should start a new instance.

**Comment by philiplb** [comment]
strace reveals nothing, here is the current stack:

> cat /proc/14139/stack
> [<ffffffff811783f2>] generic_file_write_iter+0x32/0xb0
> [<ffffffff811ebe11>] new_sync_write+0x81/0xb0
> [<ffffffffc0644df7>] do_xino_fwrite+0x57/0x90 [aufs]
> [<ffffffffc064521e>] xino_fwrite.part.28+0xe/0x10 [aufs]
> [<ffffffffc064531d>] xino_fwrite+0x6d/0x80 [aufs]
> [<ffffffffc064536f>] au_xino_do_write+0x3f/0xf0 [aufs]
> [<ffffffffc0645ea7>] au_xino_write+0x57/0xe0 [aufs]
> [<ffffffffc06576c5>] au_set_h_iptr+0xc5/0x150 [aufs]
> [<ffffffffc0658602>] au_new_inode+0x4e2/0x710 [aufs]
> [<ffffffffc06592fa>] aufs_lookup+0x16a/0x280 [aufs]
> [<ffffffff811f60ad>] lookup_real+0x1d/0x50
> [<ffffffff811f6aa3>] __lookup_hash+0x33/0x40
> [<ffffffff817ad209>] lookup_slow+0x45/0xab
> [<ffffffff811f8bf1>] link_path_walk+0x361/0x820
> [<ffffffff811f9171>] path_init+0xc1/0x470
> [<ffffffff811f9a20>] path_lookupat+0x20/0x6c0
> [<ffffffff811fa0eb>] filename_lookup+0x2b/0xc0
> [<ffffffff811fd5a4>] user_path_at_empty+0x54/0xa0
> [<ffffffff811fd601>] user_path_at+0x11/0x20
> [<ffffffff811f1450>] vfs_fstatat+0x50/0xa0
> [<ffffffff811f18ef>] SYSC_newstat+0x1f/0x40
> [<ffffffff811f1b5e>] SyS_newstat+0xe/0x10
> [<ffffffff817b770d>] system_call_fastpath+0x16/0x1b
> [<ffffffffffffffff>] 0xffffffffffffffff

**Comment by philiplb** [comment]
The machine seemed somehow to flaky yesterday. I completly restarted from scratch and reinstalled Ubuntu. So this ticket is obsolete now. But thanks. :)

**Comment by thefallentree** [comment]
this is a AUFS bug :-D https://github.com/docker/docker/issues/18180
