### ISSUE TITLE
One AWS instances are stopped and restarted, dashboard cannot reconnect

### ISSUE THREAD

**Issue by matthewsinclair** [flynn/flynn#2353]
This is a newb question, but I must be missing something fundamental about the architecture of Flynn. I'm doing some testing for a prototype and I have successfully created 3 AWS instances, created a Flynn cluster, and then deployed a simple Rails app to the cluster. This all works a treat.

However, if I stop the AWS instances and then restart them, I am no longer able to interact with the cluster from either the command line or the Flynn dashboard. If I kill the Flynn cluster and the recreate it and go thru the reinstall process, then it will work again. 

It seems odd to me that stopping the AWS instances somehow invalidates the cluster and requires it be recreated. I must be doing something really dumb. 

Any clues? Thanks in advance.

**Comment by matthewsinclair** [comment]
Update: I think I can see what is going wrong, but I don't understand how to fix it. When the AWS instances are restarted, they get new IP addresses. However, the local Flynn config is pointing to the previous IP address. How do I update the local Flynn config so that it points to the new IP addresses? 

I notice that there is a `~/.flynn/installer/data.db` file, but it's binary, so it's not something I can just edit.

**Comment by josephglanville** [comment]
Currently there is no way update this configuration reasonably, the Flynn `discoverd` service expects a static set of peers and there isn't really a good way to edit it's parameters.

Did you use the Flynn installer or have you setup the instances yourself? The instances setup by the installer usually retain their IP addresses across stop/start or restarts. So it's possible your AWS configuration is not setup to use VPC?

Full cluster restarts aren't working super well right now and this is being worked on right now however if you stop and then start them all at the same time it "should work", also single node reboots should work.
However rolling reboots are known to be problematic.

**Comment by matthewsinclair** [comment]
Aha, thanks @josephglanville for the quick response. So I'm not going mad! Phew. 

In my scenario, I'm just doing some testing and so I didn't want the AWS instances running when I wasn't using it, so I took them all down (in one go). It appears that they all come up with new public IP addresses after a stop / start. 

Maybe a simple way to set the IP address for the cluster instances would make this workable?

Anyway, thanks again, I'll close this now as at least I am able to understand what it is that is going on.
