### ISSUE TITLE
Is there a benefit to spreading hosts across different VPS providers?

### ISSUE THREAD

**Issue by christiangenco** [flynn/flynn#2355]
ie: would I get any benefit from setting up a three-host cluster with one host on AWS, one on Azure, and one on Digital Ocean (setting each up with ssh)?

Would this give me any fault tolerance if one of the hosts went down, or would everything go down anyway and it's not worth the trouble?

**Comment by titanous** [comment]
This would not work, the inter-host latencies would cause issues with the discoverd raft cluster.

**Comment by christiangenco** [comment]
:+1:  Thank you!
