### ISSUE TITLE
.slugignore file is not used to ignore certain file(s)

### ISSUE THREAD

**Issue by paukiatwee** [flynn/flynn#2359]
I deployed latest Flynn to DO with CLI v20160107.0.

I deploy a [java app](https://github.com/paukiatwee/budgetapp) with `package.json` file at the root. I also have `.slugignore` file at the root to ignore `package.json` file so Heroku will not detect the app as NodeJS app.

However, Flynn failed to use `.slugignore` file to exclude `package.json` file before detect app type (and detected as NodeJS app).

Work around is to [specify custom buildpack](https://github.com/flynn/flynn/blob/master/docs/content/faq/how-do-i-use-custom-buildpacks.md)

However, I am not sure whether Flynn is going to support `.slugignore` file or not. If no, this no longer valid issue.

**Comment by josephglanville** [comment]
This is a bug, we expect `.slugignore` to work.
Generally speaking Heroku compatibilities are considered bugs and we really appreciate reports.
Thanks for bringing to our attention we will get it patched.

**Comment by josephglanville** [comment]
Ok, looks like what needs to happen here is `.slugignore` functionality needs to move from being a `tar` exclude to actually deleting the files before the buildpacks are run. Unfortunately it also seems to support paths with leading slashes, blank lines and comments so will require a little bit of processing. Some old discussion here: https://github.com/flynn-archive/slugbuilder/issues/1
