### ISSUE TITLE
Build hangs on 'controller: docker build controller'

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2365]
The culprit seems to be the "/var/lib/dpkg/info/ca-certificates-java.postinst configure" process, which spawns a defunct Java process. https://github.com/docker/docker/issues/18180 seems to be the ultimate cause. Reproduces every time in our setup.

**Comment by titanous** [comment]
#2366 should fix this. Until we bake the new AMI you can downgrade the kernel to `3.19.0-39` to work around this bug.

**Comment by temujin9** [comment]
How long does the baking take? I can _probably_ just wait for it, and tackle things which don't depend on the build process in the mean time.

**Comment by titanous** [comment]
Should be out by the end of the day tomorrow, needs to go through code review and CI and then the build takes a few hours.

**Comment by temujin9** [comment]
:+1: I can wait that long.
