### ISSUE TITLE
Allow health check configurability

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2369]
Hi,
I don't know if and how Flynn would check the health of an app.
For example, if Flynn could detect a Java application which ran out of DB connections.
Just as an idea:
Defining a ping URL for an application would be cool. Also with a basic auth. If this URL isn't responding within a (definable) timeframe like 30s or if it's throwing N 500 in a row, it could be considered as down.

And then it might escalate:
1. Try N (3?) times to restart the application
2. Try to move it N (3?) times to a different node on multicluster setup
3. Give up and send a panic email

What do you think?

**Comment by titanous** [comment]
There is already support for health checks in Flynn. The `web` process types are monitored by making a TCP connection regularly, this is used to wait to add them to the router as well as to replace them if they stop responding later.

The health check system is flexible and can support HTTP requests as well, but there is currently no way to modify the configuration for an app that was deployed via git.

**Comment by philiplb** [comment]
What we plan now:
Sometimes, a Jetty container or similar fails hard and the application is effectivly dead but still responds with HTTP 500 so Flynns TCP monitoring doesn't catch. To counter this, we could do the following with a list of monitored applications. For each application do:

- Request a specified ping url. This ping url should just return something like '{"ok": true}' and should be publicly available. It must query the applications infrastructure like databases and only if everything succeeds, it gives its ok.
- If the ping url gives something else than "ok", fetch all the process ids of the job (depending on the scale, there could be multiple) via "flynn -a <currentApp> ps"
- Kill each id via "flynn -a <currentApp> kill <currentId>"
- Flynn will now automatically restart the process(es).
- Try this resurrection up to three times with pauses of 5 minutes in between.
- If the application still isn't online, stop trying and send out an email as it might be an error in the infrastructure

This could easily be done via a Jenkins.

**Comment by lmars** [comment]
@philiplb whilst the `web` jobs currently get a [TCP health check](https://github.com/flynn/flynn/blob/v20160624.1/gitreceive/receiver/flynn-receive.go#L204), there is support for a [HTTP health check](https://github.com/flynn/flynn/blob/v20160624.1/host/types/types.go#L145-L167) which can be configured with a path (e.g. `/status`), expected status (e.g. 200) and `KillDown` which will cause the job to stop if the health check fails (and the scheduler to subsequently restart the job).

What we need is a way to expose that health check configuration to end users (most likely via the [Flynnfile](https://github.com/flynn/flynn/issues/1084)).

**Comment by philiplb** [comment]
Ah, interesting.
Would it be worth it to write a small application to perform some own health checks like described above? Or will this be implemented in Flynn itself like you just described at some point?

**Comment by titanous** [comment]
@philiplb The current plan is to expose this functionality in Flynnfiles. For now it can be configured with `flynn release update`.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
