### ISSUE TITLE
Cluster in an undefined state 2.0

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2370]
Hi,
my cluster is in a weird state and not reachable anymore.

What has been done:

- Setup
- Creation of an app
- Deployment of some env-vars to this app
- Deployment of a PHP application
- Added a SSL certificate to the standard route of the application
- Added a second route to the application with a SSL certificate
- Leaving it alone for like 1.5 weeks

Symptoms:

- The application is not reachable
- The dashboard is not reachable
- An attempt to get the status results in this:

```bash
flynn run curl http://status-web.discoverd
```

> Get https://controller.flynn.smfhq.com/apps/beobachtungsboegendev/release: dial tcp x.x.x.x:443: connection refused

- An attempt to update the cluster results in this (note that it didn't get the latest version from today according to https://dl.flynn.io/ec2/images.json ):

> INFO[01-14|10:58:45] initializing TUF client
> INFO[01-14|10:58:45] updating TUF data
> INFO[01-14|10:58:47] getting configured release channel
> INFO[01-14|10:58:47] determining latest version of stable release channel
> INFO[01-14|10:58:47] latest stable version is v20151223.0
> INFO[01-14|10:58:47] downloading v20151223.0 flynn-host binary
> INFO[01-14|10:58:47] executing latest flynn-host binary
> INFO[01-14|10:58:47] initializing TUF client
> INFO[01-14|10:58:47] reading TUF database
> INFO[01-14|10:58:47] getting host list
> EROR[01-14|10:58:47] error getting host list                  err="object_not_found: service not found"
10:58:47.883781 host.go:136: object_not_found: service not found

When collecting the debug info, I got this line in between:

> EROR[01-14|11:05:28] error getting job logs, falling back to on-disk logs err="could not list hosts: object_not_found: service not found"

And here is the gist: https://gist.github.com/0999d3c54f7dd01951d7

**Comment by titanous** [comment]
It looks like the discoverd consensus cluster has failed, logs from the other nodes would be useful.

**Comment by philiplb** [comment]
The second node gave this as well:

> EROR[01-14|11:41:38] error getting job logs, falling back to on-disk logs err="could not list hosts: object_not_found: service not found"

Resulting in this log: https://gist.github.com/519e1005a46479b38215

The third node gave this:

> EROR[01-14|11:42:56] error getting job logs, falling back to on-disk logs err="could not list hosts: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"

Resulting in this log: https://gist.github.com/e18c73f74e707578d84a

**Comment by titanous** [comment]
Can you also gist `/var/log/upstart/flynn-host.log` from all three nodes as well as `/var/log/flynn/79091488-6ad3-43bc-a83d-ef97ca05a344.log` from the third node? Thanks!

**Comment by philiplb** [comment]
Sure.
On the first node, the file doesn't exist. But here is the flynn-host.log.1.gz
https://gist.github.com/philiplb/228f2211bf3cb7d69781

Same on the second node:
https://gist.github.com/philiplb/52222ce3a3d4693e9664

Same on the third node:
https://gist.github.com/philiplb/9431cfe5d0e1b726c18c

And the /var/log/flynn/79091488-6ad3-43bc-a83d-ef97ca05a344.log from the third node:
https://www.philiplb.de/79091488-6ad3-43bc-a83d-ef97ca05a344.log

**Comment by philiplb** [comment]
Turns out that the storage cluster of our VM provider had some issues which might have caused this. The file systems were suddenly read only. So closing it.
