### ISSUE TITLE
Guide for Integration? (Eg: I'd like to add Couchbase as a supported database)

### ISSUE THREAD

**Issue by n1rvana** [flynn/flynn#2379]
I'm interested in integrating couchbase with Flynn.... Couchbase is a distributed database natively, has great scalability and querying capabilities, and... just happens to have memcached built in.  (it's a bucket type).  I think it's a much better choice than Postgres, and for our apps I have to install couchbase anyway.

Is there guide for how to integrate databases with flynn?  Is it architected to support multiple db backends? (Eg: someone might want etcd) 

This may be a non-starter of an idea, and in that case running postgres is fine by me.

Note this would also resolve #2307

**Comment by titanous** [comment]
Our main priority this year is adding more database appliances and making it easier for others to make their own. An early version of the Redis appliance just landed and work is starting on MySQL. Using what we learn from the first three appliances we plan to make and document a framework for creating more.

**Comment by n1rvana** [comment]
Thanks!  If I'm still using Flynn (which I anticipate I will) then I'll be happy to help with that as I can, and try doing a Couchbase port (And document what I discover).

**Comment by thomasmodeneis** [comment]
Hi,
Is there any progress so far on this topic ? I'm interested in pushing forward https://github.com/flynn/flynn/issues/3499 but struggling a bit to find where to start from.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
