### ISSUE TITLE
Best practices for flynn in production

### ISSUE THREAD

**Issue by christiangenco** [flynn/flynn#2380]
After hunting around for a solid strategy for deploying Rails, I've fallen in love with flynn. The one thing keeping me from hitting the button to switch it to production is that it looks like it's not resistant against hosts rebooting: #1428 #1508 #1714 #1789 #1836 #2075

There are a few solutions floating around, like 1) editing `/etc/init/flynn-host.conf` to uncomment the commented lines:

```bash
description "Flynn layer 0"

#start on (started libvirt-bin and started networking)
stop on stopping libvirt-bin
#respawn
#respawn limit 1000 60

exec /usr/local/bin/flynn-host daemon
```

(reload with `sudo initctl reload-configuration`)

and 2) running `sudo rm /var/lib/flynn/host-state.bolt; sudo start flynn-host; flynn-host bootstrap` after a reboot.

Ideally I would be able to spin up a multi-node flynn cluster and it would self heal if a node went down, the node would eventually come back online, and the cluster would rebalance with the new node. On rare instances when the entire cluster went down (which is made more likely because every node in my cluster has to be in the same zone to [reduce latency](https://github.com/flynn/flynn/issues/2362#issuecomment-170493738)), the cluster would be able to figure things out again as nodes came back online.

Since, from open issues, it sounds like flynn isn't quite there yet, here's what I'm thinking would work in production for right now:

1. Deploy two large (~4GB) single node flynn clusters (since single node clusters seem more resilient to restarting than multi-node clusters) with two different providers (I'll use [chunkhost](https://chunkhost.com/) and [linode](https://www.linode.com/)) with an external database (I'll use [Amazon RDS](https://aws.amazon.com/rds/))
2. Deploy my app to both clusters (preferably with a script so I don't have to think about having both clusters, maybe with some sweet CI action with [Jenkins](https://jenkins-ci.org/))
3. Create a reverse proxy with [Route53 DNS Failover](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover.html) that points to each cluster and intelligently routes traffic to them based on health checks (an AWS service that should [cost about $1.50/month](http://aws.amazon.com/route53/pricing/#Health_Checks))
4. Set up a CloudWatch alarm to text me when one of the clusters goes down, and when it comes back up

Now in the event of one of my clusters failing:

1. Route53 health checks will notice the failed cluster in under 30 seconds and start routing 100% of traffic to the other cluster
2. CloudWatch sends me a text letting me know a cluster is down
3. The cluster hopefully restarts itself and flynn hopefully comes back online, otherwise I respond to the text at my leisure and manually bring it back up
4. Route53 health checks notice the cluster is back online, and start routing traffic to it again

Does that all sound sane until flynn gets more resilience against rebooting?

If there's interest, I'd be happy to turn this into an in-depth tutorial with more information on how to set up the Amazon side.

**Comment by titanous** [comment]
We're working on the reboot issue in #2375. This has been a non-trivial issue for a variety of reasons but will be fixed soon. I'd hold off on writing the tutorial, as soon as we have this issue fixed just running a three-node cluster should be enough.

**Comment by titanous** [comment]
Oh, and we're thinking along similar lines, when you `flynn install` to AWS we configure Route53 health checks and failover so a multi-node cluster should handle failure pretty well.

**Comment by titanous** [comment]
Reboots are now fixed.

**Comment by alixaxel** [comment]
@titanous You mentioned reboots are now fixed but I tested this scenario yesterday and Flynn wasn't able to get back up after simultaneously restarting a 3-node cluster. Is there any documentation that deals with this specific issue? I usually set Ubuntu clusters to auto-install security upgrades and auto-reboot afterwards, daily usually at a specific time while having NTP time synchronization on all servers.

**Comment by lmars** [comment]
> Flynn wasn't able to get back up after simultaneously restarting a 3-node cluster

The recommended approach is to reboot each node one-by-one, waiting for the cluster status to become healthy again before rebooting the next one.

**Comment by philiplb** [comment]
Which is a bit of a pitty as sometimes the whole cluster restarts like in a power outage or the provider decides to reboot the vm host machine due to maintenance.

**Comment by lmars** [comment]
@philiplb sure so sometimes these things are unavoidable, but in the cases where you want to do a controlled reboot, you should do them one-by-one.

**Comment by alixaxel** [comment]
@lmars Yeah, under ideal conditions this wouldn't be a problem, but these kind of things can and will happen, when you take into account OSes like CoreOS that restart automatically, it's just a matter of when before a cluster becomes messed up.

I would really like to see this solved or at least some acknowledgement in the documentation on how to work around it and bring the cluster back up. Otherwise I think it's too risky to trust a production system to it, HA becomes no availability at all.

**Comment by lmars** [comment]
@alixaxel I am in full agreement that Flynn should be able to recover from all nodes going offline at the same time, I was just making the point that if at all possible (i.e. in your example case of auto-upgrades or CoreOS restarting your servers), try to restart them one-by-one.

If you have detailed logs of the reboots you performed and what went wrong, please open an issue describing the behaviour you saw and let's get any issues fixed.
