### ISSUE TITLE
Unable to download node ; does it exist?

### ISSUE THREAD

**Issue by geekdave** [flynn/flynn#2383]
Not sure if this is related to https://github.com/flynn/flynn/issues/1953 or not (some of the error messages seemed similar)

Fresh install of flynn on a 3-host cluster.  Was able to do all the init stuff without any errors.  I am inside a corp network, but these machines have unrestricted access to the internet.  

Followed the install and getting started guide with no errors up until:

```
$ cd nodejs-flynn-example 
$ flynn create example
Created example

$ git remote -v
flynn	https://git.x.app.mycompany.com/example.git (fetch)
flynn	https://git.x.app.mycompany.com/example.git (push)
origin	https://github.com/flynn/nodejs-flynn-example.git (fetch)
origin	https://github.com/flynn/nodejs-flynn-example.git (push)

$ flynn route
ROUTE                                 SERVICE      ID                                         STICKY  PATH
http:example.x.app.mycompany.com  example-web  http/XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX  false   /

$ git push flynn master
Counting objects: 25, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (24/24), done.
Writing objects: 100% (25/25), 2.58 KiB | 0 bytes/s, done.
Total 25 (delta 10), reused 0 (delta 0)
-----> Building example...
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  0.10.x
       engines.npm (package.json):   2.x
       
       Resolving node version 0.10.x via semver.io...
       Downloading and installing node ...
       Unable to download node ; does it exist?
       
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
remote: Build failed: exec: job exited with status 1
To https://git.x.app.mycompany.com/example.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.x.app.mycompany.com/example.git'
```

Any pointers would be greatly appreciated.  [Uploaded debug logs here](https://gist.github.com/anonymous/e82fe23ec1a5c6f29aac#file-example-cwedokku01-dbac3627-0446-4790-a24f-a57bdc7a3a35-log)

**Comment by geekdave** [comment]
No proxies configured as far as I can see:

```
$ cat /etc/environment 
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
```

**Comment by titanous** [comment]
It looks like the version resolution step might be failing. What do you get when you run this command on a server? (also, I assume you tried this multiple times?)

```text
url --get --data-urlencode "range=0.10.x" https://semver.herokuapp.com/node/resolve
```

**Comment by geekdave** [comment]
Hey @titanous - Thanks for the quick reply.

Yes, I tried multiple times.  Interestingly enough the output of the 2nd time was _slightly_ different, in that the first time I got:

```
       Downloading and installing node ...
       Unable to download node ; does it exist?
```

...and the 2nd time I got:

```
       Downloading and installing node 0.10.41...
       Unable to download node 0.10.41; does it exist?
```

Also something I forgot to mention is that running any `flynn-` commands with `sudo` always resulted in `command not found` which apparently is because `/usr/local/bin` isn't in my `/etc/sudoers` file (which is managed by puppet on my company's VMs, and something I'm not supposed to modify).  Any time I ran a `flynn-` command I always used the full path as a prefix, so not sure if this might be an issue if behind the scenes, something is expecting these binaries to be on the path.

Here's the curl output as requested:

```
$ curl -v --get --data-urlencode "range=0.10.x" https://semver.herokuapp.com/node/resolve
* Hostname was NOT found in DNS cache
*   Trying 23.23.208.103...
* Connected to semver.herokuapp.com (23.23.208.103) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=US; ST=California; L=San Francisco; O=Heroku, Inc.; CN=*.herokuapp.com
* 	 start date: 2014-01-21 00:00:00 GMT
* 	 expire date: 2017-05-19 12:00:00 GMT
* 	 subjectAltName: semver.herokuapp.com matched
* 	 issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
* 	 SSL certificate verify ok.
> GET /node/resolve?range=0.10.x HTTP/1.1
> User-Agent: curl/7.35.0
> Host: semver.herokuapp.com
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server Cowboy is not blacklisted
< Server: Cowboy
< Connection: keep-alive
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Vary: Origin
< Content-Type: text/plain; charset=utf-8
< Content-Length: 7
< Etag: W/"7-bce4efda"
< Date: Wed, 20 Jan 2016 19:08:59 GMT
< Via: 1.1 vegur
< 
* Connection #0 to host semver.herokuapp.com left intact
```

**Comment by titanous** [comment]
Hmm, there wasn't a line at the end that said `0.10.41`? For some reason your requests are sometimes failing, could be on either end.

**Comment by geekdave** [comment]
@titanous OOPS!  Yes, it did say that at the end.  copy/paste fail:

```
* Connection #0 to host semver.herokuapp.com left intact
0.10.41
```

**Comment by titanous** [comment]
Okay, and what happens when you run this a few times?

```text
wget http://s3pository.heroku.com/node/v0.10.41/node-v0.10.41-linux-x64.tar.gz
```

**Comment by geekdave** [comment]
@titanous Ran 10x with the following output:

```
$ wget http://s3pository.heroku.com/node/v0.10.41/node-v0.10.41-linux-x64.tar.gz
--2016-01-20 13:29:47--  http://s3pository.heroku.com/node/v0.10.41/node-v0.10.41-linux-x64.tar.gz
Resolving s3pository.heroku.com (s3pository.heroku.com)... 23.23.110.193, 54.83.36.145, 50.19.94.74
Connecting to s3pository.heroku.com (s3pository.heroku.com)|23.23.110.193|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6094467 (5.8M) [binary/octet-stream]
Saving to: ‘node-v0.10.41-linux-x64.tar.gz.9’

100%[=========================================================================>] 6,094,467   4.35MB/s   in 1.3s   

2016-01-20 13:29:49 (4.35 MB/s) - ‘node-v0.10.41-linux-x64.tar.gz.9’ saved [6094467/6094467]
```

One thing I noticed is that these VMs have a local internal mirror configured for `apt-get` - could that be a problem?

**Comment by titanous** [comment]
Hmm, something more complicated is happening. I'd suggest trying a single-node cluster and taking a tcpdump if the issue persists. The local apt-get mirror should have no impact on this.

**Comment by geekdave** [comment]
Will give that a shot, @titanous.  Is there an easy way to change my primary node to expect to be a single-node?  Or do I need to install on a fresh Ubuntu box?

**Comment by titanous** [comment]
You'll need to do a fresh install.

**Comment by titanous** [comment]
Closing as I haven't seen any updates on this. Please re-open if you encounter this again and have more info.

**Comment by thomasmodeneis** [comment]
hi @titanous 
I'm having very similar issue.
```
remote: [1G[K[1G-----> Installing binaries        
remote: [1G[K[1G       engines.node (package.json):  5.6.0        
remote: [1G[K[1G       engines.npm (package.json):   3.6.0        
remote: [1G[K[1G               
remote: [1G[K[1G       Downloading and installing node 5.6.0...        
remote: [1G[K[1G       Unable to download node 5.6.0; does it exist?        
remote: [1G[K[1G               
remote: [1G[K[1G-----> Build failed    
```

**Comment by titanous** [comment]
@thomasmodeneis This is probably related to the ongoing issues with DNS in a large portion of the internet. See #3550.

**Comment by thomasmodeneis** [comment]
Oh never mind, that will probably go away tomorrow then.
Cheers.

**Comment by mandros1** [comment]
Hello, it seems I have bumped into this issue as well.
Funny it worked while it was using 12.17.0, 12.18.1 and 12.18.2 node versions, but chokes on 12.18.13 sayt
`engines.node (package.json):  12        
 remote:        engines.npm (package.json):   unspecified (use default)        
 remote:        engines.yarn (package.json):  unspecified (use default)        
 remote:                
 remote:        Resolving node version 12 via semver.io...        
 remote:        Downloading and installing node 12.18.3...        
 remote:        Unable to download node 12.18.3; does it exist?`
How did you guys resolve this?

**Comment by gabrielbrise** [comment]
Same problem as @mandros1 here

**Comment by mandros1** [comment]
@gabrielbrise I quickfixed it by setting node version in package.json to `"node": ">=12 <12.18.3"` until this is resolved
