### ISSUE TITLE
Docs suggestions

### ISSUE THREAD

**Issue by ammislam** [flynn/flynn#2385]
hi, 

I have deployed flynn on three digitalocean servers. after creating an app named 'sample' I have tried the following command 'flynn resource add postgres' but it gives me the error: 
'no app found, run from a repo with a flynn remote or specify one with -a'

**Comment by josephglanville** [comment]
Hi @ammislam if you don't run flynn commands from the directory with your application you will need to provide the app name like so:
```
flynn -a sample resource add postgres
```

**Comment by ammislam** [comment]
Hi

Thanks for the reply. now was able to add postgres. but again in same 'no app found' trouble, no matter if just write 'flynn env' or 'flynn -a sample env' to pass some db command. 

I was following this guide 
https://www.brightbox.com/blog/2015/07/30/deploying-flynn-cluster/

here after adding the postgres resource, I need to run this command 
'$ flynn env set DATABASE_URL=$(export $(flynn env | xargs); echo "postgres://$PGUSER:$PGPASSWORD@$PGHOST:5432/$PGDATABASE")'

but it is returning same no app found error. 

Also please can you point me to some guide/tutorial on how to use the web interface. I have connected my github repo after installing flynn, but from the flynn dashboard, I cannot deploy app, the deploy button after selecting the app is not active.

**Comment by titanous** [comment]
The `DATABASE_URL` is set automatically. Are you running these commands from a git repo configured for Flynn?

**Comment by ammislam** [comment]
Well I was running all the command from the primary node's terminal, the Ubuntu digital ocean server. 
On Jan 22, 2016 11:22 PM, Jonathan Rudenberg <notifications@github.com> wrote:The DATABASE_URL is set automatically. Are you running these commands from a git repo configured for Flynn?

**Comment by titanous** [comment]
The CLI will automatically pick up the app name if you run it from within a git directory configured with the app's flynn remote.

**Comment by ammislam** [comment]
okay, I am kind of confused here as to how to play with Flynn, is there any detailed guide or howto manual? 

looks like flynn guide is not fully ready and updated for people who are totally new at PaaS. Also I am not sure how multiple nodes are working here (load balancing, failover, etc) as I am executing almost all of the command on master node.

**Comment by nobert** [comment]
This is a good point. We will publish a guide that describes the Flynn workflow soon. If you have any comments, suggestions, or requests for this new guide or other docs, you can email me at alex@flynn.io.

**Comment by ammislam** [comment]
I have faced many trouble while using Flynn. I know it is a very powerful docker alternative, but even many pro developers find it hard to use due to lack of proper documentation. I am sharing my experiences: 

On my first install, I had only one node. So I did not run the init discovery to get the unique flynn indentifier. later for the bootstrap part, I used min-host 1, since it had only one nodes and skipped the host discovery parameter. 
Later I wanted to create a cluster with two additional nodes (3 is the minimum, I had 1 already created). So how would I add the new two nodes with first node - there was no guide on how to create a cluster from existing node and so on. Though I tried stopping the first flynn host, do the init discovery command, then pass the init to other two new nodes, start all nodes, and then bootstrapping again on first now, this time with min-host 3 and passing the domain discovery parameter. But it failed, the new two nodes are shown online but primary node goes to stop mode automatically. 

What I finally did, rebuild all my servers at digitalocean, re-install flynn again on all nodes, this time with proper init-discovery on primary, and passing the output to rest nodes, then min-host 3 and others on primary node, now it works. 

So looks like we cannot create cluster based off existing nodes or if possible, then there is no guideline. 

Second problem was about the CLI command after finishing installation - it is not mentioned on which node user shall run this command, on every nodes or only on the master nodes, after the CLI command there is another command to run, to create default flynn, where shall user run this command - on the primary node or on all nodes? 

So please update your documentations and instead of deploying the sample git app (the node.js one), provide details guide on how to deploy a fully functional production ready app, with database, redis, job scheduler. 

I want to deploy my app using Flynn, my stack consist of Rails, Nginx, Postgres, Sidekiq, Redis, Elasticsearch, mongoDB.

**Comment by acobster** [comment]
Not sure if this is appropriate to write up here, or deserving of its own issue (in which case I'm happy to open a new one), as this issue's title is very vague. I'm wondering if the documented usage for `flynn export` is correct:

```
The application's metadata, deploy strategy, release configuration, slug, formation, and Postgres database will be exported to a tar file.
```

...specifically the "Postgres" part? Should this language be generalized, or are database exports really only supported for Postgres? This is also in the `import` usage docs.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
