### ISSUE TITLE
Would like to add link to custom build packs to docs, can't find location.

### ISSUE THREAD

**Issue by n1rvana** [flynn/flynn#2388]
Since I'm not ready to really contribute to flynn,  I've been trying to help on docs.

I wanted to add a link to the "Custom build packs" FAQ answer under the "Languages" nav on the left of the docs, but I can't figure out how this is built. 
(I did project wide search for the word "Languages" and couldn't find it, for instance)

**Comment by titanous** [comment]
Ping @jvatic.

**Comment by jvatic** [comment]
@n1rvana The docs nav can now be edited here: https://github.com/flynn/flynn/blob/master/docs/docs-nav.json
