### ISSUE TITLE
Tag-based scheduling for system jobs

### ISSUE THREAD

**Issue by dashkb** [flynn/flynn#2391]
[Tag based scheduling](https://flynn.io/blog/2015-12-28-this-week-in-flynn) is a sweet feature.  It would be even sweeter if it could be applied to the `slugbuilder` (and perhaps other core jobs) so they can never steal CPU from critical services.

Context: I had a deploy get stuck and eat a whole processor and refuse to be `kill -9`d... if that job had been isolated to a less critical node I could have just killed it and replaced it with a new node; instead I hosed my cluster trying to get that job killed.

[My IRC logs](https://botbot.me/freenode/flynn/2016-01-26/?msg=58741267&page=2)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
