### ISSUE TITLE
pre-recieve hook Question

### ISSUE THREAD

**Issue by zwanthor** [flynn/flynn#2399]
I was going through the tutorial on using flynn, at https://flynn.io/docs, to set up my app. When I tried to push to flynn I got:

```
Counting objects: 1119, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (575/575), done.
Writing objects: 100% (1119/1119), 371.76 KiB | 0 bytes/s, done.
Total 1119 (delta 648), reused 901 (delta 512)
To https://git.something.flynnhub.com/appname.git
 ! [remote rejected] development -> development (pre-receive hook declined)
error: failed to push some refs to 'https://git.something.flynnhub.com/appname.git'
```

So I went through this code:
https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/gitreceive/server.go

When I pushed to master it worked. Is there any support to push another branch, other than master, to flynn from the command line?

**Comment by titanous** [comment]
Yes, run `git push flynn development:master` to deploy local `development` branch to Flynn.

**Comment by zwanthor** [comment]
Awesome! Thanks!
