### ISSUE TITLE
Limit access to flynn API from inside a cluster (for cluster applications)

### ISSUE THREAD

**Issue by spinus** [flynn/flynn#2402]
```
Applications run within Flynn are not fully sandboxed and have access to internal Flynn APIs that can be used to gain root access on the server. Do not run untrusted code in Flynn.
```

Is there any way to disable API access for applications?
Even if the code is trusted it can contain bugs, which means if somebody will do remote execution inside ANY app in the cluster he can do whatever he wants with the cluster, right?

**Comment by titanous** [comment]
> Is there any way to disable API access for applications?

Not currently. I'm currently working on an authorization for all of the APIs.

> Even if the code is trusted it can contain bugs, which means if somebody will do remote execution inside ANY app in the cluster he can do whatever he wants with the cluster, right?

Correct.

**Comment by spinus** [comment]
>  I'm currently working on an authorization for all of the APIs.
+1

**Comment by OmarShehata** [comment]
@titanous is there any update on the sandboxing? My use case is letting students deploy apps in class without worrying about breaking the server. The deployment and sandboxing are really the only important things for me right now. Would you recommend trying to fit Flynn into this box, or is there something else we could use in the meantime?

**Comment by titanous** [comment]
@OmarShehata Security is a priority for us, though it will take a while to get to a point where you can run untrusted code in the way that you describe. You can track our progress here: https://github.com/flynn/flynn/projects/1

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
