### ISSUE TITLE
docs: Document tag based scheduling

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2411]
We need to document:
- adding tags to hosts (e.g. `flynn-host tags set host1 disk=ssd`)
- constraining jobs to run only on hosts with matching tags (e.g. `flynn scale db=1,disk=ssd`)
- what happens when tags change

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
