### ISSUE TITLE
Cluster Wildcard SSL Certificate Installation

### ISSUE THREAD

**Issue by nasali** [flynn/flynn#2434]
Hi there,

I have a three-node Flynn cluster that was bootstrapped using the manual installation instructions. An A record for the domain name of cloud.mydomain.com correctly resolves to the three public IP addresses of the three nodes. Setting up the CLI tool to use the cluster worked, but we need to use our own SSL certificate for the custom domain, *.cloud.mydomain.com, we pointed to the cluster on AWS, not the generated self-signed one.

How do I install a wildcard SSL certificate on Flynn?

Thanks a bunch!

**Comment by titanous** [comment]
You can do something along the lines of this command to set the default certificate:

```text
flynn -a router env set TLSCERT="$(cat cert-chain.pem)" TLSKEY="$(cat cert-key.pem)"
```

Note that currently this is a bit rough, so if the chain or key are mismatched or malformed the router may not come back up after reconfiguration and there is no easy way to fix this.

**Comment by nasali** [comment]
Thank you so much for your prompt response.

I attempted what you suggested on a fresh install of three nodes on AWS, and this is what I see:
```
$ flynn -a router ps
ID                                           TYPE  STATE  CREATED        RELEASE
flynn0-19d68a81-e717-48d2-b70c-3a286f0cfb6a  app   up     2 minutes ago  e69e6731-dcfd-4e4b-9d2c-d6459c37db33
flynn1-06e71c86-fd07-42b4-a8dd-9c59b7383f4b  app   up     2 minutes ago  e69e6731-dcfd-4e4b-9d2c-d6459c37db33
flynn2-a6300aee-c399-4f3e-a2f5-bf6028de317a  app   up     2 minutes ago  e69e6731-dcfd-4e4b-9d2c-d6459c37db33

$ flynn -a router env set TLSCERT="$(cat server.crt)" TLSKEY="$(cat server.key)"
Created release af9fcd2d-21f5-4a39-8b05-612f8f6cb5fd.

$ flynn -a router ps
ID                                           TYPE  STATE  CREATED             RELEASE
flynn0-9b0206e1-eea9-4aee-a39b-78e92a8dc07a  app   up     About a minute ago  af9fcd2d-21f5-4a39-8b05-612f8f6cb5fd
flynn1-90dae0dc-655b-4135-abea-f880b885b955  app   up     About a minute ago  af9fcd2d-21f5-4a39-8b05-612f8f6cb5fd
flynn2-ecf406ff-11b0-4925-9eba-21f808d2f034  app   up     About a minute ago  af9fcd2d-21f5-4a39-8b05-612f8f6cb5fd

$ flynn -a dashboard env set TLSCERT="$(cat server.crt)" TLSKEY="$(cat server.key)"
Created release 7c301686-317c-46ac-a8da-6a424e7f150e.

$ flynn -a dashboard ps
ID                                           TYPE  STATE  CREATED        RELEASE
flynn0-8fc62fdc-b935-4c8f-811f-793dbe856f91  web   up     2 minutes ago  7c301686-317c-46ac-a8da-6a424e7f150e
flynn1-9b1ccb6a-811f-491a-a1de-367560742a07  web   up     2 minutes ago  7c301686-317c-46ac-a8da-6a424e7f150e
```
So it looks like a new release was successfully created for the router and the dashboard. However, reloading the dashboard seems to still bring up the Flynn self-signed certificate.

If I list the apps deployed, this is what I see:
```
$ flynn apps
ID                                    NAME
94276611-f5a3-4f03-b728-b379d65be26f  status
798c8084-de50-480a-8a53-3b5169abcbb3  dashboard
bea74012-9ffd-4c7f-bb16-ac1ca061c79f  taffy
732e3889-e495-45ad-99c7-bd48e54438e1  logaggregator
36f9d337-15ec-4a5c-bc64-aa19983ca3d4  gitreceive
41e05c79-aa77-40dc-b4bd-25ebb11744b6  router
74aff026-ae9e-4b42-adc8-f48226c141c7  blobstore
c1384950-3a84-428c-86d7-f24bd59efb76  discoverd
a825e7c0-5e0f-4629-a40b-d2893ad8bf74  flannel
f06406c7-0989-4d09-a06a-bd0c8859017e  postgres
aac3c573-bc7c-412c-8889-8d14d2b35567  controller
```

Am I missing something?

Thanks again.

**Comment by titanous** [comment]
Those config variable will only set the fallback certificate, if there is a certificate specified for the route (as is the case with the dashboard) the fallback will not be used and you can change it with `flynn route update`. The fallback is used for routes where no TLS certificate is specified.

**Comment by nasali** [comment]
Got it. The router is indeed using the correct certificate to encrypt traffic to deployed applications, which is what we needed.

Thank you so much @titanous
