### ISSUE TITLE
Successful app launch, but launch window didn't 

### ISSUE THREAD

**Issue by elimisteve** [flynn/flynn#2440]
Notice the "undefined"s in the URLs.  But the app deployed great!

![screenshot-flynn-python-deploy-error-deployedfine-errorsfindingappthough-screenshot - 02102016 - 06 28 39 pm](https://cloud.githubusercontent.com/assets/139603/12968275/56d4f4c2-d024-11e5-9e5c-416cf950260c.png)

**Comment by elimisteve** [comment]
I can try to replicate this if you'd like.

**Comment by titanous** [comment]
Replication steps would be great. @jvatic will investigate when he gets back.

**Comment by elimisteve** [comment]
To reproduce you can just deploy https://github.com/elimisteve/exphilorg/commit/2760154598a205124b82ea7d372be0f8889cf543

**Comment by elimisteve** [comment]
(I haven't deployed it since right after creating this issue, though, so if there's a new version of Flynn then this may be fixed.)

**Comment by jvatic** [comment]
@elimisteve I'm failing to reproduce this. Does the continue button work as expected?

**Comment by elimisteve** [comment]
Hey sorry, when I try this again I'll let you know if I run into issues.
