### ISSUE TITLE
router: Move TLS certificate details to a different object

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2442]
We should move the TLS certificates/keys out of the Route data structure/table and into a separate table/datatype. This sets us up to do a bunch of stuff:

- Use the same certificate for multiple routes
- Clean fallback certificates without env vars
- Allows changing system app certificates in one place
- Wildcard certificates (#267)
- OCSP stapling (#1049)
- CT enrollment and SCTs in handshakes (#1052)
- Chain verification and bundling (#1251)
- Let's Encrypt integration (#1995)

**Comment by josephglanville** [comment]
Agreed. I think when auth is in place it will also allow attaching of security principal data to certificates so that they can be delegated from administrators to users which is important for most admin -> developer settings.
