### ISSUE TITLE
cluster migrate-domain and change certificate in one step

### ISSUE THREAD

**Issue by felixbuenemann** [flynn/flynn#2445]
It would be great if the `flynn cluster migrate-domain` command had some extra options like `--tls-cert` and `--tls-key` that would switch out the default cert and reconfigure the endpoints to use that cert instead of adding a new self-signed one.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
