### ISSUE TITLE
Deleting old releases

### ISSUE THREAD

**Issue by dashkb** [flynn/flynn#2451]
I was backing up my cluster for an update this evening and noticed the backup was taking quite a while.  It turns out this is because of the database for blobstore, which is storing files for (many) releases that I'll never want to use again.  It's around 30GB after a couple of weeks because your tool encourages me to deploy constantly. :wink: 

I know that I could iterate through the old releases, getting their environment which contains a blob url, which I could use to delete the row in Postgres or over blobstore's API, but I'm wondering: is there a clean way to delete a release and all its associated data by ID?

**Comment by titanous** [comment]
@lmars is working on this. The first PR is up at #2448.

**Comment by dashkb** [comment]
Great!  I'll do it manually for now then.
