### ISSUE TITLE
New GitHub access token default permissions

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#2452]
The interface for creating/editing GitHub access tokens has been updated, with a new permissions screen and new defaults which do not allow access to private repos. The dashboard should be updated to reflect this.

**Comment by jvatic** [comment]
@nobert Am I missing something? Below is a screenshot of the GitHub access token page as pre-populated by the link in the dashboard:

<img width="741" alt="screen shot 2016-03-26 at 8 26 43 pm" src="https://cloud.githubusercontent.com/assets/171040/14063122/ac1af6e6-f3b2-11e5-91ff-56a887b481f5.png">
