### ISSUE TITLE
flynn cluster migrate-domain doesn't update .flynnrc

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#2453]
Using latest release, migrate-domain is leaving clusters in a partially broken state where the dashboard works, but the CLI does not work because the controller is not updated to the new domain, i.e. does not have a new certificate, and the .flynnrc file is not updated. Everything else appears fine (e.g. git and dashboard are updated with new domain/certificate).

Also, it is spits out an error message, but continues:

```
Migrate cluster domain from "xxxx.flynnhub.com" to "domain.com"? (yes/no): yes
Migrating cluster domain (this can take up to 2m0s)...
Get http://router-api.discoverd:5000/routes: dial tcp: lookup router-api.discoverd: no such host
Changed cluster domain from "xxxx.flynnhub.com" to "domain.com"
```

Logs: https://gist.github.com/b8de3045c2c7527bd495

**Comment by lmars** [comment]
@nobert AFAICT from the logs, the controller deployed successfully. The logs don't show environment variables so I can't verify that they have the correct domain.

Do you still have this cluster around? It would be good to get a dump of the routes table and job environment variables.

**Comment by lmars** [comment]
By the way, the error which was spat out was due to a worker getting a 500 from the controller when it tried to create a route:

```
t=2016-02-16T06:11:55+0000 lvl=eror msg="error creating missing routes" app=worker fn=HandleDomainMigration domain_migration=17b119b2-c644-46a0-a60a-6d952a85ea4c err="Get http://router-api.discoverd:5000/routes: dial tcp: lookup router-api.discoverd: no such host"
```

The job was then picked up by a different worker which did not have this error, and completed the domain migration:

```
t=2016-02-16T06:12:05+0000 lvl=info msg="handling domain migration" app=worker fn=HandleDomainMigration job_id=12 error_count=1
t=2016-02-16T06:12:05+0000 lvl=info msg="already migrated" app=worker fn=HandleDomainMigration domain_migration=17b119b2-c644-46a0-a60a-6d952a85ea4c app.name=controller
t=2016-02-16T06:12:05+0000 lvl=info msg="already migrated" app=worker fn=HandleDomainMigration domain_migration=17b119b2-c644-46a0-a60a-6d952a85ea4c app.name=router
t=2016-02-16T06:12:05+0000 lvl=info msg="already migrated" app=worker fn=HandleDomainMigration domain_migration=17b119b2-c644-46a0-a60a-6d952a85ea4c app.name=dashboard
t=2016-02-16T06:12:05+0000 lvl=info msg="domain migration complete" app=worker fn=HandleDomainMigration domain_migration=17b119b2-c644-46a0-a60a-6d952a85ea4c
```

The controller should use a retry dialer for the router client to avoid this error, I will fix that now.

**Comment by nobert** [comment]
I just realized what is happening. The new TLSPin is not written to the config file (it is not being rewritten at all).

When flynn has `ControllerURL` set to `controller.domain.com`, it complains:

```
Get https://controller.domain.com/apps/controller/routes: pinned: the peer leaf certificate did not match the provided pin
```

Flynn does have the new certificate -- i.e. `curl https://controller.domain.com/` and Chrome both load fine, and the controller has the routes:

```
ROUTE                               SERVICE     ID                                         STICKY  PATH
https:controller.domain.com         controller  http/0fd72f13-0f06-40a9-9ec3-9d3d787efa2d  false   /
https:controller.xxxx.flynnhub.com  controller  http/51897d08-49e0-4b77-b3d9-d5060a9d90ec  false   /
```

So everything appears fine except that .flynnrc is not being updated with the new info.

**Comment by nobert** [comment]
Confirmed that with the new TLSpin, this works fine.

**Comment by bfontaine** [comment]
Just hit into this issue; how do you get the correct `TLSpin` to put in your `~/.flynnrc`?

**Comment by jvatic** [comment]
@bfontaine You'll need to grab the `TLSCERT` env variable from the router (you can do this by [SSHing into one of the servers](https://flynn.io/docs/faq/how-do-i-ssh-to-flynn-cluster-hosts) and running `flynn-host inspect $(flynn-host ps | grep router | sed -e 's/\s\+.*//' | tr -d '\r\n')`), then your [gist from earlier](https://gist.github.com/bfontaine/0b4fca4a3df1f5da12ab) will work just fine.

**Comment by bfontaine** [comment]
@jvatic Thank you; it worked :smiley:

**Comment by bfontaine** [comment]
Another thing that should probably be updated: the git config. My `~/.gitconfig` stil has a `[credential "https://git.xxxx.flynnhub.com"]` section that I need to replace with my new domain.
