### ISSUE TITLE
App reported unhealthy for a few seconds over night

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2455]
Hi,

I'm monitoring the Symfony2 app and receive an email as soon as the expected result from the ping url isn't there anymore. This happened over night on a fresh flynn setup from yesterday evening. 12s later, it was up and running again.

This isn't serious I think, still looks like a bug which I want to report.

I'm afraid I don't have the information what service went down. So I just scrolled through the logs of flynn-host. Here are my findings:

Every 5 minutes or so, there is this happening:
> ESC[32mINFOESC[0m[02-16|00:51:50] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=4249e818-2ba9-4092-8623-067d311e8e07 ESC[32mmethodESC[0m=GET ESC[32mpathESC[0m=/host/jobs ESC[32mclient_ipESC[0m=(...............:
> ESC[32mINFOESC[0m[02-16|00:51:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=4249e818-2ba9-4092-8623-067d311e8e07 ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=3.825975ms
> ESC[32mINFOESC[0m[02-16|00:51:50] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=75e2e0ec-f07c-46e2-99e7-c8fc7bbdb477 ESC[32mmethodESC[0m=DELETE ESC[32mpathESC[0m=/host/jobs/flynn0-12860a9c-b77e-4841-9fb4-1041f672f9a7 ESC[32mclient_ipESC[0m=(...............:
> ESC[32mINFOESC[0m[02-16|00:51:50] acquiring state database                 ESC[32mappESC[0m=host ESC[32mpidESC[0m=1519 ESC[32mhost.idESC[0m=flynn0 ESC[32mfnESC[0m=StopJob ESC[32mjob.idESC[0m=flynn0-12860a9c-b77e-4841-9fb4-1041f672f9a7
> ESC[32mINFOESC[0m[02-16|00:51:50] getting job                              ESC[32mappESC[0m=host ESC[32mpidESC[0m=1519 ESC[32mhost.idESC[0m=flynn0 ESC[32mfnESC[0m=StopJob ESC[32mjob.idESC[0m=flynn0-12860a9c-b77e-4841-9fb4-1041f672f9a7
> ESC[32mINFOESC[0m[02-16|00:51:50] job status is starting, marking it as stopped ESC[32mappESC[0m=host ESC[32mpidESC[0m=1519 ESC[32mhost.idESC[0m=flynn0 ESC[32mfnESC[0m=StopJob ESC[32mjob.idESC[0m=flynn0-12860a9c-b77e-4841-9fb4-1041f672f9a7
> ESC[32mINFOESC[0m[02-16|00:51:50] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=52d7e0ac-7621-4456-95e8-887b8f04ae8a ESC[32mmethodESC[0m=DELETE ESC[32mpathESC[0m=/host/jobs/flynn0-904f0ec0-8a5c-4f88-b230-71901f344748 ESC[32mclient_ipESC[0m=(...............:
> ESC[32mINFOESC[0m[02-16|00:51:50] acquiring state database                 ESC[32mappESC[0m=host ESC[32mpidESC[0m=1519 ESC[32mhost.idESC[0m=flynn0 ESC[32mfnESC[0m=StopJob ESC[32mjob.idESC[0m=flynn0-904f0ec0-8a5c-4f88-b230-71901f344748
> ESC[32mINFOESC[0m[02-16|00:51:50] getting job                              ESC[32mappESC[0m=host ESC[32mpidESC[0m=1519 ESC[32mhost.idESC[0m=flynn0 ESC[32mfnESC[0m=StopJob ESC[32mjob.idESC[0m=flynn0-904f0ec0-8a5c-4f88-b230-71901f344748
> ESC[32mINFOESC[0m[02-16|00:51:50] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=ce35fe80-c52f-40eb-8913-0134bdf2fd47 ESC[32mmethodESC[0m=DELETE ESC[32mpathESC[0m=/host/jobs/flynn0-a5886e43-b040-4741-b165-9659d263f7da ESC[32mclient_ipESC[0m=(...............:
> ESC[32mINFOESC[0m[02-16|00:51:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=75e2e0ec-f07c-46e2-99e7-c8fc7bbdb477 ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=6.316869ms
> ESC[32mINFOESC[0m[02-16|00:51:50] job status is starting, marking it as stopped ESC[32mappESC[0m=host ESC[32mpidESC[0m=1519 ESC[32mhost.idESC[0m=flynn0 ESC[32mfnESC[0m=StopJob ESC[32mjob.idESC[0m=flynn0-904f0ec0-8a5c-4f88-b230-71901f344748
> ESC[32mINFOESC[0m[02-16|00:51:50] job status is starting, marking it as stopped ESC[32mappESC[0m=host ESC[32mpidESC[0m=1519 ESC[32mhost.idESC[0m=flynn0 ESC[32mfnESC[0m=StopJob ESC[32mjob.idESC[0m=flynn0-a5886e43-b040-4741-b165-9659d263f7da
> ESC[32mINFOESC[0m[02-16|00:51:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=52d7e0ac-7621-4456-95e8-887b8f04ae8a ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=8.875254ms
> ESC[32mINFOESC[0m[02-16|00:51:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=ce35fe80-c52f-40eb-8913-0134bdf2fd47 ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=13.671254ms
> ESC[32mINFOESC[0m[02-16|00:51:50] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=22b0343a-12e4-4378-b6ec-e9ccbb7e4390 ESC[32mmethodESC[0m=GET ESC[32mpathESC[0m=/host/jobs ESC[32mclient_ipESC[0m=(...............:
> ESC[32mINFOESC[0m[02-16|00:51:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=22b0343a-12e4-4378-b6ec-e9ccbb7e4390 ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=3.83364ms

And at some point, there where crashes in the heart beat which is about the time the monitoring reported the incident:

> ESC[32mINFOESC[0m[02-16|06:45:45] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=363261ad-2ba8-4f34-89a5-5f00a6f78f0d ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=4.999542333s
> ESC[32mINFOESC[0m[02-16|06:45:45] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=1c402fd3-54dd-40ba-82b1-e4310c63a8d6 ESC[32mmethodESC[0m=GET ESC[32mpathESC[0m=/host/jobs ESC[32mclient_ipESC[0m=100.100.11.2
> ESC[32mINFOESC[0m[02-16|06:45:45] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=435cc670-b1ed-45ba-8356-0f8eb90765e8 ESC[32mmethodESC[0m=GET ESC[32mpathESC[0m=/host/jobs ESC[32mclient_ipESC[0m=(...............:
> 2016/02/16 06:45:45 discoverd: heartbeat cluster-monitor (...............:1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:45:46 discoverd: heartbeat flynn-host ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:45:46 discoverd: heartbeat cluster-monitor ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:45:46 discoverd: heartbeat flynn-host ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:45:46 discoverd: heartbeat cluster-monitor ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:45:46 discoverd: heartbeat flynn-host ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:45:46 discoverd: heartbeat cluster-monitor ((...............::1113) failed: unknown_error: Something went wrong

> ESC[32mINFOESC[0m[02-16|06:45:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=8b7d6cbd-a4b7-4faa-ac9c-95791a32d34e ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=14.113174ms
> ESC[32mINFOESC[0m[02-16|06:45:50] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=5a42a9b3-7f32-4827-94b8-3ef2fa2ba0dd ESC[32mmethodESC[0m=GET ESC[32mpathESC[0m=/host/jobs ESC[32mclient_ipESC[0m=(...............:
> ESC[32mINFOESC[0m[02-16|06:45:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=5a42a9b3-7f32-4827-94b8-3ef2fa2ba0dd ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=2.947424ms
> ESC[32mINFOESC[0m[02-16|06:45:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=1c402fd3-54dd-40ba-82b1-e4310c63a8d6 ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=5.000484613s
> ESC[32mINFOESC[0m[02-16|06:45:50] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=f59dc696-5735-4955-9158-c73bac08243c ESC[32mmethodESC[0m=GET ESC[32mpathESC[0m=/host/jobs ESC[32mclient_ipESC[0m=100.100.11.2
> ESC[32mINFOESC[0m[02-16|06:45:50] request completed                        ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=435cc670-b1ed-45ba-8356-0f8eb90765e8 ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=4.999006446s
> ESC[32mINFOESC[0m[02-16|06:45:50] request started                          ESC[32mcomponentESC[0m=host ESC[32mreq_idESC[0m=fc77d49a-0baa-4d3d-a309-37c8496b838e ESC[32mmethodESC[0m=GET ESC[32mpathESC[0m=/host/jobs ESC[32mclient_ipESC[0m=(...............:
> 2016/02/16 06:45:51 discoverd: heartbeat flynn-host ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:45:51 discoverd: heartbeat cluster-monitor ((...............::1113) failed: unknown_error: Something went wrong

And this one a few minutes later:

> ESC[32mINFOESC[0m[02-16|06:58:31] request started                          ESC[32mreq_idESC[0m=fe1bd322-02dd-42ca-8bf2-75ddc96947af ESC[32mcomponentESC[0m=host ESC[32mmethodESC[0m=GET ESC[32mpathESC[0m=/host/jobs ESC[32mclient_ipESC[0m=(...............:
> ESC[32mINFOESC[0m[02-16|06:58:31] request completed                        ESC[32mreq_idESC[0m=fe1bd322-02dd-42ca-8bf2-75ddc96947af ESC[32mcomponentESC[0m=host ESC[32mstatusESC[0m=200 ESC[32mdurationESC[0m=9.112816ms
> 2016/02/16 06:58:32 discoverd: heartbeat flynn-host ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:58:32 discoverd: heartbeat cluster-monitor ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:58:32 discoverd: heartbeat flynn-host ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:58:32 discoverd: heartbeat cluster-monitor ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:58:32 discoverd: heartbeat flynn-host ((...............::1113) failed: unknown_error: Something went wrong
> 2016/02/16 06:58:32 discoverd: heartbeat cluster-monitor ((...............::1113) failed: unknown_error: Something went wrong

**Comment by josephglanville** [comment]
This looks like discoverd had some sort of hiccup.
What sort of network and servers is this cluster running on?

If you could upload the debug logs with `flynn-host collect-debug-info` that would be useful too.

**Comment by philiplb** [comment]
Those are small "Cloud VM"s at inter.net, kinda similar to EC2. They have one core, 1GB memory and 32GB HDDs. The ping between them is normally under 1ms.

Logs: https://gist.github.com/5da86fa3300212c642e1

**Comment by philiplb** [comment]
I must correct myself, it wasn't the status app. It was the Symfony2 app. I edited the ticket description accordingly.

**Comment by philiplb** [comment]
![screen shot 2016-02-16 at 10 48 55](https://cloud.githubusercontent.com/assets/1672238/13072680/f9360916-d49a-11e5-804b-61b710975cb6.png)

**Comment by lmars** [comment]
@philiplb there were some network related issues around the time of the reported downtime which caused issues for discoverd, with the following entries in the log of discoverd job `flynn0-7a508ee6-8138-4545-8a2e-04c08545e331`:

```
2016/02/16 05:45:34 [WARN] raft: Failed to contact 213.73.98.53:1111 in 530.04236ms
2016/02/16 05:45:34 [WARN] raft: Failed to contact 213.73.98.53:1111 in 1.019453184s
[discoverd] 2016/02/16 05:45:34 enforce expiry: discoverd: new leader, waiting for 2x TTL
2016/02/16 05:45:35 [WARN] raft: Failed to contact 213.73.98.53:1111 in 1.487307695s
2016/02/16 05:45:35 [DEBUG] raft: Failed to contact 213.73.98.53:1111 in 1.920842328s
...
2016/02/16 05:45:42 [DEBUG] raft: Failed to contact 213.73.98.53:1111 in 8.409351227s
2016/02/16 05:45:42 [ERR] raft: Failed to make RequestVote RPC to 213.73.98.53:1111: read tcp 213.73.98.53:1111: i/o timeout
2016/02/16 05:45:42 [DEBUG] raft: Failed to contact 213.73.98.53:1111 in 8.891112328s
...
2016/02/16 05:45:43 [ERR] raft: Failed to make RequestVote RPC to 213.73.98.53:1111: dial tcp 213.73.98.53:1111: i/o timeout
2016/02/16 05:45:43 [ERR] raft: Failed to AppendEntries to 213.73.98.53:1111: dial tcp 213.73.98.53:1111: i/o timeout
```

Things finally stabilised a few seconds later:

```
2016/02/16 05:45:51 [INFO] raft: Node at 213.73.113.154:1111 [Follower] entering Follower state
2016/02/16 05:45:51 [WARN] raft: Failed to get previous log: 212 log not found (last: 211)
2016/02/16 05:45:51 [DEBUG] raft: Node 213.73.113.154:1111 updated peer set (2): [213.73.98.53:1111 213.73.113.154:1111 213.73.113.27:1111]
2016/02/16 05:45:51 [DEBUG] raft: Node 213.73.113.154:1111 updated peer set (2): [213.73.98.53:1111 213.73.113.154:1111 213.73.113.27:1111]
```

Were there any reported network issues during this time (particularly between hosts `213.73.113.154` and `213.73.98.53`)?

**Comment by philiplb** [comment]
Not as far as I know. I'll contact the hosting support and ask. And I think I can close this ticket as it isn't Flynn related. Conclusion for me: Flynn behaved just fine. :)
(Could you edit out the IPs in your comment? Just in case.)

**Comment by philiplb** [comment]
(Thx for anonymizing the IPs. :))
