### ISSUE TITLE
Add Forwarded header

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2464]
The router should include the `Forwarded` header as defined in [RFC 7239](https://tools.ietf.org/html/rfc7239).

**Comment by josephglanville** [comment]
Most of the params look straightforward.

Do we want to populate the `by` field? If so need to work out the best identifier to use. I think the host IP is the obvious one.

**Comment by titanous** [comment]
The `by` field appears to be used to distinguish which network interface the request that is being forwarded came in on. So the destination IP of the client request seems like a reasonable thing to put in there.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
