### ISSUE TITLE
L10n guideline.

### ISSUE THREAD

**Issue by BreakingPitt** [flynn/flynn#2465]
Hi:

Would be nice to have a guideline about how to contribute to the L10n of flynn maybe localization can start as a L10n-XX subrepo inside the main flynn git repo:
- L10n-ES.
- L10n-IT.

And for some projects that needs user interface localization (for example a repo like flynn/dashboard use a L10 platform like:
- [Transiflex.](https://transifex.com/)
- [Crowdin.](https://crowdin.com/)

Any advice or suggestion?

Best regards

**Comment by BreakingPitt** [comment]
Hey...

Just wondering if someone had time to take a look at this?

Best regards

**Comment by titanous** [comment]
We don't have near-term plans for internationalization/localization. I'll leave this issue open as an enhancement request.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
