### ISSUE TITLE
migrate-domain should accept *.domain.com

### ISSUE THREAD

**Issue by nobert** [flynn/flynn#2467]
Although the examples/docs specify using e.g. `flynn cluster migrate-domain domain.com`, it ought to also accept `*.domain.com` as equivalent, or at least reject it with appropriate messaging. This has tripped up a few users.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
