### ISSUE TITLE
Build failed: exec: job exited with status 1

### ISSUE THREAD

**Issue by smidaamine** [flynn/flynn#2475]
I'm trying to run grails-flynn-example, i'm getting this error 

-----> Building grailsapp...
-----> Unable to select a buildpack
remote: Build failed: exec: job exited with status 1
To https://git.d191.flynnhub.com/grailsapp.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.d191.flynnhub.com/grailsapp.git'
 any ideas what cause this ?

**Comment by titanous** [comment]
We don't ship the grails buildpack any more (#623). You could try running this command before pushing:

```text
flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-grails
```

**Comment by smidaamine** [comment]
thank you @titanous  that's fix the problem
