### ISSUE TITLE
Allow deploying repo subdirectories

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2479]
We should have a config flag that allows specifying a repo subdirectory to deploy via slugbuilder instead of the root. This would help people with multiple apps in the same repo or weird directory layouts. The main thing we need to sort out is if there is any way of making this work with eg the Go buildpack with a top-level vendor/Godeps directory.

**Comment by holtgrewe** [comment]
Would this include supporting a `heroku` subdirectory with all flynn/Heroku-related stuff or is this already supported?

**Comment by titanous** [comment]
@holtgrewe Yeah, this feature request would cover what you're looking to do.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
