### ISSUE TITLE
postgres: add pgbouncer

### ISSUE THREAD

**Issue by dashkb** [flynn/flynn#2485]
The Postgres appliance has `max_connections` set to 100 which is not enough for a large cluster running many applications.  Adding [PgBouncer](https://pgbouncer.github.io) myself is a decent solution, but that PgBouncer instance becomes a single point of failure.  If the Postgres appliance were to include PgBouncer, it would allow scaling up apps (and clusters) without running out of DB connections.

**Comment by josephglanville** [comment]
In the mean time we should probably bump `max_connections` to say 400 which will allow for larger clusters. The only component utilising connections linearly as the cluster scales is the scheduler, I am sure we can look into tuning down the connection pool size used in the scheduler to make this less of a factor in cluster scaling.

**Comment by titanous** [comment]
The scheduler shouldn't have a direct connection to the db, doesn't it go through the controller web instances?

**Comment by josephglanville** [comment]
Ahh yes, my mistake. I was thinking of the router.

**Comment by dashkb** [comment]
Hey y'all; I wasn't able to successfully get pgbouncer running.  Would you accept a PR raise `max_connections`?

**Comment by titanous** [comment]
Feel free to raise the variable.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
