### ISSUE TITLE
dial tcp: lookup controller.discoverd: no DNS servers

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2492]
```
22:24:44 remote: Error retrieving app: Get http://controller.discoverd/apps/43765157-b69b-42b7-93cc-7fbeb23b62e9: dial tcp: lookup controller.discoverd: no DNS servers        
22:24:45 To https://git.qa-us-east-1.flynn-internal.nexus.bazaarvoice.com/bv-pypi.git
22:24:45  ! [remote rejected] HEAD -> master (pre-receive hook declined)
22:24:45 error: failed to push some refs to 'https://git.qa-us-east-1.flynn-internal.nexus.bazaarvoice.com/bv-pypi.git'
22:24:45 
22:24:45 Command [git -c http.sslVerify=false push -f qa-us-east-1 HEAD:refs/heads/master] failed: exit status 1
```

`flynn-host collect-debug-info` only works on two of the three hosts (and only via on-disk log fall-back): https://gist.github.com/409d597e5df8b073a935 & https://gist.github.com/076028bed5de2a763d46 . Third node it fails on, with `22:43:16.175312 host.go:140: unexpected HTTP status: 405`.

**Comment by titanous** [comment]
This was probably caused by a discoverd failure during a CPU spike, currently there is no evidence of a bug in discoverd, if this happens again we can try to get more information about the cause of the CPU load.
