### ISSUE TITLE
`flynn env set` times out on new cluster

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2493]
`flynn -a gitreceive env set 'SSH_CLIENT_KEY=-----BEGIN RSA PRIVATE KEY-----
REDACTED
-----END RSA PRIVATE KEY-----' 'SSH_CLIENT_HOSTS=# github.com SSH-2.0-libssh-0.7.0
github.com ssh-rsa REDACTED'` results in `timed out waiting for deployment completion` on a newly built cluster built (restored from a backup). https://gist.github.com/470570d3bda632a942c4 has the debug info.

**Comment by titanous** [comment]
Looks like most of your recent cluster failures after restoring from a backup have the same root cause. I'm working on figuring it out.

**Comment by titanous** [comment]
Remaining sub-issues written up in #2545.
