### ISSUE TITLE
PHP7 in buildpack

### ISSUE THREAD

**Issue by NeilW** [flynn/flynn#2496]
A user wants to use PHP 7 but it looks like only the RC version is in the current build packs in Flynn.

Is there a way of bumping the build packs on a running flynn cluster?

**Comment by titanous** [comment]
No, problem doing so in #2497. In the mean time you can specify the buildpack URL manually with:

```text
flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php
```

**Comment by josephglanville** [comment]
LGTM
