### ISSUE TITLE
Only English locales present in slugrunner image

### ISSUE THREAD

**Issue by adamcharnock** [flynn/flynn#2500]
The slugrunner image [only contains english locales](https://gist.github.com/adamcharnock/33ddb2ac4f19a47270be). This also seems to be [heroku's behaviour](http://stackoverflow.com/questions/11486133/python-locale-settings-on-heroku) (or at least, it was in the past. That SO post implies this has changed).

I came across this while doing localisation in python. Upon using a non-english locale I received `Error: unsupported locale setting`.

[Submitting following IRC conversation with `jpg]

**Comment by josephglanville** [comment]
The current list of packages is available on the Heroku wiki here: https://gist.github.com/josephglanville/2c0279f5e4938f9446d6
It does now seem to include all the language packs etc.

I wrote a small script to extract the full list of packages in the Cedar-14 stack that should allow us to install everything available in the Heroku environment:
https://gist.github.com/josephglanville/2c0279f5e4938f9446d6

**Comment by adamcharnock** [comment]
Thanks @josephglanville!
