### ISSUE TITLE
Backup may fail silently if /tmp fills up

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2509]
We've received reports of cluster backups failing silently if the postgres dump fills up `/tmp`. They should be investigated.

**Comment by titanous** [comment]
I have tested this and ran into the correct error:

```text
error dumping database: error running export: write /home/vagrant/go/src/github.com/flynn/flynn/foo/postgres.sql.gz699451114: no space left on device
```

**Comment by dottodot** [comment]
Can tmp be emptied?

**Comment by titanous** [comment]
@dottodot I think so, but I'm not sure anyone has tested that.
