### ISSUE TITLE
Unbalanced routers after bootstrap

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2521]
This is the second time we've seen two routers on one node in a three node cluster, and zero on another.

https://gist.github.com/titanous/81ed9409d35e53f2d8ff
https://gist.github.com/460bf195cc5ab5ff097f
https://gist.github.com/a3d30cc5cce5dc21b320
https://gist.github.com/90450bc2d70a373b1ab2

**Comment by josephglanville** [comment]
Ref #2511
