### ISSUE TITLE
Can't set env on broken deployment

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2525]
I've push a deployment but have some wrong env variable which are causing the app not to work but using `timed out waiting for deployment completion` give an error of 

> timed out waiting for deployment completion

before I had pushed the app I could set envs without any issue

**Comment by titanous** [comment]
Would you please provide detailed reproduction steps with an open source example app? I am so far unable to reproduce this.

**Comment by titanous** [comment]
Closing for lack of detail, please open a new issue with reproduction steps.
