### ISSUE TITLE
SSL Certificate Untrusted

### ISSUE THREAD

**Issue by aaronfranco** [flynn/flynn#2528]
Hello,

I have migrated my installation to a new domain and used my own wildcard SSL certificate for all apps running. I have my CA bundle installed with my certificate, however I'm still getting an untrusted warning and external servers are unable to make requests to my apps. When I try to verify my SSL, using SSL Checker:
https://www.sslshopper.com/ssl-checker.html
It shows that the issuer of the invalid cert is Flynn. the exact error I'm getting reads:
````
The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. The fastest way to fix this problem is to contact your SSL provider.
````

Please let me know if there is something I'm missing.

**Comment by titanous** [comment]
How did you set up the new certificate with Flynn?

**Comment by aaronfranco** [comment]
I migrated my installation to a custom domain using the CLI and added the certificate to the App following the instructions I received from Alex :)

**Comment by titanous** [comment]
Okay, do you mind posting the app domain here so I can poke at it?

**Comment by aaronfranco** [comment]
Could I email it to you?

**Comment by titanous** [comment]
Sure, jonathan@flynn.io

**Comment by aaronfranco** [comment]
thanks

**Comment by titanous** [comment]
What commands did you use to set up the TLS certificate in Flynn? It does look like it hasn't been configured properly.

**Comment by aaronfranco** [comment]
To migrate the Domain
````
flynn cluster migrate-domain yourdomain.com
````
And then I used routes to add my cert to each app
````
flynn route update http/00000000-xxxx-xxxx-xxxx-000000000000 -c certfile.cert -k keyfile.key app1.my.domain.com
````

**Comment by titanous** [comment]
Hmm, that *should* work. You could try deleting and recreating the HTTP routes with the cert/key specified. If you want the same wildcard certificate for the default routes for all apps, try this:

```text
flynn -a router env set TLSCERT="$(cat certfile.cert)" TLSKEY="$(cat certfile.key)"
```

However note that if the cert chain (leaf+intermediate) or key don't match or are invalid, this will not work properly.

**Comment by aaronfranco** [comment]
Making my cert the default for the router fixed the problem! Thanks for your support!
