### ISSUE TITLE
obsolete cipher suite

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2538]
I've install a lets-encrypt cert on my app but I'm seeing an issue where it's saying 

> Your connection to example.com is encrypted using an obsolete cipher suite. 

Normally I'd look at the SSL protocols enabled in either apache or nginx but as Flynn doesn't use either of those so that's not an option.

Please can you advise where I should be looking to resolve this.

**Comment by titanous** [comment]
Where is that message coming from?

**Comment by titanous** [comment]
Please link to a [SSL Labs](https://www.ssllabs.com/ssltest/) report.

**Comment by dottodot** [comment]
Ok The SSL Labs report actually says all is good, it was chrome when you click on the padlock that reports this.

This is the full message on chrome
```
Your connection to example.com is encrypted using an obsolete cipher suite.

The connection uses TLS 1.2.

The connection is encrypted and authenticated using AES_128_GCM and uses RSA as the key exchange mechanism.
```

**Comment by titanous** [comment]
It is complaining that ECDHE was not used for key exchange. I see this for a site hosted on Flynn:

```text
Your connection to flynn.io is encrypted using a modern cipher suite.

The connection uses TLS 1.2.

The connection is encrypted and authenticated using AES_128_GCM and uses ECDHE_RSA as the key exchange mechanism.
```

I'm not sure why you don't, what version of Chrome are you using? Can you link to the SSL Labs report?

**Comment by dottodot** [comment]
I've updated Chrome and it's still the same the version are

Version 48.0.2564.116 (64-bit)
Version 49.0.2623.75 (64-bit)

At the moment I've trying to avoid posting any links to the site publicly, if I email you the domain would that work?

**Comment by dottodot** [comment]
I'm also seeing the same on flynn.io

![screen shot 2016-03-08 at 12 40 09](https://cloud.githubusercontent.com/assets/811652/13601871/f954c27a-e52a-11e5-8732-411f25c096c5.png)

**Comment by titanous** [comment]
Please post a screenshot of the "Protocol Features" section of this page: https://www.ssllabs.com/ssltest/viewMyClient.html

**Comment by dottodot** [comment]
![screen shot 2016-03-08 at 15 20 40](https://cloud.githubusercontent.com/assets/811652/13605848/7d60d71e-e541-11e5-97d5-53edd5f81bd0.png)
![screen shot 2016-03-08 at 15 21 03](https://cloud.githubusercontent.com/assets/811652/13605846/7d5f5baa-e541-11e5-93b8-4a0fba97e6b8.png)
![screen shot 2016-03-08 at 15 21 23](https://cloud.githubusercontent.com/assets/811652/13605847/7d5f6208-e541-11e5-8654-014e4075362a.png)

**Comment by titanous** [comment]
Thanks, what OS are you running Chrome on?

**Comment by dottodot** [comment]
OSX 10.10.5

**Comment by dottodot** [comment]
OSX 10.10.5

On 8 March 2016 at 15:29, Jonathan Rudenberg <notifications@github.com>
wrote:

> Thanks, what OS are you running Chrome on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flynn/flynn/issues/2538#issuecomment-193824420>.
>



-- 

*Marcus Williams* | Dot to Dot Design
Website Design & Consultancy
07855 380126
marcus@dottodotdesign.co.uk / www.dottodotdesign.co.uk

**Comment by titanous** [comment]
Ah, that's probably the problem. It works fine on OS X 10.10, I don't think this is a problem.

**Comment by titanous** [comment]
I believe this is a limitation of OS X 10.10. I did not encounter this issue with the same version of Chrome on OS X 10.11.
