### ISSUE TITLE
Wildcard routes are limited to 5 levels deep

### ISSUE THREAD

**Issue by bfontaine** [flynn/flynn#2541]
See https://github.com/flynn/flynn/commit/2140a10dcd39d1a31947daf407a4cdde5ac414f6. It’d be great if that could be either unlimited or with a larger limit (e.g. 10).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
