### ISSUE TITLE
Opening SSH tunnel to postgres database without using ip of the postgres container

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#2544]
I want to open an SSH tunnel to the postgres instance, but can't find a way to do it via hostname rather than IP. For now I'm using a workaround of `netstat -an | grep 5432` to find what is listening on that port and just using that IP. The problem is that the IP is subject to change, and when it does I need to go find it again and update my connection.

One possible solution recommended by @lmars in IRC:

> one option is to add the flynnbr0 interface address as a nameserver entry in /etc/resolv.conf, then the host can resolve the DNS names

However per @titanous in IRC:

> that could result in a loop, we read resolv.conf to figure out the upstream resolver

Any other options on how to handle this?

**Comment by titanous** [comment]
Leader routing could solve this, but we need to set up TLS for Postgres first: #2395

**Comment by titanous** [comment]
This is now documented: https://flynn.io/docs/databases/postgres#external-access

**Comment by kevinob11** [comment]
Splendid, thanks!
