### ISSUE TITLE
Scheduler tries to re-create failed job with same job ID

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2545]
- Scheduler calls `AddJob` against host.
- `AddJob` takes longer than the scheduler timeout, and the job ends up being created
- The scheduler, thinking the job create failed, tries to place the exact same job with the same ID on the same host. This fails, but the scheduler keeps on trying.

When a `AddJob` call fails, a new job ID should be generated and we should probably re-run the placement logic. Also, we should confirm that flynn-host does not allow creation of a job with an existing ID.

**Comment by titanous** [comment]
This shouldn't happen in practice, much since #2503, however it should be fixed.

**Comment by lmars** [comment]
@titanous 

> AddJob takes longer than the scheduler timeout, and the job ends up being created

I assume we are talking about [the 5s HTTP request timeout](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L140)?

> The scheduler, thinking the job create failed, tries to place the exact same job with the same ID on the same host. This fails, but the scheduler keeps on trying.

In what way does it fail? Ideally it would be a 409 Conflict that the scheduler can catch to indicate the job already exists and stops retrying.

> When a AddJob call fails, a new job ID should be generated

This does make things a little more involved for the scheduler, there are quite a few code paths which assume a job's ID is immutable (well, [the UUID part](https://github.com/flynn/flynn/blob/master/controller/scheduler/job.go#L42-L48)).

>  and we should probably re-run the placement logic

This is currently the case (see [this loop](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L822-L853)), however most of the time it just picks the same host again.

**Comment by titanous** [comment]
> I assume we are talking about the 5s HTTP request timeout?

Yes.

> In what way does it fail? Ideally it would be a 409 Conflict that the scheduler can catch to indicate the job already exists and stops retrying.

Not certain, I wrote this issue based on notes from a few days ago. We should be able to replicate by adding a >5s delay to the AddJob HTTP request handler.
