### ISSUE TITLE
Dashboard: Log viewing is not ideal

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#2547]
![skarmavbild 2016-03-09 kl 08 49 20](https://cloud.githubusercontent.com/assets/891566/13628712/b5f25b14-e5d4-11e5-9d32-50c028e76b01.jpg)
![skarmavbild 2016-03-09 kl 08 49 29](https://cloud.githubusercontent.com/assets/891566/13628714/b951a076-e5d4-11e5-902d-cfc64bfca982.jpg)

The UX when an app has been running for a while is not very pretty. Logs is hidden far down. Also we the log view could benefit from being a lot wider, ideally fullscreen width.

Related to #2254.

**Comment by mnaughto** [comment]
Other issues with the log interface: sometimes when I select one of the processes in the list, several are highlighted. Scrolling in the log viewer is not consistent - sometimes I have to use my arrow key, sometimes it works out of the box with my trackpad. Also it's not clear what the difference between "crashed" and "down" is. Any idea when this might get resolved or improved?
