### ISSUE TITLE
Missing /dev/shm on base image

### ISSUE THREAD

**Issue by adamcharnock** [flynn/flynn#2570]
I'm encountering errors when starting up celery worker processed on flynn. It seems that celery's default worker pool makes use of shared memory, which I imagine Python expects to find in `/dev/shm`.

While a number of fixes [seem to exist](https://www.google.com/search?q=missing+%2Fdev%2Fshm), namely:

```bash
sudo ln -s /run/shm /dev/shm  # untested
```

However, I cannot gain permission to run this as part of the deployment process.

Can/should the base image be updated to include `/dev/shm`?

**Comment by titanous** [comment]
Looks like we need to do something along these lines:

```xml
<filesystem type='ram'>
    <source usage='10000'/>
    <target dir='/dev/shm'/>
</filesystem>
```

http://libvirt.org/formatdomain.html#elementsFilesystems

@josephglanville Any thoughts on this?
