### ISSUE TITLE
install-script: Check if Flynn is installed before setting remove flag for --clean

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2572]
It'd be nice not to get the confirmation prompt when remove will be a no-op.

**Comment by titanous** [comment]
This should be as simple as checking if there are any volumes in the `flynn-default` pool.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
