### ISSUE TITLE
`flynn-host update` replaces slugrunner image with slugbuilder

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2577]
@adamcharnock has a cluster that has been updated with `flynn-host update` that is using the slugbuilder image where the slugrunner image should be. We should audit the updater to figure out how this can happen. [This code](https://github.com/flynn/flynn/blob/eeb8d80c17ff255329d68210493a67734eec69f1/updater/updater.go#L224-L235) looks suspicious.

**Comment by adamcharnock** [comment]
In case it is relevant: Upon staring a new cluster I noticed that `SLUG_URL` had been set in the env for each app. I'm not sure how this came to be, as I'm pretty sure it wasn't me.
