### ISSUE TITLE
How do I stay at PHP 5.6?

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2578]
Hi,
I just installed the latest new version (v20160314.0) and tried to deploy my application. But even if I specify very explicitly the PHP version in my composer.json:

>        "php": ">=5.3.9 <=5.6.19",

I still get PHP 7:

> -----> Installing platform packages...
>        - php (7.0.4)

Is there a way to stay at PHP 5.6 currently?

Later, the deployment fails due to:

>        [ImagineExceptionRuntimeException]
>       Gd not installed

Which I actually have in the composer.json:

>         "ext-gd": "*",

I would love to use the "old" PHP buildpack, this one worked well for me. :)

**Comment by titanous** [comment]
Try this: `"php": "^5.6"`

**Comment by philiplb** [comment]
Thanks you for this fast answer.
Same result I'm afraid.

**Comment by titanous** [comment]
Did you run `composer update` and then commit the changes to `composer.lock` before pushing to Flynn?

**Comment by philiplb** [comment]
Oh, of course. That did the trick, sry for that.
Interesting: Before, the slugsize of this application used to be around 112M. Now it is 48M.
