### ISSUE TITLE
Error creating an app and be independent from flynnhub.com and flynn.io

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2579]
Hi,
while running
```bash
flynn create myapp
```

I now get this:

> Post https://controller.ow65.flynnhub.com/apps: remote error: internal error

Beside the error, would it be possible to setup a cluster being completly independent of flynnhub.com and flynn.io? Starting with the discovery:
```bash
flynn-host init --init-discovery
```

Resulting in a URL pointing to https://discovery.flynn.io

AKA "can I run a cluster on my own?"

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug-info` to collect and upload relevant logs.

You can use the `--peers` argument instead of the discovery token.

**Comment by philiplb** [comment]
Ah, good to know.

Logs: Sure:
https://gist.github.com/philiplb/c45fd21987f5e667dfbb

**Comment by philiplb** [comment]
Hm, when setting up the cluster again, I still got this error. I found this:
> flynn cluster
> NAME              CONTROLLER URL                        GIT URL
> flynn-1452010161  https://controller.ow65.flynnhub.com  https://git.ow65.flynnhub.com  (default)
> default           https://controller.flynn.xyz.com    https://git.flynn.xyz.com

No clue how this default cluster sneaked in and when. I removed it via flynn cluster remove ... and voilà, all good again.
