### ISSUE TITLE
Error on running docker container

### ISSUE THREAD

**Issue by Sabmit** [flynn/flynn#2582]
I followed the documentation to try to run a docker container, but it keeps failing.
Flynn is using docker registry api v1, and the endpoint : ``v1/repositories/IMAGE_NAME/images``

Also, I got this error : 
```00:01:28.971789 host.go:141: registry: unexpected status 404```

instead of getting a "repo not found" error (cf. [docker.go](https://github.com/flynn/flynn/blob/390ecd824a2111ec0c4d21a9a5fe13cdb940f14b/pinkerton/registry/docker.go#L54))

I've the last version of Docker running on my hosts :
```
ubuntu@ip-10-0-1-80:~$ docker -v
Docker version 1.9.1, build a34a1d5
```

API v1 does not seems to be deprecated, but I found this issue : https://github.com/docker/docker/issues/18179, I don't know if it's related.

**Comment by titanous** [comment]
This should be resolved as of #2857.
