### ISSUE TITLE
Confirmation when you delete a cluster via the installer 

### ISSUE THREAD

**Issue by jontonsoup** [flynn/flynn#2585]
I noticed that you can click the trash can on the installer page for a service and the installer will faithfully delete everything without a confirmation. 

This is scary -- I'd love to see a confirmation button at least (or the github double opt in -- a la their repo delete feature) in case I decide to ruin my life by accident.

**Comment by jvatic** [comment]
@jontonsoup There should be a confirmation modal when you click the trash icon for a cluster in the installer, are you not seeing that? What browser/version OS/version are you using? And do you see any errors in the JavaScript console?

**Comment by jontonsoup** [comment]
@jvatic Let me double check -- I was pairing on this and we both made a comment at the same time about how it seemed dangerous. Its possible we both tricked ourselves though.

**Comment by jontonsoup** [comment]
@jvatic PEBCAK -- seems to be working now. Everything probably works fine, and I just clicked the button so fast I forgot I did it :). 

Double opt in is nice something to think about to save smart people like myself from myself.

**Comment by jvatic** [comment]
@jontonsoup I'll keep an eye out for this as it could have been an intermittent bug of some kind. Feel free to open another issue regarding the double opt in.
