### ISSUE TITLE
`flynn env set` fails on restored cluster

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2586]
```
19:20:44.405927 cluster-monitor cluster-monitor'
+ echo 'Bootstrap succeeded'
Bootstrap succeeded
+ slept=0
+ add_local_flynn_config
++ cat controller.auth_pin.txt
++ cat controller.auth_key.txt
+ flynn cluster add -p a6x8x6NmzsUE+jcv76ZJi64xy6p01ZABaU8sL3TOIoM= qa-us-east-1-cluster-2016-03-16-13-41-56 qa-us-east-1.flynn.nexus.bazaarvoice.com 62b07a2c7f6e9d12928b81a3a9726649
Cluster "qa-us-east-1-cluster-2016-03-16-13-41-56" added and set as default.
+ [[ 10.100.36.169,10.100.45.219,10.100.43.172 == 10.100.36.169* ]]
+ [[ 2016-03-16-17-17-01 != \n\o\n\e ]]
+ sleep 300
++ cat ssh_client_key
++ cat ssh_client_hosts
+ flynn -a gitreceive env set 'SSH_CLIENT_KEY=-----BEGIN RSA PRIVATE KEY-----
XXX
-----END RSA PRIVATE KEY-----' 'SSH_CLIENT_HOSTS=# github.com SSH-2.0-libssh-0.7.0
github.com ssh-rsa XXX'
unknown_error: Something went wrong
```

This is after restore from a rather large backup. https://gist.github.com/cc9031fb32da9dd462d1 https://gist.github.com/6bd8d4b4f753e20f7f89 and https://gist.github.com/15e140c432d1b627c5b4 are the debug-info.

**Comment by temujin9** [comment]
Same error on a new cluster: https://gist.github.com/645dd02581fd5bf52419 https://gist.github.com/8783d07c8979beedd633 https://gist.github.com/fe296ccea45af2125d85 . Repeated tries did not improve things.

**Comment by temujin9** [comment]
Same failure location, slightly different output: "GET https://controller.prod-us-east-1.flynn.nexus.bazaarvoice.com/apps/gitreceive/release: httpclient: raw req: unexpected status 503"

collect-debug-info: https://gist.github.com/959c55aa4a39d13167a8 https://gist.github.com/e3af35c71aa8a7a011f0 https://gist.github.com/db5dd7282fd67c8c9ae6

**Comment by titanous** [comment]
I think that between #2618 and #2590 the known causes of this should be mitigated. Please open a new issue if you see it again.
