### ISSUE TITLE
Hostnames in --peer-ips

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2603]
Hi,

today, I naivly tried to init a cluster via
```bash
sudo flynn-host init --peer-ips=flynn0.foo.bar,flynn1.foo.bar,flynn2.foo.bar
```

(Where flynn0.foo.bar is a A record in a DNS server)

Then the bootstrap:
```bash
sudo \
    CLUSTER_DOMAIN=flynn.smfhq.com \
    flynn-host bootstrap \
    --min-hosts 3 \
    --peer-ips=flynn0.foo.bar,flynn1.foo.bar,flynn2.foo.bar
```

Too bad, the router didn't come up:

> 00:52:57.148045 deploy-app router
> 00:54:02.536330 deploy-app router error: unknown_error: Something went wrong

Fair enough, the parameter wants IPs, not hostnames. But wouldn't it be nice to use hostnames there? Then the initial three nodes could be dynamically replaced if one fails really hard?

**Comment by titanous** [comment]
The plan is to handle consensus cluster reconfiguration (#2398), using IPs keeps a lot of things simple. We'll be addressing this soon.

**Comment by philiplb** [comment]
I understand, thanks.
