### ISSUE TITLE
Timeouts for environment variables and releases

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2604]
With the version v20160314.0 on a freshly setup cluster I still get timeouts. For example, (re-)deployment of env vars:
> timed out waiting for job events: map[web:map[up:1]]

**Comment by titanous** [comment]
Check the logs. Is your application starting correctly?

**Comment by titanous** [comment]
Also, how big is the slug?

**Comment by philiplb** [comment]
Hi,
thanks.
The application is up and running. Steps to reproduce for me:

- Setup cluster
- Set environment variables (instant)
- Deploy application (takes a while but works, np)
- Set environment variables again or deploy again -> timeout

The slug size is 48MB.
Maybe important: The applications depedencies are a few thousand small files which is normal for Symfony2.

**Comment by jvatic** [comment]
@philiplb are you using the dashboard to set the env? If so I think I know what's going on here and will push a fix shortly.

**Comment by jvatic** [comment]
(took a closer look at this issue and it seems unlikely you're using the dashboard)

**Comment by philiplb** [comment]
That's true, I'm deploying via git push.

**Comment by philiplb** [comment]
Hi, I'm using also the command line to set the env vars.

**Comment by titanous** [comment]
Please attempt to deploy the app and then run `sudo flynn-host collect-debug-info` on a server.

**Comment by philiplb** [comment]
Thx for the fix, will try as soon as there is a new release. :)

**Comment by philiplb** [comment]
Seems to work now. :)
