### ISSUE TITLE
Explanation of warnings that occur during postgres appliance restore command

### ISSUE THREAD

**Issue by diclophis** [flynn/flynn#2606]
Heya flynn team, keep up the good work, this thing is getter better every release... small question though... what do these warnings mean, and are they safe to ignore... and/or is there a way to prevent them?

	pg_restore: [archiver (db)] Error while PROCESSING TOC:
	pg_restore: [archiver (db)] Error from TOC entry 5; 2615 2200 SCHEMA public postgres
	pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of schema public
	    Command was: DROP SCHEMA IF EXISTS public;
	
	pg_restore: [archiver (db)] could not execute query: ERROR:  schema "public" already exists
	    Command was: CREATE SCHEMA public;
	
	
	
	pg_restore: [archiver (db)] Error from TOC entry 2124; 0 0 COMMENT SCHEMA public postgres
	pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of schema public
	    Command was: COMMENT ON SCHEMA public IS 'standard public schema';
	
	
	
	pg_restore: [archiver (db)] Error from TOC entry 2125; 0 0 COMMENT EXTENSION plpgsql 
	pg_restore: [archiver (db)] could not execute query: ERROR:  must be owner of extension plpgsql
	    Command was: COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
	
	
	
	WARNING: errors ignored on restore: 4

**Comment by titanous** [comment]
Safe to ignore, there is no way to prevent them.

**Comment by diclophis** [comment]
Ok, thanks
