### ISSUE TITLE
Expand collect-debug-info capabilities

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2611]
Currently, `collect-debug-info` truncates logs in an (often failed, resulting in a 405) attempt to fit them into a Gist. 

There is a `--tarball` option for dumping locally. It would be nice if an `--all` or similar option for that to collect all necessary info, so that a second collection pass isn't required.

It would also be super awesome if there were an `--s3` option that could attempt an S3 upload to a passed-in path, rather than a Gist.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
