### ISSUE TITLE
Some processes refused to die during --clean

### ISSUE THREAD

**Issue by Snugug** [flynn/flynn#2619]
Okay, so Flynn was just hanging so I tried to [reinstall it](https://github.com/flynn/flynn/issues/1092) (I've got nothing in there) and am getting "Some processes refused to die" error. This is preventing me from working with Flynn. Thoughts on how to get past this?

```
 sudo bash /tmp/install-flynn --remove
===> 19:26:15.994 *** WARNING ***
===> 19:26:15.997 About to stop Flynn and remove all existing data
===> 19:26:16.000 Are you sure this is what you want?
(yes/no): yes
===> 19:26:17.753 stopping flynn-host daemon
===> 19:26:17.760 killing old containers
===> 19:26:17.814 running "virsh -c lxc:/// destroy dpev340-6c4515c9-0899-49aa-9d23-894362a26113"
error: Failed to destroy domain dpev340-6c4515c9-0899-49aa-9d23-894362a26113
error: internal error: Some processes refused to die
```

**Comment by lmars** [comment]
@Snugug is there anything interesting in `/var/log/libvirt/libvirtd.log`? (the containers are currently run using `libvirt-lxc` which logs to that file).

Do you also have any containers running (check `ps faux | grep libvirt-lxc`).

If this error persists, rebooting will probably clear the state.

**Comment by Snugug** [comment]
Have this in there:

`2016-03-20 13:40:47.891+0000: 19561: error : virNetSocketReadWire:1454 : End of file while reading data: Input/output error`

Restarting resolved the problem. Next time I'll remember to turn it off and on again :stuck_out_tongue_closed_eyes:
