### ISSUE TITLE
scheduler: Handle "batch" jobs

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2620]
Long running jobs (i.e. ones part of a formation) are currently managed by the scheduler which makes sure they are properly distributed and restarted when they crash.

One-off jobs (which I will now call batch jobs) are however scheduled in one of two ways:
- by `pkg/exec` using a simple [random scheduler from pkg/schedutil](https://github.com/flynn/flynn/blob/master/pkg/schedutil/simple.go#L15)
- by the controller, also [randomly](https://github.com/flynn/flynn/blob/master/controller/jobs.go#L269)

We should move this logic into the scheduler and use the same rules as we do for long running jobs (i.e. distribute evenly over hosts, restrict by tag, and in the future resource based scheduling).

I propose adding a `BatchJob` type, backed by a `batch_jobs` table in the controller database, which the scheduler then runs in the cluster:

``` go
type BatchJob struct {
    // NewJob serves as the spec for running the job
    NewJob

    // RestartOnFailure indicates whether the scheduler should
    // restart the job if it exits non-zero, likely with the same
    // backoff as long running jobs
    RestartOnFailure bool

    // Status is either "pending", "running", "succeeded" or "failed"
    Status BatchJobStatus

    // Jobs is a list of cluster jobs which have been run for
    // this batch job, making it easy to do things like view all
    // the logs
    Jobs []*Job
}
```

If we have this, then we could replace the controller worker with just running batch jobs, which would be especially beneficial for deployments as the logic can then live in the apps being deployed, logs can be seen for deployments via `flynn log -t deploy` and `git push` could attach to the batch job to give more feedback to end users.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
