### ISSUE TITLE
`flynn redis redis-cli` should work against redis app

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2624]
```text
$ flynn -a redis-41d24f34-ee9f-4b16-8336-9ac0fc5e6d48 redis redis-cli
No redis server found. Provision one with `flynn resource add redis`
```

**Comment by thomasmodeneis** [comment]
Hi @titanous 
Any ideas how can I work around to connect to the redis-cli while this enhancement is not yet done ?

Out of 3 instances of redis in the cluster I'm only able to connect to one via the normal `flynn -a appname redis redis-cli`

other instances give me error:
No redis server found. Provision one with `flynn resource add redis`

However flynn resource tells me there is a redis resource there, not sure what to do. Any ideas ?

Thanks

**Comment by josephglanville** [comment]
@thomasmodeneis can you check for the existence of a `FLYNN_REDIS` variable in your applictions environment variables? You can check this with `flynn -a appname env`

If that variable isn't present that is the problem and we will need to traceback how you created the resource to work out why a release wasn't created with it set.

**Comment by thomasmodeneis** [comment]
I'm not sure why that happened, but FLYNN_REDIS was not there. Adding FLYNN_REDIS made the trick, thanks.
