### ISSUE TITLE
Also use HTTP or connections without keep-alive for the heartbeat checks

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2625]
One of my nodes in a 3 node cluster had exhausted all of it's file handles. I had no way of connecting to the node and all requests routed to the apps on the node returned 503. However, since the heartbeat check uses keep-alive connections, the heartbeat was working fine and the node was never dropped from the cluster.

While chances of this happening are on the lower end, I think the heartbeat check should verify (at least periodically) that new connections can be opened. This way, at least in in my scenario, the heartbeat check would have failed - dropping the node from the cluster - and prevented the 503 errors.

**Comment by titanous** [comment]
The health check does not use keep-alives: https://github.com/flynn/flynn/blob/b5e12de68d26a63a4f6e0f64993d39d59f43fa64/discoverd/health/check.go#L74
