### ISSUE TITLE
Postgres Not Persisting

### ISSUE THREAD

**Issue by aaronfranco** [flynn/flynn#2631]
hello,

I have an Nodejs app that saves data into Postgres using pg-native nodejs module.
```
        pg.connect(db_conn, function(err, client, done) {
                if (err) {
                    console.log("PostGres connection error:"+err);
                    if(client){
                        done(client);
                    }
                    reject(err);
                } else {
                    resolve({"client":client, "done":done});
                }
            }
        );
```
When I made some code modifications and then redeploy my app using flynn dashboard, either the data is at a much older version or it is entirely gone. 

Is this the expected behavior?

**Comment by titanous** [comment]
In general, the Postgres appliance doesn't "lose" data. Is the code on GitHub? There may be an issue with how the data is being written to PG.

**Comment by aaronfranco** [comment]
It is being written bjson...
````
INSERT INTO table (data) VALUES '{"some":"json", "data":"saved"}';
````
or
````
UPDATE table SET data=\'{"some":"newjson", "data":"saved"}';
````
is all executed via the following two methods
````
 // native postgres for slightly improved performance
var pg = require('pg').native;
// promise library
var when = require('when');
function db() {
    return when.promise(function(resolve,reject,notify) {
        pg.connect(db_conn, function(err, client, done) {
                if (err) {
                    console.log("PostGres connection error:"+err);
                    if(client){
                        done(client);
                    }
                    reject(err);
                } else {
                    resolve({"client":client, "done":done});
                }
            }
        );
    });
}
function query(q_str) {
    return when.promise(function(resolve,reject,notify) {
        var results = [];
        db().then(function(conn){
            var q1 = conn.client.query(q_str);
            q1.on('error', function(error) {
                conn.done();
                console.log(error)
                resolve({})
            });
            q1.on('row', function(row) {
                results.push(row);
            });
            q1.on('end', function(){
                conn.done();
                resolve(results)
            });
        });
    });
}
````

When the tables are created, it using this basic query:
````
CREATE TABLE IF NOT EXISTS tablename (id serial primary key, data jsonb);

````

**Comment by titanous** [comment]
I'd suggest checking if the data is in the database with the console: `flynn -a APPNAME pg psql`

**Comment by aaronfranco** [comment]
I can confirm that when I run my app, the data is saved into the DB. Then, when I modify my release and redeploy, the database is at some older version... perhaps the data isn't being pushed to the replica-set completely... ? I'll continue investigating my app, however it never deletes data or write over the database on boot.

**Comment by titanous** [comment]
Okay, please try to create a minimal test case that can be deployed from a public GitHub repo.

**Comment by aaronfranco** [comment]
yes, It is an app issue that I'm unsure how to fix. Will close then comment when I find the solution. Thanks.

**Comment by vitaly-t** [comment]
@aaronfranco Maybe or maybe not related to your problem, depending on what you find out yourself. But instead of coding around `pg` and `when`, have a look at [pg-promise](https://github.com/vitaly-t/pg-promise), it can save you from a lot of trouble ;)
