### ISSUE TITLE
router should be able to add http/https listeners on custom ports

### ISSUE THREAD

**Issue by swaits** [flynn/flynn#2633]
It'd be useful to be able to able to add http and https listeners on ports other than 80 and 443.

For example, I may need to deploy an http service on 8080. If I could have the http router also listen on 8080, then I could do hostname based routing on that port.

As it stands, the best option is adding a tcp listener. But unfortunately, then you don't get any multiplexing. That port will be tied to a specific single app.

**Comment by Altneu** [comment]
I second this request.

**Comment by temujin9** [comment]
Thirded. BV would like this and #3196 (which pretty much looks like this plus some well-chose `flynn route add` and `flynn route delete` calls) for a number of reasons.

@titanous I'm taking you at your word that this is an easy enhancement, and going to dive into it soon (next day or two). Any pointers you can provide on how to proceed would be much appreciated.

**Comment by titanous** [comment]
This shouldn't be particularly hard, it involves adding a new HTTP route option (perhaps `listener_port`) throughout the system, and then adding support for listening on additional ports (driven by a router environment variable).

The HTTP listening code is in [this file](https://github.com/flynn/flynn/blob/master/router/http.go). The database schema [is here](https://github.com/flynn/flynn/blob/master/router/schema.go). The [associated queries](https://github.com/flynn/flynn/blob/master/router/schema/queries.go) and [data storage](https://github.com/flynn/flynn/blob/master/router/data_store.go), and [data types](https://github.com/flynn/flynn/blob/master/router/types/types.go) will need to be updated.

The CLI commands [are here](https://github.com/flynn/flynn/blob/master/cli/route.go). 

Feel free to open a PR with an early draft or ask additional questions here.
