### ISSUE TITLE
`flynn cluster add` fails on restored cluster

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2639]
```
17:54:46.113689 status-check status
17:55:02.494246 cluster-monitor cluster-monitor'
+ echo 'Bootstrap succeeded'
Bootstrap succeeded
+ slept=0
+ add_local_flynn_config
++ cat controller.auth_pin.txt
++ cat controller.auth_key.txt
+ flynn cluster add -p a6x8x6NmzsUE+jcv76ZJi64xy6p01ZABaU8sL3TOIoM= qa-us-east-1-cluster-2016-03-27-12-27-45 qa-us-east-1.flynn.nexus.bazaarvoice.com 62b07a2c7f6e9d12928b81a3a9726649
Error writing CA certificate: Get https://controller.qa-us-east-1.flynn.nexus.bazaarvoice.com/ca-cert: dial tcp 127.0.0.1:443: connection refused
```

That failure continues ad infinitum. Debug-info: https://gist.github.com/b444337c583cd99f1e6c https://gist.github.com/2fc2dcd7aa02c6e52949 https://gist.github.com/b282973076ae111e685f

**Comment by temujin9** [comment]
Another occurance: https://gist.github.com/1064d554ba615429630d https://gist.github.com/06a302325aea7eefdfa6 https://gist.github.com/e240d9a1fca7f17824b2

**Comment by temujin9** [comment]
Another occurrence: https://gist.github.com/9118c1f68abccb8248e5a204ef00e324 https://gist.github.com/d9f807f25d6c4ef1f01c358aa97af377 https://gist.github.com/859abdeb2b8e93986c89adb24853b7d4

**Comment by temujin9** [comment]
Another occurrence: https://gist.github.com/301d105dab0e552c542bdc8c6c1d90ff https://gist.github.com/b99fef3bbecad3e62abe55f4d211f4fc https://gist.github.com/45d50ba82734adc06ba84469cf4b3706

**Comment by temujin9** [comment]
https://gist.github.com/4ae7d70d2a0779cfe586a48dc7f6aa0b https://gist.github.com/70acc932ce64d6dca5e97f09acc40878 https://gist.github.com/5832ff0a9b269371144a2aa77ede5642

**Comment by tianx2** [comment]
FYI - the problem occurred again today. I accidentally tore down the stack that the problem so I wasn't able to collect the debug logs.

**Comment by tianx2** [comment]
Another occurrence:
https://gist.github.com/aa6a75160e81ca38d0eaba0f5f2439a9
https://gist.github.com/253552c0e9bd22aec6a475e6e545b788
https://gist.github.com/46b58ac54b832d857006cec5ed4ed334

**Comment by temujin9** [comment]
https://gist.github.com/137ad26215f81aecb8beeb02dcc617bf
https://gist.github.com/c977447bdb745b4a042337b9c71eac27
https://gist.github.com/acbbf99e669e44f5438feeb923ce14fb
https://gist.github.com/2f5d5909d1c89d714792c0900e2eee1c
https://gist.github.com/7ab6f52e4662cc1d97e1cd28b924e7aa

**Comment by titanous** [comment]
Has this happened recently?

**Comment by temujin9** [comment]
I don't believe so: I'll close it for now, and reopen if it does come back.
