### ISSUE TITLE
Reset root password on DO and now flynn dashboard doesn't work

### ISSUE THREAD

**Issue by jbhatab** [flynn/flynn#2640]
I reset my root password for DO and now I can't access the dashboard.

<img width="1153" alt="screen shot 2016-03-28 at 4 58 58 pm" src="https://cloud.githubusercontent.com/assets/2458718/14091552/81461acc-f506-11e5-97f7-e55278ea2797.png">

I'm getting this error when I type flynn apps, "Get https://controller.5434.flynnhub.com/apps: dial tcp 159.203.224.86:443: connection refused". I think I just need to set the new PW somehow but not sure how to do that.

**Comment by jvatic** [comment]
@jbhatab Did you [ssh into the cluster](https://flynn.io/docs/faq/how-do-i-ssh-to-flynn-cluster-hosts) and enter a new root password?

**Comment by jbhatab** [comment]
@jvatic I just reset it on the digital ocean dashboard on their website. How can I apply this new pw to flynn?

Also for the link you just sent, what is the ip it's referring to? The apps digital ocean IP? I noticed that the ip it said it had failed connection to wasn't the exact ip of the droplet but something similar so I figured it had to do with DO but not sure exactly what it was.

**Comment by jvatic** [comment]
The workflow for resetting the root password via the DO dashboard is a bit confusing. Here's the steps I had to take:

1) Press "Reset Root Password" button in DO dashboard (a temp password will be emailed to you and the droplet rebooted)
2) SSH into droplet
3) Copy and paste new root password from email when prompted for current root password
4) Enter new password and confirm
5) Wait a few seconds for everything to come back up

Yes, `<ip>` is the droplet IP.

**Comment by jbhatab** [comment]
@jvatic I really appreciate the help. Now maybe I need to give it more time, but I set the new password using flynn ssh and it still is saying connection refused. The dashboard is doing the same thing.

When I type 'flynn apps' I still get the same connection refused error: "Get https://controller.5434.flynnhub.com/apps: dial tcp 159.203.224.86:443: connection refused". 

Now I don't know if this is relevant but the ip that it is saying connection refused for is not the ip of my droplet. It's similar but not exactly the same.

**Comment by jvatic** [comment]
It sounds like DO changed the droplet IP at some point. The easiest thing to do here is start fresh.

**Comment by jvatic** [comment]
Note that I haven't been able to reproduce the IP changing by resetting the root password. You're sure the droplet IP isn't `159.203.224.86`?

**Comment by jvatic** [comment]
@jbhatab Is this still an issue?
