### ISSUE TITLE
Apps Fail to Start on Restored Cluster

### ISSUE THREAD

**Issue by nasali** [flynn/flynn#2642]
Hi there,

Restoring a single node cluster from backup, flynn-host v20160327.0, does not seem to work.
The node is setup on AWS with a VM size of m4.xlarge running Ubuntu 14. It was installed using the following:
```
$ sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn)
$ sudo flynn-host init --init-discovery
$ sudo CLUSTER_DOMAIN=mydomain.com flynn-host bootstrap --min-hosts 1 --discovery https://discovery.flynn.io/clusters/4347cb76-4195-4b66-8aea-8f9e55db4056 --from-backup ~/backup.tar.gz 
```
The output of the bootstrap is this:
```
15:48:19.424396 check online-hosts
15:48:19.521460 run-app discoverd
15:48:19.822744 run-app flannel
15:48:20.206703 wait-hosts wait-hosts
15:48:22.710089 run-app postgres
15:48:26.898262 wait postgres-wait
15:48:27.275266 restore-postgres restore
16:03:11.692078 run-app controller
16:03:13.266495 status-check status
16:04:15.370455 cluster-monitor cluster-monitor
```
But this is what I see
```
$ sudo flynn-host ps
ID                                           STATE    STARTED             CONTROLLER APP  CONTROLLER TYPE
flynn0-b952e5a6-e5ab-49dc-902e-ffc6ebfdbc35  running  About a minute ago  redis           web
flynn0-857a62f9-d74f-4c24-beaa-26492de8b30c  running  2 minutes ago       logaggregator   app
flynn0-3757b75e-0bd5-4ec2-906f-5c07e3487a37  running  2 minutes ago       controller      worker
flynn0-5d422502-0903-418e-b2d3-b95732f34d50  running  2 minutes ago       controller      worker
flynn0-89d7934c-57f6-4980-b0df-7b11aff27aad  running  2 minutes ago       controller      web
flynn0-bd333fa5-a60d-4caf-8dc2-5fe36fe12e8c  running  2 minutes ago       status          web
flynn0-01494925-9fed-4f71-b172-3dd826cd9c55  running  2 minutes ago       controller      web
flynn0-96f80d08-752d-4182-9dfd-d3ce2008f145  running  2 minutes ago       controller      scheduler
flynn0-195c6ade-0a0b-4057-adc2-12d994fd5239  running  17 minutes ago      postgres        web
flynn0-8ba39596-90a1-4715-a4e5-e24395d1451c  running  17 minutes ago      postgres        web
flynn0-6262f1f0-723a-4512-84a7-0fe55d9e225b  running  17 minutes ago      postgres        postgres
flynn0-3d3d8ceb-2653-4dec-b915-fb74ea81cb90  running  17 minutes ago      postgres        postgres
flynn0-15e7ceca-9d06-436c-a723-510760677fca  running  17 minutes ago      postgres        postgres
flynn0-574a66a8-8033-4188-a49c-d905c29cbdbd  running  17 minutes ago      flannel         app
flynn0-1a948f25-7c92-4ef6-afce-c0ab4eaf91fb  running  17 minutes ago      discoverd       app
```
That shows zero apps, and there should be a few dozen apps. I'm also unable to use the CLI to communicate with the cluster. Here's my [debug info](https://gist.github.com/anonymous/398cb1178bdedcacc382)

How do I restore my apps?

Thank you so much in advance.

**Comment by titanous** [comment]
Hmm. The apps are crashing because the blobstore hasn't been started. Would you please gist the output of `flynn-host log flynn0-96f80d08-752d-4182-9dfd-d3ce2008f145`?

**Comment by titanous** [comment]
Also, I think that the cluster may come up if you leave it for a while. There are some things we can do to improve this situation. @lmars will have a look.

**Comment by nasali** [comment]
Thanks for the quick response. Here's the output of the [command](https://gist.github.com/anonymous/062dd31fcf90b241e9a80f6f033e3db4) you pasted.

I did leave the first restore attempt, which took place yesterday, running overnight, but this morning the apps were still not running, so I attempted a restore on a brand-new VM to rule things out.

Thanks again!

**Comment by titanous** [comment]
@lmars I think what's happening here is the scheduler is hitting the `AddJob` throttling on the host and then the backoff logic is kicking in and delaying job starts by 10s of minutes. We should avoid this by adding job start throttling to the scheduler. We should also turn down the backoff as mentioned on IRC the other day.

**Comment by titanous** [comment]
@nasali You may be able to temporarily work around this by passing something like `--max-job-concurrency=32` to `flynn-host daemon` in `/var/init/flynn-host.conf` before starting `flynn-host` and the backup restore process.

**Comment by nasali** [comment]
@titanous It looks like passing that explicit value for job concurrency did not work around the issue completely. The cluster now comes back up with the apps listed via the CLI, but it doesn't serve any of them successfully (Service Unavailable for all of them) and it doesn't accept any new apps:
```
$ flynn create
Created badgers-rejuvenate-trent
$ git push flynn master
remote: Service Unavailable
fatal: unable to access 'https://git.mydomain.com/badgers-rejuvenate-trent.git/': The requested URL returned error: 503
```
So I tried to see what was going on with the gitreceive process:
```
$ flynn -a gitreceive ps
ID                                    TYPE  STATE    CREATED       RELEASE
0bc9014c-8f91-433a-bb83-9cfda5686cd0  app   pending  15 hours ago  13b64e5d-e52e-437b-9186-ec4e981a2f9b
7197eedd-69d6-4a30-8618-31ca84e79894  app   pending  15 hours ago  13b64e5d-e52e-437b-9186-ec4e981a2f9b
$ flynn -a gitreceive kill 0bc9014c-8f91-433a-bb83-9cfda5686cd0
unknown_error: Something went wrong
$ flynn -a gitreceive kill 7197eedd-69d6-4a30-8618-31ca84e79894
unknown_error: Something went wrong
```
I then figured I should yank the app I just created:
```
$ flynn delete
Are you sure you want to delete the app "badgers-rejuvenate-trent"? (yes/no): y
dial tcp: lookup blobstore.discoverd: no such host
```

So I decided to not make it worse and ask here instead. Here's the [latest gist](https://gist.github.com/c54010c23bdfe51cb73681b0f06f5645 )

Thank you.

**Comment by titanous** [comment]
Understood. I'm looking into the best fix for this today.
