### ISSUE TITLE
Dashboard Not Found

### ISSUE THREAD

**Issue by wisesascha** [flynn/flynn#2649]
I am attempting to automate the install of Flynn, and after everything has installed successfully it claims that it can't find the dashboard. When I visit it on certain IPs it says that it can't find the dashboard.  Here's the logs from the server that had the bootstrap command run on it: https://gist.github.com/0c3bcdb183dc9933ae61a7f7a10ec824. If anyone has any idea what sort of error this could be it would help a lot.

**Comment by titanous** [comment]
What URL are you trying to visit the dashboard at?

**Comment by wisesascha** [comment]
http://dashboard.famoushat.intercept.site Says not found. While https://dashboard.famoushat.intercept.site says that it can't establish a secure connection

**Comment by titanous** [comment]
What does `flynn -a dashboard route` show?

**Comment by wisesascha** [comment]
```
~ $ flynn -a dashboard route
ROUTE                                     SERVICE        ID                                         STICKY  LEADER  PATH
https:dashboard.famoushat.intercept.site  dashboard-web  http/e4179315-5057-49a7-bedc-b0e023fd49bf  false   false   /
```

**Comment by titanous** [comment]
It looks like #1145. I'm looking closer at the logs.

**Comment by titanous** [comment]
Please gist the result of: `flynn-host log Flynn50588a695c1ynwq-95091892-3ace-42b8-b896-b53228aae983`

**Comment by wisesascha** [comment]
https://gist.github.com/wisesascha/ffb3e41f8155bb6c9948e2729b698bd4

**Comment by titanous** [comment]
It looks like the log is incomplete, please post the full output.

**Comment by wisesascha** [comment]
Sorry. My terminal truncated the output and I thought it was all uniform. Here is the full contents: https://gist.github.com/3abaac75bf0f3c6c038cb43e15765d7c

**Comment by titanous** [comment]
You hit a bug (which I will fix), but it was triggered by this:

> error binding to port (check if another service is listening on :3022): address already in use
