### ISSUE TITLE
In-place upgrade breaks discoverd on single node

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2651]
@bfontaine reports that running `flynn-host upgrade` on a single node ended up putting discoverd into an infinite loop logging:

``` text
Waiting for store to catchup, current: 1 target: 169`
```

Looking at the code, I don't believe the upgrade strategy works for single-node discoverd. Since it doesn't work for any of the other databases either, we should just refuse to allow a single node in-place upgrade.

**Comment by josephglanville** [comment]
Aye for now we probably should just disable it. That said when we put in the infrastructure to support data format upgrade (like moving to new version of PG) that will probably be usable for single-node upgrades.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
