### ISSUE TITLE
CPU spike takes down a node

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2660]
I'm seeing increasing instances of CPU starvation taking down a node. https://gist.github.com/4c38de78f8f253512542b1d72589bf73 is the syslog(?) from the dead host, exposed via the AWS console. https://gist.github.com/e1efccd956c111afb44b2c60cf027f76 and https://gist.github.com/dc182a0224fb1e08ef9fd5b9c71025d7 are the surviving two nodes. (This latest one corresponded with a build of the firebird-health app, in case that helps localize the problem.)

This is probably something about the CPU limits needing further tweaking.

**Comment by titanous** [comment]
Has this happened recently? Soft lockups should never happen and are typically indicative of kernel bugs.

**Comment by temujin9** [comment]
It seems to be happening rather regularly, of late. Let me know if there are additional things we can do to help diagnose this.

**Comment by titanous** [comment]
I'd be interested to see kernel backtraces from the lockups, typically they will be logged to the same serial console output that you posted.

**Comment by temujin9** [comment]
I've notified the team, and they'll be on watch for the next time this happens. Unfortunately, I think what you see in that first log is all that's available from a dead node by default. We may have to work out some method for extracting more salient information somewhere else on a continuing basis, so it's available afterward.

**Comment by temujin9** [comment]
Okay, I'm working up a solution to this. What files would you like a dying node to dump into a tarball on s3? I'm assuming `/var/log/syslog*` at a minimum, and suspect you'll want `/var/log/flynn` and maybe `/var/log/upstart/flynn-host.log*` too; let me know if I'm missing anything.

**Comment by titanous** [comment]
Yeah, that sounds good.

**Comment by titanous** [comment]
After poking around a bit in `/var/log`, I think `kern.log` and `dmesg` would also be useful, but I expect they will be mostly copied into the serial console log.

**Comment by temujin9** [comment]
That all tars down to about 60M on the example machine I'm checking: quite doable. I'll get that going tonight: thanks!

**Comment by temujin9** [comment]
Haven't seen this recently. Closing, until / unless it recurs.
