### ISSUE TITLE
Add deploy timeout management to CLI

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2662]
During otherwise successful builds of large projects on a contended cluster, we will occasionally hit:
```
-----> Creating release...
remote: Error deploying app release: timed out waiting for deployment completion
To https://git.qa-us-east-1.flynn.nexus.bazaarvoice.com/qa-seller-ratings-display.git
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.qa-us-east-1.flynn.nexus.bazaarvoice.com/qa-seller-ratings-display.git'
```

Release will often show up as complete later, though it will not always be switched to, so this feels like an artificial timeout which should maybe be dropped.

**Comment by temujin9** [comment]
@titanous This is increasingly blocking my developers, and they are complaining. Suggestions would be appreciated.

**Comment by titanous** [comment]
Looks like we should add a command the the CLI to manage this.

**Comment by thomasmodeneis** [comment]
Hi @titanous 
I'm also facing this deployment timeout quite often, my bundle has +/- 165MB and hangs about 5 times until I manage to do a clean deploy, is there any work around to increase this timeout ?
I've found in a old ticket this command, but I'm not sure if it will work:
`flynn -a controller pg psql -- -c 'UPDATE apps SET deploy_timeout = 120'`

120 is in ms ou seconds ?

Cheers.

**Comment by josephglanville** [comment]
@thomasmodeneis That command will still work. `deploy_timeout` is in seconds.

**Comment by thomasmodeneis** [comment]
@josephglanville , setting it to 600 seconds made the trick :D
Thank you for the support.
