### ISSUE TITLE
Install fail:xdg-open: no method available for opening 'http://localhost:40202'

### ISSUE THREAD

**Issue by closerZhang** [flynn/flynn#2663]
Running CentOS 7 without gui when running flynn install then it block and print this text
flynn install
Open http://localhost:40202 in your browser to continue.
xdg-open: no method available for opening 'http://localhost:40202'

**Comment by titanous** [comment]
The Flynn installer is a web application (available at the port provided). You can also follow the manual install instructions if you do not want to use the web-based installer: https://flynn.io/docs/installation/manual
