### ISSUE TITLE
Refusing to update checked out branch

### ISSUE THREAD

**Issue by Altneu** [flynn/flynn#2671]
When I try to push to the remote git repo on my flynn cluster Git tells me it won't update the checked out branch.  I tried to create a bare repo and push to that but it didn't seem to kick off the build and release process.  I also tried to ignore the error (receive.denyCurrentBranch ignore), which then allowed the push but still didn't initiate a release.  

What am I missing?  How can I initiate a release by pushing to the git repo on the flynn cluster?

**Comment by titanous** [comment]
This sounds like #2039, can you confirm if that is the problem?

**Comment by Altneu** [comment]
I did run into that issue also, but I started over using only master and it works if I push from the repo on the Flynn node but not from a remote machine.

**Comment by Altneu** [comment]
Just to clarify the push from a remote machine is successful, but the build and release process never seems to happen. 

$ git remote -v
origin  https://github.com/xxx/xxxx (fetch)
origin  https://github.com/xxx/xxxx (push)
staging1        root@git.xxxx.xxxx.com:vcaro-api (fetch)
staging1        root@git.xxxx.xxxx.com:vcaro-api (push)


$ git push staging1 master
Counting objects: 21, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 534 bytes | 0 bytes/s, done.
Total 6 (delta 4), reused 0 (delta 0)
To root@xxx.xxx.xxx.com:vcaro-api
   9bd6931..23d99d9  master -> master

**Comment by titanous** [comment]
It's unlikely that the `staging1` remote that you are using is Flynn, we use HTTPS for transport, not SSH.

**Comment by Altneu** [comment]
I changed it manually.  When I was using HTTPS it kept prompting me for authentication.

**Comment by Altneu** [comment]
I'm guess that's the issue.  It only works over HTTPS?  If so, how do I get it to use my keys?  It worked over SSH but not HTTPS. Also I have installed the cert at least a dozen times and I still get a cert error, I had to tell git not to verify certs.

**Comment by titanous** [comment]
You are pushing over SSH to the /root/vcaro-api on the server, not to the Flynn git receiver. Try re-adding cluster with `flynn cluster add` and push to the HTTPS remote. If that still prompts for authentication, run it with these environment variables and gist the output: 

```text
GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push -v flynn master
```

**Comment by Altneu** [comment]
Remove the cluster and re-add it?  Or force the add?

**Comment by titanous** [comment]
Force-add is fine.

**Comment by Altneu** [comment]
> git push -v staging1 master
trace: built-in: git 'push' '-v' 'staging1' 'master'
trace: run_command: 'git-remote-https' 'staging1' 'https://git.stagingapi.vcaro.com/vcaro-api'
Pushing to https://git.stagingapi.vcaro.com/vcar*o-api
 Couldn't find host git.stagingapi.vcaro.com in the _netrc file; using defaults
* Adding handle: conn: 0xb5c0f8
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0xb5c0f8) send_pipe: 1, recv_pipe: 0
* About to connect() to git.stagingapi.vcaro.com port 443 (#0)
*   Trying 45.55.149.39...
* Connected to git.stagingapi.vcaro.com (45.55.149.39) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Program Files (x86)\Git/bin/curl-ca-bundle.crt
  CApath: none
* SSL connection using AES128-SHA
* Server certificate:
*        subject: O=Flynn; CN=stagingapi.vcaro.com
*        start date: 2016-04-05 20:03:00 GMT
*        expire date: 2021-04-04 20:03:00 GMT
*        issuer: O=Flynn; OU=Flynn Ephemeral CA
*        SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /vcaro-api/info/refs?service=git-receive-pack HTTP/1.1
User-Agent: git/1.9.5.msysgit.0
Host: git.stagingapi.vcaro.com
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 401 Unauthorized
< Content-Length: 24
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 07 Apr 2016 21:09:37 GMT
< Www-Authenticate: Basic
<
* Connection #0 to host git.stagingapi.vcaro.com left intact
Username for 'https://git.stagingapi.vcaro.com':

**Comment by Altneu** [comment]
[https://gist.github.com/Altneu/c49a122e698d1262c4f8b04b659d0037](url)

The force add didn't resolve the authentication issue.

**Comment by titanous** [comment]
Hmm, is this on Windows? There are several configuration items that we inject into the config that are required for authentication: https://github.com/flynn/flynn/blob/master/cli/config/git.go

Please gist the output of `git config --list --global`

**Comment by Altneu** [comment]
`>git config --list --global
trace: built-in: git 'config' '--list' '--global'
user.name=zaltneu
user.email=Altneu@users.noreply.github.com
http.https://git.vjqy.flynnhub.com.sslcainfo=C:\Users\Zach\AppData\Roaming\flynn\ca-certs\flynn-1459439170.pem
credential.https://git.vjqy.flynnhub.com.helper=C:/Users/Zach/AppData/Roaming/flynn/bin/flynn.exe git-credentials
`

**Comment by titanous** [comment]
Okay, what version of Windows and git are you using and how did you install git?

**Comment by Altneu** [comment]
I had run the flynn installer locally before I set it up on DO.  Those entries are probably from that.  How would I get the correct local config entries set for a remote repo?

**Comment by Altneu** [comment]
Windows 10.

>git --version
trace: built-in: git 'version'
git version 1.9.5.msysgit.0

**Comment by titanous** [comment]
`flynn cluster add` is supposed to add those config entries. You could manually add them too, but I'm more interested in why it's failing silently. I assume you are not passing `--no-git` to `flynn cluster add` and no errors were printed?

**Comment by Altneu** [comment]
You assume correctly.  Remember though, I am trying to push from my local to a remote flynn cluster. Everything works on the cluster itself.  I just need developers to be able to push to staging from their local environments without having to SSH into the servers - that's what is failing.

**Comment by Altneu** [comment]
Or did you want me to run flynn cluster add on my local?  When you asked, I ran it on the server.  I may have misunderstood.

**Comment by titanous** [comment]
Yes. `flynn cluster add` configures the local flynn and git clients.

**Comment by Altneu** [comment]
Ah it all makes sense now.  I was wondering how you expected the HTTPS push to work remotely.  I ran cluster add locally and it works perfectly.  That definitely wasn't clear in the manual install docs.  But I should have guessed it. 

Thanks for the help.

**Comment by titanous** [comment]
Thanks, we'll improve the docs.
