### ISSUE TITLE
Application and node flappiness on restored cluster

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2681]
Monitoring on applications and port 1113 reported lots of flappiness. Root cause isn't immediately clear.

https://bazaarvoice.box.com/s/vou182y1ay7vogw8pvn6fkgc67uy4mu0

**Comment by titanous** [comment]
Was one of the nodes replaced? One of the discoverd started as a proxy.

```text
2016/04/10 05:36:47 checking for existing discoverd process at http://10.100.38.215:1111
advertised address not in peer set, joining as proxy
2016/04/10 05:36:47 failed to contact existing discoverd server, starting up without takeover
2016/04/10 05:36:47 discoverd listening for HTTP on :1111
```

The only other known explanation for that is that the `--peer-ips` or `--min-hosts` flags were specified incorrectly when booting the cluster.

**Comment by temujin9** [comment]
If the node was replaced, it happened almost immediately; this was intended as a replacement for a broken cluster, and fared little better than what it replaced. Unfortunately, I don't believe I can retrieve the autoscaling history of a deleted cluster.

**Comment by temujin9** [comment]
If you're comfortable with your diagnosis that node replacement happened here, then feel free to close this ticket and treat it as another plea for #2398 instead.

**Comment by titanous** [comment]
Sure. That change is in progress at #2682.

**Comment by temujin9** [comment]
Ah, thanks. Subscribed to that.
