### ISSUE TITLE
Router fd exhaustion

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2684]
It looks like the router keeps client connections alive for way too long:

```text
goroutine 68281 [IO wait, 9569 minutes]:
net.(*pollDesc).Wait(0xc208914f40, 0x72, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208914f40, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208914ee0, 0xc209dd2000, 0x1000, 0x1000, 0x0, 0x7f07ba754bb0, 0xc20877eff8)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20a0734b8, 0xc209dd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc209a0ba88, 0xc209dd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20942efc0, 0xc209dd2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc209d3e000)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc209d3e000, 0xc20803210a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc209d3e000, 0x0, 0x0, 0x0, 0xc207ea2600, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2095d9f20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2095d9f20, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc209d3e000, 0xc208c7f6c0, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc209a0ba40, 0x0, 0x0, 0x0)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc209a0ba40)
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/tmp/tmp.AaXXtTCrZT/src/github.com/flynn/flynn/util/_toolchain/go/src/net/http/server.go:1751 +0x35e
```

@quentez reports that a cluster that they were running ran out of fds after receiving a lot of traffic.

[Goroutine trace](https://github.com/flynn/flynn/files/215884/flynn-router.log.zip)

**Comment by titanous** [comment]
It looks like setting a `ReadTimeout` on the HTTP server should fix this.

**Comment by titanous** [comment]
Though that will break other things, the read timeout isn't just used for idle connections, so it will kill long-running uploads. We may need to implement our own state tracking to do keep-alive timeouts.

**Comment by titanous** [comment]
Also, I have a suspicion that this issue is specific to the wacky Azure networking setup.

**Comment by quentez** [comment]
Let me know if there's anything I can do on my side to help diagnose that further.

**Comment by titanous** [comment]
I have been unable to replicate this on Azure or AWS with a backend server written in Go.

@quentez Can you describe the app that was deployed at the time and how you set up the cluster on Azure?

**Comment by swaits** [comment]
Glad to help with any diagnosis, debugging, etc. on my end too. Might be able to `seige` my install to repro it (after hours).

**Comment by quentez** [comment]
The app that was deployed was a 1-line PHP app. The source can be found [here](https://github.com/frontapp/goodcopy).

**Comment by swaits** [comment]
@titanous my apps are all ruby based, running either puma or unicorn. happy to share configs or even let you shell in if you want.

could be something with router <=> nginx though, since the app servers @quentez and I are using are vastly different.

**Comment by titanous** [comment]
The nightly release has some changes that may fix this, if either of you can still reproduce the issue can you test out the new version?

**Comment by titanous** [comment]
@swaits The AWS installer now deploys the new version. Let me know if you get a chance to try it.

**Comment by swaits** [comment]
@titanous FYI I tried this today. Installer hung on "reloading" just after it had started all the various system apps. LMK if you want me to grab a debug info dump from any (or all?) of the hosts, please.

**Comment by titanous** [comment]
Yeah, please grab the logs from a host,

**Comment by swaits** [comment]
@titanous logs and other info posted in new issue https://github.com/flynn/flynn/issues/3017

**Comment by titanous** [comment]
Good news everybody! I believe I have identified the issue, and it's not completely Flynn's fault, but we can fix it in Flynn. See #3079 for details on the details and the long-term fix.

As a short-term fix, you can reduce the `net.netfilter.nf_conntrack_tcp_timeout_established` tuneable on your servers to get rid of the "leak".
