### ISSUE TITLE
Git push fails with cannot remove dir error

### ISSUE THREAD

**Issue by tjboring** [flynn/flynn#2685]
I'm attempting to push a rails app to a freshly built Flynn cluster, but the git push command is failing. 

Command I'm using:
> git push flynn development:master

Error:
----> Building contract...
-----> Deleting 2 files matching .slugignore patterns.
remote: rm: cannot remove '/tmp/build/spec': Is a directory
remote: rm: cannot remove '/tmp/build/blackbox': Is a directory
remote: Build failed: exec: job exited with status 1

**Comment by titanous** [comment]
@josephglanville It looks like you are working on this?

**Comment by tjboring** [comment]
For now, I've been working around this by simply removing the .slugignore file from my repo before pushing my app(s) to the Flynn cluster.
