### ISSUE TITLE
All user applications are deployed to the same node

### ISSUE THREAD

**Issue by liuyang1204** [flynn/flynn#2686]
Hey, I found a strange behavior that all my applications pushed to Flynn are deployed to the same node.

This makes that node extremely slow. And I couldn't deploy more apps now (Meeting timeout error).

However, the Flynn components like `discoverd`, `controller`, `dashboard` are deployed in different nodes. 

How could I trace this problem, Anyone can help me?

**Comment by liuyang1204** [comment]
It is a 3-node cluster and the other 2 nodes have plenty resources

**Comment by liuyang1204** [comment]
I have killed all controller processes (Flynn will restart them), but still not solved

**Comment by josephglanville** [comment]
@liuyang1204 placement decisions are made by the scheduler. The algorithm used for scheduling only simply tries to spread each instance of the job over as many hosts as possible, so if that is not happening then there is likely something wrong somewhere.

Can you post the debug info from your cluster with `flynn-host collect-debug-info`, we will be able to use this to help determine what isn't working right.

**Comment by liuyang1204** [comment]
@josephglanville Thank you very much for help!

Here is the result of the command:

https://gist.github.com/anonymous/0db42fee705ce29387801a1064926e3f

**Comment by josephglanville** [comment]
@liuyang1204 can you also paste the output of `flynn scale -a` and `flynn ps -a`  for your application?

**Comment by liuyang1204** [comment]
Here is the output of the application `holiday`
```
$ flynn -a holiday scale
web=1

$ flynn -a holiday ps
ID                                         TYPE  STATE  CREATED      RELEASE
stm1-bc5ed13f-3bc3-49d0-b5d1-086ef2637dbc  web   up     4 weeks ago  49f335cf-53fb-4af7-8c2b-12aed98be908

```

I've tried kill the process listed in "ps", and Flynn started another process. But all processes are in the node `stm1`

**Comment by liuyang1204** [comment]
@josephglanville Is this what you mean?

**Comment by josephglanville** [comment]
Oh I misread what you were saying. :(

I thought you were seeing that your applications that had scale > 1 were all ending up on the same node.

However what you really meant was you had multiple applications with scale=1 and they are all on the same node.

Unfortunately the scheduler makes no attempt to balance the nodes right now.
Infact I think the default behavior will to always be to launch the first process of any application on the first node as placement is deterministic right now. @lmars does that sound correct?

In that case this should probably be considered as a feature request for resource based balancing or similar, which is planned (and some prereqs have been completely) but isn't yet done.

**Comment by liuyang1204** [comment]
> However what you really meant was you had multiple applications with scale=1 and they are all on the same node.

Exactly!

Oh it is sad that resource based balancing isn't yet done.

Could you provide some workarounds for this? 

E.x. 
1. Is it possible to change the placement decision to "random node"?
2. Is it possible to specify a fixed node to deploy by some configuration on an application?

**Comment by josephglanville** [comment]
@liuyang1204 You could use tags to force placement for now, that would get around the problem.
You can assign tags to hosts and then assign tags using the `flynn scale` command, jobs will only start on hosts that match all the tags for that job.

**Comment by lmars** [comment]
@josephglanville is correct, the scheduler only balances individual process types across the cluster, we plan to add resource based scheduling soon.

To expand on the proposed tag workaround, you can tag a host by running the following on the host itself:

```
$ flynn-host tags set HOSTID holiday=true
```

And then when you scale your `holiday` app, you can make sure the jobs go on the host tagged `holiday=true` with:

```
$ flynn -a holiday scale web=1,holiday=true
```

**Comment by liuyang1204** [comment]
Thanks a lot! I have successfully used tags for scheduling.

Looking forward to resource based scheduling!
