### ISSUE TITLE
dashboard: Support Emoji in commit messages

### ISSUE THREAD

**Issue by Snugug** [flynn/flynn#2692]
I use a lot of emoji in commit messages. It'd be great if Flynn supported the [emoji set](http://www.emoji-cheat-sheet.com/) that's rapidly becoming a standard (and GitHub uses)

**Comment by jvatic** [comment]
Can you clarify a bit what change you would like to see? I'm guessing it would be to see emoji rendered for commit messages in the dashboard app.

**Comment by Snugug** [comment]
Sorry, yup, exactly that
