### ISSUE TITLE
Flynn leaves ZFS mounts behind

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#2693]
12:37 < rikurr> lmars: are you there? I think Docker apps that fail to deploy leave ZFS mounts behind.
12:42 < rikurr> specifically: I had an invalid config for the Docker app and caused the unbind_mounts to fail
12:42 < rikurr> err="unknown port proto \"http\""
12:42 < rikurr> now=2016-04-13T17:06:09+0000 backend=libvirt-lxc at=finish fn=unbind_mounts
12:42 < rikurr> ERRO[143573] Removing active id tmp-xxx
12:44 < rikurr> the apps are all in failed state

**Comment by titanous** [comment]
There are a few different things going on here. We don't delete ZFS volumes so that data doesn't get lost. `unbind_mounts` didn't error here, but sometimes does and it's typically not a big deal because it's a catch-all. The last error is #38.
