### ISSUE TITLE
zpool Device or resource busy

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2695]
OK so I'm just setting up a new cluster and seen the new documentation regarding storage.

but when I try `zpool create flynn-default /dev/sda2` i get an error of 

```
cannot open '/dev/sda2': Device or resource busy
cannot create 'flynn-default': one or more vdevs refer to the same device, or one of
the devices is part of an active md or lvm device
```
the output of `lsblk` is
```
NAME                 MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                    8:0    0    40G  0 disk 
|-sda1                 8:1    0   487M  0 part /boot
`-sda2                 8:2    0  39.5G  0 part 
  |-vg00-lv00 (dm-0) 252:0    0   1.9G  0 lvm  [SWAP]
  `-vg00-lv01 (dm-1) 252:1    0  37.6G  0 lvm  /
sr0                   11:0    1  1024M  0 rom  
```

Any ideas why this would be?

**Comment by titanous** [comment]
It looks like sda2 has other data on it. ZFS wants a whole device or partition, check their docs for specifics.

**Comment by dottodot** [comment]
So the only way I can think this is possible to get around is to create a empty partition which as far as I tell isn't possible on most cloud servers.

**Comment by lmars** [comment]
@dottodot I would recommend attaching a new device for the zpool (e.g. with AWS, attach an empty EBS volume).

**Comment by dottodot** [comment]
Ok so I'm using 1and1 cloud and I can attached extra storage and this can be shared across all servers. Is this ok to do or should I be attaching a separate one to each server?

**Comment by lmars** [comment]
@dottodot I would suggest a device per server.
