### ISSUE TITLE
installing flynn on vps fails cause  "apt-get install linux-headers-`uname -r` " fails

### ISSUE THREAD

**Issue by jojobo** [flynn/flynn#2696]
Tried to install flynn on scaleway.com vps, and it fails cause sudo apt-get install linux-headers-`uname -r` returns "package not found" error.
On some other host company, it needed ubuntu-zfs to be installed before, otherwise the installation would fail too.
Yes these are host specific issues, but perhaps they can be addressed.

**Comment by lmars** [comment]
@jojobo are you using a custom kernel? We recommend using a stock Ubuntu kernel if possible.

**Comment by jojobo** [comment]
Just fresh ubuntu 14.04 provided by vps host.
Same on vultr.com.
Thanks

**Comment by lmars** [comment]
@jojobo what is the output of `uname -a` on your servers?

**Comment by jojobo** [comment]
4.4.4-std-3

**Comment by jojobo** [comment]
Running `apt-get install linux-headers-`uname -r` ` obviously fails when is manually run too.
Just wondering if not forcing this step and leaving vps's current installed linux headers, would work.

**Comment by lmars** [comment]
@jojobo ok so it looks like you are using a custom kernel.

Flynn depends on the `ubuntu-zfs` package, which requires the headers for you kernel to be present. You can try running `sudo apt-get install ubuntu-zfs` to see if it succeeds, and if it does then you can just remove the install of the kernel headers (i.e. [this line](https://github.com/flynn/flynn/blob/v20160412.0/script/install-flynn.tmpl#L100)) from the Flynn install script before running it.

You may also find that [this package](https://github.com/flynn/flynn/blob/v20160412.0/script/install-flynn.tmpl#L110) also fails to install if you do not have AUFS support in your kernel. If this is the case, you will need to contact your cloud server provider to ask them if they either provide a kernel with AUFS support, or provide an installable Ubuntu package to add AUFS support.

**Comment by lmars** [comment]
> I cannot find any docs on adding a node to a running cluster. any help pls?

https://flynn.io/docs/operating#adding-hosts

**Comment by jojobo** [comment]
sudo apt-get install ubuntu-zfs fails.
Tried also
sudo add-apt-repository ppa:zfs-native/stable
sudo apt-get install ubuntu-zfs 
And it installs with errors 
`configure: error:
        *** Please make sure the kmod spl devel <kernel> package for your
        *** distribution is installed then try again.  If that fails you
        *** can specify the location of the spl objects with the
        *** '--with-spl-obj=PATH' option.
Error! Bad return status for module build on kernel: * (x86_64)
Consult /var/lib/dkms/zfs/0.6.5.6/build/make.log for more information.
`
modprobe zfs still returns module zfs not found.

Thanks for the docs link

**Comment by titanous** [comment]
If you can't install a mainline kernel distributed with Ubuntu 14.04, Flynn will not operate correctly.

**Comment by lmars** [comment]
For anyone landing here because they are trying to run Flynn on Scaleway, see [this comment](https://github.com/flynn/flynn/issues/2709#issuecomment-213594407) about managing the kernel for Scaleway servers.

**Comment by alessiodionisi** [comment]
Hello,
I successfully installed Flynn on a C2L instance with Ubuntu 16.04.
Build was really fast (10 minutes).

- Install prequisites: `apt-get install build-essential libssl-dev`
- Run this script: https://github.com/scaleway/kernel-tools#how-to-build-a-custom-kernel-module
- Now install and build zfs: `apt-get install zfsutils-linux`
- Enjoy: `modprobe zfs`
- Download the Flynn install script: https://dl.flynn.io/install-flynn
- Comment from line 172 to 179 (where Flynn try to install `aufs-tools`)
- Run the installer

**Comment by batuhan** [comment]
Hey @alessiodionisi, just tried following your steps but I can't see `aufs-tools` in the installer script at all. Maybe they've changed something?

**Comment by alessiodionisi** [comment]
Hi @batuhan, with the latest version you don't need to comment the aufs-tools, Flynn don't use it anymore ;)

**Comment by batuhan** [comment]
Thanks for the info @alessiodionisi,
 
I'm getting `===> 19:47:20.798 ERROR: failed to run "modprobe zfs", exit status 1`.

Do you have a working solution as fellow Scaleway customer? :)

If not I'll open another issue with my error  either here or on Scaleway's related repos.

Thanks in advance :)
