### ISSUE TITLE
wait mariadb-wait error

### ISSUE THREAD

**Issue by artgrosvil** [flynn/flynn#2697]
When installing CLUSTER_DOMAIN wait mariadb-wait does not respond.

Error: `wait mariadb-wait error: bootstrap: timed out waiting for http://mariadb-api.discoverd/ping, last response 500`

**Comment by titanous** [comment]
Please post a link to the logs from `sudo flynn-host collect-debug-info`.

**Comment by titanous** [comment]
Please re-open this issue when you have the logs.
