### ISSUE TITLE
Java application: How to specify maven properties for building?

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2700]
Hi,
we build our wars with some parameters as configuration instead of using environment variables. This is legacy and can't easily be changed.

```bash
mvn  -DdatabaseUsername="asdasd" -DdatabaseUrl="jdbc:mysql://foo.bar:3306/blubb" \
-DdatabasePassword="asd123" clean war:war install
```

I already tried to set the environment variable JAVA_TOOL_OPTIONS upfront, but that didn't do the trick.

Is there a way to define them and adjust the Maven call?

**Comment by lmars** [comment]
@philiplb here is the part of the Java buildpack which runs the `mvn` command:

https://github.com/heroku/heroku-buildpack-java/blob/366800fc18c78617597c4383fb1b5489f1a2a161/bin/compile#L49-L58

So it looks like you can set `MAVEN_CUSTOM_OPTS` to the values that you need (via `flynn env set MAVEN_CUSTOM_OPTS="..."`).

**Comment by philiplb** [comment]
That works well, thank you. :)
Good find! I googled some time without result.
