### ISSUE TITLE
Timeout on deploying a Java application

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2704]
Hi,
sometimes, when I push a release of a Java application, I get a timeout due to the application needing a bit more time to boot than 20s:

> =====> Waiting for web job to start...
> remote: Timed out waiting for job events. Waited 20 seconds.
> remote: expected: map[web:map[up:1]]
> remote: actual: map[web:map[pending:1 starting:1]]
> To https://git.flynn.abc.com/MyApp.git
 > ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.flynn.abc.com/MyApp.git'

It is a Spring web application using the jetty runner.

The application is just fine a moment later so this is a minor issue. But it could confuse our CI.

**Comment by titanous** [comment]
This will be fixed by #2662.

**Comment by titanous** [comment]
This was actually fixed by #2889.
