### ISSUE TITLE
"Service Unavailable" flappiness in otherwise healthy applications

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2706]
Monitoring is reporting intermittent "HTTP/1.1 503 Service Unavailable" responses on otherwise healthy applications (terminus, flynn-usage-example). This appears to have been preceded by brief core process outages (scheduler and router) on one of the nodes (10.100.39.192).

https://gist.github.com/6d44327ae5b9458b05defaba1d95f71f and https://gist.github.com/83d8a70f3dc85f0aaaf39700cb91f00b are the debug info I could collect: the third hit the 405 described in #2555.

**Comment by temujin9** [comment]
Additionally, encountering similar issues against the controller itself:
```
$ flynn -c qa-us-east-1 apps
```
either returns
```
GET https://controller.flynn-qa-us-east-1.nexus.bazaarvoice.com/apps: httpclient: raw req: unexpected status 503
```
or hangs.

**Comment by titanous** [comment]
This appears to be #2638.
