### ISSUE TITLE
Better workflow for multi-host deployments

### ISSUE THREAD

**Issue by jojobo** [flynn/flynn#2707]
I love how super simple flynn is to deploy on a single host, and I wish multi-host deployments could become as easy, which is still confusing. Here are my two cents:
1. Instead of round-robin (which is not immune to failovers etc), a load-balancer container can be used to distribute traffic to hosts, and this container will have to auto-update ips in case new nodes are added, removed. Rancher which is another docker-based paas, has taken this route, and it makes quite a difference.
2. Docs on multi-host deployments are still confusing. Basically, "using flynn" section is only a single node setup tutorial ( https://flynn.io/docs ), while "operating flynn" section goes into multi-host deployments ( https://flynn.io/docs/operating ) . This "operating flynn" section assumes you're already familiar with flynn-host init --init-discovery  which is explained in the "manual installation" section, which is not true, because the "cloud installer" section is the preferred installation way, as it is right on top and the automatic way. In few words, if you want a multi host installation you need to go through the "manual installation" route.
3. Adding nodes, flynn-init etc, would be much better if they were part of the dashboard.

**Comment by titanous** [comment]
1. I'm not sure I understand point 1. We run a router process on each host which load balances traffic across all backend instances no matter what host they are on. There should be no fault tolerance issues.

2. Multi-host vs single host should be irrelevant to the Using Flynn section, is there something specific there that is single-host?

We'll be improving the installatoin docs, and managing hosts in the cluster from the dashboard is on our roadmap.

**Comment by jvatic** [comment]
>  if you want a multi host installation you need to go through the "manual installation" route.

A multi-host cluster can easily be installed via `flynn install` by incrementing the "Number of instances".

#2687 will lay the groundwork for managing hosts from the dashboard.

**Comment by jojobo** [comment]
1. Round robin setup (as docs suggest) still needs DNS A records to be updated any time that new nodes are added. While a load-balancer in front of your hosts would take care of this.
2. Well, I'd expect that "using flynn" section would also introduce the flynn-host init commands to work with a multi-host setup. Instead, these commands are introduced in "manual installation" section, which is presented as an optional installation way ("If you want to manually install Flynn, follow the manual installation guide")
3. Great to hear that !

**Comment by titanous** [comment]
1. Yes, updating DNS is required if you remove nodes. If you'd like to route some traffic to added nodes you should update the DNS as well. Each node acts as a load balancer. You could just have one in DNS if you wanted, it just wouldn't be fault tolerant.
1. Using Flynn is about *using* Flynn, not installation/setup. We will be reworking the docs soon, so any specific feedback you have on making them clearer would be helpful.

**Comment by jojobo** [comment]
@jvatic  Just to be clear, I meant that you had to read that part of docs first to understand what you needed to do. Now it's also possible to add nodes to a running cluster (which was not possible before), so no matter what installation route you choose, you can get a multi host setup.

**Comment by jojobo** [comment]
@titanous so If I understand right, you could have a single node referenced in DNS records, and that node would load balance traffic to containers accross 3 nodes ?  If so, does that mean that you just need 3 dns records even though you have like 10 containers and continue to add new ones?

2. Well it depends on how you look at it. I think that adding/removing nodes can be considered part of using flynn, but i agree eigher way. The important thing is that when you go into the multi-host setup, you're already familiar with flynn-host init commands.

**Comment by titanous** [comment]
> If I understand right, you could have a single node referenced in DNS records, and that node would load balance traffic to containers accross 3 nodes?

Yes.

>  If so, does that mean that you just need 3 dns records even though you have like 10 containers and continue to add new ones?

The number of containers is not relevant, only the number of hosts. There is a 1:1 mapping of routers to hosts, each router handles traffic for all defined routes.

**Comment by jojobo** [comment]
@titanous I meant hosts, sorry.
