### ISSUE TITLE
Nodes ran out of disk space

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2708]
Hi,

my nodes just died hard by running out of disk space. The hdd itself was very small with 32GB. I know that the ZFS file systems won't take more than 70% of the partition. Theory: The operating system itself plus Flynn already took more than 30% of space.

**Comment by titanous** [comment]
I'm not sure that this is a bug in Flynn. We have updated docs on configuring the ZFS volume on a separate disk: https://flynn.io/docs/operating#storage

Is there something we could have done in Flynn to have prevented this situation?

**Comment by philiplb** [comment]
Not sure. :)
Maybe setting the volume file to 70% of the free space instead of the whole disk?

**Comment by titanous** [comment]
I think we've solved most of the disk space issues, please let me know if you encounter anything else.
