### ISSUE TITLE
Installing flynn on a docker environment, instead of ubuntu to prevent vps compatibility issues.

### ISSUE THREAD

**Issue by jojobo** [flynn/flynn#2709]
I had many issues installing flynn on some hosts, mainly because of zfs and aufs. So it should be better to have an optional installation route through docker, since all vps are supporting docker.
Any thoughts?

**Comment by titanous** [comment]
If your VPS provider doesn't give you control over the kernel, this is typically a sign that the you don't have enough control over the VM. I'd suggest finding better hosting providers, there is nothing we can do about this without completely changing core elements of Flynn.

**Comment by jojobo** [comment]
Thanks for prompt reply. Btw, scaleway.com is gaining a lot of momentum, some say is better than digitalocean, but flynn is impossible to install there.

**Comment by lmars** [comment]
@jojobo it seems Scaleway give you some flexibility to boot a variety of kernels (see [here](https://blog.scaleway.com/2015/05/22/scaleway-bootscript-simple-kernel-management-for-your-c1-server/)) so you should be able to boot with a mainline kernel. I would suggest contacting their support to ask for instructions on doing this if it is not obvious from the documentation.

**Comment by moul** [comment]
Hi everyone, I'm from the Scaleway team, I will try to help @jojobo to get flynn running on our server

As you closed this issue, we will continue the discussion here: https://github.com/scaleway/kernel-tools/issues/257

Cheers
