### ISSUE TITLE
App in a funny state after adding a SSL route

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2710]
Hi,
I just tried to add a SSL route to my app via
```bash
flynn route add http -c cert -k key myapp.foo.bar
```

Before, I concatenated the CA chain and the actual certificate to the file "cert" as there doesn't seem to be an option to provide it properly. The certificate itself is a wildcard one if that matters.
Now I have some problems:
- No domains (routes) show up in the dashboard for this app anymore
- No domains (routes) show up in the dashboard for all other apps anymore
- Despite not having routes anymore visually, the other apps are still reachable
- When I try to remove the just added route, I get this:

> DELETE https://controller.flynn.xyz.com/apps/MyApp/routes/http/dec5efe8-effe-4a59-9e83-da0831389986: httpclient: raw req: unexpected status 503

- When I try to delete the app, I get a timeout

Here would be the debug info:
https://www.philiplb.de/misc/2016-04-19_1755_flynn-host-debug.tar.gz

**Comment by titanous** [comment]
The error is:

```text
crypto/tls: private key does not match public key
```

We have planned work to expose this error message to the client #2442.

You can use these commands to check that the key and the certificate match:

```text
openssl rsa -noout -modulus -in cert-key.pem | openssl sha1
openssl x509 -noout -modulus -in cert.pem | openssl sha1
```

**Comment by titanous** [comment]
Fixing the sync error may require a bit of fiddling with the database using `flynn -a router pg psql` (I'd suggest just deleting the broken route)

**Comment by philiplb** [comment]
Alright, thanks. Have to find out now why the key and cert don't match. :)

Ok, I tried to delete the row via
```SQL
DELETE FROM http_routes WHERE id='dec5efe8-effe-4a59-9e83-da0831389986';
```

I took the id displayed via
```SQL
SELECT id, domain FROM http_routes;
```

But some PL/pgSQL kicks in?

> ERROR:  record "new" is not assigned yet
> DETAIL:  The tuple structure of a not-yet-assigned record is indeterminate.
> CONTEXT:  PL/pgSQL function check_http_route_update() line 8 at IF

**Comment by titanous** [comment]
Try:

```sql
UPDATE http_routes SET deleted_at = now() WHERE id = 'dec5efe8-effe-4a59-9e83-da0831389986';
```

**Comment by philiplb** [comment]
Thanks.
That query worked but I'm still experiencing the symptoms described above.

**Comment by titanous** [comment]
Okay, you may need to restart each router process.

**Comment by philiplb** [comment]
Killing all router processes listed by
```bash
flynn-host ps | grep router
```

via
```bash
flynn -a router kill <routerProcessId>
```

did the trick. Now the deletion try from hours ago worked and the app is gone. :)
Now I'll redeploy with correct certificates.
There might be a nicer way to recover from this in future?

Thanks for your fast and helpfull responses. :)
