### ISSUE TITLE
Will using A record for own domain cause any issues

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2711]
There are all sort of warnings about using CNAME for a root level domain, therefore is it OK to setup A records for each of the ip addresses in the cluster and are there any downsides to doing this?

**Comment by titanous** [comment]
Yes, there are no issues with doing that, we recommend it in the docs.

**Comment by gregorym** [comment]
Can you share the link to the doc? I couldn't find it.

**Comment by josephglanville** [comment]
You will find docs regarding DNS entires required in the Bootstrap section of the Manual installation page: https://flynn.io/docs/installation/manual#bootstrap-flynn
