### ISSUE TITLE
Create tool to load env vars from file

### ISSUE THREAD

**Issue by tjboring** [flynn/flynn#2712]
We're in the process of piloting an app that is currently running on Heroku. It would be nice if we could do something like this:

// export vars from heroku
> heroku config -s -a $app > /tmp/app.config

The '-s' option export the vars in shell format, e.g. ("$var=$val").

// import vars to flynn
> flynn env -i /tmp/app.config

Where -i indicates that env vars are to be imported from the file '/tmp/app.config'. 

The file format could be one var per line:
VAR1="foo"
VAR2="bar"
VAR3="baz"
....

**Comment by titanous** [comment]
Does this work?

```text
flynn env set $(cat app.config)
```

**Comment by tjboring** [comment]
$ flynn env set $(cat ./dev-config.txt)
usage: flynn env [-t <proc>]
       flynn env set [-t <proc>] <var>=<val>...
       flynn env unset [-t <proc>] <var>...
       flynn env get [-t <proc>] <var>

**Comment by tjboring** [comment]
wait...i think i see the problem...

**Comment by tjboring** [comment]
But this does work:

for i in $(cat ./dev-config.txt)
do
  flynn -a $app env set $i
done

Of course, it's now creating a new release per env variable. :(

**Comment by titanous** [comment]
Hmm, I wonder if that's just a ZFS thing.

**Comment by titanous** [comment]
The same command I proposed worked in bash as well, were you unable to get it to work?

**Comment by tjboring** [comment]
Hmm, I'm using bash on OS X (el capitan). Using the for loop worked for me.

**Comment by lmars** [comment]
`flynn env set $(cat env.sh)` works for me with bash on both OSX and Linux, perhaps there is something in your file which breaks the CLI? In any case, I don't think we need a flag to handle parsing a shell file.

**Comment by thomasmodeneis** [comment]
@lmars I think this should be better documented on the https://flynn.io/docs/cli#env
