### ISSUE TITLE
How to add a TLS route with a certificate chain?

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2713]
Hi,

I'm running into the problem that I need to create an HTTPS route including the certificate chain.
I tried to just concatenate the chain (first entry) and certificate (second entry) and gave the resulting file to "flynn route add -c" including the correct private key.
But that try either ends up in #2710 (second time now) or the route just doesn't work.
If I just add the certificate with the key, the route works, but SSLLabs complains about the missing chain and I'm not sure if all clients (mostly random iOS and Android versions) can handle that well.
Is there any way currently to include the chain into the route?

**Comment by titanous** [comment]
The leaf certificate should be the first item in the file, and the intermediate(s) should be concatenated after it.

**Comment by philiplb** [comment]
That did it, thank you.

**Comment by philiplb** [comment]
(And SSLLabs is cool now as well)
