### ISSUE TITLE
Flannel unhealthy

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2715]
The status endpoint tells me that flannel is unhealthy.
Here are the last lines of its log:

> 2016-04-19T22:23:36.293007Z app[app.Flynn1-f641a6a2-2de2-4cc3-87d0-b7965a81263b]: t=2016-04-19T22:23:36+0000 lvl=eror msg="heartbeat failed" component=discoverd service=flannel addr=x.y.z.w:5002 err="unknown_error: Something went wrong"
> 2016-04-19T22:23:36.493962Z app[app.Flynn1-f641a6a2-2de2-4cc3-87d0-b7965a81263b]: t=2016-04-19T22:23:36+0000 lvl=eror msg="heartbeat failed" component=discoverd service=flannel addr=x.y.z.w:5002 err="unknown_error: Something went wrong"
> 2016-04-19T22:23:36.694988Z app[app.Flynn1-f641a6a2-2de2-4cc3-87d0-b7965a81263b]: t=2016-04-19T22:23:36+0000 lvl=eror msg="heartbeat failed" component=discoverd service=flannel addr=x.y.z.w:5002 err="unknown_error: Something went wrong"
> 2016-04-19T22:23:36.895515Z app[app.Flynn1-f641a6a2-2de2-4cc3-87d0-b7965a81263b]: t=2016-04-19T22:23:36+0000 lvl=eror msg="heartbeat failed" component=discoverd service=flannel addr=x.y.z.w:5002 err="unknown_error: Something went wrong"

And the usual debug infos: https://www.philiplb.de/misc/2016-04-20_1105flynn-host-debug.tar.gz

How do I recover? Maybe killing flannel so it restarts?
What would be the permanent fix?

**Comment by philiplb** [comment]
Yep, killing flannel on all nodes so it restarts recovered from this issue.
As the root cause is unknown, I would leave this ticket open.

**Comment by titanous** [comment]
There was a temporary discoverd interruption between 22:22:20 and 22:23:31 UTC. This type of failure is usually due to a network interruption. It went away and everything was happy within a minute. Was flannel showing unhealthy outside of this period?

**Comment by philiplb** [comment]
Yes, it was unhealthy this morning at around 10am UTC.

**Comment by titanous** [comment]
K, thanks.

**Comment by titanous** [comment]
Does this still happen? I remember discussing debugging it a bit in IRC, but I don't remember the resolution.

**Comment by philiplb** [comment]
Hi,
thanks for asking. Since then, it happened on the upgrade to v20160512 once again and the two following updates not any more.
