### ISSUE TITLE
How can I make Flynn to tell my Django app that the connection is HTTPS

### ISSUE THREAD

**Issue by holtgrewe** [flynn/flynn#2717]
I found instructions how to make nginx set the `X-Forwarded-Protocol` header to `https` on HTTPs connections. This can then be interpreted by Django to see that the connection is secure.

How can I make Flynn do the same?

**Comment by titanous** [comment]
Flynn sets these headers automatically: `X-Forwarded-Proto`, `X-Forwarded-For`, `X-Forwarded-Port`

No configuration is required.
