### ISSUE TITLE
Getting RPC failed/HTTP 503 from git push flynn master

### ISSUE THREAD

**Issue by holtgrewe** [flynn/flynn#2720]
I'm pushing a large Java application. Previously, this worked but it stopped working between two pushes.

```
$ git push flynn master
Counting objects: 143552, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (31688/31688), done.
error: RPC failed; result=22, HTTP code = 503
fatal: The remote end hung up unexpectedly
Writing objects: 100% (143552/143552), 149.24 MiB | 891.00 KiB/s, done.
Total 143552 (delta 92522), reused 142979 (delta 91951)
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

Error log is here:

https://gist.github.com/aa2ae70f5b29a92bc40489d4e24b8c37

I'm currently using xip.io for DNS as I have to wait for our IT services to setup a proper wildcard DNS for my host. Spuriously, I can't get DNS resolution for my hosts (in Firefox and doing git push). I'm adding this in case it is useful information.

Please advice.

Edit: updated error log, I posted an older one.

**Comment by holtgrewe** [comment]
One more piece of information: pushing a small Python app works fine.

**Comment by holtgrewe** [comment]
OK, I could work around this issue by creating a new app with `flynn --create`. I will keep the flynn app around for a week or so, in case you are interested in a post mortem analysis.

I'm closing this ticket for now.

**Comment by titanous** [comment]
Please re-open this issue if you run into the error again.
