### ISSUE TITLE
Document how to deploy Wordpress

### ISSUE THREAD

**Issue by hoangweb** [flynn/flynn#2722]
hello admin!
i'm new to flynn. today, i want to deploy app from exist my own image (not public on docker hub), it's possible?
& because i wish i use flynn api to create everything for complete a demo site, for ex: assign database to app, & upload .sql file &  so i think:
image1: store code, php runtime (php:5.6-cli)
mariadb: built-in in flynn, so i will do put .sql file automatically after assign db to my app.

how i create a  script to do this, and also want to modify dashboard ui to integrate my product. So i just hit-one click & coffee for wating app deploy complete with all tasks i setup for a complete demo website. thank a man.

**Comment by titanous** [comment]
The API is documented here: https://flynn.io/docs/api/controller

I'd suggest taking a look at the CLI code for usage examples: https://github.com/flynn/flynn/tree/master/cli

Information on deploying a specific Docker image is here: https://flynn.io/docs/faq/how-can-i-deploy-a-docker-image

**Comment by ktdocker90** [comment]
i readed about how to deploy an image, but nerver done. can you write complete example about deploy wordpress from an image (https://hub.docker.com/_/wordpress/) with already data imported in mariadb, please please? thank very much.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
