### ISSUE TITLE
Scaling postgres database accross nodes on a rails, postgres app

### ISSUE THREAD

**Issue by jojobo** [flynn/flynn#2723]
From what I understand, flynn scales easily your web app, but not the connected postgres db. So you can add new nodes and scale your web app to many new nodes, but postgres db will remain confined in your original node. Am I missing smth here? Just to make the point clear, rancher which is also a docker based paas, scales seperately the web app and the database, so you can have many postgres db containers across various nodes. I don't see how you can scale the db containers in current docs. And if this is the case, does it make any sense to scale only your web app while having limited database performance?

**Comment by titanous** [comment]
Flynn runs databases in a highly available configuration, across multiple nodes. All writes and consistent reads will go through the primary instance. There is no way to magically scale write traffic across multiple Postgres/MySQL hosts. For that you'd need to shard your database, which requires careful consideration and implementation in your app.

Flynn will support running multiple database clusters soon, which can be used for sharding. However, in the majority of cases you can avoid the need for sharding by ensuring that you provision enough CPU, memory, and disk for the database. We'll be improving the tooling around dedicating resources to databases soon.

**Comment by jojobo** [comment]
So, with the current setup, it is complicated to assess how much resources your db needs, since it shares resources with app containers on one node. Basically, app containers get distributed evenly across nodes, but that one node where your postgres container is, will get overloaded.

For instance, say you got 3 nodes, and you scale your web app to 9, then you end up I guess with 3 web app containers in each node, BUT on the node where your postgres container is, you'll hit performance bottlenecks since postgres container is sharing resources with 3 other app containers and might not get enough cpu ( ram, disk) on its node. I'm I wrong? Sure you can provision 3 more capable nodes, but then you end up with 2 nodes wasting resources.

 If so, I'd suggest creating some tool that would limit web app containers on a per node basis, so that you can set a max of web containers on the node where db container is found.

**Comment by titanous** [comment]
Yeah, we can already do that with tag-based scheduling (#2411).
