### ISSUE TITLE
Can't push update and can't backup

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2726]
If I try and push an update I get the error

```remote: Error deploying app release: timed out waiting for deployment completion```

so I though ok time to create a new cluster but I can't back it up either as a fair while into the process I get the error

```
error dumping postgres database: error running postgres export: read tcp 82.666.34.66:443: operation timed out
```

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug-info` and post the link to the logs here.

**Comment by dottodot** [comment]
node1 https://gist.github.com/304b9a5c32a44bd9fee7f745ba262820
node2 https://gist.github.com/c8e49980c54ec4b02255fa4462f245a5 
node3 https://gist.github.com/e6e60c4d8b5d804e7ffd73b1f78f0e9c

**Comment by titanous** [comment]
It looks like the deploy is failing because the web process of your app is taking too long to start. We are going to add a command to change how long we wait for processes to start soon (#2662). In the mean time you can tweak the setting with:

```text
flynn -a controller pg psql -- -c "UPDATE apps SET deploy_timeout = 1000 WHERE name = 'bailey'"
```

The error encountered while taking the backup was probably just a network interruption somewhere, you could try again on a server to avoid transiting the internet.

**Comment by dottodot** [comment]
How do I backup on the server as `flynn cluster backup --file backup.tar`  gives the error 

```
no clusters configured
```

**Comment by titanous** [comment]
Copy the cluster stanza from `~/.flynnrc` where the Flynn CLI is configured to the same file on the server.

**Comment by dottodot** [comment]
That works great also a lot quicker than downloading.

**Comment by dottodot** [comment]
But the only problem is if there isn't enough space as I've just found out due to the amount of disk space used by flynn. I've a 40GB hard disk with 2 apps and don't have enough space to do a backup!!!

**Comment by dottodot** [comment]
Not sure why I didn't try this before but if you copy `~/.flynnrc` to your new server then run `flynn cluster backup --file backup.tar` you can save the backup directly to your new server without the pain of downloading then uploading or not having enough space, plus the benefit of saving a lot of time. Might be a nice tip to add to the docs as it's not obvious that that's an option.
