### ISSUE TITLE
Preserve routes when exporting/importing apps

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2728]
Exporting an app from `cluster 1` to import it in `cluster 2` won't copy over the routes that were defined for this app in `cluster 1`.

It would be nice to have that, at least as an option. Some apps can have many routes, and having to add them again every time a given app is imported onto a new cluster can be cumbersome.

**Comment by titanous** [comment]
Routes, are exported, they just aren't imported by default. Adding `--import` to the `flynn import` command will bring them in. Also, full cluster backups taken with `flynn cluster backup` will restore routes by default.

**Comment by quentez** [comment]
Oh I missed that. Awesome!
