### ISSUE TITLE
Are Applications with their slugs soft or hard deleted?

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2729]
Hi,
when I delete an application, are all slugs of its history soft or hard deleted? So, can I free harddrive space by deleting applications?

**Comment by philiplb** [comment]
At least the db entries of blobstore.files are actually deleted. I don't find any with the same file size despite having the same app created, deployed and deleted multiple times.

**Comment by philiplb** [comment]
Ah, I see some "DELETE"s in the log of blobstore. Does he actually delete then?

**Comment by philiplb** [comment]
Reading the used Postgres filesystem implementation, I learned that Large Objects are used and the files are stored in the db.
As there is nothing soft deleted in the files table, I would say the large objects are deleted, too. :)

**Comment by lmars** [comment]
FYI slug cleanup is being implemented in #2448 / #2679.
