### ISSUE TITLE
Route with path wrongly configured?

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2730]
Hi,

I've setup two apps with two routes. I added the routes in this order:
```bash
flynn -a myApp1 route add http foo.bar.com
flynn -a myApp2 route add http foo.bar.com/staging
```

But when I access http://foo.bar.com/staging, myApp1 seems to answer?

**Comment by titanous** [comment]
I can't reproduce this. Would you please show the `flynn route` output for both apps and double-check that it isn't working correctly?

**Comment by philiplb** [comment]
In order to distinguish them absolutely, I removed the /staging-app (currently not in use anyway) and  deployed the PHP sample. The / app is Java.

The current result: The app running at the "root" of the domain is still fine, the app running at /staging is producing a 404. Both apps just work fine via the flynn URLs.

```bash
flynn -a myApp1 route
```
> ROUTE                             SERVICE     ID                                         STICKY  LEADER  PATH
> https:myapp.solutions.xyz.com  myapp1-web  http/0f78611b-e331-4f9e-ae27-538954e928a7  false   false   /
> http:myapp1.flynn.xyz.com       myapp1-web  http/81f32760-1ceb-438b-a28e-f2ef8100bee9  false   false   /

```bash
flynn -a myApp2 route
```

> ROUTE                               SERVICE            ID                                         STICKY  LEADER  PATH
> https:myapp.solutions.xyz.com    myapp2-web  http/fb004b85-d6f9-4856-87f6-737611280542  false   false   /staging/
> http:myapp2.flynn.xyz.com  myapp2-web  http/5fa193a8-4a99-42c8-a653-20359c2ba4ee  false   false   /

**Comment by josephglanville** [comment]
@philiplb Flynn's router doesn't currently do path rewriting. So the app at `/staging-app` will need to be configured to handle paths prefixed with this. Alternatively you can configure your HTTP server to rewrite the paths for your application if you are using one. We may support rewriting paths directly in Flynn at some stage.

**Comment by philiplb** [comment]
Thank you for the answer. That's good to know. I assume the PHP Flynn sample application currently deployed at /staging doesn't need URL rewriting?

**Comment by philiplb** [comment]
Here is an example of a test application:
So I got this application: https://github.com/philiplb/SimplePHPTest
Branches:
- master: should not be deployed, development happening here
- staging: upcoming version to be tested, "beta"-version. Should be deployed to /staging
- production: production version, should be deployed to /

Each version prints a slightly different string to distinguish them if they answer.

This is how I setup the two Flynn applications:

**Created a DNS CNAME**

myapp.solutions.smfhq.com pointing to approd.flynn.smfhq.com 

This might be wrong? Could be also A records for each Flynn cluster? The later would require more work on application setup and on Flynn maintenance when adding more nodes or exchanging some outside the consensus set

**Deployed Production**

```bash
git checkout production
flynn create appprod
git push flynn production:master
flynn -a appprod route add http -c cert -k key myapp.solutions.smfhq.com
```

**Deployed Staging**

```bash
git checkout staging
flynn create appstaging
git push flynn staging:master
flynn -a appstaging route add http -c cert -k key myapp.solutions.smfhq.com/staging
```

**Routes**

```bash
flynn -a appprod route
```

> ROUTE                            SERVICE      ID                                         STICKY  LEADER  PATH
> https:myapp.solutions.smfhq.com  appprod-web  http/9a7edae3-12dd-4f2c-b110-176eaf9909e2  false   false   /
> http:appprod.flynn.smfhq.com     appprod-web  http/27f9d901-3f73-42d1-853f-138871cc76a1  false   false   /

```bash
flynn -a appstaging route
```

> ROUTE                            SERVICE         ID                                         STICKY  LEADER  PATH
> https:myapp.solutions.smfhq.com  appstaging-web  http/b7b1d280-8e3c-476d-911f-b7365cdaa215  false   false   /staging/
> http:appstaging.flynn.smfhq.com  appstaging-web  http/34733ff5-8765-407f-873c-0e811620393d  false   false   /

**Resulting Urls**

* https://myapp.solutions.smfhq.com/ -> Works fine
* http://appprod.flynn.smfhq.com/ -> Works fine
* https://myapp.solutions.smfhq.com/staging -> 404, the problem
* http://appstaging.flynn.smfhq.com/ -> Works fine

**Comment by philiplb** [comment]
What comes into my mind: Does the order of adding routes matter? So / matches before /staging Bad a chance?
Apache mod_proxy behaves the same.

**Comment by titanous** [comment]
Paths are matched depth-first, order of creation doesn't matter.

As @josephglanville points out, the problem is very likely the path prefix. Requests are for /staging/foo not /foo.

**Comment by philiplb** [comment]
OK, what exactly is meant with foo in this case?
The app itself is just an index.php with a single line oft output, no pathes yet.

**Comment by titanous** [comment]
Rename `index.php` in the staging branch to `staging.php` and you should see what I mean.

**Comment by titanous** [comment]
Just to be even clearer:

A request to `http://myapp.solutions.smfhq.com/staging` results in this HTTP request to your staging app:

```text
GET /staging
```

And a request to `http://appstaging.flynn.smfhq.com/` results in this HTTP request to your staging app:

```text
GET /
```

**Comment by philiplb** [comment]
Ah, alright, got it. :-)
Now I have to come up with something. Maybe installing a reverse proxy application to proxy the Flynn urls.

**Comment by philiplb** [comment]
This is now solved without big hassle. :-)
- Java: The jetty-runner has a parameter "--path" which can be set to an environment variable. Production sets this to "/", staging to "/staging"
- PHP: Can be easily done via mod_rewrite having an environment variable in the Apache config

**Comment by dropfen** [comment]
Guys, currently I can add domains like *www.app.com* and *app.com*
But how to create a simple rewrite_rule from *www.app.com* to *app.com* ?

**Comment by titanous** [comment]
@dropfen That is not currently supported by the router, you should do it in your app.
