### ISSUE TITLE
running rake tasks or "flynn run rails console" returns "the handle is invalid" error

### ISSUE THREAD

**Issue by jojobo** [flynn/flynn#2734]
I'm trying to run rake task with 'flynn run rake somenamespace:task' but I get "the handle is invalid".
Same when I run flynn run rails console. The app is deployed and fully functional.

**Comment by lmars** [comment]
@jojobo can you gist the full output of your command? Is that error part of a Ruby backtrace?

**Comment by jojobo** [comment]
@lmars I found the problem. I'm on windows and it fails using command prompt, but it works fine using git bash.

**Comment by lmars** [comment]
@jojobo ok glad you got to the bottom of it.
