### ISSUE TITLE
Response HTTP/1.1 503 Service Unavailable: Back-end server is at capacity

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#2738]
Here are the gists for the debug-info:
https://gist.github.com/83c08983faacbd60be8277a33a1fcd29
https://gist.github.com/1992f9a819f45488262feaa7b0ca42f6

**Comment by titanous** [comment]
It looks like one host is missing from that cluster. Also, what is the name of the app that you are getting the 503 from?

**Comment by tianx2** [comment]
We are checking these 3 apps:
* firebird-health
* terminus
* flynn-usage-example

Currently collecting debug-info on the missing node.

**Comment by titanous** [comment]
From the router log it looks like there were a few short windows where discoverd wasn't working properly, were the failures you saw intermittent?

**Comment by titanous** [comment]
Also, was the text returned actually "Back-end server is at capacity"? That error string is not used by Flynn anywhere.

**Comment by tianx2** [comment]
So the 503 "Back-end server is at capacity" is an error returned by the AWS ElasticLoadBalancer which sits in front of the containers. Let me track down why the ELB is returning those errors. Basically, I'm getting constant flakiness where the app would be OK and then we would get 503 errors.

**Comment by tianx2** [comment]
Here is the log to the last node - https://bazaarvoice.box.com/s/diwi0d27m7gi3jnmbetyb5flhzd20ks3
I guess 7.5 MB is too large for a gist.

**Comment by titanous** [comment]
It looks like the host with IP 10.100.37.115 was replaced, which is why the cluster was unstable. #2682 will address reconfiguration of the consensus cluster.

**Comment by tianx2** [comment]
@titanous I'm unsure what you mean by replaced. There was a node termination on April 23rd for the cluster. But this issue occurred today on April 25th around 11:00 AM ET. That IP address seems like something that could have been April 23rd. It's just strange to see the instability so long after.

**Comment by titanous** [comment]
A node termination in a three-node cluster would take the cluster down to two nodes. The Raft consensus algorithm requires a majority to accept writes, so with two nodes the cluster will be fine unless there are issues with either of the remaining two nodes. An issue could be something as simple as a temporary network interruption or CPU spike.
