### ISSUE TITLE
Push git tag to master fails if tag has a message

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#2746]
When deploying to Flynn I frequently push a tag rather than a branch `git push flynn v1.0.0:master`. When creating the tag if I use the message option `git tag v1.0.0 -m "any message"` I get a failure when pushing to flynn. The application actually successfully deploys, but then I immediately get the following error:

```
fatal: protocol error: bad line length character: erro
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'https://git.flynn.hostname.com/app-name.git'
```

Without the `-m` option I don't get the error.

**Comment by lmars** [comment]
This is easily reproducible, we'll work on a fix.

**Comment by kevinob11** [comment]
Thanks!

**Comment by lmars** [comment]
@kevinob11 ok so this kind of push leads to an error from git on the server side:

```
error: Trying to write non-commit object e51a7409abe1a08aade57c8ce6f7afdd8f50887a to branch refs/heads/master
```

I came across [this SO answer](http://stackoverflow.com/a/4061542/2622394) which explains why this is failing (you cannot push an annotated tag to a branch), and you can get around it by using the `^{type}` "peeling" operator like so:

```
$ git push flynn v1.0.0^{commit}:master
```

Do you want to give that a try?

**Comment by kevinob11** [comment]
Ah yes, that works great, and even better the following shorthand:
```
git push flynn v1.0.0~0:master
```
