### ISSUE TITLE
git asking for login credentials 

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2752]
When trying to push on another pc it's asking for the login credentials for git. 

Both have the same ~/.flynnrc and I've installed the certificate can't think what I'm missing.

**Comment by titanous** [comment]
Run `flynn cluster add` with the details from `~/.flynnrc`. It configures git with a credentials helper and CA certificate.

**Comment by hadifarnoud** [comment]
it says `A cluster with the URL "https://controller.eg55.flynnhub.com" already exists in ~/.flynnrc`
