### ISSUE TITLE
Unable to start flynn-host

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#2753]
After my instance (single node cluster) went down I was unable to restart Flynn with `start flynn-host`. Rebooting the machine was also of no help.

Here's the `flynn-host collect-debug-info` output:
https://gist.github.com/66fe193d9f74c0653c5512b5364c1e21

And the `/var/log/upstart/flynn-host.log`, which looks quite interesting:
https://gist.github.com/thomasfedb/6e350d976bd03a832d157b3301414be8

**Comment by thomasfedb** [comment]
Here's the full set of `/var/log/upstart/flynn-host.log.*.gz` files:
https://gist.github.com/thomasfedb/5ceb946c0b342d86027e6b694748457f

**Comment by lmars** [comment]
The issue restarting flynn-host was due to #2338 which was fixed but @thomasfedb had a version without the fix, which was resolved by downloading a newer version of flynn-host:

```
sudo FLYNN_VERSION=v20151231.0 flynn-host download
```
