### ISSUE TITLE
Router flapping

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2757]
https://bazaarvoice.box.com/s/s4i6gy9phfvo9n2i93lh15rjj17runmb

The router on 10.100.45.56 is flapping, and apparently causing both developer-facing and user-facing issues. Doesn't look like #2638, but maybe I'm missing something.

**Comment by lmars** [comment]
@temujin9 I am looking in to this, but I may need some expanded logs, can you hold off on nuking the cluster?

**Comment by temujin9** [comment]
Yes, I can. Let me know what you need.
