### ISSUE TITLE
"discoverd: timed out waiting for instances" failure on bootstrap

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2758]
Failure on bootstrap:
```
17:45:48.092460 wait-controller wait-controller
17:46:18.094218 host.go:142: error getting controller instance: discoverd: timed out waiting for instances'
```

https://gist.github.com/5c8fbcd0103f3efe97a537780ba5377a is the debug-info from the boostrapping node.

**Comment by titanous** [comment]
Looks like a bug in recent changes to the controller:

```text
17:45:48.635196 controller.go:64: ERROR: duplicate key value violates unique constraint "artifacts_type_uri_idx" (SQLSTATE 23505)
```

/cc @lmars

**Comment by lmars** [comment]
@temujin9 I see the issue, working on a patch now.

**Comment by temujin9** [comment]
@lmars Thanks. Please let me know when it's released: this is blocking all rebuilds of a failed cluster, so it's P2 at least, and becomes P1 if any of our production clusters have a failure.

**Comment by temujin9** [comment]
(https://gist.github.com/d6f8597191b2c62356e2c3ef78c08917 and https://gist.github.com/083c0f0ed6b2ab54c1ccb14594d88986 are the newest failures, if that helps any.)
