### ISSUE TITLE
controller: Use GraphQL

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#2759]
- [ ] Add [Relay](https://facebook.github.io/relay/) compatible [GraphQL](http://graphql.org) endpoint add deprecation response header to all the other endpoints it replaces.
- [ ] Update docs
- [ ] Update Go Client
- [ ] Update dashboard

Replaces #533, #2742, #2261, #2262, and #2260

Progress can be tracked on the [controller-graphql](https://github.com/flynn/flynn/tree/controller-graphql) branch.

**Comment by jvatic** [comment]
## Versioning

The way backward compatibility works in the server is by only adding fields and never removing or changing them (other than to mark as deprecated to omit from docs).

We also have to handle backwards compatibility on the CLI client (it will inevitably be newer than the server it's talking to). This means structuring it to handle using both REST and as many versions of the GraphQL endpoint we support. The simplest solution that comes to mind is to proxy commands from the main CLI (other than `flynn install`) to another binary (which excludes the installer) downloaded from/for each server version the CLI is configured to interact with. Another potential solution is to have multiple versions of the Go client packaged with it. Thoughts?

**Comment by jvatic** [comment]
As per a conversation with @titanous, backwards compatibility on the client should, unless a better solution is found, be managed via a versioning layer that handles translating from/to the latest version of everything (i.e. the main CLI code doesn't know about any previous revisions) and returns an error if the server it's interacting with doesn't support an operation.

**Comment by jvatic** [comment]
https://github.com/graphql-go looks like the most complete Go implementation

**Comment by jvatic** [comment]
Progress can be tracked on the [controller-graphql](https://github.com/flynn/flynn/tree/controller-graphql) branch.

**Comment by titanous** [comment]
Closed in favor of #3358.
