### ISSUE TITLE
Flynn updater

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#276]

**Comment by lmars** [comment]
All layer 1 components can now be updated by running `flynn-host update`, namely:

* blobstore
* taffy
* dashboard
* router
* gitreceive
* controller
* logaggregator (possible data loss until replication lands #1339 and deployer updated)
* postgres

What remains is updating layer 0 components, namely:

* flynn-host
* discoverd
* etcd
* flannel

Updating those needs #1373 to land first.

We will add full documentation on the process once this work is complete.

**Comment by titanous** [comment]
This is done!

**Comment by lmars** [comment]
:heart_eyes:
