### ISSUE TITLE
Mixed releases

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2764]
My releases seem to have got in a mess and I seem to have an old release mixed in with the new ones

```
cluster7-4507f6b3-9136-462b-b1f5-fdf089b7170d  web              up       9 hours ago    38887ab5-5f75-46b6-acc1-2ba82f0c4b39
cluster9-450fc767-d910-4afa-8ffa-8802b2dd673a  web              up       9 hours ago    38887ab5-5f75-46b6-acc1-2ba82f0c4b39
cluster7-5d289645-0017-495d-92c6-be9da5819e2a  checkout_expire  up       9 hours ago    38887ab5-5f75-46b6-acc1-2ba82f0c4b39
596500d4-d7f1-432d-9caa-95e74e74f6d0           web              pending  9 hours ago    38887ab5-5f75-46b6-acc1-2ba82f0c4b39
cluster7-e893446e-b776-422d-ade6-bfa4667926c5  web              up       3 minutes ago  6adbba79-811d-491f-bfa1-eb23d0272615
```
I've tried killing it but it just starts a fresh process on the same release. Also the one that shows as pending can't be killed I juts get an error of

```
unknown_error: Something went wrong
```

**Comment by lmars** [comment]
@dottodot please run `sudo flynn-host collect-debug-info` on all hosts in your cluster and post the resulting gist links.

Also, what is the output of `flynn scale --all`?

**Comment by dottodot** [comment]
`flynn scale --all` gives me
```
checkout_expire=1 web=1

6adbba79-811d-491f-bfa1-eb23d0272615
web=1
```
Trying to get the logs but don't think it's working as been running for 35 minutes and not got a link.

**Comment by dottodot** [comment]
OK got the logs eventually

https://gist.github.com/17c70ad5056ec670a920982c10350cc7 
https://gist.github.com/3517a16995a1a4f04a9195dd751f53e5
https://gist.github.com/b752bd1196b2864416069f6c7a5b5a29

**Comment by dottodot** [comment]
and there is definitely 2 different versions running as I'm sometime seeing an old version of my app on some requests and the new one on other requests.

**Comment by dottodot** [comment]
Ended up creating a new cluster so closing for now.
