### ISSUE TITLE
Downloading TUF db fails on stable channel

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2765]
When installing Flynn from the stable channel, the process fails with the following error:

```
ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin"
```

**Comment by lmars** [comment]
@quentez can you gist the full output?

**Comment by quentez** [comment]
I can't actually, these instances were reset multiple times after that 😕. After maybe ~1h it started working again. The server on your side was apparently returning a 500.

**Comment by lmars** [comment]
@quentez ok, well the downloads come from an AWS CloudFront distribution backed by an S3 bucket, so there is not much I can do but put this down to AWS being intermittent at that time.

If this happens again, please try and grab the full output.
