### ISSUE TITLE
Problem using redis appliance

### ISSUE THREAD

**Issue by tjboring** [flynn/flynn#2767]
I can create a redis resource but cannot connect to it. Here are the steps I've performed:

> flynn resource add redis
> flynn resource
ID                                    Provider ID                           Provider Name
97fd42a0-6a8f-40ad-bdea-181e7414192e  01ad67c8-cc08-4c7a-ba18-2b6140c71854  redis
> flynn redis redis-cli
No redis server found. Provision one with `flynn resource add redis`

This shows a redis app, so the above should work?
> flynn apps
ID                                    NAME
9ca77233-5fc9-4ae9-9e32-187dc093cb28  redis-2b1b4ffa-b297-48c2-8421-72ba4f18883c

I've tried creating a brand new cluster, then create a redis resource on it, with the same results.

I can also tail the logs for each instance of the redis app:
> flynn -c $cluster -a $name-of-redis-app

Any idea what might be going on here?

**Comment by titanous** [comment]
Currently `flynn redis redis-cli` looks for an environment variable in the app release called `FLYNN_REDIS`. If it does not exist, then that error will be shown. Is it possible that the variable has been deleted or replaced accidentally?

**Comment by tjboring** [comment]
Ah, ok, that explains it. If I set the environment variable in one of the apps, I can then connect via the redis-cli.

So this was just a misunderstanding on my part. #nothingtoseehere
