### ISSUE TITLE
Cluster unresponsive

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2768]
Not really sure what happened here: there was no loss of underlying node, but monitoring reports that we lost host, router, and scheduler on this node around 6:02PM, and they never recovered.

https://bazaarvoice.box.com/s/zr0sh334c8msrlfh5cvja0mhbfby52ra

I'll keep the offender around for a bit, in case you want more. Speak up soon; I'll probably nuke it tomorrow afternoon if I don't hear otherwise.

**Comment by titanous** [comment]
If you still have the broken node around (10.100.41.26): Is `/var/lib/docker` around with subdirectories and data in those directories?

**Comment by titanous** [comment]
Also, can you check the uptime of the host? Everything I'm seeing points to a reboot.

**Comment by temujin9** [comment]
Uptime confirms it's a reboot. `/var/lib/docker/` is indeed empty; we don't handle the reboot well, and so it looks like the mount which happens underneath that did not happen. I'll put it on the list of things to clean up.
