### ISSUE TITLE
error dumping mariadb database on backup

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#2771]
Trying to backup I get the error

```
error dumping mariadb database: error running mariadb export: unexpected command exit status 2
```

**Comment by titanous** [comment]
Please post the debug info for the cluster.

**Comment by dottodot** [comment]
https://gist.github.com/17c70ad5056ec670a920982c10350cc7 
https://gist.github.com/3517a16995a1a4f04a9195dd751f53e5
https://gist.github.com/b752bd1196b2864416069f6c7a5b5a29

**Comment by dottodot** [comment]
Going to close this as just ended up creating a new cluster. Not sure if it's because I didn't have much free disk space.
