### ISSUE TITLE
Slugbuilder job gets stuck

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2773]
After pushing a large app, the slugbuilder job will sometimes fail to start after the git receive step is finished. When that happens, the slugbuilder job will remain visible in the `flynn-host ps` list, with a `starting` status. It won't be cleared/killed/removed at any point after that.

Moreover I'm suspecting this may be affecting the scaling count for the targeted app later on, as the same number of jobs will be stuck in a `pending` state (as if the "slots" were already taken by the slugbuilder... I have clearly no idea what I'm talking about here).

Debug info: https://gist.github.com/anonymous/28b47ddf8f68ffdddca45ecbe799dba3

(Also: I haven't found a way to clear these jobs... Even `flynn-host stop ID` does nothing here).

**Comment by titanous** [comment]
Please also collect the complete scheduler logs by running `flynn-host ps -a` on a host and then `flynn-host log $JOB_ID` for each process labeled "controller scheduler" and put them in a gist. Thanks!

**Comment by quentez** [comment]
Yep. Here it is: https://gist.github.com/quentez/b4712482a496720e2e2e45245f958cc4

**Comment by titanous** [comment]
@lmars please take a look at this.

**Comment by quentez** [comment]
For what it's worth, the stable version seems a lot more stable when it comes to spawning/killing and overall scheduling jobs without ending up in a completely messed up situation.

(I tried the same workflow on two fresh nightly clusters, and it ended up stuck both times. I tried it again on a stable cluster and things appear to be working well so far).

**Comment by lmars** [comment]
@quentez can you please run `sudo flynn-host collect-debug-info` on the host which has the "starting" slugbuilder jobs (i.e. `ip172310138`).

**Comment by quentez** [comment]
@lmars I'm afraid I can't. Since I had no way to kill the `starting` jobs, I ended up resetting the cluster completely and using the `stable` channel instead. I've made sure to post here the logs that @titanous requested before I performed the reset.

Things have been working rather smoothly on `stable` since then, but this bug is something I was able to reproduce even after a full cluster reset on `nightly`.

**Comment by lmars** [comment]
@quentez I see in IRC you mention that this happened again on a new cluster, can you please run `sudo flynn-host collect-debug-info` on the host which has the jobs stuck in the "starting" state?

**Comment by quentez** [comment]
@lmars Sure. Here you go: https://gist.github.com/c1bab2407e78673a4ee1e16f9ba70cf7

**Comment by titanous** [comment]
Looks like this was fixed by #2833, please open a new issue if you see this again.
