### ISSUE TITLE
scheduler: Should stop starting jobs before running ones

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2774]
When a scale-up is still in progress (some jobs `up`, others `starting`), a scale-down command may kill the `up` jobs and leave the `starting` alive. This results in the app becoming unavailable until the `starting` jobs are ready to serve new requests.

**Comment by lmars** [comment]
@quentez when the scheduler is scaling a process type down, it [stops the most recently started job first](https://github.com/flynn/flynn/blob/v20160502.0/controller/scheduler/scheduler.go#L1315-L1337), so in most cases this will stop the starting jobs before the running ones as it is likely they started more recently.

Were you finding that you had "starting" jobs which were not transitioning to "up"?

**Comment by lmars** [comment]
Oh I just realised that starting jobs have a zero `StartedAt` field, so they will actually be picked _after_ the running jobs, so that's a bug.
