### ISSUE TITLE
export/backup fails on OS X using client v20160503.0

### ISSUE THREAD

**Issue by swaits** [flynn/flynn#2777]
On OS X (10.11.3), with client v20160503.0, both backup and export are having trouble fetching artifacts. Example diagnostics as follows:

    error retrieving artifact: GET https://controller.j9oe.flynnhub.com/artifacts/: httpclient: raw req: unexpected status 401
    error getting mariadb app artifact: GET https://controller.j9oe.flynnhub.com/artifacts/: httpclient: raw req: unexpected status 401
    error getting flannel app artifact: GET https://controller.j9oe.flynnhub.com/artifacts/: httpclient: raw req: unexpected status 401

Works as expected when reverting to client v20160327.0.

**Comment by jvatic** [comment]
This is a bug introduced in #2448 (`release.ImageArtifactID()` doesn't fallback to `release.LegacyArtifactID`).

A workaround is to use curl against the backup endpoint: `curl -o ~/flynn-backup.tar CONTROLLER_URL/backup --user ":$(flynn -a controller env get AUTH_KEY)"`

**Comment by lmars** [comment]
FYI I am currently working on a fix for this.
