### ISSUE TITLE
Request: Ability to "git push" without deploying immediately

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2778]
We have a pretty large app, and the build process when deploying can take anywhere between 8 and 15 minutes. It can also fail for reasons that won't always be caught in CI first. We also have components that aren't in Flynn, and that need to be updated at the same time when they communicate together.

As a result, it would be super helpful to be able to push and create a release, but be able to deploy it at a later date, when everything is ready and we're confident the process won't fail. This would be similar to how you can send an app for review on iOS, but it won't be released on the AppStore until you decide so.

Another way to do this could be to have a way to move a route between apps without any downtime. If that was possible we would create a new app, make sure everything is ready, and then move the route at the exact moment we want to release the new version.

**Comment by jvatic** [comment]
Presumably updating a route's `ParentRef` field to `controller.RouteParentRefPrefix + "APP_ID"` (`controller/apps/APP_ID`) should do what you want in the case of moving the route between apps.

**Comment by josephglanville** [comment]
Moving a route between apps would have no downtime is definitely something we could look at making nicer. We could probably support this through the route update interface, it's already fully supported by the underlying routing engine.

As for doing a push without deploying the release I think that could be a toggle on a per-app basis. You could create a new release with `git push` and then scale up the new release followed by scaling down the old release. We could also look at extending `flynn deployment` to actually create deployments between 2 releases on the CLI. Something along the lines of `flynn deployment create <FROM_ID> <TO_ID>`

Thoughts?

**Comment by jvatic** [comment]
We could add the ability to set `App` (ID) instead of `ParentRef` when updating through the controller.

I think it makes sense to support not deploying on `git push` via an app meta key such as `flynn-git-deploy: false` or `flynn-git-release-only: true`. Why not `flynn deployment create <TO_ID>`?

**Comment by quentez** [comment]
For the routes side of things, maybe the CLI could just ask for confirmation with a warning when trying to add a route that already exists on another app (and that would then be overwritten by the new one). The advantage of this would be that it doesn't add complexity, the downside is HTTPS routes where you'd need to provide the certificate again and again.

**Comment by titanous** [comment]
We're going to split the management of certificates off of the management of routes.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
