### ISSUE TITLE
Git Push won't start after a few failed attemps

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2788]
I created an app and tried deploying it on a brand new cluster (version `v20160505.0`). 
The buildpack crashed twice for different reasons (I can still see the `slugbuilder` jobs as `crashed`).
On the 3rd attempt, the `git push` command won't even start writing objects, failing with the following error:

```
error: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503 Service Unavailable
```

Here's the server logs: https://gist.github.com/b0e10c926d2db0f00e3acecb4b0ea992

**Comment by titanous** [comment]
How big is the repo?

**Comment by quentez** [comment]
Around 250MB.

**Comment by titanous** [comment]
I think that the repo cache is taking too long to download. I'll look into the best way to fix this.

**Comment by titanous** [comment]
For now the best workaround would be something along these lines: https://github.com/flynn/flynn/issues/2787#issuecomment-217478084

We're going to be implementing some fixes to support large repos better.

**Comment by quentez** [comment]
Ok, I'll try something in that vein if the problem presents itself again. Thank you.

**Comment by javaHelper** [comment]
I am still facing this issue and frustrated in trying so many solutions. Could you please help as its not even pushing 100KB file.
