### ISSUE TITLE
Ability to see the tags of a deployed application

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2795]
Hi,

in order to move around some applications on some nodes (so that not every app ends up at the first node), I scaled them with tags so they ended up spread in the cluster:

```bash
flynn -a myApp scale web=1,host=flynn2
```

I then removed again the tags (I think):

```bash
flynn -a myApp scale web=1
```

And according to flynn-host ps, the application stayed at the node flynn2.

Now the question: If I later want to check, with what tags an application is deployed?
And I assume, if the application goes down and no more nodes fulfill the tags, then it won't restart?

**Comment by lmars** [comment]
@philiplb 

> If I later want to check, with what tags an application is deployed?

We don't currently expose that, I have opened #2809.

> if the application goes down and no more nodes fulfill the tags, then it won't restart?

Correct, a job will remain pending if it has tags which cannot be satisfied.

**Comment by philiplb** [comment]
@lmars 

Ok, cool. Thank you!

**Comment by lmars** [comment]
Closing in favour of #2809.
