### ISSUE TITLE
scheduler: Don't place multiple n=1 apps on the same host

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2796]
The scheduler currently only distributes process types across all hosts on a per-app basis, and it also [picks hosts in sorted order](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L693-L712) (likely to make the tests more predictable), which means multiple apps scaled to n=1 all get placed on the same host (the one that is first in the sorted list).

Possible fixes:

* Pick a host at random when they have the same amount of jobs and expect that to distribute better
* When no hosts have a job of a particular type, do some further counting to determine which host has the least jobs of any app / type

/cc @titanous

**Comment by philiplb** [comment]
Just distributing them randomly would be a first good step. Yesterday this was a real problem for me:

- Cluster specs: three nodes each having two cores and two GB of memory
- I restored from backup
- All applications are scaled with web=1
- Eleven Java applications where starting on the first node each with a XMX of 350MB

This almost killed the first node. While the applications where starting (and some of them crashing and the vserver becoming more and more unresponsive), I moved them around via

```bash
flynn -a currentapp scale web=1,host=flynnX
sleep 30
flynn -a currentapp scale web=1
```

until things stabilized.
Each node has a tag "host=flynnX" with X being a node number starting from zero.
