### ISSUE TITLE
Status app shows mariadb and postgress as unhealthy

### ISSUE THREAD

**Issue by ohhatiya** [flynn/flynn#2803]
We are monitoring the output of the status app, and occasionally mariadb and postgres go into an unhealthy state. Here's the HTTP response from the status app when in this state:
```json
{
  "data": {
    "status": "unhealthy",
    "detail": {
      "blobstore": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "controller": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "controller-scheduler": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "controller-worker": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "dashboard": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "discoverd": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "flannel": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "gitreceive": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "logaggregator": {
        "status": "healthy",
        "version": "v20160506.0"
      },
      "mariadb": {
        "status": "unhealthy",
        "version": "v20160506.0"
      },
      "postgres": {
        "status": "unhealthy",
        "version": "v20160506.0"
      },
      "router": {
        "status": "healthy",
        "version": "v20160506.0"
      }
    },
    "version": "v20160506.0"
  }
}
```

Here's debug info gists for the nodes in our cluster while the unhealthy status is being reported:
https://gist.github.com/6adb0ba0604f08b4eb242f97e9394c5d
https://gist.github.com/a48cdc7b22ecaca9b9e67c8456fe5aa6
https://gist.github.com/7f5f61e22a8c49b633bd3d07f46dc1e3

They started reporting unhealthy today at 17:18 UTC. Another cluster had the same thing happen earlier today, but in that case it resolved itself after about 20 minutes.

Also, at the same time it started reporting unhealthy, another app returned 503 briefly. However, that resolved itself immediately. May or may not be related.

**Comment by josephglanville** [comment]
There appears to be a networking issue in play. The postgres cluster did fail over however `ip1010041123-1aa4d6c9-37f8-4b80-b9c5-3b9fe9ca599b` become the new primary and as of the time of the log dump is accepting writes. However for the status page to report unhealthy the postgres API musn't be able to reach the database and confirm it's availability.

Was this failure intermittent or does it appear to be stuck in the unhealthy state?

**Comment by josephglanville** [comment]
Also given an app returned `503` (which should only occur if the router wasn't able to find a backend) either means your application crashed when it's database wasn't available or that the disruption also caused a disruption to `discoverd`, which would also explain the postgres failover.

**Comment by ohhatiya** [comment]
The issue happened twice (on two different clusters). The first time it lasted about 20 minutes, and then resolved itself. The second time it never resolved itself, and the cluster was eventually replaced.

**Comment by temujin9** [comment]
This may also be related to the pg_dump, as mentioned in #2743.

**Comment by temujin9** [comment]
(It is also worth noting: the clustering setup appears to worked well enough to provide us with HA for the database, even if it didn't recover fully in at least one case.)

**Comment by ohhatiya** [comment]
A similar issue occurred again, then another time shortly thereafter.

The first time, all apps returned 503s for a few minutes, then recovered (some took a few minutes longer to recover than others).

The second time, most apps recovered much more quickly, but controller, controller-worker, postgres, and mariadb all stayed unhealthy.

Here are debug info for all hosts in the cluster:
https://bazaarvoice.box.com/s/glvy2zykdhxucv63jwyzn8n7c4xrc9gw
https://bazaarvoice.box.com/s/87laclpd976vz0daut69ylgi523ftgfi
https://bazaarvoice.box.com/s/9cue49wp9f5l48ftw1veap2y4k55uko7
https://bazaarvoice.box.com/s/fq3ey1gl6t8q8drc75a2rpepg7l4re9d
https://bazaarvoice.box.com/s/qesif7vntliardr0h812g86wkrqtbvmk

The first incident happened at 2016-05-12 00:21 UTC. The second happened at 2016-05-12 01:37 UTC.

**Comment by tianx2** [comment]
@josephglanville This seems to be happening at a daily frequency. I know this has occurred with version `v20160514.0` and `v20160517.1`. Is there something we could do to find the root cause?

Here is some logs - https://bazaarvoice.box.com/s/qkfsmpq2ck975zp0f945olj8mn5y7mfd

**Comment by tianx2** [comment]
@josephglanville added some logs as `flynn-[6-10].tar.gz` for v20160518.0. This started out as `postgres` showing as unhealthy. Eventually degrades to `controller` and `mariadb` showing as unhealthy.

**Comment by tjboring** [comment]
FWIW, I've noticed this issue on a newly created (i.e. in the last 7 days) cluster. For some reason, this morning, the status endpoint started reporting that the mariadb component was unhealthy. When I checked the scale for that app:

> flynn -a mariadb scale

it reported 0. 

I asked @lmars on IRC if Flynn used mariab for internal purposes, and he said no. And we're not using it, so it's fine for it to be a 0. For some reason the status started reporting as unhealthy.

**Comment by josephglanville** [comment]
The status will report unhealthy in the JSON output but the overall cluster status and HTTP return code of the status endpoint should indicate that the cluster is healthy. You only need to monitor the MariaDB portion of the health endpoint if you are actively using MariaDB.

**Comment by temujin9** [comment]
We are alerting purely on the HTTP return code, so that should be okay.

However, it is somewhat concerning that it is scaled correctly (mariadb=3 web=2) on one of our clusters, showing unhealthy, and *not* causing an overall alert. Is status aware of whether the component is used by applications somehow?

**Comment by tianx2** [comment]
Is there something we can do about postgres going unhealthy. It seems to go unhealthy for about 10-30 minutes but then recovers some of the time. Other times, there will be a cascade of failures that cause other components to go unhealthy. Since postgres seems to be a major component of using the flynn CLI especially when doing deploys, it's difficult to know what to do in the case postgres goes down. Do you have some tips on what can be done to determine what needs to be done in terms of recovery. We're planning on adding some logging to find the root cause of what's causing postgres to go "unhealthy" in the first place. 

This causes outages in interacting with the flynn CLI for some subset of commands.

**Comment by titanous** [comment]
I think the quick fix here is to move blobstore data out of Postgres and into S3, it will drastically reduce the size of backups and the impact that taking backups from Postgres has. We're also looking at ways to isolate the load while backups are being performed.

#2622 tracks the work to add S3 blob support, I'll be working on it this upcoming week.

We also need to update the discoverd logging so we can get a better idea of the root cause of any instability (#2526).

**Comment by temujin9** [comment]
Update: this has occurred again. `flynn -a postgres log -f` shows lots of repetitions of
```
2016-05-24T18:56:38.338840Z app[postgres.ip1010036169-209edeec-1da6-4430-b713-d31198c0ca87]: t=2016-05-24T18:56:38+0000 lvl=dbug msg="checking replication status" app=postgres component=postgres fn=checkReplStatus name=a0287ef6-b8f5-4482-b9de-73e363777dc5
2016-05-24T18:56:38.351215Z app[postgres.ip1010036169-209edeec-1da6-4430-b713-d31198c0ca87]: t=2016-05-24T18:56:38+0000 lvl=dbug msg="no replication status" app=postgres component=postgres fn=checkReplStatus name=a0287ef6-b8f5-4482-b9de-73e363777dc5
```
and some instances of
```
2016-05-24T19:21:55.774562Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=info msg="discoverd peers" app=postgres component=peer peers=0
2016-05-24T19:21:55.776528Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=dbug msg=moving app=postgres component=peer
2016-05-24T19:21:55.789262Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=info msg="starting state evaluation" app=postgres component=peer fn=evalClusterState
2016-05-24T19:21:55.801284Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=warn msg="would takeover but no async peers present" app=postgres component=peer fn=startTakeover reason="sync gone" min_wal=1/C5000060
2016-05-24T19:21:55.805260Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=dbug msg="at rest" app=postgres component=peer fn=rest
2016-05-24T19:21:55.835469Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=info msg="discoverd peers" app=postgres component=peer peers=1
2016-05-24T19:21:55.869113Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=dbug msg=moving app=postgres component=peer
2016-05-24T19:21:55.877245Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=info msg="starting state evaluation" app=postgres component=peer fn=evalClusterState
2016-05-24T19:21:55.882305Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:55+0000 lvl=dbug msg="at rest" app=postgres component=peer fn=rest
```
and
```
2016-05-24T19:22:06.721627Z app[postgres.ip1010040204-7007e943-e631-4c2b-942d-44c891aa8c7f]: t=2016-05-24T19:21:59+0000 lvl=eror msg="heartbeat failed" component=discoverd service=postgres addr=100.100.97.147:5432 err="unknown_error: Something went wrong"
```

Collecting debug-info from the nodes has also proven exceedingly difficult. Here's some collected logs from the postgres app: https://bazaarvoice.box.com/s/xobtr4duu42tev62nmjtlnlgum0tyvl0

Even if we remove the load from Postgres, this isn't a good failure mode to have.

**Comment by titanous** [comment]
@josephglanville This sticks out to me, I haven't seen it in the other logs but we should take a closer look:

> FATAL: highest timeline 7 of the primary is behind recovery timeline 8

**Comment by temujin9** [comment]
Another apparent instance of this, caught earlier in the life-cycle: https://bazaarvoice.box.com/s/2eve8ijx99g6w72b0c6o307jgrrjxe5v are the postgres logs.

Of particular interest:
```
2016-05-24T23:02:33.174228Z app[postgres.ip101003610-ebe5670b-84bb-4a35-a561-0d64b56146c6]: pg_basebackup: could not create directory "/data": Permission denied
```

**Comment by titanous** [comment]
@temujin9 If the host is still around, can you retrieve the `/var/log/flynn/flynn-host.log` file from 10.100.36.10?

**Comment by temujin9** [comment]
Here's the debug-info: https://bazaarvoice.box.com/s/ftn6dgetxnt51v23bqemx0aat71jrchx

**Comment by temujin9** [comment]
Here's the flynn-host.log: https://bazaarvoice.box.com/s/6cy2posef6xjh4p7755l8l2zutkmvjzw

**Comment by temujin9** [comment]
Another instance happened this morning. Similar complaints about lack of /data as the last logs. https://bazaarvoice.box.com/s/doolbv47sbitnacvsc2sfi4m947uq79t has debug-info and the full flynn-host.log from all nodes.

**Comment by titanous** [comment]
This is #2725. We're putting together a plan to track it down.

**Comment by philiplb** [comment]
Hi, every now and then (like once a week), the Flynn status goes unhealthy for a few minutes: It's always the postgres and it happens during the cluster backup. Doesn't bother me that much, but might be interesting for you as I've seen that you lately dealed with the health of the postgres a bit.
