### ISSUE TITLE
Deployment rollback ends up scaling app down

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2807]
I'm not sure exactly what caused this, but a failed deploy on @tjboring's cluster ended up rolling back to a null formation instead of the correct previous scale.

Here are the logs from the worker and the recent events for the app: https://gist.github.com/titanous/330f393f20d66b8e508601d7964e4e67

I have the rest of the cluster logs, let me know if you need anything else.

**Comment by lmars** [comment]
@titanous here is the chain of events:

* scaled up the new release and all jobs started
* scaled down the old release but did not get all the down events
* marked the deploy as failed but did not trigger a rollback as it doesn't really make sense to (see [this comment](https://github.com/flynn/flynn/blob/master/controller/worker/deployment/all_at_once.go#L71-L80))
* deploy retried, detected no old jobs running but new release only partially running (missing a `clock` job)
* scaled the new release up but failed to get an `up` event for `clock`
* rolled back to the old release, which was already scaled down by the previous failed deploy

So, whilst the initial deploy encountered an error, it was effectively finished, so I am going to modify the worker to not retry a deploy in that case.
