### ISSUE TITLE
cli: Show process tags in output of `flynn scale`

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2809]
Process type tags can be set with the `scale` command (e.g. `flynn scale db=1,disk=ssd`) but they should also be shown when running `flynn scale` (i.e. without arguments).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
