### ISSUE TITLE
NodeJS deployment terminating abruptly

### ISSUE THREAD

**Issue by thomasmodeneis** [flynn/flynn#2811]
Hi,

I'm trying to get a NodeJS package deployed to Flynn and is terminating with errors, but the very same works for Heroku:

This is the error I see in the logs:
```
remote: /tmp/buildpacks/000004_heroku-buildpack-nodejs/lib/dependencies.sh: line 1:   195 Killed                  npm install --unsafe-perm --userconfig $build_dir/.npmrc 2>&1
```

I'm not sure what's going on, any ideas ?

**Comment by titanous** [comment]
Are there a lot of dependencies? What are the log lines the precede that error? It's possible that the build job is running out of memory. The latest nightly release has support for changing the resource limits for slugbuilder jobs.

**Comment by thomasmodeneis** [comment]
There are quite a few dependencies, this project uses ReactJS + Babel + Webpack + Bower.
The strange thing is that there is no error.

Is there a way for me to test this deployment with more memory ?

**Comment by titanous** [comment]
Yep, if you are running a release with 438fe5a8e5f09e179ceb229ca990947368e0a933, you can do:

```text
flynn limit set slugbuilder memory=2GB
```

**Comment by thomasmodeneis** [comment]
Hi @titanous 
I've updated to `v20160520.0` and executed the re-deploy with the recommended configuration and it works like dream.
Thank you very much for the support!!
Thomas.
