### ISSUE TITLE
High disk usage without that many deployments

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2812]
Hi,

my three node cluster has 100GB of space on each node. I have 12 deployed applications with a backup of around 5GB. Each applications has like one or two deployments from fresh git repositories without history.

The first node has only 24GB space left.
I wonder if that is expected?
For example, the folder /var/lib/docker alone is 22GB.

Second node: 38GB left
Third node: 37GB left

Are there any "leaks" I can manually clean up?

**Comment by titanous** [comment]
Check if there is space available in ZFS with `sudo zfs list`.

**Comment by philiplb** [comment]
45GB available, looks good. :)
Got it, I remember that this is the sparse file.
Thanks @titanous

**Comment by wuyouguo** [comment]
I want to unsubscribe this thread。

发件人: Jonathan Rudenberg [mailto:notifications@github.com]
发送时间: 2016年5月11日 22:15
收件人: flynn/flynn
主题: Re: [flynn/flynn] High disk usage without that many deployments (#2812)


Check if there is space available in ZFS with sudo zfs list.
