### ISSUE TITLE
Router needs security controls

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2815]
The router should be able to chose whether to route to an application based on network criteria, such as what address the original request came from. For maximum value, it should respect (or allow separate criteria for) X-Forwarded-For.

That will allow me to expose a cluster to the internet, but only allow controller actions from within our networks.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
