### ISSUE TITLE
Jobs stuck "starting" after deploy

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2820]
I bootstrapped a new cluster yesterday and deployed an app on top of it. The second deployment failed (the step after the release creation timed-out), and now I have 8 jobs stuck in a "starting" state for this app that I can do nothing about (I can't kill them). Now I probably have to start a new cluster again.

Here are the steps I followed to get there:

- Bootstrap new cluster (version `v20160511.1`).
- Create new app, configure env variables.
- Deploy new app for the 1st time, everything works as expected.
- Make changes to the app and deploy again, the deploy timeouts after the release is created.
- I now have 8 jobs stuck in a "starting" state.

The cluster debug information is here: https://gist.github.com/836ce1e0c521a4a2b8cc125c1985c128

**Comment by titanous** [comment]
We'll look into this. Deleting the app should clear out the "starting" instances.

**Comment by quentez** [comment]
I tried deleting the app, but it didn't get rid of the "starting" jobs. 
Could the original timeout be because of the size of the app? (The slug is 88MB).

**Comment by titanous** [comment]
It's probably because the app took too long to start. You could try changing the timeout:

```text
flynn -a controller pg psql -- -c "UPDATE apps SET deploy_timeout = 1000 WHERE name = 'front-main'"
```

**Comment by quentez** [comment]
I'll make sure to try that. I can understand the timeout and I don't mind having to tweak the system to make that work. What I don't find reassuring is that it's so easy to get the cluster in an unpredictable state as soon as something doesn't go as planned.

**Comment by titanous** [comment]
@lmars please look into this.

**Comment by lmars** [comment]
@quentez can you collect debug info on one of the nodes with the stuck "starting" jobs? So either `ip172313018` or `ip172314196`.

**Comment by lmars** [comment]
@quentez so the deploy timed out because the jobs never transitioned from the starting state (the deploy waits for all jobs to come up), but I can't really diagnose why that was the case without the host logs from those hosts I mentioned, will you be able to provide them? I just need `/var/log/upstart/flynn-host.log`.

**Comment by lmars** [comment]
@quentez I wonder if processes are getting killed by the kernel due to memory exhaustion and flynn-host is not realising this, can you also check for OOM related logs in `/var/log/syslog` (e.g. lines containing `Killed process` or `oom-killer`)?

**Comment by quentez** [comment]
@lmars Sorry for the lack of reactivity. I wasn't able to get the logs as I needed to boot a new cluster, and since we're currently testing our deployment on ~20 nodes it can be quickly expensive to keep failed clusters around. I'll make sure to collect the logs you mentioned if it was to happen again.

**Comment by titanous** [comment]
Looks like this was fixed by #2833, please open a new issue if you see this again. We're also adding more information on the pending state in #2982.

**Comment by evantahler** [comment]
@titanous is there a better way to configure the app's start timeout than the SQL listed above?

**Comment by titanous** [comment]
```
flynn deployment timeout 300
```

**Comment by evantahler** [comment]
Ya'll are the best
