### ISSUE TITLE
Tags are missing in a cluster restored from backup

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2825]
Hi,

yesterday I restored a cluster from backup. Everything was restored fine except the tags of the nodes. They where missing.
I looked into an exported tar and they are not listed within the flynn.json.

**Comment by titanous** [comment]
Host tags are associated with the host, you'd need to apply them to the hosts before doing the restore. We can't predict if you're going to restore to the same hosts (in fact, most people don't).

**Comment by philiplb** [comment]
This makes sense. So what I really want is to extend our backup script a bit so it stores the tags as well and a small script to restore them. Thank you. :)
