### ISSUE TITLE
Upon successful deploy, get error message "failed to push some refs"

### ISSUE THREAD

**Issue by paul-e-cooley** [flynn/flynn#2827]
After deploying an application to a cluster, the application starts up properly and begins serving requests as expected. However, at the end of the phase, I receive the following error:

`=====> Waiting for web job to start...
remote: Timed out waiting for job events. Waited 20 seconds.
remote: expected: map[web:map[up:1]]
remote: actual: map[web:map[pending:1 starting:1]]
To https://git.flynn-prod-us-east-1.nexus.bazaarvoice.com/bazaar-hubble.git
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.flynn-prod-us-east-1.nexus.bazaarvoice.com/bazaar-hubble.git'
Command [git -c http.sslVerify=false push -f prod-us-east-1 HEAD:refs/heads/master] failed: exit status 1
/home/temujin9/.gvm/gos/go1.4/src/github.com/bazaarvoice/flynn-ops/bvflynn/output/output.go:20 (0x80a19)
/home/temujin9/Projects/Bazaarvoice/code/flynn-ops/bvflynn/.tup/mnt/@tupjob-106/home/temujin9/Projects/Bazaarvoice/code/flynn-ops/bvflynn/push.go:80 (0xd1ef)
/home/temujin9/.gvm/pkgsets/go1.4/global/src/github.com/spf13/cobra/command.go:534 (0x5d37d)
/home/temujin9/.gvm/pkgsets/go1.4/global/src/github.com/spf13/cobra/command.go:617 (0x5d8f9)
/home/temujin9/Projects/Bazaarvoice/code/flynn-ops/bvflynn/.tup/mnt/@tupjob-106/home/temujin9/Projects/Bazaarvoice/code/flynn-ops/bvflynn/bvflynn.go:61 (0x3574)
/home/temujin9/.gvm/gos/go1.4/src/runtime/proc.go:63 (0x218b6)
/home/temujin9/.gvm/gos/go1.4/src/runtime/asm_386.s:2287 (0x41aa1)
`
Is there a way around this error and get the proper information from the deployment phase as a success?

**Comment by paul-e-cooley** [comment]
@temujin9

**Comment by titanous** [comment]
@paul-e-cooley I'm really sorry this issue didn't get a response, it looks like I didn't get an email from GitHub for it. Did it get sorted out?

**Comment by paul-e-cooley** [comment]
No, this is still an issue.

**Comment by titanous** [comment]
The error points to a timeout during the deploy, have you tried bumping the deploy timeout?

**Comment by temujin9** [comment]
All our deploys currently bump timeout considerably.

Cheers,

Nathaniel Eliot

**Comment by titanous** [comment]
The timeout in that error message is 20 seconds, and according to the code is supposed to be taken from the `deploy_timeout` field, what is the actual timeout for the app?

**Comment by temujin9** [comment]
We execute "UPDATE apps SET deploy_timeout = 600 WHERE name = '$app'" before every push, and examination of the DB shows that is working.

**Comment by titanous** [comment]
Fixed in #2889.

**Comment by temujin9** [comment]
@paul-e-cooley This is now be deployed on all our endpoints.
