### ISSUE TITLE
controller-scheduler and controller-worker unhealthy

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2830]
Hi,

currently the controller-scheduler and controller-worker are unhealthy.
The log from the scheduler says for example:

> t=2016-05-13T23:45:03+0000 lvl=warn msg="formation event stream disconnected" component=scheduler fn=streamFormationEvents err="Server error: controller: resource not found"
> t=2016-05-13T23:45:03+0000 lvl=info msg="connecting formation event stream" component=scheduler fn=streamFormationEvents

When it reported unhealthy, i stopped all controller processes and ran flynn-host fix. This didn't solve the problem.

Luckily, all deployed applications are still fine.

How can I recover?

Here is a nodes debug info:
https://www.philiplb.de/misc/2016-05-14-0155-flynn-host-debug.tar.gz

**Comment by philiplb** [comment]
Restored from backup. Will reopen if that happens again.

**Comment by lmars** [comment]
@philiplb FYI this looks like the bug I have proposed a fix for in #2835.

**Comment by philiplb** [comment]
@lmars 
Nice, thank you. :)
