### ISSUE TITLE
Flannel unhealthy after restore from backup

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2836]
Hi,

when I restore a cluster from backup, I often get flannel unhealthy. The restore hangs at the point 

> status-check status

until I flynn-host stop flannel so it restarts. Afterwards, everything seems to be good.

Here are the debug logs from the fresh cluster:

https://www.philiplb.de/misc/2016-05-16-1930flynn-host-debug.tar.gz

**Comment by titanous** [comment]
Is this different from #2715?

**Comment by philiplb** [comment]
I don't think so.
