### ISSUE TITLE
blobstore/postgres fail after backup restore

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#2840]
Attempting to create a cluster from a backup seems to consistently fail with flynn version v20160516.0. I have attempted 3 times and it's failed each time with the same error.

https://gist.github.com/anonymous/b8f1770fc797e80a95ea029e4ad77719

@lmars @titanous

**Comment by titanous** [comment]
Fixed in #2838. I'm rolling a release now.

**Comment by tianx2** [comment]
Thanks @titanous I'll close this and wait for the new release.
