### ISSUE TITLE
Release channel UI

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2844]
It is not currently clear how to determine what the stable / nightly versions are, and what features / bug fixes they include.

We should expose a UI (perhaps a web interface at `releases.flynn.io`) which shows the following:

* the current stable / nightly version
* a changelog containing features / bug fixes which are included in a release since the last version (perhaps a list of pull requests)

The changelog would require us to track historic versions of a channel (we currently just store the current channel version) so we could determine the changes since the last version on that channel.

We could take this a step further and have a bot which adds comments to GitHub pull requests when they are released to the stable / nightly channel, so anyone landing on a PR knows the relevant versions they need to benefit from the change.

As an FYI, here is how I currently determine the current stable / nightly version using [`tuf-client`](https://github.com/flynn/go-tuf/tree/master/cmd/tuf-client) (requires golang to install):

```
$ go get github.com/flynn/go-tuf/cmd/tuf-client

$ tuf-client init https://dl.flynn.io/tuf <<< '[{"keytype":"ed25519","keyval":{"public":"6cfda23aa48f530aebd5b9c01030d06d02f25876b5508d681675270027af4731"}}]'

$ tuf-client get https://dl.flynn.io/tuf /channels/stable
v20160512.0

$ tuf-client get https://dl.flynn.io/tuf /channels/nightly
v20160519.0
```

**Comment by lmars** [comment]
A first pass at the UI is available at https://releases.flynn.io.

Some work is needed on the design (I am no designer :smile:) but the relevant information is all there.

The source is available at https://github.com/flynn/flynn-releases.

**Comment by lmars** [comment]
Oh and you can get the same information as JSON from https://releases.flynn.io/api/channels

**Comment by josephglanville** [comment]
That is awesome. 👍
