### ISSUE TITLE
Add configuration option for router header timeout

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2848]
Hi,

there seems to be a limit if a request takes longer than 2 minutes? Then I get an HTTP 503 back.
Can this value be tweaked per application?
I have a legacy one sometimes taking that long.

**Comment by titanous** [comment]
This is a timeout waiting for the status/headers. Currently it is hard-coded.

**Comment by philiplb** [comment]
Ok, good to know, thank you.

**Comment by tjboring** [comment]
I experienced this today also:

2016-05-19T19:29:50.132577Z app[app.ip1002170-bf6b92b1-55b6-4e9f-a5cb-80293056f517]: t=2016-05-19T19:29:50+0000 lvl=eror msg="unretriable request error" app=router request_id=0be3964c-7c0c-4f08-8858-45115b1b8885 client_addr=54.163.87.5:46810 host=git.7p5p.flynnhub.com path=/contract-dev.git/git-receive-pack method=POST backend=100.100.90.9:5000 err="net/http: timeout awaiting response headers" attempt=0

**Comment by tjboring** [comment]
I'm consistently getting this error trying to do a push from circleci. I'm using the workaround for large repos mentioned in https://git.io/vwNop.

I'm not getting it when doing a push from my laptop, however.

**Comment by philiplb** [comment]
Hm, I meant normal HTTP requests against a running application, not the deployment.

**Comment by titanous** [comment]
I've bumped the timeout to 10 minutes in lieu of a per-route tunable.

**Comment by philiplb** [comment]
This one application where we ran into this is now a bit optimized and is running fine in Flynn and 10 minutes "ought to be enough for anybody.". :) So I close this for now?
