### ISSUE TITLE
Git push takes 4x long on Flynn compared to Heroku

### ISSUE THREAD

**Issue by tjboring** [flynn/flynn#2849]
We're seeing that the time for a git push on Flynn is 8+ minutes, compared to 2+ on Heroku. I've checked these numbers and they are consistent whether the push is from circleci or locally from my laptop.

It would be nice if this time could be reduced to be on par with Heroku.

**Comment by jvatic** [comment]
@tjboring Can you provide some more details such as what buildpack is being used? A repo to reproduce this case would also be great.

**Comment by titanous** [comment]
I suspect most of the time difference is in our git repo handling, which could use some optimization. #2829 should improve this somewhat. I think we'll end up adding support for S3 so that large blobs don't need to go into postgres (#2622).

**Comment by tjboring** [comment]
Currently, we're only using one buildpack:
https://github.com/heroku/heroku-buildpack-ruby

**Comment by tjboring** [comment]
I just cloned that buildpack from GitHub to my laptop and it took 2s. Any way that operation could be cached?

**Comment by titanous** [comment]
@tjboring Sorry for the late reply, I missed the email for this. Cloning the buildpack is not currently cached if you are setting `BUILDPACK_URL`, though we could explore doing so.

**Comment by tjboring** [comment]
@titanous disregard my previous comment. 2s out of 10m is insignificant. :(

Still, anything that can be done to reduce the amount of time it's taking to do a `git push` is welcome.

**Comment by titanous** [comment]
@tjboring I forgot to ask, what EC2 instance type are you using?

**Comment by tjboring** [comment]
Initially m3.medium. latest cluster is m3.large. I'm considering trying one
of the memory optimized ones too.

**Comment by lmars** [comment]
@tjboring when doing the push, do you have a sense of which steps are taking a long time? We have a demo Ruby app which takes about 30s to deploy:

```
$ time git push flynn master
Counting objects: 19, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (16/16), done.
Writing objects: 100% (19/19), 2.98 KiB | 0 bytes/s, done.
Total 19 (delta 2), reused 0 (delta 0)
-----> Building ruby...
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.1.2
-----> Installing dependencies using bundler 1.11.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/..........
       Fetching version metadata from https://rubygems.org/..
...
       Bundle completed (12.80s)
       Cleaning up the bundler cache.
       
-----> Discovering process types
       Procfile declares types -> web
       Default process types for Ruby -> rake, console, web
-----> Compiled slug size is 18M
-----> Creating release...
=====> Application deployed
=====> Waiting for web job to start...
=====> Default web formation scaled to 1
To https://git.1.localflynn.com/ruby.git
 * [new branch]      master -> master

real    0m31.358s
user    0m0.028s
sys     0m0.004s
```

Note the `Bundle complete` line which has an indication of how long `bundle install` took.

**Comment by tjboring** [comment]
@lmars interesting update: i built a new cluster last week, with m3.large AWS nodes, and git push has "magically" gotten faster. (Well, ok, it's not really magic! ;-)

At any rate, the app the we were deploying and was talking on avg. 10+ min, is now taking ~3 min. 

FWIW, the slugsize on the app is 87M.

**Comment by lmars** [comment]
@tjboring ok that's good news, so did you determine which part of the deploy was taking the most amount of time? What did the `Bundle completed` line show?

**Comment by titanous** [comment]
Looks like this was resolved.

**Comment by tjboring** [comment]
Yes, since switching to the new cluster and upgrading to the latest version of Flynn and using s3 for the blobstore backend, deploys are taking somewhere between 2-4 minutes. So much more reasonable. Thanks!
