### ISSUE TITLE
Deployment failing multiple times before succeeding

### ISSUE THREAD

**Issue by ecahill** [flynn/flynn#2850]
During a deployment, we sometimes have to try 3 or 4 times because we keep seeing the error below before it finally succeeds. 

```------------------------------------------------------------------
Configuring prod-seller-ratings-display for prod-us-east-1 on host
------------------------------------------------------------------
web process type failed to start, got down job event

Command [flynn -c prod-us-east-1 -a prod-seller-ratings-display env set BVFLYNN_APP_SCOPE=prod AWS_REGION=us-east-1 BVFLYNN_VPC=prod BVFLYNN_REGION=us-east-1 BVFLYNN_ENDPOINT=prod-us-east-1 BVFLYNN_ENDPOINT_SCOPE= BVFLYNN_APP=prod-seller-ratings-display] failed: exit status 1
```

@temujin9 can provide more information from the Flynn logs

**Comment by temujin9** [comment]
Debug info from the cluster in question:
https://gist.github.com/9fe0810a5392f23ed64b2748b04fa4b7
https://gist.github.com/748478b6ac06949500a24bc393214774
https://gist.github.com/296601945549812cec67e9eb6d3e35a5
https://gist.github.com/fbd4587d5f9fce56af376b8148dd5499

**Comment by titanous** [comment]
It looks like there were several failures while starting jobs on 10.100.53.100, but it doesn't look like the `/var/log/flynn/flynn-host.log` file from that host was posted.

**Comment by titanous** [comment]
Has this happened again? Without the log from the host I was unable to diagnose the cause of the failure.
