### ISSUE TITLE
Cancelling a "git push" doesn't cancel the deploy

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2852]
When a buildpack is running after a `git push`, killing the local process won't stop it from running and deploying the new code. This makes it difficult to cancel a deploy if we realize that there's a problem (we'd have to kill the slugbuilder job manually). Is there a way to detect from within a `post-receive` hook whether the disconnection from the client was intentional or not?

**Comment by titanous** [comment]
I have a branch that mostly implements this, but ran into some issues propagating the disconnect all the way through. I think that Go 1.6 will solve this, so it's blocked on #2558 which needs some more testing.

**Comment by thomasmodeneis** [comment]
I ran into the same problem, but I cancelled 3 times a deployment in sequence, and it caused the cluster to be completely not responsive and stop accepting a "git push" at all. 
Is this the same behaviour for you ?
