### ISSUE TITLE
"flynn-host promote" gets "Something went wrong"

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2853]
Running `flynn-host demote` and then `flynn-host promote` from a replacement node in a formerly 3 node cluster results in

"20:49:26.782596 host.go:138: unknown_error: Something went wrong"

https://gist.github.com/49ff715aece8e045d534a99b0884552a is the debug-info from the newest node. 

I'm gonna try to do it `promote` and then `demote`, in case going to two nodes for consensus is causing the issue.

**Comment by josephglanville** [comment]
Something seems not right here.

Can you confirm the exact steps you took to get here?

The expected order of events is something like this:

1. Node goes down or existing node needs replacing.
2. If node is up, `flynn-host demote` is used to remove it from the Raft consensus.
3. A new node is added and `flynn-host promote` is used to join consensus.
4. `flynn -a discoverd env set DISCOVERD_PEERS=<list of ips with ports>` is used to make the changes to the consensus set permanent.

**Comment by temujin9** [comment]
That's exactly the steps I took, on a freshly restored three node cluster which I forced a node replacement on. It failed at step 3.

**Comment by temujin9** [comment]
Replicated on a new cluster, both before and after doing the `demote`. https://gist.github.com/531ff98194a6901e2455c5a7eaa2ddf9

**Comment by temujin9** [comment]
As the above closed ticket indicates, this is triggered on a 3-node cluster, but not on a 5 node.

**Comment by josephglanville** [comment]
I wasn't able to reproduce this on AWS either. I may need to catch you on IRC at some point to further discuss the exact steps to trigger it and any differences there are compared to cluster created by installer.

**Comment by titanous** [comment]
Was this fixed by #2919?

**Comment by temujin9** [comment]
This particular issue does not recur, now that I've corrected the order of operations. I am now having a different set of issues, which I will ticket separately.

**Comment by SalvoLunar** [comment]
Hi,

I'm getting this error when trying to promote a new host by running this command on the leader node:

flynn-host promote 10.8.169.19

10:41:54.359015 host.go:166: Post http://10.8.169.19:1111/raft/promote: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Port 1111 is open on the new node and so are 443 and 80 for both TCP and UDP.
I'm not sure what to do next.

Can you advice?

Thanks,
Salvo
