### ISSUE TITLE
Since Flynn does not have --buildpack, how can I deploy Backbone apps?

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#2863]
[there is](https://github.com/GabKlein/heroku-buildpack-backbone) a buildpack for heroku that allows me to deploy backbone apps. how can I do the same for Flynn?

**Comment by jvatic** [comment]
`flynn env set BUILDPACK_URL="https://github.com/GabKlein/heroku-buildpack-backbone.git"`

**Comment by hadifarnoud** [comment]
it looks like this buildpack just use Node anyway.
