### ISSUE TITLE
Git push failing with a 503 error

### ISSUE THREAD

**Issue by tjboring** [flynn/flynn#2864]
This behavior happened last Friday (5/20), and persisted for 1h or more. I tried to push again a couple hours later, and it worked just fine.

I've collected the debug logs from each of the nodes in the cluster. Ping me on IRC and I'll paste the links to you.

**Comment by hadifarnoud** [comment]
I keep getting `fatal: The remote end hung up unexpectedly` error. is this the same issue?

**Comment by tjboring** [comment]
Yes. Same thing.

**Comment by alandickey** [comment]
This is happening to me today, 5.27.

**Comment by titanous** [comment]
@alandickey Please provide the logs from your cluster obtained by running `sudo flynn-host collect-debug-info`.

**Comment by alandickey** [comment]
I don't understand how to do what you request.

At any rate, I just re-did the push that failed repeatedly earlier in the
day, and it worked:

adickey@afd-kudev64:~/git/primes$ git push
Username for 'https://github.com': alandickey
Password for 'https://alandickey@github.com':
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 241 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
To https://github.com/alandickey/primes.git
   d676a38..2befb30  master -> master

Thank you.

Alan F. Dickey
mailto:alan.dickey@gmail.com
AT&T cell: 908-334-0932
Google Fi: 908-376-9295

**Comment by hadifarnoud** [comment]
@titanous there is no docs on how to install flynn-host or how it works? I can provide debug info

**Comment by tjboring** [comment]
Flynn-pilot is installed on the nodes. Ssh to them and run `sudo flynn-host
collect-debug-info`.

**Comment by titanous** [comment]
I believe that the root cause of this was sorted out in IRC, please open a new issue if you see it again.
