### ISSUE TITLE
add a private networking option in the installer for DigitalOcean

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#2868]
I installed Flynn alongside two ElasticSearch and Mongo servers which listen on a private network for security reasons.

I discovered Flynn installer does not enable private networking during installation. took me a while to figure that out.

We had to enable the private networking and setup the interface separately. It would be nice to have it done automatically during installation

**Comment by titanous** [comment]
On DigitalOcean the private network does not provide any security benefits (the "private" IP is accessible to all VMs in the same datacenter). Is there a reason to use the private network?

**Comment by hadifarnoud** [comment]
I did not know that. have to setup a firewall
it still is a layer of security if you close your DB from internet. it would be nice to have the option

**Comment by titanous** [comment]
So far I'm not convinced that the very marginal/arguable security impact is worth the additional code to handle this.

**Comment by hadifarnoud** [comment]
fair enough

**Comment by dutchakdev** [comment]
@titanous private network gives a benefit as speed and free traffic.

**Comment by hadifarnoud** [comment]
@dutchakdev it's probably best to write a PR yourself. they have more important features to release than private networking imho.

**Comment by dutchakdev** [comment]
@hadifarnoud yes. Just listed the benefits. Cluster through an external network is not a good solution.
