### ISSUE TITLE
Adding flynn hosts from a base image for auto-scaling

### ISSUE THREAD

**Issue by eyalrosen** [flynn/flynn#2870]
Hello,
I'm trying to auto-scale my flynn cluster.
Is it possible to create a base image of a flynn server and than to create instances of it on-demand?
Thanks!

**Comment by lmars** [comment]
@eyalrosen we create both EC2 and VirtualBox images for each Flynn stable release. Details can be found at:

* EC2: https://dl.flynn.io/ec2/images.json
* VirtualBox: https://dl.flynn.io/vagrant/flynn-base.json

These images are created using [Packer](https://packer.io) with [these templates](https://github.com/flynn/flynn/tree/master/util/packer) so you can create your own images using those if you wish.

If you have used `flynn install` with AWS, then you will have a CloudFormation stack that you could modify for auto scaling.

**Comment by eyalrosen** [comment]
Awesome. Thanks @lmars !
