### ISSUE TITLE
after release, old version keeps running and app is serving multiple instances 

### ISSUE THREAD

**Issue by thomasmodeneis** [flynn/flynn#2872]
Hi,

I'm running into a strange state here, I have one app with two versions running at same time and I can't figure out a way to remove the old one without having to get the whole app deleted/recreated.

When I run flynn ps I get this two versions:

```
$ flynn ps
ID                                                     TYPE  STATE  CREATED         RELEASE
flynn14638178630-(...)-5d37889d4573  web   up     17 minutes ago  a39e1195-(...)-8469f19f9bf8
flynn14638178630-(...)-146939ef8bb4  web   up     5 minutes ago   5dd4ffd3-(...)-113ffb5a6234
flynn14638178632-(...)-acf832eaa32f  web   up     4 minutes ago   5dd4ffd3-(...)-113ffb5a6234
flynn14638178631-(...)-8880bd18cb7f  web   up     4 minutes ago   5dd4ffd3-(...)-113ffb5a6234
flynn14638178631-(...)-a1ca1d71de8f  web   up     2 minutes ago   a39e1195-(...)-844b-8469f19f9bf8
```

```
a39e1195-(...)-8469f19f9bf8  24 minutes ago
(...)
5dd4ffd3-(...)-113ffb5a6234  16 hours ago
```
As you can see there are two apps running, release `5dd4ffd3` and `a39e1195`, and any attempt to kill the old version `5dd4ffd3` happens to have the same old version restarted! :|

I'm really not sure what is going on, does anyone have any advices on what can I do to get this sorted ?

Thank you.

**Comment by thomasmodeneis** [comment]
so I've forced the scale to 0 for that version and that worked.
```
flynn scale --release=5dd4ffd3-b2da-(...)-113ffb5a6234 web=0
```

I'm still not sure what caused this behavior.

**Comment by josephglanville** [comment]
@thomasmodeneis Could you post the debug info collected with `flynn-host collect-debug-info` for this cluster?

**Comment by thomasmodeneis** [comment]
Sorry mate, 

I've tried to convince others about releasing internal logs to public but the main argument was that this goes straight to github as a gist and will open our internals to public.
Is there a way to collect this info and zip sending like FTP or something ?

Thanks and sorry for taking very long for answering your request.

**Comment by josephglanville** [comment]
@thomasmodeneis the collect-debug-info has a tar output option. If you use this you can sanitize the archive first. If you are still not super comfortable posting to GitHub or IRC you can email me at joseph@flynn.io.

We plan to make collect-debug-info only collect logs for system applications which will make the gists/archive to be much less sensitive.

**Comment by titanous** [comment]
We have new debug code in the latest version and this looks like the same issue as #2895, so I'm going to close it in favor of that issue.
