### ISSUE TITLE
how to setup DNS for multiple apps using same domain on /directory

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#2878]
I have 3 apps. one uses kamva.ir/blog, another one uses kamva.ir/admin and one more that uses kamva.ir

how should I setup my DNS? I can CNAME to just one of them

**Comment by titanous** [comment]
CNAME `kamva.ir` to your Flynn cluster, HTTP paths are not considered when doing DNS lookups.

**Comment by hadifarnoud** [comment]
this is what I did on Digital Ocean for `kamva.ir`:

I set A record for @ to my Flynn cluster IP.
I also set CNAME for * to `eg55.flynnhub.com`

now, `http://shop-admin.eg55.flynnhub.com` works just fine, but `http://kamva.ir/admin` gives a 404 Not Found.

output of `flynn route`:

```
ROUTE                              SERVICE         ID                               STICKY  LEADER  PATH
http:kamva.ir/admin                shop-admin-web  http/a2b18faf-2786-4270-ab4c-***  false   false   /
http:shop-admin.eg55.flynnhub.com  shop-admin-web  http/b9d87af5-c94b-46db-***-595f  false   false   /
```

what am I doing wrong?

**Comment by titanous** [comment]
How did you add the route? Did you use the dashboard? There may be a bug there. Try deleting the route and re-adding it with the CLI.

**Comment by hadifarnoud** [comment]
yes I used the dashboard. It seems to be working now. PATH correctly shows /admin

**Comment by titanous** [comment]
@jvatic please fix this.
