### ISSUE TITLE
provisioning postgres does not set env 

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#2879]
when I provisioned a postgres db for my node app, it failed to set environment valuables,  says `Error setting app env: undefined`

and it does not allow me to set the variables myself. says `undefined:1 Uncaught (in promise) Timed out waiting for deployment completion`

I restarted the whole server, it did not help. I removed the database and did it again, still the same.

flynn-host debug info: https://gist.github.com/8c1323586dd36930884418c951fd97b7

**Comment by hadifarnoud** [comment]
possibly related to #2822

**Comment by hadifarnoud** [comment]
when I scale down web worker to 0, it works fine. interesting

**Comment by lmars** [comment]
@hadifarnoud this looks like the deployment (which happens when you set an environment variable) is timing out on the client side, but it most likely succeeded after a while. Can you check if the environment variables exist using the CLI (i.e. `flynn env`)?

We have a number of issues relating to deployment timeouts, we need to improve the situation.

**Comment by hadifarnoud** [comment]
the env were not set. I did check with CLI and the app was not working because of env were not set.

**Comment by lmars** [comment]
@hadifarnoud ok, can you try setting the environment variables using the CLI (`flynn env set KEY=VAL`)? Please post the full output here if it fails.

**Comment by hadifarnoud** [comment]
the output was the same `Error setting app env: undefined`

**Comment by mathiasjakobsen** [comment]
This is still a problem with the latest version of Flynn. But, if you scale down to 0 web workers, both creation and deleting of a resource succeeds without any errors, and a lot faster than with 1+ workers.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
