### ISSUE TITLE
Router should have option to rewrite path

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#2886]
I installed a blog on domain.com/blog. It gives me 404 error but router does go inside my app. I can see the footer of 404 error is my blog's. 

when I change the domain to blog.domain.com, everything works fine. I change the URL base in my blog config and works just fine.

If it was a normal nginx server, I could serve it over reverse proxy on /blog. [more info](https://www.allaboutghost.com/how-to-install-ghost-in-a-subdirectory/)

wouldn't be useful if router worked in the same manner?

**Comment by philiplb** [comment]
This should do it for you:
https://github.com/flynn/flynn/issues/2730

**Comment by hadifarnoud** [comment]
@philiplb please look at "more info". Ghost app needs a reverse proxy to work. and I'm using nginx

**Comment by philiplb** [comment]
#2730 should be the same issue you are having. You can configure some URL rewriting in your nginx.

**Comment by hadifarnoud** [comment]
ok. can you please elaborate on how to add URL rewriting in Flynn? couldn't find anything in docs

**Comment by philiplb** [comment]
Via a custom nginx config: https://devcenter.heroku.com/articles/custom-php-settings#web-server-settings

**Comment by hadifarnoud** [comment]
cool. this is for PHP I guess. what would be the Node.js equivalent?

**Comment by hadifarnoud** [comment]
I think it's needed to be handled by Flynn as the other issue mentions. @lmars

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
