### ISSUE TITLE
error: timed out waiting for 3 hosts to come online (currently 0 online)

### ISSUE THREAD

**Issue by ouyangjia** [flynn/flynn#2887]
HELP!

debug information uploaded to: 
https://gist.github.com/2144abb4ebf1cec6c89ac7b7291c13eb 

CLUSTER_DOMAIN=demo.jianyiyun.net flynn-host bootstrap --min-hosts 3 --discovery https://discovery.flynn.io/clusters/8adc2748-a28e-4ac1-aafe-d7ffbfe0167f

the error is:
14:58:30.762616 check online-hosts
15:00:31.044956 check online-hosts error: timed out waiting for 3 hosts to come online (currently 0 online)

The following hosts were discovered but remained unreachable:

**Comment by josephglanville** [comment]
It looks like you already previous run the cluster bootstrap before. It shouldn't need to be run again.
Can you explain further how your cluster got into this state?
Specifically the steps you took to install Flynn and what you have done since then.

**Comment by ouyangjia** [comment]
Thanks, I solved it.

**Comment by andyjeffries** [comment]
Getting the same problem, @ouyangjia how did you solve it?

**Comment by andyjeffries** [comment]
Typically, I just got round it too...

For me, I literally just did:

```
curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn
bash /tmp/install-flynn --clean
```

And re-inited as a fresh installation.

**Comment by hadifarnoud** [comment]
I'm restoring from backup and did a `--clean` as well. I think because I restored from this backup a few hours ago and then did it again (it's a single node), it can't find the node and I don't have the discovery url.
