### ISSUE TITLE
Suggestion/discussion: CoreOS Torus, a modern distributed storage system

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2888]
Hi,

CoreOS just presented Torus, a modern distributed storage system. As far as I can see, it is a clustered filesystem.
This could be useful in many ways if integrated in Flynn:

- It could serve as backend for the blobstore instead of the PostgreSQL
- It could be exposed to the user applications to be used as reliable, local filesystem

Thoughts? :-)

**Comment by titanous** [comment]
Currently Torus is a prototype, it will be interesting to watch it develop. The only exposed interface is a block store (similar to EBS, except designed for containers), it does not currently implement a shared filesystem.

**Comment by titanous** [comment]
I'm going to close this for now, as Torus doesn't look like it's going to be ready any time soon. We can re-evaluate if/when it has relevant features.
