### ISSUE TITLE
Flynn install command should allow cluster creation from commandline

### ISSUE THREAD

**Issue by tjboring** [flynn/flynn#2893]
I currently have to run `flynn install` and then create a cluster by clicking in the web UI. Alternatively, I'd like to be able to create an instance by doing something like:

```
>  flynn install -n $cluster_name -c $credentials --aws_region $region --aws_instance_type $type --instance_count 3
```

Something like the above would allow me to automate most of the process for bringing up a new cluster.

**Comment by jvatic** [comment]
Related: #2645
