### ISSUE TITLE
Error on exporting applications without release

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2894]
Hi,

I've just created an application, set some environment variables and exported it without any release:

```bash
flynn create myapp
```

Set the environment variables on the dashboard.

```bash
flynn export -f myapp.tar
```

This results in this error:

> error retrieving artifact: GET https://controller.flynn.smfhq.com/artifacts/: httpclient: raw req: unexpected status 401

The tar itself looks fine though. And I can import it, so it's actually good.

**Comment by lmars** [comment]
@philiplb what version of the CLI are you using (i.e. `flynn version`)?

**Comment by philiplb** [comment]
v20160512.0

**Comment by titanous** [comment]
Can you update to the latest version with `flynn update`? I believe this bug has been fixed.

**Comment by philiplb** [comment]
Cool. Will do as soon as it hits the stable channel. :)

**Comment by titanous** [comment]
@philiplb This is in the CLI, which doesn't have a separate stable channel, and should be backwards compatible, is there a reason you're running an older version? If there are compatibility issues with older clusters that you've encountered, we'd like to fix them.
