### ISSUE TITLE
PHP Buildpack with Java

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2896]
Hi,

we have a PHP application coming with a small Java command line tool which will be called from PHP. Can I somehow install Java in deploying the PHP application? In the ideal world, the tool would also be compiled via Gradle in deployment.
Plan B is to have the JDK within the repository.

**Comment by philiplb** [comment]
Ah, great, thank you. Where could I define the gradle call? A line in the Procfile?

**Comment by titanous** [comment]
I'm pretty sure the buildpack uses Maven by default, I don't know much about the Java ecosystem. This repo should have useful links: https://github.com/heroku/heroku-buildpack-java

**Comment by philiplb** [comment]
Alright, thanks. :-)

**Comment by philiplb** [comment]
Hm, a first test failed.
This is the current test: https://github.com/smartmobilefactory/flynnphpjava

I initialized the application:

```bash
flynn create phpjava
```

When I run

```bash
git push flynn master
```

I get this error:

> Counting objects: 48, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (33/33), done.
> Writing objects: 100% (48/48), 53.87 KiB | 0 bytes/s, done.
> Total 48 (delta 4), reused 0 (delta 0)
> -----> Building phpjava...
> -----> Multipack app detected
>        =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-java
> remote: Build failed: exec: job exited with status 1
> To https://git.flynn.abc.com/phpjava.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.flynn.abc.com/phpjava.git'

Any clue what went wrong and how I could go on?

**Comment by philiplb** [comment]
Ah, https://github.com/heroku/heroku-buildpack-java uses Maven, right.
Switched to https://github.com/heroku/heroku-buildpack-gradle , looking better. :)
