### ISSUE TITLE
Flynn cluster fail - discoverd flakiness?

### ISSUE THREAD

**Issue by brettneese** [flynn/flynn#2897]
Got a warning this morning that our web apps were down. Trying to extract anything from the cluster using the CLI resulted in:

```GET https://controller.flynn.[domain].com/apps/dashboard/release: httpclient: raw req: unexpected status 503```

I'm guessing it has to do with that `discoverd` flakiness, but not sure.

flynn-host is reporting ``v20160512.0``.

Any suggestions on how to get this cluster online again - or at least to a point where we can do a cluster backup? 

Host logs:

https://gist.github.com/anonymous/b09a84f607c12b28c8dfde9b248e9d19
https://gist.github.com/anonymous/2c89b9371e3e03f07c588e455e8f3626a
https://gist.github.comanonymous//635015b1dbe7576c6ba101b29f5472cf

**Comment by titanous** [comment]
It looks like flynn-host isn't running on 10.0.2.77, perhaps it rebooted? I'd suggest starting flynn-host on that host and waiting a bit to see if things start working. If not, try running `flynn-host fix -n 3` and post the output here.

**Comment by brettneese** [comment]
OK, so restarting it by hand doesn't work. Upstart is giving me 

```
DBUG[06-07|18:36:01] zfs get all -Hp flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5 package=zfs
t=2016-06-07T18:36:01+0000 lvl=eror msg="error opening state databases" app=host pid=5683 fn=runDaemon host.id=ip100277 err="could not restore from volume persistence db: cannot restore volume \"7a67c2d1-43ee-4524-af82-3d6da5d4ebb5\": exit status 1: \"/sbin/zfs zfs get all -Hp flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5\" => cannot open 'flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5': dataset does not exist\n"
18:36:01.912603 host.go:368: could not restore from volume persistence db: cannot restore volume "7a67c2d1-43ee-4524-af82-3d6da5d4ebb5": exit status 1: "/sbin/zfs zfs get all -Hp flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5" => cannot open 'flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5': dataset does not exist
t=2016-06-07T18:36:01+0000 lvl=info msg="starting daemon" app=host pid=5696 fn=runDaemon host.id=ip100277
t=2016-06-07T18:36:01+0000 lvl=info msg="validating host ID" app=host pid=5696 fn=runDaemon host.id=ip100277
t=2016-06-07T18:36:01+0000 lvl=info msg="detecting external IP" app=host pid=5696 fn=runDaemon host.id=ip100277
t=2016-06-07T18:36:01+0000 lvl=info msg="using external IP 10.0.2.77" app=host pid=5696 fn=runDaemon host.id=ip100277
t=2016-06-07T18:36:01+0000 lvl=info msg="registering with cluster discovery service" app=host pid=5696 fn=runDaemon host.id=ip100277 token=https://discovery.flynn.io/clusters/54cf1511-7bba-404c-9217-5e677b0d5d89 addr=10.0.2.77:1113 name=ip100277
t=2016-06-07T18:36:02+0000 lvl=info msg="registered with cluster discovery service" app=host pid=5696 fn=runDaemon host.id=ip100277 id=a89eee2f-a2b3-4b2b-a89b-7333a1e99df8
t=2016-06-07T18:36:02+0000 lvl=info msg="initializing volume manager" app=host pid=5696 fn=runDaemon host.id=ip100277 provider=zfs
t=2016-06-07T18:36:02+0000 lvl=info msg="initializing job backend" app=host pid=5696 fn=runDaemon host.id=ip100277 type=libvirt-lxc
t=2016-06-07T18:36:02+0000 lvl=info msg="creating HTTP listener" app=host pid=5696 fn=runDaemon host.id=ip100277
t=2016-06-07T18:36:02+0000 lvl=info msg="opening state databases" app=host pid=5696 fn=runDaemon host.id=ip100277
DBUG[06-07|18:36:02] zfs get all -Hp flynn-default            package=zfs
DBUG[06-07|18:36:02] zfs get all -Hp flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5 package=zfs
t=2016-06-07T18:36:02+0000 lvl=eror msg="error opening state databases" app=host pid=5696 fn=runDaemon host.id=ip100277 err="could not restore from volume persistence db: cannot restore volume \"7a67c2d1-43ee-4524-af82-3d6da5d4ebb5\": exit status 1: \"/sbin/zfs zfs get all -Hp flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5\" => cannot open 'flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5': dataset does not exist\n"
18:36:02.228421 host.go:368: could not restore from volume persistence db: cannot restore volume "7a67c2d1-43ee-4524-af82-3d6da5d4ebb5": exit status 1: "/sbin/zfs zfs get all -Hp flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5" => cannot open 'flynn-default/7a67c2d1-43ee-4524-af82-3d6da5d4ebb5': dataset does not exist
```

Doing ``flynn-host fix`` gets me:

```EROR[06-07|18:37:52] unable to list hosts from discoverd, falling back to peer IP list error="Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused"
18:37:52.748912 host.go:142: error connecting to discoverd, use --peer-ips: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: connection refused```

**Comment by titanous** [comment]
Hmm, it sounds like the data volume may be detached or not mounted. Does `sudo zpool list` show anything? Are there two EBS volumes attached to the instance?

**Comment by brettneese** [comment]
Hmm, looks like you may be right:

```
ubuntu@ip-10-0-2-77:~$ sudo zpool list
NAME            SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
flynn-default  34.2G  95.5K  34.2G         -     0%     0%  1.00x  ONLINE  -
ubuntu@ip-10-0-2-77:~$ lsblk
NAME    MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
xvda    202:0    0  50G  0 disk 
└─xvda1 202:1    0  50G  0 part /```

**Comment by titanous** [comment]
Did you set up the cluster with `flynn install`? If so, there should be a second EBS volume that needs to be attached to the instance.

**Comment by brettneese** [comment]
Yeah, I did! Not sure how it disappeared all of a sudden?

**Comment by brettneese** [comment]
At least one other host has their volumes set up correctly, and we've been running flynn for a couple weeks without any problems.

**Comment by titanous** [comment]
You'll also need to run `sudo zpool destroy flynn-default` and `rm -rf /var/lib/flynn/volumes/zfs/vdev` as a fallback got created that will conflict with the real data volume.

**Comment by titanous** [comment]
(note that that should not be run if the volume is attached)

**Comment by brettneese** [comment]
OK, so I should just run that and attach the volume?

**Comment by titanous** [comment]
Yeah.

**Comment by brettneese** [comment]
Didn't quite work - do I need to format the volume first?

**Comment by brettneese** [comment]
Ok, that worked, but I'm still getting 503's.

Currently trying to run ```flynn-host fix -n 3``` but it seems to be frozen at ```found controller instance, checking critical formations```

**Comment by titanous** [comment]
Okay, that's probably caused by #2875, a known issue. Try killing all running controller web and scheduler jobs by looking in `flynn-host ps` and stopping each relevant job ID with `flynn-host stop`.

**Comment by titanous** [comment]
(and after that run the same fix command)

**Comment by brettneese** [comment]
Not sure what I did, but now I'm getting:

```20:07:05.903354 host.go:142: expected at least 3 hosts, but 2 found```

Went ahead and changed the -n to 2. Seeing what that does. Really just need a backup so I can build a new cluster.

**Comment by brettneese** [comment]
Now I'm getting stuck on ```INFO[06-07|20:11:56] waiting for postgres to come up read-write```

**Comment by brettneese** [comment]
And.... ```20:16:56.535196 host.go:142: timeout waiting for expected status```

**Comment by titanous** [comment]
This gist describes steps to take a manual backup, stop flynn-host before starting: https://gist.github.com/titanous/36754c1da91c632640a7

Let me know if anything needs clarification.

**Comment by brettneese** [comment]
Perfect, that's pretty easy.

Any ideas why the cluster might've failed in the first place? We'd like to try and prevent downtime, I thought if one host failed the cluster could continue working but maybe two of them actually failed (since the first host does not appear to be set up correctly.)

**Comment by titanous** [comment]
I think at least one host failed, removing fault tolerance, and then there was a subsequent network disruption that broke consensus temporarily. I will have another look at the logs to sort out why it was a persistent failure instead of just transient.

**Comment by brettneese** [comment]
We got anotger cluster running, so I'm going to go ahead and close this - sorry it's been open for so long! :)
