### ISSUE TITLE
Set limits for multiple processes in one command

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#2898]
At the moment, one command is required per process to configure its limits. This is a problem for us because we have more than 30 different processes in our main app, and updating the limits results in a new release being created every time (we'd like to avoid the overhead, both in time and space, that would result from creating 30+ releases every time we need to tweak the limits).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
