### ISSUE TITLE
Restore cluster from backup after using the installer

### ISSUE THREAD

**Issue by brettneese** [flynn/flynn#2904]
Is it possible to restore/re-bootstrap a cluster from a backup using ```flynn-host bootstrap --from-backup```? 

Our backups on s3 are large and my internet connection is slow (took 3 hours to upload last night, which resulted in a failure) but I don't feel like configuring and wiring up all the AWS stuff by hand.

If it helps, when I tried to do this, I got: 

```16:29:42.598419 restore-postgres restore error: error running psql restore: exec: job exited with status 2 - "psql: FATAL:  password authentication failed for user \"flynn\"\n"```

**Comment by titanous** [comment]
You could run the manual install script with the `--clean` flag on the nodes provisioned by the installer and then manually bootstrap.

**Comment by brettneese** [comment]
Nah, that makes too much sense. ;-)

Closing.
