### ISSUE TITLE
TUF mismatch in current release

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2908]
"01:36:04.406916 host.go:136: tuf: failed to download v1/images/41dc8c75a0047edf9b2940be2b86472793e26a0af6bf79ed4d7b72b07f133c83/layer: wrong sha512 hash, expected fb062525576717b8be50a77eaa9284ba1616c95e0be49b9bb93182229692e7534403a4e38b98e6ca06beca7a92bd6b1c9fadf402c334a931bac329c7244733fe got 03bf7e4f15e251ea75d2a0cdcaf10406fc922f74d6ee49279430289cdcb2b4875baceae120283e6eff9a68160b4c6130878b2d39b034b98bd3ec74095d7d284d"

Gotten this multiple times now.

**Comment by tianx2** [comment]
i was told to add my gists from flynn IRC channel to this ticket:
https://gist.github.com/72adfab793f4583bf810b35fc09d0f95
https://gist.github.com/tianx2/48357607c08bea35c8269f738a199fca
https://gist.github.com/tianx2/eefa84104efffebeac3d32e689e025b3

**Comment by titanous** [comment]
Which version were you trying to install? I was unable to reproduce with v20160610.0.

**Comment by temujin9** [comment]
The most recent version was causing this. I can try it again, see if it continues.

**Comment by temujin9** [comment]
I am now unable to trigger this. Closing it for now, will reopen or open another if it recurs.
