### ISSUE TITLE
flynn bootstrap restore gets unreachable hosts error

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#2910]
When trying to bootstrap restore I get an issue about unreachable hosts. Here are the related gists:
https://gist.github.com/72adfab793f4583bf810b35fc09d0f95
https://gist.github.com/tianx2/eefa84104efffebeac3d32e689e025b3

Had this issue with version 20160606 through version 08

CC @lmars

**Comment by tianx2** [comment]
truncated cloud-init.log - https://gist.github.com/tianx2/4906eb1cff6a916c89428dcd402a73f3

**Comment by lmars** [comment]
A description of the gists:

* debug-info from `10.100.55.122`: https://gist.github.com/72adfab793f4583bf810b35fc09d0f95
* cloud-init log (containing bootstrap log) from `10.100.55.122`: https://gist.github.com/tianx2/48357607c08bea35c8269f738a199fca
* discoverd on-disk log from `10.100.55.122`: https://gist.github.com/tianx2/eefa84104efffebeac3d32e689e025b3

The bootstrap error:

```
flynn-host bootstrap --peer-ips=10.100.55.122,10.100.55.120,10.100.55.127,10.100.55.129,10.100.55.119 --from-backup /mnt/flynn-restore-source --timeout 3600
+ bootstrap_output='11:06:34.094699 check online-hosts
11:06:34.102719 run-app discoverd
11:06:44.394105 run-app flannel
11:06:52.337077 wait-hosts wait-hosts
12:06:52.337479 wait-hosts wait-hosts error: bootstrap: timed out waiting for hosts to come up

The following hosts were unreachable:
	10.100.55.122:1113'
```

Host `10.100.55.122` has both `flynn-host` and `discoverd` running, but `flynn-host ps` does not include any jobs for `10.100.55.122`.

This is as far as I got, but I need to head offline.

**Comment by titanous** [comment]
If the host is still around, the log from flannel on 10.100.55.122 would be really helpful. /var/log/flynn/ae4d746f-7cf9-41b2-9ffe-54bf4d23a28a.log

**Comment by temujin9** [comment]
Another one seems to have hit this: https://gist.github.com/658d951a9ba8182096fac097f4dd2e4f https://gist.github.com/6b3268c4c030bccebedf28a4a865cb43 https://gist.github.com/8fc745bef8d4a94a952649e993cc6739

**Comment by temujin9** [comment]
The flannel log from the offending node of the most recent: https://gist.github.com/704425d372d5c50daa9bfea0ed00b120

**Comment by temujin9** [comment]
We appear to be getting this fairly regularly today. Unfortunately, only the most recent instance was preserved:

https://gist.github.com/e139d4bf90a294acb9de1ef7ae3aec40
https://gist.github.com/f0b326f721a515671aad22526d0e5b78
https://gist.github.com/8c94a4365042a422b31dfc19714ca6f5
https://gist.github.com/22dadd637c413219bfbd928f9b8a4d69
https://gist.github.com/b15ebe1f992ceba9e2dcba76e4875e91
