### ISSUE TITLE
script: Detect TMPDIR mounted with noexec

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2926]
A user encountered an error installing Flynn with:

```
===> 16:51:11.433 running "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin" install-flynn: line 233: ./flynn-host: Permission denied
```

The reason for the issue was that, although a call to `chmod +x flynn-host` succeeded (i.e. [here](https://github.com/flynn/flynn/blob/v20160613.0/script/install-flynn.tmpl#L131)), `TMPDIR` was mounted with `noexec` meaning the `flynn-host` binary did not have the executable bit set.

We should print a more informative error when the `flynn-host` binary is not executable.

**Comment by lmars** [comment]
P.S. to get around this, the user re-mounted `TMPDIR` without `noexec` being set.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
