### ISSUE TITLE
Add private ssh key to container.

### ISSUE THREAD

**Issue by andymilga** [flynn/flynn#2927]
Hello,
I need to add private key to container before i start deploying application, because i got some gems in my private gitlab repo. My colleague found this [issue](https://github.com/flynn/flynn/issues/2906), but this doesn't works for me. I got SSH_CLIENT_KEY variable for application. I see my private_key via cli
(like 'flynn -a #app_name env' ) and i see it in dashboard, but when i'm redeploying app - no .ssh directory created in /app.

**Comment by jvatic** [comment]
@andymilga what app did you set the variables on?

**Comment by lmars** [comment]
@andymilga to clarify, the `SSH_CLIENT_HOSTS` and `SSH_CLIENT_KEY` environment variables need to be set on the `gitreceive` app rather than your own app as that is where the `git clone` calls happen when your app is being built, so your command should be something like:

```
flynn -a gitreceive env set SSH_CLIENT_HOSTS="$(cat ~/.ssh/known_hosts)" SSH_CLIENT_KEY="$(cat ~/.ssh/mykey)"
```
