### ISSUE TITLE
Allow user to specify cluster name during creation

### ISSUE THREAD

**Issue by tjboring** [flynn/flynn#2938]
Allow the user to specify the name makes it easier to work with Flynn post-creation, especially if you have multiple clusters. Just one example:

```
> flynn -c prod apps

vs.

> flynn -c flynn-1234567 apps
```

I know I can create an environment variable in .bashrc, which is what I'm currently doing. But that doesn't help other engineers.

This change would also reduce the opportunities for mistakes. Is `flynn-1234567` production or is `flynn-1234576`?

**Comment by jvatic** [comment]
@tjboring You can change the name of the cluster (as seen by the flynn cmd) in your flynnrc file.

**Comment by tjboring** [comment]
@jvatic OK, so the `cluster-name` argument to the `flynn cluster add` command is free-form; it's not validated against anything. Correct? 

So, changing the name in .flynnrc is a short-term workaround. That said, I still think it'd be worthwhile if the cluster name could be specified by the user at cluster creation time. Here are some issues I see with this (which I probably should have outlined earlier):

- I create a new cluster; `flynn install` assigns it name `flynn-1234567`
- I change my .flynnrc file so the cluster name is `dev`
- I tell our other 9 engineers to use the name `dev` when they do `flynn cluster add` on their machines
- Another engineer goes to look at our machines in AWS and all they see is `flynn-1234567`

Is there a technical reason why the cluster name can't be specified by the user at creation time?

**Comment by jvatic** [comment]
@tjboring There's no technical reason why you can't give a name before creation within the `flynn install` app.
