### ISSUE TITLE
Flynn Client & Host CLIs should expose cluster status

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#2963]
Both `flynn` and `flynn-host` should expose a `status` command that reports the details of the cluster's status.

**Comment by philiplb** [comment]
@titanous @lmars 
Here, I would add another command to flynn and flynn-host which calls controller.Client.Status(), correct? + The integration tests. :)

**Comment by lmars** [comment]
@philiplb sounds right yes.

**Comment by philiplb** [comment]
@lmars 
Thanks.
I have a small problem here:
In the Vagrant box, I'm running a local Flynn via _script/bootstrap-flynn_.

And then I add it via _flynn cluster add_. The dashboard is running fine, its status page shows all apps and their health. However, in my status command, the call to the status endpoint results in nil Detail:
```golang
func runStatus(args *docopt.Args, client controller.Client) error {
	clusterStatus, err := client.Status()
	if clusterStatus != nil {
		printStatus(clusterStatus)

		if clusterStatus.Detail != nil {
			// This is never reached...
			detail := make(map[string]json.RawMessage)
			if err := json.Unmarshal(*clusterStatus.Detail, &detail); err != nil {
				return err
			}
			for app, rawAppStatus := range detail {
				fmt.Println(app, ": ")
				var appStatus status.Status
				if err := json.Unmarshal(rawAppStatus, &appStatus); err != nil {
					return err
				}
				printStatus(appStatus)
			}
		}

	}
	return err
}
```

Do you know how I can get the apps details?

**Comment by philiplb** [comment]
@lmars @titanous 
Ou, also on our live cluster, I don't get the details.

**Comment by lmars** [comment]
@philiplb I didn't look close enough when I made my last comment, `client.Status()` just returns the status of the controller (which has no details), rather than the status of the cluster (which comes from the status app).

You need to make a request to the status app which can be found internally at `http://status-web.discoverd`, externally we should run a job which gets the status using `curl`.

**Comment by titanous** [comment]
Perhaps we should expose the cluster status endpoint from the controller API?

**Comment by lmars** [comment]
@titanous that is a good idea yes.

**Comment by philiplb** [comment]
@titanous Could you give some directions about how to expose the cluster status endpoint from the controller API?

**Comment by lmars** [comment]
@philiplb 

* Add a new handler to the controller `GET /cluster/status` (existing handlers are [here](https://github.com/flynn/flynn/blob/master/controller/controller.go#L260-L325))
* The handler should `GET http://status-web.discoverd` and return the result
* Add `client.ClusterStatus()` which hits that endpoint

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
