### ISSUE TITLE
Add ability to expose clients to web

### ISSUE THREAD

**Issue by michaelyork** [flynn/flynn#2965]
As far as I can tell, there's no way to expose redis/mysql/etc on an externally-accessible port. Would be great for local development!

**Comment by titanous** [comment]
This is supported in the dashboard, and via slightly arcane underdocumented CLI command. I'm working a list of docs to write, thanks for the reminder.

The main thing to watch out for us that TLS is not currently enabled for any of those databases, so running them over I trusted networks isn't a good idea.

**Comment by michaelyork** [comment]
Was about to say, just discovered this! Sorry for the premature filing. You guys have done a tremendous job – loving Flynn.

```
➜  *** git:(master) flynn redis
usage: flynn redis redis-cli [--] [<argument>...]
       flynn redis dump [-q] [-f <file>]
       flynn redis restore [-q] [-f <file>]
```

**Comment by titanous** [comment]
In case anyone finds this issue: the client commands available frome the CLI are tunneled over a pinned TLS connection, the security considerations only come into play if you choose to forward a prot via the router directly to the database server.

**Comment by michaelyork** [comment]
@titanous I should ask too just to clarify: is there a way to directly access redis or mysql without the CLI? For example, connecting via a third-party client like Sequel Pro?

**Comment by titanous** [comment]
Yeah, that's what I was originally talking about. If you go to the database section of the dashboard it can help you create a route for use with external apps.

**Comment by michaelyork** [comment]
Got it, only shows up when creating the appliance as "standalone". Not when provisioning a database from the apps panel. Thanks!

**Comment by titanous** [comment]
@jvatic please open an issue about making that clearer.

**Comment by jvatic** [comment]
@titanous I've opened #2966 to track this.

**Comment by KidkArolis** [comment]
I'm trying to connect to MySQL db inside a flynn cluster over ssh tunnel using Sequel Pro UI.

I'm trying to do this with the following settings:

![image](https://cloud.githubusercontent.com/assets/324440/22267882/5c301f20-e27d-11e6-81f2-fcc762250a07.png)

But I get "Unable to connect to host leader.mariadb.discoverd, or the request timed out." Is that not a real host? Is it running in a container? Is there a way to connect to this MySQL over the ssh tunnel?

**Comment by josephglanville** [comment]
The MariaDB processes run in containers. If you wish to connect to MariaDB over an SSH tunnel you will need to run an SSH daemon in a container on the Flynn cluster.
Open a new issue if you need help with getting that going.
