### ISSUE TITLE
Can't push to git at flynn behind NGINX-proxy

### ISSUE THREAD

**Issue by nlsrchtr** [flynn/flynn#2968]
Thanks for your work and all your energy you put into this software.

I installed flynn on our internal network and want to give access to it, by using our central NGINX load-balancer setup. Everything is working, but I can't push any code to the repository. It fails with the following message:

`fatal: unable to access 'https://git.$HOSTNAME/$APPNAME.git/': SSL: certificate verification failed (result: 5)`

I think this is based on the two different SSL certificates, which are currently in use. Our own wildcard certificate for `*.$HOSTNAME`, which is handled by our NGINX and the second, self-signed certificated, which is handled by the git endpoint.

Could you point me to some resources or solutions, how I can fix this situation - besides disabling certificate check on client side? Maybe I can set the certificate for the git endpoint?

Thanks for your time and effort.

_Maybe it helps to have our NGINX config_

```
server {
  listen       IP_ADDRESS:443 ssl;
  server_name  flynn.SERVERNAME *.flynn.SERVERNAME;

  ssl on;
  ssl_certificate           /etc/nginx/certs/flynn/flynn.crt;
  ssl_certificate_key       /etc/nginx/certs/flynn/flynn.key;
  ssl_dhparam               /etc/nginx/certs/dhparam.pem;
  ssl_session_cache         shared:SSL:10m;
  ssl_session_timeout       1d;
  ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers               $CIPHERS
  ssl_prefer_server_ciphers on;
  ssl_stapling              on;
  ssl_trusted_certificate   /etc/nginx/certs/flynn/flynn.chain;

  access_log            /var/log/nginx/vhosts_access.log combined;
  error_log             /var/log/nginx/vhosts_error.log;

  location / {
    proxy_pass            https://flynn_cluster;
    proxy_read_timeout    90;
    proxy_connect_timeout 90;
    proxy_redirect        off;
  }

  ssl_session_tickets off;
}
```

**Comment by titanous** [comment]
The `flynn` CLI specifies the CA certificate to use in `~/.gitconfig` during the `flynn cluster add` command. You could change or remove the relevant `sslCAInfo` field in that file to fix this issue.

**Comment by nlsrchtr** [comment]
Thanks for this quick reply. Removing that part from the config worked great!
