### ISSUE TITLE
Flynn CI Runner V2

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2970]
We currently have a CI runner which runs as a standalone service on a single bare metal VM. The runner builds and tests Flynn in Linux VMs running under KVM.

We should implement a new CI runner which runs in a Flynn cluster. It should be much more generic and support building and testing all types of software, not just Flynn.

What follows is a brain dump of some of my thoughts on this.

---
### Current runner implementation

Here is an overview of how the current CI runner builds and tests Flynn:

1) We have an [Upstart job](https://github.com/flynn/flynn/blob/v20160621.0/test/scripts/upstart.conf) which pulls the latest Flynn code, creates a base VM image with Flynn build dependencies then starts the runner. To create the image, we download [ubuntu-base](https://wiki.ubuntu.com/Core), chroot into it and run a setup script (see [build.sh](https://github.com/flynn/flynn/blob/v20160621.0/test/rootfs/build.sh)).

2) On startup, the runner creates a CoW image from the base image, starts a VM, then pulls the latest Flynn code and builds Flynn using [this script](https://github.com/flynn/flynn/blob/v20160621.0/test/cluster/cluster.go#L396-L438) via SSH. This CoW image serves as a cache so that triggered builds don't need to build Flynn from scratch.

3) When the runner receives a GitHub webhook, it creates a CoW image from the cached build image, fetches the commit referenced in the webhook and builds Flynn again. It then uses CoW images of this resulting image to boot VMs to form two Flynn clusters (`default` and `release`). It uses `start-stop-daemon` to start `flynn-host` on each VM (see [here](https://github.com/flynn/flynn/blob/v20160621.0/test/cluster/cluster.go#L474-L498)), then runs bootstrap on the first VM in the cluster (see [here](https://github.com/flynn/flynn/blob/v20160621.0/test/cluster/cluster.go#L511-L531)).

4) With a Flynn cluster up and running, the runner runs the `flynn-test` binary on the first VM in the `default` cluster using [this script](https://github.com/flynn/flynn/blob/v20160621.0/test/runner/runner.go#L301-L350).

5) As part of running the test suites, `flynn-test` interacts with the runner via HTTP to boot new VMs to tests things like scheduling jobs on new hosts and promoting hosts in service discovery.

---
### Proposed runner implementation

A sketchy outline of how I think a new runner could work:
- The runner runs in Flynn, has a database of builds (probably PostgreSQL) and exposes a simple UI for creating / viewing / editing builds
- Builds have many volumes which are used for caching and passing around intermediate build state (the volumes are essentially throw away, losing a cache just extends the build time, and losing intermediate state fails the build, maybe restarts it?)
- Builds have many sources which provide the code to be built (e.g. a GitHub webhook which pulls code into a git cache volume, checks out a commit then triggers a build)
- When a build is triggered by a source, a pre-defined `build` job is started with the source code as a volume, and this job then decides what other jobs need to run based on the code (e.g. by reading a `Flynnfile` which defines a bunch of steps needed to build the software). These jobs would be called `steps`
- The build job is responsible for ensuring all the steps run, and fails the build if any step fails (and doesn't run any further steps)
- Steps have many volumes, and can either request fresh volumes or attach volumes from previous steps either from the same build or from previous builds (e.g. use the cache from the last build of master)

With this in hand, and assuming a similar workflow to what we currently have, a Flynn test run would have steps something like:
- `rootfs` - Download and extract `ubuntu-base`, chroot and run setup.
  
  This step would probably be cached based on a hash of the setup script. We could make the setup script idempotent so adding a single package is re-run in a previously built rootfs rather than building from scratch.
  
  Extracting an `ubuntu-base` tarball in a Flynn job is currently problematic as it requires `CAP_MKNOD`, which containers don't have (see discussion of KVM below). We could instead use a zvol block device and copy an Ubuntu cloud image into it using `dd`, but then it isn't as easy to chroot into it (Ubuntu cloud images have partitions, so you need to call `partprobe` on the zvol device to pick up the partition, but then the container can't see the new partition device :unamused:)
  
  I'm sure we could figure something out :smile:.
- `build` - Start a VM, SSH in and build Flynn.
  
  This step would attach a clone of either the `build` volume or the `rootfs` volume from the most recent `master` build, thus creating a chain of CoW volumes from each build of master. We would probably want a mechanism to build from a clean slate in case we get odd state related issues.
- `test` - Create a release referencing the `build` volume and run the `flynn-test` binary which would create clusters using the release and run tests.
  
  I haven't got to this step in my manual testing, but basically the step would run `flynn -a buildX-clusterY scale vm=3`, wait for 3 SSH services to appear in discoverd, SSH in and bootstrap them. Individual tests would be able to create their own Flynn clusters in a similar fashion. 

Now, this is still not ideal because we are creating one monolithic VM image using a single job at a time. Ideally we would do away with the first two steps and instead run a distributed build of Flynn, where we have a job per component (e.g. `discoverd` / `controller` / `postgres` etc.) each of which builds a component into a volume, and then a final job attaches all the volumes and creates a final artifact which constitutes the Flynn build ready to run the tests.

Progress has been made on this approach with [bake](https://github.com/flynn/bake), so we may want to pull on that string a little more.

In any case, I think the proposed step runner approach could support this workflow too.

---
### KVM in Flynn

I think we want to continue to test Flynn using VMs as it provides an environment which is closer to how users run Flynn in the wild.

With that in mind, I see there being three options for running VMs using KVM in Flynn:
#### Via libvirt

We already use libvirt as a container runtime and it has [support from KVM / QEMU](https://libvirt.org/drvqemu.html), so we could use it as a VM runtime, although we have talked about dropping libvirt as a dependency.
#### Inside a container

To run VMs using KVM in a container, we need to expose the `/dev/kvm` device.

This is possible using this [libvirt hostdev option](https://libvirt.org/formatdomain.html#elementsHostDevCaps), but we could consider giving containers `CAP_MKNOD` so they can create that themselves (currently not possible with [libvirt 1.2.2](https://github.com/libvirt/libvirt/blob/v1.2.2/src/lxc/lxc_container.c#L1743), so we would either need to update libvirt or switch to a different container runtime).

For networking, one approach is to expose `/dev/net/tun` to the container, have `flynn-host` assign an IP to the container but for `containerinit` not to configure networking, instead allowing the KVM runner to create a TAP device and provide the assigned IP to the VM. I have managed to make this work, but you do need a mechanism to pass the IP to the VM. Here are possibilities for that:

1) Run a DHCP server which serves the VM's MAC address with the assigned IP
2) Specify the IP on the kernel command line using `ip=` which, if configured in the VM's initrd, will trigger [ipconfig](http://git.kernel.org/cgit/libs/klibc/klibc.git/tree/usr/kinit/ipconfig/README.ipconfig) to configure the network
3) Mount a directory at `/etc/network/interfaces.d` using 9P (this is [what we currently do](https://github.com/flynn/flynn/blob/v20160621.0/test/rootfs/setup.sh#L58)). This requires the VM to know what to mount, and to also support 9P filesystems
4) Create a `cloud-init` `NoCloud` data source which specifies `network-interfaces` (see [here](http://cloudinit.readthedocs.io/en/latest/topics/datasources.html#no-cloud)) (obviously requires `cloud-init` to be present in the image)

Options 2, 3 and 4 are Linux specific, with 3 and 4 being Debian / Ubuntu specific, so option 1 gives the most flexibility.
#### KVM job backend

Rather than running VMs in containers, we could implement a KVM job backend.

If we make assumptions about what is going to run in the VM (i.e. a Linux program from a Docker image), we could expose the job's image to the VM using 9P, mount it as the root filesystem (possible with a [modified Ubuntu initrd](http://unix.stackexchange.com/a/94253)) then exec `.containerinit` as init inside the VM, which would then act as it does now but probably expose stdin / stdout / stderr using console devices rather than passing FDs over Unix sockets. Another option here is to create a custom initrd containing `containerinit` which does exactly what we need.

If instead we want to run opaque VM images, we could provide `flynn-host` with the VM image rather than a Docker image (perhaps the VM images could be imported as zvols and they would be presented as block storage to the VM). For networking, we would probably want `flynn-host` (or some other service) to act as DHCP server for maximum compatibility.
#### KVM runner

We currently use [QEMU](http://wiki.qemu.org/Main_Page) to run VMs using KVM, but if we are aiming for speed and know what kind of workloads will be running, we may want to consider [kvmtool](https://kernel.googlesource.com/pub/scm/linux/kernel/git/will/kvmtool/+/master/README).

---

Ok brain dump over! There is more in there but I'll let someone else speak...

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
