### ISSUE TITLE
Cluster down after node restart

### ISSUE THREAD

**Issue by michaelyork** [flynn/flynn#2971]
Had to manually reboot my single-node cluster via `sudo reboot` and can't get flynn back up. Looking at `/var/log/upstart/flynn-host.log`:

```
EROR[06-21|17:12:02] did not find any controller api instances component=cluster-monitor fn=checkCluster
EROR[06-21|17:12:02] scheduler is not up                      component=cluster-monitor fn=checkCluster
EROR[06-21|17:12:02] fault deadline reached                   component=cluster-monitor fn=checkCluster
INFO[06-21|17:12:02] initiating cluster repair                component=cluster-monitor fn=repairCluster
INFO[06-21|17:12:02] killing any running schedulers to prevent interference component=cluster-monitor fn=repairCluster
INFO[06-21|17:12:02] request started                          component=host req_id=71277d06-2aed-4daa-ac77-e0815d244d7a method=GET path=/host/jobs client_ip=***
INFO[06-21|17:12:02] request completed                        component=host req_id=71277d06-2aed-4daa-ac77-e0815d244d7a status=200 duration=21.890463ms
INFO[06-21|17:12:02] checking postgres                        component=cluster-monitor fn=repairCluster
INFO[06-21|17:12:02] no running postgres leader               component=cluster-monitor fn=repairCluster
INFO[06-21|17:12:02] found 0 running postgres instances       component=cluster-monitor fn=repairCluster
INFO[06-21|17:12:02] getting postgres status                  component=cluster-monitor fn=repairCluster
INFO[06-21|17:12:02] getting postgres service metadata        component=cluster-monitor fn=repairCluster
INFO[06-21|17:12:02] getting postgres primary job info        component=cluster-monitor fn=repairCluster job.id=flynn1466446688-f0cb6148-c579-423e-860f-21f3715cdd3f
EROR[06-21|17:12:02] error repairing cluster                  component=cluster-monitor fn=checkCluster err="unable to get postgres primary job details: unable to get host for job lookup: cluster: unknown host \"flynn1466446688\""
```

**Comment by lmars** [comment]
@michaelyork please run `sudo flynn-host collect-debug-info` on your host and post the resulting gist here.

**Comment by michaelyork** [comment]
https://gist.github.com/3748ff27f1d3bdbbc5e1e684de743f86

**Comment by lmars** [comment]
@michaelyork did you change the host ID after the reboot? If you did, looks like we don't handle that correctly.

**Comment by michaelyork** [comment]
Had only changed the cluster-name before rebooting. Then ran `sudo reboot` the next morning. Everything was working fine post-name change and pre-reboot.

**Comment by lmars** [comment]
Ok this seems like a bug which we will fix. For now I suspect reverting back to the original host ID will bring the cluster back.

**Comment by michaelyork** [comment]
Got it. Unclear how to do that given the current state of the install. Run
`flynn-host migrate-domain &lt;xxxx.flynnhub.com&gt;`?

On Jun 21 2016, at 3:52 pm, Lewis Marshall &lt;notifications@github.com&gt;
wrote:  

> Ok this seems like a bug which we will fix. For now I suspect reverting back
to the original host ID will bring the cluster back.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/flynn/flynn/issues/2971#issuecomment-227596052), or
[mute the
thread](https://github.com/notifications/unsubscribe/ADvDlR9w6u5kFS7EbCs_UBQcjJUWkFz2ks5qOGsSgaJpZM4I7LdG).![](https://github.com/notifications/beacon/ADvDlYDkoYKvqwWfLmDp4llUSFXg3C0Fks5qOGsSgaJpZM4I7LdG.gif)

**Comment by lmars** [comment]
@michaelyork how did you change the host ID before the reboot? I assumed you edited `/etc/init/flynn-host.conf` (in which case you would just reverse your change and run `sudo restart flynn-host`), but if you did it some other way then let me know what you did and I can advise what steps to take.

**Comment by titanous** [comment]
Closing due to lack of information, please feel free to open a new issue with a repro case.

**Comment by LaSanta** [comment]
hey guys i have a similar problem...i renamed the machine on digitalocean console from flynn-<deviced-id>-0 to something else and the next time i did a git push flynn <remote> the app got deployed but django couldn't connect to leader.postgres.dicoverd...so i put back the machine names as it was and restarted them...the service went up but then crashed within minutes...i got into the machines and tried stopping/starting flynn-host... i've collected the logs i'll post them asap...
