### ISSUE TITLE
"flynn-host ps" gets "could not list hosts: Error sending HTTP request [...] connection refused" during node replacement

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#2972]
Three node cluster, restored from backup, one node manually knocked over for testing purposes.

https://gist.github.com/4ced71fa41370b1b1b5462072a794e04 is the only debug-info I was able to retrieve from the hosts, and I believe that was in the newest node. The other two hang at "getting job logs", and the status page has gone from unhealthy to unresponsive as time progresses.

**Comment by lmars** [comment]
The underlying issue here was #2974, I'll close this in favour of that issue.
