### ISSUE TITLE
New hosts can block if discoverd not started before other jobs

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#2974]
When a new host comes online, the scheduler sees it and proceeds to start all omni jobs plus jobs for any partially running formations on that host.

Given the host has an AddJobs rate limit of 4 by default, and jobs dependent on discoverd will block waiting for discoverd to start, if the scheduler starts 4 such jobs before discoverd, the host will be stuck.

This was evident in #2972 when the scheduler started postgres / scheduler / router / monitor (user app) before discoverd, all of which blocked and caused the scheduling of the discoverd job to receive `ratelimited: maximum concurrent AddJob calls running, try again later`.

We should unblock the rate limiter before blocking waiting for discoverd, or alternatively always start discoverd & flannel before other jobs on a new host.

/cc @temujin9

**Comment by josephglanville** [comment]
A possible solution here is to rethink the way the libvirt backend sets the discoverd environment variable and instead pull it from the current peer list of the hosts default discoverd client. The would decouple the need for discoverd to actually be running from the ability to start jobs if the `flynn-host` process was started with `--peer-ips` or similar to join it to an existing and functional discoverd cluster.

**Comment by titanous** [comment]
I think the blocking until discoverd starts behavior is what we want, the majority of services depend on discoverd to start up.

**Comment by titanous** [comment]
Or is this just in the case where discoverd is running elsewhere?

**Comment by josephglanville** [comment]
Only in the case where the host was added to an existing operational discoverd cluster. As the client is cluster aware now there is no reason to block on the local discoverd being available.

**Comment by titanous** [comment]
Okay, that makes sense.
