### ISSUE TITLE
"flynn run" returns "httpclient: unexpected status 400"

### ISSUE THREAD

**Issue by nlsrchtr** [flynn/flynn#2977]
When I run one of the following commands, as explained in the [docs](https://flynn.io/docs/how-to-deploy-ruby#run-jobs):

`flynn run rake db:migrate`
`flynn run -r RELEASE_ID rake db:migrate`
`flynn run -r RELEASE_ID -l -- rake db:migrate`

I always get:

`POST https://controller.flynn.DOMAIN/apps/APP_NAME/jobs: httpclient: unexpected status 400`

Is this a bug or do I missed something during the setup? Where can I find the log-file, so I could debug the request further? Tailing `/var/log/upstart/flynn-host.log` doesn't gave any answer.

Thanks for any information and further help!

**Comment by lmars** [comment]
@nlsrchtr check the output of `flynn -a controller log` for any errors around the time you get the `400` response.

If you can't see anything obvious, run `sudo flynn-host collect-debug-info` on a host in your cluster and post the resulting gist link here and we'll take a look.

**Comment by nlsrchtr** [comment]
Hi @lmars, I think my setup (running flynn behind a NGINX proxy) is the reason for this behaviour. I change the setup and now it works as expected. Thanks for your response!
