### ISSUE TITLE
scheduler should ignore hosts that aren't accepting jobs

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#2981]
A single host in a cluster started hanging on `AddJob` calls, which caused the ratelimit to be exhausted indefinitely. This cluster was running a version before a69a455f9c92546b0dd91a212b3e22e84b2e72f0, so the scheduler tried to repeatedly place the job on the same host, resulting in perpetually pending jobs.

@lmars I'm not sure of the exact behavior with a69a455f9c92546b0dd91a212b3e22e84b2e72f0 when a host is misbehaving but not down. Do you think we need more code to handle this situation?

/cc @quentez

**Comment by lmars** [comment]
The scheduler has the concept of [a host check](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L939-L943) which it will perform if a host drops from discoverd, and if it fails more than 10 times the host is unfollowed which means jobs are no longer scheduled on that host (it also treats that host as gone and re-schedules all its jobs onto healthy hosts, see [here](https://github.com/flynn/flynn/blob/master/controller/scheduler/scheduler.go#L917-L937)).

It seems we should have a similar mechanism for dealing with hosts in the state described.

@titanous do you know why the calls were hanging, and did the scheduler get a HTTP timeout error or did it too hang?

**Comment by titanous** [comment]
The scheduler was getting the ratelimit error:

```text
lvl=eror msg="error adding job to the cluster" component=scheduler fn=StartJob app.id=0f5f6d25-2629-4892-8752-a049d4b8ad4e release.id=1990bb16-6cf7-4cd6-bb38-214d482d0f47 job.type=web err="ratelimited: maximum concurrent AddJob calls running, try again later"
lvl=info msg="failed to start job after 820 attempts, waiting 30s before trying again" component=scheduler fn=StartJob app.id=0f5f6d25-2629-4892-8752-a049d4b8ad4e release.id=1990bb16-6cf7-4cd6-bb38-214d482d0f47 job.type=web
```

Ping me if you want the full log.

**Comment by titanous** [comment]
Also, it's not clear that we should reschedule all jobs in this case, only stop placing new ones.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
