### ISSUE TITLE
AWS flynn install - the encrypted flag cannot be specified 

### ISSUE THREAD

**Issue by IsNull** [flynn/flynn#2983]
The installation of flynn on AWS fails with the flynn cli  `v20160624.0`. It worked about 3 weeks ago when I tested it the first time. Tested on **t2.medium** and **m4.large** both give the same error.

**AWS::EC2::Instance (Instance0)	CREATE_FAILED (the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified.)**

Log output of `flynn install`:
```
[...]
AWS::EC2::SubnetRouteTableAssociation (SubnetRoute)	CREATE_IN_PROGRESS
AWS::EC2::SubnetRouteTableAssociation (SubnetRoute)	CREATE_IN_PROGRESS (Resource creation Initiated)
AWS::EC2::Instance (Instance0)	CREATE_IN_PROGRESS
AWS::EC2::Instance (Instance0)	CREATE_FAILED (the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified.)
AWS::EC2::Route (GatewayRoute)	CREATE_FAILED (Resource creation cancelled)
AWS::EC2::SubnetRouteTableAssociation (SubnetRoute)	CREATE_FAILED (Resource creation cancelled)
Error: Failed to create stack flynn-1466785584
```

**Comment by titanous** [comment]
Indeed, I'll fix.

**Comment by titanous** [comment]
I'm starting a build now, I'll post an update when it's ready.

**Comment by IsNull** [comment]
Your reaction time is amazing. Im very impressed 😄

**Comment by titanous** [comment]
`v20160624.1` is out with the fix for this issue. Run `flynn update` to get it.
