### ISSUE TITLE
Using the apt buildpack in a multi-buildpack environment causes library issues

### ISSUE THREAD

**Issue by slurms** [flynn/flynn#2985]
When using [heroku-buildpack-apt](https://github.com/ddollar/heroku-buildpack-apt) to install additional required packages, I get library path issues.

.buildpacks:

```
    https://github.com/ddollar/heroku-buildpack-apt
    https://github.com/heroku/heroku-buildpack-python
```

Aptfile:

```
gettext
binutils
libproj-dev
gdal-bin
```

Pushing a python application with this setup works, but when running `flynn run python manage.py loaddata --format json - < data.json` I get the following error:

```
ImportError: Could not find the GEOS library (tried "geos_c", "GEOS"). Try setting GEOS_LIBRARY_PATH in your settings.
```

The [documentation](https://docs.djangoproject.com/en/1.9/ref/contrib/gis/install/geolibs/#can-t-find-geos-library) seems to suggest that something is broken with the library paths.

Similarly, in bin/post_compile:
```
python manage.py compilemessages
```

When it runs I get this error:

```
remote: CommandError: Execution of msgfmt failed: msgfmt: error while loading shared libraries: libgettextsrc-0.18.3.so: cannot open shared object file: No such file or directory
```

If I add the following to bin/post_compile, everything works:
```
export BUILD_DIR="/tmp/build"
export LD_LIBRARY_PATH="$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/lib/i386-linux-gnu:$BUILD_DIR/.apt/usr/lib:$LD_LIBRARY_PATH"
```

I guess we need to set `LD_LIBRARY_PATH` correctly in slugrunner and ensure that the paths are being set correctly for the post_compile step also.

**Comment by lmars** [comment]
@slurms I believe adding `libgeos-dev` to the `Aptfile` should fix the first issue.

Regarding `bin/post_compile`, I suspect whatever calls that script is not sourcing the files in `.profile.d` first (which is what would set `LD_LIBRARY_PATH`).

Is `bin/post_compile` specific to the Python buildpack? I don't think it is a standard buildpack thing, but I may be wrong.

**Comment by slurms** [comment]
@lmars yeah, you were right about the first issue, thanks.

`bin/post_compile` looks like it's not strictly Python specific, but it is an "experimental feature":

https://github.com/heroku/heroku-buildpack-python/blob/master/bin/compile#L231

I guess it's more of a problem with the buildpack than anything in Flynn!

**Comment by lmars** [comment]
@slurms there isn't much we can do about the post_compile issue, you should open an issue on the Python buildpack.

I will close this, please open a new issue if you continue to have problems.
