### ISSUE TITLE
Restore a backup v20160512 to v20160624.1 doesn't restore the TLS certificates

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2989]
Hi,
after upgrading from v20160512 to v20160624.1 from backup, all TLS routes have lost their certificate and are using some self signed ones now.
Currently, I'm restoring the routes manually by removing and adding them.

**Comment by titanous** [comment]
@jvatic this sounds like a bug in the migration

**Comment by jvatic** [comment]
I've reproduced this by booting a cluster locally from the v20160512.0 tag, creating a route with a cert, creating a cluster backup, and booting another cluster locally from the v20160624.1 tag (and also from the current master (c5a81ed)). There is an entry for the certificate in the router database which is empty (no cert or key).
