### ISSUE TITLE
Can't delete releases after upgrade from v20160512 to v20160624.1

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2990]
Hi,
I upgraded from v20160512 to v20160624.1 via backup restore and wanted to clean up some releases. But I just get "controller: resource not found" no matter what application I try?

> ➜  ~ flynn -a myapp release
> ID                                    Created
> 2173b16c-3999-4779-b363-ea6e9c285d1c  5 weeks ago
> 53ee727a-43f0-46b8-aecf-0c8608bca885  6 weeks ago
> ➜  ~ flynn -a myapp release delete 53ee727a-43f0-46b8-aecf-0c8608bca885
> Are you sure you want to delete release "53ee727a-43f0-46b8-aecf-0c8608bca885"? (yes/no): yes
> controller: resource not found

**Comment by titanous** [comment]
Is there a corresponding 404 in the controller web process log?

**Comment by philiplb** [comment]
I think yes?

> 2016-06-25T18:40:50.510472Z app[web.Flynn1-f90d0e08-b63d-4979-bf05-8915a40cf486]: t=2016-06-25T18:40:50+0000 lvl=info msg="request started" component=controller req_id=6596aedf-4414-4f2a-a340-031e49201859 method=DELETE path=/releases/e7047194-0bfb-4057-8b21-e6721cdcbb38 client_ip=79.247.154.120
> 2016-06-25T18:40:50.524595Z app[web.Flynn1-f90d0e08-b63d-4979-bf05-8915a40cf486]: t=2016-06-25T18:40:50+0000 lvl=info msg="request completed" component=controller req_id=6596aedf-4414-4f2a-a340-031e49201859 status=404 duration=13.971428ms

**Comment by lmars** [comment]
@philiplb what version of the Flynn CLI are you using (i.e. `flynn version` on your local machine)?

The path in the logs is `/releases/xxx` but it should be `/apps/xxx/releases/xxx` (changed in fe07945).

**Comment by philiplb** [comment]
That was it, I was on an old CLI version. Thank you! :)
