### ISSUE TITLE
Some orphans in the blobstore

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#2993]
Hi,
yesterday, I moved from the Postgres Blobstore to the S3 blobstore. Today, I cleaned up some old releases and also deleted an application.
This application has been created and deleted some days before.
I noticed, that there are still blobs from it in the S3 bucket.
How could I clean up such orphans?

**Comment by titanous** [comment]
Are they in the blobstore database or just S3?

**Comment by philiplb** [comment]
My sample file is also in the Table "files" of the Blobstore DB.

**Comment by lmars** [comment]
@philiplb are the remaining slugs from the app you deleted? There is a bug where deleting an app doesn't delete the associated releases (#2900) which I plan to fix soon.

**Comment by philiplb** [comment]
Yes, they are. Will this fix include some cleanup? (Would be NP to delete them manuall although :) )

**Comment by lmars** [comment]
@philiplb you should clean them up manually for now, watch #2900 for a proper fix.

**Comment by philiplb** [comment]
Ok, thank you. :)
