### ISSUE TITLE
flynn cli support for ARM

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#2997]
I was trying to get Flynn CLI running on Raspberry Pi. it gives me `cannot execute binary file: Exec format error`

how can I get git push rights to flynn on Pi without having Flynn CLI?

**Comment by philiplb** [comment]
ARM isn't supported, see https://flynn.io/docs/installation/manual :
> Flynn can be installed using our install script on Ubuntu 14.04 amd64.

**Comment by josephglanville** [comment]
It is potentially possible to build the CLI on ARM. However we would need to investigate what enumerations of `GOARM` and `GOARCH` values are necessary.

**Comment by hadifarnoud** [comment]
since there is no granular access control and one person can have access to all apps, we were going to use a Raspberry Pi to build a physical interface to Flynn. It would be quite easy to do if cli works on ARM.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
