### ISSUE TITLE
"Internal server error" on "git push"

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3000]
```
Counting objects: 25, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (25/25), 2.63 KiB | 0 bytes/s, done.
Total 25 (delta 10), reused 25 (delta 10)
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500 Internal Server Error
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
```

Status currently returns green for that cluster. https://bazaarvoice.box.com/s/gdv9rmpiqbob1v25upjn7q519xz99s0d is the debug-info.

**Comment by titanous** [comment]
@josephglanville This looks like discoverd instability, the cleaner logs make it easier to see the errors.

@temujin9 Have you had a chance to test out the S3 backend for the blobstore? We are evaluating options to prevent PostgreSQL load from impacting the system, but it has turned out to be quite a bit more complicated than it should be, so moving the load off of it until we get that resolved should improved stability.

**Comment by dottodot** [comment]
I'm having the same issue and I can't provide the debug info because I get an error of

```
host.go:136: unexpected HTTP status: 405
```

**Comment by titanous** [comment]
@dottodot Please gist the log from gitreceive.

**Comment by dottodot** [comment]
I ended up creating a new cluster as really need to push an update, but I still have access to the old one.

When I try and log gitreceive I get `host.go:136: no such job`

**Comment by titanous** [comment]
@dottodot you can run `flynn-host ps` get the IDs from the gitreceive jobs to provide to `flynn-host log`.

**Comment by dottodot** [comment]
Sorry I ended up deleting the problem cluster to save costs. I'll report back if it happens again on the current one.

**Comment by dottodot** [comment]
OK I've not go exactly the same error but I'm unable to push with a different error

```
remote: ERROR: Error retrieving app: Get http://controller.discoverd/apps/de0c1743-834a-41cd-a36b-0a9f754d2267: dial tcp: lookup controller.discoverd on [::1]:53: read udp [::1]:55125->[::1]:53: read: connection refused
To https://git.cloud.dottodotdesign.co.uk/bailey-live.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.cloud.dottodotdesign.co.uk/bailey-live.git'
```

and both occurred after running out of disk space which I used the script from this issue https://github.com/flynn/flynn/issues/3075 to fix

Here's my debug info
https://gist.github.com/5c545fc7a479c1b5448a5b1ef7080d66
https://gist.github.com/a5f8059a2667cde751926262702b2d15
https://gist.github.com/87550c4ccf4ca627b5bd1f0aa56f1fad

**Comment by temujin9** [comment]
@dottodot That sounds like a different error, which should probably go in its own ticket.

**Comment by dottodot** [comment]
OK I'm going to build a new cluster with the nightly build as had loads of various issues on the current stable one

**Comment by titanous** [comment]
Closing, as this issue is very old and it's not clear that it is still relevant.
