### ISSUE TITLE
Flynn installer doesn't respect FLYNN_VERSION environmental variable

### ISSUE THREAD

**Issue by brettneese** [flynn/flynn#3002]
When reinstalling a flaky node (long story, another bug report incoming), I attempt to run:

![image](https://cloud.githubusercontent.com/assets/504279/16392201/49fc73b6-3c70-11e6-888e-d883008684b2.png)

and then

![image](https://cloud.githubusercontent.com/assets/504279/16392175/2acab82c-3c70-11e6-896e-5c581105c05c.png)

but the installer insists on installing ```v20160624.1```: 

![image](https://cloud.githubusercontent.com/assets/504279/16392219/670fa5b8-3c70-11e6-8eec-ec7df96bd44d.png)

:(

Any suggestions on how I can coerce the installer to install the right version? I've also tried it inline (```FLYNN_VERSION=v20160512.0 sudo ./install-flynn```).

**Comment by lmars** [comment]
@brettneese `sudo` does not maintain environment variables by default, you should run:

```
sudo FLYNN_VERSION=v20160512.0 bash install-flynn
```

**Comment by brettneese** [comment]
Ahh, thought it might be something like that. 

A flag would be super useful, should I close this and open another issue?

**Comment by lmars** [comment]
See #3003.
