### ISSUE TITLE
Mailing list for stable releases

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#3008]
There should be a mailing list that I can join to be notified when a stable release is available.

**Comment by JMSwag** [comment]
@titanous Is there currently a matrix that shows which releases are stable?

**Comment by titanous** [comment]
https://releases.flynn.io just went up.

**Comment by JMSwag** [comment]
@titanous Thank you sir!

**Comment by titanous** [comment]
The releases mailing list is now available, you can subscribe to it here: https://flynn.io/docs/installation/cloud#release-mailing-list
