### ISSUE TITLE
Allow configuration of the deploy strategy from the CLI

### ISSUE THREAD

**Issue by quentez** [flynn/flynn#3010]
At the moment, it's possible to change the deploy strategy from `all-at-once` to `one-by-one` by directly changing the value in the controller DB:

```
flynn -a controller pg psql -- -c "UPDATE apps SET strategy = 'all-at-once' WHERE name = '<app_name>'"
```

It would be useful to have this as a configuration setting on the CLI, at least before we end up having other ways to set and version an app's configuration.

I would also like to suggest another strategy that would be `one-by-one-per-server`. Our reason for wanting a `one-by-one` deployment is to limit the impact on the app's performance, and in that regard it makes sense at a server level but not really at a cluster level (and the current `one-by-one` can take a really long time if the app is deployed across many nodes).

**Comment by lmars** [comment]
I think we should move the deployment strategy (and perhaps the deployment timeout) to app metadata so we don't have to keep adding explicit support for new variables, so something like:

```
$ flynn meta set deploy.strategy=one-by-one
$ flynn meta set deploy.timeout=120
```

@titanous @josephglanville @jvatic WDYT?

> I would also like to suggest another strategy that would be `one-by-one-per-server`

I'll be doing some work on moving deployments to jobs once #2744 is merged so I will take this into consideration.

**Comment by josephglanville** [comment]
I think the deployment strategy and other variables affecting how a job is deployed/scheduled should be per process rather than per app. If we could come up with a way to support it in the process type structure I think that would be ideal.

**Comment by titanous** [comment]
> the deployment strategy and other variables affecting how a job is deployed/scheduled should be per process

I agree, this would be ideal.

**Comment by lmars** [comment]
FYI the request for a "one per host" deployment strategy has been added in https://github.com/flynn/flynn/pull/4567.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
