### ISSUE TITLE
controller: Route certs not updated when migrating back to original domain

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#3015]
When migrating from domain `a` to domain `b` then back to domain `a` without passing in the original certificate causes routes for domain `a` to have the wrong cert (the existing routes won't be updated and will still have the original cert). To work around this simply remove all domain `a` related routes before migrating back to it.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
