### ISSUE TITLE
controller reports unhealthy when cannot reach discoverd on node not part of cluster.

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#3022]
There seems to be an issue when a cluster gets a replacement node. Basically, I'm seeing an EC2 instance go down for a cluster. The replacement EC2 instance joins the cluster just fine, but I'll see controller get intermittent errors saying it couldn't reach the `discoverd` component on the IP address of the EC2 instance that went down.

Since our monitoring tool creates an incident everytime the flynn status endpoint reports unhealthy, this intermittent error causes a great deal of flappiness. It seems like when the error appears, the status for `controller` will report unhealthy. Then it will report healthy again after a few seconds. This will just repeat endlessly.

This is for `v20160627.0` of flynn. I will post links to logs in a bit. CC @temujin9.

**Comment by tianx2** [comment]
Here's a link to the logs - https://bazaarvoice.box.com/s/oasrx97y6nf8s0jyfoim5u7e4ar6l8z4

I only grabbed logs from two nodes so far as I'm having strange download speed issues copying files from AWS.

**Comment by tianx2** [comment]
I updated the box link with all the logs from a cluster that ran into this particular problem. let me know if there is anything you need before i tear it down.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
