### ISSUE TITLE
cli: Attach arbitrary files to releases

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3026]
I should be able to attach arbitrary files to a release which are then available to app processes.

Releases already have many [FileArtifacts](https://github.com/flynn/flynn/blob/master/controller/types/types.go#L21) which are downloaded into `/artifacts` [before a job starts](https://github.com/flynn/flynn/blob/master/host/containerinit/init.go#L411-L429) (this is how slugs work), so we just need a way to add file artifacts using the CLI, for example:

```
$ flynn file add path/to/file
```

This would upload the file to the blobstore, create an artifact and add it to `release.FileArtifacts`.

This would for example allow users to attach TLS certificates to a release and read them from the disk in the job.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
