### ISSUE TITLE
Release pipeline improvements

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3040]
We need to update the release pipeline to better support applying changes to different release channels and support the UI changes proposed in #2844.

What I propose:

### Release chain

The first part of a version (e.g. `v20160624` in `v20160624.1`) becomes a "release chain" which can have patches applied to it.

### Applying changes to a release chain

Create a branch named after the chain (e.g. `v20160624`), pull request into it, then once merged have the release machine build that branch with a minor version bump (e.g. to `v20160624.2`). Building a chain branch does not update any channels.

### Releasing changes to a channel

Once the required changes have been applied to the chain currently pointed to by the channel, point the channel at the released version as we do now (e.g. `script/release-channel stable v20160624.2`).

### Changelog

Changelogs are generated when updating a channel with the `script/release-channel`. By default they are a list of merged pull requests since the current version on that channel, but can be overridden with a flag so we can have custom Changelog descriptions (e.g. when doing a monthly stable release).

Changelogs are stored in the tuf repo in `/channel/{name}/{version}/changelog.txt` (e.g. `/channel/stable/v20160624.1/changelog.txt`), and can be read by the release UI and displayed to the user.

### Channel history

Since all channel updates generate a Changelog, channel history can be determined by listing sorted entries in the tuf repo like `/channel/{name}/v*`.

/cc @titanous @josephglanville @jvatic thoughts?

**Comment by titanous** [comment]
For changes to a "release chain" (which should be quite rare), should we instead mark the version with a "patch number"? (ie. `v20160624.1p1`)

**Comment by lmars** [comment]
@titanous I did think of that, but then it wasn't clear how we use pul requests / branches to indicate that the release machine should build it.

We could go with something more manual (e.g. call the branch whatever you want like `stable-hotfix-1`, and then after merge run something like `script/release-branch stable-hotfix-1 v20160624.1p1` followed by `script/release-channel stable v20160624.1p1`), WDYT?

As you say, doing this will be rare so maybe it is fine as a more manual thing.

**Comment by lmars** [comment]
I guess you could just call the branch `v20160624.1p1`?

**Comment by titanous** [comment]
The script could detect the `pN` suffix and look for a branch named for the release number without the patch number? Also, to prevent having tags and branches with the same name, we probably want to call it RELEASE-hotfix or similar.

**Comment by lmars** [comment]
@titanous ok, so how about this:

* pull request and merge into a branch named `v20160624.1-xxx` (where `xxx` can be anything, e.g. `hotfix`)
* release machine detects a push to one of these release branches and builds a patch version (e.g. `v20160624.1p1`)
* once released, we manually run `script/release-channel stable v20160624.1p1`

So there is no release chain, just individually patched versions.

**Comment by titanous** [comment]
Yep, that sounds fine (though I think it will probably be manually triggered instead of automatically by the PR merge)

**Comment by lmars** [comment]
These changes have been made in #3062. Once we have some releases with changelogs, the next step will be to add a UI (most likely with a JSON API backend) (#2844).
