### ISSUE TITLE
appliance/mongodb: Wrong protocol in DATABASE_URL

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#3043]
It appears [DATABASE_URL](https://github.com/flynn/flynn/blob/5672516c3e42d5f6bce0ed487eb5e3fbdd8ee18e/appliance/mongodb/cmd/flynn-mongodb-api/main.go#L85) should have a [`mongodb` protocol](https://docs.mongodb.com/manual/reference/connection-string/) (currently uses `mongo`).

**Comment by titanous** [comment]
Indeed, please fix.
