### ISSUE TITLE
Updating env var reverts to old slug

### ISSUE THREAD

**Issue by dashkb** [flynn/flynn#3048]
Encountered a problem today where I'd deploy, see my changes live, update an env var and see my changes go away.  It's now been multiple deploys, but each time I set a config var it's still using that same slug from ~~before I started working today.~~ days ago!

**Comment by titanous** [comment]
What version of Flynn? `flynn-host version`

**Comment by dashkb** [comment]
v20160512.0

**Comment by titanous** [comment]
How are you updating the end? Is it possible that you are setting the `SLUG_URL` variable?

**Comment by dashkb** [comment]
Thank you!  It was set from a `flynn import`.

**Comment by dashkb** [comment]
...although I'd still expect a deploy to overwrite/unset it.

**Comment by titanous** [comment]
I'm unclear on the exact sequence of events here, however we have moved the slug field out of the env in more recent releases.

**Comment by dashkb** [comment]
Hey @titanous I've built a new cluster again today and this is happening again.  The SLUG_URL is set in the environment, and now I'm not able to unset it.

```
❯ f -a production env unset SLUG_URL
web process type failed to start, got down job event
```

Exact sequence of events:

1. build new cluster
2. import app from `flynn export`
3. `git push` new code; everything OK
4. set an env var, reverts back to old slug from two clusters ago
5. `git push` new code, everything OK
6. goto 4

What do you think?

**Comment by titanous** [comment]
What version of Flynn are you running?

**Comment by dashkb** [comment]
v20160624, installed via the AMI

**Comment by titanous** [comment]
The SLUG_URL env var is not used at all in that version. By slug reverts back, do you mean that the app reverts back to a previous release?

**Comment by dashkb** [comment]
Yes, the app is reverting to a previous release.  Additionally, I'm seeing 

```
2016-07-18T20:20:39.079279Z app[web.ip1723135113-113e5e50-f880-4b03-9f01-5864f80ec21d]: gzip: stdin: unexpected end of file
2016-07-18T20:20:39.079351Z app[web.ip1723135113-113e5e50-f880-4b03-9f01-5864f80ec21d]: tar: Child returned status 1
2016-07-18T20:20:39.079417Z app[web.ip1723135113-113e5e50-f880-4b03-9f01-5864f80ec21d]: tar: Error is not recoverable: exiting now
2016-07-18T20:20:39.901402Z app[web.ip1723135112-8e5a59ff-2040-41a9-8b0a-1b3da977d3d2]:
2016-07-18T20:20:39.901550Z app[web.ip1723135112-8e5a59ff-2040-41a9-8b0a-1b3da977d3d2]: gzip: stdin: unexpected end of file
2016-07-18T20:20:39.901891Z app[web.ip1723135112-8e5a59ff-2040-41a9-8b0a-1b3da977d3d2]: tar: Child returned status 1
2016-07-18T20:20:39.902034Z app[web.ip1723135112-8e5a59ff-2040-41a9-8b0a-1b3da977d3d2]: tar: Error is not recoverable: exiting now
```

in the app's logs, which persists until I push code again.

**Comment by lmars** [comment]
@dashkb what is your local CLI version (`flynn version`)?

**Comment by dashkb** [comment]
Old... v20160216.0.  Should I upgrade?

**Comment by lmars** [comment]
@dashkb yes run `flynn update` and let us know if it fixes your issue.

**Comment by dashkb** [comment]
OK everything seems to be working now.  Thanks for your help as usual.

One bit of oddness- `flynn run` no longer prepares the things; I have to run `flynn run /runner/init [my command]`; not a big deal.

**Comment by titanous** [comment]
Great to hear! That issue is tracked in #3154 and is currently being fixed.
