### ISSUE TITLE
dashboard: routing links don't contain the path

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3050]
Hi,
after adding a route to "https://myapp.foo.bar/dev", I noticed that it shows up in the dashboard correctly as "myapp.foo.bar/dev", but the href of the link leads to "http://myapp.foo.bar". It would be nice, if the href would also contain the path (/dev) and the protocoll (https if a certificate is given).

**Comment by jvatic** [comment]
See #2463 for adding https links
