### ISSUE TITLE
Can't backup no space left on device

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3052]
Nearly every time I try and create a new cluster I run into the issue when backing up of 

> error dumping postgres database: error exporting: write backup.tar: no space left on device

which leaves me no option but to have to start from fresh which is less than ideal.

How can I free up some space so I can do and backup and restore without running into this issue?

Also I guessing that the cluster that's being backed up requires a certain amount of free space so perhaps this should be documented.

**Comment by philiplb** [comment]
Can you delete some old releases?

**Comment by dottodot** [comment]
Ah ok that worked. Is there a way to delete multiple releases at a time as it's a bit of a pain doing them individually when you have a lot.

**Comment by titanous** [comment]
You can enable garbage collection

```text
flynn meta set gc.max_inactive_slug_releases=N
```

Which will prune everything but the most recent N releases after each deploy.

**Comment by dottodot** [comment]
OK great, thanks for your help.

**Comment by JMSwag** [comment]
@titanous Can this be set globally?

**Comment by lmars** [comment]
@JMSwag the garbage collection flag cannot currently be set globally, please open a new issue requesting that.

**Comment by JMSwag** [comment]
@lmars ack
