### ISSUE TITLE
Support deploying tarballs

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#306]
It should be easy to deploy using a tarball (without using git).

This is currently possible on the development box by doing the following (after installing [jq](http://stedolan.github.io/jq/)):

```
$ flynn create example
Created example
$ export CONTROLLER_AUTH_KEY="<key from bootstrap output>"
$ export SLUGRUNNER_IMAGE_ID=$(jq --raw-output '.["flynn/slugrunner"]' version.json)
$ export SLUGBUILDER_IMAGE_ID=$(jq --raw-output '.["flynn/slugbuilder"]' version.json)
$ (cd test/apps/basic; tar c .) | receiver/flynn-receiver example
-----> Building example...
-----> Node.js app detected
-----> Requested node range: 0.10.x
-----> Resolved node version: 0.10.32
-----> Downloading and installing node
-----> Installing dependencies
       npm WARN package.json node-example@0.0.1 No description
       npm WARN package.json node-example@0.0.1 No repository field.
       npm WARN package.json node-example@0.0.1 No README data
-----> Cleaning up node-gyp and npm artifacts
-----> Building runtime environment
-----> Discovering process types
       Procfile declares types -> web
-----> Compiled slug size is 5.5M
-----> Creating release...
=====> Application deployed
=====> Added default web=1 formation
```

**Comment by philiplb** [comment]
+1
There might be situations where you don't have a git repository or where your CI slightly alters some code depending on the environment.

**Comment by philiplb** [comment]
Any plans for this in the (somewhat) near future? :)

**Comment by lmars** [comment]
Given we now have `flynn docker push IMAGE`, you can accomplish this by building a Docker image for your app and pushing that instead.

We may still want to consider adding something like `flynn tarball push path/to/tar` though which runs the slugbuilder on the tarball and deploys.

**Comment by lmars** [comment]
FYI since dd8cff9, this can now be achieved by running a job with the `gitreceive` app and passing the tarball via stdin:

```
tar c . | flynn -a gitreceive run /bin/flynn-receiver APPNAME REVISION
```

The `REVISION` arg can be any string (it doesn't affect any part of the deploy).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
