### ISSUE TITLE
Docker-receive failing with 500, "error authorizing context: basic authentication failed"

### ISSUE THREAD

**Issue by brettneese** [flynn/flynn#3067]
When I try and deploy any docker image on ```v20160620.1```, I end up with a ```received unexpected HTTP status: 500 Internal Server Error``` after I do ```flynn docker login``` (which receives no output, but no errors, either) and, for instance, ```flynn -a hello-world docker push google/nodejs-hello:latest.``` (After creating ```hello-world```, of course.)

FWIW, this is from a bash script on a Jenkins Docker image running on Docker on a different machine (non-Flynn), but I've verified that my ```~/.flynnrc``` is correct by comparing it across both machines. I can't do it locally, either - I'm running into issues with the CA certs on my OS X local machine which I haven't had time to really debug. (I tried the steps in the prompt to no avail, which is fine, we'll be deploying from this jenkins box, anyway.) 

I've also tried several different things by attaching myself directly to the box and running the same commands. No dice there, either.

Looking at the docker-receive logs, I notice I'm getting:

```2016-07-06T21:37:09.123568Z app[app.ip172315675-1997a1d4-f54f-4484-bafc-00c2e955b86c]: time="2016-07-06T21:37:09Z" level=warning msg="error authorizing context: basic authentication failed" http.request.host="100.100.76.11:80" http.request.id=26e54a31-9633-4a76-a246-ebad40205cf7 http.request.method=GET http.request.remoteaddr="100.100.76.11:47671" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=054ca103-106a-41f0-83ec-1c1b48cbfb53 version=v20160624.1```

Help?

**Comment by titanous** [comment]
Can you confirm that the output of `flynn -a controller env get AUTH_KEY` matches the string returned from `flynn -a docker-receive env get AUTH_KEY`?

**Comment by brettneese** [comment]
It does.

One note I just found out - I'm using Amazon's ECR service as our registry. Interestingly, when I delete the ```~/.docker/config.json``` file and then run ```flynn docker login``` again, the auths for ECR come back as well as the Flynn auths. Is it possible something is caching something?

I've also tried doing a  ```docker login``` after browsing the source - this returns "login successful" but I still have auth errors when I try to push.

**Comment by brettneese** [comment]
However, I just tried accessing the Docker registry via curl*, using the auth header in ~/.docker/config.json, and that works just fine.

```curl --cacert /Users/brettneese/.flynn/ca-certs/default.pem   -X GET https://docker.flynn.$HOST.com/v2/ -H "Authorization: Basic $TOKEN"````

**Comment by lmars** [comment]
@brettneese can you gist the full output of the `flynn docker push`? Particularly the output of `docker push`?

**Comment by lmars** [comment]
@brettneese also, what version of docker are you using?

**Comment by brettneese** [comment]
```Docker version 1.11.2, build b9f10c9``` 

I'll get you the full output in just a sec.

**Comment by brettneese** [comment]
```flynn: getting image config with "docker inspect -f {{ json .Config }} 613658333627.dkr.ecr.us-east-1.amazonaws.com/crapi:development"
flynn: tagging Docker image with "docker tag --force 613658333627.dkr.ecr.us-east-1.amazonaws.com/crapi:development docker.flynn.hbkapps.com/crapi-development:latest"
Warning: '--force' is deprecated, it will be removed soon. See usage.
flynn: pushing Docker image with "docker push docker.flynn.hbkapps.com/crapi-development:latest"
The push refers to a repository [docker.flynn.hbkapps.com/crapi-development]
9ebe0ca3ebca: Pushing   686 MB/686 MB
39b8b56a94f0: Pushing 44.18 MB/44.18 MB
77bc0e7a04da: Pushing 30.66 MB/30.66 MB
01fc208968f4: Pushing 30.99 MB/30.99 MB
87af935eabc7: Pushing  2.56 kB
69ba6958f010: Retrying in 5 seconds 
4520469d298c: Pushing 526.8 kB/465.8 MB
d7f060d78a05: Pushing 529.8 kB
c56d4afe16bc: Waiting 
d6d4774beb42: Waiting 
c4df50b6a1e3: Waiting 
e9637161bc7f: Waiting 
2321aed56776: Waiting 
13485739f910: Waiting 
bf6734d83178: Waiting 
b0c9806990b8: Waiting 
aba531537a76: Waiting 
97184b2c7a26: Waiting 
1eff6a7da46d: Waiting 
f860b2678c51: Waiting 
5f4dfaa92570: Waiting 
5f70bf18a086: Waiting 
a3cc72c42c61: Waiting 
912d12501c4d: Waiting 
cd0736ada991: Waiting 
c4af1604d3f2: Waiting 
received unexpected HTTP status: 500 Internal Server Error
exit status 1```

**Comment by lmars** [comment]
@brettneese ok so it is managing to push some data, but then on failing it is falling back to a different transport and not using the correct authentication.

Can you gist the output of `flynn -a docker-receive log`?

**Comment by brettneese** [comment]
https://gist.github.com/brettneese/8581633bd64c1150254050cf51ae75fa

**Comment by titanous** [comment]
Looks like the error is that we don't have valid certificate roots in the container:

```text
x509: failed to load system roots and no roots provided
```

I'll fix.

**Comment by brettneese** [comment]
I'm also just now noticing some AWS errors (we're using our blobstore on S3) - is that related? 

Also, will there be any way we can hotfix your changes rather than waiting for a stable release?

**Comment by titanous** [comment]
Yeah, those are the same errors I saw. I think we can set you up with a hotfix once I get the fix merged and released.
