### ISSUE TITLE
Wrong version of nodejs installing

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3070]
I have the following in my package.json

```
"engines": {
        "node": "4.x"
    }
```
but node 5.11.1 is installed instead

**Comment by titanous** [comment]
I get this when I specify that version in a `package.json`:

```text
-----> Installing binaries
       engines.node (package.json):  4.x
       engines.npm (package.json):   unspecified (use default)

       Resolving node version 4.x via semver.io...
       Downloading and installing node 4.4.7...
       Using default npm version: 2.15.8
```

Can you provide the buildpack output? Are you sure that you are pushing a git tree that contains the correct `package.json`?

**Comment by dottodot** [comment]
Yes sorry, me being stupid and pushing wrong branch
