### ISSUE TITLE
PPS During Build Caused Null Routing with Server Provider

### ISSUE THREAD

**Issue by mbreisch** [flynn/flynn#3076]
Hi,

During a build of a django app, my server provider null routed all traffic to one node based on a potential DDOS on UDP port 8472. I believe from what I've been reading this is a flynn port. I have attached the logs. If this indeed was caused by the builder, could further issues like this be avoided if I switch to the S3 blob storage backend.

Any assistance would be appreciated.
Edited: Added the wrong link.
[Logs attached here.](https://gist.github.com/anonymous/62598cc0c261f88780fe10b7999182b1)

**Comment by titanous** [comment]
That port is used for substantially all of Flynn's communication, which is over the VXLAN overlay network protocol. Tell your provider to whitelist inter-host communication, there should be no inbound traffic from the internet hitting that port.

**Comment by mbreisch** [comment]
Okay, I'll do that thanks. They recommended that I setup VLan instead of using VXLan, I can only assume this is not a possibility at the moment.

**Comment by titanous** [comment]
The networking setup will change in the next few months, but it's going to shift from unencrypted VXLAN to a fully encrypted overlay network with less overhead. It will still be over UDP to a single port. It's very unlikely that we're going to switch away from the UDP overlay network model.
