### ISSUE TITLE
scheduler "error persisting job" due to 404 from controller

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3092]
Not sure what causes this, I've seen it in most Flynn clusters that have anything interesting running on them (look at CI logs for lots of examples).

``` text
lvl=eror msg="error persisting job" component=scheduler fn=RunPutJobs job.id=f124815b-b30e102b-c00c-42b3-a38b-1a14d6863c9f job.state=down err="controller: resource not found"
```

**Comment by lmars** [comment]
This could happen when deleting an app, which scales down related formations but then persisting the job state will get a 404 as the app has gone.

**Comment by lmars** [comment]
We should probably not scope jobs by app for `PutJob` as we need to mark the job as down regardless of whether the app is deleted or not.
