### ISSUE TITLE
Cluster completely broken

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3095]
My apps seem to still be running but pretty much everything else doesn't work such as

flynn ps
backup
dashboard
can't collect debug info

even fix hosts end on an error of
```14:00:30.676978 host.go:136: already have enough instances, unable to fix```

is there anything I can do that will help fix it at least so that I can backup to a new cluster

**Comment by titanous** [comment]
This gist describes how to manually take a backup: https://gist.github.com/titanous/36754c1da91c632640a7

**Comment by dottodot** [comment]
so if I have the following in zfs list how do I know which one to take a snapshot of?

```
NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
flynn-default                                       22.7G  13.2G    19K  /flynn-default
flynn-default/11542b19-b5ba-4fdd-a38f-f4c371ea14e9  18.7G  13.2G  18.7G  /var/lib/flynn/volumes/zfs/mnt/11542b19-b5ba-4fdd-a38f-f4c371ea14e9
flynn-default/3169f0b9-5337-4777-bd8b-552a7daac9d7  3.92G  13.2G  3.92G  /var/lib/flynn/volumes/zfs/mnt/3169f0b9-5337-4777-bd8b-552a7daac9d7
flynn-default/935d8c53-b17d-457a-b76a-6b94015a30dc    20K  13.2G    20K  /var/lib/flynn/volumes/zfs/mnt/935d8c53-b17d-457a-b76a-6b94015a30dc
flynn-default/c731e101-1399-4f5c-9d62-43b83f638d89   534K  13.2G   534K  /var/lib/flynn/volumes/zfs/mnt/c731e101-1399-4f5c-9d62-43b83f638d89
flynn-default/c7b286a8-771d-47ad-a82e-fa1b0090ae6f    20K  13.2G    20K  /var/lib/flynn/volumes/zfs/mnt/c7b286a8-771d-47ad-a82e-fa1b0090ae6f
```

**Comment by titanous** [comment]
The largest one, `flynn-default/11542b19-b5ba-4fdd-a38f-f4c371ea14e9`.

**Comment by dottodot** [comment]
Any idea how I get past 

error connecting to postgresFATAL: password authentication failed for user "postgres" (SQLSTATE 28P01)

**Comment by titanous** [comment]
You may need to tweak the `pg_hba.conf`. I haven't seen that error before, was postgres already installed on the server?

**Comment by dottodot** [comment]
no this is the first time it's been installed. Any idea what I need to change as can't see anything obvious?

**Comment by titanous** [comment]
You could try changing the `pg_hba.conf` in the data directory as well as `/etc/postgres/9.4` to something like this:

```text
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128            trust
local   all             all                                     trust
```

**Comment by dottodot** [comment]
Ok that worked but now I get the following error

```
2016/07/11 15:03:53 connecting to postgres
2016/07/11 15:03:53 error getting db nameno rows in result set
```

**Comment by titanous** [comment]
It sounds like the postgres that you have running is not pointing at the data directory from Flynn. Try stopping the running postgres process and making sure that you run it using the command from the document so that it points at the Flynn data.

**Comment by dottodot** [comment]
Ok seem to be getting closer and I got the following output but now it's seem to be stuck on autovacuum launcher started

```
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:36.803 UTC LOG:  database system was interrupted; last known up at 2016-07-11 13:02:40 UTC
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:36.847 UTC LOG:  database system was not properly shut down; automatic recovery in progress
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:36.852 UTC LOG:  redo starts at 3/57000060
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:36.890 UTC LOG:  record with zero length at 3/59009CC0
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:36.890 UTC LOG:  redo done at 3/59009C90
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:36.890 UTC LOG:  last completed transaction was at log time 2016-07-11 13:09:52.154658+00
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:37.030 UTC LOG:  MultiXact member wraparound protections are now enabled
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:37.033 UTC LOG:  database system is ready to accept connections
0c8380b9-63b7-475f-85f0-6c816e00f7c5 2016-07-11 15:11:37.033 UTC LOG:  autovacuum launcher started
```

**Comment by titanous** [comment]
Nothing is stuck, postgres is running as expected in the foreground, run the dump tool in another window.

**Comment by dottodot** [comment]
Ok so I'm trying to restore the backup now but I'm getting the following error

```
15:42:08.213834 run-app discoverd
15:42:08.407484 run-app discoverd error: bootstrap: host error while launching job: "unknown capability \"CAP_AUDIT_READ\""
```
Is this a problem with the backup or something else

**Comment by titanous** [comment]
Something else, what is the output of `uname -a`?

**Comment by dottodot** [comment]
Linux cluster7 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by titanous** [comment]
Ah, you'll need to update your kernel to 3.16 or greater (latest from Ubuntu should be 3.19).

**Comment by dottodot** [comment]
Ok that worked but on my restore it's been on status-check status for 15 minutes now which seems a bit long compared to previous restores

**Comment by dottodot** [comment]
Ignore that it's just finished.

But I think all I've done is restore the problem onto the new cluster. For example flynn -a bailey-live ps returns unknown_error: Something went wrong

**Comment by titanous** [comment]
Please post the debug info.

**Comment by dottodot** [comment]
https://gist.github.com/390451ccc07dc6d4fc878380ff0c7065
https://gist.github.com/3efc34b79f8ed937068570c9a78fd910
https://gist.github.com/a3b665a6379937689b75c1a6e98243f1

**Comment by titanous** [comment]
I don't see a corresponding request or error in the logs, are you sure you are talking to the right endpoint with the client and not the old cluster?

**Comment by dottodot** [comment]
Oh yes, sorry been a nightmare afternoon and my brain is scrambled.

**Comment by dottodot** [comment]
OK that's all good.

One last think is I have a pending job

```
ID                                             TYPE             STATE    CREATED         RELEASE
c7452b36-b2db-43f4-b756-1824e17e885e           web              pending  4 hours ago     6985ce7e-9731-4acc-856f-628587b3457e
```
I've tried killing it  but I get unknown_error: Something went wrong

**Comment by titanous** [comment]
That's an extraneous database entry from the backup, @lmars will provide advice on how to remove it and file an issue about fixing that. You can ignore it for now, it will have no impact on anything.

**Comment by lmars** [comment]
@dottodot run the following to mark the pending job as down:

```
$ flynn -a controller pg psql -- -c "UPDATE job_cache SET state = 'down' WHERE job_id = 'c7452b36-b2db-43f4-b756-1824e17e885e'"
```

I'm working on a proper fix now.

**Comment by dottodot** [comment]
Great thanks I'm all up and running again.

**Comment by dottodot** [comment]
OK I'm back having to do the manual backup as my cluster is broken but when i run

```
/usr/lib/postgresql/9.4/bin/postgres -D /var/lib/flynn/volumes/zfs/mnt/pg-restore/db
```
i get the error

> postgres cannot access the server configuration file "/var/lib/flynn/volumes/zfs/mnt/pg-restore/db/postgresql.conf": Permission denied

and I've changed the permissions using

```
# Change the permissions to our current user

sudo chown -R $(id -u):$(id -g) /var/lib/flynn/volumes/zfs/mnt/pg-restore
```
and i've checked that the ownership is set correctly so no idea why it doesn't work, I didn't have this problem last time

**Comment by titanous** [comment]
What version of Flynn are you trying to recover?

**Comment by dottodot** [comment]
Currently trying to backup on v20160711.0 so I can create a new cluster using v20160717.0

I've tried the normal way but it won't backup which was expected as pretty much everything else isn't working either.

**Comment by titanous** [comment]
We updated to Postgres 9.5, so you'll need to use it instead of 9.4.

**Comment by dottodot** [comment]
Ok so I did

```
apt-get install \
  postgresql-9.5 \
  postgresql-contrib-9.5 \
  postgresql-9.5-pgextwlist \
  postgresql-9.5-plv8 \
  postgresql-9.5-postgis \
  postgresql-9.5-pgrouting
```
then 
```
/usr/lib/postgresql/9.5/bin/postgres -D /var/lib/flynn/volumes/zfs/mnt/pg-restore/db
```
which gives the same error of

> postgres cannot access the server configuration file "/var/lib/flynn/volumes/zfs/mnt/pg-restore/db/postgresql.conf": Permission denied

**Comment by titanous** [comment]
Does that file exist? Can you read it?

**Comment by dottodot** [comment]
Only as the sudo and I've checked the owner / group and they are set to the current user so doesn't make much sense.

**Comment by titanous** [comment]
Try `sudo chmod u+r /var/lib/flynn/volumes/zfs/mnt/pg-restore/db/postgresql.conf`

Maybe it lost the read bit?

**Comment by dottodot** [comment]
Nope not that either, I've tried on 2 different servers and get the same issue, very confusing.

Do you know of any way to get postgres to accept starting using the root user as I'd then be able to get around it.

**Comment by titanous** [comment]
I'm pretty sure Postgres is hard-coded not to run as root. I assume you've checked that the permission flags look right with `ls -la`? Can you post the output here?

**Comment by dottodot** [comment]
yes they look ok to me

```
1 -rwxr-xr-x 1 marcus marcus  207 Jul 11 16:37 backup_label.old
2 drwxr-xr-x 8 marcus marcus    8 Jul 11 16:37 base
3 drwxr-xr-x 2 marcus marcus   54 Jul 11 16:37 global
1 drwxr-xr-x 2 marcus marcus    3 Jul 11 16:37 pg_clog
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_commit_ts
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_dynshmem
1 -rwxr-xr-x 1 marcus marcus  345 Jul 11 16:37 pg_hba.conf
3 -rwxr-xr-x 1 marcus marcus 1636 Jul 11 16:37 pg_ident.conf
1 drwxr-xr-x 4 marcus marcus    4 Jul 11 16:37 pg_logical
1 drwxr-xr-x 4 marcus marcus    4 Jul 11 16:37 pg_multixact
1 drwxr-xr-x 2 marcus marcus    3 Jul 11 16:37 pg_notify
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_replslot
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_serial
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_snapshots
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_stat
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_stat_tmp
1 drwxr-xr-x 2 marcus marcus    3 Jul 11 16:37 pg_subtrans
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_tblspc
1 drwxr-xr-x 2 marcus marcus    2 Jul 11 16:37 pg_twophase
1 -rwxr-xr-x 1 marcus marcus    4 Jul 11 16:37 PG_VERSION
5 drwxr-xr-x 3 marcus marcus  158 Jul 15 12:32 pg_xlog
1 -rwxr-xr-x 1 marcus marcus   88 Jul 11 16:37 postgresql.auto.conf
2 -rwxr-xr-x 1 marcus marcus 1147 Jul 11 16:37 postgresql.conf
1 -rwxr-xr-x 1 marcus marcus   53 Jul 11 16:37 postmaster.opts
1 -rwxr-xr-x 1 marcus marcus   57 Jul 11 16:37 postmaster.pid
1 -rwxr-xr-x 1 marcus marcus  252 Jul 11 16:37 recovery.conf
```

**Comment by titanous** [comment]
Try reading the file after running `sudo chmod a+r /var/lib/flynn/volumes/zfs/mnt/pg-restore/db/postgresql.conf`

**Comment by dottodot** [comment]
no that's not worked either

**Comment by titanous** [comment]
Okay, I'd try copying the files out to the `/` filesystem somewhere and see if it works better there.

**Comment by dottodot** [comment]
OK didn't have enough room so had to add some space and mangement to get past the issues problem but now I get 

> server version: 9.5.3; pg_dumpall version: 9.4.8
aborting because of server version mismatch

so should I actually be using postgres 9.4 and not 9.5?

**Comment by titanous** [comment]
The `pg_dumpall` command from your path is from 9.4, change the PATH so that the binary from 9.5 comes first.

**Comment by dottodot** [comment]
sorry you've lost me now, do you mean in the faildump script, if so the one download in the instructions seems to be encrypted or can I just create my own from the gist?

**Comment by titanous** [comment]
You could just uninstall the postgres 9.4 packages.

**Comment by dottodot** [comment]
That now gives me 

> sh: 1: /usr/lib/postgresql/9.4/bin/pg_dumpall: not found

**Comment by titanous** [comment]
Ah, it's hard-coded in the binary. Give me a minute.

**Comment by titanous** [comment]
Use this one instead: [faildump.gz](https://github.com/flynn/flynn/files/369468/faildump.gz)

**Comment by dottodot** [comment]
Nice one that's working

**Comment by dottodot** [comment]
Now on restore I'm getting 

> host.go:153: error getting controller instance: discoverd: timed out waiting for instances

not sure if it's related to my previous issues or new

https://gist.github.com/6f7152454943f3e04d3f8ad22832d567 
https://gist.github.com/db34b4327d548124a25fc086b58f9ab2 
https://gist.github.com/131c1983f0960201757ac61042f43eab

**Comment by titanous** [comment]
Looks like a new bug in the nightly, I'll open an issue.

**Comment by titanous** [comment]
#3148

**Comment by dottodot** [comment]
OK can you keep me posted as to when to fix is available as still stuck with a broken cluster at the moment and I can't push any updates.

**Comment by titanous** [comment]
Sure, I'm going to fix it today.

**Comment by titanous** [comment]
@dottodot The fix is in `v20160719.0`

**Comment by dottodot** [comment]
Thanks I updated to this this morning and all working now.

**Comment by titanous** [comment]
Great!
