### ISSUE TITLE
All apps deployed from Docker image via docker-receive showing "service unavailable"

### ISSUE THREAD

**Issue by brettneese** [flynn/flynn#3097]
On a fairly fresh cluster, except with the newer docker-receive per https://github.com/flynn/flynn/pull/3069#issuecomment-231137775, Flynn refuses to  route to apps, showing just a "Service Unavailable." 

I've tried even the barest bones Node.js Docker image (https://github.com/jlchereau/Docker-AWS), alongside 3 of our own apps -- all return the same error. Dashboard and other Flynn non-Docker released apps seem to load just fine; haven't tried a custom buildpack-built app on this cluster.

Apps are scaled and have the correct ports (I think). No abnormalities in the app logs. Restarting the (single in the case) Flynn host didn't fix anything. 

```Flynn host version v20160624.1.``` 

``flynn-host collect-debug-logs`` was actually to big for gist, so [here's an s3 link](https://s3.amazonaws.com/hbkapps-org/flynn-host-debug.tar.gz
) to the ``.tar.gz``

**Comment by lmars** [comment]
@brettneese looks like the default route for apps pushed with `docker-receive` have the wrong service (`APPNAME-web` instead of just `APPNAME`), we'll work on a fix for that.

In the meantime, you can fix the route by grabbing the route ID from `flynn -a APPNAME route` and updating it with:

```
$ flynn -a APPNAME route update $ID --service APPNAME
```

**Comment by brettneese** [comment]
What are the chances a fix for this will land in the next stable release? It's incredibly annoying.

**Comment by titanous** [comment]
I'll fix it now. The bug is in the CLI, so it will go out with the next nightly.

**Comment by titanous** [comment]
Fix is in #3159.

**Comment by brettneese** [comment]
@titanous how do you download nightly releases of the CLI?

**Comment by titanous** [comment]
`flynn update`

**Comment by brettneese** [comment]
Ah, @mnaughto passed your message onto me as well. Didn't realize the CDN only had nightly releases. Thanks. 👍
