### ISSUE TITLE
Docker CLI - docker tag --force is no longer an option

### ISSUE THREAD

**Issue by mnaughto** [flynn/flynn#3105]
Trying to run `flynn -a <app> docker push <image name>` results in the following log messages and error:

    flynn: getting image config with "docker inspect -f {{ json .Config }} <image name>"
    flynn: tagging Docker image with "docker tag --force <image name> docker.flynn.mydomain.com/<image name>:latest"
    unknown flag: --force
    See 'docker tag --help'.
    exit status 1

The `force` flag was deprecated in the CLI version I was using, and I just upgraded to the new Docker for Mac, which removes the `force` flag. I think the fix is just to remove that argument [here](https://github.com/flynn/flynn/blob/master/cli/docker.go#L207), but it's sort of preventing us from doing a whole lot with docker now.

**Comment by brettneese** [comment]
I submitted a PR for this here: https://github.com/flynn/flynn/pull/3106, but not sure if there are any side-effects (I don't have a Go environment set up, so I just deleted it using the GitHub web UI).

**Comment by diclophis** [comment]
This is currently blocking an effort to deploy a docker-registry into our flynn repo...

Does anyone have any suggestions on other peices of software we could deploy to flynn to get a docker registry going on our cluster?

**Comment by brettneese** [comment]
We used a Jenkins server, I can post more info about it and the deploy
script we're using when I'm not on my phone.

**Comment by lmars** [comment]
@diclophis the `docker-receive` app is actually a Docker registry, you can push and pull Docker images directly to / from it if you wish.

We should also fix the CLI (see #3106).

**Comment by diclophis** [comment]
@lmars how might i get the `docker/config.json` to talk to the `docker-receive` app?

**Comment by lmars** [comment]
@diclophis run `flynn docker login` to update your Docker config with the appropriate credentials (it is just a wrapper around `docker login`).

**Comment by diclophis** [comment]
great thanks @lmars
