### ISSUE TITLE
Buildpack Gradle / Node Crash with Exit Value 137

### ISSUE THREAD

**Issue by IsNull** [flynn/flynn#3107]
I have an issue where the build of a Gradle/Node project fails often, but not always on a single AWS node. (4 out of 5)  I have several gradle/node projects which are setup the same way and work without issue.

This build works locally and on Travis without issue. It also worked on another, older flynn node.

The only interesting part of the buidpack error: 
```
[2016-07-12T17:43:19.222867521Z]        Caused by: org.gradle.process.internal.ExecException: Process 'command '/tmp/build/warden-webapp/.gradle/nodejs/node-v6.2.0-linux-x64/bin/node'' finished with non-zero exit value 137
```

Exit value `137` probably means the process has been killed by another process with `SIGKILL`.

flynn host debug log:
https://gist.github.com/7449e3360564b167b835c07919409329

**Comment by titanous** [comment]
Try giving the build process more memory: `flynn limit set slugbuilder memory=4GB`

**Comment by IsNull** [comment]
Not sure this worked:

```
isnull$ flynn limit set slugbuilder memory=4GB
no apps in git remotes
```

I installed the app using the web ui.

**Comment by titanous** [comment]
Ah, add a `-a` flag to the command with the name of the app: `flynn -a APPNAME limit set slugbuilder memory=4GB`

**Comment by IsNull** [comment]
Ok thanks this seems to work, I will try to rebuild now.

So the build gets out of memory and is killed as a consequence?

Any chance to set the slugbuilder memory globally (assuming this will fix it)? Also, would it make sense to set the available memory for the builder according to the physically available memory automatically?

**Comment by titanous** [comment]
> So the build gets out of memory and is killed as a consequence?

Yes.

> Any chance to set the slugbuilder memory globally (assuming this will fix it)?

Not currently, it's a per-app setting.

> Also, would it make sense to set the available memory for the builder according to the physically available memory automatically?

Yes, please open an issue about this.
