### ISSUE TITLE
slugbuilder memory handling enhancement

### ISSUE THREAD

**Issue by IsNull** [flynn/flynn#3108]
If the slugbuilder runs out of memory the build will crash. I have observed in #3107 that the process exiting with 137, which is the only indication in the build log so far.

Some ideas to enhance this behaviour:
- [ ] Improve the log so that out-of-memory exception is obvious
- [x] Make it possible to set the available memory for the slugbuilder globally (make the default editable)
- [ ] Probably set the default available memory to a reasonable amount (percentage?) depending on the available system memory.

Maybe there are even better ways to handle this. But a reasonable default value depending on the available memory seems like the best UX.

**Comment by IsNull** [comment]
@titanous Any chance that you could support manually setting a global default for the slug-builder memory, similar to`flynn limit set slugbuilder memory=3GB`, but as a global default?

All the other enhancements in this issue are 'nice to have', but this one is quite severe. Because the Dashboard can not be used to deploy an app which requires more memory. Since the initial deploy (build) will fail and the memory can only be set afterwards.

Or is there any workaround how I can specify the default slug-builder size by editing some properties on flynn-host?

**Comment by titanous** [comment]
> Any chance that you could support manually setting a global default for the slug-builder memory, similar to `flynn limit set slugbuilder memory=3GB`, but as a global default?

Yes, this is something that could be supported by adding env vars to the dashboard and gitreceive apps.

> Or is there any workaround how I can specify the default slug-builder size by editing some properties on flynn-host?

There are no workarounds that I'm aware of.

**Comment by titanous** [comment]
Support for a global default is implemented in #3258.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
