### ISSUE TITLE
Add support for DigitalOcean block storage

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3115]
The installer should use block storage for the ZFS pool: https://www.digitalocean.com/community/tutorials/how-to-use-block-storage-on-digitalocean

**Comment by ron137** [comment]
Please add this feature 👍

**Comment by schu34** [comment]
Any updates on this? would be super helpful for my setup

**Comment by titanous** [comment]
The installer doesn't exist anymore, so you'd implement this in your own automation.
