### ISSUE TITLE
host: Add info endpoint to determine compatibility

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3118]
There are a few places where we do explicit version checks to determine whether to take certain actions (e.g. [whether to update postgres](https://github.com/flynn/flynn/blob/master/host/cli/update.go#L44-L47), or [whether to install libvirt](https://github.com/flynn/flynn/blob/master/script/install-flynn.tmpl#L169-L185)).

We should instead have something like `flynn-host info` which can be used to make more explicit comparisons (e.g. does the host expect postgres 9.4 / 9.5, or does the host use libvirt / libcontainer).

This will also prevent the need to keep bumping the arbitrary version string in `TestReleaseImages`.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
