### ISSUE TITLE
env set timed out after about 20mins

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3124]
Flynn v20160711.0

So I just tried to set an env variable ie `flynn env set` but after about 20 mins I got 

```
timed out waiting for job events: map[run_workers:map[up:2] web:map[up:3] checkout_expire:map[up:1]]
```

Not had this issue before so not sure why it's not working now, but seems live it's the web process that's timing out.

**Comment by josephglanville** [comment]
Can you post the debug info collected with `flynn-host collect-debug-info`.

**Comment by dottodot** [comment]
Unfortunately `flynn-host collect-debug-info` gives the error 

```host.go:153: unexpected HTTP status: 405```

**Comment by lmars** [comment]
@dottodot the 405 status is because your logs are too big for a gist, pass the `--tarball` flag to create a tarball of the logs and email it to us logs@flynn.io.

**Comment by dottodot** [comment]
OK I've sent you the logs

**Comment by dottodot** [comment]
Same thing is happening when pushing an update so something is really broken. 

In fact I've been having constant issues since updating to the latest stable or using nightly builds to a point where I'm having to build a new cluster every 3 days just so I can push updates. I was finding the previous stable pretty good so there's feels like something has been introduced that's causing these problems.

**Comment by titanous** [comment]
This sounds like it's the same root problem as #3129 and #3125. I'm looking into it.
