### ISSUE TITLE
cli: Interactive release update

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3132]
I would like to able to do an interactive update of a release on the command line which would fetch the current release, open the JSON representation using `$EDITOR`, then on save / exit would update the release with my changes.

This workflow will probably be less of a requirement once we have a Flynnfile (#1084).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
