### ISSUE TITLE
Flynn-host service prevents boot

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3134]
I am running tests on the latest nightly `v20160714.0`. I am unable to get it to boot after running install-flynn. Here are some descriptions of the environment I am running Flynn in and the steps I have taken.

I am running the hosts in Redhat Enterprise Virtualization. Here is the software that RHEV reports for the VM hosts:
OS Version: RHEV Hypervisor - 7.2 - 20160413.0.el7ev
Kernel Version: 3.10.0 - 327.13.1.el7.x86_64
KVM Version: 2.3.0 - 31.el7_2.10
LIBVIRT Version: libvirt-1.2.17-13.el7_2.4
VDSM Version: vdsm-4.17.26-0.el7ev

The Flynn host install is directly from the latest Ubuntu 14.04.4 server ISO. 

The disks for the VMs are located on iSCSI storage pools managed by the RHEV cluster. I have created the VMs with 2 disks, one for the OS install and one that I create a zpool on directly using `sudo zpool create -f flynn-default /dev/vdb`. 

After creating the zpool I am able to reboot the hosts repeatedly with no issue. I then run `sudo bash ./install-flynn --channel nightly`. When I reboot the host after successful completion of the `install-flynn` script I the host locks on boot at this stage: ![flynn-boot-fail](https://cloud.githubusercontent.com/assets/20210084/16877413/87b893c8-4a6d-11e6-86bb-249474664b99.png)

I booted the host into recovery using the ISO and disabled the flynn-host service. I was then able to successfully boot. After it booted I ran `service flynn-host start` and it brought up the `flynn-host` daemon.

**Comment by lmars** [comment]
@bbaptist I highly suspect the cgroups change in bea0afb is the issue, I am investigating.

**Comment by lmars** [comment]
@bbaptist please give the change I made in #3139 a try and see if it fixes the issue for you.

**Comment by bbaptist** [comment]
I changed the Upstart config to what is in #3139 and I am able to successfully reboot.
