### ISSUE TITLE
Error writing CA certificate:

### ISSUE THREAD

**Issue by blakebarber** [flynn/flynn#3136]
When running `flynn cluster add -p <pin-here> default flynn.mydomain.com <other-number/string>` on my dev machine after installing on my 3 node setup I get the following error:

```
Error writing CA certificate: Get https://controller.flynn.blakesdev.co/ca-cert: dial tcp: lookup controller.flynn.blakesdev.co on 24.35.128.34:53: no such host
```

That IP address isn't one of mine. I can't access the dashboard either (http://dashboard.flynn.mydomain.com). These are 3 servers that I just launched and installed flynn on. Any help would be appreciated. I thought this was close to issue #1868 but I can't figure it out.

**Comment by titanous** [comment]
That IP address is your local DNS resolver (note the port 53 after the IP). The problem is that you don't have a wildcard record setup in the DNS zone, you should have `*.flynn.blakesdev.co` pointing at the Flynn servers.

**Comment by blakebarber** [comment]
Thanks for the fast response. I'm pretty sure I have it set up correctly. But let me know if it is wrong.
![screen shot 2016-07-15 at 11 02 18 pm](https://cloud.githubusercontent.com/assets/1070185/16892667/4f7634d4-4ae0-11e6-91d8-c5a3945c8401.png)

**Comment by titanous** [comment]
Try `*.flynn`

**Comment by blakebarber** [comment]
That isn't working either. Would I need to reinstall now that I've added that record?

**Comment by titanous** [comment]
No, you don't need to reinstall, you just need to correctly configure the wildcard DNS record.

**Comment by titanous** [comment]
Note that DNS is heavily cached, including NXDOMAIN responses, so you may need to clear caches or wait for them to expire.

**Comment by superhero1** [comment]
For anyone experiencing that issue on Windows try:
`ipconfig /flushdns`

inside a command window.

**Comment by najmsheikh** [comment]
Were you able to fix this? I'm facing the same issue
