### ISSUE TITLE
proposal: Add "edge" channel

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3137]
I wonder if we should add an `edge` channel which tracks master, regardless of whether it passes CI so people can try out fixes as soon as they are merged (see https://github.com/flynn/flynn/pull/3133#issuecomment-233122188)?

/cc @titanous @josephglanville @jvatic WDYT?

**Comment by titanous** [comment]
I think we should do this, but we should focus on stabilizing CI first, as this is a minor improvement and having CI green is a major one.

**Comment by josephglanville** [comment]
I concur. Good idea but shouldn't be a crutch for CI not being stable.

**Comment by jvatic** [comment]
SGTM

**Comment by lmars** [comment]
We now release master regardless of whether it passes CI, closing.
