### ISSUE TITLE
Fixing a broken initial push does not scale back up

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3144]
When deploying broken code as an initial release, the app is scaled back down (as expected):

```
-----> Creating release...
=====> Scaling initial release to web=1
-----> Waiting for initial web job to start...
-----> WARN: scaling initial release down to web=0 due to error
remote: ERROR: Initial web job failed to start
```

Subsequent deploys the do not try to scale the app back up:

```
-----> Creating release...
=====> Application deployed
```

**Comment by BeOleg** [comment]
Same here, @lmars where you able to solve?

**Comment by titanous** [comment]
@BeOleg `flynn scale web=1` should do it after deploying a working version of the code.

**Comment by BeOleg** [comment]
cool, will try, I think the problem is that my python app is detected as node despite `package.json` being in `.slugignore`

**Comment by BeOleg** [comment]
A question not for this forum:
do you guys plan to support postgis or maybe docker-hub powered database backends any time soon? how about new relic support?

**Comment by titanous** [comment]
Ah, this should do the trick.

```text
flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-python
```

> do you guys plan to support postgis or maybe docker-hub powered database backends any time soon?

We already support PostgreSQL with PostGIS, along with MongoDB, MySQL, and Redis.

> how about new relic support?

What would that look like? As far as I know there is host and app level agents for NR, both should work fine already.

**Comment by BeOleg** [comment]
And last and not least, as far as I undestand the scaling of flynn is vertical, more instances running all the same containers.
how about vertical scaling where every container gets his own instance, something like this.

**Comment by titanous** [comment]
I'm not sure what you're asking. The best place to ask a clearer version of this question would be on StackOverflow with the `flynn` tag.

**Comment by BeOleg** [comment]
I am currently migrating from `wercker` to your platfrom.
I have though about the supported version of your product or the hosted one.
However I do want to learn how to do some devops on my own, and that would kind of destroy that opportunity.
Where could I find some reading materials about securing your solution... setting up a frontend proxy, encapsulating the business logic nodes in a private network and so forth, is that doable?

**Comment by BeOleg** [comment]
the afforementioned command give the bloew output
```bash
(nexchange) Olegs-MBP:nexchange beoleg$ flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-python
no apps in git remotes
```

**Comment by BeOleg** [comment]
Thanks for the meteor quick answers and the attention BTW, it is really as written on the site.
I will clean all the garbage content once my problem is resolved and leave only the info other users can use...

**Comment by titanous** [comment]
> I have though about the supported version of your product or the hosted one.  However I do want to learn how to do some devops on my own, and that would kind of destroy that opportunity.

With the support option you could set it up yourself and we'd make sure that everything is configured properly, and provide you with help and guidance wherever necessary. Email me at jonathan@flynn.io if you'd like to discuss further.

> Where could I find some reading materials about securing your solution... setting up a frontend proxy, encapsulating the business logic nodes in a private network and so forth, is that doable?

I don't think we have anything written about that currently. Feel free to ask questions on StackOverflow with the `flynn` tag if you have specific things you'd like to do and we can talk through it there.

> no apps in git remotes

Did you use `flynn docker push`? If so you'll need to specify the app name for each command:

```text
flynn -a APPNAME env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-python
```

If you used `git push`, then the command will figure out the app/cluster details if you are in the git repo with a Flynn remote configured.

**Comment by BeOleg** [comment]
I have emailed you.
I have used `git push` indeed.
I can push the docker image and try again.
However both should work fine.

Right now .slugignore is being ignored and the `flynn env` command does not work.
Thanks again.

**Comment by titanous** [comment]
> I have used git push

In that case run the `flynn env` command from the git repo. (specifying the app name will also work though)

**Comment by BeOleg** [comment]
if only wercker would respond to issues as fast as your guys do...
well...
https://github.com/wercker/support/issues/266

**Comment by BeOleg** [comment]
Yeah it's about 1 AM Friday night in my timezone, I missed the `APPNAME` placeholder, sorry
