### ISSUE TITLE
Blob storage - self hosted (minio.io)

### ISSUE THREAD

**Issue by IsNull** [flynn/flynn#3145]
In my search for self hosted network blob storage I found [minio.io](https://www.minio.io), which basically is an open source S3 alternative. It is even compatible with the S3 API. Since I am not sure if you are aware of this project, I thought I share it here.

I wonder if this could be useful for Flynn? It would allow you to basically "require" a blob-storage, since you would be able to either self host it within Flynn or just require it to be setup on the SAN.
It could therefore solve some issues regarding Postgres which is currently used for blob storage.

What are your thoughts on this?

**Comment by titanous** [comment]
As far as I can see, minio isn't highly available/multi-node, is that correct?

**Comment by IsNull** [comment]
>Microstorage architecture achieves exascale by provisioning a large number of smaller instances. Any failure is contained within a single instance.

They have apparently put quite some thought into the scaling issue: https://blog.minio.io/microstorage-for-microservices-70231db026a8#.7fodrpciy

I have to however admit that I do not fully understand this concept and how data is being synchronised, if at all. I do some more reading on this, its quite interesting. The one thing the containers do not solve well is persistent storage, and so it is to no surprise that this topic is raising big questions in a lot of places.

I will investigate further.

**Comment by IsNull** [comment]
I did some more research and this is what I come up with so far:

* There are two mini versions planed, minio y and a paid minio XL version with some advanced availability features, but since it will be paid I stopped there
* It is possible to mirror one minio server to another one using `mc mirror`. A user sugested this in a cron job. (Can you call this eventual consistency? :) )

I am not sure if it is possible to have multiple minio server instances reading/writing to the same FS volumes in case the web server becomes the bottleneck. The data itself should be protected by the SAN (raid etc).

Well since I found out that there will be a paid version of minio my enthusiasm died quite a bit. Projects following this business model will, at some point when the investors knock on the door, try to move as many users as possible to the paying side. Meaning that most features will be in the paid version.

**Comment by bbaptist** [comment]
There is also SX that is similar. [SX Cluster](http://www.skylable.com/products/sx/)

Also has the commercial aspect but the main cluster solution is GPL.

**Comment by IsNull** [comment]
GlusterFS and ceph are other fully open source alternatives which support (actually require) clustering, but these seem not very lightweight.

**Comment by titanous** [comment]
Yeah, we've evaluated Gluster and Ceph in the past, but they were both unfit for integration for a variety of reasons. Riak CS is the only thing I'm aware of that is properly designed.

**Comment by titanous** [comment]
Given that minio doesn't look like a good fit, I'm going to close this issue.

**Comment by alixaxel** [comment]
@titanous @IsNull Sorry for resurrecting an old issue, but as far as I can tell, Minio does provide an HA setup option as part of their OSS - see https://docs.minio.io/docs/distributed-minio-quickstart-guide.

I even found a Terraform + Ansible playbook to spin up a Minio cluster: https://github.com/bryanl/ha-minio

Would be great to see this implemented as a Flynn appliance.
