### ISSUE TITLE
pg commands not working

### ISSUE THREAD

**Issue by me** [flynn/flynn#3146]
Tried with two different clusters from scratch, first with installer, then manual. When I run any pg command, e.g. 

```
$ flynn pg psql
```
I just get
```
Usage: /bin/start-flynn-postgres {postgres|api}
```

**Comment by titanous** [comment]
Looks like there was a regression in the CLI, what platform are you on? I can link you to an older binary to use while we fix this.

**Comment by titanous** [comment]
`flynn update` should get you a fixed version (`v20160718.0`).

**Comment by me** [comment]
Thans @titanous, that worked!

**Comment by titanous** [comment]
Thanks for reporting this!
