### ISSUE TITLE
Allow host tag deletion to specify tag with value

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3150]
Using nightly `v20160718.0`

I am not able to delete a host tag using the `flynn-host tags del` command.

<pre>ubuntu@ie-flynn-16071300:~$ sudo flynn-host tags
HOST             TAGS
ieflynn16071302  
ieflynn16071301  
ieflynn16071300  db=true
ubuntu@ie-flynn-16071300:~$ sudo flynn-host tags del ieflynn16071300 db=true
ubuntu@ie-flynn-16071300:~$ sudo flynn-host tags
HOST             TAGS
ieflynn16071302  
ieflynn16071301  
ieflynn16071300  db=true
</pre>

**Comment by lmars** [comment]
@bbaptist the command to delete should be:

```
$ flynn-host tags del ieflynn16071300 db
```

**Comment by bbaptist** [comment]
Dang, I re-read that help command 10 times.

Thanks.

**Comment by titanous** [comment]
Probably worth making the variant you used work too.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
