### ISSUE TITLE
flynn-host: "Error: Status 403 trying to pull repository flynn/flannel"

### ISSUE THREAD

**Issue by kenaniah** [flynn/flynn#3151]
When attempting to add a new host to the cluster, I initialized flynn via `flynn-host init --discovery ...` and then ran into 403 Forbidden errors while attempting to download flynn components.

`flynn-host collect-debug-info` here:
https://gist.github.com/anonymous/06e3e3f2d7054d024a5a451930b0b049#file-flynn-host-log-L60

**Comment by titanous** [comment]
What steps did you take to install the same version of Flynn on the new host?
