### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3154]
Recently all of my Flynn apps are returning `executable file not found in $PATH` when I try to `flynn run [cmd]` where command is a command line app exposed by a node app (knexjs). This is affecting both apps that I've pushed to recently and those that I haven't.

I've echoed the PATH by running `flynn run sh` then `echo $PATH` which yielded: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

To my knowledge nothing has changed about my Flynn cluster or apps, and this is affecting apps that I'm sure haven't received updates to the node modules in question.

Any direction on troubleshooting would be greatly appreciated!

**Comment by lmars** [comment]
The jobs are not getting the required Entrypoint of `/runner/init`. In the short term, you can set it explicitly with:

```
$ flynn run -e /runner/init <cmd>
```

I am working on a patch.
