### ISSUE TITLE
Can't run electron on Flynn - /dev/shm: No such file or directory

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3170]
I can't get electron to un on Flynn, when I try to I get the error in the following gist:

https://gist.github.com/kevinob11/4b8d1737d0b926e92ab83c4968d2741d#file-error-txt-L1

To repro the error I created https://github.com/praece/flynn-electron-nightmare-test, which includes nightmarejs, electron-prebuilt and xvfb. After creating the release I test by getting shell access using `flynn run sh` then entering the following commands:
```
$ Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
$ export DISPLAY=:9.0
$ ELECTRON_ENABLE_LOGGING=true node_modules/electron-prebuilt/dist/electron
```

**Comment by titanous** [comment]
This appears to work fine when run in today's stable release that uses libcontainer instead of libvirt-lxc.

**Comment by kevinob11** [comment]
Great, we're going to spin a new cluster, migrate and test asap!

**Comment by kevinob11** [comment]
Fixed! Thanks!
