### ISSUE TITLE
docker-receive: Fresh install log filled with auth warnings

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3171]
I have a clean install of Flynn `v20160722.0`, the docker-receive logs are filled with the following warning.

```
time="2016-07-22T18:53:54Z" level=warning msg="error authorizing context: basic authentication failed" http.request.host="100.100.36.8:80" http.request.id=94e630fd-a960-44c5-a1f1-0da9512b6b8d http.request.method=GET http.request.remoteaddr="100.100.36.8:34064" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=947939f7-695b-4187-8dc0-fa6f8448176d version=v20160722.0
```

**Comment by titanous** [comment]
@lmars Looks like the registry is making requests to itself? The source and destination IPs are the same.

**Comment by lmars** [comment]
This is the result of the [service healthcheck](https://github.com/flynn/flynn/blob/master/bootstrap/manifest_template.json#L547-L551).

Some options:

* Just ignore the log messages
* Use the appropriate basic auth creds for the health check
* Don't log the basic auth failure (maybe just from containerinit based on the User-Agent header)

**Comment by titanous** [comment]
Can we just add an unauthenticated endpoint to ping?

**Comment by bbaptist** [comment]
I performed a backup of my `v20160722.0` cluster and then a restore to `v20160726.0`. This error is still filling the logs, is there a command you would run to fix this?

`2016-07-26T20:41:29.394220Z app[app.ieflynn16071300-6401b078-07ce-4364-9417-edb9e2f854ff]: time="2016-07-26T20:41:29Z" level=warning msg="error authorizing context: basic authentication failed" http.request.host="100.100.63.14:80" http.request.id=3828a388-7270-4692-93ac-cf74aa760da8 http.request.method=GET http.request.remoteaddr="100.100.63.14:60940" http.request.uri="/v2/" http.request.useragent="Go-http-client/1.1" instance.id=4faf095b-5a95-4dce-88fb-e69e845de377 version=v20160726.0`

**Comment by lmars** [comment]
@bbaptist your `docker-receive` release is still using `/v2` for the healthcheck, you can update the release by creating `updates.json` containing:

```
{
  "processes": {
    "app": {
      "ports": [
        {
          "port": 80,
          "proto": "tcp",
          "service": {
            "name": "docker-receive",
            "create": true,
            "check": {"type": "http", "path": "/.well-known/status"}
          }
        }
      ]
    }
  }
}
```

then running `flynn -a docker-receive release update updates.json`.

**Comment by bbaptist** [comment]
Is this something that should have been still fixed when doing a new install and then restoring from backup?

**Comment by lmars** [comment]
@bbaptist most likely yes, but given that it is just some log spam I didn't feel it was necessary to try and back port to old releases.
