### ISSUE TITLE
slugbuilder cache directory does not persist between builds

### ISSUE THREAD

**Issue by kenaniah** [flynn/flynn#3178]
The slugbuilder does not persist the `/tmp/cache` directory in between builds on a cluster running  `v20160722.1` using s3 for the blobstore (not yet sure if s3 is relevant). Buildpacks used:
 * https://github.com/heroku/heroku-buildpack-nodejs
 * https://github.com/heroku/heroku-buildpack-ruby

**Comment by titanous** [comment]
I'm unable to reproduce this, in my testing the buildpack cache works fine. Can you please provide the steps you used to test this?

**Comment by titanous** [comment]
Closing due to a lack of information, please let us know if you can provide information on how to reproduce the error.
