### ISSUE TITLE
REDIS_IMAGE_URI isn't rewritten on backup restore

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3180]
It seems like we should use an artifact ID for this and the other similar env vars, not the image URL.

**Comment by lmars** [comment]
I have moved to using artifact IDs in #3100, I'll also make sure the Redis image is handled during backup / restore.

**Comment by lmars** [comment]
This will also need to check `REDIS_IMAGE_ID` once #3233 is merged.
