### ISSUE TITLE
dashboard: Show git History of a Release

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3182]
Hi,

just a quick thought, feel free to close it if it doesn't make that much sense. :)

As releases are currently created via git push, would it be possible to show the commits of a release since the last one? Much like in Jenkins, where you can see the single commits of a build which happened in the repository since the last build.

This would provide some kind of automated changelog per release.

**Comment by lmars** [comment]
We could probably store the current and previous commit in the release metadata (e.g. [here](https://github.com/flynn/flynn/blob/master/gitreceive/server.go#L310)), then you could run a diff against a checked out version of you repo (e.g. run a job with the app's git cache attached).
