### ISSUE TITLE
feature request: allow specification of Availability Zone in AWS installer

### ISSUE THREAD

**Issue by swaits** [flynn/flynn#3190]
Because Reserved Instances are tied to a specific AZ, it'd be nice to be able to use the Flynn Installer to spin up installations in specific AZs.

Proposed functionality..

On the installer UI, next to or below the Region selection, add another selection with region-specific AZs.

This second selector may default to "Any".

Its options should include the AZs relative to the currently selected Region. So, if a user chooses US East, the AZs should be:
- Any
- us-east-1a
- us-east-1b
- us-east-1c
- us-east-1d
- us-east-1e

(I'm not sure if you can pull the available AZs dynamically from the AWS API, but I'm guessing "yes, you can")

**Comment by titanous** [comment]
AWS AZs are different for each account, so we definitely need to pull them from the API.

**Comment by mrrooijen** [comment]
In addition to that, how about an option to evenly distribute the nodes across all of the available AZs for improved HA?

**Comment by kvitajakub** [comment]
I just found this, +1 for distributing the nodes of cluster across multiple AZs or regions in Azure.
For me its the only reason I need to do manual setup of the instances and network.
