### ISSUE TITLE
Is there any doc about how to gracefully shutdown flynn ?

### ISSUE THREAD

**Issue by wenerme** [flynn/flynn#3191]
I follow the instruction got a flynn cluster running, how can I shutdown ?

**Comment by lmars** [comment]
@wenerme you can stop Flynn by running `sudo stop flynn-host`, or you can remove it completely by running the install script with `--remove`:

```
$ curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn
$ sudo bash /tmp/install-flynn --remove
```
