### ISSUE TITLE
docs: Uninstall Flynn

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3192]
Hi,
there might be situations where I want to uninstall Flynn completly without anything left over. Like removing a single machine from a cluster and giving it a new task. Is there a way to do this?

**Comment by lmars** [comment]
You can remove Flynn completely by running the install script with `--remove`:

```
$ curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn
$ sudo bash /tmp/install-flynn --remove
```

**Comment by philiplb** [comment]
Alright, thank you. :)

**Comment by jaimeiniesta** [comment]
How can I uninstall the flynn client from my mac? This script says `ERROR: this script is only compatible with Ubuntu 14.04 LTS, Trusty Tahr`

**Comment by lmars** [comment]
@jaimeiniesta the install script is for nodes in a cluster, you can uninstall the Flynn CLI by just deleting it:

```
$ rm $(which flynn)
```

You may also want to remove `~/.flynnrc` and `~/.flynn`, that will remove access to any clusters you have configured though.
