### ISSUE TITLE
Docker x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by SystemZ** [flynn/flynn#3193]
Hello, I was trying to push docker image to flynn cluster but it looks like there is a problem with certificate.

Following docs https://flynn.io/docs/docker I used `flynn docker set-push-url` and `flynn docker login`, these commands run without output.

I think that I need to add custom certificate to Docker, same as I added it in browser.

CLI version:
```
v20160727.0
```

```plain
flynn -a hugi docker push cantino/huginn-single-process
flynn: getting image config with "docker inspect -f {{ json .Config }} cantino/huginn-single-process"
flynn: tagging Docker image with "docker tag cantino/huginn-single-process docker.someclusterid.flynnhub.com/hugi:latest"
flynn: pushing Docker image with "docker push docker.someclusterid.flynnhub.com/hugi:latest"
The push refers to a repository [docker.someclusterid.flynnhub.com/hugi]
unable to ping registry endpoint https://docker.someclusterid.flynnhub.com/v0/
v2 ping attempt failed with error: Get https://docker.someclusterid.flynnhub.com/v2/: x509: certificate signed by unknown authority
 v1 ping attempt failed with error: Get https://docker.someclusterid.flynnhub.com/v1/_ping: x509: certificate signed by unknown authority
exit status 1
```

**Comment by lmars** [comment]
@SystemZ the `flynn docker login` command is supposed to detect the TLS failure and print a warning (i.e. [this one](https://github.com/flynn/flynn/blob/master/cli/docker.go#L154-L167)), I'm not sure why it did not do that, did it exit with a zero exit status?

**Comment by lmars** [comment]
@SystemZ can you check if there is an associated entry in `~/.docker/config.json`?

**Comment by SystemZ** [comment]
```bash
flynn docker login && echo "OK" || echo "NOT OK"
```
```
OK
```
Looks like exit with 0

I have `~/.docker/` dir but no `config.json` file.
Maybe it's fault in my OS? It's Ubuntu 16.04 Desktop.

**Comment by lmars** [comment]
@SystemZ try `docker login docker.someclusterid.flynnhub.com` with username `flynn` and password being the output of `flynn -a docker-receive env get AUTH_KEY`.

**Comment by SystemZ** [comment]
@lmars 

```bash
docker login docker.someclusterid.flynnhub.com
```

```plain
Username: flynn
Password: 
Email: test
Error response from daemon: invalid registry endpoint https://docker.someclusterid.flynnhub.com/v0/: unable to ping registry endpoint https://docker.someclusterid.flynnhub.com/v0/
v2 ping attempt failed with error: Get https://docker.someclusterid.flynnhub.com/v2/: x509: certificate signed by unknown authority
 v1 ping attempt failed with error: Get https://docker.someclusterid.flynnhub.com/v1/_ping: x509: certificate signed by unknown authority. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry docker.someclusterid.flynnhub.com` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/docker.someclusterid.flynnhub.com/ca.crt
```

Same error, should I use `--insecure-registry` flag or just place `ca.crt` manually?

**Comment by lmars** [comment]
Ah ok I have found the reason why this isn't working as expected (I will push a fix shortly).

You need to copy the Flynn CA certificate from `$HOME/.flynn/ca-certs/default.pem` to `/etc/docker/certs.d/docker.someclusterid.flynnhub.com/ca.crt` on the docker daemon's host and restart docker.

Once you have done that, you should be able to run `flynn docker push`.

**Comment by SystemZ** [comment]
This fixed issue for me:
```bash
sudo mkdir -p /etc/docker/certs.d/docker.someclusterid.flynnhub.com/
sudo cp /home/user/.flynn/ca-certs/flynn-sometimestamp.pem /etc/docker/certs.d/docker.someclusterid.flynnhub.com/ca.crt
flynn docker login
```

Thanks @lmars for fast reaction :)
