### ISSUE TITLE
Allow moving controller/dashboard/git to different ports

### ISSUE THREAD

**Issue by tzusman** [flynn/flynn#3196]
Moving these services to a different port would enable administrators to restrict traffic to these services down to their office IPs, or be able to dynamically grant access for a short duration to remote workers.

This approach would enable the use of a public monitoring service to ensure that those ports (and thus services) aren't globally accessible.

**Comment by titanous** [comment]
More broadly: The router should have the ability to create arbitrary pairs of HTTP/HTTPS listeners should be assignable to those listeners. This would allow an IPv6-only service for example or any number of other options.

**Comment by titanous** [comment]
#2633 is a prerequisite.

**Comment by titanous** [comment]
This is supported as of #4000.
