### ISSUE TITLE
Restoring from backup pre-mongo doesn't create mongodb provider

### ISSUE THREAD

**Issue by jvatic** [flynn/flynn#3198]
Restoring from a backup pre-dating the mongodb appliance causes it not to be there. This in turn breaks database related views in the dashboard.

Thank you @swaits for reporting this.

**Comment by jvatic** [comment]
A quick workaround for this issue, assuming you don't need mongodb, is to create a placeholder provider and app:

`flynn provider add mongodb http://example.com`
`flynn create mongodb --remote=""`

**Comment by philiplb** [comment]
Hi,
this is also the case here with a backup of a cluster not having started the mongodb appliance on v20160814.

**Comment by titanous** [comment]
@philiplb You did a clean install of v20160814 and then restored it and the mongodb provider wasn't there?

**Comment by philiplb** [comment]
I did a clean install of v20160814 and imported a backup being created a few hours before with the version v20160721.2.
None of the deployed applications use a mongodb appliance and so the mongodb provider was never running.

**Comment by titanous** [comment]
Was the v20160721.2 cluster previously restored from a backup? My understanding of this issue is that the root cause is that the mongodb app/provider are missing from the database as we don't currently create them when restoring a backup. This should only affect databases that date back to clusters that predate the appliance.

**Comment by philiplb** [comment]
Yes, this cluster was always upgraded via backup restore on the stable channel. The initial version was v20160327.

**Comment by titanous** [comment]
Alternatively you should be able to add the missing MongoDB appliance with:

```text
CONTROLLER_KEY=$(flynn -a controller env get AUTH_KEY) flynn-host bootstrap --steps controller-key,mongodb-password,mongodb
```

Set `SINGLETON=false` if you have a multi-node cluster.

**Comment by philiplb** [comment]
Hi @titanous 
this workaround worked for us. At least, the providers page on the dashboard is available again. But the bootstrap command ended with an error, not sure if this is interesting:

```bash
foo@bar:~$ export CONTROLLER_KEY=...
foo@bar:~$ flynn-host bootstrap --steps controller-key,mongodb-password,mongodb,add-mongodb-provider
```

> 22:38:03.118423 check online-hosts
> 22:38:03.119412 gen-random controller-key
> 22:38:03.119519 gen-random controller-key ...
> 22:38:03.119533 gen-random mongodb-password
> 22:38:03.119559 gen-random mongodb-password ...
> 22:38:03.119569 deploy-app mongodb
> 22:38:03.349040 add-provider add-mongodb-provider
> 22:38:13.385606 add-provider add-mongodb-provider error: unknown_error: Something went wrong

**Comment by titanous** [comment]
@philiplb did you use the other workaround previously?

**Comment by philiplb** [comment]
@titanous 
Yes, but I deleted the mongodb app again as I don't use any DB (yet) and I wanted the dashboard to be clean.

**Comment by titanous** [comment]
Ah, the error was probably because you didn't also delete the provider. You can delete it and run the steps `controller_key,add-mongodb-provider` again if you want it to work.

**Comment by philiplb** [comment]
@titanous  That did the trick, thank you. :)

**Comment by tingggg** [comment]
> 2017-08-18T09:51:12.413587Z app[mongodb.10131317-a3aa9d3b-0a0e-4c2e-a000-171b67bcde0d]: 2017-08-18T09:51:12.413+0000 I ACCESS   [conn178] SCRAM-SHA-1 authentication failed for flynn on admin from client 100.100.78.41 ; UserNotFound: Could not find user flynn@admin
2017-08-18T09:51:12.415781Z app[mongodb.10131317-a3aa9d3b-0a0e-4c2e-a000-171b67bcde0d]: t=2017-08-18T09:51:12+0000 lvl=dbug msg="ignoring error connecting to mongodb" app=mongodb fn=start id= port=27017 err="server returned error on SASL authentication step: Authentication failed."
2017-08-18T09:51:12.415929Z app[mongodb.10131317-a3aa9d3b-0a0e-4c2e-a000-171b67bcde0d]: 2017-08-18T09:51:12.413+0000 I NETWORK  [conn178] end connection 100.100.78.41:51508 (0 connections now open)
2017-08-18T09:51:13.154977Z app[mongodb.1013116150-75a18014-97b1-4300-9347-9d7c667e4f4b]: 2017-08-18T09:51:13.154+0000 I NETWORK  [initandlisten] connection accepted from 100.100.50.196:55652 #162 (1 connection now open)
