### ISSUE TITLE
DNS lookup error in installer on macOS

### ISSUE THREAD

**Issue by robgraeber** [flynn/flynn#3202]
Getting this error after I input my credientials and try to setup a cluster:

```
Error: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: lookup ec2.us-east-1.amazonaws.com on 192.168.1.1:53: read udp 192.168.1.124:53614->192.168.1.1:53: i/o timeout 
```

Any ideas?

**Comment by titanous** [comment]
What operating system are you using? Did you try again after that error?

What does this command return?

```text
dig @192.168.1.1 ec2.us-east-1.amazonaws.com
```

**Comment by robgraeber** [comment]
Using El Capitan, and yeah it consistently fails.

Here's the dig:
```
dig @192.168.1.1 ec2.us-east-1.amazonaws.com

; <<>> DiG 9.8.3-P1 <<>> @192.168.1.1 ec2.us-east-1.amazonaws.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64008
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ec2.us-east-1.amazonaws.com.	IN	A

;; ANSWER SECTION:
ec2.us-east-1.amazonaws.com. 380 IN	CNAME	ec2.amazonaws.com.
ec2.amazonaws.com.	34	IN	A	54.239.29.8

;; Query time: 22 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Jul 29 10:31:45 2016
;; MSG SIZE  rcvd: 79
```

**Comment by titanous** [comment]
Do you have any Search Domains or other unusual config options specified in the DNS section of network setttings?

**Comment by michaelyork** [comment]
I should add that I experienced the same things a few days back w/ the AWS option.

**Comment by robgraeber** [comment]
So I figured out it works when tethering from my phone, so I figure it's something with my router.

I'm using DD-WRT which is a custom router firmware that's pretty common. I tried toggling various options like the firewall but nothing worked. 

Here's my router settings for reference:
![screen shot 2016-07-29 at 9 46 17 pm](https://cloud.githubusercontent.com/assets/2387719/17268159/670c812e-55d6-11e6-9119-8e3838409510.png)

**Comment by josephglanville** [comment]
@robgraeber these settings wouldn't effect DNS. DNS for your network is being provided by the device at `192.168.1.253`. I would try investigate there. Also check if you have any settings configured in the advanced settings for your network device on your Mac. i.e: System Preferences -> Network -> Ethernet -> Advanced -> DNS.

This problem is usually caused by one of these layers having strange search domains.

**Comment by robgraeber** [comment]
these are my dns settings, should be the default:

![screen shot 2016-07-29 at 11 15 03 pm](https://cloud.githubusercontent.com/assets/2387719/17268566/7943c738-55e2-11e6-9b72-ab841fadad0c.png)

**Comment by titanous** [comment]
@robgraeber Can you get a packet capture of the DNS request that is failing? Wireshark should make it reasonably easy to do and you can limit it down to just the relevant packets.

**Comment by pinkencryption** [comment]
Is it because of elastic IP situation ?

**Comment by chad-upton** [comment]
It's because he has a local route to 192.168.1.0, the subnet in aws needs to be changed to something other than 192.168.1.x.  If you don't want to do that, just change your local router to something like 10.0.0.0/8.

**Comment by titanous** [comment]
@chad-upton I don't believe this has anything to do with the AWS configuration, as nothing has been set up on AWS. The error is while looking up the DNS entry for the EC2 API. I believe this is a bug in the netgo DNS resolver, but until I see a packet dump I won't be able to learn anything else.

**Comment by robgraeber** [comment]
I don't believe any dns requests are failing:
![screen shot 2016-08-02 at 1 42 23 am](https://cloud.githubusercontent.com/assets/2387719/17322475/74f91daa-5852-11e6-9b3b-9c1bc419da57.png)

Here's the packet dump: 
[packetdump.pcapng.zip](https://github.com/flynn/flynn/files/396170/packetdump.pcapng.zip)

**Comment by titanous** [comment]
For some reason the DNS server isn't responding to the DNS requests from the Flynn client. It looks like the router might run DNSMasq, is it possible for you to find out what version and whether there are any debug/error logs that can be retrieved?

You can confirm that it is a problem with the DNS server by changing your local DNS config to 8.8.8.8 / 8.8.4.4 and trying again.
