### ISSUE TITLE
Add browser security headers to dashboard

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3208]
We should add `Content-Security-Policy`, `X-Content-Type-Options`, `X-Frame-Options`, and `X-XSS-Protection` headers to the dashboard.

**Comment by onnimonni** [comment]
How about these:
* Automatically redirecting http->https?
* public key pinning HPKP -https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning
* HSTS - https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet

**Comment by titanous** [comment]
@onnimonni Yes, we will be doing those as a part of a broader security push (#3184) once we have Let's Encrypt support in place.
