### ISSUE TITLE
Storage disk format

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3209]
Just wondering, when I format a disk to be used for flynn I've previously been formatting as ext4. Should I be actually formatting it as zfs and is there any benefit in doing so?

**Comment by titanous** [comment]
The root filesystem should be ext4. The ZFS pool should be on separate disk(s): https://flynn.io/docs/production#custom-zfs-pool

**Comment by dottodot** [comment]
Yes that's what I mean. I have the option to format my separate disk however I want, but I've previously been formatting it as ext4 befor running `zpool create flynn-default /dev/sdb1` should i be formatting it as zfs?

**Comment by titanous** [comment]
You shouldn't need to format the zpool disk at all. The create command takes care of that.

**Comment by dottodot** [comment]
Ah ok, didn't realise that. Thanks.
