### ISSUE TITLE
Discoverd returns invalid DNS responses

### ISSUE THREAD

**Issue by ohhatiya** [flynn/flynn#3210]
In some cases discoverd is returning DNS responses >512 bytes over UDP even when EDNS has not been requested.

It seems like the issue may be caused by the behavior of miekg/dns described at https://github.com/miekg/dns/issues/216.

**Comment by titanous** [comment]
Are you seeing this for discoverd service entries, requests that trigger recursion, or both?

**Comment by ohhatiya** [comment]
Only noticed it for requests that trigger recursion.

**Comment by titanous** [comment]
Thanks, will fix.
