### ISSUE TITLE
Can't use http routes for docker containers

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3213]
**What I wanted to achieve**
To use a simlpe docker container as http app in demo flynn environment.

**Steps to reproduce:**
```bash
$ git clone https://github.com/tobilg/docker-mini-webserver
$ cd docker-mini-webserver/
$ flynn create --remote "" node-example
$ docker build -t node-example .
$ flynn -a node-example docker push node-example
$ flynn -a node-example scale app=1

# Then I tried the http route
$ curl node-example.demo.localflynn.com
Service Unavailable
```

**Some debugging information:**
```bash
# Debug routes
$ flynn -a node-example route
ROUTE                                  SERVICE           ID                                         STICKY  LEADER  PATH
http:node-example.demo.localflynn.com  node-example-web  http/08addd49-3ae5-4628-b31d-3c9476dd129c  false   false   /

# Then I deleted default route since it was mapped for node-example-web and I only had node-example-app

$ flynn -a node-example route remove http/08addd49-3ae5-4628-b31d-3c9476dd129c
$ flynn -a node-example route add http -s node-example-app node-example.demo.localflynn.com
$ flynn -a node-example route                                                                      master
ROUTE                                  SERVICE           ID                                         STICKY  LEADER  PATH
http:node-example.demo.localflynn.com  node-example-app  http/57730ecb-4d0f-4560-8f5f-04bfe54b0771  false   false   /

# And even still only errors
$ curl node-example.demo.localflynn.com
Service Unavailable
```

**System information**
```bash
$ flynn version
v20160801.0
$ flynn cluster
NAME             CONTROLLER URL                          GIT URL                          DOCKER URL
demo-virtualbox  https://controller.demo.localflynn.com  https://git.demo.localflynn.com  https://docker.demo.localflynn.com  (default)
$ uname -sp
Darwin i386
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31
```

**Comment by lmars** [comment]
@onnimonni you will need to modify the app to listen on the port specified in the `PORT` environment variable (i.e. [here](https://github.com/tobilg/docker-mini-webserver/blob/master/mini-webserver.js#L5)).

Some details as to why this is necessary: routing domains to jobs is done at the router level which uses registered services to find the right jobs, and for apps deployed via `flynn docker push` we set up a default service on [port 8080](https://github.com/flynn/flynn/blob/master/cli/docker.go#L241-L248) and put that port in the `PORT` environment variable, so for the app to receive HTTP traffic from the router there must be something listening on that port.

**Comment by onnimonni** [comment]
Thanks! I tried to find this in the docs but didn't find anything related to this.

So container needs to listen in fixed port `8080` in order to be routable?

**Comment by titanous** [comment]
@onnimonni Currently the port is static at 8080, but you should use the `PORT` env var as we may change the way the port number is allocated in the future.

**Comment by titanous** [comment]
@lmars Can you add a section to the Docker docs that explains this and links over to https://flynn.io/docs/apps#routes

**Comment by onnimonni** [comment]
Thanks for clarifying, now it's working :)!

Could you change the flynn docs to be hosted in github as well so for example in this case I could just create a PR into the docs?

**Comment by titanous** [comment]
They are hosted here! https://github.com/flynn/flynn/tree/master/docs/content

Feel free to send a PR.

**Comment by onnimonni** [comment]
Sorry I missed them, I was looking for something like `flynn/docs`.

**Comment by SalvoLunar** [comment]
Hello, 
I'm using a docker wordpress image, that works on port 80 and 443.
How can I map the static 8080 port to port 80?

Thanks,
Salvo
