### ISSUE TITLE
Flynn asks for credentials on git push if there is space in path to flynn.exe 

### ISSUE THREAD

**Issue by pinkencryption** [flynn/flynn#3214]
Hi,

The username on windows contained spaces. Thus the home directory was on spaces. Thus the .gitconfig additions contained spaces and the commands were being failed. 
Let's fix this and make sure when we design .gitconfig we take care of the spaces in directory paths anywhere.

**Comment by pinkencryption** [comment]
To replicate -- 
Install flynn on windows with a username containing spaces
Add cluster
Deploy app by git push
You will see git asking for username.

Fix it.

**Comment by jvatic** [comment]
A quick workaround until this is fixed is to add quotes around the username in the gitconfig (this is only necessary for the helper entry):

```
[credential "https://git.xxxx.flynnhub.com"]
helper = C:/Users/'name with a space'/AppData/Roaming/flynn/bin/flynn.exe git-credentials
```

**Comment by lukaspj** [comment]
I don't have space in my username but have this same issue.
The temporary work-around for me is to use the "escape" key to dismiss the dialog, which I discovered in this chat:
https://botbot.me/freenode/flynn/2016-09-23/?msg=73512637&page=1

Kindda annoying though. Could it be an issue with upper/lower-case? 

My helper path from git config : `helper=C:/Users/Lukas/AppData/Roaming/flynn/bin/flynn.exe git-credentials`

**Comment by scratchmex** [comment]
I can confirm the problem still exists here

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
