### ISSUE TITLE
Get Public Route in Environment Variable

### ISSUE THREAD

**Issue by IsNull** [flynn/flynn#3217]
I am currently deploying several apps to Flynn which all register themselves on a Eureka Service Discovery server (from [Spring Cloud Netflix](https://cloud.spring.io/spring-cloud-netflix/)), which also runs on Flynn. (I don't want to have Vendor lock-in so using Eureka is a nice way to run my system on different PaaS.)

All application instances use their internal IPs to register themselves at Eureka, which works quite well. I think using discoverd would be similar, but use the internal domain names instead.

I have now the situation that I want to send the user from app-A to app-B. The service discovery system gives me however the internal IPs which are useless as soon I am outside of Flynn. What I actually need is the applications route. I.e. I need _application_ discovery with public routes.

I have seen that on other PaaS such as CloudFoundry, each instance has its routes available in a environment variable `vcap.application.uris[0]`. So if the instance knows which route it has, I could somehow get this to work. 

But maybe I miss something and this problem can be solved simpler.

**Comment by lmars** [comment]
@IsNull you can lookup routes using the router API which is available within the cluster at `router-api.discoverd:5000`.

For example, from within a job in your app (e.g. `flynn run bash`), get the routes with:

```
curl "http://router-api.discoverd:5000/routes?parent_ref=controller/apps/$FLYNN_APP_ID"
```

which will return JSON like:

```
[
  {
    "type": "http",
    "id": "5e9cb70e-f045-49c2-9618-a829ffb13184",
    "parent_ref": "controller/apps/72134082-871e-47f0-965e-a9d137384212",
    "service": "nodejs-web",
    "leader": false,
    "created_at": "2016-08-03T12:23:19.209492Z",
    "updated_at": "2016-08-03T12:23:19.209492Z",
    "domain": "nodejs.1.localflynn.com",
    "path": "/"
  }
]
```

Does that help with what you are trying to achieve?

**Comment by IsNull** [comment]
While I am able to get the correct domain this way (tried it manually), it would be great to have my code not to depend on Flynn specifics. I.e. I have obviously separate configuration profiles for different environments/PaaS but it should not be something in the code base.

So a `APPLICATION_DOMAIN` or similar for the first application route would be nice.

Alternatively, exposing `$CLUSTER_DOMAIN` and `$APPLICATION_NAME` in the environment variables? With these, I could build the applicaiton route myself. 

The instances would then basically use this domain to register at Eureka, and as a consequence the load balancing would happen by the default Flynn route handler. (Since different instances all resolve to the same application domain)

**Comment by titanous** [comment]
We're currently discussing a new configuration system for apps that would be good for this, putting the routes in the environment is not idea because it requires restarting the application every time a route changes.

**Comment by titanous** [comment]
I'll update this issue when the issue describing the config system goes up.

**Comment by IsNull** [comment]
Thank you for the heads up - I'm looking forward to whatever you come up with.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
