### ISSUE TITLE
Feature Request: Allow using different docker container for multiple processes in one app.

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3228]
Hey!

I can use `Procfile` to define different processes when I use buildpacks but I didn't find anything like that for the docker containers in the docs.
Do you have something similiar in mind already in the roadmap?

It would be perfect to have something similiar as `docker-compose.yml` is.

**Comment by lmars** [comment]
@onnimonni we plan to support a `Flynnfile` (#1084) which will have more flexibility in defining process types for all apps (i.e. buildpack, docker push etc.), and it's on our upcoming roadmap so work will begin on it soon.

In the short term you can manually change the release configuration using `flynn release update` (see [here](https://flynn.io/docs/cli#release)).

**Comment by onnimonni** [comment]
thanks @lmars :)!

**Comment by onnimonni** [comment]
I think we misunderstood eachother.

I know I can start different processes to the same docker container. But can I add multiple different container images into 1 application?

Or should those be just new applications in the flynn model?

For example I would want to split nginx and php processes to different containers.

Here's my example containerized application configuration:
```
$ flynn -a php-test-server release show --json | to_json
{
    "artifact": "9af821af-1ac7-4711-8d09-f82d5733926e",
    "artifacts": [
        "9af821af-1ac7-4711-8d09-f82d5733926e"
    ],
    "created_at": "2016-08-04T07:03:27.675254Z",
    "env": {
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "PORT": "8080",
        "PROJECT_ROOT": "/var/www/project",
    },
    "id": "7e9d41ec-9db9-4886-807e-d70ef5b11dc5",
    "meta": {
        "docker-receive": "true"
    },
    "processes": {
        "app": {
            "args": [
                "/init"
            ],
            "ports": [
                {
                    "port": 8080,
                    "proto": "tcp",
                    "service": {
                        "create": true,
                        "name": "php-test-server-web"
                    }
                }
            ],
            "resources": {
                "cpu": {
                    "limit": 1000,
                    "request": 1000
                },
                "max_fd": {
                    "limit": 10000,
                    "request": 10000
                },
                "memory": {
                    "limit": 1073741824,
                    "request": 1073741824
                }
            }
        }
    }
}
```

**Comment by onnimonni** [comment]
It would be brilliant to be able to do something like this:
```
$ flynn -a myapp docker push web-image --process=web
$ flynn -a myapp docker push app-image --process=app
$ flynn -a myapp docker push service-image --process=service
```

I hope that `Flynnfile` can also support these kind of deployments.

**Comment by lmars** [comment]
@onnimonni ah ok, so no you can't push two separate Docker images to the same app, you will need to either split into two apps or bundle everything in the same Docker image (I would probably do the latter).

**Comment by onnimonni** [comment]
Thanks for making it clear!

Would it be possible in the future to start these as in some structured way? Or do you want all docker containers to act as independent applications? What about if application is depending on another application and they need to be started in some strict sequence?

Have you discussed anything related?

I don't mind if this is not in the prioritized roadmap but just to let you know I would be willing to put time and effort helping to make something like this happen.

It could be named eg. FlynnFleet. For starters this could only provide provide links to another applications as envs and start them in certain order.

Maybe I'll just hack a prototype with the flynn api.

**Comment by onnimonni** [comment]
Also if I split these into several applications it gets really hard for APP2 to get access into one of the appliances of APP1.

My use case would be to use nginx with redis appliance in APP1 and then allow WordPress to purge the redis cache of nginx in APP2 when something changes in the APP2. (Similiar setting as in this [easyengine nginx tutorial](https://easyengine.io/wordpress-nginx/tutorials/single-site/redis_cache-with-conditional-purging/))

I can pass the redis config in Headers with nginx to APP2 but that isn't really ideal.

If I use the same container image for all services then I need to update all of them everytime I do even a small change to some part.
The image also gets super big and for example if php has version update I will also need to reinstall nginx again creating unneccessary traffic with the container layers. Which could be cached really nicely and allowing faster deploys.

I can work my way through these minor annoyances but something in the flynn core would be brilliant :)!

**Comment by titanous** [comment]
Currently we plan to add support for deploying interdependent app stacks with Flynnfiles (#1084).

**Comment by onnimonni** [comment]
Excellent! I will follow that one closely. Thanks @titanous!
