### ISSUE TITLE
Question: Best practises for forwarding logs from flynn to external analyzer?

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3229]
Hey!

I'm willing to update the docs in return if you can share few pointers how log forwarding should be done from flynn cluster to eg. graylog or elk-stack.

I'm wondering this because for my typical application can output different kind of logs like:

* nginx error logs
* nginx access logs
* application logs
* application error logs
* container startup/debug logs
* ...

If I just combine them all to container stdout/stderr it'll be harder to use them later on.

**Comment by lmars** [comment]
We have plans to support forwarding logs from the built-in logging system to external servers (#1422).

For now you can use something like rsyslog to collect the on disk logs on each host in `/var/log/flynn` (there is a file per app, with each log line being an [RFC5424 syslog Message](https://tools.ietf.org/html/rfc5424#section-6)).

**Comment by onnimonni** [comment]
Sorry I didn't find #1422. My bad!
