### ISSUE TITLE
dashboard: "No resource selected" on the providers tab

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3244]
Hi,
suddenly, when I want to visit the providers tab (MySQL etc.), I just get the message "No resource selected". Firebug has shown this JS error:
![screen shot 2016-08-08 at 17 31 50](https://cloud.githubusercontent.com/assets/1672238/17485568/3f7798f0-5d8e-11e6-8799-321453fa5f32.png)

Maybe a missing env var somewhere?

**Comment by titanous** [comment]
Do you have a mongodb provider in your cluster? I wonder if this is #3198.

**Comment by philiplb** [comment]
No, mongodb is not used and also doesn't show up on the health page.

**Comment by titanous** [comment]
That might be the problem, can you try the suggested workaround in #3198?

**Comment by philiplb** [comment]
This workaround seems to work. Wheras I now have this dummy application. :) As soon as I delete it, the providers page falls back in the above mentioned state.
-> So this ticket could be a duplicate to #3198
