### ISSUE TITLE
ZFS tuning

### ISSUE THREAD

**Issue by obrienmd** [flynn/flynn#3249]
A few notes on the ZFS configuration on a default Flynn install for Ubuntu 14.04 are below.
- Generally, zfs LZ4 compression is recommended (1), current in Flynn is no compression.
- For Postgres, an 8k ZFS recordsize is recommended (2), current in Flynn is default 128k.
- For Postgres, atime=off is recommended (2), current in Flynn is default on.

**References:**
(sorry for Reddit, there are lots of sources out there but it was an easy find with lots of info)
- (1) http://open-zfs.org/wiki/Performance_tuning#LZ4_compression
- (2) https://www.reddit.com/r/zfs/comments/3mvv8e/does_anyone_run_mysql_or_postgresql_on_zfs/

**Comment by obrienmd** [comment]
Updated to include recordsize, atime.

**Comment by onnimonni** [comment]
For Mariadb Recommended recordsize is 16k because the innodb page size is 16k (1). To bypass this we would need to compile our own version. So maybe just compromise perfect postgres settings just a little bit.

**References:**
* (1) https://blogs.oracle.com/realneel/entry/mysql_innodb_zfs_best_practices

**Comment by obrienmd** [comment]
Perhaps this is getting too granular, but could Flynn not just use 8k for the zvol backing postgres, 16k for the one backing mariadb, and default for apps? Not sure that's how zfs works, not an expert on that either :)

**Comment by titanous** [comment]
Yes, the parameters can be set per-dataset. My understanding is that the `recordsize` setting specifies the *maximum* record size, so it's impact is not as big. We should also evaluate disabling the primary and/or secondary caches (`primarycache=metadata, secondarycache=metadata`) for databases that do their own caching like Postgres.

**Comment by obrienmd** [comment]
It's even less big with LZ4 compression enabled, apparently.

**Comment by obrienmd** [comment]
Would it make sense to have a "performance tracking" project board like the "security tracking" one that's now used for sec-related items?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
