### ISSUE TITLE
Redis error from socket.io->redis client (sub): Error: Redis connection to leader

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3250]
Just trying to push to a staging version of my app but it failing and when checking the logs I can see errors such as 

```
2016-08-09T17:48:23.798908Z app[web.cluster2-093bc41a-0e48-4afa-a8e1-0213485e16c0]: Redis error from socket.io->redis client (sub): Error: Redis connection to leader.redis-8661f01f-1369-49ab-b918-8859c981b6b1.discoverd:6379 failed - getaddrinfo ENOTFOUND leader.redis-8661f01f-1369-49ab-b918-8859c981b6b1.discoverd leader.redis-8661f01f-1369-49ab-b918-8859c981b6b1.discoverd:6379
2016-08-09T17:48:23.799012Z app[web.cluster2-093bc41a-0e48-4afa-a8e1-0213485e16c0]:     at errnoException (dns.js:27:10)
2016-08-09T17:48:23.799650Z app[web.cluster2-093bc41a-0e48-4afa-a8e1-0213485e16c0]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

any ideas why this might be?

**Comment by titanous** [comment]
Did it work previously?

Please collect the debug info.

**Comment by dottodot** [comment]
Not sure as haven't used it for a while, maybe I should delete it an d try again?

**Comment by titanous** [comment]
The error probably indicates that one of these things is true: discoverd is broken, the redis instance is broken, or the redis instance doesn't exist.

**Comment by dottodot** [comment]
yes something is wrong as it won't let me delete the app and I get the error unknown_error: Something went wrong

Not sure if it's related to the issues I had the other day. Anyway I'll collect the debug info and get it over to you.

**Comment by dottodot** [comment]
Ok it's been sat at `getting job logs` for some time now, doesn't usually take this long.

**Comment by dottodot** [comment]
OK it's been nearly 20 mins now so doesn't look like it's going to collect the debug info

**Comment by titanous** [comment]
Okay, you can manually tar up `/var/log/flynn` and email to logs@flynn.io

**Comment by dottodot** [comment]
Ok those have been sent to you. Also as a bit of a test I just tried creating a new app and pushing but it ended in the same result.

**Comment by lmars** [comment]
@dottodot was this cluster updated with `flynn-host update` or restored from a backup?

The Redis jobs are failing to start because the image artifact is incorrect, which coincidentally I have proposed a fix for today in #3247.

**Comment by dottodot** [comment]
It was restored from a backup. So do I just go through the instructions in the post to fix it?

**Comment by dottodot** [comment]
If so I've just run the first command and get.

```
The program 'docker' is currently not installed. You can install it by typing:
apt-get install docker
       redis: 
The program 'docker' is currently not installed. You can install it by typing:
apt-get install docker
 slugbuilder: 
The program 'docker' is currently not installed. You can install it by typing:
apt-get install docker
  slugrunner: 
```

**Comment by lmars** [comment]
@dottodot no you don't need to run those commands, those commands are just proof that the change in that PR works.

You can update the image URI with the following:

```
$ REDIS_IMAGE_URI=$(grep -oP 'https://dl.flynn.io/tuf\?name=flynn/redis&id=\w+' /etc/flynn/bootstrap-manifest.json | uniq)

$ flynn -a controller pg psql -- -c "UPDATE artifacts SET uri = '${REDIS_IMAGE_URI}' WHERE uri LIKE '%flynn/redis%'"
```

You should see `UPDATE 1` (or `UPDATE N` if you have N Redis resources).

You may need to scale the Redis app down and back up again, e.g.:

```
$ flynn -a $REDIS_APP scale redis=0

$ flynn -a $REDIS_APP scale redis=1
```

(you can get `$REDIS_APP` from `flynn apps`).

**Comment by dottodot** [comment]
```
flynn -a controller pg psql -- -c "UPDATE artifacts SET uri = '${REDIS_IMAGE_URI}' WHERE uri LIKE '%flynn/redis%'"
```
gives an error of
```
ERROR:  duplicate key value violates unique constraint "artifacts_type_uri_idx"
DETAIL:  Key (type, uri)=(docker, https://dl.flynn.io/tuf?name=flynn/redis&id=57b74ddacab85a36f263957ae042bddbae8a8432631cf023029aed52ca109d7e) already exists.
```

**Comment by lmars** [comment]
@dottodot ah ok, try this instead:

```
$ flynn -a controller pg psql -- -c "UPDATE release_artifacts SET artifact_id = (SELECT artifact_id FROM artifacts WHERE uri = '${REDIS_IMAGE_URI}') WHERE release_id IN (SELECT release_id FROM apps WHERE meta->>'flynn-system-app' = 'true' AND name LIKE 'redis-%')"
```

Note that the proper fix (#3247) is now merged so should make it into a release later today.

**Comment by dottodot** [comment]
That gives the error
```
ERROR:  null value in column "artifact_id" violates not-null constraint
DETAIL:  Failing row contains (93516c6f-f8fd-46ef-aa00-68724ebb7c39, null, 2016-05-23 13:52:54.484808+00, null, 0).
```

**Comment by lmars** [comment]
@dottodot ok that doesn't make much sense, the error you got from the first command indicates that the Redis artifact already exists, but the second that it doesn't exist!

Are you sure you had `$REDIS_IMAGE_URI` set when you ran the second command?

You could just do things more directly:


grab the appropriate `artifact_id`:

```
$ flynn -a controller pg psql -- -c "SELECT artifact_id FROM artifacts WHERE uri = 'https://dl.flynn.io/tuf?name=flynn/redis&id=57b74ddacab85a36f263957ae042bddbae8a8432631cf023029aed52ca109d7e'"
```

update the Redis apps to use that id (substitute `$ARTIFACT_ID` with the id from above):

```
$ flynn -a controller pg psql -- -c "UPDATE release_artifacts SET artifact_id = '${ARTIFACT_ID}' WHERE release_id IN (SELECT release_id FROM apps WHERE meta->>'flynn-system-app' = 'true' AND name LIKE 'redis-%')"
```

You can also wait for the next nightly release which will include a fix for this.

**Comment by dottodot** [comment]
OK I updated to the nightly which seem to have worked as I can now create a new app with redis however the app I was having issues with seem to be a bit broken as I can't delete it as I get the error

unknown_error: Something went wrong

**Comment by lmars** [comment]
@dottodot sorry I missed your reply, so you get an error deleting your app or deleting the Redis app? Can you try it again then gist the output of `flynn -a controller log`? `sudo flynn-host collect-debug-info` would also be useful.

**Comment by dottodot** [comment]
It's the app called bailey-staging I'm trying to delete. I've sent the logs via email.

**Comment by lmars** [comment]
@dottodot ok so the app is failing to delete because the Redis provider can no longer find the original release which was created when the resource was provisioned.

Because app deletion is not transactional, I suspect a previous failed attempt at deleting the app did actually manage to delete the Redis release, can you check if it still exists in the database with:

```
$ flynn -a controller pg psql -- -c "SELECT release_id, env->>'FLYNN_REDIS', created_at, deleted_at FROM releases WHERE release_id = '1a9c4aa7-5ebb-414f-9b6b-ddfb25ced2d1'"
```

If it does exist, run the following to undelete it then try deleting the app once more:

```
$ flynn -a controller pg psql -- -c "UPDATE releases SET deleted_at = NULL WHERE release_id = '1a9c4aa7-5ebb-414f-9b6b-ddfb25ced2d1'"
```

If it doesn't exist we will need to try and figure out how that happened.

**Comment by dottodot** [comment]
running the first command I got 

```
              release_id              | ?column? |          created_at           |          deleted_at           
--------------------------------------+----------+-------------------------------+-------------------------------
 1a9c4aa7-5ebb-414f-9b6b-ddfb25ced2d1 |          | 2016-05-30 08:29:35.359494+00 | 2016-08-11 09:49:40.812447+00
```
then the second i got
```
UPDATE 1
```
but on deleting the app I still get
```
unknown_error: Something went wrong
```

**Comment by lmars** [comment]
@dottodot ok, please collect debug info again, sorry this is getting drawn out but it's always good for us to understand exactly what is going on.

**Comment by dottodot** [comment]
OK I've emailed you the latest logs

**Comment by lmars** [comment]
@dottodot ok so the previous undelete of the release worked, but then the release is missing the `FLYNN_REDIS` environment variable (which is really strange) so the worker can't find the appropriate Redis app to delete.

First, please post the `env` column of that release (just so I can understand what is going on):

```
$ flynn -a controller pg psql -- -c "SELECT env FROM releases WHERE release_id = '1a9c4aa7-5ebb-414f-9b6b-ddfb25ced2d1'"
```

Then, fix the env by grabbing the name of the Redis app which is supposed to get deleted with:

```
$ FLYNN_REDIS="$(flynn -a bailey-staging env get FLYNN_REDIS)"
```

and set `FLYNN_REDIS` to this same value for the broken Redis release:

```
$ flynn -a controller pg psql -- -c "UPDATE releases SET env = '{\"FLYNN_REDIS\": \"${FLYNN_REDIS}\"}' WHERE release_id = '1a9c4aa7-5ebb-414f-9b6b-ddfb25ced2d1'"
```

Now, with your fingers crossed, try deleting the app again :wink:.

**Comment by dottodot** [comment]
OK the first command gives me

```
 env  
------
 null
(1 row)
```
then the second
```
no app release found
```

**Comment by lmars** [comment]
@dottodot ok, just set `FLYNN_REDIS` to the app name of the Redis app which you know needs to be deleted (e.g. `FLYNN_REDIS=redis-xxx`, you can find it in `flynn apps`).

Feel free to ping me in IRC if you want to do this synchronously (lmars in #flynn on Freenode).

**Comment by lmars** [comment]
After a conversation in IRC, we figured out that the Redis app also no longer exists, so we just removed the resource record in the database:

```
$ flynn -a controller pg psql -- -c "UPDATE app_resources SET deleted_at = now() WHERE app_id = '${APPID}'"
```

and then deleting the app worked.
