### ISSUE TITLE
SRV records returned from discoverd are not in standard format

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3251]
**What I was trying to do:**
I was trying to use the SRV record from discoverd in other application for automatic dns SRV port resolving with nginx in another application.

**What I was expecting:**
```
0	IN	SRV	1 1 8080 _http._tcp.php-web.discoverd.
```
**What I got instead:**
```
0	IN	SRV	1 1 8080 a795615b7cac0ed23d71f420ba1d06a2.php-web._i.discoverd.
```
**Debug:**
```
bash-4.3# drill SRV php-web.discoverd
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 32906
;; flags: qr aa rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; php-web.discoverd.	IN	SRV

;; ANSWER SECTION:
php-web.discoverd.	0	IN	SRV	1 1 8080 a795615b7cac0ed23d71f420ba1d06a2.php-web._i.discoverd.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 100.100.29.1
;; WHEN: Tue Aug  9 23:31:49 2016
;; MSG SIZE  rcvd: 125
```

**Links:**
http://nginx.org/en/docs/http/ngx_http_upstream_module.html#service

**Comment by titanous** [comment]
I believe that the answer to that query complies with [RFC 2782](https://tools.ietf.org/html/rfc2782). The target (`a795615b7cac0ed23d71f420ba1d06a2.php-web._i.discoverd.`) will  return an A record containing address of that service instance.

If the target referenced the domain in the DNS question, there would be no way to disambiguate which instance corresponds with the record returned in the answer.

**Comment by titanous** [comment]
I think the problem with your configuration is actually this:

> If the service name does not contain a dot (“.”), then the RFC-compliant name is constructed and the TCP protocol is added to the service prefix.

Try something like this:

```text
server discoverd service=_php-web resolve;
```

Which should result in the domain: `_php-web._tcp.discoverd.`

**Comment by onnimonni** [comment]
thanks again @titanous!

I jumped the wagon too early and didn't notice that the `resolve` module is only available in the `nginx plus` so even if this works I couldn't test it yet.

I try to test other `SRV` routing possibilities soon.

If this thread bothers you until then you can close it and we can reopen then.
