### ISSUE TITLE
Feature Request: Google cloud storage as blobstorage

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3252]
Reasons to support GCS:
* It's has [better throughput according to this test]( http://blog.zachbjornson.com/2015/12/29/cloud-storage-performance.html).
* It's cheaper ( 0.03$ vs 0.026$ )
* It has been supporting http2 since it's really early stages

**Comment by imjorge** [comment]
@titanous isn't this already in https://github.com/flynn/flynn/blob/master/blobstore/backend/gcs.go?

**Comment by lmars** [comment]
This is indeed implemented, see [here](https://flynn.io/docs/production#google-cloud-storage) for docs on how to set it up.
