### ISSUE TITLE
Missing artifact IDs in gitreceive env of cluster restored from backup

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3253]
A cluster started from a nightly a few days ago and then backed up and restored to `v20160809.0` is missing the `SLUGBUILDER_IMAGE_ID` and `SLUGRUNNER_IMAGE_ID` environment variables for gitreceive. A push reports this error:

```text
remote: ERROR: Error getting slugbuilder image: GET http://controller.discoverd/artifacts/: httpclient: raw req: unexpected status 401
```

I took a quick look at the backup restore code and it doesn't look like the old `_URI` variables are converted to the new `_ID` anywhere.

Thanks to @bbaptist for reporting this.

/cc @lmars

**Comment by lmars** [comment]
Fixed in #3253.
