### ISSUE TITLE
Bootstrap gives http link to dashboard which results in ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3263]
**What I did:**
After I had bootstrapped the cluster flynn outputted http link to dashboard:
**http://**dashboard.flynn.mysite.com/login

I went to the link and entered my token to login input.

**What I was expecting:**
To enter the dashboard.

**What I got instead:**
Login didn't do anything because it returned  301 to https://dashboard.flynn.mysite.com/user/sessions and my browser didn't yet trust the self-signed cert and denied the 301 without any warnings.

When I opened chrome dev tools I immediately understood that I should use **https** instead:
**https://**dashboard.flynn.mysite.com/login

For less experienced users this might be really confusing.

**Comment by titanous** [comment]
The dashboard is supposed to prompt you to install the CA certificate. We're going to be fixing this up soon with Let's Encrypt support (#1995).

**Comment by onnimonni** [comment]
Excellent :)!

**Comment by jvatic** [comment]
Hmm, the dashboard didn't redirect you to `/installcert` when visiting the http URL?
While attempting to reproduce this scenario, I've found that clicking on a navigation item while on the `/installcert` page incorrectly loads the login page (#3286). I haven't been able to reproduce the scenario where the `/installcert` page doesn't load (it could take a few seconds if on a slow connection though).

**Comment by onnimonni** [comment]
No it didn't redirect to anywhere. I had installed the cert from other clusters correctly before and the moment this happened I might have had 3 certs from different clusters installed already. Maybe this affected the process somehow?

**Comment by jvatic** [comment]
Having certs from other clusters installed wouldn't effect this. Can you see what requests are made in the network console? There should be a few requests to `/ping` of the controller. Any errors in the JavaScript console would also be helpful.

**Comment by onnimonni** [comment]
Sorry I can't reproduce this anymore either :(.

**Comment by jvatic** [comment]
Please open a new issue if this comes up again
