### ISSUE TITLE
Can't use full-chain ssl certificate in router.

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3264]
**What I was trying to achieve:**
I wanted to add my own wildcard certificate to the router as default certificate.

**What I did:**
I followed the commands in this issue https://github.com/flynn/flynn/issues/2434.

I tried first to use my full-chain crt containing also the intermediate cert:
```
$ flynn -a router env set TLSCERT="$(cat mysite.com-full-chain.crt)" TLSKEY="$(cat mysite.com.key)"
app process type failed to start, got down job event
```

But when I tried the same command without full-chain cert it succeeded:
```
$ flynn -a router env set TLSCERT="$(cat mysite.com.crt)" TLSKEY="$(cat mysite.com.key)"
Created release 1bc4ba50-adc4-4147-b8d2-8d4cd41d4821.
```

My full-chain cert is in following format and at least it works in nginx:
```
-----BEGIN CERTIFICATE-----
MIIETT...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEGjCC...
-----END CERTIFICATE-----
```

**Comment by titanous** [comment]
What is the error from the router log? `flynn -a router log`

**Comment by onnimonni** [comment]
```
2016-08-11T14:10:45.893703Z app[app.grid2.flynn.hki.geniem.io-fdbf5167-b86b-46dc-b636-910a911a31bc]: 14:10:45.893640 server.go:118: crypto/tls: private key type does not match public key type
```

This might be affected that my key is using elliptic curves (ecdsa) and the intermediate is using rsa.

**Comment by titanous** [comment]
Ah, the issue is that the certificate is out of order. Put the end-entity certificate first, and the intermediate second. This will be fixed by #1251.

**Comment by onnimonni** [comment]
You mean like this:
```
-----BEGIN CERTIFICATE-----
Root cert
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Intermediate
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
My cert
-----END CERTIFICATE-----
```

**Comment by titanous** [comment]
Like this:

```text
-----BEGIN CERTIFICATE-----
My cert
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Intermediate
-----END CERTIFICATE-----
```

Don't include the root.

**Comment by onnimonni** [comment]
Yeah it worked!
