### ISSUE TITLE
Better error messages for flynn env / env parser should support nested quotes

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3265]
I tried to use single quotes `'` to wrap my secret_access_key and this what I got:

```
$ flynn -a blobstore env set BACKEND_S3MAIN="backend=s3 region=eu-west-1 \
bucket=flynnblobstore access_key_id='XXXXXXXXXXXXX' \
secret_access_key='XXXXXXXXXXXXXXXXXXXXX'"
web process type failed to start, got down job event
```

By removing the single quotes everything worked out:

```
$ flynn -a blobstore env set BACKEND_S3MAIN="backend=s3 region=eu-west-1 \
bucket=flynnblobstore access_key_id=XXXXXXXXXXXXX \
secret_access_key=XXXXXXXXXXXXXXXXXXXXX"
Created release 5a1c6cf6-837e-4a60-9da4-19d047a666f0.
```

It would be nice to have error message which is somehow related to the problem at hand.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
