### ISSUE TITLE
Add easy way to configure auth for applications

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3268]
I think we could provide env eg `FLYNN_ROUTER_HTPASSWD` which could be used to add basic auth easily from commandline but maybe even straight from the dashboard.

This can also be implemented in route or completely in other method than the current ones available in the cli.

**Comment by titanous** [comment]
I'm not convinced that we should put this complexity into the router. Inevitably the next request will be supporting multiple usernames/passwords and every language and framework already has an easy way to handle this.

**Comment by onnimonni** [comment]
I agree and I also wanted to ask this to hear your opinion.

I raised this question because it's a really typical need in web development and I would love to have a way which even non-techical people could use.

**Comment by titanous** [comment]
There are some things we can do once we have the user auth system in place (#410). Basic auth is pretty kludgy.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
