### ISSUE TITLE
Unable to view logs during app build

### ISSUE THREAD

**Issue by michaelyork** [flynn/flynn#3277]
I only know this is broken because I remember what it looked like in a previous Flynn install from a few months back.

<img width="751" alt="screen shot 2016-08-11 at 3 30 52 pm" src="https://cloud.githubusercontent.com/assets/3916693/17607212/3f1beb20-5fd9-11e6-8f2e-ae224b3d2326.png">

Attempting to view via the logs UI, or via job logs in CLI, also returns nothing. Applies to all of my apps on this installation.

**Comment by titanous** [comment]
Are there any errors in the Javascript console?

**Comment by michaelyork** [comment]
None whatsoever. :(

**Comment by titanous** [comment]
Please collect the debug logs from the cluster with `sudo flynn-host collect-debug-info`.

**Comment by michaelyork** [comment]
Sent to logs@, thanks!

**Comment by titanous** [comment]
Does `flynn -a taffy log -r` show the deploy logs that didn't appear in the dashboard?

**Comment by michaelyork** [comment]
Yup! I see them all here.

**Comment by titanous** [comment]
@jvatic This does appear to be a dashboard issue since they are accessible via the CLI.

**Comment by jvatic** [comment]
What browser/version and OS/version does this occur with?
And does using a different browser exhibit the same behaviour?

**Comment by michaelyork** [comment]
It's happening across both Safari and Chrome on macOS Sierra and El Capitan.

**Comment by michaelyork** [comment]
I should also note that the `slugbuilder` process logs are also blank when you go into "Show logs" in the dashboard, while the other processes show their logs just fine.

**Comment by jvatic** [comment]
Sorry for the delay. I've been unable to reproduce the issue. Do you see any errors in the JavaScript console?

**Comment by michaelyork** [comment]
No errors in the console.
