### ISSUE TITLE
Allow changing cluster name

### ISSUE THREAD

**Issue by steverandy** [flynn/flynn#3278]
Once a cluster has been created, is there a way to change its name?
By default flynn generates a random name and but I don't see any field to set a name for the cluster.

**Comment by titanous** [comment]
Where is the cluster name that you want to change? In the CLI?

**Comment by steverandy** [comment]
Either web GUI or CLI.
Currently I don't see option to rename in web GUI or CLI.

**Comment by titanous** [comment]
Just to clarify, are you talking about the name shown by `flynn cluster` (eg. `flynn-1468029976`) or the cluster domain (eg. `2z24.flynnhub.com`)?

**Comment by steverandy** [comment]
The cluster name (flynn-1468029976)

**Comment by titanous** [comment]
You can change it in the CLI by changing the section header in `~/.flynnrc`. I will keep this issue open as a feature request for the dashboard/CLI to make it a command.
