### ISSUE TITLE
docker app killed unexpectedly

### ISSUE THREAD

**Issue by jsimnz** [flynn/flynn#3279]
I was running an app via a docker image opposed to a git repo and buildback, and partway through its execution it randomly died, only leaving a "killed" message in the log.

The container is being used for some basic deep learning stuff, but is rather compute and memory intensive. Originally I thought it was a memory issue, but rerunning it on a 32GB instance caused the same issue.

Running the same container on the same machine using regular docker commands completed without issue.

There isn't much info to go on since the only message is "killed". Any thoughts.

As a reference, this is the image I was running https://hub.docker.com/r/jsimnz/apartment-hunt/

**Comment by lmars** [comment]
@jsimnz did you try increasing the memory limit for the process (see [here](https://flynn.io/docs/apps#limits))?

**Comment by jsimnz** [comment]
Oh, I see, all good now. I knew you could set limits, but I didn't realize that there were default limits. Make sense though. Maybe a documentation update about that.

Thanks!

**Comment by lmars** [comment]
@jsimnz the docs are in GitHub if you want to take a stab at clarifying the default limits :smile:

https://github.com/flynn/flynn/blob/master/docs/content/apps.md
