### ISSUE TITLE
Default app for unmatched routes

### ISSUE THREAD

**Issue by paukiatwee** [flynn/flynn#3282]
As a developer, I want able to define default app to handle for any routes that did not match existing routes, so that I can have app that handle any custom domain.

Let say I build a SaaS that allow customer to use `customer001.myapp.com` as well as use `customer.com`. I know I can define wildcard `*.myapp.com` route to **my app**, but I want able to route `customer.com` to **my app** as well (by define **my app** as default app to handle unmatched routes).

Or such feature already implemented?

**Comment by titanous** [comment]
You can add two routes:

```text
flynn route add http "*.myapp.com"
flynn route add http myapp.com
```

Is that what you're looking for?

**Comment by titanous** [comment]
Ah, I understand. Do you know the domains you want to handle ahead of time? If so, you can use the Flynn API to add a new route for each customer domain.

**Comment by paukiatwee** [comment]
Can we define default app (cluster wide) to handle unmatched routes? If using API to add each domain, it is possible that hundred of routes map to single app, not sure performance will drop or not.

**Comment by titanous** [comment]
The router is designed to handle many routes (for this use case), and if there are performance issues we'd be happy to fix them. The reason why having explicit routes is better is that it will allow you to take advantage of the upcoming Let's Encrypt support (#1995) so that you can automatically provision free TLS certificates for all of your customer domains.

**Comment by paukiatwee** [comment]
Ah, that is good point for LE support. Any documentation for add route API? swagger.yml would be great, but I cant find any.

**Comment by titanous** [comment]
https://flynn.io/docs/api/controller#create-route

**Comment by paukiatwee** [comment]
Awesome!
