### ISSUE TITLE
Debug log service

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3284]
`flynn-host collect-debug-info` currently uploads logs to `gist.github.com` and frequently fails when logs are too big to upload, and our strategy of buffering all the logs in memory before creating the gist also sometimes causes issues.

Although we have a `--tarball` fallback, it is not always easy for users to share that in order to get assistance.

We should add a dedicated service which receives the logs from `flynn-host collect-debug-info` (perhaps as a stream to minimise in-memory buffering) and exposes them to Flynn collaborators for viewing.

Some things to consider:
- Web UI (I personally prefer CLI tools like `less` and `grep`)
- Authentication
- Storage (most likely S3 backed blobstore)
- Size limit
- Rate limit
- Encrypted logs (public Flynn GPG key?)
- Resumable uploads

/cc @titanous

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
