### ISSUE TITLE
worker: Still SetAppRelease if scaling old release down fails

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3285]
If scaling down the old release during a deployment fails, we treat it as a failed deploy but we skip doing a rollback as that would involve stopping the new, functioning release (see [here](https://github.com/flynn/flynn/blob/v20160812.0/controller/worker/deployment/all_at_once.go#L68-L88) and [here](https://github.com/flynn/flynn/blob/v20160812.0/controller/worker/deployment/one_by_one.go#L106-L129)).

This then means though that we don't [set the app release](https://github.com/flynn/flynn/blob/v20160812.0/controller/worker/deployment/context.go#L114-L123) so the old (now scaled down) release is still the app's release rather than the new, functioning release, meaning subsequent deploys think the app has no scale and scales it to `web=1`, effectively "losing" the new release but leaving it scaled up.

I think the solution here is to just log the error when scaling the old formation fails but not return any error so that the deploy is marked as a success.

@titanous wdyt?

**Comment by titanous** [comment]
I think we should add a warning field that gets populated with the error while marking it successful. That way it can be displayed to the user so they can check that everything looks right.
