### ISSUE TITLE
had Error(http://127.0.0.1:1111/services/flynn-host/instances: EOF) when update on single node mode

### ISSUE THREAD

**Issue by koolay** [flynn/flynn#3290]
I have error, when I `flynn-host udpate` on single node mode. (AWS)

`ubuntu@ip-xxxx:~$` sudo flynn-host update
INFO[08-15|06:43:34] initializing TUF client 
INFO[08-15|06:43:34] updating TUF data 
INFO[08-15|06:43:44] getting configured release channel 
INFO[08-15|06:43:44] determining latest version of stable release channel 
INFO[08-15|06:43:44] latest stable version is v20160814.0 
INFO[08-15|06:43:44] downloading v20160814.0 flynn-host binary 
INFO[08-15|06:43:45] executing latest flynn-host binary 
INFO[08-15|06:43:45] initializing TUF client 
INFO[08-15|06:43:45] reading TUF database 
INFO[08-15|06:43:45] getting host list 
EROR[08-15|06:43:45] error getting host list                  err="Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: EOF"
06:43:45.702422 host.go:153: Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: EOF`

What 's the problem, how to fix?

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug info` and post the logs link here.

**Comment by koolay** [comment]
The log is too large ? Memory usage is 430/992M.

sudo flynn-host collect-debug-info

INFO[08-15|14:23:51] uploading logs and debug information to a private, anonymous gist
INFO[08-15|14:23:51] this may take a while depending on the size of your logs
INFO[08-15|14:23:51] getting flynn-host logs
fatal error: runtime: out of memory


runtime stack:
runtime.throw(0xf57d10, 0x16)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sysMap(0xc82b730000, 0x16850000, 0x0, 0x15b2a58)
	/usr/local/go/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0x1597080, 0x16850000, 0xc820019220)
	/usr/local/go/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0x1597080, 0xb428, 0x0)
	/usr/local/go/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0x1597080, 0xb427, 0xc8200160c0)
	/usr/local/go/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0x1597080, 0xb427, 0x100000000, 0x47b029)
	/usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7ffcb87479a0)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x1597080, 0xb427, 0x10100000000, 0x20)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x1684d79e, 0xc800000001, 0xc8201af418)
	/usr/local/go/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0x1592100)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc8201af2b0 sp=0xc8201af2a8
runtime.mallocgc(0x1684d79e, 0xbf81c0, 0xc800000001, 0xb426acf)
	/usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc8201af388 sp=0xc8201af2b0
runtime.newarray(0xbf81c0, 0x1684d79e, 0xc8201af428)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc8201af3c8 sp=0xc8201af388
runtime.makeslice(0xbd8480, 0x1684d79e, 0x1684d79e, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc8201af418 sp=0xc8201af3c8
bytes.makeSlice(0x1684d79e, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:198 +0x64 fp=0xc8201af468 sp=0xc8201af418
bytes.(*Buffer).ReadFrom(0xc8201af598, 0x7f05e529a270, 0xc8200246e0, 0xb426acf, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:170 +0xd3 fp=0xc8201af518 sp=0xc8201af468
io/ioutil.readAll(0x7f05e529a270, 0xc8200246e0, 0xb426acf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:33 +0x156 fp=0xc8201af610 sp=0xc8201af518
io/ioutil.ReadFile(0xf5f6c0, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/ioutil/ioutil.go:70 +0x19f fp=0xc8201af6d8 sp=0xc8201af610
github.com/flynn/flynn/host/cli.(*Gist).AddLocalFile(0xc8201d0c00, 0xec0640, 0xe, 0xf5f6c0, 0x1d, 0x0, 0x0)
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/host/cli/gist.go:34 +0x4f fp=0xc8201af798 sp=0xc8201af6d8
github.com/flynn/flynn/host/cli.runCollectDebugInfo(0xc8202219e0, 0x0, 0x0)
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/host/cli/collect-debug-info.go:68 +0x33e fp=0xc8201afae0 sp=0xc8201af798
github.com/flynn/flynn/host/cli.Run(0x7ffcb874996c, 0x12, 0x15b0210, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x60c fp=0xc8201afc00 sp=0xc8201afae0
main.main()
	/tmp/tmp.XVqY6Q6Pji/src/github.com/flynn/flynn/host/host.go:145 +0xb38 fp=0xc8201aff00 sp=0xc8201afc00
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc8201aff50 sp=0xc8201aff00
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8201aff58 sp=0xc8201aff50

**Comment by titanous** [comment]
Okay, please collect the logs manually from `/var/log/flynn` and email them to logs@flynn.io

**Comment by koolay** [comment]
http:s//gist.github.com/2556b17848a849fc887896c5f41f5dc8

**Comment by koolay** [comment]
`sudo flynn-host ps`

16:14:02.033186 host.go:153: could not list hosts: Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: EOF

`ps -ef | grep flynn`

root      1167     1  3 16:01 ?        00:00:29 /usr/local/bin/flynn-host daemon
root      3566  3536  0 16:02 ?        00:00:00 sudo -u postgres -E -H /bin/flynn-postgres
message+  3573  3566  0 16:02 ?        00:00:01 /bin/flynn-postgres
root      3715  3686  0 16:02 ?        00:00:02 /bin/flynn-controller
root      3766  3736  2 16:02 ?        00:00:14 /bin/flynn-scheduler
root      3879  3816  0 16:02 ?        00:00:03 /bin/flynn-status
root      3906  3851  0 16:02 ?        00:00:04 /bin/flynn-router -http-port 80 -https-port 443 -tcp-range-start 3000 -tcp-range-end 3500
root      3917  3856  0 16:02 ?        00:00:01 /bin/flynn-redis-api
root      4038  3933  0 16:03 ?        00:00:01 /bin/flynn-worker
root      4040  3934  0 16:03 ?        00:00:01 /bin/flynn-blobstore
root      4041  3921  0 16:03 ?        00:00:01 /bin/flynn-postgres-api
root      4072  3963  0 16:03 ?        00:00:01 /bin/flynn-mongodb-api
message+  4087  3582  0 16:03 ?        00:00:00 postgres: flynn postgres 100.100.33.8(45704) idle
root      4164  4103  0 16:03 ?        00:00:00 /bin/flynn-dashboard
root     12467 12437  0 16:13 ?        00:00:00 /bin/flynn-mariadb-api

**Comment by titanous** [comment]
Please send the `discoverd` process a SIGQUIT and then gist the resulting trace from `/var/log/flynn/e15be6b2-df1c-4917-b5fc-bb8d861d3b1d.log`

**Comment by koolay** [comment]
https://gist.github.com/anonymous/d7e53e7a0dd12ea84610a6e6f2470fb2

**Comment by titanous** [comment]
@koolay That file looks mangled, can you try uploading the log file again?

**Comment by koolay** [comment]
https://gist.github.com/95479d85089efe42eb3e7929b412135b

https://gist.github.com/anonymous/701a49a0925a86e5270611db5615bac9

**Comment by titanous** [comment]
That trace looks like it's from a different process, did you end up running SIGQUIT twice?

**Comment by titanous** [comment]
Also, did you try to run the update multiple times?

**Comment by koolay** [comment]
Yes, It's blocking, then I do it again.
How to repair?

**Comment by titanous** [comment]
You should run the install script with the `--clean` parameter to delete all data and state and bootstrap a new cluster.

**Comment by koolay** [comment]
Thanks. 
It work. I reinstall with the --clean parameter.

**Comment by SalvoLunar** [comment]
getting a similar error after attempting to restart the flynn-host 
00:33:10.536323 host.go:166: could not list hosts: Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: net/http: request canceled (Client.Timeout exceeded while awaiting headers),Get http://127.0.0.1:1111/services/flynn-host/instances: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Can you help?

**Comment by SalvoLunar** [comment]
Some other error appearing when attempting to fix with flynn-host fix --min-hosts 3
EROR[05-27|00:41:04] unable to list hosts from discoverd, falling back to peer IP list error="Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: net/http: request canceled (Client.Timeout exceeded while awaiting headers),Get http://127.0.0.1:1111/services/flynn-host/instances: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
