### ISSUE TITLE
Ability to set tags on application create or pre-initial scale

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3293]
Right now as far as I know the only way to set a tag on an application is to do a `flynn scale web=3,active=true`. This means if you deploy an application initially and want it to go to a particular set of hosts it will be scaled to 1 and then immediately re-released with the scale you set and the tags assigned to it.

I would like to be able to set tags for the initial scale if possible.

**Comment by lmars** [comment]
We probably want to add `ProcessType.DefaultTags` or similar and expose it via the CLI.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
