### ISSUE TITLE
Controller refuses connection on custom domain

### ISSUE THREAD

**Issue by Nop0x** [flynn/flynn#3296]
Hey,

just did a fresh install of flynn and my controller seems to be rejecting any form of communcation:

> `vagrant@flynn:~$ flynn create`
> `Post https://controller.worldscolli.de/apps: dial tcp 144.76.184.51:443: getsockopt: connection refused`

atm in the machine port 80 is free, but i forward requests to this port through port 25000.

e.g.: dashboard.worldscolli.de:25000 works.

boostrapped flynn with:

`sudo \ CLUSTER_DOMAIN=worldscolli.de \ flynn-host bootstrap`

ca certificate creating failes as I want to add my cluster:

`Error writing CA certificate: Get https://controller.worldscolli.de/ca-cert: dial tcp 144.76.184.51:443: getsockopt: connection refused`

any idea?

thanks in advance!

**Comment by titanous** [comment]
It looks like you are using the Vagrant VM, is that correct? Do you have a firewall configured? Are you using a Vagrantfile from the repo?
