### ISSUE TITLE
collect-debug-info should grab /var/log/flynn if local host isn't in discoverd

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3297]
If discoverd/flynn-host are not working properly on a host, `collect-debug-info` may end up collecting logs from other hosts based on the job list but skip the host it is being run on due to a lack of listed jobs. In this case the tool should manually collect the log files.

**Comment by tianx2** [comment]
logs - https://bazaarvoice.box.com/s/5pmlxf5ssrf038vokcefnlp1hu6pj8k2

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
