### ISSUE TITLE
after update, providers disappeared from dashboard

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#3298]
in dashboard, the providers tab is empty. inside apps, databases seems to have no name but present.

I get `VM124 dashboard-56ebc63….js:9060 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined` and `VM124 dashboard-56ebc63….js:4274 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined` errors

Version: v20160814.0

**Comment by hadifarnoud** [comment]
it seems the actual providers exist and working but not shown

**Comment by jvatic** [comment]
Can you post the output of `flynn provider`? I think this may be #3198.

**Comment by hadifarnoud** [comment]
```
c1a34fcf-af18-4732-a6c3-0287a0a898da  mysql     http://mariadb-api.discoverd/databases
3c2cf900-0df9-4435-834b-0d1d0cfe4db4  redis     http://redis-api.discoverd/clusters
b7165b71-cd87-4f24-b195-fc0737b0ca7f  postgres  http://postgres-api.discoverd/databases
```

**Comment by jvatic** [comment]
This is indeed #3198, there is a workaround here: https://github.com/flynn/flynn/issues/3198#issuecomment-235968699

**Comment by hadifarnoud** [comment]
@jvatic the url in that workaround should not matter, right?
when this bug is fixed, how can I revert this?

**Comment by jvatic** [comment]
Correct, the URL is irrelevant.

This should revert the workaround:
```
flynn -a controller pg psql
=> DELETE FROM providers where name = 'mongodb';
DELETE 1
=> \q
flynn -a mongodb delete --yes
```

We'll have a fix for using mongodb soon.

**Comment by jvatic** [comment]
See here if you need to use mongodb: https://github.com/flynn/flynn/issues/3198#issuecomment-240152451
