### ISSUE TITLE
Blobstore slug garbage collection doesn't appear to remove old slugs

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3302]
I am on version `v20160814.0` and using the S3 blobstore backend.

I have set `gc.max_inactive_slug_releases=2` using the command `flynn meta set gc.max_inactive_slug_releases=2`.

I have a staging Flynn cluster I am using to test the deployment system we are developing. We have been doing quite a few pushes to the only app in the cluster and I was expecting that the S3 blobstore would contain only a few images. However, I see about 17 200MB images stored there. To me this is not expected behavior.

Is there a bug in the garbage collection, or a misunderstanding of the feature on my part?

**Comment by lmars** [comment]
@bbaptist please deploy your app then run `sudo flynn-host collect-debug-info` and post the resulting gist here.

**Comment by bbaptist** [comment]
Here is the requested `flynn-host collect-debug-info` post deploy of application.

https://gist.github.com/63e445ff54762f2f04cfb6c83474b576

**Comment by bbaptist** [comment]
I just deleted that app from Flynn and all the images are still found in the S3 blobstore. Shouldn't all the images associated with this app have also been removed?

**Comment by lmars** [comment]
@bbaptist thanks for the debug info, so the garbage collection cycle is happening but it determines that no releases need to be deleted:

```
t=2016-08-16T23:33:07+0000 lvl=info msg="handling garbage collection" app=worker fn=HandleAppGarbageCollection job_id=143 error_count=0
t=2016-08-16T23:33:07+0000 lvl=info msg="getting app" app=worker fn=HandleAppGarbageCollection app.id=31e90770-ebe6-4313-972d-e327b3f1f2a8
t=2016-08-16T23:33:07+0000 lvl=info msg="deleting old slug releases" app=worker fn=HandleAppGarbageCollection app.id=31e90770-ebe6-4313-972d-e327b3f1f2a8
t=2016-08-16T23:33:07+0000 lvl=info msg="gc.max_inactive_slug_releases is set to 2" app=worker fn=HandleAppGarbageCollection app.id=31e90770-ebe6-4313-972d-e327b3f1f2a8
t=2016-08-16T23:33:07+0000 lvl=info msg="getting app releases" app=worker fn=HandleAppGarbageCollection app.id=31e90770-ebe6-4313-972d-e327b3f1f2a8
t=2016-08-16T23:33:07+0000 lvl=info msg="getting app formations" app=worker fn=HandleAppGarbageCollection app.id=31e90770-ebe6-4313-972d-e327b3f1f2a8
t=2016-08-16T23:33:07+0000 lvl=info msg="app has 37 releases (2 with distinct slugs)" app=worker fn=HandleAppGarbageCollection app.id=31e90770-ebe6-4313-972d-e327b3f1f2a8
t=2016-08-16T23:33:07+0000 lvl=info msg="no old releases to delete" app=worker fn=HandleAppGarbageCollection app.id=31e90770-ebe6-4313-972d-e327b3f1f2a8
t=2016-08-16T23:33:07+0000 lvl=info msg="garbage collection finished" app=worker fn=HandleAppGarbageCollection app.id=31e90770-ebe6-4313-972d-e327b3f1f2a8
```

So 37 releases were found but only 2 of them are inactive and have distinct slugs, so we need to determine whether all the releases are considered active or if they have the same slug.

Can you gist the output of the following command:

```
$ flynn -a controller pg psql -- -c "SELECT f.release_id, f.processes, f.deleted_at, a.uri FROM formations f INNER JOIN release_artifacts r USING (release_id) INNER JOIN artifacts a USING (artifact_id) WHERE app_id = '31e90770-ebe6-4313-972d-e327b3f1f2a8' AND type = 'file'"
```

This will tell us the scale and slug URI for each of your app's releases.

**Comment by bbaptist** [comment]
Here is the gist for that SQL command: https://gist.github.com/bbaptist/6a5ad6b423c628ed2f355df90bf37873

**Comment by bbaptist** [comment]
One thing to note, I had to delete this app and start over for the testing I was doing with our deploy system. I did a manual empty of the S3 bucket and cleared out the blobstore with the command `flynn -a blobstore pg psql -- -c "TRUNCATE files"`

**Comment by lmars** [comment]
@bbaptist did you run the SQL command before or after deleting the app?

**Comment by bbaptist** [comment]
@lmars I ran the `flynn -a controller pg psql -- -c "SELECT f.release_id, f.processes, f.deleted_at, a.uri FROM formations f INNER JOIN release_artifacts r USING (release_id) INNER JOIN artifacts a USING (artifact_id) WHERE app_id = '31e90770-ebe6-4313-972d-e327b3f1f2a8' AND type = 'file'"` command you asked me to run after I had deleted the app from the cluster.

**Comment by bbaptist** [comment]
If it helps for me to debug this, I have an environment with the exact same setup as described in the original post displaying this issue with the same app but a new deployment of it. I can run the controller psql with that app if you need me to.

**Comment by lmars** [comment]
@bbaptist if you have a cluster in this state it would be super helpful if you could jump into IRC (#flynn on Freenode) and we can debug this together, I'd really like to get to the bottom of this one as I can't reproduce myself.

**Comment by lmars** [comment]
@bbaptist after debugging this in IRC, slug GC is working as expected but you are seeing lots of blobs remain in S3 due to the git and build caches being leaked.

I have opened #3344 to track fixing that, thanks for helping us get to the bottom of it!
