### ISSUE TITLE
DB appliances: Add the availability to set an optional name for a DB

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3303]
Hi,
sooner or later, I want to migrate some databases to Flynn. Most of them will be for Flynn hosted applications but some of them not. They will be used by external applications (like a Sonar).
What bothers me a bit here is that the DBs will have random names. If I provision multiple MySQL DBs for external tools, I will have a hard time to map them to the belonging tool just by looking at the Flynn dashboard.
So it would be ideal to be able to give them a name which is displayed on the dashboard so I could recognize them again.

**Comment by jvatic** [comment]
A workaround until this is implemented would be to create an empty application with the desired name and assign the externally accessible DB to it.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
