### ISSUE TITLE
New lines in environment variables break 'flynn env' cli output

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3304]
If you put environment variables with new line characters into Flynn using `flynn env set KEY='text\nnextline'` the output from `flynn env` will be missing the values for some of the KEYs.

They show up in the dashboard properly, but arbitrary values (not all of the values) are missing in the cli.

**Comment by lmars** [comment]
@bbaptist I can't seem to reproduce this:

```
$ flynn env set KEY1='foo'

$ flynn env
KEY1=foo

$ flynn env set KEY2='line1
> line2
> line3'

$ flynn env
KEY1=foo
KEY2=line1
line2
line3

$ flynn env set KEY3='line1\nline2\nline3'

$ flynn env
KEY1=foo
KEY2=line1
line2
line3
KEY3=line1\nline2\nline3

$ flynn env set KEY4="$(echo -e 'line1\nline2\nline3')"

$ flynn env
KEY1=foo
KEY2=line1
line2
line3
KEY3=line1\nline2\nline3
KEY4=line1
line2
line3
```

Can you perhaps give a concrete example?

**Comment by bbaptist** [comment]
Wow, this is an embarrassing combination of reading comprehension, flawed bash parsing logic, and not verifying the output of the `flynn` cli, since the key/value pairs are separated by new lines. I think flynn is working correct, sorry for the distraction.
