### ISSUE TITLE
mariadb: Can't provision a MySQL DB

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3305]
Hi,
if I try to provision a MySQL DB from the Dashboard, I just get a "Something went wrong".
The click on the button triggers this log on the mariadb application:

> 2016-08-16T21:24:36.383578Z app[web.Flynn0-b9089792-1a91-4689-b618-c49442bbe289]: t=2016-08-16T21:24:36+0000 lvl=info msg="request started" component=mariadb-api req_id=8f6b8b93-e2c6-4249-90a3-ccf0c079be92 method=POST path=/databases client_ip=100.100.43.0
> 2016-08-16T21:24:36.384308Z app[web.Flynn0-b9089792-1a91-4689-b618-c49442bbe289]: t=2016-08-16T21:24:36+0000 lvl=info msg="checking status" app=mariadb-web fn=ScaleUp host=leader.mariadb.discoverd:3306
> 2016-08-16T21:24:36.391282Z app[web.Flynn0-b9089792-1a91-4689-b618-c49442bbe289]: t=2016-08-16T21:24:36+0000 lvl=info msg="error checking status" app=mariadb-web fn=ScaleUp err="Get http://leader.mariadb.discoverd:3307/status: dial tcp: lookup leader.mariadb.discoverd on 100.100.82.1:53: no such host"
> 2016-08-16T21:24:36.391325Z app[web.Flynn0-b9089792-1a91-4689-b618-c49442bbe289]: t=2016-08-16T21:24:36+0000 lvl=info msg="connecting to controller" app=mariadb-web fn=ScaleUp
> 2016-08-16T21:24:36.391592Z app[web.Flynn0-b9089792-1a91-4689-b618-c49442bbe289]: t=2016-08-16T21:24:36+0000 lvl=info msg="retrieving app release" app=mariadb-web fn=ScaleUp app=34c17374-f4d8-4104-9c85-ad9cf20154e2
> 2016-08-16T21:24:36.393424Z app[web.Flynn0-b9089792-1a91-4689-b618-c49442bbe289]: t=2016-08-16T21:24:36+0000 lvl=eror msg="get release error" app=mariadb-web fn=ScaleUp app=34c17374-f4d8-4104-9c85-ad9cf20154e2 err="GET http://controller.discoverd/apps/34c17374-f4d8-4104-9c85-ad9cf20154e2/release: httpclient: raw req: unexpected status 401"
> 2016-08-16T21:24:36.393457Z app[web.Flynn0-b9089792-1a91-4689-b618-c49442bbe289]: t=2016-08-16T21:24:36+0000 lvl=eror msg="GET http://controller.discoverd/apps/34c17374-f4d8-4104-9c85-ad9cf20154e2/release: httpclient: raw req: unexpected status 401" component=mariadb-api req_id=8f6b8b93-e2c6-4249-90a3-ccf0c079be92
> 2016-08-16T21:24:36.393633Z app[web.Flynn0-b9089792-1a91-4689-b618-c49442bbe289]: t=2016-08-16T21:24:36+0000 lvl=info msg="request completed" component=mariadb-api req_id=8f6b8b93-e2c6-4249-90a3-ccf0c079be92 status=500 duration=50.523113ms

**Comment by josephglanville** [comment]
Looks like the controller key is not set correctly on the mariadb release.
Is this a new cluster, a restore from backup or a cluster has been updated?

**Comment by philiplb** [comment]
I might have mangled with the controller key:
On a cluster node, I executed this:

```bash
CONTROLLER_KEY=$(flynn -a controller env get AUTH_KEY) flynn-host bootstrap --steps controller-key,mongodb-password,mongodb,add-mongodb-provider
```
But as no cluster is setup for the flynn CLI, the variable CONTROLLER_KEY was invalid and the command seemed to have generated a new key.

How do I recover? What else might be broken now? :)

**Comment by philiplb** [comment]
Just checked via
```bash
flynn -a controller env get AUTH_KEY
```

It's still the same key from the initial cluster setup.

**Comment by josephglanville** [comment]
Can you check if `flynn -a mariadb env -t web get CONTROLLER_KEY` matches the one currently set on the controller? If not you will need to update it with `flynn -a mariadb env -t web set CONTROLLER_KEY=<correctKey>`

**Comment by philiplb** [comment]
I got a

> var "CONTROLLER_KEY" not found in release "f0faab3d-e6a3-4b58-8220-8d0a1d98276e"

When I tried to set it, I got his:

> sirenia cluster in unhealthy state (has no asyncs)

**Comment by josephglanville** [comment]
Ok, please upload debug info with `flynn-host collect-debug-info`.

**Comment by philiplb** [comment]
Sure, mailed them to logs@flynn.io

**Comment by philiplb** [comment]
Hi, backups are broken now:

> mysqldump: Got error: 2005: "Unknown MySQL server host 'leader.mariadb.discoverd' (-2)" when trying to connect
> error dumping mariadb database: error running mariadb export: unexpected command exit status 2

Scaling mariadb down fixed it, backups are working again, as long as the mariadb is down:

```bash
flynn -a mariadb scale mariadb=0,web=0
```

**Comment by philiplb** [comment]
Trying to run flynn-host fix:
> INFO[08-19|19:49:59] found expected hosts                     n=3
> INFO[08-19|19:49:59] ensuring discoverd is running on all hosts
> INFO[08-19|19:49:59] checking flannel
> INFO[08-19|19:49:59] flannel looks good
> INFO[08-19|19:49:59] waiting for discoverd to be available
> INFO[08-19|19:49:59] checking for running controller API
> INFO[08-19|19:49:59] found running controller API instances   n=2
> INFO[08-19|19:49:59] found controller instance, checking critical formations
> INFO[08-19|19:49:59] checking status of sirenia databases
> INFO[08-19|19:49:59] checking for database state              db=postgres
> INFO[08-19|19:49:59] checking sirenia cluster status          fn=FixSirenia service=postgres
> INFO[08-19|19:49:59] found running leader                     fn=FixSirenia service=postgres
> INFO[08-19|19:49:59] found running instances                  fn=FixSirenia service=postgres count=3
> INFO[08-19|19:49:59] getting sirenia status                   fn=FixSirenia service=postgres
> INFO[08-19|19:49:59] cluster claims to be read-write          fn=FixSirenia service=postgres
> INFO[08-19|19:49:59] checking for database state              db=mariadb
> INFO[08-19|19:49:59] checking sirenia cluster status          fn=FixSirenia service=mariadb
> INFO[08-19|19:49:59] no running leader                        fn=FixSirenia service=mariadb
> INFO[08-19|19:49:59] found running instances                  fn=FixSirenia service=mariadb count=0
> INFO[08-19|19:49:59] getting sirenia status                   fn=FixSirenia service=mariadb
> INFO[08-19|19:49:59] getting service metadata                 fn=FixSirenia service=mariadb
> INFO[08-19|19:49:59] getting primary job info                 fn=FixSirenia service=mariadb job.id=Flynn1-2d5eea57-1062-456f-adf5-d2944370401e
> INFO[08-19|19:49:59] getting sync job info                    fn=FixSirenia service=mariadb job.id=Flynn2-fea81cfb-1d29-472b-b1fb-03ddc2350f8c
> INFO[08-19|19:49:59] terminating unassigned sirenia instances fn=FixSirenia service=mariadb
> INFO[08-19|19:49:59] starting primary job                     fn=FixSirenia service=mariadb job.id=Flynn1-7008874e-a8ca-4baf-b6c4-7d8b2c252c84
> INFO[08-19|19:49:59] starting sync job                        fn=FixSirenia service=mariadb job.id=Flynn2-d06e5dfa-6481-4b16-9cf0-4d4b0cfdbbea
> INFO[08-19|19:49:59] waiting for instance to start            fn=FixSirenia service=mariadb job.id=Flynn1-7008874e-a8ca-4baf-b6c4-7d8b2c252c84
19:50:59.864265 host.go:153: timed out waiting for sirenia instance to come up

**Comment by philiplb** [comment]
Hi,
is there any way to make the MariaDB work again? I'd love to develop a small application using it. :)

**Comment by josephglanville** [comment]
@philiplb after scaling down the appliance to 0 it may be difficult to get it started back up again.
Could you post the logs returned by `flynn-host log Flynn1-7008874e-a8ca-4baf-b6c4-7d8b2c252c84` and `flynn-host log Flynn2-d06e5dfa-6481-4b16-9cf0-4d4b0cfdbbea`.

It might be possible to revive it with the data intact, if not I can help you delete the cluster state so that you can start fresh and restore from backup.

**Comment by philiplb** [comment]
Those logs are empty. Actually, there is no data to revive, so I might just wait for the next stable release where I will restore from backup anyway?

**Comment by philiplb** [comment]
After an update to the new stable version v20160918.1, I rechecked mariadb.
Restoring resulted in zero mariadb instances and two web instances.
So I scaled the mariadb instances up to three.
But the mariadb provider is still unhealthy. The logs are empty. I tried to run flynn-host fix, but all mariadb related things are:

INFO[09-19|21:23:14] skipping recovery of db, no state in discoverd db=mariadb

Any clue how I can reanimate mariadb?

**Comment by josephglanville** [comment]
I don't know how you could end up with the log output from `flynn -a mariadb log` being empty.
Technically if there is no state in discoverd scaling up the actual mariadb cluster by provisioning a resource or running `flynn -a mariadb scale mariadb=3` should do the job.

**Comment by philiplb** [comment]
Ah, that was me looking at "log -f" while scaling around. Then nothing happened. :)
Happy days: Scaling down to mariadb=0 and then up again to mariadb=3 fixed it! It made the status healthy and provisioning a DB worked just fine.
Thank you. :)
I'll close this ticket then.
