### ISSUE TITLE
How to push to flynn docker-receive from CI?

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3310]
Is there a possibility to login to docker registry without flynn binary?

I would like to push docker images from my CI after succesful builds to flynn.

**Comment by onnimonni** [comment]
Ok it was really easy:
```
docker login --username=user --password=$AUTH_KEY docker.$CLUSTER_DOMAIN
```

I just needed to enable `--insecure-registry=docker.$CLUSTER_DOMAIN` into docker daemon opts.

**Comment by onnimonni** [comment]
@titanous If I just push new image to flynn with existing image tag should it trigger the new release automatically?

**Comment by onnimonni** [comment]
And how should I figure out the image tag name for existing application?

**Comment by lmars** [comment]
@onnimonni 

> I just needed to enable --insecure-registry=docker.$CLUSTER_DOMAIN into docker daemon opts.

It would be better to configure the Docker daemon to trust the Flynn cluster's CA certificate (see [here](https://github.com/flynn/flynn/blob/master/cli/docker.go#L154-L167) for the instructions for doing that, which are printed when `flynn docker login` fails with a TLS error).

> If I just push new image to flynn with existing image tag should it trigger the new release automatically?

If you push a Docker image directly to the docker-receive app, the image will be stored in the blobstore but it will not be deployed.

When running `flynn docker push`, it first [tags the image and pushes it to docker-receive](https://github.com/flynn/flynn/blob/master/cli/docker.go#L188-L224) but it then [creates a release and deploys it](https://github.com/flynn/flynn/blob/master/cli/docker.go#L226-L281).

So, to answer your question, if you push a new image with the same tag with `flynn docker push` then yes, it will be deployed, but not if you push directly with `docker push`.

> And how should I figure out the image tag name for existing application?

I'm not sure what you are asking, you can see what images you have with `docker images` and then push any of them.

**Comment by onnimonni** [comment]
Thanks @lmars!

Would it be possible to trigger the release also with `docker push`? This would mean that we could use plethora of available tools with flynn immediately.

> When running flynn docker push, it first tags the image and pushes it to docker-receive but it then creates a release and deploys it.

Which kind of curl request I'll need to do send to create a release from the already pushed image?

**Comment by lmars** [comment]
> Would it be possible to trigger the release also with docker push?

It is not possible without re-architecting the current workflow (the docker-receive app is currently pretty simple, it just receives Docker images and uploads them to the blobstore). Given `flynn docker push` can do the deployment, we are unlikely to support this.

> Which kind of curl request I'll need to do send to create a release from the already pushed image?

Doing the deployment with `curl` is possible but it would be quite involved (wait for an artifact create event, construct a valid release configuration, create the release, create a deployment, wait for deployment events). Given all of this is handled by `flynn docker push`, I would strongly suggest using that instead.

**Comment by onnimonni** [comment]
Thanks for these pointers.

I'll just try to create a flynn plugin (containing the flynn binary) for my CI which does the login and push instead.

**Comment by onnimonni** [comment]
And It seems like a good thing that Flynn doesn't immediately trigger the release after docker push because then Flynn can support more complex interconnected docker deploys with Flynnfile in the future. Just to add some wishful thinking.

**Comment by lmars** [comment]
@onnimonni yes, so to clarify the current workflow, the `docker-receive` app receives the Docker image, uploads it to the blobstore and creates an Artifact using the controller API.

This subsequently triggers an Artifact event informing subscribers a new image has been pushed, and the subscriber can then proceed to do something with that image (e.g. in the case of `flynn docker push`, deploy it to a Flynn cluster).
