### ISSUE TITLE
Feature Request: Add javascript dns lookups on dashboard route adding modal

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3311]
We could do dns check in the dashboard javascript to show the user if dns is already set correctly or not.

It could automatically show the needed CNAME records (if domain is not bare domain) or A records (if domain is bare domain).

Javacript DNS requests can be done with webrtc: http://stackoverflow.com/questions/102605/can-i-perform-a-dns-lookup-hostname-to-ip-address-using-client-side-javascript#answer-25962226

If this is not possible with JS we could add function to backend which returns the results of dns lookup.

<img width="757" alt="flynn-route-add-modal" src="https://cloud.githubusercontent.com/assets/5691777/17807414/0aa7d31e-6613-11e6-8b40-5297228e819c.png">

**Comment by titanous** [comment]
We can definitely recommend the CNAME, but there is no reliable way to get a list of all A records that are necessary for an apex domain. For example, Route53 only provides on A record per query when health checks are in use even if there are multiple servers.

**Comment by onnimonni** [comment]
Thanks! In my opinion CNAME is good enough already. But in case it's bare domain we could just ask those from the server then? Just list public IPs of all of the connected flynn nodes?

**Comment by titanous** [comment]
> Just list public IPs of all of the connected flynn nodes?

That isn't available easily currently, either. On AWS the public IPs are not configured locally, we'll have to hit APIs to get them.

**Comment by onnimonni** [comment]
And I can see that with health checking enabled A records are always non-preferred and I can see that you don't want to support those. Luckily few services provide ANAME records ( dnssimple ) or CNAME flattening ( cloudflare ).
