### ISSUE TITLE
Schema for controller release processes object?

### ISSUE THREAD

**Issue by Tyler-Murphy** [flynn/flynn#3312]
https://flynn.io/schema/controller/release

It'd be great to see more information about what goes into the processes part of this... maybe a reference to another definition like some of the other fields have.

```
    "processes": {
      "type": "object"
    },
```

The examples are easy enough to follow, so this doesn't seem like a big deal, but having a complete, authoritative schema would be helpful.

**Comment by jvatic** [comment]
The schema file can be found [here](https://github.com/flynn/flynn/blob/d438311f02afc2863943813cabbaf54a11940189/schema/controller/release.json) and the Go type definition [here](https://github.com/flynn/flynn/blob/d438311f02afc2863943813cabbaf54a11940189/controller/types/types.go#L54-L110). Feel free to submit a PR with an updated schema, though be advised we will be moving to GraphQL soon which will make these schemas obsolete (#2759).

**Comment by titanous** [comment]
We are no longer updating the controller schemas due to the move to gRPC (#3358).
