### ISSUE TITLE
Flynn environment variables

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#333]
It would be useful for jobs to have environment variables like:

* `FLYNN_JOB_ID`
* `FLYNN_APP_ID`
* `FLYNN_RELEASE_ID`

`FLYNN_JOB_ID` would be particularly useful in the example apps (where we currently display the hostname as the ID).

**Comment by archSeer** [comment]
Resolved with https://github.com/flynn/flynn/commit/affbadca222b0cee4fcbd1805fca1d582319531a.
