### ISSUE TITLE
pg_dump blocks exclusive lock for migration, preventing process start

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3331]
We just ran into a scenario where an automated full-cluster backup was running and someone tried to change the blobstore configuration. The blobstore deploy failed with a timeout due to the `LOCK TABLE schema_migrations IN ACCESS EXCLUSIVE MODE` that we do when starting processes that use the `pkg/postgres` migration system.

It looks like `pg_dump` had a shared lock on the `schema_migrations` table that was held while dumping the large objects, which can take quite a while: https://gist.github.com/titanous/8df6b35c52261c94cecdfdefab8363e1

We should figure out how to avoid this, as it could prevent the blobstore from recovering if new instances need to be started while a backup is running.

**Comment by josephglanville** [comment]
`pg_dump` takes and holds `ACCESS SHARE` on all tables that it intends to dump for the duration of the dump process, this is primarily to ensure the tables aren't dropped in the process. I don't think this is avoidable so we need to look at what we can do with regards to the migration system instead.

Namely, would it be safe to use an `EXCLUSIVE` lock in place of an `ACCESS EXCLUSIVE` lock? `EXCLUSIVE` prevents concurrent modification of any kind but doesn't block access to reads and most importantly doesn't conflict with `ACCESS SHARE`, my assumption is yes but I haven't considered all possible reasons why it was written with `ACCESS EXCLUSIVE`.

**Comment by titanous** [comment]
The lock exists to make sure that only one attempt to migrate is made at a time. It doesn't matter how this is accomplished (for example, it seems like an advisory lock would work as well).

**Comment by josephglanville** [comment]
Closed by #3336
