### ISSUE TITLE
Per-container, per-target traffic attribution

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3333]
In AWS (and likely in other environments), some traffic costs money. In order to properly attribute costs to individual teams, we need to keep counts of usage in a fairly fine grained manner. Exposing these via some form of low-impact API, so that our existing monitoring system can poll it, should be sufficient.

**Comment by lmars** [comment]
[Packetbeat](https://www.elastic.co/products/beats/packetbeat) may be useful for this sort of thing, it is written in Go and has [various capturing options](https://www.elastic.co/guide/en/beats/packetbeat/current/capturing-options.html).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
