### ISSUE TITLE
Single node cluster down after restart

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3334]
I restarted a single node via `sudo shutdown -r now` and after reboot it won't come up. Logs from `/var/log/upstart/flynn-host.log` are below. Any guidance would be appreciated!

```
INFO[08-26|12:55:48] request started                          component=host req_id=ef386519-4ea1-4196-9427-ff4fa1d69ed7 method=GET path=/host/jobs client_ip=100.100.89.5
INFO[08-26|12:55:48] request started                          component=host req_id=fede05bb-1a68-4678-a664-622b8ea9307f method=GET path=/host/jobs client_ip=100.100.89.5
INFO[08-26|12:55:48] request completed                        component=host req_id=fede05bb-1a68-4678-a664-622b8ea9307f status=200 duration=50.061954ms
now=2016-08-26T19:55:48+0000 fn=unbind_mounts job.id=flynn-96d84d2a-19f2-4077-a614-3c690a41c6b9 backend=libvirt-lxc at=start
now=2016-08-26T19:55:48+0000 backend=libvirt-lxc fn=unbind_mounts job.id=flynn-96d84d2a-19f2-4077-a614-3c690a41c6b9 at=finish
now=2016-08-26T19:55:48+0000 fn=watch_container job.id=flynn-96d84d2a-19f2-4077-a614-3c690a41c6b9 at=cleanup_mounts status=finish backend=libvirt-lxc
INFO[08-26|12:55:53] request completed                        component=host req_id=ef386519-4ea1-4196-9427-ff4fa1d69ed7 status=200 duration=5.000100379s
INFO[08-26|12:55:53] request started                          component=host req_id=8006e1d7-cc00-4c03-9e95-ec6d7a163310 method=GET path=/host/jobs client_ip=100.100.89.5
EROR[08-26|12:55:57] scheduler is not up                      component=cluster-monitor fn=checkCluster
EROR[08-26|12:55:57] cluster is unhealthy, setting fault      component=cluster-monitor fn=checkCluster
INFO[08-26|12:55:58] request completed                        component=host req_id=8006e1d7-cc00-4c03-9e95-ec6d7a163310 status=200 duration=5.000141565s
INFO[08-26|12:55:58] request started                          component=host req_id=61e2bbe4-e5b8-4fca-b2d1-baaaae4b609b method=GET path=/host/jobs client_ip=100.100.89.5
INFO[08-26|12:56:03] request completed                        component=host req_id=61e2bbe4-e5b8-4fca-b2d1-baaaae4b609b status=200 duration=4.999867031s
INFO[08-26|12:56:03] request started                          component=host req_id=34b8e925-ca31-4d1c-92f7-ef5965b1f79d method=GET path=/host/jobs client_ip=100.100.89.5
```

**Comment by titanous** [comment]
Give it a few more minutes and then check if there is anything new in the logs.

**Comment by kevinob11** [comment]
Will do, thanks!

**Comment by kevinob11** [comment]
It looks like the content of this gist is just repeating every few minutes.

https://gist.github.com/kevinob11/d1c0aae004927bb3b04f57920700cc85

**Comment by josephglanville** [comment]
Looks like the scheduler is having trouble starting, can you collect the debug logs with `flynn-host collect-debug-info` so we can take a look.

**Comment by kevinob11** [comment]
Here you go!

https://gist.github.com/b067e4778dc08685a26f1120bebf7de6

**Comment by lmars** [comment]
@kevinob11 you are hitting against a bug in the scheduler which I pushed a fix for just yesterday (#3329).

To get things running, you will need to purge your flynn-host state database so it doesn't have so many stopped jobs. I have written a Go program which will do this, you can find instructions for running it in the following gist (follow the instructions in the shell script, the Go code is just for reference so you know what the compiled program does):

https://gist.github.com/lmars/cfb46fe104d1c17be8f22acf41c907e9

If this brings your cluster back up ok I would suggest taking a backup and restoring into a newer version of Flynn (you are currently running `v20160218.0` whereas the latest stable is `v20160814.0`).

**Comment by kevinob11** [comment]
The Go program ran successfully, but the cluster still didn't start.

```
now=2016-08-27T17:54:58+0000 fn=watch_container job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e at=change state=exited backend=libvirt-lxc
now=2016-08-27T17:54:58+0000 backend=libvirt-lxc fn=watch_container job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e at=exited status=1
now=2016-08-27T17:54:58+0000 backend=libvirt-lxc at=start fn=waitExit job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e
now=2016-08-27T17:54:58+0000 at=done backend=libvirt-lxc fn=waitExit job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e
now=2016-08-27T17:54:58+0000 job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e backend=libvirt-lxc fn=cleanup at=start
now=2016-08-27T17:54:58+0000 job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e backend=libvirt-lxc fn=unbind_mounts at=start
now=2016-08-27T17:54:58+0000 backend=libvirt-lxc fn=unbind_mounts err="invalid argument" at=unmount file=.containerinit status=error job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e
now=2016-08-27T17:54:58+0000 backend=libvirt-lxc fn=unbind_mounts job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e at=unmount file=resolv.conf status=error err="invalid argument"
now=2016-08-27T17:54:58+0000 fn=unbind_mounts job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e backend=libvirt-lxc at=finish
ERRO[0266] Removing active id tmp-flynn-fc11e28a-5732-4e92-9c5e-5044a711588e
now=2016-08-27T17:54:58+0000 job.id=flynn-fc11e28a-5732-4e92-9c5e-5044a711588e backend=libvirt-lxc fn=cleanup at=finish
EROR[08-27|10:55:07] scheduler is not up                      component=cluster-monitor fn=checkCluster
EROR[08-27|10:55:17] scheduler is not up                      component=cluster-monitor fn=checkCluster
EROR[08-27|10:55:27] scheduler is not up                      component=cluster-monitor fn=checkCluster
INFO[08-27|10:55:29] request started                          component=host req_id=eadf349d-f1d8-4449-9674-9a5bcf23d79d method=GET path=/host/jobs client_ip=70.35.113.79
INFO[08-27|10:55:29] request completed                        component=host req_id=eadf349d-f1d8-4449-9674-9a5bcf23d79d status=200 duration=37.91903ms
INFO[08-27|10:55:31] request started                          component=host req_id=dce9f954-f200-4c11-aff8-952e52ec9c25 method=GET path=/host/jobs client_ip=70.35.113.79
INFO[08-27|10:55:31] request completed                        component=host req_id=dce9f954-f200-4c11-aff8-952e52ec9c25 status=200 duration=34.384887ms
INFO[08-27|10:55:33] request started                          component=host req_id=4b43a415-96b0-496e-bbf0-327235dbf0f3 method=GET path=/host/jobs client_ip=70.35.113.79
INFO[08-27|10:55:33] request completed                        component=host req_id=4b43a415-96b0-496e-bbf0-327235dbf0f3 status=200 duration=31.145143ms
EROR[08-27|10:55:37] scheduler is not up                      component=cluster-monitor fn=checkCluster
```

This is my old cluster, I've already moved to Flynn 1.0, but I brought it back up to do some testing on my old apps to diagnose an issue I'm having.

**Comment by lmars** [comment]
@kevinob11 it's probably best to just boot a fresh cluster, the version is pretty old and we have fixed quite a few resurrection bugs since then.

**Comment by kevinob11** [comment]
Ok, fair enough. Thanks!

**Comment by kevinob11** [comment]
Quick follow up, the reason I brought this up is I moved to a new cluster on Flynn 1.0 recently, when I did my users started noticing more issues with requests failing. I looked in the router logs on a tip from @lmars and found quite a few `net/http: request canceled` errors. I wanted to bring this old machine back up to see if I had those same errors in my router there. I wasn't able to bring the machine back up, but I grepped the /var/log/flynn directory for the same error and didn't see any instances of it. I also added per request logging to my app, I see those requests begin, but then they never complete, and act as if they've been canceled.

Can you think of anything that could be causing this or point me to a good next step in troubleshooting?

Thanks!

**Comment by titanous** [comment]
Are you using HTTPS? Is the client that has this issues Safari?

**Comment by kevinob11** [comment]
Yes to HTTPS and the client is iOS, so yes on Safari.

**Comment by titanous** [comment]
This might be #3261. What version of Flynn are you running? (`flynn-host version`)

**Comment by titanous** [comment]
Also, are the canceled requests for image files? That's another indicator for this issue.

**Comment by kevinob11** [comment]
v20160721.2, so definitely before that went in.

They were just requests to a data api, should have returned json. Requests are GET requests to a simple path + query. Eg`/api/user?ids=1234,12351,1234512,12341,12341234`

**Comment by titanous** [comment]
Hmm, can you see if this happens with the latest stable release (v20160814.0) or a nightly? It's still likely that this is the same pipelining bug or something along similar lines.

**Comment by kevinob11** [comment]
Sure, we were going to spin up a new cluster next weekend anyway, I'll let you know if this works!

**Comment by titanous** [comment]
Great, if you're still having trouble on the latest version, please open a new issue.

**Comment by kevinob11** [comment]
Will do.
