### ISSUE TITLE
digitalocean firewall during flynn install

### ISSUE THREAD

**Issue by defunctzombie** [flynn/flynn#3338]
Could not find this in the documentation, but does `flynn install` setup the firewall on the host correctly when using digitalocean or is that left to the end user to configure?

Related, is there a way to make flynn use the "private" ip network digitalocean provides for node-to-node communication?

**Comment by titanous** [comment]
Yes, a firewall is configured by default when using `flynn install`. So far we have not implemented anything related to "private IPs", as they are accessible to all DigitalOcean users and provide no apparent benefit.

**Comment by defunctzombie** [comment]
@titanous thanks for the quick response! So on digitalocean using `flynn install` would be the recommended approach and correct level of public facing security?

When I add more hosts (after installing flynn on them manuall and using flynn-host) do those firewalls also get configured properly for public facing DO servers?

**Comment by titanous** [comment]
Yes, the defaults are secure. Adding hosts would require manually adding the new nodes to the firewall son the existing cluster (just vanilla iptables). We don't currently have any cluster lifecycle orchestration, so you'd probably want to move to any standard tools that you are familiar with for production.

**Comment by defunctzombie** [comment]
Closing as original question was answered. Hopefully there is a nice way to add more hosts in the future, but Ill go with manual firewall rules for now if I need to add hosts.

**Comment by darkpixel** [comment]
FYI - the 'private IPs' at Digital Ocean are a way of transferring data back and forth between droplets that *DOES NOT* count against your bandwidth.  Seems ideal for cluster communication and traffic redirected between machines.

**Comment by KidkArolis** [comment]
> Yes, the defaults are secure.

I've just used flynn installer on a single DigitalOcean machine. Now I'm trying to figure out the firewall situation. Looking at the `iptables -L` output, I'm a little confused about the second line `ACCEPT     all  --  anywhere             anywhere` which seems like it would open up all traffic publicly. I'm new to `iptables` though so not sure how to interpret this output.

```
root@flynn:~# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  216.58.208.132       anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request
DROP       all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

Is this basically all good and the right ports are opened/closed? Or is there an issue with the installer? Or am I supposed to do something like this: https://philiplb.de/flynn/2016/04/19/flynn-ufw/.

Cheers for an amazing piece of software!
