### ISSUE TITLE
Why Flynn doesn't support small EC2 instances?

### ISSUE THREAD

**Issue by simon0191** [flynn/flynn#3339]
Why Flynn doesn't support small EC2 instances like t2.micro, t2.small, etc ?
https://github.com/flynn/flynn/blob/e4ea5d9e42442bcc0487ff839eceb3f595ac2e55/installer/aws_cluster.go#L24

**Comment by titanous** [comment]
Those instance types are heavily CPU-throttled and/or a small RAM allocation, which results in unpredictable performance and a poor user experience when using Flynn. You are of course free to install Flynn manually on these instance types, but we don't recommend it.

**Comment by simon0191** [comment]
@titanous I would like to run a custom version of the installer that allows me to select a t2.small instance.
I would add t2.small to the options of aws-instance-type-picker https://github.com/flynn/flynn/blob/e4efd66a96a6246f732e3269140602864dfe3bc1/installer/app/src/views/aws-instance-type-picker.js.jsx

And disable the validation here https://github.com/flynn/flynn/blob/e4ea5d9e42442bcc0487ff839eceb3f595ac2e55/installer/aws_cluster.go#L141

1. Do you think that those modifications are enough to get what I want?
2. How can I run the project locally? (I don't have idea of how to run a Go project)

**Comment by titanous** [comment]
Yes, that sounds right. This document covers the development environment: https://flynn.io/docs/development

**Comment by jvatic** [comment]
You can also compile the installer independently (see #3128).

**Comment by simon0191** [comment]
Guys, when I run `script/installer-dev compile` as mentioned in #3128 I get this error:
```
vagrant@flynn:~/go/src/github.com/flynn/flynn$ script/dashboard-dev compile
Unable to find image 'flynn/dashboard-builder:latest' locally
Pulling repository docker.io/flynn/dashboard-builder
Error: image flynn/dashboard-builder:latest not found
```
The steps that I followed was:
1. vagrant up
2. vagrant ssh
3. script/installer-dev compile

What do you think I am doing wrong?

**Comment by jvatic** [comment]
You'll need to build the dependent image. The easiest method is to run `make`.

(Also, note that you ran the `dashboard-dev` script rather than the `installer-dev` one.)

**Comment by simon0191** [comment]
Thanks! it's working like a charm: https://www.slashbox.co
