### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3346]
Can you clarify if fonts installed on the server are accessible within the app. I converting svg to png using phantomjs and the fonts aren't rendering which suggest the installed fonts aren't being used which worked on my previous server setup. That might not be the case but wanted to check.

**Comment by josephglanville** [comment]
The fonts installed on the host will not be available within the container no.
However you could install the fonts during your applications build phase.
If the fonts are available via Apt you could use `https://github.com/ddollar/heroku-buildpack-apt`.
Heroku doesn't seem to have supported behavior for configuring fonts but I have seen suggestions putting TTF fonts in a `.font` directory in the root of the application should work.
I am not sure if this is undocumented Heroku behavior or specific to certain buildpacks so your mileage might vary.

**Comment by dottodot** [comment]
OK thanks for the advise, I'll get it a try and report back just in case anyone else needs this.

**Comment by dottodot** [comment]
I can confirm that adding TTF fonts to a `.fonts` folder does work.
