### ISSUE TITLE
Add error from router if SNI and Host header don't match

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3348]
A SNI/Host header mismatch is never sent by browsers and indicates an improperly configured or implemented non-browser client.

**Comment by imjorge** [comment]
@titanous You want to make sure that when reaching https://github.com/flynn/flynn/blob/master/router/http.go#L470 the `req.Host` value matches the `hello.ServerName` from https://github.com/flynn/flynn/blob/master/router/http.go#L394 ?

**Comment by titanous** [comment]
Yes, that's correct.

**Comment by imjorge** [comment]
@titanous i do not see where we could store `hello.ServerName`, when the TLS is negotiated, such that matches the connection that was accepted and then served when we test `req.Host`. What was your idea?

**Comment by titanous** [comment]
Check if the `TLS` field on the HTTP `Request` is set.

**Comment by imjorge** [comment]
@titanous should that check be guarded by a flag?

**Comment by titanous** [comment]
No.

**Comment by titanous** [comment]
I just realized that this will interfere with HTTP/2 [host coalescing](https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/).
