### ISSUE TITLE
Load average spike on node, probably due to zil_clean processes

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3350]
I've got a cluster with a node which has had a sustained load of 6-8 since the 29th.

```
Warning: Permanently added '10.100.55.213' (ECDSA) to the list of known hosts.
 21:06:39 up 4 days,  3:01,  0 users,  load average: 2.67, 2.60, 2.79

Warning: Permanently added '10.100.55.216' (ECDSA) to the list of known hosts.
 21:06:44 up 4 days,  3:01,  0 users,  load average: 5.79, 6.00, 6.23

Warning: Permanently added '10.100.55.201' (ECDSA) to the list of known hosts.
 21:06:51 up 4 days,  3:01,  0 users,  load average: 3.27, 2.92, 3.17

Warning: Permanently added '10.100.55.217' (ECDSA) to the list of known hosts.
 21:06:53 up 4 days,  3:01,  0 users,  load average: 2.32, 2.41, 2.58

Warning: Permanently added '10.100.55.218' (ECDSA) to the list of known hosts.
 21:07:10 up 4 days,  3:02,  0 users,  load average: 2.61, 2.59, 2.70
```

Process list on the affected node shows a lot of zil_clean processes:
```
$ ps aux | grep -c zil_clean
8976
```

https://bazaarvoice.box.com/s/bwl6lb43hb0y9r2mipjhj8onojlhx73p has tarballs of /var/log/flynn, as collect-debug-info kept hanging. http://zfs-discuss.opensolaris.narkive.com/z6yLSOEf/lots-of-zil-clean-threads seems to describe the same error.

**Comment by josephglanville** [comment]
That number of `zil_clean` processes does seem much too high.
Can you please provide the output of `zfs list` and `dmesg` for the affected node.
If you could also quickly check if there is disk IO happening and CPU usage etc to see if there is anything that stands out, specifically disk utilisation/idle time.

**Comment by temujin9** [comment]
Unfortunately, I cannot do the `zfs list` or the `dmesg`: the cluster was replaced. I will keep an eye out for similar issues, and grab those if I see it.

There did not seem to be any high disk IO or CPU usage correlated, per the metrics dashboard that showed up the problem in the first place.

**Comment by josephglanville** [comment]
Lets leave this here for now, if we see it again we can try debug the actual root cause.
When it next occurs we need the machine/pool intact and probably need to examine it live without it having being rebooted as I think it's unlikely this will persist across reboots.

**Comment by temujin9** [comment]
Well, I have another example. However, nobody is responding to pages on chat.

https://bazaarvoice.box.com/s/sz2m41w1luu3qjwfu51ci7svty7vhidn is the logs. https://bazaarvoice.box.com/s/1lohvgv8n94p9hyghgomxus7bnpsygdu is the output of zfs list and dmesg on each host.

**Comment by temujin9** [comment]
After some investigation with @lmars, we determined that a past version of discoverd (6cea0eb2-26ca-45da-aa9d-da4bd664f04b) had been scaled up. Scaling it down removed at least one source of excessive processes, though it does not appear to reduce the existing `zil_clean` count.

`flynn-host volume gc` does help clean up, on newly launched clusters.

**Comment by temujin9** [comment]
This seems to be resolved without code changes. Closing it for now.
