### ISSUE TITLE
Combine blobstore binaries

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3353]
`flynn-blobstore`, `flynn-blobstore-migrate`, and the new `flynn-blobstore-cleanup` should all be subcommands of a single binary (when separate they are >15MB each).

**Comment by imjorge** [comment]
@titanous using go-docopt and putting `flynn-blobstore-migrate` and `flynn-blobstore-cleanup` on `flynn-blobstore` binary?

```
flynn-blobstore
flynn-blobstore cleanup [-concurrency <concurrency>]
flynn-blobstore migrate [-delete <delete>] [-concurrency <concurrency>] [-prefix <prefix>]
```

**Comment by titanous** [comment]
Yeah, that sounds fine.
