### ISSUE TITLE
How to set custom TLS certificates on Dashboard / Controller

### ISSUE THREAD

**Issue by benosman** [flynn/flynn#3354]
I know LetsEncrypt integration is in the pipeline, but in the meantime I'm doing it semi-manually using terraform and acme.

I have the certificates and have run the following command to set up the default cert.

```flynn -a router env set TLSCERT="$(cat cert-chain.pem)" TLSKEY="$(cat cert-key.pem)"```

This works fine, and when visiting my app using https it shows the LetsEncrypt certificate.

However, when I access ```dashboard.<flynndomain>```, ```controller.<flynndomain>``` or ```git.<flynndomain>``` it still uses the self certified certificate. 

I also tried updating the route for dashboard and controller apps, as follows but still no joy:

```flynn -a dashboard route update http/4aa48f43-11a1-4af2-863c-58c3a5fc6c69 --tls-cert cert-chain.pem --tls-key cert-key.pem```

```flynn -a controller route update http/f78e7dd7-4c2e-44b4-8580-77af51a568c3 --tls-cert cert-chain.pem --tls-key cert-key.pem```

I've searched through the docs and issue queue for similar questions but can't find any thing that works. 

Am I missing something?

Ben

P.S. Thanks for all your work on this project - it's great :)

**Comment by titanous** [comment]
You are doing it correctly, `flynn route update` should be run with new certificates against these apps: `controller`, `gitreceive`, `docker-receive`, `dashboard`

**Comment by benosman** [comment]
Thanks, It now seems to be partially working - so i'm guessing it is a cache issue that means I wasn't seeing the correct cert. 

By the way, Is there a way to run ```route update``` without knowing the uuid of the route first?

**Comment by titanous** [comment]
Not currently, #3185 tracks implementing that. You could test with `curl`, `openssl`, or another browser.

**Comment by benosman** [comment]
Okay, thought as much - Thanks for the quick reply. 

Closing this now as it's all resolved.

**Comment by benosman** [comment]
Hello again,

Following on from the above, since i'm trying to use Lets Encrypt the certificates will need to be updated regularly, after which they will need repinning.

When a new cluster is bootstrapped the log shows the command to add the cluster to the flynn cli:

```
flynn cluster add -p <PIN> default <DOMAIN> <KEY>
```

If I apply the new certificate using the commands above (e.g setting via the routes) is there a way of programmatically retrieving the PIN and KEY for the cluster?

**Comment by titanous** [comment]
You can calculate the pin with:

```text
openssl x509 -inform PEM -outform DER < cert.pem | openssl dgst -binary -sha256 | openssl base64
```

**Comment by benosman** [comment]
Thanks, that works for me.

I know the controller key should stay the same when changing the certificate, but is there a way to retrieve it from the cluster. I've been looking through the code for a way, but I'm still a bit new to golang.

**Comment by titanous** [comment]
You can look in the `certificates` table in the router postgres database:

```text
flynn -a router pg psql
```

**Comment by titanous** [comment]
Sorry, you want the controller key, not the controller certificate key. Run `flynn-host inspect JOB_ID` against a job id from a controller job listed by `flynn-host ps`. It will be an environment variable.

**Comment by evantahler** [comment]
I'm following these steps, but now I get an error: `pinned: the peer leaf certificate did not match the provided pin` when changing the core apps' routes
