### ISSUE TITLE
Feature Request: Specify default TLS cert during bootstrap

### ISSUE THREAD

**Issue by benosman** [flynn/flynn#3355]
Following on from my support request in #3354:

I would like to be able to specify a custom TLS Certificate and Key during the bootstrap phase. This would prevent the self cert being generated, and could also be propagated to all the default apps - e.g. controller, dashboard, git-receive, docker-receive.

I see it being passed in either via ENV variables, or command args: 
```TLSCERT="$(cat cert-chain.pem)" TLSKEY="$(cat cert-key.pem)"```

Would this be something that would be considered?

**Comment by titanous** [comment]
This is supported by specifying these environment variables when doing a bootstrap: https://github.com/flynn/flynn/blob/a29df903dd7c971ff817b1c76ce5b6cf2d7da0ad/bootstrap/manifest_template.json#L165-L167

**Comment by benosman** [comment]
Ah, so it does... Thank you :)
