### ISSUE TITLE
Rapid disk overflow on newly created cluster

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3356]
The disk usage on one machine in this restored cluster leapt to almost 50% shortly after startup (possibly during the restore process), and continued to rise quickly, hitting 100% in less than 24 hours.

https://bazaarvoice.box.com/s/dgwk6zuck0oeqeg7okl2bshbtn7b207p is the /var/log/flynn for all nodes. https://bazaarvoice.box.com/s/bl4uqaxrbgw2nshc9zpd10liuy5rpvj5 has a listing of /var/lib/docker/aufs/mnt/tmp-* on the bad node, per conversation with @lmars on IRC.

**Comment by temujin9** [comment]
/var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev appears to be the source of the on-disk bloating. Notably, its often larger than /var/lib/docker/aufs (though not predictably). We do not yet use https://github.com/flynn/flynn/blob/master/docs/content/production.html.md#custom-zfs-pool (in case it matters for debugging).

**Comment by josephglanville** [comment]
This is the backing ZFS file and it's size is limited so after it reaches that max size it shouldn't consume more space. Ideally you should be using an external ZFS pool, either by partitioning the disk the root filesystem is using or by attaching another disk.
What seems to be happening here is the remainder of the root disk isn't a sufficient amount of space for what needs to be staged on the root filesystem.

Attaching another disk is definitely preferred though as it sounds like the root fs needs more breathing room in your case.

If you can't create the pool on another device you could create the backing file manually as a smaller percentage of the root disk. By creating the zfs pool prior to `flynn-host`startup with `zpool create -f flynn-default /path/to/backing/file` you will avoid the creation of the default pool.

**Comment by lmars** [comment]
It's also worth mentioning that once we land #3100, slugs will be stored in the ZFS pool and only downloaded once, and the temporary filesystem of the jobs will also be in ZFS, which will prevent the large amount of disk usage in `/var/lib/docker` (that directory will no longer be used).

**Comment by temujin9** [comment]
Okay, the root causes of this size explosion (old discoverd container scaled up, creating a lot of volumes which weren't garbage collected) appear to be addressed. 

I'm still concerned that its allowed to max out the root volume; that should probably not happen by default. However, it sounds like the separate volume using `zpool` is your internal solution, and a better one overall (when it works). I will attempt that again, and debug that if it fails again, instead.
