### ISSUE TITLE
Use gRPC for all communication

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3358]
I believe that it makes sense to move from JSON over HTTP APIs to [gRPC](http://www.grpc.io).

Using gRPC will make it easy to have a clear schema of every API endpoint and the input/output parameters, something which we have done partially with JSON schemas but is a pain to maintain because they are disconnected from the actual implementation.

This will allow us to eventually drop traditional RESTish HTTP APIs entirely and have fully type-safe, introspectable, well-defined schematized APIs everywhere. Having these well-defined schemas will help a lot when implementing authorization, as policy can be specified against request parameters and RPC endpoints easily. This should also remove a lot of cruft and inconsistency in our handling of API endpoints and make everything cleaner.

Since the in-place updater isn't currently a recommended update path, we can do this component by component without worrying about backwards compatibility, changing out the APIs completely one at a time.

The components with APIs that should be updated are:
- [ ] discoverd
  - [ ] client API
  - [ ] raft
- [ ] flynn-host
- [ ] scheduler
- [ ] flannel
- [ ] postgres
  - [ ] api
  - [ ] sirenia
- [ ] mariadb
  - [ ] api
  - [ ] sirenia
- [ ] mongodb
  - [ ] api
  - [ ] sirenia
- [ ] redis-api
- [ ] logaggregator
  - [ ] api
  - [ ] log streams (replacing syslog)
- [ ] controller

The main thing that appears to be missing from the gRPC ecosystem is an easy way to introspect and run arbitrary RPCs from a CLI (similar to curl). We should find or create a tool like this to aid in debugging live systems.

**Comment by lmars** [comment]
I think this is a good idea, I do think the CLI is pretty important as I currently use `curl` / `jq` quite a bit during development, and I don't think it would be too much work to implement.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
