### ISSUE TITLE
Scheduler process not running/cluster migration fails

### ISSUE THREAD

**Issue by dbuxton** [flynn/flynn#3362]
On a three-node cluster that apps appear to be running fine on, cluster migration fails:

```
flynn cluster migrate-domain xxx.example.com                           [16:47:38]
Migrate cluster domain from "yyy.flynnhub.com" to "xxx.example.com"? (yes/no): yes
Migrating cluster domain (this can take up to 2m0s)...
scheduler process type failed to start, got down job event
scheduler process type failed to start, got down job event
scheduler process type failed to start, got down job event
scheduler process type failed to start, got down job event
timed out waiting for domain migration to complete
```

Have looked for similar issues and the closest fit I could find was https://github.com/flynn/flynn/issues/2308 - but there are no load issues on the machines.

Any ideas? This is a test cluster and so it would be fine to nuke and start again, but it would be good to understand how to debug an issue like this.

**Comment by lmars** [comment]
@dbuxton please run `sudo flynn-host collect-debug-info` on a host in your cluster and post the resulting gist link here (or email it to logs@flynn.io).

**Comment by dbuxton** [comment]
Worryingly that just hangs on `getting job logs` (tried with `--tarball` too and does the same)

Running `tail -f /var/log/flynn-host.log` on one of the instances and in a different window doing `flynn cluster migrate-domain` I get https://gist.github.com/dbuxton/3564ab9bd1a757b21216a573d6909714 - but not sure if this is the file you'd most want to see.

**Comment by titanous** [comment]
@dbuxton Can you manually tar up `/var/log/flynn` and post a link here or send to logs@flynn.io?

**Comment by dbuxton** [comment]
Done

**Comment by titanous** [comment]
@dbuxton Can you provide the logs from the other two nodes as well?

**Comment by lmars** [comment]
@dbuxton also, what version of Flynn are you running (`flynn-host version`)?

**Comment by lmars** [comment]
(I ask because this may be a scheduler bug I fixed in #3329 where the scheduler fails to start as the `putJobs` channel blocks with >1000 jobs).

**Comment by dbuxton** [comment]
`v20160814.0`

Sounds like you may be right about the bug... Any way of fixing without reinstall? I tried `flynn-host update` but it doesn't complete (probably due to the same bug!)

**Comment by dbuxton** [comment]
(I'll hold off getting logs until you think that they're really necessary)

**Comment by dbuxton** [comment]
Any thoughts on this @lmars ?

**Comment by lmars** [comment]
@dbuxton sorry for not getting back to you.

When you ran `flynn-host update`, did you get an error? Also, were you updating to the nightly version (i.e. updating `/etc/flynn/channel.txt` to contain `nightly` before running the update)?

**Comment by dbuxton** [comment]
Sorry for the delay here.

Closing this as I ended up simply nuking the cluster. My feedback would be that it would help to have a decent place to find all the docs for this stuff...

**Comment by lmars** [comment]
@dbuxton Flynn docs can be found here: https://flynn.io/docs

Is there something specific you would like us to add?

**Comment by dbuxton** [comment]
I think the docs are great as a quickstart guide but it doesn't really give enough information to understand how to debug flynn-host (or even use it AFAICT). 

One interim way of addressing could be to give a bit more of a guide of where the entrypoints are in the code - I found myself looking through the source but found it hard to see how different calls fit together.

**Comment by lmars** [comment]
@dbuxton ok thanks for the feedback, we'll take this into consideration in our next docs push.
