### ISSUE TITLE
Flynn commands don't terminate without manual interrupt (v20160814.0)

### ISSUE THREAD

**Issue by maxim** [flynn/flynn#3366]
I noticed the problem in both `flynn install` (ran from client CLI) and `flynn-host update` (ran on a cluster host) where logs just hang there and you don't get the terminal back. In case of update log just hangs there saying "flynn-host updated successfully" 3 times, meaning it finished updating all 3 hosts in the cluster.

**Comment by titanous** [comment]
`flynn install` is designed to stay running until stopped, it is basically a local web server.

That log message from `flynn-host update` does not mean that it's done, there are a bunch of subsequent steps, how long did you wait for it to finish?

**Comment by maxim** [comment]
@titanous Waited about 10 minutes.

**Comment by titanous** [comment]
Okay, something probably went wrong with the in-place updater, there are still a few bugs, which is why it is not the primary update method that we recommend. Is it still running?

**Comment by maxim** [comment]
I interrupted it and changed channel (it was updating to the same version). Now running update to nightly, and that's taking a while, stuck on success message from 2 of 3 hosts.

**Comment by maxim** [comment]
Looks like this issue is misleading, and occurred for entirely different reasons. I'll close it.
