### ISSUE TITLE
script: Stop flynn-host directly when doing clean install

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3369]
Running the install script with `--clean` tries to stop `flynn-host` via Upstart (see [here](https://github.com/flynn/flynn/blob/master/script/install-flynn.tmpl#L227-L231)), but this won't work if an update has been run because Upstart will no longer be tracking the process (see #2224).

We should take a more direct approach like `killall flynn-host` or grepping `ps` output.

**Comment by titanous** [comment]
This is not an issue with 16.04/systemd, so closing.
