### ISSUE TITLE
Log OOM kills to the containerinit log

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3375]
When the OOM killer kills a task, it is currently only logged to dmesg. There is a notification system that allows a userspace process to get a notification, and we should hook it up in containerinit so that OOM events are visible (in concert with #2669).

https://github.com/torvalds/linux/blob/9395452b4aab7bc2475ef8935b4a4fb99d778d70/Documentation/cgroup-v1/memory.txt#L729
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Resource_Management_Guide/sec-Using_the_Notification_API.html

**Comment by titanous** [comment]
This appears to be built-in to libcontainer already: https://github.com/opencontainers/runc/blob/1e319efa3639a32d07a63e0b11f5a6f8b6aabe06/libcontainer/container_linux.go#L109-L119

We should test both hooks out. The main problem with the OOM hook is it doesn't appear to provide any information about the process that was killed. We can probably solve that by adding separate logging for each child process that exits.

**Comment by josephglanville** [comment]
Logging memory pressure notifications is also probably a good idea. Hopefully we can use both later to indicate to users when they either need to increase memory limits or add more cluster capacity when memory pressure occurs. (as we don't have strict resource based scheduling yet, so memory can be overcommitted).

**Comment by lmars** [comment]
I had a look into this and I don't think containerinit is the right place for it.

In the large amount of cases, jobs are a single process (a child of containerinit) and so if it gets OOM killed, it will exit, containerinit gets a SIGCHLD / wait status and exits itself. Waiting for the OOM notification would either race with that workflow (i.e. between `wait(2)` and the OOM event), or cause a delay when marking the job as done.

It may be better to subscribe to the event in `flynn-host` and just inject the notifications into the app log.

@titanous @josephglanville wdyt?

**Comment by titanous** [comment]
Sounds fine to me.
