### ISSUE TITLE
Is there anything in the setup that would prevent access to cdn images

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3379]
Bit of complicated one this but trying to narrow down where the issue is, as the problem I have doesn't occur locally or on my current server that isn't using flynn.

In my node js app I'm converting svgs to pngs using https://github.com/domenic/svg2png which uses phantomjs to do the conversion.

Within the svg there are references to images that are stored in a cloudinary cdn but these images are not being rendered in the final png so I'm trying to work out why this would be as there are no restrictions on the images themselves, so working if there is anything that would cause this behaviour in Flynn.

Probably not relevant but so you can see what I mean this is an example of an svg I'm trying to convert

https://s3.eu-central-1.amazonaws.com/boxxer/uploads/items/57c46a04f1dc422b002ff291.svg

but the result looks like

https://res.cloudinary.com/dot-to-dot-design/image/upload/f_auto,q_auto,w_600/boxxer_s3/uploads/items/57c46a04f1dc422b002ff291_1472543810612.png

both should look the same.

**Comment by titanous** [comment]
Flynn should not have any impact on this.

**Comment by lmars** [comment]
@dottodot if you run `flynn run bash`, can you fetch the external URLs using `curl`?

**Comment by dottodot** [comment]
Yes that works so it's not an issue there, thanks for the suggestion though. Thinking its going probably some issue with phantomjs so closing.
