### ISSUE TITLE
azure manual install

### ISSUE THREAD

**Issue by pdaniel-frk** [flynn/flynn#3383]
Hello,

I try to install flynn on azure using manual install. I am not usinz the cloud installer. 

After i follow all the steps in the documentation, open all ports inbound and outbound (for test purposes) in azure, i get this error when i try to bootstrap the cluser :

20:46:56.525491 wait-hosts wait-hosts error: bootstrap: timed out waiting for hosts to come up

The following hosts were unreachable:

the debug information cand be found here :

 https://gist.github.com/c7e7f648809b25ac6f6267b47cba28cb

I don;t know what to do next. All the servers are up.

Thx.

**Comment by titanous** [comment]
Can you try deploying again? It might be a transient failure. We'll take a look at the logs.

**Comment by pdaniel-frk** [comment]
I tried using ssh from flynn installer. I have the same error.

**Comment by jvatic** [comment]
@pdaniel-frk You can use the [Azure template the installer uses](https://github.com/flynn/flynn/blob/master/installer/azure_template.go) for launching a cluster for reference if you want a custom stack. Though using the installer to launch it for you would be the easiest option.

**Comment by pdaniel-frk** [comment]
Hello, Thx for the suggestion. My problem is that my company has multiple azure accounts. I want to be able to start 1 machine in one account, another machine in the second account and a third machine in the third account, and install flynn on this machines, in different accounts. This is a budget limitation, being multiple companies under a group.

**Comment by pdaniel** [comment]
Can i see in any way how many machines are online in a cluster? Or can i see if i get network/port errors when my machines are communicating with etcd?

**Comment by titanous** [comment]
Yes, `flynn-host list` will show a list of hosts and their Raft status.

**Comment by pdaniel-frk** [comment]
I did a telnet 

telnet <ip> 1113 to see if i can connect. Ports are open. I really don't understand why the cluster nodes cannot communicate with each other.

**Comment by pdaniel-frk** [comment]
after i executed the bootsrap command  i got

**Comment by titanous** [comment]
From the original log, it looks like flannel is not coming up correctly:

> Error looking up interface 40.117.186.172: No interface with given IP found

What flags did you provide to `flynn-host init`?

**Comment by pdaniel-frk** [comment]
the same problem i get on google compute engine

19:32:42.676590 wait-hosts wait-hosts error: bootstrap: timed out waiting for hosts to come up

The following hosts were unreachable:
        130.211.53.3:1113
        104.155.123.204:1113
        104.199.4.55:1113

**Comment by pdaniel-frk** [comment]
this are all the commands i've executed. The ip's are changed because i recreated the VM's

sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn)

sudo flynn-host init --init-discovery --external-ip=130.211.53.3

sudo flynn-host init --external-ip=104.199.4.55 --discovery https://discovery.flynn.io/clusters/aeb0e134-8c68-4f88-99a2-b21c93a4cb62

sudo flynn-host init --external-ip=104.155.123.204 --discovery https://discovery.flynn.io/clusters/aeb0e134-8c68-4f88-99a2-b21c93a4cb62


sudo start flynn-host

sudo \
    CLUSTER_DOMAIN=mysubdomain \
    flynn-host bootstrap \
    --min-hosts 3 \
    --discovery https://discovery.flynn.io/clusters/aeb0e134-8c68-4f88-99a2-b21c93a4cb62

**Comment by pdaniel-frk** [comment]
So, i have some results.

After @titanous comment, i had an idea. In azure i configured the virtual machines to have the same public ip and private ip. After i did that, everything worked. So it seems there is a problem with flannel and multiple hosts that are not in the same network. Also the remote hosts do not have the public ip on a network interface attached to the vm. This is a problem i believe with all the iaas providers.

**Comment by josephglanville** [comment]
Currently Flynn doesn't make a distinction between advertised addresses and listen addresses in all system services and as such needs the 2 to be equal. This means that nodes should be reachable from other nodes by the addresses they are listening on.
I recommend deploying Flynn on a single private network. If you need geo-redundancy deploy multiple clusters.
