### ISSUE TITLE
Standardize logging

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#34]
Components are using some combination of `fmt`, `log`, `grohl`, and martini request logging. We want to standardize on using [`log15`](https://github.com/inconshreveable/log15) everywhere.

**Comment by lmars** [comment]
We have begun to use `log15` which has been good so far, but I think we need some consensus on the format of the messages and what context is useful to add.

My current thoughts are:

* Components should have a global `logger` with an `app` context:

    `var logger = log15.New("app", "deployer")`

* Loggers should include a `fn` context to help identify where a log message came from:

    `log := logger.New("fn", "HandleJob")`

* Info messages should describe what action is being taken, or what action was taken:

    `log.Info("creating controller client")`
    `log.Info("performing deployment")`
    `log.Info("deployment complete"`)

* Error messages should generally take the form `error ACTION` and include an `err` context:

    `log.Error("error creating controller client", "err", err)`

There is also a convention to include an `at` context which I have not been doing so far, so we should decide whether that provides added benefit when reading logs / finding where logs came from.

**Comment by titanous** [comment]
This is all good, I agree that dropping `at` makes sense.
