### ISSUE TITLE
install-flynn appears to reset zpool 

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3400]
Attempting to precreate the zpool as suggested in several other tickets does not work as advertised.

After everything is installed, checking `zpool list` outputs the zpool Flynn comes with:

```
  pool: flynn-default
 state: ONLINE
  scan: none requested
config:

        NAME                                                        STATE     READ WRITE CKSUM
        flynn-default                                               ONLINE       0     0     0
          /var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev  ONLINE       0     0     0

errors: No known data errors
```

https://bazaarvoice.box.com/s/t4nz9le56u9frhqgywoa6tr3dzn60adv has debug-info and the init logs which show the attempt, including several `zpool list` outputs which show respectively the pool created before install, and then missing after.

I strongly suspect that the `ubuntu-zfs` package is somehow conflicting with / superseding `zfs-fuse`.

**Comment by titanous** [comment]
What is the full `zpool create` command that you are running and it's output?

**Comment by temujin9** [comment]
Both of those are visible in the host init.

**Comment by titanous** [comment]
Yeah, it looks like you are installing `zfs-fuse` first and then running `zpool create` using it which is almost certainly screwing things up, instead you drop that package and run the flynn installer and then the `zpool create` command.

**Comment by lmars** [comment]
> run the flynn installer and then the zpool create command

FYI as part of #3100, images will in future be stored in the zpool, meaning you will need to set up the zpool before running the installer as it will download images into the zpool.

Could you instead just install the `ubuntu-zfs` package, or do you specifically need `zfs-fuse`?

**Comment by temujin9** [comment]
@lmars There we have a chicken-and-egg problem: ubuntu-zfs is not available for installation until your installer script runs.

**Comment by temujin9** [comment]
@titanous That appears to have done it. 

So:
- Any chance you could update the installer to take the device ZFS should initialize as a parameter, so we don't have to worry about that chicken-and-egg problem?
- Failing that: where does `ubuntu-zfs` come from, exactly?

**Comment by titanous** [comment]
> Any chance you could update the installer to take the device ZFS should initialize as a parameter, so we don't have to worry about that chicken-and-egg problem?

Yeah, this is probably a reasonable thing to do.

> Failing that: where does `ubuntu-zfs` come from, exactly?

https://github.com/flynn/flynn/blob/d15df319d7316ee5d4a25f39b85aec6179c6d85f/script/install-flynn.tmpl#L120-L144

**Comment by temujin9** [comment]
Opened an issue for that; closing this, as I have a workaround in place.
