### ISSUE TITLE
flynn usage questions

### ISSUE THREAD

**Issue by pdaniel-frk** [flynn/flynn#3402]
Hello,

I have some questions regarding flynn.

1. Mongo Provider can be run in the cluster? I tried to scale up the mongodb but every time i close my leader machine, mongo goes down. 
2. How can i setup flynn to use my internal git? I don't have my projects on github, i have a private git repository (gogs) exposed over internet. The flynn remote command is the sollution? I din't managed to setup a private repository project using it.

**Comment by josephglanville** [comment]
The MongoDB provider works for both single node and clustered deployments.

Flynn doesn't care where your repository is hosted unless you are using the dashboard to deploy it.
To get your app setup with Flynn clone it locally and then run `flynn create <name>`
This will create a git remote that will point at your Flynn cluster.
Then you can run `git push flynn master` to deploy your app.

**Comment by pdaniel-frk** [comment]
Can you tell me how i can setup mongodb to run in the cluster? I need to scale it ? How does flynn decides how to scale apps and providers in the cluster? If i have let's say 3 virtual machines, and i want to scale mongodb to have an instance run on every VM, i only need to say something like flynn -a mongodb scale mongodb=3?

**Comment by josephglanville** [comment]
You shouldn't run scale commands directly on the database appliances, simply provisioning a resource for an app will take care of scaling up the database. The scheduler will attempt to place all of the appliance jobs on different hosts.

**Comment by pdaniel-frk** [comment]
Ok, thx. It seems i have some problems with the mongodb and mariadb deployments. I've opened a new issue. 

https://github.com/flynn/flynn/issues/3403

**Comment by pdaniel-frk** [comment]
Another question. How can i check ho many hosts are online? How many hosts flynn see online. Let's say a restart a host. How can i be sure that the host is still available to the cluster?

**Comment by josephglanville** [comment]
`flynn-host list` provides a realtime view of which peers are currently up and registered with `discoverd`.

**Comment by pdaniel-frk** [comment]
Yes, thx, i found it. 

Do you have any idea if this problem is being investigated?

https://github.com/flynn/flynn/issues/3383

I can deploy flynn only doing the hack described in my comment. Does flynn also supports weave instead of flannel? Maybe it is a flannel problem or maybe we need to pass some more configs params to flannel. I've seen some issues open on flannel github regarding multi node deployment.
