### ISSUE TITLE
Offer Prometheus Compatible Metrics

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3414]
Hi,
we use [Prometheus](https://prometheus.io/docs/instrumenting/exposition_formats/) for monitoring various things: Machines, Apache, MySQL, custom, project dependend metrics, etc..

In order to monitor our cluster, it would be very helpful if Flynn could offer some compatible metrics. Each Flynn component could expose some metrics actually.

For example, the router metrics could be similar to the [Apache](https://github.com/neezgee/apache_exporter) ones, but with a label for each requested application.

The scheduler could expose the uptime of each app as a label maybe?

The blobstore the amount of stored objects and their size.

The logaggregator the amount of logged lines, maybe with a label for each log level.

etc., the sky is the limit.

Writing a metrics exporter isn't hard:
https://prometheus.io/docs/instrumenting/writing_exporters/
https://prometheus.io/docs/instrumenting/exposition_formats/

I think this would put Flynn in a very nice position to figure out, what's going on in the cluster. And if each component could offer some metrics, it could replace the current status application with a much more powerful system.

What's currently possible with the [node_exporter](https://github.com/prometheus/node_exporter): https://gist.github.com/philiplb/b55cc99a3717ce0d8d3060edd07db2ce

**Comment by lmars** [comment]
Related #201.

**Comment by philiplb** [comment]
A comment towards #201: 
[When does it not fit?](https://prometheus.io/docs/introduction/overview/#when-does-it-not-fit?)

 

> Prometheus values reliability. You can always view what statistics are available about your system, even under failure conditions. If you need 100% accuracy, such as for per-request billing, Prometheus is not a good choice as the collected data will likely not be detailed and complete enough. In such a case you would be best off using some other system to collect and analyse the data for billing, and Prometheus for the rest of your monitoring.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
