### ISSUE TITLE
Using python 3.4 in runtime.txt causes an error

### ISSUE THREAD

**Issue by BeOleg** [flynn/flynn#3420]
`Requested runtime (python-3.4.3) is not available for this stack (cedar-14).`

**Comment by titanous** [comment]
Try `python-3.5.2`

**Comment by BeOleg** [comment]
Same out come :(

**Comment by lmars** [comment]
@BeOleg did you commit the change to `runtime.txt`? I am able to successfully use `python-3.5.2`:

```
$ cat runtime.txt 
python-3.5.2

$ git push flynn master
...
-----> Building python...
-----> Python app detected
-----> Installing python-3.5.2
       $ pip install -r requirements.txt
...
```

Can you post the full output of your `git push`?

**Comment by lmars** [comment]
Interestingly, I can also use `python-3.4.3`:

```
$ cat runtime.txt 
python-3.4.3

$ git push flynn master
...
-----> Building python...
-----> Python app detected
-----> Installing python-3.4.3
       $ pip install -r requirements.txt
...
```

What version of Flynn are you running? (run `flynn-host version` on a host in your cluster)
