### ISSUE TITLE
Vagrant demo: Can't proceed after step "Install certificate"

### ISSUE THREAD

**Issue by adri** [flynn/flynn#3422]
When I try out the vagrant box, I'm not able to continue after the "install certificate" step.
I'd love to give flynn a try but this blocks me. Maybe you have an idea? 
I researched other issues but the suggested solutions didn't resolve in different behavior.
### Steps to reproduce
1. Follow the installation steps under https://flynn.io/docs/installation/vagrant
   Please see the following GIF (sorry it takes a bit to import the box):
   ![flynn-install-cert-1](https://cloud.githubusercontent.com/assets/133832/18808440/10d71698-8263-11e6-8937-051725919020.gif)
2. Download, open and install the certificate like described on http://dashboard.demo.localflynn.com/installcert
   Please see the GIF. I also closed and reopened Safari.
   ![flynn-install-cert-2](https://cloud.githubusercontent.com/assets/133832/18808445/49516276-8263-11e6-82b0-23e87f4953ed.gif)
### Actual Result

I get redirected to the http://dashboard.demo.localflynn.com/installcert page again after adding the certificate to my keychain.
### Expected Result

Proceeding to another page or some information how to proceed after trusting the certificate.
### Notes

MacOS Sierra 10.12
Vagrant 1.7.4
Safari 10.0
fish 2.2.0

**Comment by titanous** [comment]
This is almost certainly Safari 10/macOS Sierra, we'll get that fixed up. For now, Firefox should work.

**Comment by adri** [comment]
I also tried chrome with the same result. Let me check in Firefox.

**Comment by jvatic** [comment]
I was unable to reproduce the issue with Safari 10 or Chrome 53 on macOS Sierra.

**Comment by adri** [comment]
Firefox works! They have their own certificate management, I guess it's related to the macOS Keychain. Any tips how to narrow down the issue?

**Comment by jvatic** [comment]
Are you using the stable or preview version of macOS Sierra?

**Comment by adri** [comment]
I'm using the stable version. Didn't install the preview version.
<img width="171" alt="screen shot 2016-09-24 at 16 56 20" src="https://cloud.githubusercontent.com/assets/133832/18809293/d71bcd76-8277-11e6-93ca-78d7fd4c614f.png">

**Comment by jvatic** [comment]
That's apparently the same version I'm using. One subtle detail which may be significant is in your screencast the icon to the left of the certificate name in the keychain list doesn't change to the trusted icon although it does state that it is trusted when you select it again. The icon does change (after a second or two) when I go through this flow. Is there another machine you can try this on with the same macOS version?

**Comment by adri** [comment]
On another mac with the preview version of macOS Sierra it works! I'll try to update in the coming days to the stable version and retest.

The icon change is related to the search. When I search again for `flyn` in the Keychain Access app, the icon updates.

**Comment by schappim** [comment]
I can confirm that I can replicate this in Safari and Chrome (sorry on my phone so can't give you versions). @adri which beta are you talking about? 10.12.1 beta 4?

**Comment by mattstrayer** [comment]
Can confirm running the Sierra 10.12.1 Beta (16B2548a) no browser works. (Firefox, Chrome, or Safari) for the cert install. 

May try downgrading to stable Sierra. Anyone happen to know if that can be done without doing a clean install?

**Comment by mattstrayer** [comment]
Updating to the stable Sierra 12.1 release, cleaning out all flynn items in the keychain, updating flynn to the most current version, installing, "always trusting", and then restarting the computer allowed me to finally access the dashboard.

**Comment by janniks** [comment]
Still not fixed 😕
Same issue with current version _(fresh install)_ and fresh DigitalOcean ubuntu droplet (16.04 x64)

Neither Safari, Chrome, nor Firefox worked _(all latest versions)_
Will try a reboot later, but it's hard to choose Flynn as PaaS with these kind of problems already during setup...
