### ISSUE TITLE
Launch of flynn cluster failed

### ISSUE THREAD

**Issue by lwoodson** [flynn/flynn#3423]
We had a failed cluster creation at Bazaarvoice today 

https://gist.github.com/anonymous/63a16e6ef39f872f26c12250cd9f5c8d

Will be trying to get a new cluster up quickly as opposed to diagnosing this cluster.

**Comment by lwoodson** [comment]
Also https://gist.github.com/anonymous/615556d238cdbae85921668d493c8793

**Comment by lwoodson** [comment]
Here are some additional cloud init logs that might have some details about the failure https://bazaarvoice.box.com/s/y1mssr07w20wscyb8p6bd0zlmhu86w8f

**Comment by josephglanville** [comment]
Root cause of this failure was `flannel` unsuccessfully setting metadata in `discoverd`:
```
2016/09/24 17:44:03 error creating discoverd service metadata: unknown_error: Something went wrong
```

There is perhaps a retry we are missing here.

**Comment by lmars** [comment]
The flannel error was in a call to `service.SetMeta` which failed on the server with `ErrNoKnownLeader`:

```
t=2016-09-24T17:44:03+0000 lvl=eror msg="discoverd: no known leader" component=discoverd req_id=6094c2fb-e328-4457-b962-8d8bca335979
t=2016-09-24T17:44:03+0000 lvl=info msg="request completed" component=discoverd req_id=6094c2fb-e328-4457-b962-8d8bca335979 method=PUT path=/services/flannel/meta client_ip=10.100.39.229 status=500 duration=172.599µs
```

Given any request which receives that error hasn't been processed by the Raft cluster, I wonder if we should retry all requests which return that error?

@josephglanville @titanous thoughts?

**Comment by josephglanville** [comment]
If we return 503 instead of 500 on `ErrNoKnownLeader` is probably the right move, this will indicate it as retriable to the discoverd client code and also have the client try attempt a different server. This will also be useful during net splits.

**Comment by titanous** [comment]
This looks related to #3318.
