### ISSUE TITLE
Couldn't find any package by regex 'linux-headers-3.2.34-30'

### ISSUE THREAD

**Issue by shankardevy** [flynn/flynn#3428]
I tried to install flynn on a new server running ubuntu 14.04 and I got this error. The server is running on ARM processor.

```
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package linux-headers-3.2.34-30
E: Couldn't find any package by regex 'linux-headers-3.2.34-30'
[1;31m===> 12:36:31.893 ERROR: failed to run "apt-get install -y linux-headers-3.2.34-30", exit status 100[0m
Error: Process exited with status 1
```

**Comment by shankardevy** [comment]
I also got the same error trying to install it on a Intel VPS  with ubuntu 14.04, so I believe it's not due to ARM processor.

**Comment by josephglanville** [comment]
This means there isn't a headers package available for the currently running kernel with the configured apt sources.
Your VPS is likely not running stock Ubuntu 14.04.
Your best bet is to find a way to run fully stock Ubuntu, failing that installing the stock kernel and headers is likely good enough.

**Comment by lmars** [comment]
@shankardevy are you using a stock Ubuntu kernel as mentioned in the [installation docs](https://flynn.io/docs/installation/manual)? Also, Flynn doesn't currently support ARM (see #1965).
