### ISSUE TITLE
Git credentials required when pushing to flynn master?

### ISSUE THREAD

**Issue by aghasoroush** [flynn/flynn#3431]
Hi,

I'm using windows and when trying to run : git push flynn master, a pup up window opens and I have to enter the git credentials but always there is an error with this title : remote: Authentication required
What's this problem ?!

git --version: git version 2.8.1.windows.1
flynn version: v20160926.0
Microsoft Windows [Version 10.0.10240]

**Comment by jvatic** [comment]
Possible duplicate of #3214?

**Comment by aghasoroush** [comment]
@jvatic No. But the problem still exists :)

**Comment by jvatic** [comment]
You shouldn't have to enter the credentials (this should be taken care of via a git helper). [Here's an IRC discussion with a similar issue](https://botbot.me/freenode/flynn/2016-09-23/?msg=73512637&page=1), does pressing the escape key when prompted for credentials work?

**Comment by aghasoroush** [comment]
@jvatic Thanks man ! Pressing escape works like a charm.
