### ISSUE TITLE
"Add external route" from GUI is not sticky

### ISSUE THREAD

**Issue by ddemaree** [flynn/flynn#3433]
I have external TCP routes set up for both MariaDB and Postgres (originally created from the CLI), but the GUI seems not to know that—the "Create external route for provider" button is still displayed for each of them. If I click the button, it acknowledges that the route exists and will let me see the external connection info, but on refresh or state change it'll forget the external route again.

External access appears to work no matter what, this is just a GUI consistency issue afaik.

**Comment by michaelyork** [comment]
+1, observed as well in latest stable release.

Looks like a new port is generated each time "add external route" is hit too. Doesn't seem great. :(

**Comment by michaelyork** [comment]
@jvatic Any issue here if multiple routes were generated by having accidentally re-created them? Will they stick around following a cluster backup/restore?

**Comment by jvatic** [comment]
You can remove any duplicate routes via the CLI, for example:

```
$ flynn -a postgres route
ROUTE     SERVICE   ID                                        STICKY  LEADER  PATH
tcp:3050  postgres  tcp/367504d6-e5d8-4e8d-9857-e3144ac7011d          true
$ flynn -a postgres route remove tcp/367504d6-e5d8-4e8d-9857-e3144ac7011d
Route tcp/367504d6-e5d8-4e8d-9857-e3144ac7011d removed.
```

Otherwise they will persist across a backup/restore.

**Comment by michaelyork** [comment]
Hmm, works for postgres but doesn't seem to work for redis.

```
➜  ~ flynn -a redis route   
ROUTE  SERVICE  ID  STICKY  LEADER  PATH
```

I definitely do have external routes registered / working though. Just tested one now.

**Comment by jvatic** [comment]
Redis is setup a bit differently and each instance has it's own app on which the route is created:

```
$ flynn apps | grep redis
ba43d727-f0aa-464c-84f0-012fef5978d0  redis-7a51d08f-5f9d-403b-990e-df114b3a99a7
1b29ed70-df17-41d0-ae3b-f555fe2eff69  redis-2d8f48a7-e7c1-42c0-a80d-868ef926c15a
0b5f91b1-8a26-4cc1-8682-b03a36bcba74  redis
$ flynn -a redis-7a51d08f-5f9d-403b-990e-df114b3a99a7 route
ROUTE     SERVICE                                     ID                                        STICKY  LEADER  PATH
tcp:3427  redis-7a51d08f-5f9d-403b-990e-df114b3a99a7  tcp/8ffbf3f1-da95-4faa-be28-86158553e580          true
$ flynn -a redis-7a51d08f-5f9d-403b-990e-df114b3a99a7 route remove tcp/8ffbf3f1-da95-4faa-be28-86158553e580
Route tcp/8ffbf3f1-da95-4faa-be28-86158553e580 removed.
```

**Comment by michaelyork** [comment]
Awesome, that did the trick. Thank you!
