### ISSUE TITLE
Cluster has become unresponsive

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3434]
This happen whilst trying to push an update, I didn't get any errors i just got stuck half way through. Now flynn commands don't work and I don't think `flynn-host collect-debug-info` is working either as that been sat on `getting scheduler state` for 30 mins.

**Comment by dottodot** [comment]
Dashboard it also showing no apps and none of the pages work.

**Comment by lmars** [comment]
@dottodot when you say "trying to push an update", do you mean running `flynn-host update` or pushing your own app? It may be useful to come into #flynn in IRC freenode so we can help you debug the issue.

**Comment by lmars** [comment]
After debugging in IRC we found that all postgres queries by the controller were blocking. Here is a stack trace from one of the controller web jobs:

https://gist.github.com/dottodot/054a6b74486b4e33ecb24d5547980dcf

Then, due to #1920, the schedulers were also blocked doing queries to the controller, and external requests were timing out via the router.

We killed the controller web and scheduler jobs and ran `flynn-host fix` but the new controller web job just hung again:

```
INFO[09-27|16:55:50] found expected hosts                     n=3
INFO[09-27|16:55:50] ensuring discoverd is running on all hosts 
INFO[09-27|16:55:50] checking flannel 
INFO[09-27|16:55:50] flannel looks good 
INFO[09-27|16:55:50] waiting for discoverd to be available 
INFO[09-27|16:55:50] checking for running controller API 
INFO[09-27|16:55:50] checking status of sirenia databases 
INFO[09-27|16:55:50] checking for database state              db=postgres
INFO[09-27|16:55:50] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[09-27|16:55:50] found running leader                     fn=FixSirenia service=postgres
INFO[09-27|16:55:50] found running instances                  fn=FixSirenia service=postgres count=3
INFO[09-27|16:55:50] getting sirenia status                   fn=FixSirenia service=postgres
INFO[09-27|16:55:50] cluster claims to be read-write          fn=FixSirenia service=postgres
INFO[09-27|16:55:50] checking for database state              db=mariadb
INFO[09-27|16:55:50] skipping recovery of db, no state in discoverd db=mariadb
INFO[09-27|16:55:50] checking for database state              db=mongodb
INFO[09-27|16:55:50] skipping recovery of db, no state in discoverd db=mongodb
INFO[09-27|16:55:50] checking for running controller API 
INFO[09-27|16:55:50] killing any running schedulers to prevent interference 
INFO[09-27|16:55:50] no controller web process running, getting release details from hosts 
INFO[09-27|16:55:50] starting controller web job              job.id=cluster4-6eb46a53-6027-4978-b2f8-e0a649508962 release=b71e07c3-eb81-4f87-b020-8a45db9d1aa9
INFO[09-27|16:55:50] waiting for job to start 
16:56:50.916245 host.go:153: discoverd: timed out waiting for instances
```

After sending SIGQUIT and getting the stack trace, we saw that web job was stuck trying to [lock the schema table](https://github.com/flynn/flynn/blob/master/pkg/postgres/migrate.go#L51).

We then connected to the controller database and tried to list the locks with `SELECT relation::regclass, * FROM pg_locks WHERE NOT GRANTED;` but that hung, and hitting CTRL-C  printed `Cancel request sent` but the shell was not returned. We killed that job, got another psql shell and tried `SELECT * FROM pg_stat_replication` but that also hung.

I don't know why postgres is hanging in this way, so rather than making things worse I will defer to @jpg / @titanous to provide some insight / suggestions on how to get things back to normal.

Apps are still running in the cluster but there are no controller scheduler or web jobs.

Here are the commands we ran to get a pg shell for the controller:

```
$ image="$(grep -oP "https?://.*\?name=flynn/postgresql&id=\w+" /etc/flynn/bootstrap-manifest.json | uniq)"

$ flynn-host run "$image" /usr/bin/env $(flynn-host inspect cluster4-6eb46a53-6027-4978-b2f8-e0a649508962 | grep -F 'ENV[PG' | sed -r 's/ENV\[(.*)\]\s+(.*)/\1=\2/' | xargs) psql
```

Once the database is fixed, `flynn-host fix -n 3` should bring the controller web and scheduler jobs back online.

IRC conversation: https://botbot.me/freenode/flynn/2016-09-27/?msg=73766380&page=1

**Comment by dottodot** [comment]
Are you able to advise on this, really need to send some updates to my apps and completely stuck at the moment.

**Comment by titanous** [comment]
I'd suggest killing all controller jobs (types `web`, `scheduler`, and `worker`), and running `flynn-host fix -n 3` again.

**Comment by dottodot** [comment]
so doing `flynn-host stop` on each job id or is there a quicker way of doing it?

**Comment by titanous** [comment]
Yeah, that's the best way to do it.

**Comment by dottodot** [comment]
Ok just done some and stop the dashboard and that hasn't come back and none of the other jobs I stopped have come back either. I worried that if I carry on there will be nothing working.

**Comment by titanous** [comment]
The dashboard uses the controller API, as long as you only stop the controller apps, nothing more should stop working, as the controller was already broken.

**Comment by dottodot** [comment]
And just confirmed on a non critical app, once stopped that it doesn't recover.

**Comment by dottodot** [comment]
There aren't any controller apps showing.

**Comment by titanous** [comment]
Yes, recovery has been broken since the controller broke. What is the output of `flynn-host fix -n 3`?

**Comment by dottodot** [comment]
INFO[09-29|14:09:14] found expected hosts                     n=3
INFO[09-29|14:09:14] ensuring discoverd is running on all hosts 
INFO[09-29|14:09:15] checking flannel 
INFO[09-29|14:09:16] flannel looks good 
INFO[09-29|14:09:16] waiting for discoverd to be available 
INFO[09-29|14:09:16] checking for running controller API 
INFO[09-29|14:09:16] checking status of sirenia databases 
INFO[09-29|14:09:16] checking for database state              db=postgres
INFO[09-29|14:09:16] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[09-29|14:09:16] no running leader                        fn=FixSirenia service=postgres
INFO[09-29|14:09:16] found running instances                  fn=FixSirenia service=postgres count=4
INFO[09-29|14:09:16] getting sirenia status                   fn=FixSirenia service=postgres
INFO[09-29|14:09:16] getting service metadata                 fn=FixSirenia service=postgres
INFO[09-29|14:09:16] getting primary job info                 fn=FixSirenia service=postgres job.id=cluster6-72a405de-f3cd-4bf6-9cab-32449482dc14
INFO[09-29|14:09:16] getting sync job info                    fn=FixSirenia service=postgres job.id=cluster4-5399e12c-074f-4118-a9c3-07777e968199
INFO[09-29|14:09:16] terminating unassigned sirenia instances fn=FixSirenia service=postgres
INFO[09-29|14:09:26] starting primary job                     fn=FixSirenia service=postgres job.id=cluster6-62171614-b2fa-4cf5-a5f1-12380da9f1cf
INFO[09-29|14:09:26] starting sync job                        fn=FixSirenia service=postgres job.id=cluster4-458081e8-deab-4dfd-ab97-ad051281f58c
INFO[09-29|14:09:26] waiting for instance to start            fn=FixSirenia service=postgres job.id=cluster6-62171614-b2fa-4cf5-a5f1-12380da9f1cf
14:10:26.617122 host.go:153: timed out waiting for sirenia instance to come up

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug-info` and post the log here.

**Comment by dottodot** [comment]
That just hangs

**Comment by titanous** [comment]
Okay, please run the fix command again, and if it doesn't work, collect the logs in `/var/log/flynn` on each host and email them or a link to them to logs@flynn.io

**Comment by titanous** [comment]
And if fix doesn't work, post the output here.

**Comment by dottodot** [comment]
same again, i'll get the logs over to you

INFO[09-29|14:25:30] found expected hosts                     n=3
INFO[09-29|14:25:30] ensuring discoverd is running on all hosts 
INFO[09-29|14:25:32] checking flannel 
INFO[09-29|14:25:32] flannel looks good 
INFO[09-29|14:25:32] waiting for discoverd to be available 
INFO[09-29|14:25:32] checking for running controller API 
INFO[09-29|14:25:32] checking status of sirenia databases 
INFO[09-29|14:25:32] checking for database state              db=postgres
INFO[09-29|14:25:32] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[09-29|14:25:32] no running leader                        fn=FixSirenia service=postgres
INFO[09-29|14:25:32] found running instances                  fn=FixSirenia service=postgres count=6
INFO[09-29|14:25:32] getting sirenia status                   fn=FixSirenia service=postgres
INFO[09-29|14:25:32] getting service metadata                 fn=FixSirenia service=postgres
INFO[09-29|14:25:32] getting primary job info                 fn=FixSirenia service=postgres job.id=cluster6-4037ef46-5b5e-42ba-87cc-a78a8d556ce7
INFO[09-29|14:25:32] getting sync job info                    fn=FixSirenia service=postgres job.id=cluster4-5399e12c-074f-4118-a9c3-07777e968199
INFO[09-29|14:25:32] terminating unassigned sirenia instances fn=FixSirenia service=postgres
INFO[09-29|14:26:02] starting primary job                     fn=FixSirenia service=postgres job.id=cluster6-c4b8a77b-fef4-42ea-8409-158c4894b145
INFO[09-29|14:26:02] starting sync job                        fn=FixSirenia service=postgres job.id=cluster4-f3060481-c71b-4a5a-8e7d-14513e6bfb94
INFO[09-29|14:26:02] waiting for instance to start            fn=FixSirenia service=postgres job.id=cluster6-c4b8a77b-fef4-42ea-8409-158c4894b145
14:27:02.796454 host.go:153: timed out waiting for sirenia instance to come up

**Comment by dottodot** [comment]
logs have been sent

**Comment by titanous** [comment]
Please also provide the output of `flynn-host ps -a` and `flynn-host version`.

**Comment by dottodot** [comment]
v20160811.0

https://gist.github.com/dottodot/00ef71d60e4481f8cd43142de726adc3

**Comment by titanous** [comment]
The root cause is this error from discoverd on the log labelled `cluster3`:

> raft: Failed to append to logs: write /data/raft.db: no space left on device

**Comment by dottodot** [comment]
so why is there so much difference in disk usage between different node? Also I thought the garbage collection issue had been resolved.

Is there a way for me to free up some space, I can remember  if there is a way to do it.

**Comment by dottodot** [comment]
just tried https://gist.github.com/lmars/6d072bc88c3a4c9f87d2 and that didn't do anything

**Comment by titanous** [comment]
Please post the output of `sudo zfs list` on each host.

**Comment by dottodot** [comment]
```
root@cluster4:~# sudo zfs list
NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
flynn-default                                       23.5G  15.0G    19K  /flynn-default
flynn-default/5025e2ad-f8c9-4a63-982f-febdb7bdd606  6.65M  15.0G  6.65M  /var/lib/flynn/volumes/zfs/mnt/5025e2ad-f8c9-4a63-982f-febdb7bdd606
flynn-default/9350cdbc-2ef8-4a32-9ac0-535ce15e11ba    20K  15.0G    20K  /var/lib/flynn/volumes/zfs/mnt/9350cdbc-2ef8-4a32-9ac0-535ce15e11ba
flynn-default/a17f4ccf-16d6-4557-b5af-8e12ebbb335c  7.61G  15.0G  7.61G  /var/lib/flynn/volumes/zfs/mnt/a17f4ccf-16d6-4557-b5af-8e12ebbb335c
flynn-default/baa99605-36b9-41a6-8b24-aac41ee36689  10.5G  15.0G  10.5G  /var/lib/flynn/volumes/zfs/mnt/baa99605-36b9-41a6-8b24-aac41ee36689
flynn-default/bfdf0f5b-5621-43d7-9c6f-8b090202d6d0  5.39G  15.0G  5.39G  /var/lib/flynn/volumes/zfs/mnt/bfdf0f5b-5621-43d7-9c6f-8b090202d6d0
flynn-default/e93dce10-841f-4a0a-b3cf-431c86739502    20K  15.0G    20K  /var/lib/flynn/volumes/zfs/mnt/e93dce10-841f-4a0a-b3cf-431c86739502
flynn-default/pg-restore                             280K  15.0G  10.5G  /var/lib/flynn/volumes/zfs/mnt/pg-restore
```
```
root@cluster5:~# zfs list
NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
flynn-default                                       34.9G  3.58G    19K  /flynn-default
flynn-default/111cc540-8349-4646-8461-cf0492a40ac9  10.5G  3.58G  10.5G  /var/lib/flynn/volumes/zfs/mnt/111cc540-8349-4646-8461-cf0492a40ac9
flynn-default/31dcf0a7-0eb7-43f7-b28f-75fad1e8fbb0  12.8G  3.58G  12.8G  /var/lib/flynn/volumes/zfs/mnt/31dcf0a7-0eb7-43f7-b28f-75fad1e8fbb0
flynn-default/3f24aff3-9ca4-43b4-9eb6-1d4c80b45cad  11.7G  3.58G  11.7G  /var/lib/flynn/volumes/zfs/mnt/3f24aff3-9ca4-43b4-9eb6-1d4c80b45cad
flynn-default/d0f49986-9817-4dca-8430-0cebd444fa35  6.65M  3.58G  6.65M  /var/lib/flynn/volumes/zfs/mnt/d0f49986-9817-4dca-8430-0cebd444fa35
```
```
root@cluster6:~# zfs list
NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
flynn-default                                       38.5G      0    19K  /flynn-default
flynn-default/0de857d0-ce2b-437e-a44a-30ee90976dec  4.40M      0  4.40M  /var/lib/flynn/volumes/zfs/mnt/0de857d0-ce2b-437e-a44a-30ee90976dec
flynn-default/15f015e9-82f3-4095-8f0d-e5472067c04b  7.17G      0  7.17G  /var/lib/flynn/volumes/zfs/mnt/15f015e9-82f3-4095-8f0d-e5472067c04b
flynn-default/3ff5c68f-9ef3-473c-ab07-88607443181d    19K      0    19K  /var/lib/flynn/volumes/zfs/mnt/3ff5c68f-9ef3-473c-ab07-88607443181d
flynn-default/597a3da4-38ad-49fa-9fa1-74bb102ed993  13.5G      0  13.5G  /var/lib/flynn/volumes/zfs/mnt/597a3da4-38ad-49fa-9fa1-74bb102ed993
flynn-default/6ded61a1-9bbf-460f-b455-6f0300dd419c    20K      0    20K  /var/lib/flynn/volumes/zfs/mnt/6ded61a1-9bbf-460f-b455-6f0300dd419c
flynn-default/bc5a7299-6b84-4a78-a352-6a19e15ab57d  10.6G      0  10.6G  /var/lib/flynn/volumes/zfs/mnt/bc5a7299-6b84-4a78-a352-6a19e15ab57d
flynn-default/fd30991f-d540-43ce-a32e-ed346adf3ed4  7.21G      0  7.21G  /var/lib/flynn/volumes/zfs/mnt/fd30991f-d540-43ce-a32e-ed346adf3ed4
```

**Comment by titanous** [comment]
There is a new volume GC command in the latest stable release, so let's try to use that on `cluster6`.

```text
curl https://dl.flynn.io/tuf/targets/v20160918.1/b20d8722ac26346a358b988d76ab7f4e790322dbfc8d93eec0668559e16bbeea05dd4993c1e172886b990932e4e069c560f1aef608c00fa22b1389866624b377.flynn-host.gz | gunzip > flynn-host

chmod +x flynn-host

./flynn-host volume gc
```

**Comment by titanous** [comment]
Actually, wait a minute.

**Comment by titanous** [comment]
Instead, run `flynn-host volume list`, and post the output here.

**Comment by dottodot** [comment]
Sorry I was too quick and did the first one, but here's the output

```
ID                                    HOST
597a3da4-38ad-49fa-9fa1-74bb102ed993  cluster6
6ded61a1-9bbf-460f-b455-6f0300dd419c  cluster6
bc5a7299-6b84-4a78-a352-6a19e15ab57d  cluster6
0de857d0-ce2b-437e-a44a-30ee90976dec  cluster6
fd30991f-d540-43ce-a32e-ed346adf3ed4  cluster6
15f015e9-82f3-4095-8f0d-e5472067c04b  cluster6
3f24aff3-9ca4-43b4-9eb6-1d4c80b45cad  cluster5
31dcf0a7-0eb7-43f7-b28f-75fad1e8fbb0  cluster5
111cc540-8349-4646-8461-cf0492a40ac9  cluster5
d0f49986-9817-4dca-8430-0cebd444fa35  cluster5
a17f4ccf-16d6-4557-b5af-8e12ebbb335c  cluster4
baa99605-36b9-41a6-8b24-aac41ee36689  cluster4
5025e2ad-f8c9-4a63-982f-febdb7bdd606  cluster4
bfdf0f5b-5621-43d7-9c6f-8b090202d6d0  cluster4
9350cdbc-2ef8-4a32-9ac0-535ce15e11ba  cluster4
e93dce10-841f-4a0a-b3cf-431c86739502  cluster4
```

**Comment by titanous** [comment]
Okay, please post the output of `sudo zfs list` again. I'm just sorting out how to figure out which volumes to delete.

**Comment by dottodot** [comment]
```
NAME                                                 USED  AVAIL  REFER  MOUNTPOINT
flynn-default                                       38.5G      0    19K  /flynn-default
flynn-default/0de857d0-ce2b-437e-a44a-30ee90976dec  4.52M      0  4.52M  /var/lib/flynn/volumes/zfs/mnt/0de857d0-ce2b-437e-a44a-30ee90976dec
flynn-default/15f015e9-82f3-4095-8f0d-e5472067c04b  7.17G      0  7.17G  /var/lib/flynn/volumes/zfs/mnt/15f015e9-82f3-4095-8f0d-e5472067c04b
flynn-default/597a3da4-38ad-49fa-9fa1-74bb102ed993  13.5G      0  13.5G  /var/lib/flynn/volumes/zfs/mnt/597a3da4-38ad-49fa-9fa1-74bb102ed993
flynn-default/6ded61a1-9bbf-460f-b455-6f0300dd419c    20K      0    20K  /var/lib/flynn/volumes/zfs/mnt/6ded61a1-9bbf-460f-b455-6f0300dd419c
flynn-default/bc5a7299-6b84-4a78-a352-6a19e15ab57d  10.6G      0  10.6G  /var/lib/flynn/volumes/zfs/mnt/bc5a7299-6b84-4a78-a352-6a19e15ab57d
flynn-default/fd30991f-d540-43ce-a32e-ed346adf3ed4  7.21G      0  7.21G  /var/lib/flynn/volumes/zfs/mnt/fd30991f-d540-43ce-a32e-ed346adf3ed4
```

**Comment by titanous** [comment]
Okay, gist the output of these two commands:

```text
curl localhost:1111/host/jobs

flynn-host discover --json postgres
```

**Comment by dottodot** [comment]
I got this
```
root@cluster6:~# curl localhost:1111/host/jobs
404 page not found
root@cluster6:~# flynn-host discover --json postgres
17:34:45.926226 host.go:153: object_not_found: no leader found
```

**Comment by titanous** [comment]
Okay, I can build the second one from the logs, the port should be 1113 for the first one.

**Comment by dottodot** [comment]
I've just emailed the gist to logs as it contained my env vars that I don't want public

**Comment by titanous** [comment]
Okay, run this command, which will delete some stale volumes and free up space:

```text
./flynn-host volume delete 15f015e9-82f3-4095-8f0d-e5472067c04b bc5a7299-6b84-4a78-a352-6a19e15ab57d fd30991f-d540-43ce-a32e-ed346adf3ed4
```

**Comment by dottodot** [comment]
OK i got 

```
15f015e9-82f3-4095-8f0d-e5472067c04b deleted
could not delete volume bc5a7299-6b84-4a78-a352-6a19e15ab57d: unknown_error: Something went wrong
fd30991f-d540-43ce-a32e-ed346adf3ed4 deleted
17:51:11.981887 host.go:154: could not delete all volumes
```
and zfs list is now
```
flynn-default                                       24.2G  14.4G    19K  /flynn-default
flynn-default/0de857d0-ce2b-437e-a44a-30ee90976dec  6.53M  14.4G  6.53M  /var/lib/flynn/volumes/zfs/mnt/0de857d0-ce2b-437e-a44a-30ee90976dec
flynn-default/597a3da4-38ad-49fa-9fa1-74bb102ed993  13.5G  14.4G  13.5G  /var/lib/flynn/volumes/zfs/mnt/597a3da4-38ad-49fa-9fa1-74bb102ed993
flynn-default/6ded61a1-9bbf-460f-b455-6f0300dd419c    20K  14.4G    20K  /var/lib/flynn/volumes/zfs/mnt/6ded61a1-9bbf-460f-b455-6f0300dd419c
flynn-default/bc5a7299-6b84-4a78-a352-6a19e15ab57d  10.7G  14.4G  10.7G  /var/lib/flynn/volumes/zfs/mnt/bc5a7299-6b84-4a78-a352-6a19e15ab57d
```

**Comment by titanous** [comment]
Okay, give it a few minutes and then run the fix command again. Send over a new copy of the logs and output if things are still not working.

**Comment by dottodot** [comment]
OK that's seem to have cleared it up the `flynn` command is working again.

Do I need to worry about the other node that only has 3.56G left

**Comment by titanous** [comment]
Take a backup and then run `./flynn-host volume gc`, that should fix everything up.

**Comment by dottodot** [comment]
Ok I'll give that a go. 

Out of interest is there anyway to monitor and get warnings when disk space is getting low so that action can be taken before it causes an issue?

**Comment by dottodot** [comment]
ok just run `./flynn-host volume gc` on the node that's low on space and it didn't do anything

**Comment by dottodot** [comment]
Also node 1 has suddenly dropped in disk space from around 15GB to 2.62G

**Comment by titanous** [comment]
Hmm, I wonder if the GC command is broken, @josephglanville can take a look. You can also run `flynn-host volume delete` against the multi-gigabyte volumes that are not the largest one on each host.

**Comment by dottodot** [comment]
so on this 

```
flynn-default                                       37.2G  1.31G    19K  /flynn-default
flynn-default/111cc540-8349-4646-8461-cf0492a40ac9  12.7G  1.31G  12.7G  /var/lib/flynn/volumes/zfs/mnt/111cc540-8349-4646-8461-cf0492a40ac9
flynn-default/31dcf0a7-0eb7-43f7-b28f-75fad1e8fbb0  12.8G  1.31G  12.8G  /var/lib/flynn/volumes/zfs/mnt/31dcf0a7-0eb7-43f7-b28f-75fad1e8fbb0
flynn-default/3f24aff3-9ca4-43b4-9eb6-1d4c80b45cad  11.7G  1.31G  11.7G  /var/lib/flynn/volumes/zfs/mnt/3f24aff3-9ca4-43b4-9eb6-1d4c80b45cad
flynn-default/d0f49986-9817-4dca-8430-0cebd444fa35  6.78M  1.31G  6.78M  /var/lib/flynn/volumes/zfs/mnt/d0f49986-9817-4dca-8430-0cebd444fa35
```
could i delete 111cc540-8349-4646-8461-cf0492a40ac9 & 3f24aff3-9ca4-43b4-9eb6-1d4c80b45c

**Comment by titanous** [comment]
Yeah.
