### ISSUE TITLE
Provide native packages for a couple popular linux distributions

### ISSUE THREAD

**Issue by diclophis** [flynn/flynn#3436]
With the recent 1.4 release of kubernetes they have re-adopted the practice of publishing .deb/.rpm packages for two popular linux distros (in combination with a cluster bootstrap utility called `kubeadm`)... http://kubernetes.io/docs/getting-started-guides/kubeadm/

I feel that, in-order to remain an viable competitor to kubernetes, the flynn project should also provide some level of native distro packaging support.

This would greatly simplify the installation procedure by making it fit more squarely into an environment that might have some degree of legacy `apt/yum` based configuration management.

Also... just to note... kubeadm's style of `kubeadm init` ... `kubeadm join TOKEN` very much mirrors flynn's bootstrapping procedure from a year ago...

**Comment by diclophis** [comment]
You can imagine a world were everything else on a given flynn node is installed via a debian package... except flynn itself... What makes flynn so special that it wouldn't work as a debian package? And why wouldn't you want to install of of your server software in the same way via the "native packaging system"?

A specific advantage of a debian/apt package repo is that it allows a system maintainer to establish a clear and specific set of packages in a repo, and provide those packages for eternity without having to rely on any external systems... if everything else on a given system comes from this "frozen in time apt repo" ... except flynn... that doesn't make too much sense. Not to say keeping a mirror of a git repo is the hardest thing in the world... but why force a system administrator to jump through this extra hoop?

Also promoting `curl pipe to sudo bash` as a primary installation mechanism is laughable from a security perspective.

The `native package signing` is annoying, but it serves an extremely important purpose... and the more I think about it, it probably makes the most sense to just build and publish our own debs, from our own build box and publish to our own apt repo... but damn if it wouldn't be nice to also just be able to `apt-get install flynn` from a reliable community source as well.

**Comment by titanous** [comment]
> What makes flynn so special that it wouldn't work as a debian package?

We have our own update system that is more secure than Debian packaging (it uses [The Update Framework](https://theupdateframework.github.io/). Also, Flynn works with container images, not distro packages, and trying to shoehorn them in doesn't make much sense.

> And why wouldn't you want to install of of your server software in the same way via the "native packaging system"?

We strongly recommend the use of immutable hosts, so it really doesn't matter how the bits end up on disk.

> A specific advantage of a debian/apt package repo is that it allows a system maintainer to establish a clear and specific set of packages in a repo, and provide those packages for eternity without having to rely on any external systems... if everything else on a given system comes from this "frozen in time apt repo" ... except flynn... that doesn't make too much sense. Not to say keeping a mirror of a git repo is the hardest thing in the world... but why force a system administrator to jump through this extra hoop?

If you freeze packages in time, you open yourself up to the massive number of security vulnerabilities that are constantly being patched. You can absolutely maintain your own builds of Flynn and your own TUF repo: https://flynn.io/docs/development#releasing-flynn

> Also promoting `curl pipe to sudo bash` as a primary installation mechanism is laughable from a security perspective.

Can you explain why this is laughable? No matter how you distribute software, there is a "bootstrapping trust" problem. Downloading a script over a trusted HTTPS connection provides the same level of security as providing a GPG key or cryptographic checksum from an HTTPS website. 

The script has a cryptographic checksum of a binary that in turn has the TUF keys compiled into it, these keys are used to verify signatures for the downloads of all subsequent components and updates. We also provide instructions for inspecting the script before running it. As I'm sure you know, a `.deb` package can run whatever it wants as root during installation, running a script for installation is literally no different from a threat model perspective.

> The native package signing is annoying, but it serves an extremely important purpose

As I've mentioned above, we have our own secure download/update system that uses cryptographic signatures and has a threat model that is way more robust and comprehensive than throwing some random GPG signatures around.

**Comment by diclophis** [comment]
Ok
