### ISSUE TITLE
Docker "entrypoint" seems to be inexplicably cached 

### ISSUE THREAD

**Issue by mnaughto** [flynn/flynn#3443]
My team has been running version v20160726.0 of Flynn for a while now and it's been fairly stable, but we've been making some improvements/optimizations to our Dockerfiles and have run into a rather odd issue. 

Previously, we had been building `FROM openshift/base-centos7` (don't ask). This image is built with `ENTRYPOINT ["container-entrypoint"]`, and we'd been deploying Flynn using that resulting image for a while. 

Then, within the last few days, we switched to building `FROM node:0.10`. These built images run the default command and commands passed via `docker exec`/`docker run` as expected on our build server (both in Jenkins and from command line). That's why I was rather flummoxed to see the deployments from this new base image fail with the following error message:

    deployer: app job failed to start: exec: "/opt/app-root/src/container-entrypoint": stat /opt/app-root/src/container-entrypoint: no such file or directory

`/opt/app-root/src` is the `WORKDIR` specified in the Dockerfile. I've tried a few different things to remedy this issue:

1. Spinning down all running instances of the job on flynn before deploying.
2. Specifying an alternative `ENTRYPOINT`.
3. Placing the entrypoint file referenced in the error message in the location it's referring to.

Naturally, number three worked, but the other two did not. I tried these just for experimentation's sake, but it certainly seems like something is getting cached that is causing the Docker backend to keep using the original `ENTRYPOINT`. I know this is something that gets returned from `docker inspect`, so I wonder if that metadata is being cached.

Any idea what might be happening or how I might go about fixing it? One thing I haven't tried is building to a completely different Flynn application, but that would mess up our build process a bit :-/, and I don't think it should be necessary. 

**EDIT**: I did try deploying to a different (new) Flynn application, after removing any `ENTRYPOINT` references and that worked as expected. 

**EDIT 2**: After further investigation, after doing a couple of `flynn export` operations, it looks like the entrypoint and cmd attributes are stored with the job/process information, and in the code around https://github.com/flynn/flynn/blob/master/cli/docker.go#L239 makes it seem like that data is preserved for previous releases, though I don't think it should be. Is there a way to tweak this metadata on-the-fly?

**Comment by lmars** [comment]
@mnaughto when deploying a Docker image, the Flynn CLI extracts the `Entrypoint` and `Cmd` values from the image [here](https://github.com/flynn/flynn/blob/v20160726.0/cli/docker.go#L188-L190) and uses them to construct the `Args` for the resulting `app` process type [here](https://github.com/flynn/flynn/blob/v20160726.0/cli/docker.go#L239).

On each push, the `Args` are explicitly set to the `Entrypoint` and `Cmd` from the Docker image, there is no caching from the previous release.

To demonstrate this:

* create a Docker image with `Entrypoint` which prints "foo" then sleeps:

```shell
$ ID=$(docker run -d ubuntu:trusty /bin/true)                                                                                                                    
$ docker wait $ID
$ docker commit --change 'ENTRYPOINT ["bash", "-c", "echo foo; sleep 600"]' $ID entrypoint-test:foo
```

* push it to Flynn:

```shell
$ flynn create --remote "" test
$ flynn -a test docker push entrypoint-test:foo
$ flynn -a test scale app=1
```

* check "foo" appears in the log:

```shell
$ flynn -a test log
2016-09-30T00:22:47.450541Z app[app.host0-3798d79f-8688-4a80-98a1-a573526ccb19]: foo
```

* update the `Entrypoint` to print "bar" instead:

```shell
$ docker commit --change 'ENTRYPOINT ["bash", "-c", "echo bar; sleep 600"]' $ID entrypoint-test:bar
$ flynn -a test docker push entrypoint-test:bar
```

* see "bar" now printed in the log:

```shell
$ flynn -a test log
2016-09-30T00:22:47.450541Z app[app.host0-3798d79f-8688-4a80-98a1-a573526ccb19]: foo
2016-09-30T00:24:51.531381Z app[app.host0-93817778-c7d7-439b-a274-e956ec7415b4]: bar
```

* push an image with a `Cmd` but no `Entrypoint`:

```shell
$ docker commit --change 'CMD ["bash", "-c", "echo baz; sleep 600"]' $ID entrypoint-test:baz
$ flynn -a test docker push entrypoint-test:baz
$ flynn -a test log
2016-09-30T00:22:47.450541Z app[app.host0-3798d79f-8688-4a80-98a1-a573526ccb19]: foo
2016-09-30T00:24:51.531381Z app[app.host0-93817778-c7d7-439b-a274-e956ec7415b4]: bar
2016-09-30T00:26:19.062685Z app[app.host0-c49301b8-200d-448d-9d98-4d7b4abfc3ab]: baz
```

I can also see the correct args in the three releases:

```shell
$ flynn -a test release -q | xargs -L1 flynn -a test release show --json | jq '{ id: .id, created: .created_at, args: .processes.app.args }'
{
  "id": "add904b1-2ee5-493a-b1c4-e89b5a78f723",
  "created": "2016-09-30T00:26:18.658666Z",
  "args": [
    "bash",
    "-c",
    "echo baz; sleep 600"
  ]
}
{
  "id": "706152ff-3bab-4420-8fad-e183e0d17a58",
  "created": "2016-09-30T00:24:51.07693Z",
  "args": [
    "bash",
    "-c",
    "echo bar; sleep 600"
  ]
}
{
  "id": "661a9dd8-b577-4a46-a997-e71cfb1b6156",
  "created": "2016-09-30T00:22:35.620826Z",
  "args": [
    "bash",
    "-c",
    "echo foo; sleep 600"
  ]
}
```

Is it possible that the images you are pushing still have an `ENTRYPOINT` (you can check with `docker inspect --format '{{ .Config.Entrypoint }}' IMAGE`)?

**Comment by mnaughto** [comment]
Here's the output from the latest deployment I ran (replacing the actual image identifier with `<tag>`):

    flynn: pushing Docker image with "docker push <tag>"
    flynn: image pushed, waiting for artifact creation
    flynn: deploying release using artifact URI <artifact uri>
    deployer: app job failed to start: exec: "/opt/app-root/src/container-entrypoint": stat /opt/app-root/src/container-entrypoint: no such file or directory

And when I run `docker inspect -f '{{ json .Config.Entrypoint }}' <tag>`:

    null

And when I run `docker inspect -f '{{ json .Config.Cmd }}' <tag>`:

    ["/bin/sh","-c","npm start -d"]    

But I'm also able to reproduce your sequence. However, when I run `flynn -a <my-app> release -q | xargs -L1 flynn -a <my-app> release show --json | jq '{ entrypoint: .processes.app.entrypoint }'`, the entrypoint is always set to `["container-entrypoint"]`, but I think that's because there haven't been any successful deployments without it set to that.

**Comment by lmars** [comment]
@mnaughto ok, I'll try and dig a little deeper and see if I can reproduce this.

**Comment by lmars** [comment]
@mnaughto I still can't seem to reproduce this, here are the steps I took:

```shell
$ cat openshift/Dockerfile 
FROM openshift/base-centos7
CMD ["/bin/bash", "-c", "echo openshift; sleep 600"]

$ docker build -t test:openshift ./openshift
$ docker inspect -f '{{ json .Config.Entrypoint }}' test:openshift
["container-entrypoint"]

$ flynn -a test docker push test:openshift
$ flynn -a test log
2016-10-04T14:37:28.683717Z app[app.host0-59dcd7ef-6760-40e8-8d9c-42495d650641]: openshift


$ cat node/Dockerfile 
FROM node:0.10
CMD ["/bin/bash", "-c", "echo node; sleep 600"]

$ docker build -t test:node ./node
$ docker inspect -f '{{ json .Config.Entrypoint }}' test:node
null

$ flynn -a test docker push test:node
$ flynn -a test log
2016-10-04T14:37:28.683717Z app[app.host0-59dcd7ef-6760-40e8-8d9c-42495d650641]: openshift
2016-10-04T14:39:45.403853Z app[app.host0-0970b1a5-c36a-49f1-a168-db627767f5e2]: node
```

So the app seemed to work fine after switching the base image (I did not modify the `ENTRYPOINT`), and the release args are as expected:

```
$ flynn -a test release -q | xargs -L1 flynn -a test release show --json | jq '{ id: .id, created: .created_at, args: .processes.app.args }'
{
  "id": "7e9fbee9-6d40-4b3f-8abc-3d4a7158bede",
  "created": "2016-10-04T14:39:32.660585Z",
  "args": [
    "/bin/bash",
    "-c",
    "echo node; sleep 600"
  ]
}
{
  "id": "30a6661d-ef74-4837-9d4b-6f616c30214c",
  "created": "2016-10-04T14:37:10.392831Z",
  "args": [
    "container-entrypoint",
    "/bin/bash",
    "-c",
    "echo openshift; sleep 600"
  ]
}
```

All I can suggest is to create a new app to deploy your modified image to, making sure there are no more references to `/opt/app-root/src/container-entrypoint`.

**Comment by lmars** [comment]
@mnaughto any further thoughts on this issue? Did you manage to resolve it?
