### ISSUE TITLE
Stuck creating release....

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3446]
OK so I've had a few issues recently

https://github.com/flynn/flynn/issues/3434

and I updated to using S3 blobstore

https://github.com/flynn/flynn/issues/3444

and I've also now created a new cluster using v20160918.1

but now git push seems to get stuck at Creating release...

```
-----> Compiled slug size is 123M
-----> Creating release...
```

Here's my debug info
https://gist.github.com/ba4ec1948a6876c43490f94a4529c071
https://gist.github.com/fbb7461cf6e6e924fd344ba4ef5379f8

and I can't collect on the 3rd node

**Comment by dottodot** [comment]
and keep getting errors like

GET https://controller.cloud.dottodotdesign.co.uk/apps/bailey-live/jobs: httpclient: raw req: unexpected status 503

and my app is now not working

**Comment by dottodot** [comment]
and running flynn-host fix -n 3 --peer-ips

give the error
```
INFO[09-30|12:44:06] waiting for discoverd to be available 
12:45:06.338924 host.go:154: timed out waiting for discoverd, last error: discoverd: timed out waiting for instances
```

**Comment by dottodot** [comment]
Actually it's seems like every time I run `flynn-host collect-debug-info` on node 3 it gets stuck and breaks the cluster and I have to then run flynn-host fix

**Comment by josephglanville** [comment]
I'm gathering `46.101.178.128` is the `cluster3`?
Can you gist the contents of `/var/log/flynn/c91bbc2b-13a5-4927-b873-91be961c0a81.log` from that node.

Something seems pretty seriously wrong at a network level however. `cluster2` seems to have had intermittent contact with `cluster3` however after `cluster1` lost contact it never regained it.
The `discoverd` logs on `cluster3` are going to be essential for understanding if this is a bug or very flaky network however as the other 2 seem to be functioning normally.

**Comment by dottodot** [comment]
Yes that's correct

Something weird is definitely going on and I followed the same procedure I normally do when setting up a new cluster, unless I've missed something.

https://gist.github.com/dottodot/cbb91955ae9daa8d2008d6fbab110090

**Comment by josephglanville** [comment]
From what I can there seems to be a networking issue on `cluster3`, either kernel level on that host or at the hardware/provider level. You could have a look at the load by running `top` or `htop` and checking if there are any processes consuming excessive CPU or similar.
If you can't see anything wrong you may need to look at hardware issues or open a support ticket with your provider, or if it's easy then replace the machine and build a new cluster.

**Comment by dottodot** [comment]
It actually looks ok at moment, one thing I've just noticed is I've not setup swap memory which I had on my previous cluster could it be I'm running out of memory?

**Comment by josephglanville** [comment]
Potentially, you could check this with `free` or `top`/`htop` as suggested above.

**Comment by dottodot** [comment]
Yes my bad, it must have been running out of memory as I can now collect logs and deploy. 

My swap memory on that server jump to 1.5GB used during the deployment.
