### ISSUE TITLE
controller: Formation events can be delivered out of order

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3449]
When clients are subscribed to formation events, both [`sendUpdatedSince`](https://github.com/flynn/flynn/blob/v20160918.1/controller/formation.go#L401-L405) and [`publish`](https://github.com/flynn/flynn/blob/v20160918.1/controller/formation.go#L365) are run in separate goroutines, so if a formation is updated at the same time a client is subscribing, the events may be delivered out of order.

This behaviour can be seen in the following CI build:

https://ci.flynn.io/builds/20160930015420-2570f960

`ControllerSuite.TestKeyRotation` failed with `web process type failed to start, got down job event` because the scheduler formation stream was disconnected, then on reconnect it got a correct `web=2` scale up for release `ada5a29c-9390-49c4-b075-470b684ac179`, followed shortly after with a stale `web=1` scale, causing it to stop the job it just started and cause the deploy to fail:

```
t=2016-09-30T02:16:35+0000 lvl=info msg="handling formation change" component=scheduler fn=HandleFormationChange app.id=9b855b91-ed92-4db3-b231-ae7ec906fa34 release.id=ada5a29c-9390-49c4-b075-470b684ac179 processes="map[scheduler:1 web:1]"
t=2016-09-30T02:16:35+0000 lvl=warn msg="formation event stream disconnected" component=scheduler fn=streamFormationEvents err=nil
t=2016-09-30T02:16:36+0000 lvl=info msg="connecting formation event stream" component=scheduler fn=streamFormationEvents
t=2016-09-30T02:16:36+0000 lvl=info msg="handling formation change" component=scheduler fn=HandleFormationChange app.id=9b855b91-ed92-4db3-b231-ae7ec906fa34 release.id=ada5a29c-9390-49c4-b075-470b684ac179 processes="map[scheduler:1 web:2]"
t=2016-09-30T02:16:36+0000 lvl=info msg="expected different from actual" component=scheduler fn=formationDiff app.id=9b855b91-ed92-4db3-b231-ae7ec906fa34 release.id=ada5a29c-9390-49c4-b075-470b684ac179 expected="map[scheduler:3 web:2]" actual="map[scheduler:3 web:1]" diff="map[scheduler:0 web:1]"
t=2016-09-30T02:16:36+0000 lvl=info msg="starting 1 new web jobs" component=scheduler fn=handleFormationDiff app.id=9b855b91-ed92-4db3-b231-ae7ec906fa34 release.id=ada5a29c-9390-49c4-b075-470b684ac179
t=2016-09-30T02:16:36+0000 lvl=info msg="handling formation change" component=scheduler fn=HandleFormationChange app.id=9b855b91-ed92-4db3-b231-ae7ec906fa34 release.id=ada5a29c-9390-49c4-b075-470b684ac179 processes="map[scheduler:1 web:1]"
t=2016-09-30T02:16:36+0000 lvl=info msg="expected different from actual" component=scheduler fn=formationDiff app.id=9b855b91-ed92-4db3-b231-ae7ec906fa34 release.id=ada5a29c-9390-49c4-b075-470b684ac179 expected="map[scheduler:3 web:1]" actual="map[scheduler:3 web:2]" diff="map[scheduler:0 web:-1]"
t=2016-09-30T02:16:36+0000 lvl=info msg="stopping 1 web jobs" component=scheduler fn=handleFormationDiff app.id=9b855b91-ed92-4db3-b231-ae7ec906fa34 release.id=ada5a29c-9390-49c4-b075-470b684ac179
```

There are two fixes we can make here:

1) Update the controller so that it delivers all the "current" formations (i.e. the ones from `sendUpdatedSince`) before delivering any coming from the pg notify stream
2) Update the scheduler to ignore stale formation updates (i.e. track `formation.UpdatedAt`, and ignore any updates for values less than the current value)

@titanous @josephglanville thoughts?

**Comment by josephglanville** [comment]
I think 1) is the cleaner option, 2) sounds fairly robust too but it never feels good to rely on clocks in distributed systems for ordering semantics.
