### ISSUE TITLE
Updates to flunn/slugbuilder and flynn/slugrunner docker images

### ISSUE THREAD

**Issue by sosedoff** [flynn/flynn#3457]
Hi there,

Are there any planned updates to docker images `flunn/slugbuilder` and `flynn/slugrunner`?
Looks like last push was about a year ago. Were they replaced by some other images?

**Comment by titanous** [comment]
We don't distribute images on Docker Hub, so those are quite old.

**Comment by sosedoff** [comment]
Ok, thanks. Is there any way to use updated images without flynn's private registry (i assume there's one) ?

**Comment by titanous** [comment]
You can clone the repo and build the images yourself. We don't use a registry to distribute images, they are packaged into a TUF repo, the format will be changing soon to not be Docker-based at all.

**Comment by sosedoff** [comment]
Great, thanks for the info.
