### ISSUE TITLE
Vagrant installer: flynn command not found

### ISSUE THREAD

**Issue by guestisp** [flynn/flynn#3459]
seems that `flynn` must be installed prior the execution of vagrant installer

```
Connection to 127.0.0.1 closed.
make[2]: uscita dalla directory "/home/ale/flynn/demo"
bash: riga 1: flynn: comando non trovato
Makefile:35: set di istruzioni per l'obiettivo "bootstrap" non riuscito
make[1]: *** [bootstrap] Errore 127
make[1]: uscita dalla directory "/home/ale/flynn/demo"
Makefile:22: set di istruzioni per l'obiettivo "init" non riuscito
make: *** [init] Errore 2
```

i've destroyed the vagrant VM, manually installed the `flynn` cli and started again the vagrant installed and everything went ok

So, in docs, you should say that `flynn` cli must be installed prior running `make init` or `make init` should install the cli during the process

**Comment by lmars** [comment]
@guestisp the demo Makefile already has an `install-cli` target which installs the CLI (see [here](https://github.com/flynn/flynn/blob/master/demo/Makefile#L26-L29)), we should make that a dependency of the other commands. Are you interested in contributing that change?

**Comment by guestisp** [comment]
In my environment the cli wasn't installed

I've immediately abandoned the project as there is any auth system. A paas without auth is more or less useless in any environment with more than 1 developer

I don't want that my app could be destroyed by an human error made by another developer

**Comment by lmars** [comment]
@guestisp I probably wouldn't go as far as calling Flynn useless, but I fully understand your concerns, we are actively working on security improvements (see https://github.com/flynn/flynn/projects/1).

**Comment by guestisp** [comment]
I've wrote "more or less" :-)

Any ETA about a real Auth feature ?

**Comment by lmars** [comment]
@guestisp we don't have a strict ETA, feel free to watch the relevant issues to be updated as the work progresses.
