### ISSUE TITLE
Docker --email flag is deprecated

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#3466]
> Flag --email has been deprecated, will be removed in 1.13.

Noticed while running `flynn docker login`

**Comment by lmars** [comment]
Note that `--email` is required when using Docker 1.9.1, so we will either need to explicitly not support that version (note that we currently use that version for building Flynn, see #2459), or do some form of version check.

**Comment by grauschnabel** [comment]
For me this is a critical bug as it is not possible to add docker apps to flynn cluster

**Comment by lmars** [comment]
@grauschnabel the `--email` flag is still just deprecated rather than being removed (see [here](https://docs.docker.com/engine/deprecated/#e-and---email-flags-on-docker-login)) so other than printing a warning, it will not prevent you from deploying apps to Flynn.

**Comment by freerobby** [comment]
@lmars @titanous FYI: `--email` has been removed in the edge branch on Docker, so I suspect this will be a breaking change on the next Docker stable release.

**Comment by subos2008** [comment]
Note that this has broken "aws ecr get-login" as that supplies the -e flag, which now falls over with a fatal error.

**Comment by titanous** [comment]
@subos2008 I think you might be on the wrong issue tracker, Flynn doesn't use ECR.

**Comment by okwei2000** [comment]
this is breaking my bamboo build.. why gives an error code when -e is supplied?

**Comment by lmars** [comment]
@okwei2000 the Docker `--email` flag has been removed, are you using the latest version of both Docker and the Flynn CLI?
