### ISSUE TITLE
bootstrap: Restoring a corrupt PostgreSQL should throw an error

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3468]
When restoring from a backup, PostgreSQL errors are ignored which can lead to unexpected issues if the backup is corrupt.

I tried setting `ON_ERROR_STOP=on` but then the restore fails quite early with:

```
20:04:43.457096 restore-postgres restore
SET
SET
SET
DROP DATABASE
DROP DATABASE
NOTICE:  database "808d3a97df8e68216505bc29e5303c8d" does not exist, skipping
NOTICE:  database "8c873e26912dd998659d5cc7a5a08369" does not exist, skipping
NOTICE:  database "c6be63e437ba6ca22378e607d362cbf4" does not exist, skipping
DROP DATABASE
NOTICE:  role "5f88e706beab20f2755168edce833b69" does not exist, skipping
DROP ROLE
NOTICE:  role "9cdfab8d5fdfcaacd97c39f285c78ee4" does not exist, skipping
DROP ROLE
NOTICE:  role "b8be92697ca3695e1ecb10ea80c5d7ff" does not exist, skipping
DROP ROLE
ERROR:  current user cannot be dropped
```

This seems to be a long standing issue, see this bug from 2008: https://www.postgresql.org/message-id/200804241637.m3OGbAOe071623@wwwmaster.postgresql.org

@josephglanville any thoughts on how to get around this?

**Comment by josephglanville** [comment]
We could generate the dumps without `--clean` which should avoid adding the `DROP` commands for roles/databases. Will need to check if that will work fine or not though.
The caveat here being that if someone manually restores the dump they will need to drop pre-existing roles/databases themselves or the restore will error.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
