### ISSUE TITLE
cli: Output a checksum when creating a backup

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3469]
To help users maintain data integrity, the Flynn CLI should optionally output a checksum which can then be used to verify the backup before importing into a new cluster, e.g.:

``` shell
$ flynn cluster backup --file backup.tar --checksum sha256
Creating cluster backup...
Backup complete.
sha256 checksum: daebe2b9f64bbccd43df236cf2d21d64cc2356ea8307210a58e8c0f8a59fc2c2
```

**Comment by titanous** [comment]
We should probably just print it out by default, and provide a way to verify it automatically during restore.

**Comment by josephglanville** [comment]
We could hash each individual file and store the checksums in a manifest inside the tar archive, makes recovery from corruption a bit easier.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
