### ISSUE TITLE
Can I run vpn client inside flynn docker container?

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3473]
I need to connect into Microsoft azure with strongswan. Do You have NET_ADMIN capability enabled? Is it possible to turn it on for one container?

I would want to deploy networkproxy container/application which forwards incoming requests through vpn connection into rest api hosted inside azure.

**Comment by lmars** [comment]
@onnimonni containers are not currently granted `CAP_NET_ADMIN` (see [here](https://github.com/flynn/flynn/blob/master/host/libcontainer_backend.go#L53-L70) for the list of granted capabilities).

Flynn doesn't currently expose an interface for adding extra capabilities, but will do in the future.

**Comment by onnimonni** [comment]
I understand. Thanks @lmars! Is there issue where I can track this?

**Comment by lmars** [comment]
@onnimonni see #3475.
