### ISSUE TITLE
Application not starting in a timely manner after scaling

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3483]
The app's name is `qa-bvjs-apps-scoutfile`.

Freshly restored cluster, from slightly outdated backup. Application was then migrated via import / export, to bring it up to date.

Application appeared to be misbehaving. User scaled it down and back up, now it isn't starting at all. Last logs are from the job before the last slugbuilder:
```
flynn -c qa-us-east-1 -a qa-bvjs-apps-scoutfile scale
dimsum=1 web=1

flynn -c qa-us-east-1 -a qa-bvjs-apps-scoutfile ps --all
ID                                                 TYPE         STATE  CREATED            RELEASE
ip1010038164-319940b4-e915-4884-9a87-6a4e09136fc0  run          down   About an hour ago  8b78d134-3907-4404-a362-6812f870789e
ip1010038162-0f753400-c7ca-491b-aa08-05ca0bd02400  slugbuilder  down   About an hour ago  8b78d134-3907-4404-a362-6812f870789e
ip1010038162-635cf7a4-7b14-4c40-8555-4d9bd45cf773  web          down   59 minutes ago     bcaa7833-9911-4c03-945d-23fb8ad368c7
ip1010038163-a0c46de0-fe22-4521-b9dc-991b88e4b21d  dimsum       down   59 minutes ago     bcaa7833-9911-4c03-945d-23fb8ad368c7
ip1010038163-b9390bdf-fd1a-4d80-b6a8-1f9fbb6440cc  web          down   58 minutes ago     2dc8d474-e260-4f36-81d6-3ea425ed040b
ip1010038163-e60cf634-deeb-413d-9a51-c0cdb9d78b47  dimsum       down   58 minutes ago     2dc8d474-e260-4f36-81d6-3ea425ed040b
ip1010038164-08804b1f-d699-4fd6-82ca-f61c455588af  slugbuilder  down   48 minutes ago     2dc8d474-e260-4f36-81d6-3ea425ed040b
ip1010038164-61de1de3-f92a-407a-bf90-b6fce3a05c86  web          down   47 minutes ago     672518a1-23d4-47cd-adb7-b361465c9876
ip1010038163-661b66d3-55a6-4a1b-9072-c5954c27a134  dimsum       down   47 minutes ago     672518a1-23d4-47cd-adb7-b361465c9876
ip1010038163-b2d22759-d2c5-4cb8-99e7-c5c51c9dccaa  slugbuilder  down   19 minutes ago     672518a1-23d4-47cd-adb7-b361465c9876
ip1010038163-ddfa462b-9a00-4ac4-92ba-a23858544984  web          down   19 minutes ago     e9e13d25-b4de-4b65-b5df-382779528a41
ip1010038164-2d96436b-8b03-452c-91fb-9b88058a3b7b  dimsum       down   19 minutes ago     e9e13d25-b4de-4b65-b5df-382779528a41

flynn -c qa-us-east-1 -a qa-bvjs-apps-scoutfile log | tail -n 1
2016-10-07T20:56:31.776646Z app[web.ip1010038164-61de1de3-f92a-407a-bf90-b6fce3a05c86]: [2016-10-07T20:56:31.776Z]  info  - [Web Service]  Responding with a deployment for srd-testcustomer-1 in main_site / production
```

https://bazaarvoice.box.com/s/fl0v8i8ho5394djlv5pkqqq6tcfm1ivd has the debug info.

**Comment by temujin9** [comment]
Additional: `scale` commands result in:
```
scaling dimsum: 0=>1, web: 0=>1

Timed out waiting for job events. Waited 20 seconds.
expected: map[web:map[up:1] dimsum:map[up:1]]
actual: map[]
```
Though they "appear" to eventually succeed, in that later scale queries show them at the target.

**Comment by temujin9** [comment]
Delete and redeploy is a viable workaround.

**Comment by lmars** [comment]
@temujin9 could you clarify a few things?

> Application appeared to be misbehaving

In what way was it misbehaving? Were any jobs running?

> User scaled it down and back up, now it isn't starting at all

So is the attached output of `flynn ps --all` from just after this chain of events?

Looking at the scheduler log, release `e9e13d25-b4de-4b65-b5df-382779528a41` (which is the most recent release in your output) was scaled up at `2016-10-07T20:55:46+0000` and the jobs started, but then it was subsequently scaled down at `t=2016-10-07T21:00:46+0000`.

> Additional: scale commands result in: ... Though they "appear" to eventually succeed, in that later scale queries show them at the target.

I can't see any evidence of failed scale events in the debug info, so can you post the output of the following after the failed scale event:

```
$ flynn release
$ flynn ps --all
$ flynn scale --all
```

Collecting the debug info again would be useful too.

**Comment by temujin9** [comment]
I feel like this may have been transient or user error. It has not repeated since I reported it.

Closing for now. I will reopen, and grab the output of those logs, if it recurs.

**Comment by temujin9** [comment]
(Sorry, thought this was a different ticket. I'm going to leave this one open for at least a few more days, to ensure it doesn't repeat. I will gather that information if / when it occurs again.)

**Comment by titanous** [comment]
Has this happened recently?

**Comment by temujin9** [comment]
Not that I've seen. Closing until / unless it recurs.
