### ISSUE TITLE
host: Log critical system resource usage

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3484]
Flynn should monitor and emit log messages when system resource usage becomes critical, for example:
- when the `flynn-default` zpool reaches N% usage
- when 1m system load exceeds N
- when free memory drops below N%

This would help when debugging issues like #3424 to determine whether disk space usage correlated with cluster issues (and could perhaps trigger the collection of debug info).

This could either be part of `flynn-host` or a separate service, and could also be exposed via an API to provide system metrics (ref #201 #3414).

@titanous @josephglanville thoughts?

**Comment by IsNull** [comment]
Once the API is defined, it would be great to have this very basic system status information available in the dashboard. I.e. a list of all nodes in the cluster, and each node the basic disk/memory/cpu information.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
