### ISSUE TITLE
High CPU causes cluster failures but no node eviction

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3487]
The AWS S3 upload step of our backup scripts is getting caught in some loop, spiking CPU through the roof, and rendering a node mostly inoperable. This has caused several outages across multiple clusters.

This has several unfortunate side effects:
- The failure is below the threshold of AWS's auto-termination (preventing the issue from autohealing)
- The high CPU usage renders the node unavailable to SSH for diagnostic purposes
- The node is still semi-functional, so it is still participating in the overall Flynn cluster.

Remediation is fairly simple, in our environment: kill the stuck node, and wait for it to be replaced. However, Flynn doesn't evict the node even though its involvement is bringing down the other nodes; in one case, a long enough outage resulted in a cluster which could not recover at all, even after the offending node was removed.

@josephglanville worked with me to debug this, and can describe some of how the failures looked from within Flynn.

**Comment by titanous** [comment]
Is there a reasonable way to detect this? If the flynn-host and discoverd APIs are operating, then I'm not sure what we can do. If they aren't, it will look like a network partition and our failure logic will kick in.

**Comment by temujin9** [comment]
I don't know. I was hoping @josephglanville would comment more with what the failures looked like inside Flynn. At this point, I suspect he may lack the context to do so meaningfully.

The trigger of this problem has been resolved, so I suppose we can close this for now. However, it's still a danger, as far as I'm concerned, anytime a process outside Flynn starts overconsuming resources.
