### ISSUE TITLE
Adding a cluster fails on certificate issue

### ISSUE THREAD

**Issue by markcipolla** [flynn/flynn#3491]
Hi, 

After a catastrophic laptop failure 🔥 , I've lost all my files.
I can log into the cluster via the web (thanks the gods for password managers), but how do I get my local machine to recognise the cluster?

GENERATED CODE being the four letter generated string that denotes my cluster
KEY being the password to log on

```
flynn cluster add production [GENERATED CODE].flynnhub.com [KEY]
Error writing CA certificate: Get https://controller.[GENERATED CODE].flynnhub.com/ca-cert: x509: certificate signed by unknown authority
```

Thanks!

**Comment by titanous** [comment]
Set a `-p` flag (the certificate pin) to the output of this command:

```text
DOMAIN=[GENERATED CODE].flynnhub.com; openssl s_client -connect controller.$DOMAIN:443 -servername controller.$DOMAIN 2>/dev/null </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -inform PEM -outform DER | openssl dgst -binary -sha256 | openssl base64
```

**Comment by markcipolla** [comment]
![](https://media.giphy.com/media/3oEdva9BUHPIs2SkGk/giphy.gif)

Thanks @titanous! 👍 
Could this be added to https://flynn.io/docs/cli ?
