### ISSUE TITLE
Is it normal to have multiple processes down?

### ISSUE THREAD

**Issue by simon0191** [flynn/flynn#3494]
My app seems to be working normally but when I run `$ flynn ps --all` I get this:
```
ID                                              TYPE         STATE  CREATED            RELEASE
ip1000172-4beda32d-fefe-4eef-bd5e-dd8445477d72  slugbuilder  down   About an hour ago  c6cf1128-c9ec-439c-a668-46825746476f
ip1000179-1021ce91-7c12-4fb1-afc9-6a0acf4a984c  web          down   About an hour ago  30c80b83-7f2f-45ed-93ba-4b4103cb1d9c
ip1000172-30f6df5e-382b-4a4f-a80f-1f3a8873758a  web          down   30 minutes ago     7b202706-a00b-4c65-bf01-17ab314a779a
ip1000172-2c09e5d6-4ac7-4d75-a153-952f220efc17  run          down   27 minutes ago     3f81ad81-7a61-426e-b0c7-86240378b33d
ip1000179-326279bc-28cf-40a1-a469-7b5e5af13580  web          down   24 minutes ago     f717a7c8-b5a7-4951-93df-5d657ae28fc6
ip1002132-1e7c239c-9e6d-4a2e-b979-35de9b80716f  slugbuilder  down   22 minutes ago     f717a7c8-b5a7-4951-93df-5d657ae28fc6
ip1002132-4ece72e7-08cb-4937-b9fd-fabd44caf358  web          up     19 minutes ago     3339ebba-0d09-4df8-868d-4532bd96e508
ip1000179-c2ce2a49-62f8-455c-83b4-72b3b0e46838  web          up     10 minutes ago     3339ebba-0d09-4df8-868d-4532bd96e508
```

**Comment by titanous** [comment]
Yes, that is normal. Those are processes from the two builds (slugbuilder) and the previous release (note the id in the release column). Each time you deploy, new processes are created that replace the old ones. Drop the `--all` flag to see everything that is currently running.

**Comment by simon0191** [comment]
Do I have to remove them to free disk space? If yes, how can I do that?

**Comment by titanous** [comment]
The process entries themselves do not take up a meaningful amount of disk space. Each release can take some space, you can enable garbage collection for an app by running:

```text
flynn meta set gc.max_inactive_slug_releases=N
```

Where N is the number of previous releases you want to keep. This will be set by default in the next release.

**Comment by simon0191** [comment]
I'll close the issue since it's normal behaviour
