### ISSUE TITLE
Add support for AWS-China Region 

### ISSUE THREAD

**Issue by smewp** [flynn/flynn#3498]
AWS-China has two regions, cn-north-1a and cn-north-1b.  However, seems the console is always just cn-north-1.  https://console.amazonaws.cn/console/home?region=cn-north-1#

**Comment by titanous** [comment]
Unfortunately this is not possible, as we'd need a legal entity in China to get an AWS account that has access to the Chinese regions (in order to host the AMIs there).

**Comment by titanous** [comment]
It's worth noting that you can use the manual installation instructions or the SSH option in the installer instead. Sorry for the inconvenience!

**Comment by smewp** [comment]
I have such a legal entity in China, with an AWS-China account, and I'd be happy to help in any way with creating a community image.  I did spend hours on the SSH option and could not get the install to complete. I think it was a problem with your hosting website not being accessible to complete the download on the AWS-China server.

**Comment by titanous** [comment]
If you could provide the errors that you ran into I can take a look and see if there is anything we can do about that. We are hosted by CloudFront, so I'm not sure what's going on there.
