### ISSUE TITLE
RethinkDB database appliance

### ISSUE THREAD

**Issue by gutenye** [flynn/flynn#3499]
RethinkDB is another popular NoSQL database.

**Comment by philiplb** [comment]
Where the company behind it just went bankrupt. :/ https://news.ycombinator.com/item?id=12641936

**Comment by ZetaHunter** [comment]
@philiplb it will continue to exist as an open source project though.

**Comment by thomasmodeneis** [comment]
Company had to close but Compose.io is not giving up on RethinkDB.
BlockChainDB going to support RethinkDB too.

https://docs.google.com/document/d/1Fy-drBGDTyibwEBBAX6G5otqtWiKOD2sBXmL2uVTFtE/edit

**Comment by wishinghand** [comment]
Now that RethinkDB has official stewardship after the founding company died, I'd love to revisit this becoming an option for Flynn.

**Comment by aleclarson** [comment]
I would like a RethinkDB integration, too. 👍

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
