### ISSUE TITLE
Downloading Buildpack failing

### ISSUE THREAD

**Issue by holtgrewe** [flynn/flynn#3500]
I'm trying to push [this app and revision](https://github.com/bihealth/flowcelltool/tree/a06352ed288ef873b32c9b1b37b1a450175ac33b). This is what I'm getting:

```
Counting objects: 866, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (721/721), done.
Writing objects: 100% (866/866), 163.04 KiB | 0 bytes/s, done.
Total 866 (delta 520), reused 244 (delta 98)
-----> Building flowcells...
-----> Multipack app detected
       =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-apt.git
remote: ERROR: Build failed: exec: job exited with status 1
To https://git.cubipaas.bihealth.org/flowcells.git
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
```

I'm running a fresh install of flynn v20160918.1.

Debug information is available here: https://gist.github.com/a5e7921bb4a3873ff3bd89aa5611dab0

What can I do?

**Comment by titanous** [comment]
It looks like you have pulled in the apt buildpack, but don't have an Aptfile, which could cause that error. Try again after committing an Aptfile.
