### ISSUE TITLE
Nodejs app build failed

### ISSUE THREAD

**Issue by NamPNQ** [flynn/flynn#3501]
I try build using heroku node buildpack, and it exited with code 127 when install dependencies, without any log

**Comment by titanous** [comment]
Try increasing the amount of memory available to the build process (the default is 1GB):

```text
flynn limit set slugbuilder memory=3GB
```

**Comment by NamPNQ** [comment]
Have way to set it by default? The issuse appear many times

**Comment by NamPNQ** [comment]
@titanous Have way to rebuild in dashboard when build failed?

**Comment by titanous** [comment]
> Have way to set it by default?

Not currently.

> Have way to rebuild in dashboard when build failed?

You should be able to deploy again through the dashboard.

**Comment by titanous** [comment]
Actually, I was wrong, you can set it by default: https://flynn.io/docs/apps#slugbuilder-limits
