### ISSUE TITLE
Provisioning database on separate node?

### ISSUE THREAD

**Issue by joshmn** [flynn/flynn#3503]
Bounced around documentation for a bit, couldn't find what I was looking for:

I've set up Flynn with a few different nodes in an initial cluster, just to play around with. It wasn't immediately clear if I could define what node I wanted to, say, dedicate to a web node, or dedicate to a Postgres node. 

Is Flynn set up for this? Is it on the roadmap? Am I in the wrong place?

**Comment by titanous** [comment]
Yes, tags can be used to do this. It looks like there is no docs section for this, but there are details in the release announcement: https://flynn.io/blog/2015-12-28-this-week-in-flynn

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
