### ISSUE TITLE
UI is not listing clusters

### ISSUE THREAD

**Issue by kvitajakub** [flynn/flynn#3504]
I installed Flynn on Fedora 24 as root by

```
L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
```

I created and added clusters which are listed in the command line:

```
flynn cluster
NAME              CONTROLLER URL                        GIT URL                        DOCKER URL
dev               https://controller.[xxx].flynnhub.com  https://git.[xxx].flynnhub.com  (none)
flynn-1476460741  https://controller.[xxx].flynnhub.com  https://git.[xxx].flynnhub.com  (none)  (default)
```

But none of these clusters appear on the left side of the graphical interface which pops up after

```
flynn install
```

This list is probably important as it is the only way I found how to destroy clusters. Right now I need to ask colleagues (who use macbooks) to remove them for me. Is this a bug or change in interface?

Would it be possible to add a cluster deletion option to CLI?

**Comment by jvatic** [comment]
The clusters listed in the installer UI are ones you've created using the installer on your local machine (data is stored in `~/.flynn/installer`). The `flynn cluster` command lists what clusters are configured in your `~/.flynnrc`. So this is the expected behaviour assuming the clusters you wish to destroy through the installer were created using another machine. I agree this isn't ideal and should be improved.

**Comment by kvitajakub** [comment]
Actually the cluster `flynn-1476460741` was created on the local machine, as well as previous cluster. But only clusters I have seen in the UI were the ones which were currently created.
We deleted the previous cluster manually from AWS.

I was wrong about deleting clusters from other machines, we were just in process of trying that.

**Comment by jvatic** [comment]
So to clarify, you created `flynn-1476460741` via `flynn install` but when running `flynn install` again it doesn't show up in the list?

**Comment by kvitajakub** [comment]
Yes, exactly.
