### ISSUE TITLE
MariaDB TIME handling issue with Rails less than version 5.x

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3505]
According to [this commit](https://github.com/rails/rails/pull/24542) to Ruby on Rails, MariaDB does not handle the TIME values in a MySQL compatible way making it unable to be used with any version of Rails less than 5.

It looks like MariaDB [has a work around](https://mariadb.com/kb/en/mariadb/time/) in the use of the '--mysql56-temporal-format' option.

It might be a good idea to enable this option for MariaDB to avoid issues with Rails sites.

**Comment by josephglanville** [comment]
Have you tested if this fixes the problem? I think that option only changes the on-disk format rather than the behavior of the `TIME` and `DATE` types.

**Comment by josephglanville** [comment]
It looks like the issue to support this behaviour is still open: https://jira.mariadb.org/browse/MDEV-9541

**Comment by bbaptist** [comment]
I had not tested against a server. From my research it seemed these both addressed the same issue, reading the MariaDB Jira bug you posted it looks like they are not the same.

**Comment by titanous** [comment]
I'm closing this, as it doesn't look like we can do anything about it.
