### ISSUE TITLE
Idea: remove hard-coded values, like key sizes

### ISSUE THREAD

**Issue by Leryan** [flynn/flynn#3506]
Hi,

Well… i never used flynn but I went around the code just to see what this tool was doing, and i saw a hard-coded SSH key size.

https://github.com/flynn/flynn/blob/master/pkg/sshkeygen/sshkeygen.go#L22

I think this is just like Java's DH parameter hard-coded size: all applications relying on old versions of Java were generating weak DH parameters, and here for the SSH key it's the same.

Even if this tool is not as old as Java, I don't think such values should be hard-coded and non-configurable.

**Comment by titanous** [comment]
The CLI is auto-updated, so if there is a weakness in RSA 2048, we can have this changed within a few hours.

**Comment by Leryan** [comment]
Woha fast answer! Ok that's cool :)
