### ISSUE TITLE
Is it possible to stop node and restart it?

### ISSUE THREAD

**Issue by simon0191** [flynn/flynn#3507]
I want to get access to the nodes of the cluster to install a script that reports memory usage to CloudWatch but I lost the private key. I saw [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html#replacing-lost-key-pair) that it's possible to recover access to the EC2 but I'll need to restart each node. 

After restart, the nodes will have a new IP. I guess that I'll have to update the A record in the hosted zone and the health checks. Anything else?

**Comment by titanous** [comment]
Did you deploy with `flynn install`? If so, here are the details for connecting with SSH: https://flynn.io/docs/installation/cloud#ssh-access

Change host IPs will probably break the Flynn cluster, as it has them stored in internal databases for cluster communication.

**Comment by simon0191** [comment]
:S
I lost that key. I ran the installer inside vagrant and the I did vagrant destroy.

**Comment by simon0191** [comment]
Or, is it possible to add new nodes and then remove the original ones?

**Comment by titanous** [comment]
Yes, you can do that. Add 3 or more new nodes, and then demote the old ones: https://flynn.io/docs/production#adding-hosts

**Comment by titanous** [comment]
Though just running the installer again and restoring a backup, seems like it'd be easier.
