### ISSUE TITLE
Error while restoring backup.

### ISSUE THREAD

**Issue by alejoescobar** [flynn/flynn#3509]
Hi, we were restoring our flynn backup when we got the following error:
```
Migrating domain (xym5.flynnhub.com to rmm5.flynnhub.com)
Error: Domain migration error: timed out waiting for job events: map[web:map[down:1]]
```
Our apps seem to be working fine, but we're not sure what's going to happen with the domain migration and how this error can affect the whole backup restore process.

**Comment by josephglanville** [comment]
Hi, could you please login to one of your cluster nodes and post the output of `flynn-host collect-debug-info`.
If the output creates a tarball you can email it to `logs@flynn.io` with the issue number and we will take a look.

**Comment by alejoescobar** [comment]
Done!

**Comment by lmars** [comment]
@alejoescobar I'm investigating why you got that particular error, but the domain migration actually retries itself when it fails, and the second attempt completed at 06:17 UTC:

```
t=2016-10-15T06:17:34+0000 lvl=info msg="domain migration complete" app=worker fn=HandleDomainMigration domain_migration=4aadcabb-0f84-4d58-9503-75d9e4223a56
```

**Comment by lmars** [comment]
@alejoescobar the underlying issue here was #3518.

Since the domain migration did succeed eventually, I am going to close this issue and look into fixing #3518.
