### ISSUE TITLE
Generated SSH key permissions should be more restrictive

### ISSUE THREAD

**Issue by danhawkes** [flynn/flynn#3511]
Attempting to use the `~/.flynn/installer/keys/flynn` key on ubuntu 16.04, get the following error:

```
debug1: Offering RSA public key: ./keys/flynn.pub
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug2: input_userauth_pk_ok: fp SHA256:eg2DGPqkM1pyu1UQf/DCVB+wiZEdEJ+K2r7cAnBcvAQ
debug3: sign_and_send_pubkey: RSA SHA256:eg2DGPqkM1pyu1UQf/DCVB+wiZEdEJ+K2r7cAnBcvAQ
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for './keys/flynn.pub' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "./keys/flynn.pub": bad permissions
```

**Comment by lmars** [comment]
Those permissions are set here:

https://github.com/flynn/flynn/blob/master/installer/persistence.go#L56

Are you interested in submitting a patch for that?

**Comment by lmars** [comment]
Oh wait, that is the public key, that doesn't need strict permissions right? The private key is `0600`:

https://github.com/flynn/flynn/blob/master/installer/persistence.go#L48

Are you perhaps using the public key when you should be using the private key?

**Comment by danhawkes** [comment]
Ah, apologies: yeah. That log message matches what I get like when pointing ssh at the wrong file.
