### ISSUE TITLE
Support for configurable long lived connection draining

### ISSUE THREAD

**Issue by jamesmintram** [flynn/flynn#3513]
I need to control when my application is killed during a deployment. Each app container will have a large number of long lived websocket connections. With the current "All At Once" deployment, all of the old containers will be killed in rapid succession which could lead to a thundering herd of reconnections.

To solve this problem, it would be good if an application could receive a custom signal when the scheduler wants to terminate it and have a configurable timeout (which is currently hard coded to 10s)

This would allow my app to drain its connections at a steady rate and then terminate itself.

**Comment by lmars** [comment]
Just to outline my thoughts on a possible approach here:

* Add `--drain-signal` (a Unix signal like `SIGUSR1`) and `--drain-timeout` flags when adding routes
* If the drain signal is set, send it to the job when all routers have emitted the `backend-down` event (i.e. when all routers have stopped routing requests to the backend)
* Replace the hard coded [`routerDrainTimeout`](https://github.com/flynn/flynn/blob/v20161022.0/controller/scheduler/scheduler.go#L33) with the drain timeout configured in the route

This would then allow the app to receive a signal and start gracefully closing connections once all routers have stopped routing new requests to it, with a user defined timeout after which the job will receive `SIGTERM` (and `SIGKILL` after a further 10s).

This would be useful when deploying the controller which serves streaming SSE requests.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
