### ISSUE TITLE
Deploying different branches

### ISSUE THREAD

**Issue by dabeeeenster** [flynn/flynn#3515]
Hi,

Just learning Flynn and couldn't see this documented anywhere. Is there a best practise in terms of deploying different branches of the same app to Flynn? Ideally we'd want dev/staging/master branches all deployed to their own app?

**Comment by titanous** [comment]
You can create new apps with different remotes, so for example:

```text
flynn create myapp-staging --remote staging
flynn -a staging env set FOO=bar
git push staging staging:master
```

**Comment by dabeeeenster** [comment]
Ah great thanks. It would be good to make this explicit in the docs somewhere maybe? Not sure how common a pattern it is for others tho.

**Comment by lmars** [comment]
@dabeeeenster the docs are here if you want to take a stab at updating them:

https://github.com/flynn/flynn/tree/master/docs/content

**Comment by onnimonni** [comment]
@dabeeeenster we use separate flynn clusters for staging / production. Maybe You can do this too?

**Comment by lmars** [comment]
Docs were updated in #3521.

**Comment by SalvoLunar** [comment]
Hi @titanous,

I've followed your instructions and created a staging and production branch for my app, but when I try to git push production production:master I get this error:

```
error: src refspec production does not match any.
error: failed to push some refs to 'https://git.fsp.lunarct.ie/fourstar-production.git'
```
I've already tried to git commit some change but when I try to push I get exacly the same error.

Can you give me some advice?
