### ISSUE TITLE
Unreasonable high queue time

### ISSUE THREAD

**Issue by simon0191** [flynn/flynn#3516]
After migrating our app from heroku to flynn our queue time metric has increased unreasonably, even though the app seems to be behaving normally. We thought it was a problem of new relic so we set up App signal to compare but we are getting very similar metrics: Queue time >50 secs and some times > 90secs.

- New relic queue time metric with a lot of pikes >50secs:
![screen shot 2016-10-15 at 3 40 17 pm](https://cloud.githubusercontent.com/assets/1335661/19413285/50d56e5c-92ee-11e6-8c6c-f1fcfd0618a7.png)

- New relic queue time metric filtering out request queuing:
![screen shot 2016-10-15 at 3 40 38 pm](https://cloud.githubusercontent.com/assets/1335661/19413281/492fb608-92ee-11e6-9aa8-a748eb99fb24.png)

- Appsignal queue time metric with a lot of pikes >50secs:
![screen shot 2016-10-15 at 3 40 07 pm](https://cloud.githubusercontent.com/assets/1335661/19413294/9c63d64c-92ee-11e6-8e5c-5bcfc999a746.png)

**Comment by titanous** [comment]
The Flynn router doesn't do any queuing, check the router log for "retriable request error" to see if app backends are not responding to some requests:

```
flynn -a router log
```

You should also check the memory consumption of your app, we've seen this symptom before when the memory limit is too low. You can increase it with this command (the default is 1GB):

```text
flynn limit set web memory=3GB
```

**Comment by titanous** [comment]
It's also worth noting two things:

1. The "request queuing time" that New Relic shows is the time between the Flynn router receiving the request and the New Relic agent in your app seeing the request. This is done by setting the `X-Request-Start` header in the router to the timestamp that the request was received.
2. New Relic uses the numeric mean for that chart, so it can be very skewed. A single offset of a few minutes will skew the chart depending on the throughput.

**Comment by titanous** [comment]
Was this issue resolved?

**Comment by simon0191** [comment]
@titanous After moving the app to a new flynn cluster, pikes went down from 90secs to 4secs. 4secs are better but still worse than the request queuing time reported when the app was in heroku. 
Do you think it has something to do with #3581 ?

**Comment by titanous** [comment]
Yeah, that could be the cause, try installing ntp (we will add it to the next stable release's AMI).

**Comment by simon0191** [comment]
Done. Do I have to restart the servers or anything else? or is it enough to just install ntp?

**Comment by titanous** [comment]
That should be enough, it might take a bit of time for the clock to skew towards accuracy, I forget what the exact behavior is.

**Comment by simon0191** [comment]
@titanous pikes completely disappeared after installing ntp. Thanks! I'll close the issue.

In the screenshot, the vertical line is the time of installation of ntp:
<img width="718" alt="screen shot 2016-10-30 at 6 59 00 pm" src="https://cloud.githubusercontent.com/assets/1335661/19841131/4f9f28a2-9ed3-11e6-940d-e8cb1e9c1dae.png">
