### ISSUE TITLE
Rename app

### ISSUE THREAD

**Issue by mfclarke** [flynn/flynn#3517]
Hi, is it possible to rename an existing app in a cluster? Or do I need to totally recreate it?

**Comment by lmars** [comment]
@mfclarke we don't have a UI for renaming apps because there are multiple places where the name appears, and updating all of those references would be cumbersome, so instead the name is immutable.

You can however export / import into a new app:

```
$ flynn -a old-app export --file export.tar
$ flynn import --name new-app --file export.tar
$ flynn -a new-app remote add
```
