### ISSUE TITLE
How to find which app owns a running process?

### ISSUE THREAD

**Issue by simon0191** [flynn/flynn#3528]
`flynn ps` gives me the processes IDs with their respective release ID. In order to find the app that owns a specific process I had to go the dashboard to manually search for the release ID. Is there an easy way through the command line to find the application that owns a running process?
```
$ flynn ps
ID                                              TYPE  STATE  CREATED        RELEASE
ip1006207-ce89ccbb-88af-48cf-9f74-4db4ab15d4f6  run   up     2 days ago     0b3611cf-8811-47de-b291-5976f170ca1b
ip1000145-c0079eec-f85e-4c7e-96d3-1e4e2788608c  run   up     11 hours ago   0b3611cf-8811-47de-b291-5976f170ca1b
ip1007108-5970cabb-c354-4a82-b6a0-0d5ba39fc1a4  run   up     10 hours ago   0b3611cf-8811-47de-b291-5976f170ca1b
ip1006207-d007e647-8479-4ac2-a564-8de936bf6dcc  run   up     10 hours ago   0b3611cf-8811-47de-b291-5976f170ca1b
ip1006207-42eb610e-1c1d-46eb-a974-251cdabe7614  run   up     9 hours ago    0b3611cf-8811-47de-b291-5976f170ca1b
ip1007108-41c4121a-9b7d-45be-a788-e87c89687f77  web   up     9 minutes ago  c2849173-cff3-4e7e-9f23-cca7287f9f6b
ip1006207-89baa198-92fb-4ec9-87f7-51b1efce6be0  web   up     9 minutes ago  c2849173-cff3-4e7e-9f23-cca7287f9f6b
```

**Comment by josephglanville** [comment]
`flynn ps` only shows processes for the currently selected application. If you don't specify it like `flynn -a <app_name> ps` it's automatically infered from the git remote if you are currently in a git repository.

The `flynn` command doesn't actually have a `ps` command for listing all running processes for all apps, so they are always from a single app. If you do want to see all running processes for all apps you can execute `flynn-host ps` from a cluster node, this is a more low level administrative CLI compared to the user/consumer level `flynn` CLI.

**Comment by simon0191** [comment]
For the output pasted above I ran the command inside an app repo but the releases' IDs of the first 5 processes belong to the postgres application.

**Comment by josephglanville** [comment]
Interesting, those are likely caused by running `flynn pg` commands.
I think there is an open issue on them not terminating if you don't correctly exit the command.
