### ISSUE TITLE
Issue when connecting to Postgres from an Elixir/Phoenix app

### ISSUE THREAD

**Issue by jaimeiniesta** [flynn/flynn#3531]
Hello, I'm following [a blog post](http://nsomar.com/how-to-use-flynn-to-deploy-a-phenix-app/) about deploying an Elixir / Phoenix app in Flynn. Everything goes well as per the post, but if I also try to have a postgres db and connect to it I get into these errors. 

Any idea why it might be failing? It complains about "ssl not available"

```
$ flynn run mix ecto.migrate

14:30:03.227 [error] Postgrex.Protocol (#PID<0.210.0>) failed to connect: ** (Postgrex.Error) ssl not available
** (DBConnection.ConnectionError) connection not available because of disconnection
(db_connection) lib/db_connection.ex:718: DBConnection.checkout/2
(db_connection) lib/db_connection.ex:619: DBConnection.run/3
(db_connection) lib/db_connection.ex:921: DBConnection.run_meter/3
(db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
(ecto) lib/ecto/adapters/postgres/connection.ex:82: Ecto.Adapters.Postgres.Connection.execute/4
(ecto) lib/ecto/adapters/sql.ex:228: Ecto.Adapters.SQL.sql_call/6
(ecto) lib/ecto/adapters/sql.ex:178: Ecto.Adapters.SQL.query!/5
(ecto) lib/ecto/adapters/postgres.ex:69: Ecto.Adapters.Postgres.execute_ddl/3
````

**Comment by josephglanville** [comment]
It looks like you have forced SSL on?
Are you explicitly connecting or does your framework use the `DATABASE_URL` environment variable?

**Comment by jaimeiniesta** [comment]
That was it, thanks!

Phoenix has a `config/prod.exs` file where access to the database is configured. One of the default options (which works fine in Heroku) enables SSL for the database. I've turned it off and now it works fine.

The framework uses the `DATABASE_URL` environment variable.

Now I wonder, doesn't disabling SSL in the DB connection represent a risk? I guess it doesn't because the DB is within Flynn, as is the app, we're not connecting to an external DB.

**Comment by josephglanville** [comment]
Yeah the risk is somewhat mitigated by the fact the VXLAN overlay network is isolated. That said we are hoping to support SSL at some stage but don't right now.

**Comment by jaimeiniesta** [comment]
That's great, thanks!
