### ISSUE TITLE
Overlay network encryption

### ISSUE THREAD

**Issue by toonsevrin** [flynn/flynn#3533]
Encrypt and authorize all internal communication

**Comment by titanous** [comment]
Indeed, the plan is to use Wireguard.

**Comment by toonsevrin** [comment]
Looks great! What would you recommend us to do for now? All internode traffic is exposed to the web.

**Comment by titanous** [comment]
For now, run a firewall that only allows communication between cluster hosts.

**Comment by toonsevrin** [comment]
Definitely, and then we'd just encrypt all our services with ssl (against mitm)?

**Comment by titanous** [comment]
The router supports TLS termination, are you expecting MITM in the internal network? Currently Flynn is not capable of defending against that threat model, but it will eventually.

**Comment by toonsevrin** [comment]
I see, we are developing an online game, which is not really a friendly environment, so we are preparing for the worst haha. I'm considering to run our services in a seperate flynn cluster on a vLan (within an OVH vRack, which should give propper data isolation). The tls termination would be perfect for this!

Our game instances require an even cheaper host (Hetzner). This host does not have any data isolation, which means we'll still have to find a solution to that one. Any reccomendations?

**Comment by titanous** [comment]
For now, only use hosting providers that you trust not to tamper with your network.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
