### ISSUE TITLE
Unable to remove postgres resource

### ISSUE THREAD

**Issue by jaimeiniesta** [flynn/flynn#3534]
I have a Rails app with a Postgres DB (and a Redis DB as well) in Flynn.

I tried to remove the Postgres resource using the dashboard, but all it it did was remove the environment variables, creating a new release -- but the DB is still there and it can't be removed.

I've also tried to remove it using the CLI but it's not clear to me what should I use for `resource`:

`flynn resource remove <provider> <resource>``

The dashboard logs just show a lot of "CRASHED" but no more info. Is there a way that I can debug this?

**Comment by jaimeiniesta** [comment]
Forgot to say that's in v20160918.1

**Comment by lmars** [comment]
@jaimeiniesta 

> the DB is still there and it can't be removed.

When you say it is "still there", are you talking about it still appearing in the dashboard? Does it appear when running `flynn resource` form the command line?

> it's not clear to me what should I use for `resource`

That should be the resource ID (visible in `flynn resource`):

```
$ flynn resource add postgres
Created resource 102a5485-c2db-49d3-9343-35e761623ba1 and release a4f99930-c7ff-434d-bff2-05001d8753fd.

$ flynn resource
ID                                    Provider ID                           Provider Name
102a5485-c2db-49d3-9343-35e761623ba1  4dc63c92-d30a-45dc-9ca8-89ca37327c39  postgres

$ flynn resource remove postgres 102a5485-c2db-49d3-9343-35e761623ba1
Deleted resource 102a5485-c2db-49d3-9343-35e761623ba1, created release dc219eb2-3f22-49e4-8f4a-895603ae497d.

$ flynn resource
ID  Provider ID  Provider Name
```

If `flynn resource` is empty then the database has been deleted, there may however be a bug in the dashboard where the resource is cached.

**Comment by jaimeiniesta** [comment]
Thanks, the resource is being shown on the dashboard, and it also appears from the command line.

When trying to remove it from the command line it just complains that "Something went wrong":

```
$ flynn resource remove postgres fe091fc0-3ed1-4f14-914c-eb6e724d9eb0
unknown_error: Something went wrong
```

If there's a way to show more info, the logs, or enable a verbose mode for the CLI, let me know :)

**Comment by lmars** [comment]
@jaimeiniesta check both the controller and postgres logs to see if they give more information on the error:

```
$ flynn -a postgres log --process-type web --raw-output
$ flynn -a controller log --process-type web --raw-output
```

**Comment by jaimeiniesta** [comment]
The postgres log gets added these 3 lines whenever I try to remove the resource:

```
t=2016-10-19T00:45:29+0000 lvl=info msg="request started" component=postgres-api req_id=ac02c3af-4454-4a88-abeb-132257fa2ac8 method=DELETE path=/databases client_ip=100.100.57.3
t=2016-10-19T00:45:29+0000 lvl=eror msg="ERROR: database \"21f1bd1f4f6d587c07ec90ee35ca3535\" does not exist (SQLSTATE 3D000)" component=postgres-api req_id=ac02c3af-4454-4a88-abeb-132257fa2ac8
t=2016-10-19T00:45:29+0000 lvl=info msg="request completed" component=postgres-api req_id=ac02c3af-4454-4a88-abeb-132257fa2ac8 status=500 duration=7.028837ms
```

**Comment by lmars** [comment]
Hmm ok that is interesting, can you please run `sudo flynn-host collect-debug-info` on a host in your cluster and post the resulting gist link? That will help us debug what went wrong here.

Once you've done that, you can just manually delete the resource record in the controller database (since the actual PostgreSQL database already got deleted):

```
$ flynn -a controller pg psql -- -c "DELETE FROM app_resources WHERE resource_id = 'fe091fc0-3ed1-4f14-914c-eb6e724d9eb0'; UPDATE resources SET deleted_at = now() WHERE resource_id = 'fe091fc0-3ed1-4f14-914c-eb6e724d9eb0'"
```

**Comment by jaimeiniesta** [comment]
> Hmm ok that is interesting, can you please run `sudo flynn-host collect-debug-info` on a host in your cluster and post the resulting gist link? That will help us debug what went wrong here.

Sure, but I'm not sure how to ssh into the host so I can run that from there? I mean, the host was created by the flynn install, I don't have a password, or do I?

**Comment by lmars** [comment]
The installer creates an SSH keypair and stores it in `$HOME/.flynn`, so you can use that to SSH to the servers, see:

https://flynn.io/docs/installation/cloud#ssh-access

**Comment by jaimeiniesta** [comment]
I'm trying to SSH into the server as explained on the docs, but it still asks for the password:

```
$ ssh -i ~/.flynn/installer/keys/flynn ubuntu@<<HOST_IP_GOES_HERE>>
ubuntu@104.131.115.125's password:
```

**Comment by lmars** [comment]
Which cloud provider are you using? On DigitalOcean the user should be `root`, and on Azure `flynn` (we have [updated the docs](https://github.com/flynn/flynn/pull/3526) but haven't deployed the change yet).

**Comment by jaimeiniesta** [comment]
Ah, cool! I'm on DigitalOcean, using `root` worked fine, thanks.

**Comment by jaimeiniesta** [comment]
@lmars I've sent you the link to the gist with debug information via Olark in your site - to avoid posting it publicly.

**Comment by jaimeiniesta** [comment]
I was finally able to remove the postgres resource with your instructions, thanks @lmars 

I've also tried adding and removing one and it works now, it must have been a temporary glitch.

**Comment by lmars** [comment]
@jaimeiniesta ok glad you managed to remove it eventually! Can you send the debug logs to logs@flynn.io?

**Comment by jaimeiniesta** [comment]
Sure!

**Comment by lmars** [comment]
@jaimeiniesta did you reboot after creating the resource? Some of the logs are empty, could you instead send us a tarball of the log files in `/var/log/flynn`?

**Comment by jaimeiniesta** [comment]
Yep, I did reboot the server. I'll send the logs!

**Comment by lmars** [comment]
@jaimeiniesta the issue here was that you ran `rake db:reset` which dropped the database, and then subsequent requests to deprovision the database failed because it no longer existed.

I have opened #3537 to track fixing this bug.
