### ISSUE TITLE
slugrunner: User cannot write to /dev/stdout

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3535]
Slug based jobs run as the `nobody` user (see [here](https://github.com/flynn/flynn/blob/master/slugrunner/runner/init#L59)) but that user does not have write permissions to `/dev/stdout` as it is either owned by root:

```
# use a non-tty stdin so the job has no TTY
$ flynn run ls -l /dev/stdout < /dev/null
prw-r--r-- 1 root root 0 Oct 19 00:00 /dev/stdout

$ flynn run bash <<< 'echo > /dev/stdout'
bash: line 1: /dev/stdout: Permission denied
```

or is a symlink to the root owned `/dev/pts/0` for TTY jobs:

```
$ flynn run ls -l /dev/stdout
lrwxrwxrwx 1 root root 15 Oct 19 00:01 /dev/stdout -> /proc/self/fd/1

$ flynn run ls -l /proc/self/fd/1
lrwx------ 1 nobody nogroup 64 Oct 19 00:01 /proc/self/fd/1 -> /dev/pts/0

$ flynn run ls -l /dev/pts/0
crw--w---- 1 root tty 136, 0 Oct 19 00:02 /dev/pts/0

$ flynn run bash -c 'echo foo > /dev/stdout'
bash: /dev/stdout: Permission denied
```

We should `chown nobody /dev/std{in,out,err}` and add the `nobody` user to the `tty` group.

**Comment by sleighter** [comment]
Thanks @lmars. This seems to have made a difference, but it was not sufficient to solve the problem I'm having with using PDFKit/wkhtmltopdf from ruby apps.

The PDF content is now appearing in the logs, but the application isn't capturing the child-process output. The application seems to hang while waiting for the child-process output, then fails with the same `command failed` error seen before.

**Comment by lmars** [comment]
@sleighter ah ok I see the issue there.

Rather than symlinking `/dev/stdout` to `/proc/self/fd/0`, Flynn creates `/dev/stdout` as a FIFO which is connected to the container's stdout (this is because `/proc/self/fd/0` is a symlink to a socket for the main process in the container, and you cannot call `open(2)` on a socket).

This however breaks forked processes which expect `/dev/stdout` to be *their* stdout, rather than the container's.

Let me play around and see if we can get this to work.

**Comment by lmars** [comment]
@sleighter before running PDFKit, you could run `ln -fs /proc/self/fd/1 /dev/stdout` (perhaps as part of your boot sequence)

**Comment by sleighter** [comment]
@lmars I assume that you mean during application boot, so I added that to my app initialization. However, the 'nobody' user can't perform that action, I get this message in the logs:
`ln: cannot remove ‘/dev/stdout’: Permission denied`
