### ISSUE TITLE
What should happen when a node fails

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3543]
If I have a 3 node cluster and this morning one node had some kind of failure (still to be determined) and this brought down the whole cluster.

I thought the point of having 3 nodes in a cluster was to cover this sort of situation so you app continues to run on the remaining 2.

**Comment by josephglanville** [comment]
One node going down shouldn't drastically affect things unless the system PostgreSQL primary was running on that node, in that case there will be a period of recovery before the cluster will resume normal operation. This shouldn't affect user applications unless they are using the built in PostgreSQL database.

Could you provide more details on what you considered "bringing the whole cluster down", whether or not the cluster recovered after some time or not and the debug info collected with `flynn-host collect-debug-info`, ideally from each node if it didn't recover. You can email to logs@flynn.io and I will take a look.

**Comment by dottodot** [comment]
I rather foolishly created a new cluster and forgot to get the logs from 2 of them, just the one that failed so I'll email you those to see if there is anything you can see from that.

At the time of the failure all the apps where reporting service unavailable.

**Comment by josephglanville** [comment]
Going to close this for now, if you run into this again please open a new issue with the debug logs. Thanks!
