### ISSUE TITLE
How can I keep a certain number of release history of my app?

### ISSUE THREAD

**Issue by koolay** [flynn/flynn#3551]
Have a configuration for  keeping the latest some relases, and remove older releases automatically?

**Comment by lmars** [comment]
@koolay this is controlled via the `gc.max_inactive_slug_releases` app meta variable.

You can check the current value with `flynn meta`:

```
$ flynn meta
KEY                            VALUE
gc.max_inactive_slug_releases  10
```

and set it with:

```
$ flynn meta set gc.max_inactive_slug_releases=20
```

**Comment by koolay** [comment]
@lmars 

```
$ flynn meta
KEY                            VALUE
gc.max_inactive_slug_releases  3
```

I changed the value,  but there are still six releases on the board ui.
How to trigger it to work?

**Comment by lmars** [comment]
@koolay have you created more than six releases? In other words, is it cleaning any releases or is the number of releases continuing to increase?

The `gc.max_inactive_slug_releases` actually controls how many releases with distinct slugs to keep (i.e. how many releases created via `git push flynn master`), so you can end up with more releases if you for example create ones with `flynn env set`.

**Comment by koolay** [comment]
@lmars 
by `git push flynn master` ,  there are seven releases on board .
Actually I had set `gc.max_inactive_slug_releases = 3`,  but cleaning not work.

**Comment by koolay** [comment]
it is a BUG?

**Comment by lmars** [comment]
@koolay apologies I missed your last comment. Please run `sudo flynn-host collect-debug-info` on a host in your cluster and send the resulting gist to logs@flynn.io.
