### ISSUE TITLE
3 node cluster went down, Mongo never came back

### ISSUE THREAD

**Issue by nicatronTg** [flynn/flynn#3552]
```
shank@exo-flynn-01:~$ flynn-host --version
v20161017.1
```

Over the weekend I installed a fresh flynn cluster on three brand new Ubuntu 14.04 LTS VMs in a test environment to evaluate moving some side projects to a flynn cluster. Anyway, I got everything working using the normal docs: three flynn nodes running in one cluster with an app deployed and everything seemingly good on the dashboard.

For various reasons, I suspended the Ubuntu VMs a couple times all at once and resumed them, but later on, evidently something happened and they crashed. I rebooted the Ubuntu VMs and expected flynn to recover automatically, but it didn't. Things like the dashboard weren't working, so I googled around and found the `flynn-host fix` command and gave it a try. It seemed to resolve some issues (the dashboard and app routing were working) but Mongo never came back.

The dashboard doesn't show Mongo as a configured resource anymore, oddly enough. The health page seems to show everything but Mongo running, and `flynn-host fix -n 3` doesn't seem to help.

No apps were configured with Mongo -- I installed it from the providers page and hit provision.

![screen shot 2016-10-21 at 10 06 25 pm](https://cloud.githubusercontent.com/assets/532647/19616818/e355757e-97da-11e6-957b-fe0c557897f1.png)

![screen shot 2016-10-21 at 10 08 32 pm](https://cloud.githubusercontent.com/assets/532647/19616820/f4aee026-97da-11e6-93de-983088ad7747.png)

```
shank@exo-flynn-02:~$ flynn-host fix -n 3
INFO[10-21|22:07:11] found expected hosts                     n=3
INFO[10-21|22:07:11] ensuring discoverd is running on all hosts
INFO[10-21|22:07:11] checking flannel
INFO[10-21|22:07:11] flannel looks good
INFO[10-21|22:07:11] waiting for discoverd to be available
INFO[10-21|22:07:11] checking for running controller API
INFO[10-21|22:07:11] found running controller API instances   n=2
INFO[10-21|22:07:11] found controller instance, checking critical formations
INFO[10-21|22:07:11] checking status of sirenia databases
INFO[10-21|22:07:11] checking for database state              db=postgres
INFO[10-21|22:07:11] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[10-21|22:07:11] found running leader                     fn=FixSirenia service=postgres
INFO[10-21|22:07:11] found running instances                  fn=FixSirenia service=postgres count=3
INFO[10-21|22:07:11] getting sirenia status                   fn=FixSirenia service=postgres
INFO[10-21|22:07:11] cluster claims to be read-write          fn=FixSirenia service=postgres
INFO[10-21|22:07:11] checking for database state              db=mariadb
INFO[10-21|22:07:11] skipping recovery of db, no state in discoverd db=mariadb
INFO[10-21|22:07:11] checking for database state              db=mongodb
INFO[10-21|22:07:11] checking sirenia cluster status          fn=FixSirenia service=mongodb
INFO[10-21|22:07:11] found running leader                     fn=FixSirenia service=mongodb
INFO[10-21|22:07:11] found running instances                  fn=FixSirenia service=mongodb count=3
INFO[10-21|22:07:11] getting sirenia status                   fn=FixSirenia service=mongodb
INFO[10-21|22:07:25] getting service metadata                 fn=FixSirenia service=mongodb
INFO[10-21|22:07:25] getting primary job info                 fn=FixSirenia service=mongodb job.id=exoflynn03-db634360-e66f-47e8-953c-5ebefed628af
INFO[10-21|22:07:25] getting sync job info                    fn=FixSirenia service=mongodb job.id=exoflynn01-bdf389e5-3c0c-4e0b-bde7-6f721a27034c
INFO[10-21|22:07:25] terminating unassigned sirenia instances fn=FixSirenia service=mongodb
INFO[10-21|22:07:25] starting sync job                        fn=FixSirenia service=mongodb job.id=exoflynn01-5c3ca0a6-c901-4c9e-964b-7575985f1737
INFO[10-21|22:07:26] waiting for instance to start            fn=FixSirenia service=mongodb job.id=exoflynn01-5c3ca0a6-c901-4c9e-964b-7575985f1737
INFO[10-21|22:07:26] waiting for cluster to come up read-write fn=FixSirenia service=mongodb
22:12:46.674138 host.go:157: timeout waiting for expected status
```

**Comment by lmars** [comment]
@nicatronTg please run `sudo flynn-host collect-debug-info` on each node in your cluster and sending the resulting gist links to logs@flynn.io.

**Comment by nicatronTg** [comment]
@lmars do you have a particular location you want tarballs uploaded?

```
INFO[10-22|09:21:04] Total size of 220335188 bytes exceeds gist limit, falling back to tarball.
INFO[10-22|09:21:16] created tarball containing debug information at /tmp/flynn-host-debug028866571/flynn-host-debug.tar.gz
```

**Comment by nicatronTg** [comment]
Uploaded & sent.

**Comment by josephglanville** [comment]
@nicatronTg thanks we have received the logs, I will look into this today.

**Comment by josephglanville** [comment]
I think I have identified the issue. It seems that there is a bug in the MongoDB appliance which is only hit when both of the existing Sync and Primary peers go down and when resurrected have different IP addresses.

Thanks for reporting!

**Comment by nicatronTg** [comment]
Oh! That would actually make a lot of sense! Is there any short term fix I can apply, or at least, purge the dead Mongo appliance and make a new one?

**Comment by josephglanville** [comment]
Unfortunately I don't think a quick fix is possible in this case, it would probably be best to purge the state and start again unless you have data that you need to retrieve from the MongoDB cluster (which I could assist with on IRC if needed).

This procedure will remove all of the current permissions etc created by the resource provider so you will need to re-create any resources. Removing resources is likely to fail on not being able to delete missing users/databases however so you may need to work around that by just creating new ones and ignoring the old ones.
It's likely a better idea to create a new cluster if that wouldn't be too time consuming for you but this would work if that isn't an option.

To purge the appliance state start by scaling down the `mongodb` cluster.
```
$ flynn -a mongodb scale mongodb=0
```
This will stop all running MongoDB processes.

Then the persistent cluster state in `discoverd` needs to be purged so that we can bootstrap a new cluster state. These commands need to be run from a cluster node.

First get the index of the current service meta.
```
$ curl -s http://127.0.0.1:1111/services/mongodb/meta | jq '.index'
```

Then set it to empty, substituting $INDEX for the value obtained in the previous command.
```
 curl -s -H "Content-Type: application/json" -X PUT -d '{"data":"{}", "index": $INDEX}' http://127.0.0.1:1111/services/mongodb/meta
```

Finally scale up the MongoDB cluster again:
```
$ flynn -a mongodb scale mongodb=3
```
