### ISSUE TITLE
Question: Where are the cli docs in the repo?

### ISSUE THREAD

**Issue by nicatronTg** [flynn/flynn#3553]
I was looking for the CLI docs stored in the repo, but I couldn't find them. I'm looking for the source to `https://flynn.io/docs/cli` but it's like it doesn't exist. Is it not versioned or generated on the fly?

![screen shot 2016-10-21 at 10 35 42 pm](https://cloud.githubusercontent.com/assets/532647/19616949/022673f0-97df-11e6-8e92-f6bd53df3b46.png)

**Comment by lmars** [comment]
@nicatronTg the CLI usage and examples in the docs are generated from the CLI source code (e.g. here is the usage for `flynn create`: https://github.com/flynn/flynn/blob/master/cli/app.go#L14-L32).

I believe the leading paragraphs on that page are stored in the Flynn website repo, which is private.

Are you looking to contribute some changes to that page?

**Comment by nicatronTg** [comment]
@lmars I was just wondering because I considered adding the `flynn-host fix` command to that page, though it doesn't really fit as it's not considered part of the cli tool. That's my 2c.

Thanks!
