### ISSUE TITLE
Resizing a host

### ISSUE THREAD

**Issue by jaimeiniesta** [flynn/flynn#3555]
If a host is resized (say for example you start with a 2Gb host and then resize it to 8 Gb), does Flynn need to be reconfigured / reinstalled, or will it automatically detect all the RAM and disk space in the system?

**Comment by josephglanville** [comment]
Flynn will automatically use all new resources available. However due the current nature of the Flynn scheduler we recommend using uniform sized Flynn nodes in your cluster.

**Comment by josephglanville** [comment]
Also if you are intending on replacing a host in a cluster you should read the production docs, specifically this section on safely replacing hosts: https://flynn.io/docs/production#replacing-hosts

**Comment by jaimeiniesta** [comment]
Thank you, after https://github.com/flynn/flynn/issues/3557 I see that better than resizing a host, a better option is adding more hosts with the same size to the cluster.
