### ISSUE TITLE
Total RAM in a cluster?

### ISSUE THREAD

**Issue by jaimeiniesta** [flynn/flynn#3557]
Sorry for the naïve question but I don't really understand how a cluster works, so here it goes:

If I have a cluster with 3 instances and each instance has 8 Gb of RAM, does my cluster have a total of 24 Gb of RAM available to the apps?

I guess it doesn't, and that the only reason for having several instances is high availability?

**Comment by josephglanville** [comment]
Additional cluster nodes provide both more capacity (i.e RAM/CPU for applications) and high availability.

So in your case yes, there should be roughly 24GB of RAM available to applications minus some RAM for Flynn and OS level system services.

**Comment by jaimeiniesta** [comment]
Awesome! Thanks :)
