### ISSUE TITLE
Removing a discoverd service doesn't delete service meta

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#3558]
Removing a service from discoverd leaves the service meta intact which will be returned from calls to `Subscribe`, as such will be returned when creating a service stream. I discovered this while investigating a work around for #3552 and was quite surprised by the behavior.

I think we should change `RemoveService` to also delete the service meta.

Thoughts @lmars, @titanous?

**Comment by lmars** [comment]
Yes I think removing a service should also remove the service meta too.
