### ISSUE TITLE
Help contributing documentation

### ISSUE THREAD

**Issue by amingilani** [flynn/flynn#3561]
There are a few best practices on start that are undocumented, e.g. sharing clusters between teams, etc.

Would you like me to write a tutorial on that? Any preferences on sharing clusters? I pgp encrypted the token and the cert before sending it out to the team.

**Comment by lmars** [comment]
@amingilani the Flynn documentation can be found here:

https://github.com/flynn/flynn/tree/master/docs/content

We'd be more than happy for you to make some improvements :smile:.

As for sharing cluster details, I personally use 1password but GPG encryption also sounds fine. In future we will have more robust solutions (see the [Security Improvements](https://github.com/flynn/flynn/projects/1)).
