### ISSUE TITLE
Total CPU cores in a cluster?

### ISSUE THREAD

**Issue by jaimeiniesta** [flynn/flynn#3562]
In https://github.com/flynn/flynn/issues/3557 we see that adding additional hosts to the cluster provides more RAM and CPU.

Does that apply to the cores? I mean, If I have a cluster of 3 hosts with 2 cores each, does that mean that my apps have 6 cores available? Or only 2?

**Comment by jaimeiniesta** [comment]
As a reference, a Standard-1X Heroku dyno reports 8 cores:

```
~ $ grep -c processor /proc/cpuinfo
8
```

**Comment by josephglanville** [comment]
Your jobs will only see the number of cores available on the local machine, i.e as many cores as a single node has.

All jobs on the same node share the CPU cores however, so whilst the jobs do see all the cores and can "use" them all at the same time they don't necessarily get all of the performance as they are sharing with the other jobs on the same cluster node.

Does that all make sense?

**Comment by jaimeiniesta** [comment]
Makes sense, so, regarding parallelism, my jobs will have 2 cores available in that scenario; adding more hosts will increase CPU in the sense that there are more CPUs to share, not in having more cores available.

So in the above scenario, a job can have 100% CPU usage on 2 cores at most.

**Comment by josephglanville** [comment]
Yep, precisely.
