### ISSUE TITLE
Request to Share Terraform Templates/Examples

### ISSUE THREAD

**Issue by sleighter** [flynn/flynn#3567]
Although Flynn is not strongly opinionated about infrastructure management, the stability and maintainability of Flynn clusters requires well-designed infrastructure. Anyone coming from Heroku to Flynn is unlikely to have experience with or buy-in to any particular management tool.

To this end, providing example or reference templates for infrastructure management tools would be very valuable. I understand that the Flynn team uses Terraform in-house, so it's probably easiest to start there. Sharing those templates, or snippets of them, would be very helpful in getting started with Flynn. Moreover, without good tooling, collecting debug information from Flynn clusters can be very tedious. Encouraging infrastructure parity between the dev-team and public should ease Flynn debugging overall.

I understand that the Flynn team likely wants to avoid supporting infrastructure and that providing full templates for multiple management tools is out of scope for this project, but sharing examples of internal best-practices would be very valuable to the community.

**Comment by tombh** [comment]
I'm looking for any Terraform/Ansible/Chef/Puppet setups on the web, but can't find anything of note anywhere. Anyone have any pointers?

**Comment by ndbroadbent** [comment]
Would like to add my +1 to this issue. I'd like to set up a production cluster on AWS, with a multiple-az VPC for high availability. But I'm struggling to find some docs that talk about infrastructure. A production-ready terraform setup would be amazing.

**Comment by titanous** [comment]
The Flynn team has no plans to maintain or provide this type of automation, however this a good idea for a community project.
