### ISSUE TITLE
Bootstrapping a Cluster with a Backup Times Out Waiting for Postgres

### ISSUE THREAD

**Issue by sleighter** [flynn/flynn#3569]
When attempting to bootstrap a cluster with the `--from-backup` option, the bootstrap fails with this error:

```
+ flynn-host bootstrap --from-backup ./backup-to-restore.tar --min-hosts 5 --discovery https://discovery.flynn.io/clusters/[cluster-id]
17:20:12.535750 check online-hosts
17:22:16.193759 run-app discoverd
17:22:16.698458 run-app flannel
17:22:16.884780 wait-hosts wait-hosts
17:22:18.401666 run-app postgres
17:22:48.461552 run-app postgres error: bootstrap: timed out waiting for job event
```

This log is from the node running `bootstrap`
https://gist.github.com/anonymous/46099d0198a8aab6775be07225dd4461

These are logs from the other nodes:
https://gist.github.com/2925f59ca93ebad47d44ca629e972aef
https://gist.github.com/e507d58bfbf51bf82de019b37df05437
https://gist.github.com/75e415a0e21f90d44beec49f36a0fb66
https://gist.github.com/06eb37f6119e704c48e41075466934d7

**Comment by nusnewob** [comment]
I'm having the same , restore fails when `Flynn` tries to start up `postgres`

```
23:19:39.260759 check online-hosts
23:19:39.271262 run-app discoverd
23:19:40.016380 run-app flannel
23:19:40.661367 wait-hosts wait-hosts
23:19:40.668404 run-app postgres
23:20:10.753178 run-app postgres error: bootstrap: timed out waiting for job event
```

logs from bootstrap node:
https://gist.github.com/2a795bb8e0cd84aea657736e7a24b9c6

logs from other nodes:
https://gist.github.com/2a9455d2150a0e448eb4f021d9466d78
https://gist.github.com/fe70147ebe8630a1fdc267ca3f6d9580
https://gist.github.com/0ed6a1c1b83baf82c1c690deaee79078

**Comment by sleighter** [comment]
@nusnewob 
In my case, the issue was that I was using an S3 backend for the blobstore. The new cluster hosts didn't have correct IAM permissions for the blobstore S3 bucket that was configured in the backup. This led to the timeout when trying to bring up Postgres.

What blobstore backend are you using?

**Comment by nusnewob** [comment]
I'm using S3 backend for blobstore as well. My IAM policy for my instances looks like this,

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:GetBucketLocation"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::datastore.flynn-domain",
        "arn:aws:s3:::datastore.flynn-domain/*"
      ]
    }
  ]
}
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
