### ISSUE TITLE
When a single-node cluster reboots, mongo vanishes

### ISSUE THREAD

**Issue by Shigawire** [flynn/flynn#3572]
Similarly to https://github.com/flynn/flynn/issues/3552 my MongoDB dies when I restart a single node cluster. I've an app requiring MongoDB and would really love to continue using Flynn. 
However, I think a node should withstand a reboot without having to rebuild the entire stack.

```flynn -a appname mongodb mongo``` results in the following:

``` MongoDB shell version: 3.2.10
connecting to: leader.mongodb.discoverd:27017/f1716ca9bbaa2ac8e3ced9c306f0226e
2016-10-25T06:15:32.412+0000 I NETWORK  [thread1] getaddrinfo("leader.mongodb.discoverd") failed: Name or service not known
2016-10-25T06:15:32.420+0000 E QUERY    [thread1] Error: couldn't initialize connection to host leader.mongodb.discoverd, address is invalid :
connect@src/mongo/shell/mongo.js:231:14
@(connect):1:6```

This is the collect-debug-info gist from immediately after the reboot: https://gist.github.com/6d445d26b52847cfc5aac7950bc99a2b

I've tried applying flynn-host fix -n 1. Unfortunately, some segmentation violation occurs upon that process:

```
root@ubuntu-2gb-fra1-01:~# flynn-host fix -n 1
INFO[10-25|06:18:59] found expected hosts                     n=1
INFO[10-25|06:18:59] ensuring discoverd is running on all hosts
INFO[10-25|06:19:00] checking flannel
INFO[10-25|06:19:00] flannel looks good
INFO[10-25|06:19:00] waiting for discoverd to be available
INFO[10-25|06:19:00] checking for running controller API
INFO[10-25|06:19:00] found running controller API instances   n=1
INFO[10-25|06:19:00] found controller instance, checking critical formations
INFO[10-25|06:19:00] checking status of sirenia databases
INFO[10-25|06:19:00] checking for database state              db=postgres
INFO[10-25|06:19:00] checking sirenia cluster status          fn=FixSirenia service=postgres
INFO[10-25|06:19:00] found running leader                     fn=FixSirenia service=postgres
INFO[10-25|06:19:00] found running instances                  fn=FixSirenia service=postgres count=1
INFO[10-25|06:19:00] getting sirenia status                   fn=FixSirenia service=postgres
INFO[10-25|06:19:00] cluster claims to be read-write          fn=FixSirenia service=postgres
INFO[10-25|06:19:00] checking for database state              db=mariadb
INFO[10-25|06:19:00] skipping recovery of db, no state in discoverd db=mariadb
INFO[10-25|06:19:00] checking for database state              db=mongodb
INFO[10-25|06:19:00] checking sirenia cluster status          fn=FixSirenia service=mongodb
INFO[10-25|06:19:00] no running leader                        fn=FixSirenia service=mongodb
INFO[10-25|06:19:00] found running instances                  fn=FixSirenia service=mongodb count=3
INFO[10-25|06:19:00] getting sirenia status                   fn=FixSirenia service=mongodb
INFO[10-25|06:19:00] getting service metadata                 fn=FixSirenia service=mongodb
INFO[10-25|06:19:00] getting primary job info                 fn=FixSirenia service=mongodb job.id=ubuntu2gbfra101-1b4397fc-163d-4a51-8523-f986dbab606b
INFO[10-25|06:19:00] terminating unassigned sirenia instances fn=FixSirenia service=mongodb
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x729021]

goroutine 1 [running]:
panic(0xb20da0, 0xc4200100a0)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:500 +0x1a1
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc420015410, 0x0, 0x0, 0x0, 0xb20da0, 0xc4200100a0)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x222
github.com/flynn/flynn/pkg/shutdown.Exit()
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x6a
panic(0xb20da0, 0xc4200100a0)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:458 +0x243
github.com/flynn/flynn/host/fixer.(*ClusterFixer).FixSirenia(0xc42016ec90, 0xbeb8ce, 0x7, 0x0, 0x2)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/fixer/sirenia.go:111 +0xbe1
github.com/flynn/flynn/host/fixer.(*ClusterFixer).Run(0xc42016ec90, 0xc42028b060, 0xc42028b0c0, 0x0, 0xc42028b0c0)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/fixer/fixer.go:122 +0x1089
github.com/flynn/flynn/host/fixer.(*ClusterFixer).Run-fm(0xc42028b060, 0xc42028b0c0, 0xc4200d7170, 0x3)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/cli/fix.go:8 +0x3e
github.com/flynn/flynn/host/cli.Run(0x7ffc633898cf, 0x3, 0xc420209ba0, 0x2, 0x2, 0xc4201d7c01, 0xc68ce8)
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/cli/cli.go:57 +0x3ca
main.main()
	/tmp/tmp.Qxrkc8u1kZ/src/github.com/flynn/flynn/host/host.go:149 +0x4d4
```


And this is the collect-debug-info gist AFTER I've tried to use ```flynn-host fix``` command: 
https://gist.github.com/4d8089d8eaed06dafd7643a0ef1a40c0

Maybe this helps to identify the issue? I've been able to reproduce it on my local VMWare machine and DigitalOcean instances...

In that other ticket, one reply states 

> I think I have identified the issue. It seems that there is a bug in the MongoDB appliance which >is only hit when both of the existing Sync and Primary peers go down and when resurrected >have different IP addresses.
>
>Thanks for reporting!

Which is also the same case here, if I am not mistaking?

**Comment by josephglanville** [comment]
@Shigawire I am looking at this now, I think it's likely the same root cause but will keep this issue open incase I discover differently. Thanks.

**Comment by Shigawire** [comment]
@josephglanville thank you! I can give you access to the DO instance that has this issue, as I just set it up to reproduce this issue.

**Comment by josephglanville** [comment]
@Shigawire that shouldn't be necessary, I will let you know if it would be useful however. Thanks for offering. :)

**Comment by hugoleodev** [comment]
I'm experiencing the same problem with mariadb.

**Comment by Shigawire** [comment]
@hugoleodev didn't check that, however my dashboard status shows MariaDB and MongoDB as unavailable.
