### ISSUE TITLE
Error deploying cachethq/docker:2.3.10

### ISSUE THREAD

**Issue by imjorge** [flynn/flynn#3578]
```
$ docker pull cachethq/docker:2.3.10
$ flynn docker set-push-url
$ flynn docker login
$ flynn -a cachet docker push cachethq/docker:2.3.10
[...]
flynn: image pushed, waiting for artifact creation
flynn: deploying release using artifact URI http://flynn:a943bc854c26d1449d947364c465f21d@docker-receive.discoverd?name=cachet&id=sha256:b62af40cdb2af3126a586efcb5da872865cff64df4ebd63a398cc69752acaee9
controller: resource not found
```

I have `v20160814.0`

Sent logs tarball to logs@flynn.io

/cc @lmars

**Comment by lmars** [comment]
@imjorge does the `cachet` app exist? Check `flynn apps`.

**Comment by imjorge** [comment]
No. I ran `flynn apps` after the command failed (to see if it got created
anyway) but it was not listed.

**Comment by lmars** [comment]
@imjorge you have to create the app first with `flynn create cachet` before pushing the Docker image, see https://flynn.io/docs/docker#push-an-image.

**Comment by imjorge** [comment]
indeed. after creating the app with `flynn create cachet --remote=""` i can `flynn docker push`.

@lmars how would one translate something like a `docker exec` into this?

I specifically talking about [this section on cachet docs](https://docs.cachethq.io/docs/get-started-with-docker#running-containers-manually):

```
$ docker exec -it cachet php artisan key:generate
$ docker exec -it cachet php artisan app:install
$ docker exec -it cachet php artisan config:cache
```

As I understand, when we do `flynn run` we get a container with the same filesystem as the running one, but not the running one. That way it will not do what those instructions are trying to do to the running container.

**Comment by lmars** [comment]
@imjorge if the commands need to change the filesystem of the image, they should be run at the build stage (i.e. before pushing the image to Flynn).

You could accomplish this by building your own Docker image based on `cachethq/docker`, for example with a Dockerfile like:

```
FROM cachethq/docker:2.3.10

RUN php artisan key:generate
```

do:

```
$ docker build -t my-cachet:2.3.10
$ flynn -a cachet docker push my-cachet:2.3.10
```

I haven't tested this, and you will probably need to look into exactly what those commands do (i.e. determine if they are build-time things, so should be done like above, or run-time things, so should be done with `flynn run`).
