### ISSUE TITLE
Restore overrides shipped in certificates

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3584]
I establish certificates on build with TLS_CA, TLS_CERT, and TLS_KEY. They appear to get overwritten with the subsequent restore process. @lmars believes they should be migrated automatically.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
