### ISSUE TITLE
router: add support for gzip compression

### ISSUE THREAD

**Issue by blurrcat** [flynn/flynn#3586]
It is common to have load balancers like Nginx to compress response of certain mimetypes. It seems Flynn's router doesn't have this option. Compression can be implemented in the application server, but that can be less efficient, say in a Python app.

Can you add support for this? I think at a minimum allow users to set:
- `compress_mimetyes`: a list of mimetypes to compress, e.g., "text/html,text/css" 
- `compress_level`: gzip compression level.
- `compress_min_size`: minimum file size threshold for compression

Thanks in advance.

**Comment by titanous** [comment]
I think this should be done in the application, as the router is a shared resource that we don't have per-app CPU constraints for.

**Comment by dabeeeenster** [comment]
I think it would be better to leave this decision up to the user and enable the option suggested? Even if there are caveats? Enabling it on the application server is messy and has potential performance issues.

**Comment by titanous** [comment]
@dabeeeenster There's nothing to "leave up to the user" as this is not implemented in the router currently.

The router merely routes traffic to backends, it does not do any processing of the traffic.

We may add some lightweight security features like HTTPS redirects, where they are justifiable, but what we're not going to be doing is turning the router into the next nginx with hundreds of options and features.

**Comment by dabeeeenster** [comment]
Ah I thought it might have been using NGINX to do the routing - didn't realise it was all hand-made! 

I can see the reason for not wanting to open the rabbit hole. Personally for me, force-SSL and gzip would be the only two things I would expect out of a router but I appreciate it's tricky!
