### ISSUE TITLE
docs: flynn's relationship to docker

### ISSUE THREAD

**Issue by blurrcat** [flynn/flynn#3587]
The docs is not clear on how exactly flynn uses docker. At this age when docker is burning everywhere, less susceptible readers(me) would assume docker is used when they see flynn is running everything in "containers".

Of course a quick `ps` on the flynn host shows that the docker daemon is not running and flynn/application processes are actually running under something called `containerinit`. This is all fine until the application complains it can't `mkdir /var/lib/docker/aufs/mnt/tmp-i...`, no space left on device.

I think the docs should be clear that:
* flynn does not run things in docker but uses a custom implementation
* even if your zpool is backed by a separate block device, enough space should be left on the root device for running the containers

**Comment by titanous** [comment]
The fact that we don't use Docker is documented: https://flynn.io/docs/architecture#flynn-host

We will be using ZFS for container images and temporary filesystems as soon as #3100 is merged, which will also remove the docker-based image code that you saw an error message from.
