### ISSUE TITLE
Error when installing Flynn in an openstack VM

### ISSUE THREAD

**Issue by SellamiRami** [flynn/flynn#3588]
Dear all, 

I want to install Flynn in an OpenStack VM of type Ubuntu. However when I execute the command line vagrant up I get this error that I failed to fix. 

Could you please help in fixing this error?

Here is the error: 

ubuntu@flynnvm1:~/flynn/demo$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'flynn-base' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
**The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.**

Thank you in advance for your help.

Best regards, 
Rami Sellami.

**Comment by josephglanville** [comment]
You probably want to use the graphical installer with the SSH option, docs are here: https://flynn.io/docs/installation/cloud

You could also use the manual installation process but I would only recommend it if you aren't able to use the above installation procedure as it's more involved. Docs on that process are here: https://flynn.io/docs/installation/manual

**Comment by SellamiRami** [comment]
Dear @josephglanville, 

Thank you very much for your response. I used this link [https://flynn.io/docs/installation/manual](url) and it works.

Now I want to add a cluster in order to deploy an application. However I can not recognize the information that need to put in this command: flynn cluster add -p **<tls pin> <cluster name> <controller domain> <controller key>**. 

Could you please provide me more details about these parameters?

I am very thankful for your response. 

Cheers, 
Rami Sellami

**Comment by josephglanville** [comment]
@SellamiRami the `flynn-host bootstrap` command in the manual installation process would have printed the information required to add the cluster to you command line.

**Comment by SellamiRami** [comment]
Thank your fast response @josephglanville. 

Here is the output of the command `flynn-host bootstrap`: 

```
08:25:35.041745 check online-hosts
08:25:35.042796 require-env require-env
08:25:35.042928 require-env require-env error: Missing required environment variable(s): CLUSTER_DOMAIN
```
What does it mean?

**Comment by josephglanville** [comment]
Did you follow all of the manual installation guide?
Specifically did you run the steps here: https://flynn.io/docs/installation/manual#bootstrap-flynn?

**Comment by SellamiRami** [comment]
After executing this command : 

`$ sudo \
    CLUSTER_DOMAIN=demo.localflynn.com \
    flynn-host bootstrap \
    --min-hosts 3 \
    --discovery https://discovery.flynn.io/clusters/53e8402e-030f-4861-95ba-d5b5a91b5902`

I get this output: 

`sudo: unable to resolve host flynnvm1
08:31:15.867033 check online-hosts
08:37:20.245797 check online-hosts error: timed out waiting for 3 hosts to come online (currently 0 online)

The following hosts were discovered but remained unreachable:

http://192.168.101.176:1113

http://10.37.1.188:1113

http://139.129.54.109:1113

http://192.168.16.177:1113

http://46.4.126.75:1113

http://10.10.2.50:1113

http://51.255.35.114:1113

http://115.28.190.131:1113

http://172.31.31.88:1113

http://192.168.4.7:1113

http://46.101.209.159:1113

http://192.168.1.128:1113

http://172.21.0.116:1113

http://192.168.80.135:1113

http://10.8.0.2:1113

http://10.8.0.3:1113

http://192.168.0.79:1113`

**Comment by josephglanville** [comment]
I think you should start again and use the SSH installer, I don't think the manual installer is a good fit for you if you don't need the additional flexibility.

**Comment by SellamiRami** [comment]
OK I will try the SSH installer and I'll come back to you.

Thank you very much for your help and availability.

Cheers, 
Rami.
