### ISSUE TITLE
Error setting memory limit

### ISSUE THREAD

**Issue by Altneu** [flynn/flynn#3590]
Getting an error:
 "web process type failed to start, got down job event" 

when running this command: 
"flynn limit set web memory=2GB"

after a deploy on a newly created single node cluster.  Please help.

**Comment by Altneu** [comment]
within the instances, getting "bash: : command not found" whenever I run the limit command.

**Comment by Altneu** [comment]
[flynn-host.zip](https://github.com/flynn/flynn/files/559809/flynn-host.zip)

That may help

**Comment by josephglanville** [comment]
You should check your apps logs with `flynn log`, if you can't see anything obvious check what processes have been started with `flynn ps -a`, if some seem to have failed or crashed check if there is anything useful there. If the processes are not starting then there may be a scheduler issue. Will take a look at the logs shortly.

**Comment by Altneu** [comment]
`flynn log` is what showed 'bash: : command not found'

flynn ps -a shows a bunch of web processes down, and a few slugbuilders down...it seems like new web processes get created every time I run the limit command, but they remain down

**Comment by josephglanville** [comment]
Is there anything interesting in the logs of the down web processes? You can check the logs of a specific process using `flynn log -j <job_id>`, you can get the job IDs from `flynn ps -a`.

**Comment by Altneu** [comment]
There are 4 processes created each time I run the limit command once.  The first two created have a single log entry:  'bash: : command not found'

the second two have empty logs.

**Comment by josephglanville** [comment]
I would start by checking that the `Procfile` is correct, it sounds like the slugrunner is trying to execute your application but failing to do so.

**Comment by Altneu** [comment]
the application is running.  Procfile is correct.

**Comment by josephglanville** [comment]
Can you run `flynn-host collect-debug-info` and paste the resulting gist link.

**Comment by Altneu** [comment]
Do I need to kill the running jobs before running the limit command?  That would seem to go against the theme of flynn, and I didn't see that in docs.

**Comment by Altneu** [comment]
[https://gist.github.com/d7baa2f633ddfda9d60db3c57c56c468](url)

**Comment by josephglanville** [comment]
No, that is unnecessary. The limit command performs a deployment to replace the running processes, which is what is failing here. WHen it attempts to start new processes they are not coming up so it's not proceeding to shut down the existing ones.

**Comment by josephglanville** [comment]
Can you provide the output of `flynn-host log prodwebapi1-9d758dd4-8789-4d16-a15c-cea3fc749393`, if the output is sensitive you can email it to logs@flynn.io.

**Comment by Altneu** [comment]
I just added an empty line and did a commit and release, and the deployment worked and the app is running.  The box has 8GB of memory, I am trying to set my process to 2GB from the default of 1GB and I have the process scale set to 2...so I wouldn't think its running into a memory issue.

**Comment by Altneu** [comment]
The only thing in the log you requested is:

'bash: : command not found'

**Comment by josephglanville** [comment]
Can you paste output of `flynn release show --json`. I am trying to understand what command is actually being attempted to be executed in the container.

**Comment by Altneu** [comment]
`{"id":"fe18c08c-138f-4859-a6ec-a29f86b44659","artifact":"6003dea0-db26-4f0d-b57d-b6b6bd60996d","meta":{"git":"true"},"processes":{"web":{"ports":[{"port":8080,"proto":"tcp","service":{"name":"vcaro-device-new-web","crea
te":true,"check":{"type":"tcp","status.omitempty":0}}}],"service":"vcaro-device-new-web","resources":{"cpu":{"request":1000,"limit":1000},"max_fd":{"request":10000,"limit":10000},"memory":{"request":1073741824,"limit":1
073741824}}}},"created_at":"2016-10-29T07:33:23.131588Z"}`

**Comment by lmars** [comment]
@Altneu what version of the Flynn CLI are you using? Run `flynn version` on your machine.

**Comment by lmars** [comment]
@Altneu I've looked through the logs and I highly suspect this is due to an outdated CLI, run `flynn update` to update to the latest version.

**Comment by Altneu** [comment]
That was it, thank you!.  Funny thing is that was the first thing I considered, but I saw this statement - 'The CLI is securely updated automatically in the background during use.' - at the top of docs.
