### ISSUE TITLE
Can't SSH into an instance

### ISSUE THREAD

**Issue by shockey** [flynn/flynn#3591]
Hi- I'm setting up a Flynn cluster for a staging environment.

I wanted to add some swap to the (only) instance I'm using, since it's on a relatively small box (1gb).

Per the documentation:

> If you need to access cloud instances provisioned with the installer, you can connect to them with SSH. The installer will generate an SSH keypair, and will install the public key on all hosts it provisions. The keys are stored in ~/.flynn/installer/keys. The default key is called flynn.

Trying to do this results in a prompt for a password:
```
→ ssh -i ~/.flynn/installer/keys/flynn ubuntu@[removed]          
ubuntu@[removed]'s password: 
```

**Comment by josephglanville** [comment]
What cloud provider are you using? DigitalOcean uses the `root` account and Azure the `flynn` account. #3526 has been merged to fix the docs but an update hasn't bene pushed yet.

**Comment by shockey** [comment]
Aha- I'm on DO. Root worked perfectly. Thanks!
