### ISSUE TITLE
router: Support UDP routes

### ISSUE THREAD

**Issue by Altneu** [flynn/flynn#3595]
If so how would I configure a UDP route?  If not, is UDP support something that can be added in the future?

**Comment by lmars** [comment]
@Altneu the router does not currently support UDP routes, but there is no reason why it couldn't in the future.

We will leave this issue open to track adding support.

**Comment by philiplb** [comment]
That would be nice for game servers. :)

**Comment by Altneu** [comment]
Would be nice for IOT infrastructure as well.

**Comment by altneuPerficient** [comment]
Could someone point me in the direction of where this enhancement would be made in the code?  If I have the time I may try to do it myself.

**Comment by deini** [comment]
@altneuPerficient were you able to play around with this? Would love this too.

**Comment by altneuPerficient** [comment]
@deini haven't had a chance yet.  Its high on my list of things to do though.

**Comment by titanous** [comment]
Just as a pointer if anyone is interested in doing this, it'd basically be very similar to UDP NAT. The 5-tuple is used to identify client flows, the destination port is used to identify the backend service, and the source port used from the router to the backend (and the destination when responding) is used to identify flows on the backend side. Each flow would get an activity timeout for garbage collection and zero-downtime deploy integration with the scheduler.

**Comment by altneuPerficient** [comment]
Thanks for the pointers @titanous, would be great if someone who is familiar with the codebase already could take this on, however I am open to giving it a shot as soon as I have time.

**Comment by ignaciosiri** [comment]
Any updates on this? Im trying to run a rails task that listens to UDPSocket port for packets. Is it possible to run this behind flynn?  Or should i run this task as a standalone app side by side? 
I know this is not possible in dokku, but maybe flynn does the trick. Thanks in advance!

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
