### ISSUE TITLE
Mariadb appliance enhancement: allow longer indexes than 767 bytes.

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3597]
Hey!

I'm constantly colliding with this problem in flynn database appliance, even though this isn't really flynn's fault.

We are hosting some WordPress sites in flynn and want to move everything over here in the future.
Many of the WordPress plugins create tables into the mysql for storing their internal data and we have been bumping into this issue lately:
```
WordPress-database error: Index column size too large. The maximum column size is 767 bytes. Query CREATE INDEX typeitem ON wp_sometable (type, item)
```

It happens when the plugin tries to run a SQL-query like this:
```
CREATE TABLE wp_sometable
...
type varchar(255) NOT NULL DEFAULT 'post',
...
```

**Why this happens:**
Historically this was the maximum length that could be fitted into 767 bytes using `charset=utf8`.

The problem started when people wanted to have emojis in the charset and new charset `utf8mb4` was created.

> Default utf8 encoding is 3 byte in MySQL, whereas utf8_mb4 is 4 byte variable (utf32 is 4 byte fixed)
> http://dev.mysql.com/doc/refman/5.7/en/charset-unicode.html

So `charset=utf8` is `255*3 = 765` and can fit into the default index but `charset=utf8mb` is `255*4= 1020` so it can't fit into the allowed index length limit.

**Possible fix:**
Is it possible to enable: http://dev.mysql.com/doc/refman/5.5/en/innodb-parameters.html#sysvar_innodb_large_prefix

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
