### ISSUE TITLE
Compression issue behind router...

### ISSUE THREAD

**Issue by Altneu** [flynn/flynn#3599]
I'm having an issue getting http response body compression to work properly through Flynn.  The same code base deployed through Dokku is compressing response bodies.  

I am using express with the compression module and I have verified that the necessary headers are being passed through the router, the compression module function call to determine if a response should be compressed is returning true and the compression logic is running; however the browser is not receiving a compressed response.  

Any ideas on what may be breaking compression?

**Comment by titanous** [comment]
Can you provide an example app that demonstrates the issue? It's possible that the router is stripping the compression, but it'd be easier to track down with a reproducible test case.

**Comment by Altneu** [comment]
Working on it.

**Comment by Altneu** [comment]
Non issue...turns out Chrome reports compression inconsistently over TLS, dev tools showed compression on an endpoint deployed through dokku but not through Flynn....strange.  Verified with fiddler and all is good.

**Comment by titanous** [comment]
FWIW, the difference is HTTP/2 on Flynn.
