### ISSUE TITLE
Custom Process Kill Timeout

### ISSUE THREAD

**Issue by evantahler** [flynn/flynn#3600]
When stopping a `worker` type process, perhaps 10 seconds between SIGTERM and SIGKILL is not enough.  It would be handy to have this configured via ENV.  Perhaps `FLYNN_KILL_TIMEOUT`

**Comment by titanous** [comment]
This makes sense, I think it belongs in the upcoming Flynnfile feature: #1084.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
