### ISSUE TITLE
Having several entries from "flynn ps" in pending state, and deployment now fails on timeout.

### ISSUE THREAD

**Issue by alfredqy** [flynn/flynn#3608]
I can see processes from 4 different releases. The oldest one has all 7 nodes up and the 3 newer releases each has 2 nodes in pending state. When I now tried to push a new release, it times out with the following error message: 

remote: ERROR: Error deploying app release: timed out waiting for job events: map[upload-web:map[up:3] web:map[up:3] admin-web:map[up:1]]

Are the processes with pending state the problem? Why are they in pending state? How to get them out of it? Thanks!

**Comment by titanous** [comment]
@alfredqy Please run `sudo flynn-host collect-debug-info` on one of the hosts and provide the resulting debug logs here.

**Comment by alfredqy** [comment]
@titanous thanks. Following instructions here: https://flynn.io/docs/installation/cloud#ssh-access

When I try to ssh in with the keys it still asks for password. There shouldn’t be one with the keys should it?

I get this debug when I run with -vvv:

debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/username/.flynn/installer/keys/flynn
debug3: send_pubkey_test
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password

**Comment by titanous** [comment]
What hosting provider did you use? What username did you pass to SSH?

**Comment by alfredqy** [comment]
DigitalOcean. I passed ubuntu as the username.

**Comment by titanous** [comment]
Try using root, looks like a docs update needs deploying.

**Comment by alfredqy** [comment]
Tried using root. Sort of hanging but in the log: Authentication succeeded (publickey).

**Comment by titanous** [comment]
If auth succeeded and the login is hanging, the VM is broken or the CPU is pegged. How many hosts in the cluster? Can you try a different one?

**Comment by alfredqy** [comment]
We are able to get in one of the hosts with root. The other two however don't seem to be accessible.

And we've got from collect-debug info command:
fatal error: runtime: out of memory

The output above the error:
INFO[11-02|19:17:24] uploading logs and debug information to a private, anonymous gist 
INFO[11-02|19:17:24] this may take a while depending on the size of your logs 
INFO[11-02|19:17:24] getting flynn-host logs 
INFO[11-02|19:17:25] getting scheduler state 
INFO[11-02|19:17:25] getting job logs

**Comment by alfredqy** [comment]
We have three hosts in the cluster. We are able to get into one of the three with root but not the other two.

**Comment by alfredqy** [comment]
We rebooted the two hosts that we lost access. Before reboot, our site page shows service not available. After reboot, flynn ps looks clean now and we are trying to make a new release push.

Any suggestions where we can look at to learn from the situation? What happened and maybe how to prevent getting into it again?

By the way, thanks for your prompt responses!

**Comment by titanous** [comment]
Can you provide the logs from the command? It should generate a gist link.

**Comment by alfredqy** [comment]
We've got this:
Total size of 305005871 bytes exceeds gist limit, falling back to tarball

Its in a tmp file on the server 300mb. Let us know what we need to do.

**Comment by titanous** [comment]
Can you upload it somewhere and post a link here?
