### ISSUE TITLE
Best practice for internal communication

### ISSUE THREAD

**Issue by FlorianRappl** [flynn/flynn#3614]
I have a couple of (REST-based) services that should only be reachable from other services in my cluster (i.e., "internal").

Currently, I have implemented this by removing the default route and using the discovery service with an URL like `$APPNAME-$PROCTYPE.discoverd:$PORT`. However, I wonder if it is possible to use "internal routes". I think that using `$PORT` (picked from the environment, i.e., it uses the same port as the callee) is not bullet proof (or am I wrong here?) and will only pick one particular service instance (if its available with the given port).

Another thing that should come as a side-effect (and excludes using the `leader.` prefix) is that facilitating the load balancing mechanism would be appreciated. Otherwise, scaling such a service up has no effect.

What did not work for me was using `$APPNAME-$PROCTYPE.discoverd` with no port (i.e., therefore falling back to either 80 or 443 depending on the protocol).

Of course I could implement the communication also in my software layer, but having it from the PaaS would be great.

Sorry for asking here, but I did not find anything in the documentation nor the examples!

**Comment by lmars** [comment]
@FlorianRappl you have two options:

1) Use DNS SRV records (each job has its own SRV record which includes the port):

```
$ flynn -a my-app run dig +short my-app-web.discoverd SRV
1 1 8080 55651bcfde5b8faeb300c3c9eee5c162.my-app-web._i.discoverd.
1 1 8080 95da09c55b876819bc1fa02a04ebfaf9.my-app-web._i.discoverd.
1 1 8080 c76e765424361a92f1bfae8380381a71.my-app-web._i.discoverd.
```

2) Use the discoverd API to get the service instances from `$DISCOVERD/services/SERVICE/instances` (I've run through `jq` to grab just the address):

```
$ flynn -a my-app run bash -c 'curl --silent $DISCOVERD/services/my-app-web/instances' | jq --raw-output .[].addr                                                                             
100.100.31.22:8080
100.100.31.24:8080
100.100.31.23:8080
```

**Comment by FlorianRappl** [comment]
Yep, but both options require myself to do the load balancing (or am I wrong?). I need to pick an instance explicitly here. Maybe I am thinking in the wrong direction...

Thanks for your help @lmars!

**Comment by titanous** [comment]
Using the discoverd DNS records will result in a random selection of three instances with a 0 TTL, so that should randomly load balance things (which is not significantly different from what the router does). If you want something more intelligent, you'd need to build that yourself.

**Comment by FlorianRappl** [comment]
Awesome @titanous - no, this is exactly what I need! Thanks for the clarification 👍 .
