### ISSUE TITLE
Changing the cluster domain

### ISSUE THREAD

**Issue by mhlz** [flynn/flynn#3616]
I can't find any documentation on how to change the cluster domain. From looking around the system applications in the Flynn dashboard I assume that I'd have to change it in all the configurations and routes there, but are there any other places where the domain might be configured?

I'd like to avoid reinstalling because of all the work that already went into setting things up. Any advice on how to do this would be greatly appreciated :)

**Comment by titanous** [comment]
`flynn cluster migrate-domain example.com` will do a domain migration, including updating routes, please be sure to take a backup first and ensure the DNS is configured properly before starting.

**Comment by mhlz** [comment]
Thank you! I guess I must be blind not finding that.

**Comment by SalvoLunar** [comment]
Hi @titanous 

I'm in a similar situation where I'm trying to recreate my production environment on a different hosting. 
I've made a backup of my current cluster, and restored it on the new enviroment using the bootstrap command with a different domain name. But when I try to get the cli-add-command from flynn-host the domain name returned is not the new one.
Is there a way to change this?

Thanks,
Salvo
