### ISSUE TITLE
Browser installer - Install dependencies before installing anything

### ISSUE THREAD

**Issue by cohan** [flynn/flynn#3617]
Could the `flynn install` command first check for and install dependencies if needed, bailing out before making any chances if it can't pre-setup the system?

In some cases (in mine specifically a dedicated server at online.net) Ubuntu 14.04 comes as an extremely minimal install so doesn't include curl by default. Installing curl is an easy enough thing to do but it does make me wonder if other things are missing.

It also causes the message "If Flynn is already installed, it will be stopped and removed along with all data before installing the latest version. Would you like to proceed?" which only seems to ask for one server in a multi-server setup - eventually the easiest fix is to reinstall the OS on everything and start over hoping you don't miss something in take two

**Comment by lmars** [comment]
@cohan the install script installs all the dependencies needed to run Flynn, but yes `flynn install` attempts to fetch the install script on the server using `curl` which isn't guaranteed to be present. We should do something like `which curl || apt-get install curl` first (probably [here](https://github.com/flynn/flynn/blob/master/installer/bare_cluster.go#L52)).

> It also causes the message "If Flynn is already installed, it will be stopped and removed along with all data before installing the latest version. Would you like to proceed?" which only seems to ask for one server in a multi-server setup

This sounds like a bug, we should fix it (/cc @jvatic).

> eventually the easiest fix is to reinstall the OS on everything and start over hoping you don't miss something in take two

Or you could run the install script manually on each server with `--clean` and either accept the prompt or specify `--yes`.
