### ISSUE TITLE
Require signed commits for deployment

### ISSUE THREAD

**Issue by kckrinke** [flynn/flynn#3620]
I'd like for there to be some way of uploading a GPG pubkey to the flynn app dashboard. Then, in order for a `git push flynn` to succeed; the commit must be signed by the private key which flynn will of course validate with the configured pubkey.

**Comment by lmars** [comment]
@kckrinke the current plan is to add user accounts (#410) and then be able to add user level permissions (e.g. user X can deploy to app Y). Would that satisfy your use case? You could probably implement a GPG based authentication system if you really need GPG.

**Comment by kckrinke** [comment]
This isn't just about user authentication, it's also a vetting control for the actual code and forces a sort of multi-factor-user-permission protocol.

Currently, it's a wild-west scenario in terms of access permissions and admin privileges for flynn which even the user account setup proposed doesn't cover fully. In the end, I'm looking for the following (and will be building out what I can myself of course):

* VPN credentials to "dial in" to the cluster dashboard etc
* User accounts (as-per #410 but would also like to see some granular user permissions too)
* SSH keys required in order to push to git at all (regardless of which app)
* GPG signed commits required for specific app (ie: "production") pushes

This issue is referring to just the last point in the above list.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
