### ISSUE TITLE
cli: 'flynn scale' should wait for service events

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3621]
Running `flynn scale` just waits for job events, but when scaling jobs which expose services this doesn't indicate that the job is actually ready to serve requests, evident in the following [CI failure](https://ci.flynn.io/builds/20161104075439-b61baf77):

```
++ 08:24:16.901 /home/ubuntu/go/src/github.com/flynn/flynn/test/../cli/bin/flynn -a gitreceive scale app=1
scaling app: 0=>1

08:24:17.060 ==> app 8522eaef-1d1d-4500-acdb-65de44d472a8 pending
08:24:17.139 ==> app 998ef605-8522eaef-1d1d-4500-acdb-65de44d472a8 starting
08:24:17.478 ==> app 998ef605-8522eaef-1d1d-4500-acdb-65de44d472a8 up

scale completed in 492.380781ms

++ 08:24:17.480 /usr/bin/git commit -m bump --allow-empty
[master 3162126] bump

++ 08:24:17.487 /usr/bin/git push flynn master --progress
fatal: unable to access 'https://git.flynn-e42891ff817ff9ec.local/crows-revolt-barrie.git/': The requested URL returned error: 503
```

I am actually wondering if the scheduler should only mark a job as `up` once the relevant service has started (rather than just when the job is marked as running by the host).

This would mean the job would remain in the `starting` state until the service starts, which I think makes sense. This would also simplify deployments (just wait for job events rather than job and/or service events, see #3518).

@titanous @josephglanville @jvatic wdyt?

**Comment by titanous** [comment]
SGTM

**Comment by lmars** [comment]
There is still a race between the scheduler / router seeing the service as up (which is also a race in the current deployment implementation), so the scheduler should probably just wait for N router backend up events, but we need to make sure we still mark a job as up even if a router is acting up and not sending the events.

**Comment by titanous** [comment]
Do the router backend events have the job ID? Seems like that could be added, as it's in the discoverd meta.

**Comment by lmars** [comment]
The router backend events do have the job ID yes: https://github.com/flynn/flynn/blob/master/router/types/types.go#L211-L215

So yes the scheduler has the information it needs, but if there are N routers and the scheduler only has N-1 up events, should it have a timeout to mark the job as up without waiting for the last event in case it never comes?

**Comment by titanous** [comment]
Ah, you meant N routers, not N jobs.

**Comment by titanous** [comment]
Yeah, a short timeout makes sense.
