### ISSUE TITLE
Clarify docs about single-node and/or intranet installation

### ISSUE THREAD

**Issue by tuukkamustonen** [flynn/flynn#3624]
At  https://flynn.io/docs/installation/manual:

> If you are starting more than one node, the cluster should be configured using a discovery token. flynn-host init is a tool that handles generating and configuring the token.

Does this mean that I can actually skip `sudo flynn-host init` commands if I'm going single-node?

Later on, when I run `flynn-host bootstrap`, should I omit `--discovery-url` if going single-node?

If I run discovery commands and pass `--discovery-url`, I get:

```
14:56:17.184567 check online-hosts
14:58:18.095882 check online-hosts error: timed out waiting for 1 hosts to come online (currently 0 online)

The following hosts were discovered but remained unreachable:

```

And if I omit `--discovery-url`, I get:

```
15:00:31.207176 check online-hosts
15:02:31.253575 check online-hosts error: timed out waiting for 1 hosts to come online (currently 0 online)

The following hosts were discovered but remained unreachable:

http://127.0.0.1:1113
```

I got `flynn-host` running, but it doesn't listen to that port (it doesn't seem to listen any port)... should it?

Trying to `flynn create example` gives:

```
15:23:54.433097 main.go:172: no clusters configured
```

My instance is in intranet, configured into an internal DNS server.

I have (now) `http_proxy`, `https_proxy`, `HTTP_PROXY` and `HTTPS_PROXY` environment variables set (to survive through the installation), but where/how should I configure them for flynn?

**Comment by IsNull** [comment]
It is probably a [bug](https://github.com/flynn/flynn/issues/3640) in the current version of flynn, maybe just try `v20160918.1`.

**Comment by titanous** [comment]
> Does this mean that I can actually skip `sudo flynn-host init` commands if I'm going single-node?

Yes.

> Later on, when I run `flynn-host bootstrap`, should I omit `--discovery-url` if going single-node?

Yes. 

From your issue it sounds like the flynn-host process is not running or there is a restrictive firewall configured. Also, Flynn does not currently support proxies (see #1973).

**Comment by tuukkamustonen** [comment]
Alright, fair enough. I guess I'll wait until proxy support is available...

**Comment by webmutation** [comment]
I admit I was confused as well. Is it still necessary to create a CNAME DNS record with one node? The only thing that I see the DNS setting being used is for service discovery

**Comment by IsNull** [comment]
@webmutation To access an application running in Flynn you need a working route to it.

In order to resolve applications in flynn dynamically, you require a wildcard DNS entry:
 i.e. `<appname>.my.flynn.cluster.com`, so you need DNS settings in place which resolve `*.my.flynn.cluster.com` to your flynn cluster nodes.
