### ISSUE TITLE
Use port 80 for downloading key from ubuntu keyserver

### ISSUE THREAD

**Issue by tuukkamustonen** [flynn/flynn#3625]
I'm installing flynn behind a proxy, that only allows traffic into 80 and 443 ports.

By default, `apt-key adv` uses port `11371` which caused issues for me.

However, it seems that you can instruct command to use port `80` by putting `hkp://SERVER:80` as in:

```
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E871F18B51E0147C77796AC81196BA81F6B0FC61
```

Not that big of a deal, but might avoid a few problems when people install flynn behind a proxy...

**Comment by IsNull** [comment]
We observed this as well while installing Flynn on-prem behind a firewall. After manually allowing the port it worked, but I assume not all network admins are that happy about such exceptions :)

**Comment by lmars** [comment]
@tuukkamustonen @IsNull this sounds like a simple change, are either of you willing to submit a PR? You can find the script [here](https://github.com/flynn/flynn/blob/master/script/install-flynn.tmpl).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
