### ISSUE TITLE
Feature Request: Allow adding /etc/hosts entries to containers with flynn cli

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3635]
Hey!

Is there a way to add custom entries to containers `/etc/hosts` without modifying my docker containers?

I would need this in order to have valid https certificate when doing api calls through nginx stream proxy machine.

For example docker-compose has `extra-hosts` variable: https://docs.docker.com/compose/compose-file/#/extrahosts

**Comment by titanous** [comment]
Can you have a wrapper in your container image that reads from the environment and writes the file before starting the app? This seems like a pretty obscure thing to have flags for.

**Comment by onnimonni** [comment]
ofc I can.

I just thought that because this is supported by docker ( by:  `--add-host=example.com:127.0.0.1` ) it could be supported in Flynn too and I wanted to know if there's better way to do this than adding those layers into the containers.

Hopefully this issue will help people to find this information later on.

**Comment by titanous** [comment]
A wrapper is the best way for you to do this in Flynn, unlike Docker we try to avoid adding flags and options for every thing that you could possibly want to do.

**Comment by onnimonni** [comment]
I understand. Thanks for taking the time and sorting this one.
