### ISSUE TITLE
demo installation fails at `make init`

### ISSUE THREAD

**Issue by jperals** [flynn/flynn#3636]
Following the instructions here: https://flynn.io/docs/installation/vagrant, I am getting this output after typing `make init`:
```
CLUSTER_DOMAIN="demo.localflynn.com" SSH_AUTH_SOCK="" FLAG_BOOTSTRAP=false vagrant box update
==> default: Box 'flynn-base' not installed, can't check for updates.
CLUSTER_DOMAIN="demo.localflynn.com" SSH_AUTH_SOCK="" FLAG_BOOTSTRAP=false vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'flynn-base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: > 0
==> default: Box file was not detected as metadata. Adding it directly...
You specified a box version constraint with a direct box file
path. Box version constraints only work with boxes from Vagrant
Cloud or a custom box host. Please remove the version constraint
and try again.
make[1]: *** [up] Error 1
make: *** [init] Error 2
```

If I comment out the line `config.vm.box_version = "> 0"` from the Vagrantfile, then I get a different error message:
```
CLUSTER_DOMAIN="demo.localflynn.com" SSH_AUTH_SOCK="" FLAG_BOOTSTRAP=false vagrant box update
==> default: Box 'flynn-base' not installed, can't check for updates.
CLUSTER_DOMAIN="demo.localflynn.com" SSH_AUTH_SOCK="" FLAG_BOOTSTRAP=false vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'flynn-base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'flynn-base' (v0) for provider: virtualbox
    default: Downloading: https://dl.flynn.io/vagrant/flynn-base.json
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.


make[1]: *** [up] Error 1
make: *** [init] Error 2
```

I installed the latest Virtualbox (5.1.8) and Vagrant (1.8.7) on Mac OS X 10.11.4.

I am pretty new on this, so there might be something I'm doing wrong, but I believed I did everything pretty much as explained.

**Comment by lmars** [comment]
@jperals the output is indicating that Vagrant could not download the manifest file at the following URL:

https://dl.flynn.io/vagrant/flynn-base.json

That link works for me, do you get valid JSON when you go to that URL?

**Comment by titanous** [comment]
Looks like the latest version of Vagrant is broken with our Vagrantfile. I'm investigating.

**Comment by jperals** [comment]
@lmars Yes, I also get good looking JSON when I visit that URL with my browser (and on the same network as when using the failing scripts).

**Comment by titanous** [comment]
This is an upstream issue: mitchellh/vagrant#7970

Looks like this workaround works:

```text
sudo rm /opt/vagrant/embedded/bin/curl
```

**Comment by jperals** [comment]
@titanous Right! In my case I applied the symbolic link workaround: 

```sudo ln -s /usr/bin/curl /opt/vagrant/embedded/bin/curl```

and it worked as well.

Thanks!

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
