### ISSUE TITLE
AWS Ubuntu 14.04 image only provides kernel 3.13, overlayfs wants 3.19

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3648]
v20161108.0 fails at the install-flynn step with 
```
+ /tmp/install-flynn -r https://dl.flynn.io
modprobe: FATAL: Module overlay not found.
===> 01:49:05.295 ERROR: OverlayFS is either missing or does not support multiple lower directories, consider upgrading your kernel to at least 3.19
```

This happens even on the most recent official version of Ubuntu 14.04 available in AWS. I am trying a replacement using v20161106.3, which I'm fairly sure will evade the issue.

**Comment by temujin9** [comment]
Allowing launches on 15.04 or 16.04 would probably solve this problem, but your install script currently dislikes that idea strongly.

**Comment by lmars** [comment]
@temujin9 we install the xenial kernel (4.4) in [the Flynn AMI](https://github.com/flynn/flynn/blob/master/util/packer/ubuntu-14.04/scripts/upgrade.sh#L38), can you do the same?

We will be upgrading to 16.04 real soon, just waiting on updating our Docker dependency (#3637).

**Comment by temujin9** [comment]
That would require a reboot to take effect, which is not something my architecture is designed to handle.

**Comment by lmars** [comment]
@temujin9 can you use the Flynn AMI?

**Comment by temujin9** [comment]
Initial attempts have not been very fruitful. I could try some more, as that would also improve several other things IMO.

**Comment by temujin9** [comment]
How soon is real soon? I could pin my launches to v20161106.3, until you've released the thing that lets me do 16.04.

**Comment by lmars** [comment]
@temujin9 we are aiming to have 16.04 support in the next stable release (next Tuesday).

**Comment by temujin9** [comment]
Okay, I can wait for that. Ping here when that does drop?

**Comment by lmars** [comment]
@temujin9 probably worth subscribing to #2789.

**Comment by temujin9** [comment]
v20161106.3 is affected by this.

v20161104.0 hits "ERROR: failed to verify flynn-host binary checksum".

v20161102.0 works.

**Comment by titanous** [comment]
The install script with support for 16.04 is now available.
