### ISSUE TITLE
SSL Cipher suites

### ISSUE THREAD

**Issue by simon0191** [flynn/flynn#3654]
I was configuring cloudfront to serve the assets of my rails app deployed in flynn and I got a 502 bad gateway response each time I tried to access the assets using https. I saw in the [AWS documentation](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html) that the error was caused because my site doesn't support any of the cipher suites supported by cloudfront.

I verified with [ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=www.salonomi.com) and effectively my site supports 4 cipher suites that are not supported by cloudfront.

I also verified wiht ssllabs the flynn dashboard and it supports 2 more cipher suites, including 1 that is supported by cloudfront.

Since flynn manages the certificate of my app, Is there a way to enable additional cipher suites? Why does the flynn dashboard support more cipher suites than my application?

**Comment by titanous** [comment]
You have an ECDSA certificate. CloudFront will work if you use an RSA certificate instead.
