### ISSUE TITLE
I can't deploy and scale apps on flynn 

### ISSUE THREAD

**Issue by hugoleodev** [flynn/flynn#3655]
When I deploy or scale apps on my flynn node I'm gettings the follow error.

flynn: getting image config with "docker inspect -f {{ json .Config }} brbid/wp"
flynn: tagging Docker image with "docker tag brbid/wp docker.flynn.tree.sh/alexandro:latest"
flynn: pushing Docker image with "docker push docker.flynn.tree.sh/alexandro:latest"
The push refers to a repository [docker.flynn.tree.sh/alexandro]
508c549726fb: Layer already exists 
b1405bec6915: Layer already exists 
eab431e9cb17: Layer already exists 
a3f836de1386: Layer already exists 
8050217d10d4: Layer already exists 
9a999c18ebce: Layer already exists 
54a54e27530f: Layer already exists 
3cbb6cb8568b: Layer already exists 
55410c2ce269: Layer already exists 
78227ac00a42: Layer already exists 
097a916f6a5a: Layer already exists 
3e77de2f74ab: Layer already exists 
4c36fb098bb8: Layer already exists 
73ccb4760634: Layer already exists 
daae20c55d80: Layer already exists 
c54d1662afc3: Layer already exists 
2478b27e35a5: Layer already exists 
0dfa0375a8c9: Layer already exists 
a4a6b530da26: Layer already exists 
a03521c7187f: Layer already exists 
3703e26e0d5e: Layer already exists 
4591824cd00a: Layer already exists 
c1870dfa056f: Layer already exists 
26fdebcea995: Layer already exists 
0fe2204ee16b: Layer already exists 
6fd178795bc8: Layer already exists 
5670c80821b4: Layer already exists 
b383c4b9507c: Layer already exists 
e40dce3d41d4: Layer already exists 
7b7797fb4360: Layer already exists 
c9a0778a74b0: Layer already exists 
ca73e27525f7: Layer already exists 
142a601d9793: Layer already exists 
latest: digest: sha256:38011ab174516686f5bf33cc93c04c0fb7c0593edc16bbe2ecf891603855639c size: 32473
flynn: image pushed, waiting for artifact creation
flynn: deploying release using artifact URI http://flynn:0a41db91c5852c0ae7002385f3984730@docker-receive.discoverd?name=alexandro&id=sha256:38011ab174516686f5bf33cc93c04c0fb7c0593edc16bbe2ecf891603855639c
object_not_found: service not found

The "flynn-host" log https://transfer.sh/QgbBE/flynn-host-debug.tar.gz 

The "flynn log" https://gist.github.com/hugoleodev/20e472f9e9e986869f57d79f847b5ca8

The "flynn ps" log https://gist.github.com/hugoleodev/282101ce833b9927840eac0223e871fa

**Comment by lmars** [comment]
@hugoleodev the issue here is that your instance is running out of memory, and because there is no swap to handle the pressure, certain jobs started throwing errors (for example `discoverd` was intermittently marking services as down).

You should take a cluster backup and restore to a cluster with more memory.

**Comment by hugoleodev** [comment]
@lmars I will fix it now. Once again, thank you for your support.
