### ISSUE TITLE
docker login failure with private docker registry

### ISSUE THREAD

**Issue by mbukosky** [flynn/flynn#3656]
Hi,

I am unable to deploy with docker to my private docker registry. Is this currently supported? Here are the commands I run. Is there a way to pass in the username and password when I login?

Thanks for all the help

`flyn v20161017.1`
`Docker version 1.12.1, build 6f9534c`

```
$ flynn docker set-push-url dockerhub.myprivatereg.com
$ flynn docker login

error running `docker login`: exit status 1 - output: {"Flag --email has been deprecated, will be removed in 1.13.
Error response from daemon: Get https://dockerhub.myprivatereg.com/v2/: unauthorized: incorrect username or password\n" '\x00' "\x00\x00\x00\x00" 
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" '\x00'}
```

**Comment by josephglanville** [comment]
Flynn runs it's own registry internally. The push URL should be set to the docker receive endpoint for your Flynn cluster.

The easiest way to reset it is probably to edit `~/.flynnrc` and change the DockerPushURL line to read:
```
DockerPushURL = ""
```

Once that is down you can fetch the image from your private registry with `docker pull <image>` then push it to Flynn with `flynn docker push <image>`.

**Comment by mbukosky** [comment]
Thanks, that makes sense now. I am now getting a cert error but I'll just follow the directions to see if that gets resolved.

Thanks!

```
WARN: docker configuration failed with a TLS error.
WARN:
WARN: Copy the TLS CA certificate /Users/xxx/.flynn/ca-certs/flynn-6666.pem
WARN: to /etc/docker/certs.d/docker.xxx.flynnhub.com/ca.crt
WARN: on the docker daemon's host and restart docker.
WARN:
WARN: If using Docker for Mac, go to Docker -> Preferences
WARN: -> Advanced, add "docker.xxxx.flynnhub.com" as an
WARN: Insecure Registry and hit "Apply & Restart".

Error configuring docker, follow the above instructions and try again.
```

**Comment by josephglanville** [comment]
No problem, make sure you follow along here: https://flynn.io/docs/docker
Specifically creating the app and pushing the docker image to it.

Let us know how you go! :)

**Comment by mbukosky** [comment]
Thanks again, I got it working. Just to be clear, when resolving the TLS error above, I have to copy the TLS certs over to each node (host) AND configure my local docker Mac with Insecure Reg?

**Comment by josephglanville** [comment]
No, you only need to copy the certs into your local `/etc/docker/certs.d`.
I am unsure if anything special needs to be done for Docker for Mac, I don't use it unfortunately.

**Comment by mbukosky** [comment]
Ok thanks for clearing that up.

**Comment by josephglanville** [comment]
Thanks! If you do find specific steps are required to get this to work on Docker for Mac if you could open an issue or PR to add to the docs that would be great. :)

**Comment by artemave** [comment]
Getting this on OSX:

```
% flynn docker login                                                                                                                      
WARN: docker configuration failed with a TLS error.
WARN:
WARN: Copy the TLS CA certificate /Users/artem/.flynn/ca-certs/default.pem
WARN: to /etc/docker/certs.d/docker.prs.fakesh.it/ca.crt
WARN: on the docker daemon's host and restart docker.
WARN:
WARN: If using Docker for Mac, go to Docker -> Preferences
WARN: -> Advanced, add "docker.prs.fakesh.it" as an
WARN: Insecure Registry and hit "Apply & Restart".
```

I added `docker.prs.fakesh.it` to insecure registries (and restarted docker) and even copied `default.pem` to `/etc/docker/certs.d/docker.prs.fakesh.it/ca.crt` and every seemingly relevant place in `~/.docker` but to no avail.

**Comment by lmars** [comment]
@artemave what happens when you run:

```
$ docker login docker.prs.fakesh.it
```

**Comment by artemave** [comment]
@lmars it prompts for login:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/23721/33263260-0b27e7ea-d361-11e7-95bd-7830b278338f.png">

**Comment by lmars** [comment]
Ok, and if you use `flynn` as the Username and the `Controller Key` from `~/.flynnrc` as the password, does it work?

That is all `flynn docker login` does (i.e. calls `docker login --username flynn --password KEY URL`).

**Comment by artemave** [comment]
`docker login --username flynn --password $KEY_URL docker.prs.fakesh.it`

Gives:
`Error response from daemon: Get https://docker.prs.fakesh.it/v2/: x509: certificate signed by unknown authority`

**Comment by lmars** [comment]
Right, so that means you haven't configured the Docker daemon to trust the Flynn TLS certificate (which is what the warning from `flynn docker login` is trying to get you to do).

You may find the Docker documentation more informative, see point 3 of "Use self-signed certificates" [here](https://docs.docker.com/registry/insecure/#use-self-signed-certificates), with the cert being the Flynn one in `/Users/artem/.flynn/ca-certs/default.pem`.

**Comment by artemave** [comment]
I _think_ this fixed it:

1. `sudo security add-trusted-cert -d -r trustAsRoot -k /Library/Keychains/System.keychain ~/.flynn/ca-certs/default.pem`

2. restart docker

Thanks for you help @lmars !
