### ISSUE TITLE
Flynn host dies after first deploy attempt

### ISSUE THREAD

**Issue by mbajur** [flynn/flynn#3659]
Hello there!

I've been trying to finally play a bit with flynn (i'm coming from dokku) but encountered a blocker. I've tried everything for three times and it always acts the same.

I'm provisioning a new VM with Ubuntu 14.04 and updating kernel to 4.x. I'm running install script for flynn and that works fine. Next step is deploying an actuall app - i'm doing so (tried that with three completely different apps) and deploy output fails after compiling a slug:

```
-----> Discovering process types
       Default process types for Ruby -> rake, console, web
-----> Compiled slug size is 17M
remote: ERROR: Build failed: exec: job exited with status 22
```

And, after this one deploy attempt, my VM becomes unresponsible from flynn point of view. The dashboard stops to display any data (UI generally works but there is no data displayed), i'm not able to run, for instance, `$ flynn apps` cause it ends up with `Unknown error` and another deploy attempts ends up with

```
> git push --set-upstream flynn master
remote: Internal server error
fatal: unable to access 'https://git.*.flynnhub.com/spoonbills-admire-ingersoll.git/': The requested URL returned error: 500
```

After server reboot, dashboard stops to work and never starts again. The only way to "solve" this is to reinstall everything from scratch but it will fail again on first deploy. And obviously is not a solution at all.

Here is my `flynn-host collect-debug-info` result:
https://gist.github.com/a4c42b4a87b646ed7942cb27b9aad044

I'm afraid i'm not able to extract any usefull informations from it.

Thanks in advance for any clues!

ps. Sorry if that's a duplicate of some other issue, i'm not even sure how to search for it cause i can't find any error message nor anything helpfull.

**Comment by lmars** [comment]
From the blobstore log during the upload of the build:

```
t=2016-11-10T16:49:45+0000 lvl=info msg="request started" component=blobstore req_id=a47139b9-bde6-4964-be6b-a6e7058a7262 method=PUT path=/bb179dab-1d10-4df7-ad0c-012c180f0641/slug.tgz client_ip=100.100.31.18
2016/11/10 16:49:51 error: PANIC: could not write to log file 000000010000000000000001 at offset 10354688, length 8192: Invalid exchange (SQLSTATE XX000)
```

And in the PostgreSQL log:

```
50f6b876-a98d-4598-8ae5-ff364b5cffcc 2016-11-10 16:49:45.223 UTC PANIC:  could not write to log file 000000010000000000000001 at offset 10354688, length 8192: Invalid exchange
50f6b876-a98d-4598-8ae5-ff364b5cffcc 2016-11-10 16:49:51.469 UTC LOG:  server process (PID 91) was terminated by signal 6: Aborted
50f6b876-a98d-4598-8ae5-ff364b5cffcc 2016-11-10 16:49:51.469 UTC DETAIL:  Failed process was running: UPDATE files SET file_oid = lo_create(0) WHERE file_id = $1 RETURNING file_oid
```

This leaves PostgreSQL in recovery mode, and causes the resulting issues for the cluster.

Your VM has 1GB of memory with no swap, and the kernel is OOM killing processes because there is not enough available memory.

You should use a VM with more available memory.

**Comment by josephglanville** [comment]
It looks like something caused PostgreSQL to crash which is likely the cause of the follow on effects.
Specifically the main server process got a `SIGABORT` which means the PostgreSQL server detected a fatal error condition, in this case it was unable to write to the WAL.

Can you check you have sufficient free space with `df -h` we recommend running Flynn on servers with no less than 40GB of storage for evaluation purposes.

```
50f6b876-a98d-4598-8ae5-ff364b5cffcc 2016-11-10 16:49:45.223 UTC PANIC:  could not write to log file 000000010000000000000001 at offset 10354688, length 8192: Invalid exchange
50f6b876-a98d-4598-8ae5-ff364b5cffcc 2016-11-10 16:49:51.469 UTC LOG:  server process (PID 91) was terminated by signal 6: Aborted
```

**Comment by mbajur** [comment]
Makes sense. My machine is pretty weak, just for testing purposes. I'm gonna check it again on a bigger one and let you know.

**Comment by mbajur** [comment]
I've upgraded my VM and indeed, it seems that was the reason. Thanks :) 

However, i managed to deploy a first app (totally small one, just for testing purposes) and later, i tried to deploy a second one (not so small) and it failed during the deploy. Git push logs are a bit chaotic so i'm not sure what's the actuall error message, all i can see is (during `npm install` step):

    line 1:   211 Killed

After that, the same thing happened with my flynn host as in OP, dashboard works but not showing any data, i'm not able to push anything to flynn. Once again, i'm not able to extract anything helpfull from the logs https://gist.github.com/anonymous/92b4230d3450fdf75f171c4eb14c62dc

I can see something bad is happening with postgres but not sure what's causing it nor what to do about it/what to google for: https://gist.githubusercontent.com/anonymous/92b4230d3450fdf75f171c4eb14c62dc/raw/24d819b05d77796aa762b6daef6e0f13bd60a93e/postgres-postgres-flynn-cb30f53e-fd70-4e2b-9ae7-186a168658b5.log

**Comment by titanous** [comment]
That output likely means that npm ran out of memory. You can fix this by increasing the slugbuilder memory limit: https://flynn.io/docs/apps#slugbuilder-limits

**Comment by mbajur** [comment]
Thank you so much! Will try that in a bit.

I'm trying to understand how Flynn works and where to look for answers - to
be honest I'm a bit overwhelmed by amount of different log files that Flynn
produces (that amount is totally understandable - but it's still a lot :) -
could you possibly point me to the log file you found info about npm
running out of memory? I'm gonna find the lines and quote them here to
maybe help someone find that issue on Google

Thanks in advance!

13.11.2016 18:17 "Jonathan Rudenberg" <notifications@github.com> napisał(a):

**Comment by titanous** [comment]
I didn't actually look at any log files, the line you pointed that said "Killed" was all I needed to see.

**Comment by titanous** [comment]
Though there may also be other problems, let me know if things are still not working after changing the slugbuilder memory limit.

**Comment by titanous** [comment]
After looking at the postgres logs, I believe that the WAL is corrupt after the crashes from the smaller VM, did you re-install Flynn or just bump the memory and reboot?

If things aren't working, I'd suggest starting from a clean installation to make sure there is no corrupt data.

**Comment by mbajur** [comment]
My (pretty crappy) VPS provider does not allows scaling VMs so I created a
bigger one and installed everything from scratch

13.11.2016 18:42 "Jonathan Rudenberg" <notifications@github.com> napisał(a):

**Comment by titanous** [comment]
Okay, in that case, something is wrong with Postgres:

```text
PANIC:  could not write to log file 000000010000000000000004 at offset 13631488, length 491520: Invalid exchange
STATEMENT:  commit
LOG:  server process (PID 96) was terminated by signal 6: Aborted
DETAIL:  Failed process was running: commit
LOG:  terminating any other active server processes
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2016-11-10 22:23:17 UTC
```

@josephglanville may have some ideas on why that happened.

**Comment by titanous** [comment]
Please post the output of `sudo zfs list` and `sudo df -h`

**Comment by mbajur** [comment]
Here are the outputs:

https://gist.github.com/mbajur/3d39f3db09efedb609d6043e8434a405

**Comment by mbajur** [comment]
Ok guys, i installed flynn from scratch on OVH SSD machine and the crash was not there so i think we can assume it was a one-time issue. I think that issue can be closed than.

Thanks for all your support!
