### ISSUE TITLE
How to overwrite entrypoint for docker

### ISSUE THREAD

**Issue by mbukosky** [flynn/flynn#3660]
Hi,

I am having trouble finding docs to set the entrypoint on a docker image. The docs say 

> You now have a release with an app process which runs using the pushed image and has an ENTRYPOINT, CMD and ENV as taken from the Docker image’s config.

but don't explain how to override the entrypoint.

I have tried the following command with no luck. Any ideas?

```
// Image was pushed successfully ...
$ flynn -a myapp run -e /tmp/scripts/start.bash
usage: flynn run [-d] [-r <release>] [-e <entrypoint>] [-l] [--] <command> [<argument>...]
```

Thanks

**Comment by lmars** [comment]
@mbukosky the `-e` flag is deprecated, just pass the script as `<command>`, i.e.:

```shell
$ flynn -a myapp run /tmp/scripts/start.bash
```

**Comment by mbukosky** [comment]
Thanks for the help but  I get the following error when I run that command

```
$ flynn -a myapp run /tmp/scripts/start.bash
unknown_error: Something went wrong
```

Any way to get more logging?

**Comment by lmars** [comment]
@mbukosky run `flynn -a controller log -t web -n 50` and see if there is an error reported.

**Comment by mbukosky** [comment]
Thanks I did find one error

`lvl=eror msg="attach wait failed: filesystem layer verification failed for digest sha256:xxx" component=controller req_id=yyy`

I guess there is something wrong with my docker image or setup? I'll keep digging around. Thanks again for the help.

**Comment by lmars** [comment]
@mbukosky do you have free disk space on the host? Check `df -h`.

**Comment by mbukosky** [comment]
oh snap, yeah I am working with 30 GB VMs and they are already out of space. That is what you get when you using a 9 GB docker image :(

Thanks for the help. You can close this out.

**Comment by lmars** [comment]
Ok we should try and make these issues more visible.

Also, just to let you know we have recently migrated to a new image format. Images are now stored in the ZFS zpool and can be garbage collected via `flynn-host volume gc`. It is in the current nightly version and will hit stable next week so you will likely get that the next time you decide to update your cluster.

**Comment by mbukosky** [comment]
Oh cool, I'll make sure to download the new version and try it out.
