### ISSUE TITLE
Can't create, delete or push apps: unknown_error: Something went wrong

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3661]
```
onnimonni@mac:~> flynn -c cluster2 -a project scale app=0
scaling app: 1=>0

unknown_error: Something went wrong
onnimonni@mac:~> flynn -c cluster2 -a blobstore env set DEFAULT_BACKEND=s3main
unknown_error: Something went wrong
```

This cluster is running 2months old build, which I plan to update soon.

I think this is because one of our flynn cluster didn't properly use s3 bucket before and the postgres is too full to handle anything atm.

Is there something I can do to free up space in postgres?

**Comment by kckrinke** [comment]
I just encountered a similar error while trying to set env variables in flynn and would love to know if there's any "garbage collection" utility for cleaning up anything that's on the root filesystem (ie: main postgres, /var/lib/docker/..., etc).

**Comment by titanous** [comment]
@kckrinke @onnimonni Have you both confirmed that you ran out of disk space on the hosts?

**Comment by kckrinke** [comment]
@titanous - 100% ran out of space for me - but I'm violating min specs with 10G rootfs (I read somewhere 40G is min) so don't take my specific error case as something worth investigating. Just echoing the need for some troubleshooting documentation around the garbage collection topic. Your gc.go program (from another issue) works great at helping me tame the flux in my constrained environment as an example.

**Comment by onnimonni** [comment]
In my case it's 5 node cluster and there's still plenty of space left:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on

# grid1
none             69G   38G   29G  57% /var/lib/docker/aufs/mnt/tmp-grid1.flynn.example.com-c3e36036-f571-44f3-a95c-eab1ae70183f

# grid2
none             69G   39G   28G  59% /var/lib/docker/aufs/mnt/tmp-grid2.flynn.example.com-a58e66d0-ced4-4752-9c42-94b93b4ef317

# grid3
none             69G   48G   19G  73% /var/lib/docker/aufs/mnt/tmp-grid3.flynn.example.com-0e4d21e0-f4c4-406d-8b42-59f8c52cc60c

# grid4
none             69G   38G   29G  57% /var/lib/docker/aufs/mnt/tmp-grid4.flynn.example.com-16d323ad-aaa6-4ffc-87be-40997481b74d

# grid5
none             69G   36G   31G  54% /var/lib/docker/aufs/mnt/tmp-grid5.flynn.example.com-aeabec30-0f6d-4466-87d3-ef32738070d4
```

I also checked other volumes but non of them was even near 100%.

**Comment by titanous** [comment]
@onnimonni Please provide the debug info.

**Comment by onnimonni** [comment]
I would but I can't
```
$ sudo flynn-host collect-debug-info --tarball
INFO[11-16|21:34:53] creating a tarball containing logs and debug information
INFO[11-16|21:34:53] this may take a while depending on the size of your logs
INFO[11-16|21:34:53] getting flynn-host logs
INFO[11-16|21:34:54] getting scheduler state
INFO[11-16|21:34:54] getting job logs
<--- Hangs over here
```

**Comment by titanous** [comment]
Okay, then please manually collect `/var/log/flynn` from each host.

**Comment by onnimonni** [comment]
I just upload this monster.tar.gz to google drive and send the link for you. Might take a few minutes.

**Comment by titanous** [comment]
@onnimonni It does look like it ran out of disk space. I'd suggest building a new cluster.

**Comment by titanous** [comment]
Closing this, as it doesn't appear to be a Flynn bug.
