### ISSUE TITLE
Multi node cluster fails after one node shuts down

### ISSUE THREAD

**Issue by wasi** [flynn/flynn#3670]
My goal is to set up a HA cluster of 3 nodes that can handle one node to shut down.
I have tried it many times with different releases (v20161017.1 and v20161108.0) but failed every time so far. This is the report of my latest attempt.

- Setup 3 x 4gb DO instance with 14.04.5 (flynn1-flynn3)
- manual install with nightly channel (v20161108.0)
- deployed one custom app (rails + postgres)
- made sure everything was running.
- Power off flynn3

The output from flynn1 (flynn2 similar)
````
root@flynn-1:~# flynn-host list
ID      ADDR                RAFT STATUS
flynn2  138.68.95.101:1113  peer
flynn1  138.68.73.165:1113  peer (leader)
root@flynn-1:~# flynn-host list
22:46:17.430385 host.go:157: object_not_found: service not found
root@flynn-1:~# flynn-host list
ID      ADDR                RAFT STATUS
flynn1  138.68.73.165:1113  peer (leader)
root@flynn-1:~# flynn-host ps
22:46:57.433005 host.go:157: could not list hosts: object_not_found: service not found
root@flynn-1:~# flynn-host list
22:47:00.079856 host.go:157: object_not_found: service not found
root@flynn-1:~# flynn-host list
ID      ADDR                RAFT STATUS
flynn1  138.68.73.165:1113  peer (leader)
flynn2  138.68.95.101:1113  peer
root@flynn-1:~# flynn-host list
ID      ADDR                RAFT STATUS
flynn2  138.68.95.101:1113  peer
root@flynn-1:~# flynn-host list
````

approx 10-20 sec delay between commands. The dashboard came back temporarily, the app did never (on previous attempts the app also came back for some time).

`flynn-host collect-debug-info` return `EROR[11-13|22:49:11] error getting scheduler state            err="Get http://100.100.98.5:5000/debug/state: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"` on both hosts. So I also created a tarball for `/var/log/flynn`

flynn1: https://gist.github.com/1d3aecc4f0a6a0784e995d0f06a787b2
https://transfer.sh/ABjTG/flynn1.tar

flynn2: https://gist.github.com/9ebd4b487bb68503f7c2f25c86c64567
https://transfer.sh/qlDuy/flynn2.tar

**Comment by wasi** [comment]
I did a quick try with v20161114.0 and it worked! :-) So its ok for me to close the issue.

**Comment by titanous** [comment]
Great!
