### ISSUE TITLE
host: Cluster monitor should verify PostgreSQL is read/write before starting controller jobs

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#3671]
If PostgreSQL isn't successfully repaired by starting the primary/sync then starting the controller jobs will fail.
This can lead to misleading errors when the source of the problem is the PostgreSQL cluster not achieving read/write.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
