### ISSUE TITLE
Import of App fails due to not supported --jobs argument

### ISSUE THREAD

**Issue by n0daft** [flynn/flynn#3673]
We are trying to migrate an app with a PostgreSQL database from a cluster A to a cluster B. The export was successful. The import however, fails with an error message.

### export statement
` flynn -a warden export --file warden.tar` (clusterA is default)

### import statement
`flynn -c clusterB import --file warden.tar`

**error message**
>Cluster versions prior to v20161018.0 don't support the --jobs argument for parallel restore.

`flynn -c clusterA --version` shows `v20161108.0`
`flynn -c clusterB --version` shows `v20161108.0`

logs from Cluster B (import):
[flynn-log.tar.zip](https://github.com/flynn/flynn/files/588840/flynn-log.tar.zip)

**Comment by lmars** [comment]
@n0daft this looks like a bug in the CLI, try:

```
flynn -c clusterB import --file warden.tar --jobs 1
```

**Comment by n0daft** [comment]
Your suggestion works. Thx.
