### ISSUE TITLE
Can't promote proxy after node failure

### ISSUE THREAD

**Issue by wasi** [flynn/flynn#3680]
I have a test setup of 3 nodes running v20161114.0 with one app. I powered off one node and the app kept alive, but some internal apps kept failing / recovering. For some time the dashboard was unavailable.
I added one node as replacement (with `flynn-host init --peer-ips`). After that the internal apps are running stable again. But I cannot promote the new node to peer (`host.go:157: unknown_error: Something went wrong`).

Debug Info:
peer 1: https://gist.github.com/a98daa3b188f74cfdf5e8a7e43d66d6e
peer 2: https://gist.github.com/431c9368e5fef8bcab849a5a32ae3006
proxy (new node): https://gist.github.com/6329b20e43b2aede192f8c195bb84aa5

**Comment by josephglanville** [comment]
Looks like the issue here is the current process requires the failed node to be demoted first.
I think it might be possible to make a promotion work in this case though which would be less confusing. You could try demoting the failed node first and before promoting the replacement and confirm that works that would be great.

**Comment by wasi** [comment]
I forced demotion and it seems to work (`Forcefully removed peer`).
but promotion doesn't work yet (`host.go:157: unknown_error: Something went wrong`).
logs: https://gist.github.com/cce809b16b49b9753cd7b6b673059dee

**Comment by josephglanville** [comment]
For some reason `138.68.105.244` doesn't seem to be reachable from ubuntu4. But if these logs are correct then a leader has been elected and the discoverd cluster should be working.

**Comment by wasi** [comment]
yeah. 138.68.105.244 is the dropped node.
