### ISSUE TITLE
TLS is not valid after 'flynn cluster migrate-domain'

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3681]
I'm doing the backup-restore update for one of our clusters and I wanted to change the address as well.

old domain was `old.example.com`.

I used:
```
$ flynn cluster migrate-domain new.domain.com
```

and it worked just fine. But after that I'm getting this error:

```
$ flynn apps
Get https://controller.new.domain.com/apps: pinned: the peer leaf certificate did not match the provided pin
```

After I just remove related tls pin from `~/.flynnrc`:
```
$ flynn apps
Get https://controller.old.example.com/apps: x509: certificate is valid for *.old.example.com, not controller.new.domain.com
```

**Comment by onnimonni** [comment]
I know that the TLS certificate is incorrect but I don't know how to replace it with new one because all of the commands output these errors.

**Comment by evantahler** [comment]
I wrote a bunch of stuff about this topic here https://blog.evantahler.com/productionizing-flynn-and-hosting-your-root-domain-s-fc849638e206

I think you need to still have a PIN, but generate it from your new cert. `openssl x509 -inform PEM -outform DER < key.pem | openssl dgst -binary -sha256 | openssl base64`

**Comment by onnimonni** [comment]
I already deleted this cluster and can't reproduce it anymore. I'll use your link if this happens again.

**Comment by jxltom** [comment]
I have exact same issue and solved it by re-installing manually instead of cloud installation and providing custom domain during the manual installation. Refer it [here](https://github.com/flynn/flynn/issues/3801#issuecomment-275387651) for more details. Wish there is a good solution without re-installing.
