### ISSUE TITLE
Having issues installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by bdevore17** [flynn/flynn#3687]
I have been trying to install flynn via ssh on ubuntu 16.04, before installing it asks me "If Flynn is already installed, it will be stopped and removed along with all data before installing the latest version. Would you like to proceed?". Flynn has not already been installed. I respond yes and the install fails and I again receive the same prompt. This continues on and on until I select 'No', which aborts the install.

I have pasted my logs below. Any help on this would be greatly appreciated.

**Comment by bdevore17** [comment]
Detecting authentication
Verified authentication for ******@*********
Allocating domain
Configuring DNS
Installing flynn
Installing flynn on *********
Running `curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn && sudo bash /tmp/install-flynn --clean` on ***********
<SUDO_PROMPT>
[1;33m===> 13:50:33.320 *** WARNING ***[0m
[1;33m===> 13:50:33.321 About to stop Flynn and remove all existing data[0m
[1;33m===> 13:50:33.323 Are you sure this is what you want?[0m
(yes/no): [1;32m===> 13:50:39.917 stopping flynn-host daemon[0m
[1;32m===> 13:50:39.921 running "systemctl stop flynn-host"[0m
Failed to stop flynn-host.service: Unit flynn-host.service not loaded.
[1;31m===> 13:50:39.928 ERROR: failed to run "systemctl stop flynn-host", exit status 5[0m
Installing flynn on ***********
Running `curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn && sudo bash /tmp/install-flynn --clean` on ***********
<SUDO_PROMPT>
Using cached password
[1;33m===> 13:50:51.254 *** WARNING ***[0m
[1;33m===> 13:50:51.256 About to stop Flynn and remove all existing data[0m
[1;33m===> 13:50:51.258 Are you sure this is what you want?[0m
Error: Install aborted

**Comment by bdevore17** [comment]
`Detecting authentication
Verified authentication for ******@*********
Allocating domain
Configuring DNS
Installing flynn
Installing flynn on *********
Running `curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn && sudo bash /tmp/install-flynn --clean` on ***********
<SUDO_PROMPT>
[1;33m===> 13:50:33.320 *** WARNING ***[0m
[1;33m===> 13:50:33.321 About to stop Flynn and remove all existing data[0m
[1;33m===> 13:50:33.323 Are you sure this is what you want?[0m
(yes/no): [1;32m===> 13:50:39.917 stopping flynn-host daemon[0m
[1;32m===> 13:50:39.921 running "systemctl stop flynn-host"[0m
Failed to stop flynn-host.service: Unit flynn-host.service not loaded.
[1;31m===> 13:50:39.928 ERROR: failed to run "systemctl stop flynn-host", exit status 5[0m
Installing flynn on ***********
Running `curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn && sudo bash /tmp/install-flynn --clean` on ***********
<SUDO_PROMPT>
Using cached password
[1;33m===> 13:50:51.254 *** WARNING ***[0m
[1;33m===> 13:50:51.256 About to stop Flynn and remove all existing data[0m
[1;33m===> 13:50:51.258 Are you sure this is what you want?[0m
Error: Install aborted`

**Comment by bdevore17** [comment]
Detecting authentication
Verified authentication for ******@*********
Allocating domain
Configuring DNS
Installing flynn
Installing flynn on *********
Running `curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn && sudo bash /tmp/install-flynn --clean` on ***********
<SUDO_PROMPT>
[1;33m===> 13:50:33.320 *** WARNING ***[0m
[1;33m===> 13:50:33.321 About to stop Flynn and remove all existing data[0m
[1;33m===> 13:50:33.323 Are you sure this is what you want?[0m
(yes/no): [1;32m===> 13:50:39.917 stopping flynn-host daemon[0m
[1;32m===> 13:50:39.921 running "systemctl stop flynn-host"[0m
Failed to stop flynn-host.service: Unit flynn-host.service not loaded.
[1;31m===> 13:50:39.928 ERROR: failed to run "systemctl stop flynn-host", exit status 5[0m
Installing flynn on ***********
Running `curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn && sudo bash /tmp/install-flynn --clean` on ***********
<SUDO_PROMPT>
Using cached password
[1;33m===> 13:50:51.254 *** WARNING ***[0m
[1;33m===> 13:50:51.256 About to stop Flynn and remove all existing data[0m
[1;33m===> 13:50:51.258 Are you sure this is what you want?[0m
Error: Install aborted

**Comment by bdevore17** [comment]
https://gist.github.com/bdevore17/16900cbd2aab1600d28d79af5f642ad1

**Comment by lmars** [comment]
This looks like a bug, we'll fix it.

**Comment by lmars** [comment]
Fixed in #3688, we'll post again here when it has been released to `dl.flynn.io`.

**Comment by bdevore17** [comment]
Thanks!

**Comment by titanous** [comment]
The fix for this has been deployed.
