### ISSUE TITLE
Support for ElasticSearch Appliance

### ISSUE THREAD

**Issue by timjurka** [flynn/flynn#3693]
For applications that require full document indexing and ranking at search time, ElasticSearch would be a helpful appliance to be bundled by default.

**Comment by lmars** [comment]
Elasrticsearch is on our list of appliances to add next.

**Comment by lalloni** [comment]
Are there any plans already setup for the implementation of this?

I may have some time to work on this.

**Comment by titanous** [comment]
@lalloni We have not spent much time on it yet. There are some architectural questions, like for example should we try to make a discoverd plugin for discovery/leader election, similar to the now outdated Zookeeper plugin?

**Comment by lalloni** [comment]
@titanous What would be the need satisfied by such discoverd plugin? Can you provide a link to zookeeper discoverd plugin so I can take a look anyway? (I can't find it using github/google).

**Comment by titanous** [comment]
https://github.com/grmblfrz/elasticsearch-zookeeper

The idea is that it would mitigate some of the stability issues in ES: https://www.elastic.co/guide/en/elasticsearch/resiliency/current/index.html

**Comment by darbio** [comment]
+1 and happy to help

**Comment by johnnagro** [comment]
+1 also happy to help

**Comment by OfekA** [comment]
What is the current status of this issue?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
