### ISSUE TITLE
Support for RabbitMQ appliance

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#3694]
A clustered and flynn managed RabbitMQ appliance would be awesome.

**Comment by aemadrid** [comment]
+1

**Comment by aemadrid** [comment]
If getting this would take too long or it is not in the immediate roadmap it would help greatly to get some help in how to run RabbitMQ with docker images.

**Comment by josephglanville** [comment]
You can run any RabbitMQ docker image using the existing Docker documentation right now if you don't need persistence. Clustering may prove more difficult you probably want to look at https://github.com/aweber/rabbitmq-autocluster/ and configure it to use DNS for service discovery.

**Comment by aemadrid** [comment]
Thanks for the info on the autocluster project. I do need persistence though. Non-persistant queues are of not much use to me.

**Comment by josephglanville** [comment]
Depending on your requirements something like https://github.com/chanks/que may fit the bill. It would be persistent but it wouldn't have all of RabbitMQ's features ofcourse.

**Comment by aemadrid** [comment]
Thanks for the info. I've looked at [que](https://github.com/chanks/que) before but we do need the exchanges/OUBSUB functionality that RabiitMQ provides.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
