### ISSUE TITLE
Am I able to set subdomain to custom path?

### ISSUE THREAD

**Issue by regedarek** [flynn/flynn#3695]
I have route:

```
http:panel.kw.krakow.pl          kw-app-web  http/401f0cbc-bd3a-4e38-9cd7-f27f29ae1c6f  false   false   /
```

And I would like to set up another: `wypozyczalnia.kw.krakow.pl` to `panel.kw.krakow.pl/reservations/new`

Can I achieve this?

**Comment by titanous** [comment]
The Flynn router doesn't support rewriting paths, so you'd create a route for wypozyczalnia.kw.krakow.pl and then rewrite the path in your app based on the `Host` header.

**Comment by regedarek** [comment]
thanks, solution in rails:

```
  get '/', to: 'reservations#new', constraints: lambda{|request|request.env['SERVER_NAME'].match('wypozyczalnia')}
```
