### ISSUE TITLE
"Open" a slug?

### ISSUE THREAD

**Issue by evantahler** [flynn/flynn#3696]
I've got an application I'm deploying where something is going wrong with the build process.  Since I'm using the S3 blobstore, I can find and download the slug from my deployments.   How do I "open" this file?  It doesn't appear to be a `tar`, a `tar.gz`, etc... 

Specifically, I'm pre-compiling some assets which might be using the `/tmp/app` directory as an absolute path

**Comment by titanous** [comment]
What version of Flynn are you running on the servers? (`flynn-host version`)

**Comment by evantahler** [comment]
`v20161114.0`.

**Comment by titanous** [comment]
It's a SquashFS filesystem, `unsquashfs` from the `squashfs-tools` package (`squashfs` in Homebrew) knows how to extract it.

**Comment by evantahler** [comment]
Hmm... no dice.
I've got a 35MB slug and there seems to be no content inside of it:
```
unsquashfs 92b10381-2b10-49e7-882c-abcd03558443 -i
Parallel unsquashfs: Using 8 processors
0 inodes (0 blocks) to write



created 0 files
created 1 directories
created 0 symlinks
created 0 devices
created 0 fifos
```

I can confirm that the build cache, which creates a `*.gz` file containing my `node_modules`, looks great (and I can extract it)

**Comment by titanous** [comment]
What does `file 92b10381-2b10-49e7-882c-abcd03558443` say?

**Comment by evantahler** [comment]
> file 92b10381-2b10-49e7-882c-abcd03558443
92b10381-2b10-49e7-882c-abcd03558443: Squashfs filesystem, little endian, version 4.0, 35849068 bytes, 14492 inodes, blocksize: 131072 bytes, created: Wed Nov 16 19:01:10 2016

I'm also happy to share the file with you, there's nothing private in it. 

(Thanks for all your help BTW)

**Comment by lmars** [comment]
@evantahler 

> I'm pre-compiling some assets which might be using the /tmp/app directory as an absolute path

`/tmp/app` is a temporary directory and those files don't end up in the slug. Buildpacks are given a directory as their first argument which is where files should be created.

**Comment by evantahler** [comment]
@lmars yep, makes sense! I just want to confirm that is what is happening... 
re: https://github.com/zeit/next.js/issues/198

**Comment by lmars** [comment]
@evantahler please share the file (you can send it to logs@flynn.io)

**Comment by evantahler** [comment]
sent!

**Comment by lmars** [comment]
@evantahler I was able to extract the slug:

```
$ unsquashfs 92b10381-2b10-49e7-882c-abcd03558443 
Parallel unsquashfs: Using 4 processors
12525 inodes (12932 blocks) to write

[=========================================================================================================================================================================================|] 12932/12932 100%

created 12502 files
created 1967 directories
created 23 symlinks
created 0 devices
created 0 fifos

$ unsquashfs -version
unsquashfs version 4.3 (2014/05/12)
```

This is on OSX, installed with `brew install squashfs`.

I think you just need to drop the `-i` flag.

**Comment by evantahler** [comment]
well... I'm feeling very foolish.  
Thanks You!

**Comment by evantahler** [comment]
But hey, now when I google this next time, I'll find this :D

**Comment by lmars** [comment]
No problem, happy to help!
