### ISSUE TITLE
Host tags not working

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3699]
I am setting up a cluster to have higher powered hardware that will run the flynn cluster databases. I set a host tag as such `flynn-host tags set flynnhost private=true`. Then ran a scale `flynn -a postgres scale postgres=3,private=true web=2`, that output `persisting tag change`. When I ran `flynn -a postgres limit set postgres memory=6GB` it started the postgres on a server not tagged with `private=true`.

**Comment by bbaptist** [comment]
Just to note, I ran the `flynn-host tags` on all three hosts I wanted to run the postgres services.

**Comment by bbaptist** [comment]
Also forgot to mention this is with the latest stable `v20161114.0`

**Comment by lmars** [comment]
It seems tags are being dropped during deployments (e.g. [here](https://github.com/flynn/flynn/blob/master/controller/worker/deployment/one_by_one.go#L59-L63)).

This is actually fixed in #3667 but that has some outstanding changes before being merged, I suspect it will make it into master in say a week from now.

@bbaptist are you able to wait for that?

**Comment by bbaptist** [comment]
I guess this I will have to bring up the cluster/postgres on the hosts we want and then migrate to the new stable version next month.

**Comment by bbaptist** [comment]
Will we hit this bug for scheduling user defined apps? Meaning if I have a host tag of `public=true` and scale `web=1,public=true` will it put that app on the public server?

**Comment by lmars** [comment]
@bbaptist tags are unfortunately not currently usable, they work for scaling but a deployment effectively deletes the tags. This will be fixed in #3667.

**Comment by bbaptist** [comment]
Ouch, that torpedoes us using this until they are fix then.
