### ISSUE TITLE
After a backup restore upgrade, the logagreggator process is spiking one or two nodes CPUs

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3700]
Hi,
every time, I upgrade a three node cluster via backup restoring, I have one or two nodes with spiking CPU cores. This doesn't settle after even after 30 minutes.
There are one to four instances of /bin/logagreggator around, all two cores of the node(s) are saturated.
There is no unusual amount of logging arround. flynn-host stop <logagreggator ids> fixes the situation.
@titanous is suspecting filled up buffers which don't refill by restarting the process.

**Comment by titanous** [comment]
IRC conversation: https://botbot.me/freenode/flynn/2016-11-16/?msg=76578124&page=2

**Comment by philiplb** [comment]
@titanous When I upgrade to v20161114.0p1, should there any profiling or similar happen?

**Comment by titanous** [comment]
Haven't gotten to adding that code yet, will do so before the next stable release.

**Comment by philiplb** [comment]
@titanous Upgraded to v20161218.1 and had to kill the logaggregator again.
(Otherwise all was/is good)

**Comment by philiplb** [comment]
For the first time, this hasn't happen during an upgrade (to v20170217.0). So I'm closing this. :)

**Comment by philiplb** [comment]
Happened again when I restored a cluster running v20170217.0 and today when I upgraded to v20170321.0.

**Comment by kwando** [comment]
You are not alone, I usually see this when upgrading my clusters too.

**Comment by philiplb** [comment]
Hi,
I just discovered, that after restoring, the MariaDB needs about 30min (for us) to catch up and replicate. Meanwhile, I get messages once in a second like this in
```bash
flynn -a mariadb log -f -i
```

> 2017-07-28T13:56:13.753494Z app[mariadb.Flynn1-a56468eb-fef9-44bb-bcaa-c32ec6aeeb80]: t=2017-07-28T13:56:13+0000 lvl=eror msg="error reading slave xlog" app=mariadb fn=waitForSync sync_name= start_time=2017-07-28T13:56:12+0000 err="dial tcp 100.100.68.22:3306: getsockopt: connection refused"

It ends with:

> <some status messages>
> 2017-07-28T13:56:19.785548Z app[mariadb.Flynn1-a56468eb-fef9-44bb-bcaa-c32ec6aeeb80]: t=2017-07-28T13:56:19+0000 lvl=info msg="finished waiting for downstream replication" app=mariadb fn=waitForSync sync_name= start_time=2017-07-28T13:56:17+0000

And afterwards, everything is fine. So I think this is resolved.

**Comment by philiplb** [comment]
I'm afraid this was not the cause, just happened again.

**Comment by philiplb** [comment]
I just restored a cluster from backup. But before I started the flynn-host daemon, I deleted /var/log/flynn/*.log on all nodes. This time, the logagregator behaves fine. So closing this until it occures again.
