### ISSUE TITLE
TUF Repo error

### ISSUE THREAD

**Issue by JMSwag** [flynn/flynn#3705]
Hey Gentlemen,

Can someone confirm the tuf repository is up to date. I'm getting an "unknown target file" error when attempting to manually install flynn.

```
$ sudo ./install-flynn --clean --yes --channel nightly --version v20161111
...

===> 11:00:35.459 running "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin"
INFO[11-17|11:00:35] initializing TUF client
INFO[11-17|11:00:39] downloading components with version v20161111
INFO[11-17|11:00:39] downloading images
11:00:39.342293 host.go:157: tuf: unknown target file: v20161111/version.json.gz
===> 11:00:39.358 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 1

```

**Comment by titanous** [comment]
You are specifying a version that doesn't exist. What version do you want?

**Comment by titanous** [comment]
It's worth noting that you can leave off the `--version` flag to get the latest version from a channel.

**Comment by JMSwag** [comment]
The latest stable would be fine.

```
$  sudo ./install-flynn --clean --yes
...

INFO[11-17|11:16:14] initializing TUF client
INFO[11-17|11:16:18] getting configured release channel
INFO[11-17|11:16:18] determining latest version of stable release channel
INFO[11-17|11:16:18] latest stable version is v20161114.0
INFO[11-17|11:16:18] downloading components with version v20161114.0
INFO[11-17|11:16:18] downloading images
11:16:18.622108 host.go:157: tuf: unknown target file: v20161114.0/version.json.gz
===> 11:16:18.640 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 1

```

**Comment by titanous** [comment]
Hmm, I can't reproduce that issue, it must be a CDN glitch. I'll run an invalidation, please try again in 30 minutes.

**Comment by JMSwag** [comment]
Ack. Thanks!

**Comment by lmars** [comment]
@JMSwag the issue here is probably because you are using an old install script, you should download the latest script (`curl -o install-flynn https://dl.flynn.io/install-flynn`) and try again.

**Comment by JMSwag** [comment]
@lmars That fixed it. Thanks guys.

**Comment by SalvoLunar** [comment]
Hey guys,

Getting this error:
===> 11:43:58.017 running "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin"
/tmp/install-flynn: line 398: ./flynn-host: cannot execute binary file: Exec format error
===> 11:43:58.027 **ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 126**

Does anybody have any clue of how to fix this?

**Comment by titanous** [comment]
What is the output of `uname -a`?

**Comment by SalvoLunar** [comment]
Just read somewhere that Flynn doesn't work on ARM, after switching to X86 everything is working.
