### ISSUE TITLE
Better slug scalability

### ISSUE THREAD

**Issue by nickandrew** [flynn/flynn#371]
I'm using flynn/slugbuilder and flynn/slugrunner under Mesosphere, actually, to run a sample application inside a docker container. After trying (and failing) to scale up to 100 instances, I realised the slug pattern isn't helping scale. Key requirement is that multiple instances of the app should share the same memory and/or disk blocks whenever possible.

The flynn/slugrunner container is the same for all instances, so that'll be shared, but it downloads the app from a URL, so that means (a) a GET request for every instance, and (b) the resulting unpacked application is specific to each container (i.e. not sharing disk blocks). This would be better if my app were burned into the container, then all instances would share exactly the same disk blocks.

As for memory, I don't know how much shared memory is possible with perl apps, since each .pm module is compiled by the interpreter. Perhaps the application itself has to fork after perl loads the modules, to get a benefit here.

Feel free to treat this as a comment. I'm just thinking to improve scalability you might consider adding a variant to slugbuilder which would create a container with the app burned into it.

**Comment by lmars** [comment]
Slugs are now SquashFS filesystems, mounted once and shared between all jobs on a single host (see #3619).
