### ISSUE TITLE
sudo: start: command not found

### ISSUE THREAD

**Issue by scottrobertson** [flynn/flynn#3716]
Hey

Trying a manual install (to upgrade to the latest version) on Ubuntu 16.04 (Digital Ocean). Getting the following error when running `sudo start flynn-host` from the docs:

`sudo: start: command not found`

**Comment by josephglanville** [comment]
The install script installs a systemd unit for `flynn-host`, something like `systemctl start flynn-host` should work. 16.04 support has just landed so there are some sections in the docs that need to account for both 14.04 and 16.04 that haven't been updated yet.

**Comment by scottrobertson** [comment]
> 16.04 support has just landed so there are some sections in the docs that need to account for both 14.04 and 16.04 that haven't been updated yet.

Oh yeah, totally aware of that, that is mainly why I opened this to point it out :)

**Comment by titanous** [comment]
This was fixed by #3777.
