### ISSUE TITLE
util/cedarish: Missing packages

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3717]
The Heroku Cedar 14 stack has `postgresql-client-9.5` but this is missing from the Flynn cedarish image.

We should check what other packages are missing too:

https://devcenter.heroku.com/articles/cedar-ubuntu-packages

Perhaps write a script which parses that page and updates the [Dockerfile](https://github.com/flynn/flynn/blob/master/util/cedarish/Dockerfile).

**Comment by lmars** [comment]
P.S. if you need a package which is missing, consider using the [Apt buildpack](https://github.com/heroku/heroku-buildpack-apt) (add it to `.buildpacks` along with the buildpack you use, and put your packages in `Aptfile`).

**Comment by lmars** [comment]
Or maybe we should just run the Heroku `cedar-14.sh` script:

https://github.com/heroku/stack-images/blob/master/bin/cedar-14.sh

**Comment by lmars** [comment]
Or just use the [Heroku Cedar Docker image](https://hub.docker.com/r/heroku/cedar/) rather than building our own...

**Comment by slurms** [comment]
Would it also be useful to have a concept similar to heroku's stacks: https://devcenter.heroku.com/articles/stack? That way people could configure the base image / os that their applications are run on relatively easily (and flynn could provide a ubuntu 16.04 version of the current slugbuilder image).

**Comment by lmars** [comment]
@slurms in terms of deploying using Heroku buildpacks, we plan to provide the same stacks that Heroku do to maintain as much compatibility as possible (some buildpacks may not currently function on 16.04 for example).

Moving forward, we plan to provide other build strategies which support arbitrary workflows (see #3753 for the beginnings of that).

**Comment by slurms** [comment]
@lmars nice, I didn't see that, but it looks like the best approach :+1:. This is one of the things I'm most looking forwards to (that and letsencrypt support). Ideally it'd be great to be able to specify your own docker image to build from on a per-application level.

**Comment by nicolas-brousse** [comment]
Hi,

Do you still plan to do this changes? And also support ubuntu 16.04 stack?

Heroku have also an [Heroku 16 Docker image](https://hub.docker.com/r/heroku/heroku/).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
