### ISSUE TITLE
flynn-host can not start

### ISSUE THREAD

**Issue by wuyi78951** [flynn/flynn#3720]
https://gist.github.com/anonymous/bb40957ca112b865554c9607db7b82c3

**Comment by josephglanville** [comment]
What is the exact problem you are experiencing? From the debug logs `flynn-host` appears to be running:
```
root      2745  0.0  0.0 1178076 23752 ?       Ssl  09:43   0:00 /usr/local/bin/flynn-host daemon
```

**Comment by josephglanville** [comment]
Looking closer it appears you have restarted either `flynn-host` or the node it's running on and resurrection hasn't worked correctly.

**Comment by wuyi78951** [comment]
Mainly do not see the situation of Flynn running:
1. status flynn-host  no results
2. flynn-host ps prompt 10:58:14.795452 host.go:157: Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused...
I have used --clean to re-install a few times, still did not solve.

**Comment by josephglanville** [comment]
Ahh I see, so the bootstrap steps outlined here https://flynn.io/docs/installation/manual have not been run successfully?

I suggest using the graphical installer if the manual installation process isn't working for you. You can use it with the SSH installer mode to use it on any server.

**Comment by wuyi78951** [comment]
thanks, i will try

**Comment by wuyi78951** [comment]
i run flynn install, but firefox no response, why?

**Comment by josephglanville** [comment]
Are you running `flynn install` on your local machine? If not you need to download the CLI to your workstation and run it from there.

**Comment by wuyi78951** [comment]
yes, i first run L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
second run flynn install, but can't run my browser

**Comment by wuyi78951** [comment]
i copy the address from konsole to my browser chrome can run, but  the prompt message is 'the authenticity of host XXXX can't be established', Are you sure you want to continue connecting?

**Comment by wuyi78951** [comment]
I'm sure my username and password are correct.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
