### ISSUE TITLE
Postgres in singleton mode on multi-node cluster

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3725]
I ran a cluster backup then restored on a new cluster with 4 nodes. The restore came up fine, but the output of `curl http://127.0.0.1:1111/services/postgres/meta` shows postgres is still in singleton mode. Is this expected behavior when restoring to a multi-node cluster if postgres was in singleton mode on the previous cluster? Is there any way to switch postgres out of singleton mode short of spinning another cluster and importing apps 1-by-1? Output of above curl in the gist below.

https://gist.github.com/kevinob11/7730c116354fc2dcaa6afc9f11908a94

**Comment by titanous** [comment]
Did you specify `-n 4` when bootstrapping?

**Comment by kevinob11** [comment]
Yep, below is my exact bootstrap command.

`sudo flynn-host bootstrap --min-hosts 4 --discovery https://discovery.flynn.io/clusters/57d39664-fa8a-480b-97c4-370a6e98c111 --from-backup /mnt/oldflynn/backup.tar`

**Comment by titanous** [comment]
What version of Flynn?

**Comment by kevinob11** [comment]
Current latest `v20161114.0p1`

**Comment by titanous** [comment]
It looks like the fix (https://github.com/flynn/flynn/commit/48adeff42c4fb98822d51fd00eaf4f0c3adeef1d) for this issue came after the stable release, so you'll need to install the nightly or do the app import/export.

**Comment by kevinob11** [comment]
Ok, thanks!
