### ISSUE TITLE
Is it possible to use docker images to make third party binaries available to the main App ?

### ISSUE THREAD

**Issue by pgaultier** [flynn/flynn#3729]
Right now, We are using `Flynn` successfully to deploy php applications to our cluster.

In our latest app, we are using third-parties binaries (`pdftk` not to mention it) we need to deploy into our `flynn` environment.

Is there a way to link external docker containers to make tools easily available to the PHP app ?

For example, in our case, we would like to make `cartoncloud/pdftk` image available to our app in order to be able to run `docker run cartoncloud/pdftk` from the PHP application.

**Comment by titanous** [comment]
There is no easy way to do `docker run` from Flynn. There are internal APIs that could be used to do something similar, but it would be relatively complicated and rely on internal implementation details.

I think your best option would be to create a Docker image and HTTP API that wraps `pdftk` that is called by your apps. You could also build your app in a Docker image instead or use the [apt buildpack](https://github.com/heroku/heroku-buildpack-apt) to get the binaries into the app container.

**Comment by pgaultier** [comment]
Thank you very much for your answer. 

The apt buildpack way should do the trick right now.
