### ISSUE TITLE
Define an output file for `flynn-host collect-debug-info`

### ISSUE THREAD

**Issue by sleighter** [flynn/flynn#3732]
I want to automate the process of collecting debug info from several hosts and uploading the resulting tarballs to an s3 bucket. I'd like to trigger this operation via an Ansible playbook. To do this, I need to know specifically where `collect-debug-info` writes its output. 

Currently the command uses a random temp file, making it difficult to automatically upload the file after creation. The location of the tarball would have to be parsed from the humanized output message from the command.

I have two ideas for providing this capability:
 1. Add a `--out-file` option to `flynn-host collect-debug-info` to define the output file. Could either overwrite an existing file or consider a `--overwrite` flag to force the operation.
 2. Add option to write the tarball to stdout (just like `flynn cluster backup`), so the output can be piped directly to an S3 file.

**Comment by lmars** [comment]
Related to #3284.
