### ISSUE TITLE
Error in adding clusters doc

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3735]
I think there is an error in the documentation for adding a cluster via the CLI. The docs specify a controller domain which is the cluster domain prepended by `https://controller.` but when I use a full controller domain I end up with a misconfigured cluster because the git url is set to `https://git.https://controller.paas.praece.com`. I am able to set up the cluster properly using just the cluster domain, in this example `paas.praece.com`.

**Comment by kevinob11** [comment]
Link to referenced doc: https://flynn.io/docs/cli#adding-clusters

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
