### ISSUE TITLE
dashborad.* should be flynn.*

### ISSUE THREAD

**Issue by evantahler** [flynn/flynn#3737]
When creating a new Flynn cluster, the "dashboard" app is mounted at `dashboard.app.com`.  However, `dashboard` is a very common subdomain your application may want to use.  To that end, I suggest that the Flynn UI application reside at `flynn.app.com` rather than `dashboard.app.com` by default

**Comment by evantahler** [comment]
Also, changing that URL causes some front-end JS problems: 
<img width="872" alt="screen_shot_2016-11-28_at_4_19_30_pm" src="https://cloud.githubusercontent.com/assets/303226/20691557/b063c7a0-b586-11e6-8c24-9490f0bd82d4.png">

**Comment by titanous** [comment]
We also use other generic subdomains like `status`, `git`, `docker`, `controller`, and so on. Short of prefixing everything with `flynn-`, I think the best option is to not use your primary domain as the cluster domain.

**Comment by evantahler** [comment]
I guess that's fair... and I can certainly do the prefixing myself.... so I guess the real issue is the JS which seems to expect the URL to really be "dashboard.*"

**Comment by titanous** [comment]
Try changing the `URL` env var for the `dashboard` app.

**Comment by evantahler** [comment]
Ah! That did it.  
Thanks!
