### ISSUE TITLE
can't create cluster in chrome

### ISSUE THREAD

**Issue by wuyi78951** [flynn/flynn#3738]
when i create clusters in chrome, the prompt message is 'the authenticity of host XXXX can't be established', Are you sure you want to continue connecting?

**Comment by scottrobertson** [comment]
Not sure about how Flynn does this, but this usually happens when you SSH into a host, reinstall that host, and then try and SSH in again. Maybe try checking if it's in ~/.ssh/known_hosts` and remove it from there if it is.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
