### ISSUE TITLE
Container zvol near capacity

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3746]
One of my app container zvol file systems is nearing capacity. Root fs and zfs zpool both have plenty of space. Output of both `sudo zpool list` and `df -h` are in the gists below. The id of the container nearing capacity is `paasf-59d2b5cf-84f4-4bef-a3ff-c354cb1018f8`. Will flynn manage these for me? Can I safely turn off monitoring on these volumes?

https://gist.github.com/kevinob11/761db221cd782997730e2c5f7781427e
https://gist.github.com/kevinob11/d732e9da44719f7a6bb5b97ed5cf4c75

**Comment by titanous** [comment]
By default 100MB is allocated for temporary files written by each container. If you fill this up, subsequent writes of files will get a standard `ENOSPC` error. You can increase the limit with a command like this:

```text
flynn limit set web temp_disk=500MB
```

**Comment by kevinob11** [comment]
Right, works great, thanks!

**Comment by mbukosky** [comment]
@titanous I am running into the same issue when trying to upload and run a docker image. I am unable to set the `temp_disk` because of the following error

```
flynn -a my-docker-app limit set web temp_disk=500MB
Warning: "web" is not an existing process type, setting anyway
invalid resource limit type: ["temp_disk" "500MB"]
```

I also tried this with app and got the same error. Any ideas?

**Comment by titanous** [comment]
@mbukosky The process type for a Docker app is typically `app`, so try that instead of `web`. If that doesn't work, what version of Flynn do you have on the server? (`flynn-host version`)

**Comment by mbukosky** [comment]
@titanous here is the information you asked for. Calling limit on `app` didn't work either. Any other ideas?

* error setting temp_disk
```
$ flynn -a my-docker-app limit set app temp_disk=500MB
invalid resource limit type: ["temp_disk" "500MB"]
```

* cli
```
$ flynn version
v20161031.0
```

* host
```
$ flynn-host version
v20161114.0p1
```

**Comment by titanous** [comment]
Try again after running `flynn update`

**Comment by mbukosky** [comment]
Thanks for the help, I am in the middle of a demo and don't want to risk updating the cli. Will try this out next week.
