### ISSUE TITLE
Postgres in read-only mode after node failure

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3748]
We brought down 1 node in a 3 node cluster to test failover. Postgres went into read-only mode and hasn't recovered after about 15 minutes. Below is a drive folder of the debug info for the other two nodes while the third node is still down, I'll post debug info for the third node when we bring it back up shortly.

https://drive.google.com/open?id=0B418afhyEfo4VG4xTlo3cGZBa1E

**Comment by kevinob11** [comment]
After bringing the 3rd node back up postgres immediately recovered, logs from the 3rd node (labeled G) are now in the folder as well.

**Comment by josephglanville** [comment]
Is there any chance you could retry capture of logs from the last node G.
The logs for it's discoverd job are missing. Would also show how the cluster eventually recovered.

**Comment by kevinob11** [comment]
Ok, I've added a second version of the "G" node logs.

https://drive.google.com/open?id=0B418afhyEfo4VG4xTlo3cGZBa1E

**Comment by kevinob11** [comment]
@josephglanville I've added the logs in the same folder, anything else I can get you to help with diagnosis?

**Comment by josephglanville** [comment]
This should be enough now, it takes a little while to get to the bottom of what went wrong with these sometimes but I am looking into it.

**Comment by kevinob11** [comment]
Thanks for looking into it!

**Comment by kevinob11** [comment]
@josephglanville any luck? Sorry to be pushy, just looking to get an idea so I can schedule my next stress test.

**Comment by kevinob11** [comment]
@josephglanville @titanous any progress?

**Comment by josephglanville** [comment]
@kevinob11 I made some progress before heading off for the Christmas/NYE break but didn't find the root cause. Will be looking at this and similar failures/error conditions this coming week when I get back. :)

**Comment by kevinob11** [comment]
@josephglanville Thanks!

**Comment by josephglanville** [comment]
Just letting you know I haven't forgotten about this, sorry it's taking a while things have been hectic coming off holidays.

**Comment by kevinob11** [comment]
Thanks for the check in, and for looking into it!
