### ISSUE TITLE
flynn cluster backup breaks my terminal

### ISSUE THREAD

**Issue by shockey** [flynn/flynn#3749]
So.... Long story.

I was trying to deploy a new version of my app to Flynn, so I pushed. I got an error that looked like an OOM error back from the Git remote:

```
Killed                  npm install
```

Awesome. I SSHed into the node (this is a single-node cluster) and added a 2GB of swap, to augment the 2GB of RAM.

Then I push again, and get this:

```
remote: mkdir: cannot create directory '/tmp/build/.heroku': No space left on device
remote: ERROR: Build failed: exec: job exited with status 1
```

I took a look at FS usage, and sure enough, the disk was full. Looks like some Docker files have clogged up everything, in a similar fashion to #1565.

I tried to run the scripts mentioned in #1565 and siblings to serve as a stopgap. No dice, `df -h` still showed zero free bytes. Next, I decided to do an in-place upgrade to see if that would solve the Docker problem. As suggested in the documentation, I ran a `flynn cluster backup` first.

That went well for a couple of minutes, but then my fans came on. My terminal was pegging my CPU! This was in the window when it locked up:

![image](https://cloud.githubusercontent.com/assets/680248/20959375/37d93cfc-bc20-11e6-9ed3-4065b02fd4ec.png)

My `flynn-host --version` is `v20160918.1`.

With so many things going wrong here, I'm concerned about the state of my node. The cluster in question is used for production.

Help? 😨

**Comment by imjorge** [comment]
@shockey regarding the output you are seeing when running `flynn cluster backup`, that is the backup tar file being written to stdout. As per the docs:

```
    backup
        Takes a backup of the cluster.

        The backup may be restored while creating a new cluster with
        'flynn-host bootstrap --from-backup'.

        options:
            --file=<backup-file>  file to write backup to (defaults to stdout)
```

Note the information:

> --file=<backup-file>  file to write backup to (defaults to stdout)

So you probably want to run something like:

```
flynn cluster backup --file=backup.tar
```

**Comment by shockey** [comment]
Thanks @imjorge. I didn't reference the backup/restore docs that were right above [this section](https://flynn.io/docs/production#in-place-update) in the docs, rather I copy-pasted `flynn backup cluster` from that section. 

Closing!
