### ISSUE TITLE
docker err mounting "/" to rootfs "/var/lib/flynn/image/mnt..."

### ISSUE THREAD

**Issue by philejmath** [flynn/flynn#3750]
Since I updated to the November release I can't seem to get docker containers that were previously working to start up in Flynn cluster. 

I've tried these containers: 
sebp/elk:es241_l240_k461 (elastic search) 
jenkins 

There are no errors in the app logs. 

scale output: 
> Timed out waiting for job events. Waited 20 seconds.
> expected: map[app:map[up:1]]
> actual: map[app:map[pending:7 starting:6 down:6]]

flynn-host.log:
> t=2016-12-07T14:34:21+0000 lvl=eror msg="error running job" app=host pid=11368 host.id=ip1006158 fn=AddJob job.id=ip1006158-d200dcd8-6dd1-4acb-bd4b-cfc96cdd5623 err="rootfs_linux.go:53: mounting \"/\" to rootfs \"/var/lib/flynn/image/mnt/ip1006158-d200dcd8-6dd1-4acb-bd4b-cfc96cdd5623\" caused \"no such file or directory\""

**Comment by lmars** [comment]
@philejmath sorry it took a while to respond, it looks like there is an issue when there are lots of layers, I can see this in `dmesg`:

```
overlayfs: failed to resolve '/var/lib/flynn/volum': -2
```

So it looks like something is being truncated. I'll push a fix in the next few days.

**Comment by lmars** [comment]
Fix proposed in #3758.
