### ISSUE TITLE
Feature: Automated management of round robin DNS for cloudflare

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3751]
Thoughts on adding automated management of round robin DNS for the cluster for users on Cloudflare? It wouldn't cover all users, but I think it is a pretty common use case. I realize I could create this myself using a monitoring tool and a small app that connects to the Cloudflare api, but it would be great if it was build in!

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
