### ISSUE TITLE
Latency between Flynn hosts and multiple regions

### ISSUE THREAD

**Issue by guestisp** [flynn/flynn#3754]
I've seen in docs that is not advisable running Flynn hosts over wan

This makes impossible to create a cluster across multiple regions, right?

In addition, when setting a tag on some Flynn hosts, how can i scale an up by placing one instance on tag1 and other instance on tag2?

In other words, how can i scale an app over multiple regions?

**Comment by titanous** [comment]
> This makes impossible to create a cluster across multiple regions, right?

You should not run a cluster across hosts with more than a few milliseconds latency between them.

> In other words, how can i scale an app over multiple regions?

You should run a separate cluster in each region.
