### ISSUE TITLE
Reset login token

### ISSUE THREAD

**Issue by pyr0hu** [flynn/flynn#3755]
I reinstalled my computer and forgot to save the ~/.flynnrc file, so now, I don't have access to the login token. Can I retrieve it anyhow? I have access to the flynn-host machine, but couldn't find anything to retrieve

**Comment by lmars** [comment]
@pyr0hu you can find the login token by grabbing the job ID of the dashboard job with `flynn-host ps` and then getting the environment variables with `flynn-host inspect`, here is a one-liner:

```
$ flynn-host ps | grep dashboard | awk '{print $1}' | head -1 | xargs flynn-host inspect | grep -F 'ENV[LOGIN_TOKEN]'
```

**Comment by pyr0hu** [comment]
greatly appreciated! thanks
