### ISSUE TITLE
Cluster gone berzerk

### ISSUE THREAD

**Issue by walski** [flynn/flynn#3757]
Hey, I'm trying to recover a 3 node cluster which seems to have gone totally crazy. First one of the nodes accumulated more than 2,600 ZFS mounts and started to demote itself to "proxy" all the time. Trying to fix this I destroyed all volumes on that node and re-installed Flynn with the ``--clean`` flag. But that didn't help at all. Now the remaining two nodes in the cluster seem to be in some sort of weirdo mode, too where the current leader has 35,000+ (!!) jobs and the third node is not able to integrate into the cluster anymore at all.

Is there any way to say "reset" the whole cluster and just keep the Postgres DBs and the app configuration and releases of the one single user app I have installed but throwing away everything else, most importantly the current scheduled/running jobs, etc?

I obviously tried to run ``flynn-host fix`` a number of times but it either didn't work (collectd not started on that third, failed node) or it didn't fix much.

There is a debug log of one of the two *working* nodes here: http://walski.net/flynn-host-debug206405587.tar.gz

**Comment by josephglanville** [comment]
@walski best way to reset is to take a backup and and create a new cluster with it.

Will take a look through the logs today and see if we can work out what went wrong.

**Comment by walski** [comment]
Hey, I did reset the cluster and that actually worked. I was a bit worried at first that this would also restore the "rogue jobs" etc. But it seemed to have worked. At least the cluster operates again, I can push new releases and none of the nodes is running an excessive amount of jobs anymore. :+1:

The only thing that worries me a bit is that pushing new releases takes a really long time. I am not playing around with Flynn for too long so I cannot say if that's normal behavior for my cluster but a new release through git push takes longer than 5 minutes atm. While most of the time is spent in the latest stages of it when it says, right around "Slug compiled" and "Creating release" etc. The normal "Rails deployment process" with the asset pipeline, gem bundling etc seems to be "at normal speed".

Thanks for your help @josephglanville.

**Comment by josephglanville** [comment]
The final stages of the `git push` basically involve uploading the slug into the blobstore then performing the actual deployment by replacing the running processes with ones based on the new slug.

You can check how long the actual deployment portion takes by running `flynn deployment` just as `git push` completes, the time created vs completed is the time taken.

**Comment by walski** [comment]
Well that can't be it then:

``98b5f508-9eef-446f-be8c-6538a5e0756b  complete  About a minute ago  17 seconds ago``

The whole process takes a lot longer. I'll do some better time keeping with the next deployment.

**Comment by walski** [comment]
Here is a little more detailed timing information on a recent push:

```
$ # Start
$ date
Sun Dec 11 13:53:23 EST 2016

$ # Default process types for Multipack -> rake, console, web, worker
$ date
Sun Dec 11 13:54:57 EST 2016

$ # Compiled slug size is 65.69 MiB
$ date
Sun Dec 11 13:55:46 EST 2016

$ # Creating release...
$ date
Sun Dec 11 13:58:01 EST 2016

$ # Application deployed
$ date
Sun Dec 11 13:59:42 EST 2016
```

So the part that really takes the longest is between ``Compiled slug size …`` and ``Creating release...`` with a little over 2 minutes.

**Comment by josephglanville** [comment]
That would imply that the time is spent uploading the cache directory to the blobstore. Which can either be due to slow network/disk I/O or insufficient CPU to perform the compression. You could try running iostat/iotop/bwm-ng etc to try determine if there is resource bottleneck.

**Comment by josephglanville** [comment]
It could also be due to slow postgres performance if you are using the default blobstore. This can be even more apparent when using a multi-node cluster as the writes are amplified even further.

**Comment by titanous** [comment]
It's worth noting that external blobstore backends tend to have better performance: https://flynn.io/docs/production#blobstore-backend
