### ISSUE TITLE
migrate-domain timed out

### ISSUE THREAD

**Issue by lezardo76** [flynn/flynn#3759]
Hello,
A new flynn tester here.
I managed to install flynn on three hosts in our test vmware infrastructure.
I wanted to change the dns to something else, here is the command I ran:
>flynn cluster migrate-domain paas_test.my_company.org

Migrate cluster domain from "6lmy.flynnhub.com" to "paas_test.my_company.org"? (yes/no): yes
Migrating cluster domain (this can take up to 2m0s)...
timed out waiting for job events: map[scheduler:map[up:3]]
timed out waiting for job events: map[scheduler:map[up:3]]
timed out waiting for domain migration to complete

Before running this command, we have registered paas_test.my_company.org in our internal DNS (pointing to the three host IP addresses).

Could you guide us on this? As I'm new, what's the procedure to give you the right logs?

PS: If it succeed, will it remove the 6lmy.flynnhub.com entry in your DNS?

Tks!

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug-info` on the server.

**Comment by lezardo76** [comment]
sorry, I'm not able to submit any logs. the command always freeze at:
INFO[12-19|11:12:46] getting job logs 
even if I wait for hours.

The list command shows well my three hosts.
The fix command blocks as well. I think I have to reinstall everything.

**Comment by titanous** [comment]
You could also manually collect the logs from `/var/log/flynn` and send a tarball to logs@flynn.io

**Comment by titanous** [comment]
Closing due to lack of information.
