### ISSUE TITLE
Custom Domain for Flynn Dashboard

### ISSUE THREAD

**Issue by n0daft** [flynn/flynn#3761]
We have a flynn cluster on premise and configured the DNS according to the flynn docs:

> demo.localflynn.com.    A      192.168.84.42
demo.localflynn.com.    A      192.168.84.43
demo.localflynn.com.    A      192.168.84.44
*.demo.localflynn.com.  CNAME  demo.localflynn.com.

Custom routes like *app.demo.localflynn.com* configured via the flynn dashboard work perfectly. However, we cannot get a custom route for the dashboard to work (dashboard.demo.localflynn.com). Calling the URL leads to a `Service Unavailable. Sorry for the inconvenience. Please try again in a few minutes.` message. The browser console logs: 

```
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

Refused to connect to http://dashboard.xxxx.flynnhub.com/config because it does not appear in the connect-src directive of the Content Security Policy
```

Another Flynn system application like *status* however works with the custom route.
What am I missing?

Flynn version: v20161017.1

**Comment by jvatic** [comment]
What is the `URL` env set to on the dashboard? (`flynn -a dashboard env get URL`).

**Comment by n0daft** [comment]
@jvatic the URL env is `https://dashboard.xxxx.flynnhub.com`

**Comment by jvatic** [comment]
Changing it to `https://dashboard.demo.localflynn.com` (`flynn -a dashboard env set URL=https://dashboard.demo.localflynn.com`) should resolve the issue.

**Comment by n0daft** [comment]
@jvatic your solution resolved the issue. Thank you very much for your quick response.

**Comment by SalvoLunar** [comment]
Hi @jvatic 

I'm having a similar issue but the URL seems correct.
This is the error I'm getting:
![error](https://user-images.githubusercontent.com/31966108/41649531-b4f87bc8-7473-11e8-9c16-8317a41f6291.png)

is there any other possible cause for this? Could it be related to the certificate?
