### ISSUE TITLE
[FR] Implement read-only and tmpfs

### ISSUE THREAD

**Issue by hazcod** [flynn/flynn#3765]
Current status: docker image is mounted read-only & a temporary ext2 filesystem is mounted on top of this. Max size of this fs can be set with `temp_disk`.

Feature: Allow the user to create a read-only filesystem (theoretically possible with `temp_disk=0`) EXCLUDING a specific location, such as /tmp/.

This would offer a security advantage where no binaries can be changed at runtime, but still a possibility to drop temporary files in let's say /tmp/.

(Docker manages this with the `read-only: true` and `tmpfs` flags.)

**Comment by lmars** [comment]
FYI having a read-only root filesystem in the container is **not** currently possible by setting `temp_disk=0` (I proposed that could be the way to enable it, but that will currently lead to a crash creating a zero sized ext2 filesystem).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
