### ISSUE TITLE
router: Investigate defensive approaches to reduce impact of byzantine discoverd failure modes

### ISSUE THREAD

**Issue by josephglanville** [flynn/flynn#3766]
As of right now most Flynn control plane components can fail without adversely impacting production traffic to guest applications.
The main exceptions are the router and tangentially discoverd.

The router makes use of discoverd to track which backends are up and available to serve traffic.
It uses discoverd down events to remove backends from the routable set and maintains an internal cache of the discoverd state from it's frame of reference.
Complete discoverd outages are handled gracefully by the router by serving from the cache.

However there are some byzantine failure modes of discoverd that can happen under extranous circumstances. Namely it's possible for discoverd to mark all services as down even though they are functioning fine. This causes the router to remove all available backends from the set and return 503 in the case of HTTP/HTTPS or simply close TCP connections in L3 mode.

To prevent this we should come up with a defensive paradigm for the router to implement regarding sane state changes from discoverd.

One possible approach is to attempt to fail more gracefully, by maintaining a set of last seen routable backends and falling back in the case that all have been removed from the active set by discoverd. This should not be harmful in the case where backends truly are down but allows us to fail less hard when discoverd has an incorrect view of the world.

**Comment by IsNull** [comment]
[Netflix Eureka](https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Peer-to-Peer-Communication) is a service discovery server which handles your described problem of a full network outage or partial network segmentation with a threshold system. 

I.e. when there are N registered services, the system expects at lest a certain threshold of incoming "alive" messages. If this is not happening, it is assumed that at least partially the network is down and the currently registered services are kept in cache.

> When the Eureka server comes up, it tries to get all of the instance registry information from a neighboring node. If there is a problem getting the information from a node, the server tries all of the peers before it gives up. If the server is able to successfully get all of the instances, it sets the renewal threshold that it should be receiving based on that information. If any time, the renewals falls below the percent configured for that value (below 85% within 15 mins), the server stops expiring instances to protect the current instance registry information.

>In Netflix, the above safeguard is called as self-preservation mode and is primarily used as a protection in scenarios where there is a network partition between a group of clients and the Eureka Server. In these scenarios, the server tries to protect the information it already has. There may be scenarios in case of a mass outage that this may cause the clients to get the instances that do not exist anymore. The clients must make sure they are resilient to eureka server returning an instance that is non-existent or un-responsive. The best protection in these scenarios is to timeout quickly and try other servers.


Maybe that helps.

**Comment by josephglanville** [comment]
Interesting, I was aware of Eureka but haven't used to before. I will definitely read up on their approaches to this sort of problem.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
