### ISSUE TITLE
how to re-run bootstrap to fix unhealthy mongodb?

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#3772]
I have issues with mongodb, I have two mongo databases. I can't remove them from Flynn. can't create or restore a db either. basically, mongodb is broken.

I just want to get rid of mongodb and recreate the whole mongo app fresh. how can I do that?

**Comment by hadifarnoud** [comment]
debug logs: https://dl.dropboxusercontent.com/u/3116541/flynn-host-debug.tar.gz

**Comment by jvatic** [comment]
See [here](https://github.com/flynn/flynn/issues/3298#issuecomment-240152480) for removing mongodb and [here](https://github.com/flynn/flynn/issues/3198#issuecomment-240152451) for adding it again.

**Comment by hadifarnoud** [comment]
I can't delete @jvatic 
```
ERROR:  update or delete on table "providers" violates foreign key constraint "resources_provider_id_fkey" on table "resources"
DETAIL:  Key (provider_id)=(305d0406-98ae-4291-a7d9-9490e3fa2d12) is still referenced from table "resources".
```

**Comment by jvatic** [comment]
You need to first delete any existing mongodb databases.

**Comment by hadifarnoud** [comment]
I can't delete them @jvatic. that's part of the issue

**Comment by jvatic** [comment]
You can delete the controller record of mongodb databases with:

```
$ flynn -a controller pg psql
=> DELETE FROM resources where provider_id = (SELECT provider_id from providers where name = 'mongodb');
```

Then you should be able to delete the provider.

**Comment by hadifarnoud** [comment]
still can't :(
```
ERROR:  update or delete on table "resources" violates foreign key constraint "app_resources_resource_id_fkey" on table "app_resources"
DETAIL:  Key (resource_id)=(c0097d9d-da5c-431a-a846-e087160cadf0) is still referenced from table "app_resources".
```

**Comment by jvatic** [comment]
Ah right, you'll first need to find and delete the appropriate `app_resources` records.

**Comment by hadifarnoud** [comment]
Can you tell me how? Don't want to f* up this node

**Comment by jvatic** [comment]
This should do what you want:

```
$ flynn -a controller pg psql
=> DELETE FROM app_resources WHERE resource_id in (SELECT resource_id FROM resources WHERE provider_id = (SELECT provider_id FROM providers WHERE name = 'mongodb'));
```

**Comment by hadifarnoud** [comment]
unable to add mongo
```
root@flynn1:~# CONTROLLER_KEY=$(flynn -a controller env get AUTH_KEY) flynn-host bootstrap --steps controller-key,mongodb-password,mongodb,add-mongodb-provider
06:39:40.470663 main.go:173: no clusters configured
06:39:40.575241 check online-hosts
06:39:40.581469 gen-random controller-key
06:39:40.582057 gen-random controller-key ****
06:39:40.582074 gen-random mongodb-password
06:39:40.582105 gen-random mongodb-password ****
06:39:40.582121 deploy-app mongodb
06:39:40.586921 deploy-app mongodb error: POST http://100.100.6.5:80/apps: httpclient: raw req: unexpected status 401
```

**Comment by lmars** [comment]
It looks like you don't have the CLI configured:

```
06:39:40.470663 main.go:173: no clusters configured
```

Just grab the controller key locally with `flynn -a controller env get AUTH_KEY` then run the following on the server:

```
$ export CONTROLLER_KEY="$CONTROLLER_KEY"
$ flynn-host bootstrap --steps controller-key,mongodb-password,mongodb,add-mongodb-provider
```

**Comment by hadifarnoud** [comment]
I still get 401 @lmars. I set controller key by doing `export CONTROLLER_KEY="3d0810d******e18b4e168"`

then `flynn-host bootstrap --steps CONTROLLER_KEY,mongodb-password,mongodb,add-mongodb-provider`

it does not say `no cluster configured` anymore but still get 401:
```
root@flynn1:~# flynn-host bootstrap --steps CONTROLLER_KEY,mongodb-password,mongodb,add-mongodb-provider
11:58:42.468881 check online-hosts
11:58:42.474673 gen-random mongodb-password
11:58:42.475436 gen-random mongodb-password ff708******39a89065
11:58:42.475458 deploy-app mongodb
11:58:42.480327 deploy-app mongodb error: POST http://100.100.6.5:80/apps: httpclient: raw req: unexpected status 401
````

**Comment by hadifarnoud** [comment]
I now get this @lmars 
```
12:03:56.915039 check online-hosts
12:03:56.919380 gen-random controller-key
12:03:56.923725 gen-random controller-key ****
12:03:56.923979 gen-random mongodb-password
12:03:56.924197 gen-random mongodb-password ****
12:03:56.924319 deploy-app mongodb
12:03:56.941709 deploy-app mongodb error: object_exists: application "mongodb" already exists
```

I have no provider in gui

**Comment by hadifarnoud** [comment]
my bad, for some reason mongodb was not deleted. mongo is added back in providers but I still have issue adding it to my apps. `flynn -a team resource add mongodb` takes forever and at the end throws `POST https://controller.eg55.flynnhub.com/providers/mongodb/resources: httpclient: raw req: unexpected status 503` error.

mongodb is still unhealthy in /status page.

**Comment by lmars** [comment]
@hadifarnoud please run `sudo flynn-host collect-debug-info` and send us the logs.

If your other apps are in a functioning state, it may be worth exporting them with `flynn -a APP export --file APP.tar`, booting a fresh cluster then importing your apps with `flynn import APP.tar`.

**Comment by hadifarnoud** [comment]
@lmars we have too many apps to export them one by one. emailed the logs just now
