### ISSUE TITLE
Ghost containers

### ISSUE THREAD

**Issue by pfeodrippe** [flynn/flynn#3776]
I have 0 processes running in my dashboard, but ghost containers are still running... I've tried to kill them and didn't work, they always come back.

```
$ flynn ps
ID                                             TYPE    STATE  CREATED         RELEASE
ip100736-11afe8b7-0c61-4db7-9e30-666e09701e95  web     up     12 seconds ago  b62c987b-38dd-4669-abd1-975f3ff297f2
ip100736-15d8ee92-4b5e-4c29-998a-24a2f0d8c95f  clock   up     8 seconds ago   b62c987b-38dd-4669-abd1-975f3ff297f2
ip100736-e229ee50-2ae7-415b-ab90-238a6ef04d0d  worker  up     2 seconds ago   b62c987b-38dd-4669-abd1-975f3ff297f2
```

**Comment by titanous** [comment]
What does `flynn scale -a` say?

**Comment by pfeodrippe** [comment]
```
20b883c7-fb13-456a-9f68-31af106f8d24 (current)
b62c987b-38dd-4669-abd1-975f3ff297f2
clock=1 web=1 worker=1
```

@titanous thanks! Maybe better to use the cli only?

**Comment by titanous** [comment]
You can scale the old release down with `flynn scale -r b62c987b-38dd-4669-abd1-975f3ff297f2 clock=0 web=0 worker=0`

**Comment by pfeodrippe** [comment]
@titanous awesome,man! So theses ids are the deployed releases and because of some inconsistency, the dashboard forgot the old release? The normal is to appear only one id when I do ```flynn scale -a```, right? 

Well, it's not a real ghost container, it's only a ghost for the dashboard.
Thanks, man!

**Comment by lmars** [comment]
@pfeodrippe can you run `sudo flynn-host collect-debug-info` on a host in your cluster and send the resulting gist to logs@flynn.io? I am interested to know why the old release was still scaled up.

**Comment by pfeodrippe** [comment]
@lmars not working (sorry for the delay in response)
```
sudo: unable to resolve host ip-10-0-7-36
INFO[12-20|13:24:14] uploading logs and debug information to a private, anonymous gist
INFO[12-20|13:24:14] this may take a while depending on the size of your logs
INFO[12-20|13:24:14] getting flynn-host logs
INFO[12-20|13:24:14] getting sirenia metadata
INFO[12-20|13:24:14] getting scheduler state
INFO[12-20|13:24:14] getting job logs
INFO[12-20|13:24:32] getting system information
INFO[12-20|13:24:33] creating anonymous gist
150.89 MB / 150.89 MB [=====================================] 100.00 % 75.36 MB/s 0sEROR[12-20|13:24:48] unexpected HTTP status: 405
150.89 MB / 150.89 MB [=====================================] 100.00 % 9.78 MB/s 15s
13:24:48.942054 host.go:157: unexpected HTTP status: 405
```

**Comment by lmars** [comment]
@pfeodrippe re-run it with the `--tarball` flag and send the resulting tarball to logs@flynn.io.

**Comment by pfeodrippe** [comment]
@lmars sent the tar file. thanks!

**Comment by lmars** [comment]
@pfeodrippe I have looked at the logs but unfortunately they don't go back far enough to diagnose the underlying issue here (Flynn only retains 200MB of logs per app, and that release seems to be a few weeks old).

I am going to close this but if you notice this behaviour again please collect the debug info and send it to us.
