### ISSUE TITLE
"vagrant up" failed: Authentication failure. Retrying...

### ISSUE THREAD

**Issue by happy-tanuki** [flynn/flynn#3785]
Following the instructions here: https://flynn.io/docs/installation/vagrant, `make init` or `vagrant up` was failed using Box 'flynn-base' (v20161218.1).

    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2200
        default: SSH username: vagrant
        default: SSH auth method: private key
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...

I needed to add a `vagrant` user with no password.

    $ vagrant ssh
    vagrant@flynn:~$ mkdir ~/.ssh
    vagrant@flynn:~$ curl -Lo ~/.ssh/authorized_keys https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub
    vagrant@flynn:~$ sudo sh -c "echo 'vagrant ALL=NOPASSWD:ALL' > /etc/sudoers.d/vagrant"

In addition, `make up` failed with the error. Is the correct command `systemctl start flynn-host.service` in order to `start flynn-host`?

    CLUSTER_DOMAIN="demo.localflynn.com" SSH_AUTH_SOCK="" FLAG_BOOTSTRAP=false vagrant ssh -c 'sudo start flynn-host || echo flynn-host already running or unable to start'
    sudo: start: command not found

My environment is:
* Virtualbox (5.1.12)
* Vagrant (1.9.1)
* Mac OS X 10.12.1

**Comment by titanous** [comment]
We just re-did the Vagrant box, so there are probably some bugs in the handling of it. @lmars will look into it when he's back from holidays.
