### ISSUE TITLE
Specify cluster in `flynn cluster backup`

### ISSUE THREAD

**Issue by kvitajakub** [flynn/flynn#3786]
When dumping cluster to tar file from command line it looks like default cluster is saved.
Is it possible to add option to pick a cluster to save?
From help:
```
flynn cluster backup [--file <file>]
```

**Comment by lmars** [comment]
There is a global `-c` flag which specifies the cluster, or you can set the `FLYNN_CLUSTER` environment variable:

```
flynn -c "my-cluster" cluster backup
```

or

```
export FLYNN_CLUSTER="my-cluster"
flynn cluster backup
```
