### ISSUE TITLE
SSL cert route issues while restoring cluster from backup

### ISSUE THREAD

**Issue by kvitajakub** [flynn/flynn#3787]
I restored cluster through installer on AWS. I had couple custom https routes which were created, but  when I accessed them they used SSL cert from the cluster default route. This doesn't make any sense as they were using completely different domains and I added the certificate and key manually through `flynn route`. I assume this should not be happening, or am I missing something?

**Comment by lmars** [comment]
@kvitajakub do the routes show up when you run `flynn route` on the new cluster?

**Comment by kvitajakub** [comment]
@lmars yes they do.
I was testing them with https://www.ssllabs.com/ssltest/ and this reported original certificate.
I already updated the routes with proper cert, as I needed to use them.

**Comment by kvitajakub** [comment]
I tried to do it again and now everything works fine. I have no idea what happened yesterday. Sorry about this.
