### ISSUE TITLE
dashboard: failing to provision a mariadb on a new app

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3790]
Hi,
I just tried to provision a mariadb via the dashboard to a freshly created app ("flynn create foo") without release.
It creates the db, but gets a 500 on a POST against https://controller.flynn....com/releases
I assume this is the release where the environment variables are created.

**Comment by titanous** [comment]
Yeah, your assumption is correct.

This is probably a dashboard bug, we have changed some things around creating releases recently. I suspect that the `app_id` field is missing from the release. /cc @jvatic

**Comment by lmars** [comment]
@philiplb can you post the corresponding error from the controller log around that time?

```
$ flynn -a controller log -t web
```

**Comment by jvatic** [comment]
Lack of an `app_id` in the dashboard's request to create the release was indeed the issue. As a workaround you can create an empty release with `flynn env set`, then the dashboard should work as expected.

**Comment by philiplb** [comment]
Thx. :-)
