### ISSUE TITLE
Per app log-sink

### ISSUE THREAD

**Issue by kvitajakub** [flynn/flynn#3791]
Hello,

the new log-sink feature works very nicely for me. We needed that a long time now. Thank you!
However, log is flooded with the stuff from dashboard and controller. Is it possible to configure log sinks per app?

**Comment by titanous** [comment]
Not yet, though this is the logical evolution of this feature. We may be able to add a flag filters out logs for system apps from the cluster-wide stream as well.

**Comment by kvitajakub** [comment]
Thank you. That would be nice.

For the future readers:
In the meantime we are using logs in `/var/log/flynn` and configure remote syslog directly on the nodes. Quite easy to configure with ansible.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
