### ISSUE TITLE
sirenia: Improve resilience when discoverd services flap

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3792]
Under certain circumstances (e.g. high load, network issues etc.), discoverd can start marking services as down even though the actual jobs are still running, and this can result in db appliances getting into odd states unnecessarily.

When a service is marked as down, we should consider performing some internal checks (e.g. get the status via the HTTP API) before removing it from the state machine.

We should also make discoverd more reliable, but this seems like a good fail-safe to prevent cluster meltdown.

Relates to #3766.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
