### ISSUE TITLE
Coreutils unknown filesystem type error

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#3795]
When getting the logs of a rails app running Phusion Passenger from the Flynn CLI tool we are getting this error: `tail: unrecognized file system type 0x794c7630 for ‘/app/log/passenger.8080.log’. please report this to bug-coreutils@gnu.org. reverting to polling`.

Talking to @lmars it might be the buildpack not having a new coreutils that recognises the container filesystems.

**Comment by lmars** [comment]
@bbaptist the Flynn cedarish stack uses the same version of `coreutils` as the Heroku Cedar 14 stack (i.e. `8.21-1​ubuntu5.4`).

You can get an updated version with OverlayFS support by using the [Apt buildpack](https://github.com/heroku/heroku-buildpack-apt) with the following in an `Aptfile`:

```
http://archive.ubuntu.com/ubuntu/pool/main/c/coreutils/coreutils_8.25-2ubuntu2_amd64.deb
```

Heroku currently have a `heroku-16` stack in alpha which will have this updated version, we will likely add a similar stack to Flynn once it comes out of alpha.
