### ISSUE TITLE
Problem pushing a Ruby on Rails app

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3799]
Hi,
I just tried to push a quite old Ruby on Rails app to Flynn but got this error:
https://gist.github.com/philiplb/cd82999bf7066d972ad5982ff6e6c411

I executed said "bundle exec rake -P" locally and it worked just fine.

Do you have any maybe?

**Comment by josephglanville** [comment]
If you are no longer using Capistrano I would suggest removing it and any plugins/extensions for it from the Gemfile. Failing that there is likely an issue with the load/require order of your Capistrano gems, namely `rvm-capistrano`.

**Comment by philiplb** [comment]
That did the trick, thank you very much. :)
