### ISSUE TITLE
host: Hung containers prevent scheduling jobs due to ratelimiter

### ISSUE THREAD

**Issue by kevinob11** [flynn/flynn#3800]
When deploying I get the error below. Usually it resolves itself within a few minutes. I don't have any other builds running concurrently.
`remote: ERROR: Build failed: ratelimited: maximum concurrent AddJob calls running, try again later`

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug-info` on each host and post the logs here.

**Comment by kevinob11** [comment]
Ok, available here:

https://drive.google.com/drive/folders/0B418afhyEfo4MXp5T2lQaHhIV3c?zx=gv84ppltfr9e

**Comment by lmars** [comment]
One of your hosts (`paase`) has four containers which are stuck in the startup phase:

```
root      2470  0.0  0.0  18944   700 ?        D     2016   0:00  \_ /usr/local/bin/flynn-host libcontainer-init
root      2718  0.0  0.0  18944   672 ?        D     2016   0:00  \_ /usr/local/bin/flynn-host libcontainer-init
root      2972  0.0  0.0  18944   684 ?        D     2016   0:00  \_ /usr/local/bin/flynn-host libcontainer-init
root      6722  0.0  0.0  18944   684 ?        D     2016   0:00  \_ /usr/local/bin/flynn-host libcontainer-init
```

`flynn-host` rate limits requests when it is starting four jobs concurrently (which are expected to start pretty quickly), so these stuck containers are causing the error you are seeing when scheduling jobs on this particular host.

I suspect this is https://github.com/docker/docker/issues/5618, could you check `/var/log/syslog*` (some may be gzipped) for errors like:

```
unregister_netdevice: waiting for lo to become free. Usage count = N
```

**Comment by kevinob11** [comment]
Yep, a near constant stream of:
`Jan  7 10:14:57 paas-e kernel: [3676291.640043] unregister_netdevice: waiting for eth0 to become free. Usage count = 1`

**Comment by lmars** [comment]
@kevinob11 although I have seen this in the wild, I have been unable to reproduce this and given it is a kernel hang, the processes can't be killed so the only way to get rid of them is to reboot the node.

We should probably release the rate limiter in this case (e.g. when a job has failed to start after N seconds), although we will leak these processes (possibly at a high rate).

**Comment by kevinob11** [comment]
Makes sense, thanks

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
