### ISSUE TITLE
Cluster setup from web installer may fail related to netfilter-persistent

### ISSUE THREAD

**Issue by ncantelmo** [flynn/flynn#3802]
Attempting to set up a 3x 2 GB / 40 GB cluster on DigitalOcean via the web installer failed multiple times before successfully completing on the third of fourth try.  I don't have complete logs from the failed startup, so I'll do the best I can to describe what I remember seeing last night.

First off, I know that the logs included the lines:
'netfilter-persistent: command not found' and
'run-parts: executing /usr/share/netfilter-persistent/plugins.d/15-ip4tables save'

The failures appeared to hang in different places, and I don't believe any of them stopped immediately upon hitting the initial issue with netfilter-persistent. There would be a message about a missing dependency or service setup failure around netfilter-persistent, and then the installer would print some lines related to setting it up (looked like a delayed or retry attempt), and finally the install would get stuck. I waited about 5-10 minutes each time before killing the install and starting over.

There may have been some interplay between previously failed (but not fully cleaned up clusters) and the new deployment attempts, but it seems pretty unlikely. The only reason I'm mentioning it is because I made sure to fully clean up the previous failed clusters before the last attempt finally completed successfully.

**Comment by lmars** [comment]
@ncantelmo I have bootstrapped multiple DigitalOcean clusters and cannot reproduce what you describe.

If you see this again please post the full output from the installer.

**Comment by ncantelmo** [comment]
I was able to reproduce the issue with the following steps:

1. Running `flynn install`
2. Install a 3-node cluster on DO (successfully)
3. Killing the `flynn install` process via Ctrl-C
4. Running `flynn cluster remove <cluster-name>`
5. Running `flynn install` (removed cluster still listed in installer)
6. Without cleaning up the removed cluster, installing a new 3-node cluster on DO

As requested, a log from the installer is attached.
[flynn-install-failure-20160113.txt](https://github.com/flynn/flynn/files/705740/flynn-install-failure-20160113.txt)
