### ISSUE TITLE
Add streaming option to `flynn-host collect-debug-info`

### ISSUE THREAD

**Issue by simon0191** [flynn/flynn#3810]
I tried to collect debug info for issue #3809 but the host ran out of memory. What do you think about adding a streaming option to `flynn-host collect-debug-info` so the data can be streamed for example to S3 and avoid store all the debug info in memory before posting it?

**Comment by lmars** [comment]
See #3284 for plans on improving debug log collection (I have written a custom debug log service already, we just need to deploy it).

**Comment by imjorge** [comment]
@lmars is the custom debug log service you wrote open source? And, if so,
where can I take a look?

**Comment by lmars** [comment]
@imjorge it is currently in a private repository, but we will make it public once the initial review is done and I'll ping you in the PR.

**Comment by imjorge** [comment]
@lmars great! Love your work! Always a good oportunity to learn.
