### ISSUE TITLE
Problems with Static Buildpack

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3815]
Hi,
I created this little repo: https://github.com/philiplb/swagger-ui-on-flynn
It is using the static buildpack via a .buildpacks file: https://github.com/pearkes/heroku-buildpack-static

But on git push flynn master, I get this error?

> Counting objects: 66, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (65/65), done.
> Writing objects: 100% (66/66), 1004.63 KiB | 0 bytes/s, done.
> Total 66 (delta 4), reused 0 (delta 0)
> -----> Building swaggerui...
> -----> Multipack app detected
>        =====> Downloading Buildpack: https://github.com/pearkes/heroku-buildpack-static
>        =====> Detected Framework: Static
> -----> Bundling Apache v2.2.19
> remote:
> remote: gzip: stdin: not in gzip format
> remote: tar: Child returned status 1
> remote: tar: Error is not recoverable: exiting now
> remote: ERROR: Build failed: exec: job exited with status 2
> To https://git.flynn.....com/swaggerui.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.flynn.....com/swaggerui.git'

Do you have any clue, what's wrong here?

**Comment by philiplb** [comment]
I just used the PHP buildpack now by adding an composer.json containing "{}" and removing the .buildpacks. Feels like a bit of resource waste as the PHP interpreter gets installed and not used, but that doesn't matter much.

**Comment by titanous** [comment]
Try using the built-in `Staticfile` buildpack by creating an empty file in the root of the repo called `Staticfile`.
