### ISSUE TITLE
One node of a three node cluster is slowly running out of disk space

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3820]
Hi,
one of my nodes is slowly running out of disk space due to an ever growing /var/lib/flynn/volumes. A "flynn-host volume gc" deleted some volumes, but that didn't bring much:
- Before: 74805658	/var/lib/flynn/volumes/zfs
- After: 72157416	/var/lib/flynn/volumes/zfs

Any clues? Maybe not anymore needed slugbuilder caches are the cause?

**Comment by philiplb** [comment]
So this morning I had a meltdown (the first since march 2016 :)) and had to restore from backup:

- Two of three nodes went down due to maintencance of the VM host
- They rebooted and came back
- The cluster mostly came back except the MariaDB
- One of the nodes ran out of disk space (it was close anyway) and I saw no way to clean the disk space, see above

So a tool to remove unwanted zfs volumes would be great like "older than x days and currently not in use".

Here is the disk space of the new cluster since a few hours:

![screen shot 2017-01-12 at 11 02 24](https://cloud.githubusercontent.com/assets/1672238/21885859/c68f5d18-d8b9-11e6-9ac3-d881ba119970.png)
![screen shot 2017-01-12 at 11 02 38](https://cloud.githubusercontent.com/assets/1672238/21885864/c9e89704-d8b9-11e6-9465-c084487d8ec4.png)

Note the available disk space going slowly down. No deployment happened during this time.

Just in case, the debug logs: https://philiplb.de/misc/flynn-host-debug-2017-01-12-11-35.tar.gz

**Comment by lmars** [comment]
@philiplb if you are using the sparse file for the ZFS pool (which is the default) then it is configured to grow to 70% of the root disk, it will not shrink when removing volumes (you can check the space available within the zpool with `sudo zpool list`).

I strongly suggest using a dedicated disk for the zpool (see [here](https://flynn.io/docs/production#storage)).

**Comment by philiplb** [comment]
@lmars 
I do actually. How can I check the size of the sparse file?

**Comment by lmars** [comment]
@philiplb you can check the size of the sparse file with `ls -s`:

```
$ ls -lhs /var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev
11G -rw------- 1 root root 207G Jan 12 14:05 /var/lib/flynn/volumes/zfs/vdev/flynn-default-zpool.vdev
```

Here, `207G` is the configured size (i.e. 70% of my root disk which is ~300G), and `11G` is the size of the file on the filesystem.

Because ZFS is using the sparse file like a real disk, it will just keep allocating blocks from the file (i.e. consuming real space on your root disk), but it won't clean those blocks when you delete a volume because that is not usually necessary when using a block device (i.e. the blocks can be overwritten in the future, but they will not be zeroed out).

So if you are using the sparse file, you should expect it to use 70% of your root disk regardless of how big the data in the zpool is, and if that is an issue you should switch to using a dedicated disk for the zpool as mentioned.

**Comment by philiplb** [comment]
@lmars Yeah, I see. Thank you for the detailed answer. Now I can investigate, where the 30GB left of the 100GB disk went.

**Comment by lmars** [comment]
@philiplb 

> The mount folder contains mounts "into" the sparse file and so it doesn't consume more disk space?

Yes `/var/lib/flynn/volumes/zfs/mnt` contains directories which are mounted from ZFS zvols, so they all exist on the sparse file.

You may find this command useful to list the 50 top directories by space used on the root disk:

```
$ sudo du --separate-dirs --one-file-system / | sort -n | tail -50
```

**Comment by philiplb** [comment]
@lmars Thank you, that's a handy command.
The biggest folder beside the sparse file is indeed /var/lib/docker/aufs/diff with 26G. Is this mounted from within the sparse file as well or is it separate?
If separate, can I limit its size somehow? Aka what is it actually? I don't use the docker capabilities of Flynn (yet), so it confuses me a bit here.

**Comment by lmars** [comment]
@philiplb did you previously have a old version of Flynn on this host? We switched away from AUFS in version `v20161114.0`, so if you are on a more recent version you can safely delete that directory:

```
$ sudo rm -rf /var/lib/docker/aufs
```

**Comment by philiplb** [comment]
@lmars This cluster went through every stable update since 20160327 indeed.
Thank you very much for the support, now the cluster is safe again IMHO, no matter if the sparse file grows to its maximum. :)
