### ISSUE TITLE
AWS region ap-south-1(Mumbai) not available

### ISSUE THREAD

**Issue by thecodinghouse** [flynn/flynn#3827]
While creating the cluster using AWS option the region ap-south-1(Mumbai) is not listed in available options

**Comment by lmars** [comment]
The region needs to be added to [this list](https://github.com/flynn/flynn/blob/master/util/packer/ubuntu.json#L100-L110).

**Comment by vivekdurai** [comment]
Added via [this pull request](https://github.com/flynn/flynn/pull/3959).
