### ISSUE TITLE
Password protected maven repository doesn't work

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#383]
From @temujin9 on IRC:

> https://devcenter.heroku.com/articles/using-a-custom-maven-settings-xml#using-password-protected-repositories doesn't seem to work on Flynn: the password doesn't appear to be picked up as advertised, despite being available in the running env context.

**Comment by titanous** [comment]
@temujin9 Is this still an issue?

**Comment by temujin9** [comment]
I have a workaround in place, so I actually don't really know.

**Comment by titanous** [comment]
Closing due to lack of data, if anyone encounters this they can open a new issue.
