### ISSUE TITLE
appliance/mongodb: Crashes with 'Invariant failure _role != Role::candidate'

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3830]
See the end of the following gist for an example:

https://gist.githubusercontent.com/anonymous/67bd7575a4e9fe0dc7b5a4c5c856b9d2/raw/ab58cdbf91c07df0bb6baada12762ad1ed9ecd60/mongodb-mongodb-ea7523d5ad06465b9f8646758fa09ff0-62bae6d4-671a-4d73-b5f8-2bb26a9d6ebe.log

From debug info:

https://gist.github.com/67bd7575a4e9fe0dc7b5a4c5c856b9d2

CI failure:

`BackupSuite.Test_v20160814_0_nodejs_mysql` in https://ci.flynn.io/builds/20170112144210-7724b6f7

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
