### ISSUE TITLE
Cant connect to MySQL database with flynn mysql console

### ISSUE THREAD

**Issue by dabeeeenster** [flynn/flynn#3835]
I created a MySQL DB using the web console, and associated it with my app. The app can connect fine, but when I run flynn mysql console I can't connect:

```
~/projects/carpricetracker [master] » flynn mysql console                                                                                                                                    [15:43:49]
No mysql database found. Provision one with `flynn resource add mysql`
~/projects/carpricetracker [master] » flynn resource                                                                                                                                         [15:43:50]
ID                                    Provider ID                           Provider Name
19de50bc-6590-4125-99b9-c67888e7ce70  6903be0d-c936-4c01-a858-74bc3db749c6  mysql
```

**Comment by josephglanville** [comment]
Can you check that `flynn env` shows that `FLYNN_MYSQL` has been set correctly? It's possible the `MYSQL_HOST` and other variables are correct but `FLYNN_MYSQL` has been overwritten.
This would allow your app to continue to connect but it will cause the `flynn mysql` CLI to not function correctly.

**Comment by dabeeeenster** [comment]
Ah that will be it - it just shows a couple of app vars and no MySQL ones. I assumed that they would be synchronised with my client but thinking about that now it might be a stretch. Is there a way to do this other than manually?

**Comment by josephglanville** [comment]
You should be able to inspect older releases to find where they were overwritten and restore them.
Listing old releases can be done with `flynn release`, you can then inspect one with `flynn release show <ID>`.

**Comment by dabeeeenster** [comment]
Understood - thanks. It would be nice for vars generated on the server to be reflected on the client?

**Comment by josephglanville** [comment]
They should be, when `flynn resource add` was run they should have been visible to `flynn env`.

Have you found the missing variables in an old release yet?

**Comment by dabeeeenster** [comment]
So I created the DB thru the dashboard and not on the client..

**Comment by fanminjian** [comment]
@josephglanville How can I reset mariadb? I am not able to start mariadb process.

**Comment by josephglanville** [comment]
@fanminjian create a new issue and post the debug information captured with `flynn-host collect-debug-info`

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
