### ISSUE TITLE
Staticfile buildpack doesn't build

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3837]
Hi,
I just tried the buildpack https://github.com/cloudfoundry/staticfile-buildpack like this:
- added a .buildpacks into the projects root with the address above
- added an empty Staticfile
- pushed to Flynn

But I got this result? Not sure what to do here.

> Counting objects: 7, done.
> Delta compression using up to 4 threads.
> Compressing objects: 100% (6/6), done.
> Writing objects: 100% (7/7), 1.14 KiB | 0 bytes/s, done.
> Total 7 (delta 2), reused 0 (delta 0)
> -----> Building swaggerui...
> -----> Multipack app detected
>        =====> Downloading Buildpack: https://github.com/cloudfoundry/staticfile-buildpack
>        =====> Detected Framework: staticfile 1.3.16
> remote: /tmp/buildpackLEEDO/bin/compile: line 14: /tmp/buildpackLEEDO/compile-extensions/bin/check_stack_support: No such file or directory
> remote: ERROR: Build failed: exec: job exited with status 1
> To https://git.flynn.....com/swaggerui.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.flynn.....com/swaggerui.git'

**Comment by titanous** [comment]
The multi buildpack (triggered by the `.buildpacks` file) doesn't support git submodules (see #3611), and the lack of a required submodule triggers this issue. You can delete the `.buildpacks` file and see if the correct buildpack kicks in, and if it doesn't, set `BUILDPACK_URL`.

**Comment by philiplb** [comment]
That did it, thank you very much. :)
https://github.com/philiplb/swagger-ui-on-flynn
