### ISSUE TITLE
What's the maximum peers I can have per clusters

### ISSUE THREAD

**Issue by fanminjian** [flynn/flynn#3838]
Do I need to do that after adding one host?

flynn -a discoverd env set DISCOVERD_PEERS= with additional host ip?

**Comment by josephglanville** [comment]
@fanminjian I would suggest reading the docs on adding hosts in the production docs here: https://flynn.io/docs/production#adding-hosts

If you want the new peer to act as a discoverd Raft peer you can achieve that by promoting it once it has been added with `flynn-host promote $PEER_IP`.
However I recommend not exceeding 5 or perhaps 7 Raft peers as increasing the number of peers does increase resilience but it does so at the cost of reducing performance when inter-peer latency is affected.

You should also be aware that you can't use this process to expand a single node cluster to multi-node. If you currently have a single node cluster I would recommend doing a backup and restore to create a multi-node cluster.

**Comment by fanminjian** [comment]
Thanks for prompt reply and sharing the information. 7 nodes would be more than enough for us at moment. Cheers
