### ISSUE TITLE
Can't find container ip addresses

### ISSUE THREAD

**Issue by mrrooijen** [flynn/flynn#3839]
Trying to lookup container ip addresses, but it doesn't appear to find them.

I have an app called `myapp` that's running 3 web processes.

```
$ flynn run nslookup myapp-web.discoverd
Server:		100.100.32.1
Address:	100.100.32.1#53

** server can't find myapp-web.discoverd: NXDOMAIN
```

Thoughts?

**Comment by titanous** [comment]
What is the output of `flynn -a myapp ps`?

**Comment by mrrooijen** [comment]
```
ID                                              TYPE  STATE  CREATED         RELEASE
ip1000186-32283608-ac97-4899-ad55-4de36727b726  web   up     3 hours ago     7b4e60c4-f929-42bd-961d-455ded745079
ip100158-9e717751-078d-4ede-b969-2d0b26776fe5   web   up     13 seconds ago  c0a13fae-f36b-44f7-90aa-7607aa7473ed
ip1003166-00c33335-eaa3-44a8-be14-16c7305f8a31  web   up     13 seconds ago  c0a13fae-f36b-44f7-90aa-7607aa7473ed
ip1000186-d4747042-9e63-4a47-90e6-d43306ec63db  web   up     13 seconds ago  c0a13fae-f36b-44f7-90aa-7607aa7473ed
```

(separate issue btw: for some reason the first entry in this list has been around for quite a while, and I'm not sure why. `flynn scale web=0` removes the last 3, but the first process doesn't get removed.)

**Comment by titanous** [comment]
Please run `sudo flynn-host collect-debug-info` and post the logs here so we can take a look.

**Comment by mrrooijen** [comment]
https://gist.github.com/anonymous/988d4e90801aec5d39de74c6d7069946

Note that the "separate" issue I mentioned is no longer present because I removed the cluster it occurred in. Wasn't sure whether you requested the debug dump due to the separate issue or the main issue.

Regardless, I still cannot `flynn run nslookup myapp-web.discoverd` despite having the following `flynn ps` output:

```
ID                                             TYPE  STATE  CREATED        RELEASE
ip100661-a64a3bb9-b8be-48d1-bad7-f13710d09b66  web   up     8 minutes ago  e99afd36-bc94-44cc-b117-d73025d110e4
ip100661-6ca4fffc-a9ce-4073-9132-9aa4dea1e0e9  web   up     6 minutes ago  e99afd36-bc94-44cc-b117-d73025d110e4
ip100661-5c33df9e-1148-49b8-9cae-322682ea5267  web   up     6 minutes ago  e99afd36-bc94-44cc-b117-d73025d110e4
```

It still results in the following response:

```
flynn run nslookup myapp-web.discoverd
Server:		100.100.19.1
Address:	100.100.19.1#53

** server can't find myapp-web.discoverd: NXDOMAIN
```

**Comment by titanous** [comment]
Please make a gist of the output of `flynn release show --json`. Note that if you have any secrets in the app environment, they will need to be redacted from the JSON.

**Comment by mrrooijen** [comment]
```json
{
  "id": "e99afd36-bc94-44cc-b117-d73025d110e4",
  "app_id": "6b4bbf8e-048e-4a97-b910-3231faf18789",
  "artifacts": [
    "0bda64dd-67b3-41d0-b5a3-47e0d76a730e",
    "0cee81a3-5435-4e8d-b47a-ab6f1fad3013"
  ],
  "env": {
    "BUILDPACK_URL": "https://github.com/HashNuke/heroku-buildpack-elixir.git",
    "COOKIE": "monster",
    "MIX_ENV": "prod",
    "PARTY_DNS": "myapp-web.discoverd",
    "PARTY_SNAME": "web"
  },
  "meta": {
    "git": "true"
  },
  "processes": {
    "web": {
      "args": [
        "/runner/init",
        "start",
        "web"
      ],
      "ports": [
        {
          "port": 8080,
          "proto": "tcp",
          "service": {
            "name": "myapp-web",
            "create": true,
            "check": {
              "type": "tcp"
            }
          }
        }
      ],
      "service": "myapp-web",
      "resources": {
        "cpu": {
          "request": 1000,
          "limit": 1000
        },
        "max_fd": {
          "request": 10000,
          "limit": 10000
        },
        "memory": {
          "request": 1073741824,
          "limit": 1073741824
        },
        "temp_disk": {
          "request": 104857600,
          "limit": 104857600
        }
      }
    }
  },
  "created_at": "2017-01-17T18:54:40.183577Z",
  "artifact": "0bda64dd-67b3-41d0-b5a3-47e0d76a730e"
}
```

**Comment by titanous** [comment]
Okay, that all looks good, is your app listening on `$PORT`?

**Comment by mrrooijen** [comment]
Nope. It actually currently doesn't bind to any port (just sandboxing this library, eventually it'll be integrated into another project which will bind to `PORT`).

Note that while it currently doesn't bind to any port, when I run this using `docker-compose` I am able to link the containers together, and discover the container ip via `nslookup web` from within a separate container. 

For context: I'm trying to link together two Elixir (Erlang) nodes, and they are accessible via the overlay network provided by docker-compose without any configuration other than this in `docker-compose.yml`:

```yml
version: "2"
services:
  web:
    build: .
    environment:
      - MIX_ENV
      - PARTY_SNAME
      - PARTY_DNS
      - COOKIE
```

I'm quite new to Docker Compose and Elixir, so I'm not entirely sure how they are actually connecting (It'd have to be some port I'd assume), so I guess all ports are accessible by default by docker-compose?

**Comment by titanous** [comment]
The Flynn health check tries to connect using TCP to `$PORT` to see if the service is up, if there is nothing listening then subsequent deploys will fail and the app instances will not show up in service discovery.

**Comment by mrrooijen** [comment]
Aha. Perhaps I can create a basic (idle) TCP socket and bind it to PORT in order to become discoverable in that case. I'll give it a try.

**Comment by mrrooijen** [comment]
Yep. Looks like listening on $PORT will result in the service being discoverable. 👍

**Comment by mrrooijen** [comment]
Quick additional question related to container networking on Flynn: is communicating between containers secure? I know that for example Rancher encrypts all data that transfers over their overlay network (between containers) so you don't really have to worry about encryption at the app-level.

If Flynn doesn't encrypt/secure the connection between two containers, would running it on AWS (within the Flynn-configured VPC) make it secure?

**Comment by titanous** [comment]
@mrrooijen Currently there is no encryption for the overlay network, though we plan to add it in the future. Using a AWS VPC should be fine, as the only entity that can see your traffic at that point would be AWS.

**Comment by mrrooijen** [comment]
Sounds good.
