### ISSUE TITLE
Adding SSL certificate chain

### ISSUE THREAD

**Issue by holtgrewe** [flynn/flynn#3841]
In German academia, SSL certificates are often created having more than one hop from a generally trusted authority to the SSL certificate itself:

1. Telekom CA creates a certificate for DFN CA
2. DNF CA creates a certificate for a local CA
3. The local CA signs a certificate for machine.example.com

Now, generally only the first certificate is shipped with browsers and operating systems. (e.g., see `openssl s_client -connect www.bihealth.org`). In order to make the site appear as valid, I know that you can make Apache send more than one certificate (in the right order, the certificate closest to the root comes last).

When I'm trying to add multiple certificates in one PEM file with `flynn route add`, then Flynn fails with the error message:

```
validation_error: Certificate invalid: tls: private key does not match public key
```

Please advise.

**Comment by titanous** [comment]
The certificates should be in a PEM formatted file in order from leaf to CA, so something like this:

```
Leaf (machine.example.com, signed by Intermediate 2)
Intermediate 2 (signed by Intermediate 1)
Intermediate 1 (signed by CA, in trust store)
```
