### ISSUE TITLE
Restore backup on v20170116.0 fails [mariadb, web]

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#3843]
```
# flynn-host bootstrap --from-backup cluster-backup_20170117T200651.tar -n1
20:51:23.826362 check online-hosts
20:51:23.828669 run-app discoverd
20:51:24.687713 run-app flannel
20:51:25.439647 wait-hosts wait-hosts
20:51:27.457164 run-app postgres
20:51:29.414813 sirenia-wait postgres-wait
20:51:37.732980 restore-postgres restore
20:52:11.428918 run-app controller
20:52:12.464224 wait-controller wait-controller
20:52:12.913656 run-app mariadb
20:52:14.721747 sirenia-wait mariadb-wait
20:52:29.819895 host.go:163: error updating mariadb formation: validation_error: Requested formation includes process types that do not exist in release. Invalid process types: [mariadb, web]
```

Logs: https://gist.github.com/7eacfa34b812ff9d5dfa0a7776cd5909

**Comment by titanous** [comment]
What Flynn version was the cluster backup taken from?

**Comment by kwando** [comment]
Good question, I don't know, probably last stable version since that node was fairly fresh.

Might make sense to add ```flynn-host --version``` as meta data into the backup somewhere.

**Comment by kwando** [comment]
FYI, same thing happens when trying to restore on ```v20161218.1```. I can provide you with the broken backup if that is to any help.

**Comment by titanous** [comment]
That'd be awesome, please post it here or email to logs@flynn.io

**Comment by kwando** [comment]
I've sent an email with a download link.

**Comment by philiplb** [comment]
I plan to upgrade to v20170116.0 from v20161218.1 via the backup restore route tonight. Can I check if my backup is affected by this somehow? If not, I would wait with the upgrade until this is resolved.
