### ISSUE TITLE
compress database dump in flynn export

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#3844]
Database dump should probably be compressed in the output tar file when exporting an app.

Backing up one of my apps that is using mariadb makes me download 150+MB, while a full cluster backup weighs in at ~40MB.

```flynn export --file my-app.tar```  vs
```flynn cluster backup --file cluster-backup.tar```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
