### ISSUE TITLE
Unable to add route with path

### ISSUE THREAD

**Issue by fameoflight** [flynn/flynn#3845]
```flynn route add http example.com/path/```
validation_error: Invalid route

v20170116.0

Let me know if there is anything else I can provide that help debug the issue. Also I am posting here since I couldn't find much help on this specific issue.

**Comment by kwando** [comment]
Try ```flynn route add http://example.com/path/```

**Comment by kwando** [comment]
Is ```http://example.com``` a route in your cluster?

**Comment by fameoflight** [comment]
yep

**Comment by fameoflight** [comment]
Okay I tried remove the route path even than I am still getting the same error

**Comment by kwando** [comment]
Hmm, then I'm out of ideas. I'll have to hand you over to the experts. 

You should probably do ```flynn-host collect-debug-info``` and provide that information here.

**Comment by titanous** [comment]
@fameoflight Can you provide the output of `flynn route` for the app that has `example.com` already as a route?

**Comment by fameoflight** [comment]
here is the output 

ROUTE                                           SERVICE                      ID                                         STICKY  LEADER  PATH
https:fameoflight.com                           quetzals-spurn-euphemia-web  http/195c2e7b-cd58-47bc-a487-d51e6fcd5ecb  false   false   /
http:quetzals-spurn-euphemia.2mkz.flynnhub.com  quetzals-spurn-euphemia-web  http/0236b47a-895f-4136-a752-7fd0cdeabd41  false   false   /

btw I already tried flynn-host but the command is not available on my machine.

**Comment by fameoflight** [comment]
flynn-host
zsh: command not found: flynn-host

**Comment by titanous** [comment]
Please try this command:

```text
flynn route add http fameoflight.com/path
```

(it might be the trailing slash)

**Comment by fameoflight** [comment]
this worked I don't understand why did this work now
