### ISSUE TITLE
Permanent storage for app

### ISSUE THREAD

**Issue by pyr0hu** [flynn/flynn#3848]
Hello!

Is it possible to attach permanent storage for an application? E.g. I have a Laravel application and I want to locally store uploaded files. This requires to set up a symlink from the /storage/app to public/storage. I got around this by setting the base path to public/storage. Now the only issue is when I uploaded an image, redeployed the application, it disappears, as the storage is recreated again. Is it somehow possible to set a permanent storage for an app?

**Comment by titanous** [comment]
This is not currently possible, though watch #1521 for an upcoming solution.

**Comment by pyr0hu** [comment]
Wow, that was fast! Thank you, I'll look into S3 then :)
