### ISSUE TITLE
How much workload the databases can handle?

### ISSUE THREAD

**Issue by flaviobarros** [flynn/flynn#3849]
In the documentation it's statet that: **"Flynn’s databases are currently designed with staging, testing, development, and small-scale production workloads in mind. They are not currently suitable for storing large amounts of data. We are in the process of making them usable for all use cases, including high volume, large dataset workloads."** 

I just installed flynn in digital ocean, with 3 nodes (1Gb RAM each) and I'm about to deploy a system that will receive some traffic. In this system I will record a lot of clicks in the database related to a experiment in a big site. When should I be concerned regarding the database workload?

**Comment by josephglanville** [comment]
The main limiting factor right now in handling higher throughput workloads is #3425 isn't quite yet done.

There some other concerns regarding write throughput due to replication but they are secondary to being able to scale up resource usage of the databases to match the workload.

**Comment by flaviobarros** [comment]
Ok. For example, if I would have more then 100 thousand write requisitions per day in the database what would you advise-me to do? Do you think that flynn could hold such a load or should I look for something else as a managed database service?

**Comment by josephglanville** [comment]
If your load is relatively spread out 100k writes/day is nothing that it can't handle.

I am working very hard to get #3425 merged this cycle, it should be on master in just a few days so if you have performance requirements that would require you to tweak database settings running master may be an option.

However if this is a business critical application for now I would suggest using a hosted database option until #3425 is in stable and is battletested.
