### ISSUE TITLE
Feature: new API wrapper to parallel CLI functionality

### ISSUE THREAD

**Issue by mltsy** [flynn/flynn#3854]
After @lmars explained to me how to add a new resource using the controller API, it became evident that the CLI contains a lot of functionality not available through the API (added logic).  It would be awesome if flynn had an API that paralleled the functionality of the CLI (a go wrapper around the client could basically re-use a lot of the same code the CLI uses, but expose it via an API interface).

Alternatively, this could just be implemented as extra endpoints on the controller API, and the CLI could use those rather than containing the logic itself - which would reduce redundancy somewhat, if there isn't some reason not to implement it that way.

Any other interest in this, or thoughts about how to implement it?

**Comment by titanous** [comment]
We're headed in this direction with #2759. Instead of having dumb individual REST-style resources, writes (aka GraphQL mutations) are much closer to RPC calls and we can have them do a bit more on the controller side.

**Comment by mltsy** [comment]
Ooh yes!  That sounds pretty great :+1:

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
