### ISSUE TITLE
How to use the controller api from inside the Flynn?

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3856]
I'm trying to learn Golang so I decided to create a small app which can put the tarball from `$ flynn cluster backup` to aws s3 bucket automatically at user defined times.

I read your [api documentation](https://flynn.io/docs/api/controller) and taking the cluster backup seems really easy.

I wanted to test these with `curl` before coding anything and I tried this from my computer:
```
$ curl -i -H 'Content-Type: application/json' -u :$AUTH_KEY https://controller.example.com/backup
HTTP/1.1 200 OK
Content-Disposition: attachment; filename="flynn-backup-2017-01-19_202910.tar"
Content-Type: application/tar
Date: Thu, 19 Jan 2017 20:29:10 GMT
Transfer-Encoding: chunked
wiX$�����;S�g�m��ݲf*9Ƙ�(��M����}��5�;���9�_k�"
...
```
The resulting tarball works just fine. But when I create the same request inside the flynn cluster I only get `json` instead of the tarball:
```
$ flynn -a test run bash
$ curl -i -H 'Content-Type: application/json' -u :$AUTH_KEY http://controller.discoverd/backup
HTTP/1.1 200 OK
Content-Disposition: attachment; filename="flynn-backup-2017-01-19_203236.tar"
Content-Type: application/tar
Date: Thu, 19 Jan 2017 20:32:36 GMT
Transfer-Encoding: chunked

flynn-backup-2017-01-19_203236/flynn.json0000644000000000000000000003761613040221144015535 0ustar0000000000000000{
  "controller": {
    "app": {
      "id": "9760ca16-8c2e-43bf-ad8e-ca3806c406c5",
```

Is this even possible using `discoverd`?

```
$ flynn-host version
v20170116.0
```

**Comment by lmars** [comment]
@onnimonni the response in the second snippet looks like a tar file header, did you try writing it to a file and inspecting it with `tar tf`? e.g.:

```
$ curl -u :$AUTH_KEY -o backup.tar http://controller.discoverd/backup
$ tar tf backup.tar
```

**Comment by onnimonni** [comment]
Crap, I should have tried that before asking. I tried that now and the result works just fine. Thanks again and sorry for bothering!

**Comment by lmars** [comment]
No problem!

When learning Go, I'd suggest reading through the [Language Spec](https://golang.org/ref/spec) and [Effective Go](https://golang.org/doc/effective_go.html).
