### ISSUE TITLE
Automatically backup database appliances to external location?

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3857]
Hey!

Database backups are crucial part of every application and so far I have used hacky bash scripts to achieve mine. Do you already have an strategy in mind to deal with these? It could use the external storage defined in blobstore app.

I would like to see an external append-only backup storage like s3 in case the cluster gets hacked or to prevent developers/sysadmins from accidentally wiping out all of the data.

It would be nice to have a subcommand which could be used to easily rollback databases too.

**Comment by titanous** [comment]
Yes, we plan to have an automatic backup system, see #1244.
