### ISSUE TITLE
RPC failed; curl 18 transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by fzerorubigd** [flynn/flynn#3864]
I have a flynn cluster with 3 node, the nodes has no public IP, but they have an internal networking with this ips  (192.168.100.{101,102,103}) all 3 node have internet access (via NAT) and ports 80 and 443  from gateway (a public ip ) are forwarded to them using haproxy (80 in http mode, 443 in tcp mode) . 

I can publish apps inside this cluster, but the problem is sometimes I get this error on my git push : 

```
-----> Compiled slug size is 38.86 MiB
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```
when an app start to show this message, I can not publish that app anymore. is there anyway to investigate this?

**Comment by titanous** [comment]
Please try pushing without HAProxy in front of the cluster.

**Comment by fzerorubigd** [comment]
I have no public ipv4 available, but I can assign ipv6 (and AAAA record) is
that a problem??

**Comment by titanous** [comment]
Hmm, I don't think we've tested IPv6 at all. You could also do it from a host inside the private network (including one of the Flynn hosts).

**Comment by fzerorubigd** [comment]
I use /etc/hosts on the gateway to handle dns records, the result is changed to this : 

```
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date
```

**Comment by titanous** [comment]
Please run again with `GIT_TRACE=1 GIT_CURL_VERBOSE=1 git push flynn master` (make sure to redact the authentication details) and then run `sudo flynn-host collect-debug-info` and post the output of both here.

**Comment by fzerorubigd** [comment]
the first one https://gist.github.com/fzerorubigd/b0b559c177a5929cf25558beb466dfb0 and the other log, its actually big :) https://gist.github.com/anonymous/7cf35aa20e62b2650492f1cc2276f929

**Comment by fzerorubigd** [comment]
I think its solved. 
The reason was haproxy timeout. setting dns name on /etc/host is not enough since the `*.app.example.com` is required and its passed to the DNS server anyway. 
So, by setting a high timeout (more than hour) and using tcp mode everything is fine. 

Thank you!

**Comment by madslundholmdk** [comment]
@fzerorubigd what did you set the timeout to?
