### ISSUE TITLE
Deploy fails with "No space left on device"

### ISSUE THREAD

**Issue by RobinDaugherty** [flynn/flynn#3867]
Could be a duplicate of #3863, but I'm not certain.

We have a cluster running 20161218.1. 3 nodes. Deployments of applications to this cluster are failing. Slug build fails with:

```
ERROR: could not create slug image: mksquashfs error: exit status 1: 
Write failed because No space left on device

FATAL ERROR:Failed to write to output filesystem
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on /tmp/squashfs-167743186, block size 131072
```

Here is the output of `df` on each node: https://gist.github.com/RobinDaugherty/ca7ecca5e7331563740e97e763c94883

In setting this cluster up, [the instructions](https://flynn.io/docs/production#custom-zfs-pool) were followed to add a raw disk to the ZFS pool and then remove the original image file.

Here is the output of `zpool list` on each node:
```
NAME            SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
flynn-default  8.06G  7.37G   705M     75.7G    62%    91%  1.00x  ONLINE  -

NAME            SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
flynn-default  8.06G  6.40G  1.66G     75.7G    56%    79%  1.00x  ONLINE  -

NAME            SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
flynn-default  8.06G  7.22G   861M     75.7G    60%    89%  1.00x  ONLINE  -
```

It seems possible but unlikely that 705 MB is not enough to build a slug. It's possible that I need to increase the size of the ZFS pool to fill the available raw disk, as I believe the disk kept the original size. I will try that to see if anything changes.

**Comment by josephglanville** [comment]
@RobinDaugherty can you run `zpool status` on each node?

It looks like perhaps the process to migrate the data to the dedicated disk didn't work correctly as the zpool seems to only have 8gb of capacity.

@kenaniah it looks like you might have the same problem, 5gb zpool is very small also.
Did you too attempt to move the zpool to a dedicated disk?

**Comment by RobinDaugherty** [comment]
I deleted those nodes, but here's one from a node that seems to be in the same state:

```
  pool: flynn-default
 state: ONLINE
  scan: resilvered 1.48G in 0h0m with 0 errors on Thu Jan 12 17:00:04 2017
config:

	NAME        STATE     READ WRITE CKSUM
	flynn-default  ONLINE       0     0     0
	  sdc       ONLINE       0     0     0
```

This ZFS pool was created by the Flynn installer, so it was originally in an image file, and I added `sdc` to it later. From my research into ZFS, it seems impossible to increase the size of a ZFS mirror volume directly. You must have `autoexpand` enabled before adding a larger physical disk to it. However, I haven't tried using that method.

The method I ended up using is to create a ZFS pool named `flynn-default` before installing Flynn so that the image file is never created in the first place. This makes the pool large enough to be comfortable in our case. (This is covered in [the docs](https://flynn.io/docs/production#custom-zfs-pool).)

**Comment by RobinDaugherty** [comment]
I also looked for ways to reduce the disk usage of the ZFS pool, for example by deleting releases. Space doesn't seem to be freed by doing that.

**Comment by lmars** [comment]
@RobinDaugherty 

> it seems impossible to increase the size of a ZFS mirror volume directly. You must have autoexpand enabled before adding a larger physical disk to it. However, I haven't tried using that method.

You should enable `autoexpand`, that is what the Flynn installer does in AWS to move from the sparse file to an EBS volume (see [here](https://github.com/flynn/flynn/blob/master/installer/cluster.go#L925-L933)).

> I also looked for ways to reduce the disk usage of the ZFS pool, for example by deleting releases. Space doesn't seem to be freed by doing that.

If you want to reclaim disk space used by PostgreSQL, you need to run `VACUUM FULL` (see [this comment](https://github.com/flynn/flynn/issues/3646#issuecomment-259825872)).

**Comment by RobinDaugherty** [comment]
`autoexpand` seems to be on for the zpool created by the installer. After switching to a raw drive I also tried [turning it off and back on](https://jsosic.wordpress.com/2013/01/01/expanding-zfs-zpool-raid/). But that didn't seem to work. This is on Ubuntu 16.04, so it seems very possible that it is localized to this version.

I didn't think about a vacuum! I'll give that a try next time. The comment you linked to was specifically about the blob store, but in our case we're use S3 for the blob store. Is it odd that our ZFS drive is filling up when we're using an external blob store? Is there a way to get a breakdown of disk usage to try to narrow down the cause?

**Comment by titanous** [comment]
@RobinDaugherty It's also possible that the zpool was filling up with container images from previous app releases, `flynn-host volume gc` will clean those up (they will be automatically removed in a future release).
