### ISSUE TITLE
Deploy Jenkins as new app from .war file

### ISSUE THREAD

**Issue by regedarek** [flynn/flynn#3870]
I have jenkins.war file. Am I able to deploy it in my flynn cluster as new app? How to do that?

**Comment by lmars** [comment]
@regedarek Flynn uses the [Heroku Java buildpack](https://github.com/heroku/heroku-buildpack-java) to build Java apps pushed via 'git push', take a look through that README (I suspect you want to run it with the Jetty Runner e.g. `java -jar jetty-runner.jar jenkins.war`).

You could also build and push a Docker image containing Java and your `war` file (see [here](https://flynn.io/docs/docker)).

**Comment by imjorge** [comment]
@regedarek See [here](https://github.com/imjorge/jenkins-on-flynn) for a working solution.

**Comment by lmars** [comment]
@imjorge nice :+1:
