### ISSUE TITLE
Add HTTP/2 server push to router

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3871]
**I'm just throwing this here as an idea:**

I think plenty of people were pretty excited when http2 server push was first presented. Finally we could stop inlining stuff into the html document and achieve better caching results in the browsers.

Unfortunately almost everyone including nginx and caddy are thinking that this would only lead to more unnecessary bandwidth usage and shouldn't be done for now.

I'm suggesting something similiar what [cloudflare has done](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/).

They will use http2 server push promise if the response contains Link headers:
```
Link: </asset/to/push.js>; rel=preload; as=script
```

In Flynn this could be implemented:
1. Router checks if the response contains `Link:` headers
2. Router adds push promise to the tcp frame: https://godoc.org/golang.org/x/net/http2#Framer.WritePushPromise
3. Router creates request to the linked assets and sends them to the client immediately.

End result would look like this:
```
HTTP/2.0 200 OK
Content-Type: text/html; charset=UTF-8
Date: Tue, 24 Jan 2017 13:08:36 GMT
Link: </asset/to/push.js>; rel=preload; as=script
Link: </asset/to/push.css>; rel=preload; as=style
```

I know this goes against the guideline of keeping the router simplistic as possible but this could save one roundtrip and give huge performance boost on the first page load. Because the first page load is so important for the client experience I believe this feature would be useful for the users of Flynn.

What do you think @titanous?

**Edit:** I moved the cache awereness of the http2 server push feature into another issue https://github.com/flynn/flynn/issues/3874

**Comment by titanous** [comment]
I think it makes sense to implement push using the exact same syntax as CloudFlare. Though, I don't think we need to do anything related to cookies or sticky backends?

**Comment by onnimonni** [comment]
And leave that part to the client application? Maybe that's for the best. 

I'm a bit worried about caching and that the client applications would just cache those headers leading into situation where Flynn router pushes everything in every request.

**Comment by titanous** [comment]
I'm not sure what you mean about client applications? The apps deployed on Flynn have complete control over their caching and so can do whatever they want. It'd be a bug to cache the headers incorrectly across different URLs.

**Comment by onnimonni** [comment]
Yes I know,  sorry for being unclear.  I feel that accidental misusage of this feature is the main reason why nginx hasn't created the http2 server push already.

And even cloudflare implements this logic for their users. 

I might be afraid for no reason and you know better.

**Comment by titanous** [comment]
Can you link to the CF docs for this?

**Comment by onnimonni** [comment]
And yes I meant client applications = deployed applications.

**Comment by onnimonni** [comment]
CF is being quite vague about it. This is the best I could find: https://support.cloudflare.com/hc/en-us/articles/218367338-HTTP-2-Server-Push

**Comment by onnimonni** [comment]
Here's W3C document about the `preload` in http2 server push: https://www.w3.org/TR/preload/#server-push-http-2
It's also quite vague about the implementation but does list one more thing. 

Link headers with `nopush` should be skipped by the router:
```
Link: </dont/want/to/push/this.css>; rel=preload; as=stylesheet; nopush
```

**Comment by onnimonni** [comment]
I created a demo which demostrates this feature in CF:
https://http2-server-push-demo.keksi.io/

I hope this is useful for figuring out the http2 server push.

After I have visited the example site I can see in `chrome://net-internals/ ` -> `Events` tab these logs:
```
...
t=16487 [st= 582]    HTTP2_SESSION_RECV_HEADERS
                     --> fin = false
                     --> :status: 200
                         date: Tue, 24 Jan 2017 20:06:50 GMT
                         content-type: text/html; charset=UTF-8
                         set-cookie: [125 bytes were stripped]
                         cache-control: public, max-age=0, must-revalidate
                         x-frame-options: DENY
                         x-xss-protection: 1; mode=block
                         age: 386
                         vary: Accept-Encoding
                         strict-transport-security: max-age=31536000; includeSubDomains; preload
                         x-content-type-options: nosniff
                         server: cloudflare-nginx
                         cf-ray: 32661bb299225b81-HEL
                         content-encoding: gzip
                         cf-h2-pushed: </image.jpg>
                     --> stream_id = 1
t=16489 [st= 584]    HTTP2_SESSION_RECV_PUSH_PROMISE
                     --> :authority: http2-server-push-demo.keksi.io
                         :method: GET
                         :path: /image.jpg
                         :scheme: https
                         accept-encoding: gzip, deflate, sdch, br
                         user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
                         accept-language: fi-FI,fi;q=0.8,en-US;q=0.6,en;q=0.4
                     --> id = 1
                     --> promised_stream_id = 2
t=16489 [st= 584]    HTTP2_SESSION_RECV_DATA
                     --> fin = false
                     --> size = 802
                     --> stream_id = 1
t=16489 [st= 584]    HTTP2_SESSION_UPDATE_RECV_WINDOW
                     --> delta = -802
                     --> window_size = 15727838
t=16489 [st= 584]    HTTP2_SESSION_RECV_DATA
                     --> fin = false
                     --> size = 599
                     --> stream_id = 1
t=16489 [st= 584]    HTTP2_SESSION_UPDATE_RECV_WINDOW
                     --> delta = -599
                     --> window_size = 15727239
t=16489 [st= 584]    HTTP2_SESSION_RECV_DATA
                     --> fin = true
                     --> size = 0
                     --> stream_id = 1
t=16489 [st= 584]    HTTP2_STREAM_UPDATE_RECV_WINDOW
                     --> delta = 802
                     --> window_size = 15728041
t=16489 [st= 584]    HTTP2_STREAM_UPDATE_RECV_WINDOW
                     --> delta = 599
                     --> window_size = 15728640
t=16500 [st= 595]    HTTP2_SESSION_SEND_HEADERS
                     --> exclusive = true
                     --> fin = true
                     --> has_priority = true
                     --> :method: GET
                         :authority: http2-server-push-demo.keksi.io
                         :scheme: https
                         :path: /style.css
                         pragma: no-cache
                         cache-control: no-cache
                         user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
                         accept: text/css,*/*;q=0.1
                         dnt: 1
                         referer: https://http2-server-push-demo.keksi.io/
                         accept-encoding: gzip, deflate, sdch, br
                         accept-language: fi-FI,fi;q=0.8,en-US;q=0.6,en;q=0.4
                         cookie: [52 bytes were stripped]
                     --> parent_stream_id = 0
                     --> stream_id = 3
                     --> weight = 256
t=16501 [st= 596]    HTTP2_STREAM_ADOPTED_PUSH_STREAM
                     --> stream_id = 2
                     --> url = "https://http2-server-push-demo.keksi.io/image.jpg"
...
```

**Comment by onnimonni** [comment]
After playing a while with this I noticed that Cloudflare will just push the same cached assets again if browser is closed and reopened or if I go to another path in the site like `/subpage/`:
<img width="611" alt="demo-site-chrome-network-cached-assets" src="https://cloud.githubusercontent.com/assets/5691777/22266901/713e553c-e28a-11e6-9dfb-6e42c8557c4a.png">

**Steps to reproduce:**
1. Visit: https://http2-server-push-demo.keksi.io/ so that assets get cached
2. Close chrome ( So that all sessions are closed )
3. Open [chrome://net-internals/#events](chrome://net-internals/#events)
4. Visit https://http2-server-push-demo.keksi.io/ again and see from  [chrome://net-internals/#events](chrome://net-internals/#events) that the `image.jpg` gets pushed again even though it's already in browser cache

Example logs:
https://gist.github.com/onnimonni/bb5db7dd9112990c8314b4e6c178c087

This is unnecessary traffic which won't happen with http1.1.

If this feature is implemented developers should be adviced about the dangers of just adding the `Link` headers for all assets.

**Comment by onnimonni** [comment]
Sorry for all the confusion Let's just keep this issue only about adding http/2 server push support and the cache awereness in another issue I created here: https://github.com/flynn/flynn/issues/3874

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
