### ISSUE TITLE
Add cache-awareness to HTTP/2 server push

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3874]
We have issue about adding HTTP2 server push in https://github.com/flynn/flynn/issues/3871.

This issue is about tuning the server push to be more browser cache aware.

h2o web server really shines in this with their `http2-casper` feature:
https://h2o.examp1e.net/configure/http2_directives.html#http2-casper

I'm hoping that we could have something similiar in Flynn.

Here's a really good document about http2 best practises:
https://docs.google.com/document/d/1K0NykTXBbbbTlv60t5MyJvXjqKGsCVNYHyLEXIxYMv0/edit#heading=h.2cp5b1jj5o7n

**Comment by onnimonni** [comment]
@titanous I edited the original issue #3871 and I hope this makes my intentions more clearer.

My go skills are growing and I would be willing to help with this If you feel that this would be a good addition into Flynn.

**Comment by titanous** [comment]
Yes, I think this would be a great addition to Flynn. Let me know if you have any implementation questions and feel free to submit PRs early and often.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
