### ISSUE TITLE
Can not start interactive session: unknown_error: Something went wrong

### ISSUE THREAD

**Issue by villepietarinen** [flynn/flynn#3876]
```
flynn -c stage -a example run bash
unknown_error: Something went wrong
```

This happens every second or third time when connecting.

```
flynn-host version
v20170116.0

flynn version
v20170125.0
```

**Comment by lmars** [comment]
@villepietarinen check `flynn -a controller log -t web` shortly after you encounter this error, you should see a more revealing error message in that log.
