### ISSUE TITLE
flynn-wp: cropping does not work

### ISSUE THREAD

**Issue by regedarek** [flynn/flynn#3877]
Hey,
I installed wordpress with: https://github.com/zomnium/flynn-wp/

I just have one issue: During cropping images I get an error.
I don't see anything in flynn logs. Just noticed that: slugbuilder service is DOWN.

Could you help me find what can cause the problem?

**Comment by lmars** [comment]
@regedarek 

> During cropping images I get an error.

What error do you get?

> Just noticed that: slugbuilder service is DOWN.

That is expected, the slugbuilder is a one off job which builds your app when you do a `git push`, so it exits once the build has finished and your code is deployed.

**Comment by regedarek** [comment]
looks like on my server there is no imagemagick, how I can add it to this container? or should I install it on my server?

**Comment by lmars** [comment]
@regedarek apps deployed via `git push` have access to both `imagemagick` and `libmagickwand-dev`, see this for example:

```
$ flynn run convert --version
Version: ImageMagick 6.7.7-10 2016-11-29 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

$ flynn run dpkg -l libmagickwand-dev
...
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  libmagickwand-dev                                     8:6.7.7.10-6ubuntu3.3           amd64                           image manipulation library - development files
```
