### ISSUE TITLE
Add a warning and mention in docs that AMIs cannot be used as-is for installation

### ISSUE THREAD

**Issue by rikur** [flynn/flynn#3882]
Apparently the AMIs are meant to be used via the cloud-installer, not just by themselves. I tried to use them as a shortcut for faster installation, but many things were missing and made the cluster unusable:
 - flynn-host doesn't start by default
 - flynn-default zfs pool isn't expanded from 5.41G
 - .. probably many other setup steps that the installer does

Could be nice to have a warning of some sort if someone tries to do the same. Would have saved me hours of debugging.

**Comment by titanous** [comment]
Currently the AMIs aren't documented anywhere, so this doesn't seem like a big deal?

**Comment by rikur** [comment]
Probably not a big deal, just a suggestion to help tinkerers like me :)

**Comment by rikur** [comment]
Maybe this issue, even after it has been closed, will help people who google "Can I use the Flynn AMIs for installation" :)

**Comment by titanous** [comment]
Yeah, I think that's good enough for now :)
