### ISSUE TITLE
Add automatic deploy from Github

### ISSUE THREAD

**Issue by jxltom** [flynn/flynn#3883]
Flynn is awesome.

It will great for adding automatic deploy from a chosen branch of GitHub. Every push to the chosen branch will trigger a new deployment. For a reference, Heroku already has this feature [Automatic deploys](https://devcenter.heroku.com/articles/github-integration#automatic-deploys).

**Comment by imjorge** [comment]
@jxltom perhaps you want [this](https://github.com/lmars/flynn-webhook-deploy)?
