### ISSUE TITLE
host: Tags are lost after restart

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3893]
Hi,
one of my nodes was rebooted by the hoster this morning (planned) and it lost its tags. Would be nice if they would be persistent. :)

**Comment by lmars** [comment]
The tags are currently "stored" in discoverd instance metadata, but the new host which comes up doesn't retrieve that metadata on startup so overwrites it with empty metadata.

We should store the tags in the local host state database.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
