### ISSUE TITLE
Flynn should complain about incompatible firewall settings

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#3899]
Just had a fun evening tearing my hair out over a Flynn single-node cluster that wouldn't start until I worked out that I needed to change my firewall setting on the internal network interfaces.

In particular: https://philiplb.de/flynn/2016/04/19/flynn-ufw/

Would be great if Flynn could either:

1. Configure the firewall itself during installation or boostrap.
2. Fail in a clear manner and report that the firewall is an issue.

**Comment by lmars** [comment]
I think option 2 is the way to go (there are many ways for users to configure firewalls, and I don't think Flynn should be interfering with that).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
