### ISSUE TITLE
Flynn run fails on Windows with "Descripteur non valide"

### ISSUE THREAD

**Issue by seza443** [flynn/flynn#3908]
I'm trying to run `flynn run rake db:migrate` but it outputs

    Descripteur non valide

Other commands like `flynn ps` work fine

    > flynn version
    v20170207.0

    OS: Windows 10 64 bits Pro

**Comment by seza443** [comment]
Running the same command from an Ubuntu machine, configured for the same cluster and same app works fine. The issue is related to Windows I guess

**Comment by titanous** [comment]
I think that interactive terminals are not currently supported on Windows.

**Comment by shasderias** [comment]
@titanous That would be correct.

A workaround is to install Bash on Ubuntu for Windows/Windows Subsystem for Linux and run Flynn from bash.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
