### ISSUE TITLE
Log sink not sending to syslog server

### ISSUE THREAD

**Issue by RobinDaugherty** [flynn/flynn#3909]
I put in place a log-sink, which functioned for about 36 hours before it stopped sending.

This is a cluster with 3 hosts running `v20170116.0p2`. The destination is a LogDNA (syslog, non-SSL) endpoint, and we have another cluster sending to the same syslog URL, and it is working correctly. The other cluster is running `v20170207.0`.

There are 2 `logaggregator` processes running. Nothing in their respective logs (in `/var/log/flynn/<logaggregator appid>.log` on each of the hosts) seems to be out of the ordinary.

In the `sinks` table, I have about 10 sinks that are deleted (have non-null `deleted_at` values) from my attempts at setting up a working sink previously.

I've removed the existing sink, restarted the `logaggregator` processes, and added a new sink.

When I did this, a small handful of outdated log entries were sent to the destination. It seems like a random assortment of entries from a couple of apps (~200), plus about 5 from the router and 100 or so from `logaggregator`. All of the entries except the very last one from `logaggregator` have timestamps from _before the log entries stopped coming in several days ago_. After this batch, there are no more log entries sent.

In `/var/log/flynn/flynn-host.log`, I see the following entries with similar time codes on each host:
```
t=2017-02-09T15:25:19+0000 lvl=info msg="connecting to sink" app=host pid=20604 host.id=flynn05.example.com component=logmux fn=addSink
t=2017-02-09T15:25:19+0000 lvl=info msg="got cursor" app=host pid=20604 host.id=flynn05.example.com component=logmux fn=addSink cursor.timestamp=2017-02-09T15:23:
37+0000 cursor.seq=2292264
```

But that's the last mention of logmux in those logs.

Any more information I can gather? Ideas on how to troubleshoot further?

**Comment by titanous** [comment]
@RobinDaugherty All of the external sync sending is done directly from `flynn-host`, so the logs from each host would be useful. `flynn-host collect-debug-info` would grab that, you can also grab `/var/log/flynn/flynn-host.log` directly.

**Comment by landonclark** [comment]
I was just coming to search for this same issue.  I am seeing the same thing?  Is this closed due to lack of context or is it fixed?

**Comment by lmars** [comment]
@landonclark we closed this due to lack of information. As previously mentioned, the logs from your cluster would be useful in debugging this.

**Comment by landonclark** [comment]
What's the preferred way to send things to you that are too large for gist and attachment?  my collect-debug-log is about 58MB?
