### ISSUE TITLE
docker-receive: Images with ENV containing tabs cannot be pushed

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3910]
The artifact fails to be created with the following error in the `docker-receive` logs:

```
ERROR: json: error calling MarshalJSON for type json.RawMessage: invalid character '\\t' in string literal\n
```

To reproduce:

* build a Docker image with a tab in an env var

```
$ docker build -t tab-env - <<< "$(echo -e 'FROM scratch\nENV FOO bar\tbaz')"                                                                                                          
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM scratch
 ---> 
Step 2 : ENV FOO bar    baz
 ---> Running in 81741bc7e676
 ---> 06703e5d8c2f
Removing intermediate container 81741bc7e676
Successfully built 06703e5d8c2f
```

* push it to Flynn

```
$ flynn -a tab-env docker push tab-env
flynn: getting image config with "docker inspect -f {{ json .Config }} tab-env"
flynn: tagging Docker image with "docker tag tab-env docker.1.localflynn.com/tab-env:latest"
flynn: pushing Docker image with "docker push docker.1.localflynn.com/tab-env:latest"
The push refers to a repository [docker.1.localflynn.com/tab-env] (len: 1)
06703e5d8c2f: Pushed 
latest: digest: sha256:1346da490a595ff0b0f147771b79e83fb122c7f8fad0b3db142655eabdfefcca size: 1322
Received unexpected HTTP status: 500 Internal Server Error
```

The error is specifically trying to encode `Artifact.RawManifest` which contains the tab character in `Entrypoint.Env`, we should probably quote the raw manifest (i.e. convert literal tabs to `\t`).

**Comment by schroedingersZombie** [comment]
I also encounter that problem when restoring a backup containing an docker image with tab in environment. At least I think, that this has the same cause.
`17:29:17.545360 migrate-artifacts running Docker image migrator
17:29:17.557127 migrate-artifacts converting 3 active Docker images to Flynn images
17:29:17.557134 migrate-artifacts converting Docker image 8ba9251a-366a-48f7-b1ee-df8ea1bf81a9 (1/3)
17:30:04.618664 migrate-artifacts ERROR: json: error calling MarshalJSON for type json.RawMessage: invalid character '\t' in string literal
17:30:04.621416 migrate-artifacts error converting Docker image 8ba9251a-366a-48f7-b1ee-df8ea1bf81a9 (1/3): exit status 1
17:30:04.621435 migrate-artifacts error running Docker image migrator: exit status 1
17:30:04.908255 migrate-artifacts migrate-artifacts error: error migrating Docker images: exec: job exited with status 1
`

**Comment by lmars** [comment]
@schroedingersZombie did this prevent the restore from completing? If the cluster booted, the easiest thing will be to re-deploy the image just without any tabs in the environment variables.

**Comment by schroedingersZombie** [comment]
@lmars I just tried it again, and sadly the cluster won't boot after that restore.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
