### ISSUE TITLE
Error: bootstrap: controller-wait wait error: bootstrap: timed out

### ISSUE THREAD

**Issue by Schinti95** [flynn/flynn#3912]
i have an issue trying to set up my first flynn-cluster, maybe someone is able to help me with this: 

`Error: bootstrap: controller-wait wait error: bootstrap: timed out waiting for http://controller.discoverd, last response "Get http://100.100.17.4:80: dial tcp 100.100.17.4:80: i/o timeout"`

hope someone can help me, thanks

**Comment by lmars** [comment]
@Schinti95 do you have a firewall configured? Or have you perhaps also installed Docker 1.13 on the same host?

**Comment by Schinti95** [comment]
@lmars for firewall I just have iptables configured:

> *filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p udp -m udp --dport 443 -j ACCEPT
-A INPUT -p udp -m udp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -m state --state INVALID -j DROP
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s <IP HOST 1>/32 -j ACCEPT
-A INPUT -s <IP HOST 2>/32 -j ACCEPT
-A INPUT -s <IP HOST 3>/32 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
-A INPUT -i flynnbr0 -j ACCEPT
-A INPUT -i flannel0 -j ACCEPT
-A INPUT -i flannel.1 -j ACCEPT
-A INPUT -i vnet+ -j ACCEPT
-A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
-A OUTPUT -p tcp -m tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT

I just noticed on 2 Hosts i habe Docker 1.12.6, on one Host I habe 1.13.0 , can this be the issue?

**Comment by lmars** [comment]
@Schinti95 Docker is known to mess with iptables and potentially cause issues (see [here](https://twitter.com/jbeda/status/826969113801093121) for example).

I recommend installing Flynn on hosts without Docker.
