### ISSUE TITLE
Getting the host ip from flynn env

### ISSUE THREAD

**Issue by fi0** [flynn/flynn#3913]
how do I access services that are running on the flynn host without docker, from a container?
from `flynn env` I do not see the ip / host name of the flynn host

**Comment by josephglanville** [comment]
@fi0 could you be more specific? Are you talking about services you have installed directly on the host machine or are you talking about Flynn services?

**Comment by fi0** [comment]
I want to run a postgres service directly on the host machine without flynn.
And I want to access the postgres service from a service running in a flynn container.

**Comment by josephglanville** [comment]
You can use the hosts external IP address, it should be routable from containers. You could also use the loopback address if you only have a single Flynn host, i.e `127.0.0.1:5432`

**Comment by l4u** [comment]
thank you @josephglanville

**Comment by fi0** [comment]
The host external IP works. But 127.0.0.1 doesn't work. Do I need to set up forwarding if I want to use the loopback address?

**Comment by fi0** [comment]
When I use the gateway address (from `route`), it works. How do I add it to env automatically?

**Comment by titanous** [comment]
You should set the IP that you want to access with `flynn env set`, there is no way to do this automatically out of the box.
