### ISSUE TITLE
Flynn unusable

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#3915]
Not sure what going on with the latest version of Flynn but I'm finding it pretty much unusable as I can no long push updates to my apps without fear of it bringing down 1 or more of the apps running on the servers.

I'll email you my latest logs where when I pushed 1 app another app went into a service unavailable state straight away.

**Comment by lmars** [comment]
@dottodot is your app perhaps crashing due to memory constraints?

Run the following to check if your app is hitting the memory limit:

```
flynn -a sticky log --init | grep -F 'lack of available memory'
```

Also, check `/var/log/syslog` to see if the kernel is killing processes due to the host running low on memory.

**Comment by dottodot** [comment]
Going to try a cluster with 4G of memory to see if that resolves it. Thankfully found alternative hosting for the same price so I don't have to double my costs.

**Comment by lmars** [comment]
@dottodot did you confirm it was a memory issue though? I didn't see evidence of it in the logs, it was just more of a suspicion because the debug logs don't include your app logs / syslog.

**Comment by dottodot** [comment]
I seem a lot of these errors in the log

2017-02-13T11:21:21.389274Z app[web.cluster3-a7576a8e-0894-495a-97fe-c9b1fad9562c]: t=2017-02-13T11:21:21+0000 lvl=warn msg="healthcheck error" component=containerinit name=bailey-live-web port=8080 proto=tcp component=monitor check=tcp://100.100.7.8:8080 err="dial tcp 100.100.7.8:8080: getsockopt: connection refused"

**Comment by lmars** [comment]
@dottodot that is an expected error when your app is starting up (containerinit does checks on the process to wait for it to start accepting connections before registering the service and thus leading to existing jobs being stopped).

If your app is being killed due to memory issues, you will see the following in the log:

```
FATAL: a container process was killed due to lack of available memory
```

Is that appearing? Do you have any OOM warnings in `/var/log/syslog`?

**Comment by lmars** [comment]
P.S. if that log you posted is repeated and then your app dies, then your app is being killed because it is genuinely failing the healthcheck (i.e. it is not accepting connections on port 8080).

**Comment by dottodot** [comment]
I can't see anything like that but since I upgraded the memory I seem to be able to push updates without issue now.

**Comment by lmars** [comment]
@dottodot are you happy to close this issue then? You should also keep an eye on `/var/log/syslog`.

**Comment by dottodot** [comment]
Yes, If I run into more issues I'll create a new one.
