### ISSUE TITLE
dial tcp: i/o timeout on flynn create 

### ISSUE THREAD

**Issue by Snazzyham** [flynn/flynn#3918]
Apologies if this is a duplicate but I couldn't find an issue referencing this anywhere. 

So I installed flynn on my remote server using the cli tool (flynn install) on my local machine and got that all up and running. 

Now when I try and follow the `Deploy` instructions in the docs, running `flynn create` returns 
```
Post https://controller.6myp.flynnhub.com/apps: dial tcp: i/o timeout
```

I tried running the same thing on my server via SSH but that says I have no clusters defined. 

I apologise if I'm doing anything wrong, I'm new to the whole PaaS thing and servers in general.

**Comment by josephglanville** [comment]
It seems like there may be a networking issue between your local machine and your server. Did you use the SSH installer? If so can you check to see you don't have firewall rules configured with `iptables` or `ufw` that might be conflicting?

The reason you get an error that no clusters have been configured on the server is that the flynn CLI isn't configured on the server you could use the information from your local copy of `~/.flynnrc` to run the `flynn cluster add` command on the server if you want to use flynn CLI commands on the server.

**Comment by Snazzyham** [comment]
Thanks for the quick response, tried running it again on a different wifi network and it worked fine. Thanks! closing issue now.
