### ISSUE TITLE
Flynn does not update node IP if it was changed by DHCP

### ISSUE THREAD

**Issue by IsNull** [flynn/flynn#3921]
Flynn host version: `v20170116.0p2`, Ubuntu 16.04

The (DHCP) IP of my single node Flynn has changed from `192.168.1.253` to `192.168.1.50`. (I have made this change on the DHCP server)

This caused the "cluster" to completely die. Even after a reboot the new IP is not picked up by Flynn / discovered.

```
ubuntu@flynn-home:~$ ifconfig
ens18     Link encap:Ethernet  HWaddr 4a:dc:79:fb:bb:1d  
          inet addr:192.168.1.50  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::48dc:79ff:fefb:bb1d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:127284 errors:0 dropped:5 overruns:0 frame:0
          TX packets:77378 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:11696680 (11.6 MB)  TX bytes:4775496 (4.7 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:199331 errors:0 dropped:0 overruns:0 frame:0
          TX packets:199331 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:40238457 (40.2 MB)  TX bytes:40238457 (40.2 MB)

ubuntu@flynn-home:~$ flynn-host list
09:32:34.563284 host.go:163: Error sending HTTP request, errors: Get http://192.168.1.253:1111/services/flynn-host/instances: dial tcp 192.168.1.253:1111: getsockopt: no route to host,Get http://192.168.1.253:1111/services/flynn-host/instances: dial tcp 192.168.1.253:1111: getsockopt: no route to host,Get http://192.168.1.253:1111/services/flynn-host/instances: dial tcp 192.168.1.253:1111: getsockopt: no route to host,Get http://192.168.1.253:1111/services/flynn-host/instances: dial tcp 192.168.1.253:1111: getsockopt: no route to host
```

* This should probably not happen
* `flynn-host fix` ends up in the same error as `list`
* Would there be a way to manually update the old IP to the new one?

**Comment by josephglanville** [comment]
This is expected as the `discoverd` cluster uses static addresses for cluster membership.
You can technically fix this up with `flynn-host promote` command though I haven't attempted to fix it before.

What is strange is that a single node being down is causing cluster wide outage, perhaps this is due to load balancing or DNS setup not being configured with health checks?
Does `flynn-host list` work from other nodes in the cluster?

In production scenarios care should be taken to ensure Flynn cluster nodes don't change addresses.

**Comment by IsNull** [comment]
Thank you for your super fast response. 

> What is strange is that a single node being down is causing cluster wide outage

It is a non production, single node cluster for experiments :) So I am a bit surprised that a single node cant survive a changing IP. After all, it does not need to talk to any other node. I will try to fix it with 

```
ubuntu@flynn-home:~$ flynn-host promote 192.168.1.50
09:52:45.363487 host.go:163: unknown_error: Something went wrong
```

Well I'm going ahead and make a fixed IP and reinstall Flynn.

> In production scenarios care should be taken to ensure Flynn cluster nodes don't change addresses.

In production, we have static IPs on the servers due to general policies. However, I cant remember reading about this requirement in the docs. Maybe it would be a good idea to state this in the docs under the host requirements?

**Comment by josephglanville** [comment]
Yes I do believe we should add this to the docs. @titanous do you think adding it the operating/production requirements section would be sufficient?

**Comment by titanous** [comment]
Yeah, a mention in the requirements section seems fine.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
