### ISSUE TITLE
SSL certificate problem: Invalid certificate chain

### ISSUE THREAD

**Issue by regedarek** [flynn/flynn#3927]
Hey, I just set up on new machine my flynn cluster. I have access to it but I cannot deploy. Can you help me?

```
fatal: unable to access 'https://git.wpx9.flynnhub.com/kw-app.git/': SSL certificate problem: Invalid certificate chain
```

**Comment by titanous** [comment]
Have you run `flynn cluster add` on the client machine you are trying to deploy from?

**Comment by regedarek** [comment]
Ah the issue was wrong domain domain:(added `https://controller.`)

```
flynn cluster add -p pin= flynn wpx9.flynnhub.com key
```
