### ISSUE TITLE
Cannot deploy thru git

### ISSUE THREAD

**Issue by pyr0hu** [flynn/flynn#3934]
Hello!

Today I tried to push a new deployment from git, but I got some weird error.

```
Counting objects: 50, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (48/48), done.
Writing objects: 100% (50/50), 6.59 KiB | 0 bytes/s, done.
Total 50 (delta 24), reused 0 (delta 0)
-----> Building production...
-----> PHP app detected
-----> Bootstrapping...
remote: 
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote: ERROR: Build failed: exec: job exited with status 2
To https://git.xxxxxx.com/production.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.xxxxxx.com/production.git'
```

It never happened before, tried restarting the whole server, still the same

**Comment by philiplb** [comment]
The current PHP buildpack of Flynn is outdated and broken. You can set it to a more recent version via this env var for the time being:
BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php#v119
See https://botbot.me/freenode/flynn/2017-02-22/?msg=81375875&page=1 for reference.

**Comment by lmars** [comment]
@pyr0hu the PHP buildpack currently referenced by Flynn seems to have a broken link to PHP 7.0.14 [here](https://github.com/heroku/heroku-buildpack-php/blob/960199a9/bin/compile#L100):

```
$ curl -fsSLo /dev/null https://lang-php.s3.amazonaws.com/dist-cedar-14-stable/php-min-7.0.14.tar.gz                         
curl: (22) The requested URL returned error: 404 Not Found
```

As @philiplb has said, updating to a more recent buildpack version fixes this as it now references PHP 7.0.16 which does exist.

We will update the built-in buildpack version and push a release.

**Comment by dzuelke** [comment]
Why even pin to a version, and not just use the latest? This will happen again with `#v119` eventually...

**Comment by titanous** [comment]
@dzuelke Why do the URLs break? We reference consistent versions of the buildpacks in our build process so that we have repeatable (and soon reproducible builds).

**Comment by dzuelke** [comment]
The buildpack and the S3 bucket the buildpack loads its stuff from are two different things.

You can always host your own repository if you want stability, or you always pull in the latest version of the buildpack.

**Comment by titanous** [comment]
@dzuelke By "repository" do you mean S3 bucket?

**Comment by dzuelke** [comment]
Yeah, basically. It pulls bootstrapping stuff directly off S3, and uses a Composer repository for platform installs.

**Comment by dzuelke** [comment]
Also, if you want to fetch the latest version(s) of Heroku's official buildpacks that are guaranteed to work, instead of some pinned revision or tag or master from Git, which may not, you can find all the links at https://buildkits.heroku.com
