### ISSUE TITLE
"unexpected status downloading .. 404" when exporting an app

### ISSUE THREAD

**Issue by kochjoel** [flynn/flynn#3936]
```
$ flynn -c stage -a app export --file=app.tar
19.28 KB 5.24 KB/s 3s
unexpected status downloading bc7c3e91b2bf01f13e7af3bda4c95f58004564fa42c062809c767edb3e53fa69.layer: 404
```

Sending logs.

**Comment by lmars** [comment]
@kochjoel have you deleted any apps in this cluster? I can see the image getting deleted in the logs as the result of an app being deleted, so there may be a bug if the image was in use by other apps too.
