### ISSUE TITLE
Allow HTTP Clients to Define X-Request-ID header

### ISSUE THREAD

**Issue by sleighter** [flynn/flynn#3939]
Heroku supports client-defined X-Request-ID headers, but the flynn HTTP router always assigns a random UUID. The Flynn router should use an existing value for X-Request-ID, if one exists. 

Relevant code: https://github.com/flynn/flynn/blob/master/router/http.go#L598

**Comment by titanous** [comment]
Currently we overwrite the client-provided header because it allows injection of arbitrary client-controlled values. Would it make more sense to use a different header in the client and then choose if you want to use it in your app?

**Comment by sleighter** [comment]
Our use case exposes a Flynn-hosted service internally. The Request-ID is being provided by another service (which may receive it from another upstream service or from a mobile app) and it's important that we maintain the same Request-ID header throughout the entire request pipeline so we can coordinate logs.

My first thought was also to say that clients shouldn't be permitted to define that value, but after reading Heroku's documentation (https://devcenter.heroku.com/articles/http-request-id) and exploring our use case, it seems like it should be perfectly safe to allow clients to set that header.

**Comment by titanous** [comment]
Okay, I think if we implement the same limitations, it should be fine:

> The value must be between 20 and 200 characters, and consist of ASCII letters, digits, or the characters +, /, =, and -. Invalid IDs will be ignored and replaced with generated ones.
