### ISSUE TITLE
Flynn eating up the whole disk

### ISSUE THREAD

**Issue by pyr0hu** [flynn/flynn#3940]
Flynn seems to take up the whole disk space.

I tried to push a new deployment but got an error:
`The "https://lang-php.s3.amazonaws.com/dist-cedar-14-stable/php-7.1.2.tar.gz" file could not be written to /tmp/build/.heroku/php/vendor/composer/b603c438/83646a6665670083c482ef21907a262d.gz: Only 2076672 of 11592791 bytes written, possibly out of free disk space`

df -h shows the current list: [gist link](https://gist.github.com/pyr0hu/f7e02403060ea689e0a1cbe622b8c763)

Tried running `flynn-host volume gc` but still says the error.

Is there any method to clean up the host a little bit?

**Comment by lmars** [comment]
@pyr0hu did you previously have an older version of Flynn on this host?

**Comment by pyr0hu** [comment]
No, I havent upgraded the host, its the same as when it was installed. Should I try upgrading?

**Comment by lmars** [comment]
@pyr0hu ok there is no need to upgrade, but it seems you have some old style Flynn images mounted which indicates you previously had an older version of Flynn running on this host.

Are you sure there has only ever been one version of Flynn on this host?

**Comment by koolay** [comment]
Maybe the dashboard should show the usage of disk space?

**Comment by pyr0hu** [comment]
@lmars yes, I'm pretty sure. I can't deploy, nor change the configuration. (Config change only works if I set the workers to 0, make changes, then reset the workers)

**Comment by lmars** [comment]
@pyr0hu ok so there are some mounted filesystems which look like old style Flynn images, you should unmount and delete them all:

```
$ grep -oP '/var/lib/docker/aufs/mnt/tmp-\S+' /proc/mounts | xargs -L1 sudo umount
$ sudo rm -rf /var/lib/docker/aufs
```
