### ISSUE TITLE
Wrong ENV Parameters causing Flynn failure

### ISSUE THREAD

**Issue by sarbull** [flynn/flynn#3942]
When i try to deploy one of my node projects that contains `process.env.DATABASE_URL`, and on start it does a connection to that DB, the whole Flynn Dashboard modules crashes.

In order to solve this i had to do this workaround
```bash
$ git init # git clone
$ flynn create my-app
$ flynn set env DATABASE_URL=://test
$ git push flynn master
```

So my concern is that when you auth to github and try to deploy an app directly from github initially you dont have the DATABASE_URL and the app fails to deploy causing this big failure through the whole flynn system, the machine needs a sudo reboot in order to recover from the failure.

How do i preset the ENV variables on launching an app directly from github? Any thoughts on this?

**Comment by jvatic** [comment]
You have the option of setting ENV vars in the dashboard when launching from a github repo. You can also launch a database from that screen (which will set DATABASE_URL). Are these options not showing up?

**Comment by sarbull** [comment]
@jvatic i tried that, but somehow it doesn't send those ENV variables to the upcoming checkout from github and launch of the app, that's actually the issue.

Wrong ENV not setting -> checkout from git -> trying to start -> undefined needed ENV variables -> failure.

Thank you,
Cezar Sirbu

**Comment by jvatic** [comment]
I am unable to reproduce this issue. Please post the deploy log (and flynn-host debug logs if you can just in case it's a deeper issue).
