### ISSUE TITLE
Vagrant box doesn't allow connections from the host system on OS X

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#3944]
Hi,
I cloned the commit b6d3f9d7d8a1d67ef9206b0a0c1bda44529938f7 and ran _vagrant up_. I entered the machine via _vagrant ssh_ and ran _make_. The build succeeded and I ran _script/bootstrap-flynn_. But afterwards, I couldn't reach the dashboard http://dashboard.1.localflynn.com. in the browser of the host system, I got a timeout. Also adding the local cluster didn't work:

> Error writing CA certificate: Get https://controller.1.localflynn.com/ca-cert: dial tcp 192.0.2.200:443:
> connect: no route to host

Versions:
- OS X: 10.12.3
- Flynn: b6d3f9d7d8a1d67ef9206b0a0c1bda44529938f7
- Vagrant: 1.9.1
- VirtualBox: 5.0.32 r112930

**Comment by lmars** [comment]
@philiplb yes this is due to using a loopback device for the network inside the VM [here](https://github.com/flynn/flynn/blob/master/script/start-flynn-host#L115-L117).

The change was made in 812480f due to the fact Ubuntu 16.04 no longer always has a predictable `eth0` device to create the IPs on (systemd renames it to something like `ensXX`) so it was easier to just use `lo` which always exists.

We need to switch `lo` for the `ensXX` device (probably looking up the name in the `/sys/class/net` directory).

Do you want to give that a go?

**Comment by AtheistOfFail** [comment]
`PERSONAL-MacBook-Pro:demo USER$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'flynn-base'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'flynn-base' is up to date...
==> default: Setting the name of the VM: demo_default_1488320402271_27366
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/flynn-host.service to /lib/systemd/system/flynn-host.service.
==> default: 22:20:23.487372 check online-hosts
==> default: 22:20:24.493817 require-env require-env
==> default: 22:20:24.493837 resource-check resource-check
==> default: 22:20:24.495594 run-app discoverd
==> default: 22:20:24.817714 run-app flannel
==> default: 22:20:25.004769 wait-hosts wait-hosts
==> default: 22:20:27.511941 gen-random pg-password
==> default: 22:20:27.512025 gen-random pg-password 06583f42a3b08593ac3ae078181d973c
==> default: 22:20:27.512031 run-app postgres
==> default: 22:20:28.282481 gen-random controller-key
==> default: 22:20:28.282546 gen-random controller-key dfa3ec655737a02cbc5986fbfd4e06ea
==> default: 22:20:28.282549 gen-random bootstrap-id
==> default: 22:20:28.282568 gen-random bootstrap-id 46aba6ff-ff75-4de7-92eb-2cf6ab32cce5
==> default: 22:20:28.282569 gen-random dashboard-session-secret
==> default: 22:20:28.282591 gen-random dashboard-session-secret 1cffef003b3627445a7336eeaf1d1bf5
==> default: 22:20:28.282595 gen-random dashboard-login-token
==> default: 22:20:28.282603 gen-random dashboard-login-token 7f5dfbf8ffc5fa5ec3f31fb485b9b2c9
==> default: 22:20:28.282605 gen-random name-seed
==> default: 22:20:28.282613 gen-random name-seed 2c13a27a321bf4290dff
==> default: 22:20:28.282614 gen-random router-sticky-key
==> default: 22:20:28.282631 gen-random router-sticky-key FbVj6Q5W+NgykztBz6bbI+zK31sZTaiQ6NP0ydICFhk=
==> default: 22:20:28.282632 wait postgres-wait
==> default: 22:20:31.112125 gen-tls-cert controller-cert
==> default: 22:20:32.015436 gen-tls-cert controller-cert pin: L6VXfTPJZ9CSMtBbbBaBZRoo0NQhd0ldud/1JhE0uco=
==> default: 22:20:32.015456 run-app controller
==> default: 22:20:32.746062 wait controller-wait
==> default: 22:20:33.660801 add-app controller-inception
==> default: 22:20:33.751995 add-app postgres-app
==> default: 22:20:33.777351 add-app flannel-app
==> default: 22:20:33.817472 add-app discoverd-app
==> default: 22:20:33.845620 scale-app scheduler-scale
==> default: 22:20:33.860418 run-app scheduler
==> default: 22:20:34.109017 create-artifact slugbuilder-image
==> default: 22:20:34.114063 create-artifact slugrunner-image
==> default: 22:20:34.121303 create-artifact redis-image
==> default: 22:20:34.129490 deploy-app redis
==> default: 22:20:34.188192 add-provider add-redis-provider
==> default: 22:20:34.195457 gen-random mariadb-password
==> default: 22:20:34.195490 gen-random mariadb-password 17fefb8b7f5dcc18d1ef32843d3de4c0
==> default: 22:20:34.195492 deploy-app mariadb
==> default: 22:20:34.249036 add-provider add-mysql-provider
==> default: 22:20:34.252601 gen-random mongodb-password
==> default: 22:20:34.252724 gen-random mongodb-password 24e4be82e133669a017217cf3d8a42ee
==> default: 22:20:34.252731 deploy-app mongodb
==> default: 22:20:34.336830 add-provider add-mongodb-provider
==> default: 22:20:34.346736 deploy-app blobstore
==> default: 22:20:34.990089 deploy-app router
==> default: 22:20:36.187029 deploy-app gitreceive
==> default: 22:20:36.386856 gen-random docker-receive-secret
==> default: 22:20:36.386890 gen-random docker-receive-secret dc1d4eee7f2a72cd0b01f271755833d3
==> default: 22:20:36.386893 deploy-app docker-receive
==> default: 22:20:36.505882 wait router-wait
==> default: 22:20:37.419994 add-route gitreceive-route
==> default: 22:20:37.434924 add-route docker-receive-route
==> default: 22:20:37.443477 add-route controller-route
==> default: 22:20:37.484177 wait controller-route-wait
==> default: 22:20:37.989277 deploy-app logaggregator
==> default: 22:20:38.069909 deploy-app taffy
==> default: 22:20:38.118452 gen-random status-key
==> default: 22:20:38.118564 gen-random status-key 0ff19ab0f1084fcc1c2b18a8df543f55
==> default: 22:20:38.118568 deploy-app dashboard
==> default: 22:20:38.226342 add-route dashboard-route
==> default: 22:20:38.250570 deploy-app status
==> default: 22:20:38.318296 add-route status-route
==> default: 22:20:38.340233 wait redis-wait
==> default: 22:20:38.344343 wait mariadb-wait
==> default: 22:20:38.358856 wait mongodb-wait
==> default: 22:20:38.371320 wait blobstore-wait
==> default: 22:20:38.387817 wait gitreceive-wait
==> default: 22:20:38.388546 wait docker-receive-wait
==> default: 22:20:38.395347 status-check status-check
==> default: 22:20:39.234207 status-check status-check all services healthy
==> default: 22:20:39.234219 cluster-monitor cluster-monitor
==> default: 22:20:39.243330 log log-complete
==> default: 22:20:39.243502 log log-complete 
==> default: 
==> default: Flynn bootstrapping complete. Install the Flynn CLI (see https://flynn.io/docs/cli for instructions) and paste the line below into a terminal window:
==> default: 
==> default: flynn cluster add -p L6VXfTPJZ9CSMtBbbBaBZRoo0NQhd0ldud/1JhE0uco= default demo.localflynn.com dfa3ec655737a02cbc5986fbfd4e06ea
==> default: 
==> default: The built-in dashboard can be accessed at http://dashboard.demo.localflynn.com and your login token is 7f5dfbf8ffc5fa5ec3f31fb485b9b2c9
PERSONAL-MacBook-Pro:demo USER$ flynn cluster add -p L6VXfTPJZ9CSMtBbbBaBZRoo0NQhd0ldud/1JhE0uco= default demo.localflynn.com dfa3ec655737a02cbc5986fbfd4e06ea
Error writing CA certificate: Get https://controller.demo.localflynn.com/ca-cert: dial tcp 192.0.2.200:443: i/o timeout`

This also appears when spinning up a machine using vagrant up and then adding the cluster to flynn. Right now, it's no longer possible to use vagrant on OSX to try flynn.

**Comment by philiplb** [comment]
@lmars 
Thanks. I just replaced "lo" there with "enp0s8" having the IP 192.0.2.100 and ran the bootstrap-script. But I can't reach http://dashboard.1.localflynn.com.
Tried again with enp0s3 (10.0.2.15) and no luck.
Anything else I'm missing?

**Comment by titanous** [comment]
@philiplb It should work if you replace it with `enp0s8`, you may have to reboot the VM.

**Comment by philiplb** [comment]
@titanous Rebooting the vm did the trick, thank you. :)
