### ISSUE TITLE
Multiple routers (for multiple ssl certificates)

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#3945]
Hey guys! 

We just started with Flynn and really loving it so far! 
One question with regard to ssl certificates. Is it possible to have multiple? 
Adding one is a breeze! We are not sure though how to add another ssl certificate.

**Comment by lmars** [comment]
@heldopslippers TLS certificates are per route, so you can use multiple TLS certificates by adding different routes.

For example, if your app is called `MYAPP` and it has a web process, you can add a route with a custom certificate with:

```
$ flynn route add http --service "MYAPP-web" --tls-cert path/to/tls-cert.pem --tls-key path/to/tls-key.pem myapp.some-domain.org
```
