### ISSUE TITLE
Add an ability to stream binarylogs from database appliances to a new cluster

### ISSUE THREAD

**Issue by onnimonni** [flynn/flynn#3958]
When doing backup/restore update and waiting for the dns propagation some requests will come to the old cluster. It would be fantastic to have a easy command which could be used to stream the writes from the old cluster databases to the new cluster databases.

Currently we do the backup/restore update in silent hours and create a sql dump of the changes from the binarylogs which can be used in the new cluster.

I'm most concerned about the mariadb but I would think this is useful for other appliances as well.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
