### ISSUE TITLE
'flynn CMD help' produces shorter help than 'flynn help CMD' or 'flynn CMD -h'

### ISSUE THREAD

**Issue by simonamor** [flynn/flynn#3960]
Compare the output from the following commands:
 flynn help route
 flynn route -h
 flynn route help

14:08:33   lmars | well, it is a bug in how `flynn CMD help' works
14:08:43   lmars | each command has full usage
14:08:59   lmars | so it should always print that rather than the stripped down version
14:09:57   lmars | I think that is actually handled by the docopt library
14:10:21   lmars | 'flynn help CMD' should work as expected

**Comment by titanous** [comment]
This is expected, `flynn foo help` is not a valid command.
