### ISSUE TITLE
Restore mongodb Dump > 97mb

### ISSUE THREAD

**Issue by wasi** [flynn/flynn#3962]
Hi,

the volume for the restore Job is limited to 97mb. So when I try to restore a dump > 97 mb I get out of disk error:

```
tar: xxx.metadata.json: Cannot write: No space left on device
```

volume from df -h:
```
/dev/zd640                                                97M   97M  1.0K 100% /var/lib/flynn/volumes/zfs/mnt/ext2/flynn1-b4ae79d1-1e6b-45c5-9c70-d2233d65c6c4
```

Is there a possibility to increase the volume size? I would not want to open access to mongodb and use mongorestore, but that would be a possibility.

**Comment by kwando** [comment]
Flynn has a default limit of 100MB in containers. See this comment:
https://github.com/flynn/flynn/issues/3863#issuecomment-274298690

**Comment by wasi** [comment]
Thanks @kwando 
Its working with increased slug builder.

**Comment by wasi** [comment]
actually the mongodb restore command seams to not use the slugbuilder size:
```
$ flynn limit
worker:       cpu=1000  max_fd=10000  memory=1GB  temp_disk=100MB
console:      cpu=1000  max_fd=10000  memory=1GB  temp_disk=100MB
rake:         cpu=1000  max_fd=10000  memory=1GB  temp_disk=100MB
slugbuilder:  cpu=1000  max_fd=10000  memory=1GB  temp_disk=250MB
web:          cpu=1000  max_fd=10000  memory=1GB  temp_disk=100MB

$ df -h
/dev/zd816                                                97M  7.5M   90M   8% /var/lib/flynn/volumes/zfs/mnt/ext2/flynn1-f8e2d3b5-73d9-43a9-9a10-18e2c49426f
```

Maybe another job type is used to restore the db?

**Comment by josephglanville** [comment]
The proper solution to this is to re-use the data volume for one-off job support to attach a data volume to stream the backup to.
