### ISSUE TITLE
Adding git remote to applications using controller API

### ISSUE THREAD

**Issue by jacobbednarz** [flynn/flynn#3964]
I'm trying to automate the process of application creation via another service (outside of flynn) using the controller API. Unfortunately, I can't quite seem to find where and how you can associate a remote with an application. For example, I'd like to setup the following:

`application1` -> `https://github.com/org/repo1.git` (public)
`application2` -> `https://token@github.com/org/repo2.git` (private)

Would you be able point me to some documentation as to how this is possible? Or whether I have missed something here?

**Comment by titanous** [comment]
Are asking about how the dashboard associates GitHub repos with Flynn apps?

**Comment by jacobbednarz** [comment]
No sorry. I'm probably not being clear enough here. In essence I want to create an application using the controller API and define a remote (the equivalent of `flynn create -r https://github.com/org/repo1.git sample-app`).

The reasoning behind this is that each application needs to use it's own token and not be owned by the same person.

**Comment by lmars** [comment]
@jacobbednarz I think you may be misunderstanding the `--remote` flag of `flynn create`.

When you run `flynn create --remote <remote>`, what happens is that the CLI creates an app using the controller API, and then on your local machine runs:

```
$ git remote add <remote> https://git.<cluster-domain>/<appname>.git
```

This then allows you to run `git push <remote> master` to push your local master branch to the Flynn `gitreceive` app, which then deploys your application.

There is no integration with GitHub at this level, and there is no way to associate an app with a remote git repository via the controller API (although you can deploy my [webhook deploy app](https://github.com/lmars/flynn-webhook-deploy) to deploy your app using a GitHub webhook).

**Comment by jacobbednarz** [comment]
Ah thanks @lmars. I presumed that if you gave it a different URL, you would be able to use it to build artifacts for deployments. 

Thanks for the link - I'll check out that application for achieving this instead.
