### ISSUE TITLE
flynn install on 0.0.0.0

### ISSUE THREAD

**Issue by Kentoseth** [flynn/flynn#3970]
I am running the flynn-cli and need to bind the web-installer to 0.0.0.0 instead of `localhost`.

The cli only allows:

`flynn install`

and nothing like:

`flynn install -h 0.0.0.0`

What do I need to change/adjust to make this happen?

**Comment by Kentoseth** [comment]
I think I found the file:

 [flynn/installer/http.go](https://github.com/flynn/flynn/blob/a628b8fd0eb3a88496cb9dc34588508a8d453534/installer/http.go)

Can this be updated to support binding to 0.0.0.0 ?

**Comment by lmars** [comment]
@Kentoseth although the output of `flynn install` includes `http://localhost`, the installer does in fact bind to `0.0.0.0` as desired.
