### ISSUE TITLE
Flynn ate all diskspace

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#3972]
Something happened to my single flynn-node yesterday. It decided to chew up all available diskspace..

![skarmavbild 2017-03-06 kl 13 45 04](https://cloud.githubusercontent.com/assets/891566/23610532/263ce96e-0273-11e7-8bc9-fd0ce48b54e1.png)

https://izzy.merciless.me/kwando/debug-logs-5510b24918b334ad4890fb20da7115efc9654b9135325ca537b16b2223379b3f1442fca5f8018f21.tar

**Comment by kwando** [comment]
Seems like a large portion of diskspace is used by mongodb.
```/var/lib/flynn/volumes/zfs/mnt/data/05ec5bbe-a96b-4692-9251-f85ec4a85354``` uses 59GB data..


```
root@flynn-node1:/var/lib/flynn/volumes/zfs/mnt/data# du -sh * 2> /dev/null
2.5K    04560419-d552-461c-bf6d-372b738f9c52
59G     05ec5bbe-a96b-4692-9251-f85ec4a85354
131K    17ebc3dc-3fbc-4f3d-b3ff-416ac62f5e3c
512     21d64a1c-3222-476a-96ef-62c3710066ee
11K     393827d9-35de-4bfa-adfc-7eef0f2540e0
110M    94bd03d7-1b71-422a-9bb2-f5c96915880e
4.9G    97b5ac31-a5cf-405f-b2d8-b6320c230709
2.5K    e2f86a37-ae61-4a55-bae1-ac08ca3379c7
root@flynn-node1:/var/lib/flynn/volumes/zfs/mnt/data# cd 05ec5bbe-a96b-4692-9251-f85ec4a85354
root@flynn-node1:/var/lib/flynn/volumes/zfs/mnt/data/05ec5bbe-a96b-4692-9251-f85ec4a85354# du -sh * 2> /dev/null
17K     collection-0--176926832963943288.wt
17K     collection-0-3791739043208152943.wt
37K     collection-0--4570663118354696780.wt
33K     collection-2--176926832963943288.wt
37K     collection-2-3791739043208152943.wt
17K     collection-3-3791739043208152943.wt
17K     collection-5-3791739043208152943.wt
35M     diagnostic.data
17K     index-1--176926832963943288.wt
17K     index-1-3791739043208152943.wt
37K     index-1--4570663118354696780.wt
17K     index-3--176926832963943288.wt
17K     index-4--176926832963943288.wt
17K     index-4-3791739043208152943.wt
17K     index-6-3791739043208152943.wt
1.0K    instance_id
221M    journal
1.0K    Keyfile
37K     _mdb_catalog.wt
1.0K    mongod.conf
1.0K    mongod.lock
37K     sizeStorer.wt
1.0K    storage.bson
1.0K    WiredTiger
59G     WiredTigerLAS.wt
1.0K    WiredTiger.lock
1.5K    WiredTiger.turtle
81K     WiredTiger.wt
```

I'm not using mongodb in this cluster, can I reclaim this space somehow?

**Comment by titanous** [comment]
This sounds like #3613.

**Comment by titanous** [comment]
If you don't use mongodb you can run `flynn -a mongodb scale mongodb=0` and then `flynn-host volume gc` to clean this up.

**Comment by kwando** [comment]
Thanks for this information. I ended up rebuilding my flynn node from a nightly backup. I've scaled down mongodb and run ```flynn-host volume gc``` on the fresh node.

**Comment by titanous** [comment]
I'm closing as a duplicate, thanks for letting us know that this issue still exists.
