### ISSUE TITLE
dashboard env management tweaks

### ISSUE THREAD

**Issue by WriteCodeEveryday** [flynn/flynn#3975]
I wish I had the JSX knowledge to make this change myself but I don't.

Here's what this issue is about.

If you want to migrate from a competing host (say Heroku) and you use the "heroku config --app app_name", you'll get a K-V pair of your env tokens. Being able to copy and paste these into the ENV panel in the flynn dashboard would be a godsend for quick migrations.

The data looks like this.

> ENV_KEY_ONE : ENV_DATA
> ENV_KEY_TWO : ENV_DATA2

What I'm asking for is simply to monitor the first field in the ENV panel, just like we do now, but if there's a string with some "\n" line terminators dropped in, the line should be split by new lines (one key per line) and split by ":" so you end up with a key:value pair and just dropped into the ENV panel. This would make migrations from Heroku to Flynn as simply as spinning up a cluster, creating the app, adding the env variables and using the existing Github integration.

**Comment by lmars** [comment]
Flynn should probably have a single command to migrate apps from Heroku, but in the meantime you can do something like this:

```
$ flynn -a APPNAME env set "$(sed -e 's/ : /=/g' heroku.env)"
```

**Comment by titanous** [comment]
This should work:

```text
flynn env set $(heroku config:get --shell)
```
