### ISSUE TITLE
Pushing to Flynn remote gives HTTPS error

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#3981]
When I attempt to push my repo to Flynn, I receive the following error:

```
fatal: unable to access 'https://git.<cluster>/<app>.git/': Peer's certificate has an invalid signature.
```

I have the following in my `~/.gitconfig`:

```
[http "https://git.<cluster>"]
	sslCAInfo = /home/thomasfedb/.flynn/ca-certs/default.pem
[credential "https://git.<cluster>"]
	helper = /home/thomasfedb/.bin/flynn git-credentials
```

This is using Git 2.9.3 on Fedora 26 and using Flynn CLI v20170217.0

**Comment by titanous** [comment]
What is the full output of `curl --version`?

**Comment by titanous** [comment]
Is this error a new development? Any idea what changed?

**Comment by thomasfedb** [comment]
```
curl 7.51.0 (x86_64-redhat-linux-gnu) libcurl/7.51.0 NSS/3.27 zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.11) libssh2/1.8.0 nghttp2/1.13.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink PSL 
```

**Comment by thomasfedb** [comment]
Seemed to occur without any cause. Cluster is also quite young, so I doubt the cert expired.

**Comment by titanous** [comment]
Looks like curl is using NSS (instead of OpenSSL), and NSS is pretty strict about certificate validation, I'll track down what it is complaining about.

**Comment by thomasfedb** [comment]
Thanks @titanous, much appreciated.

**Comment by thomasfedb** [comment]
@titanous do you think a fix is going to land anytime soon?

**Comment by titanous** [comment]
I haven't had time to look at this yet, but I'm planning to this week. In the mean time it should work with curl that is compiled against OpenSSL.

**Comment by thomasfedb** [comment]
@titanous has this been resolved?

**Comment by ottuzzi** [comment]
Hi,

same problem here:
`$ git push flynn master
fatal: unable to access 'https://git.testflynn.brucalipto.org/example.git/': SSL                                                                                                     certificate problem: unable to get local issuer certificate
`
but curl is compiled with OpenSSL
`$ curl --version
curl 7.53.1 (x86_64-pc-msys) libcurl/7.53.1 OpenSSL/1.0.2k zlib/1.2.11 libssh2/1.7.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy Metalink
`
I'm playing on Windows10 with MSYS2 environment.

**Comment by thomasfedb** [comment]
Did this get fixed @titanous @lmars?

**Comment by titanous** [comment]
@thomasfedb Unfortunately I haven't had a chance to look into this yet and it's been low priority due to the apparently limited impact of the issue.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
