### ISSUE TITLE
Process fails to scale up from zero instances

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#3983]
```
$ flynn -c qa-us-east-1 -a qa-bvjs-apps-scoutfile scale
dimsum=0 web=1

$flynn -c qa-us-east-1 -a qa-bvjs-apps-scoutfile scale dimsum=1
requested scale equals current scale, nothing to do!

$ flynn -c qa-us-east-1 -a qa-bvjs-apps-scoutfile scale
dimsum=0 web=1
```

That's probably not supposed to happen. Nothing obviously wrong with the Procfile.

**Comment by temujin9** [comment]
From one of the bug reporters: "one of these scale commands seemed to have taken it from zero to non-zero, because the service did some work".

Debug info coming shortly.

**Comment by temujin9** [comment]
debug-info: https://bazaarvoice.box.com/s/zpjay1lt95xjomiqcv74zivqco4vfovo

**Comment by j105** [comment]
@temujin9 restore to previous flynn cli will fix this issue.

**Comment by lmars** [comment]
@temujin9 what version of the CLI were you using here?

We recently merged some changes related to scaling which made it into nightly version `v20170309.0`, and I see you cluster version is `v20170308.0` so we may well have some compatibility issues here.

**Comment by temujin9** [comment]
I have an evergreen mechanism in place, so the CLI was at whichever version
was current the day that ticket was opened.

Cheers,


Nathaniel Eliot
