### ISSUE TITLE
Cluster Refusing :80 on 2 of 6 nodes

### ISSUE THREAD

**Issue by thomasfedb** [flynn/flynn#3984]
I have a cluster with 6 nodes, which is refusing connections on port 80 on 2 nodes. Networking and firewall settings were configured identically on all nodes, and look the same on inspection.

I currently have a web app deployed to the cluster, scaled to 6 web processes, which have ended up on 4 different nodes. My hypothesis is that nodes that are not running a web process are refusing connections.

I notice that these two notes are also not running `flynn-router`.

How best to fix this one? Any idea how we arrived at this state?

**Comment by lmars** [comment]
@thomasfedb the router is the process which accepts connections on host port 80 so it not running would explain this behaviour.

Check `flynn -a router log` and `flynn -a router ps --all` to see if the router is crashing for any reason (for example there may be other processes already listening on the ports it is trying to bind to, namely 80, 443 and 3000-3500).

**Comment by thomasfedb** [comment]
Hey @lmars,

Logs don't show any errors that are causing the router to crash or fail to bind. `ps --all` reveals one running process and one process 'down'.

**Comment by thomasfedb** [comment]
Turns out my cluster had some nodes with identical hostnames, with Flynn wasn't very happy about. Rebuilt it with new nodes with unique hostnames and everything seems to be working fine now.

**Comment by lmars** [comment]
@thomasfedb glad we got to the bottom of it, I'll close this.

**Comment by mikejarema** [comment]
I faced this particular issue as well when following the [Installation Guide](https://flynn.io/docs/installation/manual) for a cluster of 3 nodes on Linode. After 3 failed attempts from scratch, each time the flynn-router ran only on a single node, I followed @thomasfedb's advice above and gave each host a unique hostname.

Here's the snippet from my server bootstrapping script which applies the unique hostname:
````
# Give this machine a unique hostname (as per https://askubuntu.com/a/87687/400948)
export CUSTOM_HOSTNAME=server1 # <-- must differ per server instance, eg. server2, server3 ...
hostname $CUSTOM_HOSTNAME
echo $CUSTOM_HOSTNAME > /etc/hostname
sed -i "s/.*127\.0\.1\.1.*/127.0.1.1 ${CUSTOM_HOSTNAME}/" /etc/hosts
````
