### ISSUE TITLE
Setup via CLI/web-dashboard fails for git config

### ISSUE THREAD

**Issue by Kentoseth** [flynn/flynn#3988]
From this issue here: #3742 

I was instructed to open a new issue here.

I was facing a similar issue regarding: `git push flynn master` where it was asking me for a username/password.

I then took a look at the flynn CLI logs and found this issue:

```
INFO[03-13|00:53:55] Event: log: WARNING: Failed to configure CLI: error "exec: \"git\": executable file not found in $PATH" running "git config --global http.https://git.someurl.com.sslCAInfo /home/user/.flynn/ca-certs/flynn-14909098098.pem": ""
```

This issue occurred during the setup of a cluster via the web dashboard (ie. after running `flynn install` and going through the setup procedures)

Please indicate if I can run the `git config ...` command locally or do I need to re-install the cluster?

Steps to reproduce:

 1) Running flynn-CLI in LXC-container (Ubuntu 14.04)
 2) `flynn install` and see web-dashboard via [IP]:[PORT]
 3) Setup flynn cluster on Ubuntu 16.04 server via SSH option

**Comment by lmars** [comment]
@Kentoseth ssh to your server, run `flynn-host cli-add-command`, copy the `flynn cluster add ...` command and run it on your local machine.

**Comment by lmars** [comment]
P.S. the reason this doesn't "just work" for you is because you are running `flynn install` in a container, so it is trying to configure the container to push to the cluster (and failing because the container doesn't have `git`).

You should consider running `flynn install` directly on the machine you want to use to `git push`.

**Comment by Kentoseth** [comment]
@lmars that is odd, because I specifically set the container up with git installed as well.

I will attempt removing the cluster and re-installing it to see the outcome.
