### ISSUE TITLE
test: Run tests against current stable as well as master

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#3993]
We currently have quite a comprehensive suite of integrations tests, but they all test against a cluster running the code being pushed, so do not catch issues like #3992 where the nightly CLI was unable to scale apps in stable clusters.

The CI runner currently boots a cluster then runs the tests against that cluster, we should update this so that it boots both a cluster using the code being pushed and a stable cluster, then performs a test run against each.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
