### ISSUE TITLE
create from docker

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#3996]
we could use
`docker pull wordpress
`
to create a new worpdress installation.  Why not also with flynn like
`flynn create --docker wordpress
`
or similar to do that.

What would be the actual way for getting the expected result?
Thanks

**Comment by lmars** [comment]
You can deploy Docker images to Flynn my following [these instructions](https://flynn.io/docs/docker), so for example:

```
$ flynn create --remote "" wordpress
$ flynn -a wordpress docker push wordpress
$ flynn -a wordpress scale app=1
```

You may of course want to [provision a database](https://flynn.io/docs/databases/mysql#adding-a-database-to-an-app).
