### ISSUE TITLE
in-place update fails from v20170116.0p2 to v20170217.0

### ISSUE THREAD

**Issue by n0daft** [flynn/flynn#4002]
I was trying to update a 3 node cluster from v20170116.0p2 to v20170217.0 by executing `flynn-host update` on the leader node.

The update failed at starting deploy the system app.

```
INFO[03-20|12:38:32] pulling binaries and config              host=srvflynn2
INFO[03-20|12:38:32] pulling binaries and config              host=srvflynn1
INFO[03-20|12:38:32] pulling binaries and config              host=srvflynn3
INFO[03-20|12:38:41] binaries and config pulled successfully  host=srvflynn1
INFO[03-20|12:38:41] binaries and config pulled successfully  host=srvflynn2
INFO[03-20|12:38:41] binaries and config pulled successfully  host=srvflynn3
INFO[03-20|12:38:41] validating binaries 
INFO[03-20|12:38:41] updating flynn-host daemon on all hosts 
INFO[03-20|12:38:42] flynn-host updated successfully          host=srvflynn2
INFO[03-20|12:38:42] flynn-host updated successfully          host=srvflynn3
INFO[03-20|12:38:47] flynn-host updated successfully          host=srvflynn1
INFO[03-20|11:38:48] validating images 
INFO[03-20|11:38:48] creating new image artifacts 
INFO[03-20|11:38:48] starting deploy of system app            name=discoverd
EROR[03-20|11:40:52] error deploying app                      name=discoverd err="timed out waiting for discoverd deployment (expected=3 actual=0)"
12:40:52.743201 host.go:164: exec: job exited with status 1
```

After the failed update a `flynn-host version` shows `v20170217.0` while status page on web interface shows `v20170116.0p2`.

`flynn-host list`results in

```
host.go:164: Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused
```

`flynn-host fix --min-hosts=3` as well as `flynn-host fix --min-hosts=3 --peer-ips=[IPs of nodes]`
result in

```
unable to list hosts from discoverd, falling back to peer IP list error="Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused
```

I've then stopped and restarted flynn-host with `sudo service flynn-host stop/start` on each of the nodes. But this didn't help. `flynn-host list` still doesn't work.

I'm actually not sure in which state the cluster is right now as the deployed apps still work, but the update didn't really succeed.

**Comment by lmars** [comment]
@n0daft we are aware that the in-place update isn't as reliable as it should be, for now we recommend doing a backup/restore (see [here](https://flynn.io/docs/production#updating)).

We still would like to know what went wrong, so please run `sudo flynn-host collect-debug-info` and post the resulting gist. If that fails, create a tarball of `/var/log/flynn` and send it to logs@flynn.io.

**Comment by n0daft** [comment]
I know, but I thought I'd give it a try. I've sent you the debug info.

**Comment by n0daft** [comment]
Closing this as the update procedure clearly aims for backup/restore which has proven itself to work.
