### ISSUE TITLE
Linode install failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by randy-girard** [flynn/flynn#4003]
Trying to run the installer over SSH on a linode server using:

Ubuntu 16.04
Kernel: 4.9.7-x86_64-linode80

Running `curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn && sudo bash /tmp/install-flynn --clean` on X.X.X.X
modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.9.7-x86_64-linode80/modules.builtin.bin'
[1;31m===> 16:20:23.084 ERROR: OverlayFS is either missing or does not support multiple lower directories, consider upgrading your kernel to at least 3.19[0m

Not sure what this means or how to fix.

**Comment by lmars** [comment]
@randy-girard you will need to use a stock Ubuntu kernel rather than a Linode kernel (see the note on [this page](https://flynn.io/docs/installation/manual#manual-installation))
