### ISSUE TITLE
Cluster fails to start multiple important user services

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#4004]
I stood up a cluster, and it came up healthy, but then several user services (flynn-usage-example, portal-navigation-legacy, maybe others) failed to start. Thankfully, rolling back to the prior cluster resolved the immediate issue.

Debug info: https://bazaarvoice.box.com/s/1e9k3oxfo7osk2ej0l5e0pfl5xserf6c

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
