### ISSUE TITLE
site down - broadcasting down event

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#4005]
Does this indicate an issue? 

The reason I ask is I've had one of my sites going down twice now and I can see this in the error discoverd logs appearing around the time the issue started. And just before there's is the error

```
2017/03/21 22:26:00 [INFO] raft: Node at 139.162.180.77:1111 [Follower] entering Follower state (Leader: "")
2017/03/21 22:26:00 [ERR] raft-net: Failed to flush response: write tcp4 139.162.180.77:1111->139.162.165.60:34100: write: broken pipe
2017/03/21 22:26:01 [INFO] raft: Duplicate RequestVote for same term: 453
2017/03/21 22:26:01 [WARN] raft: Failed to get previous log: 6714 log not found (last: 6622)
```

**Comment by dottodot** [comment]
I've emailed you the logs to look at. This has happened twice now and both times while I've been in bed meaning the site was down for 8 hours leading to a significant lose of sales.

The other occurrence was on 2017/03/14 also around 22:00

**Comment by lmars** [comment]
@dottodot it looks like your nodes experience frequent network connectivity issues which lead to the discoverd leader marking all services as down because the clients are not configured with an appropriate timeout.

We have fixed this in #3955 which will be in the stable release this week.

**Comment by dottodot** [comment]
Ok thanks, do you know what day yet so that I can keep an eye out for it.

**Comment by dottodot** [comment]
Also are the network connectivity issues related to flynn or do I have another issue in that respect?

**Comment by lmars** [comment]
> do you know what day yet so that I can keep an eye out for it.

You can subscribe to the release mailing list to be notified about stable releases [here](https://flynn.io/docs/stability#release-mailing-list), although the stable release will most likely be today.

> are the network connectivity issues related to flynn or do I have another issue in that respect

They indicate an issue with the underlying network rather than within Flynn itself, although once the clients have a reasonable timeout there should be little impact from this level of unreliability.

**Comment by dottodot** [comment]
Sorry one last thing, apart from upgrading to the new release will there be anything I need to do settings wise?

**Comment by titanous** [comment]
No settings need to be changed.
