### ISSUE TITLE
Remove cluster at another machine

### ISSUE THREAD

**Issue by pfeodrippe** [flynn/flynn#4008]
Hi, how could I remove a cluster that was not created at this machine?

**Comment by titanous** [comment]
I'm not sure what the question is?

**Comment by jvatic** [comment]
I believe @pfeodrippe is asking how to remove a cluster created with `flynn install` from a machine other than the one on which it was run? In this case you could copy `~/.flynn/installer` to the machine you wish to delete the cluster from and run `flynn install` (the cluster will now be in the list with an icon to delete it).

**Comment by jvatic** [comment]
But it's probably going to be much easier for you to log into the provider console and delete it from there.

**Comment by pfeodrippe** [comment]
Yes, @jvatic is correct, sorry for the misunderstanding.
So if I don't have access to the previous machine, the best thing to do is to log at the host?

**Comment by titanous** [comment]
Yes.

**Comment by pfeodrippe** [comment]
@titanous Which command? Is there a ```flynn-host``` docs somewhere or only the cli help?

**Comment by titanous** [comment]
You would delete the provisioned hosts from your infrastructure provider's control panel or API, there is no flynn-host command for this.

**Comment by pfeodrippe** [comment]
@titanous I'm using AWS, I would have to delete all the resources manually? Flynn only create EC2 instances, right, no more resources?

**Comment by titanous** [comment]
On AWS you can delete the corresponding CloudFormation stack which will destroy all of the resources created.

**Comment by pfeodrippe** [comment]
@titanous Oh, ok. Thanks!!
