### ISSUE TITLE
Update cluster by restoring backup without automatic domain-migration

### ISSUE THREAD

**Issue by n0daft** [flynn/flynn#4009]
I noticed that when installing flynn via the web installer and specifying a cluster backup file the installer automatically creates a new domain and migrates from the old to the new.

Can this behavior be controlled? The old cluster had a custom domain which should stay the way it was. The aim is to update to new flynn versions with the least amount of work and time possible.

**Comment by n0daft** [comment]
I figured out a way. On the host of my single-node cluster I ran:

* `sudo bash /tmp/install-flynn --clean`
* started the flynn-host with `sudo systemctl start flynn-host`
* defined the cluster domain in a variable `CLUSTER_DOMAIN=cloud.demo.ch`
* manually bootstrapped with `flynn-host bootstrap --from-backup backup.tar`

Now I didn't had to worry about a new cluster domain being automatically created. Not sure if there no other way. To be able to configure the domain via web installer would be nice. 

For a three node cluster, I guess I would have to run `install-flynn --clean` on each of the nodes, right?

**Comment by titanous** [comment]
> Can this behavior be controlled?

Not currently, and the installer is basically in maintenance mode at this point so it's unlikely that this will be changed.

> For a three node cluster, I guess I would have to run `install-flynn --clean` on each of the nodes, right?

Yes.

**Comment by n0daft** [comment]
@titanous thank you for your answer, much appreciated.
