### ISSUE TITLE
Rails assets:precompile

### ISSUE THREAD

**Issue by Cryptophobia** [flynn/flynn#4010]
Hi Flynn Devs,

I am testing Flynn for production and I am trying to deploy a couple of Rails 4 apps. Bundler runs fine but when reaching the `rake assets:precompile` step everything seems to bomb out and I have no way to debug what is going on. The `rake assets:precompile` command works on the master branch before trying the deployment to flynn. Could this be a problem with Flynn or is it bundler/ruby buildpack issue?

```
 NoMethodError: undefined method `[]' for nil:NilClass
       /tmp/build/app/config/environments/production.rb:7:in `block in <top (required)>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:210:in `instance_eval'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:210:in `configure'
       /tmp/build/app/config/environments/production.rb:1:in `<top (required)>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:597:in `each'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:597:in `block in <class:Engine>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
       /tmp/build/app/config/environment.rb:5:in `<top (required)>'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
       /tmp/build/app/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
       !
       !     Precompiling assets failed.
       !
remote: ERROR: Build failed: exec: job exited with status 1
```

Any help would be greatly appreciated.

**Comment by lmars** [comment]
That stack trace is indicating an issue with the code on line 7 of `config/environments/production.rb` (it is calling `[]` on something which is `nil`).

What code do you have in that file?

**Comment by Cryptophobia** [comment]
Just some config for the Rails SMTP mailer. But the problem is I can't change it in the master branch.

Is it possible to deploy a branch other than `master` with flynn? Seems like flynn always takes whatever is latest in `master` on the git origin. Is that correct?

**Comment by lmars** [comment]
@Cryptophobia you always have to push to the remote `master` branch, but you can push any local branch or even an explicit commit:

```
$ git push flynn local-branch:master

$ git push flynn COMMIT:master
```

**Comment by Cryptophobia** [comment]
@lmars Thank you. I got passed the `assets:precompile` error but it is important to note that the changes have to be committed on the local branch.

Is this in the documentation? Couldn't find information in the docs on deploying a local-branch.

Also now I am getting redis errors when I try to the internally created redis address. When I provision an externally available redis it works fine but internally provisioned redis gives me the following errors:

```
SocketError: getaddrinfo: Name or service not known
/tmp/build/app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:229:in `getaddrinfo'
/tmp/build/app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:229:in `connect'
/tmp/build/app/vendor/bundle/ruby/2.3.0/gems/redis-3.3.3/lib/redis/connection/ruby.rb:313:in `connect'
```

**Comment by lmars** [comment]
@Cryptophobia for the Redis error, try the advice offered here: https://github.com/flynn/flynn/issues/4014#issuecomment-289428815.

**Comment by Cryptophobia** [comment]
Found one thing:

When provisioning redis in for internal it does not add the host `.discoverd` like it does when provisioning PostgreSQL.

**Comment by Cryptophobia** [comment]
@lmars Hi, so I have one of my applications running flawlessly and I am happy. 

However there is an another application that I am trying to deploy that uses PostgreSQL. I am encountering lots of errors when I try to restore the db from a dump file. 

I run this command to create the dump file on my local machine:
`pg_dump -c --format=custom --no-acl --no-owner app_development > app_development.dump`

When I restore with the command: `flynn pg restore -f app_development.dump` on the flynn app , I am getting lots of errors related to `Error from TOC..`

How can I run a clean database restore using the command: `flynn run pg_restore -c` with the `-c` option? 

Seems like when I do that command the container asks me to install dependencies such as postgresql-client...

**Comment by Cryptophobia** [comment]
@lmars , you can ignore the above. i had a few extensions that i enabled in postgresql to get past the above problem.

```
 hstore    | 1.3     | public     | data type for storing sets of (key, value) pairs
 plpgsql   | 1.0     | pg_catalog | PL/pgSQL procedural language
 uuid-ossp | 1.0     | public     | generate universally unique identifiers (UUIDs)
```

**Comment by lmars** [comment]
@Cryptophobia glad you got to the bottom of it, I will close this issue.
