### ISSUE TITLE
Migrated application has a stale route

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#4011]
I recently did a system-wide export / import pass. After it was done, an odd user complaint popped up:

```
flynn -c prod-us-east-1 -a feedcheck delete -y
Deleted feedcheck (removed 1 routes, deleted 1 releases, deprovisioned 0 resources)

[ . . . push happens inside orchestration . . . ]

panic: conflict: Duplicate route

Command [flynn -c prod-us-east-1 -a feedcheck route add http feedcheck.flynn-prod-us-east-1-internal.nexus.bazaarvoice.com] failed: exit status 1
```

Several rounds of debugging, including deleting and repushing from scratch, didn't resolve the issue.

I've collected https://bazaarvoice.box.com/s/4qpa1jwlkuobogj4i9o6tv7k1vmi9evw from the cluster. Ping here soon if you want further testing.

**Comment by temujin9** [comment]
(Apologies: the title was from before I found the source of the phantom instances elsewhere.)

**Comment by temujin9** [comment]
This problem persists across backup and restore with the application existing. I'm retrying now with a backup taken while the application was deleted, as well as trying to migrate away from it to a clean cluster.

**Comment by lmars** [comment]
@temujin9 where exactly are you seeing the error `panic: conflict: Duplicate route`? As output from running the CLI command? I am trying to figure out why you are getting `panic: ` (the CLI should never panic).

**Comment by temujin9** [comment]
The panic is from the surrounding code, sorry. The error is from the command which follows it.

**Comment by lmars** [comment]
Ok, so after deleting the app, do you create it again?

When you create an app, the controller automatically creates a route like `<app>.<cluster-domain>`, so are you perhaps creating that same route?

**Comment by temujin9** [comment]
Nope. Cluster domain lacks the `-internal` component that we added there.

**Comment by temujin9** [comment]
(And yes, we are recreating the application.)

**Comment by lmars** [comment]
After deleting the app, run the following to see what routes exist in the router database:

```
$ flynn -a router pg psql -- -c "SELECT parent_ref, service, domain FROM http_routes"
```

If you can see the problematic route in there, grab the app ID from `parent_ref` and check what app it is from `flynn apps`, and if it isn't there it may be a deleted app so check the database directly:

```
$ flynn -a controller pg psql -- -c "SELECT name, created_at, deleted_at FROM apps WHERE app_id = '$APPID'"
```

**Comment by temujin9** [comment]
```
$ flynn -c $BVFLYNN_ENDPOINT -a router pg psql -- -c "SELECT h.parent_ref, h.service, h.domain FROM http_routes AS h WHERE domain = 'feedcheck.flynn-prod-us-east-1-internal.nexus.bazaarvoice.com'"
                      parent_ref                      |    service    |                            domain                             
------------------------------------------------------+---------------+---------------------------------------------------------------
 controller/apps/5309a585-30da-48e2-9e5e-de1f1dbaef4a | feedcheck-web | feedcheck.flynn-prod-us-east-1-internal.nexus.bazaarvoice.com
 controller/apps/d36fe582-56b7-4fa7-84c4-cd2665ee49b5 | feedcheck-web | feedcheck.flynn-prod-us-east-1-internal.nexus.bazaarvoice.com
 controller/apps/d36fe582-56b7-4fa7-84c4-cd2665ee49b5 | feedcheck-web | feedcheck.flynn-prod-us-east-1-internal.nexus.bazaarvoice.com
(3 rows)

$ flynn -a controller pg psql -- -c "SELECT name, created_at, deleted_at FROM apps WHERE app_id = '5309a585-30da-48e2-9e5e-de1f1dbaef4a'"
 name | created_at | deleted_at                                                                                                                                                                                                                                        
------+------------+------------                                                                                                                                                                                                                                       
(0 rows)                                                                                                                                                                                                                                                               


$ flynn -a controller pg psql -- -c "SELECT name, created_at, deleted_at FROM apps WHERE app_id = 'd36fe582-56b7-4fa7-84c4-cd2665ee49b5'"
 name | created_at | deleted_at 
------+------------+------------
(0 rows)
```

**Comment by lmars** [comment]
So it is unclear how those routes have stuck around (perhaps a previous app deletion failed halfway through), but you can just delete them (some of them are probably already deleted):

```
$ flynn -a router pg psql -- -c "UPDATE http_routes SET deleted_at = now() WHERE parent_ref IN ('controller/apps/5309a585-30da-48e2-9e5e-de1f1dbaef4a', 'controller/apps/d36fe582-56b7-4fa7-84c4-cd2665ee49b5')"
```

**Comment by temujin9** [comment]
I'd like to know why, because this kind of failure endangers our ability to trust the import / export system.

**Comment by temujin9** [comment]
Possible additional thing, or possibly it's own thing:
```
Migrating feedcheck2 to flynn-prod-us-east-1-cluster-2017-03-24-17-46-39
Removing existing app feedcheck2 from flynn-prod-us-east-1-cluster-2017-03-24-17-46-39
Deleted feedcheck2 (removed 1 routes, deleted 0 releases, deprovisioned 0 resources)
7.81 KB 3.28 KB/s 2s                                                                                                                                                                                                                                                   unexpected status downloading 13673d9be4f32f8108139462720a0c07f79d4e6f8c3b11e33fcb3f912ad90451.layer: 404
missing layer in export: 13673d9be4f32f8108139462720a0c07f79d4e6f8c3b11e33fcb3f912ad90451
```

feedcheck2 is probably just a repush of feedcheck, so I feel this is probably related somehow.

**Comment by lmars** [comment]
> this kind of failure endangers our ability to trust the import / export system.

Perhaps I am confused, how is this related to import / export? I thought you were deleting and then recreating an app in the same cluster?

It may be better to talk synchronously in IRC.

**Comment by lmars** [comment]
After [a discussion in IRC](https://botbot.me/freenode/flynn/2017-03-25/?msg=82960668&page=1) we realised the route from the deleted app leaked due to the following sequence of events:

* app deletion started by user
* route deleted by worker
* app deletion timed out whilst deleting some releases
* app deletion retried by worker
* route recreated by user as part of push
* app deletion finished

This can be prevented by not allowing actions to be taken on an app when it is in the process of being deleted (an easy way to do that is mark it as deleted before doing all the cleanup).

I've addressed the "missing layer" issue in #4013.

**Comment by crawlik** [comment]
Similar effect with a staled route was observed after user did `-a APPNAME scale web=0` and `-a APPNAME delete' of a django app. 

User actions:

- `scale web=0` Django app was still accessible via http and generating logs
- `-a APPNAME delete' 
-  `create APPNAME`
- secondary route creation with `-a APPNAME route add http secondary_route` resulted with 
`conflict: Duplicate route`

**Comment by lmars** [comment]
@crawlik are you sure that the `flynn -a APP delete` step finished properly?

On success, it will output how many routes got removed so it would be interesting to see if that matches the number of routes the app has.

**Comment by crawlik** [comment]
@lmars i am not sure as it was not done by me.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
