### ISSUE TITLE
Git EndPoint Internal Server Error When restoring cluster from backup

### ISSUE THREAD

**Issue by cdesch** [flynn/flynn#4021]
```
cjsMBP15:healthcare_executive_partners cj$ flynn --version
v20170328.1

```
I restored a cluster from backup tarball after it had crashed. The cluster was running several applications and the restore process worked great. Everything is running fine, although I need to push an update to one of the new applications. When pushing via git, the old git remote on my local repo needed to be replaced with the new git endpoint.... thats fine.... afterward, when pushing to the git endpoint I get a `internal server` error: 
```

cjsMBP15:healthcare_executive_partners cj$ git remote -v
flynn   https://git.22e1.flynnhub.com/hepartners.git (fetch)
flynn   https://git.22e1.flynnhub.com/hepartners.git (push)
heroku  https://git.heroku.com/healthcarexecutivepartners.git (fetch)
heroku  https://git.heroku.com/healthcarexecutivepartners.git (push)
origin  ssh://git@git.cloud.kickinespresso.com:7999/hep/healthcare_executive_partners.git (fetch)
origin  ssh://git@git.cloud.kickinespresso.com:7999/hep/healthcare_executive_partners.git (push)
cjsMBP15:healthcare_executive_partners cj$ git push flynn master
remote: Internal server error
fatal: unable to access 'https://git.22e1.flynnhub.com/hepartners.git/': The requested URL returned error: 500

```

I added it back through `flynn remote add` command:

       cjsMBP15:healthcare_executive_partners cj$ flynn -a hepartners remote add

 I suppose there is something I need to do on the cluster side to make this work, but I'm not sure what. 

What is the process for reconnecting the local repo remotes to the restored cluster?

**Comment by titanous** [comment]
Is `22e1.flynnhub.com` the old cluster or the new one?

**Comment by cdesch** [comment]
new cluster

**Comment by titanous** [comment]
Okay, please run `sudo flynn-host collect-debug-info` on one of the servers and post the link to the logs here.

**Comment by cdesch** [comment]
Here is the debug : https://gist.github.com/anonymous/a321b1f0b2811ab36971cac464b21d25

**Comment by titanous** [comment]
It looks like you are using the S3 backend for the blobstore but the credentials are invalid. If you update the blobstore configuration to have valid credentials for access to the bucket that the previous cluster was using it should work.

**Comment by cdesch** [comment]
That was it. S3 Credentials were bad. I replaced the keys and tried it. It works. 

Quick question for you: When you are setting up the blob store with:

```
flynn -a blobstore env set BACKEND_S3MAIN="backend=s3 region=us-east-1 \
bucket=flynnblobstore access_key_id=$AWS_ACCESS_KEY_ID \
secret_access_key=$AWS_SECRET_ACCESS_KEY"

flynn -a blobstore env set DEFAULT_BACKEND=s3main
```

are you replacing `$AWS_ACCESS_KEY_ID` and `$AWS_SECRET_ACCESS_KEY` with the key or setting them as ENV variables? If you are setting them as ENV, where are you setting them? Is it part of the `flynn env` ? I thought that was supposed to be specific to apps --  Not a global ENV for the cluster.

**Comment by titanous** [comment]
@cdesch Those are just placeholders, if left intact and the credentials you wanted to use were in your local environment they would be interpolated by the shell and passed to the `flynn` command.

**Comment by cdesch** [comment]
Cool. Thanks @titanous . What user and `.profile` should I load those env variables on in Ubuntu so flynn has access to them? Should that be the `root` with `.bashrc` or `.profile`? Looking at the digital oceans standard deployment when provisioning through the `flynn install` looks like it should be on the `root` account.

Maybe that should be a feature request for the installation/provisioning in `flynn install` -- to set the blobstore parameters prior to building the cluster.

**Comment by lmars** [comment]
@cdesch the command to update the blobstore environment to have the correct credentials only needs to be run once on your local machine, you don't need to put anything in `.profile` or `.bashrc` on the servers.

If you find the `$AWS_...` variables confusing, you could just specify the credentials directly in the `flynn env set` command, for example:

```
flynn -a blobstore env set BACKEND_S3MAIN="backend=s3 \
  region=us-east-1 \
  bucket=flynnblobstore \
  access_key_id=AKIAIOSFODNN7EXAMPLE \
  secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
```

This is however not as secure as using shell variables because they could be added to your history file.
