### ISSUE TITLE
blobstore: minio backend crashes for large file uploads

### ISSUE THREAD

**Issue by fzerorubigd** [flynn/flynn#4025]
I use minio backend and every thing works fine except for when I need to get cache for build after expiring the link (10 minute here : https://github.com/flynn/flynn/blob/master/blobstore/backend/minio.go#L93) I get this error and then next time I try to push the repo, the cache is not there and the building process is started with clean cache.  

I use nightly build of flynn which support minio. is there any other information i must provide for this?

**Comment by lmars** [comment]
Where are you seeing the error? Can you paste the full output?

**Comment by lmars** [comment]
From our discussion in IRC, the blobstore is being killed during the cache upload as it runs out of memory, most likely due to the way the minio client is buffering the file upload.

Increasing the blobstore memory with `flynn -a blobstore limit set memory=2GB` is a temporary workaround.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
