### ISSUE TITLE
Where are default DNS records in Azure?

### ISSUE THREAD

**Issue by kvitajakub** [flynn/flynn#4029]
Hi,

I am trying to deploy Flynn on Azure and I managed to run the installer successfully. However I can't find the DNS records for the `xxxx.flynnhub.com`. Are DNS records in Azure deployment stored differently than in AWS? (Do you use your own resources for that?)

Do I need to worry about them when creating and deleting clusters? I don't want them to clutter the place.
I will migrate the domain to my own, but from what I understand that should not be a related problem/question.

Thank you.

**Comment by lmars** [comment]
@kvitajakub 

> I can't find the DNS records for the xxxx.flynnhub.com

The `flynnhub.com` domain is controlled by Flynn and we expose a simple service for creating subdomains pointing at your cluster, which allows users to install Flynn and try it out without needing to set up their own DNS records.

> Do I need to worry about them when creating and deleting clusters? I don't want them to clutter the place.

No need to worry about cleaning up the `flynnhub.com` subdomains.

> I will migrate the domain to my own, but from what I understand that should not be a related problem/question.

You can migrate to your own domain by running `flynn cluster migrate-domain my-domain.com` (making sure `*.my-domain.com` points at your Flynn cluster).
