### ISSUE TITLE
flynn route app to install certificate

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4030]
I would like to have my app itself to install and update the certificate.  So how can this be done?

I found two ways:

1) install flynn in the app and use it with a script
2) use the controller api

but in both cases my app gets to many access rights (to other apps too), but I just want it to install the private key and the certificate, so I think this is too many access for the app.

any hints/ideas?

Thanks

**Comment by titanous** [comment]
We don't currently have granular permissions for the API, but will be implementing them as a part of #410, which will allow you to do this without exposing additional capabilities to the app.
