### ISSUE TITLE
Strange IP address appearing in flynn cluster add

### ISSUE THREAD

**Issue by andyjeffries** [flynn/flynn#4034]
I'm trying to run (I've tried to remove IDs and my real domain name in the below in case they are sensitive):

```
flynn cluster add -p {SOME_LONG_ID}+{SOME_SHORT_ID}= default flynn.example.com {SOME_LONG_ID}
```

The output I get is:

```
Error writing CA certificate: Get https://controller.flynn.example.com/ca-cert: dial tcp: lookup controller.flynn.example.com on 192.168.0.1:53: no such host
```

The funny thing is I don't know where it's getting 192.168.0.1 from? The servers have internal IPs of 10.0.0.69, 10.0.0.70 and 10.0.0.71 and public floating IPs that are NATed to them by OpenStack.

My local machine is on a 192.168.x.x network, so it may be that, but if I dig from my local machine:

```
dig -tany controller.flynn.example.com @192.168.0.1
;; QUESTION SECTION:
;controller.flynn.example.com.	IN	ANY

;; ANSWER SECTION:
controller.flynn.example.com. 600	IN	CNAME	flynn.example.com.
```

Can anyone shed some light on why this is going wrong and how to fix it?

**Comment by titanous** [comment]
192.168.0.1 is the DNS server that the Flynn CLI is trying to do a DNS lookup against. What is the output of `dig -tany flynn.example.com @192.168.0.1`?

**Comment by andyjeffries** [comment]
```
$ dig -tany flynn.example.com.com @192.168.0.1

;; QUESTION SECTION:
;flynn.example.com.			IN	ANY

;; ANSWER SECTION:
flynn.example.com.		510	IN	A	1.2.3.51
flynn.example.com.		510	IN	A	1.2.3.52
flynn.example.com.		510	IN	A	1.2.3.53
```

(obviously the 1.2.3 is replaced with the real public IP address part, but again, I don't know what needs to be kept secret here).

**Comment by andyjeffries** [comment]
When I try the `flynn cluster add` again, I now get:

```
Error writing CA certificate: Get https://controller.flynn.civo.com/ca-cert: dial tcp 1.2.3.53:443: i/o timeout
```

**Comment by titanous** [comment]
Sounds like you have a firewall or routing issue, can you curl that URL or connect to the IP on port 443?
