### ISSUE TITLE
./bin/rewrite-index-meta: Permission denied using heroku-buildpack-ember-cli

### ISSUE THREAD

**Issue by joeczucha** [flynn/flynn#4035]
I've just deployed an Ember CLI app using the [Ember CLI buildpack](https://github.com/heroku/heroku-buildpack-ember-cli) but it fails at the very end:
        
    ...
    -----> Installed directory to /app/bin
           Using release configuration from last framework (Static HTML).
    -----> Discovering process types
           Procfile declares types -> web
           Default process types for Multipack -> web
    -----> Compiled slug size is 53.87 MiB
    -----> Creating release...
    =====> Scaling initial release to web=1
    -----> Waiting for initial web job to start...
    -----> WARN: scaling initial release down to web=0 due to error
    remote: ERROR: Initial web job failed to start
    To https://git.studiostaging.com/wagner.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'https://git.studiostaging.com/wagner.git'

In the Flynn log I see the following:

    2017-04-15T01:06:25.083071Z app[web.lannister-7193251e-1842-479f-b2fe-2f3a166a9ffb]: bash: ./bin/rewrite-index-meta: Permission denied

I tried deploying the exact same app on Heroku and it's worked fine: 

    ...
    remote:
    remote: -----> Caching build
    remote:        Clearing previous node cache
    remote:        Saving 2 cacheDirectories (default):
    remote:        - node_modules
    remote:        - bower_components (nothing to cache)
    remote:
    remote: -----> Build succeeded!
    remote: -----> Discovering process types
    remote:        Procfile declares types     -> (none)
    remote:        Default types for buildpack -> web
    remote:
    remote: -----> Compressing...
    remote:        Done: 59.3M
    remote: -----> Launching...
    remote:        Released v4
    remote:        https://pouring-beers-34663.herokuapp.com/ deployed to Heroku
    remote:
    remote: Verifying deploy... done.
    To https://git.heroku.com/pouring-beers-34663.git
     * [new branch]      master -> master

...so I wasn't sure whether this would be an issue that I'd need to report to you or if it's one for the buildpack maintainers.

Thanks in advance, let me know if you need anything more.

**Comment by lmars** [comment]
@joeczucha is the `bin/rewrite-index-meta` file part of your app?

**Comment by joeczucha** [comment]
@lmars No, it's [part of the buildpack](https://github.com/heroku/heroku-buildpack-ember-cli/blob/master/scripts/rewrite-index-meta)...

**Comment by lmars** [comment]
@joeczucha that file is not executable:

```
$ git clone https://github.com/heroku/heroku-buildpack-ember-cli.git

$ stat -f '%Sp' heroku-buildpack-ember-cli/scripts/rewrite-index-meta 
-rw-r--r--
```

The buildpack maintainer needs to make the files executable.

**Comment by joeczucha** [comment]
Thanks @lmars, I figured that might be the case. I got it working with [another EmberJS buildpack](https://github.com/heroku/heroku-buildpack-emberjs) that I found but I'll let them know anyway.

Just out of curiosity - and because I don't understand much about all this - how come it worked when I deployed to Heroku? Is it just how the permissions are handled by the respective filesystems?

**Comment by titanous** [comment]
@joeczucha I'm not sure why it's working on Heroku, but in general trying to execute a file that doesn't have the execute bit isn't going to work.
