### ISSUE TITLE
controller api 404

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4036]
Hi there,

Has something changed, I just follow [https://flynn.io/docs/api/controller#update-route](https://flynn.io/docs/api/controller#update-route) but I always get a 404 status, I really have checked my url many many times now...

So is the documentation right?

Thanks,
Martin

**Comment by lmars** [comment]
@grauschnabel what is the exact URL which is giving a 404?

**Comment by grauschnabel** [comment]
its

`https://controller.myzg.flynnhub.com/apps/primedev/routes/http/4fa29fa4-473e-46cf-88d1-cf0ea73ad73c`
(I just changed some letters for security.)
and I use in my python code:
`        res = requests.put(url, auth=('', self.flynn_auth_key), data=json.dumps(data), verify=f.name)
`
where url is the string above with

**Comment by lmars** [comment]
@grauschnabel so are you sure that route exists? Does it appear in `flynn -a primedev route`?

**Comment by grauschnabel** [comment]
yes it does, i copy and pasted it (the ID) from there.

**Comment by lmars** [comment]
@grauschnabel are you passing a full representation of the route as the request body?

You should get the route first with `GET /apps/<app>/routes/<route-id>`, modify it and then `PUT /apps/<app>/routes/<route-id>`.

**Comment by grauschnabel** [comment]
ok, I'll try it this way and tell you if it worked.

**Comment by grauschnabel** [comment]
ok, it works this way, but maybe 404 is the wrong status code?  406 would fit better I think - maybe.

Thanks for your help.
