### ISSUE TITLE
could not create slug image: unexpected HTTP status: 500 Internal Server Error

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#4045]
git push has suddenly stopped working properly and it will either hang during the deploy and never complete or I'll get this error.

> remote: 2017/04/20 17:03:34 ERROR: could not create slug image: unexpected HTTP status: 500 Internal Server Error
remote: ERROR: Build failed: exec: job exited with status 1

I've done all the usual things such as checking disk space and fix-hosts but that all seems ok.

I've emailed you the logs.

**Comment by lmars** [comment]
@dottodot I can see some errors in the blobstore log like:

```
XAmzContentSHA256Mismatch: The provided 'x-amz-content-sha256' header does not match what was computed.
```

It seems to only be happening in job `cluster4-d1c12fbe-7f86-42c4-93a8-3230038f10c6` and for large uploads.

I suggest restarting that job with:

```
$ flynn -a blobstore kill cluster4-d1c12fbe-7f86-42c4-93a8-3230038f10c6
```

**Comment by dottodot** [comment]
OK the first attempt to push has worked, but probably won't know for sure until I've done a few so will report back if there are any more issues.
