### ISSUE TITLE
env set with values containing space

### ISSUE THREAD

**Issue by j3r3my** [flynn/flynn#4054]
Hello,
In automating the build and deploy of our flynn environments, we often encounter environment variables that have spaces in them:
`DEPARTMENT=Default Department`

Running this directly on the command-line works:
`flynn -a appName -c clusterName env set DEPARTMENT="Default Department"`

However, if I have a config file that I'm running programmatically via Ansible essentially running the command:
`flynn -a appName -c clusterName env set $(cat myEnvVars.config)`

it fails every time with:
`invalid var format: "space"`

I've tried various forms of quotes, escapes and even URL encodings to try and get this to work from a single config file but am having to handle all of my config vars containing spaces as one-off releases...

**Comment by lmars** [comment]
@j3r3my does `myEnvVars.config` contain `KEY=VAL` pairs? Does it contain the string "space"?

**Comment by j3r3my** [comment]
It does - so - whatever the value is that has the space; some examples
` TEST="my value" # returns invalid var format: "value"`
` TEST="my space" # returns invalid var format: "space"`
` TEST="Default Department" # returns invalid var format: "Department"`

If I remove the key=value pairs which have spaces in the value, `flynn env set` works as expected.

**Comment by lmars** [comment]
@j3r3my you can get this to work in the shell with:

```
$ sh -c "flynn env set $(cat myEnvVars.config | xargs -d '\n')"
```

It is probably worth us adding something like `flynn env set --file env.json` where `env.json` contains a JSON object of key-value pairs.

**Comment by j3r3my** [comment]
This worked but only on a linux system (I ran this successfully on a jump box in AWS). I couldn't get this to run from macOS via terminal at all (something to do with the version of xargs I guess?). The json file or a mechanism that would work on a file exported from Heroku (I read from another post) would be fantastic:
```
heroku config -s --remote myRemote > myVars.json
gives us
  VAR='my var here'
  VAR2=thevar2
  VAR3='another space'
then we can
  flynn -a myapp -c mycluster env set --file myVars.json
```
Thanks so much for your assistance. This gives me more reason to move to a better OS (linux) for day-to-day work!
