### ISSUE TITLE
Migrating blobstore to Minio result in TLS exception

### ISSUE THREAD

**Issue by n0daft** [flynn/flynn#4056]
Currently trying to migrate blobstore to Minio. I have a dedicated minio server whose API is available under a non TLS secured URL.

After trying to migrate via 
```
flynn -a blobstore env set BACKEND_MINIO="backend=minio endpoint=minio.custom.domain:9000 bucket=flynnblobstore access_key_id=key_id secret_access_key=access_key" DEFAULT_BACKEND="minio"`
```

The blobstore web crashes with `Get https://minio.custom.domain:9000/flynnblobstore/?location=: remote error: tls: internal error`.

I guess this is expected as the minio server is not served via https. However, I wonder if flynn would accept a self-signed certificate of if it has to be one from a thrusted CA.

**Comment by lmars** [comment]
@n0daft you need to set `insecure=true` to disable TLS:

```
flynn -a blobstore env set BACKEND_MINIO="backend=minio \
  endpoint=minio.custom.domain:9000 \
  bucket=flynnblobstore \
  access_key_id=key_id \
  secret_access_key=access_key \
  insecure=true" DEFAULT_BACKEND="minio"
```

**Comment by n0daft** [comment]
Thanks for the quick answer. Haven't realized that this is possible. Will try it later.

**Comment by n0daft** [comment]
Worked like a charm. Also the migrate command afterwards. Although I'm not sure if it copied all blobs:
The logs seem to have a counter of some sort
```
2017/04/26 09:26:02 [36/177] Moving /slugs/images/56444861d9f496768c40100a0c11d0b7b27a622e9376664bef7e7725ff6b2188.json (7af3cf2a-0674-4126-beb4-f8169008403a, 563 bytes) from postgres to minio
2017/04/26 09:26:06 [37/177] Moving /ed89c17c-0073-44c3-a26b-7f94a533fcad-cache.tgz (50b49409-ac14-4b9d-934c-a1afbadb5d04, 130804657 bytes) from postgres to minio
2017/04/26 09:26:06 [38/177] Moving /slugs/images/4535971fd89b053b8b8805f14610d8eadefc8e3a2d4ecc178ec55d88045c5d45.json (c9ed9d61-deb6-48d3-aad0-0ff178c87706, 563 bytes) from postgres to minio
```

After 38 the command was finished. No exception. The /177 just made me curious if there is more that could be migrated. What does the /177 stand for?

**Comment by n0daft** [comment]
Something is definitely strange. I started the command again:

`flynn -a blobstore run /bin/flynn-blobstore migrate --delete`

After some successful migration movement log entries the command just aborts. No error logs no nothing. Its just like I ctrl+c it, except I don't.

**Comment by lmars** [comment]
This could be the same as #4025, try:

```
flynn -a blobstore run --limits memory=2GB /bin/flynn-blobstore migrate --delete
```

**Comment by n0daft** [comment]
Although experiencing the same behavior with `--limits memory=2GB` it definitely helped: the process was able to move 55 blobs this time. On previous attempts a max of around 20 moves were reached. Does the memory has to be bigger than the total size of all blobs to move?

**Comment by n0daft** [comment]
BTW: After the blobstore process is aborted its state is marked as 'done':

```
$ flynn-host ps -a
flynn1-6c659665-b6c2-4a24-80b9-932af8c87ad2  done     7 minutes ago      blobstore
```

Also there are no logs to find for the given process id via `flynn-host log $JOB_ID`.

**Comment by n0daft** [comment]
I ran the command again for the last 50 blobs with a limit of 4GB. According to htop the process reached a memory peek of 2.3GB which also explains why the previous execution with a limit of 2GB suddenly aborted.

Long story short: Printing an error when 'flynn run' runs out of memory (as you suggested) would be a great help.
