### ISSUE TITLE
After reboot Flynn not starting up

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#4057]
Hi Guys, 

Problem with our FLynn cluster after reboot. It is not starting up again. 
Flynn-host ps gives us this: 
![screen shot 2017-04-26 at 10 34 41](https://cloud.githubusercontent.com/assets/87234/25425365/06abc734-2a6c-11e7-87b7-82c66f1bd327.png)

As it is a production server, we really need this thing up again..

**Comment by lmars** [comment]
Try running `flynn-host fix --min-hosts=N` where `N` is the number of hosts in the cluster.

**Comment by githublukas** [comment]
Kill your memory processess and then reboot.

**Comment by heldopslippers** [comment]
It is up and running again! 
Thanxs so much for your help in IRC @lmars 👍
