### ISSUE TITLE
cli: Print an error if 'flynn run' runs out of memory

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#4058]
See [here](https://github.com/flynn/flynn/issues/4056#issuecomment-297338728) where it would have been useful to know that `flynn run` exited because the job ran out of memory.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
