### ISSUE TITLE
Reboot brings down cluster

### ISSUE THREAD

**Issue by j3r3my** [flynn/flynn#4064]
Hello, I've lost 2 three-node clusters this week (different apps) doing basic server-patching followed by reboots in AWS. Both clusters I tried multiple suggestions:
```
flynn-host fix --min-hosts 3
flynn-host fix --min-hosts 1 --peer-ips 127.0.0.1
flynn-host fix --min-hosts 3 --peer-ips 127.0.0.1,IP2,IP3
flynn-host fix --min-hosts 3 --peer-ips IP1,IP2,IP3
sudo rm /var/lib/flynn/host-state.bolt; sudo start flynn-host; flynn-host bootstrap
```
I'm in the midst of rebuilding the first one but have lost a lot of faith in Flynn if it can't handle basic operational tasks like server patching. This is reproducible whether I reboot all nodes at once (expected) or in a series.

**Comment by titanous** [comment]
Please provide the full logs from each host collected with `sudo flynn-host collect-debug-info`.

**Comment by j3r3my** [comment]
They're pretty big files even when compressed - anywhere else I can push them to? They're all over 60MB.

**Comment by lmars** [comment]
@j3r3my I recommend using one of Dropbox / S3 / Google Drive.

**Comment by j3r3my** [comment]
https://drive.google.com/open?id=0Bz8wjwQdzA64aGVyd09ZRHRfV3c

**Comment by j3r3my** [comment]
Hello,
Just checking in to see if there's been any progress on this? 
Thanks!

**Comment by titanous** [comment]
I this this is an issue that we've seen in the past where the sirenia state becomes desynced with the data volumes. The volume ID change in #3990 may fix this, but we should make sure that there are no other latent issues.

@j3r3my as far as rebooting hosts go, our team operates production clusters based on the principles of immutable infrastructure, so to patch a cluster you'd just boot up a new cluster with the updated base image. Flynn can handle reboots (modulo this specific issue), but the code paths are not as well tested as they should be. In general a rolling restart while ensuring that everything comes back before moving on to the next host is the best option.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
