### ISSUE TITLE
Consider rancher-os as an alternative to ubuntu.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [flynn/flynn#4065]
[Rancher OS](http://docs.rancher.com/os/) is a docker-based Operating System. 

Flynn's security might be improved by making flynn-host run inside it's own docker container.

Alternative, consider just the Rule of Cool of having a Rancher OS installer.

**Comment by lmars** [comment]
> making flynn-host run inside it's own docker container.

Certainly easier said than done!

`flynn-host` is a similar service to `containerd`: it runs containers, creates cgroups, writes to `/proc`, manages the network (iptables, interfaces, etc.) and creates ZFS volumes (which aren't Linux namespace aware).

Given it needs to perform all these operations, you will most likely have to run it in a privileged Docker container in the host network namespace with write access to cgroups and `/proc`, at which point you may as well just run it as a regular daemon.

Installing ZFS on RancherOS is also more involved than on Ubuntu 16.04 (compare [this guide](https://docs.rancher.com/os/storage/using-zfs/) to the equivalent `apt-get install zfsutils-linux` on Ubuntu).

**Comment by lmars** [comment]
P.S. what is more likely is shipping a minimal "FlynnOS" using [LinuxKit](https://github.com/linuxkit/linuxkit).

**Comment by WriteCodeEveryday** [comment]
@lmars Sir, I disagree with this assessment, sure, building three helicarriers was a monumental undertaking but consider the image of Hydra as a "Rule of Cool" when those three took off, however I will agree with you on the basis that I have committed exactly 0 lines to the Flynn project so there's a chance (possible huge) I know nothing.

**Comment by lmars** [comment]
@WriteCodeEveryday

> I disagree with this assessment

What exactly are you disagreeing with? Do you think running `flynn-host` in a Docker container is more straight forward than what I describe?

**Comment by WriteCodeEveryday** [comment]
@lmars 

> building three helicarriers was a monumental undertaking but consider the image of Hydra as a "Rule of Cool" when those three took off

Lewis, I am messing with you, it is the plot of Captain America: The Winter Soldier.

>  I will agree with you on the basis that I have committed exactly 0 lines to the Flynn project so there's a chance (possibly huge) that I may know nothing.

**Comment by lmars** [comment]
It's been a long day :smile:
