### ISSUE TITLE
is redis working correctly?

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4071]
I installed a new cluster with this settings (about an hour ago):

digitalocean
FRA1 (Franfurt)
3 droplets

using s3 for blobstore, and the latest flynn installer 20170430.0.

now i have many session expired messages.  odoo uses redis for that, and id worked 1-2 months ago.  is there an issue I don't know?  What can I do?

**Comment by lmars** [comment]
Did you restore from a backup?

Redis data is not stored in the backup, if you want to maintain the data in Redis you will need to export / import it manually using `flynn redis dump` and `flynn redis restore` (refer to `flynn help redis`).

**Comment by grauschnabel** [comment]
sorry this was the wrong place, this was solved somewhere else: [odooku #16](https://github.com/adaptivdesign/odooku/issues/16)
