### ISSUE TITLE
flynn-host daemon --external-ip IP does not work

### ISSUE THREAD

**Issue by geefinator** [flynn/flynn#4077]
Currently if I try to start the daemon with --external-ip it just spits out the daemon usage string as if I have an incorrect option specified.
```
root@flynn-test-1:~# flynn-host daemon --external-ip 172.x.x.x
usage: flynn-host daemon [options]
root@flynn-test-1:~# flynn-host daemon --external-ip "172.x.x.x"
usage: flynn-host daemon [options]
root@flynn-test-1:~# flynn-host daemon --external-ip=172.x.x.x
usage: flynn-host daemon [options]
root@flynn-test-1:~# flynn-host daemon --external-ip"172.x.x.x"
usage: flynn-host daemon [options]
```
I have tried just about every combination I can think of to get it to register that option, which is clearly defined in the daemon help:

```root@flynn-test-1:~# flynn-host daemon --help
usage: flynn-host daemon [options]

options:
  --http-port=PORT           HTTP port [default: 1113]
  --external-ip=IP           external IP of host
...
```
If this isn't the right place for this type of issue feel free to close, but this is driving me nuts.

**Comment by lmars** [comment]
I can't reproduce this, what version are you using (`flynn-host version`)?

**Comment by geefinator** [comment]
Looks like the version is: ```v20170417.2```

**Comment by titanous** [comment]
I've been unable to reproduce this as well.

**Comment by geefinator** [comment]
I am going to close this because I think it is related to the way we have our 16.04 vms set up in our environment.  I don't think this is a legitimate bug within flynn.
