### ISSUE TITLE
flynn-host http port 1113 gets not responsive

### ISSUE THREAD

**Issue by crawlik** [flynn/flynn#4078]
Looks like flynn-host process gets stuck and not responding to http requests on port 1113 on one out of three flynn servers. Is there a way to unstuck w/o rebuilding whole cluster?

```
root@ip-10-120-72-54:/opt# curl localhost:1113/host/status
curl: (56) Recv failure: Connection reset by peer
```
```
root@ip-10-120-72-54:/opt# flynn-host ps -a
17:03:07.136668 host.go:166: could not get jobs for host ip101207254: Get http://10.120.72.54:1113/host/jobs: read tcp 10.120.72.54:56966->10.120.72.54:1113: read: connection reset by peer
```

TCP connection is accepted.
```
root@ip-10-120-72-54:/opt# nc -v localhost 1113
Connection to localhost 1113 port [tcp/*] succeeded!
```

Log file is staled. Nothing is logged for the last 6 hours.

```
root@ip-10-120-72-54:/var/log/flynn# tail -n 3 flynn-host.log
t=2017-05-02T11:24:11+0000 lvl=info msg="request completed" component=host req_id=bcf1fc76-b41c-411a-8718-93a352ead155 status=200 duration=137.514µs
t=2017-05-02T11:24:11+0000 lvl=info msg="request started" component=host req_id=ea150cd5-f58d-4341-b48e-83836b8225b3 method=GET path=/host/jobs client_ip=10.120.126.57
t=2017-05-02T11:24:11+0000 lvl=info msg="request completed" component=host req_id=ea150cd5-f58d-4341-b48e-83836b8225b3 status=200 duration=210.300423ms
root@ip-10-120-72-54:/var/log/flynn# date
Tue May  2 17:28:17 UTC 2017
```

top for flynn-host
```
1:Def - 17:33:54 up 2 days,  3:14,  2 users,  load average: 0.00, 0.06, 0.08
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us,  0.0 sy,  0.0 ni, 99.0 id,  0.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 15664324 total,  1324920 free,  5851068 used,  8488336 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  4428940 avail Mem

1  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  1894 root      20   0 1336564  94772  16832 S   0.0  0.6  59:26.97 flynn-host
2  PID  PPID     TIME+  %CPU %MEM  PR  NI S    VIRT    RES   UID COMMAND
  1894     1  59:26.97   0.0  0.6  20   0 S 1336564  94772     0 flynn-host
3  PID %MEM    VIRT    RES   CODE    DATA    SHR nMaj nDRT  %CPU COMMAND
  1894  0.6 1336564  94772  10332 1309344  16832  372    0   0.0 flynn-host
4  PID  PPID   UID USER     RUSER    TTY          TIME+  %CPU %MEM S COMMAND
  1894     1     0 root     root     ?         59:26.97   0.0  0.6 S flynn-host
```

```
root@ip-10-120-72-54:/opt# flynn version
v20170430.0
```

**Comment by crawlik** [comment]
Looks like `http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s` is the culprit. Running `systemctl running flynn-host` on affected server solved the problem. But i am still not clear why so many connections are established. Will do more investigation once I hit this problem again.
 
```
root@ip-10-120-72-54:/opt# systemctl status flynn-host
● flynn-host.service - Flynn host daemon
   Loaded: loaded (/lib/systemd/system/flynn-host.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-04-30 14:24:22 UTC; 2 days ago
     Docs: https://flynn.io/docs
 Main PID: 1894 (flynn-host)
    Tasks: 48
   Memory: 267.7M
      CPU: 1h 34.515s
   CGroup: /system.slice/flynn-host.service
           └─1894 /usr/local/bin/flynn-host daemon

May 02 18:11:13 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:13 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
May 02 18:11:14 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:14 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
May 02 18:11:15 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:15 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
May 02 18:11:16 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:16 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
May 02 18:11:17 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:17 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
May 02 18:11:18 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:18 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
May 02 18:11:19 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:19 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
May 02 18:11:20 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:20 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
May 02 18:11:21 ip-10-120-72-54 flynn-host[1894]: 2017/05/02 18:11:21 http: Accept error: accept tcp [::]:1113: accept4: too many open files; retrying in 1s
```

**Comment by lmars** [comment]
If you see this again please send a `SIGQUIT` signal to the `flynn-host daemon` process and then post the resulting backtrace which is output to stderr.

**Comment by crawlik** [comment]
@lmars we will do. Is it safe to bounce flynn-host `systemctl restart flynn-host` to get it going again? I did it a couple of times and it seems to be operational after that.

**Comment by lmars** [comment]
> Is it safe to bounce flynn-host systemctl restart flynn-host to get it going again?

It is "safe" in the sense that the daemon should come back up, but you may end up with an unbalanced cluster as some jobs are moved away from that host, so I would treat it as a last resort.

**Comment by crawlik** [comment]
> ... so I would treat it as a last resort

Is there a better way to handle it?

**Comment by crawlik** [comment]
@lmars just hit this problem again, run the following command

```bash
kill -s SIGQUIT 1922 | tee flynn-host.sigquit
```

but nothing was reported by kill to stderr or stdout. Does this command look correct? flynn-host got restarted and port 1113 is working again.

```
root@ip-10-120-121-117:/home/ubuntu# ls -la flynn-host.sigquit
-rw-r--r-- 1 root root 0 May  4 16:07 flynn-host.sigquit
```

Also tried `kill -3 pid` I would use for JVM process, but no stacktrace as well.

**Comment by titanous** [comment]
@crawlik it would have been logged to the systemd journal (16.04) or /var/log/upstart/flynn-host.log (14.04)

**Comment by crawlik** [comment]
@lmars here is log with stack trace
https://bazaarvoice.box.com/s/1lolclzpf9cmef3kvza1ld44zg5jpduw

**Comment by titanous** [comment]
Thanks, can you also provide the corresponding flynn-host log from, /var/log/flynn/flynn-host.log

**Comment by titanous** [comment]
@crawlik Were you doing anything with the ZFS snapshot system? I found a couple places that could cause this deadlock that I fixed in #4088, but we don't currently call that code anywhere in Flynn.

**Comment by crawlik** [comment]
> Were you doing anything with the ZFS snapshot system?

@titanous Not intentionally or knowingly.  @temujin9 any ideas if we do ^^^

Here is all logs https://bazaarvoice.box.com/s/6ynfu9umrg2byx2pkaf4brxjwqd65mgl

**Comment by temujin9** [comment]
We use the backup system once an hour, but I don't believe that touches the
snapshot systems. I could be incorrect.

Cheers,


Nathaniel Eliot

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
