### ISSUE TITLE
Flynn went down. 

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#4091]
Probably due to memory issues flynn went down.
- Restart didn't help. 
- flynn-host fix --min-hosts 1 tells me everything is ok. 
I think it has something todo with postgres. Not sure how tot fix it though. 

Anybody know how to check what is wrong? 
[Logs](https://drive.google.com/a/website-development.nl/file/d/0B_l6au1xMoeCQ2ZDOEZ3VmhfVGM/view?usp=sharing)

**Comment by lmars** [comment]
@heldopslippers those logs seem to be private, please make them public so we can view them.

**Comment by heldopslippers** [comment]
In the last 8 hours I tried a lot of things. 
Currently flynn-host isn't even able to start.

getting: "could not list hosts: Error sending HTTP request" 
"flynn-host collect-debug-info" gets me also "error sending http requests" 
And the runs out of memory: 



`INFO[05-05|15:06:47] getting system information 
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb19a0a, 0x16)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/panic.go:566 +0x95
runtime.sysMap(0xc709b50000, 0x9cff0000, 0x0, 0x105b7b8)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/mem_linux.go:219 +0x1d0
runtime.(*mheap).sysAlloc(0x1042140, 0x9cff0000, 0x1)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/malloc.go:407 +0x37a
runtime.(*mheap).grow(0x1042140, 0x4e7f7, 0x0)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/mheap.go:726 +0x62
runtime.(*mheap).allocSpanLocked(0x1042140, 0x4e7f7, 0x2000)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/mheap.go:630 +0x4f2
runtime.(*mheap).alloc_m(0x1042140, 0x4e7f7, 0x7f0100000000, 0x44cb59)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/mheap.go:515 +0xe0
runtime.(*mheap).alloc.func1()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/mheap.go:579 +0x4b
runtime.systemstack(0x7f8a8c71ce18)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:314 +0xab
runtime.(*mheap).alloc(0x1042140, 0x4e7f7, 0x100000000, 0xd)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/mheap.go:580 +0xa0
runtime.largeAlloc(0x9cfee000, 0x7f8a8e0e3000, 0xd)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/malloc.go:774 +0x93
runtime.mallocgc.func1()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/malloc.go:669 +0x3e
runtime.systemstack(0xc42001a000)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:252 fp=0xc4201f53b8 sp=0xc4201f53b0
runtime.mallocgc(0x9cfee000, 0x0, 0x0, 0xc420236060)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/malloc.go:670 +0x90c fp=0xc4201f5458 sp=0xc4201f53b8
runtime.growslice(0xa25020, 0xc420236060, 0x2e, 0x30, 0x9cfed9b8, 0xc420236060, 0x5, 0x30)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/slice.go:126 +0x24e fp=0xc4201f54e8 sp=0xc4201f5458
fmt.(*fmt).padString(0xc420636040, 0xc66cb20000, 0x9cfed98a)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/fmt/format.go:110 +0x112 fp=0xc4201f5570 sp=0xc4201f54e8
fmt.(*fmt).fmt_s(0xc420636040, 0xc66cb20000, 0x9cfed98a)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/fmt/format.go:328 +0x61 fp=0xc4201f55a8 sp=0xc4201f5570
fmt.(*pp).fmtString(0xc420636000, 0xc66cb20000, 0x9cfed98a, 0xc400000076)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/fmt/print.go:430 +0x145 fp=0xc4201f55e0 sp=0xc4201f55a8
fmt.(*pp).printArg(0xc420636000, 0xa24d20, 0xc420242040, 0x76)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/fmt/print.go:658 +0xc1d fp=0xc4201f56d8 sp=0xc4201f55e0
fmt.(*pp).doPrintln(0xc420636000, 0xc4201f5af8, 0x4, 0x4)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/fmt/print.go:1125 +0xa3 fp=0xc4201f5750 sp=0xc4201f56d8
fmt.Sprintln(0xc4201f5af8, 0x4, 0x4, 0xa24d20, 0xc420242040)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/fmt/print.go:264 +0x56 fp=0xc4201f57a8 sp=0xc4201f5750
github.com/flynn/flynn/host/cli.runCollectDebugInfo(0xc4201b5e40, 0x191, 0xc420125b50)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/host/cli/collect-debug-info.go:103 +0xc36 fp=0xc4201f5ba8 sp=0xc4201f57a8
github.com/flynn/flynn/host/cli.Run(0x7fff17a93859, 0x12, 0x10595c8, 0x0, 0x0, 0xc42004fc01, 0xb83438)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/host/cli/cli.go:62 +0x4b4 fp=0xc4201f5c80 sp=0xc4201f5ba8
main.main()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/host/host.go:156 +0x4d4 fp=0xc4201f5f38 sp=0xc4201f5c80
runtime.main()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:183 +0x1f4 fp=0xc4201f5f90 sp=0xc4201f5f38
runtime.goexit()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4201f5f98 sp=0xc4201f5f90

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive, 2 minutes]:
github.com/flynn/flynn/pkg/shutdown.(*handler).wait(0xc420013890)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/pkg/shutdown/handler.go:58 +0x117
created by github.com/flynn/flynn/pkg/shutdown.newHandler
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/pkg/shutdown/handler.go:25 +0xc3

goroutine 18 [select, 2 minutes, locked to thread]:
runtime.gopark(0xb82f78, 0x0, 0xb0eb76, 0x6, 0x18, 0x2)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42003af20, 0x0, 0x18)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/select.go:423 +0x1235
runtime.selectgo(0xc42003af20)
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/tmp/tmp.qLLGi4btkT/src/github.com/flynn/flynn/util/_toolchain/go/src/runtime/asm_amd64.s:2086 +0x1
`
