### ISSUE TITLE
redis, apcu, memcached

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4095]
Hi there,

How can I deploy a php app with uses redis, apcu, memcached in the requirements?  I don't figure out how I can implement that in the composer.json file, sorry, for asking here.  Do I have to do something else on the system to have that supported?

**Comment by titanous** [comment]
Flynn fully supports composer.json, so I'd go upstream if you need help with that.

**Comment by philiplb** [comment]
How:
See https://devcenter.heroku.com/articles/php-support#extensions
Example requirement of an app using gd:
```json
"ext-gd": "*"
```
