### ISSUE TITLE
flynnhub.com subdomains blacklisted as deceptive

### ISSUE THREAD

**Issue by dabeeeenster** [flynn/flynn#4096]
If I visit flynnhub.com or any associated subdomains in Chrome or Firefox, they are blacklisted as a deceptive site. This is also causing API calls to silently fail to those domains.

**Comment by titanous** [comment]
I'm investigating this.

**Comment by titanous** [comment]
I've responded to the report and requested a review.

**Comment by titanous** [comment]
The site has been marked as safe, the blocklist should update in the next few hours.

**Comment by dabeeeenster** [comment]
Great thanks - this looks to be working here
