### ISSUE TITLE
Flynn vagrant demo dashboard service unavailable

### ISSUE THREAD

**Issue by jongirard** [flynn/flynn#4100]
Following the steps for installing Flynn locally with no errors using Vagrant, the dashboard loads but says "Service Unavailable, please try again in a few minutes". Entering the provided login token does nothing either.

flynn -a dashboard log says `22:18:20.076939 main.go:174: no clusters configured.`

**Comment by huseyin** [comment]
just run the following commands:

~~~
$ make up
$ make init
$ make dashboard
~~~
