### ISSUE TITLE
Play framework / Scala apps support?

### ISSUE THREAD

**Issue by nileshtrivedi** [flynn/flynn#4102]
I was really surprised to see no mention of Play framework in the docs. Even googling did not help. Is no one running Play apps on Flynn? Are there plans to support those?

**Comment by josephglanville** [comment]
Flynn ships with `heroku-buildpack-scala` which should automatically detect and handle Play applications.
If you want to use a later version you can set the buildpack manually with `flynn env set BUILDPACK_URL="https://github.com/heroku/heroku-buildpack-scala"`

**Comment by lmars** [comment]
@nileshtrivedi there is a Play example app here: https://github.com/flynn-examples/play-flynn-example
