### ISSUE TITLE
flynn cluster not reachable after apt-get dist-upgrade

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4103]
Hi there,

I was running on all hosts (using cluster-ssh):

```
apt-get update && apt-get dist-upgrade && apt-get autoremove && apt-get autoclean && reboot
```

Now the dashboard is not reachable, and none of the apps.  The flynn client also does not reach the hosts:
```
$ flynn apps
Get https://controller.idonttell.flynnhub.com/apps: dial tcp this.is.my.ip:443: getsockopt: connection refused
```

But there is no problem to reach the digialocean droplets via ssh using their ip addresses.

It looks like there is no server started wich answers on port 443.
What can I do?

I tried to check the status:
```
root@flynn-1493633356-2:~# systemctl status flynn-host
● flynn-host.service - Flynn host daemon
   Loaded: loaded (/lib/systemd/system/flynn-host.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-05-11 07:55:41 UTC; 4min 24s ago
     Docs: https://flynn.io/docs
 Main PID: 2746 (flynn-host)
    Tasks: 12
   Memory: 27.4M
      CPU: 1.719s
   CGroup: /system.slice/flynn-host.service
           └─2746 /usr/local/bin/flynn-host daemon

May 11 07:55:41 flynn-1493633356-2 systemd[1]: Started Flynn host daemon.
May 11 07:57:43 flynn-1493633356-2 flynn-host[2746]: 2017/05/11 07:57:43 resurrecting flynn14936333562-9699d9f1-1b78-4577-b3c1-6bbb9a35190b as flynn14May 11 07:57:43 flynn-1493633356-2 flynn-host[2746]: 2017/05/11 07:57:43 resurrecting flynn14936333562-ce2f2114-9ed6-44a6-b89e-75be844b5fee as flynn14
```

Thanks,
Martin

**Comment by lmars** [comment]
@grauschnabel did you upgrade the kernel? If so, you may need to re-install ZFS for the new kernel.

**Comment by grauschnabel** [comment]
@lmars, yes there was a kernel upgrade I think.  i did now
```
 apt-get install --reinstall libzfs2linux zfs-zed zfsutils-linux && reboot
```
on the maschines, but it didn't help.  so anything else?  Any logs where I can find something?   I think I checked it all... :(

**Comment by lmars** [comment]
Please run `sudo flynn-host collect-debug-info` and post the resulting gist.

**Comment by grauschnabel** [comment]
this seems to hang on:
```
EROR[05-11|18:23:13] error getting scheduler state            err="object_not_found: no leader found"
```
maybe I need to repair something there?

**Comment by grauschnabel** [comment]
it seems to be something with the controller, from ```flynn-host fix -n 3```:
```
INFO[05-11|19:00:58] no controller web process running, getting release details from hosts 
INFO[05-11|19:00:59] provisioning volume for controller web job job.id=flynn14936333562-09570ba1-1439-4d14-81bb-ec159486a2ff release=c03dd500-f7fc-47ea-b31d-014e9c9d1dd2
INFO[05-11|19:00:59] starting controller web job              job.id=flynn14936333562-09570ba1-1439-4d14-81bb-ec159486a2ff release=c03dd500-f7fc-47ea-b31d-014e9c9d1dd2
INFO[05-11|19:00:59] waiting for job to start 
19:01:59.210994 host.go:166: discoverd: timed out waiting for instances
```
but mabe this is a zfs issue?

**Comment by grauschnabel** [comment]
EROR[05-11|19:16:09] error fixing controller                  err="error getting controller release: Get http://100.100.69.4:80/apps/controller/release: dial tcp 100.100.69.4:80: i/o timeout"

**Comment by grauschnabel** [comment]
it seems that `/bin/start-flynn-controller` and `/bin/flynn-controller` files are missing here.  how can I get them back?

**Comment by grauschnabel** [comment]
I did the following:
copied the database files from the bigest zfs to my local machine and set up a local postgresql-9.5 server with this files.  then I could create a dump which worked with a new created flynn cluster.
