### ISSUE TITLE
Apps that use Nvidia GPU's

### ISSUE THREAD

**Issue by abagshaw** [flynn/flynn#4110]
Is it possible to deploy apps to Flynn that rely on Nvidia GPU's? I suppose this would require some integration with nvidia-docker as, from my understanding, all apps run in docker containers managed through Flynn.

**Comment by WriteCodeEveryday** [comment]
Remember that you can always deploy a docker container. If you are using the AWS GPU instances, it should allow you to access the CUDA cores. Just build a docker container fromthe nvidia-docker with your code in it (instructions for deploying docker containers should be on the flynn site)

**Comment by titanous** [comment]
This can definitely work in Flynn, though some permissions may need tweaking. Let us know if you run into any issues when testing it out.
