### ISSUE TITLE
cluster backup very small file

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4111]
Hi there,

When I try `flynn cluster backup --file myfile.tar` the created file is about 3 MB large.  There are some releases which report a much higher size on `git push flynn master` and even a simple `flynn -a oneofmyapps pg dump` creates a larger file than a full cluster backup.
Is this normal behaviour?  I use s3 blobstore like in production and a 3 droplet cluster.

Thanks

**Comment by philiplb** [comment]
Hi,
that sounds reasonable. It contains a dump from the Postgres and a few KB of Metadata. The app releases stay in S3.

**Comment by grauschnabel** [comment]
Does that mean, a restore to a testing environment with working on that, maybe remove apps, could destroy the stability of the production system?

**Comment by titanous** [comment]
If you use an external blobstore backend, then yes, you'd need to migrate to a new backend if you didn't want to impact an existing cluster with the same backend configured.
