### ISSUE TITLE
Backups no longer appear to include build slugs

### ISSUE THREAD

**Issue by dabeeeenster** [flynn/flynn#4113]
Is this intentional? After upgrading the flynn client to ```v20170514.0-a013e9a```, running a backup against a cluster just dumps these files:

```
flynn-backup-2017-05-17_010005/flynn.json
flynn-backup-2017-05-17_010005/postgres.sql.gz
flynn-backup-2017-05-17_010005/mysql.sql.gz
```

Previously backup tar files used to be much larger and include slugs?

**Comment by titanous** [comment]
If you have an external blobstore backend configured, no blobs are included in the backup.

**Comment by dabeeeenster** [comment]
Ah understood. Has this changed on the client since the start of 2017?

**Comment by titanous** [comment]
Nope, nothing here has changed.
