### ISSUE TITLE
'remote: ERROR: Build failed: exec: job exited with status 7' while deploying "go-flynn-example"

### ISSUE THREAD

**Issue by schorsch3000** [flynn/flynn#4114]
I've set up a cluster of three nodes according to the documentation.
Next i've tried to deploy the go-flynn-example according to https://flynn.io/docs/basics

pushing to flyn takes about 140 sec, hanging tme majority of time at 

`-----> Go app detected
`
the complete output:
```

git push flynn master
Counting objects: 732, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (453/453), done.
Writing objects: 100% (732/732), 933.65 KiB | 0 bytes/s, done.
Total 732 (delta 217), reused 732 (delta 217)
-----> Building example...
-----> Go app detected
remote: ERROR: Build failed: exec: job exited with status 7
To https://git.<$CLUSTER_DOMAIN>/example.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.<$CLUSTER_DOMAIN>/example.git'

```

what's going on here?

**Comment by titanous** [comment]
Are you able to deploy other non-Go example apps? Usually that means that there was an issue downloading dependencies.

**Comment by schorsch3000** [comment]
Yes, that was the problem, my firewall was working TOO hard and was blocking incomming ACK packages, making it unable to start downloading the dependencies.
Sorry for the hassle, everything is fine now :)
