### ISSUE TITLE
Bootstrapping cluster from backup fails 

### ISSUE THREAD

**Issue by crawlik** [flynn/flynn#4115]
Came across this problem recently (3 times at least) and wonder if you guys have any insights into that. Cluster is still up. Let me know if you want me to investigate it.

```
++ flynn-host bootstrap --peer-ips=10.110.125.220,10.110.83.207,10.110.101.142 --from-backup /mnt/tmp/flynn-restore-source --timeout 5400
+ bootstrap_output='20:17:28.158195 check online-hosts
20:17:28.161893 run-app discoverd
20:17:29.856429 run-app flannel
20:17:33.952796 wait-hosts wait-hosts
20:17:34.456745 run-app postgres
20:17:48.762665 sirenia-wait postgres-wait
20:17:48.767971 restore-postgres restore
20:29:33.639533 run-app controller
20:29:35.486819 wait-controller wait-controller
20:30:05.489105 host.go:166: error getting controller instance: discoverd: timed out waiting for instances'
+ echo 'Bootstrap failed, collecting debugging info'
Bootstrap failed, collecting debugging info
++ flynn-host collect-debug-info
+ debug_info='t=2017-05-17T20:30:05+0000 lvl=info msg="uploading logs and debug information to a private, anonymous gist"
t=2017-05-17T20:30:05+0000 lvl=info msg="this may take a while depending on the size of your logs"
t=2017-05-17T20:30:05+0000 lvl=info msg="getting flynn-host logs"
t=2017-05-17T20:30:05+0000 lvl=info msg="getting sirenia metadata"
t=2017-05-17T20:30:05+0000 lvl=info msg="getting scheduler state"
t=2017-05-17T20:30:05+0000 lvl=eror msg="error getting scheduler state" err="object_not_found: no leader found"
t=2017-05-17T20:30:05+0000 lvl=info msg="getting job logs"
t=2017-05-17T20:30:05+0000 lvl=info msg="getting system information"
t=2017-05-17T20:30:06+0000 lvl=info msg="creating anonymous gist"
t=2017-05-17T20:30:08+0000 lvl=info msg="debug information uploaded to: https://gist.github.com/1e7d0b9e18ba9f19fbc19ec87f6c75b2"'
```
Here is some log files

https://bazaarvoice.box.com/s/5lzm57s668einf7kg6mh75rbyz0c3xqc
https://bazaarvoice.box.com/s/fjvgumkvxn9jvxoyife4s0cfegfc3x20

**Comment by temujin9** [comment]
This problem survives a migration (import / export) of user applications into a new cluster. My strong suspicion is that something about the structure of one of our legacy applications is poisoning the restore.

**Comment by temujin9** [comment]
Apparently, the survival of this issue past migration is not sure. I just built a cluster restoring from backup on the affected endpoint, and the issue did not recreate.

**Comment by lmars** [comment]
The controller job is failing to start as it is trying to create a table which already exists:

```
20:29:35.563422 controller.go:64: ERROR: relation "artifacts" already exists (SQLSTATE 42P07)
```

The artifacts table has always existed in Flynn and is the first table created in the first migration (see [here](https://github.com/flynn/flynn/blob/master/controller/schema.go#L14-L23)) so my suspicion here is that the backup is corrupted and for some reason does not have the migrations table.

**Comment by titanous** [comment]
Closing as a variant of #3468.
