### ISSUE TITLE
Mounting Flynn under PCLinuxOS.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [flynn/flynn#4122]
I know it's probably a long shot but I recently picked up an Optiplex FX160 for cheap (dual core 1.6Ghz Atom, 4GB of RAM, 160GB spinning platter). Ubuntu won't recognize the complete RAM and it eats it with the SIS Graphics driver. The recommendation is either Mandriva, or PCLINUXOS. 

I'm not asking for support, I'm just asking for someone to estimate the odds of Flynn working under PCLINUXOS or Mandriva in this hardware (I know Ubuntu is the only supported one).

**Comment by lmars** [comment]
@WriteCodeEveryday as long as you can manually install the packages Flynn depends on (see all the references to `apt-get` in the [install script](https://github.com/flynn/flynn/blob/master/script/install-flynn.tmpl)), then you should be able to get Flynn to work.

**Comment by WriteCodeEveryday** [comment]
@lmars I got to give it to you guys, I never thought this would run under such terrible specs but it works. Thank you for the help.
