### ISSUE TITLE
Striving for immutable infrastructure

### ISSUE THREAD

**Issue by n0daft** [flynn/flynn#4124]
I've read that the general approach for fixing broken flynn clusters (and also updating to new flynn versions) is to set up a new cluster and restore the content from a cluster backup (i.e. aiming for an immutable infrastructure).

To minimize downtime in case of cluster update an/or cluster failure I've created the following setup inside a productive server cluster environment:

* 3 node Flynn cluster 
* Flynn operator (separate linux VM having access to Flynn cluster via Flynn CLI)
* Minio server acting as blobstore for Flynn blobs and Flynn cluster backups
* Automatic cluster backup and upload to minio via cron job on Flynn operator VM

Moreover, I've created bash scripts which allow me to automatically clean install an entire n-node cluster and restore it from a given backup file.

With this setup I am able to automatically reinstall a complete production cluster and bootstrap it with the latest cluster backup at any time. In case of emergency I'm able to get the cluster back up in approximately 5 min.

However there are some drawbacks to this solution:

* I'm not really a bash script expert and the development and maintenance of bash scripts seems somewhat cumbersome
* Although being a powerful scripting language, bash scripts come out short in certain aspects compared with modern programming languages like go (for example concurrency)
* In general, a more high-level solution to automate this process might present a neater way to assure a configurable and immutable infrastructure

I wonder what your thoughts on this topic are and how you aim for an immutable infrastructure?

**Comment by titanous** [comment]
This all sounds reasonable!

**Comment by temujin9** [comment]
I can give a couple of additional pointers, having done something similar:
- I used Bash for version 1 of an in-house Flynn deployment tool. Your intuition that Bash is the wrong tool for this job is pretty much correct. It's good for very simple things, and okay for mildly complex things, but you rapidly reach a point of diminishing returns.
- I switched to Golang for the second version of that tool; I chose it so I could level up on the language Flynn itself was built on. You could also go with Python, which is probably easier to get into, and the sysadmin's typical first choice of replacement language for Bash scripts.
- Automatic backups can also be accomplished from within a Flynn application, if you build in the flynn binary and credentials. That gives you all of the benefits of a Flynn app, like automatic restart, logging, and easy reconfig.

**Comment by temujin9** [comment]
Ah, one final pointer:
- Use a load balancer, if your hosting environment provides it. That will allow quicker addition and removal of nodes, which can allow save you the downtime from DNS propagation.

**Comment by thomasmodeneis** [comment]
@titanous sorry, why was this closed anyway ?? This ticket sounds like a great idea!!!

**Comment by titanous** [comment]
@thomasmodeneis Flynn is already designed for immutable infrastructure, and many people including some who posted on this issue use these techniques. The issue was closed because it is not an applicable feature request or bug.

**Comment by temujin9** [comment]
@thomasmodeneis If you want a reference implementation, I'm building an open-source one with Python DSL over Terraform, currently targeting AWS, at https://github.com/greenfieldguild/lightcycle .

**Comment by philiplb** [comment]
Added lightcycle to https://github.com/philiplb/awesome-flynn :)
