### ISSUE TITLE
what to do after kernel upgrade?

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4125]
Hi there,

I had the issue #4103 again, so I would like you to include a chapter in the docs for how to upgrade a flynn cluster -> not only the cluster, what to do if you run apt-get dist-upgrade so the flynn does not break...

**Comment by IsNull** [comment]
Flynn is not stable when you mutate the infrastructure. This includes updates, reconfigurations, network changes etc. If you need to do system updates, flynn updates or other changes, you should do this on a new cluster install.

This boils down to

1. Create a cluster backup using the flynn cli
2. Reinstall flynn with the `--clean` parameter, which tears down the whole thing
3. If necessary, do your modifications (reinstall should yield the latest updates / flynn version automatically)
4. Now bootstrap your flynn cluster using the backup file you took in step 1


In step 2., you could alternatively also spin up new nodes for the cluster. This however would require additional work on the DNS / Loadbalancer (point to the new IPs)

Btw, related: https://github.com/flynn/flynn/issues/4124

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
