### ISSUE TITLE
wordpress doesn't save data

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4126]
hi there,
I tried to fork flynn-wp to fix some issues.

Now I found out that added plugins do not be found by the `flynn run bash` environment and a simple scale web=0 and scale web=1 does remove the data. So now I tried to figure out what happens here.

There is an issue from 2015 which should have solved the problem with scheduler v2, but I still do have that problem.  is there a way to fix that?

What is the usual way to have apps which depend on a local filesystem?  I also need to know how I can later make new git pushes to the app without getting the data destroyed...

Martin

**Comment by lmars** [comment]
Jobs do not have persistent storage by default, so installing plugins into a web job will be local to that job and lost when that job stops.

If you need persistent data, consider storing that data in the blobstore which can be backed by external storage (see [here](https://flynn.io/docs/production#blobstore-backend)).

For plugins, I would suggest installing them locally, committing them to your git repository along with any data migrations and then deploying that change.

**Comment by grauschnabel** [comment]
I think I did not fully understand your answer. I use the Amazon 23rd backend already for the blobstore, so how can I enable persistent data? 

I don't like the solution with adding plugins to the repo, because I need flexibility here, so flynn-wp could be a just install app. But maybe I could link external storage like s3 somehow?

**Comment by lmars** [comment]
> how can I enable persistent data?

You can persist data by uploading it to the blobstore (see [here](https://github.com/flynn/flynn/blob/master/blobstore/README.md)).

> I don't like the solution with adding plugins to the repo, because I need flexibility here, so flynn-wp could be a just install app

You can still have a base flynn-wp, and then fork that for each app you deploy with its collection of plugins and themes. This is the recommended way to deploy wordpress to environments which do not provide a persistent filesystem (see [here](https://github.com/mhoofman/wordpress-heroku#usage) and [here](http://hackingui.com/front-end/how-we-built-hackingui-wordpress-heroku-git/#git) for example).

**Comment by grauschnabel** [comment]
thanks for your answer.  I understand that with adding plugins to the git, but I have some people which have no ideas about that, so I need to have an instance wich just runs and users can add their plugins on the web interface.

**Comment by grauschnabel** [comment]
Would there be a way to mount a persitent zfs volume to my app where i can store data which will be available directly in all workers? (if mounted everywhere)?  Like nfs or similar?  This is a thing I'm really new with, so just if you have ideas...

**Comment by lmars** [comment]
> Would there be a way to mount a persitent zfs volume to my app where i can store data which will be available directly in all workers?

ZFS volumes are persistent but can only be attached to a single job for consistency reasons.

> Like nfs or similar?

NFS support is a planned feature but work has not yet begun on implementing it #1521.

**Comment by grauschnabel** [comment]
I'll find a solution

**Comment by aaomidi** [comment]
Did you find a solution to this? @grauschnabel

**Comment by grauschnabel** [comment]
No, sorry, for that. So I think you new to be at least a sysasmin if you want to successfully use WordPress with flynn. It's hard just to install it and let a publisher do the rest... But if I find something, I would tell you.

**Comment by aaomidi** [comment]
Thanks, it's quite annoying that flynn doesn't provide flat-file storage for people who don't need scaling.

**Comment by grauschnabel** [comment]
I would like to have an easy way to mount external storage to some directories, which are available from all instances. That would be the best solution. A file store like a database...
