### ISSUE TITLE
api and resources

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4127]
Hi there,

What is the easyest way to do
`flynn resource add mysql`
within the api?

Createing and deleting apps works fine, but this seems not to be so simple...

**Comment by lmars** [comment]
It isn't straight forward to add resources via the API, but if you want to try then refer to the code in both the CLI and the Go API client both [here](https://github.com/flynn/flynn/blob/master/cli/resource.go#L58-L80) and [here](https://github.com/flynn/flynn/blob/master/controller/client/v1/client.go#L224-L233).

This difficulty has also come up in the past (see #3854), until we have something like that it is probably easier to just shell out to the CLI.
