### ISSUE TITLE
api: delete app response to fast how to wait?

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4128]
hi there,

when I send a 
`delete /apps/myapp-id` and right when the response is there a `post /apps` with the same name which the app had I just deleted, i get a `{'code': 'object_exists', 'message': 'application "spg" already exists', 'retry': False}` response.
If I wait some time, the post/apps works correctly.

Is this the expected behaviour?  How can I wait for the app do be deleted?  sending a get /apps/myname every second until its 404?  or is there a better way?

**Comment by lmars** [comment]
@grauschnabel when you delete an app, it is removed in a background worker process, and you need to wait for an "app_deletion" event for that app.

Check out the Go API client code for `DeleteApp` [here](https://github.com/flynn/flynn/blob/master/controller/client/v1/client.go#L179-L211).
