### ISSUE TITLE
Gems that compliment Flynn.

### ISSUE THREAD

**Issue by WriteCodeEveryday** [flynn/flynn#4130]
Good morning, I recently finished up the first prototype for [flynn_auto_scale](https://github.com/WriteCodeEveryday/flynn_auto_scale) based on the ideas from the Auto Scaling issue (https://github.com/flynn/flynn/issues/2209#issuecomment-301605083).

Could we get a small section on the wiki for libraries / gems and plugins that interface with Flynn?

I'm not asking for a prime front page location in the README but I've had great luck with "if you build it, they will come" in the past and I'd like to see how many people are willing to sink the time to support the great Flynn ecosystem.

**Comment by lmars** [comment]
@WriteCodeEveryday feel free to open a pull request adding to either the README or the [documentation](https://github.com/flynn/flynn/tree/master/docs/content).

**Comment by titanous** [comment]
Actually, since we don't have a wiki, I think the best way to handle this would be for a community member to maintain a separate `awesome-flynn` style repo so that we don't have to keep our docs up to date with external projects.

**Comment by philiplb** [comment]
Nice idea, I'll start one. :)

**Comment by titanous** [comment]
Thanks @philiplb!
