### ISSUE TITLE
Unable to bootstrap new cluster

### ISSUE THREAD

**Issue by joeczucha** [flynn/flynn#4134]
I'm sure this is server-specific as I've had no problems in the past, but I don't seem able to bootstrap my new dedicated server. 

I installed using:

    sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn)

then:

    sudo systemctl start flynn-host

I then tried to Boostrap using:

    CLUSTER_DOMAIN=myhost.com flynn-host bootstrap --min-hosts 1 --timeout 600

but I get:

    02:36:56.573199 check online-hosts
    02:36:56.575038 require-env require-env
    02:36:56.575065 resource-check resource-check
    02:36:56.576394 run-app discoverd
    02:36:57.294998 run-app flannel
    02:36:57.911810 wait-hosts wait-hosts
    02:37:00.916751 gen-random pg-password
    02:37:00.916807 gen-random pg-password 93d8ae7e5dc14f9d9aaedab10bb4e93f
    02:37:00.916817 run-app postgres
    02:37:31.959536 run-app postgres error: bootstrap: timed out waiting for job event

Log here: 

https://gist.github.com/anonymous/edf4b0d0ae379831347716c9a4d33ba3

Any advice appreciated. Thanks!

**Edit:** Not sure if this is relevant but this box is a SoYouStart dedicated box. I've never had any troubles installing in the past, but that's always been into the cloud (usually Digital Ocean). Perhaps he dedi is missing a dependency that usually comes installed on DO boxes and isn't mentioned in the installation instructions? Just a thought anyway.

**Comment by titanous** [comment]
It looks like `named` is running, which conflicts with discoverd: https://gist.github.com/anonymous/edf4b0d0ae379831347716c9a4d33ba3#file-0-debug-output-log-L804

**Comment by joeczucha** [comment]
Thanks for your quick feedback @titanous 

It turns out that named is provided by the `bind9` package, so I ran:

    apt-get remove bind9 

and everything is now working as expected.

Thanks again!

Joe
