### ISSUE TITLE
Resource-aware scheduling

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#4135]
Presuming a stable core cluster of highly connected predictable nodes, find ways to accommodate nodes that are less predictable in availability, latency, or underlying hardware, for tasks which are intended to run opportunistically on a shifting pool of lower cost hardware or spot priced instances.

Sayeth @titanous:
"The scheduler currently isn't set up for that as it doesn't take into account resource availability and usage. Probably on the order of a few weeks of work. The scheduler isn't exactly the easiest code we have, but its just a matter of learning how it works first."

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
