### ISSUE TITLE
Cluster went down (again)! 

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#4140]
Hi, 

Our cluster went down (again). After running stable for only 20 days (ugh). 
We can't seem to fine a reason why this is happening.  

Running 3 setup cluster (with s3 blockstorage)

**Comment by heldopslippers** [comment]
so on s1. 
Flynn-host list gives me socket errors. 
on s2 or s3:
Flynn-host list gives me 2 operating servers as peer.

**Comment by heldopslippers** [comment]
Ok, so I could be a memory problem. 
 flynn-host fix --min-hosts 3 gives me: 
error getting controller release: unknown_error: Something went wrong

**Comment by heldopslippers** [comment]
After setting back a back, the cluster went down AGAIN last night. Currently the there are a lot of problems. How can this be so unreliable.

**Comment by philiplb** [comment]
What are the specs of the machines? HDD, Cores, RAM.

**Comment by heldopslippers** [comment]
3 times 8GB servers, we are trying to add a server to the cluster. but currently we aren't able to promote it

**Comment by philiplb** [comment]
That's about what we are running with ~50 deployed applications and no hickups. They are up since v20170321 got released.
So the specs itself are fine. Are there any other services running on those machines?

**Comment by heldopslippers** [comment]
nope nothing, we are really not sure why this has happened. We didn't change anything. I think it has something todo with memory problems. Beceause it got very high.

**Comment by philiplb** [comment]
And network connectivity between the nodes? Any big latencies or outages here?

**Comment by heldopslippers** [comment]
nope all very low, that was the first thing I checked. 
We are currently setting up a new cluster with 4 servers from a backup. Hopefully this will work.

**Comment by philiplb** [comment]
There need to be an uneven amount of consensus nodes, 3 or 5. So with 4 you would take 3 consensus nodes and 1 not-consensus (What was the term here? I mean not promoted. :))
The memory stuff seems interesting. I would recommend to immediatly collect debug information when this happens and post them here. That gives @titanous or @lmars a chance to investigate the root cause.

**Comment by heldopslippers** [comment]
Hi Philip, 

Thanxs for the info. 
I will post the logs. 
(3 peers and one leader). What would be best? adding another?

**Comment by philiplb** [comment]
I'd go for three consensus nodes and one proxy according to https://flynn.io/docs/production#cluster-requirements

**Comment by heldopslippers** [comment]
Ok little update! We are back online! (Yeah!). 
with 4 servers. 
Luckily we had "backy" (our backup app). I will post the code so others can use it as well. 
Also with our recovering script so people now what to do when they encounter a meltdown. 

I would love to see some work on detailed documentation about how to check what is going on when something is wrong.

**Comment by lmars** [comment]
@heldopslippers if you can't collect debug info, please create a tarball of `/var/log/flynn` on each node.

**Comment by heldopslippers** [comment]
@lmars I have the old servers still running, I probably can create a debug log.

**Comment by heldopslippers** [comment]
Just fwi, there is no real upside to adding a proxy in the cluster right? 
If memory was the problem of the cluster meltdown, it would be better to just have 5 peer servers in the cluster.

**Comment by heldopslippers** [comment]
Here is the debug log: https://drive.google.com/file/d/0B_l6au1xMoeCeVcxd012NmhfcW8/view?usp=sharing

**Comment by lmars** [comment]
@heldopslippers looking at one of your PostgreSQL logs (`postgres-postgres-ReloadSEO2-773af32b-52a8-4fd6-b9db-1a98f7c94823.log`), the primary died because it ran out of available memory:

```
t=2017-06-08T22:29:36+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:36+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:36+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:36+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:36+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:36+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:37+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:37+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:37+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
t=2017-06-08T22:29:37+0000 lvl=crit msg="FATAL: a container process was killed due to lack of available memory" component=flynn-host
```

At this point, you had over 250 long-lived connections to PostgreSQL:

```
grep '2017-06-08 22:29:3.*disconnect' postgres-postgres-ReloadSEO2-773af32b-52a8-4fd6-b9db-1a98f7c94823.log | wc -l
     255
```

Is that expected?

Also, I see you have datadog installed on the server, did you get any memory alerts? Datadog should be able to show you that PostgreSQL was reaching this point.

**Comment by heldopslippers** [comment]
Hi Imars, 

250 connections is not expected (we have 3 instances + 1 or 2 sidekiq per app). We run about 15 apps, so it should be around 80 connections. But this could be because of the system removing app instances to free up memory (and then Flynn restarting it again).
Eventually the system would quit flynn critical systems (could this be the case?). 

I did not get a signal from datadog about memory (I don't think I activated it). 
Would it be possible to give mission critical Flynn process a higher priority (so they don't get killed)? Or build in some kind of monitoring so it is detected early?

**Comment by pouledodue** [comment]
@heldopslippers i'd definitely like to see your recovery code ^^

**Comment by lmars** [comment]
@heldopslippers 

> Would it be possible to give mission critical Flynn process a higher priority

If you expect PostgreSQL to use more than the allocated 1GB of RAM, then you can raise the memory limit with:

```
$ flynn -a postgres limit set postgres memory=2GB
```

When the system is running out of total available memory however, it is the Linux kernel which decides which processes to kill. Ideally you run instances with enough RAM to meet your memory requirements and never get into a situation where the kernel needs to kill processes to free up memory.

> build in some kind of monitoring so it is detected early?

This is planned (see #201 and #3484) but I don't believe anyone is currently working on that.

If you are running Datadog, it definitely has the capability to detect these issues and alert you.

**Comment by heldopslippers** [comment]
Thanxs for the update imar. 
I will keep a close eye on the cluster next few weeks.
Clsoing this.
