### ISSUE TITLE
MariaDB reported as unhealthy but working fine

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4144]
Hi,
our cluster seems a bit weird currently: The MariaDB reports as unhealthy but is working just fine. Running flynn-host fix found nothing and didn't have an effect. Is this something to worry about and how do I get out of this state? Scaling the MariaDB application to "mariadb=0 web=0" and back to "mariadb=3 web=2" maybe?
What was the root cause?

Here are the debug logs: https://philiplb.de/misc/2017-06-21_10-50_flynn-host-debug.tar.gz

**Comment by philiplb** [comment]
Anything I can do here? Running a cluster in this state has an uneasy feeling.

**Comment by titanous** [comment]
Based on troubleshooting in IRC:

The MariaDB cluster is in the unhealthy state because the primary did not record a valid downstream after bailing out on monitoring when the sync didn't make forward progress on the xlog in one minute.

Cluster status: https://gist.github.com/philiplb/8365ecb7efc11c56a22a58f22c822bb9

**Comment by philiplb** [comment]
As this doesn't sound too bad of a state, I assume I can leave this cluster in this state and it will recover as soon as I upgrade from a new version via backup/restore. I will do this as soon as the June version is released which I assume will happen any day.

**Comment by philiplb** [comment]
I just tried to recover via resetting the limits:

```bash
flynn -a mariadb limit set web temp_disk=1G
# Now wait for the mariadb logs to settle, there will be some connection errors for a few minutes until the nodes are in sync again.
flynn -a mariadb limit set mariadb temp_disk=1G
```

But that didn't help, still in the same state.

**Comment by philiplb** [comment]
After upgrading to v20170719.0-81418bc via backup&restore, the MariaDB reports as healthy again.

**Comment by philiplb** [comment]
I think I got again in this state. After some random errors in the cluster (blobstore unhealthy, backup failing), the MariaDB is unhealthy again but seems to work fine.

**Comment by philiplb** [comment]
Some weeks ago, a few days ago and today again, our hoster rebooted the host machines of the VM for maintenance and again, the MariaDB didn't came back. It was shown as unhealthy but the apps could connect to it just fine.
But the weird thing: The first two times, it travelled back in time and the DB switched to an old state. One time "only" a few days were missing and one time it went to a state being about two month old.
We could restore the cluster from backups right before the reboots and I then could restore the work of some customers of the day manually. But this is scary.
So as it happened today again, I moved all the production DBs to a classic MySQL server until this issue is resolved and the MariaDB survives a reboot of the infrastructure.
Most of our dev and staging DBs are still running via Flynn though.
This also brings me into the position to be able to debug this "live" with you without the need to restore everything immediatly.

**Comment by philiplb** [comment]
My attempts to fix it:
- flynn-host fix did nothing
- flynn -a mariadb scale mariadb=0 web=0 && flynn -a mariadb scale mariadb=3 web=2 showed some action of the MariaDB in the logs ending with two lines "could not connect to <ip>" (two different IPs)

A shame I needed to bring this back up real quick and forgot to collect logs.

**Comment by philiplb** [comment]
So our hoster did some maintenance again and one of the VMs got rebooted. MariaDB didn't survive again.
So currently, the MariaDB is useless for us and all DBs will be moved to a dedicated server.

**Comment by philiplb** [comment]
Hi,
so this happened again after a reboot of one of the EC2-instances.
This is currently the only bug for us making Flynn a bit unreliable by not surviving a reboot of a node.
@titanous Could you give me some hints about how to fix it? I would like to give it a go and create a PR if successful.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
