### ISSUE TITLE
Issue with heroku-buildpack-emberjs

### ISSUE THREAD

**Issue by joeczucha** [flynn/flynn#4145]
I'm trying to use the official [Heroku Ember CLI build pack ](https://github.com/heroku/heroku-buildpack-emberjs) but it comes in a weird form: 

https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz

Does Flynn support this? I tried adding it to a .buildpacks file but I get the following:

    git push flynn master
    Counting objects: 590, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (553/553), done.
    Writing objects: 100% (590/590), 16.32 MiB | 2.14 MiB/s, done.
    Total 590 (delta 274), reused 0 (delta 0)
    -----> Building testapp...
    -----> Multipack app detected
           =====> Downloading Buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz
           =====> Detected Framework: emberjs

           EmberJS Buildpack

           Usage:
           buildpack detect <build-dir>
           buildpack compile <build-dir> <cache-dir> <env-dir>
           buildpack release <build-dir>
           buildpack test-compile <build-dir> <cache-dir> <env-dir>
           buildpack test <build-dir> <env-dir>
           buildpack (-v | --version)
           buildpack (-h | --help)

    remote: ERROR: Build failed: exec: job exited with status 255
    To https://git.mydomain.com/testapp.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'https://git.mydomain.com/testapp.git'

Tested and working on Heroku. Thanks in advance.

**Comment by titanous** [comment]
@joeczucha Thanks for the report! Can you provide a link to an example app that should work with this buildpack?

**Comment by joeczucha** [comment]
No problem - here is an example app: https://github.com/joeczucha/flynn-ember-test

Deployed to Heroku: https://flynn-ember-test.herokuapp.com/

Log (not sure if this is useful but just in case!):

    Joes-iMac:flynn-test-app joe$ git push heroku master
    Counting objects: 3, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (3/3), done.
    Writing objects: 100% (3/3), 314 bytes | 0 bytes/s, done.
    Total 3 (delta 2), reused 0 (delta 0)
    remote: Compressing source files... done.
    remote: Building source:
    remote:
    remote: -----> Node.js app detected
    remote:
    remote: -----> Creating runtime environment
    remote:
    remote:        NPM_CONFIG_LOGLEVEL=error
    remote:        NPM_CONFIG_PRODUCTION=true
    remote:        NODE_VERBOSE=false
    remote:        NODE_ENV=production
    remote:        NODE_MODULES_CACHE=true
    remote:
    remote: -----> Installing binaries
    remote:        engines.node (package.json):  >= 4
    remote:        engines.npm (package.json):   unspecified (use default)
    remote:
    remote:        Resolving node version >= 4 via semver.io...
    remote:        Downloading and installing node 8.1.2...
    remote:        Using default npm version: 5.0.3
    remote:
    remote: -----> Restoring cache
    remote:        Loading 2 from cacheDirectories (default):
    remote:        - node_modules (not cached - skipping)
    remote:        - bower_components (not cached - skipping)
    remote:
    remote: -----> Building dependencies
    remote:        Installing node modules (package.json)
    remote:
    remote:        > fsevents@1.1.2 install /tmp/build_0f327abac286eb3a010dadf207b20a75/node_modules/fsevents
    remote:        > node install
    remote:
    remote:
    remote:        > spawn-sync@1.0.15 postinstall /tmp/build_0f327abac286eb3a010dadf207b20a75/node_modules/spawn-sync
    remote:        > node postinstall
    remote:
    remote:        added 928 packages in 31.23s
    remote:
    remote: -----> Caching build
    remote:        Clearing previous node cache
    remote:        Saving 2 cacheDirectories (default):
    remote:        - node_modules
    remote:        - bower_components (nothing to cache)
    remote:
    remote: -----> Build succeeded!
    remote: -----> Discovering process types
    remote:        Procfile declares types     -> (none)
    remote:        Default types for buildpack -> web
    remote:
    remote: -----> Compressing...
    remote:        Done: 36.3M
    remote: -----> Launching...
    remote:        Released v4
    remote:        https://flynn-ember-test.herokuapp.com/ deployed to Heroku
    remote:
    remote: Verifying deploy... done.
    To https://git.heroku.com/flynn-ember-test.git
       1e6a9ff..555bf0d  master -> master

Then attempted to deploy the same app to Flynn:

    Joes-iMac:flynn-test-app joe$ git push flynn master
    Counting objects: 43, done.
    Delta compression using up to 8 threads.
    Compressing objects: 100% (39/39), done.
    Writing objects: 100% (43/43), 8.34 KiB | 0 bytes/s, done.
    Total 43 (delta 4), reused 0 (delta 0)
    -----> Building flynn-ember-test...
    -----> Multipack app detected
           =====> Downloading Buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/emberjs.tgz
           =====> Detected Framework: emberjs

           EmberJS Buildpack

           Usage:
           buildpack detect <build-dir>
           buildpack compile <build-dir> <cache-dir> <env-dir>
           buildpack release <build-dir>
           buildpack test-compile <build-dir> <cache-dir> <env-dir>
           buildpack test <build-dir> <env-dir>
           buildpack (-v | --version)
           buildpack (-h | --help)

    remote: ERROR: Build failed: exec: job exited with status 255
    To https://git.mydomain.com/flynn-ember-test.git
     ! [remote rejected] master -> master (pre-receive hook declined)
    error: failed to push some refs to 'https://git.mydomain.com/flynn-ember-test.git'

Let me know if I can help further. Thanks for investigating :)

**Comment by philiplb** [comment]
@joeczucha sry, OT: mind if I put your ember sample into https://github.com/philiplb/awesome-flynn ? :)

**Comment by joeczucha** [comment]
Ha, so I just tried removing the .buildpacks file and deploying the app without specifying one. You'll never guess what... it worked! 

Now I feel pretty stupid :)

**Comment by titanous** [comment]
💯
