### ISSUE TITLE
Where to start debugging when the cluster goes down?

### ISSUE THREAD

**Issue by itsMichaelBates** [flynn/flynn#4146]
I deployed a cluster of three Ubuntu 16.04 nodes running Flynn v20170514.0-a013e9a with 20GB EBS disks on AWS (t2.medium size). About 10 hours after deploying these nodes 2/2 web apps hosted on these nodes failed to respond to requests (the browser displayed "Service Unavailable"). Also, the Dashboard and Status page was unavailable too (long request time and then "Service Unavailable" or a timeout). And the flynn (client) CLI timed out with a TCP timeout (I can't remember the exact error, but it was to do with the TCP connection timing out).

Because I'm new to Flynn, I had no idea how to debug this issue (which is bad when your site gets a fair amount of traffic (~300,000 page views per month).

I ended up restarting the flynn-host service and that brought everything back to life. I also changed the web server I was using for one of the apps (Python) from Gunicorn to Waitress. (the other app is a nodejs app).

About 10 hours later the cluster went down in the same fashion as before. This time I tried to do a little debugging, but I'm not very familiar with Flynn, so wasn't sure where to start looking. What I did notice is the router app was getting heaps of `too many open files; retrying in 140ms`. I don't know if this is useful, but from looking around the issues on this repo it sounds like others with this issue have similar symptoms to my problem.

In the end I recreated the cluster from backup with t2.large size nodes and 50GB EBS volumes in the hope that that will help.

My question is where should we start when debugging Flynn? There isn't really much mentioned on the topic in the docs.

And if anyone has any ideas on this issue me and my users would be very much appreciative!

Thanks

**Comment by titanous** [comment]
It sounds like this issue was caused by the router running out of file descriptors (by default the limit is 10k fds per router instance). Do you use CloudFlare? We've seen an issue in the past where their edge cache keeps thousands of connections open, exhausting the fd limit (#3470).

As far as debugging Flynn goes, looking at the logs is usually the place to start. `flynn-host` on the servers provides access to them if the `flynn` CLI isn't working.

**Comment by itsMichaelBates** [comment]
Unfortunately this only solved the problem for longer before going down again. I am using Cloudflare however I've since moved this app to Heroku as we were suffering too much downtime.

It might be something to look into though. Thanks for your help.
