### ISSUE TITLE
Confused about updating a cluster

### ISSUE THREAD

**Issue by itsMichaelBates** [flynn/flynn#4147]
According to the docs at https://flynn.io/docs/production#backup/restore, the correct way to update a cluster is to take a backup, provision a new cluster using the steps at https://flynn.io/docs/installation/manual and run the bootstrap command like so:

```
$ sudo \
    CLUSTER_DOMAIN=yourdomain.com \
    flynn-host bootstrap \
    --min-hosts 3 \
    --discovery https://discovery.flynn.io/clusters/53e8402e-030f-4861-95ba-d5b5a91b5902
    --from-backup backup.tar
```

Do I have to update the DNS records _before_ bootstrapping or after the bootstrap? I guess what I'm asking is how does flynn know which nodes to provision (my guess is the discovery URL).

The docs confused me because I thought I had to change the DNS to the new nodes before running the bootstrap (resulting in downtime). Maybe some explanation in the section on Backup/Restore could clear things up a little.

**Comment by titanous** [comment]
Bootstrapping doesn't rely on the DNS, so to do a zero downtime update, you'd restore the backup to a new cluster, confirm that everything is working, and then switch over the DNS.

**Comment by titanous** [comment]
Also, it's worth noting that the discovery URL needs to be new for each new cluster that you start.
