### ISSUE TITLE
How to use it without domain?

### ISSUE THREAD

**Issue by dilame** [flynn/flynn#4148]
I just want to run one worker without domain. How can i do it with flynn? Is it possible? What if i want to run more workers?

**Comment by titanous** [comment]
I'm not sure what you're asking? Can you describe in more detail what you're looking to do?

**Comment by dilame** [comment]
@titanous i just want to use my VPS like heroku. I have app that recieve jobs from AMQP server and do some job. This app has no domain, and dont need it. How to set up my VPS  with Ubuntu 16.04 to  work with flynn? I didn't find information about it in documentation.

**Comment by pouledodue** [comment]
I used xip.io where any IP points to your server like 1.2.3.4.xip.io will point to ip 1.2.3.4
but I don't know if it's the right way

**Comment by lmars** [comment]
`CLUSTER_DOMAIN` is used as a DNS name under which all of the Flynn apps can be reached via HTTP.

If you don't want to reach any Flynn apps via HTTP, then you can set the `CLUSTER_DOMAIN` to whatever you want (e.g. `example.com`).

If you want the Flynn CLI to work from your machine (which accesses the controller app over HTTP), you will need to point `controller.example.com` at the IP of your cluster (for example in `/etc/hosts`), and if you want `git push` to work then you will also need to point `git.example.com` at your cluster.

As @pouledodue mentioned, you can also use a [xip.io](http://xip.io/) domain as `CLUSTER_DOMAIN`, but we have found that service to be unreliable in the past (sometimes failing to return any A records).
