### ISSUE TITLE
Using SSL cert from LetsEncrypt throws error in Chrome

### ISSUE THREAD

**Issue by itsMichaelBates** [flynn/flynn#4149]
A few of our users have reported that they are getting the error `ERR_CERT_AUTHORITY_INVALID` in Chrome when browsing to an app hosted on Flynn (host version `v20170514.0-a013e9a`) .

If I put Cloudflare in front of the app the error goes away, but as soon as I remove it the same users report this issue.

Any ideas?

**Comment by titanous** [comment]
@itsMichaelBates It's possible that you are not adding the intermediate certificate, which should follow the leaf certificate in the certificate PEM file when creating/updating the route.

**Comment by itsMichaelBates** [comment]
How would I go about doing that?

I'm adding the cert like so:

```
flynn route update <route-id> --tls-cert=cert.crt --tls-key=cert.key
```

Am I doing it wrong?

**Comment by titanous** [comment]
That command is correct, but you need to confirm that the cert file is in the correct format (leaf certificate followed by intermediate, both in PEM format).
