### ISSUE TITLE
Current HEAD build fails

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4152]
Hi,
I just freshly cloned  ce67ec4 and tried to build it. But it fails: https://gist.github.com/philiplb/d16c266f2b8fb106aca815bde6f4baf7
What might cause this?

**Comment by lmars** [comment]
Do you have any untracked files in your tree? I suspect there are some old files which are being included in the build (no code on master references `Godeps/_workspace` anymore).

**Comment by philiplb** [comment]
Ah, I had this from some time ago in my local $GOPATH and gogland decided to generate the import "github.com/flynn/go-tuf/Godeps/_workspace/src/github.com/flynn/go-docopt" in the file I edited causing the build in vagrant to fail.
Thank you, it's building just fine now. :)
