### ISSUE TITLE
Postgres hanged, Flynn not working anymore

### ISSUE THREAD

**Issue by goocastro** [flynn/flynn#4155]
I am running Flynn in 3 nodes. For some reason Flynn is not working anymore, I can't access any app on it, not even the dashboard.

The closest I got from finding the origin of the problem is the postgres hanged:

    ubuntu@ip-172-31-4-226:~$ sudo flynn-host ps
    ID                                                 STATE    CREATED             CONTROLLER APP  CONTROLLER TYPE  ERROR
    ip1723113225-06fd350f-54de-4ea1-bba6-ebf07a153f16  running  About a minute ago  postgres        postgres         
    ip1723113225-c6893210-1596-4f7b-877a-d541d0597cf6  running  4 minutes ago       discoverd       app              
    ip1723113225-239d044c-5dd5-4a5d-aca1-0e3532bead9b  running  4 minutes ago       flannel         app              
    ip172314226-0f268fcc-2cfa-4398-ab41-57bd061e6133   running  36 minutes ago      postgres        postgres         
    ip17231928-4d643bee-9c53-4df1-8714-3cd16d8ba21d    running  37 minutes ago      discoverd       app              
    ip17231928-92f58f6d-fb8b-4d3a-9c09-85854b28700e    running  37 minutes ago      flannel         app              
    ip172314226-fa1d7aec-5954-4971-b145-34657b48d0b6   running  38 minutes ago      discoverd       app              
    ip172314226-1c3d4eb8-d400-40b1-87b4-ab2282b2c988   running  38 minutes ago      flannel         app   

As you can see above, only two instances of postgres, not three, and one of them are not getting up, the logs only says 'postgres is not runnig', and I have no idea how to get my Flynn working again.

    ubuntu@ip-172-31-4-226:~$ sudo flynn-host log ip172314226-0f268fcc-2cfa-4398-ab41-57bd061e6133
    t=2017-06-26T22:26:16+0000 lvl=info msg="db init" app=postgres component=peer online=false setup=false
    t=2017-06-26T22:26:16+0000 lvl=info msg="starting event handler" app=postgres component=discoverd fn=receiveEvents
    t=2017-06-26T22:26:16+0000 lvl=info msg="discoverd init" app=postgres component=peer peers=0 state=true
    t=2017-06-26T22:26:16+0000 lvl=dbug msg=moving app=postgres component=peer
    t=2017-06-26T22:26:16+0000 lvl=info msg="starting state evaluation" app=postgres component=peer fn=evalClusterState
    t=2017-06-26T22:26:16+0000 lvl=info msg="assuming unassigned role" app=postgres component=peer role=unassigned fn=assumeUnassigned
    t=2017-06-26T22:26:16+0000 lvl=info msg="reconfiguring database" app=postgres component=peer fn=applyConfig
    t=2017-06-26T22:26:16+0000 lvl=dbug msg="skipping stop, already offline" app=postgres component=peer fn=applyConfig
    t=2017-06-26T22:26:16+0000 lvl=info msg="applied database config" app=postgres component=peer fn=applyConfig
    t=2017-06-26T22:26:16+0000 lvl=info msg="skipping config apply, no changes" app=postgres component=peer fn=applyConfig
    t=2017-06-26T22:26:16+0000 lvl=dbug msg="at rest" app=postgres component=peer fn=rest
    t=2017-06-26T22:26:16+0000 lvl=info msg="discoverd peers" app=postgres component=peer peers=1
    t=2017-06-26T22:26:16+0000 lvl=dbug msg=moving app=postgres component=peer
    t=2017-06-26T22:26:16+0000 lvl=info msg="starting state evaluation" app=postgres component=peer fn=evalClusterState
    t=2017-06-26T22:26:16+0000 lvl=dbug msg="at rest" app=postgres component=peer fn=rest
    t=2017-06-26T22:26:16+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:16+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=info msg="discoverd peers" app=postgres component=peer peers=2
    t=2017-06-26T22:26:17+0000 lvl=dbug msg=moving app=postgres component=peer
    t=2017-06-26T22:26:17+0000 lvl=info msg="starting state evaluation" app=postgres component=peer fn=evalClusterState
    t=2017-06-26T22:26:17+0000 lvl=dbug msg="at rest" app=postgres component=peer fn=rest
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:17+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:18+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:19+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:20+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:20+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"
    t=2017-06-26T22:26:20+0000 lvl=eror msg="error getting postgres info" app=postgres component=http fn=handleGetStatus err="postgres is not running"

    // And it continues for a lot of lines...

Any ideas?

**Comment by goocastro** [comment]
I can't even debug it.

When I try to run `collect-debug-info`

    ubuntu@ip-172-31-4-226:~$ sudo flynn-host collect-debug-info
    INFO[06-28|09:28:15] uploading logs and debug information to a private, anonymous gist
    INFO[06-28|09:28:15] this may take a while depending on the size of your logs
    INFO[06-28|09:28:15] getting flynn-host logs
    INFO[06-28|09:28:46] getting scheduler state
    EROR[06-28|09:28:56] error getting scheduler state            err="Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: 
    getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-schedul
    er/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.
    0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/controller-scheduler/leader: dial tcp 127.0.0.1:1111: getsockopt

**Comment by titanous** [comment]
It sounds like discoverd is down, you could manually collect the logs from `/var/log/flynn` (make sure you omit any sensitive app logs).
