### ISSUE TITLE
Docker v17.06.0-ce deprecated --email flag from docker login

### ISSUE THREAD

**Issue by deini** [flynn/flynn#4156]
Docker v17.06.0-ce got released today [Changelog](https://docs.docker.com/release-notes/docker-ce/#17060-ce-2017-06-28)

Which remove deprecated --email flag from docker login breaking flynn's docker login

```
❯ flynn docker login
error running `docker login`: exit status 125 - output: {"unknown flag: --email\nSee 'docker login --help'.\n" '\x00' "\x00\x00\x00\x00" "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" '\x00'}
```

**Comment by bmv437** [comment]
Looks to be this line here.
https://github.com/flynn/flynn/blob/master/cli/docker.go#L134

I'm having the same issue, and it's breaking my CI pipeline. Gonna whip up a PR today.
