### ISSUE TITLE
Setting mariadb limits results in `sirenia cluster in singleton mode`

### ISSUE THREAD

**Issue by alecgorge** [flynn/flynn#4158]
I am migrating some apps to flynn. I'm only running a single node, but I expect to have both a postgres db and a mariadb that exceed 1GB in space.

I'm migrating the mariadb first and I am unable to run some queries/import all the data because it fails with something like this: `Error writing file '/tmp/MYzoll0t' (Errcode: 28 "No space left on device")`

I am not short on inodes or disk space on the node and when I try to increase temp_disk, it fails with a rather cryptic error message and exit code `1`.

```
alecgorge@Alecs-iMac ~/D/c/r/iguana (master)> flynn -a mariadb ps
ID                                                            TYPE     STATE  CREATED       RELEASE
domain.com-6b711e3f-a10f-466b-a669-e1e15891c794  web      up     4 days ago    6805510c-c0a4-4430-9cda-67e65c19694c
domain.com-3e8cf246-9dde-4edc-a1c4-b578b22ec41a  mariadb  up     13 hours ago  6805510c-c0a4-4430-9cda-67e65c19694c
alecgorge@Alecs-iMac ~/D/c/r/iguana (master)> flynn -a mariadb limit set mariadb temp_disk=2GB
sirenia cluster in singleton mode
alecgorge@Alecs-iMac ~/D/c/r/iguana (master) [1]> flynn -a mariadb limit
mariadb:  cpu=1000  max_fd=10000  memory=1GB  temp_disk=100MB
web:      cpu=1000  max_fd=10000  memory=1GB  temp_disk=100MB
domain.com ~/D/c/r/iguana (master)> flynn -a mariadb limit set web temp_disk=2GB
sirenia cluster in singleton mode
alecgorge@Alecs-iMac ~/D/c/r/iguana (master) [1]>
```

I attempted to gather debug logs but it didn't work:

```
$ sudo flynn-host collect-debug-info
INFO[06-30|08:51:47] uploading logs and debug information to a private, anonymous gist
INFO[06-30|08:51:47] this may take a while depending on the size of your logs
INFO[06-30|08:51:47] getting flynn-host logs
INFO[06-30|08:51:48] getting sirenia metadata
INFO[06-30|08:51:48] getting scheduler state
INFO[06-30|08:51:48] getting job logs
INFO[06-30|08:52:01] getting system information
INFO[06-30|08:52:06] creating anonymous gist
105.19 MB / 105.19 MB [=====================================================================================================================================================================================================================================================] 100.00 % 52.47 MB/s 0sEROR[06-30|08:52:18] unexpected HTTP status: 405
105.19 MB / 105.19 MB [=====================================================================================================================================================================================================================================================] 100.00 % 8.63 MB/s 12s
08:52:18.700958 host.go:166: unexpected HTTP status: 405
```

I deploy everything with `flynn docker push`

**Comment by alecgorge** [comment]
There seems to be space if I run in the container directly:

```
alecgorge@Alecs-iMac ~/D/c/r/iguana (master)> flynn -a mariadb run bash -l
root@01387554-7e41-4fdf-aa89-1b29c58ee821:/# df -h
Filesystem                                                                                 Size  Used Avail Use% Mounted on
overlay                                                                                     97M  1.6M   96M   2% /
tmpfs                                                                                      2.0G     0  2.0G   0% /dev
shm                                                                                         64M     0   64M   0% /dev/shm
tmpfs                                                                                      2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/vda1                                                                                   60G   44G   13G  78% /.containerinit
/dev/zvol/flynn-default/ext2/domain.com-01387554-7e41-4fdf-aa89-1b29c58ee821   97M  1.6M   96M   2% /.container-diff
root@01387554-7e41-4fdf-aa89-1b29c58ee821:/# df -i
Filesystem                                                                                 Inodes  IUsed   IFree IUse% Mounted on
overlay                                                                                     25688     20   25668    1% /
tmpfs                                                                                      505801     16  505785    1% /dev
shm                                                                                        505801      1  505800    1% /dev/shm
tmpfs                                                                                      505801     16  505785    1% /sys/fs/cgroup
/dev/vda1                                                                                 3840000 104712 3735288    3% /.containerinit
/dev/zvol/flynn-default/ext2/domain.com-01387554-7e41-4fdf-aa89-1b29c58ee821   25688     20   25668    1% /.container-diff
root@01387554-7e41-4fdf-aa89-1b29c58ee821:/#
```

I can write files as well to tmp

**Comment by philiplb** [comment]
With flynn run, you start a new container to run the given command in, you don't "login" into a running one.
To increase your available disk space, do something like this:

```bash
flynn -a mariadb deployment timeout 3600
flynn -a mariadb limit set web temp_disk=1G
# Now wait for the mariadb logs to settle, there will be some connection errors for a few minutes until the nodes are in sync again.
flynn -a mariadb limit set mariadb temp_disk=1G
```

**Comment by alecgorge** [comment]
@philiplb thanks for the quick response!

I don't think it worked though. The last two commands both output `sirenia cluster in singleton mode` and I still get the "No space left on device" error.

**Comment by alecgorge** [comment]
Any update? This is a really frustrating issue and the only thing preventing me from fully running on flynn instead of cloud66.

**Comment by titanous** [comment]
This is expected, the parameters of the database appliances cannot be changed on single node clusters. Use a multi-node cluster if you'd like to change these settings.

**Comment by alecgorge** [comment]
@titanous Thank you for your response, but I'm not sure I understand. Can you give me some insight into the reasoning behind this? 

Not being able to run any query that requires writing tables out to MariaDB's `tmpdir` and might exceed 100MB seems like a pretty huge (undocumented) limitation for single node clusters. This isn't a big webservice and doesn't need a cluster.

Is there _any_ workaround (change the default my.conf to put `tmpdir` in /data/tmp or something?) or will I have to migrate off of Flynn?

**Comment by titanous** [comment]
In order to change config parameters with minimal downtime, Flynn does a rolling restart of database instances. When there is only one server, it's not possible to do a rolling restart. All of our production users run multi-node clusters for reliability, so we have not implemented a special case that would allow applying custom configuration to databases in single-node clusters.

**Comment by alecgorge** [comment]
That doesn't seem particularly useful for getting started with Flynn. If I don't mind downtime, can I just search through the code to find the error message and comment out that check?

**Comment by titanous** [comment]
Singleton mode is designed to allow trying out Flynn, but a single server isn't particularly reliable so we don't spend time on features specifically for it. I believe that implementing support for this would require some changes to how deployments work. The place to start looking would be [in the deployer](https://github.com/flynn/flynn/blob/master/controller/worker/deployment/sirenia.go) which is only designed to deploy multi-node clusters.
