### ISSUE TITLE
Routing for DB (a)sync Replicas

### ISSUE THREAD

**Issue by alixaxel** [flynn/flynn#4159]
It would be useful to be able to access the DB replicas (specially the sync one) to offload read-only queries away from the primary.

I haven't seen anything like this in the documentation, and I'm not sure where to start looking for it in the source code.

**Comment by josephglanville** [comment]
This would require touching multiple components.

The database appliances use an abstract state machine for managing replication, this is in the `pkg/sirenia` directory. Right now all nodes are given random IDs and those IDs change when jobs are replaced so are not stable. What could be introduced however is a peer alias that could be published to `discoverd`. i.e `primary`, `sync`, `async-0` for a 3 node cluster.

Once this is done the router could be modified to be aware of these alias labels and you could introduce a new kind of route, lets say we call it an `alias` route that would do a lookup for alias names in the local service cache.

If you are interested I would be happy to provide some additional guidance.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
