### ISSUE TITLE
Questions about Flynn

### ISSUE THREAD

**Issue by agalisteo** [flynn/flynn#4166]
I would like to use flynn in production but I have some questions:

* HTTP Basic Authentication for a specific web app
* Possibility to edit Flynn Webserver and create redirects and rewrites
* Binding TCP services to specific ports between host and apps

**Comment by philiplb** [comment]
* Flynn just routes the traffic to your applications having their server within the container. You define yourself the server and it's configuration. See this example: https://flynn.io/docs/languages/php#apache2
* See above
* You can add TCP routes for specific ports. Flynn will route those to the application processes in their containers

**Comment by agalisteo** [comment]
@philiplb for example, if i want basic auth in my app, i need build my own buildpack with a basic auth webserver like nginx and create a new route in flynn to redirect my http traffic to nginx server inside the container?

**Comment by titanous** [comment]
@agalisteo You should implement basic auth in your app. Each language/framework has a way to do this.
