### ISSUE TITLE
Is it possible to start with one node and later on add more if needed?

### ISSUE THREAD

**Issue by OfekA** [flynn/flynn#4168]
I'm asking this just to make sure since the docs are not 100% clear on that.

If I run `flynn-host bootstrap` without running `flynn-host init --init-discovery` beforehand, will I be able to run this at a later time if needed?

Oh and, thanks for making this amazing software :+1:

**Comment by titanous** [comment]
Single node clusters can't be switched to multi-node clusters, if you want to add nodes in the future you'll need to start with a cluster of three or more nodes.

**Comment by OfekA** [comment]
I assume that the best upgrade path would be to export the necessary apps and import them on the new cluster?

**Comment by titanous** [comment]
You can do that, or do a full cluster backup/restore to a multi-node cluster: https://flynn.io/docs/production#backup/restore

**Comment by OfekA** [comment]
Sounds even better, thank you for you help :)
