### ISSUE TITLE
Incomplete route output in `flynn info` command

### ISSUE THREAD

**Issue by brad-werth** [flynn/flynn#4172]
When running `flynn info`, it outputs the `Web URL:`. This information is obtained from the registered routes, of which there can be more than one. The info command just picks one (seemingly the most recently added, so one cannot just register the "important" one first) to display for the Web URL. I propose that the output be amended to Web URLs:, which would display an ordered list of all of the available routes.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
