### ISSUE TITLE
leader has full swap and high memory pressure

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#4173]
Hi there, 

Our 5 server cluster is working without anyproblem. 
However we see a very high memory pressure and full swap on the leader. 

we are not sure what will happen when is doesn't have any memory left. No good things I suppose. 
What kind of things would we be able to do to change this?

**Comment by titanous** [comment]
Can you determine what process(es) are consuming memory/swap?

**Comment by heldopslippers** [comment]
Hi Titanous, 

I did some checking of the last few days. 
Apparently it is many some sidekiq workers and ruby processes. 
Are those automatically redistributed when pressure on the main gets to high? 
Here is the output of: ps -eo pmem,pcpu,vsize,pid,cmd | sort -k 1 -nr | head -5
11.5  2.9 2517292 5654 sidekiq 4.0.2 app [1 of 1 busy]
 7.8  0.3 1683648 5905 puma 3.7.0 (tcp://0.0.0.0:8080) [app]
 4.9  0.5 1467272 5774 puma 3.6.1 (tcp://0.0.0.0:8080) [app]
 4.0  0.8 1351668 19785 puma 3.6.0 (tcp://0.0.0.0:8080) [app]
 3.8  0.0 1207128 6114 puma 3.6.1 (tcp://0.0.0.0:8080) [app]

**Comment by lmars** [comment]
@heldopslippers 

> Are those automatically redistributed when pressure on the main gets to high?

Flynn currently distributes your app processes evenly across the cluster (so a scale of `worker=6` in a three node cluster would give you 2 per host), but does not currently redistribute jobs based on available system resources.

How many sidekiq processes are you running? You should consider running them across your cluster (i.e. a scale equal to the cluster size) which should lead to the load being more distributed.

**Comment by heldopslippers** [comment]
hi Imars, 

Thanxs for the explanation.
We are running 2 or 3 sidekiq workers per app (we have about 20 apps running). 
Would it make sense to swap out the leader with a bigger server in case this pressure keeps this high?

**Comment by titanous** [comment]
You should ensure that all servers are the same size, otherwise the round-robin scheduling will not be effective.
