### ISSUE TITLE
flynn run fails on Windows with "The handle is invalid"

### ISSUE THREAD

**Issue by braunsonm** [flynn/flynn#4179]
Trying to run a command on my flynn cluster to the app called example returns `The handle is invalid` (not a very descriptive error).

Git remote is added as `https://git.flynn.mydomain.com/example.git`

I should also note that even running this with `flynn -a example run` it still will return an error.

**Comment by lmars** [comment]
This sounds like the same as https://github.com/flynn/flynn/issues/2734.

I suggest running `flynn` from within a bash shell.

**Comment by ChaosMTA** [comment]
This creates some issues though as things such as creating a super user in Django will not work.

```$ flynn run python manage.py createsuperuser
Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.
```

Works fine in Dokku. Plus having to use a bash on windows seems like a valid bug on Flynn.

**Comment by lmars** [comment]
> This creates some issues though as things such as creating a super user in Django will not work.

That error is saying you are running a command without a TTY, but Flynn allocates a TTY if it itself is being run in a TTY (see [here](https://github.com/flynn/flynn/blob/master/cli/run.go#L106)), so are you running `flynn run` in a TTY?

> having to use a bash on windows seems like a valid bug on Flynn.

I don't think it is clear whether or not Flynn is doing anything wrong here, it seems this has more to do with your environment not supporting TTYs correctly.

**Comment by ChaosMTA** [comment]
I'm just running it in git bash. It not working in PowerShell, or cmd for myself and other users seems to be a bug.

**Comment by lmars** [comment]
I unfortunately do not have access to a Windows machine to test this, it may well be a bug but it is hard to clarify without more information.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
