### ISSUE TITLE
Failed to start flynn-host.service: Unit flynn-host.service not found.

### ISSUE THREAD

**Issue by connelevalsam** [flynn/flynn#4182]
install flynn
`sudo bash < <(curl -fsSL https://dl.flynn.io/install-flynn)`
also did
`sudo flynn-host update`
Tried running
`sudo systemctl start flynn-host`
Outputs
`Failed to start flynn-host.service: Unit flynn-host.service not found.`
Also did 
`sudo start flynn-host`
and it output
`Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused`
So now am so confused. Like I want to uninstall it and try installing it again.
But don't know how.

**Comment by lmars** [comment]
@connelevalsam did you get any errors when you ran the install script?

Please run the following and put the full output in a gist so we can see what happens:

```
$ curl -fsSL -o /tmp/install-flynn https://dl.flynn.io/install-flynn
$ sudo bash /tmp/install-flynn --clean
```

**Comment by connelevalsam** [comment]
Thanks @lmars here's the gist:
[https://gist.github.com/connelevalsam/47998a29016c65ce7ff2ee05a029f196](url)

**Comment by titanous** [comment]
@connelevalsam The error in the log you posted has been fixed (#4186), please try again and post a new full log if it fails.

**Comment by connelevalsam** [comment]
@titanous thanks for your reply, are you saying I should install flynn again?

**Comment by lmars** [comment]
@connelevalsam yes try installing from clean again.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
