### ISSUE TITLE
`flynn -a appname log -j jobid` doesn't show logs for down jobs

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#4183]
When you run `flynn -a appname log -j jobid` using the CLI it doesn't show the log for jobs in the down state. However, if you run `flynn-host log jobid` on the host it will show the logs for the down jobs. I thionk it would be beneficial to be able to see these logs from the CLI as well.

**Comment by lmars** [comment]
The Flynn CLI does show logs for down jobs, but the CLI gets those logs from the logaggregator which only stores the last 10,000 log lines for each app (in an in-memory ring buffer), whereas `flynn-host log` gets the logs from disk on the host, which stores up to 200MB per app.
