### ISSUE TITLE
Flynn host failing to start after reboot

### ISSUE THREAD

**Issue by harryspink** [flynn/flynn#4188]
Our Flynn server is failing to start after the server was restarted. We have had to restart the server a number of times before and using the `sudo flynn-host fix --min-hosts 1` we've been able to bring it back online with no problems.

Is there something that we're not spotting that is causing the scheduler not to stay online?

In case it helps, the log files can be found at http://46.101.85.182/flynn-host-debug.tar.gz

Thank you in advance!

**Comment by lmars** [comment]
I think the issue is the large amount of crashed jobs (36,000) that the scheduler is trying to load on start.

Try running the script in the following gist to clean the job database:

https://gist.github.com/lmars/cfb46fe104d1c17be8f22acf41c907e9

**Comment by harryspink** [comment]
Works perfectly. Thank you!
