### ISSUE TITLE
Change the ssl certificate on a cluster

### ISSUE THREAD

**Issue by ConnorPeticca** [flynn/flynn#4189]
I was trying to change the ssl cert on my cluster but every time I would try and change it I would get kicked out of cli saying that "the peer leaf certificate did not match the provided pin"

**Comment by titanous** [comment]
Removing the `TLSPin` from `~/.flynnrc` will fix this.

**Comment by ConnorPeticca** [comment]
Wow, that was fast. Also, what is the best way to actually set the default cert? I saw a suggestion to set the router env vars.

**Comment by titanous** [comment]
The default cert is currently set using those env vars. You'll also need to update the routes for the `controller`, `gitreceive`, `status`, `dashboard`, and `docker-receive` apps.

**Comment by ConnorPeticca** [comment]
What would the commands  be?

**Comment by ConnorPeticca** [comment]
Im getting this error now after updating the controller route

Get https://controller.services.primemc.org/apps/gitreceive/routes: x509: certificate signed by unknown authority

**Comment by titanous** [comment]
That means that your certificate is not trusted by your machine's root store, or you failed to include necessary intermediate certificates in order to form a valid chain to a trusted root.

**Comment by ConnorPeticca** [comment]
Okay so i got the intermediate cert but how do I construct the cert.pem and key.pem

**Comment by titanous** [comment]
The certificate file should be the leaf cert followed by the intermediate, the key file should just be the key.

**Comment by ConnorPeticca** [comment]
Closing, thanks for the help. Your replies were very timely, which I appreciate. I used this thread https://stackoverflow.com/questions/35755252/installing-tls-certificate-in-flynn along with the above replies to solve my issues.
