### ISSUE TITLE
git push flynn master freezes on local instance

### ISSUE THREAD

**Issue by XuryaX** [flynn/flynn#4190]
Hi, 
I have setup flynn on my local machine with the vagrant method. Everything seems to be really simple for deploying an app using flynn.  But when I am deploying an application from the examples, when I push the code to flynn using
`git push flynn master`
The command line freezes when it tries to  install the environment, be it in the given example go application or the example phthon application.
```
root@Shaurya-Z510:/home/xuryax/Desktop/work/flynn-go/python-flynn-example# sudo git push flynn master
Counting objects: 23, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (19/19), done.
Writing objects: 100% (23/23), 3.19 KiB | 0 bytes/s, done.
Total 23 (delta 5), reused 0 (delta 0)
-----> Building pexample...
-----> Python app detected
-----> Installing python-3.6.1
```

Not sure why this is happening.

**Comment by titanous** [comment]
How long did you wait before determining that it had "frozen"? is there any network activity? Usually this is the point where Python is downloaded.

**Comment by XuryaX** [comment]
Around 45 minutes. I figured it would take time, but I don't think it should freeze for 45 minutes for python.Could not see any network activity either.

**Comment by XuryaX** [comment]
It does seem to download. The network activity spikes  up when I run the command. A 6-7  minutes it comes down back. Probably download is completed by this time. But even if it is installing after this, it should not take this long.

**Comment by XuryaX** [comment]
I dont know what the issue was. Restarted a couple of times. Same steps  works  good now.
