### ISSUE TITLE
Bootstrap Failed : wait postgress : discoverd failed waiting for instances.

### ISSUE THREAD

**Issue by XuryaX** [flynn/flynn#4192]
Hi,
After successfully deploying Flynn on my local instance, I am trying to deploy it on my AWS instances.
I am trying to have a cluster of 3 nodes with specs:-
- 2 GB Ram
- 1 Core
- 20 GB HDD

![image](https://user-images.githubusercontent.com/6430258/28682643-469b6f00-731b-11e7-8915-5430f0058dbe.png)

Although this failed, postgres was started on all the instances.
![image](https://user-images.githubusercontent.com/6430258/28682668-5e64ee86-731b-11e7-8577-303cc46a0f21.png)

This seems to be very weird. All the ports are open, initially, I was having some problems with ports, was not sure all the ports which had to be open (like 1113, 1111 which were not mentioned in the docs), so I opened all the TCP ports, to make sure everything worked.
I tried it twice with fresh instances.

After this error, if I close all the processes which were started(like Postgres,discoverd,flannel ), and then run bootstrap again then I don't get past waithosts

wait-hosts wait-hosts error: object_not_found: service not found.

The specs are not as specified by Flynn Docs, but it was just a test setup, when we move to production would use better hardware. It should have at least got setup with these specs as well, I guess.

Please let me know what I am missing because I followed the docs completely. 

-Shaurya

**Comment by mhemrg** [comment]
Same issue. @XuryaX did you find a solution to fix this?
