### ISSUE TITLE
Old release still running

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4193]
Hi,
I have a very weird behaviour: I deployed a golang application to Flynn and did some requests against it. Every now and then I hit an error. This was the behaviour of the app a few releases (days) ago. Diving a bit deeper, I just discovered that there is still an old release running answering every now and then. I scaled the application down to web=0 and the new release isn't answering anymore but now I always get responses from the old one. What happens here and what can I do now?

**Comment by philiplb** [comment]
The cluster is only a few days old. It was restored from backup in order to upgrade to v20170719.0-81418bc which was flawless.

**Comment by philiplb** [comment]
Collecting Debug Logs dies:

> smf@Flynn0:~$ sudo flynn-host collect-debug-info --tarball
> INFO[07-28|14:35:07] creating a tarball containing logs and debug information
> INFO[07-28|14:35:07] this may take a while depending on the size of your logs
> INFO[07-28|14:35:07] getting flynn-host logs
> smf@Flynn0:~$

**Comment by philiplb** [comment]
That seemed to be a symptom of a dying cluster:

[14:40] <philiplb> also the postgres connections don't work anymore.
[14:40] <philiplb> collecting debug infos just dies after "INFO[07-28|14:31:31] getting flynn-host logs"
[14:43] <philiplb> flynn-host fix:
[14:43] <philiplb> "INFO[07-28|14:41:47] ensuring discoverd is running on all hosts"
[14:44] <philiplb> EROR[07-28|14:43:30] error listing jobs                       host=Flynn1 error="Get http://213.73.113.27:1113/host/jobs: read tcp xxx:39538->xxx:1113: read: connection reset by peer"
[14:45] <philiplb> INFO[07-28|14:43:32] checking flannel
[14:45] <philiplb> 14:45:15.883815 host.go:166: error getting jobs list from Flynn1: Get http://213.73.113.27:1113/host/jobs: read tcp xxx:41810->xxx:1113: read: connection reset by peer
[14:45] <philiplb> and dead
[14:51] <philiplb> restoring from backup
[15:08] <philiplb> on restoring: every now and then, it fails to download an image. one of three nodes is reinstalled now. this is not good.

**Comment by philiplb** [comment]
Ok, I restored the cluster from backup. But I leave this ticket open: In case this happens again:
- In case the log collection fails as shown above, what information can I collect to help investigate the root cause?
- My steps after noticing the failing DBs were: Trying to collect the logs, trying to run flynn-host fix. What else should/could I have done?

**Comment by thomasmodeneis** [comment]
I'm having this issue right now.

I have 3 versions of my app running simultaneously:
1) f262d508-388b-419f-b88c-d647cd0ec53b
2) 0af91cad-b16f-4fda-9c2b-3d137d58f1e0
3) a665fd9b-7f82-409f-9ab6-efed4934207d

```
$ flynn ps
ID                                              TYPE  STATE  CREATED            RELEASE
vps431265-283f724a-520e-4431-aab1-28efd8e01ae1  web   up     2 hours ago        f262d508-388b-419f-b88c-d647cd0ec53b
vps431266-1f714ee1-49a8-492b-92b2-3156ad899d59  web   up     2 hours ago        0af91cad-b16f-4fda-9c2b-3d137d58f1e0
vps431267-f1b9c2f5-2618-4369-973d-61dc01e0aaa2  web   up     2 hours ago        f262d508-388b-419f-b88c-d647cd0ec53b
vps431265-6b5854ca-e269-4473-aa5e-f69da420550c  web   up     2 hours ago        0af91cad-b16f-4fda-9c2b-3d137d58f1e0
vps431265-1298bb38-d110-4559-b346-d7cbd5c9661b  web   up     2 hours ago        f262d508-388b-419f-b88c-d647cd0ec53b
vps431265-96f7904b-19c9-4b8e-a660-0f49e2c21cf1  web   up     2 hours ago        0af91cad-b16f-4fda-9c2b-3d137d58f1e0
vps431265-3d49d78d-e52d-4a00-9e18-12d871b480c8  web   up     About an hour ago  a665fd9b-7f82-409f-9ab6-efed4934207d
vps431267-af8fa756-4c9d-4ec5-b2a3-3f937d6573ec  web   up     About an hour ago  0af91cad-b16f-4fda-9c2b-3d137d58f1e0
vps431266-9588fe15-8907-4480-8ea8-a7fb792160bf  web   up     About an hour ago  f262d508-388b-419f-b88c-d647cd0ec53b
```

I have 9 instances of the app running right now, but the scale is supposed to be 1:
```
$ flynn scale
slugbuilder=0 web=1
```

I'm not able to kill any of the running instances:
```
flynn kill vps431266-9588fe15-8907-4480-8ea8-a7fb792160bf
ERROR: could not kill job vps431266-9588fe15-8907-4480-8ea8-a7fb792160bf: unknown_error: Something went wrong
Could not kill all jobs.
```

I'm also not able to delete the app or anything else.
I already re-created the cluster 3x from the backup and always I end-up with the same behaviour.

This is the version the cluster is running on:
```
flynn version
v20170719.0-81418bc
```

Any ideas ?

Thanks.

**Comment by titanous** [comment]
@thomasmodeneis you can use `flynn scale -a` to see the previous releases and `flynn scale -r RELEASE_ID web=0` to scale them down.

**Comment by thomasmodeneis** [comment]
Hi @titanous,
I tried the recommended way to scale down, but its returning me the unknown_error:
```
➜  git:(master) ✗ flynn scale -r e69ffc2e-a06d-49bb-92fa-240492c9ed69 web=0
unknown_error: Something went wrong
➜  git:(master) ✗ flynn scale -r 0af91cad-b16f-4fda-9c2b-3d137d58f1e0 web=0
unknown_error: Something went wrong
➜  git:(master) ✗ flynn scale -r f262d508-388b-419f-b88c-d647cd0ec53b web=0
unknown_error: Something went wrong
```

**Comment by lmars** [comment]
@thomasmodeneis what version of the CLI are you using (`flynn version`)?

Also check `flynn -a controller log -t web -r` just after attempting to scale down, it should include a more informative error.

**Comment by thomasmodeneis** [comment]
Hi @lmars 
Thanks for your prompt answer, I really appreciate that.

I did it and this was the output:
```
t=2017-10-09T07:18:52+0000 lvl=info msg="request started" component=controller req_id=44ac283e-ef13-4784-bf32-8d1654490fce method=PUT path=/apps/myapp/scale/f262d508-388b-419f-b88c-d647cd0ec53b clien
t_ip=5.62.39.34
t=2017-10-09T07:18:52+0000 lvl=eror msg="ERROR: cannot execute UPDATE in a read-only transaction (SQLSTATE 25006)" component=controller req_id=44ac283e-ef13-4784-bf32-8d1654490fce
t=2017-10-09T07:18:52+0000 lvl=info msg="request completed" component=controller req_id=44ac283e-ef13-4784-bf32-8d1654490fce status=500 duration=20.232344ms
```

**Comment by schu34** [comment]
I'm having a similar problem with node.js deployments. I'm able to stop the outdated versions using `flynn kill <job-id>` is there any more permanent solution

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
