### ISSUE TITLE
Backup fails

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4195]
Hi,
the cluster backup just failed with

> error dumping postgres database: error running postgres export: unknown_error: Something went wrong

What should I do now? If the backup doesn't work, I don't dare to keep Flynn in production.

**Comment by philiplb** [comment]
Another try just failed with

> error dumping mongodb database: error running mongodb export: unknown_error: Something went wrong

**Comment by philiplb** [comment]
Another try just failed with

> error dumping mariadb database: error running mariadb export: unknown_error: Something went wrong

**Comment by philiplb** [comment]
And another try just worked.

**Comment by titanous** [comment]
These symptoms make it sound like you have a misbehaving `flynn-host`, check `/var/log/flynn/flynn-host.log` on each server for errors corresponding to the failed backups.

**Comment by philiplb** [comment]
there is a socket leak (flynn-host has 1035 open files according to lsof)
I'll add the stack trace of flynn-host tonight outside our office hours which I will get via sending a SIGQUIT to the flynn-host process.

**Comment by philiplb** [comment]
I'm having the log of the unhealthy reported MariaDB open and just saw this, maybe related. Some time after the SIGQUIT of the faulty flynn-host:

> 2017-07-31T18:34:46.752632Z app[mariadb.Flynn0-e822e222-85ae-4bf3-bd7d-74c085ffe7e3]: goroutine 20 [running]:
> 2017-07-31T18:34:46.752665Z app[mariadb.Flynn0-e822e222-85ae-4bf3-bd7d-74c085ffe7e3]: github.com/flynn/flynn/pkg/sirenia/state.(*Peer).evalClusterState(0xc42014a0f0)
> 2017-07-31T18:34:46.752819Z app[mariadb.Flynn0-e822e222-85ae-4bf3-bd7d-74c085ffe7e3]: 	/go/src/github.com/flynn/flynn/pkg/sirenia/state/state.go:592 +0x1d59
> 2017-07-31T18:34:46.752856Z app[mariadb.Flynn0-e822e222-85ae-4bf3-bd7d-74c085ffe7e3]: github.com/flynn/flynn/pkg/sirenia/state.(*Peer).Run(0xc42014a0f0)
> 2017-07-31T18:34:46.752903Z app[mariadb.Flynn0-e822e222-85ae-4bf3-bd7d-74c085ffe7e3]: 	/go/src/github.com/flynn/flynn/pkg/sirenia/state/state.go:297 +0x2e4
> 2017-07-31T18:34:46.753001Z app[mariadb.Flynn0-e822e222-85ae-4bf3-bd7d-74c085ffe7e3]: created by main.main
> 2017-07-31T18:34:46.753019Z app[mariadb.Flynn0-e822e222-85ae-4bf3-bd7d-74c085ffe7e3]: 	/go/src/github.com/flynn/flynn/appliance/mariadb/cmd/flynn-mariadb/main.go:81 +0xc0b

**Comment by philiplb** [comment]
So I sent the SIGQUIT via sudo kill -3 <flynn-host-pid> and here is the log. I sent it around 2025 and watched everything a bit: https://philiplb.de/misc/2017-07-31-2040.flynn-host.log.tar.gz

**Comment by philiplb** [comment]
And I'm having six MariaDB instances running?

> Flynn0-38d1c730-f40c-4986-a7fa-7607b65ae7f0  running   30 minutes ago  mariadb                                     mariadb
> Flynn0-1fca1ef0-eefd-40ee-b3af-7c3d1b65604e  starting  2 days ago      mariadb
> Flynn1-16e2428c-67fc-44f3-8d36-8447e55ea2fb  running   2 days ago      mariadb                                     mariadb
> Flynn2-4c013c22-a753-44d9-a9e6-2be1fa53c22a  running   2 days ago      mariadb                                     mariadb
> Flynn2-dc92e237-f772-428a-9a9e-b1fd5343e66a  running   2 days ago      mariadb                                     mariadb
> Flynn1-6699a32f-e59f-4c0c-8b6c-a9b1495b5304  running   2 days ago      mariadb                                     web
> Flynn0-72bf1e62-4c58-46d8-8521-92600ba90def  running   2 days ago      mariadb                                     web
> Flynn2-5fc231b4-bd8d-4509-9ebe-d9129513c8f3  running   2 days ago      mariadb                                     mariadb
> Flynn1-0695e295-6f11-4191-8b78-b26474631083  running   2 days ago      mariadb                                     mariadb

"flynn-host stop"ing the oldest ones just restarts them. The scale is the default "mariadb=3 web=2".

**Comment by philiplb** [comment]
And I'm afraid the MariaDB is behaving a bit strange. Every now and then a specific application goes down here. And being written in PHP, there is no permanent DB connection.

**Comment by philiplb** [comment]
Collecting logs still fails, I tried 2 of 3 nodes:

> INFO[07-31|21:53:40] creating a tarball containing logs and debug information
> INFO[07-31|21:53:40] this may take a while depending on the size of your logs
> INFO[07-31|21:53:40] getting flynn-host logs
> smf@Flynn1:~$ echo $?
> 137

**Comment by philiplb** [comment]
I restored the cluster from backup and it hums happily along.
The MariaDB still has 6 mariadb processes. I'm starting to think this is normal. Is it?

**Comment by philiplb** [comment]
Might the leak have been related to this? https://github.com/flynn/flynn/pull/4212

**Comment by philiplb** [comment]
This leak (or something else?) caused a third meltdown out of nothing yesterday. I start to move our production databases out of Flynn to an own server now.

**Comment by philiplb** [comment]
Didn't happen again, so closing it for now.
