### ISSUE TITLE
dial tcp: i/o timeout on all flynn CLI commands

### ISSUE THREAD

**Issue by mltsy** [flynn/flynn#4196]
I'm hoping to solve this on my own and post a solution, but so far I'm stumped:

I had a working configuration on my Ubuntu 16.04 machine for several months, and recently when I tried to connect, I am suddenly getting `Get [url]: dial tcp: i/o timeout` on every command.  I tried restarting the machine, re-installing the CLI, removing .flynnrc and re-adding clusters (timed out trying to add them).  The only think I can think that I've changed since the last time it worked was to instlal a bunch of software updates recommended by Ubuntu's "Software Updater", which installed a few hundred updates to various libraries, so it's very possible one of those is causing the problem.

The really odd thing though is that I'm able to send a request to the controller API endpoint mentioned in the timeout message, and get a perfectly good response using curl or postman, or any other HTTP client that allows basic authentication, but for some reason the CLI is timing out.

**Comment by mltsy** [comment]
Okay, we figured out how to fix the issue, although I'm still not sure what was causing it.  We circumvented dnsmasq on my machine (by setting set the DNS server for the internet-connected interface to an external DNS server address), and it started working like a charm!

What is still inexplicable is the fact that every attempt to request something from the controller API URL worked fine, except for flynn CLI commands.  Does the Flynn CLI do something unusual when resolving the hostname?  (We did notice that when running `strace flynn apps` it would occasionally work, whereas without `strace` it always failed... FWIW)

I'll leave this open, just in case someone wants to request more info or attempt to reproduce the error, but feel free to close it otherwise.

**Comment by titanous** [comment]
The path for DNS resolution is completely different, the Flynn CLI does DNS resolution directly using the system-configured resolver instead of using `getaddrinfo`, so it sounds like either`getaddrinfo` was returning a different address than dnsmasq due to caching or the Flynn CLI was not getting a response from dnsmasq for some reason.

**Comment by mltsy** [comment]
Ah, perfect!  Thanks for the explanation.  Yeah, dnsmasq isn't running anymore, so I'm not sure how it was responding previously now (or not responding, as the case may be).  Seems like it was the culprit in any case, but dang... that was a tricky one!  It would be great if there were some indication that it could be a DNS issue when the timeout happens (or if Flynn could fallback to getaddrinfo?), but perhaps this issue being filed will be enough guidance for someone in the future. :smile:
