### ISSUE TITLE
Set database appliance limits on bootstrap

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#4197]
We have a need to set the database appliance limits on a single node cluster. Currently it is not possible to do this with Flynn. I would be interested in taking a look at making the changes to the `flynn-host bootstrap` code to allow you to pass an option or environment variable to bootstrap to set the database limits.

Can someone point me to the place in the `flynn-host bootstap` code this would need to happen?

**Comment by titanous** [comment]
You'd need to modify the [manifest](https://github.com/flynn/flynn/blob/master/bootstrap/manifest_template.json) and potentially the associated code in the same directory.

**Comment by bbaptist** [comment]
So the manifest is a json list of releases to send to the `flynn-host bootstrap`? I would just need to add a block like this under processes - postgres? Obviously filling the values from an ENVVAR like `CLUSTER_DOMAIN`
```json
"postgres": {
      "resources": {
        "temp_disk": {
          "limit": 104857600,
          "request": 104857600
        },
        "memory": {
          "limit": 4294967296,
          "request": 4294967296
        },
        "max_fd": {
          "limit": 10000,
          "request": 10000
        },
        "cpu": {
          "limit": 1000,
          "request": 1000
        }
      },
```

**Comment by titanous** [comment]
Yeah, something along those lines should work. The code corresponding to each step type is in the `bootstrap/` directory of the source tree.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
