### ISSUE TITLE
Log Sink Support

### ISSUE THREAD

**Issue by XuryaX** [flynn/flynn#4202]
Hi, 
I found that remote syslog servers are supported.
https://github.com/flynn/flynn/pull/3606

But it has not been documented on how to use the syslog inside an app. Does this just push the logs we can see on the dashboard to a syslog server?

I was trying to connect to the syslog socket inside the container -> /dev/log but was not able to.

Basically I get these errors:-

> File "/app/.heroku/python/lib/python3.5/logging/handlers.py", line 834, in _connect_unixsocket
>        self.socket.connect(address)
>        FileNotFoundError: [Errno 2] No such file or directory
> 

Is it lack of documentation provided?

**Comment by titanous** [comment]
That change added support for sending all log lines from the Flynn cluster to a syslog server. Flynn automatically collects all lines output to stdout/stderr and does not provide a syslog socket inside of app containers.
