### ISSUE TITLE
Install TLS cert: .flynn/ca-cert is not updated

### ISSUE THREAD

**Issue by n0daft** [flynn/flynn#4205]
I recently created a new 3-node cluster (v20170719.0-81418bc) with a custom domain right from the start. After that, I installed an officially certified wildcard TLS certificate by setting the router environment variables and updating the routes of `dashboard`, `gitreceive`, `docker-receive` and `controller`. I then calculated the TLS pin and updated flynnrc.

Everything worked fine except I wasn't able to manually `git push` to the cluster. I always received the message 
```
fatal: unable to access 'https://git.somedomain.ch/sample.git/': SSL: certificate verification failed (result: 5)
```

I had to manually replace the `clusteralias.pem` file in `.flynn/ca-certs` folder with the new `chain-bundle.pem` to make it work.

Is this the expected behavior or did I miss something?

**Comment by titanous** [comment]
Yes, I believe this is expected, you can remove the relevant `sslCAInfo` config option in `~/.gitconfig` to fix it.
