### ISSUE TITLE
SLUGBUILDER_DEFAULT_MEMORY_LIMIT seems to be ignored

### ISSUE THREAD

**Issue by n0daft** [flynn/flynn#4206]
I recently created a new 3 node cluster. The first app I wanted to deploy failed with the following error:

```
node-v6.2.0-linux-x64/bin/node'' finished with non-zero exit value 137
```

After some search in your issues I found It is caused by the slugbuilder running out of memory (https://github.com/flynn/flynn/issues/3107). In response to the issue https://github.com/flynn/flynn/issues/3108 a variable `SLUGBUILDER_DEFAULT_MEMORY_LIMIT ` has been introduced. 

So I deleted the failed app and set the variable according to the [docs](https://flynn.io/docs/apps#slugbuilder-limits):

```
limit=SLUGBUILDER_DEFAULT_MEMORY_LIMIT=4GB
flynn -a gitreceive env set $limit
flynn -a taffy env set $limit
```

I tried to redeploy the app but it still fails with the same error. It seems the variable is ignored. I was able to deploy the app with the cli by separating the steps:

```
cd sample
flynn create sample
flynn -a sample limit set slugbuilder memory=4GB 
git push flynn master
```

But then I don't have any source history for the app but a scalable process type `slugbuilder` in the dashboard instead. How can apps in the Dashboard be deployed for the first time without running into memory problems?

**Comment by thomasmodeneis** [comment]
I usually have to increase the Disk and the Memory together for each app.
This is only needed for nodejs deployments as they tend to consume so much more memory and disk.
So as a collateral effect I avoid building the dist compiled files on the buildpack, and use the buildpack only to install the dependencies. Also changing from NPM to YARN helps ALOT.

`flynn limit set slugbuilder temp_disk=2GB`
`flynn limit set slugbuilder memory=2GB`

Please let me know if the issue persists.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
