### ISSUE TITLE
Zero-downtime with docker, how to wait program running inside container?

### ISSUE THREAD

**Issue by roquie** [flynn/flynn#4207]
How to wait a 10s, when I'm deploying docker container, between starting/up states? My app starts inside a docker container after 10s and this time app is unavailable.
![screen shot 2017-08-12 at 16 11 39](https://user-images.githubusercontent.com/3214290/29241093-30ce11d4-7f7b-11e7-9ba3-045f602d13ed.png)

**Comment by theodorton** [comment]
Not a solution to your problem, but docker has support for healthchecks. If healthchecks have been defined for an image, flynn should wait for the new docker container to be considered healthy before replacing the old one (blue/green deployment).

**Comment by roquie** [comment]
Thanks!
