### ISSUE TITLE
Flynn host failing to start after reboot

### ISSUE THREAD

**Issue by roquie** [flynn/flynn#4208]
After `reboot` command, flynn failing to start.
`flynn-host fix --min-hosts 1` logs see here (with full `flynn-host.log` log file): https://gist.github.com/roquie/f0a596c493d380c84aad41704261daa6

This gists does not help me https://github.com/flynn/flynn/issues/4188
`flynn-host collect-debug-info` see here: https://gist.github.com/3ffcfda67ace25a5ece36d3657c85353

In the debug info, I see error: `failed to connect to container`.

How to fix that?

**Comment by lmars** [comment]
@roquie I suspect running Docker is causing the issue as it creates conflicting iptables rules. Disable Docker from running on start and reboot again.

**Comment by roquie** [comment]
Yes, you're right. Thanks.

@lmars What can you say about this https://github.com/flynn/flynn/issues/4207 issue? It's possible?
