### ISSUE TITLE
Process from a docker app still running after removing app

### ISSUE THREAD

**Issue by nicolasblanco** [flynn/flynn#4210]
Hello.

I've created an app and pushed to it a docker image by following the flynn guide, Docker section. After playing around with the app, I've removed it completely.
But on the host where my flynn is running, the process run by the docker image is still present and running (using `top` & `htop`).
I even tried to restart the whole instance, the process is still there running.

How can I debug this?
Thanks for your ideas.

**Comment by lmars** [comment]
Check `flynn -a APPNAME scale --all` and scale down any running releases with `flynn -a APPNAME scale -r RELEASE app=0`

**Comment by nicolasblanco** [comment]
Thanks for your comment @lmars but the app was removed so when I try to specify the old app name with -a I get an error:
`No app release, specify a release with --release`

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
