### ISSUE TITLE
Formatting of the log strings

### ISSUE THREAD

**Issue by AlexandrPy** [flynn/flynn#4211]
Hi! I cannot find any info about the format of the log strings. Currently, it gives me too much useless info. Is there any possibility to change the format?

**Comment by kwando** [comment]
Which logs? flynn-host logs or app logs?

**Comment by AlexandrPy** [comment]
flynn-host logs

**Comment by titanous** [comment]
What do you think is useless?

**Comment by AlexandrPy** [comment]
From DigitalOcean droplets I receive logs like this `Aug 16 17:21:52 flynn-production-ams2-node-1 4585242b-9685-4619-ac58-93c2472f9801.log:  244 <0>1 2017-08-16T15:21:52.785788344Z flynnproductionams2node1 4585242b-9685-4619-ac58-93c2472f9801 worker.flynnproductionams2node1-bf5c60f0-ddf7-40e6-98cd-6b9a3744d52c ID2 [flynn seq="1850673"] cannot send spans: [Errno 110] Connection timed out`, where the middle part is not interesting for me `244 <0>1 2017-08-16T15:21:52.785788344Z flynnproductionams2node1 4585242b-9685-4619-ac58-93c2472f9801 worker.flynnproductionams2node1-bf5c60f0-ddf7-40e6-98cd-6b9a3744d52c ID2 [flynn seq="1850673"]`.

Can I edit somehow the format to not display this?

**Comment by titanous** [comment]
The metadata is used internally, so it can't be removed. You can add a syslog log sink with `flynn cluster log-sink`.

**Comment by AlexandrPy** [comment]
ok, thank you.
