### ISSUE TITLE
https ssl certificate attachment unknown error

### ISSUE THREAD

**Issue by XuryaX** [flynn/flynn#4214]
I was  trying to attach a certificate for  HTTPS in my app. I got an unnown error

`F:\abcd>flynn -a appname route update http/ip1005075-d853bac7-ceee-4c9c-ac70-0dfc149a6ae1 -k abcd.com.crt -c abcd.com.chain.crt`

`unknown_error: Something went wrong`

**Comment by titanous** [comment]
What is the output of `flynn -a router log -n 100`?

**Comment by titanous** [comment]
Ah, the issue is that you are using the wrong route ID. Use the ID from `flynn route`.
