### ISSUE TITLE
Not able to write to the file system for logging

### ISSUE THREAD

**Issue by mogupta** [flynn/flynn#4217]
I am trying to create a log file in the container filesystem. In the `/app/logs` folder . 
When I start a process from the dashboard it is not able to create the file but if I bash into the container using `flynn run bash` and run `node test.js` it works perfectly fine. Here is a small example I am using to test.  My guess is that it is related to permissions. I can see that uid 5000 is the user running the process if I switch it on from the dashboard. user 5000 is the user `flynn` and the `/app` folder is also owned by flynn so not sure what I am missing. 

```
var fs = require('fs');
fs.writeFileSync("/tmp/test", "Hey there!", function(err) {
    if(err) {
        return console.log(err);
    }

    console.log("The file was saved!");
});
```

My use case is to create a log file for all http requests and then use `filebeat` to harvest the logs and stream it to an ELK stack for later analysis.

**Comment by lmars** [comment]
@mogupta when you say "it is not able to create the file", are you seeing an error in your app logs? If so, what is the error?

**Comment by mogupta** [comment]
@lmars no, I am not seeing any error. which is weird. on my local is does shows an error if for example the parent folder is missing.

**Comment by lmars** [comment]
So how are you determining that the file is not being created?

**Comment by mogupta** [comment]
I am bashing into the container using `flynn run bash` and checking to see if the file is created

**Comment by lmars** [comment]
Ok when you run `flynn run bash` you are running bash in its own container with its own filesystem, rather than connecting to an existing one.

If you want to collect the logs using `filebeat` you will need to run it in the same container as your app process.

**Comment by mogupta** [comment]
Got it. thanks. So I am able to read the logs using the same process. Now how should I go about creating a volume that two process can share. 

1. app process (creating logs)
2. filebeat process (harvesting logs) 

Mohit

**Comment by titanous** [comment]
This is not currently supported. Note that Flynn automatically aggregates the stdout/stderr streams, and you can set up a Syslog stream with `flynn cluster log-sink`.
