### ISSUE TITLE
Custom DNS resolve for application containers, or using internal dns, instead default one

### ISSUE THREAD

**Issue by andymilga** [flynn/flynn#4220]
my git installation and my flynn installation are running at one kvm host in different VMs. For some reasons i dont want to allow internal hosts to be able to connect to internal host via ISP. In this case im using internal DNS server. So i need my flynn apps resolve my git in internal ip, not in external. How can i do this? By default my flynn apps using 100.100.79.1 as primary dns server and i cant find way i can change this. I dont rly matter if it will be dns server or just hosts file.

**Comment by lmars** [comment]
Each app container uses an IP like `100.100.x.1` for DNS queries which is the Flynn `discoverd` service allowing them to resolve `*.discoverd` domains within the Flynn cluster.

The `discoverd` service then uses whatever is configured in the host `/etc/resolv.conf` as upstream resolvers for everything else (i.e. anything which isn't `*.discoverd`), so merely configuring `/etc/resolv.conf` on the host before starting Flynn should be all you need to do.

**Comment by andymilga** [comment]
@lmars yeah, that works fine, thank you.
