### ISSUE TITLE
All of a sudden, cluster fails and flynn-host wont start

### ISSUE THREAD

**Issue by thomasmodeneis** [flynn/flynn#4221]
I have logs for all 3 instances, but they are quite big and wont fit into gist, is there email or some other alternative method of sending it ? 

I often run into this problem, actually only this year it happened 8 times (every month). 
I would really appreciate if I could have a easier way to work around it, like un-install flynn, removing dfs, and restoring from backup step by step guide.

Thanks.

**Comment by thomasmodeneis** [comment]
My cluster is now dying every 3 days or so.
I have to restart the legs one by one and wait for it to restore, sometimes it cant restore and I have to trigger the flix. Sometimes it works. Just now it failed with this error:

```
root@flynn1:~# flynn-host fix --min-hosts 3
INFO[08-29|22:12:58] found expected hosts                     n=3
INFO[08-29|22:12:58] ensuring discoverd is running on all hosts 
INFO[08-29|22:13:03] started discoverd instance               job.id=flynn3-05010784-3ea0-460f-9b4f-782b8feb4319
INFO[08-29|22:13:06] checking flannel 
INFO[08-29|22:13:09] flannel is not running on each host, starting missing jobs 
INFO[08-29|22:13:11] started flannel job                      job.id=flynn3-3815f464-f2f1-4836-8555-0ee16d09c0e8
INFO[08-29|22:13:11] flannel fix complete 
INFO[08-29|22:13:11] waiting for discoverd to be available 
INFO[08-29|22:13:11] checking for running controller API 
INFO[08-29|22:13:11] found running controller API instances   n=1
INFO[08-29|22:13:11] found controller instance, checking critical formations 
EROR[08-29|22:13:21] error fixing controller                  err="error getting controller release: unknown_error: Something went wrong"
INFO[08-29|22:13:21] killing any running schedulers to prevent interference 
INFO[08-29|22:13:23] stopped scheduler instance               job.id=flynn1-3d077ad3-8bd5-4f17-9003-20b290b2d604
INFO[08-29|22:13:24] stopped scheduler instance               job.id=flynn2-fca9589b-a107-4004-b0b2-899946522f52
INFO[08-29|22:13:26] checking status of sirenia databases 
INFO[08-29|22:13:26] checking for database state              db=postgres
INFO[08-29|22:13:26] checking sirenia cluster status          fn=CheckSirenia service=postgres
INFO[08-29|22:13:26] no running leader                        fn=CheckSirenia service=postgres
INFO[08-29|22:13:26] found running instances                  fn=CheckSirenia service=postgres count=3
INFO[08-29|22:13:26] getting sirenia status                   fn=CheckSirenia service=postgres
INFO[08-29|22:13:26] killing any running schedulers to prevent interference 
INFO[08-29|22:13:29] getting service metadata                 fn=FixSirenia service=postgres
INFO[08-29|22:13:29] getting primary job info                 fn=FixSirenia service=postgres job.id=flynn3-7e98bfa8-3c47-47fd-a8b0-dbd88cf70c4a
INFO[08-29|22:13:29] getting sync job info                    fn=FixSirenia service=postgres job.id=flynn3-166ee4b3-68e4-4185-b073-9ce66c35dae2
INFO[08-29|22:13:29] terminating unassigned sirenia instances fn=FixSirenia service=postgres
EROR[08-29|22:13:29] error stopping unassigned sirenia job    fn=FixSirenia service=postgres jobID=flynn2-2486c9ea-57d2-4d86-ad73-9df385e02ae5
INFO[08-29|22:13:29] starting primary job                     fn=FixSirenia service=postgres job.id=flynn3-d91c2a43-6027-4e6d-be01-6c2516163f51
INFO[08-29|22:13:30] starting sync job                        fn=FixSirenia service=postgres job.id=flynn3-6fe01f64-65d6-48b7-b249-f252c34ebb24
INFO[08-29|22:13:30] waiting for instance to start            fn=FixSirenia service=postgres job.id=flynn3-d91c2a43-6027-4e6d-be01-6c2516163f51
INFO[08-29|22:13:32] waiting for cluster to come up read-write fn=FixSirenia service=postgres addr=100.100.81.10:5432
22:18:37.568220 host.go:166: timeout waiting for expected status
```

Any ideas on how to increase the timeout ? or any other tips to deal with this ?

Thanks

**Comment by thomasmodeneis** [comment]
Now, after I restarted the legs again and hoping for a better luck, the cluster again failed with a timeout, this time, strangely it waited much longer, any ideas why ?

```
INFO[08-29|22:39:51] waiting for instance to start            fn=FixSirenia service=postgres job.id=flynn3-ce77d69f-abed-4264-b93c-16110e12821c
INFO[08-29|22:39:53] waiting for cluster to come up read-write fn=FixSirenia service=postgres addr=100.100.88.2:5432
22:45:04.692555 host.go:166: timeout waiting for expected status
```

**Comment by thomasmodeneis** [comment]
Today after 40 hours, flynn cluster was in a failure state all night long.

Its a very strange behaviour, flynn cmd line is not operational from my box, but from inside the cluster, flynn-host ps reports normal.

I was about to delete flynn and recover the backups but decided to stop all jobs via the web-ui (still operational) and when I did this, the cluster got back alive.

I have all the logs but not sure if I should update here or send it to some email ?
Cheers.

**Comment by thomasmodeneis** [comment]
Oh, I was singing the victory too early, the cluster is back to failure state.
Basically it seems that the things are alive, but the router somehow is unable to do its job properly and the apps are not getting the traffic.

**Comment by thomasmodeneis** [comment]
Today it happened again, when I went to restore the cluster now it seems that flannel is not able to start for some reason, all 3 of them are reporting this error:

```
[2017-09-10T14:22:34.150374Z]    I0910 14:22:34.150245      17 main.go:356] Installing signal handlers
[2017-09-10T14:22:34.151785Z]    I0910 14:22:34.151702      17 main.go:306] Using 145.239.77.136 as external interface
[2017-09-10T14:22:34.178806Z]    I0910 14:22:34.178601      17 subnet.go:104] Subnet lease acquired: 100.100.25.0/24
[2017-09-10T14:22:34.270184Z]    I0910 14:22:34.270094      17 main.go:324] VXLAN mode initialized
[2017-09-10T14:22:34.270345Z]    I0910 14:22:34.270156      17 vxlan.go:113] Watching for new subnet leases
[2017-09-10T14:22:34.270992Z]    I0910 14:22:34.270921      17 vxlan.go:172] Subnet added: 100.100.65.0/24
[2017-09-10T14:22:34.271123Z]    I0910 14:22:34.271012      17 device.go:130] calling NeighAdd: 145.239.77.137, 52:7f:dd:33:12:cb
[2017-09-10T14:22:34.271168Z]    E0910 14:22:34.271123      17 vxlan.go:186] Error adding L2 entry: file exists
[2017-09-10T14:22:34.271299Z]    I0910 14:22:34.271165      17 device.go:153] calling NeighSet: 100.100.65.0, 52:7f:dd:33:12:cb
[2017-09-10T14:22:34.271366Z]    I0910 14:22:34.271273      17 device.go:181] calling RouteAdd: 100.100.65.0/24
[2017-09-10T14:22:34.27172Z]     E0910 14:22:34.271592      17 vxlan.go:192] Error adding route: file exists
[2017-09-10T14:22:34.271795Z]    I0910 14:22:34.271695      17 vxlan.go:172] Subnet added: 100.100.97.0/24
[2017-09-10T14:22:34.272019Z]    I0910 14:22:34.271982      17 device.go:130] calling NeighAdd: 145.239.77.138, 8a:b9:3d:a2:5d:03
[2017-09-10T14:22:34.272272Z]    E0910 14:22:34.272219      17 vxlan.go:186] Error adding L2 entry: file exists
[2017-09-10T14:22:34.272445Z]    I0910 14:22:34.272368      17 device.go:153] calling NeighSet: 100.100.97.0, 8a:b9:3d:a2:5d:03
[2017-09-10T14:22:34.272573Z]    I0910 14:22:34.272468      17 device.go:181] calling RouteAdd: 100.100.97.0/24
[2017-09-10T14:22:34.272877Z]    E0910 14:22:34.272835      17 vxlan.go:192] Error adding route: file exists
```

the consequence of it seems to be that the discoverd is not able to be alive longer than 2 mins and the backup restore is now locked on this stage for almost 2 hours:

```
14:50:08.415019 check online-hosts
14:50:08.849076 run-app discoverd
14:50:11.384276 run-app flannel
14:50:12.524593 wait-hosts wait-hosts
14:50:13.534548 run-app postgres
14:50:17.262607 sirenia-wait postgres-wait
14:50:22.649259 restore-postgres restore
```


any ideas ?

**Comment by GBeushausen** [comment]
Why is nobody helping him? I'm thinking about starting a Flynn cluster, but with these kinds of support issues, i'm not sure if i should.

**Comment by titanous** [comment]
Hey @GBeushausen,

We use GitHub issues to track bugs and feature requests, it is not a support channel. Flynn is an open source project that is maintained by a small team with limited resources. Our team offers [commercial support](https://flynn.io/pricing) with a 24/7 SLA and we prioritize supporting our paying customers and frequent contributors.

In order to fix bugs reported here, we need the full cluster logs, not just snippets.

**Comment by GBeushausen** [comment]
Hi @titanous,

thanks for the info. I'm just evaluating if Flynn would be a good solution for us. It looks very promising, but those cluster breakdowns reported here look a bit scare. But i'll test it a more deeply myself.

Btw. do you offer any startup support plans? Spending over 30K for your support seams a little high to me.

**Comment by titanous** [comment]
>  I'm just evaluating if Flynn would be a good solution for us. It looks very promising, but those cluster breakdowns reported here look a bit scare.

Our experience is that failures like this typically only happen when a cluster is underprovisioned on resources, has an unreliable network, or is not following our best practices. If you use one of the big three cloud providers, follow the [production best practices](https://flynn.io/docs/production) carefully, and ensure that your cluster has enough CPU/RAM/disk, this type of failure is unlikely.

> do you offer any startup support plans?

Yes, our published pricing is definitely for startups, which are the majority of our customers. That price covers us operating multiple Flynn clusters for an engineering team and providing 24/7 devops support for just about anything you need, including architecture and security advice, application performance troubleshooting, etc.

**Comment by pouledodue** [comment]
@titanous would it be possible for you to add simple disk/ram/cpu email alerts built-in?

I remember chasing a weird error message, turned out to be a disk partition full caused the problem;

Would have been avoided if Flynn had a built-in mechanism to send me an email "Hey your disk XYZ is quite full, you WILL have weird problems with Flynn soon because of this! Take action now!"

**Comment by lmars** [comment]
@pouledodue I proposed something in https://github.com/flynn/flynn/issues/3484.

**Comment by pouledodue** [comment]
there is hope

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.

**Comment by GBeushausen** [comment]
@titanous That's very sad to hear, but i expected it, due to your crazy high and unaffordable pricing. Why don't you try to hit a mass market and offer it at a reasonable price? Like Heroku or something.
