### ISSUE TITLE
The certificate is not trusted in all web browsers

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#4225]
Hi There, 

We have an app running with SSL. However we get reports that it isn't trusted on all web browsers. 
https://www.sslshopper.com/ssl-checker.html#hostname=shopify.reloadseo.com
Is this an issue with Flynn?

**Comment by titanous** [comment]
You need to add the intermediate certificate. Append the intermediate to the certificate file that you used to create the route and update the route with the new file and existing key.

**Comment by heldopslippers** [comment]
Thanxs for the info! 
If anybody else has this issue: 
cat domain.crt domain.ca-bundle >> cert.crt

That's it.
