### ISSUE TITLE
Old versions running

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#4226]
Hi There, 

We just discovered one of our app is still running old deploys. 
Killing it manually with `flynn kill` just restarts them. 

What can be done about this.

**Comment by heldopslippers** [comment]
See issue: #4175  solved the problem.

**Comment by mfclarke** [comment]
I just had the exact same problem, and the solution from 4175 fixed it for me too. I haven't updated my flynn cluster for a while though.
