### ISSUE TITLE
discoverd ignores current DNS recursors

### ISSUE THREAD

**Issue by crawlik** [flynn/flynn#4227]
We run into a problem with discoverd service overriding 
 [current DNS recursors](https://github.com/flynn/flynn/blob/master/discoverd/main.go#L133)  with [default ones](https://github.com/flynn/flynn/blob/master/discoverd/main.go#L571 ). "recursor" option is not passed from command line and `StringVar` will default it to "8.8.8.8,8.8.4.4".

Issue happens whenever a new discoverd release is created. For example running `flynn -a discoverd env set DEBUG=true`  will lead to discoverd restart and hitting this [path](https://github.com/flynn/flynn/blob/master/discoverd/main.go#L118) effectively overriding upstream dns resolvers returned by `waitHostDNSConfig` Looks like checking for existing resolvers should fix the problem

```golang
if len(opt.Recursors) > 0 && len(resolvers) == 0 {
	resolvers = opt.Recursors
}
```

**Comment by lmars** [comment]
I think we should drop the default flag values and just use the host resolvers as the default.

**Comment by crawlik** [comment]
This idea sounds like a winner to me! We better fail DNS resolutions loudly If no host or command line resolvers are provided.

**Comment by lmars** [comment]
@crawlik can you make that change and pull request it?

**Comment by crawlik** [comment]
@lmars I will do it
