### ISSUE TITLE
how to properly enable certbot with flynn?

### ISSUE THREAD

**Issue by shalakhin** [flynn/flynn#4232]
I use certbot to have https and can't find how to do that with flynn. Has somebody tried that?

**Comment by shalakhin** [comment]
Anyone trying this?

**Comment by bbaptist** [comment]
Just take the full chain certificate and key and update the route you have created with `flynn route` for your domain. If you mean how to order the certificate then I recommend using something like [GetSSL](https://github.com/srvrco/getssl) and the DNS verification option.

**Comment by titanous** [comment]
See #4240 and #1995.
