### ISSUE TITLE
Create App + Provision DB + Add ENV -> 1 command?

### ISSUE THREAD

**Issue by Kentoseth** [flynn/flynn#4233]
Hello all,

So I noticed that flynn seems to accumulate a lot of excess-baggage (via failed-builds) of apps.

In my case, the `web` kept crashing because I could not provision the DB (Redis) and add my ENV key simultaneously whilst running `git push flynn master`.

Is there a suggestion to run a **single** command to:

- Create app / Push to Master (I'm not sure if the DB should be provisioned after creating the app or after pushing to Master - so please suggest the option)
- Provision a DB (Redis)
- Add an ENV

**Comment by titanous** [comment]
There's no single command to do those things, but if you don't like the records for a few crashed processes hanging around (which are not problematic in any way), you can either scale the app down before changing settings or set the environment up before deploying the app.
