### ISSUE TITLE
flynn run [command] on DB with no external route?

### ISSUE THREAD

**Issue by Kentoseth** [flynn/flynn#4234]
As the title says, can I execute a command like:

`flynn run python manage.py db upgrade` (normally used to setup a DB)

If I do not expose an external route for the DB?

I initially set it up with no external route and when running that command, I got a 503.

Then I re-set it up (with external route) and it worked (running the command above).

Just clarifying this matter to make sure.

**Comment by titanous** [comment]
Yes, that command will work without the external route. The external route will never be used from inside the app unless you specifically configure it to do so.

**Comment by Kentoseth** [comment]
How do I delete the DB route after adding it?

When I enter: `flynn route`

It doesn't show that route. Nor does it show it via the web-dashboard.

Thanks for your help.

**Comment by titanous** [comment]
`flynn -a postgres route` should show it (change `postgres` if it's a different database type)

**Comment by Kentoseth** [comment]
For anyone else that comes across this issue, the following won't work:

`flynn route remove [ID]`

It needs to be:

`flynn -a [appname] route remove [ID]`
