### ISSUE TITLE
Removing unneeded DB options breaks /providers Page

### ISSUE THREAD

**Issue by Kentoseth** [flynn/flynn#4235]
When I remove unneeded DBs like `mongodb` and mariadb` using:

`flynn -a mongodb delete`

And I then try to visit the providers page:

https://dashboard.[xxxx].flynnhub.com/providers

It comes up with the error:

`No resource selected`

(and I am no longer able to provision redis/postgres any longer)

I would like to remove the unneeded DBs (especially mongoDB), as it seems to be an unnecessary resource-hog (mongodb and mariadb were showing as "unhealthy" on my status page, despite me not even using them).

Is there a way to restore the 2 DBs or should I re-install flynn?

**Comment by lmars** [comment]
There is no need to delete the `mongodb` or `mariadb` apps, and in fact you shouldn't delete them. They are scaled down until you actually provision a resource so they are not running by default.

I suggest bootstrapping a fresh cluster from a recent backup.
