### ISSUE TITLE
Scaling mariadb with host tags, now in pending state

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#4236]
I attempted to scale the `mariadb` app with host tags so it would run on my SSD disk cluster members and now 2 out of 3 of the processes are stuck in a pending state. How would I go about fixing this?

**Comment by lmars** [comment]
What does `flynn -a mariadb scale` and `flynn -a mariadb ps --all` say?

**Comment by bbaptist** [comment]
```
flynn -a mariadb scale
mariadb=3 web=2
```
flynn -a mariadb ps --all
ID                                                    TYPE     STATE    CREATED            RELEASE
ieflynn16071307-dbea1a63-8ae8-4ac5-8fb9-ac461fdd4401  web      up       11 weeks ago       3d231052-150f-441f-bfff-041ee06eeb86
ieflynn16071306-140d7f2c-a14f-4b01-b228-7b414f8605ff  web      up       11 weeks ago       3d231052-150f-441f-bfff-041ee06eeb86
ieflynn16071300-2acf5417-b5ec-4c05-8bc1-567fbc35fb7d  mariadb  down     18 hours ago       3d231052-150f-441f-bfff-041ee06eeb86
ieflynn16071306-9140370c-bb02-479c-8832-272b7e4e7c6c  mariadb  up       18 hours ago       3d231052-150f-441f-bfff-041ee06eeb86
ieflynn16071301-275e6605-e7c2-45df-a6ba-1bbe6b3ec39b  mariadb  down     18 hours ago       3d231052-150f-441f-bfff-041ee06eeb86
515bcd70-f5bd-4a54-8e8a-f1057824e796                  mariadb  down     About an hour ago  3d231052-150f-441f-bfff-041ee06eeb86
dd514a5d-6540-418e-99e4-4cbc914f956e                  mariadb  down     About an hour ago  3d231052-150f-441f-bfff-041ee06eeb86
9b95aca8-1df8-4da6-beae-85e15573f7e1                  mariadb  down     About an hour ago  3d231052-150f-441f-bfff-041ee06eeb86
6cbb701b-4e6c-4100-a185-f355cf28dd8b                  mariadb  down     About an hour ago  3d231052-150f-441f-bfff-041ee06eeb86
f24bce56-4e41-4174-af4b-77a2497e5755                  mariadb  down     About an hour ago  3d231052-150f-441f-bfff-041ee06eeb86
97ce9c74-c18c-4925-b6dd-1bef1d5617a0                  mariadb  down     About an hour ago  3d231052-150f-441f-bfff-041ee06eeb86
25c1ab7f-1a34-4c4b-8b76-662bed55cb9c                  mariadb  down     About an hour ago  3d231052-150f-441f-bfff-041ee06eeb86
e952e5f5-43bc-44f2-a204-36efe18ff89e                  mariadb  down     About an hour ago  3d231052-150f-441f-bfff-041ee06eeb86
4c1001e2-32ca-4441-bad9-69371dcabc9d                  mariadb  pending  59 minutes ago     3d231052-150f-441f-bfff-041ee06eeb86
8144efc9-ca4f-4ceb-8e6e-02c20676090e                  mariadb  pending  59 minutes ago     3d231052-150f-441f-bfff-041ee06eeb86
```

**Comment by lmars** [comment]
Check the scheduler logs for messages about that release:

```
$ flynn -a controller log -t scheduler | grep 3d231052-150f-441f-bfff-041ee06eeb86
```

It may be easier to just collect debug logs.

**Comment by bbaptist** [comment]
This cluster's scheduler job was seriously messed up. I had to recreate the cluster from scratch to clear up the job history. Closing as invalid.
