### ISSUE TITLE
Cluster failed after out of space error

### ISSUE THREAD

**Issue by asadm** [flynn/flynn#4237]
I had a cluster perfectly running for a few months now but it failed today when I pushed a new app. I am no longer able to access the cluster. 
I checked that it's because of low space so I ran `flynn-host volume gc` but that didn't fix much.

- `flynn-host collect-debug-info` times out.
- `flynn-host fix -n 5` times out too.
- It seems postgres is not able to start. Logs say:
```sh
14:55:01.185429 host.go:166: job flynn1488268945vm2-0b304fb1-d51e-48b4-95ab-c261ede58eaf required volume a4a1d843-5a88-4857-898d-c1baa48f030f, but that volume does not exist
```

Here is the [output from `flynn-host volume list`](https://gist.githubusercontent.com/asadm/dfca826ee54d72f1ff93cf344fed1033/raw/817fdf77df3452ab960d312f7df7762b98bc059c/flynn-host.volume.list.txt)

[Output from `sudo zfs list`](https://gist.githubusercontent.com/asadm/dfca826ee54d72f1ff93cf344fed1033/raw/4ae29f050e0cec67b6d38cbe03149ee5339e87de/zfs.list.txt)

[Output from `sudo zpool list`](https://gist.githubusercontent.com/asadm/dfca826ee54d72f1ff93cf344fed1033/raw/4ae29f050e0cec67b6d38cbe03149ee5339e87de/zpool.list.txt)

I had a production mongodb running here. How do I check if my data has been deleted? How do I retrieve it?

Thanks

**Comment by thomasmodeneis** [comment]
Do you have backups ? The best way is to do backups daily so you can restore things when this happens.

I suspect this is similar to my issue #4221 ; next time it happens I will the same cmds you used and report here as well. 
Cheers.

**Comment by asadm** [comment]
Sadly no backups since this was a cluster for a few side-projects.

**Comment by thomasmodeneis** [comment]
Oh thats very sad to hear, next time do the backups:
`flynn cluster backup --file flynn-backup-05-09-2017.tar.gz`

When the cluster gets unhealthy kill it on all legs, do the cluster init on master and add the token on all slaves and restore backup:

`sudo CLUSTER_DOMAIN=cloud.comentarismo.com flynn-host bootstrap --min-hosts 3 --discovery https://discovery.flynn.io/clusters/TOKEN --from-backup /root/flynn-backup-05-09-2017.tar.gz`

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
