### ISSUE TITLE
How to clear logs?

### ISSUE THREAD

**Issue by mfclarke** [flynn/flynn#4238]
My cluster has been running for a while now, and my process logs are getting pretty huge. It causes the "Show Logs" part of the dashboard to take 15-20 seconds to load. Is there a way to flush these out? I've been deleting the rotated logs in /var/log/flynn (the 1GB log files that have the date appended). This helps with disk usage, but not the "Show Logs" dashboard page.

**Comment by furedal** [comment]
`flynn log help`
`usage: flynn log [-f] [-j <id>] [-n <lines>] [-r] [-s] [-t <type>] [-i]`

Use -n so you wont get overwhelmed :)

**Comment by thomasmodeneis** [comment]
Does `flynn-host volume gc` help in any ways ?

**Comment by philiplb** [comment]
I think this won't help with the logs.
See https://github.com/flynn/flynn/blob/master/host/cli/volume.go#L58-L123
There seems to be situations, where ZFS volumes are not attached to any process. They are just garbarge. This tool collects the used volumes and compares this list with the actual existing volumes. It then deletes every unused existing volume.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
