### ISSUE TITLE
missing data  on postgres database

### ISSUE THREAD

**Issue by grauschnabel** [flynn/flynn#4241]
Hi there,

This is a really urgent request, because I could not see it come.

I tried to use a `flynn pg dump` on another postgres database with `pg_restore` this worked for one app but not for the other, there are missing primary keys.  Interestingly the app worked fine on the flynn cluster, but the same app on the other machine (manually, development) does not, there is missing data and missing keys.  

Now going into the `flynn pg psql` I could see that the same data is missing there.  so the dumps since I don't know when - which should be backup - are also corrupt.  Interestingly the app on the flynn cluster worked well.  But then I did a `sudo reboot` on the machine (my cluster has only one at the moment) made the app not to start anymore.  Seems it could not restore its state from the database.

What can I do here?  Or is the work of a company now lost from the last I don't know how many weeks or months?

Thanks for this help!
Martin

**Comment by titanous** [comment]
Hi @grauschnabel, can you provide an isolated reproduction case of `flynn pg dump` / `flynn pg restore` losing data? We have not seen this before, so an example of how it can happen would be useful.
