### ISSUE TITLE
Flynn abandoned?

### ISSUE THREAD

**Issue by kwando** [flynn/flynn#4242]
What is happening with Flynn? It's awfully quiet around here nowadays, I feel there is a lack of progress and this worries me a bit about the health of this project.

Our company is running flynn in production, and we are happy but sometimes I get the feeling it is time to jump of this ship. Which is a shame since I personally like flynn _a lot_.

**Comment by titanous** [comment]
We're still around, and Flynn certainly isn't dead! Our current focus is on our paid products and paying customers, but we continue to fix bugs and develop new features.
