### ISSUE TITLE
Custom internal DNS names for services

### ISSUE THREAD

**Issue by MrDHat** [flynn/flynn#4248]
We use docker compose in development and are exploring flynn for production deployment. We use service names to send requests between different services, for ex: if there is a notification service, we declare the service name as `notification` in docker compose and say, port, `3000`. Now, for any HTTP requests, we use `notification:3000` as the base URI.

How do I make sure I replicate the same in flynn. So, essentially, I would want my services to run by the same DNS name and on same ports in production

**Comment by theodorton** [comment]
You can use the discoverd suffixes. So if you have 2 apps: `service-a` and `service-b`, each with a `web` process declared, you can access them by `service-a-web.discoverd` and `service-b-web.discoverd` respectively. You should probably be able to provide these domains as environment variables to your app to avoid being "stuck" with `notification:3000`.
