### ISSUE TITLE
Blobstore not uploading to AWS

### ISSUE THREAD

**Issue by reneweteling** [flynn/flynn#4251]
Hey Guys,

Im trying to move all the blobstore data to a s3 bucket. Because my disk is slipping full with all sorts of stuff stored in:

```
/var/lib/flynn/volumes/zfs/mnt/squashfs/and
and 
/var/lib/flynn/volumes/zfs/mnt/ext2/
```

This is my attempt in moving it all to s3

```bash
➜ flynn -a blobstore env
BACKEND_S3MAIN=backend=s3 region=eu-central-1 bucket=flynn.hosting.weteling.com access_key_id=blablabla secret_access_key=non-of-your-beezwax
➜ flynn -a blobstore run /bin/flynn-blobstore migrate --delete
2017/09/19 06:47:08 Configured additional backend: s3main (s3)
2017/09/19 06:47:08 Finished with no errors.
➜ aws s3 ls s3://flynn.hosting.weteling.com/ --profile rene --region eu-central-1
➜ 
```

As you can see the s3 bucket is empty

This is my aws policy
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutObject",
                "s3:ListMultipartUploadParts",
                "s3:AbortMultipartUpload",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::flynn.hosting.weteling.com",
                "arn:aws:s3:::flynn.hosting.weteling.com/*"
            ]
        }
    ]
}
```

So im clueueless guys im running flynn: v20170719.0-81418bc

**Comment by lmars** [comment]
You need to run `flynn -a blobstore env set DEFAULT_BACKEND=s3main` to set the S3 backend as the default.

Also, files in `/var/lib/flynn/volumes/zfs/mnt` are mounted ZFS volumes so moving the blobstore to S3 will have no effect on those. Are you using a disk for your ZFS pool?

**Comment by reneweteling** [comment]
i feel so stupid now.... thanks!! the AWS part is working!

About the disks, I'm not using a physical disk, it's just some space on the server. It's running on default settings. (sorry for the late response, I'm in the middle of moving.)

Thanks!
