### ISSUE TITLE
Register a service with Discoverd

### ISSUE THREAD

**Issue by bbaptist** [flynn/flynn#4257]
I have added `memcached` as an additional process in my Procfile using the apt buildpack and the multi-buildpack. From what I can tell it is up and running on the default port. However, I have no idea how you would tell another app how to connect to this service. Is there a way to register it with Discoverd and access it by that DNS name?

**Comment by bbaptist** [comment]
This issue seem similar to the closed issue #4248, the answer there is not really what either of us is asking though. I don't really want to create a routable app, just a resolvable one.

**Comment by lmars** [comment]
@bbaptist you can do this by assigning a port to the process type using `flynn release update release.json` where `release.json` contains something like the following:

```
{
  "processes": {
    "memcached": {
      "ports": [
        {
          "port": 11211,
          "proto": "tcp",
          "service": {
            "name": "memcached",
            "create": true
          }
        }
      ]
    }
  }
}
```

It will then be discoverable at `memcached.discoverd`.

This is admittedly not a great API, to be addressed by introducing a Flynnfile (#1084).

**Comment by bbaptist** [comment]
OK, great start. However, some questions.

To make sure the name is something unique per app I would be able to change the service name to `appname-memcached` and have it discoverable at `appname-memcached.discoverd` correct?

If I have already added your example release does it remove the previously created `memcached.discoverd` entry upon running another release update?

**Comment by lmars** [comment]
> To make sure the name is something unique per app I would be able to change the service name to appname-memcached and have it discoverable at appname-memcached.discoverd correct?

Correct.

> If I have already added your example release does it remove the previously created memcached.discoverd entry upon running another release update?

It is not removed but it will not interfere with other services.
