### ISSUE TITLE
Setting up docker container, correct configuration

### ISSUE THREAD

**Issue by trinode** [flynn/flynn#4258]
Hi there, I've been trying to launch a docker container in flynn, I've been trying to piece together the correct config to launch it in flynn and bind the ports, I've seen things refering to "data": true and others.

The Docker image I'm trying to run is minio/minio (https://hub.docker.com/r/minio/minio/) and I know it writes it's config into /root and I'm trying to configure it to store files in /data

if I was to run it locally it would be:
 ```docker run -p 9000:9000 minio/minio server /data```

I'm really struggling to find documentation on the correct schema and options but this is my best effort:-

```
{
  "processes": {
    "app": {
      "args": ["minio", "server", "/data"],
      "volumes": [{"path": "/data"}, {"path": "/root"}],
      "ports": [
        {
          "proto": "tcp",
          "port": 9000,
          "service": {
            "name": "miniofilestore",
            "create": true
          }
        }
      ]
    }
  }
}
```

which I keep testing via: ```flynn -a miniofilestore release update config.json --clean```

I've pushed the image up fine, through various experiments I've had it running but not reachable, or just crashing with no error, or not receiving the command parameters so just showing the help and then exiting.

adding "minio" as the first "arg" (["minio", "server", "/data"]) with the app scaled to one instance seems to result in the app starting once, (the logs show it's running fine), but then trying to start more of them:-

![image](https://user-images.githubusercontent.com/965926/30889934-96fcbf18-a321-11e7-97ae-10312591f17a.png)

Any help would really be appreciated.

**Comment by lmars** [comment]
@trinode we actually run minio in the integration test suite to test the minio backend, here is the config we use: https://github.com/flynn/flynn/blob/master/test/helper.go#L438-L455.

It is pretty similar to what you have so it should work fine. Perhaps check `flynn -a minio log`?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
