### ISSUE TITLE
Can not build play framwork app

### ISSUE THREAD

**Issue by Elvis5566** [flynn/flynn#4259]
Hi Guys,

I followed #4102 to set env BUILDPACK_URL="https://github.com/heroku/heroku-buildpack-scala
and try to deploy heroku's sample app https://github.com/heroku/scala-getting-started.git to flynn.
I set up single node cluster with ec2 t2.micro instance and build failed. 
There is no error message but 

> remote: .sbt_home/bin/sbt: line 27:   307 Killed                  sbt-extras ${SBT_EXTRAS_OPTS} -J-Xmx${maxSbtHeap}M -J-Xms${maxSbtHeap}M -J-XX:+UseCompressedOops -sbt-dir $sbtHome -ivy $sbtHome/.ivy2 -sbt-launch-dir $SBT_HOME/launchers -Duser.home=$sbtHome -Divy.default.ivy.user.dir=$sbtHome/.ivy2 -Dfile.encoding=UTF8 -Dsbt.global.base=$sbtHome $(([ -n "$HEROKU_TEST_RUN_ID" ] || [[ "$DYNO" != *run.* ]]) && echo "-Dsbt.log.noformat=true -batch") -no-colors $@

It looks like sbt is killed by system, so I try to deploy the same app to ec2 t2.medium instance. This time, it works!!

Then I tried to deploy my own app to the same machine (t2.medium), but it failed again.
It weird that I can see the "compilation completed" message, but sbt is killed eventually.
I also tried SBT_OPTS
-Xmx4G
-J-Xmx4G
-J-XX:MaxMetaspaceSize=4G
-J-XX:+CMSClassUnloadingEnabled
none of them work

I also tried this app https://github.com/mkbehbehani/play-heroku-seed, failed again.

My app is a small one, there is no way to run out of memory during compilation.
I checked memory usage on the machine by command top.
Before sbt killed, there are at least 100mb free memory.

Please help me to solve this issue.
Thank you!!

**Comment by titanous** [comment]
Try adjusting the slugbuilder memory limit: https://flynn.io/docs/apps#slugbuilder-limits

**Comment by Elvis5566** [comment]
OMG
I managed to deploy the app to server.
Thank you titanous!!!
You save my day :)
