### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4260]
Hi,

would be nice if Flynn would participate in the Hacktoberfest. :)
https://hacktoberfest.digitalocean.com/
I would have some smallish issues here to tackle like https://github.com/flynn/flynn/issues/3241 or https://github.com/flynn/flynn/issues/2963. :)

**Comment by titanous** [comment]
It looks like we already are!

> Pull requests can be made in any GitHub-hosted repositories/projects.

> You can contribute to any project on GitHub.
