### ISSUE TITLE
Postgres: Change collation and ctype

### ISSUE THREAD

**Issue by furedal** [flynn/flynn#4261]
Hey, as the title states, I am want to change the collation and ctype of my postgres database.
Right now they are defaulten to 'en_US.UTF-8' but need them to be changed to 'sv_SE.UTF-8'.

I tried the following:
`flynn -a myapp pg psql`
`update pg_database set datcollate='sv_SE.UTF-8', datctype='sv_SE.UTF-8';`
and
`update pg_database set datcollate='sv_SE.UTF-8', datctype='sv_SE.UTF-8' where datname='mydatabasename';`

But receiving this error:
`ERROR:  permission denied for relation pg_database`

I was doing this before adding any relations to the database and was hoping it would work.
Do I need to manually create my own database and configure everything or do Flynn provide a way to configure the database settings?

**Comment by lmars** [comment]
Perhaps try `flynn -a postgres pg psql`

**Comment by furedal** [comment]
@lmars Simple as that! Thank you!
