### ISSUE TITLE
How to increase default /dev/shm size

### ISSUE THREAD

**Issue by ngrichyj4** [flynn/flynn#4263]
I'm using the google chrome headless browser with Selenium in a Rails app. The browser crashes randomly and all research & fixes points /dev/shm been too small. Is there a way in Flynn to set a custom size. A quick df -h shows the default size is 64MB.

Thanks.

**Comment by titanous** [comment]
It's currently hard-coded here: https://github.com/flynn/flynn/blob/144bd29b21873654fc500656ca2414e156184182/host/libcontainer_backend.go#L476

I think it makes sense to configure it via the existing limits infrastructure.

**Comment by ngrichyj4** [comment]
Great, thanks. I was able to build a custom flynn-host with the /dev/shm increased.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
