### ISSUE TITLE
TLS Handshake Error + Twilio / NewRelic

### ISSUE THREAD

**Issue by ggrochow** [flynn/flynn#4264]
Hey, I've been using flynn in production for about a year now, and decided to due a probably long overdue flynn version upgrade.

I've setup a new flynn-cluster of 3 servers, in the same configuration as our old one. ( as best as I could ). 
Due to some bugs I was unable to restore directly from a cluster-backup, or app-backups, so I manually set all the setting in an attempt to match our old-cluster.

Things seem to be working ok for end-users, accessing our site in the browser shows no signs of any issues. We are having some issues with external applications accessing stuff on our new server.

I've noticed two things that seem to be failing,
* We have a new-relic downtime detection setup on an app, which I believe is just a simple curl against a robots.txt file. It says we have something crazy like 99% downtime, though not a single user nor myself has reported any issues accessing the site since this started. 
* We have some twilio web-hook endpoints setup, but they seem to fail 90% of the time.  ( some do go through fine oddly enough ) The only information im really getting from twilio's end is a very generic [error 11220](https://www.twilio.com/docs/api/errors/11220) I've been doing some back-and forth with their support, but so far no real information has came from that. 

I was watching some logs as some twilio requests were failing, and it looks like the router was having some issues.
```
Oct 04 13:48:33 flynn20170829 router/app.flynn20170829-26e6a318-c5ed-44fd-bf8f-4e31eb331a5a: 2017/10/04 20:48:33 http: TLS handshake error from 70.70.178.88:65412: EOF
Oct 04 13:53:33 flynn20170829 router/app.flynn20170829-26e6a318-c5ed-44fd-bf8f-4e31eb331a5a: 2017/10/04 20:53:33 http: TLS handshake error from 70.70.178.88:49163: EOF
Oct 04 13:58:43 flynn20170829 router/app.flynn20170829-26e6a318-c5ed-44fd-bf8f-4e31eb331a5a: 2017/10/04 20:58:43 http: TLS handshake error from 70.70.178.88:49204: EOF
Oct 04 14:03:43 flynn20170829 router/app.flynn20170829-26e6a318-c5ed-44fd-bf8f-4e31eb331a5a: 2017/10/04 21:03:43 http: TLS handshake error from 70.70.178.88:49530: EOF 
```

Any idea what could be causing this / how I could go about debugging? 

What sort of information could I provide / look at that would help here? 

Im not the greatest at devops / debugging this sortof stuff, so any help here would be greatly appreciated.

**Comment by titanous** [comment]
It sounds like Twilio and New Relic have either extremely outdated TLS clients or there is a misconfiguration somewhere. Flynn provides no knobs to configure TLS, it comes with a secure configuration out of the box that you can see the details of at https://www.ssllabs.com/ssltest/

That message in the logs just indicates that the remote client disconnected before finishing the TLS handshake, it does not indicate a bug or issue on the Flynn side. In order to debug this you'll either need to get a packet capture of the handshake with tcpdump or have the vendors in question provide the exact errors they are getting.

**Comment by ggrochow** [comment]
I don't think they have anything super strange going on with their TLS clients, as both were working totally fine when pointed at my old flynn-cluster, with the same apps running.

Any ideas on how I could have mis-configured something along the way that would cause issues here? I at first was thinking maybe I goof'd with some firewall settings, since that was causing some issues at first, but these errors keep happening even when I disable ufw on all of my servers

I've noticed that on my [old server's SSLtest scan](https://www.ssllabs.com/ssltest/analyze.html?d=process.crewdriverapp.com&hideResults=on&latest) It had all servers 'graded', however a scan of my [new cluster's servers](https://www.ssllabs.com/ssltest/analyze.html?d=stage.crewdriverapp.com) show only a single 'grade'. Could this possibly be a 'hint' as where I could look?

As you can see, its a cluster of 3 servers, If I wanted to run a tcpdump and attempt to capture the handshake, would I need to record all servers at once, and figure out where the requests made it?

thanks for the quick response + any further assistance you can provide.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
