### ISSUE TITLE
Wildcard Routes with Path

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4266]
Hi,
is something like this possible?
flynn -a myApp route add http "*.test.com/myPath"
So all requests with matching this wildcard URL having the given path would end up in myApp.

**Comment by titanous** [comment]
Yes, that should work.

**Comment by philiplb** [comment]
Cool, thank you. I forgot to mention the actual problem. :) On execution, I get this result:

> validation_error: Invalid route

**Comment by trenta3** [comment]
I can confirm this behaviour. It also fails with the same error from the dashboard.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
