### ISSUE TITLE
remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#4267]
Hi There, 

We are running out of usable PG connections on our cluster.
How do we check howmany connections are at the moment allowed and change this setting? 

Currently we have 5 servers with 8GB - mem each.

**Comment by nicolas-brousse** [comment]
Hi,

Yesterday I install [pghero](https://github.com/pghero/pghero/) in my cluster to check how it looks with Flynn.
My configuration: 3 servers with 4cores + 4GB mem each.

I don't know if the PG configuration is set, but in my case, pghero show me when I check an app database:

![](https://i.imgur.com/ILVSmgH.png)

**Comment by nicolas-brousse** [comment]
I just saw that there is the postgresql configuration here https://github.com/flynn/flynn/blob/9fc0a690590a48e2e24b2f56aaaa9349a7cf9d20/appliance/postgresql/postgres.go#L893

**Comment by heldopslippers** [comment]
Oh PGhero would be a good idea! thanxs. 
And I found the config file in the flynn repo as well. 
Not sure how it works when you want to change a setting.

**Comment by heldopslippers** [comment]
Hmm apparently one database - user has 120 open connections. 
That seems excessive. How can I determine which one it is.

**Comment by nicolas-brousse** [comment]
I don't think you can change a setting of PostgreSQL database.

I also have one database - user who has 41 open connections.

I run this commands to have easily list of postgres database env values per app, if it could help you.
```sql
$ flynn -a controller pg psql
psql (9.5.5)
Type "help" for help.

ee30bc34f7d0eb809dac9c9b94ad6242=> SELECT a.name, r.env FROM resources AS r LEFT JOIN app_resources ar ON ar.resource_id = r.resource_id LEFT JOIN apps a ON a.app_id = ar.app_id WHERE r.provider_id = (SELECT provider_id FROM providers WHERE name='postgres');
```

In my case it is the controller who have 41 connections opened.

If you have the problem with one of your app, may be you could use this buildpack: https://github.com/heroku/heroku-buildpack-pgbouncer. I never used it but may be it could help you.

**Comment by heldopslippers** [comment]
Awesome @nicolas-brousse , thanxs so much for the info. 
I will dive into this and see if the PGbouncer is an option.

**Comment by heldopslippers** [comment]
So small update, I closed all apps. Still the amount of connections are incredibly high. 
I am not willing to close the systems apps, to see if that is the problem as this is a production system. 

But one app using 120 connections is just waaay to much. 
anybody have ideas how to tackle this problem?

**Comment by heldopslippers** [comment]
So another update:
Killing a few processes of the router and controller apps helps bring down the amount of connections for a few seconds. But this is very temporary. Currently it is over 206 connections, with 114 from the Router and Controller.

Would be awesome if one of the devs could give some tips on this issue.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
