### ISSUE TITLE
Timeline on security?

### ISSUE THREAD

**Issue by rw** [flynn/flynn#4268]
On your website, you say:

> Applications run within Flynn are not fully sandboxed and have access to internal Flynn APIs that can be used to gain root access on the server. Do not run untrusted code in Flynn.

> There may be other unknown security flaws in Flynn. For the time being we do not recommend running Flynn in environments where there is access to sensitive data or services.

> We are currently working to implement and improve basic security practices in Flynn so that it is secure by default, inside and outside. After that, the sky is the limit. Expect to see industry-leading security policies and practices baked into Flynn in the future.

This translates to: "don't make mistakes or get hacked". It makes even thinking about using Flynn pretty scary.

1) Do you have a timeline on implementing and auditing the security features you talked about?
2) Would you please add security labels to the choices for GitHub issues?

**Comment by titanous** [comment]
There is no specific timeline, but a variety of security features are in progress and will be landing in the coming months. Take a look at this project for details: https://github.com/flynn/flynn/projects/1
