### ISSUE TITLE
Sample Response for "List Active Formations" API doc is outdated

### ISSUE THREAD

**Issue by mltsy** [flynn/flynn#4269]
The sample response shown here: https://flynn.io/docs/api/controller#list-all-active-formations
is out of date - missing new fields and contains incorrect names and formats for some existing fields.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
