### ISSUE TITLE
Is Flynn abandoned?

### ISSUE THREAD

**Issue by michaelyork** [flynn/flynn#4271]
Seems like there's less and less activity here these days. :(

**Comment by lukaspj** [comment]
See #4244 and #4242

**Comment by titanous** [comment]
Nope, definitely not abandoned!

**Comment by michaelyork** [comment]
Great news, @titanous. Though the other referenced issues were a tiny bit vague – is the work that's happening for paid customers planned to port over to this repo? Or is that to remain closed-source?

Happy either way, just curious. :)

**Comment by titanous** [comment]
Most of the work we do for paying customers is support, not development. There are no closed source modifications to Flynn at all.

**Comment by michaelyork** [comment]
🙌
