### ISSUE TITLE
Blobstore Backend on Digital Ocean spaces

### ISSUE THREAD

**Issue by adam187** [flynn/flynn#4274]
Hi, i have a question about using [Digital Ocean spaces](https://www.digitalocean.com/products/object-storage/) for [Blobstore Backend storage](https://flynn.io/docs/production#blobstore-backend).

It looks like it have same api as [Amazon S3](https://www.digitalocean.com/community/tutorials/how-to-manage-digitalocean-spaces-with-s3cmd) so i guess it should be possible to use it for Blobstore Backend also?

**Comment by titanous** [comment]
You can try the [minio backend](https://github.com/flynn/flynn/blob/master/blobstore/backend/minio.go) which is designed to support generic S3-clone backends.

**Comment by JMSwag** [comment]
@adam187 Documented here -> #4456

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
