### ISSUE TITLE
Mysql default database charset 

### ISSUE THREAD

**Issue by narongdejsrn** [flynn/flynn#4275]
Hi.

Is it possible to modify default provisioning of mysql database charset and collation? My service need to provision a lot of mysql database to be utf8_unicode_ci and it would be nice to have this feature

Best Regards,

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
