### ISSUE TITLE
Again problems with our cluster

### ISSUE THREAD

**Issue by heldopslippers** [flynn/flynn#4276]
Our current problems: 

Router and Controller run with a total of 100 connections to the postgres db. This is a lot. 
For us there is no way to fix this. 
Also the router currently is running with 2 different releases (why, I have no idea). 
tried to kill one of them but it keeps getting restarted.

**Comment by hadifarnoud** [comment]
it's perhaps time to migrate to another PaaS. We have many issues with `Service Unavailable` too. It feels like Flynn has been abandoned unfortunately. The support is non-existent and there is no new bugfix or new features. 

it is a great platform and I hate to see it sunset

**Comment by heldopslippers** [comment]
hi hadifarnoud, 

We actually switched to Nanobox last week. We had so many problems with Flynn. 
It's a black box with a lot of problems, and no support. 

Really happy with Nanobox though!

**Comment by hadifarnoud** [comment]
Flynn was so promising imo. it's a shame to see it die

**Comment by titanous** [comment]
Flynn is definitely not dead, as explained in #4244.
