### ISSUE TITLE
docker push remote error: tls: internal error

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#4279]
Bit new to docker so might be doing something wrong but when I try to push my image I get an error of `Get https://docker.myhost.com/v2/: remote error: tls: internal error`

**Comment by dottodot** [comment]
Actually might be something to do with `flynn docker login` as that also gives an error of 

```
error running `docker login`: exit status 1 - output: {"WARNING! Using --password via the CLI is insecure. Use --password-stdin.\nError response from daemon: Get https://docker.myhost.com/v2/: remote error: tls: internal error\n" '\x00' "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" '\x00'}
```

**Comment by lmars** [comment]
What version of Docker are you using (check `docker version`).

**Comment by dottodot** [comment]
Client:
Version: 17.10.0-ce

**Comment by lmars** [comment]
I am unable to reproduce this. What OS and version are you running? What happens when you hit the endpoint using curl (`curl -v https://docker.myhost.com/v2/`)?

**Comment by dottodot** [comment]
this is what i get 

> * TCP_NODELAY set
> * Connected to docker.myhost.com (0.0.0.0) port 443 (#0)
> * Unknown SSL protocol error in connection to docker.myhost.com:-9838
> * Closing connection 0
> curl: (35) Unknown SSL protocol error in connection to docker.myhost.com-9838

**Comment by lmars** [comment]
Ok, I suspect there is something wrong in your cluster. What is the output of the following right after trying `flynn docker login`:

```
$ flynn -a docker-receive ps

$ flynn -a docker-receive scale --all

$ flynn -a router log --number 10 --raw-output
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
