### ISSUE TITLE
flynn-host bootstrap error

### ISSUE THREAD

**Issue by zookz** [flynn/flynn#4282]
flynn-host version :
v20170719.0-81418bc

09:45:16.884597 check online-hosts
09:45:17.404917 require-env require-env
09:45:17.404949 resource-check resource-check
09:45:17.415840 run-app discoverd
09:45:17.799141 run-app discoverd error: bootstrap: host error while launching job: "error getting squashfs layer from https://dl.flynn.io/tuf?target=/layers/6dc530a0d72a16d92ebf587ac63d7ea243bcb0c351b100d485069586e52c145a.squashfs: verify: data too short"

flynn-host collect-debug-info :
https://gist.github.com/anonymous/a3fdbce0b6a2a58e0c3aebf389e357b2

**Comment by lmars** [comment]
Run `sudo flynn-host download` and then try again.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
