### ISSUE TITLE
Linux module missing after hard reboot on Linode

### ISSUE THREAD

**Issue by j105** [flynn/flynn#4283]
flannel.1, flynnbr0, and veth* are missing

flynn-host list timeout

How can I re-boostrap node and join into existing cluster?

Any help appreciated thanks

**Comment by j105** [comment]
```t=2017-11-17T05:53:12+0000 lvl=eror msg="error running job" app=host pid=5127 host.id=node135 fn=AddJob job.id=node135-35a26452-88a0-4323-884f-ffb2610fe525 err="error getting squashfs layer from https://dl.flynn.io/tuf?target=/layers/6dc530a0d72a16d92ebf587ac63d7ea243bcb0c351b100d485069586e52c145a.squashfs: verify: data too short"```

**Comment by philiplb** [comment]
What was your solution?

**Comment by lmars** [comment]
I suspect the kernel got upgraded, in which case the ZFS kernel modules need to be recompiled by running:

```
$ dpkg-reconfigure spl-dkms
$ dpkg-reconfigure zfs-dkms
```
