### ISSUE TITLE
Fresh installation flynn-host list timeout

### ISSUE THREAD

**Issue by j105** [flynn/flynn#4284]
Tried both Linode & DO

flannel.1, flynnbr0, and veth* network interfaces are not there.

**Comment by lmars** [comment]
Did you follow the [manual installation docs](https://flynn.io/docs/installation/manual)? Did you get any errors along the way?

**Comment by j105** [comment]
@imars there wasn't errors along the way. I am able to bootstrap single node cluster but not 3 nodes formation. flynn-host list command timeout. There is nothing listening on port 1111.

**Comment by lmars** [comment]
Is flynn-host running on each of the three servers? There will only be something listening on port 1111 if you successfully bootstrap the cluster, so what happens when you run `flynn-host bootstrap` in the 3 node cluster?

**Comment by j105** [comment]
Both 3 ```flynn-host``` status are green which means up & running.
Just not being able to ```flynn-host list``` to get a list of peers.

**Comment by j105** [comment]
@lmars any thoughts?

**Comment by lmars** [comment]
@j105 please post both the command you are running and the output of `flynn-host bootstrap` in the 3 node cluster.
