### ISSUE TITLE
Not able to bootstrap multi-nodes cluster

### ISSUE THREAD

**Issue by j105** [flynn/flynn#4288]
Here is the debug info

https://gist.github.com/9e21d961660f7dfebb4c9778a53a9396

**Comment by j105** [comment]
@lmars Could you please help? thanks

**Comment by lmars** [comment]
That debug info shows `flynn-host` is running and waiting to be bootstrapped, what happens when you run `flynn-host bootstrap`? Please post the exact command you are running and the output you get.

**Comment by j105** [comment]
It times out and not able to find 3 nodes.

**Comment by lmars** [comment]
Please post the output.
