### ISSUE TITLE
Error after restart

### ISSUE THREAD

**Issue by theprogramer** [flynn/flynn#4297]
EROR[12-06|09:26:10] error getting scheduler state            err="Get http://100.100.23.4:5000/debug/state: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"

**Comment by theprogramer** [comment]
Could not recover it.
I needed to create a new cluster.
I found some similar issues: #3424 #4155 #4167 #4107.
There is a wondering way to recover this?
I'm coming from dokku and today I was 4hs offline.
This is worrying.

**Comment by titanous** [comment]
Without the full cluster logs, we will not be able to diagnose the issue and fix bugs (if any).

**Comment by theprogramer** [comment]
I really missed the logs.
How can I generate them? If needed again.

flynn-host collect-debug-info gave me

`EROR[12-06|09:26:10] error getting scheduler state err="Get http://100.100.23.4:5000/debug/state: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"`

flynn-host fix --min-hosts = 1 everything was green but did not solve ...

I was very happy with Flynn
It's a great job.

**Comment by reneweteling** [comment]
Im getting the same error im afraid...

![image](https://user-images.githubusercontent.com/3830933/35506793-d554ab60-04ea-11e8-8c98-75b332868e87.png)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
