### ISSUE TITLE
Error: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by Kentoseth** [flynn/flynn#4298]
I have been getting this error (for the unsupported `flynn-install` binary):
```
Error: Post https://domains.flynn.io/domains: x509: certificate has expired or is not yet valid 
```

I know that the devs have said they are no longer supporting it, but if anybody else has gotten this issue and has a fix for it, please share what you did to fix this issue.

**Comment by titanous** [comment]
The supporting infrastructure (including domains.flynn.io) for `flynn-install` has been shut down, so this won't be fixed.

**Comment by Kentoseth** [comment]
wow that was quick :)

Thanks for clarifying.
