### ISSUE TITLE
Unable to install CA Certificate and continue

### ISSUE THREAD

**Issue by khalidadil** [flynn/flynn#4302]
I'm following the guide over all [https://flynn.io/docs/cli](https://flynn.io/docs/cli) with a clean digitalocean box on Ubuntu 16.

I have setup flynn with a single node and am able to access the dashboard. When accessing the dashboard, I see a message that a CA certificate needs to be installed. I have downloaded the certificate, added it to the keychain, set it as trusted, closed the dialog, and provided my admin password, but when clicking the 'All Done' button, I continue to be redirected to the same page.

These are the steps in [video form](https://cl.ly/1R3F1b0P2A1G). Are there any clear mistakes that I'm making?

Update: I have restarted my Macbook Pro (10.11.6) and restarted the browser (Chrome and Safari) and this still does not work. I followed the steps to install a certificate on my Windows computer and that worked, but my work machine is the Mac.

I have also tried removing and reinstalling the certificate on my Mac, but didn't see any different results.

**Comment by mathiasjakobsen** [comment]
@khalidadil Hi Khalid. Did you find a solution for this issue? We are having the exact same problem.

**Comment by jvatic** [comment]
@khalidadil Sorry for the late response, it seems this issue got buried.

I am unable to reproduce this issue and suspect certificate management with keychain may be acting up on your machine. If this issue persists, please try using Firefox which manages the certificate itself and is known to work consistently.

**Comment by khalidadil** [comment]
I tried Firefox and it worked as expected. I was still having issues with Chrome and Safari, so I then:
1) Updated Flynn and Ubuntu on my server
2) Reset my public/private SSH keys (unlikely to be related, but one of the steps I took)
3) Deleted the certificate in the keychain (I had tried this step in the past)

Now it seems to be working for me in Chrome 69.0.3497.100/Firefox 62.0.2/Safari 11.1.2.
