### ISSUE TITLE
Blobstore fills up locally when using s3main

### ISSUE THREAD

**Issue by furedal** [flynn/flynn#4304]
Hey
I have setup my flynn cluster using AWS s3 as blobstore.
Following the guide, I have managed to migrate my slugs to my s3. It works fine when Flynn creates a new slug. It will be uploaded to my s3.
The problem that is occurring is that the same slugs also persist locally and now my disk is full. I guess that I wont be able to remove the slugs now as postgres vacuum requires double the diskspace.
I tried `flynn -a blobstore run /bin/flynn-blobstore cleanup` but it ended up removing all the slugs from my S3 but not the local ones.

Is it required that i vacuum postgres every time when i create new slugs or what?
Is there any way to remove the existing slugs without having any diskspace?

` flynn-host --v`
`$v20170719.0-81418bc`

**Comment by artemave** [comment]
@furedal I am seeing something similar (I think). Have you managed to sort this out?

**Comment by furedal** [comment]
@artemave Hey, yes and no. I found that you can run `flynn-host volume gc` and flynn cleaned up a few gb for me. I am not sure if it is cleaning all the leaking slugs, but for now this works for me.

**Comment by artemave** [comment]
This fixed my issue, thanks!

But, like you say, it's not ideal... I am going to add a cron job on one of the hosts to run gc daily.

**Comment by furedal** [comment]
You should probably do some pushes and see if there is anything new to clean up before relying on the gc. Good luck.

**Comment by artemave** [comment]
I can see new volumes appearing after few pushes.

**Comment by lmars** [comment]
Flynn doesn't yet have automatic garbage collection for volumes (see #2750), so the current fix is to run `flynn-host volume gc` periodically on each host in your cluster.

**Comment by furedal** [comment]
Thanks, good to know! No bugs then, only lack of reading the documentations I guess! :)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
