### ISSUE TITLE
Question: How to handle child/worker processes

### ISSUE THREAD

**Issue by joshfester** [flynn/flynn#4308]
I'm setting up a pretty standard Rails app with Puma server. Say I have 3 nodes with 2 cores each, and I'd like to have one Puma process per core. Each Puma process can have multiple worker processes. Should I set Flynn to make 3 web (Puma) processes (one for each server node), and then configure Puma to have 2 worker processes each (one per core on each web process)? Or should I use one web process and configure Puma to use 6 worker processes (one per core total)? I can't find any reference to this scenario in the docs. Thanks!

**Comment by nicolas-brousse** [comment]
Hi,

Flynn doesn't have knowledge of the puma configuration you will make. And it is not really its job.  
If I'm not wrong, to have the scenario you describe, you need to define:
- 3 web processes on Flynn CLI or dashboard
- tell puma to 2 worker processes

I'm not completely sure that setting 3 web processes will create 1 processes per node. But when I did some tries it was what I had.

But I'm sure that if you ask for 1 web process and configure Puma to use 6 workers, it will not create 1 process per node. It will be 1 process on only 1 node with 2 cores with Puma asking for 6 workers.

**Comment by joshfester** [comment]
Awesome. Thanks for the quick answer!

**Comment by lmars** [comment]
> I'm not completely sure that setting 3 web processes will create 1 processes per node. But when I did some tries it was what I had.

To clarify, Flynn will distribute processes for the same app and type evenly across nodes in the cluster (so 3 web processes in a 3 node cluster will always run 1 process on each node).
