### ISSUE TITLE
Question: Server monitoring

### ISSUE THREAD

**Issue by joshfester** [flynn/flynn#4309]
Does Flynn provide any method for monitoring each node via something like New Relic? Or would monitoring agents need to be manually installed on each node? Or maybe install via a buildpack and then set the number of processes to the number of nodes? I'm just trying to figure out the best practices

**Comment by lmars** [comment]
Flynn does not currently have a built-in monitoring solution.

You can either run a monitoring agent as a Flynn app and deploy using a Docker image, or manually install a monitoring agent on each node in your cluster directly.
