### ISSUE TITLE
Building PHP app with private SSH composer requirements

### ISSUE THREAD

**Issue by GBeushausen** [flynn/flynn#4310]
Hi,

i'm evaluating Flynn. I would like to test a PHP7 app wich uses a private dependency using composer. The code is not stored on Github or BitBucket. It's stored in AWS codecommit. To be able to access it with SSH, you need a config file in ~/.ssh and a private key.

I've set the private key in both the app and git-receive environments. In composer i've added the following preinstall script:

` #!/bin/bash
    # Generates an SSH config file for connections if a config var exists.

    if [ "$GIT_SSH_KEY" != "" ]; then
      echo "Detected SSH key for git. Adding SSH config" >&1
      echo "" >&1

      # Ensure we have an ssh folder
      if [ ! -d ~/.ssh ]; then
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
      fi

      # Load the private key into a file.
      echo $GIT_SSH_KEY | base64 --decode > ~/.ssh/deploy_key

      # Change the permissions on the file to
      # be read-only for this user.
      chmod 400 ~/.ssh/deploy_key

      # Setup the ssh config file.
      echo -e "Host git-codecommit.*.amazonaws.com\n"\
              " User XXX\n"\
              " IdentityFile ~/.ssh/deploy_key\n"\
              > ~/.ssh/config
    fi
`
Unfortunately composer cannot clone this repository. The answer is always:

 Host key verification failed.

I've added some debug data within the preinstall script, so i already know that the config file and  the SSH keys are both correct. I wonder why the build process doesn't use the SSH key configuration?

Best regards,

Gunnar

**Comment by lmars** [comment]
@GBeushausen the "Host key verification failed" error happens because you haven't explicitly trusted the remote SSH host key.

Flynn already has support for this by setting the `SSH_CLIENT_KEY` and `SSH_CLIENT_HOSTS` environment variables on the `gitreceive` app, for example:

```
$ flynn -a gitreceive env set SSH_CLIENT_HOSTS="$(ssh-keyscan -H github.com)" SSH_CLIENT_KEY="$(cat ~/.ssh/id_rsa)"
```

Change `github.com` to the host you are connecting to.

See https://flynn.io/docs/production#ssh-client-key.

**Comment by GBeushausen** [comment]
Great. Thanks. I missed that point. Now it works perfectly.
