### ISSUE TITLE
Error writing CA certificate: i/o timed out

### ISSUE THREAD

**Issue by ticruz38** [flynn/flynn#4312]
after a git push, my flynn CLI stopped working with such messages. I removed the cluster and added it again but impossible to connect to the controller.
The funny thing is that the cluster is still working, the dashboard does connect to my apps, and everything is working fine on another machine.

`flynn cluster add -p <key> default flynn.example.fr <otherkey>`
> Error writing CA certificate: Get https://controller.flynn.example.fr/ca-cert: dial tcp: i/o timeout

Should I remove a certificate somewhere? How comes I get a timeout on my local machine, when I can connect with my cloud machine or via a get in the browser?

**Comment by fmendoza** [comment]
Same here. Did you manage it to fix this issue?

**Comment by ronalddas** [comment]
Even i am getting the same i/o timeout error. I am able to access my dashboard though.

**Comment by crawfordleeds** [comment]
I was receiving this error and it seems to have been an issue of the firewall. Here are my firewall rules in Digital Ocean.
<img width="945" alt="Screen Shot 2019-11-26 at 2 57 41 PM" src="https://user-images.githubusercontent.com/25166339/69676015-24957900-105d-11ea-95c3-70e0ca2da7c8.png">

Just changing the firewall on an existing droplet didn't seem to do the trick, I had to set the firewall rules then destroy the droplet and create a new one.

**Comment by innomadic** [comment]
I get this error when I try to do an initial `flynn cluster add`  with vanilla Flynn demo box.  

Error writing CA certificate: Get https://controller.demo.localflynn.com/ca-cert: dial tcp 192.0.2.200:443: i/o timeout

**Comment by innomadic** [comment]
I got this again when I tried to deploy to a remote server, but resolved it after I made a correction to my DNS.

Still don't know why it didn't work in my local vagrant installation. Maybe, thought, still related to name resolution.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
