### ISSUE TITLE
Question: setting limits via controller API

### ISSUE THREAD

**Issue by artemave** [flynn/flynn#4314]
I have this little automation where after creating an app (via contorller api) I want to bump up its slugbuilder temp_disk.

Following the way `flynn limit set` works, I am trying to create a release with the following payload:

```
{
  app_id: MY_APP_ID,
  processes: {
    slugbuilder: {
      resources: {
        temp_disk: {
          limit: '2GB'
        }
      }
    }
  }
}
```

But that fails with `400 Bad request`. Something must be wrong with the above payload but I can't work out what.

Question 1: what is wrong?

Question 2: is there a controller debug mode where I can see what's being posted to it (to reverse engineer cli requests)

Thanks!

**Comment by lmars** [comment]
@artemave creating (and subsequently deploying) a new release via the API is a little involved, have you considered just running `flynn limit set` as a sub-process?

**Comment by lmars** [comment]
Related: https://github.com/flynn/flynn/issues/3854

**Comment by artemave** [comment]
I managed to repurpose a fake flynn controller from my tests to capture requests from the cli. So, for the reference, this is the json payload of `flynn set limit slugbuilder temp_disk=1GB`:

```
{
  "app_id": "2",
  "processes": {
    "slugbuilder": {
      "resources": {
        "cpu": {
          "request": 1000,
          "limit": 1000
        },
        "max_fd": {
          "request": 10000,
          "limit": 10000
        },
        "memory": {
          "request": 1073741824,
          "limit": 1073741824
        },
        "temp_disk": {
          "request": null,
          "limit": 1073741824
        }
      }
    }
  }
}
```

Thanks!
