### ISSUE TITLE
Meltdown and Spectre

### ISSUE THREAD

**Issue by nicolas-brousse** [flynn/flynn#4315]
Hi,

Did you notice something we need to know about Meltdown and Spectre?  
Does upgrading the node(s) kernel(s) is enough?

Thanks.

**Comment by titanous** [comment]
Flynn does not require any patches for Meltdown/Spectre, but you should install the patched Linux kernel release when it is available for Ubuntu.

**Comment by nicolas-brousse** [comment]
Thanks for the answer
