### ISSUE TITLE
New stable version?

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4319]
Hi,
as of writing this issue, the current stable version is v20170719.0. This is quite some month old and quite some fixes have been done since then.
Are there any plans to release a new stable version soon?

**Comment by titanous** [comment]
Hey, sorry for the delay, I'm aiming to do a stable release next week.

**Comment by philiplb** [comment]
I would guess next third tuesday of this month, the 20th, then?

**Comment by Arm1stice** [comment]
@titanous Any update on a stable release? Is this project still being actively maintained?

**Comment by titanous** [comment]
Yes, the project is still maintained. We run nightly internally, and haven't had the time to do a stable release recently (which would just bump the current nightly release to the stable channel). This is still on my list to do, but in the mean time I'd suggest just using the nightly channel.

**Comment by Arm1stice** [comment]
Ah, I understand. Thank you for the quick reply.

**Comment by philiplb** [comment]
Any news on this?

**Comment by philiplb** [comment]
Release scheme will switch to nightlies only, see https://github.com/flynn/flynn/issues/4397 .
