### ISSUE TITLE
Flynn apps booting after server restart

### ISSUE THREAD

**Issue by reneweteling** [flynn/flynn#4321]
Hi,

I needed to do some patches on the server this required a restart after the restart Flynn did come back (the daemon) but the web services didn't. I've tried everything I could think of, updated Flynn to the latest version, tried to get the debug-info and even tried to bootstrap the server again (on a copy). The latter did work, only all the data was lost, Flynn was in its initial state. I've got a couple of apps running on Flynn, including my backup app. (this makes restoring the cluster quite difficult) 

When trying to collect the debug info the job hangs.

```bash
root@Ubuntu-1604-xenial-64-minimal / # flynn-host version
v20170719.0-81418bc
root@Ubuntu-1604-xenial-64-minimal / # flynn-host ps
ID                                                              STATE    CREATED         CONTROLLER APP  CONTROLLER TYPE  ERROR
Ubuntu1604xenial64minimal-2bbaadff-2c66-4be9-9903-a61a00e54051  running  29 minutes ago  controller      scheduler
Ubuntu1604xenial64minimal-a3f06c02-4dfa-419f-a6de-5fe3f1ba24a7  running  29 minutes ago  controller      web
Ubuntu1604xenial64minimal-dec1ed4e-82a4-4937-96dd-87a28287ab3b  running  29 minutes ago  mongodb         mongodb
Ubuntu1604xenial64minimal-41ac12d3-98fe-43e0-959b-e223cab5d2ac  running  29 minutes ago  postgres        postgres
Ubuntu1604xenial64minimal-3277231e-9c3c-4292-a2c6-e7d5179c7880  running  31 minutes ago  discoverd       app
Ubuntu1604xenial64minimal-17b97d8d-650d-43a6-9eb5-a4bcf6cd1254  running  31 minutes ago  flannel         app
root@Ubuntu-1604-xenial-64-minimal / # flynn-host collect-debug-info
INFO[01-29|13:15:18] uploading logs and debug information to a private, anonymous gist
INFO[01-29|13:15:18] this may take a while depending on the size of your logs
INFO[01-29|13:15:18] getting flynn-host logs
INFO[01-29|13:15:22] getting sirenia metadata
INFO[01-29|13:15:22] getting scheduler state
EROR[01-29|13:15:32] error getting scheduler state            err="Get http://100.100.76.5:5000/debug/state: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
INFO[01-29|13:15:32] getting job logs
```

What i find curios is that the host-state.bolt file is over 1GB in size. This seems odd...

All help is extremely welcome, this is costing me money, so if i need to hire someone here, or contribute beers somewhere id me more than happy to do so.

Thanks

**Comment by lmars** [comment]
Try `flynn-host fix --min-hosts N` where `N` is the number of hosts in your cluster.

**Comment by lmars** [comment]
Also, you can clean ip the host state with the instructions in this gist:

https://gist.github.com/lmars/cfb46fe104d1c17be8f22acf41c907e9

That may be the cause of the issue here.

**Comment by reneweteling** [comment]
Hi @lmars, i have already tried this, thats not working, the state cleaner is quite impressive

```bash
INFO[01-29|17:33:07] deleting job                             id=Ubuntu1604xenial64minimal-fffe9bcd-f550-4a7b-b6a7-e54bccbca652
INFO[01-29|17:33:07] deleting job                             id=Ubuntu1604xenial64minimal-ffff5df8-0daf-48e0-a721-a7d92e9f97a0
INFO[01-29|17:33:07] deleting job                             id=Ubuntu1604xenial64minimal-ffff91ad-3d59-48e0-b6fb-d34a4e9754db
INFO[01-29|17:33:07] successfully cleaned state database      path=/var/lib/flynn/host-state.bolt deleted-jobs=130983
```

im restarting now, lets hope

**Comment by reneweteling** [comment]
@imars this is awesome, flynn-host is quick again, flyn-host ps usually takes about 1 minute to respond now its direct, all my apps are booting again :)

Thanks!!!!!! so much!!!!
