### ISSUE TITLE
Question: how does Flynn secure my Git repository in my server?

### ISSUE THREAD

**Issue by zulhfreelancer** [flynn/flynn#4323]
Hi,

I'm coming from Heroku background and I really like Flynn so far. I am aware that everytime I run `flynn create` command, it will auto-create Git remote for me which I can deploy my app easily later using `git push flynn master` command just like Heroku.

In Heroku land, I ran `heroku login` to authenticate myself to the Git repo inside Heroku. But when I use Flynn, there is no equivalent command for that.

So, I am curious here. How does Flynn secure the Git repo inside my server?

Can someone copy my Flynn's Git remote, add it into their dev environment as `flynn` remote, push and overwrite my app?

Thanks.

**Comment by lmars** [comment]
@zulhfreelancer when you run the initial `flynn cluster add` command on your machine, some credentials are written to a `.flynnrc` file in your home directory which give you access to the Flynn cluster.

Git is also configured to use the Flynn CLI for credentials when pushing to the Flynn cluster via the [credential helper](https://git-scm.com/docs/gitcredentials) (you can see this in your `~/.gitconfig` file).

So, if someone copies your git remote, they also need to have Git configured to use the Flynn CLI, and the Flynn CLI also needs to be configured with the credentials of your cluster, so as long as you don't share `~/.flynnrc` then they will not be able to access the git remote.

**Comment by zulhfreelancer** [comment]
This is really cool and helpful. Thank you for answering my question! 🙂
