### ISSUE TITLE
Flynn CLI instalation will fail on Linux and/or in fish (shell)

### ISSUE THREAD

**Issue by Darkless012** [flynn/flynn#4325]
Example installation script will fail on Linux if the targeted directory is not writable to user.
(/usr/local/bin/ is owned by root and has `drwxr-xr-x` permissions)

see: https://flynn.io/docs/cli#installation

```
$ L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
bash: /usr/local/bin/flynn: Permission denied
curl: (23) Failed writing body (0 != 16384)
```

Second issue is with running this script in fish (or any other shell), since this command is using bash syntax.

Therefore I would like to suggest improved version of this "cli instalation command" in following form:

```
sudo bash -c 'L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L'
```
This will start new bash as a superuser - which will solve both problems (access rights + bash syntax)

However I'm not sure how this command will work on MAC machine.

Also I wanted to make pull-request for the corresponding DOCs, but I couldn't find it in repo.
https://flynn.io/docs/cli#installation

**Comment by ndyakov** [comment]
Hey, just tested this in OSX High Sierra with `fish version 2.3.1`. Works fine.

**Comment by titanous** [comment]
It also works fine on ZSH. Can you describe the shell issue you ran into?

**Comment by ndyakov** [comment]
@titanous He probably meant that only `L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L` won't work in `fish` or `zsh`

**Comment by titanous** [comment]
It definitely works fine with zsh.

**Comment by ndyakov** [comment]
@titanous It does not in fish:
```
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
fish: L=/usr/local/bin/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
```

**Comment by Darkless012** [comment]
@ndyakov @titanous Thanks for the tests :), I've updated the title.

Can you run the cli installation command without root elevation on Mac? If so, who is the owner and what are the rights on /usr/local/bin/ folder on Mac?

**Comment by ndyakov** [comment]
@Darkless012 works without sudo, the logged in user is the owner (i guess if it's in the admin group) `admin` is the group of `/usr/local/bin`

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
