### ISSUE TITLE
Error when trying to push to a backed-up cluster

### ISSUE THREAD

**Issue by martinrisseeuw** [flynn/flynn#4326]
I moved my cluster recently from one server to another. Everything seems to run fine the only problem is that I can't push any changes anymore. When I try to push the changes it returns this error:

```
fatal: unable to access '<repo url>': error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01
```

I tried googling the error but without any succes maybe someone can point me in the right direction? 

After moving I installed also another cluster from scratch on another server and this works like a charm. I checked if im currently on the right cluster with the flynn cli and this is the case. So it seems like something did went wrong with using the back-up unfortunately I don't have an idea where to start.

**Comment by SalvoLunar** [comment]
Hi @martinrisseeuw did you manage to solve this?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
