### ISSUE TITLE
Bootstrap: "check online-hosts error: timed out" Issue

### ISSUE THREAD

**Issue by andreykats** [flynn/flynn#4327]
I'm attempting to deploy a 3 node cluster on 3 fresh AWS EC2 Ubuntu 16.04.3 instances. I'm following the instruction to a T but keep getting "check online-hosts error: timed out waiting for 3 hosts to come online (currently 0 online)" when doing the bootstrap command. The security policy that i've attached is open to all traffic, has internet, and i'm able to ping all 3 instances. 

I must be missing something.
Can someone please offer some wisdom?

**Comment by titanous** [comment]
This almost always indicates that there is a communication issue between hosts. Check that:

- You haven't reused a discovery token.
- There are no iptables/ufw rules in place.
- UDP is allowed between hosts in your security groups.
- Docker is not installed on any hosts.

If all of those things check out, please run `flynn-host collect-debug-info` and post the resulting gist here.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
