### ISSUE TITLE
How To use Persistent Volumes? 

### ISSUE THREAD

**Issue by trenta3** [flynn/flynn#4329]
I can see that many issues about Persistent Volumes were closed as solved (#534, #2438, #585).
Moreover, some issues from a couple years ago were asking about flat-file storage volumes (#4126, #1681) and the answer they got was something like: "this is work in progress, we will eventually get there":
> Flynn currently supports adding ZFS volumes to your applications which means data saved to the volume will be persisted even if the job dies, but these volumes are not currently sticky, so whilst the data remains on disk, restarting your app will get a new, empty volume. This will be fixed by our v2 scheduler.

The v2 scheduler has already been out for some time now (#1484) but nonetheless I couldn't find any documentation whatsoever (both using `flynn help` and looking at the website) on how to use Persistent Volumes and there are even confused informations on what can currently be done with them.

---

So I'd like to know if the following things can be done now on flynn and **how** (and if not now, then if they are scheduled and what is their ETA):
1. **Flat-file storage**: e.g. mount a volume under `/data` such that the process in the docker can freely read and write it. Which limitations does it have? If I start a new job will it be able to access the same volume or will it create a new empty one?
   If I always have **at most one** job running, will it always have the same volume underlying or it can be that sometimes (maybe after a restart) the volume is found to be empty?
2. **Volume management from flynn CLI**: Is it possible to snapshot volumes and to backup them as per issue #534?
   In the same issue it is written that, in order to attach a volume, it is sufficient to specify `"data": true` in the release file. If i do as said, flynn will warn me to prefer specifying `"volumes": [{"path": "/data"}]`. Can there be multiple volumes attached at different paths?
3. **How to run commands in a container with volume attached**: `flynn run` should spawn a new container, which from my "experiments" doesn't seem to have any volumes attached. How can i "play" or "see" what is inside the volumes?
   My "experiments" consisted in creating a fake single-page web process, updating the release inserting `"data": true` as appropriate. Using `flynn ps` and `flynn volume` I can see that a volume was created and attached to the `web` job, but when using `flynn run` no volume is attached to the `run` job.
4. **Volume documentation**: Where can I find more informations about which kinds of volumes are available, how they are assigned to jobs and how they can be effectively deployed on a flynn cluster?

Thank you in advance for any further information.

**Comment by trenta3** [comment]
Concerning point 1 from my previous message, after some tests I managed to attach a flat-file storage to my jobs. I'm including below a description of how to do that, but **be aware that these commands are not supported by any information on the internals of flynn, so using them in production may result in data losses. Be also aware that I have tested them only on a single machine cluster**.

------
## Flat-file storage: Mount a read-write "persistent" volume under a given path
```
LOCAL_CLI$ flynn release
<IDs> <Created_Dates>
LOCAL_CLI$ flynn release show --json <ID>
{ ... }
```

Now add the key `processes.web.volumes = [{"path": "<path>"}]`.

```
LOCAL_CLI$ flynn release update <updated_json>
Release updated ...
```

Now you have a flat file storage you can write to under `<path>`.
Unfortunately you usually cannot write to it because it is owned by user `root` while every process running inside the container is owned by user `flynn`.

So you have to log to you flynn machine as root user, and change ownership of the zfs volume.
```
LOCAL_CLI$ flynn ps
<Ps_IDs> <Types> <States> <Created> <Releases>
LOCAL_CLI$ flynn volume
<Vol_IDs> <Hosts> <States> <Attached Job> <Created> <Decommissioned>
```

Search the volume ID which has the field attached job equal to the ps ID.

```
root@flynn# mount | grep <Vol_ID>
root@flynn# cd /var/lib/flynn/volumes/zfs/mnt/data/<Vol_ID>
root@flynn# chown -R 5000:5000 .
```

You now have a storage you can also use! Hurray!

From my tests scaling the number of jobs to zero and then back to one does not loose the volume, and when scaling to two jobs they can both access the same volume.
------

I would like to know if these instructions work at all and if they should work by design or it is only an accident.
Thank you in advance.

**Comment by augnustin** [comment]
Hum, not sure this is a decent solution.

I'm quite new with flynn, and pretty surprised this case is not handled yet, but I have experience with docker. 

What you are doing feels like you are using a `/tmp` folder to store your actual data, hoping this won't be deleted at some point... not acceptable. 

The notion of persistent volume seems to exist in flynn (https://flynn.io/docs/cli#volume) but I just can't understand how to use it.

What is expected is a mounting point from a host, that would be available on every release without changing its name.

Any further insights on this would be welcome from the flynn team.

Cheers

**Comment by trenta3** [comment]
@augnustin Indeed.
I was just reporting here my experiences but I never used such setup in production and I also strongly advise against it.

In general, I would recommend you to stay away from flynn for the following reasons (but it is also about 8 months that I'm not using it anymore, so not sure if these are fixed now):
* Absolutely no documentation about internals or working details. Some features are claimed to exist here and there (such as persisten volumes) but there is no documentation on how to use them
* Issues are abandoned: they generally do not get any official reply even about easily solvable problems
* During the time I've used flynn (about one year, if I remember well) my single machine cluster suddenly broke 4 times without any reasons and with the `fix` command doing nothing good to restore its functionality: I've had to reinstall it from scratch and loose all data (except backups obviously).

Please consider searching for another PaaS.

**Comment by roshanjonah** [comment]
@trenta3 Have you found any other alternatives that seem to resolve this or address this? Because all our apps require persistent storage.

I am surprised Flynn supports databases out of the box but people are struggling to set up a stateful app with persistent storage?!

**Comment by trenta3** [comment]
Hi! I'm no longer using Flynn, and I left because I received no answers
from the Flynn team in many months and different requests, and because I
had data loss in my hobby cluster four times, without machine failure.

Nowadays there are more adequate PaaS products IMO than flynn.
I would probably suggest using buildpacks and docker over a kubernetes
installation.
There are many hassle-free ways to install kubernetes right now, like using
microk8s or rancher depending on the size of your installation, and they
come already with many useful tools like dashboards, monitoring, high
availability and the like.
The learning curve is a little bit steeper but it is worth the efforts.
Gitlab for example has free CI minutes and kubernetes integration so you
can build a docker image using buildpacks in the CI pipeline and then
deploy on your cluster directly.

Feel free to ask if something isn't clear.
Best wishes

**Comment by augnustin** [comment]
Flynn is dead :skull:

**Comment by Berndinox** [comment]
> Hi! I'm no longer using Flynn, and I left because I received no answers from the Flynn team in many months and different requests, and because I had data loss in my hobby cluster four times, without machine failure. Nowadays there are more adequate PaaS products IMO than flynn. I would probably suggest using buildpacks and docker over a kubernetes installation. There are many hassle-free ways to install kubernetes right now, like using microk8s or rancher depending on the size of your installation, and they come already with many useful tools like dashboards, monitoring, high availability and the like. The learning curve is a little bit steeper but it is worth the efforts. Gitlab for example has free CI minutes and kubernetes integration so you can build a docker image using buildpacks in the CI pipeline and then deploy on your cluster directly. Feel free to ask if something isn't clear. Best wishes

May you have an more in detail example on how to use your workflow?
I'm very interessted, unfortunately i'm absolutely new to buildpacks. 

I would like to convert an old statefull php app to something "scaleable" inside a Container!

BR Bernd

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
