### ISSUE TITLE
Arango support

### ISSUE THREAD

**Issue by OKNoah** [flynn/flynn#4330]
Hi,

Is there any interest in supporting ArangoDB on Flynn?

In any case, I'd like to know if it's possible to set up the Docker container.

The issue I'm finding with [the instructions](https://hub.docker.com/_/arangodb/) is you must run some `docker ...` commands, but don't see `docker` is installed on a  Flynn node, at least not accessible through that command.

Any guidance appreciated.

**Comment by lmars** [comment]
@OKNoah see [here](https://flynn.io/docs/docker) for instructions on deploying Docker containers to a Flynn cluster, you can run all the `docker` commands locally (or anywhere you have the Flynn CLI configured).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
