### ISSUE TITLE
Flynn ask me for credentials for git

### ISSUE THREAD

**Issue by buckle2000** [flynn/flynn#4337]
I installed flynn and followed the instructions [here](https://flynn.io/docs/basics).
When I typed in `git push flynn master` on my local machine, git ask me for "username and password".
Where can I get the username and the password?

**Comment by buckle2000** [comment]
```
C:\xxxxx>git push flynn master
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (9/9), 1.74 KiB | 5.74 MiB/s, done.
Total 9 (delta 0), reused 0 (delta 0)
fatal: protocol error: bad line length character: ?[1G
error: failed to push some refs to 'https://git.<domain>/donkeys-humiliate-bayham.git'
```

**Comment by philiplb** [comment]
You need to [add a cluster](https://flynn.io/docs/cli#adding-clusters) which will configure your local git.

**Comment by buckle2000** [comment]
I did that.
```
C:\path>flynn cluster
NAME     CONTROLLER URL                            GIT URL                            DOCKER URL
default  https://controller.<domain>  https://git.<domain> (none)  (default)
```

**Comment by thomasmodeneis** [comment]
I think the problem here is that you are trying to merge flynn branch with master.
You should configure your git origin/master to use SSH instead of HTTP, that will avoid the issue to happen.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
