### ISSUE TITLE
Running one-off commands with docker

### ISSUE THREAD

**Issue by theodorton** [flynn/flynn#4338]
I'm unable to use `flynn run` with a docker image. I'm getting:

```
exec: "/app/runner/init": stat /app/runner/init: no such file or directory
```

Am I missing some arguments, or is running commands with docker containers not supported?

**Comment by imjorge** [comment]
@theodorton what was the exact command you used?

**Comment by lmars** [comment]
`flynn run` is supported with apps deployed using Docker images, did you perhaps first deploy the app using `git push`? This may be a bug when switching between the two deployment strategies.

**Comment by theodorton** [comment]
@lmars Yes, I deployed it initially with `git push` then changed to docker.

@imjorge The exact command is `flynn run bundle exec rails c`

I could try to setup the app using docker initially to see if that resolves the issue. I'll report back.

**Comment by theodorton** [comment]
@lmars Seems like it works when I create a new app with docker deploy as the initial deploy.

I still think one should be able to switch deployment strategies without experiencing this bug. I'm somewhat hesitant to remove my old app in case I lose any resources I've provisioned.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
