### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by christiaangoossens** [flynn/flynn#4339]
Hi Flynn team,

It looks like Flynn only binds the router ports 80 and 443 to 0.0.0.0 on IPv4, and not on tcp6 (netstat). My host has a IPv6 address and correct firewall.

Should IPv6 be supported by Flynn?

**Comment by christiaangoossens** [comment]
This is for version `v20180216.dev3`.

**Comment by lmars** [comment]
@christiaangoossens the Flynn router does not currently listen on IPv6 addresses no, it wouldn't be too difficult to add but I don't believe anyone is currently working to add it.

**Comment by steffann** [comment]
Flynn looks really nice, but lack of IPv6 support makes it unusable for us :(
