### ISSUE TITLE
Custom ZFS pool

### ISSUE THREAD

**Issue by afgallo** [flynn/flynn#4343]
Hi there,

Firstly, I just wanted to say what a joy is to use Flynn. Thanks to all contributors for such great work!

I've been playing around with Flynn for some time now and wanted to set up a cluster with production best practices in mind. I was going through the production docs and more specifically https://flynn.io/docs/production#custom-zfs-pool. I ran the command

`sudo bash /tmp/install-flynn --channel nightly --zpool-create-device /dev/vda1 --zpool-create-options "-f"`

 and then got this issue:

`===> 23:38:18.093 running "zpool create -f flynn-default /dev/vda1"
cannot open '/dev/vda1': Device or resource busy
cannot create 'flynn-default': one or more vdevs refer to the same device, or one of
the devices is part of an active md or lvm device
===> 23:38:18.113 ERROR: failed to run "zpool create -f flynn-default /dev/vda1", exit status 1
`

I also tried running:

`sudo bash /tmp/install-flynn --channel nightly --zpool-create-device /dev/vda --zpool-create-options "-f"`

and then got:

`
===> 23:41:24.727 running "zpool create -f flynn-default /dev/vda"
the kernel failed to rescan the partition table: 16
cannot label 'vda': try using parted(8) and then provide a specific slice: -1
===> 23:41:25.193 ERROR: failed to run "zpool create -f flynn-default /dev/vda", exit status 1
`

I don't think there's anything wrong with Flynn, it's just probably my lack of understanding of zpool and Linux disk management in general :(

So my question to you guys is how can I leverage the 80GB disk space I get from a Digital Ocean host and set up the zpool correctly?

Many thanks!

**Comment by titanous** [comment]
Is `/dev/vda` the OS disk? If so, that won't work without repartitioning, as a ZFS pool requires a separate partition or separate disks if you are not using the sparse file.

**Comment by afgallo** [comment]
That's correct @titanous. I'll try and dig some doco on how to partition disks then. Thanks for your help.
