### ISSUE TITLE
Ubuntu 14.04 with Kernel 4.4.0-116-generic broken

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4344]
Hi,
I had to restore the cluster this morning again due to https://github.com/flynn/flynn/issues/3894 and https://github.com/flynn/flynn/issues/4144 .
One of the nodes was upgraded to 4.4.0-116-generic. The Flynn installer is not working with this version and fails with this message:

> ===> 08:46:55.961 running "modprobe zfs"
> modprobe: ERROR: could not insert 'zfs': Exec format error
> ===> 08:46:55.964 ERROR: failed to run "modprobe zfs", exit status 1

So I had to switch to the kernel 4.4.0-112-generic. With this version, Flynn runs fine.

Will this be fixed or is this the end of the support of Ubuntu 14.04?

**Comment by titanous** [comment]
It sounds like the ZFS module didn't get built for the kernel version you installed, usually this will fix it:

```
dpkg-reconfigure spl-dkms
dpkg-reconfigure zfs-dkms
```

We plan to deprecate 14.04 when we add support for 18.04 next month, so that we don't have to support three versions of Ubuntu.

**Comment by philiplb** [comment]
Ok, I understand.
Ubuntu 14.04 has support until April 2019 as of https://www.ubuntu.com/info/release-end-of-life . Shouldn't Flynn support it until it runs out of support?
I understand the reasoning behind stopping supporting 14.04, just a question.
Or maybe let the support for 18.04 mature a bit for a month or two and then drop 14.04? Because then I would skip 16.04 and go directly to 18.04 but I would like to know it stable. As far as I remember, Flynn had a few quirks on 16.04 in the beginning.

**Comment by titanous** [comment]
My impression is that 18.04 shouldn't require too many changes, so as long as the code paths are not too different, we may keep 14.04 around while we make sure 18.04 is stable.

**Comment by philiplb** [comment]
Great, thank you!
