### ISSUE TITLE
How to deploy microservices to Flynn?

### ISSUE THREAD

**Issue by roquie** [flynn/flynn#4345]
I would like to deploy my microservices without any authentication and use their in local network. It's possible with Flynn?

**Comment by philiplb** [comment]
I would guess, there is nothing special about them application wise, they should be deployable like any application. Then remove the default route and use Flynns discovery service to find out the internal URL. Could be something like <applicationname>.discoverd as URL. Not sure about the port.
You can find out a lot about your processes via flynn-host inspect on one of your nodes.

**Comment by roquie** [comment]
Thank. Ok, I'm attempt to try this variant. Until I do not close this issue.

**Comment by roquie** [comment]
Hmm. How I can to know first part of `.discoverd` URI? Appname, release name, release id or new added local route does not help me to use curl in neighbour container.

**Comment by kwando** [comment]
I _think_ the hostname is ```<app-name>-web.discoverd```

**Comment by imjorge** [comment]
@roquie please refer to https://flynn.io/docs/apps#service-discovery

> Flynn automatically registers each web process type in service discovery for internal requests that do not go through the router. The service discovery entries are available via DNS. The pattern `$APPNAME-$PROCTYPE.discoverd` is used for the DNS name, for example `myapp-web.discoverd` and `myapp-admin-web.discoverd`. This feature can be used to communicate internally between apps and processes.

**Comment by bbaptist** [comment]
I also discussed services on other ports registered with discoverd in this issue https://github.com/flynn/flynn/issues/4257

**Comment by roquie** [comment]
Yay! Thanks for your help! I'm found in the [flynn docs](https://flynn.io/docs/docker) example how send request.
```
flynn -a nodejs run curl http://nodejs-web.discoverd:8080
```

Here is need to be set container port, then it will be work.
