### ISSUE TITLE
Unable to pull private repository via composer during deploy

### ISSUE THREAD

**Issue by andrewbridge** [flynn/flynn#4348]
I've set up the demo environment and I'm trying to deploy a PHP application to it which includes a private github repository defined similar to:

```json
{
    "require": {
        "repo-author/repo-name": "0.1.0",
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "repo-author/repo-name",
                "version": "0.1.0",
                "type": "package",
                "source": {
                    "url": "git@github.com:repo-author/repo-name.git",
                    "type": "git",
                    "reference": "master"
                }
            }
        }
    ]
}
```

Prior to deploying, I set the `SSH_CLIENT_HOSTS` and `SSH_CLIENT_KEY` with:

```sh
flynn -a gitreceive env set SSH_CLIENT_HOSTS="$(cat ~/.ssh/known_hosts)"\
   SSH_CLIENT_KEY="$(cat ~/.ssh/id_rsa)"
```

And the key listed is definitely the one I use locally to work with the same repo.

However, when I push to flynn, after running the initial bootstrap steps, composer is run and eventually fails with

```sh
 - Installing repo-author/repo-name (0.1.0): Cloning master
       
       
       [RuntimeException]
       Failed to execute git clone --no-checkout 'git@github.com:repo-author/repo-name.git' '/tmp/build/app/vendor/repo-author/repo-name' && cd '/tmp/build/app/vendor/repo-author/repo-name' && git remote add composer 'git@github.com:repo-author/repo-name.git' && git fetch composer
```

I'm pretty sure I'm probably doing something wrong here, but as I can't find a great deal of additional advice elsewhere on the Internet, I thought I'd check myself: what is the suggested way of working with private dependencies when using flynn?

**Comment by andrewbridge** [comment]
Wow, that's an embarrassing oversight on my part...had entirely forgotten about it thanks to my `ssh-agent`. Thanks for the sanity check.

Is this the preferred way to handle this type of thing or would an access token type approach using HTTPS be a better solution than passing round private keys?

**Comment by lmars** [comment]
You should probably generate an SSH key just for this purpose and add it as a key in Github with just the permissions it needs (i.e. read-only permission to the repository it needs to pull).

**Comment by andrewbridge** [comment]
Yup, sounds sensible enough! Cheers, I'll close this!
