### ISSUE TITLE
Mysql (Errcode: 28 "No space left on device")

### ISSUE THREAD

**Issue by xanderu** [flynn/flynn#4349]
I get this error when i try to import a 250MB .sql file in to mysql DB
`ERROR 3 (HY000) at line 395935: Error writing file '/tmp/MLvBOGCz' (Errcode: 28 "No space left on device")`
I have tried to add more volumes (`flynn-host volume create`) but this problem persist.
Can you help ?

**Comment by philiplb** [comment]
Hi,
you can give it more disk space like this:
```bash
flynn -a mariadb deployment timeout 3600
flynn -a mariadb limit set web temp_disk=1G
# Now wait for the mariadb logs to settle, there will be some connection errors for a few minutes until the nodes are in sync again.
flynn -a mariadb limit set mariadb temp_disk=1G
```

**Comment by xanderu** [comment]
I get this message `sirenia cluster in singleton mode` . And the problem persist.

**Comment by xanderu** [comment]
I made a research and I think I need a `multi-node cluster` . How can I make a this ?

**Comment by philiplb** [comment]
https://flynn.io/docs/installation/manual

**Comment by xanderu** [comment]
Thank you!
