### ISSUE TITLE
Kubernetes Deployment support

### ISSUE THREAD

**Issue by sr229** [flynn/flynn#4351]
Related PaaS projects like Deis integrates on Kubernetes (sadly this is gonna be shut down as most of its members are now part of Azure Container Services), so it would benefit those who use k8s that wants to use Flynn as part of their existing Kubernetes Cluster

**Comment by AleksSem** [comment]
As far as i know Deis is built as on top layer of Kubernetes like a facade to simplify api and provide some ui.
Such integration for developers should be quite difficult because Flynn not using Kubernetes.
So Kubernetes and Flynn are PAAS but Deis is Facade over Kubernete.

**Comment by lmars** [comment]
Please see [this comment](https://github.com/flynn/flynn/issues/3330#issuecomment-242571876) which is still relevant to this question.

**Comment by evectis** [comment]
Per the CNCF, Flynn is a PaaS/Container Service Platform - https://landscape.cncf.io/grouping=organization&landscape=platform&organization=flynn&selected=flynn
Are there any current plans to provide native support for Kubernetes?
