### ISSUE TITLE
What is recommended way to work locally with flynn

### ISSUE THREAD

**Issue by pie6k** [flynn/flynn#4352]
I've go app with several microservices. I'd like to mirror 1:1 my infrastructure on production with my local machine (exluding database **data**). Also, I'd like to be able to iterate without re-deploying after every file-save.

My current workflow (without flynn) locally is:

1. I test my API
2. I see some bug
3. I fix bug in the code and save file
4. I CTRL+C, `node server.js` (re-start server)
5. I'm able to see bug fixed (or no, and being able to re-iterate in under 10 seconds)

A also need all services to be able to communicate with each other locally as they depend on each other. 

I've checked vagrant image, but it looks more like demo (even domain is set to `https://dashboard.demo.localflynn.com`) so I bet it's more like quick-demo than way to work locally with flyyn

**Comment by roquie** [comment]
Read this https://github.com/flynn/flynn/issues/4345

For local development you may use current variant, but, if you want true-microservices use Docker with Flynn. It help you to relocate your app to other solution or paas like Flynn. If it will be needed.

**Comment by thomasmodeneis** [comment]
I usually do not test flynn locally. Its not really needed.
The app should behave live the same as its locally, its a isolated Heroku style buildpack. So yes, there is no real need to run a local cluster for testing.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
