### ISSUE TITLE
Bind router requests to other docker container port

### ISSUE THREAD

**Issue by roquie** [flynn/flynn#4353]
Hi there!

I completely understand, what this PR https://github.com/flynn/flynn/pull/4000 give me instrument to bind any container port to use with flynn router?

Using this `-p` parameter or env variable I can to deal with it?

I'm use such container for which I can't change the port exposing. Therefore, I want to bind container port to router for proxying requests.

**Comment by roquie** [comment]
Oh, I got the following error: "validation_error: Port not reserved for HTTP traffic"
Like this
https://github.com/flynn/flynn/issues/4216

**Comment by roquie** [comment]
`flynn -a test-app env set ADDITIONAL_HTTP_PORTS=8090` also does not work for me.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
