### ISSUE TITLE
Ubuntu 16.04 with 4.4.121-mainline-rev1 broken

### ISSUE THREAD

**Issue by joeczucha** [flynn/flynn#4354]
I've just tried to install Flynn on a few Scaleway VPS servers running Ubuntu 16.04 and I'm getting the same error as #4344. Maybe it's a bug rather than a problem with the kernel version?

    ...
    ===> 00:27:14.760 loading zfs kernel module
    ===> 00:27:14.765 running "modprobe zfs"
    modprobe: FATAL: Module zfs not found in directory /lib/modules/4.4.121-mainline-rev1
    ===> 00:27:14.773 ERROR: failed to run "modprobe zfs", exit status 1

Linux flynn-02 4.4.121-mainline-rev1 #1 SMP Sun Mar 11 16:36:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Thanks for any advice - and all your awesome work on this project 🥇

**Comment by AleksSem** [comment]
Scaleway has custom linux kernel without zfs support. You should update kernel to default.

**Comment by joeczucha** [comment]
You're quite right, installing 4.13.0-37-generic sorted it. Thanks
