### ISSUE TITLE
Flynn product roadmap

### ISSUE THREAD

**Issue by artemave** [flynn/flynn#4356]
Hello,

Flynn is a fantastic product and lots of people love it. But it's development has gone quiet recently and those of us who care can't help but think "Oh no, what's going on? Is this it?"

I saw this [firefox product roadmap](https://wiki.mozilla.org/Firefox/Roadmap) the other day and it seemed like perhaps flynn could do with one too. Just so we know what's going on. And what's going to happen.

This isn't just curiosity. Products like flynn need people to believe in it.

Thanks!

**Comment by philiplb** [comment]
There are labels on the issues: "roadmap/upcoming" (next on table) "roadmap/current" (right after "roadmap/upcoming"). I think they are stalled as the development of new bigger features is a bit frozen.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
