### ISSUE TITLE
"flynn pg restore" and "flynn import" does not restore all my schemas, only "public"

### ISSUE THREAD

**Issue by linpau** [flynn/flynn#4357]
Hi,

I have pg database with many schemas. When i run "flynn pg restore" and "flynn import", only the "public" schema is restored.
I managed to restore the other schemas by provision a route to postgres and run pg_restore (not flynn), but this was time consuming.

I would like to be able to restore all schemas and to choose which one to restore with the "flynn pg restore"-command.
I also would like "flynn import" to restore all schemas

I found the following lines interesting and i think it's the -n flag that we have to work with.
1. 
[flynn/cli/pg.go L191](https://github.com/flynn/flynn/blob/f4c030045c7dd1b58061df69acf52d6b9599b13f/cli/pg.go#L191)
> fmt.Sprintf("set -o pipefail; cat > /data/temp.dump && pg_restore -d %s -n public --clean --if-exists --no-owner --no-acl --jobs %d /data/temp.dump", config.Env["PGDATABASE"], jobs),

2. 
[[flynn/cli/pg.go L194]](https://github.com/flynn/flynn/blob/f4c030045c7dd1b58061df69acf52d6b9599b13f/cli/pg.go#L194)
> config.Args = []string{"pg_restore", "-d", config.Env["PGDATABASE"], "-n", "public", "--clean", "--if-exists", "--no-owner", "--no-acl"}

I'm new to all of this so all help and feedback is welcome :)

**Comment by oleg-kiviljov** [comment]
is there any update on this? Feels like its an important feature to have. Why only public schema is imported anyway if full backup is taken?

**Comment by linpau** [comment]
I can't see any changes in the code. Still "-n public".

I wish to be able to select which schema to restore and to get all schemas restored as default.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
