### ISSUE TITLE
Some way to clear deploy logs?

### ISSUE THREAD

**Issue by schu34** [flynn/flynn#4358]
I'm building an app which is going to be deployed to a flynn cluster run by my company, the cluster has been up for an few months now, and it seems to be preforming great, the only problem i've run into is that each time I deploy the app (usually at least once per day, sometimes far more) the log screen in the dashboard gets slower. at this point, it's pretty much unusable. it takes about a minute to load at all and once it does, I can't scroll down the list of deploys to the left. When I select a deploy from the list it hangs for a couple minutes before it even highlights the deploy, at which point it hangs indefinitely, and never seems to load the actual logs. I think this issue is brought up in #2254 but it doesn't seem like it's a priority for you guys. In the mean time I'm wondering if theres some way I can just clear the list so that it'll be fast enough to be useful again.

**Comment by thomasmodeneis** [comment]
What you can do is perform a GC `flynn-host volume gc` and also scale up the logaggregator.

**Comment by schu34** [comment]
Thanks for the response. If you don't mind, what exactly does the `gc` command do? I have apps in production running on my cluster so I don't like just blindly running commands

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
