### ISSUE TITLE
Log sink stops pushing data to LogDNA

### ISSUE THREAD

**Issue by airways** [flynn/flynn#4359]
We have a log sink setup to push our logs to LogDNA. This log sink stops working without warning and has to be manually deleted and re-added, using the exact same settings as LogDNA provides for Flynn in their popup for adding log sources.

I am not sure how long the sink keeps working, as we only notice that this is a problem when the cluster starts becoming unstable as chronicled in #4317.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
