### ISSUE TITLE
Missing PGPORT env var

### ISSUE THREAD

**Issue by dschnare** [flynn/flynn#4360]
After adding a `postgres` resource our app was expecting `PGPORT` to be an available environment port. This however wasn't the case. Can you add `PGPORT` to the exported environment variables?

**Comment by titanous** [comment]
I'm not aware of any standard software that requires PGPORT when it is the default of 5432, like it is on Flynn. Can you just set it for your app?

**Comment by dschnare** [comment]
It's likely a very rarely used env var, but flynn does provide all the env vars necessary to reconstruct the `DATABASE_URL` except the port. Is it reasonable to always have apps hard code the postgres port?

I'm inclined to suggest to not have apps hard code the postgres port since all the other env vars necessary to construct a new `DATABASE_URL` are being exported except `PGPORT`. This is coming from more of an app developer point of view though.

It looks like Heroku doesn't export anything but `DATABASE_URL` (I could be wrong), so an app doesn't have the option. Flynn gives you the option to use `DATABASE_URL` or to rely on standard postgres env vars.

**Comment by titanous** [comment]
I'm not saying to hardcode it, just default to 5432 (the PostgreSQL port registered with IANA) if `PGPORT` isn't set. If you don't specify a port, that's what libpq (the official client) and most other clients I've seen use.

**Comment by dschnare** [comment]
Yeah good point. If not specified then assume the port is 5432. I hadn't realized that this port was a full-on standard.
