### ISSUE TITLE
Got "Service unavailable" when stress test my app

### ISSUE THREAD

**Issue by Elvis5566** [flynn/flynn#4361]
Hi Guys,

I am developing an app on flynn with play framework 2.6(AKKA http)/ ubuntu 16.04/ aws ec2(t2.medium)
and try to figure out how many connections a single ec2 instance can hold.

I used wrk to stress test the app with only 2k connections
`wrk -t4 -c2000 -d30s -T120s --latency http://staging.app.mydomain.com`
The web shows nothing but "Service unavailable" while this command running.

and with [Gatling](https://gatling.io/), I can only keep about 4000 websocket connections.

I've tweaked kernel config with
```
net.core.somaxconn = 10000
net.core.netdev_max_backlog = 20000
net.ipv4.tcp_max_syn_backlog = 20000
net.ipv4.tcp_mem = 65536 131072 262144
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
```
but still doesn't work...
There is no error log for my app.
But with 
`flynn -a router log -n 100`
I saw "retriable dial error" and "request failed" like this
```
2018-04-02T07:08:40.635487Z app[app.ip-f0f4d254-ff7a-4b8a-a14d-36f29978dfcd]: t=2018-04-02T07:08:40+0000 lvl=eror msg="retriable dial error" app=router request_id=6232ac03-2955-42e2-80c8-c88f7b6b25a2 client_addr=34.212.166.179:50732 host=staging.app.mydomain.com path=/ method=GET backend=100.100.99.46:8080 err="dial tcp 100.100.99.46:8080: i/o timeout" attempt=0
2018-04-02T07:08:40.635755Z app[app.ip-f0f4d254-ff7a-4b8a-a14d-36f29978dfcd]: t=2018-04-02T07:08:40+0000 lvl=eror msg="request failed" app=router request_id=6232ac03-2955-42e2-80c8-c88f7b6b25a2 client_addr=34.212.166.179:50732 host=staging.app.mydomain.com path=/ method=GET status=503 num_backends=1
```

with
`flynn -a staging limit`
I got 
```
slugbuilder:  cpu=1000  max_fd=10000  memory=4GB  temp_disk=100MB
web:          cpu=1000  max_fd=20000  memory=4GB  temp_disk=100MB
```
It's not possible my app can only hold such few connections.
The memory is sufficient. (there are still 1.6g available)
And it's not because JVM run out of memory (I did not see outOfMemory exception)
I have two app on the same host.
When the test one is unavailable, the other one still works.
So I wonder if there is something I need to config on flynn to fix this issue.

Any help would be much appreciated.
Thank you!

**Comment by thomasmodeneis** [comment]
You could try to scale up the router and also add more instances, you have one instance and you are hitting it with 4k simultaneous users. 
This test does not mean much, its not a problem on Flynn. You would rather scale up the app and reduce the stress test to something like 50 users per sec. On the normal world, you should setup a LB and a CDN in front of your Flynn.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
