### ISSUE TITLE
How to bind Flynn to eth0:1 IP address only?

### ISSUE THREAD

**Issue by denisvmedia** [flynn/flynn#4362]
I use Linode platform to host my services. And I want to have the cluster run on the Private Network. Linode puts the private network IP to the `eth0:1` interface alias. According to what I found (particularly #2190), I tried to use `--external-ip` but failed. What I tried:
1. I tried to run `flynn-host init --external-ip=192.168.x.y`
2. I tried to modify /lib/systemd/system/flynn-host.service `ExecStart=/usr/local/bin/flynn-host daemon --external-ip=192.168.x.y`
(if I do both at once, this will lead to the problem described here: #4077, and I believe that's what the author of the issue had)
3. I tried `--listen-ip=192.168.x.y` (in combination with `--external-ip` and without this combination)

But no luck. According to the logs, there is some problem with discoverd, either it doesn't start or starts but on the eth0 ip (which is a public IP).

Now I have no idea what else to do... My main aim is to avoid exposing any flynn information outside (I want to have no flynn services available from the Internet). And also I will use haproxy or nginx to forward requests to the services that I started inside. Is this really doable (at least without using an intermediate VM to host Flynn)?

**Comment by thomasmodeneis** [comment]
Hmm, the init command also requires you to set the token. 
I see your call does not include the token, are you sure that you can do this without the token ?

**Comment by denisvmedia** [comment]
@thomasmodeneis The problem is not related to the token. Actually being not able to solve that problem forced me to move to Kubernetes :D

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
