### ISSUE TITLE
Kernel OOM killer tracking

### ISSUE THREAD

**Issue by tianx2** [flynn/flynn#4365]
If I get a message in the system logs from kernel like this:
```text
Task in /flynn/user/ip1012012361-15a49519-f867-4139-9a7a-b567a4179d20 killed as a result of limit of /flynn/user/ip1012012361-15a49519-f867-4139-9a7a-b567a4179d20
```

How do I track that back to the offending application/process?

**Comment by titanous** [comment]
`ip1012012361-15a49519-f867-4139-9a7a-b567a4179d20` is the job ID, so `flynn-host inspect ip1012012361-15a49519-f867-4139-9a7a-b567a4179d20` will give you all the details.
