### ISSUE TITLE
Cert update questions

### ISSUE THREAD

**Issue by rlangfordBV** [flynn/flynn#4370]
Hello,

Last week, I updated our TLS certs on some of our Flynn clusters using the following (names and paths changed to protect the guilty)

```
for rid in $(flynn -c $MY_ENDPOINT -a controller route | awk '{ print $3 }' | grep -vw ID); do \
 flynn -c $MY_ENDPOINT -a controller route update "$rid" -s controller \
 --tls-cert ~/.myflynn/keys/$MY_ENDPOINT/controller_tls_cert \
 --tls-key ~/.myflynn/keys/$MY_ENDPOINT/controller_tls_key ; \
done
```

And now I'm receiving cert warnings when trying to push a docker app:
```
error running `docker login`: exit status 1 - output: {"WARNING! Using --password via the CLI is insecure. Use --password-stdin.\nError response from daemon: Get https://docker.url.of.my.flynn.cluster/v2/: x509: certificate has expired or is not yet valid\n" <redacted repetition of '\x00' strings"}
```

What is the correct process to follow to update the cert for other applications?  What applications need to be updated? I can surmise that `docker-receive` is one, but are there others?  Do I need to update ALL the applications?  Is there any tooling to facilitate this process?

**Comment by lmars** [comment]
The process looks fine, you should also update the routes for `gitreceive`, `docker-receive` and `dashboard` apps in the same way if you want them to use CA issued certificates rather than the default self-signed certificates.

Work is under way to integrate Let's Encrypt, which will remove the need to do this in the future.

**Comment by rlangfordBV** [comment]
Thanks, @lmars!  I found a blog post mentioning those applications, and I was able to update them yesterday!
