### ISSUE TITLE
Sensitive data & Services

### ISSUE THREAD

**Issue by afgallo** [flynn/flynn#4378]
The security docs, more specifically https://flynn.io/docs/security#applications notes

> There may be other unknown security flaws in Flynn. For the time being we do not recommend running Flynn in environments where there is access to sensitive data or services.

I think this might be the only reason that is stopping me from deploying my cluster into production.
I love Flynn and would very much like to use in prod! I would really appreciate if you guys could share with us the plan you might have to address this issue in particular.

Many thanks!

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
