### ISSUE TITLE
 getsockopt: connection refused After an Hard Reboot

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4380]
Hello,

Flynn seems to be very unstable, I rebooted my servers ( Scaleway ) , logged in, restarted flynn-host in all my nodes and now from my flynn cli I cannot do anything.

Keep getting these sorts of errors:
 getsockopt: connection refused

or 

flynn docker login
error running `docker login`: exit status 1 - output: {"WARNING! Using --password via the CLI is insecure. Use --password-stdin.\nError response from daemon: Get http://docker.........../v2/: EOF\n" '\x00' '\x00' "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"}

Do you have any idea of how to fix this?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
