### ISSUE TITLE
Redis version

### ISSUE THREAD

**Issue by AlexMeah** [flynn/flynn#4384]
The current Redis version (3.0?) is missing the [GEO functions](https://redis.io/commands/geoadd) added in 3.2 and is also a full major behind latest stable 4.0.9.

Are there any plan to update it?

**Comment by thomasmodeneis** [comment]
Hi @AlexMeah 
I don't know, actually I've been avoiding to use Redis inside Flynn. Its not persistent storage and is also causes my cluster to behave a bit worse due to high memory usage. 
I prefer to have my redis outside with master/slave/sentinel because is much more reliable.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
