### ISSUE TITLE
Time-based log retention?

### ISSUE THREAD

**Issue by Tyler-Murphy** [flynn/flynn#4389]
Is it possible to control log retention time?

Does adding a log sink affect how logs are handled on each host?

**Comment by thomasmodeneis** [comment]
The only way I know to cleanup space is by running: `flynn-host volume gc`
I'm not sure if this will cleanup the logs, anyone ?

**Comment by philiplb** [comment]
I think this won't help with the logs.
See https://github.com/flynn/flynn/blob/master/host/cli/volume.go#L58-L123
There seems to be situations, where ZFS volumes are not attached to any process. They are just garbarge. This tool collects the used volumes and compares this list with the actual existing volumes. It then deletes every unused existing volume.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
