### ISSUE TITLE
Stuck deployment via `git push` cancel led to an extra instance using old version

### ISSUE THREAD

**Issue by FreeLineTM** [flynn/flynn#4390]
I deployed a new version of my app and the push went stuck when releasing and I Ctrl + C-ed it. I then pushed again, a push which was successful but I now had one updated job of my app running and one of the old version. Killing the old one results in it being restarted, and scaling up and down from 1 (what I want) to anything simply ignores the extra job like it doesn't exist (scaling to 0 results in the instance I want to kill still running).

What should I do in this situation? I've already rebooted the machine several times and ran `flynn-host fix`.

**Comment by FreeLineTM** [comment]
I realised Flynn was not updated, so I ran `flynn-host update` which killed the old instance and it was *not* restarted. Should the issue be closed or is it still relevant as it might be a problem if there are no updates? Not sure what happened during the update process fixed it.

**Comment by lmars** [comment]
@FreeLineTM to scale down an old release, first get the release ID from:

```
$ flynn scale --all
```

then scale it down with:

```
$ flynn scale -r <release-id> web=0
```
