### ISSUE TITLE
Incorrect URL printed from Flynn's git push

### ISSUE THREAD

**Issue by wkoszek** [flynn/flynn#4391]
I'm trying Flynn in Vagrant box. When you push an app to Flynn, it shows incorrect URL:

```
=====> Application deployed
To https://git.demo.localflynn.com/app3.git
* [new branch]      master -> master
This part shows a wrong URL.
```

I think it should show the URL that is accessible. The URL should be like this:

```
$ flynn route
ROUTE                          SERVICE   ID                                         STICKY  LEADER  PATH
http:app3.demo.localflynn.com  app3-web  http/7f45e7c8-a303-4bd8-af3b-34fac0462f20  false   false   /
```

**Comment by thomasmodeneis** [comment]
hi @wkoszek , that is correct actually.
Its telling you that the git branch flynn is not updated with master. Thats how Flynn works.
The deployment does not tell you what URL the app is available, as you have the option to create many routes for a single app.

**Comment by wkoszek** [comment]
Hi @thomasmodeneis 

I'm sure it's technically correct, but not very usable. First thing after deployment is to try to access the service to see if it works OK. I can't do that now with Flynn. I'd be OK with `flynn` automatically printing out the `flynn route` output at the end.

My $0.02 of usability feedback.

**Comment by wkoszek** [comment]
Pressed 'Close' instead of 'Comment'

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
