### ISSUE TITLE
Ubuntu 18.04 Support

### ISSUE THREAD

**Issue by AienTech** [flynn/flynn#4392]
Hi everyone,
I already asked this question in flynn irc channel. Just wantet to know if there are any plans to support ubuntu 18.04?

regards

**Comment by philiplb** [comment]
Do the current nightlies work on 18.04? :-)

**Comment by lmars** [comment]
Whilst we haven't done any testing, I see no reason why Flynn wouldn't work on 18.04.

You can give it a try by just editing the version check in the install script (i.e. add an ` || is_ubuntu_bionic` everywhere you see [`is_ubuntu_trusty`](https://github.com/flynn/flynn/blob/master/script/install-flynn.tmpl#L232), or just pretend trusty is bionic and change `16.04` to `18.04` for testing purposes).

**Comment by philiplb** [comment]
I'm trying to setup a 3-node-cluster with this and also tried a single host one. But bootstrapping always fails with

> 16:03:33.627160 run-app discoverd
> 16:04:03.689925 run-app discoverd error: bootstrap: timed out waiting for job event

Any idea what I could do here?

Here are the logs of one of the hosts:

> t=2018-08-31T15:43:13+0000 lvl=info msg="starting daemon" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="validating host ID" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="detecting external IP" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="using external IP 172.31.24.8" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="registering with cluster discovery service" app=host pid=4369 fn=runDaemon host.id=ip17231248 token=https://discovery.flynn.io/clusters/798e90a6-2c25-49ff-90b1-a2cdefef5de1 addr=172.31.24.8:1113 name=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="registered with cluster discovery service" app=host pid=4369 fn=runDaemon host.id=ip17231248 id=5788ea15-147d-4790-9197-89eb1e9730f7
> t=2018-08-31T15:43:13+0000 lvl=info msg="initializing volume manager" app=host pid=4369 fn=runDaemon host.id=ip17231248 provider=zfs
> t=2018-08-31T15:43:13+0000 lvl=info msg="initializing job backend" app=host pid=4369 fn=runDaemon host.id=ip17231248 type=libcontainer
> t=2018-08-31T15:43:13+0000 lvl=info msg="setting host status PID" app=host pid=4369 fn=runDaemon host.id=ip17231248 pid=4369
> t=2018-08-31T15:43:13+0000 lvl=info msg="creating HTTP listener" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="opening state databases" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="starting sink persistence routine" app=host pid=4369 host.id=ip17231248 component=sinkManager fn=persistSinks
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/data" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/ext2" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/00b6f64ee3de6906df781fc9c7fdc87121295f08c6dac2bc80124a663bf8e046" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/01b9b169f4e8480624ce1f8b7584ae8a231a91fb44cf8fd63b7c5e12f778cd24" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/05c52bffd84649fbb3903a3c441aa28024cbd7bc5f930a8498f95ff65188256f" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/11b172c646f465690733669900a0c272bc3e55a872fea4837c768df9ab7ea135" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/1ffd099f03255709f061dde7688dfe0598387795b38babb37ab86030eaa46d9e" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/31c1b3064fdb60ff2e55b85a1ab5e6879df5e63e638d553aef5d806a9d08d8a4" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/34208476c7528e0cf50c7f512e022178ee75928c6f680cd2e9bc2bdb3ba13a86" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/3c3d8039d02a9d47dd2ee1c85b37360b321ea197273dd4dc873b9c5e005d096f" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/435a73367f3ab76d3cf14b46a7a297d850c19f53e27049a0933aef77caa31bae" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/49bf8bafc185f0acf801a72e01f0f864b888e91bd2fcf6139806460548203cc4" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/4e9f13fc7cc37af43ac8274d300251248a6404b5e3f9db8b87c8850a80a0f653" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/4fbfccf56731bcf2d5d4c39c08f4d0bf6e0d3bdc5118075251411ea6486bbdea" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/5031c3ca95b4d3d2d8f8a869ab43ddd7d72035d36ff36b40e2dab0fe2d923427" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/6483b4c91fb482e265e6c0358adf81e6bf27aecb8aa7edfb5a809bf5db7a647f" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/6751c9987330b80198a532d6643b27568f61d90ea29d39aa3ba21ff6e82e6c6c" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/6d1c73b6767a44587362d2083c43e038589652bfaa22d861a367c47d8b9ac287" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/6dc530a0d72a16d92ebf587ac63d7ea243bcb0c351b100d485069586e52c145a" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/73cfd2ac3ea15e6d2385869a278b2aa85754590439d9c326428aa83e8db7ca60" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/77bb5ee8509cd4928fe315df70483690500d89bf6c99af3c8daf5a86896e7a78" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/7b4d6c66fbc48bf578ce14d1beb6c1d83e4d81bd6bb2fc706d110c103ef96746" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/84963f0c72b38adc96dd1bca37bde57138af2621d2a0cc3cfcbc745c68763f7b" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/8de3f6ac3d29b70d0054a5a35f26d902a7ecaed460a96eb2637d9906887d1f86" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/90db2bc2e84c2e04a72f1165e190b22b7cc9c5d67e49c888d8f7dda7c26f4c1a" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/b2d311f3f7148c12bf0567e2805938936c972425ff9de72283aa5e13a10e60bf" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/b31f754603eed9715aed85b2e589d68432a005d212e3b976f713d2fecba9f4eb" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/c3895dada3af0558f3320689471476c6451a265dd55235c9eb4634cf6f62e31d" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/cbb805c7031bf97ecd955220c617d4e9c4a8036fbfe24e2cb186f28704f786cc" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/cd5fec716e8e543c688fa930d95cbec40b2dbfd1300b37655e72c41d52ab20f8" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/e0217a5609bc35ab018d4e613ab4fd3bfe4917261fd3143afeec33e7f8e9162a" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/e2d00e523b3d934cf233198bfc781ec0a8d3e626daf52c05b4d0faf909a9567a" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/ea7426975406f7355486cc3af07c5899d722fbee717d223edb385f309c112a07" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/f404f624c737b5020e95a5feba71d6535f7923bc4b0bda2bfaef0e79cc806062" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/fb4fd2a7d1f63aa01470d4abda77e8b7061f3f5744bd075d7d99c9cf41be21fe" package=zfs
> t=2018-08-31T15:43:13+0000 lvl=info msg="restoring state" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="no stored global backend config" app=host pid=4369 host.id=ip17231248 component=backend backend=libcontainer fn=UnmarshalState
> t=2018-08-31T15:43:13+0000 lvl=info msg="serving HTTP requests" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:13+0000 lvl=info msg="getting cluster peer IPs" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:43:14+0000 lvl=info msg="got cluster peer IPs" app=host pid=4369 fn=runDaemon host.id=ip17231248 peers=[172.31.18.66]
> t=2018-08-31T15:43:14+0000 lvl=info msg="connecting to cluster peers" app=host pid=4369 fn=runDaemon host.id=ip17231248 ips=[172.31.18.66]
> t=2018-08-31T15:44:15+0000 lvl=info msg="no cluster peers available" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:44:15+0000 lvl=info msg="resurrecting jobs" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:44:15+0000 lvl=info msg="blocking main goroutine" app=host pid=4369 fn=runDaemon host.id=ip17231248
> t=2018-08-31T15:44:15+0000 lvl=info msg="waiting for discoverd" component=cluster-monitor fn=Run
> t=2018-08-31T15:56:07+0000 lvl=info msg="request started" req_id=4a919a05-0a49-4b86-9416-c5e541e54d60 component=host method=GET path=/ client_ip=172.31.24.8
> t=2018-08-31T15:56:07+0000 lvl=info msg="request completed" req_id=4a919a05-0a49-4b86-9416-c5e541e54d60 component=host status=404 duration=97.907µs
> t=2018-08-31T16:03:33+0000 lvl=info msg="request started" component=host req_id=6fd5745e-6658-4077-8ec0-57833045fda8 method=GET path=/host/status client_ip=172.31.18.66
> t=2018-08-31T16:03:33+0000 lvl=info msg="request completed" component=host req_id=6fd5745e-6658-4077-8ec0-57833045fda8 status=200 duration=163.986µs
> t=2018-08-31T16:03:33+0000 lvl=info msg="request started" component=host req_id=6f855cb6-9e88-400d-a36a-26129885f025 method=POST path=/host/resource-check client_ip=172.31.18.66
> t=2018-08-31T16:03:33+0000 lvl=info msg="request completed" component=host req_id=6f855cb6-9e88-400d-a36a-26129885f025 status=200 duration=157.609µs

**Comment by philiplb** [comment]
Hi, anything I could do here and how?

**Comment by lmars** [comment]
@philiplb sorry for the slow response, so I think this is an issue with ZFS and the latest 4.15 Linux kernel, I haven't yet tracked down the issue but for now I have been downgrading to 4.13 which seems to work just fine.

**Comment by philiplb** [comment]
@lmars Did you have any chance to track this issue down?

**Comment by Padrio** [comment]
So, still no progress on this?

**Comment by Padrio** [comment]
Wheew, something is happening. Nice!

**Comment by raphaelpflieger** [comment]
Currently having the same discoverd error and log file as @philiplb on a bare Ubuntu 18.04 instance. I had a look at #4532 but it's not quite clear on how to implement the workaround :/ Anyone here had more success on this ?

**Comment by fastengineer** [comment]
@raphaelpflieger I have the same fail at this night.
```

03:06:42.431512 check online-hosts
03:06:42.800059 require-env require-env
03:06:42.800186 resource-check resource-check
03:06:42.802553 run-app discoverd
03:07:12.905448 run-app discoverd error: bootstrap: timed out waiting for job event

```

**Comment by raphaelpflieger** [comment]
@fastengineer unfortunately nothing changed on this issue on our side as well, the only way to get Flynn to deploy the cluster was to continue using Ubuntu 16 :/ When our cloud provider will stop providing it on its instances we will basically be screwed with our production app, we're all quite stressed about this... It looks like this project is dead, too bad because it was really filling a niche between Dokku/CapRover and Kubernetes
