### ISSUE TITLE
Can't access Rack server on additional port

### ISSUE THREAD

**Issue by ngrichyj4** [flynn/flynn#4393]
I'm running a rack server (middleware) along side my Rails app. The rack server listens on an additional port 0.0.0.0:4242 while the Rails app is accessible on port 80 & 443. The rails app can't seem to send requests to the rack server on port ::4242 via domain.com:4242/. I've added the 4242 port to the ADDITIONAL_HTTP_PORTS env and also added an additional route using: 'flynn route add http -p 4242 domain.com' but it's still not working. Is there a way to get this working.

Thanks.

**Comment by ngrichyj4** [comment]
Nevermind, I found what I was looking for here: https://flynn.io/docs/apps#additional-process-types

**Comment by thomasmodeneis** [comment]
Hi,
Yes, deploying the service with other than web should allow you to have it binding on the port.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
