### ISSUE TITLE
Controller API sample tutorial

### ISSUE THREAD

**Issue by sirakoff** [flynn/flynn#4394]
Can someone please show me how to deploy an app using the controller api only? Thanks in advance!

**Comment by dereke** [comment]
I'm not aware of any tutorials but there is some code in pr-apps that uses the controller to create apps.

https://github.com/featurist/flynn-pr-apps/blob/master/lib/flynnService.js

**Comment by sirakoff** [comment]
Thanks!, but is there a way to deploy using tarball or using git without the flynn cli?

**Comment by sirakoff** [comment]
Ok, i finally got it. The username for git is user and the password is the controller key. But you'd have to add the ca-cert in `~/.gitconfig`

`[http "clusterDomain"]`
`sslCAInfo = path/to/cert.pem`

So git url becomes:
`https://user:controllerAuthKey@git.clusterDomain/appName.git`

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
