### ISSUE TITLE
adding new host. clarify process.

### ISSUE THREAD

**Issue by martunta** [flynn/flynn#4396]
I have issue with one of the hosts not working as expected (application instances launched there are not accessible). After a long time trying to fix it, I decided to replace the host with another one, who would have fresh install.

However, after following instructions in documentation, I could not get new host to register.
What I did was:
1) create new server
2) install flynn (with the same version (1709) as other nodes.
3) run 'flynn-host init --init-discovery' in one of the existing, good, nodes
4) run 'flynn-host init --discover $url' on the new node

and nothing happens. new node does not appear in the 'flynn-host list'
what am I doing wrong?

**Comment by martunta** [comment]
any ideas how to do this? one of the tree hosts is never responding to any requests, and there seems to be no way how to replace it :/ 
I have to keep manually rescaling app to kill processes from this node and replace them with other :/

**Comment by bbaptist** [comment]
[Adding hosts](https://flynn.io/docs/production#adding-hosts) and [Replacing hosts](https://flynn.io/docs/production#replacing-hosts)

Basically just init a new host, demote the failing host, add the new host as a consensus member.

**Comment by martunta** [comment]
as you can see in my comment below - this is what I did, and nothing happened. Can you please explain what I did wrong?

**Comment by bbaptist** [comment]
You don't init a new discovery, you use the current cluster discovery token. It can be found in an existing host's `/etc/flynn/host.json`.

**Comment by bbaptist** [comment]
So in concise steps:

1. Install same version of Flynn
1. On new host run `flynn-host init --discovery https://discovery.flynn.io/clusters/${discovery_token}`
1. Restart `flynn-host`
1. New host has joined the cluster.

**Comment by martunta** [comment]
ok, my new host joined! I now see it in the `flynn-host list`

demoting and promoting is not going to smoothly. when doing promote new host I get `05:51:46.870693 host.go:166: unknown_error: Something went wrong` so obviously I am still doing something wrong :)

**Comment by martunta** [comment]
ok, turns out it needs ip with a port not hostname. now promoted. 

but when I went to change discoverd env then all hell broke loose. Now discoverd is down completely after timeout and there is no way of reviving it. `fix` with --min-hosts-3 and peer-ips finds everything, but then times out after waiting for web contorller to start. 

Now this is scary, cluster is uncontrollable :/

**Comment by martunta** [comment]
and nothing int he flynn-host.log either. How can system fail with error messages and produce no logs :(

**Comment by martunta** [comment]
ok, restarting flynn-host services on each node made 'flynn-host list' to work again ... but all the apps are down now.

**Comment by martunta** [comment]
ok, after bricking all the flynn installation for second time I have ended my around two year journey in using it in production. halas. Days worth of work and I have rebuilt everything using docker swarm and traefik.

**Comment by alexanderadam** [comment]
@martunta do you have your setup (traefik + flynn) documented somewhere?

**Comment by martunta** [comment]
not really. sorry.
