### ISSUE TITLE
how to change blobstore to default?

### ISSUE THREAD

**Issue by hadifarnoud** [flynn/flynn#4398]
my S3 bucket was deleted so I want to change blobstore back to local. losing the S3 bucket will break Flynn.

there are [docs](https://flynn.io/docs/production#blobstore-backend) on how to migrate to S3, GC, or Azure but there is no doc to do the reverse.

at the moment, pushing to flynn returns 500 error.

**Comment by hadifarnoud** [comment]
tried changing env on blobstore back to `postgres`. it didn't help

**Comment by hadifarnoud** [comment]
@titanous @lmars can you please help? We are in a bad position.

**Comment by thomasmodeneis** [comment]
Hi @hadifarnoud 

Basically you need to restore the blobstore configs back to your postgres:
```
flynn -a blobstore env
DATABASE_URL=postgres://12345:4324234@leader.postgres.discoverd:5432/4aafef0bda8f1866f4a9f2b428ffde4e
FLYNN_POSTGRES=postgres
PGDATABASE=db123
PGHOST=leader.postgres.discoverd
PGPASSWORD=qwe321
PGUSER=user123
```

You can get the info for the postgress on the dashboard by clicking on the postgres that is associated to the blobstore.

**Comment by hadifarnoud** [comment]
I wish it was that easy @thomasmodeneis 
I still get these errors when pushing to git
```
t=2018-06-17T16:42:35+0000 lvl=info msg="request started" component=blobstore req_id=51b50a08-b053-4408-9167-b3530b529372 method=GET path=/repos/19b8dfea-efc6-456e-a6d4-b09910fff298.tar client_ip=100.100.50.11
2018/06/17 16:42:35 error: blobstore: unknown backend "s3main"
t=2018-06-17T16:42:35+0000 lvl=info msg="request completed" component=blobstore req_id=51b50a08-b053-4408-9167-b3530b529372 status=500 duration=11.070751ms
```

**Comment by hadifarnoud** [comment]
doing `flynn -a blobstore run /bin/flynn-blobstore cleanup` does not appear to help
```
2018/06/17 16:55:24 [2687/2692] Skipping /27bf8e34-1cce-4799-902c-c3863922c13c-cache.tgz (53d9fca6-1c46-40a7-8ac3-29f284970e2a) because backend is not configured
2018/06/17 16:55:24 [2688/2692] Skipping /repos/27bf8e34-1cce-4799-902c-c3863922c13c.tar (797c95ac-0180-44cf-82c5-47a821c9ce20) because backend is not configured
2018/06/17 16:55:24 [2689/2692] Skipping /4b3c987a-2f73-4bc1-9795-a68c61b0a92a-cache.tgz (d5fa46a8-14e5-49dd-972e-cc59a5364e20) because backend is not configured
2018/06/17 16:55:24 [2690/2692] Skipping /repos/4b3c987a-2f73-4bc1-9795-a68c61b0a92a.tar (8a79c1eb-fb4e-4911-b704-99811af8fc4d) because backend is not configured
2018/06/17 16:55:24 [2691/2692] Skipping /4b3c987a-2f73-4bc1-9795-a68c61b0a92a-cache.tgz (221f4e11-2090-4675-b867-37ddc65d54e3) because backend is not configured
2018/06/17 16:55:24 [2692/2692] Skipping /repos/4b3c987a-2f73-4bc1-9795-a68c61b0a92a.tar (969ac9fc-da7e-49ab-8af4-b999e9f7a544) because backend is not configured
2018/06/17 16:55:24 Done
```

**Comment by hadifarnoud** [comment]
the worst thing is, I can't even restore from backup as the s3 bucket is not there anymore.

**Comment by josephglanville** [comment]
Unfortunately if you don't have a backup of the contents of the s3 bucket you are in trouble.

Flynn relies on the blobstore for it's own internals not just your apps.

The only way to recover is to use an old backup to restore the cluster to an earlier date.

Before doing that make sure you export your postgres databases manually pg_dump as you won't be able to use the normal export process with a broken/missing blobstore.

**Comment by hadifarnoud** [comment]
but it's working just fine as it is. all my backups are done when I had S3 setup. does those backups work? if not, I should just back up database of each app. We have many routes on more than 20 apps. is there a way to back up the routes only from flynn postgres?
