### ISSUE TITLE
http: unexpected EOF reading trailer

### ISSUE THREAD

**Issue by joeczucha** [flynn/flynn#4399]
My laptop battery died during a deployment and that somehow managed to kill my whole 3-node cluster.

I stopped flynn-host on each of the nodes, then restarted them and ran `flynn-host fix --min-hosts 3` on the main host. I get the following:

    # flynn-host fix --min-hosts 3
    INFO[06-08|13:48:09] found expected hosts                     n=3
    INFO[06-08|13:48:09] ensuring discoverd is running on all hosts
    EROR[06-08|13:48:23] error listing jobs                       host=flynn01 error="http: unexpected EOF reading trailer"
    INFO[06-08|13:48:24] checking flannel
    INFO[06-08|13:49:16] flannel is not running on each host, starting missing jobs
    INFO[06-08|13:49:16] started flannel job                      job.id=flynn01-f2faeffd-6e16-47a1-883a-f1479a9708e1
    INFO[06-08|13:49:16] flannel fix complete
    INFO[06-08|13:49:16] waiting for discoverd to be available
    INFO[06-08|13:49:16] checking for running controller API
    INFO[06-08|13:49:16] checking status of sirenia databases
    INFO[06-08|13:49:16] checking for database state              db=postgres
    INFO[06-08|13:49:16] checking sirenia cluster status          fn=CheckSirenia service=postgres
    INFO[06-08|13:49:16] found running leader                     fn=CheckSirenia service=postgres
    INFO[06-08|13:49:16] found running instances                  fn=CheckSirenia service=postgres count=2
    INFO[06-08|13:49:16] getting sirenia status                   fn=CheckSirenia service=postgres
    INFO[06-08|13:49:16] killing any running schedulers to prevent interference
    INFO[06-08|13:49:35] getting service metadata                 fn=FixSirenia service=postgres
    INFO[06-08|13:49:35] getting primary job info                 fn=FixSirenia service=postgres job.id=flynn03-e6439876-de09-4870-ae1e-c602897d1ffa
    INFO[06-08|13:49:35] getting sync job info                    fn=FixSirenia service=postgres job.id=flynn02-abcc1c5d-8e05-4351-967f-67680bcfbfdc
    INFO[06-08|13:49:35] terminating unassigned sirenia instances fn=FixSirenia service=postgres
    INFO[06-08|13:49:35] checking for database state              db=mariadb
    INFO[06-08|13:49:35] checking sirenia cluster status          fn=CheckSirenia service=mariadb
    INFO[06-08|13:49:35] found running leader                     fn=CheckSirenia service=mariadb
    INFO[06-08|13:49:35] found running instances                  fn=CheckSirenia service=mariadb count=2
    INFO[06-08|13:49:35] getting sirenia status                   fn=CheckSirenia service=mariadb
    INFO[06-08|13:49:35] cluster claims to be read-write          fn=CheckSirenia service=mariadb
    INFO[06-08|13:49:35] checking for database state              db=mongodb
    INFO[06-08|13:49:35] skipping recovery of db, no state in discoverd db=mongodb
    INFO[06-08|13:49:35] checking for running controller API
    INFO[06-08|13:49:35] killing any running schedulers to prevent interference
    13:49:57.400922 host.go:166: error listing jobs from flynn01: http: unexpected EOF reading trailer

The flynn-host log also seems to be full of this:

    t=2018-06-08T13:50:53+0000 lvl=info msg="request started" component=host req_id=821e8a0a-ebd8-4931-b5ca-d49483be893c method=GET path=/host/jobs client_ip=10.10.194.75
    t=2018-06-08T13:51:03+0000 lvl=info msg="request completed" component=host req_id=821e8a0a-ebd8-4931-b5ca-d49483be893c status=200 duration=9.868473227s
    t=2018-06-08T13:51:15+0000 lvl=info msg="request started" component=host req_id=5adaeb45-48d0-49b4-bc59-487332ba990b method=GET path=/host/jobs client_ip=10.10.194.75
    t=2018-06-08T13:51:24+0000 lvl=info msg="request completed" component=host req_id=5adaeb45-48d0-49b4-bc59-487332ba990b status=200 duration=9.028439401s
    t=2018-06-08T13:51:42+0000 lvl=info msg="request started" component=host req_id=7a73a44b-14b0-4444-bd12-83ed6f11132f method=GET path=/host/jobs client_ip=10.10.194.233
    t=2018-06-08T13:51:49+0000 lvl=info msg="request completed" component=host req_id=7a73a44b-14b0-4444-bd12-83ed6f11132f status=200 duration=6.437168223s
    t=2018-06-08T13:52:00+0000 lvl=info msg="request started" component=host req_id=9d0b6ea2-99ba-4789-92fe-d1e725377002 method=GET path=/host/jobs client_ip=10.10.194.233
    t=2018-06-08T13:52:07+0000 lvl=info msg="request completed" component=host req_id=9d0b6ea2-99ba-4789-92fe-d1e725377002 status=200 duration=7.215830668s
    t=2018-06-08T13:52:19+0000 lvl=info msg="request started" component=host req_id=31dc4ab5-33ff-4781-91a9-b19c35196114 method=GET path=/host/jobs client_ip=10.10.194.233

Any suggestions? 

Thanks

**Comment by joeczucha** [comment]
This is the output of `flynn-host ps` on the first node

    ID                                            STATE     CREATED             CONTROLLER APP  CONTROLLER TYPE  ERROR
    flynn03-034f3c1e-a4fc-415e-9e78-ef8218529700  running   About a minute ago  controller      web
    flynn01-852469f7-deff-4086-9687-09d9efb3742a  running   3 minutes ago       discoverd       app
    flynn01-8f046d40-5036-4030-90bb-2ba16c98d8d8  running   3 minutes ago       flannel         app
    flynn03-49725367-8c58-47e1-bde4-62cb15c817ff  running   4 minutes ago       controller      web
    flynn03-0643e0c2-caf2-45f7-a43b-b973c6c7baac  running   6 minutes ago       controller      web
    flynn03-a9e5fadd-befd-41a9-81b7-ec6562be0cfc  running   9 minutes ago       controller      web
    flynn03-0cad773a-2afe-49b8-bc9f-7cdaaee8772a  running   10 minutes ago      controller      web
    flynn03-e32a7cd0-ae25-465f-b7d8-1de623f13895  running   12 minutes ago      controller      web
    flynn03-892e253c-97af-42d8-8774-40c5bb73f046  running   14 minutes ago      controller      web
    flynn03-ba022b46-f16a-4376-af2b-6ac499bf20a2  running   16 minutes ago      controller      web
    flynn03-c3fe043d-9f6d-4b13-a8aa-b71b7e776c58  running   18 minutes ago      controller      web
    flynn03-e5ea4012-d092-43f7-a726-7373472f3f73  running   21 minutes ago      controller      web
    flynn03-5da36458-4891-4d8d-9e31-9144fcf39503  running   22 minutes ago      controller      web
    flynn03-294bbea2-f233-47e7-aab9-3641da82b13c  running   25 minutes ago      controller      web
    flynn03-656efe18-24f6-4cc3-8533-66a7296134d1  running   27 minutes ago      controller      web
    flynn03-b3e9993b-bf6b-42dc-8302-9453b8ebea7f  running   34 minutes ago      controller      web
    flynn03-dea3ad68-e5b0-4924-8bd3-f6ed6259baf9  running   36 minutes ago      controller      web
    flynn03-9b96affd-a784-4cc1-9684-ca07fce7e189  running   37 minutes ago      controller      web
    flynn03-61027f58-c7b3-4045-bb63-169f866a9881  running   39 minutes ago      controller      web
    flynn03-398c54ac-7532-4e37-acf9-5ea79c8e4f45  running   41 minutes ago      controller      web
    flynn03-40455c06-9783-4c59-8828-dcc51a92c81b  running   42 minutes ago      controller      web
    flynn03-5e3255ad-266a-4df8-8b1b-4ecf2d9bc2a3  running   44 minutes ago      controller      web
    flynn03-e15e4b51-3782-48a8-b720-e7996ddd0c23  running   46 minutes ago      controller      web
    flynn03-f89a7445-6025-4933-91b3-ee9b4e4bae34  running   48 minutes ago      controller      web
    flynn03-afb2c9e0-d4fd-487a-9319-571056c7378e  running   50 minutes ago      controller      web
    flynn03-3107cbbc-61f3-4ce5-b0bc-5958e5b605ee  running   52 minutes ago      controller      web
    flynn03-9f888c3d-8e39-4c14-85ee-e3c4b15c048e  running   54 minutes ago      controller      web
    flynn03-d6d8c4a5-12a3-47a5-a89e-980a84ae7e97  running   55 minutes ago      controller      web
    flynn03-4ecca378-0ef9-4ded-b864-56ccf6d4b453  running   57 minutes ago      controller      web
    flynn03-d9cd0193-c578-4e5d-9687-33fa385f3a98  running   59 minutes ago      controller      web
    flynn03-b92245aa-943b-43c0-9bd9-cab2fa154af8  running   About an hour ago   controller      web
    flynn03-92edc376-a78a-4dcb-84ff-c5e6731198e1  running   About an hour ago   controller      web
    flynn03-3573a939-5292-4097-b8a9-6db19e3a2ff0  running   About an hour ago   controller      web
    flynn03-842d371a-26a4-4d55-b1da-f8a792af2d65  running   About an hour ago   controller      web
    flynn03-0cadcf42-ed50-4c8d-8c71-c7e9e397fc43  running   About an hour ago   mariadb         mariadb
    flynn02-d2645fb1-7911-4599-9256-abe4303fd7e3  running   About an hour ago   mariadb         mariadb
    flynn02-abcc1c5d-8e05-4351-967f-67680bcfbfdc  running   About an hour ago   postgres        postgres
    flynn03-e6439876-de09-4870-ae1e-c602897d1ffa  running   About an hour ago   postgres        postgres
    flynn03-cb287634-dc1c-453f-9220-43173a2af513  running   About an hour ago   discoverd       app
    flynn03-df2f42cd-5d97-4e87-b7b6-50f228dfb621  running   About an hour ago   flannel         app
    flynn02-790f03f7-00dd-4bfa-ab39-b830a9837a6c  running   About an hour ago   discoverd       app
    flynn02-d4da207a-e633-471c-969e-79642f05fecd  running   About an hour ago   flannel         app
    flynn01-5b994a02-1800-40ae-8039-05ecc908d257  starting  About an hour ago   flannel         app

**Comment by joeczucha** [comment]
I manually went through and killed all those jobs, then restarted flynn-host on each of the nodes. Now it looks a bit more sane: 

    ID                                            STATE    CREATED        CONTROLLER APP  CONTROLLER TYPE  ERROR
    flynn02-87bce5b7-8ca3-4e13-9ff5-79a2f9616d5a  running  2 minutes ago  postgres        postgres
    flynn03-5c0378cc-f1d8-49a3-b9ad-4f72c93b879c  running  2 minutes ago  postgres        postgres
    flynn01-aeba7c10-fc13-40ad-9600-73cd5f45c26e  running  4 minutes ago  discoverd       app
    flynn01-4a275f1e-8d1a-43d0-bccf-ff64d71d7e89  running  4 minutes ago  flannel         app
    flynn03-be68620d-7245-4223-9cab-a0679448c3cf  running  4 minutes ago  discoverd       app
    flynn03-6f92c7ca-97fd-4c22-8481-448a5edc4213  running  4 minutes ago  flannel         app
    flynn02-8491a5bc-71d7-41c3-a2aa-872aaf4e4117  running  4 minutes ago  discoverd       app
    flynn02-0548c902-e29c-47e6-9cbf-63acf62e2f2d  running  4 minutes ago  flannel         app

But now I'm just getting this error:

# flynn-host fix -n 3
INFO[06-08|15:06:15] found expected hosts                     n=3
INFO[06-08|15:06:15] ensuring discoverd is running on all hosts
15:07:21.254145 host.go:166: error starting discoverd on flynn01: unknown_error: Something went wrong

**Comment by joeczucha** [comment]
I manually went through and killed all those jobs, then restarted flynn-host on each of the nodes. Now it looks a bit more sane: 

    ID                                            STATE    CREATED        CONTROLLER APP  CONTROLLER TYPE  ERROR
    flynn02-87bce5b7-8ca3-4e13-9ff5-79a2f9616d5a  running  2 minutes ago  postgres        postgres
    flynn03-5c0378cc-f1d8-49a3-b9ad-4f72c93b879c  running  2 minutes ago  postgres        postgres
    flynn01-aeba7c10-fc13-40ad-9600-73cd5f45c26e  running  4 minutes ago  discoverd       app
    flynn01-4a275f1e-8d1a-43d0-bccf-ff64d71d7e89  running  4 minutes ago  flannel         app
    flynn03-be68620d-7245-4223-9cab-a0679448c3cf  running  4 minutes ago  discoverd       app
    flynn03-6f92c7ca-97fd-4c22-8481-448a5edc4213  running  4 minutes ago  flannel         app
    flynn02-8491a5bc-71d7-41c3-a2aa-872aaf4e4117  running  4 minutes ago  discoverd       app
    flynn02-0548c902-e29c-47e6-9cbf-63acf62e2f2d  running  4 minutes ago  flannel         app

But now I'm just getting this error:

    $ flynn-host fix -n 3
    INFO[06-08|15:06:15] found expected hosts                     n=3
    INFO[06-08|15:06:15] ensuring discoverd is running on all hosts
    15:07:21.254145 host.go:166: error starting discoverd on flynn01: unknown_error: Something went wrong

**Comment by joeczucha** [comment]
$ flynn-host fix -n 3
    INFO[06-08|15:19:02] found expected hosts                     n=3
    INFO[06-08|15:19:02] ensuring discoverd is running on all hosts
    15:25:11.223849 host.go:166: error listing jobs on flynn01: Get http://10.10.194.233:1113/host/jobs: EOF

**Comment by joeczucha** [comment]
Not sure if this is an improvement but now I'm just getting

    $ flynn-host fix -n 3
    INFO[06-08|15:19:02] found expected hosts                     n=3
    INFO[06-08|15:19:02] ensuring discoverd is running on all hosts
    15:25:11.223849 host.go:166: error listing jobs on flynn01: Get http://10.10.194.233:1113/host/jobs: EOF

It looks like the jobs file might be corrupted, is there any way to regenerate it?

**Comment by thomasmodeneis** [comment]
Restart flynn host on each node:
`systemctl restart flynn-host`

Then fix the cluster:
`flynn-host fix --min-hosts 3`

On my experience, nodes with 3 legs tend to fail to restore if data was corrupted in one of the legs.
If this is your case you have to demote the faulty leg, re-install, and init with the token, this works most of the cases. :)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
