### ISSUE TITLE
Retrieve Discovery Token

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4400]
Is there any way to retrieve the discovery token from an existing cluster?
Is this set in some env variable?

Thanks,
Salvo

**Comment by SalvoLunar** [comment]
I want to add a node to my existing cluster and I'm not sure if I can reuse the discovery token.
What's the correct way to add a new node? this doesn't seem to be explained well in the documentation.

Can you please advice?

Thanks,
Salvo

**Comment by thomasmodeneis** [comment]
To add a new PEER you first need to init the PEER:
`sudo flynn-host init --discovery=https://discovery.flynn.io/clusters/TOKEN`

and then set it to discoverd:
`flynn -a discoverd env set DISCOVERD_PEERS=NEW_PEER_IP`

**Comment by bbaptist** [comment]
You can just do the init with the discovery token and then restart `flynn-host`, no need to pass any IP addresses, they are stored in the discovery server.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
