### ISSUE TITLE
Setting up Cloudflare Load Balancing with Flynn

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4404]
Hi there,

I need to create an endpoint to check the health of my nodes so that I can configure the Load Balancer in Cloudflare.

I can see that is possible to [monitor](https://flynn.io/docs/production#monitoring) the entire Cluster but I think it would be useful to have some functionality that allows to monitor the health of a single node.

Also the documentation [states](https://flynn.io/docs/production#dns-and-load-balancing) that 

> We recommend running Flynn with low-TTL round-robin DNS A records pointing at each host. For automatic failover, **health checks should be configured that automatically remove a host’s A record if it is unhealthy**.

But it doesn't explain how to do so.

Can you please advice?

Thanks,
Salvo

**Comment by thomasmodeneis** [comment]
Hi,

```
You can hit /host/status on port 1113:
➜  ~ curl 107.150.40.146:1113/host/status
{"id":"s121447","pid":11986,"url":"http://YOUR_CLUSTER_PEER:1113","discoverd":{"job_id":"s121447-56cb0400-0ed1-4e25-a380-9c450a330868","url":"","dns":":53"},"network":{"job_id":"s121447-813ea143-f50c-4361-a6ee-c5af33a4eb82","subnet":"/24","mtu":1450,"resolvers":["127.0.0.1"]},"version":"v20170719.0-81418bc","flags":null}% 
```

**Comment by bbaptist** [comment]
You can check the status of an individual node by fetching a ping page at http://xxx.xxx.xxx.xxx/ping with the host header of controller.your.flynn.domain, with the xxx.xxx.xxx.xxx being the IP address of the host you want to get the status of.

For example:
```
curl -f -s -w '%{http_code}' -H "Host: controller.your.flynn.domain"  http://xxx.xxx.xxx.xxx/ping
```
This will return `200` on success and another http code on any errors.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
