### ISSUE TITLE
Dashboard not working after reboot

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4405]
When trying to access the dashboard after the reboot of one of the nodes ( I had to clean install flynn-host and reinit discovery) the dashboard is not working anymore

It's accessible and I can login but I cannot see any apps, not even the standard ones.

this is the erros I'm getting:

Refused to connect to '<URL>' because it violates the following Content Security Policy directive: "connect-src 'self' controller.******.com status.********

and 

![screen shot 2018-06-19 at 18 58 17](https://user-images.githubusercontent.com/31966108/41615304-c8aae83a-73f2-11e8-864d-b5e43512a8d9.png)
.com api.github.com".

Not sure what I can do to fix this.

Can you advice?

**Comment by SalvoLunar** [comment]
Also these resources seem to have been blocked
![screen shot 2018-06-19 at 19 02 24](https://user-images.githubusercontent.com/31966108/41615510-5a14955a-73f3-11e8-9d58-9c85b290ad66.png)

**Comment by jvatic** [comment]
@SalvoLunar are `CONTROLLER_DOMAIN` and `DEFAULT_ROUTE_DOMAIN` set correctly on the dashboard app? And is SSL correctly configured? (you should be able to access `CONTROLLER_DOMAIN` via https)
