### ISSUE TITLE
Bootstrap process hangs on "checking online hosts"

### ISSUE THREAD

**Issue by joeczucha** [flynn/flynn#4408]
I'm trying to create a new Flynn cluster and running into some issues. I've followed the steps below numerous times, but this is the first time doing so on Hetzner Cloud so I'm wondering if they use an incompatible kernel or something.

The steps that I followed were:

Rebuild the machines to a clean Ubuntu 16.04 build

    $ apt-get update && apt-get upgrade -y
    $ reboot
    $ apt-get dist-upgrade -y
    $ bash < <(curl -fsSL https://dl.flynn.io/install-flynn)

On first node:

    $ flynn-host init --init-discovery

On other nodes:

    $ flynn-host init --discovery https://discovery.flynn.io/clusters/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

    $ systemctl start flynn-host
    $ systemctl status flynn-host

Then, just to be safe: 

    $ service ufw stop

All looks good so far:

    $ service flynn-host status

    ● flynn-host.service - Flynn host daemon
      Loaded: loaded (/lib/systemd/system/flynn-host.service; enabled; vendor preset: enabled)
      Active: active (running) since Sat 2018-06-30 14:57:48 CEST; 2h 12min ago
        Docs: https://flynn.io/docs
    Main PID: 14260 (flynn-host)
        Tasks: 9
      Memory: 7.8M
          CPU: 1.933s
      CGroup: /system.slice/flynn-host.service
              └─14260 /usr/local/bin/flynn-host daemon

    Jun 30 14:57:48 flynn-01 systemd[1]: Started Flynn host daemon.

However, at that point, running `flynn ps` gives me:

    $ flynn-host ps

    17:04:22.651936 host.go:166: could not list hosts: Error sending HTTP request, errors: Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused,Get http://127.0.0.1:1111/services/flynn-host/instances: dial tcp 127.0.0.1:1111: getsockopt: connection refused

It also won't let me run `flynn host collect-debug-info`, returning the same errors as above.

Running the bootstrap command just gets stuck on "checking online hosts".

This is the content of `/var/log/flynn/flynn-host.log`:

    t=2018-06-30T14:57:48+0200 lvl=info msg="starting daemon" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:48+0200 lvl=info msg="validating host ID" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:48+0200 lvl=info msg="detecting external IP" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:48+0200 lvl=info msg="using external IP 195.201.16.12" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:48+0200 lvl=info msg="registering with cluster discovery service" app=host pid=14260 fn=runDaemon host.id=flynn01 token=https://discovery.flynn.io/clusters/0e94c07d-1dbe-4164-b83b-bd97ce031b05 addr=195.201.16.12:1113 name=flynn01
    t=2018-06-30T14:57:48+0200 lvl=info msg="registered with cluster discovery service" app=host pid=14260 fn=runDaemon host.id=flynn01 id=d7335efe-4b9e-4f05-b857-b5c5d380436f
    t=2018-06-30T14:57:48+0200 lvl=info msg="initializing volume manager" app=host pid=14260 fn=runDaemon host.id=flynn01 provider=zfs
    t=2018-06-30T14:57:48+0200 lvl=info msg="initializing job backend" app=host pid=14260 fn=runDaemon host.id=flynn01 type=libcontainer
    t=2018-06-30T14:57:49+0200 lvl=info msg="setting host status PID" app=host pid=14260 fn=runDaemon host.id=flynn01 pid=14260
    t=2018-06-30T14:57:49+0200 lvl=info msg="creating HTTP listener" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:49+0200 lvl=info msg="opening state databases" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:49+0200 lvl=info msg="starting sink persistence routine" app=host pid=14260 host.id=flynn01 component=sinkManager fn=persistSinks
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/data" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/ext2" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/00b6f64ee3de6906df781fc9c7fdc87121295f08c6dac2bc80124a663bf8e046" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/01b9b169f4e8480624ce1f8b7584ae8a231a91fb44cf8fd63b7c5e12f778cd24" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/05c52bffd84649fbb3903a3c441aa28024cbd7bc5f930a8498f95ff65188256f" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/11b172c646f465690733669900a0c272bc3e55a872fea4837c768df9ab7ea135" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/1ffd099f03255709f061dde7688dfe0598387795b38babb37ab86030eaa46d9e" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/31c1b3064fdb60ff2e55b85a1ab5e6879df5e63e638d553aef5d806a9d08d8a4" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/34208476c7528e0cf50c7f512e022178ee75928c6f680cd2e9bc2bdb3ba13a86" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/3c3d8039d02a9d47dd2ee1c85b37360b321ea197273dd4dc873b9c5e005d096f" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/435a73367f3ab76d3cf14b46a7a297d850c19f53e27049a0933aef77caa31bae" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/49bf8bafc185f0acf801a72e01f0f864b888e91bd2fcf6139806460548203cc4" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/4e9f13fc7cc37af43ac8274d300251248a6404b5e3f9db8b87c8850a80a0f653" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/4fbfccf56731bcf2d5d4c39c08f4d0bf6e0d3bdc5118075251411ea6486bbdea" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/5031c3ca95b4d3d2d8f8a869ab43ddd7d72035d36ff36b40e2dab0fe2d923427" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/6483b4c91fb482e265e6c0358adf81e6bf27aecb8aa7edfb5a809bf5db7a647f" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/6751c9987330b80198a532d6643b27568f61d90ea29d39aa3ba21ff6e82e6c6c" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/6d1c73b6767a44587362d2083c43e038589652bfaa22d861a367c47d8b9ac287" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/6dc530a0d72a16d92ebf587ac63d7ea243bcb0c351b100d485069586e52c145a" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/73cfd2ac3ea15e6d2385869a278b2aa85754590439d9c326428aa83e8db7ca60" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/77bb5ee8509cd4928fe315df70483690500d89bf6c99af3c8daf5a86896e7a78" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/7b4d6c66fbc48bf578ce14d1beb6c1d83e4d81bd6bb2fc706d110c103ef96746" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/84963f0c72b38adc96dd1bca37bde57138af2621d2a0cc3cfcbc745c68763f7b" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/8de3f6ac3d29b70d0054a5a35f26d902a7ecaed460a96eb2637d9906887d1f86" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/90db2bc2e84c2e04a72f1165e190b22b7cc9c5d67e49c888d8f7dda7c26f4c1a" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/b2d311f3f7148c12bf0567e2805938936c972425ff9de72283aa5e13a10e60bf" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/b31f754603eed9715aed85b2e589d68432a005d212e3b976f713d2fecba9f4eb" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/c3895dada3af0558f3320689471476c6451a265dd55235c9eb4634cf6f62e31d" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/cbb805c7031bf97ecd955220c617d4e9c4a8036fbfe24e2cb186f28704f786cc" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/cd5fec716e8e543c688fa930d95cbec40b2dbfd1300b37655e72c41d52ab20f8" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/e0217a5609bc35ab018d4e613ab4fd3bfe4917261fd3143afeec33e7f8e9162a" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/e2d00e523b3d934cf233198bfc781ec0a8d3e626daf52c05b4d0faf909a9567a" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/ea7426975406f7355486cc3af07c5899d722fbee717d223edb385f309c112a07" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/f404f624c737b5020e95a5feba71d6535f7923bc4b0bda2bfaef0e79cc806062" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=dbug msg="zfs get all -Hp flynn-default/squashfs/fb4fd2a7d1f63aa01470d4abda77e8b7061f3f5744bd075d7d99c9cf41be21fe" package=zfs
    t=2018-06-30T14:57:49+0200 lvl=info msg="restoring state" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:49+0200 lvl=info msg="no stored global backend config" app=host pid=14260 host.id=flynn01 component=backend backend=libcontainer fn=UnmarshalState
    t=2018-06-30T14:57:49+0200 lvl=info msg="serving HTTP requests" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:49+0200 lvl=info msg="getting cluster peer IPs" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:49+0200 lvl=info msg="got cluster peer IPs" app=host pid=14260 fn=runDaemon host.id=flynn01 peers=[]
    t=2018-06-30T14:57:49+0200 lvl=info msg="connecting to cluster peers" app=host pid=14260 fn=runDaemon host.id=flynn01 ips=[]
    t=2018-06-30T14:57:49+0200 lvl=info msg="no cluster peers available" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:49+0200 lvl=info msg="resurrecting jobs" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:49+0200 lvl=info msg="blocking main goroutine" app=host pid=14260 fn=runDaemon host.id=flynn01
    t=2018-06-30T14:57:49+0200 lvl=info msg="waiting for discoverd" component=cluster-monitor fn=Run

The kernel version is:

    $ uname -r
    4.4.0-128-generic

There are also no firewalls or security groups in place.

Any advice would be greatly appreciated.

Thanks!

**Comment by xzyaoi** [comment]
Same here, 

Kernel Version is:

```
4.4.0-91-generic
```

**Comment by joeczucha** [comment]
@xzyaoi Also on Hetzner or another host?

**Comment by xzyaoi** [comment]
@joeczucha Another host, hosted by QCloud in China.

**Comment by xzyaoi** [comment]
@joeczucha I try to stop the service first, and then re-run the command

```
flynn-host init --init-discovery
```

and

```
flynn-host init --discovery https://discovery.flynn.io/clusters/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

Now it is working. But I still have no idea why at the begining it is not working.

**Comment by joeczucha** [comment]
I managed to get mine working too: I re-ran the commands to init and set the discovery token but it still wasn't finding the hosts. In the end, I just specified the hosts manually `CLUSTER_DOMAIN=xxxx.com flynn-host bootstrap --min-hosts 3 --peer-ips=xx.xx.xx.xx,xx.xx.xx.xx,xx.xx.xx.xx` and it worked straight away.

Very strange, maybe there is an issue with the discovery service.
