### ISSUE TITLE
47mb Rails app taking > 20 minutes to deploy

### ISSUE THREAD

**Issue by mikesutton** [flynn/flynn#4409]
I have a cluster of 2 hosts - 8gb mem each. Same network.
A pretty basic rails app - with Postgres - is consistently taking ~15mins and more to deploy.

GIt push works pretty quickly, then it sits are the building <app> for 3-5 mins.

Asset precompile happens in ~5-10 seconds.

Bundle takes about 5 mins

Then it sits at Compiled slug size for ~10 mins.

I'm stumped - also a newbie, love the ease, but this is not sustainable.

Things I've tried:

Bumping slugbuilder memory to 5gb!
Increasing postgres processes

Any pointers to logs etc woould be hugely appreciate.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
