### ISSUE TITLE
could not garbage collect all volumes

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4410]
Hi,

I'm trying to run the garbage collector on my cluster but I'm getting this error:

15:03:53.351614 host.go:166: could not garbage collect all volumes

This is happening for over 20 volumes, they seem somehow stuck...

could not delete ext2 volume XXXXXX.xxxxxx.com-25ac16f0-ad9c-41e3-a2bf-2cde46d0deb0: unknown_error: Something went wrong

I've updated my wordpress website but I keep seeing the old version popping up every now and then, and it think the 2 problems are related.

Is there any way I can force the garbage collector to delete those volumes?

Cheers,
Salvo

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
