### ISSUE TITLE
Deleting app without deleting routes causes them to never be deleted.

### ISSUE THREAD

**Issue by MaddoxDevelopment** [flynn/flynn#4411]
I'm not sure if this is intentional or not, but when you delete an app without deleting the routes first, they can not be used again unless you login to the router's db and remove them manually.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
