### ISSUE TITLE
Add peers

### ISSUE THREAD

**Issue by theprogramer** [flynn/flynn#4414]
How add peers to an solo cluster?

I have an peer and two proxies.
How promote this two proxies to peers?
If i promote only one, the cluster broken: "Unknow leader"

flynn-host fix --min-hosts 3 --peer-ips {...}
Dont promote the proxies to peers....

**Comment by jvatic** [comment]
I believe you must start with at least 3 nodes in a cluster if you want to add peers to it. You can however take a full cluster backup and restore into a multi-node cluster.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
