### ISSUE TITLE
Sonarqube nor dotnet core docker image not starting

### ISSUE THREAD

**Issue by Assassyn** [flynn/flynn#4415]
I am trying to run the Sonarqube in Flynn. The same image is running on Azure web app for container without any problems. 

Checking app process log it seems that SonarQube is stating properly until the last step. The lsat few lines of log looks like that: 

[2018-07-22T11:26:20.093786Z]    2018.07.22 11:26:20 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
[2018-07-22T11:26:21.377574Z]    2018.07.22 11:26:21 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
[2018-07-22T11:26:21.379176Z]    2018.07.22 11:26:21 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by bbaptist** [comment]
The port needs to be changed to start on 8080. By default for web processes in Flynn it has a health check on port 8080 and if it is not able to connect it stops the container.

**Comment by Assassyn** [comment]
I have tried to explose the port ( I am not sure I did it correctly)


My docker files looks like that: 

FROM sonarqube:7.1-alpine

WORKDIR $SONARQUBE_HOME

EXPOSE 8080

COPY entrypoint.sh /opt/sonarqube/bin/

RUN chown sonarqube:sonarqube /opt/sonarqube/bin/entrypoint.sh
RUN chown sonarqube:sonarqube /opt/sonarqube/extensions/
RUN chmod +x /opt/sonarqube/bin/entrypoint.sh

ENTRYPOINT ["/opt/sonarqube/bin/entrypoint.sh"]

**Comment by Assassyn** [comment]
I have tried to deploy another, .net based docker image, and I have no error and "Service unavailable" as well

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
