### ISSUE TITLE
After a reboot flynn does not start.

### ISSUE THREAD

**Issue by Assassyn** [flynn/flynn#4416]
I am runing 64bit Ubunty 16.04 with flynn nightly ( stable one has exactly the same problem)

After every reboot a single node flynn is not able to start.

when I run flynn-host ps it reporting only two services running

flynnmaster-e6e5d4f1-a2c2-4f56-9631-8633a55b3661  running  48 seconds ago  discoverd       app
flynnmaster-09aa2dee-7896-46c7-9edf-5d552a7f4c86  running  48 seconds ago  flannel         app

the collect-debug-info have 401 error.

Dashboard does not work for http not https

I did run the flynn-host log for first instnace of controller and i got this result:

panic: dial tcp 100.100.89.2:5432: getsockopt: connection timed out [recovered]
        panic: dial tcp 100.100.89.2:5432: getsockopt: connection timed out

goroutine 1 [running]:
github.com/flynn/flynn/pkg/shutdown.(*handler).exit(0xc420067650, 0x0, 0x0, 0x0, 0x8a9a20, 0xc42007f4a0)
        /go/src/github.com/flynn/flynn/pkg/shutdown/handler.go:69 +0x1d8
github.com/flynn/flynn/pkg/shutdown.Exit()
        /go/src/github.com/flynn/flynn/pkg/shutdown/handler.go:40 +0x6a
panic(0x8a9a20, 0xc42007f4a0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/flynn/flynn/pkg/postgres.Wait(0xc42007ee10, 0x0, 0xa)
        /go/src/github.com/flynn/flynn/pkg/postgres/postgres.go:83 +0x785
main.main()
        /go/src/github.com/flynn/flynn/controller/controller.go:61 +0x10e

I have checkd that firewall is deactivated.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
