### ISSUE TITLE
git submodules doesn't work with github-created apps

### ISSUE THREAD

**Issue by Darkless012** [flynn/flynn#4418]
First I have to say that submodules works while using `git push flynn` (eg. gitreceived should work)

But having the same source code (commit), the deploy via Dashboard button (from github repositories) will not pull any submodules. The submodule folder is just empty.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
