### ISSUE TITLE
tried to unlink postgresql from app, database was deleted

### ISSUE THREAD

**Issue by linpau** [flynn/flynn#4424]
Hi,

I had two apps tied to one redis database and one postgresql database.
In flynn dashboard/providers I tried to unlink one of the apps from the redis database. The database was kept and the app was unlinked successfully.
I then tried to unlink one the same app from the postgresql database. The database was deleted!

In both cases I was informed that the data was going to be kept and in both cases two apps were tied to the database.

1. I'm glad I had a backup, but please take a look at this.
2. How would I unlink a database like this through the Command Line Interface?

**Comment by jvatic** [comment]
@linpau what version of Flynn are you using? (The cluster status page in the dashboard shows the Flynn version at the top, second last icon in the navigation.) I could not reproduce this behaviour, any additional information you can provide may be helpful.

**Comment by linpau** [comment]
@jvatic I got this output from flynn-host version
v20170719.0-81418bc

**Comment by jvatic** [comment]
@linpau It looks like you're running the latest "stable" release which is very outdated at this point. The "nightly" channel is, counterintuitively, the recommended one to use and contains over a year worth of bug fixes.

**Comment by linpau** [comment]
Thank you @jvatic
