### ISSUE TITLE
Unable to execute any commands on MongoDB

### ISSUE THREAD

**Issue by amarksteadman** [flynn/flynn#4426]
Using a MongoDB database created with the Flynn CLI, any operation on the database (via the MongoDB shell or in-app) results in the error "not authorized on admin to execute command". For example:

```
$ flynn mongodb mongo
MongoDB shell version: 3.2.11

rs0:PRIMARY> show dbs
2018-08-29T12:19:00.491+0000 E QUERY    [thread1] Error: listDatabases failed:{
	"ok" : 0,
	"errmsg" : "not authorized on admin to execute command { listDatabases: 1.0 }",
	"code" : 13
} :
```

This is using the latest version of Flynn as of 2018-08-28, creating a MongoDB database using the Flynn CLI as per the docs. The stack is running on a 3-node Ubuntu 16.04 cluster, running on DigitalOcean.

The app in question uses PostgreSQL, Redis and MongoDB, so the `DATABASE_URL` environment variable is now set to PostgreSQL, as MongoDB isn't the primary database for the app. Doubt that makes a difference, but thought I'd mention it. I've not done any kind of provisioning or dump/restore on the database... this is literally the first thing I've tried to do on the db, but not a single action will run.

Looking forward to using Flynn in production as soon as MongoDB is fixed.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
