### ISSUE TITLE
Is Flynn in active development / maintenance only?

### ISSUE THREAD

**Issue by Vorror** [flynn/flynn#4428]
I'm curious to know if the Flynn project is in maintenance-only mode.

It seems that the roadmap has stalled:
https://github.com/flynn/flynn/projects/1

The two "ongoing" issues #1995 and #267 have been in progress for years.

Nearly every datastore (mariadb, redis, mongo) Flynn ships with is outdated with no documentation on how to self-upgrade. This is in addition to not supporting Ubuntu 18.04.

There additionally has been no "stable" release for over a year. I know that the  _plan_ [#4319] is to switch to nightly-only channel releases, but that was never done. A short blurb to use the nightly channel could have been added to the installation docs/README.

A lot of PRs from the nightly builds don't have an associated issue — so I'm running under the assumption that Flynn is still used internally, but no longer a focus?

Flynn is a great project and while it would be unfortunate to hear that it's in maintenance mode I think the roadmap + its future should be clearly stated.

**Comment by philiplb** [comment]
Good point describing our situation here as well.

**Comment by philiplb** [comment]
Every now and then there seems to be a push in development for a few days which then stops. Like switching to gRPC for the internal APIs (https://github.com/flynn/flynn/pull/4307), the (nice) Prometheus metrics with Grafana (https://github.com/flynn/flynn/pull/4373) or some Docker refactoring (https://github.com/flynn/flynn/pull/4367) and a branch where LetsEncrypt support was  visible (https://github.com/flynn/flynn/tree/lets-encrypt).
Some CI improvements (https://github.com/flynn/flynn/pull/4425) give a bit of hope that the infrastructure gets some maintenance as preparation for further development though. :)

All in all we stick with Flynn as it still fullfils our needs and there is nothing better for us yet.

**Comment by titanous** [comment]
We use Flynn extensively in production, but haven't had a lot of development bandwidth to push features forward. That said, we do have a variety of projects in progress (including the PRs that @philiplb) that will be released in the coming months. Thanks for using Flynn!

**Comment by Vorror** [comment]
@titanous Thanks for the reply! Have you thought about allowing financial contributions to the project(i.e opencollective)?

I appreciate that opensource dev offers 0 monetary incentive for Flynn since you have a paid support. But I imagine if the community at least provided something to offset the costs Prime Directive may focus on it a bit more.
