### ISSUE TITLE
Out of Memory - MySQL

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4436]
Hi,

I had some problem with mysql this morning and I had to restore everything from a backup.
I've checked the logs back and I find out that these processes where killed because of OOM issues.

```
[7767519.006003] Killed process 19445 (mysqld) total-vm:973984kB, anon-rss:83580kB, file-rss:0kB
[7767519.039701] Killed process 9032 (innobackupex) total-vm:265472kB, anon-rss:26716kB, file-rss:0kB
```

I'm running flynn on a 3 nodes cluster with 4gb of Ram each and I'm using it for a relatively simple wordpress website.
Is there any way to avoid this issue without having to increase the RAM on each node?

Could this be a configuration issue?

Thanks,
Salvo

**Comment by JMSwag** [comment]
Try updating the memory limit for mariadb.

```
# Example
flynn -a maridb limit set mariadb memory=2GB
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
