### ISSUE TITLE
docker based CI/CD using gitlab & multiple processes

### ISSUE THREAD

**Issue by mihado** [flynn/flynn#4437]
hi there,

I'm thinking of the following setup for a rails app:
* `script/server` to start the server process
* `script/worker` to start the worker process
* The docker image will be built with `script/server` as the default command.
* The image will be hosted on the registry of the project on gitlab.

If I do nothing, I assume that the web process will be started automatically. Is it true?
How do I enable the worker process?
Is there a setting to keep only 5 recent releases on flynn host?

Many thanks.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
