### ISSUE TITLE
blobstore: unknown backend "s3main"

### ISSUE THREAD

**Issue by dottodot** [flynn/flynn#4438]
I've recently moved my blobstore from s3 to minio but the blobstore logs keep throwing an error of 

```
blobstore: unknown backend "s3main"
```
when i have the following setting
```
DEFAULT_BACKEND=minio
```

why is this and how do I fix it.

**Comment by bbaptist** [comment]
Do you have the `BACKEND_MINIO` variable set?

What version are you running?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
