### ISSUE TITLE
Occasional 500s on discovery.flynn.io

### ISSUE THREAD

**Issue by lenn4rd** [flynn/flynn#4439]
Yesterday I upgraded my Flynn cluster to the most recent nightly build and had some issues getting the nodes to form a cluster. In the past this process was flawless but yesterday I saw some log messages about the discovery service returning a 500. When I run the same requests, i.e. `GET https://discovery.flynn.io/clusters/<UUID>/instances`, I occasionally see a server error.

Just wanted to let you know. Am I right in assuming this can cause issues when forming the cluster and causing nodes to drop out?

**Comment by titanous** [comment]
This issue should be resolved now. It could cause issues starting new clusters, but shouldn't affect existing ones.

**Comment by lenn4rd** [comment]
From my side it looks fine now. Thanks!
