### ISSUE TITLE
Webpacker requires Yarn >= 0.25.2 and you are using 0.22.0

### ISSUE THREAD

**Issue by williamhatch** [flynn/flynn#4447]
rake assets:precompile
I, [2018-10-11T04:14:39.628368 #23]  INFO -- : Writing /app/public/assets/application-19f7aded4e7e773e7aaded6553cd10f08d882d38782ae6c1ab7bd9d20d8bd39b.js
I, [2018-10-11T04:14:39.631544 #23]  INFO -- : Writing /app/public/assets/application-19f7aded4e7e773e7aaded6553cd10f08d882d38782ae6c1ab7bd9d20d8bd39b.js.gz
I, [2018-10-11T04:14:39.698862 #23]  INFO -- : Writing /app/public/assets/application-13e444d43799ce64b43514f6cc94f23d6e633a449e576c5ccb14945b7634132a.css
I, [2018-10-11T04:14:39.699044 #23]  INFO -- : Writing /app/public/assets/application-13e444d43799ce64b43514f6cc94f23d6e633a449e576c5ccb14945b7634132a.css.gz
Webpacker requires Yarn >= 0.25.2 and you are using 0.22.0
Please upgrade Yarn https://yarnpkg.com/lang/en/docs/install/

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
