### ISSUE TITLE
when using flynn-host bootstrap --min-hosts 3

### ISSUE THREAD

**Issue by williamhatch** [flynn/flynn#4449]
deploy-app redis error: timed out waiting for scale to complete (waited 300 seconds)

**Comment by williamhatch** [comment]
stop at   deploy-app redis


05:56:22.359259 gen-random pg-password
05:56:22.359333 gen-random pg-password fffba3cbb2e48686c5f0e8ac8e3c8f87
05:56:22.359338 run-app postgres
05:56:24.074844 gen-random controller-key
05:56:24.075063 gen-random controller-key 0e86d1054eb452e2cacbccf46a8f4eaf
05:56:24.075383 gen-random bootstrap-id
05:56:24.075459 gen-random bootstrap-id bfb4bde5-7a8e-48d6-9930-38dcd08da70f
05:56:24.075549 gen-random dashboard-session-secret
05:56:24.075559 gen-random dashboard-session-secret 0877667e6866561a2d03a2f2f4cfdda6
05:56:24.075624 gen-random dashboard-login-token
05:56:24.075738 gen-random dashboard-login-token ae8c3f31b17d2174bb8d20586592a243
05:56:24.075747 gen-random name-seed
05:56:24.075828 gen-random name-seed 8a16ba59050f849e0e35
05:56:24.075836 gen-random router-sticky-key
05:56:24.075934 gen-random router-sticky-key ODoWl/Hp6z9Kck8d2olOfVat++qQWJ7dO0vjbvI8HP8=
05:56:24.075943 wait postgres-wait
05:56:28.724494 gen-tls-cert controller-cert
05:56:30.878167 gen-tls-cert controller-cert pin: wybKYg8dn2JOsvCO3UN+PutKslYE/T0wU4nv34frT4U=
05:56:30.880257 run-app controller
05:56:32.199058 wait controller-wait
05:56:33.404172 add-app controller-inception
05:56:33.576374 add-app postgres-app
05:56:33.623741 add-app flannel-app
05:56:33.665363 add-app discoverd-app
05:56:33.713313 scale-app scheduler-scale
05:56:33.726011 run-app scheduler
05:56:34.527645 create-artifact slugbuilder-image
05:56:34.743348 create-artifact slugrunner-image
05:56:34.752770 create-artifact redis-image
05:56:34.761788 deploy-app redis

**Comment by randy-girard** [comment]
I am also having this issue.

**Comment by signsi** [comment]
Me too.

**Comment by randy-girard** [comment]
I rebuilt the cluster 🤷‍♂️

**Comment by randy-girard** [comment]
I had this happen again. I got farther running the fix in http://github.com/flynn/flynn/issues/4334 

https://gist.github.com/lmars/cfb46fe104d1c17be8f22acf41c907e9

But now I am stuck on 
```
14:57:53.604517 deploy-app router
15:02:55.798277 deploy-app router error: timed out waiting for scale to complete (waited 300 seconds)
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
