### ISSUE TITLE
loving flynn...s3 failure 

### ISSUE THREAD

**Issue by parrolabs** [flynn/flynn#4452]
Hey Flynners ,

Been working in flynn for about a week! loving it. Though when runnning this: 

`flynn -a blobstore env set BACKEND_S3MAIN="backend=s3 region=us-east-1 \
bucket=flynnblobstore access_key_id=$AWS_ACCESS_KEY_ID \
secret_access_key=$AWS_SECRET_ACCESS_KEY"

flynn -a blobstore env set DEFAULT_BACKEND=s3main`

There seems to be an issue as we get this: `web job failed to start: got down job event` Any idea what that can be?

**Comment by parrolabs** [comment]
This is what the log says `2018-10-16T20:41:21.944068Z app[web.ip172313833-f6678631-c60b-4d84-8faa-180c9cf02c2f]: 2018/10/16 20:41:21 blobstore: missing S3 bucket param for s3main`

but when I try to add it, I get this `web job failed to start: got down job event`

**Comment by lmars** [comment]
@parrolabs does `flynn -a blobstore env` show `BACKEND_S3MAIN` with the value you expect? Also, did you change `flynnblobstore` to the name of your own bucket?

**Comment by parrolabs** [comment]
Is working already. I was just a little too creative with the "". It needs to be exactly as the instructions say.
