### ISSUE TITLE
Pushing Node.js repo failed: Exited with status 6

### ISSUE THREAD

**Issue by wizcas** [flynn/flynn#4458]
I'm new to flynn and trying to deploy my Node.js repo. It failed with a exit status 6.

I searched google and issues, finding nothing about this exit code. There is no detailed errors with git push outputs. Any idea what causes this? Or where can I get detailed logs? (I've tried to look up `flynn-host.log` but seems there's nothing really useful...)

Here's the git output:

```
$ git push flynn master
Counting objects: 247, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (144/144), done.
Writing objects: 100% (247/247), 52.91 KiB | 2.52 MiB/s, done.
Total 247 (delta 127), reused 158 (delta 100)
-----> Building apis...
-----> Node.js app detected
remote: ERROR: Build failed: exec: job exited with status 6
```

**Comment by philiplb** [comment]
Anything interesting with `flynn log -i`? Like out of memory of the build container?

**Comment by wizcas** [comment]
@philiplb thanks for the reply! I don't have a chance trying that now, but just realized that my server can't access internet anymore after bootstrapping Flynn! And there is certainly no way to download dependencies with npm. 

Any idea what can I do with it? I'm not quite familiar with server network configurations...

**Comment by wizcas** [comment]
@philiplb The log outputs nothing...

**Comment by crawfordleeds** [comment]
Looks like an issue with your firewall. I had the same issue (with a Python app), removed the firewall all together, and it worked. Still trying to figure out the proper firewall config.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
