### ISSUE TITLE
Can't push a PHP on simple Vagrant cluster

### ISSUE THREAD

**Issue by guestisp** [flynn/flynn#4481]
I'm getting this:
```
$ git push flynn master
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 8 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (12/12), 1.33 KiB | 1.33 MiB/s, done.
Total 12 (delta 4), reused 0 (delta 0)
-----> Building alligators-convince-southwold...
-----> PHP app detected
-----> Bootstrapping...
       
       !     ERROR: Failed to download minimal PHP for bootstrapping.
       Please try again, or contact support if this problem persists.
       
remote: ERROR: Build failed: exec: job exited with status 1
To https://git.demo.localflynn.com/alligators-convince-southwold.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.demo.localflynn.com/alligators-convince-southwold.git'
```

when trying to push to a simple vagrant test cluster.

This is the composer.json:
```
{
    "require": {
	"php": "^7.0.0"    
    }
}
```

Any idea ?

**Comment by HangingClowns** [comment]
Had something similar, yesterday. `flynn env set BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-php.git`, then push again. Should be alright. Also, you should include the `composer.lock` file, too.

**Comment by guestisp** [comment]
Yes, that solved the issue.
But is flynn still an actively developed project ? I have seen tons of issue pending from years and, after 2 years, no progress on user auth........

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
