### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by drobnikj** [flynn/flynn#4482]
I'm migrating from dokku to flynn.
I was able to reproduce all features, which I have in dokku set up except monorepo support.
I used https://gitlab.com/notpushkin/dokku-monorepo.

Is it possible to use something similar for flynn?

I just need to deploy 3 apps from one git repository.

**Comment by mattbillenstein** [comment]
Think you want multi-buildpacks?  From a project where I have a python app and a react app:

```
$ cat .buildpacks
https://github.com/heroku/heroku-buildpack-nodejs
https://github.com/heroku/heroku-buildpack-python
```

package.json and requirements.txt both in the root of the repo..

**Comment by bgschiller** [comment]
@drobnikj I suspect you can accomplish this using `git subtree`. Check out https://stackoverflow.com/a/5977494/1586229, or google "git subtree heroku" for more examples.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
