### ISSUE TITLE
Heroku Like Sleep

### ISSUE THREAD

**Issue by linchpinstudios** [flynn/flynn#4484]
We're running a lot of sites on our Flynn cluster. Most of which are actually just for portfolio pieces that don't get a lot of traffic.

Is there a way that we can sleep the processes until a request is made? or maybe set the process to 0 and when the route gets a request it shows a "starting process" page and then scales back up to 1?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
