### ISSUE TITLE
Scale up flynn cloud? Any other support distro?

### ISSUE THREAD

**Issue by chengjk84** [flynn/flynn#4486]
can i start flynn cluster with just single flynn node on DigitalOcean, then add more nodes in future? if can, please share some idea and guide on how to do it...

can flynn be installed on other distro other then ubuntu?

**Comment by bbaptist** [comment]
If you are going to do a multi-node Flynn cluster you have to start with at least 3 nodes. Adding nodes is as simple as doing a `flynn-host init --discovery` with the discovery token and then starting the `flynn-host` daemon.

The only supported OS is Ubuntu right now.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
