### ISSUE TITLE
could not restore from host persistence db: error loading container state: EOF

### ISSUE THREAD

**Issue by joeczucha** [flynn/flynn#4487]
One of my nodes has just died after being stable for a month. 

Having restarted it, I'm getting the following error:

    t=2018-12-11T01:53:30+0100 lvl=info msg="restoring state" app=host pid=5173 fn=runDaemon host.id=flynn02
    t=2018-12-11T01:53:31+0100 lvl=eror msg="error restoring state" app=host pid=5173 fn=runDaemon host.id=flynn02 err="could not restore from host persistence db: error loading container state: EOF"

Is there anything obvious I should check or should I collect logs and send over? Thanks

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
