### ISSUE TITLE
my mistake and error

### ISSUE THREAD

**Issue by andespo** [flynn/flynn#4488]
Hi folks, 
I had two shells open and I was wrong to do the demote on a single flynn node, I tried to block the demote but I did not have time

_root@flynn-01:/etc/flynn# flynn -a discoverd env get DISCOVERD_PEERS
172.X.X.84:1111,
root@flynn-01:/etc/flynn# flynn-host demote --force 172.X.X.84:1111
2018/12/13 17:28:54 Attempting to gracefully demote peer.

[1]+  Stopped                 flynn-host demote --force 172.X.X.84:1111
root@flynn-01:/etc/flynn# 
root@flynn-01:/etc/flynn# 
root@flynn-01:/etc/flynn# 
root@flynn-01:/etc/flynn# flynn -a discoverd env get DISCOVERD_PEERS  
GET https://controller.flynn.domain.local/apps/discoverd/release: httpclient: raw req: unexpected status 503_

if I try to do the promote I get the following error

_root@flynn-01:/etc/flynn# flynn-host promote 172.X.X.84:1111     
17:36:18.152010 host.go:166: Post http://172.X.X.84:1111/raft/promote: net/http: request canceled (Client.Timeout exceeded while awaiting headers)_

How can I fix it? 
Thanks in advance 
A.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
