### ISSUE TITLE
flynn create example freezing

### ISSUE THREAD

**Issue by ronalddas** [flynn/flynn#4491]
I am running flynn on a single node in gcloud, can acess dashboard. After adding the cluster in my local machine and following the flynn basics instructions. After cloning the go example and when I type in flynn create example , nothing happens. The other commands like flynn cluster and all seems to be working. Any idea why this is happening?

**Comment by HangingClowns** [comment]
something you want to happen? i just did the same on my machine about a min ago, didn't get a reply, but if you check `git remote -v` you'll see there's a new remote called `flynn` in the repo. then you can just push the code and it should work.

**Comment by ronalddas** [comment]
No, I only have the origin in the git remotes. 
`ronald@ronald-XPS-13-9360:~/WORK/StartUp/misc/go-flynn-example$ flynn create example


^Cronald@ronald-XPS-13-9360:~/WORK/StartUp/misc/go-flynn-example$ 
ronald@ronald-XPS-13-9360:~/WORK/StartUp/misc/go-flynn-example$ git remote -v
origin	https://github.com/flynn-examples/go-flynn-example (fetch)
origin	https://github.com/flynn-examples/go-flynn-example (push)
ronald@ronald-XPS-13-9360:~/WORK/StartUp/misc/go-flynn-example$ 
`

**Comment by HangingClowns** [comment]
You can try `flynn -a example remote add flynn`. That should add the remote called `flynn` to the repo.

**Comment by ronalddas** [comment]
I hadn't configured the firewall properly. Once I did that [,](https://www.philiplb.de/flynn/2016/04/19/flynn-ufw/) the flynn create command started working fine
