### ISSUE TITLE
Can't initialize cluster due to 500 error on discovery.flynn.io

### ISSUE THREAD

**Issue by tamiswa** [flynn/flynn#4493]
I am trying to create a cluster but the `sudo flynn-host init --init-discovery` command is failing with the following error:

`12:51:46.471026 host.go:166: POST https://discovery.flynn.io/clusters: unexpected status 500`

Seems like something is wrong with the server?

**Comment by lmars** [comment]
@tamiswa this is fixed now, thanks for reporting.

**Comment by tamiswa** [comment]
It worked. Thanks!
