### ISSUE TITLE
Update Flynn to Latest

### ISSUE THREAD

**Issue by HangingClowns** [flynn/flynn#4494]
Just wanted to be sure and keep record, but when you install flynn, you're always on release:
```
v20170719.0-81418bc
```

Is there plans to cut a new stable build? Should I be on unstable?

**Comment by jbrady42** [comment]
Unfortunately the Flynn team decided to stop the stable releases a little over a year ago. You can install the latest by specifying the nightly channel to the flynn installer.


It is recommended that you test and pin a version you know works well, as there is no guarantee with nightly.

**Comment by parrolabs** [comment]
Is Flynn no longer officially maintained? I mean is it going to be outphased? I guess everybody is going to be moving to Kubernetes and Docker eventually...I mean that is the future...loving Flynn though

**Comment by HangingClowns** [comment]
That's not good. :( @jbrady42 do you have a version you recommend? How to "pin" to a version?

@lmars is there a version that you can recommend for people to use?

**Comment by lmars** [comment]
I run many production applications using Flynn and it works really well with little to no maintenance. If I ever do encounter issues or notice others have spotted bugs then I contribute fixes, but I typically just deploy my applications safe in the knowledge that Flynn will run them as expected.

As for versions, I personally use the nightly version by installing with:

```
$ curl -fsSL -o install-flynn https://dl.flynn.io/install-flynn
$ sudo bash install-flynn --channel nightly
```

I also sometimes use my Let's Encrypt dev build:

https://github.com/flynn/flynn/issues/1995#issuecomment-366395394

**Comment by HangingClowns** [comment]
Thanks for the reply. Is there a way to update to the dev branch or your branch? Or I would need to spin up new servers? Cause I already have running services.

**Comment by lmars** [comment]
I suggest doing a backup and restore to a new cluster:

https://flynn.io/docs/production#updating

**Comment by lmars** [comment]
If you can handle downtime, you can take a backup, re-install Flynn on the current servers with `install-flynn --clean` (which stops all services and re-installs from a clean slate), then bootstrap from the backup.

**Comment by jbrady42** [comment]
@HangingClowns 
We use `v20180516.0` in prod, but are currently evaluating the latest nightly `v20190108.0` in testing. You can specify the version with chanel to the installer.

Flynn does not handle in-place updates or OS changes very well so doing a backup and restore to a new cluster is standard practice. If you plan on running long term, have an automated install from a known version and restore from a backup file.

**Comment by hadifarnoud** [comment]
although Flynn is not actively maintained, I still think the simplicity of running a Flynn cluster can justify working on this old tech. We are moving to kubernetes too but will keep our existing Flynn cluster.

We do run into issues sometimes but most of the times it's not critical issue. fixing some weird bugs and lack of letsencrypt support will make it perfect for small projects.

I hope others start contributing more to Flynn and send more PR.

**Comment by parrolabs** [comment]
I think it would be great to maintain it. Maybe we at Parrolabs can contribute. Seems that the team at flynn still works as they are answering questions. For example @titanous is always there to help

**Comment by hadifarnoud** [comment]
this is weird. I get a different version in dashboard's `/status` 

status says version is `v20180905.dev2-2d93aa3` but flynn-host says `v20190108.0-aa5424a`

**Comment by HangingClowns** [comment]
thanks @lmars i just updated to nightly and it was quite "painless" to do a restore from backup. Although took me some time to figure out I needed to turn on the services on all hosts, but after I did, they managed to find each other and the sites seem to be up and working :)
