### ISSUE TITLE
Remote Add Creates Weird URL

### ISSUE THREAD

**Issue by parrolabs** [flynn/flynn#4495]
I am trying to add the flynn remote via this command

`flynn -c production -a bcback remote add flynn`

Created remote flynn with url https://git.https://controller.cluster.parrolabs.com/bcback.git.

As you can see there is like `https://git.` appended to the URL. Is that a bug that needs some working on?

**Comment by lmars** [comment]
That is indeed a bug, I've pushed a fix in #4496.

For now, you should just manually fix `GitURL` in your `~/.flynnrc` file and then try re-adding the git remote.

**Comment by lmars** [comment]
P.S. the `GitURL` in your `~/.flynnrc` should be `https://git.cluster.parrolabs.com`.
