### ISSUE TITLE
Redirecting /api gives an error

### ISSUE THREAD

**Issue by parrolabs** [flynn/flynn#4498]
Hey There,

Loving Flynn, but having some CORS issue. Therefore I setup the backend to be going to:

www.myopainseminars.com/api
but now it is showing scanning....

It does show the domain in the routes for the backend 
`https:www.myopainseminars.com            myopainback-web  <id>  false   false   /api/`

The issue is if we set it up with api.myopainseminars.com we get some CORS related issues (on some browsers)

Thoughts?

**Comment by lmars** [comment]
What are the CORS issues you were having? Were you setting the appropriate CORS headers in the API response?

**Comment by parrolabs** [comment]
The CORS seem to be working, but still the /api is not working. We had another issue, which is that we needed to use an NPM plugin for forcing SSL. CORS is no longer the issue, but /api would be great to have. Same with /blog for example.

**Comment by titanous** [comment]
Check the requests that are going to your server, it's possible you aren't handling the `/api` path in the implementation and are instead looking for `/`. The router doesn't rewrite requests, so the path is passed through unmodified even for routes with path prefixes.

**Comment by parrolabs** [comment]
That is great help. I will have a look into that @titanous

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
