### ISSUE TITLE
tuf: failed to decode timestamp.json

### ISSUE THREAD

**Issue by brkkyk** [flynn/flynn#4499]
I'm getting this error when i try to install flynn host.
`EROR[01-10|11:30:42] error updating TUF client                err="tuf: failed to decode timestamp.json: expired at 2019-01-10 06:00:02 +0000 UTC"
11:30:42.818968 host.go:167: tuf: failed to decode timestamp.json: expired at 2019-01-10 06:00:02 +0000 UTC
===> 11:30:42.826 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 1`

It's not working with both stable and nightly builds.

Thanks.

**Comment by lmars** [comment]
This should be fixed now.
