### ISSUE TITLE
Only one node in cluster seems to work

### ISSUE THREAD

**Issue by parrolabs** [flynn/flynn#4501]
We have a 3 Node cluster ,but when checking the Statistics of those nodes in the EC2 portal, I happen to notice that only one of those 3 has a CPU that goes up and down (see: https://cl.ly/0f95f66a397d). Like sometimes it hits 60%, but none of the other nodes do anything it seems. 

In the console you can see that the cluster comprises of these 3 nodes. I am wondering how this works and what can be done to more load-balance this.

**Comment by bbaptist** [comment]
Do you have an application that is scaled to '3' and running on all the nodes? Is this application primarily limited by databases access? What you are possibly seeing is that the node showing CPU activity is the one running the Flynn database application.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
