### ISSUE TITLE
docker troubles (rabbitmq)

### ISSUE THREAD

**Issue by ruiisidro** [flynn/flynn#4505]
Dear all,  I'm following the dosc (https://flynn.io/docs/docker) with some sucess, but struggling to grasp a few details and letting my rabbitmq install unavailable. 

I'm doing 
```
flynn docker set-push-url
flynn docker login

flynn create --remote "" rabbitmq
flynn -a rabbitmq docker push rabbitmq:3-management
flynn -a rabbitmq scale app=1

flynn -a rabbitmq run curl http://rabbitmq-web.discoverd:8080

//not prety sure wht to do here but...
flynn -a rabbitmq run curl http://rabbitmq-web.discoverd:15672
flynn -a rabbitmq run curl http://rabbitmq-web.discoverd:8080

//alway get "The handle is invalid."
```

I've done changes in UFW in the server to try to open ports 15672 and 8080 with no effect. 

My logs can read...

> 
> [2019-01-28T12:16:35.138736Z]      ##  ##
> [2019-01-28T12:16:35.138828Z]      ##  ##      RabbitMQ 3.7.8. Copyright (C) 2007-2018 Pivotal Software, Inc.
> [2019-01-28T12:16:35.138868Z]      ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
> [2019-01-28T12:16:35.138973Z]      ######  ##
> [2019-01-28T12:16:35.139005Z]      ##########  Logs: <stdout>
> [2019-01-28T12:16:35.139143Z]                  Starting broker...
> [2019-01-28T12:16:35.166421Z]    2019-01-28 12:16:35.166 [info] <0.198.0> 
> [2019-01-28T12:16:35.166551Z]     node           : rabbit@e32ab3b0-3426-48db-8b32-c0500b9225c0
> [2019-01-28T12:16:35.166746Z]     home dir       : /var/lib/rabbitmq
> [2019-01-28T12:16:35.166764Z]     config file(s) : /etc/rabbitmq/rabbitmq.conf
> [2019-01-28T12:16:35.166875Z]     cookie hash    : XoksDEMn+jmz5U/BzWyxgw==
> [2019-01-28T12:16:35.166891Z]     log(s)         : <stdout>
> [2019-01-28T12:16:35.166977Z]     database dir   : /var/lib/rabbitmq/mnesia/rabbit@e32ab3b0-3426-48db-8b32-c0500b9225c0
> ...

> [2019-01-28T12:16:40.118399Z]    2019-01-28 12:16:40.118 [info] <0.5.0> Server startup complete; 3 plugins started.
> [2019-01-28T12:16:40.118518Z]     * rabbitmq_management
> [2019-01-28T12:16:40.118717Z]     * rabbitmq_web_dispatch
> [2019-01-28T12:16:40.118756Z]     * rabbitmq_management_agent
> [2019-01-28T12:16:40.119208Z]     completed with 3 plugins.

I'm sure I'm missing something simple can you give me some advice?

**Comment by titanous** [comment]
I think this might be a bug in `flynn run` on Windows. Please try on Linux or macOS.

**Comment by ruiisidro** [comment]
I've tried to delete all images and start over with a macOS machine, still no success :(

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
