### ISSUE TITLE
How to re-bootstrap new cluster

### ISSUE THREAD

**Issue by ghost** [flynn/flynn#4508]
So... like a complete moron, I wasn't paying enough attention when I ran the bootstrap command, and I added the wrong cluster URL. I haven't been able to figure out how to re-bootstrap since the flynn command isn't setup yet... only the flynn-host command (I have a bare-metal setup with 3 nodes).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
