### ISSUE TITLE
Unable to push image from docker private repository

### ISSUE THREAD

**Issue by vchavkov** [flynn/flynn#4509]
I am following docker push instructions https://flynn.io/docs/docker but I am not able to make a release by following them.

I have setup a private docker registry with valid certificate.

I have setup private registry url by 'flynn docker set-push-url'

I am able to login by 'flynn docker login' and I am able to push images.

but always I receive timeout on artifact creation.

vchavkov@vchavkov-lx-lt:~/git/nodejs-flynn-example$ flynn -a "test" docker push test:1.1
flynn: getting image config with "docker inspect -f {{ json .Config }} test:1.1"
flynn: tagging Docker image with "docker tag test:1.1 a.assistance.bg:5000/test:latest"
flynn: pushing Docker image with "docker push a.assistance.bg:5000/test:latest"
The push refers to repository [a.assistance.bg:5000/test]
2e2e4b033dce: Layer already exists 
90ca4514d160: Layer already exists 
9d4655a54c18: Layer already exists 
640deb45d63e: Layer already exists 
767f936afb51: Layer already exists 
latest: digest: sha256:b8d5866b9246c97643807e34faa3cb5a75491e189aaf9f6f4c8239c2402a31e0 size: 1363
flynn: image pushed, waiting for artifact creation
timed out waiting for artifact creation

This 4 nodes setup and there is enough RAM and CPU on each node.

I am testing with sample nodejs app https://github.com/flynn-examples/nodejs-flynn-example.git

**Comment by SalvoLunar** [comment]
Hi there,

I'm having a similar issue, I'm unable to push new images on the cluster, I get this error:

`error parsing HTTP 404 response body: invalid character 'N' looking for beginning of value: "Not Found\n"`

and when I try to login i get this error:

```
flynn -c fcdprod docker login
error running `docker login`: exit status 1 - output: {"WARNING! Using --password via the CLI is insecure. Use --password-stdin.\nError response from daemon: login attempt to http://docker.cluster.test.com/v2/ failed with status: 404 Not Found\n" '\x00' '\x00' "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"}
```

**Comment by lmars** [comment]
@SalvoLunar update your Flynn CLI (i.e. run `flynn update`) and then try just running `flynn docker push <image>`.

**Comment by SalvoLunar** [comment]
Thanks @lmars, i've ran the update and that worked.

Just to note though that I had also to remove and re-run the cli-add-command in order to be able to push the image on the cluster, before doing that i was getting this error:
`cluster: missing ImageURL .flynnrc config
`

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
