### ISSUE TITLE
Flynn-host fix not working

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4511]
Hi there,

My cluster suddenly stopped working today after months without an issue.

I think the problem was related to disk space issue because when I ran the garbage collector loads of volumes got deleted.

I've restarted the server and restarted flynn 

I even tried [this](https://gist.github.com/lmars/cfb46fe104d1c17be8f22acf41c907e9) 
to clean the jobs

if I run flynn-host ps on any of the nodes I can see that some of the services are started but nothing else:
`
scwd443af-53db1e59-0ebb-4133-b84e-3ab7c6383322  running   3 minutes ago   postgres        postgres         
scwc3ae39-3eb3604f-0f31-44a5-8a41-f3b565ef74ce  running   3 minutes ago   postgres        postgres         
scwd443af-b7f79ff1-05b0-432d-bcfc-9311037c3777  running   41 minutes ago  flannel         app              
scwd443af-19d74500-825c-40bc-bc88-0be425b7c602  running   41 minutes ago  discoverd       app              
scwc3ae39-9812c852-6909-4c13-bc92-60f999839ffd  running   41 minutes ago  flannel         app              
scwc3ae39-bc95f9d2-1e96-45d8-a665-536b8c8aebbd  running   41 minutes ago  discoverd       app              
scw610bdf-e0d83a95-8579-4a02-8e56-437c315bb5be  running   41 minutes ago  discoverd       app              
scw610bdf-ce678c73-68b2-4700-971f-98a953251f0f  running   41 minutes ago  flannel         app              
scwd443af-d7a4851c-63bc-47b9-9a2b-d59935c6f5af  starting  47 minutes ago  flannel         app              
scw610bdf-b1fe9a76-a0a9-45ca-bedb-d25b8aa413f8  starting  14 hours ago    controller      web  
`

So I tried to run the fix command and this is what I get:
`
root@scw-610bdf:~# sudo flynn-host fix --min-hosts=3 --peer-ips=10.21.56.3,10.21.229.139,10.20.255.143
INFO[03-06|14:15:43] found expected hosts                     n=3
INFO[03-06|14:15:43] ensuring discoverd is running on all hosts 
INFO[03-06|14:15:44] checking flannel 
INFO[03-06|14:15:44] flannel looks good 
INFO[03-06|14:15:44] waiting for discoverd to be available 
INFO[03-06|14:15:44] checking for running controller API 
INFO[03-06|14:15:44] checking status of sirenia databases 
INFO[03-06|14:15:44] checking for database state              db=postgres
INFO[03-06|14:15:44] checking sirenia cluster status          fn=CheckSirenia service=postgres
INFO[03-06|14:15:44] no running leader                        fn=CheckSirenia service=postgres
INFO[03-06|14:15:44] found running instances                  fn=CheckSirenia service=postgres count=2
INFO[03-06|14:15:44] getting sirenia status                   fn=CheckSirenia service=postgres
INFO[03-06|14:15:44] killing any running schedulers to prevent interference 
INFO[03-06|14:15:44] getting service metadata                 fn=FixSirenia service=postgres
INFO[03-06|14:15:44] getting primary job info                 fn=FixSirenia service=postgres job.id=scwc3ae39-891b06ab-f99c-4858-a91c-4d13f6ca5cc3
INFO[03-06|14:15:45] getting sync job info                    fn=FixSirenia service=postgres job.id=scwd443af-7a6034e8-f176-40fd-aeaa-a81a7fb5b25a
INFO[03-06|14:15:45] terminating unassigned sirenia instances fn=FixSirenia service=postgres
INFO[03-06|14:15:45] starting primary job                     fn=FixSirenia service=postgres job.id=scwc3ae39-c231e6b9-b127-4d8c-b438-faa96b6785cc
INFO[03-06|14:15:45] starting sync job                        fn=FixSirenia service=postgres job.id=scwd443af-c40d4036-beaa-46db-9c20-977009ff5915
INFO[03-06|14:15:45] waiting for instance to start            fn=FixSirenia service=postgres job.id=scwc3ae39-c231e6b9-b127-4d8c-b438-faa96b6785cc
INFO[03-06|14:15:46] waiting for cluster to come up read-write fn=FixSirenia service=postgres addr=100.100.8.13:5432
14:21:07.307132 host.go:167: timeout waiting for expected status
`
I even tried to allow all traffic on port 5432 but it doesn't seem to produce any results

Do you have any suggestions on how to fix this issue?

Thanks,
Salvo

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
