### ISSUE TITLE
Any news about ipv6 router ?

### ISSUE THREAD

**Issue by simonfr** [flynn/flynn#4513]
Hello,

Today I try to install flynn on ipv6 only host. It works but flfynn router only listen on TCP4. 

Does this feature will be implemented soon ? Or I've forgot to add any parameter ?

Thanks

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
