### ISSUE TITLE
Error when deploying app

### ISSUE THREAD

**Issue by brkkyk** [flynn/flynn#4514]
Hello,

I just encountered with an error. It exited deploying process at the end of it. It gives me this error:
`remote: ERROR: Build failed: exec: job exited with status 22
`

I couldn't find any information related to status code 22.
Thanks

**Comment by bin4ryio** [comment]
Did you manage to find out where to debug these build job error? Official docs aren't that helpful on these.

**Comment by brkkyk** [comment]
@bin4ryio actually what i think about current state of Flynn project is UNSTABLE. actively looking for more stable alternative. I'm commenting like this because we're long time user of Flynn and it's complete mess. Don't recommend you to use Flynn at all. Please also let me notice if you find more stable PaaS alternative.

**Comment by bin4ryio** [comment]
OK noted. I should stick with Dokku til then. Appreciate ur input mate

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
