### ISSUE TITLE
error updating TUF client

### ISSUE THREAD

**Issue by dvlro** [flynn/flynn#4516]
16:12:32.952040 host.go:167: tuf: failed to decode timestamp.json: expired at 2019-03-27 12:00:03 +0000 UTC
===> 16:12:32.954 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 1

Can someone help me with this? Thank you!

**Comment by titanous** [comment]
Fixed, thanks for letting us know!
