### ISSUE TITLE
 tuf: failed to decode timestamp.json: expired at 2019-04-09 06:00:03 +0000 UTC

### ISSUE THREAD

**Issue by roquie** [flynn/flynn#4518]
Pls fix it.

EROR[04-09|09:47:18] error updating TUF client                err="tuf: failed to decode timestamp.json: expired at 2019-04-09 06:00:03 +0000 UTC"
09:47:18.606523 host.go:167: tuf: failed to decode timestamp.json: expired at 2019-04-09 06:00:03 +0000 UTC
===> 09:47:18.612 ERROR: failed to run "./flynn-host download --repository https://dl.flynn.io/tuf --tuf-db /etc/flynn/tuf.db --config-dir /etc/flynn --bin-dir /usr/local/bin", exit status 1

**Comment by roquie** [comment]
https://github.com/flynn/flynn/issues/4516

https://github.com/flynn/flynn/issues/4286

https://github.com/flynn/flynn/issues/4186

https://github.com/flynn/flynn/issues/3408

**Comment by titanous** [comment]
Fixed.

**Comment by roquie** [comment]
thx
