### ISSUE TITLE
Is the docker controller gone?

### ISSUE THREAD

**Issue by SalvoLunar** [flynn/flynn#4521]
Yesterday I updated flynn on one of my clusters and now I'm not able to push any docker images onto it anymore.

it seems that the docker controller is not there anymore.

in fact when I visit docker.cluster.mydomain.com/v2 I get a not found error.
The controller is not appearing in the dashboard either.

Was it removed?

**Comment by lmars** [comment]
It was removed and replaced with a simpler service that just receives tarballs from the CLI exported from the Docker daemon (see https://github.com/flynn/flynn/pull/4367).

There is no longer a need to run `flynn docker login` or `flynn docker set-push-url`, just running `flynn docker push <image>` is enough to deploy a Docker image.

We need to update the docs, though.
