### ISSUE TITLE
Flynn postgres pgadmin

### ISSUE THREAD

**Issue by augnustin** [flynn/flynn#4522]
Anyone here has been configuring pgadmin to being able to access its postgres flynn ressource?

I understand I need to set up an [external access](https://flynn.io/docs/databases/postgres#external-access).

But then what can I do with the TCP route: `tcp/58e39f3e-32f6-134f-b6a9-d6572e07374d listening on port 3163` ?

I know how to setup ssh tunneling, but I have never dealt with those kind of routes.

Thanks

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
