### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by voidberg** [flynn/flynn#4523]
Hi,

Is there a way of attaching a persistent volume to an app that stays the same between releases? I'm looking at hosting a Drupal website and while it has integrations with S3 and various other providers, some parts of the application always use a file system for uploaded files making it tricky.

I've been following the steps in #4329 and that worked to some extent, but from my tests, when deploying a new release, a new set of empty volumes is attached to the new release.

Is there's a way of keeping the same volumes when doing new releases or is there a better way of doing this?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
