### ISSUE TITLE
Blobstore remote access

### ISSUE THREAD

**Issue by voidberg** [flynn/flynn#4524]
Hi,

I am trying to write a plugin for the Craft CMS to use the blobstore as a backend for assets. 

The only way of accessing it that I've found requires the code being in the app container, which makes developing a pain. Is there a way I can access the blobstore for a particular app remotely, from my local machine?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
