### ISSUE TITLE
pg dump with pg_dump options

### ISSUE THREAD

**Issue by augnustin** [flynn/flynn#4525]
I have been struggling a lot importing the `flynn pg dump -f latest.dump` output into my local postgres instance.

```
$ pg_restore --clean --no-acl --no-owner -d mydb latest.dump
```
is not entirely correct, since it generates errors at first run and needs to be run twice to properly run without any error/warning.

From my investigations, the solution would be to run : 

```
$ pg_dump  --clean --no-acl --no-owner latest.dump
```

and then 

```
$ pg_restore -d mydb latest.dump
```

would run out-of-the-box. 

I understand keeping the DB name by default is useful so that `flynn dump` and `flynn restore` work symmetrically, but it would help being able to forward `pg_dump` options to `flynn pg dump`.

Cheers

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
