### ISSUE TITLE
Router crashes on upgrading a cluster from v20170719.0 to v20190425.0 via backup/restore if it has dependent routes

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4526]
Hi,

I'm currently in the process of upgrading our clusters from v20170719.0 to v20190425.0 via backup/restore. I ran into the following problem:
I have some applications having a staging environment and a production environment. They have routes like this:

- production: https://foo.bar
- staging: https://foo.bar/staging

If I try to restore the v20170719.0 backup with a v20190425.0 cluster, it gets stuck on

> status-check status

And the router crashes, gets started again, crashes, rinse and repeat. This is the log of one attempt:

> t=2019-05-17T15:24:56+0000 lvl=info msg="starting the job" component=containerinit args="[/bin/flynn-router -http-port 80 -https-port 443 -tcp-range-start 3000 -tcp-range-end 3500]"
> t=2019-05-17T15:24:56+0000 lvl=info msg="connecting to postgres" fn=main
> t=2019-05-17T15:24:56+0000 lvl=info msg="running DB migrations" fn=main
> 15:24:56.908783 server.go:207: ERROR: default route for ... has dependent routes (SQLSTATE P0001)
> t=2019-05-17T15:24:56+0000 lvl=info msg="job exited" component=containerinit status=1
> t=2019-05-17T15:24:56+0000 lvl=info msg=exiting component=containerinit
> t=2019-05-17T15:24:56+0000 lvl=info msg="received signal" component=containerinit type="child exited"

My current workaround would be to change those routes to not be dependent of each others but this would produce some work on other places for the clients.

Are there any other solutions to this problem?

**Comment by philiplb** [comment]
So the upgrade of our production cluster was done yesterday:
As a workaround here, I exported the apps with depending routes and deleted them. Afterwards, I upgraded the cluster via backup/restore and in the end, I imported the apps again.
Today, I tested whether I can restore a backup of the cluster including those apps and this works just fine.
But I would still think of this as a bug because v20170719.0 is still the default stable version of Flynn.

**Comment by pouledodue** [comment]
is flynn still maintained?

**Comment by neil-wwt** [comment]
@pouledodue I created a issue to ask that exact same thing: https://github.com/flynn/flynn/issues/4527

**Comment by Padrio** [comment]
> is flynn still maintained?

It's more like being held alive. The line between dead and maintained here is incredible. But wouldn't suggest to use Flynn in a serious productive environment.

**Comment by pouledodue** [comment]
@Padrio what would you use in a serious prod environment besides managed solutions?
I tried Rancher, DC/OS and they were quite not ready for prod use too despite promising the world and being developed for years

**Comment by Padrio** [comment]
Thats something im searching for myself. But when you don't have a complex microservice architecture the good old bare-metal/vps with some provisioning using puppet/chef/ansible seems like a good way. 

It always depends on what your needs are. Especially your software architecture and how painful downtimes are.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
