### ISSUE TITLE
Is Flynn still maintained?

### ISSUE THREAD

**Issue by neil-wwt** [flynn/flynn#4527]
I would love to use and contribute to this project, but it looks to me to be unmaintained. Is that true?

Here is what I found:

The read me says 
> Flynn is very actively developed by Prime Directive, Inc. and the Flynn community.
https://github.com/flynn/flynn

In Sep 2017 @titanous said 
> We still have a full-time team working on Flynn, and are financially stable (and growing!). As I mentioned in the issue referenced above, our focus is on our paying customers since they are what allow us to continue building Flynn. 
https://github.com/flynn/flynn/issues/4244

But... 

No new commits since 2018...

No new releases since 2017...
https://releases.flynn.io/

No blog posts since 2017...
https://flynn.io/blog

No twitter activity since 2016...
https://twitter.com/flynnscale

It seems like this is not longer being maintained and I can't find any info on "Prime Directive, Inc" 

I would love to use and contribute to this project. It is exactly what I need... but I need to see some signs of life first.

Is anyone out there?

**Comment by neil-wwt** [comment]
This is a duplicate of https://github.com/flynn/flynn/issues/4271 but I think the answer may have changed.

**Comment by pouledodue** [comment]
> It is exactly what I need...

there are alternatives

**Comment by neil-wwt** [comment]
> there are alternatives
@pouledodue please, do share!

**Comment by pouledodue** [comment]
caprover

**Comment by laughinghan** [comment]
CapRover doesn't have the same level of high-availability, its main node is a single-point-of-failure:

https://github.com/caprover/caprover/issues/162
https://github.com/caprover/caprover/issues/197

Whereas, from what I understand (I have used neither), none of the nodes in a Flynn cluster are a SPoF, because they elect a leader with Raft.

**Comment by hadifarnoud** [comment]
they say it is maintained but I see no sign of life either. It's sad.

Flynn is super easy to use but it never got the attention it deserved from the community. I think it still has a place in this market despite k8s growth. founders believe otherwise.

it would be nice to be honest with us and explain the current situation clearly. people like us invested in Flynn and are worried about its support and development in the future

**Comment by laughinghan** [comment]
In all fairness to the creators of Flynn, what market? You're not a paying customer of Flynn, are you? Nor would you have been a paying customer of Kubernetes, right?

The creators of Flynn don't owe us anything. The onus is on us to contribute maintenance work or financially. I for one would almost immediately pay $20/node/month for a cluster that they ran on my VPSes (e.g. DigitalOcean droplets that I pay for separately; _not_ included in the $20). Even at $50/node/month I would consider it as I scaled up (thought I would start by running it on my own); there's no perfect apples-to-apples comparison with Heroku, but I think that would be comparable.

The $9,000/month listed on their pricing page, especially without taking into account cluster size, is obviously not something I could afford until I've scaled up _a lot_. I agree that it is disappointing that they don't feel like a funnel from the open source project is worth continuing to invest in.

**Comment by ahelord** [comment]
@titanous  Could you confirm that you no longer have maintenance?

**Comment by titanous** [comment]
Flynn is still developed actively. We use it in production extensively and have a variety of projects in progress (take a look at the branch activity to see some of them). The nightly release channel is the correct channel to use, and we will be removing the stable channel soon.

**Comment by neil-wwt** [comment]
@titanous Would you mind sharing a link to the nightly releases?

I see a Apr 24 2019 release here: https://github.com/flynn/flynn/releases
But that seems to be from year old (Apr 15 2018) code: https://github.com/flynn/flynn/commit/b4b05fce92da5fbc53b272362d87b994b88a3869 

I see that there is some activity on a few topic branches: https://github.com/flynn/flynn/branches But I would expect those changes to be incorporated back to mainline/master on a regular basis. I think of updates to mainline (as well as frequent releases) as the indicator of an active software project.

I _want_ to use Flynn (and would love to be a paying customer) but first I need to see some signs of life. Would you mind sharing some links or more info?

**Comment by titanous** [comment]
That commit was originally written in 2018 but was merged recently (look at the commit log and corresponding pull request). Nightly channel is here: https://releases.flynn.io/#ch-nightly

And yes, of course the branches will be merged when they are ready, I was just providing some pointers to what we're currently working on.

**Comment by ahelord** [comment]
@titanous  if you need resources you could do the same thing that the parse server community did
https://opencollective.com/parse-server

this product seems to me a change in the rules of the game,
since products like Heroku are very expensive and startups that try to get products very fast are bankrupt.

Continue is a very important project.

**Comment by hadifarnoud** [comment]
@titanous It would be helpful to keep stable release channel and just merge the nightly build you know for a fact (since you're using it on production a lot) is stable.

that will give us the confidence to update.

**Comment by bbaptist** [comment]
> That commit was originally written in 2018 but was merged recently (look at the commit log and corresponding pull request). Nightly channel is here: https://releases.flynn.io/#ch-nightly
> 
> And yes, of course the branches will be merged when they are ready, I was just providing some pointers to what we're currently working on.

https://releases.flynn.io is a 404 error page.

**Comment by neil-wwt** [comment]
@bbaptist works for me... :/

**Comment by bbaptist** [comment]
I don't see how, I get a Google hosted 404 error page.

**Comment by bbaptist** [comment]
Huh, serious DNS caching errors, it shows up now.

**Comment by Padrio** [comment]
@neil-wwt When you're searching for a self-hosted highly available PaaS service checkout https://github.com/rancher/rio 
Rancher is actively developing their products and technically rio is a PaaS which can be hosted on a Kubernetes Cluster.

**Comment by pouledodue** [comment]
@Padrio do you think it is reliable? Last time I installed their [main product](https://github.com/rancher/rancher) about 6 months ago it was not reliable
