### ISSUE TITLE
Add http route to process other than `web`

### ISSUE THREAD

**Issue by behzadsh** [flynn/flynn#4528]
I have two processes, one for http API running on `web` process and other for gRPC running on `grpc-web`.

I'm not sure if I understand it right, but it seems like since pull request #2002, every process that ends with `-web` could have separate http routes.

I add a route for process `grpc-web` but I get `Service Unavailable` or `"error": "2 UNKNOWN: Stream removed"` when calling gRPC endpoint.
Here is my routes list:

```
ROUTE                          SERVICE        ID                                         STICKY  LEADER  PATH
http:grpc.app.example.com      app-grpc-web   http/44281e3a-61c0-460c-93f6-7ad21d5f85f3  false   false   /
http:app.example.com           app-web        http/dc5b41f0-57cc-4447-a2dd-df17679a0af0  false   false   /
http:app.cluster.example.com   app-web        http/82f672d3-5ce4-4629-b184-01bdb469e090  false   false   /
```

P.S. gRPC server listens on port `8888`, I also added a TCP port on `grpc-web` process but had no luck with running it.

**Comment by bbaptist** [comment]
Pretty sure you want to run the server on the default -web port 8080.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
