### ISSUE TITLE
Log management

### ISSUE THREAD

**Issue by brkkyk** [flynn/flynn#4531]
Hey there,

Currently log management little bit unclear. After using flynn couple of months, dashboard got frozen when we try to access to logs. Is there any improvement on roadmap for log management and dashboard UI?

Thanks for all the hardwork.

@titanous

**Comment by ruiisidro** [comment]
I'm also having a couple of difficulties on this. Also when doing a 

> df -h

I get a big list (I mean a really big list of records) I was not expecting to see. 

Hope someone can provide a few tips on server management using flynn in a real environment. 

Thank you for the great work, for my use case this is awesome, event with a few hiccups...

**Comment by JMSwag** [comment]
I've had good success with [logdna](https://docs.logdna.com/docs/flynn).

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
