### ISSUE TITLE
Installation of v20190715.0 fails on aws Ubuntu 18.04

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4535]
Hi,
I just tried out to install a cluster with v20190715.0 on aws Ubuntu 18.04 (ami-009c174642dba28e4) and the installer failed with this message:

> E: Package 'ntp' has no installation candidate
null_resource.flynnlayer0[0] (remote-exec): ===> 14:56:53.010 ERROR: failed to run "apt-get install --yes iptables zfsutils-linux ntp", exit status 100

Here is the complete log of the installer:

> ===> 14:56:52.327 *** WARNING ***
> ===> 14:56:52.329 About to stop Flynn and remove all existing data
> ===> 14:56:52.330 stopping flynn-host daemon
> Failed to stop flynn-host.service: Unit flynn-host.service not loaded.
> Failed to disable unit: Unit file flynn-host.service does not exist.
> ===> 14:56:52.341 killing old containers
> No .containerinit found running; none killed.
> ===> 14:56:52.364 destroying ZFS volumes
> /tmp/install-flynn: line 279: zpool: command not found
> ===> 14:56:52.369 removing Flynn files and directories
> ===> 14:56:52.371 running "rm -rf /usr/local/bin/flynn* /var/lib/flynn /etc/flynn /etc/init/flynn-host.conf /lib/systemd/system/flynn-host.service"
> ===> 14:56:52.373 Flynn successfully removed
> ===> 14:56:52.375 installing runtime dependencies
> ===> 14:56:52.376 running "apt-get install --yes iptables zfsutils-linux ntp"
> Reading package lists... 0%
> Reading package lists... 0%
> Reading package lists... 0%
> Reading package lists... 27%
> Reading package lists... 27%
> Reading package lists... 41%
> Reading package lists... 41%
> Reading package lists... 41%
> Reading package lists... 41%
> Reading package lists... 41%
> Reading package lists... 41%
> Reading package lists... 61%
> Reading package lists... 61%
> Reading package lists... 74%
> Reading package lists... 74%
> Reading package lists... 74%
> Reading package lists... 74%
> Reading package lists... 74%
> Reading package lists... 74%
> Reading package lists... 88%
> Reading package lists... 88%
> Reading package lists... 97%
> Reading package lists... 97%
> Reading package lists... 97%
> Reading package lists... 97%
> Reading package lists... 97%
> Reading package lists... 97%
> Reading package lists... Done
> Building dependency tree... 0%
> Building dependency tree... 0%
> Building dependency tree... 50%
> Building dependency tree... 50%
> Building dependency tree
> Reading state information... 0%
> Reading state information... 0%
> Reading state information... Done
> Package ntp is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> E: Package 'ntp' has no installation candidate
> ===> 14:56:53.010 ERROR: failed to run "apt-get install --yes iptables zfsutils-linux ntp", exit status 100
> null_resource.flynnlayer0[0]: Still creating... [50s elapsed]
> sudo: flynn-host: command not found
> Failed to start flynn-host.service: Unit flynn-host.service not found.

**Comment by philiplb** [comment]
I think the line

> /tmp/install-flynn: line 279: zpool: command not found

is also notable.

**Comment by titanous** [comment]
Hmm, can you try running `apt-get update` before the install script?

The `zpool` error is a red herring due to the use of `--clean`.

**Comment by philiplb** [comment]
That did the trick, thanks.
But now it hangs on
> 15:50:17.816982 restore-postgres restore
The backup I'm restoring is really small. I once setup an empty cluster with the same domain and took it from there right after the installation, no apps deployed.
I attached the debug information.
[restore-debug-information.tar.zip](https://github.com/flynn/flynn/files/3411828/restore-debug-information.tar.zip)
(had to zip it because GitHub didn't let me upload the tar)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
