### ISSUE TITLE
Collected Debug Information can't be uploaded as Gist

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4539]
Hi,
I just collected some debug information and it failed to create a Gist:

> INFO[07-19|16:03:12] getting system information
INFO[07-19|16:03:12] creating anonymous gist
259.87 KB / 259.87 KB [==============================================================================================================================================================================================================================================================================================================================] 100.00 % 1.27 MB/s 0sEROR[07-19|16:03:13] unexpected HTTP status: 401
259.87 KB / 259.87 KB [============================================================================================================================================================================================================================================================================================================================] 100.00 % 281.90 KB/s 0s
16:03:13.069149 host.go:167: unexpected HTTP status: 401

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
