### ISSUE TITLE
Custom 404 Not Found HTML page

### ISSUE THREAD

**Issue by ruiisidro** [flynn/flynn#4540]
Dear all, 

I need to provide a custom 404 page in my flynn cluster. I'm working on a directory service that will provide a page for each customer as a subdomain of my flynn cluster.  
Suppose I have 10 subpages currently such as: 
http://example1,mydomain.com
http://example2,mydomain.com
...
http://example10,mydomain.com

So If someone try to access a non existing sub-page - let's say http://example21,mydomain.com - currently flynn answers with a blank page and the message "Not Found". I need it to be a bit more customized to please my designers team!

Where / how can we change the 404 page for the cluster? 

I did manage to redirect to a custom 404 by setting up the nginx of each container (http://example10,mydomain.com/nonexistingpage.html is redirected to a custom 404 in that container), but I don't know where/how to setup the generic 404 of the cluster it self.

**Comment by philiplb** [comment]
Hi,

Flynn answers with a 503 when you hit a non existing route as no application exists for it.

The first option I see: you can actually customize this page with this undocumented feature: https://github.com/flynn/flynn/pull/4368

But this is still an HTTP 503, not your desired HTTP 404. The second option I see here is to deploy an application just answering with an HTTP 404 and your desired HTML body at any path/domain. For this application you then setup a wildcard route like *.mydomain.com so the Flynn router falls back to this one if the request can't be fullfilled with the other routes.

**Comment by ruiisidro** [comment]
Thanks! This is a great suggestion and fixes a lot of this use case. Already implemented it. 
In each project container there's a custom 404 (each container is a micro-site). For all the other cases the * route works fine.

By the way the project is this: https://www.andaver.me/en/. It's still under hard development but already functional. Any  comment is deeply grateful
