### ISSUE TITLE
flynn pg restore from file not restoring installed extensions. Also same for flynn import --file

### ISSUE THREAD

**Issue by jasonrubenstein** [flynn/flynn#4552]
Results while importing an app whose database has extensions installed: 
```
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 262; 1259 31619 TABLE activity ff9fe19ae07b53dc09dc1a4422ae8ef5
pg_restore: [archiver (db)] could not execute query: ERROR:  function public.gen_random_uuid() does not exist
```

- Repro: 
- Create a flynn app, 
-  In the app's database run `CREATE EXTENSION IF NOT EXISTS pgcrypto;` and `CREATE EXTENSION if not exists pg_trgm;` 
- Create some data in the database.   
- Run `flynn -c mycluster -a myapp export --file myapp.tar`
- Run `flynn -c mycluster -a myapp pg dump -f myapp.dump`
- Run `flynn -c mycluster -a myapp import --file myapp.tar` (optionally, `--name myapp2`)

and the database in the app won't restore, as the db expects the extensions to be installed. In our case it's looking for `gen_random_uuid()` from `pgcrypto`.

I can get around this manually by restoring the app, then installing the extensions manually, and then running `flynn -c mycluster -a myapp pg restore -f myapp.dump`

But, is it possible for the import command to be aware of pg extensions and install as required before restoring the database? 

(_update_) It is possible that this `-n public` in the `pg_restore`  (in file cli/pg.go) will only restore objects that are in the named schema ("public"), and like it's sibling option in pg_dump, does not include any extensions.  

(_update 2_)
confirmed.  But by adding this prior to the pg_restore, it will restore extensions.  
```
pg_restore -l myapp.dump | grep -i extension > exts.list
pg_restore  --clean --create --no-acl --no-owner -d postgres -L exts.list myapp.dump
pg_restore  --clean --if-exists --no-acl --no-owner -n "public" -d postgres myapp.dump
```
works, though needs a thorough test.

**Comment by mattbillenstein** [comment]
Workaround - putting the extensions you need in the template1 db will create them in any new database prior to the import...

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
