### ISSUE TITLE
Timed out waiting to scale

### ISSUE THREAD

**Issue by troykelly** [flynn/flynn#4555]
Similar to #4497 but we are listening to the port on startup.

Getting the below after deploy, once web service has started listening on `PORT` (in this case 8080) - but for some reason deploy isn't noticing it.
```
ERROR: timed out waiting for scale to complete
```

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
