### ISSUE TITLE
Dashboard: ephemeral certificate is invalid in MacOS Catalina (10.15) & iOS 13

### ISSUE THREAD

**Issue by troykelly** [flynn/flynn#4559]
Apple now enforces its requirements for trusted certificates: [Requirements for trusted certificates in iOS 13 and macOS 10.15](https://support.apple.com/en-us/HT210176)

As such macOS users are unable to access the Flynn Dashboard with a "Your connection is not private" error in Chrome, or untrusted certificate in Safari.

For example: NET::ERR_CERT_REVOKED
<img width="613" alt="Screen Shot 2019-10-18 at 10 24 45 am" src="https://user-images.githubusercontent.com/4564803/67054863-a8706180-f191-11e9-82cf-778e2a09c9c5.png">

**Comment by philiplb** [comment]
So it's really time for the LetsEncrypt automation which was promised a long time ago.

**Comment by troykelly** [comment]
Oh, I thought Flynn was abandoned.
I was just putting this here so people would not spend a day working out what was going wrong given the error is quite deceptive.

**Comment by jsenin** [comment]
> Oh, I thought Flynn was abandoned.
> I was just putting this here so people would not spend a day working out what was going wrong given the error is quite deceptive.

So, Flynn is dead? do you know any other alternative ?

**Comment by pouledodue** [comment]
the trend seems to point to [Knative](https://knative.dev/docs/serving/samples/hello-world/)

**Comment by troykelly** [comment]
> the trend seems to point to [Knative](https://knative.dev/docs/serving/samples/hello-world/)

I don't think their site works?
Try https://cloud.google.com/knative/

**Comment by raj457036** [comment]
is flynn still active or not?

**Comment by troykelly** [comment]
@raj457036 It is not

**Comment by raj457036** [comment]
Is there any similar tool which is easy to use? I don't want to use the scary kubernets at all...

**Comment by troykelly** [comment]
Have you looked at https://www.cloudfoundry.org/

**Comment by randy-girard** [comment]
Flynn is still active. I use a fairly recent version of it. Also I had this issue, and fixed it, but I can't quite recall the solution. I am trying to locate so that I can add it here for others.
