### ISSUE TITLE
Restored production cluster: Applications won't come up

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4571]
Hi,
I just had to restore our production cluster from backup. It seems to be okay except no deployed application actually comes up.

The version is v20190425.0.

flynn-host ps -a shows this for each application:

> ip....  failed   28 minutes ago      ...                               web              error getting squashfs layer from https://dl.flynn.io/tuf?target=/layers/....squashfs: verify: data too short

And if I want to redeploy an application, all I get is this:

> remote: ERROR: Error getting slugbuilder image: json: cannot unmarshal array into Go value of type types.Artifact To https://git..../....git

I really need some urgent help here if possible. :(

**Comment by titanous** [comment]
Have you tried a (much) more recent version? Have you tried re-deploying the cluster? It seems like something is wrong with the base images that get downloaded by the installer.

**Comment by philiplb** [comment]
Thank you so much for the response!
I'm trying v20191217.0 now, will have a result in about 15min.

**Comment by philiplb** [comment]
@titanous 
This worked well and everything is back online.
Thank you again so much for the ultra fast response on a christmas night which is really extraordinary!
