### ISSUE TITLE
Flynn dashboard does not get past /installcert screen

### ISSUE THREAD

**Issue by janniks** [flynn/flynn#4572]
## Issue

Flynn dashboard does not get past `/installcert` screen

## Reproduce

Prerequisites:
- Clean DigitalOcean Ubuntu 16.04 x64 droplet
- Clean flynn install (latest version)

Steps:
- Visit dashboard, redirect to `/installcert`
- Install cert on login keychain, mark always trust

Result:
- **Actual**: Dashboard still redirects to `/installcert` - `All Done` button does nothing
- **Expected**: Open real dashboard, other dashboard tabs should work
---
_Also tried a restart, also tried installing cert to different keychain, also tried Safari, also tried Firefox with own cert manager_

**Comment by janniks** [comment]
Sadly, this makes it very hard for us to switch to Flynn. Is there a latest stable version, or something I'm missing...?

**Comment by jvatic** [comment]
@janniks can you post more details about what browser versions and OS you've tried this on? Also, are there any errors in the developer console in the browser?

**Comment by janniks** [comment]
@jvatic good tip!

- macOS 10.14.6
- Firefox 71.0 (64-bit)
- Chrome 79.0.3945.88 (Official Build) (64-bit)

Chrome console:
```
dashboard-b00c9e9075ecf57fd8aeb8f831e9ba0a.js:16367 Uncaught (in promise) Error: HTTPS certificate is not trusted.
```

Firefox console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://controller.flynn.janniks.com/ping. (Reason: CORS request did not succeed).
Error: HTTPS certificate is not trusted.
```

I have checked the system keychain and the Firefox built-in certificate manager. The Flynn certificate shows up and is marked as trusted in both...

**Comment by janniks** [comment]
_Trying a restart again now..._

**Comment by jvatic** [comment]
Hmm... Can you confirm the version of Flynn that's installed?

**Comment by janniks** [comment]
using `flynn --version` results in `v20170719.0-81418bc`

**Comment by jvatic** [comment]
@janniks That's likely the issue, you're using a very old version of Flynn. You'll want the nightly channel to get the current version.

**Comment by janniks** [comment]
Thanks @jvatic - this might be worth noting in the docs. How stable is the nightly build?

**Comment by s-kris** [comment]
Having same issue. (Similar server)
I tried installing latest nightly but still can't past the /installcert page.
Tried on chrome, firefox and restarting browsers, macbook, server and reinstalling flynn too.
Any suggestions will be helpful.
Thanks!
