### ISSUE TITLE
Install `devDependencies` as buildpacks now prune them

### ISSUE THREAD

**Issue by pareeohnos** [flynn/flynn#4576]
I've been running into an issue trying to get an app deployed which was caused by flynn not installing `devDependencies` of my project. Unfortunately, some of these are required to be able to build the app so I've had to set `YARN_PRODUCTION=false` which causes them to install. Later in the deployment however, the `purge` step runs to remove all of the dev dependencies, however it is skipped when `YARN_PRODUCTION` is not true, so they're not removed.

The current behaviour of heroku is to actually install the `devDependencies` by default (https://devcenter.heroku.com/changelog-items/1376), and rely on them being purged later. Since the buildpacks appear to have this purge step included, flynn should automatically be installing `devDependencies` as well.

I'm unsure where the issue lies here though, as I assume the buildpack is responsible for installing the dependencies so I'm not sure why it has the pruning step but isn't installing all of the dependencies?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
