### ISSUE TITLE
Gitreceive will always upload the repo regardless deploy failure 

### ISSUE THREAD

**Issue by j105** [flynn/flynn#4587]
https://github.com/flynn/flynn/blob/master/gitreceive/server.go#L123

Mentioned issue will cause git repo in error status and return

remote: fatal: bad object HEAD

Steps to reproduce

- A success deployment ##version 1
- Rebase or amend repo to a state of not aligned with existing state stored in flynn ##version2
- Deploy the change with force push and try to fail above deployment 
- Try to push ##version 1
- Fail

cmd.Wait() is not getting any error when deployment failed in pre-receive

Temp fix will have to ```git checkout --force master``` before every upload to blobstore or with a proper fix which handles the deployment failures.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
