### ISSUE TITLE
Invalid Route when creating route via cli

### ISSUE THREAD

**Issue by rlangfordBV** [flynn/flynn#4589]
Hello,

This command, which looks correct according to the help output will not work for me.

```
$ flynn -c my-cluster \
        -a my-app \
        route add http \
        -s my-app-web \
        -p 50443 \
        -c /tmp/star-com/star-com.crt \
        -k /tmp/star-com/star-com.key myurl.mycompany.com
validation_error: Invalid route  
```

I have checked that my cert is valid, and I have added the complete chain in the `.crt` file

Where can I find out why this has gone awry?

**Comment by lmars** [comment]
@rlangfordBV it's the `-p 50443` that is causing you issues, Flynn currently only supports creating HTTP routes on the default router ports (typically 80 and 443), and so any value for `-p` currently leads to an invalid route.

What was your intention with that flag? Do you actually want the router to be listening on the externally facing port `50443`?

**Comment by rlangfordBV** [comment]
Yes, we do.  We have a public load balancer for making flynn apps open to the public internet.  This ELB expects to be able to talk to the flynn router on `50080` and `50443`.

The reasoning for this is not known to me, it's one of those "it was this way when I found it" things.

**Comment by lmars** [comment]
@rlangfordBV ah ok, so I broke this in https://github.com/flynn/flynn/pull/4569, sorry about that.

So if this is causing you issues in production I suggest pinning to a version from before I made that change (e.g. `v20191231.0`, let me know if you need help with that), and I'll try to ship a fix in the next week or so.

**Comment by rlangfordBV** [comment]
@lmars,

Cool, I can do that. I'll knock it out tomorrow.

Thanks!

**Comment by rlangfordBV** [comment]
Can I restore a cluster backup from a newer version to that older version?  It seems like the postgres databases could potentially have issues with that

**Comment by rlangfordBV** [comment]
@lmars,

Unfortunately, I don't think using an old version will work in our case as our cluster backups are based on the latest version of flynn, and have the database changes as well.  I've tried to spin up a half a dozen clusters to no avail.

**Comment by rlangfordBV** [comment]
Ok, I migated the app to k8s. ¯\_(ツ)_/¯

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
