### ISSUE TITLE
How to "reset" the MongoDB to it's initial state?

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4590]
Hi,

as far as I can remember, initially the MongoDB-service is not activated/running in Flynn and greyed out on the health page.
As we don't use the MongoDB, I would like to deactivate it to save some resources. And it is failing every few weeks, so that disturbs our monitoring.

How could I do that?

**Comment by philiplb** [comment]
Meanwhile, this broken (and unused) MongoDB caused our cluster backup to fail. I "fixed" it via

```bash
flynn -a mongodb scale mongodb=0 web=0
flynn -a mongodb scale mongodb=3 web=2
```

Yet it would be far nicer to just deactivate this MongoDB. :)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
