### ISSUE TITLE
ERROR: /app/.heroku/python/bin/pip: No such file or directory

### ISSUE THREAD

**Issue by scratchmex** [flynn/flynn#4594]
I'm cloning the Heroku Python getting started (https://github.com/heroku/python-getting-started) and don't work, this is the console error:

```console
❯ git push flynn master
Logon failed, use ctrl+c to cancel basic credential prompt.
Counting objects: 460, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (206/206), done.
Writing objects: 100% (460/460), 79.41 KiB | 9.93 MiB/s, done.
Total 460 (delta 226), reused 460 (delta 226)
-----> Building py-getting...
-----> Python app detected
-----> Installing python-3.7.6
-----> Installing pip
-----> Installing requirements with pip
       /builder/buildpacks/000006_heroku-buildpack-python/bin/steps/pip-install: line 7: /app/.heroku/python/bin/pip: No such file or directory
remote: ERROR: Build failed: exec: job exited with status 1
```

**Comment by JMSwag** [comment]
@scratchmex What version of Flynn are you using? Are you using the build in buildpacks? If so, trying adding the latest python buildpack using a .buildpacks file.

**Comment by scratchmex** [comment]
Latest version. What do you mean by buildpack build? How do I add a .buildpacks file?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
