### ISSUE TITLE
Calls to `recover` that have no effect

### ISSUE THREAD

**Issue by owen-mc** [flynn/flynn#4595]
I was testing a static analysis tool for go programs by running it on `flynn/flynn`. It highlighted that the calls to `recover` in `ExitWithCode`, `Fatal` and `Fatalf` in `/pkg/shutdown/handler.go` don't do anything. The reason is that calls to `recover` only have an effect if they are in a function that has been deferred [1], but `ExitWithCode`, `Fatal` and `Fatalf` aren't ever deferred. I'm not sure why `exit` wasn't also highlighted - either it is deferred somewhere, or it isn't called at all (or the tool isn't working correctly).

[1] "Recover is only useful inside deferred functions." https://blog.golang.org/defer-panic-and-recover

**Comment by lmars** [comment]
@owen-mc they may well be there in error, what do you propose?

**Comment by owen-mc** [comment]
I'd delete the lines ```
	if serious != nil {
		panic(serious)
	}
```
in `exit` as the condition can never evaluate to true, and then get rid of the argument `serious`.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
