### ISSUE TITLE
Problem installing: failed to decode timestamp.json: expired at <insert time here>

### ISSUE THREAD

**Issue by matiasturunen** [flynn/flynn#4596]
I got an error while installing flynn via installation script available at flynn.io. Precise error text is `tuf: failed to decode timestamp.json: expired at 2020-05-21 12:00:03 +0000 UTC`
This seems to have happened at least twice before, and apparently there is a known fix for this. Previous issues: #4286 #4499

**Comment by titanous** [comment]
Sorry about that! Looks like the monitoring broke, fixing it now. Should be working in a few minutes.
