### ISSUE TITLE
465 issue? Anybody running on production?

### ISSUE THREAD

**Issue by fastengineer** [flynn/flynn#4598]
I tried installing 2 times and failed 2 times. Bootstrapping not success.

There are many issues here. Is it suitable for production?

**Comment by hadifarnoud** [comment]
we migrated to kuberenetes a few days ago. not much support and development over here

**Comment by fastengineer** [comment]
I am sorry to see beautiful inactive projects. Kube is overkill for most projects. But there isn't alternative so much.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.

**Comment by hadifarnoud** [comment]
sorry @fastengineer I missed your message. did not find any email on your github account

contact me via hadi.farnoud [at.] gmail.com

**Comment by fastengineer** [comment]
> Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.

okey not bad, can we direct the developer team and the community to an active project? I have a candidate https://github.com/teamhephy/workflow
