### ISSUE TITLE
Flynn should have a Gitter chat similar to Tsuru

### ISSUE THREAD

**Issue by cyberquarks** [flynn/flynn#4605]
Similar to Tsuru https://gitter.im/tsuru/tsuru 
Flynn should also have a Gitter chat room so developers/users of Flynn can help each other as a community

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
