### ISSUE TITLE
Missing install guide for single machine or virtual machine instance

### ISSUE THREAD

**Issue by questionaut** [flynn/flynn#4606]
The best way to run Flynn on a development environment is described here: https://flynn.io/docs/installation/vagrant
However there's a "missing manual" on how to bootstrap Flynn on a single machine or virtual machine, for example running on Hyper-V or VMWare or bare-metal Linux server (non-clustered configuration) is missing. 

The "Bootstrap Flynn" section in this manual https://flynn.io/docs/installation/manual does not seem to apply to Single machine instance (bare-metal or virtual machine)

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
