### ISSUE TITLE
Is the dashboard coming back?

### ISSUE THREAD

**Issue by kipparker** [flynn/flynn#4612]
I notice the web dashboard has been removed recently, are there any plans to bring it back? I can see there was a lot of work on a dashboard v2.0, but the PR was closed, is that still planned to be released at some point?

**Comment by rlangfordBV** [comment]
Yeah, we're pinning the Flynn clusters we still have to the March version because this change without a replacement was dumb.

**Comment by hadifarnoud** [comment]
don't use flynn in production. it is not maintained anymore

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
