### ISSUE TITLE
Flynn creating zombie processes impossible to close

### ISSUE THREAD

**Issue by SlimBN** [flynn/flynn#4616]
Well to be honest lost a lot of time trying to solve the problems and am not looking in to it, just looking on how to completely delete Flynn from my machine and never hear of it again.

P.S : sudo bash /tmp/install-flynn --remove command is not working 👎 freezes when trying to delete the volume data

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
