### ISSUE TITLE
Dashboard Certificate Installation  Screen Persists after Adding and Trusting Certificate

### ISSUE THREAD

**Issue by innomadic** [flynn/flynn#4617]
I am trying to set up Flynn for the first time, and upon first loading the dashboard, I saw this screen:

`Install CA certificate to continue`.

I followed the instructions to install and trust the certificate, but each time I load the screen, I am directed back to this screen -- if I click on any of the menu options (backup, status, providers, etc.) it only shows this certificate screen.

I also noticed that the Certificate instructions do not completely load in Firefox, but they do load in Google Chrome.  

So, ultimately, I cannot use the dashboard.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
