### ISSUE TITLE
Ubuntu 20.04 Support

### ISSUE THREAD

**Issue by johncadengo** [flynn/flynn#4618]
Hi, I couldn't really find anything mentioning this. Is there support for versions of Ubuntu other than 14.04 and 16.04? I'm currently running 20.04, but I couldn't find any mention of 18.04 either.

**Comment by philiplb** [comment]
Actually, Ubuntu 18.04 is supported but we are running into problems updating to it at AWS EC2: https://github.com/flynn/flynn/issues/4535
I will try that again soonish with a newer Flynn version. But if this doesn't work, I don't know what to do as the support of 16.04 will be EOL in April 2021.

**Comment by mohessaid** [comment]
Any news regarding this issue? I am planning on using Flynn in a new server with 20.04, then I saw this.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
