### ISSUE TITLE
Good bye

### ISSUE THREAD

**Issue by philiplb** [flynn/flynn#4621]
Hi,

a warm good bye to Flynn, thank you for all the years of being the core of our infrastructure. And it was quite a good experience, barely any maintenance needed and not many outages. For us, Flynn was really reliable. And if there was an hickup, you were always there for us!

So long and thank you!

Cheers
Philip

**Comment by titanous** [comment]
Thanks for being such a wonderful user and providing great feedback over the years!

**Comment by bjmc** [comment]
I only discovered Flynn by the time it was too late, but it looked like a really promising PaaS option. I wonder if there's any appetite for a community-supported fork? How hard is it to self-host Flynn?

**Comment by WriteCodeEveryday** [comment]
Yeah, this is a major loss to all.

I wasn't even aware it was this close to the end :(

Honestly, I've spent years hosting things using Flynn and very few things were as easy as the cloud installer.

**Comment by sunguroku** [comment]
Hi everyone, I'm the maintainer of [Porter](https://github.com/porter-dev/porter). I just wanted to drop in to tell Flynn users about the project we're working on, which is a next-gen substitute for Flynn that is built on top of Kubernetes. We're at an early stage and have raised a small round of funding from investors including Y Combinator, and we'll be actively working on the project for years to come. Please check out our repo and join our [community](https://discord.gg/MhYNuWwqum) if you have questions about our roadmap, etc.

It's really sad to see Flynn being unmaintained. Thank you to all the maintainers who made this awesome project. Really hope Porter can fill this void and live up to Flynn. We'll be doing our best!

That said,

**Comment by hadifarnoud** [comment]
thank you for such an awesome PaaS. I'm looking forward to what you guys do next with all the knowledge you gained doing Flynn

Good luck

**Comment by onesatorix** [comment]
Hey Folks - We are the developers of [Satorix](https://www.satorix.com/), a fully managed repository, CI/CD pipeline and hosting solution for streamlined application development and hosting. We built Satorix using Flynn and we’re now faced with migrating to K8. 

We really enjoyed Flynn and are sad to see it come to an end. 

If anyone is interested in discussing possibilities, or you find your situation similar to ours, we’d love to talk about collaboration / options. 

Please email flynn@satorix.com and we'll see about arranging a call / group discussion in the next week or so! 

Thank you!

**Comment by leemcd56** [comment]
> Hi everyone, I'm the maintainer of [Porter](https://github.com/porter-dev/porter). I just wanted to drop in to tell Flynn users about the project we're working on, which is a next-gen substitute for Flynn that is built on top of Kubernetes. We're at an early stage and have raised a small round of funding from investors including Y Combinator, and we'll be actively working on the project for years to come. Please check out our repo and join our [community](https://discord.gg/MhYNuWwqum) if you have questions about our roadmap, etc.
> 
> 
> 
> It's really sad to see Flynn being unmaintained. Thank you to all the maintainers who made this awesome project. Really hope Porter can fill this void and live up to Flynn. We'll be doing our best - please give us a try!

I have a question about Porter. Could it be made to work with Docker Swarm? I mentioned your app to a friend of mine and he asked me that. 🙂

**Comment by sunguroku** [comment]
> > Hi everyone, I'm the maintainer of [Porter](https://github.com/porter-dev/porter). I just wanted to drop in to tell Flynn users about the project we're working on, which is a next-gen substitute for Flynn that is built on top of Kubernetes. We're at an early stage and have raised a small round of funding from investors including Y Combinator, and we'll be actively working on the project for years to come. Please check out our repo and join our [community](https://discord.gg/MhYNuWwqum) if you have questions about our roadmap, etc.
> > It's really sad to see Flynn being unmaintained. Thank you to all the maintainers who made this awesome project. Really hope Porter can fill this void and live up to Flynn. We'll be doing our best - please give us a try!
> 
> I have a question about Porter. Could it be made to work with Docker Swarm? I mentioned your app to a friend of mine and he asked me that. 🙂

It's built on top of Kubernetes, and we don't have any plans to support Docker Swarm. However, I'd love to know why you'd prefer Docker swarm over k8s - we made this implementation decision because we deem k8s as the objective winner among all container orchestrators.

**Comment by leemcd56** [comment]
> > > Hi everyone, I'm the maintainer of [Porter](https://github.com/porter-dev/porter). I just wanted to drop in to tell Flynn users about the project we're working on, which is a next-gen substitute for Flynn that is built on top of Kubernetes. We're at an early stage and have raised a small round of funding from investors including Y Combinator, and we'll be actively working on the project for years to come. Please check out our repo and join our [community](https://discord.gg/MhYNuWwqum) if you have questions about our roadmap, etc.
> > > It's really sad to see Flynn being unmaintained. Thank you to all the maintainers who made this awesome project. Really hope Porter can fill this void and live up to Flynn. We'll be doing our best - please give us a try!
> > 
> > 
> > I have a question about Porter. Could it be made to work with Docker Swarm? I mentioned your app to a friend of mine and he asked me that. 🙂
> 
> It's built on top of Kubernetes, and we don't have any plans to support Docker Swarm. However, I'd love to know why you'd prefer Docker swarm over k8s - we made this implementation decision because we deem k8s as the objective winner among all container orchestrators.

I actually prefer Kubernetes myself, but my friend only wanted to know because they prefer Swarm.

**Comment by voarsh2** [comment]
Why is there no self host for Porter?

**Comment by sunguroku** [comment]
> Why is there no self host for Porter?

There are some functionalities (e.g. provisioning resources in your AWS/GCP account) that is difficult to support on the self-hosted control plane. For users looking for a true Heroku-like experience that allows them to deploy with a click of a button, the hosted control plane delivers a better experience.

That said, for users who are willing to expose themselves to devops to some extent, we are making a self-hosted version that is coming very soon! For now, there is a locally runnable instance that you can spin up through our CLI.

**Comment by sarbull** [comment]
bye, i liked flynn
