### ISSUE TITLE
Only web: process types get assigned $PORT and default routing

### ISSUE THREAD

**Issue by diclophis** [flynn/flynn#480]
It would appear that only `web:` process types get assigned a default routed $PORT

https://github.com/flynn/flynn/blob/45d70b5369f0a7068b8d7d5ade3d14ccc92d98ea/receiver/flynn-receive.go#L108

This came as some surprise to to me, I was anticipating that any process type would be assigned a unique $PORT and that I would be able to assign routes to these additional processes.

related to: https://github.com/flynn/flynn/issues/423

**Comment by archSeer** [comment]
#933 will partly address this by making service registration much easier, but how should we address this? It's a fair assumption that a `web` proctype will have a (single) TCP port, but for other services, we cannot be so certain (sure, a single TCP port is the most common configuration, but still).

I'm going to start adressing this after #933 is merged and after I figure out a good way for declaring such things (ports, services and checkers).

**Comment by diclophis** [comment]
It is an interesting problem for sure... I had actually thought heroku assigned $PORT to non-web, but they also have this limitation. One issue I see with this in general is that it might be entirely out of the realm of what flynn is suppose to provide... for example, if the goal is to match heroku in feature parity, and nothing further, then this ticket really is just a sidetrack. But if the goal is to go above and beyond... there is no map for how the feature should work.

I would not be opposed to having to "assign / map" a port to a process-type, but then the question of multiple ports per process raises another problem with the use of ENV variables to pass data between the layers ... do we setup `$PORT1` .... `$PORT2`, or is it a range `$LOWER_PORT` `$UPPER_PORT`.

In the short-short term just having the clause on this line: https://github.com/flynn/flynn/blob/45d70b5369f0a7068b8d7d5ade3d14ccc92d98ea/receiver/flynn-receive.go#L108 re-worked so that it accepted a case switch of multiple types determined via convention, or possibly matched some other ENV like `$PROCESS_WITH_PORTS=web,xmpp,nntp` and you did:

    if Contains(release.Env["PROCESS_WITH_PORTS"], t) {
       // assign $PORT 
    }

**Comment by titanous** [comment]
Resolved by #2002.
