### ISSUE TITLE
Add support for tag to 'release add' and drop support in host

### ISSUE THREAD

**Issue by dhrp** [flynn/flynn#509]
Currently the only way to add a docker image [release](https://flynn.io/docs/cli) is to give both the registry name, and the last image id.

e.g.
```
flynn release add -f config.json https://registry.hub.docker.com/flynn/slugbuilder?id=15d72b7f573b
```

it would be great if this command would also support the ?tag=latest type, that [pinkerton](https://github.com/flynn/flynn/tree/master/pinkerton) seems to support.

e.g.
```
flynn release add -f config.json https://registry.hub.docker.com/debian?tag=latest
```

**Comment by arekkas** [comment]
I'd like to fix this in the host as well, could you point me at a direction?

**Comment by titanous** [comment]
@arekkas https://github.com/flynn/flynn/blob/4ed1a7c57aa2ce9298c431510e8605422c4f4736/host/libvirt_lxc_backend.go#L403-L415

**Comment by arekkas** [comment]
That was quick, thanks I'll take a look :)

**Comment by arekkas** [comment]
@titanous should I simply validate `job.Artifact.URI` validate against `https://registry.hub.docker.com/[^/]+/[^\?]+?id=[a-z0-9]+`?

**Comment by titanous** [comment]
@arekkas No, since we don't force users to use the Docker, Inc. registry. Just check that it's a valid url with `name` and `id` parameters.

**Comment by arekkas** [comment]
Alright, a simple `url.Parse()` should do it then

**Comment by arekkas** [comment]
It might be smart to add tests for this, if you point me at a direction maybe i can figure it out :)

**Comment by lmars** [comment]
I am going to close this as users can now push Docker images directly to Flynn using `flynn docker push REF` (see #2857).
