### ISSUE TITLE
Crash on misconfiguration 

### ISSUE THREAD

**Issue by dhrp** [flynn/flynn#527]
The flynn controller crashes (dramatically) when there is a misconfiguration in the release config.json. I was trying to guess the configuration as I couldn't find any documentation of what/if something should go in here for routing http(s). But that's a separate issue. A fix would be to fail gracefully and write something to the log.

Steps to reproduce the crash:

```
$ cat nginx.conf 
{
    "processes": {
        "nginx": {
            "ports": [{"proto": "http"}]
        }
    }
}
$ flynn create nginx
$ flynn -a nginx release add -f nginx.conf https://registry.hub.docker.com/nginx?tag=latest
Created release cc92e5bed11a429e8ff7b75f25b3225a.
$ flynn -a nginx scale=1
[ crash ] 
```

fault:
panic: runtime error: invalid memory address or nil pointer dereference

output:
https://gist.github.com/anonymous/f3d18ae89b93c02733c8#file-tmp-flynn-host-log-L714

**Comment by titanous** [comment]
This was fixed in #668.
