### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#528]
We are not currently defensive enough with input. All input to the controller, host, router, and discoverd needs to be fully validated before processing (and tests added for bad input).

In addition we should have standard good error messages and status codes that point at the exact field that is incorrect, this is partially mentioned in #322. We also need to ensure that conflicts with existing objects are handled correctly.

**Controller**
- [x] Release
- [x] Formation
- [x] Job
- [x] Resource
- [x] Provider
- [x] Route
- [x] Artifact
- [x] App
- [x] Key

**Router**
- [ ] Route

Host and discoverd should wait until #170 is addressed.

**Comment by heavenlyhash** [comment]
Error messages stand improved now that #749 has landed.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
