### ISSUE TITLE
How to set the dashboard token

### ISSUE THREAD

**Issue by Alienero** [flynn/flynn#554]
I install flynn demo inside vagrant  and run it. But I don't know https://dashboard.demo.localflynn.com/login 's token. In the doc,I can't foud any things about that.

**Comment by geovanisouza92** [comment]
There is a way to include this in docs or login page? I found nothing related to it.

**Comment by lmars** [comment]
@geovanisouza92 I have opened a PR to make the login token more visible to end users: #699

**Comment by geovanisouza92** [comment]
:+1:
