### ISSUE TITLE
deployer: Reduce risk of workers performing the same deployments

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#603]
The queue package provides no guarantees that a job will not be locked by two workers at the same time, but two workers performing the same deployment at the same time is problematic.

A possibly approach is to add a `locked_until` column to `deployments` which is bumped every few seconds by the worker performing the deployment, and any other worker happening to lock the same job checks that `locked_until` is in the past before performing the deployment, returning an appropriate `queue.RetryAfterError` if it's in the future.

Part of #536.

**Comment by archSeer** [comment]
This is no longer needed, as `que-go` takes care of this well enough with advisory locks.
