### ISSUE TITLE
Tup does not track new files

### ISSUE THREAD

**Issue by archSeer** [flynn/flynn#620]
`test_deployer.go` isn't picked up, and `flynn-test` isn't recompiled, so the suite is not ran.

https://s3.amazonaws.com/flynn-ci-logs/20141217042017-5e287fe5-build-313c6b19d4652f63d5e564e6c4955111888812f4-2014-12-17-04-29-30.txt

**Comment by titanous** [comment]
Obsoleted by #3817.
