### ISSUE TITLE
Router request pausing/drainage

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#65]
Request pausing consists of two things:
1. Pausing all requests to a specific backend by continuing to accept new connections but waiting to proxy them until unpaused.
2. A hook to receive a notification when all existing connections have been "drained" from a backend. This hook is also useful for knowing when an old backend can be safely killed during a rolling deploy.

Request pausing is useful to perform database and other maintenance on backends without downtime (instead of returning 50x errors, there is a latency spike).

**References:**
- https://www.braintreepayments.com/braintrust/switching-datacenters
- http://signalvnoise.com/posts/3358-making-application-maintenance-fun
- http://broadcast.marcoborromeo.com/2013/01/pausing-web-traffic-with-haproxy.html
- http://blog.balancedpayments.com/payments-infrastructure-suspending-traffic-zero-downtime-migrations/
- https://github.com/solso/insomnia

**Comment by lmars** [comment]
Router request draining was implemented in #3421, with some enhancements proposed in #3513.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
