### ISSUE TITLE
Robust queuing/buffering/timeout behavior in router

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#67]
See [Heroku's docs](https://devcenter.heroku.com/articles/http-routing#request-queueing) for inspiration.

**Comment by bgentry** [comment]
In my upcoming PR, we've added some timeouts on the TCP side. However, there are not yet any timeouts on the request (corresponding to `http.Client.Timeout`). Just noting that here so we don't forget to add it.

**Comment by bgentry** [comment]
#955 includes a 120 second timeout for receiving headers on responses.

**Comment by titanous** [comment]
Note that the upgraded connection path does not have the same timeout.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
