### ISSUE TITLE
PROXY protocol support in router

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#68]
We should support the [PROXY protocol](http://haproxy.1wt.eu/download/1.5/doc/proxy-protocol.txt) for both sides of TCP connections.

**Comment by blurrcat** [comment]
Hi, do we have a timeline for this?

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
