### ISSUE TITLE
host: Invalid state after network configure error

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#696]
If [configuring the network](https://github.com/flynn/flynn/blob/master/host/manifest.go#L241-L245) fails and flynn-host exits, the state database still contains the etcd & flannel jobs, even though they are not running, which causes subsequent flynn-host daemons to fail trying to connect to non-existent jobs.

This can be reproduced by intentionally making [ConfigureNetworking](https://github.com/flynn/flynn/blob/master/host/libvirt_lxc_backend.go#L207) return an error, and then see that the etcd & flannel jobs remain in the state DB:

```
$ sudo bolt keys /tmp/flynn-host-state.bolt jobs                                  
flynn-etcd-4017f8701a0b42108ddcc3b58b982bb5
flynn-flannel-588ce3b4af7548129a9b721b1109d377
```

A subsequent flynn-host dameon log: https://gist.github.com/lmars/0f36347ea35aa5b77358, note the following error near the top:

```
now=2015-01-05T19:17:46+0000 app=host backend=libvirt-lxc fn=watch_container job.id=flynn-etcd-4017f8701a0b42108ddcc3b58b982bb5 at=connect status=error err="dial unix /tmp/containerinit-rpc.flynn-etcd-4017f8701a0b42108ddcc3b58b982bb5: no such file or directory"
```

**Comment by titanous** [comment]
Closing, the network configuration and bootstrap code has been completely redone.
