### ISSUE TITLE
Delete routes when deleting app

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#709]
Currently, stale routes are retained when deleting an app. This causes issues with duplicate routes, if an app is deleted and recreated.

**Comment by titanous** [comment]
One approach is to do #549 and just use a table in the controller database and then delete in the same transaction as the app delete. This breaks some boundaries but will always work correctly. I haven't though much about other solutions, I'd trade my kingdom for [HAT](http://www.bailis.org/blog/hat-not-cap-introducing-highly-available-transactions/).

**Comment by titanous** [comment]
Fixed by #1533
