### ISSUE TITLE
host: nil panic when flannel fails to start

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#720]
Launched a cluster, accidentally giving it a newline delimited list of peers (instead of comma delimited). Flannel ate its own head: https://gist.github.com/anonymous/d5a6b919690680846948#file-upstart-flynn-host-log-L38

IRC discussion: https://botbot.me/freenode/flynn/2015-01-12/?msg=29341441&page=2

**Comment by titanous** [comment]
This should be fixed by d5f048e8375b6629d4795391bf81941452bca78c.
