### ISSUE TITLE
host: init --peers needs better validation

### ISSUE THREAD

**Issue by temujin9** [flynn/flynn#721]
This is supposed to be a comma-delimited field; there isn't any validation for its input, which causes cryptic errors if the wrong delimiter is used.

See https://botbot.me/freenode/flynn/2015-01-12/?msg=29341441&page=2 for context.

**Comment by temujin9** [comment]
Additionally, a trailing comma passes an empty entry down the stack, resulting in more cryptic errors.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
