### ISSUE TITLE
Controller gone away when deploy a crashed app

### ISSUE THREAD

**Issue by congkhoa** [flynn/flynn#738]
I try deploy https://github.com/fastmonkeys/sentry-on-heroku app through flynn-dashboard and it's built with crashed status.
but after that, I got 503 status from controller.demo.vcflynn.com

>GET http://controller.demo.vcflynn.com:443/apps/sentry/jobs: controller: unexpected status 503

and i can not deploy any app. I try `flynn-host ps -a`:

>root@khoanc-drone:~# flynn-host ps -a

 ID                                |                            STATE  |  STARTED       |     CONTROLLER APP  | CONTROLLER TYPE
------- | --------- | ----------- | ---------- | -----------
khoancdrone-2cf3676713e44300b96e8fe6bc3c7bf5       |           crashed  |  11 minutes ago |     sentry         | web
khoancdrone-3dd2c9a093df413ebc1ec915502ab678     |             crashed |  16 minutes ago  |   sentry |          web                  
khoancdrone-91262cf2b03e426ebdbf28d24b1134de       |           done  |   49 minutes ago   |                  
khoancdrone-3226fb96898540ac9448ea6f990e66b4        |          running |  57 minutes ago    | dashboard    |   web
khoancdrone-5fac355e99f14b40870af59edf2dbe17         |         done    | 59 minutes ago     | dashboard   |    web
khoancdrone-f4f76037d2a647d7848881bf778631f8         |         running  |  59 minutes ago     | |gitreceive    |  app
khoancdrone-53c26ae76a50494a9c9a74f1d650612c                  running | 59 minutes ago   |  router          |app
khoancdrone-df61d098af884aa499bbfd6ba1020002         |         running | 59 minutes ago     | blobstore  |     web
khoancdrone-90382862bd004dad92c4732a786b939c        |          running | 59 minutes ago     controller  |    scheduler
khoancdrone-a9096f6ee9b141fc974e1dd34a9a2679          |        running |  59 minutes ago     controller  |    web
khoancdrone-599263dc43af4a469612d817523927c3        |          running |  59 minutes ago     postgres     |   web
khoancdrone-bd333e26dfa24edbb7947a8985a86913       |           running |  59 minutes ago     postgres   |     postgres
khoancdrone-flynn-discoverd-1d9b4813f422461a983a639a97870971  |  running  | About an hour ago                  
khoancdrone-flynn-flannel-110510a2c5dd4cb5a83d4e2a8ef7ba87  |   running  | About an hour ago                  
khoancdrone-flynn-etcd-c7315b0df1d447a2a6b0f4fd2c416b21   |    running  | About an hour ago                  
khoancdrone-c9057f8528f64f3ba891743201053424        |          running  | 4 hours ago   |     postgres         | postgres

And i try `restart flynn-host` but only *discoverd, flannel, etcd* started and running:

`root@khoanc-drone:~# flynn-host ps -a`
ID                                                            STATE    STARTED        CONTROLLER APP  CONTROLLER TYPE
khoancdrone-flynn-discoverd-4c38893e64c04f2ea53e129934f10dd0  running  3 seconds ago                  
khoancdrone-flynn-flannel-58699fe21c9e40e0a91b86496fa10df9    running  5 seconds ago                  
khoancdrone-flynn-etcd-ef6ebfc471a149d9b396af6e8c099271       running  6 seconds ago 

Here is log file after I restart https://gist.github.com/b04f4f9c880138cc8199

So, must I re-bootstrap my flynn-host?
Can you tell me what i should do if my app crashed?

**Comment by archSeer** [comment]
You need to take a log dump right after the crash and before restarting the system, that way we can get the full application logs (right now, only flynn-host log is complete, but we're missing logs from all of the applications that were running before the restart).

**Comment by archSeer** [comment]
Also, to re-bootstrap flynn itself, just run the bootstrap script again. Restarting `flynn-host` will only restart the host service, and not the entire system.

**Comment by nguyencongkhoa** [comment]
I'm sorry about lately resporse, so here is log after I deploy app:
https://gist.github.com/anonymous/9b8d635db79b795dbe2a
every things seem ok!
but I got 503 from controller
and, here is log after restart:
https://gist.github.com/6ba5e6a46c4ab204253e

**Comment by archSeer** [comment]
Yeah, the log after the restart is broken because you need to run `script/bootstrap-flynn` again to restart it, so we can ignore that.

As for the problem, I can see the router breaking after the deploy: https://gist.githubusercontent.com/anonymous/9b8d635db79b795dbe2a/raw/efa290d9330fd6e2440737e0ba966b32ec69d2c6/router-app-55fd7468ac8043858ec582e89ae43cfa.log

**Comment by archSeer** [comment]
One thing to try, after you deploy your app, you need to set the initial scale: `flynn scale web=1`. That should create the initial formation and start one process.

**Comment by nguyencongkhoa** [comment]
>One thing to try, after you deploy your app, you need to set the initial scale: flynn scale web=1

After deployed, app was `Added default web=1 formation`, but I still try:
` flynn scale web=1` and result:
`requested scale equals current scale, nothing to do!`

Here is log after app deployed:
https://gist.github.com/anonymous/755fb39f31b9c9f0e4c2
This time, I can deploy one more app (python-flynn) before flynn crashed. Seem, Flynn still try to run my crashed app and its gone, too. Here is my `flynn-host ps -a`  https://gist.github.com/nguyencongkhoa/8cf7c717a6e0dd1d404a
Here is log, after it gone: https://gist.github.com/anonymous/d37857406e39452d92a5
I known why my app be crashed, but I want Flynn run correctly without my app crashed or running. How should i do?

**Comment by archSeer** [comment]
Your application is failing because it is not configured properly. This is what happens when it tries to launch:

https://gist.githubusercontent.com/anonymous/755fb39f31b9c9f0e4c2/raw/fe2ea7f2295a8c993061a96b6d7db590f820784e/sentry-web-9adefba2bcea49a8a8f802faa6a34b73.log

**Comment by nguyencongkhoa** [comment]
Yeap!, I know. But, Flynn crashed when my app crashed - this is problem what i want to say

**Comment by titanous** [comment]
We've fixed a ton of bugs since this issue was opened. Please reopen if you run into more trouble.
