### ISSUE TITLE
controller: resource not found

### ISSUE THREAD

**Issue by heavenlyhash** [flynn/flynn#789]
Integration tests sometimes fail in bulk with messages of "controller: resource not found".

The host log contains the following line: "Error creating default route for controller: Post http://router-api/routes: dialer: no services found"

**Comment by titanous** [comment]
> Integration tests sometimes fail in bulk with messages of "controller: resource not found".

I'm 99% sure this is unrelated to that error message, and every cluster will have that message as the first item in the controller log.

**Comment by heavenlyhash** [comment]
Addressed by #794
