### ISSUE TITLE
data race in router

### ISSUE THREAD

**Issue by heavenlyhash** [flynn/flynn#796]
See https://s3.amazonaws.com/flynn-ci-logs/20150124075627-ebb3efd3-build-64abc0bceb3faaa955ad67dbaa93ab54a0e697ae-2015-01-24-07-57-35.txt

**Comment by bgentry** [comment]
ah, yeah, looks pretty clear-cut here. We're setting `Addr` and `TLSAddr` on the `HTTPListener` in `Start()` with no safety:

```go
	s.Addr = s.listener.Addr().String()
```

Should be pretty easy to untangle that.

**Comment by bgentry** [comment]
Should be fixed by #797.
