### ISSUE TITLE
ensure clean state db on clean host shutdown

### ISSUE THREAD

**Issue by warpfork** [flynn/flynn#816]
We should ensure that if you kill flynn-host cleanly, the state file should have no running entries.

Currently backends receive some events asynchronously from the rest of host state change commits.  This isn't a correctness problem, since cleanup proceeds normally on the next host start as if it was an unclean shutdown, but it is silly.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
