### ISSUE TITLE
controller: resource not found

### ISSUE THREAD

**Issue by ArnaudPiroelle** [flynn/flynn#824]
With a fresh install of flynn-host, an expected error occurs when i run command with flynn-cli.

Error message is:
controller: resource not found.

Dashboard works fine, but flynn cli not.

**Comment by titanous** [comment]
This is fixed master, we'll do a release with the fix in a little bit.

**Comment by ArnaudPiroelle** [comment]
Thanks !

A release date is planned?

**Comment by titanous** [comment]
We pushed a release last night.
