### ISSUE TITLE
deployer: Return value for CreateDeployment

### ISSUE THREAD

**Issue by archSeer** [flynn/flynn#845]
Currently `CreateDeployment` returns an empty deployment in the case where we have our first release (since we always transition between two releases, and simply setting the initial formation will basically deploy the release). This was so that from the code, you can call `CreateDeployment`, and it will simply call the SetAppRelease if this was the initial release, or schedule a deployment for any other release -- you do not need to care whether this was an initial deployment or not.

After discussing with @jvatic, it is a bit weird from the API side (since we return `{}` in the first case), so we're considering the alternative of throwing an error, which would then need additional checks in the code:
```
err := client.CreateDeployment(appID, releaseID)
if err != nil && err != InitialRelease { // ignore InitialRelease error
    return err
}
```

**Comment by lmars** [comment]
SGTM

**Comment by archSeer** [comment]
@lmars This is more of a question, which of the two options would be better to use?

**Comment by lmars** [comment]
Oh, +1 for returning the error.
