### ISSUE TITLE
deployer: Wait for discoverd events instead of job events

### ISSUE THREAD

**Issue by archSeer** [flynn/flynn#849]
Waiting for jobs allows us to catch run failures, but we are unable to detect crashes. By waiting for discoverd services to come up, we'd take care of both scenarios.

**Comment by lmars** [comment]
For this to work similar to using job events, certain metadata needs to be present in service discovery (e.g. `appID` & `releaseID`).

This is ok if containerinit is used to do the heartbeating as it can optionally grab those from the environment variables, but then jobs opting to do their own service registration (e.g. [the scheduler](https://github.com/flynn/flynn/blob/master/controller/scheduler/main.go#L51)), also need to register with this metadata, is that acceptable?

**Comment by archSeer** [comment]
Hmm, what about scheduler/deployer tagging the instances? If we can somehow
make it look up the instances and attach metadata, then the only
requirement we have is that all processes register.

**Comment by archSeer** [comment]
Additionally we can tag the service itself, if tagged, then watch for
service discovery events, else watch for job events.

**Comment by lmars** [comment]
@archSeer I opted to automatically add any environment variables starting with `FLYNN_` to service metadata, see #1007
