### ISSUE TITLE
Installation strategy proposal

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#864]
With the soon to be merged changes which modify `flynn-host download` to get the image manifest from the TUF repo (#617), the host and bootstrap manifests shipped with the deb package will become stale and should not be used. To fix this, we should not ship manifests directly to users and instead always consult the TUF repo.

I propose removing the OS specific packaging and just downloading and running an installer script (e.g. `curl -sL https://dl.flynn.io/installer.sh | sudo bash`).

The installer script will do the following:

* Install dependencies (e.g. `apt-get install libvirt-bin`)
* Download the latest `flynn-host` binary (e.g. `https://dl.flynn.io/flynn-host`) and verify it using a checksum embedded in the installer script
* Run `flynn-host download` to download the latest images from the TUF repo
* Save the output of `flynn-host download` (which is the manifest of downloaded images) to a local file

The following changes will then be needed:

* `flynn-host daemon` reads the manifest saved by the installer script to determine the IDs of the images it needs to use
* `flynn-host bootstrap` downloads `bootstrap_manifest.json` from the TUF repo before starting

Please add any thoughts as comments to this issue, I plan to start on this soon.

**Comment by titanous** [comment]
Perhaps `flynn-host download` should handle downloading the bootstrap manifest as well?

**Comment by lmars** [comment]
To minimise the required changes, `flynn-host download` will download both the host and bootstrap manifests, then the daemon and bootstrapping work the same as they do currently.
