### ISSUE TITLE
Add GitHub info to app meta

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#87]
The web dashboard uses a few fields in the app meta to hook up the list of commits and pull requests. Ideally if I deploy an application from the CLI that comes from GitHub, we wouldn't lose those details.

@jvatic what fields are in used by the dashboard?

**Comment by jvatic** [comment]
Note this has now changed somewhat

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
