### ISSUE TITLE
router can't retry request with body

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#872]
After looking at a few intermittent failures on CI ([1](https://s3.amazonaws.com/flynn-ci-logs/20150129052251-0fdd772b-build-d377f3932992bf601169ed11fe4c62063dcf30bb-2015-01-29-05-27-28.txt), [2](https://s3.amazonaws.com/flynn-ci-logs/20150129051901-2b18f75c-build-f990e4871b2ddfde4d0065788f67dbfb998f6e9f-2015-01-29-05-25-08.txt), [3](https://s3.amazonaws.com/flynn-ci-logs/20150129053909-00ef6c24-build-d14b2002006768b2de0368224ab35a1e7c7d7674-2015-01-29-05-43-42.txt)) I noticed a pattern. They are all failing POST requests right after some service instance churn.

It turns out they all have corresponding log lines that look like:

```text
2015/01/29 05:43:28 http: proxy error: http: invalid Read on closed Body
```

After looking at the code a bit, I think I know what is going on:

1. We hit a dial error when trying to contact a backend that just went down ([router code](https://github.com/flynn/flynn/blob/master/router/http.go#L487-L492))
1. As soon as `Transport.RoundTrip` encounters an error it closes `req.Body` (somewhere [around here](https://github.com/golang/go/blob/go1.4.1/src/net/http/transport.go#L220))
1. We try to `RoundTrip` to another backend, but `req.Body.Read` errors because it was closed by the first `RoundTrip` that failed to dial.
1. The request fails with a 503 and logs the above error.

I think we need to wrap the request body so that `Close` is a no-op and then manually close the body after the request is complete. We also need a few tests around this behavior (I don't think we have _any_ tests that make requests with inbound bodies currently).

/cc @benburkert @bgentry

**Comment by bgentry** [comment]
Damn. Thanks for doing the digging on this, I think your analysis is spot on.

At one point I noticed that we were only testing simple `GET` requests and meant to fix that, but forgot about it when I was actually adding tests. Will get some good tests for this first thing in the morning.
