### ISSUE TITLE
router: high CPU usage during/after integration tests

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#892]
I'm seeing 25-40% CPU usage from the `flynn-router` process during and after running the integration test suite. I haven't had time to look into and isolate the issue.

/cc @bgentry @benburkert

**Comment by benburkert** [comment]
I can only reproduce this on a vagrant box, which probably means it's caused by something virtualbox related.

**Comment by titanous** [comment]
Closing for now, will reopen if we see it elsewhere.
