### ISSUE TITLE
router: intermittent TestAddHTTPRoute tls oversized record error

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#893]
I've only seen this once.

```text
----------------------------------------------------------------------
FAIL: http_test.go:112: S.TestAddHTTPRoute

http_test.go:126:
    assertGet(c, "https://"+l.TLSAddr, "example.com", "1")
http_test.go:175:
    c.Assert(err, IsNil)
... value *url.Error = &url.Error{Op:"Get", URL:"https://127.0.0.1:59890", Err:(*errors.errorString)(0xc2080f09e0)} ("Get https://127.0.0.1:59890: tls: oversized record received with length 20527")

2015/01/30 04:08:59 router: proxy error: read tcp 127.0.0.1:60732: connection reset by peer
2015/01/30 04:09:00 router: proxy error: read tcp 127.0.0.1:49394: connection reset by peer
2015/01/30 04:09:01 router: proxy error: router: no backends available
2015/01/30 04:09:01 router: proxy error: router: no backends available
2015/01/30 04:09:01 router: proxy error: router: no backends available
OOPS: 33 passed, 1 FAILED
--- FAIL: Test (6.30s)
```

https://s3.amazonaws.com/flynn-ci-logs/20150130040806-51e23402-build-b1b779ef8442583924a00b28ca806b06d4b382e8-2015-01-30-04-09-13.txt

/cc @benburkert @bgentry

**Comment by archSeer** [comment]
Here's another log for it: https://ci.flynn.io/builds/20150131025847-900c26bd

**Comment by benburkert** [comment]
The `tls: oversized record received with length` error happens when a client starts a TLS handshake with a non-TLS HTTP server. This should reproduce the error:

```go
func (s *S) TestTLSRequestToHTTPServer(c *C) {
       srv := httptest.NewServer(httpTestHandler("http"))
       defer srv.Close()

       l := s.newHTTPListener(c)
       defer l.Close()

       addHTTPRoute(c, l)
       discoverdRegisterHTTP(c, l, srv.Listener.Addr().String())

       // scheme is https, server listener is http
       assertGet(c, "https://"+l.Addr, "example.com", "http")
}
```

As to why this is happening sporadically on CI, I can't say. It seems to indicate that the TLS and non-TLS listen addresses are improperly set somewhere, I don't see any obvious race conditions in the `http.go` code. Perhaps the use of `SO_REUSEPORT` is causing multiple CI processes to listen on the same port?

**Comment by titanous** [comment]
> Perhaps the use of SO_REUSEPORT is allowing multiple CI processes to listen on the same port?

This seems like a likely explanation. Perhaps we should turn that flag off for listeners in the test suite?

**Comment by titanous** [comment]
A quick eyeball of the [relevant kernel code](https://github.com/torvalds/linux/blob/9a3c4145af32125c5ee39c0272662b47307a8323/net/ipv4/inet_connection_sock.c#L45-L239) seems to indicate that a `:0` bind with `SO_REUSEPORT` could end up with multiple listeners on the same port.

**Comment by titanous** [comment]
@benburkert or @bgentry would you please take care of turning off `SO_REUSEPORT` in the tests at some point? (no rush, this failure doesn't seem very common)
