### ISSUE TITLE
CI should clean up network interfaces at start

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#908]
When the CI runner binary starts, it should delete any stale bridges and tap devices to prevent collisions.

**Comment by lmars** [comment]
We should fix this (there were lots of stale devices today after the runner died due to IRC madness), but I currently run the following script:

```bash
for tap in $(ifconfig | grep flynntap | awk '{print $1}'); do
  echo removing $tap
  sudo ip tuntap del mode tap $tap
done

for br in $(ifconfig | grep flynnbr | awk '{print $1}'); do
  echo removing $br
  sudo ip link set $br down
  sudo ip link del $br
done

for br in $(sudo ip link | grep flynnbr | awk '{print $2}' | cut -d : -f 1); do
  echo deleting $br
  sudo brctl delbr
done

echo done
```

/cc @josephglanville

**Comment by josephglanville** [comment]
@lmars I added this script to the CI machine in `/opt/flynn-test` and had it be called by Upstart before booting flynn-test. I also added statements to clean up `/opt/flynn-test/build`.

**Comment by lmars** [comment]
@josephglanville nice, maybe I should've done that :stuck_out_tongue:
