### ISSUE TITLE
CI git test fails with "Permission denied (publickey)"

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#944]
```text
++ 19:25:22.756 /usr/bin/git push flynn master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

https://s3.amazonaws.com/flynn-ci-logs/20150203192348-1db0a2fe-build-c37da7ac6201437c6148f0e63cac13ce62910ee4-2015-02-03-19-29-03.txt

**Comment by jvatic** [comment]
https://s3.amazonaws.com/flynn-ci-logs/20150208202508-6910e734-build-390a1ddda8dfc68c73cce2ebec3291baad906ed3-2015-02-08-20-30-53.txt

**Comment by titanous** [comment]
Closing, this test failure does not appear in the CI logs dating back to May 1st.
