### ISSUE TITLE
tup hangs when rebuilding components in CI

### ISSUE THREAD

**Issue by lmars** [flynn/flynn#949]
Running tup on a VM added via the test cluster API hangs waiting on the FUSE socket after building the components.

The current workaround is to manually kill the FUSE connection after a number of seconds using the FUSE control filesystem (see the `ReleaseSuite.TestReleaseImages` integration test).

**Comment by lmars** [comment]
The sleep approach was not resilient enough, so I am going to update the workaround to use inotify to wait for tup to finish rebuilding components before killing the FUSE connection.

**Comment by titanous** [comment]
Obsoleted by #3817.
