### ISSUE TITLE
ENV secrets filter for upload-debug-info

### ISSUE THREAD

**Issue by diclophis** [flynn/flynn#954]
If we have to share debug info it would be handy to have a reference / option to change how 'secret' `ENV` values are handled.

One thought would be to exclude all non-flynn related `ENV` values in the debug dump.

Or alternatively allow for a convention of a prefix/postfix we could use with our `ENV` keys (e.g. `SECRET_XYZ`

**Comment by diclophis** [comment]
Also related is this: https://github.com/flynn/flynn/issues/401

I would be extremely happy with the option of editing the debug info as needed before I upload to a public source.

**Comment by titanous** [comment]
It seems like we shouldn't include app logs by default either? We can't predict if they will contain secrets.

**Comment by diclophis** [comment]
So as for application logs, by default `rails` tries to obfuscate some things it thinks are secret, but of course doesn't catch everything (and not everyone uses `rails`). I think the best case scenario is a command line flag like `--include-app-env` and `--include-app-log` both defaulting to `false`.

The app logs are kinda nice I imaging for the flynn devs because it can allow for immediate detection of a `app-land` issue vs. `flynn-land`

**Comment by titanous** [comment]
Yeah, I was thinking flags too.

**Comment by diclophis** [comment]
many thanks
