### ISSUE TITLE
router: use CloseNotify to cancel requests when clients disconnect

### ISSUE THREAD

**Issue by bgentry** [flynn/flynn#958]
When a client disconnects, the router should also disconnect from backends (so they can stop doing unnecessary work). This was originally implemented in #926, but unfortunately that had to be put on hold due to incompatibilities in net/http between the `CloseNotifier` and `Hijacker` interfaces. That's documented in https://github.com/golang/go/issues/9763

Once that issue is resolved, it should be possible to alter the router so that it behaves well when clients go away.

**Comment by titanous** [comment]
Partially implemented by #964
