### ISSUE TITLE
Add image backend flag

### ISSUE THREAD

**Issue by chymian** [flynn/flynn#96]
flynn-host installer quits with error on /var/lib/docker being a btrfs formatted partition.
```
flynn-release download /etc/flynn/version.json                       
Downloading flynn/discoverd 933ce2c41a655a1b0d58ce6a621d9783050d0a40200526f1683eb337b87ba7b2...
main.go:52: backing file system is unsupported for this graph driver
2014/08/14 15:59:47 exit status 1
```
reinstallation with a ext4-reformated /var/lib/docker works as suspected.

platform: fresh ubu 14.04
kernel: 3.13.0-34-generic #60-Ubuntu
btrfs-tools                         3.12-1
aufs-tools                          1:3.2+20130722-1.1
flynn-host                          20140814.0~21bf97c0

**Comment by titanous** [comment]
We're moving away from Docker's image handling code, so this issue is moot.
