### ISSUE TITLE
Add instance-store AMIs

### ISSUE THREAD

**Issue by titanous** [flynn/flynn#977]
We should build and publish S3-backed AMIs, allowing EC2 instances to be booted without EBS, which removes a failure mode for running instances. Packer supports this with the `amazon-instance` builder.

**Comment by titanous** [comment]
I have this half-implemented, but ran into issues booting the resulting AMI. Let me know if you'd like to pick it up.

**Comment by lmars** [comment]
Push a branch and I may take a look.

**Comment by titanous** [comment]
https://github.com/flynn/flynn/compare/ec2-ephemeral

This is relevant: https://github.com/Lumida/packer/wiki/Building-Ubuntu-12.04-and-14.04-HVM-Instance-Store-AMIs
