### ISSUE TITLE
router: add Meta field to Route type

### ISSUE THREAD

**Issue by benburkert** [flynn/flynn#984]
Add a `Meta map[string]string` field to `router.Route` and remove the `ParentRef` field. The `Meta` field will be used by clients to associate data with routes for internal tracking. This change can happen after #959 is merged.

**Comment by titanous** [comment]
Flynn is unmaintained and our infrastructure will shut down on June 1, 2021. See [the README](https://github.com/flynn/flynn#flynn-is-unmaintained) for details.
