### ISSUE TITLE
inconsistency in UUID formatting

### ISSUE THREAD

**Issue by bgentry** [flynn/flynn#995]
in #959, @titanous brought up the point that Flynn strips dashes out of UUIDs at the presentation layer:

> In the controller we strip the dashes from UUIDs before they hit the presentation layer. I can't remember the rationale for it, and I'm open to reversing that decision, but that should happen on another ticket.

**Comment by heavenlyhash** [comment]
Relatedly, [flynn/pkg/random.UUID](https://github.com/flynn/flynn/blob/d27a5c1039a2d28a6a49d702a0c36c57d05dfb1f/pkg/random/random.go#L37) produces UUIDs with all the right bits set, but just returns them as a string (and sans dash).  There's no type right now that understands the data with multiple presentations.

**Comment by archSeer** [comment]
I think they were considered "nicer" back when the CLI was written, since postgres happily accepts the format without dashes. Sadly it always returns strings with dashes and cannot be configured otherwise *I think*. Which is why `pkg/postgres` contains CleanUUID and FormatUUID` utility functions.
